runtime/gc_vlhgc/CopyForwardScheme.cpp
runtime/vm/montable.c

String comparator, while mostly used during insertion into the string
table, in the context of mutator threads, it can also be used during
deletion in the context of GC threads when pruning string table.
With moving collectors, before the comparison, string table slot needs
to be fixed up, first. Previous change
(#9330) generalized this access,
so it goes through read barrier API, rather than directly dealing with
lower level GC concepts (Forwarding Pointer).
However, that change neglected the pruning in GC thread scenario, which
would be indirectly inhibited by RB in Balanced GC, since it does not
have active read barrier.
This change is forcing RB fixup during clearable phase of Balanced
CopyFoward.
Testing tip: Comparisons in deletion scenario occurs when String table
uses AVL (over …

Force RB in String Comparator

---

runtime/compiler/control/CompilationThread.cpp

Enable TR_DebugInliner in JitDump for crashed in inliner

---

runtime/compiler/optimizer/J9TransformUtil.cpp
runtime/compiler/optimizer/MethodHandleTransformer.cpp

This PR does the following things:
1. Don't set `doNotProfile` on refined `invokeBasic`/`linkTo*` calls. The transformation doesn't change the operand stack and local state before the call, thus the call can OSR.
2. Don't propagate any local object info to catch block, as the local object info on exception edges is unknown.

Fix two issues in MethodHandleTransformer

---

debugtools/DDR_VM/testsrc/com/ibm/j9ddr/tools/store/test/J9DDRStructureStoreTest.java

That method (which was a no-op) was removed by #12328.

Remove uses of J9DDRStructureStore.close()

---

runtime/vm/BytecodeInterpreter.hpp

In `invokehandle` and `invokedynamic`, the resolution yields an `appendix`
object for OJDK MHs. The `appendix` should only be appended to the stack
if it is not null.

OJDK MHs: Only append a non-null appendix to the stack

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/JitDump.cpp

Release OMRVMThreadName lock in JitDump
Holding on to this lock will prevent the VM from being able to shutdown
properly. This problem can easily be observed via:
```
java -Xdump:jit:events=vmstart -version
```
Suspend diagnostic thread after JitDump
If the user requested a JitDump via an event then the JVM continues
execution normally, however the diagnostic thread remains active. This
is not desirable because the diagnostic thread is looping waiting for
work and can start picking up non-JitDump compilation requests which
will cause an assert.
To prevent this and adhere to the contract outlined in `processEntries`
we suspend the diagnostic thread once the JitDump process is complete.
Fixes: #12336

Fix deadlock and potential assert in JitDump

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/control/J9Options.cpp

Generate `PRFM` instruction after each inlined allocation by JIT.
By default, the address to prefetch is 4 cache lines ahead of allocation pointer.
Options to control prefetch parameter:
- tlhPrefetchLineCount: # of lines to prefetch for each allocation. The default value is 1.
- tlhPrefetchLineSize: cache line size. The default value is 64.
- tlhPrefetchStaggeredLineCount: the distance in line count between alloction pointer
to address prefetched. The default value is 4.
Env vars to control prefetch parameter:
- TR_AArch64PrefetchThresholdSize: `PRFM` is not generated if allocation size
is smaller than this threshold. The default value is 64.
- TR_AArch64PrefetchArrayLineCount: # of lines to prefetch for each array allocation.
The default value is 4.
- TR_AArch64PrefetchType: The type of …

AArch64: Add Allocation Prefetch

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/env/j9methodServer.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.hpp
runtime/compiler/optimizer/MethodHandleTransformer.cpp
runtime/compiler/runtime/JITClientSession.hpp

This commit implements JITServer support for #11634.
- Override new front-end queries for JITServer
- Add a new front-end query
`getMemberNameFieldKnotIndexFromMethodHandleKnotIndex`
to encapsulate a sequence of operations requiring VM access and
override this query for JITServer.

JITServer support for transforming OpenJDK MethodHandles

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp

During `MemberName.init`, its `type` field should not be set to
- `java.lang.reflect.Method.signature` for `methods`; and
- `java.lang.reflect.Constructor.signature` for `constructors`.
The above approach will **incorrectly** set the `type` field for a `MemberName`. 
**Example:** for `MethodHandles.throwException`, `MemberName.type`
will be set to `T:Ljava/lang/Throwable;>(TT;)Lsun/invoke/empty/Empty;^TT;`,
which is an **invalid** `method descriptor`.
The **correct approach** is defined in `MethodHandleNatives.expand` where
`MemberName.type` is derived using `J9ROMMETHOD_SIGNATURE(J9ROMMethod *)`.
Also, `MemberName.type` does not need to be set in the `init` phase for
`methods` and `constructors`. It can be **lazy initialized** when
`MethodHandleNatives.expand` is invoked later, which …

Fix MemberName.type for methods and constructors

---

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/ThreadCommand.java

Missing 64-bit thread flavors for x86 thread and exception state.
FYI: @keithc-ca @dusanboskovic

Add missing thread flavor cases to mach-o dump reader

---

runtime/compiler/runtime/SignalHandler.c

`getenv` requires `stdlib.h` to be included.

Fix x86 macOS compilation error in SignalHandler.c

---

buildenv/jenkins/variables/defaults.yml

This value is used for build logs as well as Artifactory binaries

Increase nightly build history to 40

---

runtime/vm/lookupmethod.c

Remove the extra module in error msgs
Currently we output messages with "because module module com.test does
not read module module hamcrest.core". We insert the pre-pending
"module" when printing out module names in `getModuleNameUTF`.
Fixes #12315

Remove the extra module in error msgs

---

runtime/bcutil/ROMClassCreationContext.hpp

To identify a valid `InjectedInvoker` class, check if
- `className` has `InjectedInvoker/0x0000000000000000`; and
- `_className` has `$$InjectedInvoker` at the end.
These changes are only enabled for OJDK MHs.
Fixes: https://github.com/eclipse/openj9/issues/11926

Handle InjectedInvoker class name mismatch during ROM class creation

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ShrCCommand.java

Catch NoSuchFieldError when running on an old core where SH_CacheMap
does not have field _ccTail. Fall back to code before #6883 i.e. use
cacheMap._cc() to set compositeCacheImpl in this case.
Fixes #12357

Fix NoSuchFieldError in SCC DDR command

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ShrCCommand.java

Catch NoSuchFieldError and NoSuchMethodError when running on an old core
where SH_CacheMap does not have field _ccTail. Fall back to code before
#6883 i.e. use cacheMap._cc() to set compositeCacheImpl in this case.
Fixes #12357

(v0.26.0)Fix NoSuchFieldError in SCC DDR command

---

runtime/compiler/net/ClientStream.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/ServerStream.hpp

Noticed as part of the discussion in AdoptOpenJDK/openjdk-build#2550.

Remove redundant includes of openssl header files

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Fix `wrtbarEvaluator` to call srm->stopUsingRegister().

AArch64: Fix wrtbarEvaluator to kill scratch registers

---

jcl/src/java.base/share/classes/java/lang/System.java
jcl/src/java.base/share/classes/java/lang/Thread.java
test/functional/cmdLineTests/cmdLineTest_J9tests/j9tests_console.xml
test/functional/cmdLineTests/cmdLineTest_J9tests/playlist.xml
test/functional/cmdLineTests/cmdLineTest_J9tests/src/GetConsoleCharset.java

Also support setting extended Charset's in the jdk.charsets module.
See https://github.com/eclipse/openj9/pull/11387

Add support for sun.stderr.encoding and sun.stdout.encoding

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/OptInfo.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/gc/GCSegmentIterator.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/AbstractPointer.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/ValueTypeHelper.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/types/Scalar.java

The two implementations of `allBitsIn()` have been updated to return `false` when the argument is zero. The one caller that relied on the old behavior of `allBitsIn(0)` has been updated. Other redundant checks at call sites have been removed.
See https://github.com/eclipse/openj9/issues/12312#issuecomment-809752178.

Fix uses of flags which were not always defined

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/J9ObjectFieldOffsetIterator_V1.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/ObjectFieldInfo.java
runtime/vm/ObjectFieldInfo.hpp
runtime/vm/resolvefield.cpp
test/functional/Valhalla/playlist.xml

1. If using an object reference field as backfill, its type should be
Ltype or non-flattened Qtype. So add checks for Qtype and 
J9ClassIsFlattened before using object reference as backfill.
2. From the backfill priority list, instance singles, flat
end-aligned/unaligned singles singles are different.
isBackfillSuitableInstanceSingleAvailable() should not include flat
singles.

Fix object layout if a flattening threshold is set

---

runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/optimizer/TreeLowering.cpp

This pull request addresses comments on `TreeLowering::lowerArrayStoreCHK` that arose in the review of pull request #11968.  In particular:
- Corrected `lowerArrayStoreCHK` comments to indicate that only `awrtbari` is expected to be a child of an `ArrayStoreCHK`, and added a fatal assertion to confirm that.
- Moved generation of IL that examines the flags field of a class into `TR_J9VMBase` to isolate optimizer from detailed knowledge of J9.
- Removed a redundant call to `copyByteCodeInfo`.

Clean up tree lowering for ArrayStoreCHK

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Fix compiler warning of helper function for genHeapAlloc.

AArch64: Fix compiler warning of helper function for genHeapAlloc

---

test/functional/cmdLineTests/xcheckjni/xcheckjni.xml

Various sub tests are intermittently timing out on z/OS, which seems due
to infra issues. Increase the timeout in an attempt to reduce the
occurrences.

Increase cmdLineTester_XcheckJNI timeout

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/OptInfo.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/gc/GCSegmentIterator.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/AbstractPointer.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/ValueTypeHelper.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/types/Scalar.java

This is a cherry-pick of #12329 (after resolving the conflict in `AbstractPointer.java`).
Fixes https://github.com/eclipse/openj9/issues/12312

(0.26.0) Fix uses of flags which were not always defined

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

`evaluateNULLCHKWithPossibleResolve` does pattern matching to
find load operation in compressed references sequences, but it searches for
`TR::i2l` instead of correct opcode `TR::iu2l`.
Also, if it is a load operation and the reference count of the load node
under the compressed refs sequence is 1, explicit NULLCHK is used
even if the reference count of `TR::l2a` node is more than 2.
This commit changes `evaluateNULLCHKWithPossibleResolve` to
- Use opcode value of the parent of the reference node for judging
whether it is a load operation instead of searching `TR::iu2l`.
- Use implicit NULLCHK if `TR::l2a` node's reference count > 2.

AArch64: Properly find compressed refs sequence in implicit NULLCHK

---

test/functional/DDR_Test/tck_ddrext.xml
test/functional/HealthCenter/healthcenter.xml

Use `antlib.xml` like all other ant scripts, as advised at http://ant-contrib.sourceforge.net/tasks/index.html.

Import antcontrib tasks consistently

---

runtime/compiler/build/files/common.mk
runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/PersistentCollections.hpp
runtime/compiler/runtime/CMakeLists.txt
runtime/compiler/runtime/JITClientSession.hpp
runtime/compiler/runtime/JITServerAOTCache.cpp
runtime/compiler/runtime/JITServerAOTCache.hpp
runtime/compiler/runtime/JITServerAOTSerializationRecords.hpp
runtime/compiler/runtime/JITServerSharedROMClassCache.cpp
runtime/compiler/runtime/JITServerSharedROMClassCache.hpp

This PR defines AOT serialization records and serialized AOT method format, and adds the infrastructure needed to store and lookup serialized AOT methods in the JITServer AOT cache. See #12153 for a high-level description of the design.
`JITServerAOTCacheRecords.hpp` contains the definitions of data structures that will be used by both the server and the client, including serialized AOT methods and AOT serialization records. `JITServerAOTCache.hpp` defines the data structures used only on the server side. `JITServerAOTCache` is the main class that implements creation, storage and lookup of serialization records (which will be performed during AOT compilations) and caching of serialized AOT methods. While the current implementation only supports "private" in-memory storage (using the …

JITServer AOT cache storage infrastructure

---

runtime/compiler/runtime/codertinit.cpp

We disabled JIT helpers and hooks because we thought
they are not used on JITServer. However, JIT helpers
are needed to produce crash diagnostic info, and without
them, we crash inside a signal handler.
This commit re-enables helpers so the diagnostic facilities
are now functional.
Closes: #12374

Re-enable JIT helpers on JITServer

---

runtime/compiler/optimizer/TreeLowering.cpp
runtime/compiler/optimizer/TreeLowering.hpp

This PR introduces additional fastpaths for acmp by inlining some of the checks performed by the VM helper. The fastpaths are added in the treeLowering optimizations. A few helper functions are also introduced to make the code more readable.

Add more acmp fastpath in the JIT and move the helper call out of line

---

runtime/compiler/control/JitDump.cpp

There is a small timing hole which I haven't observed yet but it is
possible that in the time between resuming the diagnostic thread and
purging the method queue we might pick up an OrdinaryMethod compile
on the diagnostic thread.
The fix here is to simply purge the queue and then enable the
diagnostic thread.

Fix JitDump timing hole when resuming diagnostic thread

---

buildenv/jenkins/common/pipeline-functions.groovy

The usefulness of setting UNSTABLE is likely unessary and
it is currently causing an issue on internal builds trying
to update external repos.
Setting to SUCCESS will have no effect as Jenkins will always
retain the worst status.

Don't set build unstable if commit status setter fails

---

runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp
runtime/gc_vlhgc/CopyForwardScheme.cpp

Disable Dynamic Breadth-First Scan Ordering by default
for the Balanced GC policy in the OpenJ9 master branch and the upcoming release 0.26 branch in light of a newly raised issue (https://github.com/eclipse/openj9/issues/12346). Revert back to Dynamic Breadth-First Scan Ordering by default after the issue is resolved. 

Disable Dynamic Breadth First for Balanced

---

buildenv/jenkins/common/build.groovy
buildenv/jenkins/common/variables-functions.groovy

Fixes #11486
Also
Check SPEC rather than NODE_LABELS.
SPEC is more reliable. Node labels can
change, especially when debugging on
specific machines
CleanWs after bootjdk download

CleanWs after bootjdk download

---

runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp
runtime/gc_vlhgc/CopyForwardScheme.cpp

Disable Dynamic Breadth-First Scan Ordering by default for the Balanced GC policy in the OpenJ9 master branch and the upcoming release 0.26 branch in light of a newly raised issue (https://github.com/eclipse/openj9/issues/12346). Revert back to Dynamic Breadth-First Scan Ordering by default after the issue is resolved. 
Port of https://github.com/eclipse/openj9/pull/12369 for th 0.26 release.

(0.26.0) Disable Dynamic Breadth First for Balanced GC

---

runtime/compiler/ilgen/Walker.cpp

This makes some simple changes to IL generation for array element access with value types enabled:
- Disable generation of calls to `jit{Load|Store}FlattenableArrayElement` helpers if arraylets are supported, as garbage collection policies that use arraylets do not yet work with flattenable array elements.  That will avoid having optimizations that operate on such calls having to worry about handling arraylets.
- Added debug counters to track calls to the array element helpers in order to track calls to them as well as allowing subsequent optimizations that might be able to eliminate such calls to track such elimination.

Groundwork changes for some expected performance improvements with value types enabled

---

runtime/compiler/runtime/Runtime.cpp

Remove remaining J9PPCArrayCmp references as it was
previously removed due to being dummied out.

Cleanup J9PPCArrayCmp remnants

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp

Fixes: https://github.com/eclipse/openj9/issues/12404
Co-authored-by: Dan Heidinga <heidinga@redhat.com>

Add object header size to correctly locate the CallSite.target field

---

doc/release-notes/0.26/0.26.md

- Remove change to default scan behavior for the Balanced GC policy
- Add deprecation statement for jextract
[ci skip]

Update release notes for 0.26

---

jcl/src/java.base/share/classes/java/lang/System.java
jcl/src/java.base/share/classes/java/lang/Thread.java

- Take console.encoding into account for System.out and err on z/OS
- Remove trailing whitespace from System and Thread.java 
- Add a createConsole() helper to init System.err and out

Updates for setting System.err and out, fix z/OS and streamline code

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/control/JITServerHelpers.hpp

JITServerHelpers::cacheRemoteROMClass attempts to store a newly allocated
remote ROM class into the cache. However, if after the class has been
requested but before it was cached, it was cached by another thread,
the new class will not be cached, resulting in a memory leak.
This commit fixes the problem by checking whether
`JITServerHelpers::cacheRemoteROMClass`
has actually cached the class and freeing the memory if it hasn't.
Closes: #12180

Fix a memory leak when caching remote ROM classes

---

jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java

Port of #12371 to 0.26 release.

(0.26.0) Update accessCheckArgRetTypes to always check array component type

---

runtime/compiler/env/VMJ9.cpp

Replaces the call to getCPIndex with a call to getCPIndexForVM inside
reserveTrampolineIfNecessary. This is done to get the non-sign extended
version of the cpIndex. This is required to generate the key when adding the
unresolved method to the _unresolvedMethodHT hashtable in a code cache.
Issue: #12120

Use getCPIndexForVM inside trampoline code

---

runtime/compiler/optimizer/HotFieldMarking.cpp

FIx potential hot field slot offset overflow that could occur in the event there is a hot field offset calculated that is greater than the size of the field used to store the offset. This will most likely resolve https://github.com/eclipse/openj9/issues/12346, however, customer proof will be obtained after this change is merged. 

Fix Potential Hot Field Slot Offset Overflow

---

test/functional/JLM_Tests/src/org/openj9/test/management/TestOperatingSystemMXBean.java

Part of tests testOSMXBeanLocal and testOSMXBeanRemote, which run
org.openj9.test.management.TestOperatingSystemMXBean.runTestOSMXBean()
Issue https://github.com/eclipse/openj9/issues/12038

Exclude OperatingSystemMXBean PhysicalMemory test in Docker

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
runtime/jcl/j9jcl.tdf
runtime/oti/jclprots.h

- change J9JNI-NAS to J9NAS to use J9_LOOK_DIRECT_NAS and J9_LOOK_CLCONSTRAINTS
- Add CL constraint check to field resolution
Fixes: #11925, Fixes: #11928, Fixes: #11964 
Co-authored-by: Babneet Singh <sbabneet@ca.ibm.com>

Support lookupMode argument in Java16+ & add CL constraint check

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/J9ObjectFieldOffsetIterator_V1.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/ObjectFieldInfo.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/PrintObjectFieldsHelper.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/ValueTypeHelper.java
runtime/oti/j9.h
runtime/vm/ObjectFieldInfo.cpp
runtime/vm/ValueTypeHelpers.cpp
runtime/vm/ValueTypeHelpers.hpp
runtime/vm/createramclass.cpp
runtime/vm/description.c
runtime/vm/resolvefield.cpp
runtime/vm/resolvesupport.cpp
test/functional/Valhalla/src/org/openj9/test/lworld/DDRValueTypeTest.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeGenerator.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java
test/functional/cmdLineTests/valuetypeddrtests/flattenedvaluetypeddrtests.xml

1. Disable flattening of volatile field that is > 8 bytes for now, as
the current implementation of copyObjectFields() will tear this field.
2. Add test.
issue #11178

Do not flatten volatile field that is > 8 bytes

---

runtime/gc_glue_java/ScavengerDelegate.cpp
runtime/gc_glue_java/ScavengerDelegate.hpp

Not used anymore. It was not a reliable way to determining if we could
yield due to a pending Exclusive Access Request, since when external
threads would request it they would set the state directly to
J9_XACCESS_EXCLUSIVE, skipping over J9_XACCESS_PENDING.

Remove Scavenger shouldYeild()

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/env/PersistentAllocator.cpp
runtime/compiler/env/PersistentAllocator.hpp
runtime/compiler/infra/J9Monitor.cpp
runtime/compiler/infra/J9MonitorTable.cpp
runtime/compiler/infra/J9MonitorTable.hpp
runtime/compiler/ras/DebugExt.cpp

Even though JITServer uses per-client persistent allocator instances, they all use the same global `memoryAllocMonitor` to synchronize access to their lists of large variable-sized free blocks and deques of currently used segments. This global monitor can limit scalability when JITServer is used by a large number of concurrent clients.
This PR modifies the persistent allocator implementation to use separate monitors to protect access to each data structure:
- the lists of small fixed-size blocks;
- the (indexed) list of variable-sized large blocks; and
- the deque of segments.
It also removes all other references to the now unused global `memoryAllocMonitor`, which is defined in OMR and can be removed from there after this PR is merged.

Optimize locking in persistent allocator

---

runtime/compiler/runtime/JITClientSession.cpp

This PR fixes the following issues in `ClientSessionData::clearCaches()`:
- Clear the `_constantPoolToClassMap` cache that contains RAMClass and RAM constant pool pointers;
- Remove unnecessary (and incorrect anyway) synchronization and assert assumptions that make it unnecessary.

Fix clearing JITServer client session caches

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp

PR #12180 introduced a bug: when we try to cache a newly
received ROM class but find that it's already been cached,
we deallocate it but still return the pointer to the ROM class
that now contains invalid memory.
The fix is to update the class pointer with the cached value
and return that.
Closes: #12468, #12442

Fix invalid memory access when getting a ROM class

---

runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp

When per-client persistent allocators are enabled, each client session and all its persistent objects are allocated with its own allocator instance. All persistent memory used by the session is automatically freed when its allocator instance is destroyed. This PR modifies `ClientSessionData::destroy()` to skip the unnecessary destructor calls.

Optimize JITServer client session destruction when using AOT cache

---

runtime/CMakeLists.txt

Functionality seems to no longer be required. However, code left in place
should we need to re-enable it in the future.

CMake: disable add_custom_ascii_command

---

runtime/oti/j9cfg_builder.h
runtime/vm/callin.cpp

We are now preserving vector registers on PPC64between JIT runtime helper
calls. This is believed to be the cause of StackOverflowError failures seen on
PPC64. This PR increases the default stack size on PPC64 from 256kb to
512kb. This PR also introduces a stack guard to protect from overflows
between call-in frames.

Increase OS stackspace on PPC64

---

runtime/compiler/optimizer/J9Simplifier.cpp
runtime/compiler/optimizer/J9Simplifier.hpp

During IL generation with value type support enabled, the JIT generates calls to an equality comparison non-helper to compare objects, as simple address comparisons are not sufficient for comparison of value type instances in general.  Certain object equality comparisons can be simplified by decaying the non-helper call into an ordinary `acmpeq` node.
These cases are:
- if either argument to the compare is a null reference
- if the same node appears as both operands of the compare
Further possible simplifications are done by recursively simplifying the `acmpeq` node, if transformed.

Optimize object equality comparisons in Simplifier if value types support is enabled

---

runtime/compiler/optimizer/TreeLowering.cpp

When getting exit `GlRegDeps`, it should call `getExit` instead of
`getEntry`.

Fix getEntry in fastpathAcmpHelper

---

runtime/compiler/z/codegen/J9TreeEvaluator.cpp

The Z ArrayStoreCHKEvaluator was using a 32bit compare of a decompressed
object reference with NULL when fast-pathing the write barrier. This
meant that when an object reference had all 0 bits in the lower 32bits
it would skip the write barrier and fail to mark the tenured object as
having a nursery reference. The end result is a possible early free of
nursery objects with the address 0x100000000 or 0x200000000 for example.

Fix Z ArrayStoreCHKEvaluator to use a 64bit compare for compressedrefs

---

test/functional/cmdLineTests/gcRegressionTests/gcRegressionTests.xml

Increase the heap size to avoid occasional OOMs.
Fixes https://github.com/eclipse/openj9/issues/12527

Use -Xmx8m instead of -Xmx4m for gc regression testing

---

runtime/compiler/aarch64/env/J9CPU.cpp
runtime/compiler/aarch64/env/J9CPU.hpp
runtime/compiler/env/J9CompilerEnv.cpp
runtime/compiler/env/ProcessorDetection.cpp

Implement new CPU APIs on aarch64 as other platforms.
Depends on:
https://github.com/eclipse/omr/pull/5932
https://github.com/eclipse/omr/pull/5934
See OpenJ9 #10594.

AArch64: Replace CPU APIs

---

runtime/compiler/CMakeLists.txt

This PR makes the following changes:
- Allow passing extra compiler flags to the JIT CMake build via `OMR_PLATFORM_C_COMPILE_OPTIONS` and `OMR_PLATFORM_CXX_COMPILE_OPTIONS` by changing the order in which compiler flags are appended in the JIT's `CMakeLists.txt`. This change makes the behaviour consistent with the rest of the VM.
- Add CMake options `J9JIT_EXTRA_CFLAGS` and `J9JIT_EXTRA_CXXFLAGS` that can be used to pass extra compiler flags that are only used when building the JIT. This is useful e.g. when one wants to define the `DEBUG` flag only for the JIT.
With these changes it becomes easier to produce a debug build, without having to hack the makefiles as described in https://blog.openj9.org/2020/11/19/setting-up-an-openj9-development-environment-with-visual-studio-code-docker-cmake/ …

JIT CMake build improvements to enable debug build

---

runtime/ddr/j9portddrstructs.properties

Make types `J9HeapWrapper` and `J9SubAllocateHeapMem32` available to DDR in IBM builds.

Include types from omrmem32struct.h in legacy DDR

---

runtime/compiler/env/VMJ9Server.cpp

This PR fixes the issue that was first described but not fully fixed in https://github.com/eclipse/omr/issues/5837 and https://github.com/eclipse/omr/pull/5839.
In some rare circumstances, `TR_J9ServerVM::getClassLoader()` ends up being called by the optimizer through `OMR::SymbolReferenceTable::findOrCreateClassSymbol()` at the JITServer. The current implementation of `TR_J9ServerVM::getClassLoader()` erroneously assumes that it can never be called on the server side, and returns `NULL` after a non-fatal assertion. This PR fixes this issue by providing the correct implementation.

Fix TR_J9ServerVM::getClassLoader()

---

runtime/compiler/CMakeLists.txt
runtime/compiler/aarch64/env/J9CPU.cpp
runtime/compiler/aarch64/env/J9CPU.hpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/env/J9CompilerEnv.cpp
runtime/compiler/env/ProcessorDetection.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/optimizer/StaticFinalFieldFolding.hpp
runtime/gc_trace/TgcCardCleaning.cpp
runtime/gc_trace/TgcParallel.cpp
runtime/gc_trace/TgcRootScanner.cpp
runtime/gc_verbose_old_events/VerboseEventAFStart.cpp
runtime/oti/j9port_generated.h
runtime/rasdump/javadump.cpp
runtime/rasdump/trigger.c
runtime/shared_common/CacheLifecycleManager.cpp
runtime/tests/port/j9strTest.c
runtime/vm/BytecodeInterpreter.hpp
test/functional/cmdLineTests/gcRegressionTests/gcRegressionTests.xml

Issue: #12397.
Depends on eclipse/omr#5945.
The first and third of the following lines are new:
```
1TIDATETIMEUTC Date: 2021/04/14 at 18:51:14:126 (UTC)
1TIDATETIME    Date: 2021/04/14 at 14:51:14:126
1TITIMEZONE    Timezone: UTC-4 (EDT)
```

Include UTC date/time and timezone in javacore files

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/MethodHandleTransformer.cpp
runtime/compiler/optimizer/MethodHandleTransformer.hpp

This changeset includes the following: 
* recognize `java/lang/invoke/Invokers` methods that require handling in RecognizedCallTransformer
* Transform `Invokers.checkExactType` to a ZEROCHK
* Eliminate `Invokers.checkCustomized` calls when MethodHandle is a known object
Issue: #10618

Recognize and transform redundant calls in MH.invokeExact MethodHandle chain

---

runtime/CMakeLists.txt

Specify directories which are excluded when searching for debug info.
This is the same as DDR_EXCLUDED_FOLDERS from ddr/run_omrddrgen.mk.ftl.
There are some minor differences due to differences between the uma and
cmake builds.
- all of omr/ is excluded as in CMake, omr is responsible for searching
for its own object files
- compiler/ is excluded as CMake builds generate debug info when building
the compiler, where as UMA builds do not.

CMake: Specify exclude directories for DDR

---

runtime/cmake/platform/os/zos.cmake

Update shared library naming to take the form 'lib<LIB_NAME>.so'
instead of '<LIB_NAME>.dll'.

CMake update shared library naming on zos

---

jcl/src/java.base/share/classes/java/lang/Access.java
jcl/src/java.base/share/classes/java/lang/String.java
jcl/src/java.base/share/classes/java/lang/System.java
runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/il/J9MethodSymbol.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/UnsafeFastPath.cpp
runtime/gc_base/StringTable.cpp
runtime/oti/VMHelpers.hpp

Not include OpenJ9 `java.lang.String` for `JDK17`;
Update `JDK17` `StringCoding` references which have been moved into `String`;
Support `ISO-8859-1`/`Latin-1` characters between `0x80` and `0xFF` in String compression mode which is required by RI `String`.
~depends https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/295~ - **merged**
unlock https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/296 https://github.com/eclipse/openj9/pull/12547
fixes https://github.com/eclipse/openj9/issues/12398

JDK17 adopts RI java.lang.String

---

runtime/compiler/control/rossa.cpp

Setup the VM USE_VECTOR_REGISTERS flag on supported POWER systems for VectorAPI POWER linkage work.

Set VM USE_VECTOR_REGISTERS flag for supported POWER systems

---

runtime/compiler/z/codegen/J9TreeEvaluator.cpp
test/functional/JIT_Test/playlist.xml

The multiANewArrayEvaluator in the z/codegen generates an `AGHIK` instruction. This instruction is not supported on Z10
and lower platforms. This commit adds a check in the evaluator to make sure that the current architecture supports the instruction before generating it.
Tests for the evaluator have also been improved to account for all supported architectures.
Fixes: #12538

Check for arch support when generating AGHIK instruction in Z's multiANewArrayEvaluator

---

jcl/jpp_configuration.xml

Required due to adoption of reference implementation of String by #12209.

Update classpath for JAVA17

---

runtime/gc_glue_java/ScavengerDelegate.cpp

In Concurrent Scavenger, when close to terminating concurrent phase and
signaling mutator threads to flush their copy caches, prior to thread
iteration thread lock is acquired. However, it's taken after the
iterator construction, which itself advances the iteration to main VM
thread. The main thread may race and terminate before we acquire the
lock and start iteration.
The solution is to construct the iterator after acquiring the lock.

Thread iterator inside thread list lock

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Call overridden implementation of `inlineDirectCall` method
as inlining of atomic method symbols is implemented in OMR class.
Depends on https://github.com/eclipse/omr/pull/5950

AArch64: Inline direct call for atomic method symbols

---

runtime/compiler/CMakeLists.txt

CMake: Ensure that jit symbols are exported on z/OS

---

jcl/src/java.base/share/classes/java/lang/Access.java

Invoke `String` package private method `join(prefix, suffix, delimiter,elements, size)`.
depends on https://github.com/eclipse/openj9/pull/12209
With this PR and https://github.com/eclipse/openj9/pull/12209, `java -version` output is:
```
OpenJDK Runtime Environment (build 17-internal+0-adhoc.fengjcaibmcom.openj9-openjdk-jdk)
Eclipse OpenJ9 VM (build jdk17ristr-jlajoin-c2d8cf4dd9, JRE 17 Mac OS X amd64-64-Bit Compressed References 20210423_000000 (JIT enabled, AOT enabled)
OpenJ9   - c2d8cf4dd9
OMR      - 22a4853ac
JCL      - bcdde3be245 based on jdk-17+19)
```
fixes https://github.com/eclipse/openj9/issues/12545

Add JavaLangAccess.join(prefix, suffix, delimiter, elements, size)

---

runtime/tests/redirector/genericlauncher/genlauncher.c

The buffer for the -cp argument is allocated 1 byte too small. When
using glaunch to run testing, this can result in ClassNotFoundException.
Fixes internal infra issue 5428.

Fix buffer overflow in glaunch test utility

---

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
jcl/src/java.management/share/classes/java/lang/management/MemoryNotificationInfo.java

Constructor of MemoryNotificationInfo is missing null checks. Adding to maintain consistency with HotSpot. Updated JavaDoc to reflect the change.
Closes #12552

Add null check in constructor of MemoryNotificationInfo

---

buildspecs/j9.flags
buildspecs/zos_390-64.spec
buildspecs/zos_390-64_cmprssptrs.spec
runtime/buildtools.mk
runtime/include/jni.h.m4
runtime/include31/module.xml
runtime/j9vm31/j9cel4ro64.c
runtime/j9vm31/j9cel4ro64.h
runtime/j9vm31/j9vm31.h
runtime/j9vm31/j9vm31floatstubs.s
runtime/j9vm31/j9vm31natives.xml
runtime/j9vm31/jnicgen.cpp
runtime/j9vm31/jnicsup.cpp
runtime/j9vm31/jnifield.cpp
runtime/j9vm31/jniinv.cpp
runtime/j9vm31/jnimisc.cpp
runtime/j9vm31/jnireflect.cpp
runtime/j9vm31/module.xml
runtime/makelib/targets.mk.zos.inc.ftl

This PR adds two new modules:
1. An `include31` modules that produces copies jni.h, jni_convert.h and jniport.h.  For jni.h, the m4 has been updated to remap any object reference types, jclass, jfieldID, jmethodID to be 64-bit... as we want to use the 64-bit handles directly passed by the JVM.   
2. A `j9vm31` 31-bit standalone shim library to support the JavaInvokeInterface and JavaNativeInterface APIs that allow
z/OS 31-bit non-XPLINK native code to interoperate with 64-bit JVM on z/OS.
Changes include:
- the CEL4RO64 utility functions to facilitate AMODE64 calls.  Specifically, getting the call arguments into the correct 64-bit representation, and extracting the appropriate return types.  One thing to note is that float/double parameters and return value handling currently invokes …

31-bit shim library for z/OS

---

runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/ilgen/Walker.cpp
runtime/compiler/optimizer/TreeLowering.cpp
runtime/compiler/optimizer/TreeLowering.hpp

Currently when value type is enabled, ILGen generates helper calls
`jitLoadFlattenableArrayElement` and `jitStoreFlattenableArrayElement`
for both VT and non-VT aaload and aastore. This approach causes
performance regression. This change introduces inline checks in
tree lowering.
Non-VT aaload and aastore blocks are added as an extended block of
the original block that contains the helper call. The helper call is
split into its own block and moved to the end of the tree list.
Runtime check on the array component class is inserted before aaload
and aastore operations. If it's value type, the control flow jumps
to the out of line helper call block. If not, the control falls
through to the non-VT aaload and aastore blocks.
Resolves #12174

Add inline check to aaload and aastore in treeLowering

---

runtime/j9vm/jvm.c

Using J9PRIz doesn't produce any output from the fprintf() on z/OS. Fix
another fprintf(), used only when there is error condition, in the same
file as well.
Before this change -verbose:init shows
```
Adding command line arguments
VM known paths	- j9libvm directory: /j9vm/ebcdic/builds/bld_4316/peter/mz3180/jre/lib/s390/default
- j2seRoot directory: /j9vm/ebcdic/builds/bld_4316/peter/mz3180/jre/lib/s390/default
Initializing DLL load table:
```
and after
```
Adding command line arguments
VM known paths	- j9libvm directory: /j9vm/ebcdic/builds/bld_4316/peter/mz3180/jre/lib/s390/default
- j2seRoot directory: /j9vm/ebcdic/builds/bld_4316/peter/mz3180/jre/lib/s390/default
Option 0 optionString="-Xoptionsfile=/j9vm/ebcdic/builds/bld_4316/peter/mz3180/jre/lib/s390/default/options.default" …
```

Use OMR_PRIuPTR to print VM options for -verbose:init

---

runtime/gc_structs/MixedObjectIterator.hpp
runtime/gc_structs/PointerArrayIterator.hpp
runtime/gc_structs/PointerContiguousArrayIterator.hpp

Fix warning treated as error by initialization of all
GC_PointerContiguousArrayIterator class fields in constructor
#fixes https://github.com/eclipse/openj9/issues/12568

Initialize class fields in constructor

---

runtime/compiler/compile/J9NonHelperSymbols.enum
runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/compile/J9SymbolReferenceTable.hpp
runtime/compiler/compile/NonHelperSymbols.enum

* Relocate OpenJ9-specific SymbolReference functions to OpenJ9
* Make NonHelperSymbols enum extensible

Preparations to support extensible non helper SymbolReferenceTable enum

---

runtime/gc_structs/MixedObjectIterator.hpp
runtime/gc_structs/PointerArrayIterator.hpp
runtime/gc_structs/PointerContiguousArrayIterator.hpp

There was an attempt to minimize code by calling another constructor.
While there is no problem for C++ compiler itself ddrblob compilation
failed

Fix ddrblob compilation for object iterators

---

runtime/compiler/arm/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/S390PrivateLinkage.cpp

This option is inconsistently used throughout the codebase. It was
originally introduced when OOL code sequences were first implemented as
a fallback path due to register allocation issues.
We have been using OOL seuqneces for almost a decade now and in some
places we don't even have a guard or fallback path against using OOL,
so enabling this option is not safe. Because of these reasons it is
best to just remove it.

Deprecate TR_DisableOOL option

---

runtime/compiler/runtime/SymbolValidationManager.cpp

Using `TR_J9SharedCache::offsetInSharedCacheFromPointer()` in `TR::SymbolValidationManager::populateWellKnownClasses()` to convert class chain pointers returned by rememberClass() to SCC offsets can trigger a fatal assertion due to the following race condition. When Thread 1 stores a class chain, Thread 2 can look it up before Thread 1 updates the SCC area bounds in the SCC header, and converting the pointer to offset in Thread 2 fails with a fatal assertion. See discussion in #12405.
This PR is a workaround to avoid the fatal assertion by calling `TR_J9SharedCache::isPointerInSharedCache()` which checks if the pointer is in the SCC according to the current area bounds without a fatal assertion, and failing the compilation if this call does not succeed.

Avoid potential crash when converting pointers to SCC offsets

---

jcl/src/java.base/share/classes/java/lang/Class.java
jcl/src/java.base/share/classes/java/lang/invoke/MethodTypeHelper.java
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9method.h
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java

Change Class.java descriptorString() method to return Qtype descriptor
for primitive classes and Ltype descriptor for non primitive ref types
Change getBytecodeStringName in MethodTypeHelper.java to
return Qtype descriptor for primitive classes and Ltype
descriptor for non-primitive ref types.
Added tests in ValueTypeTests to check correctness of descriptors
- testMethodTypeDescriptorRef
- testMethodTypeDescriptorValue
Changed runFEMacro in j9method.cpp and nextSignatureArgument in j9method.h
to correctly handle  Q-types and the new methodDescriptors.
Signed-off-by: Oussama Saoudi <oussama.saoudi@ibm.com>

Modify Class and Method Descriptors to be compatible with Q types

---

doc/compiler/jitserver/Problem.md
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/env/J9PersistentInfo.hpp

Passing `TR_RequireJITServer` environment variable on the client
will cause the JVM to exit with error, if it ever detects a
stream failure. This can be used for debugging purposes,
to ensure that a test fails if the server crashes, instead
of continuing compiling locally.
However, in real-life scenarios there are many false positives,
because if a client stream stops sending compilations for a time
and the stream times out (default timeout is 2 seconds),
we will detect a stream failure and terminate the JVM
even though the server is still running.
This commit replaces `TR_RequireJITServer` with a command line
option `-XX:+RequireJITServer` so that it can be more
easily passed to testing infrastructure and increases the default
timeout to 1 minute if the option is provided, while still …

Replace TR_RequireJITServer with a command line option

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp

For 64-Bit platforms running with compressedrefs while lowering trees for compression sequence, we optimize compression of constant NULL object by recreating it as iconst 0. Codegenerators need actual decompressed reference for wrtbar and by lowering the aconst to iconst, we lose that information. Most of the codegen makes an assumption that the compression sequence for storing a reference would be lowered and when it needs actual decompressed object reference, it traverses the compressed child till it finds actual reference and rest of the code would be generated with the assumption that it has decompressed object reference which would take full 64 bit register. In case of constant NULL reference, it would end up iconst node which would be evaluated into the lower half of the register on …

Do not lower decompressed NULL reference to iconst before storing compressed reference

---

runtime/compiler/optimizer/TreeLowering.cpp
runtime/compiler/optimizer/TreeLowering.hpp

This PR contains Leo's implementation of delayed transformation in tree lowering. It is based on building a queue of callbacks and arguments (technically closures) that define what transformations to perform. The treeLowering optimization will then consist of a pass that  finds the trees to be lowered and records them in the queue followed by a pass (of the queue) that actually does the lowering transformations.
The original transformation methods from `TreeLowering` become a class that subclasses from `Transformer` and overrides `Transformer::lower()`. 
```
TreeLowering::fastpathAcmpHelper => class AcmpTransformer: public TR::TreeLowering::Transformer
TreeLowering::lowerArrayStoreCHK => class ArrayStoreCHKTransformer: public TR::TreeLowering::Transformer …
```

Delayed transformation tree lowering

---

runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/j9method.h

This PR fixes the following bugs:
- The standard `strtok()` function is not thread-safe, so it can't be used in the compiler.
- It is possible (whether or not it should be possible) for a class to have parentheses in its name, and therefore it is also possible for a method signature that names such a class to contain parentheses other than the pair that surround the list of parameter types. This makes even the reentrant variant `strtok_r()` unsuitable for splitting up the original method signature.
- The UTF-8 data in `romMethodSignature` is not necessarily NUL-terminated like `strcpy()` requires.
- Additionally, it seems that the out-parameter `signatureLength` is not supposed to include a NUL terminator in the count.
Instead of using `strtok()`, the input signature is now parsed using …

Fix getSignatureForLinkToStaticFor*()

---

runtime/bcutil/cfreader.c
runtime/bcutil/j9bcu.tdf
test/functional/Java9andUp/src/org/openj9/test/defineModuleAsClass/DefineModuleAsClassTest.java

The change is to change the error action for ACC_MODULE (0x8000)
from ClassFormatError to NoClassDefFoundError so as to match
the RI's behaviour when loading a class with ACC_MODULE set
in the class file.

Update the error action for ACC_MODULE

---

runtime/gc_verbose_handler_vlhgc/VerboseHandlerOutputVLHGC.hpp
runtime/gc_vlhgc/IncrementalGenerationalGC.cpp

This is follow up PR for https://github.com/eclipse/omr/pull/5781
Adapt `MM_VerboseHandlerOutputVLHGC::getConcurrentTypeString` to interface of parent class.
Signed-off-by: Enson Guo <enson.guo@ibm.com>

Adding `concurrent-start/end` for Concurrent Global/Marking

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp

Since the scratch space limit at JITServer is 512 MB, a few expensive
compilations that come more or less concurrently can easily exhaust
the entire available memory.
This commit adjusts the scratch space limit at JITServer dynamically
so that a compilation cannot use more than half the free physical memory,
leaving some memory for other compilations as well.
Closes #12619

Prevent expensive compilations from exhausting available memory at JITServer

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Replace `dmb sy` with `dmb ish` at monent/monexit evaluators.

AArch64: Issue correct memory barrier instruction at monent/monexit

---

runtime/jvmti/jvmtiThread.c
runtime/oti/j9cfg_builder.h
runtime/oti/util_api.h
runtime/util/thrhelp.c
runtime/util/util.tdf
runtime/vm/callin.cpp
runtime/vm/j9vm.tdf
runtime/vm/jniinv.c
runtime/vm/vmthread.c

Fixup OS stack free with more accurate stack size
Currently on non-windows platforms we estimate the size of the native
stack and use that for stackoverflow calculations on callin frames. The
estimation has shown to be incredibly inaccurate specifically on AIX.
The issue comes form the fact that the requested stack size and the
actual stack space allocated by the OS can differ.
This PR attempts to get a more accurate stack size so that the
stackoverflow can detect cases where we would run out of stack space.
This is the first set of changes, additional changes will be required to
address the issue where the java launcher passes the -Xss value as the
native stack size for the main thread.
Also more changes will be needed to address cases where we have a stack
overflow, but we've run out of …

Fixup OS stack free with more accurate stack size

---

runtime/jvmti/jvmtiThread.c
runtime/oti/j9cfg_builder.h
runtime/oti/util_api.h
runtime/util/thrhelp.c
runtime/util/util.tdf
runtime/vm/callin.cpp
runtime/vm/j9vm.tdf
runtime/vm/jniinv.c
runtime/vm/vmthread.c

Reverts eclipse-openj9/openj9#12609
Broke Mac, and maybe other platforms, see https://ci.eclipse.org/openj9/job/Pipeline-Personal-Build/243/

Revert "Fixup OS stack free with more accurate stack size"

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/arm/codegen/J9ARMEvaluator.cpp
runtime/compiler/codegen/J9TreeEvaluator.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/p/codegen/PPCPrivateLinkage.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp

This option is not set anywhere and there is no option flag present
which can enable this option. Therefore the code guarded by it is
dead.
Closes: #6988

Deprecate TR_OptimizeForSpace

---

jcl/src/java.base/share/classes/java/lang/System.java

The logic is similar with `jdk.internal.util.SystemProps.initProperties()`.
With this PR, JDK17 (MacOS) builds and `-version` output is:
```
OpenJDK Runtime Environment (build 17-internal+0-adhoc.fengjcaibmcom.openj9-openjdk-jdk)
Eclipse OpenJ9 VM (build nativecoding-6e9f600cfe, JRE 17 Mac OS X amd64-64-Bit Compressed References 20210506_000000 (JIT enabled, AOT enabled)
OpenJ9   - 6e9f600cfe
OMR      - d96f2b34f
JCL      - c86a0903159 based on jdk-17+20)
```
closes https://github.com/eclipse-openj9/openj9/issues/12640
Note: Mac abuild failure was caused by https://github.com/eclipse-openj9/openj9/issues/12640.

Set system property native.encoding

---

runtime/vm/ValueTypeHelpers.cpp
runtime/vm/jvminit.c

Move areValueTypesEnabled() from jvminit.c to ValueTypeHelpers.cpp

Move areValueTypesEnabled() from jvminit.c

---

runtime/compiler/codegen/CodeGenGPU.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/ilgen/Walker.cpp

Simple cleanup operation. Related to, but not dependent on eclipse/omr#5983.

Deprecate unsigned IL

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/env/J9PersistentInfo.hpp
runtime/compiler/net/CommunicationStream.hpp

When JITServer reaches 63 compilation threads any compilation request after that will be added
to the queue and requests waiting in the queue will experience delays and therefore the client can timeout.
In this commit, I send feedback to the client about the number of active compilation threads. I added a new
enum that represents the state of the active compilation threads "ServerActiveThreadState", which has 3 states: HIGH,
VERY_HIGH and NORMAL_THREAD.
JITServer sends the client feedback about the state of Active threads at the end of every compilation. The client then
receives it and in the "JITServer::CompThreadActivationPolicy" decides based on the number of Active Threads when
to suspend/maintain the compilation threads.
If the number of Active threads >= to VERY_HIGH, then we …

Sending Client feedback about number of active compilations threads

---

runtime/compiler/optimizer/J9ValuePropagation.cpp
runtime/compiler/optimizer/J9ValuePropagation.hpp

During IL generation with value type support enabled, the JIT compiler generates calls to an equality comparison non-helper to compare objects, as simple address comparisons are not sufficient for comparison of value type instances in general.  It also generates calls to helpers to perform array element load and store operations.
This pull request makes changes to the Value Propagation optimization to have it detect calls to the equality comparison non-helper for which at least one operand is not a value type, and calls to the array load/store helpers for which the component type of the array is known not to be a value type.  For each case detected, the call is replaced with inline IL similar to that which would ordinarily be generated by IL generation.
Resolves:  #12175

Look for opportunities in Value Propagation to replace nonhelper and helper calls for value type support with inline IL

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/build/files/common.mk
runtime/compiler/x/codegen/X86PrivateLinkage.cpp
runtime/compiler/z/codegen/S390PrivateLinkage.cpp

A series of commits which converts the various `RegisterDependencyGroup` classes on each platform to a cross platform extensible class. This prepares the register dependencies to be further unified and commoned up.

Convert RegisterDependencyGroup to an extensible class

---

runtime/jvmti/jvmtiThread.c
runtime/oti/j9cfg_builder.h
runtime/oti/util_api.h
runtime/util/thrhelp.c
runtime/util/util.tdf
runtime/vm/callin.cpp
runtime/vm/j9vm.tdf
runtime/vm/jniinv.c
runtime/vm/vmthread.c

Fixup OS stack free with more accurate stack size
Currently on non-windows platforms we estimate the size of the native
stack and use that for stackoverflow calculations on callin frames. The
estimation has shown to be incredibly inaccurate specifically on AIX.
The issue comes form the fact that the requested stack size and the
actual stack space allocated by the OS can differ.
This PR attempts to get a more accurate stack size so that the
stackoverflow can detect cases where we would run out of stack space.
This is the first set of changes, additional changes will be required to
address the issue where the java launcher passes the -Xss value as the
native stack size for the main thread.
Also more changes will be needed to address cases where we have a stack
overflow, but we've run out of …

Fixup OS stack free with more accurate stack size ver2

---

jcl/src/java.base/share/classes/java/lang/String.java
test/functional/JIT_Test/src/jit/test/recognizedMethod/TestJavaLangStringLatin1.java

For Java 11, `StringLatin1.inflate` is the preferred API over `String.decompress`. This commit replaces those calls.
Additionally, `StringLatin1.inflate` tests are improved to account for more corner cases.

Replace decompress calls with StringLatin1.inflate and improve StringLatin1.inflate API tests

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/CompilationThread.hpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.hpp
runtime/compiler/control/JitDump.cpp
runtime/compiler/env/J9PersistentInfo.hpp
runtime/compiler/env/j9jit.tdf
runtime/compiler/net/MessageTypes.hpp
runtime/compiler/net/ServerStream.hpp
runtime/compiler/runtime/CompileService.cpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp

This commit allows server to produce a JitDump log when a crash occurs
during a compilation.
Once the crash happens, the JitDump handler runs normally, producing
an IL log of the crashed thread until it reaches the point when
the problematic method needs to be recompiled. There, it sends
the client a `compilationThreadCrashed` message, asking it to schedule
a JitDump recompilation and blocks until the recompilation is done.
When the client receives the error message, it temporarily stops all
further compilations, purges the compilation queue and sends a request
to the server to recompile the method as a JitDump compilation.
The server will compile the method on the diagnostic thread, notify
the waiting crashed thread, allowing the JitDump handler to finish and
terminate the server.
Once …

Enable JitDump support on JITServer

---

doc/compiler/ObjectLockword.md
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/vm/jvminit.c

Global Lock Reservation is now enabled by default on Power. This is the same
behavior as if the -XX:+GlobalLockReservation option was used. To use the
previous form of lock reservation, Global Lock Reservation can be disabled
with the option -XX:-GlobalLockReservation.
Global Lock Reservation is not supported on other platforms so this change
only affects Power.
Updated documentation and comments to reflect Global Lock Reservation now
being on by default on Power.
Closes: #11424

Enabled Global Lock Reservation by default on Power

---

jcl/src/java.base/share/classes/java/lang/Access.java
jcl/src/java.base/share/classes/java/lang/Class.java
test/functional/cmdLineTests/J9security/build.xml
test/functional/cmdLineTests/J9security/j9SecurityTest.xml
test/functional/cmdLineTests/J9security/jsr292.policy
test/functional/cmdLineTests/J9security/playlist.xml
test/functional/cmdLineTests/J9security/src/com/ibm/j9/jsr292/indyn/TestJSR292.java
test/functional/cmdLineTests/J9security/src/com/ibm/j9/jsr292/indyn/bootpath/CodeNotTrusted.java

This avoids `AccessControlException` within `Lookup.lookupClassProtectionDomain` initiated by `MethodHandleResolver.resolveInvokeDynamic()`;
Added a test to ensure proper permission check when invoking BootstrapMethod.
closes https://github.com/eclipse-openj9/openj9/issues/12600

Access.protectionDomain() invokes clazz.getProtectionDomainInternal()

---

runtime/oti/j9nonbuilder.h
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/BytecodeInterpreter.inc
runtime/vm/jvminit.c
runtime/vm/swalk.c

Wrap the impdep1 handler in 'if defined J9VM_OPT_METHOD_HANDLE' as it
is OpenJ9 specific.
Fixes: #12251

Disable impdep1 handling for OpenJDK MHs

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/runtime/RelocationRuntime.cpp
runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
runtime/tests/redirector/jep178/testjep178.c

Use of `strncpy(dst, src, strlen(src))` yields a warning.

Fix warnings due to improper use of strncpy()

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.hpp

Move f2i, f2l, d2i, d2l evaluators from OMR to OpenJ9

---

runtime/compiler/net/MessageBuffer.cpp
runtime/compiler/net/MessageBuffer.hpp

Message buffers store data that is exchanged between the server
and the client. When a message that is too big for the current buffer
is sent/received, `MessageBuffer::expandIfNeeded` or
`MessageBuffer::expand`
is called. These methods allocate a new, larger buffer and copy
any existing data over.
Previously, `MessageBuffer::expandIfNeeded` reallocated buffer to twice
the required size, and `MessageBuffer::expand` to exactly the required
size.
This leads to fragmentation of global persistent memory, as memory
blocks of arbitrary sizes cannot be easily reused for future allocations.
This commit sets the default buffer size to 32K, and all subsequent
expansions are done to the size of the nearest power of 2. This ensures
that memory allocations are standardized. Once a large buffer is …

Improve JITServer::MessageBuffer capacity expansion mechanism

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

Reverts eclipse-openj9/openj9#12718
Reverting #12702 due to #12720

Revert "Fix build break in J9TreeEvaluator.cpp"

---

runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp
runtime/compiler/z/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9SystemLinkageLinux.cpp
runtime/compiler/z/codegen/J9SystemLinkagezOS.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/ReduceSynchronizedFieldLoad.cpp
runtime/compiler/z/codegen/S390PrivateLinkage.cpp
runtime/compiler/z/codegen/S390Recompilation.cpp

See each individual commit for which pseudo-instructions were unified. I did not touch x86 or ARM because they need to be taught to use `TR::InstOpCode` first and that is a much larger piece of work than what is done here. I will be tackling this once this PR is merged.
Depends on eclipse/omr#6000

Unify a set of common pseudo-instructions across codegens

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/control/JITServerHelpers.hpp
runtime/compiler/runtime/JITClientSession.cpp

JITServer caches class information sent by the JVM clients in order to
reduce client-server network communication. This is done in a two step
operation: (1) First we allocate space for the ROMClass data structure
using persistent memory; (2) Then we acquire a lock and cache the class
information.
Due to a race condition, it is possible that, by the time we allocated
and initialized the ROMClass copy, another thread already inserted a copy
into the cache. If that happens, we just have to deallocate the newly
created ROMClass copy.
The bug solved by this commit revolves around how to the perform the
deallocation: if the server uses a global cache of ROMClasses (shared
among all the clients) then we have to use routines specific to this
global cache, rather than just calling persistentFree. …

Properly free ROMClass when caching at the JITServer fails

---

runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp

Introduce a new default scan ordering type 'none'. In gencon configuration, scan ordering will be set to hierarchical if it has not already been overridden by an option. In balanced, scan ordering will be set to dynamic BF if it has not already been overridden by an option.

Introduce New Default Scan Ordering 'None'

---

runtime/compiler/optimizer/J9TransformUtil.cpp

```
error: 1036 enumeration values not handled in switch
```
Fixes: https://github.com/eclipse-openj9/openj9/issues/12734

Fix -Wswitch

---

runtime/libffi/CMakeLists.txt

Builds in macOS with case-sensitive filesystem fail because they expect
to find runtime/libffi/x86/darwin64.s, but it doesn't exist. Instead,
there is runtime/libffi/x86/darwin64.S (note the upper case 'S' at the
end). Since all other assembly files are using '.S', CMakeLists.txt has
been updated accordingly.
Signed-off-by: Sergio Aguayo <sergioag@qmailhosting.net>

Fix mismatch in filename case causing macOS builds to fail

---

runtime/bcutil/ClassFileWriter.cpp

Fix recreation of class with local type annotation
Correctly iterate type annotations in local variables when recreating
the original classfile.

Fix recreation of class with local type annotation

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/compile/J9SymbolReferenceTable.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9method.h
runtime/oti/j9nonbuilder.h

This changeset includes the following:
* Add functionality to lookup/create j9VMThreadFloatTemp1Symbol
* Insert trees to store num args to VMThread.floatTemp1 for
linkToStatic/Special
* Document this added use case of the floatTemp1 field
Depends: eclipse/omr#5961 (merged), eclipse/omr#5997 (merged)
Related: #12522
In draft state until OMR changes are merged.

Store number of arguments in vmThread.floatTemp1 for linkToStatic

---

runtime/compiler/control/J9Options.cpp

Added 'F' to the message for JITServer options which means message information
to be printed if this option is in effect.
Signed-off-by: Eman Elsabban <eman.elsaban1@gmail.com>

Print JITServer options in effect into the verbose log

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Fix width of load instructions used in VMinlineCompareAndSwapObject.

AArch64: Fix VMinlineCompareAndSwapObject

---

jcl/src/java.base/share/classes/java/lang/String.java

Updated `StringIndexOutOfBoundsException` message for `String.substring()` methods.
closes #11833 
Note: I think OpenJ9 doesn't need match RI `StringBuffer`/`StringBuilder` exception messages as per https://github.com/eclipse-openj9/openj9/issues/11833#issuecomment-780162674 unless there is a specific user request. (thanks @sharon-wang extensive testcase though)
fyi @fjeremic 

String.substring() StringIndexOutOfBoundsException helpful messages

---

runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp

When server receives the first message from the client,
it needs to initialize caches, such as CH table and unloaded class ranges.
However, messages can arrive out order, resulting in double
initialization.
This commit creates a critical section around cache initialization,
to ensure that no double initialization can occur.
This code was written by @AlexeyKhrabrov, I'm committing it in his stead.

Fix race condition in JITServer cache initialization

---

runtime/j9vm31/jnicgen.cpp

- The Call*MethodV shim methods did not set up the
arguments pointer properly from the incoming va_list (31-bit)
arg parameter.  Updated va_list_64 argument parameter
to directly reference the corresponding parameter
from the 31-bit va_list.
- Cleanup unnecessary value variable from Call*Method
shim methods.

31/64 Interop: Fix va_list_64 arguments pointer for Call*MethodV

---

doc/release-notes/0.27/0.27.md

Update release notes for 0.27 to include the change in behavior for `balanced` to use a dynamic breadth-first scan ordering policy.
Related to: https://github.com/eclipse-openj9/openj9-docs/pull/793

Update release notes for 0.27 for Balanced GC Optimization

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/compile/J9SymbolReferenceTable.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9method.h
runtime/oti/j9nonbuilder.h

Reverts eclipse-openj9/openj9#12549
#12549 causes some failures for the OpenJDK MH builds. Reverting this PR for now and a follow-up PR will address the issues faced.

Revert "Store number of arguments in vmThread.floatTemp1 for linkToStatic"

---

runtime/compiler/env/j9method.cpp

Turn on a flag to enable FastJNI on aarch64.

AArch64: Support FastJNI

---

runtime/compiler/env/VMJ9.cpp
runtime/compiler/optimizer/J9TransformUtil.cpp

The duplication appears to have been an unintended artifact of (pre-open source) refactoring.
Also (in a separate commit) fix the `SimpleRegex` matching for `-Xjit:classesWithFoldableFinalFields={...}`. A NUL-terminated string is required.

Combine the two definitions of foldFinalFieldsIn()

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.hpp
test/functional/Java11andUp/playlist.xml

This commit implements BNDCHKwithSpineCHKEvaluator() for AArch64.

AArch64: Implement BNDCHKwithSpineCHKEvaluator()

---

buildenv/docker/mkdocker.sh
buildenv/jenkins/docker-nodes/README.md
buildenv/jenkins/docker-nodes/jenkinsfile-build-container.groovy

* update jenkins container build for centos6.10
* update repos to alternate now that os is end of life
* update namespace to reference new repo location
* move perms adjusting to end of dockerfile so all content is owned by $user
* comment out freemarker requirement as its no longer in use
* remove non-existent ius-release-el6.rpm
* modified SDK location as builds were modified to reference $USER_HOME/bootjdks/

Update docker container script for use with OpenJ9 builds

---

runtime/gc_glue_java/ObjectModelDelegate.hpp

Cleanup CopyForward refactor PR for changes that were previously
required as a result of a mutual dependency between Delegate/OpenJ9.

Cleanup Refactor of CopyForward to reuse fixupForwardedObject

---

runtime/nls/jitm/j9jit.nls
runtime/nls/jitm/j9jit_ca.nls
runtime/nls/jitm/j9jit_cs.nls
runtime/nls/jitm/j9jit_de.nls
runtime/nls/jitm/j9jit_es.nls
runtime/nls/jitm/j9jit_fr.nls
runtime/nls/jitm/j9jit_hu.nls
runtime/nls/jitm/j9jit_it.nls
runtime/nls/jitm/j9jit_ja.nls
runtime/nls/jitm/j9jit_ko.nls
runtime/nls/jitm/j9jit_pl.nls
runtime/nls/jitm/j9jit_pt_BR.nls
runtime/nls/jitm/j9jit_ru.nls
runtime/nls/jitm/j9jit_sk.nls
runtime/nls/jitm/j9jit_sl.nls
runtime/nls/jitm/j9jit_tr.nls
runtime/nls/jitm/j9jit_zh.nls
runtime/nls/jitm/j9jit_zh_CN.nls
runtime/nls/jitm/j9jit_zh_TW.nls

New NLS messages must be added to the end of the file.
See https://github.com/eclipse-openj9/openj9/blob/master/runtime/nls/jitm/j9jit.nls#L24
J9NLS_RELOCATABLE_CODE_FSD_MISMATCH was added in the middle by
https://github.com/eclipse-openj9/openj9/commit/5fce799
from https://github.com/eclipse-openj9/openj9/pull/11554
Also fix incorrect jitm/j9jit nls explanation prefix

Move new jitm/j9jit message to the end and fix explanation prefix

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/optimizer/InterpreterEmulator.cpp
runtime/compiler/optimizer/InterpreterEmulator.hpp
runtime/compiler/optimizer/J9TransformUtil.cpp
runtime/compiler/optimizer/J9TransformUtil.hpp

In particular, push a known object operand whenever stateful iteration encounters a `getstatic` bytecode instruction that loads an object from a static final field declared by an allowlisted class (or any other reference-typed static final field that would be treated as a known object in `findOrCreateStaticSymbol()`).
This allows the inliner to find the `MethodHandle` for which a specialized `LambdaForm` was generated. Such a `LambdaForm` loads its `MethodHandle` from a static final field and replaces the corresponding argument, which would previously result in an unknown `MethodHandle` even when the `MethodHandle` argument is already a known object due to inlining.
Thanks to @liqunl for the original version of this change.
There is a preparatory commit to reduce code duplication.

Teach InterpreterEmulator about foldable statics

---

runtime/compiler/optimizer/J9Optimizer.cpp
runtime/compiler/optimizer/SequentialStoreSimplifier.cpp
runtime/compiler/optimizer/SequentialStoreSimplifier.hpp
test/functional/JIT_Test/playlist.xml
test/functional/JIT_Test/src/jit/test/tr/SeqLoadSimplificationTest.java
test/functional/JIT_Test/testng.xml

Changes were made inside the sequentialStoreSimplification. Despite the name
of the optimization, the changes are targeted at sequential loads.
Rewrote the optimization that identifies byte loads from conseuctive memory
addresses and replaces them with a wider load such as an iload or lload. The
new version greatly expands the number of tree patterns indentified by the
optimization. The new wide load optimization works with 2-8 consecutive byte
loads and in both big and little endian order.
The original version of the opt is still available under the env var
TR_UseOldSeqLoadOpt.
Moved sequentialStoreSimplificationGroup later in the optimization order so
that the trees are more likely to be in the right shape for the optimization.
Moved sequentialStoreSimplification out of …

Rewrite opt for combining consecutive byte loads

---

test/functional/JLM_Tests/playlist.xml
test/functional/Java11andUp/playlist.xml
test/functional/Java8andUp/playlist.xml

- Replace illegal-access with add-opens due to JEP 403.
- This replacement only worked with these six tests, and other tests with illegal-access will be worked on other PRs.
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/12727
[skip ci]

Replace illegal-access with add-opens

---

runtime/jit_vm/cthelpers.cpp
runtime/oti/j9protos.h

Add ctjithelper method header
- Add jitIsFieldStable to j9protos.h
- Remove unused field

Add ctjithelper method header

---

test/functional/DDR_Test/tck_ddrext.xml

- Add -Xaot:disableAsyncCompilation, -Xjit:disableAsyncCompilation and -Xmx512M to the TCK.cache.initialization step to match the TCK.generate.dump step. This ensures that the SCC AOT header matches the SCC AOT contents, and that the AOT code in the SCC is not ignored
- Add -Xaot:count=0 to the TCK.generate.dump step to guarantee that AOT compilation occurs

Fix Java Options for testDDRExt_SharedClasses

---

runtime/jvmti/jvmtiClass.c
runtime/oti/util_api.h
runtime/util/hshelp.c

Disable fixDirectHandles when building for OJDK method handles.
Issue: #11528

Disable J9-specific HCR code in OJDK implementation

---

runtime/j9vm31/j9vm31.h
runtime/j9vm31/jnimisc.cpp

Add 31-bit shim functions for the JNI extensions
that convert between jstring references and
alphanumeric data in EBCDIC based encodings, commonly
used by COBOL code on z/OS.

Add 31/64 shim functions for *StringPlatform APIs

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/J9ObjectFieldOffsetIterator_V1.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/ObjectFieldInfo.java
runtime/gc_base/ObjectAccessBarrier.cpp
runtime/oti/j9.h
runtime/vm/ObjectFieldInfo.cpp
runtime/vm/createramclass.cpp
runtime/vm/resolvefield.cpp
test/functional/Valhalla/playlist.xml
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java
test/functional/cmdLineTests/valuetypeddrtests/flattenedvaluetypeddrtests.xml

1. On 64-bit reference mode, ensure double alignment on all nested
fields.
2. On 32-bit reference mode, ensure double alignment on 8-byte volatile 
fields. copyObjectFields() will do 8-byte copy when possible.
closes #11178

Fix object field copying issue on valueType

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/il/J9Symbol.cpp
runtime/compiler/il/J9Symbol.hpp
runtime/compiler/optimizer/InterpreterEmulator.cpp
runtime/compiler/optimizer/J9TransformUtil.cpp
runtime/compiler/optimizer/J9TransformUtil.hpp

In the `LambdaForm`-based JSR292 implementation, `CallSite` declares a target field to be inherited by all subclasses, including `MutableCallSite`, and that field is declared final even though it's actually mutable in instances of MCS.
Because it is a final field declared in a trusted JCL package, loads of this field would normally be folded to a known object. However, folding the target in the case of a MCS can result in the spurious removal of the MCS target guard, so refuse to fold in that case.
Folding is prevented in `transformIndirectLoadChain` and `InterpreterEmulator`.
This is a prerequisite to `MutableCallSite` inlining with `LambdaForm`.
----
There are a few refactoring/cleanup commits leading up to the main commit.

Avoid folding MutableCallSite.target

---

test/functional/DDR_Test/tck_ddrext.xml

Reverts eclipse-openj9/openj9#12793
As this change is causing https://github.com/eclipse-openj9/openj9/issues/12814, failures in extended.functional across all platforms and versions.

Revert "Fix Java Options for testDDRExt_SharedClasses"

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/J9ClassHelper.java

Fixes https://github.com/eclipse-openj9/openj9/issues/12818

Delete comment referring to obsolete J9VMJavaLangClassNativesCDLC

---

runtime/gc_modron_startup/mminit.cpp
runtime/oti/j9.h
runtime/redirector/redirector.c
runtime/vm/jvminit.c

Mixedrefs build switches to `nocompressedrefs` if `-Xmx` value specified in command line is larger than the maximum heap size allowed for `compressedrefs` mode according to platform/spec.
Verified that this PR can start VM via `-Xmx300g -version` in MacOS & zOS 64bit.
closes https://github.com/eclipse-openj9/openj9/issues/12683
depending on https://github.com/eclipse/omr/pull/6036

Mixedrefs build switches to nocompressedrefs automatically based on -Xmx

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
runtime/jvmti/jvmtiClass.c
runtime/oti/j9nonbuilder.h
runtime/oti/util_api.h
runtime/util/hshelp.c

`fixMemberNames` called after HCR to do a heap walk to fix all `MemberName` objects' `vmtarget`. `MemberName->clazz` and `MemberName->vmindex` have already been fixed by existing mechanisms.
- If the object is a fieldID, set vmtarget to the field offset + modifiers. If it is a method/constructor ID, set vmtarget to the ID's method
- Move needed MemberName macros to j9nonbuilder.h
- Define struct consisting of J9VMThread * and void * to be passed into the callback function as it needs the current thread and the class hash table
Issue: #11528

Fix MemberName fields after Fast HCR and FSD

---

runtime/compiler/build/files/target/x.mk
runtime/compiler/x/amd64/codegen/AMD64J9SystemLinkage.cpp
runtime/compiler/x/amd64/codegen/AMD64JNILinkage.cpp
runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp
runtime/compiler/x/codegen/Instruction.hpp
runtime/compiler/x/codegen/J9LinkageUtils.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/J9UnresolvedDataSnippet.cpp
runtime/compiler/x/codegen/J9X86Instruction.cpp
runtime/compiler/x/codegen/J9X86Instruction.hpp
runtime/compiler/x/codegen/X86PrivateLinkage.cpp
runtime/compiler/x/codegen/X86PrivateLinkage.hpp
runtime/compiler/x/i386/codegen/IA32JNILinkage.cpp
runtime/compiler/x/i386/codegen/IA32PrivateLinkage.cpp

This PR is a sequence of commits each of which is able to compile on its own and which systematically eliminate `TR_X86OpCodes` and `TR_X86OpCode` in favour of `TR::InstOpCode::Mnemonic` and `TR::InstOpCode` respectively. Please see each commit message for what was done and why. Semantically there should be no change in behaviour following these changes.
There is still two large pieces of work do be done which will be handled in separate PRs so as to avoid introducing hundreds (thousands?) more changes here:
1. Currently we have a temporary “defines” file which for every opcode does for example #define   ADC1AccImm1 OMR::InstOpCode::ADC1AccImm1. Ideally we would like to get rid of this defines file and qualify all x86 instruction mnemonics with TR::InstOpCode:: as we do on all other …

Adopt TR::InstOpCode on x86

---

jcl/src/java.base/share/classes/com/ibm/oti/vm/AbstractClassLoader.java
jcl/src/java.base/share/classes/java/lang/Access.java
jcl/src/java.base/share/classes/java/lang/Class.java
jcl/src/java.base/share/classes/java/lang/ClassLoader.java
jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
jcl/src/java.base/share/classes/java/lang/StackWalker.java
jcl/src/java.base/share/classes/java/lang/System.java
jcl/src/java.base/share/classes/java/lang/Thread.java
jcl/src/java.base/share/classes/java/lang/ThreadGroup.java
jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
jcl/src/java.base/share/classes/java/lang/invoke/MethodType.java
jcl/src/java.base/share/classes/java/security/AccessControlContext.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/ClassLoadingMXBeanImpl.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/ManagementUtils.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/MemoryMXBeanImpl.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/MemoryPoolMXBeanImpl.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/RuntimeMXBeanImpl.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/ThreadMXBeanImpl.java
jcl/src/java.management/share/classes/java/lang/management/ManagementFactory.java
jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9AttachProvider.java
jcl/src/jdk.management/share/classes/openj9/lang/management/internal/OpenJ9DiagnosticsMXBeanImpl.java
jcl/src/openj9.cuda/share/classes/com/ibm/cuda/CudaDevice.java
jcl/src/openj9.cuda/share/classes/com/ibm/cuda/CudaModule.java
jcl/src/openj9.gpu/share/classes/com/ibm/gpu/CUDAManager.java
jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Dump.java
jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Log.java
jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Trace.java
jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedAbstractHelper.java
jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedAbstractHelperFactory.java
jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassUtilities.java

Added `JavaLangAccess` method implementations for `isEnableNativeAccess(mod)`, `addEnableNativeAccessAllUnnamed()` and `addEnableNativeAccess(mod)`;
Added `@SuppressWarnings("removal")` before `SecurityManager` to fix `error: warnings found and -Werror specified` for `warning: [removal] SecurityManager in java.lang has been deprecated and marked for removal`.
With this PR, `JDK17` `openj9-staging` branch can be built and `-version` output is as following:
```
OpenJDK Runtime Environment (build 17-internal+0-adhoc.fengjcaibmcom.mergetmp)
Eclipse OpenJ9 VM (build jdk17update-199ad9188d, JRE 17 Mac OS X amd64-64-Bit Compressed References 20210603_000000 (JIT enabled, AOT enabled)
OpenJ9   - 199ad9188d
OMR      - a5a0eca5a
JCL      - 0920b4bc912 based …
```

JDK17 update : add JavaLangAccess methods & @SuppressWarnings("removal") for SecurityManager

---

jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
runtime/bcutil/ROMClassBuilder.cpp
runtime/bcutil/ROMClassBuilder.hpp
runtime/bcutil/ROMClassCreationContext.hpp
runtime/jcl/common/clsldr.cpp

In OJDK, `MethodHandles.Lookup.ClassDefiner` is used by
- `Lookup.defineClass` (normal/non-hidden classes)
- `Lookup.defineHiddenClass`
- `Lookup.defineHiddenClassWithClassData`
In OJDK, `ClassDefiner` can define both normal and hidden classes.
In OJ9, `ClassDefiner` is only used by
- `Lookup.defineHiddenClass`
- `Lookup.defineHiddenClassWithClassData`
In OJ9, ClassDefiner is only used to define hidden classes.
`ClassDefiner` invokes `ClassLoader_defineClassImpl1` (native function).
Currently, `ClassLoader_defineClassImpl1` only defines hidden classes. It is
updated to define both hidden and normal classes. This will allow us to
support both OJ9 and OJDK verions of `Lookup`.
Without this fix, all classes created by OJDK's `Lookup.defineClass` will be
hidden classes.
This commit reverts …

Update ClassLoader_defineClassImpl1 + Redo InjectedInvoker Support

---

runtime/vm/vmprops.c
test/TestConfig/resources/excludes/feature_ojdkmh_exclude.txt
test/Utils/src/org/openj9/test/util/IncludeExcludeTestAnnotationTransformer.java

Currently, `IncludeExcludeTestAnnotationTransformer` only processes a single
exclude file.
It has been updated to process a list of exclude files.
The list can be provided via the `EXCLUDE_FILE` environment variable where the
exclude files are separated by commas.
The name of the environment variable is left unchanged. So, the existing
scripts do not need to be updated.
The new system property can be checked through `-XshowSettings:properties`.
TODO: eclipse-openj9#12811

OJDK MHs test excludes + Process a list of test exclude files

---

runtime/compiler/aarch64/codegen/ARM64JNILinkage.cpp

Parts of the JNI method dispatch and callout frame building were being
generated on the instruction stream using an uninitialized starting
instruction cursor.  The cursor-form instructions are not required for
this sequence, so simply rewrite the sequence to append at the end of
the instruction stream instead.

Fix incorrect AArch64 JNI instruction sequences

---

jcl/src/java.base/share/classes/java/lang/Access.java
jcl/src/java.base/share/classes/java/lang/ClassLoader.java

It is required by OpenJDK update b25.
With this PR, `JDK17` `openj9-staging` branch can be built and `-version` output is as following:
```
OpenJDK Runtime Environment (build 17-internal+0-adhoc.fengjcaibmcom.mergetmp)
Eclipse OpenJ9 VM (build attachlog-2894a3ca34, JRE 17 Mac OS X amd64-64-Bit Compressed References 20210605_000000 (JIT enabled, AOT enabled)
OpenJ9   - 2894a3ca34
OMR      - a5a0eca5a
JCL      - 6b4c146221b based on jdk-17+25)
```

JDK17 add Access.findNative(loader, entryName)

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp

Increase JITClient socket default timeout to 10 seconds

---

test/functional/Java8andUp/playlist.xml
test/functional/Java8andUp/src/org/openj9/test/annotationClassLoader/Test_ClassLoader.java

- Update CachedRowSet create method to solve illegal-access error for JCL_Test and JCL_Test_none_SCC
- Relate Issue: https://github.com/eclipse-openj9/openj9/issues/12727
[skip ci]

Update CachedRowSet create method for illegal-access error

---

runtime/compiler/control/JitDump.cpp

When a compilation thread is holding onto the class unload mutex and it
crashes, we must make sure to release the class unload mutex prior to
queuing the compilation, because we could encounter a deadlock.
The deadlock scenario occurs when the crashed thread holds onto the
class unload mutex, we proceed to queue a recompilation of the method
via the JitDump mechanism. When the diagnostic thread is printing a
class name for example, it will attempt to acquire VM access. The GC
could have asked for exclusive at some previous point which means the
compile thread will have to yield and wait for GC to finish. If the
GC attempts to unload classes it cannot because our crashed thread
still holds onto the class unload mutex, hence we get in a deadlock
situation.
The fix here is to simply release …

Fix deadlock when crashed thread holds onto the class unload mutex

---

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp
runtime/compiler/aarch64/codegen/J9CodeGenerator.hpp

Add suppressInliningOfRecognizedMethod to aarch64 code generator as the default implementation of this method now always returns true as described in https://github.com/eclipse/omr/issues/6049.

AArch64: Add suppressInliningOfRecognizedMethod to code generator

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

When running 64 bit compressed refs, if clazz is an address
above the 2G boundary then we can't use a push 32bit immediate
instruction to pass it on the stack to the `jitThrowClassCastException`
helper as the address gets sign extended. It needs to be
stored in a temp register and then push the register to the stack.

Fix incorrect J9Class pointer in ClassCastException

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit stops generating a shift instruction in
genArrayletAccessAddr() for AArch64 when the shift amount is 0.

AArch64: Stop generating a redundant shift instruction

---

runtime/j9vm31/j9cel4ro64.c
runtime/j9vm31/jnicsup.cpp
runtime/libffi/z/ffi64.c

Two fixes related to zOS 31/64 bit interoperability:
- LE added a new CEEPCB_3164 bit on CEEPCBFLAG6 flag within Process
Control Block (PCB) to indicate support for CEL4RO31/64. Update
both libffi and libjvm31 usage of CEL4RO31/64 checks, as previous checks
were not sufficient on older zOS releases.
- NewObjectV did not set up the arguments pointer properly
from the incoming va_list (31-bit) arg parameter.
Updated va_list_64 argument parameter to directly
reference the corresponding parameter from the 31-bit va_list.

31/64 Interop: Exploit CEEPCB_3164 bit and fix va_list_64 arg for NewObjectV

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp

For POWER instanceof evaluator, testing super class assumes class
depth to be known at compile time which is not always true. This
commit adds getting classDepth in runtime when its unknown at
compile time.
The argument `depthInReg2` for `genTestIsSuper()` decides if the depth is known and to create a load-constant for it or if it will be found in runtime and will be in scratch2Reg.

Fix ifInstanceOfEvaluator for unknown class cases

---

runtime/compiler/x/env/J9CPU.cpp

Enable SSE3 feature check which will be required across OpenJ9 and OMR for FP calculations

Enable SSE3 feature check

---

runtime/compiler/arm/codegen/ARMJNILinkage.cpp
runtime/compiler/arm/codegen/ARMJNILinkage.hpp
runtime/compiler/arm/codegen/ARMPrivateLinkage.cpp
runtime/compiler/arm/codegen/ARMPrivateLinkage.hpp
runtime/compiler/arm/codegen/Instruction.hpp
runtime/compiler/arm/codegen/J9ARMSnippet.cpp
runtime/compiler/build/files/target/arm.mk

Replicate the work done in #12729 on ARM. The changes here follow the exact same sequence of steps as on x86. There was no deviation from the sequence of steps performed.
Depends on eclipse/omr#6055

Adopt TR::InstOpCode on ARM

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/DLLMain.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/runtime/JITClientSession.hpp

This PR removes the limit of 63 compilation threads at JITServer. The user can now specify a larger number of threads with `-XcompilationThreads<N>`. The default number of threads is kept at 63. Increasing the number of server threads is beneficial in the following scenarios:
- Network connection between the server and the clients has relatively high latency, and compilation threads spend a large portion of time waiting in network I/O system calls.
- JITServer instance has a relatively large number of CPU cores available.
Closes #12847

Remove limit on number of JITServer compilation threads

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/CompilationThread.hpp
runtime/compiler/control/MethodToBeCompiled.cpp
runtime/compiler/control/MethodToBeCompiled.hpp

When JITServer clients are run in the containerized environment,
they are likely allocated a limited amount of memory that's sufficient
to run the application and support JITServer compilation, but not large
enough to perform expensive compilations locally.
If a server is temporarily unavailable, all compilations will be done
locally and we will see many failures due to low available memory.
If a compilation failed early due to insufficient memory, there will be
no recompilation attempts leading to bad performance even if server
becomes available or memory situation improves.
This commit addresses the above issue in 2 steps:
1. If the client is running low on memory, downgrade compilations to
cold, because they are typically much cheaper, making them less likely
to fail.
2. Once the …

Add support for delayed start of JITServer

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/DLLMain.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/runtime/JITClientSession.hpp

Reverts eclipse-openj9/openj9#12913
I merged 12913 by mistake, before having performed Jenkins tests on it.

Revert "Remove limit on number of JITServer compilation threads"

---

runtime/gc_base/accessBarrier.cpp
runtime/gc_base/gc_internal.h
runtime/gc_realtime/RealtimeAccessBarrier.cpp
runtime/oti/j9nonbuilder.h

The SIGQUIT handler always uses NULL for the current thread, which leads
to a crash in the blockingEnterObject read. Update this to work when
currentThread is NULL.
Fixes: #12851
[ci skip]

Allow NULL currentThread in J9VMThread blockingEnterObject read

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp
test/functional/JIT_Test/playlist.xml

The array header size recently increased from 16 bytes to 24 bytes on 64-bit platforms.  With a 16 byte header size, inline code generated by the JIT to allocate a multidimensional array on the thread-local heap didn't need to account for alignment of the array headers, as they would be aligned for any shift compression amount.  With a size of 24 bytes,
headers will not be automatically aligned for a shift compression amount of four, which requires a heap alignment of 16 bytes.
The problem can be reproduced with this simple test:
```
public class Bar {
public static final Integer[][] sub(int dim1, int dim2) {
return new Integer[dim1][dim2];
}
public static final void main(String[] args) {
sub(3, 0);
}
}
```
Running with this command:
```
java -XXgc:forcedShiftingCompressionAmount=4 …
```

Account for array header alignment for multianewarray evaluator

---

.github/workflows/runAqa.yml
.github/workflows/runAqaConfig.json

- tailor runaqa action and workflow files for openj9
- current runaqa version doesn't support build openj9
[ci skip]

Enable runaqa PR build

---

test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-6.xml

Add option -Xaot:disableSharedCacheHints for tests reusing cache 
with mprotect=none on zos_390-31. Memory protection is across process
there. Disable update to the cache if running with mprotect=none. 

Add option -Xaot:disableSharedCacheHints in SCC CML tests

---

runtime/compiler/optimizer/J9ValuePropagation.cpp

This covers a pair of minor improvements to value propagation for the prototype support for value types.
The `isValue` static method in `J9ValuePropagation.cpp` did not take into account that an array cannot be an instance of a value type.  That could prevent reference comparisons involving an array from being recognized as not needing to use the <objectEqualityComparison> non-helper.  Added a check to return `TR_no` in that case.
Also, in `J9::ValuePropagation::constrainRecognizedMethod`, a call to the `jitLoadFlattenableArrayElement` helper can be marked with the component type of the array whose element is being accessed.  That can allow the current pass of value propagation to recognize additional opportunities based on that type constraint.

Tweaks to Value Propagation for value types prototype support

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp
test/functional/JIT_Test/playlist.xml

The array header size recently increased from 16 bytes to 24 bytes on 64-bit platforms.  With a 16 byte header size, inline code generated by the JIT to allocate a multidimensional array on the thread-local heap didn't need to account for alignment of the array headers, as they would be aligned for any shift compression amount.  With a size of 24 bytes,
headers will not be automatically aligned for a shift compression amount of four, which requires a heap alignment of 16 bytes.
The problem can be reproduced with this simple test:
```
public class Bar {
public static final Integer[][] sub(int dim1, int dim2) {
return new Integer[dim1][dim2];
}
public static final void main(String[] args) {
sub(3, 0);
}
}
```
Running with this command:
```
java -XXgc:forcedShiftingCompressionAmount=4 …
```

(0.27) Account for array header alignment for multianewarray evaluator

---

buildenv/jenkins/README.md
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
buildenv/jenkins/variables/defaults.yml
test/docs/OpenJ9TestUserGuide.md

- Update repoUrl to https://github.com/adoptium/aqa-tests.git to defaults.yml
In openj9, ADOPTOPENJDK_REPO value in test build is set by upstream (defaults.yml),
so we need to update it to adoptium/aqa-tests
- Update readme files

Update git url to adoptium/aqa-tests

---

runtime/compiler/optimizer/InterpreterEmulator.cpp
runtime/compiler/optimizer/InterpreterEmulator.hpp

In particular, in the debug tracing. The much safer `snprintf()` is now used instead, though with the usual caveat that only `_snprintf()` (with the underscore) is available in older versions of MSVC.
The implementations of `Operand::printToString()` are moved into InterpreterEmulator.cpp to avoid putting `#define snprintf ...` into a header file.
A wrapper is added that checks the result and prints a warning to the log when truncation is detected. It also ensures NUL-termination in case we are using `_snprintf()`.
Call sites are updated to call the wrapper instead of calling the method directly, and to use a larger buffer size. The old sizes were either barely large enough (50), or definitely too small (20). The new size is defined as a constant `OPERAND_STR_BUF_SIZE` to keep all of the …

Stop using unsafe sprintf() in InterpreterEmulator

---

test/functional/cmdLineTests/jython/playlist.xml

- disable mode 616 testing on vmfarm
- related: runtimes/backlog issue 514
[ci skip]

add mode 616 to cmdLineTester_jython test

---

test/functional/Java14andUp/playlist.xml
test/functional/JavaAgentTest/playlist.xml
test/functional/Jsr292/playlist.xml

- Set add-opens for several required packages for tests
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/12727
[skip ci]

Set add-opens for several packages due to JEP 403

---

jcl/jpp_configuration.xml
jcl/src/java.base/share/classes/java/lang/Access.java
runtime/bcutil/defineclass.c
runtime/oti/j2sever.h
runtime/oti/j9nonbuilder.h

Added `JPP pConfig JAVA18`;
Added `BCT_Java18MajorVersionShifted`;
Added `Access.exit(status)`;
With this PR, `-version` output for JDKnext `openj9-staging`:
```
openjdk version "18-internal" 2022-03-15
OpenJDK Runtime Environment (build 18-internal+0-adhoc.fengjcaibmcom.mergetmp)
Eclipse OpenJ9 VM (build master-d8104c46a0, JRE 18 Mac OS X amd64-64-Bit Compressed References 20210611_000000 (JIT enabled, AOT enabled)
OpenJ9   - d8104c46a0
OMR      - 99f008c99
JCL      - da7073a7c4b based on jdk-9+99)
```
The JCL version is a known issue due to merging script.
close https://github.com/eclipse-openj9/openj9/issues/12930

JDK18 bringup - add JAVA18 JPP pConfig, Access.exit & MajorVersion

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/j9methodServer.cpp

The client-side handler of `ResolvedMethod_getMultipleResolvedMethods`
did not check the value of `J9JIT_RUNTIME_RESOLVE` flag for some of
the methods it created, which resulted in bugs when `-Xjit:rtResolve`
option is specified.
This commit refactors `ResolvedMethod_getMultipleResolvedMethods`
and `TR_ResolvedJ9JITServerMethod::cacheResolvedMethodCallees` to
call resolved method creation routine on the client directly, instead
of copy-pasting the code from that routine, which fixes the problem.
The code here is a small chunk of PR #12147, which should fully refactor
resolved methods creation, when it is merged at a later date.

Fix a number of issues related to runtime resolution of methods

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/DLLMain.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/runtime/JITClientSession.hpp

This PR is a rework of #12913.
The new limit is 999 (1000 including the statistics/diagnostic thread) and is somewhat artificial. It allows us to keep the existing format of compilation thread names defined in `TR::CompilationInfoPerThread::CompilationInfoPerThread()`, and is large enough for a single machine, at least in the near future.
The default number of threads is kept at 63. If the user specifies (with `-XcompilationThreads<N>`) a number of threads larger than the limit of 999, a diagnostic message is printed to `stderr`, and the default number of threads (63) is used.
If the requested number of threads is larger than the maximum number of code caches, a diagnostic message is printed to `stderr`, and JITServer start is aborted.

Increase maximum number of JITServer compilation threads

---

runtime/compiler/build/files/common.mk
runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/DLLMain.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/control/JITServerHelpers.hpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/runtime/CMakeLists.txt
runtime/compiler/runtime/JITServerAOTCache.hpp
runtime/compiler/runtime/JITServerAOTDeserializer.cpp
runtime/compiler/runtime/JITServerAOTDeserializer.hpp
runtime/compiler/runtime/JITServerAOTSerializationRecords.hpp
runtime/compiler/runtime/SymbolValidationManager.cpp
runtime/compiler/runtime/SymbolValidationManager.hpp

This PR adds the `JITServerAOTDeserializer` class that will be used at the JIT client to deserialize cached AOT methods received from the JITServer. The deserializer updates each SCC offset in relocation and validation records stored in method relocation data such that it points to the correct entity in the local SCC, which is looked up and validated using the information in AOT serialization records attached to the serialized AOT method.

JITServer AOT cache deserializer

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/J9ObjectModel.cpp
runtime/compiler/runtime/JITClientSession.hpp

`J9::ObjectModel::objectAlignmentInBytes` returns a GC
configuration parameter. This value is stored on the client
and can differ between clients. Therefore, we need to fetch
and cache this value in the VMInfo on the server.
Fixes: #12934

Use client's object alignment value on the JITServer

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit fixes two coding errors with getLoadOpCodeFromDataType():
- Use different opcodes in the case of signed Int8.
- Correct the order of arguments.
Fixes: #12831

AArch64: Fix getLoadOpCodeFromDataType()

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/CHTable.cpp
runtime/compiler/env/JITServerCHTable.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/InterpreterEmulator.cpp
runtime/compiler/optimizer/InterpreterEmulator.hpp
runtime/compiler/optimizer/J9Inliner.cpp
runtime/compiler/optimizer/J9Inliner.hpp
runtime/compiler/runtime/codertinit.cpp
runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
runtime/jcl/common/jclcinit.c
runtime/oti/j9nonbuilder.h

This series inlines `MutableCallSite` targets when the MCS is used directly via `invokedynamic`. Inlining for MCS dynamic invoker handles will be implemented afterward.
The bulk of the inlining logic is in the last commit, but there are a few additional commits to help set the stage:
- Deduplicate logic to read `MutableCallSite.epoch` (so that it can be changed in one place)
- Forget stale call methods in `InterpreterEmulator` (cleanup)
- Remember the pre-refinement method in `InterpreterEmulator` (needed to find the receiver of refined `invokeBasic()` calls and create `TR_J9MutableCallSite`, and will also be used in a later PR to recognize `invokeBasic()` in `getReturnValue()`)
- Remove dereference that crashes in out-of-process compilation (in a path that is now exercised due to MCS …

Inline MutableCallSite targets with LambdaForm

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/compile/J9SymbolReferenceTable.hpp
runtime/compiler/ilgen/Walker.cpp
runtime/oti/j9nonbuilder.h

This changeset includes the following:
* Add functionality to lookup/create j9VMThreadFloatTemp1Symbol
* Insert trees to store num args to VMThread.floatTemp1 for
linkToStatic/Special
* Document this added use case of the floatTemp1 field
Required for: #12522 
Depends: eclipse/omr#6045

 Store ROM Method arg slot count in floatTemp1 for linkToStatic

---

runtime/codert_vm/module.xml

Required for pre-CMake UMA builds.

Exclude building riscvnathelp.m4 within codert_vm/modules.xml

---

test/functional/Java9andUp/playlist.xml
test/functional/cmdLineTests/modularityddrtests/exclude.xml
test/functional/cmdLineTests/modularityddrtests/playlist.xml

- Update StaticAccessChecks-IllegalAccessPermit versions from 9+ to 11 and 16 due to JEP 403
- Add StaticAccessChecks-IllegalAccessDenyWithPermit for 17+, disabled now until new release with JEP 403
- Exclude tests in modularityddrtests that use or depend on illegal-access=permit DUMPFILE
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/12727 https://github.com/eclipse-openj9/openj9/issues/12890
[skip ci]

Exclude tests due to JEP 403

---

buildenv/jenkins/common/build.groovy

On a Docker based compile, SCM checkout runs
using git from the host. Git checkout uses Git
from the container. This seems to produce an
incompatilibilty between the git metadata. When
'git checkout' runs (in the container) it can't
seem to process correctly and fails "fatal: reference
is not a tree: <sha>". Having the scm step checkout
directly to the SHA if it is passed should eliminate
the need to run the extra checkout. Note that
OPENJDK_SHA should be passed in 100% of the builds.
It would only not be passed if someone was launching
a build job direcly without filling in the param.
Test cases
- OpenJ9 PR
- OpenJDK PR
- OpenJ9 PR depends OpenJDK PR
- Non-PR build with OpenJDK_SHA passed
- Non-PR build without OPENJDK_SHA passed
Fixes #12881
Signed-off-by: Adam Brousseau …

Checkout directly to OPENJSK_SHA if passed

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/optimizer/InterpreterEmulator.cpp
runtime/compiler/optimizer/J9TransformUtil.cpp
runtime/compiler/optimizer/J9TransformUtil.hpp

Implement Stable field folding in JIT
- recognize fileds annotated as Stable
- only handle non-array elements for now
Fixes https://github.com/eclipse-openj9/openj9/issues/12710
Depends on https://github.com/eclipse/omr/pull/6054

Implement  Stable field folding

---

runtime/oti/vm_api.h
runtime/vm/KeyHashTable.c
runtime/vm/classallocation.c
runtime/vm/createramclass.cpp

Ensure that both the package ID and the class defining it are in the
class loader hash table, or that neither are.
[ci skip]

 Ensure consistency in the ClassLoader hash table 

---

test/functional/Jsr292/src/com/ibm/j9/jsr292/api/MethodHandleAPI_foldArguments.java

The change is to replace this internal method with the method
existing in both OpenJ9 and OpenJDK in verifying the required
functionalities.
Fixes: #12927

Replace foldArguments with foldArgumentsWithCombiner in tests

---

runtime/oti/vm_api.h
runtime/vm/KeyHashTable.c
runtime/vm/classallocation.c
runtime/vm/createramclass.cpp

Reverts eclipse-openj9/openj9#12871
This is causing failures like https://github.com/eclipse-openj9/openj9/pull/12871#issuecomment-861448876

Revert " Ensure consistency in the ClassLoader hash table "

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Use store-release instruction for monitor exit and remove memory barrier.
Removing memory barrier allows loads/stores after monitor exit to be reordered before monitor exit, which is a permitted behavior by JMM.
Use xzr to store 0 into lockword instead of a temporary register.

AArch64: Use store-release for monitor exit

---

runtime/compiler/runtime/ClassUnloadAssumption.cpp

The mark-and-sweep assumption reclamation algorithm will free
marked for detach entries in
`TR_RuntimeAssumptionTable::reclaimMarkedAssumptionsFromRAT`.
The method iterates through the runtime assumption table and
frees all entries that are marked for detach, after dequeing
them from the per-compilation runtime assumption list.
However, sentinel runtime assumptions (i.e. heads of assumption lists)
are detached but never freed, since they are not part of the RAT.
The fix to this memory leak is to delete sentinels the moment they
are dequeued from the runtime assumption list.

Fix a memory leak in runtime assumption list

---

runtime/compiler/x/amd64/codegen/AMD64J9SystemLinkage.cpp
runtime/compiler/x/amd64/codegen/AMD64JNILinkage.cpp
runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp
runtime/compiler/x/codegen/AllocPrefetchSnippet.cpp
runtime/compiler/x/codegen/CallSnippet.cpp
runtime/compiler/x/codegen/J9CodeGenerator.cpp
runtime/compiler/x/codegen/J9LinkageUtils.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/J9UnresolvedDataSnippet.cpp
runtime/compiler/x/codegen/X86HelperLinkage.cpp
runtime/compiler/x/codegen/X86PrivateLinkage.cpp
runtime/compiler/x/codegen/X86Recompilation.cpp
runtime/compiler/x/i386/codegen/IA32J9SystemLinkage.cpp
runtime/compiler/x/i386/codegen/IA32JNILinkage.cpp
runtime/compiler/x/i386/codegen/IA32PrivateLinkage.cpp

This is a continuation of #12729 which eliminates the ".temp.defines" file and finishes off moving all the x86 instruction mnemonics inside the `TR::InstOpCode` class. In addition we remove some x86 defined pseudo-instructions in favour of the cross platform ones. See each commit comment to understand what was done. Each individual commit builds on its own.
Depends on eclipse/omr#6061

Move all x86 mnemonics into the TR::InstOpCode class

---

runtime/compiler/arm/codegen/ARMJNILinkage.cpp
runtime/compiler/arm/codegen/ARMPrivateLinkage.cpp
runtime/compiler/arm/codegen/ARMRecompilation.cpp
runtime/compiler/arm/codegen/CallSnippet.cpp
runtime/compiler/arm/codegen/Instruction.hpp
runtime/compiler/arm/codegen/J9ARMEvaluator.cpp
runtime/compiler/arm/codegen/J9ARMSnippet.cpp
runtime/compiler/arm/codegen/J9CodeGenerator.cpp
runtime/compiler/arm/codegen/J9TreeEvaluator.cpp

This is a continuation of #12897 which eliminates the ".temp.defines" file and finishes off moving all the ARM instruction mnemonics inside the TR::InstOpCode class. See each commit comment to understand what was done. Each individual commit builds on its own.
Depends on eclipse/omr#6070

Move all ARM mnemonics into the TR::InstOpCode class

---

test/functional/Jsr292/src/com/ibm/j9/jsr292/api/MethodHandleAPI_foldArguments.java

The test is updated to set the expected internal method
based on the java version.
Fixes: #12980

Select the correct internal method for foldArguments

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/env/JITServerPersistentCHTable.cpp
runtime/compiler/env/JITServerPersistentCHTable.hpp
runtime/compiler/runtime/RuntimeAssumptions.cpp
runtime/compiler/runtime/RuntimeAssumptions.hpp

Having more usable compilation threads at the JIT client than the current maximum of 7 improves performance when the network connection to the JITServer has high latency. The user can now specify up to 15 threads with `-XcompilationThreads<N>`, while the default is unchanged.

Increase maximum number of JIT client compilation threads

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit implements guarded devirtualization in ARM64PrivateLinkage.
Most of logic are from ppc's implementation.

AArch64: Implement guarded devirtualization

---

runtime/compiler/aarch64/runtime/Recomp.cpp

This commit changes a printf format string, to suppress a compiler
warning.

AArch64: Suppress a compiler warning

---

runtime/jilgen/CMakeLists.txt

CMake: apply OMR_EXE_LAUNCHER when launching jilgen

---

runtime/codert_vm/xnathelp.m4
runtime/oti/j9nonbuilder.h
runtime/oti/xhelpers.m4

See issue for details.
Fixes: #12585
[ci skip]

Preserve entire contents of XMM registers across helper calls on X

---

buildenv/jenkins/jobs/infrastructure/buildJDKTimeoutHandler.groovy

Old job https://ci.adoptopenjdk.net/view/Dependencies/job/jtreg/lastSuccessfulBuild/artifact/jtreg-4.2.0-tip.tar.gz does not exist anymore. Update to use the new job url.
Fixes: https://github.com/eclipse-openj9/openj9/issues/12906

Update to use Adopt job url for downloading jtreg

---

runtime/vm/exceptiondescribe.c

Always make sure the ramClass is the correct one in iterateStackTrace().
We probe the bootstrap class loader and then appClass loader to find the
corresponding ramClass of a romClass. However, the correct class could
be loaded by another class loader. In this case, the returned ramClass
is not correct, which should not be used. 
Fixes #12915

Add additional check for romClass in iterateStackTrace()

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/runtime/ClassUnloadAssumption.cpp
runtime/compiler/runtime/MetaData.cpp
runtime/compiler/runtime/RelocationRuntime.cpp

`TR_RuntimeAssumptionTable::reclaimAssumptions` marks assumptions
for detach and sets the head of the assumption list to NULL.
However, it has an issue where it does not guarantee that
`metaData->runtimeAssumptionList` will be set to NULL,
since the sentinel double pointer passed to it can be the address
of the list in the compilation object, instead of in the metadata.
It's also not always the case that the method is passed metadata
pointer when it exists.
This commit sets `_owningMetadata` attribute of a sentinel runtime
assumption when metadata is created.
At reclamation, we use the owning metadata to reset the assumption
list pointer, if metadata pointer is not directly available

Fix a bug in assumption reclamation

---

buildenv/jenkins/jobs/infrastructure/buildJDKTimeoutHandler.groovy

Update Build JDK Timeout Handler job to use jtreg5.1-b01.tar.gz

---

jcl/src/java.base/share/classes/java/lang/Access.java

Removed `JAVA_SPEC_VERSION >= 18` `JPP` decoration to make it available for `JDK17` as well.
`JDK17` builds w/ this PR, and produces `-version` output:
```
OpenJDK Runtime Environment (build 17-internal+0-adhoc.fengjcaibmcom.openj9-openjdk-jdk17)
Eclipse OpenJ9 VM (build jdk17access-5f07ceea2a, JRE 17 Mac OS X amd64-64-Bit Compressed References 20210618_000000 (JIT enabled, AOT enabled)
OpenJ9   - 5f07ceea2a
OMR      - b7eb96336
JCL      - 3b15ac03333 based on jdk-17+27)
```
closes https://github.com/eclipse-openj9/openj9/issues/13006

JDK17 requires JavaLangAccess.exit(status) implementation

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.hpp

Implement static PICs for virtual and interface call on aarch64.
This implementation is largely based on ppc's one.

AArch64: Implement static PICs for virtual and interface call

---

runtime/vm/exceptiondescribe.c

Always make sure the ramClass is the correct one in iterateStackTrace().
We probe the bootstrap class loader and then appClass loader to find the
corresponding ramClass of a romClass. However, the correct class could
be loaded by another class loader. In this case, the returned ramClass
is not correct, which should not be used. 
Fixes #12915
Port of https://github.com/eclipse-openj9/openj9/pull/12994 for the 0.27 release.

(v0.27.0)Add additional check for romClass in iterateStackTrace()

---

runtime/compiler/runtime/MetaData.cpp
runtime/oti/j9nonbuilder.h

When `TR_MethodMetaData` is created on the server, set a flag
to indicate that the compilation was done remotely.
This is useful for diagnostic purposes.
Closes: #12921

Add a flag to method metadata indicating a remote compilation

---

runtime/gc_base/accessBarrier.cpp
runtime/gc_base/gc_internal.h
runtime/gc_realtime/RealtimeAccessBarrier.cpp
runtime/oti/j9nonbuilder.h

The SIGQUIT handler always uses NULL for the current thread, which leads
to a crash in the blockingEnterObject read. Update this to work when
currentThread is NULL.
Fixes: #12851
Cherry pick https://github.com/eclipse-openj9/openj9/pull/12903 for the 0.27 release.

(0.27) Allow NULL currentThread in J9VMThread blockingEnterObject read

---

runtime/compiler/runtime/J9Profiler.hpp

The JIT no longer value profiles arraycopy lengths and I believe it is due to a subtle bug introduced when value profiling with JProfiling was first implemented.
Arraycopy length profiling was designed to not occur in the first compilation of a method, and checks a flag (`initialCompilation`) set in the `TR_RecompilationProfiler` object to determine that.   This flag is always `true`, however, due to what I believe is a bug during initialization of the `TR_RecompilationProfiler` class.  The flag is set in [1] and never changed.
However, I don't think this was intended.  The API prior to JProfiling being introduced looked like [2].  The flag `initialCompilation` was actually the name of an optional parameter to `TR_ValueProfiler` (defaults to `false`) in the original code that is simply …

Fix TR_ValueProfiler initialization to allow arraycopy length profiling

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/RomClassWalker.java
runtime/util/romclasswalk.c

Function `allSlotsInBytecodesDo` in ROM class walk
code walks bytecodes in a method, calling a slot callback
function for each bytecode argument.
The bytecode iterator in this function and identical function
in ddr code are missing handlers for some bytecodes, resulting
in pc being incremented by an incorrect amount.
Missing bytecode handlers:
- `JBinvokedynamic`
- `JBinvokeinterface`
- `JBdefaultvalue`
- `JBwithfield`

Add missing bytecodes to ROM class walk

---

runtime/gc_vlhgc/SweepHeapSectioningVLHGC.cpp
runtime/gc_vlhgc/SweepPoolManagerVLHGC.cpp
runtime/gc_vlhgc/SweepPoolManagerVLHGC.hpp

Avoid callback check and retrieve minimum free entry size from
memorypool every time.
for Balanced GC case:
minimum free entry size = max(memorypool.minimumFreeEntrySize,
minimumFreeSize for Survivor).
depends on https://github.com/eclipse/omr/pull/6081

Simplify the logic for identifying minimum free size for sweeping

---

runtime/compiler/CMakeLists.txt

- Enable compressed aot zLinux in adddition to z/OS.
- Link against system zlib on z/OS.
- Link against j9zlib for z/Linux.
- z/OS: move system zlib include path so it won't get clobbered when we
specify -qnosearch.

CMake: rework compressed AOT data in the jit

---

runtime/bcutil/defineclass.c
runtime/oti/j9nonbuilder.h

Add explicit assignment to workaround `JDK8` `zOS` `64bit` compiler issue.
Fixes an internal failure `RTC 145584`.
Related https://github.com/eclipse-openj9/openj9/pull/12935

Add explicit assignment to workaround JDK8 zOS 64bit compiler issue

---

runtime/oti/vm_api.h
runtime/vm/KeyHashTable.c
runtime/vm/classallocation.c
runtime/vm/createramclass.cpp

Ensure that both the package ID and the class defining it are in the
class loader hash table, or that neither are.
[ci skip]

Ensure consistency in the ClassLoader hash table

---

test/functional/Java9andUp/playlist.xml
test/functional/Java9andUp/testUnreflect.xml

Related: #11935 & #12779 & https://github.com/ibmruntimes/openj9-openjdk-jdk16/pull/29

Add ExcludeTestAnnotationTransformer listener to testUnreflect

---

test/functional/cmdLineTests/lockWordAlignment/build.xml

delete getDependentLibs in lockWordAlignment build.xml

---

runtime/compiler/aarch64/runtime/CMakeLists.txt
runtime/compiler/build/files/host/aarch64.mk
runtime/compiler/runtime/Runtime.cpp

This commit adds helper entries for arraycopy for AArch64.

AArch64: Add arraycopy helpers

---

runtime/vm/createramclass.cpp

1. Set J9ClassHasIdentity into array ramClass classFlags
2. Add the missing J9ClassRequiresPrePadding in the documentation of
ramClass classFlags. 

Set J9ClassHasIdentity for arrays

---

test/TestConfig/resources/excludes/feature_ojdkmh_exclude.txt

Re-enable `Test_AccessController:test_doPrivilegedFrameStackWalking`
Note: https://github.com/eclipse-openj9/openj9/pull/12716/ enabled stackwalking to find `InjectedInvoker` frame which carries the actual caller `protectiondomain` just like `OpenJ9` `SecurityFrame`. A sample stacktrace looks like:
```
java.security.AccessControlException: Access denied ("java.util.PropertyPermission" "user.home" "read")
at java.base/java.security.AccessController.throwACE(AccessController.java:176)
at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:238)
at java.base/java.security.AccessController.checkPermission(AccessController.java:385)
at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:408)
at …
```

Re-enable Test_AccessController:test_doPrivilegedFrameStackWalking

---

runtime/compiler/control/J9Options.cpp

Define privatePortLibrary in preProcessMmf(..) for
defined(TR_TARGET_64BIT) && defined(J9ZOS390).

Fix compilation error in preProcessMmf

---

runtime/compiler/z/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.hpp

Many extern evaluators declarations in z/J9CodeGenerator.cpp are defined in OMR. These evaluators should be in OpenJ9 instead. As part of this commit, all extern declarations of evaluators are removed from J9CodeGenerator.cpp and function definitions are imported over from OMR where applicable.
Closes: #12911

Move java specific evaluators from OMR

---

runtime/compiler/optimizer/EstimateCodeSize.cpp
runtime/compiler/optimizer/EstimateCodeSize.hpp
runtime/compiler/optimizer/J9EstimateCodeSize.cpp

Replace `anerrno` magic numbers with `EcsCleanupErrorStates`
enum values to identify the error location during code
size estimation.
Closes: #8664

Cleanup EstimateCodeSize magic numbers

---

runtime/compiler/control/J9Options.cpp

It will trigger a warning and compilation will fail once warnings are disallowed.

Remove unused declaration of OMRPORTLIB

---

runtime/compiler/aarch64/codegen/J9InstructionDelegate.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Instructions which do not trigger NPE (such as `add` or `prfm`) must not be
marked as an implicit exception point.
For instruction sequence for read barrier, we need to manually
set a load instruction as an implicit exception point.

AArch64: Set correct instruction as implicit exception point

---

buildenv/jenkins/common/pipeline-functions.groovy

I can't think of a reason the server would be set to repo.
I think this never surfaced before now because the name and
repo were always the same. Looking at the original commit I'd
say it was a mistake.

Fix typo in Artifactory cleanup

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
runtime/oti/VMHelpers.hpp
runtime/oti/j9nonbuilder.h

This change fixes: 
`java/lang/invoke/unreflect/UnreflectTest.java`
`java/lang/invoke/VarHandles/accessibility/TestFieldLookupAccessibility.java`
in https://github.com/ibmruntimes/openj9-openjdk-jdk16/pull/29

Add MN_TRUSTED_FINAL to MemberName flags

---

runtime/ddr/j9ddr.h
runtime/jcl/common/jclexception.c
runtime/jvmti/jvmtiCapability.c
runtime/oti/j9comp.h
runtime/oti/jvminit.h
runtime/vm/exceptiondescribe.c
runtime/vm/vmprops.c

Consolidate macro `J9_STR_`/`J9_STR` into `j9comp.h`;
Format refactoring within the methods affected.
close #13048 

Replace hard-code JAVA_MODULE_VERSION with JAVA_SPEC_VERSION_STRING

---

test/functional/JIT_Test/playlist.xml

The new test added via
https://github.com/eclipse-openj9/openj9/pull/12905 uses the
-XXgc:forcedShiftingCompressionAmount option to force shifting to 1, 2,
3, 4, but doesn't set -Xmx. The default -Xmx is 25% of the available
memory up to 25G. The default value on some machines may be too big for
smaller shift values.
Fixes https://github.com/eclipse-openj9/openj9/issues/12947
Tested this test only change via grinder, just one platform but that should be sufficient.
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/87/

Update jit_jitt_array_compress unit test to set -Xmx

---

test/functional/JIT_Test/playlist.xml

The new test added via
https://github.com/eclipse-openj9/openj9/pull/12905 uses the
-XXgc:forcedShiftingCompressionAmount option to force shifting to 1, 2,
3, 4, but doesn't set -Xmx. The default -Xmx is 25% of the available
memory up to 25G. The default value on some machines may be too big for
smaller shift values.
Issue https://github.com/eclipse-openj9/openj9/issues/12947
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/13090 for the 0.27 release.

(0.27.0) Update jit_jitt_array_compress unit test to set -Xmx

---

runtime/compiler/aarch64/codegen/J9InstructionDelegate.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Instructions which do not trigger NPE (such as `add` or `prfm`) must not be
marked as an implicit exception point.
For instruction sequence for read barrier, we need to manually
set a load instruction as an implicit exception point.
Master PR: https://github.com/eclipse-openj9/openj9/pull/13047

(0.27.0) AArch64: Set correct instruction as implicit exception point

---

runtime/compiler/control/JITClientCompilationThread.cpp

The option `TR_JITServerFollowRemoteCompileWithLocalCompile`
should be retrieved from a compilation object, instead of command line options.
Otherwise, the option is ignored when it's limited to
a single compilation/set of compilations.
VM access should be released before performing a local compile,
to avoid deadlocks during compilation,
e.g. in `TR_J9VMBase::compilationShouldBeInterrupted`.

Fix follow up local compilations on JITServer client

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/env/J9ClassEnv.hpp
runtime/compiler/optimizer/J9ValuePropagation.cpp

`J9ClassIsValueType` is mutually exclusive to `J9ClassHasIdentity`.  If the class implements `IdentityInterface`, it is not a value type.
Related to #12581

Add API to check J9ClassHasIdentity class flag

---

test/functional/Java8andUp/src/org/openj9/test/vmcheck/TestLoadingClassesFromJarfile.java

Fix testvmcheck failures from ContainsRuntimeAnnotationTest

---

runtime/oti/jvminit.h
runtime/vm/vmprops.c

`--enable-native-access` option is converted to system properties `jdk.module.enable.native.access.*` [1].
closes https://github.com/eclipse-openj9/openj9/issues/13088
This fixes the error like `JVMJ9VM007E Command-line option unrecognised: --enable-native-access=ALL-UNNAMED`.
[1] https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/acf5b4f41829774008033d189c88272983297b2d/src/java.base/share/classes/jdk/internal/module/ModuleBootstrap.java#L804-L808

JDK17+ recognize --enable-native-access option

---

runtime/compiler/build/toolcfg/gnu/common.mk

Set the `SONAME` of the JIT shared library in UMA builds as it is done in cmake builds.
This enables inclusion of that library in the archive produced by `jpackcore` (see #13034).

Define Linux SONAME for JIT shared library

---

buildenv/jenkins/common/build.groovy

A second call is only needed if a `pull` was required.

Remove unnecessary repeated call to get_docker_image_id()

---

runtime/cmake/caches/zos_390-64_mxdptrs.cmake

It doesn't yet work to build mxdptrs for z/OS, but I think this file is fine.
Not sure how this can happen since the version is hard coded.
```
19:07:16  Compiling 4 files for BUILD_JIGSAW_TOOLS
19:07:19  JVMJ9VM082E Unable to switch to IFA processor - issue "extattr +a libj9ifa29.so"
19:07:19  JVMJ9VM007E Command-line option unrecognised: --add-exports=java.base/jdk.internal.module=ALL-UNNAMED
19:07:19  Error: Could not create the Java Virtual Machine.
19:07:19  Error: A fatal exception has occurred. Program will exit.
19:07:20  make[3]: *** [/u/jenkins/workspace/Build_JDK11_s390x_zos_Personal/build/zos-s390x-normal-server-release/jdk/_packages_attribute.done] Error 1
19:07:20  ExplodedImageOptimize.gmk:40: recipe for target '/u/jenkins/workspace/Build_JDK11_s390x_zos_Personal/build/zos-s …
```

Add zos_390-64-mxdptrs.cmake

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/env/J9PersistentInfo.hpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/oti/j9nonbuilder.h
runtime/rasdump/javadump.cpp

This commit adds a new command line option `-XX:+LogJITServerConns`
which enables the newly added verbose option `TR_VerboseJITServerConns`.
The option can be enabled on both server and client.
When enabled, it logs connections/disconnections between server and client.
This commit also adds UID for the server. The client stores the latest
server UID to determine when a connection to a new server occurs.
Closes: #13055 
Depends on: eclipse/omr/pull/6090

Add an option to log JITServer connections

---

buildenv/jenkins/common/build.groovy

`make all` is broken on z/OS. Recent experiments show that it is
only the javadoc generation that is failing builds triggered by
`make all`. While we investigate the reasons for that, I've
proposed that we disable javadoc generation and start using
`make all` to build on z/OS.
Signed-off-by: Pushkar N Kulkarni <pushkar.nk@in.ibm.com>

Enable `make all` on z/OS Jenkins builds

---

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/AttachHandler.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/CommonDirectory.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/FileLock.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/WaitLoop.java
jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9AttachProvider.java
jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9VirtualMachine.java
test/functional/Java8andUp/src/org/openj9/test/fileLock/NativeFileLock.java

Ensure `lockFileRAF.close()` is called even there is an exception during `lockObject.release()`;
Reduce some timeout for error recovery;
Add more message logs. (`IPC.logMessage()` checks `isLoggingEnabled()` internally).
Note: this reduces the worst delay from up to 18min to ~1min in a customer use case.

Fix AttachAPI long delay case

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/codegen/J9CodeGenerator.hpp
runtime/compiler/z/codegen/ReduceSynchronizedFieldLoad.cpp

`isMonitorValueType` has been replaced by `isMonitorValueBasedOrValueType`. `isMonitorValueType` is no longer required. 

Remove isMonitorValueType

---

runtime/vm/jvminit.c

Given the new project AIX system target, it is safe to assume the processor is at least POWER7 and there's no need to disable HW prefetch by default.

Remove disabling HW Prefetch by default for AIX

---

test/functional/cmdLineTests/gcRegressionTests/gcRegressionTests.xml
test/functional/cmdLineTests/gcRegressionTests/gcRegressionTests_excludes.xml

Test cases cover when output filename from VerboseGC
contains string format specifiers like %c %s %i.
Signed-off-by: Enson Guo <enson.guo@ibm.com>

[Test] GC Verbose filename with format specifiers

---

test/functional/cmdLineTests/dscr/dscr.xml

Following the changes in #13136, this commit remove the "Disabling Hardware Prefetch by default" test. 
Given there is no default call to `setHWPrefetch()`, there's no trace output to compare with for a default behaviour test.

Remove the default HW prefetch test for AIX following the change #13136

---

test/functional/cmdLineTests/gcRegressionTests/gcRegressionTests.xml
test/functional/cmdLineTests/gcRegressionTests/gcRegressionTests_excludes.xml

Comment out GC Regression Tests introduced in https://github.com/eclipse-openj9/openj9/pull/12794
These tests are not being excluded as intended and as a result are causing failures.

Exclude New Problematic GC (Verbose) Regression Tests

---

runtime/util/annhelp.c
runtime/util/vmutil.tdf
test/functional/Java8andUp/src_110_up/org/openj9/test/annotation/ContainsRuntimeAnnotationTest.java
test/functional/Java8andUp/src_80/org/openj9/test/annotation/ContainsRuntimeAnnotationTest.java

findRuntimeVisibleAnnotation did not skip any type of annotation member
correctly, now it handles primitives, classes, enums, arrays, and nested
annotations.
- Modified tests to test skipping the members
Fixes: #13115

Allow findRuntimeVisibleAnnotation to correctly skip annotation members

---

runtime/vm/resolvesupport.cpp

VH polymorphic methods have special handling in
MethodHandleNatives.linkMethodHandleConstant()
and doesn't require CP entry to be resolved
Related: #12539, #13094

Skip VH polymorphic method when resolving MH ref

---

runtime/vm/jvminit.c

Delay call to `memset()` until validating pointer; see https://github.com/eclipse-openj9/openj9/pull/13113#discussion_r667899631.

Avoid using NULL pointer

---

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
jcl/src/java.base/share/classes/java/lang/ClassLoader.java
jcl/src/java.base/share/classes/java/lang/System.java
test/functional/Java8andUp/src/org/openj9/test/support/Support_Exec.java

Add `System.initialErr` to match RI behaviours;
Add/update `warning`/`error` `SecurityManager` messages;
Adjust the test to ignore warning messages in `stderr`.
Note: 
1. The warnings are always printed to the original `System.err` and will not be swallowed [1];
2. `@Deprecated(since="17", forRemoval=true)` is decorated with `OPENJDK_METHODHANDLES` to avoid compilation warning as error in `openj9` branch (`openj9-staging` branch has latest openjdk code to suppress the warning);
3. `K0B00` exception message change wasn't decorated with `JAVA_SPEC_VERSION >= 17` since it doesn't affect `JDK11` and no more `JDK16` release build.
[1] https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/96df588a3eef5a6d1082ade6d11d632c24f9f4be/test/jdk/java/lang/System/SecurityManagerWarnings.java#L73-L75 …

Add JDK17+ SecurityManager warning messages

---

runtime/vm/createramclass.cpp

When GCing after failing to add to the classloader hashtable, the class
object was not being preserved, resulting in the GC collecting the
object.
[ci skip]

Preserve class object across GC

---

runtime/jit_vm/cthelpers.cpp
runtime/oti/j9nonbuilder.h
runtime/oti/j9protos.h
runtime/oti/util_api.h
runtime/tests/annotationtests/CMakeLists.txt
runtime/tests/annotationtests/annhelp_tests.c
runtime/tests/annotationtests/module.xml
runtime/util/annhelp.c
runtime/util/vmutil.tdf
runtime/vm/intfunc.c
test/functional/Java8andUp/src_110_up/org/openj9/test/annotation/ContainsRuntimeAnnotationTest.java
test/functional/Java8andUp/src_80/org/openj9/test/annotation/ContainsRuntimeAnnotationTest.java

Helpers to detect `@ForceInline` and `@IntrinsicCandidate`, general
helper `methodContainsRuntimeAnnotation`
Fixes: #11993

Add jit ct helpers to detect method annotations

---

runtime/util/vmutil.tdf

New tracepoints must be added at the end. This fixes compatibility with the 0.27.0 and earlier releases.

Fix tracepoint additions

---

test/functional/JIT_Test/playlist.xml
test/functional/JIT_Test/src/jit/test/tr/BNDCHKSimplify/BNDCHKSimplifyTest.java
test/functional/JIT_Test/testng.xml

Similar pattern to BNDCHK but with different exception is simplified by
simplifyBoundCheckWithThrowException. This commit adds some test
cases for positive and negative situation for the simplifier.
Signed-off-by: Mohammad Nazmul Alam <mohammad.nazmul.alam@ibm.com>

Add unit test for simplifyBoundCheckWithThrowException

---

runtime/compiler/env/J9VMMethodEnv.cpp
runtime/compiler/env/J9VMMethodEnv.hpp
runtime/compiler/env/VMJ9.cpp

This commit enables the optimization by adding a new
method `J9::VMMethodEnv::isFrameIteratorSkipMethod` that
checks whether a ROM method has `J9AccMethodFrameIteratorSkip`
flag set.
Closes: #13098

Enable getCallerClass optimization for JITServer

---

doc/release-notes/0.27/0.27.md

Updated 0.27.md to indicate that Global lock reservation is now enabled by
default on Power and that the -XX:-GlobalLockReservation option can be used to
restore older behavior.

Document Global Lock Reservtion now on by default

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/optimizer/InterpreterEmulator.cpp
runtime/compiler/optimizer/J9TransformUtil.cpp
runtime/compiler/optimizer/J9TransformUtil.hpp

- recognize stable fields using jitIsFieldStable() VM helper
- make canDereferenceAtCompileTimeWithFieldSymbol() return true if field is stable
- check if value can be actually folded using avoidFoldingInstanceField()
- disable using disableStableAnnotations -Xjit option

Fold Stable fields

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.hpp

PR #13178 introduced a new front-end query: `TR_J9VMBase::isStable()`.
This commit adds a JITServer version of this method, which also requires
adding a new message type - `VM_isStable`.
Closes: #12953

Implement isStable() query for JITServer

---

runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/compile/J9Compilation.hpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/x/codegen/J9CodeGenerator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/env/J9CPU.cpp
runtime/gc_modron_startup/mminit.cpp

If the JVM Is in CRIU mode, then the JIT should be limited to the same
processor features as those used in Portable AOT mode. This is because,
the restore run may not be on the same machine as the one that created
the snapshot; thus the JIT code must be portable.
Depends on https://github.com/eclipse/omr/pull/6091
Closes https://github.com/eclipse-openj9/openj9/issues/12482

Use Portable AOT setting for JIT compiles in CRIU mode

---

runtime/vm/classsupport.c

As part of running Kafka traffic we hit a condition where both the Kerberos servers and Kafka broker go down and the client continues to send traffic over a long running connection.  An exception is thrown:
org.apache.kafka.common.errors.SaslAuthenticationException: Failed to configure SaslClientAuthenticator
Caused by: org.apache.kafka.common.KafkaException: Principal could not be determined from Subject, this may be a transient failure due to Kerberos re-login
Diagnostics are showing at least a native memory leak for some allocation which contains the following string (on the order of 10k's times):
"org.apache.kafka.common.network.SaslChannelBuilder$$Lambda$7/0x0000000000000000"
Further analysis shows the allocation coming from copyStringToUTF8WithMemAlloc called from …

Memory leak in internalFindClassString

---

runtime/gc_vlhgc/SweepHeapSectioningVLHGC.cpp
runtime/gc_vlhgc/SweepHeapSectioningVLHGC.hpp

Avoid logic duplication between SweepHeapSectioning subclasses
depends on: https://github.com/eclipse/omr/pull/6089

Share common logic in SweepHeapSectioning base class

---

test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-4.xml
test/functional/cmdLineTests/xlogTests/xlog.xml

Note: this is an addition of https://github.com/eclipse-openj9/openj9/pull/13156 to fix test failures such as following:
`Test_openjdk8_j9_extended.functional_ppc64le_linux_testList_0/83/`
```
[2021-07-20T03:49:28.409Z] Testing: Verify whether VM successfully runs in read-only shared cache with testBadBuildID and nonfatal option specified
"/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_testList_0/openjdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xint -Xshareclasses:testBadBuildID,verbose,readonly,nonfatal -version
[2021-07-20T03:49:30.374Z] Test result: FAILED
[2021-07-20T03:49:30.374Z]  [ERR] semeru version "1.8.0_302-beta"
[2021-07-20T03:49:30.374Z]  [ERR] Semeru Runtime Environment (build 1.8.0_302-beta-202107200233-b07) …
```

Recognize new product name Semeru

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/runtime/JITClientSession.hpp

There is a number of GC-related front-end queries that
were not implemented for JITServer, which was causing
a number of bugs in tests running metronome GC policy.
All of the new queries access information initialized at
JVM startup, so we cache it inside server's VM info.

Implement missing front-end queries for JITServer

---

runtime/compiler/runtime/JITServerSharedROMClassCache.cpp

Allocate the array of JITServer ROM cache partition monitors
by invoking allocator directly, instead of using operator new[].
Fixes: #13210

Fix segmentation fault when shareROMClasses is enabled

---

test/functional/Java16andUp/playlist.xml

jdk17 staging branch has changes to classes that this test depends on.
Will revert this change and fix the test when the staging branch is
merged.
Issue: #13195

Exclude CloseScope0 test jdk17 temporarily

---

runtime/include/jvmti.h.m4
runtime/jvmti/jvmtiGeneral.c
runtime/jvmti/jvmtiHook.c
runtime/tests/jvmtitests/agent/agent.c
runtime/tests/jvmtitests/agent/version.c
runtime/tests/jvmtitests/include/jvmti_test.h

`JVMTI_VERSION = 0x30000000 + majorversion * 0x10000 + minorversion (always 0) * 0x100`
Update `jniVersionIsValid()` to accept `JVMTI_VERSION`;
Update references to `JVMTI_VERSION_15`.
Note: `changecom()dnl` is required to generate `#define JVMTI_VERSION (0x30000000 + 16 * 0x10000)` instead of `#define JVMTI_VERSION (0x30000000 + JAVA_SPEC_VERSION * 0x10000)` which won't compile in OpenJDK JCL natives such as `jdk.jdwp.agent/share/native/libjdwp/debugInit.c` where `JAVA_SPEC_VERSION` is not defined.
This fixes AGCT unit testing error:
```
Error: wrong result of a valid call to GetEnv!
JVMJ9TI064E Agent initialization function Agent_OnLoad failed for library AsyncGetCallTraceTest, return code -1
JVMJ9VM015W Initialization error for library j9jvmti29(-3): JVMJ9VM009E J9VMDllMain failed
``` …

Define JVMTI_VERSION dynamically according to JAVA_SPEC_VERSION

---

runtime/include/ibmjvmti.h
runtime/jvmti/jvmtiExtensionMechanism.c
runtime/oti/jvmtiInternal.h

Inlined frames may now be reported using the new frame type `COM_IBM_STACK_FRAME_EXTENDED_INLINED`, which allows agents to distinguish which compiled frames correspond to the root method of a JIT-compiled body and which do not.
For compatibility with any existing agents, this distinction is only made if explicitly requested by the agent via the new stack trace flag `COM_IBM_GET_STACK_TRACE_MARK_INLINED_FRAMES`.

Differentiate inlined frames in extended stack traces for JVMTI agents

---

runtime/rasdump/javadump.cpp

We were seeing random GPFs during javacore generation when processing lock objects.
It looks like some stack variables specifically for lockObjects aren't initialized which could lead to this behavior.
The proposed code is defensive at minimum, and is believed to clear up the failure during javacore generation.  It's also worth noting that in some other paths where lockobjects are declared on the stack are initialized with NULL.

GPF possible while processing lockobjects when generating a javacore

---

doc/build-instructions/Build_Instructions_V11.md
doc/build-instructions/Build_Instructions_V16.md

This commit corrects the paths mentioned for the version 11 and version
16 JDK build.
Signed-off-by: Md. Alvee Noor <mnoor@unb.ca>

JDK Path Update For AArch64 Build Documentation

---

runtime/compiler/optimizer/J9TransformUtil.cpp

It should be safe to fold final statics in these classes and
it's necessary for VectorAPIExpansion

Allow folding final statics in java/lang/Byte,Short..,Double

---

runtime/compiler/net/ClientStream.cpp
runtime/compiler/runtime/Listener.cpp

When server/client create communication streams using SSL they need
to invoke methods of `SSL` objects, such as setting file descriptor
and calling accept/connect.
Change the code to perform this operations on the `SSL` object stored
inside SSL BIO, instead of creating our own `SSL` and then
replacing BIO's object with it.
This fixes a memory leak that was causing crashes.
Closes: #4382

Fix initialization of SSL connections on JITServer

---

buildenv/jenkins/common/build.groovy
buildenv/jenkins/common/variables-functions.groovy
buildenv/jenkins/variables/defaults.yml

* update the download name expected from Adopt API; OpenJDK->semeru
* modify build requirement for aarch64_linux to use docker and an
Adoptium docker container
* set CC/CXX values for specific gcc-7.5 location
* add openjdk_cache directory from the docker host to container

Move Linux aarch64 compiles to Adoptium docker container

---

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp
runtime/compiler/control/rossa.cpp

This commit enables ArrayCopyOpts and primitive arraycopy on AArch64.

AArch64: Enable ArrayCopyOpts and primitive arraycopy

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/env/J9PersistentInfo.hpp

This commit adds a new command-line option
`-XX:[+|-]JITServerLocalAsyncCompiles`.
When enabled, JITServer client will perform downgraded
sync compilations locally.

Add a JITServer option to do cold sync compiles locally

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

The inline script appears to be a legacy feature useful for consumption
by a tool that does not exist anymore.  The dump is just consuming space
in the log file and does not provide any value over other tracing.  Disable
it.

Disable inline script dump

---

runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp

- inside alwaysWorthInlining, check if method was annotated
with ForceInline
- inside tryToInline, check if method was annotated
with ForceInline
- apply to VectorAPI methods only for now

Use ForceInline annotation in JIT

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/env/j9methodServer.hpp

- Change `TR_J9ServerVM::isForceInline()` to return a correct answer.
- Cache whether a method has force inline annotation in server's
resolved method and add a query to access it.

Add JITServer support for ForceInline annotation

---

runtime/compiler/control/J9Options.cpp

This commit replaces JIT command-line option `-Xjit:shareROMClasses`
with `-XX:JITServerShareROMClasses`.
Sharing ROM classes between clients is something that users might
want to configure themselves, so making it an `-XX` option makes more
sense.

Add -XX:JITServerShareROMClasses option to JITServer

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

All floating-point operations are assumed to be strict
See #12759 

Remove precision adjustments from floating-point math

---

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.hpp

This commit implements arraycopyEvaluator() and related functions for
reference arraycopy.

AArch64: Implement reference arraycopy

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/ilgen/Walker.cpp

java/lang/invoke/MethodHandleImpl.profileBoolean() performs some internal profiling
on the boolean parameter value before returning it.  Since the OpenJ9 JIT does not
consume that profiling information the profiling overhead is not necessary and
interferes with inlining decisions..  Eliminate the call and simply replace it with
a reference to the boolean parameter.
Add java/lang/invoke/MethodHandleImpl.isCompileConstant() as a future recognized
method.

Replace MethodHandleImpl.profileBoolean() calls with boolean parameter

---

runtime/compiler/runtime/Trampoline.cpp

Portable-AOT makes some code sequences different from the
expectation of the current CPU type. When that sequence is
patched, different possible scenarios have to be considered.
Otherwise, doing only according to the current CPU type may
run into crashes.
Signed-off-by: Julian <zlwang@ca.ibm.com>

Need to consider Portable-AOT cases during code patching

---

jcl/src/java.management/share/classes/java/lang/management/MemoryType.java

JDKnext builds fail, e.g. [for xLinux](https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_linux_OpenJDK/65/console):
```
02:12:40  === Output from failing command(s) repeated here ===
02:12:40  * For target jdk_modules_java.management__the.java.management_batch:
02:12:40  /home/jenkins/workspace/Build_JDKnext_x86-64_linux_OpenJDK/build/linux-x86_64-server-release/support/j9jcl/java.management/share/classes/java/lang/management/MemoryType.java:25: warning: no initial description
02:12:40   * @since 1.5
02:12:40     ^
02:12:40  error: warnings found and -Werror specified
02:12:40  1 error
02:12:40  1 warning
```

Fix build error due to missing javadoc

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/MethodHandleTransformer.cpp

Populate known object info on nodes based on MethodHandle transformer analysis.
The node information supplements the information on "improved symbol references"
that are refined with known object info.  Storing known object info in symbol
references will eventually be deprecated and moved to nodes.

Improve known object propagation for MethodHandles

---

runtime/nls/j9vm/j9vm.nls
runtime/nls/j9vm/j9vm_ca.nls
runtime/nls/j9vm/j9vm_cs.nls
runtime/nls/j9vm/j9vm_de.nls
runtime/nls/j9vm/j9vm_es.nls
runtime/nls/j9vm/j9vm_fr.nls
runtime/nls/j9vm/j9vm_hu.nls
runtime/nls/j9vm/j9vm_it.nls
runtime/nls/j9vm/j9vm_pl.nls
runtime/nls/j9vm/j9vm_pt_BR.nls
runtime/nls/j9vm/j9vm_ru.nls
runtime/nls/j9vm/j9vm_sk.nls
runtime/nls/j9vm/j9vm_sl.nls
runtime/nls/j9vm/j9vm_tr.nls

Since there is a backslash without the trailing space, you get a message like:
Exception in thread "main"# START NON-TRANSLATABLEjava.lang.OutOfMemoryError: Java heap space
The trailing space was removed by https://github.com/eclipse-openj9/openj9/commit/328c0e433

Restore space at end of J9NLS_VM_STACK_TRACE_EXCEPTION_IN message

---

jcl/src/java.base/share/classes/java/lang/Thread.java
jcl/src/java.base/share/classes/java/lang/ThreadGroup.java
jcl/src/java.base/share/classes/java/security/AccessControlContext.java
jcl/src/java.base/share/classes/java/security/AccessController.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/LoggingMXBeanImpl.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/ThreadMXBeanImpl.java
jcl/src/java.management/share/classes/java/lang/management/RuntimeMXBean.java
jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9AttachProvider.java
jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9VirtualMachine.java
jcl/src/openj9.cuda/share/classes/com/ibm/cuda/Cuda.java
jcl/src/openj9.gpu/share/classes/com/ibm/gpu/CUDAManager.java
jcl/src/openj9.gpu/share/classes/com/ibm/gpu/SortNetwork.java
jcl/src/openj9.gpu/share/classes/com/ibm/gpu/internal/CudaGPUAssistProvider.java

Added `@Deprecated(since="17", forRemoval=true)` annotation:
```
java.lang.Thread.checkAccess();
java.lang.ThreadGroup.checkAccess();
java.security.AccessControlContext;
java.security.AccessController;
```
Also added `@SuppressWarnings("removal")` to avoid warning causing compilation failure when `-Werror` is specified.
This fixes an internal test failure.
Related to https://github.com/eclipse-openj9/openj9/issues/12760

JDK17 - add missed annotations

---

runtime/jvmti/jvmtiExtensionMechanism.c

Newer versions of Clang warns about casting void* to smaller
int types. This results in a build failure on macOS when
warnings are treated as errors.

Fix void-pointer-to-enum-cast warning in Clang

---

runtime/compiler/z/codegen/J9TreeEvaluator.cpp
test/functional/Java8andUp/src/org/openj9/test/com/ibm/jit/Test_JITHelpers.java

- `stringIndexReg` contains the current index into the search string
that we will start the search on
- `maxIndexReg = searchString.length() - patternString.length()`
and this value does not change at all
- `loadLenReg` is the minimum of the number of characters left to load
from the search string or 16. That is `loadLenReg` <= 16.
The problem here is that due to the comparison we are making we break
the assumption that the remaining number of characters we have left to
examine is always greater than or equal to the length of the pattern.
The code snippet being changed has two branches:
- The first branch branches if `stringIndexReg >= maxIndexReg`
- The second branch branches if `stringIndexReg >= searchString.length()`
There are two problems with the first branch. First problem is that …

Fix off-by-one error in String.indexOf acceleration on z15

---

runtime/compiler/z/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp

When specified this envvar will disable intrinsic inlining of the
`java/lang/String.indexOf(String)` API.

Add envvar TR_DisableIndexOfStringIntrinsic

---

jcl/src/java.base/share/classes/java/lang/Class.java

**OJDK test case:** java/lang/invoke/MethodHandles/publicLookup/Driver.java
**Current exception message format:** "Cannot cast class \<A> to class \<B>"
**Expected exception message format:** "Cannot cast \<A> to \<B>"
**Fixes:** #10648

Update exception message to support OJDK test case

---

runtime/compiler/optimizer/InterpreterEmulator.cpp
runtime/compiler/optimizer/InterpreterEmulator.hpp

This allows the inliner to inline through `invokedynamic` call site adapters in cases where the `invokedynamic` bytecode instruction does not belong to the root method.

Create known object prex args for appendices in InterpreterEmulator

---

runtime/jcl/common/java_lang_Class.cpp

Fixes warnings treated as errors in
* https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-32_windows_OMR/71/
* https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_windows_OMR/72/

Add explicit conversion from jboolean to boolean

---

runtime/compiler/control/J9Options.cpp

This change is motivated by the goal to keep the peak footprint low
when running in virtualized/cloud environments.
The user still has the possibility to change the option to any
desired value with -Xjit:scratchSpaceFactorWhenJSR292Workload=<n>

Reduce scratchSpaceFactorWhenJSR292Workload to 1 in Xtune:virtualized

---

runtime/compiler/build/files/common.mk
runtime/compiler/codegen/CodeGenGPU.cpp
runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/InterpreterEmulator.cpp
runtime/compiler/optimizer/InterpreterEmulator.hpp
runtime/compiler/optimizer/StringBuilderTransformer.cpp
runtime/compiler/runtime/SymbolValidationManager.cpp

This eliminates all instances of the MSVC conditional `snprintf` `#define` (outside of String.cpp), and it deduplicates and in some instances corrects truncation detection logic.
Closes https://github.com/eclipse-openj9/openj9/issues/11884

Change uses of snprintf() to use infra/String.hpp instead

---

runtime/compiler/build/files/common.mk
runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/CMakeLists.txt
runtime/compiler/optimizer/J9Optimizer.cpp
runtime/compiler/optimizer/Optimizations.enum
runtime/compiler/optimizer/VectorAPIExpansion.cpp
runtime/compiler/optimizer/VectorAPIExpansion.hpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp

- create new optimization pass(VectorAPIExpansion)
- add VectorAPIExpansion to the cheap warm optimization strategy
- recognize and scalarize load(), store() and binaryOp() intrinsics
- add -Xjit command line option disableVectorAPIExpansion
- add -Xjit command line option traceVectorAPIExpansion

Implement initial Vector API expansion

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

VectorSupport intrinsic candidates should not be
redefined by the user

Skip HCR guards for VectorSupport intrinsics

---

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/JVMCRIUException.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/JVMCheckpointException.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/RestoreException.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/SystemCheckpointException.java
runtime/criusupport/criusupport.c
runtime/criusupport/j9criu.tdf
runtime/nls/j9cl/j9jcl.nls
runtime/oti/j9nonbuilder.h

`checkpointJVM` should throw exceptions instead of setting return codes.
`JVMCheckpointException`: issue with the JVM
`SystemCheckpointException`: issue with CRIU
`RestoreException`: issue upon CRIU restore
Closes: #13137

Use exceptions instead of return codes for CRIU

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.hpp

overrode the ```TR_J9VMBase::delegatingMethodHandleTarget``` method in ``VMJ9Server.cpp``.
The server will send the message ```VM_delegatingMethodHandleTarget``` to the client with
the ``cwClass``, ``dmhIndex`` and ``knot``. The client will then receive the message and
call the frontend method in ``VMJ9.cpp``.
issue: #13361 
Signed-off-by: Eman Elsabban <eman.elsaban1@gmail.com>

JITServer support for ``TR_J9VMBase::delegatingMethodHandleTarget``

---

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/AttachHandler.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/CommonDirectory.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/TargetDirectory.java
test/functional/Java8andUp/src/org/openj9/test/attachAPI/TestAttachAPI.java

When restarts the docker container, which the java application
does not catch some signals like SIGTERM to shutdown gracefully:
- leave some stale file there.
- it's possible(mostly) that the java application is assigned the same
process ID as before.
As a result, the jps/jstack could not work as expected due to
these stale and conflict VM target files.
Closes: #13010
Signed-off-by: Xia Wood <xiazhongwu@gmail.com>

Cleanup stale directories and files of attach API properly

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp

The OpenJDK method handle code uses `findOrFabricateShadowSymbol`
to create symbol references needed for recognized call transformer.
The routine allows reuse of symbol references for recognized fields
even for non-private fields that belong to different classes.
This works fine in a regular compilation, however in a remote or AOT
compilation, the constant pool of fields reused outside its class
will not be relocated correctly, leading to crashes.
This commit adds a check to disallow reuse of fabricated shadow symbols
in JITServer/AOT compilations.

Do not reuse fabricated symrefs for relocatable compilations

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9Optimizer.cpp

- Add VectorAPIExpansion to optimizer strategies using OMR::IfVectorAPI
- It's experimental but, for now, the pass will run just before GRA
- Add other currently necessary optimizations, also using OMR::IfVectorAPI
- extra LocalCSE pass is needed to improve GlobalVP and is added right after it

Add VectorAPIExpansion to optimization strategies

---

runtime/bcverify/staticverify.c
runtime/nls/cfre/cfrerr.nls

Fix jsr inliner for zero indexes (0.28)
back port of #13412 

Fix jsr inliner for zero indexes (0.28)

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp

This is a v0.28.0 backport of #13425

(0.28.0) Do not reuse fabricated symrefs for relocatable compilations

---

runtime/shared_common/OSCache.cpp
runtime/tests/shared/CacheDirPerm.cpp
runtime/tests/shared/CorruptCacheTest.cpp
runtime/tests/shared/OSCacheTestMmap.cpp
runtime/tests/shared/OSCacheTestSysv.cpp
runtime/tests/shared/SharedCacheAPITest.cpp
test/functional/CacheManagement/src/tests/sharedclasses/TestUtils.java
test/functional/CacheManagement/src/tests/sharedclasses/options/TestPersistentCacheMoving01.java
test/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheJavaAPI.java
test/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheJvmtiAPI.java
test/functional/cmdLineTests/shareClassTests/SCCommandLineOptionTests/SCCOptionTestSetting.mk
test/functional/cmdLineTests/shareClassTests/SCCommandLineOptionTests/exclude_11.xml
test/functional/cmdLineTests/shareClassTests/SCCommandLineOptionTests/playlist.xml

1. Change the shared cache directory to /tmp on z/OS.
2. Update tests.
Depends on eclipse-openj9/openj9-docs#829
Close #13312

Change SCC default directory to /tmp on z/OS

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.hpp

A v0.28.0 backport of PR: #13408
Signed-off-by: Eman Elsabban <eman.elsaban1@gmail.com>

(0.28.0) JITServer support for ```TR_J9VMBase::delegatingMethodHandleTarget```

---

doc/build-instructions/Build_Instructions_V11.md
doc/build-instructions/Build_Instructions_V16.md
doc/build-instructions/Build_Instructions_V8.md

The location of the boot jdk in the documented configure command in the
Build_Instructions_V*.md files  doesn't match the current behaviour of
the mkdocker.sh script. This PR updates the documentation to match the
current locations.
Hopefully this addresses https://github.com/eclipse-openj9/openj9/issues/13459

Update the documentation for new boot jdk location

---

runtime/compiler/env/SystemSegmentProvider.cpp
runtime/compiler/env/SystemSegmentProvider.hpp

This avoids allocation within `J9::SystemSegmentProvider::release()`, which previously would push onto a `std::deque`.
Also, for segments that are larger than default but smaller than the system segment size, skip carving them into default-sized segments. The carving logic was allocating during `release()` for no benefit.
It's desirable to `release()` without allocating because we may already be trying to clean up due to an out-of-memory condition. If so, allocations may fail, throwing `std::bad_alloc()`, and furthermore, an exception throw operation itself can allocate on the heap, and if that fails, the C++ runtime library can call `std::terminate()`. That is, if there is little enough heap memory available, it won't be possible to recover from allocation failures in `release()`.
Also …

Use MemorySegment intrusive list for SystemSegmentProvider free list

---

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/AttachHandler.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/CommonDirectory.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/TargetDirectory.java
test/functional/Java8andUp/src/org/openj9/test/attachAPI/TestAttachAPI.java

When restarts the docker container, which the java application
does not catch some signals like SIGTERM to shutdown gracefully:
- leave some stale file there.
- it's possible(mostly) that the java application is assigned the same
process ID as before.
As a result, the jps/jstack could not work as expected due to
these stale and conflict VM target files.
Cherry-pick https://github.com/eclipse-openj9/openj9/pull/13331 for 0.28 release
Signed-off-by: Xia Wood <xiazhongwu@gmail.com>

(v0.28.0-release) Cleanup stale directories and files of attach API properly

---

runtime/gc_vlhgc/MemorySubSpaceTarok.cpp
runtime/gc_vlhgc/MemorySubSpaceTarok.hpp

- rename `adjustExpansionWithinSoftMax` to `adjustExpansionWithinSoftMx`
The purpose of doing this is to allow better code sharing between `MemorySubSpace::adjustExpansionWithinSoftMax` which is being introduced eclipse/omr#6141
Additionally, changing name/description of MemorySubSpaceTarok to better reflect true description.
A follow up PR should be done (once OMR side goes through), which does the following:
- Remove `MemorySubSpaceTarok::adjustExpansionWithinSoftMx`. All of these function calls should be changed to `adjustExpansionWithinSoftMax` (inherited from `MemorySubSpace`)
- Use `SOFT_MX_CONTRACT` flag for contraction in `MemorySubSpaceTarok` in the appropriate place in `MemorySubSpaceTarok::timeForHeapContract` (this flag will be introduced in OMR side)
Signed-off-by: Cedric …

Clean up softmx logic in MemorySubSpaceTarok

---

runtime/compiler/control/J9Options.cpp

This commit disables `-XX:+JITServerTechPreviewMessage` being
enabled by default for Power and x86, since JITServer is releasing
for those platforms. The option is still enabled by default for Z.

Disable JITServer Tech Preview message for Power and x86

---

runtime/compiler/il/J9MethodSymbol.cpp

JDK17+ uses the OpenJDK implementation for `java.lang.String`. Unlike
the OpenJ9 implementation it does not null-check and should not skip
adding the null-checks by the JVM.
resolve: #13367

Remove j.l.String methods from canSkipNullChecks for JDK17+

---

runtime/compiler/il/J9MethodSymbol.cpp

JDK17+ uses the OpenJDK implementation for java.lang.String. Unlike
the OpenJ9 implementation it does not null-check and should not skip
adding the null-checks by the JVM.
Port of #13465

(0.28) Remove j.l.String methods from canSkipNullChecks for JDK17+

---

runtime/gc_vlhgc/MemorySubSpaceTarok.cpp
runtime/gc_vlhgc/MemorySubSpaceTarok.hpp

Please see related PR link for motivations behind this change.
Changes include:
- remove `MemorySubSpaceTarok::adjustExpansionWithinSoftMx()` in favour of `adjustExpansionWithinSoftMax()`. The latter of the two, is inherited from `MemorySubSpace` and has no functional differences. This allows better code sharing/consistency
- Use `SOFT_MX_CONTRACT` contraction flag in `MemorySubSpaceTarok`. This better reflects the reason for contraction due to softmx. This depends on the linked OMR PR.
- Use `MEMORY_SUBSPACE_NAME_TAROK` and `MEMORY_SUBSPACE_DESCRIPTION_TAROK` flags instead of hard coded value for `getName()` and `getDescription()` in `MemorySubSpaceTarok`
This PR is related to, and is a follow up on: https://github.com/eclipse-openj9/openj9/pull/13308
This PR depends on: …

Clean up `MemorySubSpaceTarok` softmx heap resizing

---

runtime/compiler/optimizer/InterpreterEmulator.cpp

`InterpreterEmulator::findNextByteCodeToVisit()` accesses `_InterpreterEmulatorFlags`
twice. Before the second one, `_bcIndex` can be modified with the value returned
by `findNextByteCodeToGen()`. The value can be larger than `_maxByteCodeIndex`,
which causes an out of bounds access as seen in https://github.com/eclipse-openj9/openj9/issues/13096.
This commit adds a bound check before the second access to `_InterpreterEmulatorFlags`.
Closes: #13096

Add bound check before accessing flags array of InterpreterEmulator

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java
runtime/j9vm/j9scar.tdf
runtime/vm/j9vm.tdf
runtime/vm/vmbootlib.c

Try `BootLoader.getNativeLibraries().find(entryName)` if `bootstrapClassLoader.nativelibs.find(entryName)` didn't succeed;
Add trace points;
Refactoring methods affected.
This fixes an internal test failure with following stack trace
```
java.lang.UnsatisfiedLinkError: apple/security/KeychainStore._scanKeychain()V
at java.base/apple.security.KeychainStore.engineLoad(KeychainStore.java:769)
at java.base/java.security.KeyStoreSpi.engineLoad(KeyStoreSpi.java:439)
at java.base/java.security.KeyStoreSpi.engineLoad(KeyStoreSpi.java:403)
at java.base/java.security.KeyStore.load(KeyStore.java:1506)
at java.base/java.security.KeyStore$Builder$2$1.run(KeyStore.java:2193)
at java.base/java.security.KeyStore$Builder$2$1.run(KeyStore.java:2182)
at …
```

JDK17+ : Try BootLoader if bootstrapClassLoader didn't find the native

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java
runtime/j9vm/j9scar.tdf
runtime/vm/j9vm.tdf
runtime/vm/vmbootlib.c

Try `BootLoader.getNativeLibraries().find(entryName)` if `bootstrapClassLoader.nativelibs.find(entryName)` didn't succeed;
Add trace points;
Refactoring methods affected.
This fixes an internal test failure with following stack trace
```
java.lang.UnsatisfiedLinkError: apple/security/KeychainStore._scanKeychain()V
at java.base/apple.security.KeychainStore.engineLoad(KeychainStore.java:769)
at java.base/java.security.KeyStoreSpi.engineLoad(KeyStoreSpi.java:439)
at java.base/java.security.KeyStoreSpi.engineLoad(KeyStoreSpi.java:403)
at java.base/java.security.KeyStore.load(KeyStore.java:1506)
at java.base/java.security.KeyStore$Builder$2$1.run(KeyStore.java:2193)
at java.base/java.security.KeyStore$Builder$2$1.run(KeyStore.java:2182)
at …
```

(v0.28.0-release) Try BootLoader if bootstrapClassLoader didn't find the native

---

runtime/compiler/optimizer/J9TransformUtil.cpp

MethodHandleTransformer refines linkToVirtual calls to the target
method when MemberName is known. The call kind of the refined
linkToVirtual call target was always treated as Virtual.
However, for private virtual methods and java/lang/Object;
type virtual methods, there is no corresponding entry in the vtable,
and for such methods the interpreter vtable index is set as 0.
The dispatch is not performed through the vtable entry, but instead
it is a direct call to the target method obtained from MemberName.
By checking if jitVtableOffset is positive, we can determine if
a call needs to be dispatched through the vTable. Otherwise, we
can handle it similar to linkToStatic.
Closes: #13430 

Refine linkToVirtual to a direct call when no vtable entry exists

---

runtime/compiler/optimizer/InterpreterEmulator.cpp

`InterpreterEmulator::findNextByteCodeToVisit()` accesses `_InterpreterEmulatorFlags`
twice. Before the second one, `_bcIndex` can be modified with the value returned
by `findNextByteCodeToGen()`. The value can be larger than `_maxByteCodeIndex`,
which causes an out of bounds access.
This commit adds a bound check before the second access to `_InterpreterEmulatorFlags`.
Master PR: https://github.com/eclipse-openj9/openj9/pull/13476

(0.28.0) Add bound check before accessing flags array of InterpreterEmulator

---

runtime/compiler/optimizer/J9TransformUtil.cpp

MethodHandleTransformer refines linkToVirtual calls to the target
method when MemberName is known. The call kind of the refined
linkToVirtual call target was always treated as Virtual.
However, for private virtual methods and java/lang/Object;
type virtual methods, there is no corresponding entry in the vtable,
and for such methods the interpreter vtable index is set as 0.
The dispatch is not performed through the vtable entry, but instead
it is a direct call to the target method obtained from MemberName.
By checking if jitVtableOffset is positive, we can determine if
a call needs to be dispatched through the vTable. Otherwise, we
can handle it similar to linkToStatic.
Contributed to master branch via #13474
Signed-off-by: Nazim Bhuiyan nubhuiyan@ibm.com

(0.28.0) Refine linkToVirtual to a direct call when no vtable entry exists

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Remove unnecessary regdep from condition branch instruction to
ArrayStoreException JIT helper.
The unnecessary regdep keeps otherwise dead registers alive and
assigned to real registers, which results in GC error if instantiation
of ArrayStoreException triggers GC.

AArch64: Remove unnecessary regdep from reference array copy

---

doc/release-notes/0.28/0.28.md

The release notes now reflect that JITServer is fully
available on select platforms.

Update 0.28 release notes with JITServer info

---

doc/release-notes/0.28/0.28.md

The release notes now reflect that JITServer is fully
available on select platforms.

(0.28.0) Update 0.28 release notes with JITServer info

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Remove unnecessary regdep from condition branch instruction to
ArrayStoreException JIT helper.
The unnecessary regdep keeps otherwise dead registers alive and
assigned to real registers, which results in GC error if instantiation
of ArrayStoreException triggers GC.
Master PR: https://github.com/eclipse-openj9/openj9/pull/13507

(0.28.0) AArch64: Remove unnecessary regdep from reference array copy

---

runtime/compiler/optimizer/J9Inliner.cpp

This constant was removed from OMR and readded
inside `J9Inliner.cpp` as it is the only file that uses it.

Re-add MIN_PROFILED_CALL_FREQUENCY to inliner

---

runtime/compiler/env/J9ClassEnv.cpp

`TypeLayoutEntry` needs to be valid throughout the whole compilation.
When the typeLayout is constructed in ILGen, the field signature is
from `TR_VMFieldsInfo` which is stack allocated in `enumerateFields` in
the stack region for ILGen. The` stackMemoryRegion` for ILGen will be
released after genIL().
Fixes #13484

Store field signature for TypeLayoutEntry on heap

---

test/functional/cmdLineTests/jython/playlist.xml

Resolve: https://github.com/eclipse-openj9/openj9/issues/13460

Add space after JVM_OPTIONS in jython test

---

runtime/gc_trace/TgcParallel.cpp

Follow up for https://github.com/eclipse/omr/pull/6068
Update TGC to Fetch Scavenge Times from event data
Signed-off-by: Enson Guo <enson.guo@ibm.com>

Update TGC to Fetch Scavenge Times from event data

---

buildenv/jenkins/common/pipeline-functions.groovy

SHAs in local builds (derived via `git rev-parse --short`) are currently 11 or 12 digits; trimming them to 7 digits invites ambiguity. Use 11 digits.

Don't over-abbreviate SHAs

---

runtime/tests/port/j9mmapTest.c

On s390x Ubuntu 20.04, if a write attempt is made on mmap'd memory whose
protection is set to read only, and then a second attempt is made when
the map protection is set to back to writeable, the second attempt will
not update the underlying memory.
This workaround does a small read so that the write attempt on writeable
memory will work.
Issue https://github.com/eclipse-openj9/openj9/issues/12719
@pshipton

Workaround for zlinux mmap issue in pltest

---

runtime/compiler/optimizer/VectorAPIExpansion.cpp

Remove checkcasts that check objects being scalarized or vectorized

Handle checkcast in VectorAPIExpansion

---

runtime/tests/port/j9mmapTest.c

On s390x Ubuntu 20.04, if a write attempt is made on mmap'd memory whose
protection is set to read only, and then a second attempt is made when
the map protection is set to back to writeable, the second attempt will
not update the underlying memory.
This workaround does a small read so that the write attempt on writeable
memory will work.
Cherry-picked from https://github.com/eclipse-openj9/openj9/pull/13538
@pshipton

(0.28.0) Workaround for zlinux mmap issue in pltest

---

runtime/gc_base/GCExtensions.hpp
runtime/gc_modron_startup/mmparse.cpp
runtime/gc_modron_startup/mmparseXgc.cpp
runtime/gc_stats/MarkVLHGCStats.hpp
runtime/gc_verbose_handler_vlhgc/VerboseHandlerOutputVLHGC.cpp
runtime/gc_verbose_handler_vlhgc/VerboseHandlerOutputVLHGC.hpp
runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp
runtime/gc_vlhgc/EnvironmentVLHGC.cpp
runtime/gc_vlhgc/EnvironmentVLHGC.hpp
runtime/gc_vlhgc/GlobalMarkingScheme.cpp
runtime/gc_vlhgc/IncrementalGenerationalGC.cpp
runtime/gc_vlhgc/IncrementalGenerationalGC.hpp
runtime/gc_vlhgc/MemorySubSpaceTarok.cpp
runtime/gc_vlhgc/MemorySubSpaceTarok.hpp
runtime/gc_vlhgc/ReclaimDelegate.cpp
runtime/gc_vlhgc/SchedulingDelegate.cpp
runtime/gc_vlhgc/SchedulingDelegate.hpp

This change introduces 2 different major components to balanced gc, which are working together.
---------Change 1: New heap sizing logic in balanced gc
The old heap sizing logic, relied primarily on free memory %, in relation to -Xminf and -Xmaxf to decide whether or not the heap should shrink/expand.
If free memory was within the acceptable boundary, the heap sizing logic would then look at gc cpu% to decide whether to expand/contract.
The new logic (which is included in this commit), aims to take a more hybrid approach, where TENURE free memory % and GMP cpu % are working together, to determine whether or not the heap needs to change.
The function ```calculateCurrentHybridHeapOverhead``` determines what the current "hybrid overhead" of the heap/gc is (blend of gc cpu % and free memory …

New eden and heap sizing logic in Balanced GC

---

test/functional/JIT_Test/playlist.xml
test/functional/cmdLineTests/shareClassTests/SCHelperCompatTests/playlist.xml
test/functional/cmdLineTests/verbosetest/playlist.xml

https://github.com/eclipse-openj9/openj9/issues/6057 tracks known issues when running functional and extended tests with `-Xscmx400M -Xscmaxaot256m -Xjit:forceAOT -Xaot:forceAOT`. This PR temporarily disables them (only under forceAOT) until they are fixed so that new bugs don't get lost in the noise.

Disable tests known to fail with forceAOT

---

runtime/gc_vlhgc/SchedulingDelegate.cpp

https://github.com/eclipse-openj9/openj9/pull/12043 introduced a cast warning when compiled to32 bit platforms.
This commit adds the appropriate cast to fix the warning.

Fix cast warning from #12043

---

test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java

Changed typed getters/setters/withers to generic as there is currently
no support for OJDK method handles for value types.
Fixes: #13547
See #13549

Fix ValueTypeTests throwing NoSuchMethod exception

---

.github/workflows/presubmit.yml

Only run on master branch after it is updated for a supported build environment.

Disable automatic execution of linter job

---

runtime/gc_vlhgc/MemorySubSpaceTarok.cpp
runtime/gc_vlhgc/SchedulingDelegate.cpp

The data types of the 2 variables mentioned above, have changed from `uint64_t` to `uintptr_t`.
With that, several explicit casts were removed, to increase code readability.
Depends on: https://github.com/eclipse/omr/pull/6184

Remove casts related to `reservedSize` and `freeTenure`

---

buildspecs/win_x86.spec
test/functional/NativeTest/playlist.xml

- The original value {$machine_mapping.win$} is win, but there is no machine labeled win in vmfarm.
- Temporarily exclude shrtest_aix_SE80 on vmfarm
related: runtimes/test/pull/445
related: runtimes/backlog/issues/560

Update graph_req.os value in win_x86.spec

---

runtime/include/j9lib.h.ftl
runtime/include/j9lib.h.in
runtime/j9vm/jvm.c
runtime/vm/jvminit.c
runtime/vm/vmprops.c

Removed redundant `J9_DEFAULT_JCL_DLL_NAME`.
Note: this redundancy was identified while investigating native lib pre-loading via `registerBootstrapLibrary()`.
Related to https://github.com/eclipse-openj9/openj9/pull/12981#issuecomment-908422165.

JDK17+ reduce registerBootstrapLibrary usages

---

runtime/include/j9lib.h.ftl
runtime/include/j9lib.h.in
runtime/j9vm/jvm.c
runtime/vm/jvminit.c
runtime/vm/vmprops.c

Removed redundant `J9_DEFAULT_JCL_DLL_NAME`.
Cherry-pick https://github.com/eclipse-openj9/openj9/pull/13580

(v0.29.0-release) JDK17+ reduce registerBootstrapLibrary usages

---

runtime/vm/BytecodeInterpreter.hpp

Throw IAE for non-public virtual methods similar to invokeinterface.
Multiple returns converted to a single return via gotos to ease debugging.
Backporting https://github.com/eclipse-openj9/openj9/pull/13582 to the 0.29 release.

Throw IllegalAccessError (IAE) from linkToInterface

---

test/functional/cmdLineTests/shareClassTests/SCHelperCompatTests/playlist.xml

Update SCHelperCompatTests to remove `<aot>explicit</aot>`
Functional testing is failing to compile related to stricter validation on playlists: https://github.com/adoptium/TKG/pull/235

Cannot have two aot instructions in test playlists

---

runtime/rasdump/javadump.cpp

The first commit cleans up:
* remove the implicit dependency on order of flag bits in `prepState` and `requestMask`
* add missing parentheses
* explicitly compare values with `NULL` or `0`
* initialize local variables
* use `J9_ARE_ALL_BITS_SET`, `J9_ARE_ANY_BITS_SET` and `J9_ARE_NO_BITS_SET` where appropriate
The second commit fixes #13471.

Show ignored options in java dumps

---

runtime/compiler/ilgen/J9ByteCodeIlGenerator.hpp
runtime/compiler/ilgen/Walker.cpp

When value type is enabled, loadArrayElement in ILGen uses helper
calls jitLoadFlattenableArrayElement to load array elements.
In some cases, if arrays are known not to be value types, we need
an API to do regular array element load.
Fixes #13540

Split loadArrayElement into two APIs

---

runtime/vm/FastJNI_java_lang_ref_Reference.cpp

This is intended to improve performance, noted to have regressed in #13596.

Add fast JNI implementation for java.lang.ref.Reference.refersTo()

---

runtime/compiler/optimizer/IdiomTransformations.cpp
test/functional/JIT_Test/src/jit/test/loopReduction/bigEndianByte2CharMemCpy.java
test/functional/JIT_Test/src/jit/test/loopReduction/idiomTests.java
test/functional/JIT_Test/src/jit/test/loopReduction/littleEndianByte2CharMemCpy.java

Idiom recognition is incorrectly transforming byte-to-char loops for little endian.  For example,
```
for (int i = 0, j = 0; j < numChars; i += 2, j++) {
dst[j + offsetDst] = (char) (((src[i + 1 + offsetSrc] & 0xFF) << 8) | (src[i + offsetSrc] & 0xFF))
}
```
A loop such as this can be recognized and reduced to an arraycopy on little endian architectures.  Similarly, if the char was composed with the shift on the lower address byte then it would be recognized as an arraycopy on big endian architectures.
However, for little endian, the wrong address tree is chosen to start the arraycopy (i.e., `src[i + 1 + offsetSrc]` is chosen instead of  `src[i + offsetSrc]`).  Big endian selects the correct address.
Select the starting address based on the endianess of the target platform.
The loop …

Fix memcpy byte-to-char loop reduction for little endian architectures

---

runtime/gc_modron_startup/mminit.cpp

In case Xmns is specified and Xmns > Xms, match the same behavior in
Gencon.
if Xms is specified, need to report error JVMJ9GC019E " -Xmns is too
large for -Xms".
if Xms is not specified, need to reset extensions->initialMemorySize
= Xmns.
fix:https://github.com/eclipse-openj9/openj9/issues/13558

Update verification for initial memory paramters in Balanced GC

---

jcl/src/java.base/share/classes/java/lang/Access.java

`JDK17+` `Access.decodeASCII()` uses `String.decodeASCII()`
Related to https://github.com/eclipse-openj9/openj9/pull/13603#discussion_r719572946

JDK17+ Access.decodeASCII() uses String.decodeASCII()

---

jcl/jpp_configuration.xml
jcl/src/java.base/share/classes/java/lang/Access.java

Removed `OPENJDK_METHODHANDLES` since `ojdk_mh` has been promoted;
Add `rt-compressed.sunJava18.jar` for `JAVA18 pConfig`.
Related to https://github.com/eclipse-openj9/openj9/issues/13600

JDK18 adds Access.encodeASCII()

---

buildenv/jenkins/common/variables-functions.groovy

Since aarch64 linux builds in a container from Adopt,
it does not have a 17 bootjdk. Need to grab the m2 build
from the Semeru release.
Related #13585

Temporarily hack the bootjdk url for alinux on jdk17

---

test/functional/JLM_Tests/playlist.xml

Fails in every Windows 64-bit build.
Issue https://github.com/eclipse-openj9/openj9/issues/10732#issuecomment-927855842
Tested in grinder https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/249/.
Builds, shows testSoftMxNotDisclaimMemory_3 is disabled, fails because no testing runs.

Disable testSoftMxNotDisclaimMemory_3

---

runtime/gc_include/j9modron.h

This flag is defined in omrgcconts.h in OMR project

Remove duplicate definition of DEFERRED_RS_REMOVE_FLAG

---

runtime/vm/FastJNI_java_lang_ref_Reference.cpp

Add fast JNI implementation for java.lang.ref.Reference.refersTo()
back port of https://github.com/eclipse-openj9/openj9/pull/13597

(0.29) Add fast JNI implementation for java.lang.ref.Reference.refersTo()

---

runtime/port/zos390/j9gs_get_supported.s

A `DROP` directive must the refer to the same register as the corresponding `USING` directive.
The assembler issues warnings for unmatched directives.

Fix z/OS assembly warnings

---

runtime/compiler/aarch64/runtime/FlushICache.spp
runtime/compiler/aarch64/runtime/Recompilation.spp

This commit adds .text and .align directives to AArch64 asm files.

AArch64: Add .text and .align directives to asm files

---

runtime/CMakeLists.txt

An equivalent check exists in the top-level `CMakeLists.txt`.

Remove redundant cmake version check

---

jcl/src/java.base/share/classes/module-info.java.extra

Add pre-processor checks for openj9.criu
Fixes https://github.com/eclipse-openj9/openj9/issues/13828

Add pre-processor checks for openj9.criu

---

runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/il/J9SymbolReference.cpp
runtime/compiler/ilgen/Walker.cpp
runtime/compiler/optimizer/EscapeAnalysis.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/InterProceduralAnalyzer.cpp
runtime/compiler/optimizer/J9Inliner.cpp
runtime/compiler/optimizer/MonitorElimination.cpp
runtime/compiler/runtime/J9Profiler.cpp
runtime/compiler/x/codegen/X86PrivateLinkage.cpp

Depends on 
Related to eclipse/omr#6217

Replace classNameToSignature with the define in ClassEnv

---

jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java
runtime/bcutil/ROMClassBuilder.cpp
runtime/bcutil/cfreader.c
runtime/oti/cfr.h
runtime/oti/j9.h
runtime/verutil/chverify.c
runtime/vm/classsupport.c

Update VT implementation to unblock valhalla builds on repo
ibmruntimes/openj9-openjdk-jdk.valuetypes
Update checkNameImpl() to allow Constant_class descriptors.
Add implememtation of new unsafe methods.
Closes #13694

Update VT implementation to unblock valhalla builds

---

runtime/CMakeLists.txt
runtime/j9vm/generated.h.m4
runtime/oti/helpers.m4
runtime/redirector/forwarders.m4
runtime/redirector/generated.c.m4

Only decorate function names on 32-bit Windows
* define and use `DECORATED_NAME()` where appropriate
* eliminates need to remove decoration at runtime
Also:
* define `_IF` in `helpers.m4` and add support for `#else` blocks
* add missing comments on `#else` and `#endif`
* add missing dependency of `generated.c` on `forwarders.m4`
* remove recursion from forwarding functions
* allow for better string sharing
* use `fprintf()` throughout (instead of also using `printf()`)

Improve redirector

---

jcl/src/java.base/share/classes/java/lang/System.java
runtime/jcl/common/system.c
runtime/jcl/exports.cmake
runtime/jcl/module.xml
runtime/jcl/uma/se18_exports.xml
runtime/oti/jclprots.h
runtime/vm/vmprops.c

Added a native `Java_java_lang_System_getSysPropBeforePropertiesInitialized`.
Related https://github.com/eclipse-openj9/openj9/issues/13828

JDK18+ returns os.version before System.systemProperties is initialized

---

runtime/compiler/optimizer/VectorAPIExpansion.cpp
runtime/compiler/optimizer/VectorAPIExpansion.hpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp

- As a temporary solution, in order to enable codegen work, provide a way of using
vcall opcode for Vector API intrinsics instead of vector IL opcodes
- This can be enabled with TR_UseVcall environment variable.
- If TR_UseVCall is set all opcodes will use vcall
- ADD is used as an example for other ocodes which indeed don't have corresponding IL
- Don't anchor old children of the original intrinsic call since all children remain
the same and only node's opcode is changed to vcall

Use vcall for Vector API intrinsics

---

sourcetools/j9constantpool/com/ibm/oti/VMCPTool/InterfaceMethodRef.java
sourcetools/j9constantpool/com/ibm/oti/VMCPTool/StaticMethodRef.java
sourcetools/j9constantpool/com/ibm/oti/VMCPTool/VirtualMethodRef.java

`METHODALIAS` should be used.
This was discovered when investigating https://github.com/eclipse-openj9/openj9/issues/13852
fyi @keithc-ca 

Support StaticMethodRef alias

---

runtime/jcl/common/jclcinit.c
runtime/jcl/j9jcl.tdf

These assertions indicate the startup failure location to avoid a silent VM exit.
Related to https://github.com/eclipse-openj9/openj9/issues/13852#issuecomment-960250434

Add assertions to JCL startup failures

---

runtime/compiler/aarch64/runtime/PicBuilder.spp
runtime/compiler/runtime/Runtime.cpp

This commit implements a helper for Patchable GCRs on aarch64.
Depends on https://github.com/eclipse/omr/pull/6227

AArch64: Implement a helper for Patchable GCRs

---

test/functional/Java8andUp/playlist.xml
test/functional/Java8andUp/src/org/openj9/test/constantpool/ClassInitTest.java
test/functional/Java8andUp/testng.xml

Check that class initialize is done at the correct time when calling
ConstantPool methods.
Issue: #12157

Add testing for ConstantPool class load behaviour

---

test/functional/cmdLineTests/hangTest/build.xml

- Add dependency for hangTest dynamic compile
[skip ci]

Fix hangTest failure with dynamic compile

---

runtime/oti/j9porterror.h
runtime/port/common/j9hypervisor_common.c
runtime/port/common/j9port.c

Returning -1 does not give any useful information about what failed.
See also https://github.com/eclipse/omr/pull/6231
Issue https://github.com/ibmruntimes/Semeru-Runtimes/issues/5#issuecomment-962040999
Issue https://github.com/eclipse-openj9/openj9/issues/12526

Port library startup should not return -1

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

- use ForceInline inside tryToInine() and alwaysWorthInlining() for all methods
- use ForceInline in callMustBeInlined() for Vector API methods

Extend usage of ForceInline annotation in JIT

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
runtime/jcl/common/reflecthelp.c
runtime/oti/vmconstantpool.xml

In all supported Java versions of `Constructor`, `Field` and `Method`:
* the field is `clazz`, not `declaringClass`
* the field is `slot`, not `intFieldID` or `intMethodID`
Update references to affected generated macros.

Remove useless field aliases

---

runtime/jcl/common/jclexception.cpp
runtime/oti/j9modifiers_api.h

Use the dot naming convention in exception stack traces
Fixes https://github.com/eclipse-openj9/openj9/issues/13846

Use the dot naming convention in exception stack traces

---

runtime/vm/jvminit.c
test/functional/cmdLineTests/xlogTests/xlog.xml

Levels off, warning, error do not enable the verbose gc log
Issue https://github.com/eclipse-openj9/openj9/issues/13865

Only enable verbose gc log for -Xlog levels trace, debug, info

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Kill placeholder registers used for register dependencies
at arraycopy helper call.
Depends on https://github.com/eclipse/omr/pull/6233

AArch64: Kill placeholder registers for arraycopy

---

runtime/jcl/common/jclexception.cpp
runtime/oti/j9modifiers_api.h

Use the dot naming convention in exception stack traces
Fixes https://github.com/eclipse-openj9/openj9/issues/13846
Port of https://github.com/eclipse-openj9/openj9/pull/13883 for the 0.29.1 release.

(0.29.1) Use the dot naming convention in exception stack traces

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/codegen/J9CodeGenerator.hpp
runtime/compiler/optimizer/J9CallGraph.hpp
runtime/compiler/optimizer/J9Inliner.cpp
runtime/compiler/p/codegen/PPCPrivateLinkage.cpp
runtime/compiler/x/codegen/X86PrivateLinkage.cpp
runtime/compiler/z/codegen/S390PrivateLinkage.cpp

When using Interpreter Profiling data to inline or devirtualize a call
it's possible for the isInstanceOf() check to pass despite the profiled
class not being compatible with the caller's context. This can happen
when compiling for AOT where the caller is sharing a J9ROMMethod with
a 2nd classloader and the callee in the bytecodes is an Abstract class
where some method is not defined in the Abstract class but is required
by an interface. This results in the the Abstract classes VFT containing
a reference to the Interface's J9Method. Because the VFT index for any
interface methods can differ between different implementors, if we use
the VFT index to retrieve a method from a profiled class that is from
an incorrect context several different bad things can happen. The
isInstanceOf() check …

Fix getOriginalROMMethod() crash indexing off the end of the J9Class VFT

---

runtime/compiler/optimizer/EscapeAnalysis.cpp
runtime/compiler/optimizer/EscapeAnalysis.hpp

The `getCandidate` method first calls `FlushCandidate::getCandidate` to check whether the flush candidate already has a known stack allocation candidate.  If there is no known candidate, the method iterates over the stack allocation candidates checking whether any is associated with the flush candidate.  In the case that a flush candidate actually has no associated stack allocation candidate, `getCandidate` was scanning the stack allocation candidates every time it was called.  This presented a compile-time performance problem for very large methods with many stack allocation and flush candidates.
Corrected the problem by adding a way of caching the fact that the flush candidate definitely has no associated stack allocation candidate, to avoid scanning the candidates more than once.
Fixes …

Cache fact that FlushCandidate has no stack allocation candidate

---

test/functional/VM_Test/src/com/ibm/oti/jvmtests/GetNanoTimeAdjustment.java

Fix jvmnativestest test_EnsureWallClockTime()

---

jcl/src/java.base/share/classes/java/lang/System.java
runtime/bcutil/ROMClassBuilder.cpp
runtime/compiler/env/j9method.cpp
runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
runtime/jcl/common/stdinit.c
runtime/oti/vmconstantpool.xml

**1. Signature of NativeLibraries.load has changed in JDK18** 
Update the signature of NativeLibraries.load in native code for JDK18.
**2. Set the useDirectMethodHandle Java flag to false** 
Setting jdk.reflect.useDirectMethodHandle to false disables the new JEP 416
changes where the reflection API is dependent on the MethodHandle API.
This flag will be reenabled once OpenJ9 supports JEP 416.
Related: #13852
Related: #13880
**3. Update MHN.getMemberVMInfo to work with MemberName.vminfoIsConsistent** 
MemberName.vminfoIsConsistent is only used in an assertion to validate the
vmtarget and vmindex elements of MemberName. It relies on MHN.getMemberVMInfo
to retrieve the vmtarget and vmindex elements of MemberName.
For correct validation, MHN.getMemberVMInfo should return 0 for vmindex when …

Unblock JDK-next (JDK18) acceptance build

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/compile/J9SymbolReferenceTable.hpp
runtime/compiler/optimizer/J9ValuePropagation.cpp
runtime/compiler/optimizer/J9ValuePropagation.hpp
runtime/compiler/optimizer/TreeLowering.cpp
runtime/compiler/optimizer/TreeLowering.hpp

If the value stored in a call to `jitStoreFlattenableArrayElement` is known not to be a value type, the call can be transformed by Value Propagation to inline IL for an ordinary array store even if the component type of the array is not known not to be a value type.  That's because, if the component type of the array actually is a value type, the `ArrayStoreCHK` added as part of the array element store sequence would throw an `ArrayStoreException` - there is no need to deal with a potential store to a flattened value type array element.
The one special case that needs to be handled in the inline IL that's generated is the case where the value that is being stored could be a null reference.  The prototype support for value types does not permit a null reference to be stored into an element …

Allow Value Propagation to transform an array store if the value assigned is known not to be a value type

---

runtime/jcl/common/jclcinit.c
runtime/oti/vmconstantpool.xml

This fixes `java.lang.InternalError: sun.misc.Unsafe::theUnsafe cannot be accessed reflectively before java.lang.invoke is initialized`
fixes https://github.com/eclipse-openj9/openj9/issues/13917
Note: can't remove `-Djdk.reflect.useDirectMethodHandle=false` yet (https://github.com/eclipse-openj9/openj9/issues/13901)

JDK18 adds java.lang.invoke.MethodHandleNatives as requiredClasses

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

The write barrier instruction sequence uses the heap size for checking
if the object is in the heap.
The heap size must be loaded from vmstruct on AOT compilation
even if the size is constant.

AArch64: Load heap size from vmstruct on AOT compilation

---

runtime/verbose/j9vrb.tdf
runtime/vm/j9vm.tdf
runtime/vm/swalk.c

Also add the tracepoints to the normal (non-verbose) walker.

Add root values to walkStackFrames entry tracepoint

---

buildenv/jenkins/variables/defaults.yml

Set extensions repository for next release for all Valhalla specs.

Add extensions repository for Valhalla to Jenkins builds

---

runtime/compiler/control/HookedByTheJit.cpp

There's a corner case where specifying counts in an option set while the
SCC is enabled results in the option set getting ignored. The reason
this happens is because in `jitHookInitializeSendTarget`, the update is
guarded by `TR::Options::getCountsAreProvidedByUser`, which only returns
true when counts are set by the user outside an option set. This PR
fixes this issue.

Don't override counts if specified by user in subset

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/VMJ9.cpp
runtime/criusupport/criusupport.cpp
runtime/gc_modron_startup/mminit.cpp
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/CMakeLists.txt
runtime/vm/criuhelpers.cpp
runtime/vm/jvminit.c
runtime/vm/module.xml

* inline CRIU checkpoint state (only if needed)
* add missing `#endif` comments

Tidy up CRIU support

---

runtime/gc_modron_startup/mmparse.cpp

In certain edge cases, the `_wasSpecified` flag could be set true, despite a parsing error. This new control flow fixes this from potentially happening.

Improve parsing flow for `-Xmint` and `-Xmaxt`

---

runtime/rasdump/javadump.cpp

If the state contains only `J9RAS_DUMP_TRACE_DISABLED` it is shown as
```
1TIPREPSTATE   Prep State: 0x80trace_disabled
```
instead of
```
1TIPREPSTATE   Prep State: 0x80 (trace_disabled)
```

Fix annotation of 1TIPREPSTATE in javacore dumps

---

runtime/compiler/arm/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/compile/AOTClassInfo.hpp
runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/compile/J9Compilation.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/CompilationThread.hpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/control/JITServerHelpers.hpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/J9PersistentInfo.hpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/env/SharedCache.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.hpp
runtime/compiler/p/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp
runtime/compiler/runtime/RelocationRuntime.cpp
runtime/compiler/runtime/RelocationRuntime.hpp
runtime/compiler/runtime/SymbolValidationManager.cpp
runtime/compiler/runtime/SymbolValidationManager.hpp

This PR adds infrastructure for requesting necessary information from the client JVM for creating JITServer AOT cache records, and caching pointers to these records in client session data. The APIs modified or added in this PR will be used by the AOT compiler to create and remember AOT cache records corresponding to relocation and validation records.

Infrastructure for creating JITServer AOT cache records during compilation

---

test/functional/Java16andUp/build.xml
test/functional/Java16andUp/playlist.xml
test/functional/Java16andUp/src/org/openj9/test/foreignMemoryAccess/TestCloseScope0.java
test/functional/Java16andUp/testng.xml
test/functional/Java16andUp/testng_160.xml

Class changes in the jdk17 extensions repo (e.g. MemoryScope ->
ResourceScope)
Move test from Java16andUp/src_160 (where only JDK16 can run it) to
Java16andUp/src to enable for JDK16+.
Fixes: #13195

Fix close scope test failure jdk17

---

runtime/vm/BytecodeInterpreter.hpp
runtime/vm/ValueTypeHelpers.hpp

In the slow path, loadFlattenableArrayElement() could call into
J9AllocateObject() which might trigger GC. Push/pop the array object
into/from special frame so that we always have the correct array object.
Closes #13848

Push/pop the array object into/from special frame in slow path

---

runtime/compiler/CMakeLists.txt

Only include arch specific subdirectories, if the they actually exist.

CMake: add guards on compiler arch includes

---

runtime/compiler/arm/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/compile/AOTClassInfo.hpp
runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/compile/J9Compilation.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/CompilationThread.hpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/control/JITServerHelpers.hpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/J9PersistentInfo.hpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/env/SharedCache.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.hpp
runtime/compiler/p/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp
runtime/compiler/runtime/RelocationRuntime.cpp
runtime/compiler/runtime/RelocationRuntime.hpp
runtime/compiler/runtime/SymbolValidationManager.cpp
runtime/compiler/runtime/SymbolValidationManager.hpp

This PR is a rework of #13907 that fixes compilation errors on AIX and Mac.

Infrastructure for creating JITServer AOT cache records during compilation (rework)

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

The write barrier instruction sequence uses the heap size for checking
if the object is in the heap.
The heap size must be loaded from vmstruct on AOT compilation
even if the size is constant.
Original PR in the master branch: #13927

(0.29.1) AArch64: Load heap size from vmstruct on AOT compilation

---

runtime/compiler/control/J9Options.cpp

Without the buffer size, `getTRPID(char*)` can't properly check bounds. Instead, call it now using the new signature that accepts the buffer size as a parameter.

Pass buffer size to getTRPID() in JITServer

---

runtime/bcutil/ClassFileOracle.cpp
runtime/bcutil/ConstantPoolMap.cpp
runtime/bcutil/ConstantPoolMap.hpp
runtime/bcutil/ROMClassBuilder.cpp
runtime/bcutil/ROMClassWriter.cpp
runtime/bcutil/ROMClassWriter.hpp
runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/compile/J9SymbolReferenceTable.hpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9method.h
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/env/j9methodServer.hpp
runtime/compiler/net/MessageTypes.hpp
runtime/compiler/optimizer/VarHandleTransformer.cpp
runtime/gc_structs/ClassIterator.cpp
runtime/gc_structs/ClassIterator.hpp
runtime/gc_vlhgc/CopyForwardScheme.cpp
runtime/oti/VMHelpers.hpp
runtime/oti/j9nonbuilder.h
runtime/vm/createramclass.cpp

J9RomClass.varHandleMethodTypeLookupTable is not used in the OJDK method
handle implementation as varhandles are treated as method handles and
use the invoke cache instead.
Closes: #11580

Disable VarHandleMethodType lookup table code for OJDK MH

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/runtime/JITClientSession.hpp

`TR_J9VMBase::isJavaLangObject()` is a frontend query that looks at
a field stored in JavaVM. The value of this field should be fetched from
the client, so `isJavaLangObject()` needs to be overridden.
Fixes #13954

Override TR_J9VMBase::isJavaLangObject at JITServer

---

jcl/src/java.base/share/classes/java/lang/Class.java

Cache the packageName to which receiver belongs in java/lang/Class.

Cache the packageName to which receiver belongs

---

buildenv/docker/mkdocker.sh
doc/build-instructions/Build_Instructions_V11.md
doc/build-instructions/Build_Instructions_V17.md
doc/build-instructions/Build_Instructions_V8.md

* Add `--gitcache={yes|no}` option to control the creation of the git cache
* Add `--jdk=` option to specify which jdks to support building
The defaults are unchanged. Using these options not only considerably speeds up the generation of the docker image, but reduces the size from ~4GB to ~1.7GB. The use case here is for developers who want to quickly set up a build env on a new (potentially temporarily allocated) machine to build a specific JDK and as such don't need the ability to build all possible JDKs.

OpenJ9 build image improvements

---

runtime/compiler/aarch64/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/aarch64/codegen/J9AheadOfTimeCompile.hpp
runtime/compiler/arm/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/arm/codegen/J9AheadOfTimeCompile.hpp
runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/codegen/J9AheadOfTimeCompile.hpp
runtime/compiler/p/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/p/codegen/J9AheadOfTimeCompile.hpp
runtime/compiler/x/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/x/codegen/J9AheadOfTimeCompile.hpp
runtime/compiler/z/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/z/codegen/J9AheadOfTimeCompile.hpp

This PR simplifies the process of the relocation record header
initialization by removing the requirement that implementor of
initializePlatformSpecificAOTRelocationHeader has to be the one that
calls initializeCommonAOTRelocationHeader.

Simplify relo header initialization process

---

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp

The relocation debug dump code for
TR_ValidateStackWalkerMaySkipFramesRecord incorrectly tried to also
print out a beholderMethod even though there isn't one.

Remove nonexistent data from relo log format string

---

jcl/src/java.base/share/classes/java/lang/System.java
runtime/j9vm/javanextvmi.c
runtime/vm/extendedMessageNPE.cpp
test/functional/cmdline_options_testresources/build.xml
test/functional/cmdline_options_testresources/src_90/com/ibm/j9/getcallerclass/RefectionMHTests.java

The `getStackTraceElementIterator()` invoked by `GetExtendedNPEMessage()` skips hidden frames;
`JDK18` `NPE` extended message generation recognizes `JEP416` `MH` methods for `java.lang.reflect.Constructor.newInstance()`;
Updated `test_getCallerClass_Helper_Reflection_fromBootExtWithAnnotation()` to adopt `MH` frames;
Removed `-Djdk.reflect.useDirectMethodHandle=false` to re-enable `JEP416`.
Note: currently OpenJ9 stack frame iterator functions check `J9AccMethodFrameIteratorSkip` individually, ideally a unified solution can be developed to hide/show those hidden frames. Created https://github.com/eclipse-openj9/openj9/issues/13951.

GetExtendedNPEMessage skips hidden frames and recognizes MH newInstance

---

runtime/vm/CMakeLists.txt
runtime/vm/KeyHashTable.c
runtime/vm/module.xml

When the class alignment check fails in class hash table queries, print
the bad value to the console before asserting.
Debugging help for #13123 which may be removed once the underlying issue
is discovered.

Print unaligned class value

---

runtime/j9vm/asgct.cpp

There was a call to jitGetExceptionTableFromPC being made before the
metadata cache was disabled, resulting a possible malloc inside the
signal handler.

Disable JIT cache earlier in ASGCT

---

jcl/src/java.base/share/classes/java/lang/invoke/VarHandle.java

The methods function correctly but there was a slight inaccuracy in their
description (wording), which has been corrected.
Closes: https://github.com/eclipse-openj9/openj9/issues/12429

Update method description to match Javadoc

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit fixes an issue with code generation of monitorEnter/Exit
check for value types for AArch64.
Fixes: #13916
Co-authored-by: Akira Saitoh saiaki@jp.ibm.com

AArch64: Fix the check for value type monitorEnter/Exit

---

runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/exports.h

Windows builds include a number of link warnings:
```
VMJ9.cpp.obj : warning LNK4197: export 'Java_java_lang_invoke_InterfaceHandle_convertITableIndexToVTableIndex' specified multiple times; using first specification
VMJ9.cpp.obj : warning LNK4197: export 'Java_java_lang_invoke_MutableCallSite_invalidate' specified multiple times; using first specification
VMJ9.cpp.obj : warning LNK4197: export 'Java_java_lang_invoke_ThunkTuple_initialInvokeExactThunk' specified multiple times; using first specification
```
See https://openj9-jenkins.osuosl.org/view/Build_Nightly/job/Build_JDK8_x86-64_windows_Nightly/159/consoleFull for a recent example.
This fixes those warnings:
* move prototype for `MutableCallSite.invalidate()` to `exports.h`
* remove redundant uses of `JNIEXPORT`

Fix link warnings on Windows

---

runtime/j9vm/asgct.cpp

The variable was being declared in an inner scope and the address of
said variable used in an outer scope.

Move ASGCT resolve frame to proper scope

---

runtime/codert_vm/CodertVMHelpers.cpp
runtime/codert_vm/cnathelp.cpp
runtime/codert_vm/decomp.cpp
runtime/codert_vm/jswalk.c
runtime/compiler/runtime/MethodMetaData.c
runtime/compiler/runtime/MethodMetaData.h
runtime/oti/j9nonbuilder.h
runtime/oti/j9protos.h
runtime/rasdump/javadump.cpp
runtime/vm/exceptiondescribe.c

Do not use the cache as it may be in an inconsistent state. Also, do not
allocate a new cache to avoid malloc during signal handler.
Remove unnecessary stack map query in dump creation.
Related: #13838

Disable stackMap cache during ASGCT

---

runtime/compiler/control/HookedByTheJit.cpp

Closes https://github.com/eclipse-openj9/openj9/issues/14004

Check for NULL before using the APIs in TR_J9SharedCache

---

runtime/codert_vm/CodertVMHelpers.cpp
runtime/codert_vm/cnathelp.cpp
runtime/codert_vm/decomp.cpp
runtime/codert_vm/jswalk.c
runtime/compiler/runtime/MethodMetaData.c
runtime/compiler/runtime/MethodMetaData.h
runtime/oti/j9nonbuilder.h
runtime/oti/j9protos.h
runtime/rasdump/javadump.cpp
runtime/vm/exceptiondescribe.c

Reverts eclipse-openj9/openj9#14007
See https://github.com/eclipse-openj9/openj9/pull/14007#issuecomment-979652212

Revert "Disable stackMap cache during ASGCT"

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.hpp
runtime/compiler/control/J9Options.cpp
test/functional/cmdLineTests/jvmtitests/playlist.xml

This commit adds support for JIT field watch on aarch64.
Depends on https://github.com/eclipse/omr/pull/6252

AArch64: Implement JIT field watch support

---

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/IPC.java

Also tidy up:
* trim trailing whitespace
* list modifiers in canonical order
* use normal array declaration

Remove redundant check of non-Windows platform

---

test/functional/Java12andUp/src/org/openj9/test/java_lang/Test_Class.java

Object cannot be instantiated directly with value type enabled. Use an
object of Thread instead.
closes #13957

Use an object of java.lang.Thread to test Class.descriptorString()

---

runtime/compiler/env/J9KnownObjectTable.cpp
runtime/compiler/env/J9KnownObjectTable.hpp
runtime/compiler/optimizer/J9TransformUtil.cpp
runtime/compiler/optimizer/J9TransformUtil.hpp

- if array is annotated as stable, treat its elements as stable
- implement similar to arrays with constant elements except that
array element cannot be folded if its value is 0
- handle only one dimension for now, until we have a test case
and a need for multi-dimensional case

Implement Stable annotations for arrays

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp

- Move invocation type check before vTableIndex check to avoid method vtable index returned for invokespecial call.
Related: #13946 
Close: #13995 

Update getMemberVMInfo behavior to match RI

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/env/CHTable.cpp
runtime/compiler/env/CHTable.hpp

At the end of compilation the JIT acquires the VM class mutex
just before performing chtable.commit(). We can skip this lock acquire
operation if we test beforehand that a chtable.commit does not need
to be performed. This can speed up AOT loads and some JIT compilations,
because they don't have to wait for the VM class mutex.
Contention on the VM class mutex has been shown to be very heavy
in very large applications that load very many classes.
Partially addresses issue #13807

Avoid locking the CHTable at end of compilation if possible

---

test/functional/cmdLineTests/gcCheck/build.xml
test/functional/cmdLineTests/gcCheck/gcchecktests.xml
test/functional/cmdLineTests/gcCheck/src/org/openj9/test/nogc/Main.java

- Fix GCCheck class not found error
- Add print info in Main class to be used as a required condition
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/12463
[skip ci]

Fix GCCheck class not found error

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp

In corner cases the compilation queue size can grow to tens of
thousand of entries. A large compilation queue adds overhead in
terms of memory and CPU (inserting an entry requires queue scanning
to find the proper place). To avoid these overheads, this commit
imposes a limit for the compilation queue size. When the limit is
reached, future asynchronous compilation requests for interpreted
methods are rejected, and the invocation count for the methods in
question is replenished. The rejected methods will continue to
run interpreted until their invocation count reaches 0 again.
Postponing such compilation requests is not expected to be detrimental
to performance because those methods would have waited a very
long time in the queue anyway.
This compilation queue size limit does not apply to …

Impose a limit on the compilation queue size

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

Prevent a FPE when casting a float that is larger then 0x7fffffff
to an int32.

Prevent FPE in scaleSizeBasedOnBlockFrequency() float to int32 cast

---

jcl/src/java.base/share/classes/java/lang/Thread.java

Replaced `JAVA11` `JPP` decoration w/ `Sidecar18-SE-OpenJ9` to allow `JDK8` `j.l.Thread.cleanup()` to invoke `TerminatingThreadLocal.threadTerminated()` if required.
`Sidecar18-SE` (internal IBM build) is unchanged because they are still not updated to `1.8.0_322` yet.
Note: IBM Java 8 build is at `jdk8u311-b11` which doesn't have `jdk.internal.misc.TerminatingThreadLocal`.
fixes https://github.com/eclipse-openj9/openj9/issues/14008

JDK8 Thread.cleanup requires TerminatingThreadLocal.threadTerminated()

---

jcl/src/java.base/share/classes/java/lang/Thread.java

Replace JAVA11 JPP decoration w/ Sidecar18-SE-OpenJ9 to allow JDK8
j.l.Thread.cleanup() to invoke TerminatingThreadLocal.threadTerminated()
if required.
Sidecar18-SE (internal IBM build) is unchanged because they are still
not updated to 1.8.0_322.
Port of https://github.com/eclipse-openj9/openj9/pull/14069 for the 0.30 release.

(v0.30.0-release) JDK8 Thread.cleanup requires TerminatingThreadLocal.threadTerminated()

---

runtime/vm/CMakeLists.txt
runtime/vm/MHInterpreter.inc
runtime/vm/module.xml

As suggested in https://github.com/eclipse-openj9/openj9/pull/13992#discussion_r757599763.
Also, cleanup `MHInterpreter.inc`:
* fix table of names for tracing
* add missing `#endif` comments

Compile MHInterpreter code only if OPT_METHOD_HANDLE

---

runtime/compiler/optimizer/J9ValuePropagation.cpp

The transformed sequence contains OSR points that don't correspond properly to the bytecode.
Additionally, prevent the transformation under AOT when we have only a type bound, as is already done for the fixed-type case.
Issue: #14014

Prevent VP Object.clone transformation under involuntary OSR

---

CONTRIBUTING.md
doc/build-instructions/Build_Instructions_V11.md
doc/build-instructions/Build_Instructions_V17.md
doc/build-instructions/Build_Instructions_V8.md
doc/release-notes/0.15/0.15.md

Updated to reflect the change from github organization 'eclipse' to 'eclipse-openj9'.

Correct URLs targeting https://eclipse-openj9.github.io/openj9-docs

---

runtime/ddr/overrides-vm
runtime/ddr/vmddrstructs.properties
runtime/oti/j9cp.h
runtime/oti/j9nonbuilder.h
runtime/util/annhelp.c
runtime/util/hshelp.c
runtime/vm/ValueTypeHelpers.cpp
runtime/vm/createramclass.cpp
runtime/vmchk/checkclasses.c
runtime/vmchk/checkmethods.c

This is in response to https://github.com/eclipse-openj9/openj9/pull/13836#discussion_r761245514.
It is a pointer to `J9ConstantPool` (not `UDATA`): declare it as such and remove the (now redundant) casts where it is used.
Add a DDR type override to avoid compatibility problems with system dumps from older VMs.

Clarify J9Class.ramConstantPool

---

runtime/j9vm/exports.cmake
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/javanextvmi.c
runtime/redirector/forwarders.m4

Required by
* 8276422: Add command-line option to disable finalization
This will not be needed until the openj9-staging branch promotes, but it is safe to include now.

Define JVM_IsFinalizationEnabled() for Java 18+

---

runtime/gc_base/GenerationalAccessBarrierComponent.cpp
runtime/gc_base/GenerationalAccessBarrierComponent.hpp
runtime/gc_base/ObjectAccessBarrier.cpp
runtime/gc_base/ObjectAccessBarrier.hpp
runtime/gc_base/accessBarrier.cpp
runtime/gc_glue_java/GlobalCollectorDelegate.cpp
runtime/gc_modron_standard/ReadBarrierVerifier.cpp
runtime/gc_modron_standard/ReadBarrierVerifier.hpp
runtime/gc_modron_standard/StandardAccessBarrier.cpp
runtime/gc_modron_standard/StandardAccessBarrier.hpp
runtime/gc_vlhgc/VLHGCAccessBarrier.cpp
runtime/gc_vlhgc/VLHGCAccessBarrier.hpp
runtime/vm/segment.c

These changes implement the the SATB access barriers, these have been adapted from the Realtime access barriers.
- Removed Double Barrier Code, Standard SATB does not make use of it
Adapted the following barrier from realtime for Standard SATB:
- forcedToFinalizableObject
- referenceGet
- referenceReprocess
- jniDeleteGlobalReference
- ~storeObjectToInternalVMSlotImpl~
- ~readObjectFromInternalVMSlotImpl~
- stringConstantEscaped / checkStringConstantsLive
checkClassLive

Standard SATB Barrier Implementation

---

jcl/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ProgrammableInvoker.java
runtime/oti/VMHelpers.hpp
runtime/tests/clinkerffi/downcall.c
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/FFITypeHelpers.hpp
runtime/vm/OutOfLineINL_jdk_internal_foreign_abi_ProgrammableInvoker.cpp
test/functional/Java17andUp/src/org/openj9/test/java/lang/DummyClass.java
test/functional/Java17andUp/src_170/org/openj9/test/jep389/downcall/InvalidDownCallTests.java
test/functional/Java17andUp/src_170/org/openj9/test/jep389/downcall/MultiCallTests.java
test/functional/Java17andUp/src_170/org/openj9/test/jep389/downcall/MultiThreadingTests1.java
test/functional/Java17andUp/src_170/org/openj9/test/jep389/downcall/MultiThreadingTests2.java
test/functional/Java17andUp/src_170/org/openj9/test/jep389/downcall/MultiThreadingTests3.java
test/functional/Java17andUp/src_170/org/openj9/test/jep389/downcall/MultiThreadingTests4.java
test/functional/Java17andUp/src_170/org/openj9/test/jep389/downcall/PrimitiveTypeTests1.java
test/functional/Java17andUp/src_170/org/openj9/test/jep389/downcall/PrimitiveTypeTests2.java
test/functional/Java17andUp/src_170/org/openj9/test/jep389/downcall/PrimitiveTypeTests3.java
test/functional/Java18andUp/build.xml
test/functional/Java18andUp/playlist.xml
test/functional/Java18andUp/src/org/openj9/test/jep419/downcall/InvalidDownCallTests.java
test/functional/Java18andUp/src/org/openj9/test/jep419/downcall/MultiCallTests.java
test/functional/Java18andUp/src/org/openj9/test/jep419/downcall/MultiThreadingTests1.java
test/functional/Java18andUp/src/org/openj9/test/jep419/downcall/MultiThreadingTests2.java
test/functional/Java18andUp/src/org/openj9/test/jep419/downcall/MultiThreadingTests3.java
test/functional/Java18andUp/src/org/openj9/test/jep419/downcall/MultiThreadingTests4.java
test/functional/Java18andUp/src/org/openj9/test/jep419/downcall/PrimitiveTypeTests1.java
test/functional/Java18andUp/src/org/openj9/test/jep419/downcall/PrimitiveTypeTests2.java
test/functional/Java18andUp/testClinkerFfi.xml

The change is to update the code specific to the FFI downcall for
primitives to accommodate the latest APIs of JEP419 in Java18.
Fixes: #14013

Update the FFI downcall code for primitives against JEP419 in Java18

---

jcl/src/java.base/share/classes/java/lang/Object.java

Required by:
* 8276447: Deprecate finalization-related methods for removal
This only updates `java.lang.Object` so openjdk code which suppresses "removal" warnings, but not "deprecation" warnings will continue to compile.

Mark Object.finalize() for removal in Java 18+

---

runtime/compiler/optimizer/J9ValuePropagation.cpp

The transformed sequence contains OSR points that don't correspond properly to the bytecode.
Additionally, prevent the transformation under AOT when we have only a type bound, as is already done for the fixed-type case.
Fixes: #14014

(0.30.0) Prevent VP Object.clone transformation under involuntary OSR

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/compile/J9SymbolReferenceTable.hpp

Find or fabricate an array shadow symbol reference for the field of a flattened array element. 
Depends on 

Add findOrFabricateFlattenedArrayElementFieldShadowSymbol

---

test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLOpenJ9.xml

In the default class sharing mode, if the SCC cannot be started up 
JVM will silently ignore the errors and start up without SCC. 
Add a test case to enable verbose message to show the start up 
error for debugging purpose.
issue #13841

Add a test case in ShareClassesCML with verbose output enabled

---

runtime/jcl/common/java_lang_Class.cpp
runtime/jcl/common/stdinit.c
runtime/oti/VMHelpers.hpp
runtime/oti/j9nonbuilder.h
runtime/sunvmi/sunvmi.c
runtime/vm/NativeHelpers.cpp

Added `J9JavaVM.jlrMethodInvokeMH` and assigned `java.lang.reflect.Method.invoke(Object,Object[],Class<?>)`;
`VMHelpers.hpp:isReflectionMethod()` recognizes `jlrMethodInvokeMH`;
Updated other frame iterator functions accordingly.
[JEP 416](https://github.com/eclipse-openj9/openj9/issues/13852) uses `java.lang.reflect.Method.invoke(Object obj, Object[] args, Class<?> caller)` [1] instead of `java.lang.reflect.Method.invoke(Object obj, Object... args)` which is invoked by earlier Java levels or Java 18 w/ JEP 416 disabled.
Verified this fixes the issue https://github.com/eclipse-openj9/openj9/issues/14136 in default mode and `-Xjit:count=0` as well.
Note: there are a few references to `javaVM->jlrMethodInvoke` (`java.lang.reflect.Method.invoke(Object,Object[],Class<?>)`) within JIT such as …

JDK18 isReflectionMethod checks Method.invoke(Object,Object[],Class<?>)

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp

- update MemberName ref kind based on resolved method
Fixes: #13996, Fixes: #13997

Rewrite MN.resolve logic on updating method flags

---

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/J9InternalCheckpointHookAPI.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/JVMCheckpointException.java

Add user hooks capabilities
This is a first pass of adding user hooks. A subsequent PR will be
created to prevent deadlocks.
Also, re-enable security checks for JDK17+, it is likely users will
continue to use them until they are finally removed.
Additional, add helpfull messages indicating what the problem might be
if `isCRIUSupportEnabled()` returns false.
Also, delay criu library load until `isCRIUSupportEnabled()` is called
to avoid throwing exceptions in the class initializer.

Add user hooks capabilities

---

runtime/compiler/optimizer/IdiomTransformations.cpp

- Fixes https://github.com/eclipse-openj9/openj9/issues/14072

Don't create non-relocatable table during AOT in IdiomRecognition

---

runtime/jcl/common/system.c

Required by JEP 400: UTF-8 by Default.
Related to https://github.com/eclipse-openj9/openj9/issues/13470
fixes an internal workitem RTC 146694.

JDK18 specifies file.encoding UTF-8 when w/o command line defines

---

runtime/compiler/optimizer/IdiomTransformations.cpp

- Fixes https://github.com/eclipse-openj9/openj9/issues/14072
Port of https://github.com/eclipse-openj9/openj9/pull/14144 for the 0.30 release.

(0.30.0) Don't create non-relocatable table during AOT in IdiomRecognition

---

buildenv/jenkins/variables/defaults.yml

Cherry pick of https://github.com/eclipse-openj9/openj9/pull/14155 for the 0.30.0 release.

(0.30.0) Update OpenSSL except Windows to 1.1.1m

---

sourcetools/j9constantpool/com/ibm/oti/VMCPTool/Main.java
sourcetools/j9constantpool/com/ibm/oti/VMCPTool/PrimaryItem.java
sourcetools/j9constantpool/com/ibm/oti/VMCPTool/Util.java

This is to accommodate incompatible references when a J9 flag enabled or not such as:
```
<fieldref class="java/lang/Thread" name="eetop" signature="J" cast="struct J9VMThread *" flags="opt_ojdkThreadSupport"/>
<fieldref class="java/lang/Thread" name="threadRef" signature="J" cast="struct J9VMThread *" flags="!opt_ojdkThreadSupport"/>
```

VMCPTool adds a NOT operator ! for J9 flags

---

runtime/compiler/env/j9method.cpp

Include J9VMInternals.getSuperclass in the list of methods to avoid
recognizing in FSD mode.  This is to prevent special transformation
of this method to JITHelpers.getSuperclass which causes problems if
a decompilation is triggered within.
Issue https://github.com/eclipse-openj9/openj9/issues/14115

Prevent recognition of J9VMInternals.getSuperclass under FSD

---

runtime/compiler/env/j9method.cpp

Include J9VMInternals.getSuperclass in the list of methods to avoid
recognizing in FSD mode.  This is to prevent special transformation
of this method to JITHelpers.getSuperclass which causes problems if
a decompilation is triggered within.
Fixes: #14115
Port of https://github.com/eclipse-openj9/openj9/pull/14163 for the 0.30 release.

(0.30.0) Prevent recognition of J9VMInternals.getSuperclass under FSD

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/env/J9ClassEnv.hpp
runtime/compiler/net/MessageTypes.cpp
runtime/compiler/net/MessageTypes.hpp
runtime/compiler/optimizer/J9TransformUtil.cpp
runtime/compiler/optimizer/J9TransformUtil.hpp

Update `TransformUtil` to calculate element address with element stride and add `flattenedArrayElementSize` to `ClassEnv`.

Add calculate element address with element stride

---

test/functional/Java14andUp/build.xml
test/functional/Java14andUp/playlist.xml
test/functional/Java14andUp/src/org/openj9/test/utilities/RecordClassGenerator.java
test/functional/Java15andUp/build.xml
test/functional/Java15andUp/playlist.xml
test/functional/Java15andUp/src/org/openj9/test/utilities/SealedClassGenerator.java
test/functional/Java16andUp/build.xml
test/functional/Java16andUp/modules/org.openj9test.modularity.moduleX/org/openj9/test/modularity/pkgD/Test_SubClass.java
test/functional/Java16andUp/modules/org.openj9test.modularity.moduleY/org/openj9/test/modularity/pkgB/Test_SubClass.java
test/functional/Java16andUp/playlist.xml
test/functional/Java16andUp/src/org/openj9/test/utilities/SealedClassGenerator.java

Remove `--enable-preview` for `JEP 358/360/384/389/397` tests
Note: this fixes `Jep360Tests_0_FAILED`, `Jep397Tests_testSubClassOfSealedSuperFromDifferentModule_0_FAILED` & `Jep397Tests_testSubClassOfSealedSuperFromDifferentPackageInSameUnamedModule_0_FAILED ` at https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/22/tapResults/.
fyi @llxia 

Remove --enable-preview for JEP 358/360/384/389/397 tests

---

jcl/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ProgrammableInvoker.java

The change is to unify the code of calculating the hashcode for
the function signature and arguments to ensure it works on both
JDK17 and JDK18.
Fixes: #14169

Unify the code of hashing function signature & arguments in downcall

---

runtime/compiler/aarch64/codegen/MemoryReference.hpp

This is a part of a series of PRs to implement https://github.com/eclipse/omr/issues/5173.
This PR introduces static factory methods for MemoryReference objects into aarch64 codegen.
As we have J9MemoryReference class in OpenJ9 project, we must add the declaration of static factory methods to MemoryRererence class before we add implementation of factory methods to OMR project.

AArch64: Provide factory methods for MemoryReference objects

---

test/functional/cmdLineTests/gcCheck/gcchecktestsMetronome.xml
test/functional/cmdLineTests/gcCheck/playlist.xml

Duplicated the cmdLineTester_GCCheck test so the Metronome (Mode301) variation can run `!gccheck all,noobjectheap`. The success condition also needed to change in this case from `Checking HEAP...done` to `Done (`.
Fixes https://github.com/eclipse-openj9/openj9/issues/14118

Run GCCheck test on Metronome with noobjectheap option

---

LICENSE
longabout.html

Cherry pick of https://github.com/eclipse-openj9/openj9/pull/14161 for the 0.30 release.

(0.30.0) Update license copyrights missed by previous commits

---

runtime/tests/jsig/main.c

- The AIX XLC compiler does not accept a repeated use of certain keywords. `volatile` is one of those keywords.
- The AIX typedef of sig_atomic_t includes the keyword `volatile` and reports a syntax error for a statement such as:
```
./runtime/tests/jsig/main.c:61:8: error: duplicate 'volatile' declaration specifier [-Werror,-Wduplicate-decl-specifier]
static volatile sig_atomic_t handlerCalled = 0;
^
1 error generated.
```
Fixes: #14183 
Needs labels: os:aix and jdk17

AIX: correct a variable declaration by removing the keyword `volatile`

---

runtime/compiler/aarch64/codegen/ARM64JNILinkage.cpp
runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/codegen/J9MemoryReference.hpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/aarch64/codegen/MemoryReference.hpp

This is a part of a series of PRs to implement https://github.com/eclipse/omr/issues/5173.
Use factory methods of MemoryReference class to instantiate MemoryReference objects.
Depends on:
https://github.com/eclipse-openj9/openj9/pull/14195
https://github.com/eclipse/omr/pull/6279

AArch64: Use factory methods for creating MemoryReference

---

buildspecs/core.feature
buildspecs/j9.flags
jcl/jpp_configuration.xml
jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
jcl/src/java.base/share/classes/java/lang/Thread.java
jcl/src/java.base/share/classes/java/lang/ThreadGroup.java
runtime/cmake/options.cmake
runtime/include/j9cfg.h.in
runtime/jvmti/jvmtiThreadGroup.c
runtime/oti/vmconstantpool.xml

Added `opt_ojdkThreadSupport` flag and decorate the behaviour change w/ `J9VM_OPT_OJDK_THREAD_SUPPORT`;
Replaced `j.l.Thread.threadRef` with `eetop`;
Replaced `j.l.Thread.isDaemon` with `daemon`;
Replaced `j.l.Thread.runnable` with `target`;
Replaced `j.l.Thread.lock` with `blockerLock`;
Replaced `j.l.ThreadGroup.numThreads` with `nthreads`;
Replaced `j.l.ThreadGroup.numGroups` with `ngroups`;
Replaced `j.l.ThreadGroup.childrenThreads` with `threads`;
Replaced `j.l.ThreadGroup.childrenGroups` with `groups`;
Replaced `j.l.ThreadGroup.isDaemon` with `daemon`;
Updated references accordingly;
Minor refactoring at methods affected.
fyi @pshipton @0xdaryl 

Adopt RI java.lang.Thread/ThreadGroup w/ opt_ojdkThreadSupport

---

runtime/tests/jsig/main.c

Fixes #14183 for v0.30.0 branch
Added per comment in #14184

(0.30.0) AIX: correct a variable declaration by removing the keyword volatile

---

runtime/bcverify/staticverify.c

The change is to directly throw the VerifyError for the bad offset
in stackmaps without delay during the static verification so as
to match the RI's behavior on Java18.
Internal ref 146697

Throw the VerifyError in the case of the bad offset in stackmaps

---

runtime/shared_common/CacheLifecycleManager.cpp

https://github.com/eclipse-openj9/openj9/pull/13925 modified the
declaration of nattach from IDATA to UDATA. Fix the `nattach > 0`
comparison.
Fixes https://github.com/eclipse-openj9/openj9/issues/14218

Shared cache - fix comparison > 0 after nattach declaration change

---

jcl/src/java.base/share/classes/com/ibm/gpu/spi/GPUAssistHolder.java
jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
jcl/src/java.base/share/classes/java/lang/System.java
test/functional/cmdLineTests/gputests/build.xml
test/functional/cmdLineTests/gputests/gputests.xml
test/functional/cmdLineTests/gputests/gputests_exclude.xml
test/functional/cmdLineTests/gputests/playlist.xml

Checking of properties `com.ibm.gpu.enable` or `com.ibm.gpu.enforce` was occurring before they were available and so the CUDA GPU sort assist could not be enabled (with either of those properties).
This delays the call to `System.initGPUAssist()` to a point where the relevant properties are available and adds a test to verify that.

Fix GPUAssist enablement

---

jcl/src/java.base/share/classes/java/lang/System.java

Noticed while working on #14222:
* improve javadoc
* sort list of property names guaranteed by `getProperty()`
* remove dead code
* remove redundant initializations
* remove redundant uses of value returned by `Objects.requireNonNull()`

Minor improvements to java.lang.System

---

test/functional/cmdLineTests/gputests/playlist.xml

It does not (yet) apply to Java 8.

Fix GPUAssist enablement test

---

runtime/compiler/control/CompilationController.cpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/net/Message.cpp
runtime/compiler/runtime/CRuntimeImpl.cpp
runtime/compiler/runtime/ClassUnloadAssumption.cpp
runtime/compiler/runtime/HookHelpers.cpp
runtime/compiler/runtime/JITServerStatisticsThread.cpp
runtime/compiler/runtime/JitRuntime.cpp

`TR_VerboseLog::CriticalSection` should be preferred whenever it is straightforward to use.

Replace vlogAcquire()/vlogRelease() pairs with CriticalSection

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/CompilationThread.hpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/runtime/CodeRuntime.hpp
runtime/compiler/runtime/RelocationRuntimeLogger.cpp
runtime/compiler/runtime/Runtime.cpp

Currently, only a global rtLog is created when `rtLog=<log name>,aotrtDebugLevel=<nnn>` is specified. While writing to the log is done with a lock, the lock is not acquired at the start of a compile (nor should it). This means that when, for example, logging an AOT load, relo records from two different aot loads can get interleaved, making it difficult to impossible to make sense of the log.
This PR ensures that we open an rtLog per compilation thread. For non compilations thread, the global rtLog will still be used.

Open RT Log per compilation thread

---

jcl/src/java.base/share/classes/java/lang/Thread.java

There's no need to inflate the anticipated number of entries to be added to the map.
Also fix a use of raw types and do some whitespace cleanup.
Fixes: #14244.

Simplify capacity of HashMap

---

runtime/compiler/optimizer/IdiomTransformations.cpp

This commit disables array subrange overlap test
to allow arraycopy optimizations.
Signed-off-by: Siri Sahithi Ponangi <sahithi.ponangi@unb.ca>

AArch64: Disabling Subrange Overlap test

---

runtime/bcutil/cfreader.c

The change is to move the check on the constant module/package
flag from readPool() to checkPool() to ensure a module class with
ACC_MODULE set is correctly captured/rejected as NoClassDefFoundError
prior to checkPool() during the static verification.
Internal ref 146836

Move the check on the constant module/package flag to checkPool()

---

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java

Replaced `String.isBlank()` w/ `String.isEmpty()`.
Keep the leading or trailing spaces of `entry` in case the `name`/`value` retrieved from `envFileReader.readLine()` contain spaces.
closes https://github.com/eclipse-openj9/openj9/issues/14248

Use String.isEmpty() for Java 8 compatibility

---

jcl/src/java.base/share/classes/java/lang/Thread.java

See
https://bugs.openjdk.java.net/browse/JDK-8277861
http://cr.openjdk.java.net/~iris/se/18/build/latest/api/java.base/java/lang/Thread.html#stop()

Thread.stop() is deprecated for removal in jdk18

---

test/functional/cmdLineTests/modularityddrtests/modularityddrtests11.xml
test/functional/cmdLineTests/modularityddrtests/modularityddrtests17.xml
test/functional/cmdLineTests/modularityddrtests/playlist.xml

Fixes https://github.com/eclipse-openj9/openj9/issues/13965
Grinders, which passed:
jdk11 - https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/507/
jdk17 - https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/506/
jdk18 - https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/505/

Fix ddr modularity test, jdk17+ doesn't support --illegal-access option

---

jcl/src/java.base/share/classes/java/lang/System.java

Add CRIU support system property
Related to #14016

Add CRIU support system property

---

runtime/compiler/runtime/Listener.cpp

Emit the start time in the jitserver verbose log

---

runtime/jilgen/module.xml

This fixes broken build on RISC-V

RISC-V: fix UMA-based build to build and run `constgen`

---

runtime/jcl/module.xml

The 'se18' export group was removed by #13963.

Fix UMA builds for Java 18+

---

runtime/j9vm/jvm.c
runtime/redirector/redirector.c

JNI_GetDefaultJavaVMInitArgs is used by the launcher code to get default stack size.
This change makes the launcher respect J9_OS_STACK_SIZE as a minimum when creating
the main JVM thread.
Partially addresses https://github.com/eclipse-openj9/openj9/issues/12785

Provide default stack size from VM

---

jcl/src/java.base/share/classes/java/lang/System.java
runtime/jcl/common/system.c

As per JEP 400 specification, if `file.encoding` is set to `COMPAT` via `-Dfile.encoding=COMPAT`, the default charset will be same as `JDK17` and earlier. The system property value of `file.encoding` will be set to the name of that charset.
closes #14233 

JEP 400 maps -Dfile.encoding=COMPAT to platform encoding

---

runtime/gc_modron_startup/mminit.cpp

Skip `j9gc_finalizer_startup` if the finalization is disabled.
related to https://github.com/eclipse-openj9/openj9/issues/14131  https://github.com/eclipse-openj9/openj9/issues/14049
fyi @pshipton 

JDK18+ disable finalization accordingly to command line option

---

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
jcl/src/java.base/share/classes/java/lang/StringBuffer.java
jcl/src/java.base/share/classes/java/lang/StringBuilder.java

Added a precautionary condition check `count >= 0`;
Changed `InvalidObjectException` to `StreamCorruptedException` to match RI behaviours.
related internal RTC 146534

Validate the count field when deserializing StringBuffer/StringBuilder

---

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
jcl/src/java.base/share/classes/java/lang/StringBuffer.java
jcl/src/java.base/share/classes/java/lang/StringBuilder.java

Added a precautionary condition check `count >= 0`;
Changed `InvalidObjectException` to `StreamCorruptedException` to match RI behaviours.
Cherry-pick https://github.com/eclipse-openj9/openj9/pull/14314

(v0.30.0-release) Validate the count field when deserializing StringBuffer/StringBuilder

---

buildenv/jenkins/common/variables-functions.groovy
buildenv/jenkins/variables/defaults.yml

Cherry pick auto-download from https://github.com/eclipse-openj9/openj9/pull/14309
and port the openssl 1.1.1m changes for Windows.

(0.30.0) Auto-download OpenSSL on Windows

---

doc/release-notes/0.30/0.30.md

See https://github.com/eclipse-openj9/openj9/pull/14042
Cherry pick https://github.com/eclipse-openj9/openj9/pull/14060 for the 0.30 release.

(0.30.0) Add release documentation for java option `-XX:[+|-]EnsureHashed`

---

test/functional/RasapiTest/test.xml

The default -Xmx is 25% of physical RAM, which can be quite big causing
core files of excessive size to be created by the test.
Fixes https://github.com/eclipse-openj9/openj9/issues/14193

Set a small -Xmx for testing RAS

---

runtime/compiler/aarch64/runtime/PicBuilder.spp
runtime/compiler/aarch64/runtime/Recompilation.spp

This commit changes two AArch64 asm files, loading function pointers
from memory using a new macro LOAD_FUNC_PTR().  It absorbs the
difference between Linux and macOS.

AArch64: Load function pointers from memory using a macro

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java
runtime/bcutil/ClassFileOracle.cpp
runtime/bcutil/ClassFileOracle.hpp

For JEP416, a private adapter method, which accepts an additional `Class<?>`
parameter, is needed for `ClassLoader.registerAsParallelCapable(Class<?>)`.
`@CallerSensitiveAdapter` is a variant of `@CallerSensitive`. So, treat
`@CallerSensitiveAdapter` similar to `@CallerSensitive` in
- `inlInternalsNewInstanceImpl`
- `inlVMGetStackClassLoader`
- `inlVMGetStackClass`
Closes: https://github.com/eclipse-openj9/openj9/issues/14133
Related: https://github.com/eclipse-openj9/openj9/issues/13852

[JEP416] Add caller sensitive adapter method in java.lang.ClassLoader

---

runtime/compiler/optimizer/NewInitialization.cpp

New initialization is enabled on 64-bit compressed refs in addition to
32-bit. Array accesses use aladd instead of aiadd on 64-bit compressed
refs and so the code that examines array accesses should check for a
long constant offset (in addition to int constant offset as is the case
presently). This would allow the code to engage and attempt
transformations on 64-bit compressed refs for arrays. Since the rest of
the data structures are using 32-bit offsets we restrict the actual
value of the long constant to be in the 32-bit range since we do not
believe this to be a significant limiting factor in practice.
Signed-off-by: Vijay Sundaresan vijaysun@ca.ibm.com

Process aladd offsets that can fit in 32 bits

---

runtime/compiler/env/J9ObjectModel.cpp
runtime/compiler/env/J9ObjectModel.hpp

The definition of J9::ObjectModel::getObjectAlignmentInBytes needs to be overridden for the JIT server so that it uses the object alignment from the vmInfo if necessary.
Fixes: #14286

Modify getObjectAlignmentInBytes for jitserver

---

runtime/compiler/control/DLLMain.cpp
runtime/compiler/control/J9Options.cpp
runtime/gc_modron_startup/mminit.cpp
runtime/oti/j9consts.h
runtime/oti/jvminit.h
runtime/vm/jvminit.c

This PR creates a new option, called `-Xtune:throughput`, under which the JVM will favor throughput over other performance metrics. In particular, if not explicitly provided, the initial heap size (`-Xms`) will be set to the maximum heap size value (`-Xmx`). Moreover, the JIT will internally set some options to optimize more aggressively the code.
Another new option is `-Xtune:quickstart` which is set to be an alias of `-Xquickstart`.
The 3 options `-Xtune:virtualized`, `-Xtune:throughput` and `-Xtune:quickstart` are mutually exclusive (since they pull performance metrics in different directions) and the last occurrence on the command line takes effect (this is different than the old implementation where quickstart mode had precedence over -Xtune:virtualized).
The JIT code that was …

Create -Xtune:throughput option and set options that favor throughput plus other cleanup

---

test/functional/RasapiTest/test.xml

-Xmx32M is too small, causes OOM on some platforms such as Windows and
the older AIX machines.
Increase to 512M. With smaller values OOM was still seen on AIX.
See https://github.com/eclipse-openj9/openj9/pull/14310
Tested via grinder
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/534 - old AIX
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/533 - new AIX
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/532 - Windows

Set an appropriate -Xmx for testing RAS

---

runtime/j9vm/asgct.cpp
runtime/vm/jniinv.c

- make GetEnv to fetch JNIEnv safe to call from a signal handler
- disallow ASGCT if -Xrs is specified
- use the incoming JNIEnv as the target thread
- for now, allow the call only on the current thread

Updates to AsyncGetCallTrace

---

test/functional/cmdLineTests/cmdLineTest_J9tests/j9tests_consoleUpTo17.xml
test/functional/cmdLineTests/cmdLineTest_J9tests/playlist.xml

Move the console encoding tests that are only supported up to jdk17 to a
different file and test case name so they don't run and fail on jdk18.
From jdk18 the console does not use the file.encoding but the
native.encoding. native.encoding cannot be overridden on the command
line.
See JEP 400 UTF-8 by Default https://openjdk.java.net/jeps/400
Fixes https://github.com/eclipse-openj9/openj9/issues/14321
Tested via grinders:
jdk17 - https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/537- ran J9test_console, J9test_consoleUpTo17 
jdk18 - https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/539 - ran just J9test_console

Separate console encoding tests that aren't supported on jdk18

---

jcl/src/java.base/share/classes/java/lang/System.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/MemoryMXBeanImpl.java
jcl/src/java.management/share/classes/java/lang/management/MemoryMXBean.java

```
@Deprecated(forRemoval=true, since="18")
java.lang.System.runFinalization();
@Deprecated(forRemoval=false, since="18")
java.lang.management.MemoryMXBean.getObjectPendingFinalizationCount();
```
Fixes an internal RTC item 146926.
Related https://github.com/eclipse-openj9/openj9/issues/14049

JDK18 deprecates getObjectPendingFinalizationCount & runFinalization

---

jcl/src/java.base/share/classes/java/lang/Access.java
jcl/src/java.base/share/classes/java/lang/System.java
runtime/compiler/env/j9method.cpp
runtime/jcl/common/stdinit.c
runtime/oti/vmconstantpool.xml

Expand `JDK18` methods to `JDK17`:
```
Access.encodeASCII()
NativeLibraries.load(Ljdk/internal/loader/NativeLibraries$NativeLibraryImpl;Ljava/lang/String;ZZZ)Z
```
Get system property `os.version` before properties are initialized.
JDK17 `openj9-staging` builds w/ this PR & https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/59, `-version` output is:
```
openjdk version "17.0.2-internal" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2-internal+0-adhoc.jasonfeng.openj9-openjdk-jdk17)
Eclipse OpenJ9 VM (build stringaccess-4ba73dfa870, JRE 17 Mac OS X amd64-64-Bit Compressed References 20220120_000000 (JIT enabled, AOT enabled)
OpenJ9   - 4ba73dfa870
OMR      - b128a661c
JCL      - a0a685cf71d based on jdk-17.0.2+8)
```
**Note**: this PR requires JDK17 `openj9-staging` promotion, …

JDK17 adds Access.encodeASCII() & NativeLibraries.load()

---

jcl/src/java.base/share/classes/java/lang/Access.java
jcl/src/java.base/share/classes/java/lang/System.java
runtime/compiler/env/j9method.cpp
runtime/jcl/common/stdinit.c
runtime/oti/vmconstantpool.xml

Expand `JDK18` methods to `JDK17`:
```
Access.encodeASCII()
NativeLibraries.load(Ljdk/internal/loader/NativeLibraries$NativeLibraryImpl;Ljava/lang/String;ZZZ)Z
```
Get system property `os.version` before properties are initialized.
Cherry-pick https://github.com/eclipse-openj9/openj9/pull/14327

(v0.30.0-release) JDK17 adds Access.encodeASCII() & NativeLibraries.load()

---

runtime/compiler/optimizer/J9Optimizer.cpp

- move VectorAPIExpansion as early as possible to allow other optimizations
to be applied after API calls were scalarized or vectorized(PRE, striding, etc)
- VectorAPIExpansion itself requires PRE to happen, so add loop canonicalization and
PRE using IfVectorAPI flag
- during cold and warm, VectorAPIExpansion does not always happen anyway, so we
can treat those as a separate issue.

Run VectorAPIExpansion earlier in hot, scorching, and AOT strategies

---

runtime/j9vm/exports.cmake
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/jvm.c
runtime/redirector/forwarders.m4
runtime/vm/jnimisc.cpp

Changes to NativeLibraries.load() and JVM_LoadLibrary() have been back-ported from JDK18:
* 8275703: System.loadLibrary fails on Big Sur for libraries hidden from filesystem
See also #13844, #13898.

Change signatures in JDK17

---

runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/control/JITServerHelpers.hpp
runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp

The new _arrayElementSize component in ClassInfo now caches the constant
(at runtime) element size of an array class. This component is now used
by J9::ClassEnv::flattenedArrayElementSize to avoid unnecessary messages
to the client.
Fixes: #14323

Cache client array class element size

---

buildenv/jenkins/common/variables-functions.groovy
buildenv/jenkins/variables/defaults.yml
doc/build-instructions/Build_Instructions_V11.md
doc/build-instructions/Build_Instructions_V17.md
doc/build-instructions/Build_Instructions_V8.md

Issue: #14302:
* update build variables
* update build instructions

Use --with-openssl=fetched on Windows

---

runtime/compiler/control/J9Options.cpp

When a client wants to take advantage of the JITServer AOT cache
feature it will generate as many AOT compilations as possible.
AOT bodies have Guarded Counting Recompilation (GCR) IL trees in
them, to ensure that frequently called bodies are recompiled.
Experiments have shown that GCR counting can have a negative effect
on performance and we would like to minimize the amount of time
GCR counting is done.
Existing code includes a provision to stop counting when too many
methods have been queued for compilation due to GCR. This feature is
controlled by an option: GCRQueuedThresholdForCounting, but its default
value disables this feature.
In this commit, we set GCRQueuedThresholdForCounting=200 when the
JVM is running in client mode and is using the JITServer AOT cache.
This value can still …

Change GCRQueuedThresholdForCounting value for JITServer AOT cache

---

runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/VectorAPIExpansion.cpp

- signatures for many VectorSupport intrinsics have changed in Java 18
- change the ones we recognized so far
- this change will disable VectorAPI acceleration in Java 17

Switch to Java 18 method signatures for Vector API

---

runtime/compiler/control/CompilationThread.cpp

This PR fixes `printf` format warnings (treated as errors) in code under the `DEBUG` build time flag in the JIT.

Fix debug build of the compiler component

---

runtime/vm/jvminit.c

This commit enables JIT and AOT on AArch64 macOS.

AArch64 macOS: Enable JIT and AOT

---

jcl/src/java.base/share/classes/java/lang/J9VMInternals.java

Throw correct exception when initialization already failed
When initialization has already failed for a class before, throw
`NoClassDefFoundError` with `ExceptionInInitializerError` as its cause
instead of the `Throwable` that caused the first initialization failure.
Supersedes #14291 (renamed branch)
Fixes: #14080

Throw correct exception when initialization already failed

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/runtime/JITServerStatisticsThread.cpp

This PR adds the following `-Xjit:` command line options for JITServer that can be useful for performance tuning:
- `scratchSpaceFactorWhenJITServerWorkload` (default 2) - determines the scratch memory limit for out-of-process compilations at JITServer;
- `reconnectWaitTimeMs` (default 1000 ms) - determines the wait time for the client before attempting to reconnect to the JITServer after a network failure.
The JITServer statistics thread now also uses the value of the existing `timeBetweenPurges` option instead of a hard-coded value.

Make some hard-coded JITServer settings configurable

---

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/LibraryResolverFactory.java

For example, on AIX, it's normal for both
```
/usr/lib/libC.a
/usr/lib/libc.a
```
to exist. As long as the desired file is found, it should not issue a diagnostic about the other one.
(Discovered while investigating #14193.)

Fix inappropriate error about case-insensitive file match found

---

runtime/compiler/runtime/ClassUnloadAssumption.cpp

This commit adds calls to pthread_jit_write_protect_np() for AArch64
macOS.

AArch64 macOS: Add calls to pthread_jit_write_protect_np()

---

runtime/gc_base/RootScanner.cpp

Remove whitespace in RootScanner

Remove whitespace in RootScanner

---

test/functional/JIT_Test/playlist.xml
test/functional/VM_Test/j9vm.xml
test/functional/cmdLineTests/callsitedbgddrext/playlist.xml
test/functional/cmdLineTests/gcCheck/playlist.xml
test/functional/cmdLineTests/jvmtitests/playlist.xml
test/functional/cmdLineTests/pltest/playlist.xml
test/functional/cmdLineTests/xxargtest/playlist.xml

This commit exclude functional tests that fail on AArch64 macOS.

Exclude functional tests on AArch64 macOS

---

runtime/compiler/env/VMJ9Server.cpp

In an edge case, `TR_J9ServerVM::classHasBeenExtended()` currently waits for a client response while holding a client session ROM map lock. This PR changes the implementation of this method to release the lock while waiting for the response.

Do not wait for message under lock in TR_J9ServerVM::classHasBeenExtended

---

runtime/compiler/env/j9methodServer.cpp
runtime/compiler/env/j9methodServer.hpp

Since ROMClass serialization now includes all strings in the ROMClass, the implementation of this method is identical to the one in `TR_ResolvedJ9MethodBase` and can be removed.

Remove TR_ResolvedJ9JITServerMethod::fieldOrStaticName()

---

test/functional/cmdLineTests/gcRegressionTests/gcRegressionTests.xml
test/functional/cmdLineTests/gcRegressionTests/gcRegressionTests_excludes.xml
test/functional/cmdLineTests/gcRegressionTests/gcRotatingVerboseLogTests.xml
test/functional/cmdLineTests/gcRegressionTests/gcRotatingVerboseLogTests_excludes.xml
test/functional/cmdLineTests/gcRegressionTests/playlist.xml

- Enable GC rotating verbose log tests for jdk 11 and up
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/13891
- [skip ci]

Enable GC rotating verbose log tests for jdk 11 and up

---

jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java
runtime/oti/UnsafeAPI.hpp
runtime/vm/createramclass.cpp

`Unsafe.arrayIndexScale` is supposed to always return a power of 2, but the index scale of flattened arrays are not guaranteed to be a power of 2.

Throw an exception in arrayIndexScale when index scale is not a power of 2

---

jcl/src/java.management/share/classes/java/lang/management/BufferPoolMXBean.java
jcl/src/java.management/share/classes/java/lang/management/ClassLoadingMXBean.java
jcl/src/java.management/share/classes/java/lang/management/CompilationMXBean.java
jcl/src/java.management/share/classes/java/lang/management/DefaultPlatformMBeanProvider.java
jcl/src/java.management/share/classes/java/lang/management/GarbageCollectorMXBean.java
jcl/src/java.management/share/classes/java/lang/management/LockInfo.java
jcl/src/java.management/share/classes/java/lang/management/ManagementPermission.java
jcl/src/java.management/share/classes/java/lang/management/MemoryMXBean.java
jcl/src/java.management/share/classes/java/lang/management/MemoryManagerMXBean.java
jcl/src/java.management/share/classes/java/lang/management/MemoryNotificationInfo.java
jcl/src/java.management/share/classes/java/lang/management/MemoryPoolMXBean.java
jcl/src/java.management/share/classes/java/lang/management/MemoryType.java
jcl/src/java.management/share/classes/java/lang/management/MemoryUsage.java
jcl/src/java.management/share/classes/java/lang/management/MonitorInfo.java
jcl/src/java.management/share/classes/java/lang/management/OperatingSystemMXBean.java
jcl/src/java.management/share/classes/java/lang/management/PlatformLoggingMXBean.java
jcl/src/java.management/share/classes/java/lang/management/PlatformManagedObject.java
jcl/src/java.management/share/classes/java/lang/management/RuntimeMXBean.java
jcl/src/java.management/share/classes/java/lang/management/ThreadInfo.java
jcl/src/java.management/share/classes/java/lang/management/ThreadInfoAccessImpl.java
jcl/src/java.management/share/classes/java/lang/management/ThreadMXBean.java

Add module references;
Fix javadoc warnings.
The `Copyright` format change is required due to `warning: documentation comment not expected here` and `warnings found and -Werror specified`. Similar warning messages are in `java.base` module as well, and are ignored since `java.base` is part of `WARNING_MODULES`.
JDK19 builds w/ this PR and `-version` output:
```
openjdk version "19-internal" 2022-09-20
OpenJDK Runtime Environment (build 19-internal+0-adhoc.jasonfeng.openj9-openjdk-jdk)
Eclipse OpenJ9 VM (build doclint-3b4b997b371, JRE 19 Mac OS X amd64-64-Bit Compressed References 20220201_000000 (JIT enabled, AOT enabled)
OpenJ9   - 3b4b997b371
OMR      - e449b3f83
JCL      - b90944f187b based on jdk-19+7)
```
closes https://github.com/eclipse-openj9/openj9/issues/14404
Signed-off-by: …

JDK19 fix doclint:reference

---

test/functional/cmdLineTests/gcRegressionTests/playlist.xml

- Enable GCRotatingVerboseLogTests for ibm 8
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/13891
[skip ci]

Enable GCRotatingVerboseLogTests for ibm 8

---

runtime/cmake/options.cmake

Because the list of dynamic symbols is explicitly specified, it doesn't make any difference.
More detail available in https://github.com/eclipse-openj9/openj9/issues/7995#issuecomment-1027038399.

Don't use '-rdynamic' on Linux by default

---

runtime/stackmap/localmap.c

Mark receivers of all constructors as oslots

Mark receivers of all constructors as oslots

---

runtime/gc_vlhgc/SchedulingDelegate.cpp
runtime/gc_vlhgc/WriteOnceCompactor.cpp

Current rate is not quite correct since
1) it was not accounting for heap resizing changes, while it should
2) and accounting for sweep reclamation, while it should not
As a result of (1), during heap expansion (that is initially justified,
like ramp-up phase) we would underestimate heap consumption, what would
delay GMP kickoff, and in some cases we would be forced to expand even
more to be able to continue PGC. That could create positive feedback
where we would continue expanding till fully expanded.
The rate formula is completely changed to rely simply on current PGC
metrics:
consumed (survived) regions - freed (evacuated) regions
...as opposed to measuring the difference in heap occupancy between
previous and current GC.
In a stable state, those 2 approaches are very similar, but …

PGC consumption rate

---

runtime/compiler/control/CompilationThread.cpp

Don't set remoteCompReq flag if doing an AOT load

---

runtime/j9vm/java11vmi.c

Null check in trcModulesAddReadsModule uses wrong variable name.
Add missing case for when j9ToMod->moduleName is NULL because the
unnamed module is not ALL-UNNAMED
From https://github.com/eclipse-openj9/openj9/issues/14398#issuecomment-1026786169
Fixes https://github.com/eclipse-openj9/openj9/issues/14398

Fix check in trcModulesAddReadsModule function

---

runtime/j9vm/java11vmi.c

Null check in trcModulesAddReadsModule uses wrong variable name.
Add missing case for when j9ToMod->moduleName is NULL because the
unnamed module is not ALL-UNNAMED
Port of https://github.com/eclipse-openj9/openj9/pull/14432 to 0.31.0

(0.31.0) Fix check in trcModulesAddReadsModule function

---

test/functional/DDR_Test/build.xml

This commit changes a `<fail>` tag in the build.xml for DDR_Test into an
`<echo>` tag so that you can build and run functional tests on a platform
without DDR support.

Build functional tests without failing when DDR is not supported

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java
jcl/src/java.base/share/classes/java/lang/System.java
test/functional/JLM_Tests/playlist.xml
test/functional/Java8andUp/java8andUpSettings.mk
test/functional/Java8andUp/playlist.xml
test/functional/Jsr292/playlist.xml
test/functional/cmdLineTests/J9security/playlist.xml
test/functional/cmdLineTests/proxyFieldAccess/playlist.xml
test/functional/variables.mk

1. Consolidate security manager startup code invoked from
`ClassLoader.initializeClassLoaders` in `System.initSecurityManager` (new method).
2. As per the Java doc, the `java.security.manager` property should only be read
at startup. Example: If this property is initialized with `"disallow"` when the
JVM is started, then a security manager will not be set at startup and cannot
be set dynamically. Currently, this property is read in
`System.setSecurityManager`. If a user changes this property after startup, then
`System.setSecurityManager`'s behaviour will change after startup. This behaviour
does not follow the Java doc and reference implementation. To fix this issue,
the `java.security.manager` is only read once at startup in
`System.initSecurityManager`.
3. In JDK18, …

Update java.security.manager behaviour

---

runtime/stackmap/localmap.c

Mark receivers of all constructors as oslots
back port of https://github.com/eclipse-openj9/openj9/pull/14419

(0.31) Mark receivers of all constructors as oslots

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java
jcl/src/java.base/share/classes/java/lang/System.java
test/functional/JLM_Tests/playlist.xml
test/functional/Java8andUp/java8andUpSettings.mk
test/functional/Java8andUp/playlist.xml
test/functional/Jsr292/playlist.xml
test/functional/cmdLineTests/J9security/playlist.xml
test/functional/cmdLineTests/proxyFieldAccess/playlist.xml
test/functional/variables.mk

1. Consolidate security manager startup code invoked from
`ClassLoader.initializeClassLoaders` in `System.initSecurityManager` (new method).
2. As per the Java doc, the `java.security.manager` property should only be read
at startup. Example: If this property is initialized with `"disallow"` when the
JVM is started, then a security manager will not be set at startup and cannot
be set dynamically. Currently, this property is read in
`System.setSecurityManager`. If a user changes this property after startup, then
`System.setSecurityManager`'s behaviour will change after startup. This behaviour
does not follow the Java doc and reference implementation. To fix this issue,
the `java.security.manager` is only read once at startup in
`System.initSecurityManager`.
3. In JDK18, …

[0.31 release] Update java.security.manager behaviour

---

test/functional/cmdLineTests/gcRegressionTests/gcRotatingVerboseLogTests.xml

- Reset gcRotatingVerboseLogTests GC cycles file number
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/14422
- [skip ci]
Fixes https://github.com/eclipse-openj9/openj9/issues/14422

Reset gcRotatingVerboseLogTests GC cycle file number

---

runtime/j9vm/exports.cmake
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/javanextvmi.c
runtime/j9vm/module.xml
runtime/redirector/forwarders.m4
runtime/redirector/module.xml

Added `JNIEXPORT void JNICALL JVM_LoadZipLibrary(void)` stub method.
JDK19 builds w/ this PR, and `-version` output:
```
openjdk version "19-internal" 2022-09-20
OpenJDK Runtime Environment (build 19-internal+0-adhoc.jasonfeng.openj9-openjdk-jdk)
Eclipse OpenJ9 VM (build master-9398b11019e, JRE 19 Mac OS X amd64-64-Bit Compressed References 20220204_000000 (JIT enabled, AOT enabled)
OpenJ9   - 9398b11019e
OMR      - 96a484d1b
JCL      - 2f47958cb14 based on jdk-19+8)
```
This fixes JDKNext abuild failure - https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_linux_OpenJDK/201/console

JDK19 adds JVM_LoadZipLibrary stub method

---

test/functional/DDR_Test/playlist.xml
test/functional/Java8andUp/playlist.xml
test/functional/cmdLineTests/classesdbgddrext/playlist.xml
test/functional/cmdLineTests/dumpromtests/playlist.xml
test/functional/cmdLineTests/modularityddrtests/playlist.xml
test/functional/cmdLineTests/shrcdbgddrext/playlist.xml

This commit is a followup of #14376, excluding some more functional
tests that fail on AArch64 macOS.

AArch64 macOS: Exclude functional tests on AArch64 macOS

---

.github/workflows/runAqaConfig.json

Allow custom repos to be set by the users as command arguments rather than in runAqaConfig.json.
Fixes: adoptium/aqa-tests#3163
Signed-off-by: Nadeen Mohamed <nadeen@ualberta.ca>

Remove runAqaConfig.json

---

runtime/compiler/control/JitDump.cpp

When the environment variable `TR_PrintJITServerMallocStats` is set, use the `malloc_stats()` function to print the malloc heap statistics (such as the amount of allocated and reserved space in each per-thread heap) when a JIT dump is triggered, on both the server and the client.
This data is useful for profiling JITServer memory usage since it currently uses the malloc heap heavily (e.g. in message serialization).
Note that this feature is only supported on Linux since `malloc_stats()` is a non-standard glibc extension.

Option to print JITServer malloc statistics at JIT dump on Linux

---

runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/X86PrivateLinkage.cpp
runtime/compiler/x/i386/codegen/IA32PrivateLinkage.cpp

Code breakpoints inserted by the JIT should use an `int3` instruction rather
than the `bad` pseudo instruction.

Fix JIT code breakpoints on x86

---

test/functional/Jsr292/variables.mk
test/functional/variables.mk

Leading tabs have the potential to cause elements of makefiles to be considered part of a recipe instead of part of the global structure: use spaces instead.

Avoid leading tabs in makefiles outside of recipes

---

jcl/src/java.base/share/classes/module-info.java.extra

These exports to non-existent ibm modules were never used, except
perhaps temporarily for an obsolete project, and don't belong in OpenJ9
anyway. The first line was added before contribution to open source, the
others were added by https://github.com/eclipse-openj9/openj9/pull/10075

Remove unused exports in java.base/module-info.java.extra

---

runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/X86PrivateLinkage.cpp
runtime/compiler/x/i386/codegen/IA32PrivateLinkage.cpp

Code breakpoints inserted by the JIT should use an `int3` instruction rather
than the `bad` pseudo instruction.
master branch PR: #14435

(0.31.0) Fix JIT code breakpoints on x86

---

jcl/src/java.base/share/classes/java/lang/System.java

In some cases, warning messages are no longer being printed when the input
argument is null. Revising the fix in #14329 to correctly throw
UnsupportedOperationException (UOE) in case of a null input argument when the
security manager is disallowed.
When the security manager is not allowed to be set dynamically, return if the
input argument is null. UnsupportedOperationException should only be thrown for
a non-null input argument.
Fixes: #14445
Related: https://github.com/eclipse-openj9/openj9/pull/14447

[0.31 release] Correctly throw UOE from setSecurityManager

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/codegen/J9CodeGenerator.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9method.h
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/optimizer/J9TransformUtil.cpp
runtime/compiler/p/codegen/CallSnippet.cpp
runtime/compiler/p/codegen/J9CodeGenerator.hpp
runtime/compiler/p/codegen/PPCPrivateLinkage.cpp
runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp
runtime/compiler/x/codegen/CallSnippet.cpp
runtime/compiler/x/codegen/CallSnippet.hpp
runtime/compiler/x/codegen/J9CodeGenerator.hpp
runtime/compiler/x/codegen/X86PrivateLinkage.cpp
runtime/compiler/x/i386/codegen/IA32PrivateLinkage.cpp
runtime/compiler/z/codegen/J9CodeGenerator.hpp

Certain transformations in the compiler rely on a guarantee that a given resolved call node will simply call the target method without attempting to resolve a constant pool entry, since the constant pool entry may not correspond to the call in the usually expected way.
We always have this guarantee in non-AOT compilations.
In AOT compilations, we currently have this guarantee for direct calls when using the symbol validation manager (SVM) on x86, Power, and z.
In the SVM case, each code generator must now opt in to this class of transformations by explicitly declaring that it provides the needed guarantee for direct calls, virtual calls, or both.
Special-case virtual and interface resolution in AOT now respects `isResolved*DispatchGuaranteed()`. In particular, private `invokevirtual`, …

Replace forceUnresolvedDispatch() with isResolved*DispatchGuaranteed()

---

runtime/gc_base/GCExtensions.hpp
runtime/gc_modron_startup/mmparseXXgc.cpp
runtime/gc_vlhgc/CopyForwardCompactGroup.hpp
runtime/gc_vlhgc/CopyForwardScheme.cpp
runtime/gc_vlhgc/CopyForwardScheme.hpp
runtime/gc_vlhgc/WriteOnceCompactor.cpp

- new XXgc options noRecycleRemainders, recycleRemainders(default).
- if option recycleRemainders is set, discard remainders in nursery
regions and recycle remainders in non nuresery regions at the end of
PGC.
- otherwise discard all remainders at the end of PGC.
depends on https://github.com/eclipse/omr/pull/6314

Handle TLHRemainders inside CopyForward - recycle

---

test/functional/JIT_Test/playlist.xml
test/functional/cmdLineTests/shareClassTests/SCHelperCompatTests/playlist.xml
test/functional/cmdLineTests/verbosetest/playlist.xml

The approach
```
<features>
<feature>AOT:nonapplicable</feature>
</features>
```
should only be used for permanent disabling of tests. Therefore, to track the known AOT failures in [1], this PR uses the `<disables>` tag as documented in [2].
[1] https://github.com/eclipse-openj9/openj9/issues/6057
[2] https://github.com/eclipse-openj9/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md#5-exclude-tests

Use <disables> to disable known AOT tests

---

runtime/gc_vlhgc/GlobalMarkingScheme.cpp

Code added recently to support Unnamed Module Object for System
Classloader marking object, but never remember it. This line has been
missed.

Add missed rememberReferenceIfRequired call

---

buildenv/jenkins/variables/defaults.yml

This commit adds options for OpenSSL to AArch64 macOS build.

AArch64 macOS: Add OpenSSL options

---

buildenv/jenkins/variables/defaults.yml

This commit adds options for OpenSSL to AArch64 macOS build.
Original PR in master: #14444

(0.31.0) AArch64 macOS: Add OpenSSL options

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/codegen/J9CodeGenerator.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9method.h
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/optimizer/J9TransformUtil.cpp
runtime/compiler/p/codegen/CallSnippet.cpp
runtime/compiler/p/codegen/J9CodeGenerator.hpp
runtime/compiler/p/codegen/PPCPrivateLinkage.cpp
runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp
runtime/compiler/x/codegen/CallSnippet.cpp
runtime/compiler/x/codegen/CallSnippet.hpp
runtime/compiler/x/codegen/J9CodeGenerator.hpp
runtime/compiler/x/codegen/X86PrivateLinkage.cpp
runtime/compiler/x/i386/codegen/IA32PrivateLinkage.cpp
runtime/compiler/z/codegen/J9CodeGenerator.hpp

This is the v0.31.0-release PR corresponding to #14430. The commit to be merged here is the identical commit that was already merged into master as part of the original PR

(0.31.0) Replace forceUnresolvedDispatch() with isResolved*DispatchGuaranteed()

---

test/functional/DDR_Test/playlist.xml
test/functional/Java8andUp/playlist.xml
test/functional/cmdLineTests/classesdbgddrext/playlist.xml
test/functional/cmdLineTests/dumpromtests/playlist.xml
test/functional/cmdLineTests/modularityddrtests/playlist.xml
test/functional/cmdLineTests/shrcdbgddrext/playlist.xml

This commit excludes some functional tests that fail on AArch64 macOS.
- DDR-related tests (#14387)
- threadMXBeanTestSuite2_0 (#14426)
Original PR in master: #14427

(0.31.0) AArch64 macOS: Exclude functional tests on AArch64 macOS

---

runtime/compiler/runtime/MetaData.cpp
runtime/oti/j9nonbuilder.h

The new flag JIT_METADATA_IS_DESERIALIZED_COMP in the
J9JITExceptionTable flags tracks whether or not the relevant method was
deserialized and relocated from the JITServer AOT cache.
Fixes: #14297

Add deserialized method flag to method MetaData

---

runtime/bcutil/cfreader.c
runtime/nls/cfre/cfrerr.nls
runtime/oti/cfr.h
runtime/oti/j9javaaccessflags.h
runtime/oti/j9modifiers_api.h
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeGenerator.java

1. Add CFR_ACC_PRIMITIVE_VALUE_TYPE and J9AccPrimitiveValueType
2. Valhalla is built on JDKNext which is Java 19 now. Update the code to
check against Java 19 when accepting/ignoring Valhalla specific access
flags.
Closes #14460

Add new flag for ACC_PRIMITIVE

---

runtime/codert_vm/arm64nathelp.m4
runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/oti/arm64helpers.m4
runtime/oti/j9nonbuilder.h

Preserve vector registers across helper calls.
Split helper functions into two categories as other platform do.
For method invocation helpers, we save parameter FPRs only.
For other helpers, we save all 128-bit vector registers.
This implementation is based on x.
Resolves https://github.com/eclipse-openj9/openj9/issues/12179.

AArch64: Preserve vector registers across helper calls

---

runtime/compiler/control/CompilationController.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Recompilation.cpp

The option `-Xaggressive` allows switching to profiling of hot compilations
in a more aggressive manner. This has been seen to have negative performance
effects on some applications.
This commit eliminates the effect `-Xaggressive` has on switching to profiling.
More aggressive switching to profiling can be enabled with the newly created
option `-Xjit:aggressiveSwitchingToProfiling`
Another change is the elimination of code that tried to disable downgrading
to cold optimization level. That code had no effect because it was conditional
on an option that was not yet set at that point.
Depends on https://github.com/eclipse/omr/pull/6350

Eliminate the effect -Xaggressive has on switching to profiling

---

test/functional/Java8andUp/src_110_up/org/openj9/test/java/lang/Test_Class.java

Class annotations toString format has changed to use '.' instead of
'$', in JDK19, so create new JDK19 string table and conditions for
the annotations tests.
Fixes https://github.com/eclipse-openj9/openj9/issues/14498

Add new string table for jdk19 annotation tests

---

test/functional/cmdLineTests/SystemPropertiesTest/playlist.xml
test/functional/cmdLineTests/SystemPropertiesTest/src/SysPropTest.java

Use `Charset.defaultCharset().name()` when `native.encoding` is not available.
Excluded `cmdLineTester_SystemPropertiesTest_aix` for JDK18 and onward.
Related https://github.com/eclipse-openj9/openj9/issues/14227
This passes `cmdLineTester_SystemPropertiesTest_win`, `cmdLineTester_SystemPropertiesTest_aix` failure is related to AIX JCL, to be addressed along w/ https://github.com/eclipse-openj9/openj9/issues/14472, https://github.com/eclipse-openj9/openj9/issues/14473.

SysPropTest constructs String w/ native.encoding

---

runtime/compiler/aarch64/codegen/ARM64JNILinkage.cpp
runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/runtime/RelocationRecord.cpp
runtime/compiler/runtime/RelocationRecord.hpp
runtime/compiler/z/codegen/S390J9CallSnippet.cpp

On x86, the JNI Target relocation puts the incorrect address when
generating a Runtime Assumption. However, the address that the
relocation infra itself needs to patch is correct. Thus, the relo record
has to hold not just the location to patch but also the location to
register the assumption against. This is the same on most platforms, but
different on x86.
~Depends on https://github.com/eclipse/omr/pull/6326~
~Depends on https://github.com/eclipse/omr/pull/6331~
Depends on https://github.com/eclipse/omr/pull/6332
Fixes https://github.com/eclipse-openj9/openj9/issues/14300

Update JNI Target relocation record to have offset to the reloLocation.

---

test/functional/RasapiTest/test.xml

Format consistently and replace
```
<jvmarg value="-Xmx512M" />
```
with
```
<jvmarg value="-Xgcpolicy:optthruput" />
<jvmarg value="-Xms1024M" />
<jvmarg value="-Xmx1024M" />
```
Fixes https://github.com/eclipse-openj9/openj9/issues/14193

Run RAS API tests with GC policy optthruput and a fixed 1500MB heap

---

test/functional/Java8andUp/src/org/openj9/test/contendedfields/ContendedFieldsTests.java

This commit adds some lines in ContendedFieldsTests for AArch64 cache
line size.
Fixes: #14501

Fix AArch64 cache line size in ContendedFieldsTests

---

test/functional/Java8andUp/src/org/openj9/test/contendedfields/ContendedFieldsTests.java

This commit adds some lines in ContendedFieldsTests for AArch64 cache
line size.
Original PR in master: #14515

(0.31.0) Fix AArch64 cache line size in ContendedFieldsTests

---

test/functional/cmdLineTests/jvmtitests/playlist.xml

This commit excludes cmdLineTester_fieldwatchtests in
extended.functional on AArch64 macOS.

Exclude cmdLineTester_fieldwatchtests on AArch64 macOS

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.cpp
runtime/compiler/net/MessageTypes.hpp
runtime/compiler/runtime/JITClientSession.hpp

A new _JavaStringObject field has been added to
ClientSessionData::VMInfo to cache the value of J9VMJAVALANGSTRING
from the client. This is used by the server in
TR_J9ServerVM::isString when it is not NULL, rather than always sending
a message to the client.
Fixes: #13988

Eliminate VM_isString1 messages from JITServer

---

runtime/compiler/control/J9Options.cpp

The JITServer version should only be printed in client or server
compilation mode, as it is confusing otherwise. This applies even when
JITServer verbose mode is enabled.
Fixes: #14514

Guard JITServer version printing

---

test/functional/cmdLineTests/jvmtitests/playlist.xml

This commit excludes cmdLineTester_fieldwatchtests in
extended.functional on AArch64 macOS.
Original PR in master: #14523

(0.31.0) Exclude cmdLineTester_fieldwatchtests on AArch64 macOS

---

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/minidump/WindowsProcessAddressSpace.java
debugtools/DDR_VM/src/com/ibm/j9ddr/view/dtfj/image/J9DDRImageProcess.java
jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/corereaders/NewElfDump.java
jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/corereaders/NewZosDump.java
jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/image/j9/ImageProcess.java
runtime/j9vm/jvm.c
runtime/rasdump/javadump.cpp

Capture command line in environment on Linux and Windows

---

runtime/compiler/optimizer/VectorAPIExpansion.cpp

- broadcast long argument should be converted to int instead of byte or short
since we promote byte and short into int during scalarization

Fix scalarization of broadcast for byte and short

---

runtime/jvmti/jvmtiThreadGroup.c

`childrenThreadsLock` should be checked instead.
This was discovered while developing a change for https://github.com/eclipse-openj9/openj9/issues/14508

Fix JVMTI objectMonitorEnter return status code check

---

runtime/criusupport/criusupport.cpp
runtime/criusupport/j9criu.tdf
runtime/nls/j9cl/j9jcl.nls
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/criuhelpers.cpp
runtime/vm/intfunc.c
runtime/vm/j9vm.tdf
runtime/vm/jvminit.c

Defined `J9InternalHookRecord` & `J9ObjectRecord`;
Added VM internal functions `addInternalJVMCheckpointHook`, `initializeCriuHooks`, and `iterateHookRecords`;
Invokes `j9mm_iterate_all_objects` before `criu` checkpoint to record all heap objects matching instance type(s) specified within the hook record;
At restore, `iterateCriuHookRecords` performs modification accordingly.

CRIU implement internal hooks mechanism

---

runtime/compiler/p/runtime/PicBuilder.spp

We need to maintain the contents of `r11` for the case where we have
to call the helper. The GPR result of the `andi.` therefore needs to go
into another register. The GPR result isn't actually needed, only the
result of the test against 0 (stored in `cr0`) is, so we can use any
register that's free at that moment. `r0` is a good candidate.
Fixes https://github.com/eclipse-openj9/openj9/issues/14465
Signed-off-by: Younes Manton <ymanton@ca.ibm.com>

Avoid r11 in iTable offset tag bits check on Power

---

jcl/jpp_configuration.xml
jcl/src/java.base/share/classes/java/lang/ClassLoader.java

Also updated reference to `rt-compressed.sunJava19.jar` for pConfig compilation.
JDK19 `openj9-staging` branch builds w/ this PR and `-version` output:
```
openjdk version "19-internal" 2022-09-20
OpenJDK Runtime Environment (build 19-internal-adhoc.jasonfeng.openj9-openjdk-jdk)
Eclipse OpenJ9 VM (build master-ed430d715a4, JRE 19 Mac OS X amd64-64-Bit Compressed References 20220217_000000 (JIT enabled, AOT enabled)
OpenJ9   - ed430d715a4
OMR      - 2f87d0fa1
JCL      - 289d0fccf8d based on jdk-19+10)
```
closes https://github.com/eclipse-openj9/openj9/issues/14539

JDK19 uses NativeLibraries.newInstance() API

---

runtime/codert_vm/CodertVMHelpers.cpp
runtime/codert_vm/cnathelp.cpp
runtime/codert_vm/decomp.cpp
runtime/codert_vm/jswalk.c
runtime/compiler/runtime/MethodMetaData.c
runtime/compiler/runtime/MethodMetaData.h
runtime/oti/j9nonbuilder.h
runtime/oti/j9protos.h
runtime/vm/exceptiondescribe.c
runtime/vm/swalk.c

Replaces uses of currentThread with walkThread in jswalk
There are cases where a non JVM thread may trigger a javacore. In these
cases the currentThread will be NULL. This will cause crashes when we
need to walk certain jit frames as the currentThread is used to
facilitate this. This PR replaces uses of currentThread with walkThread
in these cases.

Replaces uses of currentThread with walkThread in jswalk

---

runtime/compiler/net/CommunicationStream.hpp

https://github.com/eclipse-openj9/openj9/pull/14421 changed the layout of the relocation data. As such, the JITServer minor version has to be updated.

Update JITServer minor version

---

runtime/codert_vm/CodertVMHelpers.cpp
runtime/codert_vm/cnathelp.cpp
runtime/codert_vm/decomp.cpp
runtime/codert_vm/jswalk.c
runtime/compiler/runtime/MethodMetaData.c
runtime/compiler/runtime/MethodMetaData.h
runtime/compiler/runtime/SignalHandler.c
runtime/oti/j9nonbuilder.h
runtime/oti/j9protos.h
runtime/vm/exceptiondescribe.c
runtime/vm/swalk.c

Replaces uses of currentThread with walkThread in jswalk (v2)
There are cases where a non JVM thread may trigger a javacore. In these
cases the currentThread will be NULL. This will cause crashes when we
need to walk certain jit frames as the currentThread is used to
facilitate this. This PR replaces uses of currentThread with walkThread
in these cases.
Fixes compile failure in https://github.com/eclipse-openj9/openj9/pull/14533

Replaces uses of currentThread with walkThread in jswalk (v2)

---

runtime/compiler/optimizer/J9TransformUtil.cpp

One of the effects of the `-Xaggressive` option is to enable static final field
folding for the JCL classes. Static final field folding is already enabled
under OSR (which is on by default) so this code is now obsolete and will be
deleted in this commit.
For the cases where OSR is disabled we can still enable static final field
folding for JCL classes with the `TR_EnableJCLStaticFinalFieldFolding`
environment variable.

Simplify -Xaggressive code

---

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/minidump/WindowsProcessAddressSpace.java
debugtools/DDR_VM/src/com/ibm/j9ddr/view/dtfj/image/J9DDRImageProcess.java
jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/corereaders/NewElfDump.java
jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/corereaders/NewZosDump.java
jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/image/j9/ImageProcess.java
runtime/j9vm/jvm.c
runtime/rasdump/javadump.cpp

This cherry-picks #14516, #14520, #14528 and #14536 for the 0.31.0 release.

(0.31.0) Capture command line in environment on AIX, Linux, Windows, Mac

---

test/functional/cmdLineTests/SystemPropertiesTest/build.xml
test/functional/cmdLineTests/SystemPropertiesTest/playlist.xml
test/functional/cmdLineTests/SystemPropertiesTest/src/SysPropTest.java

On AIX with jdk18+ JEP 400 UTF-8 by default, the non-ASCII characters on
the command line are converted to UTF-8 by the test (not the JVM).
Fixes https://github.com/eclipse-openj9/openj9/issues/14227
Tested via grinders, which all passed.
AIX
8: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/669/
17: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/666/
18: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/665/
Windows
8: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/670/
17: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/672/
18: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/671

Update SystemPropertiesTest to work on AIX

---

runtime/gc_vlhgc/CopyForwardScheme.cpp
runtime/gc_vlhgc/GlobalMarkCardScrubber.cpp

A card can be scrubbed only if no inter-region reference coming out of
it exists.
fix: https://github.com/eclipse-openj9/openj9/issues/14396

Fix missing condition for scrubbing reference of unamedModuleObject

---

runtime/compiler/optimizer/VectorAPIExpansion.cpp

- broadcast long argument should be converted to int instead of byte or short
since we promote byte and short into int during scalarization
Backport of https://github.com/eclipse-openj9/openj9/pull/14522 and https://github.com/eclipse-openj9/openj9/pull/14565 for the 0.31 release.

(0.31.0) Fix scalarization of broadcast for byte and short

---

runtime/compiler/runtime/ClassUnloadAssumption.cpp

This commit adds calls to pthread_jit_write_protect_np() for AArch64
macOS.
Original PR in master: #14588

(0.31.0) AArch64 macOS: Add calls to pthread_jit_write_protect_np()

---

test/functional/cmdLineTests/SystemPropertiesTest/build.xml
test/functional/cmdLineTests/SystemPropertiesTest/playlist.xml
test/functional/cmdLineTests/SystemPropertiesTest/src/SysPropTest.java

Cherry pick https://github.com/eclipse-openj9/openj9/pull/14507 and https://github.com/eclipse-openj9/openj9/pull/14579 for the 0.31 release.

(0.31.0) Update SystemPropertiesTest to work on jdk18

---

test/functional/CacheManagement/src/tests/sharedclasses/options/junit/TestOptionsBase.java

This commit excludes testSharedCacheJvmtiAPI in extended.functional on
AArch64 macOS for the time being, because it is a JVMTI-related test.

Exclude testSharedCacheJvmtiAPI on AArch64 macOS

---

test/functional/CacheManagement/src/tests/sharedclasses/options/junit/TestOptionsBase.java

This commit excludes testSharedCacheJvmtiAPI in extended.functional on
AArch64 macOS for the time being, because it is a JVMTI-related test.
Original PR in master: #14591

(0.31.0) Exclude testSharedCacheJvmtiAPI on AArch64 macOS

---

test/functional/JIT_Test/playlist.xml

Reverts eclipse-openj9/openj9#14462
This test was excluded due to #14459, which now should have been fixed by eclipse/omr#6363

Revert "auto exclude test jit_compareAndBranch_0 testflag=aot"

---

runtime/tests/jniarg/args_10.c
runtime/tests/jniarg/jniargtests.h
runtime/vm/BytecodeInterpreter.hpp
test/functional/NativeTest/jniargtests/JniArgTests.java

This commit partially reverts the change introduced by #4569, stopping
extension of boolean to uint32 in JNI calls on AArch64 macOS.
It also disables related testcases.
Original PR in master: #14575 + #14607

(0.31.0) AArch64 macOS: Stop extending boolean to uint32 in JNI calls

---

runtime/gc_vlhgc/CopyForwardScheme.cpp
runtime/gc_vlhgc/CopyForwardScheme.hpp

Fix for object allocate in copy path for CopyForward in PGC, when
allocated TLH copy cache is not large enough for object requested (what
may cause an assert later).
We will now retry the allocate, but we will force single object
allocation path.
The failure could really occur only if tlhSurvivorDiscardThreshold is
increased above _minCacheSize (what defaults to tlhMinimumSize).
Default tlhSurvivorDiscardThreshold may need to be increased in future
(or through manual tuning) to prevent too frequent single object
allocation (and contention caused by it).
A bit of cleanup (UDATA to uintptr_t) in all 'reserveMemory' methods,
but there is more cleanup in this very large file.

Fix for increased tlhSurvivorDiscardThreshold for PGC

---

runtime/oti/VMHelpers.hpp
runtime/tests/jniarg/args_10.c
runtime/tests/jniarg/jniargtests.h
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/MHInterpreter.hpp
test/functional/NativeTest/jniargtests/JniArgTests.java

This commit stops extending boolean to uint32 in JNI calls.
It also changes the type declarations of related testcases.
Fixes: #14574

Stop extending boolean to uint32 in JNI calls

---

runtime/compiler/optimizer/IdiomRecognition.cpp
runtime/compiler/optimizer/IdiomRecognition.hpp

Consider the following test case.
```
public class TestIdiomRecognition {
public static final void main(String[] args) {
char[] dst = new char[256];
char[] src = new char[256];
docopy(dst, src, 0, 0, 256);
docopy(dst, src, 0, 0, 256);
docompare(dst, src, 0, 0, 256, true);
docompare(dst, src, 0, 0, 256, true);
}
public static final void docopy(char[] dst, char[] src, int start1, int start2, int len) {
if (len < dst.length && len < src.length) {
for (int i = 0; i < len; i++) {
dst[i + start1] = src[i + start2];
}
}
}
public static final boolean docompare(char[] dst, char[] src, int start1, int start2, int len, boolean b) {
boolean same = true;
if (len < dst.length && len < src.length) {
for (int i = 0; i < len; i++) {
if (dst[i + start1] != src[i + start2]) {
same = false;
break;
}
}
} …
```

Enable Idiom Recognition outside of jitserver

---

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/runtime/RelocationRecord.cpp
runtime/compiler/runtime/RelocationRecord.hpp
runtime/compiler/runtime/SymbolValidationManager.cpp
runtime/compiler/runtime/SymbolValidationManager.hpp
runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp
runtime/compiler/x/codegen/J9CodeGenerator.hpp
runtime/compiler/x/i386/codegen/IA32PrivateLinkage.cpp

The J2I thunk from method validation ensures that the J2I thunk appropriate to the method specified by the given method ID exists and is registered with the VM, and uses the address of the J2I thunk to define the given thunk ID.
Then with this validation, it's very straightforward to guarantee resolved virtual dispatch under SVM on x86. This will allow the IL generator to generate a resolved virtual call node for `invokeinterface` when calling a non-final method of `Object`, e.g. `toString()`.
This PR requires eclipse/omr#6358 to be merged first

Implement SVM J2I thunk validation and guarantee resolved virtual dispatch under SVM on x86

---

runtime/jcl/common/system.c

Remove MaxDirectMemorySize default size in JDK11+
When sun.nio.MaxDirectMemorySize (AKA -XX:MaxDirectMemorySize) is not
set the JDK defaults to Xmx in JDK11 builds.
Fixes https://github.com/eclipse-openj9/openj9/issues/14503

Remove MaxDirectMemorySize default size in JDK11+

---

runtime/j9vm/jvm.c
runtime/rasdump/javadump.cpp

Also remove workaround of using `IBM_JAVA_COMMAND_LINE` on z/OS.
This should be the final piece of addressing #947.

Capture command line on z/OS

---

runtime/gc_modron_startup/mminit.cpp

Testing with -Xtune:throughput has shown a flaw when maximum heap size
is not a multiple of 8k (double the page size). Details follow:
Under Xtune:throughput, the initial size of heap (Xms value) is set to
equal the maximum size of the heap (Xmx value). This is done in
`gcInitializeCalculatedValues(J9JavaVM *javaVM, IDATA* memoryParameters)`
which computes Xms, Xmns, Xmno values and stores them into "gc extensions"
for future use. The logic assigns Xms=Xmx, Xmns=Xmx/4 and Xmos=Xmx/4*3.
In this process, `MM_Math::roundToCeiling()` is used and the Xmns value may
receive an extra 4K (nursery is rounded up on a 8K boundary).
Later-on, in `combinationMemoryParameterVerification()` there is some checking
that all the computed/selected values are fine. In particular, we check whether
`Xmos+Xmns …

Fix Xmns value under -Xtune:throughput

---

runtime/jcl/common/system.c

Remove MaxDirectMemorySize default size in JDK11+
When sun.nio.MaxDirectMemorySize (AKA -XX:MaxDirectMemorySize) is not
set the JDK defaults to Xmx in JDK11 builds.

(0.31) Remove MaxDirectMemorySize default size in JDK11+

---

runtime/compiler/CMakeLists.txt

Append `-O` to override `-O3` which avoids compiler problem.

Workaround a compile problem with VectorAPIExpansion.cpp on z/OS

---

runtime/jcl/common/system.c

The address of `maxDirectMemBuff` is used after the scope in which it was declare has closed. A compiler would be free to used that space for anything it thought appropriate, clobbering the contents needed for the call to `getPlatformPropertyList()`.

Fix reference to array that is out of scope

---

runtime/jcl/common/system.c

Cherry-pick #14644 for the 0.32.0 release branch.

(0.32.0) Fix reference to array that is out of scope

---

runtime/jcl/common/system.c

Cherry-pick #14644 for the 0.31.0 release branch.

(0.31.0) Fix reference to array that is out of scope

---

doc/release-notes/0.31/0.31.md

PR https://github.com/eclipse-openj9/openj9/pull/14623

Add release note for -XX:MaxDirectMemorySize change in Java 11+

---

runtime/jvmti/jvmtiExtensionMechanism.c
test/functional/CacheManagement/src/tests/sharedclasses/options/junit/TestOptionsBase.java
test/functional/cmdLineTests/jvmtitests/playlist.xml

This commit changes the implementation of JVMTI extension functions in
jvmtiExtensionMechanism.c, so that the functions use va_list for taking
arguments and their prototypes match the declaration of
jvmtiExtensionFunction.

Use va_list for arguments in JVMTI variadic functions

---

runtime/compiler/env/j9method.cpp
runtime/jcl/common/stdinit.c
runtime/oti/vmconstantpool.xml

Fixes build failure seen at https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/252/ due to:
* 8282515: More clean up on NativeLibraries just for JNI library use
Fixes: #14650.

Adjust for signature change to NativeLibraries.load() in Java 19

---

buildenv/jenkins/README.md

This commit adds aarch64_mac to buildenv/jenkins/README.md

Update README for Jenkins jobs

---

test/functional/cmdLineTests/jvmtitests/playlist.xml

This commit partially reverts #14376 to enable cmdLineTester_jvmtitests_*
on AArch64 macOS back again.

Enable cmdLineTester_jvmtitests_* on AArch64 macOS

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.hpp

This commit implements locals compaction on aarch64.
`mapStack` function is changed to call `mapCompactedStack` function
implemented in OMRLinkage class when locals compaction is enabled.
`mapSingleAutomatic` function is modified so that 8-byte (or larger)
alignment is applied only to stack allocated object without GC index,
because GC indices of stack allocated objects are already adjusted
in `createStackAtlas()` so that they are properly aligned.
Depends on https://github.com/eclipse/omr/pull/6379

AArch64: Implement Locals Compaction

---

doc/compiler/aot/SymbolValidationManager.md
runtime/compiler/aarch64/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/p/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/runtime/RelocationRecord.cpp
runtime/compiler/runtime/SymbolValidationManager.cpp
runtime/compiler/runtime/SymbolValidationManager.hpp

The SVM, at its core, maintains a mapping between the results of front end VM queries and `uint16_t` IDs. Conceptually, the ID is the symbol that is associated with the result which is the value. However, in the SVM, the term "symbol" was used to refer to the value. This is confusing for anyone new to the SVM, especially since it claims to be similar to a symbol table in a linker.
This PR improves the conceptual integrity of the SVM by actually referring to values as values and IDs as symbols.

Improve conceptual integrity of SVM nomenclature 

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/ilgen/Walker.cpp
runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp
runtime/compiler/z/codegen/J9CodeGenerator.cpp

Also restrict the optimization to when string compression
is enabled only.

Enable inlineEncodeASCII optimization for Java 17

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/HookedByTheJit.cpp

In order to ensure that a checkpoing/restore does not happen in the
middle of a compilation, when the J9HOOK_VM_PREPARING_FOR_CHECKPOINT
hook is called, all compilation threads are slated to be suspended.
Any existing compilations are allowed to complete. At restore time,
the compilation threads are resumed.
One difference between suspension at checkpoint time vs at any other
point is that the compilation queue is not purged. The reason for
this is that we want execution to continue as normal on restore.
1. Hook Thread acquires Comp Monitor
2. Hook Thread signals Comp Threads to suspend
3. Hook Thread acquires CR Monitor, releases Comp Monitor, and waits on
CR Monitor
4. Comp Threads acquire Comp Monitor and CompThread Monitor, and change
state to COMPTHREAD_SUSPENDED
5. Comp Threads …

Handle Compilation Threads at checkpoint/restore

---

runtime/rasdump/javadump.cpp

A new line beginning with `3XMJAVALTHRCCL` captures the class name and address of the related context class loader.
Fixes: #14618.

Capture Thread.contextClassLoader in javadumps

---

jcl/src/java.base/share/classes/module-info.java.extra
jcl/src/java.base/share/classes/openj9/internal/criu/InternalCRIUSupport.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
runtime/criusupport/criusupport.cpp
runtime/criusupport/criusupport.hpp
runtime/criusupport/exports.cmake
runtime/criusupport/uma/criusupport_exports.xml

This makes it straightforward to check `isCRIUSupportEnabled()` from `java.base` (particularly for security related JCL patches).
`isCheckpointAllowed()` invokes `isCRIUSupportEnabled()` first to load library `j9criu29` and complete initialization.
close https://github.com/eclipse-openj9/openj9/issues/14642
close https://github.com/eclipse-openj9/openj9/issues/14676

Move CRIU.isCRIUSupportEnabled() & related APIs into java.base

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java

`loadClass()` continues if `findClass` via `bootstrapClassLoader` not succeed
@ZainabF92 this is expected to fix the CNFE you had when loading security provider classes outside of `java.base`.
related https://github.com/eclipse-openj9/openj9/issues/14662

loadClass() continues if findClass via bootstrapClassLoader not succeed

---

doc/release-notes/0.31/0.31.md
doc/release-notes/0.32/0.32.md

This commit adds known issues of AArch64 macOS build to the release
notes of v.0.31.0  / v.0.32.0.

Add AArch64 macOS known issues to v.0.31.0 / v.0.32.0 release notes

---

doc/release-notes/0.31/0.31.md

This commit adds known issues of AArch64 macOS build to the release
notes of v.0.31.0.
Original PR in master: #14690

(0.31.0) Add AArch64 macOS known issues to release notes

---

test/functional/JLM_Tests/playlist.xml
test/functional/Java8andUp/java8andUpSettings.mk
test/functional/Jsr292/variables.mk
test/functional/cmdLineTests/J9security/playlist.xml
test/functional/cmdLineTests/proxyFieldAccess/playlist.xml
test/functional/testVars.mk

- rename variables.mk to testVars.mk for auto inclusion
- use export to pass down to all subfolders

Use auto include for variable JAVA_SECURITY_MANAGER in testing

---

runtime/libffi/riscv/ffi.c

This commit backports changes in upstream libffi, namely change in
commit
commit aa3fce08ba620c50db17215a9f14dd0f1facf741
Author: Andreas Schwab <schwab@linux-m68k.org>
Date:   Sun Feb 13 21:04:33 2022 +0100
This change properly widens integral return value narrower than
XLEN bits as documented [1]. Changes done in OpenJ9 commit 4c0adb
depend on this (documented) libffi behavior.
[1]: https://github.com/libffi/libffi/blob/ab1677106605aba1c27665964ff90bea59612ce3/doc/libffi.texi#L216-L221

RISC-V: backport libffi commit aa3fce08

---

runtime/j9vm/j7vmi.c
runtime/j9vm/javanextvmi.c
runtime/jcl/common/getstacktrace.c
runtime/jcl/common/jclexception.cpp
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/rasdump/javadump.cpp
runtime/rasdump/trigger.c
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/FastJNI_java_lang_Throwable.cpp
runtime/vm/exceptiondescribe.c

Removed J9_STACKWALK_SKIP_HIDDEN_FRAMES flag from `fillInStackTracecalls`
and added skip logic to `iterateStackTrace` call.
With JIT inlined frames, only the outer frame will be visible during to
swalk which is used by `fillInStackTracecalls`. This will cause stacktrace
inner frames that are not marked as Hidden to also be skipped.
As inlined frames will be unfolded during `iterateStackTrace`, code can
properly handle inlined frames and only skip methods that are hidden.
StackTrace created for dump files will not skip any Hidden frames to
retain verbose info for debugging purposes
Fixes: #14395 

Skip hidden frames during iterateStackTrace call

---

runtime/j9vm/j7vmi.c
runtime/j9vm/javanextvmi.c
runtime/jcl/common/getstacktrace.c
runtime/jcl/common/jclexception.cpp
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/rasdump/javadump.cpp
runtime/rasdump/trigger.c
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/FastJNI_java_lang_Throwable.cpp
runtime/vm/exceptiondescribe.c

Removed J9_STACKWALK_SKIP_HIDDEN_FRAMES flag from `fillInStackTracecalls`
and added skip logic to `iterateStackTrace` call.
With JIT inlined frames, only the outer frame will be visible during to
swalk which is used by `fillInStackTracecalls`. This will cause stacktrace
inner frames that are not marked as Hidden to also be skipped.
As inlined frames will be unfolded during `iterateStackTrace`, code can
properly handle inlined frames and only skip methods that are hidden.
StackTrace created for dump files will not skip any Hidden frames to
retain verbose info for debugging purposes.
Port of #14688 

(0.31.0) Update skip Hidden frames logic in stacktrace

---

runtime/compiler/optimizer/J9ValuePropagation.cpp
runtime/compiler/optimizer/J9ValuePropagation.hpp

Enhance analysis of `jit{Load|Store}FlattenableArrayElement` helper calls in Value Propagation's `constrainRecognizedMethod`, checking for opportunities to avoid generating `ArrayStoreCHK`, `arraylength` or `BNDCHK` nodes in the inline IL generated for array element load or store operations with value types support enabled.
This is the second pull request planned for [Issue #14402](https://github.com/eclipse-openj9/openj9/issues/14402#issuecomment-1027104497)

Improve IL for array load and store helpers for value types support
