runtime/compiler/z/codegen/J9UnresolvedDataSnippet.cpp
Under some IL configurations the Z codegen will set the index register
for a load/store memref leaving the base register NULL. This results
in a load/store instruction using R0 as the base register. Normally
this would be a small performance problem, not a functional issue.
But for the unresolved large offset case, patching will update the base
register of the load/store  with R14 which is set to the field offset
plus the contents of R0. R0 is used because the memref base register is
NULL leaving us with NoReg, but NoReg and R0 have the same 0 definition.
In such a scenario R0 contains an undefined value and can result in
storing/loading to/form a random location.
This fix will only emit the `agr` instruction adding the base register
contents to r14 when the base register is not equal to …
=> Fix >4k field offset path for unresolved field load/store in Z codegen

runtime/compiler/optimizer/J9ValuePropagation.cpp, runtime/compiler/optimizer/J9ValuePropagation.hpp
This pull request reapplies the recently reverted changes from pull request #14411, but with uses of the `override` keyword removed, as that keyword is not supported by compilers on every platform that OpenJ9 supports.
I successfully built these changes in IBM-internal builds on AIX and z/OS, as well as on Linux on x86, Power and z.
=> Reapply improved IL for transformed value types helper calls in Value Propagation

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/AttachHandler.java, jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/Attachment.java, jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/FileLock.java, jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/WaitLoop.java, jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9AttachProvider.java, jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9VirtualMachine.java
Removed the need for `Rely` files and notification when a VM attaching itself;
Avoid continuous `attachTarget` attempts to allow other attachers a chance to run;
`unlockFile` & `timeout` adjustments and log message updates.
Internal RTC 145178
=> AttachAPI improves selfAttach w/o notification & Reply files

runtime/j9vm/exports.cmake, runtime/j9vm/j9vmnatives.xml, runtime/j9vm/jvm.c, runtime/redirector/forwarders.m4
The openj9-staging branch now contains this back-port of a signature change to `JVM_LoadLibrary()`:
* 8275703: System.loadLibrary fails on Big Sur for libraries hidden from filesystem
=> jdk11: adjust signature of JVM_LoadLibrary()

jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java
resolves https://github.com/eclipse-openj9/openj9/issues/14754
=> Use named type for unsafe.inlineTypesLock

buildenv/jenkins/common/pipeline-functions.groovy
Explicitly set SDK_RESOURCE in the upstream pipeline rather than using the test pipeline default values.
Fixes: #14616
Signed-off-by: Nadeen Mohamed <nadeen@ualberta.ca>
=> Set SDK_RESOURCE in pipeline

runtime/compiler/control/rossa.cpp
This commit adds a check for disabling AOT compilation when SCC is
read only.
=> Disable AOT compilation when SCC is read only

jcl/src/java.base/share/classes/java/security/AccessController.java
When calling doPrivilegedWithCombiner with limited permissions, if the passed
AccessControlContext is null, get the current context and set it as parent.
For limited doPrivilegedWithCombiner frames, getAccSnapshot returns a
ProtectionDomain array on the first and a single object on subsequent frames.
Update code in getContextHelper to handle the different format.
Port of https://github.com/eclipse-openj9/openj9/pull/14606 to v0.32.0
fyi @pshipton
=> (v0.32.0)Fix limited doPrivilegedWithCombiner calls

runtime/j9vm/jvm.c, runtime/rasdump/javadump.cpp
Restore workaround using IBM_JAVA_COMMAND_LINE on z/OS for java dumps.
Effectively reverts #14634; see https://github.com/eclipse-openj9/openj9/pull/14634#issuecomment-1076597653.
=> Temporarily disable capturing the command line on z/OS

runtime/gc_glue_java/ObjectModelDelegate.cpp, runtime/gc_glue_java/ObjectModelDelegate.hpp, runtime/gc_include/ObjectAccessBarrierAPI.hpp, runtime/gc_include/ObjectAllocationAPI.hpp
- Implementation to seal TLH with java.lang.Object. (Relates to: https://github.com/eclipse/omr/pull/6388)
- Inline allocation path to account for SATB allocation (pre write barrier might scan newly alloced obj  object - always zero it with SATB)
=> SATB: TLH Batch Mark and Inline allocations

runtime/bcverify/staticverify.c
During bytecode verification, only CONSTANT_Methodref requires the void return
type check if the method descriptor is <init>. CONSTANT_InvokeDynamic and
CONSTANT_InterfaceMethodref do not have this requirement. See excerpts from
the JVM spec below:
CONSTANT_Methodref (Section 4.4.2; page 88); name_and_type_index: If the name
of the method in a CONSTANT_Methodref_info structure begins with a
'<' ('\u003c'), then the name must be the special name <init>, representing
an instance initialization method (§2.9.1). The return type of such a method
must be void.
CONSTANT_Methodref and CONSTANT_InterfaceMethodref share the same
section 4.4.2. There is no specific requirement for
CONSTANT_InterfaceMethodref's name_and_type_index. So, I assume that it just
needs to be a method descriptor. …
=> [0.31] Only CONSTANT_Methodref requires the void return type check

runtime/compiler/z/codegen/J9CodeGenerator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp
Math.fma and StrictMath.fma [were implemented](https://github.com/eclipse-openj9/openj9/pull/8445) as recognized methods on Z with the vector `VFMA` instruction. This patch changes the implementation to use non vector `MAEBR`/`MADBR` instruction.
=> Change recognized Math.fma method on Z to use scalar instructions

runtime/compiler/build/files/common.mk, runtime/compiler/control/DLLMain.cpp, runtime/compiler/control/HookedByTheJit.cpp, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/rossa.cpp, runtime/compiler/env/J9PersistentInfo.hpp, runtime/compiler/env/VMJ9.h, runtime/compiler/runtime/CMakeLists.txt, runtime/compiler/runtime/JITClientSession.hpp, runtime/compiler/runtime/MetricsServer.cpp, runtime/compiler/runtime/MetricsServer.hpp
This commit implements a simple HTTP server, called MetricsServer, that
responds to "GET /metrics" requests from an agent like Prometheus.
The response includes values for all the metrics that JITServer
is willing to provide information on. This commit implements support
for four metrics:
1. CPU utilization of JITServer
2. Physical memory available to JITServer
3. Number of clients connected to JITServer
4. Number of active compilation threads in JITServer
Example of a recognized HTTP request:
```
GET /metrics HTTP/1.1
Host: 127.0.0.1:9403
User-Agent: Prometheus/2.31.1
Accept: application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1
Accept-Encoding: gzip
X-Prometheus-Scrape-Timeout-Seconds: 3
```
Example of a response sent back:
```
cpu_utilization 12.000000 …
```
=> JITServer custom metrics exporter for Prometheus

runtime/compiler/z/runtime/PicBuilder.m4, test/functional/Java11andUp/playlist.xml
Adds cases for the BASR call to the C helper instanceOf for both 31 and 64 bit z/OS for unresolved net mates interface call.
Previously only the zLinux case was present, causing a bad branch on z/OS due to differing C linkages.
Fixes: #9167
Signed-off-by: Spencer Comin <Spencer.Comin@ibm.com>
=> Add z/OS dispatch for fast_jitInstanceOf

runtime/gc_vlhgc/SchedulingDelegate.cpp, runtime/gc_vlhgc/SchedulingDelegate.hpp
Don't calculate average CopyFoward _rate_ (mostly characteristic of h/w
expressed in Bytes/microsec units) if no bytes are copied (for example
due to abort, all have been subject to Mark-Compact). Otherwise we would
incorrectly drag down the averages, potentially to 0, which may later
cause problems.
We still calculate average _amount of bytes_ that are Copy-Forwarded per
PGC, and it's ok to drag down the average if we indeed do all or mostly
Mark-Compact work.
=> Average Copy Forward Rate fix

runtime/jcl/common/mgmtthread.c
Only filter the maxStackFrames during pruneStacktrace as
getStackTrace API may remove hidden frames from the stacktrace
after stackwalk resulting in less frames being returned.
Fixes: #14738 
=> Remove limit on maxStackFrames during getStackFramePCs

runtime/bcverify/staticverify.c
During bytecode verification, only CONSTANT_Methodref requires the void return
type check if the method descriptor is <init>. CONSTANT_InvokeDynamic and
CONSTANT_InterfaceMethodref do not have this requirement. See excerpts from
the JVM spec below:
CONSTANT_Methodref (Section 4.4.2; page 88); name_and_type_index: If the name
of the method in a CONSTANT_Methodref_info structure begins with a
'<' ('\u003c'), then the name must be the special name <init>, representing
an instance initialization method (§2.9.1). The return type of such a method
must be void.
CONSTANT_Methodref and CONSTANT_InterfaceMethodref share the same
section 4.4.2. There is no specific requirement for
CONSTANT_InterfaceMethodref's name_and_type_index. So, I assume that it just
needs to be a method descriptor. …
=> [0.32] Only CONSTANT_Methodref requires the void return type check

runtime/jcl/common/mgmtthread.c
Only filter the maxStackFrames during pruneStacktrace as
getStackTrace API may remove hidden frames from the stacktrace
after stackwalk resulting in less frames being returned.
Port of #14767 
=> (v0.31.0) Remove limit on maxStackFrames during getStackFramePCs

runtime/jcl/common/mgmtthread.c
Only filter the maxStackFrames during pruneStacktrace as
getStackTrace API may remove hidden frames from the stacktrace
after stackwalk resulting in less frames being returned.
Port of #14767 
=> (v0.32.0) Remove limit on maxStackFrames during getStackFramePCs

runtime/gc_vlhgc/SchedulingDelegate.cpp, runtime/gc_vlhgc/SchedulingDelegate.hpp
Don't calculate average CopyFoward rate (mostly characteristic of h/w
expressed in Bytes/microsec units) if no bytes are copied (for example
due to abort, all have been subject to Mark-Compact). Otherwise we would
incorrectly drag down the averages, potentially to 0, which may later
cause problems.
We still calculate average amount of bytes that are Copy-Forwarded per
PGC, and it's ok to drag down the average if we indeed do all or mostly
Mark-Compact work.
Port of https://github.com/eclipse-openj9/openj9/pull/14771 for the 0.32 release.
=> (v0.32.0) Average Copy Forward Rate fix

runtime/cmake/platform/toolcfg/xlc.cmake
This enables stackprotect for Java 11+.
=> Enable stackprotect on z/OS with cmake

runtime/vm/jvminit.c
Consume VMOPT_XXOPENJ9COMMANDLINEENV and VMOPT_XXNOOPENJ9COMMANDLINEENV
options so that they will be recognized by the VM when not ignoring
unrecognized -XX options.
@pshipton can you take a look
=> Consume new capture command line Java options

runtime/vm/jvminit.c
Consume VMOPT_XXOPENJ9COMMANDLINEENV and VMOPT_XXNOOPENJ9COMMANDLINEENV
options so that they will be recognized by the VM when not ignoring
unrecognized -XX options.
Port of https://github.com/eclipse-openj9/openj9/pull/14797 to 0.31.0
=> (v0.31.0) Consume new capture command line Java options

runtime/vm/jvminit.c
Consume VMOPT_XXOPENJ9COMMANDLINEENV and VMOPT_XXNOOPENJ9COMMANDLINEENV
options so that they will be recognized by the VM when not ignoring
unrecognized -XX options.
Port of https://github.com/eclipse-openj9/openj9/pull/14797 to 0.32.0
=> (v0.32.0) Consume new capture command line Java options

runtime/jcl/common/system.c
Setting -1 sets the default direct memory size to the same as -Xmx.
See also https://github.com/eclipse-openj9/openj9/pull/14623
=> On jdk11+ set sun.nio.MaxDirectMemorySize to -1 by default

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
The vector registers need to be allocated as TR_VRF not TR_FPR
=> Fix register spill issue in StringLatin1.inflate

runtime/jcl/common/system.c
Setting -1 sets the default direct memory size to the same as -Xmx.
See also https://github.com/eclipse-openj9/openj9/pull/14623
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/14798 for the 0.31 release.
=> (0.31) On jdk11+ set sun.nio.MaxDirectMemorySize to -1 by default

runtime/jcl/common/system.c
Setting -1 sets the default direct memory size to the same as -Xmx.
See also https://github.com/eclipse-openj9/openj9/pull/14623
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/14798 for the 0.32 release.
=> (0.32) On jdk11+ set sun.nio.MaxDirectMemorySize to -1 by default

runtime/compiler/optimizer/J9ValuePropagation.cpp, runtime/compiler/optimizer/J9ValuePropagation.hpp
This change delivers a commit that addresses [some review comments from pull request #14411](https://github.com/eclipse-openj9/openj9/pull/14411#pullrequestreview-887973271), but that I had inadvertently failed to included in the commits for that pull request.  The changes were:
- Moved implementations of `castTo*HelperCallTransform` methods into the base class `ValueTypesHelperCallTransform` to allow for the possibility of having them inlined.
- Also removed some redundant calls to `castToArrayOperationHelperCallTransform` that were being used to cast pointers to instances of subclasses of `ArrayOperationHelperCallTransform` to pointers to their parent class.
- Finally, corrected some typographical errors in Doxygen comments.
=> Simplify cast methods and remove redundant cast method calls

runtime/compiler/optimizer/UnsafeFastPath.cpp
Modifies the `unsafeFastPath` opt to handle the recognized method
`StringUTF16.putChar` and convert the call to an `sstorei` tree node. This is
similar to how the opt already handles `StringUTF16.getChar`.
Closes: #14794
=> Adding StringUTF16.putChar to unsafeFastPath opt

test/functional/JLM_Tests/build.xml, test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestMemoryMXBean.java, test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestMisc.java, test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestRegression.java, test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestRegression_SM.java, test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestRuntimeMXBean.java, test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestSharedClassMemoryMXBean.java, test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestSharedClassMemoryMXBean_SM.java, test/functional/JLM_Tests/testng.xml
SecurityManager will be removed in a future jdk. Separate tests that
rely on it so that they can be easily disabled in the future.
Issue: #14412
=> Separate tests that rely on SecurityManager (JLM_Tests)

runtime/compiler/codegen/CodeGenGPU.cpp, runtime/compiler/compile/J9SymbolReferenceTable.cpp, runtime/compiler/il/J9DataTypes.cpp, runtime/compiler/il/J9DataTypes.hpp, runtime/compiler/il/J9IL.cpp, runtime/compiler/ilgen/Walker.cpp, runtime/compiler/optimizer/EscapeAnalysis.cpp, runtime/compiler/optimizer/SPMDParallelizer.cpp, runtime/compiler/optimizer/SPMDPreCheck.cpp, runtime/compiler/optimizer/VectorAPIExpansion.cpp, runtime/compiler/optimizer/VectorAPIExpansion.hpp, runtime/compiler/p/codegen/PPCJNILinkage.cpp, runtime/compiler/z/codegen/S390PrivateLinkage.cpp
- see https://github.com/eclipse/omr/pull/6353 for the background
- to enable VectorAPI support, VectorAPIExpansion::supportedOnPlatform needs to be modified
correspondingly
- to enable specific opcode getSupportsOpCodeForAutoSIMD needs to be modified correspondingly
depends https://github.com/eclipse/omr/pull/6353
=> Implement new vector types

longabout.html, runtime/zlib/about.html
See https://github.com/eclipse-openj9/openj9/pull/14809
Cherry pick https://github.com/eclipse-openj9/openj9/pull/14831 for the 0.32 release.
=> (0.32) Update document dates missed when updating to zlib 1.2.12

longabout.html, runtime/libffi/LICENSE, runtime/libffi/about.html
=> Update the version and copyright date for libFFI

runtime/codert_vm/CodertVMHelpers.cpp, runtime/codert_vm/cnathelp.cpp, runtime/codert_vm/decomp.cpp, runtime/codert_vm/jswalk.c, runtime/compiler/runtime/MethodMetaData.c, runtime/compiler/runtime/MethodMetaData.h, runtime/compiler/runtime/SignalHandler.c, runtime/oti/j9nonbuilder.h, runtime/oti/j9protos.h, runtime/vm/exceptiondescribe.c, runtime/vm/swalk.c
There are cases where a non JVM thread may trigger a javacore. In these
cases the currentThread will be NULL. This will cause crashes when we
need to walk certain jit frames as the currentThread is used to
facilitate this. This PR replaces uses of currentThread with walkThread
in these cases.
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/14561 for the 0.31 branch.
=> (0.31) Replaces uses of currentThread with walkThread in jswalk

runtime/cmake/platform/toolcfg/xlc.cmake
Option `-qdebug` implies `-qgonumber` which may increase the size of object files needlessly.
=> Add compiler option "-qnogonumber" on z/OS

runtime/criusupport/criusupport.cpp
Delay loading JNI refs
The openj9.criu module is loaded after java.base so any operations that
require InternalCRIUSupport early on in JVM startup will hit an
assertion failure when attempting to setup the CRIU JNI refs.
Fixes: https://github.com/eclipse-openj9/openj9/issues/14821
=> Delay loading JNI refs

jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Trace.java
`registerApplicationImpl()` need not be `synchronized` because it's only called from `registerApplication()` which itself is `synchronized`.
=> Remove redundant synchronization

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java, runtime/criusupport/CMakeLists.txt, runtime/criusupport/criusupport.cpp, runtime/criusupport/criusupport.hpp, runtime/criusupport/module.xml, runtime/nls/j9cl/j9jcl.nls
If the user requests an unprivileged CRIU dump we check
if a non-NULL `criu_set_unprivileged` symbol can be found via
dlsym() and if so call it with `true` as the parameter.
If the user requests an unprivileged CRIU dump but the symbol
cannot be found we throw an exception.
If the user does not request an unprivileged CRIU dump we do
nothing as CRIU (currently) defaults to privileged.
Also link against libdl to get access to dlsym().
Signed-off-by: Younes Manton <ymanton@ca.ibm.com>
=> Do unprivileged CRIU dump if requested+supported

jcl/src/java.base/share/classes/java/lang/Throwable.java
Fixes https://github.com/eclipse-openj9/openj9/issues/14873
=> Initialize the cause of IllegalStateException in Throwable.initCause()

runtime/tests/port/si.c
Fixes https://github.com/eclipse-openj9/openj9/issues/14867
There is precedent for removing this test, it's excluded on AIX and z/OS as well.
=> Stop running sysinfo_test_sysinfo_set_limit_ADDRESS_SPACE on OSX

runtime/compiler/codegen/J9CodeGenerator.cpp, runtime/compiler/p/codegen/J9TreeEvaluator.cpp, runtime/compiler/x/codegen/J9TreeEvaluator.cpp, test/functional/UnsafeTest/playlist.xml
Running with optLevel=noOpt or disableLocalVP causes VM crash on startup when Unsafe.copyMemory is called. This fix ensures that the intrinsic is inlined.
Closes #13314 
=> Fix jdk/internal/misc/Unsafe.copyMemory crash without value propagation

test/functional/Jsr292/bootstrap_src_90/com/ibm/j9/jsr292/bootstrap/CallerSensitiveClass.java, test/functional/Jsr292/build.xml, test/functional/Jsr292/playlist.xml, test/functional/Jsr292/src/com/ibm/j9/jsr292/MethodTypeTests.java, test/functional/Jsr292/src/com/ibm/j9/jsr292/MethodTypeTests_SM.java, test/functional/Jsr292/testng_8.xml, test/functional/Jsr292/testng_sm.xml
SecurityManager will be removed in a future jdk. Separate tests that
rely on it so that they can be easily disabled in the future.
Issue: #14412
=> Separate tests that rely on SecurityManager (Jsr292)

test/functional/NativeTest/playlist.xml, test/functional/VM_Test/playlist.xml, test/functional/cmdLineTests/dumpromtests/playlist.xml, test/functional/cmdLineTests/fastClassHashTable/playlist.xml, test/functional/cmdLineTests/forceLazySymbolResolution/playlist.xml, test/functional/cmdLineTests/pltest/playlist.xml, test/functional/cmdLineTests/sigabrtHandlingTest/playlist.xml, test/functional/cmdLineTests/verboseVerification/playlist.xml
For example,
```
<versions>
<version>8</version>
<version>11+</version>
</versions>
```
includes all current versions.
=> Remove useless version constraints from playlist.xml files

runtime/compiler/optimizer/J9Inliner.cpp
We don't necessarily know that `callSiteClass` is a subtype of the `_receiverClass`, which may have been refined to a more specific interface. In particular, the following situation can arise:
- This call site is calling `callSiteClass.callee()`, and `callSiteClass` inherits `callee()` from an interface `defInterface`, so the callee method appears to be `defInterface.callee()`.
- The receiver comes from somewhere in the calling context with signature `subInterface`, which is a sub-interface of `defInterface`.
- `_receiverClass` is refined from `defInterface` to `subInterface` based on the calling context.
- `callSiteClass` implements `defInterface` but not `subInterface`. We know for certain that it implements `defInterface` because it inherits the callee from there. The assertion now …
=> Weaken subtyping assertion for invokevirtual of an interface method

runtime/compiler/aarch64/codegen/J9AheadOfTimeCompile.cpp, runtime/compiler/codegen/J9AheadOfTimeCompile.cpp, runtime/compiler/codegen/J9AheadOfTimeCompile.hpp, runtime/compiler/p/codegen/J9AheadOfTimeCompile.cpp, runtime/compiler/x/codegen/J9AheadOfTimeCompile.cpp, runtime/compiler/z/codegen/J9AheadOfTimeCompile.cpp
The majority of each platform's implementation of
`AheadOfTimeCompile::processRelocations()` is identical and should
be shared.
Fixes #6265
=> Share implementation of AOT processRelocations() across platforms

runtime/jcl/common/java_lang_Class.cpp, runtime/jcl/common/reflecthelp.c, runtime/oti/j9modifiers_api.h, test/functional/DDR_Test/src/j9vm/test/ddrext/Constants.java, test/functional/DDR_Test/src/j9vm/test/ddrext/junit/deadlock/TestDeadlockCase1.java, test/functional/DDR_Test/src/j9vm/test/ddrext/junit/deadlock/TestDeadlockCase2.java, test/functional/DDR_Test/src/j9vm/test/ddrext/junit/deadlock/TestDeadlockCase6.java, test/functional/Jsr292/src/com/ibm/j9/jsr292/indyn/ComplexIndyTest.java
APIs in Class.java should search VT `<new>` method as constructor
`Class.getDeclaredConstructors()` and `Class.getDeclaredConstructor()`
should search the unnamed factory method `<new>` rather than instance
initialization methods for value types.
Object is initialized via java.util.Objects.newIdentity() in Valhalla.
Update tests that check for Object to also check for Identity.
Closes #14813
=> APIs in Class.java should search VT <new> method as constructor

runtime/util/fltrem.c
DREM should not return 0 just because the divisor is denormal.
Fixes #14874
=> Fix behiavor of DREM bytecode with denormals

runtime/compiler/optimizer/J9Inliner.cpp
This is #14886 for v0.32.0-release
Fixes #14526
=> (0.32.0) Weaken subtyping assertion for invokevirtual of an interface method

runtime/compiler/x/codegen/J9CodeGenerator.cpp
Due to Issue #14654 it is now disabled and can be
enabled with the environment variable
TR_enableStringLatin1InflateInlining
=> (0.32.0) Disable StringLatin1.inflate on x86.

test/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheEnableBCI.java
Raise the number of classes loaded difference from 10 to 15, as the test
fails with a few more than 10 classes difference every so often.
Example failure https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_linux_aot_Personal/53
Tested in https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/782/
=> TestSharedCacheEnableBCI fails periodically, raise # of classes diff

runtime/compiler/env/J9ClassEnv.cpp, runtime/compiler/env/J9ClassEnv.hpp
Add two APIs in ClassEnv:
1. `isClassVisible`
2. `classCanSupportFastSubstitutability`
=> Add two APIs in ClassEnv

runtime/compiler/optimizer/OSRGuardInsertion.cpp
`structureRegion()` is deprecated due to its ambiguity.
=> Replace uses of structureRegion() with structureMemoryRegion()

runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/JITServerCompilationThread.cpp, runtime/compiler/control/MethodToBeCompiled.cpp, runtime/compiler/control/MethodToBeCompiled.hpp
When the `-Xjit:verbose=compilePerformance` option is enabled, record the time spent in the compilation queue in JIT verbose logs for successful compilations and AOT cache hits (as `... queueTime=NNNus`). This time represents the total compilation request latency which is a useful JIT performance metric. The high-resolution (microsecond) timestamp of when the compilation is queued is stored in the `MethodToBeCompiled` struct (which is reduced in size in order to make room for the newly added field without increasing memory footprint).
=> Print time spent in compilation queue in JIT performance vlogs

runtime/compiler/net/ClientStream.cpp, runtime/compiler/net/CommunicationStream.hpp, runtime/compiler/runtime/Listener.cpp
Include the error description (obtained with `strerror(errno)`) in JITServer network exception messages to improve diagnostics of network connectivity issues.
=> Include error details in JITServer network exception messages

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/JITServerCompilationThread.cpp, runtime/compiler/runtime/JITServerAOTDeserializer.cpp
This PR adds the following to JITServer verbose logs:
- Log AOT cache hits at the JITServer as "compilation end" similarly to successful compilations.
- Record sending the termination message in JIT client vlog, which is useful for debugging the JIT client shutdown sequence.
- Trace AOT cache method [de]serialization in vlog in debug mode.
This PR depends on #14383 which needs to be merged first.
=> JITServer AOT cache vlog improvements

runtime/oti/j9nonbuilder.h
Fields moved to OMR some time ago and the J9 ones are completely
unreferenced.
=> Remove unused J9VMThread fields

runtime/vm/MHInterpreter.inc
The change is to check the pending exception set via
initializeClassIfNeeded() in the OpenJ9 MH interpreter
to ensure that the captured exception is correctly
thrown out as expected.
=> Add the exception check for initializeClassIfNeeded()

runtime/vm/MHInterpreter.inc
The change is to check the pending exception set via
initializeClassIfNeeded() in the OpenJ9 MH interpreter
to ensure that the captured exception is correctly
thrown out as expected.
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/14935 for the 0.32 release.
=> (0.32) Add the exception check for initializeClassIfNeeded()

runtime/compiler/env/VMJ9.h, runtime/compiler/env/VMJ9Server.hpp, runtime/compiler/p/codegen/J9CodeGenerator.cpp, runtime/compiler/p/codegen/J9CodeGenerator.hpp
Overrides the supportsDirectJNICallsForAOT call on P and thus
enabling direct JNI for AOT compiles. Related to PR #14421.
Signed-off-by: Bhavani SN <bhavani.sn@ibm.com>
=> Re-enables JNI-direct for AOT on Power

runtime/compiler/optimizer/VectorAPIExpansion.cpp, runtime/compiler/optimizer/VectorAPIExpansion.hpp
- only transform intrinsics that have NULL masks
Signed-off-by: Gita Koblents <koblents@ca.ibm.com>
=> Handle masks in VectorAPIExpansion

runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/control/JITServerHelpers.cpp, runtime/compiler/control/JITServerHelpers.hpp, runtime/compiler/net/CommunicationStream.cpp, runtime/compiler/net/CommunicationStream.hpp
- Measure the number of messages and the amount of received data, even when detailed message size statistics (`MESSAGE_SIZE_STATS`) are not enabled at build time.
- Move all the counter definitions and updates to a single place (`CommunicationStream.cpp`).
- Factor out duplicated code for printing statistics at the client and at the server.
- Correctly compute the number of messages per compilation at the server.
- Remove dead code in `JITServer::CommunicationStream`
=> Improve JITServer message statistics

runtime/compiler/runtime/MetricsServer.hpp
This change allows us more easily to filter JITServer related
metrics in Prometheus.
=> Added "jitserver" prefix to metric names suported by JITServer

runtime/compiler/env/VMJ9.h, runtime/compiler/env/VMJ9Server.hpp, runtime/compiler/p/codegen/J9CodeGenerator.cpp, runtime/compiler/p/codegen/J9CodeGenerator.hpp
Reverts eclipse-openj9/openj9#14894
See https://github.com/eclipse-openj9/openj9/pull/14894#issuecomment-1104122943
=> Revert "Re-enables JNI-direct for AOT on Power"

runtime/criusupport/criusupport.cpp
Halt all non GC and JIT threads in signle thread mode
The original implementation failed to halt the attach API and common
cleaner threads which are Java threads but not application threads.
=> Halt all non GC and JIT threads in single thread mode

runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/CompilationThread.hpp, runtime/compiler/control/rossa.cpp, runtime/compiler/control/rossa.h, runtime/compiler/runtime/RelocationRecord.cpp, runtime/compiler/runtime/RelocationRecord.hpp, runtime/compiler/runtime/RelocationRuntime.cpp, runtime/compiler/runtime/RelocationRuntime.hpp
* Add Relocation Error codes
* Update Relocation Infrastructure to return relocation error codes rather than compilation error codes
* Use generic compilation error code for most relocation failures
* Fix compilation failure verbose log line to print `AOT load` if the failed compile was an AOT load
* Update storing of validation failure SCC hints to capture all validation failures
* Delete unused compilation error codes
=> Add Relocation Error Codes

runtime/cmake/platform/toolcfg/gnu.cmake, runtime/criusupport/CMakeLists.txt
Update j9vm build dependencies
Fixes: https://github.com/eclipse-openj9/openj9/issues/14926
=> Update j9vm build dependencies for CRIU

jcl/src/java.base/share/classes/java/lang/Class.java, jcl/src/java.base/share/classes/java/lang/Thread.java, jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/ComponentBuilder.java, jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/ManagementUtils.java, jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/ExtendedGarbageCollectorMXBeanImpl.java
Reference - https://bugs.openjdk.java.net/browse/JDK-8186958
_JDK contains number of usages of HashMap, which are created with non-optimal initial capacity.
It seems that people normally assume that the constructor HashMap(int) requires the expected size as the argument.
In fact, the argument is the initial capacity, which should be bigger than the expected size. As a result, unnecessary reallocations can occur while the maps are filled._
Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/426 w/ https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/426/commits/dca73daef2bdcee73cd491532337e0c93929e03b
=> Adopt java.util.HashMap.newHashMap(numMappings)

runtime/compiler/z/codegen/S390PrivateLinkage.cpp
P and X do not check the `TR_enableProfiledDevirtualization` option before
performing guarded devirtualization. This patch removes this check in Z
codegen to bring it in line with P and X.
I used this unit test for checking virtual function calls:
```java
class Parent {
public int call_count = 0;
public int makework = -1;
public void bar() {
call_count++;
makework ^= (makework << 2) * call_count;
}
}
class Child extends Parent {
public void bar() {
call_count++;
makework += 200 - call_count % 123;
}
}
class GrandChild extends Child {
public void bar() {
call_count++;
makework -= makework ^ call_count;
}
}
public class VirtualCallTest {
static void test(Parent p) {
p.bar();
}
public static void main(String[] args) {
Parent p = new Parent();
Child c = new Child();
GrandChild g = new …
```
=> Enable profile directed guarded devirtualization by default in Z

runtime/compiler/compile/J9SymbolReferenceTable.cpp, runtime/compiler/compile/J9SymbolReferenceTable.hpp, runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/env/j9method.cpp, runtime/compiler/env/j9method.h, runtime/compiler/env/j9methodServer.cpp, runtime/compiler/env/j9methodServer.hpp, runtime/compiler/ilgen/Walker.cpp
This change impacts how the stack is set up for resolved invokedynamic
and invokehandle calls. An invokedynamic/invokehandle call is considered
resolved when the call site table entry (invokedynamic) or MethodType
table entry (invokehandle) corresponding to the bytecodes is resolved,
allowing us to check if the entries - which we refer to as invoke
cache array, contains a null appendix object. Normally, the appendix
object is implicitly pushed as the last argument for resolved
invokedynamic/invokehandle calls where we create a call for the
adapter method as we can determine that at compile time. However, in
some cases, the appendix object may be null, which happens when the
adapter method does not expect it. Therefore, we need to check if
that's the case and skip pushing the appendix …
=> Prevent pushing null appendix object for invokedynamic and invokehandle

test/functional/cmdLineTests/criu/criuScript.sh, test/functional/cmdLineTests/criu/criu_nonPortable.xml, test/functional/cmdLineTests/criu/playlist.xml, test/functional/cmdLineTests/criu/src/CRIUTestUtils.java
Add CRIU tests
Add new tests to excercise multiple checkpoints and the non-portable
restore mode.
Depends on https://github.com/eclipse-openj9/openj9/pull/14929
=> Add CRIU tests

jcl/src/java.base/share/classes/java/lang/J9VMInternals.java, jcl/src/java.base/share/classes/java/lang/Thread.java, runtime/oti/vmconstantpool.xml
* Rename `Thread.cleanup()` to `exit()`;
* `Access.newThreadWithAcc()` doesn't inherit ThreadLocals;
* Add `interrupted` as `fieldalias` of `deadInterrupt`.
=> Adopt RI java.lang.Thread

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/LoadCommand.java, debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/MachoDumpReader.java, debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/ThreadCommand.java
This commit adds support for AArch64 core files on macOS in DDR.
=> Implement DDR support for AArch64 macOS

runtime/bcutil/cfreader.c, runtime/bcverify/staticverify.c, runtime/nls/cfre/cfrerr.nls, runtime/oti/bcverify_api.h, runtime/oti/cfreader.h, runtime/oti/j9modifiers_api.h, runtime/verbose/errormessagehelper.c, runtime/verutil/chverify.c
Add verification for value objects
For issue #14741
- Check access flags on value type classes
- Ensure that correct VT related access flags are set on other
methods/classes/fields
- Add verification of access flags and signature of the <new> method
- Add J9VM_OPT_VALHALLA_NEW_FACTORY_METHOD flag to specify whether the
<new> method is being used or if <init> is being used instead
- Update isInitOrClinitImpl to check if a method name is "\<new\>"
- Add new error messages in cfrerr.nls
=> Add verification for value objects

test/functional/Java8andUp/build.xml, test/functional/Java8andUp/playlist.xml
`--add-exports` options referring to non-existent package `openj9.tools.attach.diagnostics.info` serve no purpose
=> Remove references to non-existent package

runtime/compiler/compile/J9Compilation.cpp, runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/env/J9ClassEnv.cpp, runtime/compiler/env/J9ClassEnv.hpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/ilgen/IlGenerator.cpp, runtime/compiler/ilgen/Walker.cpp, runtime/compiler/net/MessageTypes.cpp, runtime/compiler/net/MessageTypes.hpp, runtime/compiler/optimizer/EscapeAnalysis.cpp, runtime/compiler/optimizer/J9Simplifier.cpp, runtime/compiler/optimizer/J9ValuePropagation.cpp, runtime/compiler/optimizer/J9ValuePropagation.hpp, runtime/compiler/optimizer/TreeLowering.cpp, runtime/compiler/runtime/JITClientSession.cpp, test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeArrayTests.java, test/functional/Valhalla/testng.xml
Pull request #14763 added support to the JVM and GC for the distinction between primitive value type classes and non-primitive value type classes.  This pull request adds support to the JIT for this distinction.  In particular, only primitive value type classes can be flattened in OpenJ9, and non-primitive value types permit null references.  The 'Q' descriptor is only used with primitive value type classes.
This pull request also adds some tests to exercise the various combinations of assignments to array elements, where the static type might be used to refer to an array whose component type might be a value type or a primitive value type class.
=> Add support for primitive value type classes to JIT compiler

runtime/compiler/optimizer/VectorAPIExpansion.cpp
Add missing third vector argument to the entry of ternaryIntrinsicHandler.
=> Fix Vector API method table entry for ternary ops

jcl/jpp_configuration.xml
Replaced `source path src` with `.` to support `JPP` for the java files within `openj9-openjdk-jdk8/closed/adds/jdk` and `DDR_VM`.
=> Rename configuration DDR_VM to GENERIC for extension repo closed dir

doc/compiler/README.md, doc/compiler/concepts/JitWriteBarriers.md, doc/compiler/control/CompilationControl.md, doc/compiler/misc/BestPractices.md, doc/features/ObjectLockword.md
* Move Object Lockword doc to features dir
* Use relative links in high level compiler README
* Move JIT Write Barries doc to concepts dir
* Move Best Practices dir to misc dir
* Add Compilation Control doc
=> Add Compilation Control doc

buildenv/jenkins/variables/defaults.yml
=> Update to OpenSSL 1.1.1o

runtime/cmake/platform/toolcfg/gnu.cmake
Starting in version 11, GNU compilers use DWARF version 5 by default, which is not (yet) supported by ddrgen.
=> Continue using DWARF version 4 even in gcc 11+

buildenv/jenkins/common/build.groovy
Notice the duplicate slash in the URL for the debug-image archive
in https://openj9-jenkins.osuosl.org/job/Build_JDK11_ppc64_aix_Personal/302/:
> https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_ppc64_aix_Personal/302//debug-image.tar.gz
=> Remove duplicate slash in URL for debug-image

buildenv/docker/mkdocker.sh, buildenv/jenkins/docker-nodes/jenkinsfile-build-container.groovy
Update docker file to install CRIU in a Linux x86-64 OpenJ9 CentOS 7 or
Ubuntu 16+ docker container when --criu option is provided.
=> Add CRIU to the OpenJ9 docker file

buildenv/jenkins/common/build.groovy
When running a PR build with a dependent change,
if the user pastes the full URL for the other change,
the parsing will fail. This adds logic to parse a full
url in addition to existing logic that can only parse
the shorthand.
=> Jenkins: Detect full url in Pull Request depends

jcl/src/java.base/share/classes/java/lang/ClassLoader.java, test/functional/cmdLineTests/classLoaderTest/autoModuleClassloaderTest.xml, test/functional/cmdLineTests/classLoaderTest/enableAssertionStatusTest.xml, test/functional/cmdLineTests/classLoaderTest/playlist.xml, test/functional/cmdLineTests/classLoaderTest/src/org/openj9/test/automodule/AutoModuleClassloaderTest.java, test/functional/cmdLineTests/classLoaderTest/src/org/openj9/test/automodule/CustomClassLoader.java, test/functional/cmdLineTests/classLoaderTest/src/org/openj9/test/automodule/Dummy.java
`loadClass(className)` should throw `ClassNotFoundException` if `findClass` via `bootstrapClassLoader` returns `null`;
`Class.forName(className)` in `java.base` can't load the classes outside of `java.base` module;
Add a test to verify the `classloader` of the class loaded via `automatic` module path, rename `classloadertest.xml` to
`enableAssertionStatusTest.xml`, add `autoModuleClassloaderTest.xml`, and update `playlist.xml`.
closes https://github.com/eclipse-openj9/openj9/issues/14975
This reverts https://github.com/eclipse-openj9/openj9/pull/14689
fyi @tajila 
=> loadClass throws CNFE if findClass via bootstrapClassLoader not succeed

runtime/rastrace/trcmain.c, runtime/rastrace/trctrigger.c
For example, before this change:
* these two options do the same thing even though there is no group named `staticmethodsXXXX`:
```
"-Xtrace:print=mt,methods=java/lang/System.*,trigger=group{staticmethods,jstacktrace}"
"-Xtrace:print=mt,methods=java/lang/System.*,trigger=group{staticmethodsXXXX,jstacktrace}"
```
* encountering tracepoint `j9utilcore.0` would trigger a java core if this option is used
```
"-Xtrace:trigger=tpnid{j9util.0,javadump}"
```
Don't match abbreviated trace component names: use j9_cmdla_stricmp() instead of `j9_cmdla_strnicmp()` where appropriate.
Also remove redundant, inappropriate casts.
=> Fix tracepoint matching

test/functional/cmdLineTests/classLoaderTest/playlist.xml
Java 8 doesn't support modularity tests.
related to https://github.com/eclipse-openj9/openj9/pull/15028
=> cmdLineTester_AutoModuleClassloaderTest only runs at JDK 11+

buildenv/jenkins/common/build.groovy
Signed-off-by: Gregory-Cernera <gregory.cernera@ibm.com>
- Extract any files that match the pattern `ObfuscateLog*.txt` to Artifactory
- Add the file's Artifactory links to the Jenkins description for easy download.
- With the addition of the obfuscation in the build process, we need to be able to grab the change log files for future reference (i.e., customer cases).
=> Extract the obfuscation change logs from build

runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp, runtime/compiler/x/codegen/AllocPrefetchSnippet.cpp, runtime/compiler/x/codegen/CallSnippet.cpp, runtime/compiler/x/codegen/CheckFailureSnippet.cpp, runtime/compiler/x/codegen/ForceRecompilationSnippet.cpp, runtime/compiler/x/codegen/J9UnresolvedDataSnippet.cpp, runtime/compiler/x/codegen/RecompilationSnippet.cpp, runtime/compiler/z/codegen/ForceRecompilationSnippet.cpp, runtime/compiler/z/codegen/J9S390Snippet.cpp, runtime/compiler/z/codegen/S390J9CallSnippet.cpp, runtime/compiler/z/codegen/S390StackCheckFailureSnippet.cpp
* Correct usage of x86 directCallRequiresTrampoline() API
* Replace Z NEEDS_TRAMPOLINE macro with function call
=> Correct usage of x86 directCallRequiresTrampoline() API 

runtime/compiler/env/J9SharedCache.cpp
See https://github.com/eclipse-openj9/openj9/issues/15013 for more details.
It is possible for two J9Classes to have the same J9ROMClass but have
different class chains. However, because a class chain is stored into
the SCC using a key derived from the J9ROMClass, it isn't possible to
store different class chains that have the same first J9ROMClass in the
chain. This can lead to undefined behaviour as invalid AOT code can be
executed.
This PR fixes the issue by changing the code that assumes that if it
can find an existing class chain in the SCC for a given J9Class, that it
is valid for said J9Class. The code now always validates the class
chain.
Closes https://github.com/eclipse-openj9/openj9/issues/15013
=> Always call classMatchesCachedVersion in rememberClass

runtime/compiler/optimizer/EscapeAnalysis.cpp, runtime/compiler/optimizer/SPMDParallelizer.cpp, runtime/compiler/optimizer/VectorAPIExpansion.cpp
- transform opcodes for which source and result types are the same:
vload/vstore, vloadi/vstorei, vnot, vneg, vsub, vmul, vdiv, vand, vor, vxor, vsplats
Signed-off-by: Gita Koblents <koblents@ca.ibm.com>
Depends on https://github.com/eclipse/omr/pull/6496
=> Transform old vector opcodes into new ones

runtime/vm/ClassInitialization.cpp
If there is a circularity detected, currently
checkForCyclicalVerification()
returns FALSE rather than TRUE. Negate the result of
verifyLoadingOrLinkingStack() and rename checkForCyclicalVerification()
to isCyclePresentInVerification()
Fixes #15038
=> Correctly use the return value of checkForCyclicalVerification()

test/functional/Java15andUp/playlist.xml, test/functional/Java15andUp/src/org/openj9/test/hiddenclasses/HiddenClassFinalFieldTests.java, test/functional/Java15andUp/src/org/openj9/test/records/RecordFinalFieldTests.java, test/functional/Java15andUp/src/org/openj9/test/regularclassesandinterfaces/RegularClassAndInterfaceFinalFieldTests.java, test/functional/Java15andUp/testng.xml
Make sure the final fields are not modifiable through reflection. And fix one typo in record field test.
Fixes: #9929
=> Tests for final fields of hidden class, regular class, and interface

jcl/src/java.base/share/classes/module-info.java.extra, jcl/src/java.base/share/classes/openj9/internal/criu/security/CRIUConfigurator.java
Refactor CRIUConfigurator
Move CRIUConfigurator to a new package that is only exported to
openj9.criu
=> Refactor CRIUConfigurator

buildenv/jenkins/variables/defaults.yml
Mac is not available yet, should be available sometime this week.
=> Build jdknext with Semeru jdk18 now it's available

runtime/compiler/control/CompilationThread.cpp, runtime/oti/j9nonbuilder.h
This adds a new field to J9JITConfig caled compilationRuntime and
initializes it appropriately in
TR::CompilationInfo::createCompilationInfo(J9JITConfig * jitConfig)
Issue: #15036
Signed-off-by: Manasha Vetrivelu <manasha.vetrivelu@ibm.com>
=> Add CompilationInfo pointer into the J9JITConfig

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java, jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/SecurityProviders.java, test/functional/cmdLineTests/criu/criuRandomScript.sh, test/functional/cmdLineTests/criu/criuSecurityScript.sh, test/functional/cmdLineTests/criu/criu_random.xml, test/functional/cmdLineTests/criu/criu_security.xml, test/functional/cmdLineTests/criu/playlist.xml, test/functional/cmdLineTests/criu/src/CRIURandomTest.java, test/functional/cmdLineTests/criu/src/CRIUSecurityTest.java, test/functional/cmdLineTests/criu/src/CRIUTestUtils.java
Ensures that CRIUSEC is the only provider available during checkpoint.
See PR: [ibmruntimes/openj9-openjdk-jdk11#510](https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/510)
Signed-off-by: Zainab Fatmi <zainab@ibm.com>
=> Add CRIU security hooks

runtime/oti/j9cfg_builder.h, runtime/vm/jvminit.c
Only enable extended register support on JDK17+
Current ymm/zmm registers are used for vector API. No need to save extra
vector registers on older releases.
Closes https://github.com/eclipse-openj9/openj9/issues/15011
=> Only enable extended register support on JDK17+

runtime/j9vm/jvm.c, runtime/redirector/redirector.c
Issue https://github.com/eclipse-openj9/openj9/issues/15011
Effectively revert https://github.com/eclipse-openj9/openj9/pull/14282 for non-OpenJ9 builds.
=> Don't regress the default stack size in non-OpenJ9 builds

runtime/cmake/platform/toolcfg/gnu.cmake
...for compatibility with CMake versions below 3.7.
=> Replace VERSION_GREATER_EQUAL with NOT VERSION_LESS in gnu.cmake

runtime/oti/j9nonbuilder.h, runtime/oti/vm_api.h, runtime/vm/ValueTypeHelpers.cpp, runtime/vm/intfunc.c
=> Add getDefaultValue helper function

runtime/jcl/common/sun_misc_Unsafe.cpp
match RI behavior when used for static fields
=> fix objectFieldOffset1 API for static fields

runtime/compiler/optimizer/VectorAPIExpansion.cpp
Handles newly added vector IL Opcodes (vabs and vsqrt) introduced in OMR
Depends on https://github.com/eclipse/omr/pull/6489
=> Implement vabs and sqrt IL Opcodes

jcl/src/java.base/share/classes/java/lang/Thread.java
No security check is required when the context class loader is null.
=> Thread.getContextClassLoader() should return null without security check

runtime/compiler/control/J9Options.cpp
Now that JITServer is fully supported on Z, we can remove the tech preview message for the platform.
=> Remove tech preview message for JITServer on Z

runtime/ddr/module.xml
Update include path for UMA builds as was done in #15093 for cmake builds.
=> UMA: Enable DDR for platforms with no JIT compiler

jcl/src/java.base/share/classes/java/lang/System.java
Fix NPE due to `sun.nio.cs.UTF_8.JLA` is `null`.
W/ this PR and https://github.com/eclipse-openj9/openj9/pull/15073, `openj9-staging` builds and produces `-version` output:
```
openjdk version "19-internal" 2022-09-20
OpenJDK Runtime Environment (build 19-internal-adhoc.jasonfeng.openj9-openjdk-jdk)
Eclipse OpenJ9 VM (build jdk19jlanull-ae35bc4868, JRE 19 Mac OS X amd64-64-Bit Compressed References 20220520_000000 (JIT enabled, AOT enabled)
OpenJ9   - ae35bc4868
OMR      - 42677ec34
JCL      - 7d835a41a65 based on jdk-19+23)
```
closes https://github.com/eclipse-openj9/openj9/issues/15098
=> Invoke SharedSecrets.setJavaLangAccess() before ensureProperties()

jcl/src/java.base/share/classes/java/lang/ClassLoader.java, test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_ClassLoader_SM.java
See also https://github.com/eclipse-openj9/openj9/pull/15090
=> ClassLoader.getParent() should return null without security check

jcl/src/java.base/share/classes/java/lang/Thread.java, jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/corereaders/zos/util/CompressedRecordArray.java, jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/Session.java, jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/OpenCommand.java, jcl/src/openj9.traceformat/share/classes/com/ibm/jvm/traceformat/TraceFormat.java
Replaced `System.currentTimeMillis()` w/ `System.nanoTime()`;
Refactored the code affected.
This is related to https://github.com/eclipse-openj9/openj9/pull/15016, but not CRIU specific changes.
=> Use System.nanoTime() for elapsed time measurement

runtime/criusupport/criusupport.cpp, runtime/criusupport/j9criu.tdf, runtime/oti/j9port_generated.h, test/functional/cmdLineTests/criu/criu.xml, test/functional/cmdLineTests/criu/criuRandomScript.sh, test/functional/cmdLineTests/criu/criuScript.sh, test/functional/cmdLineTests/criu/criuSecurityScript.sh, test/functional/cmdLineTests/criu/criu_nonPortable.xml, test/functional/cmdLineTests/criu/src/org/openj9/criu/CRIURandomTest.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/CRIUSecurityTest.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/CRIUSimpleTest.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/CRIUTestUtils.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/TimeChangeTest.java
Added a field `checkpointRestoreTimeDelta` within `J9PortLibrary`, which is to be set the time delta between `Checkpoint` and `Restore` of `j9time_nano_time()` return values;
Updated trace points to record the actual `j9time_nano_time()` values.
This is first part to address the issue https://github.com/eclipse-openj9/openj9/issues/14211, for `System.nanoTime()`. 
Tested w/ following code snippet:
```
long beforeSnapshot = System.nanoTime();
System.out.println("System.nanoTime() before snapshot: " + beforeSnapshot);
criuSupport.checkpointJVM();
long afterRestore = System.nanoTime();
System.out.println("System.nanoTime() after restore: " + afterRestore + ", the delta is: " + (afterRestore - beforeSnapshot));
```
Snapshot run w/ `-Xtrace:print={j9criu}`
```
System.nanoTime() before …
```
=> CRIU j9time_nano_time skips the elapsed time between Checkpoint/Restore

runtime/compiler/aarch64/codegen/CallSnippet.cpp, runtime/compiler/aarch64/runtime/Recomp.cpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/runtime/ClassUnloadAssumption.cpp, runtime/compiler/runtime/J9CodeCache.cpp, runtime/compiler/runtime/RelocationRecord.cpp, runtime/compiler/runtime/RelocationRuntime.cpp, runtime/compiler/runtime/Trampoline.cpp
This commit adds "#include <pthread.h>" to the files that call
pthread_jit_write_protect_np() on AArch64 macOS.
=> AArch64 macOS: Include pthread.h explicitly

runtime/jcl/exports.cmake
GREATER_EQUAL is not available in the minimum CMake version that OpenJ9
supports.
So, Java version >= 11 is rewritten as an "else()".
=> Avoid GREATER_EQUAL in CMake files

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp
=> Prefer TR::snprintfNoTrunc() over snprintf()

buildenv/aix/jdk11/yum_install_aix-ppc64.txt, buildenv/aix/jdk17/yum_install_aix-ppc64.txt, buildenv/aix/jdk18/yum_install_aix-ppc64.txt
freetype is built with openjdk and bundled with jdk11+.
See https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/484
=> Freetype is not required on OS for AIX with jdk11+

runtime/vm/gphandle.c
This commit fixes the check for the return code of j9sysinfo_get_env()
so that the environment variable "J9NO_DUMPS" work as expected when
"-Xdump:none" is specified.
=> Fix generateSystemDump() to make "J9NO_DUMPS" work

buildenv/jenkins/variables/defaults.yml, test/functional/DDR_Test/playlist.xml, test/functional/cmdLineTests/callsitedbgddrext/playlist.xml, test/functional/cmdLineTests/classesdbgddrext/playlist.xml, test/functional/cmdLineTests/dumpromtests/playlist.xml, test/functional/cmdLineTests/gcCheck/playlist.xml, test/functional/cmdLineTests/modularityddrtests/playlist.xml, test/functional/cmdLineTests/shrcdbgddrext/playlist.xml
This commit enables DDR of AArch64 macOS builds.
=> AArch64 macOS: Enable DDR build

runtime/compiler/control/CompilationThread.cpp
This commit disables known object table in AOT compilation.
Fixes: #15059
=> Disable known object table in AOT compilation

runtime/tests/clinkerffi/downcall.h
The following dup is removed:
typedef struct stru_Byte_Byte_Byte stru_Byte_Byte_Byte;
It fails to compile on the latest xlC 16.1.0.7 on AIX.
=> Remove duplicate typedef in tests downcall.h

buildenv/jenkins/common/build.groovy
Also support, e.g., `ibmruntimes/openj9-openjdk-jdk#openj9-staging`.
Fixes #15125.
=> Expand PR build depends pattern

runtime/compiler/control/CompilationThread.cpp
This commit disables known object table in AOT compilation.
Original PR in master: #15131
=> (0.33.0) Disable known object table in AOT compilation

test/functional/Java16andUp/build.xml, test/functional/Java16andUp/playlist.xml, test/functional/Java16andUp/src_160/org/openj9/test/foreignMemoryAccess/TestCloseScope0.java, test/functional/Java16andUp/testng.xml, test/functional/Java16andUp/testng_160.xml, test/functional/Java17andUp/build.xml, test/functional/Java17andUp/playlist.xml, test/functional/Java17andUp/src_170/org/openj9/test/foreignMemoryAccess/TestCloseScope0.java, test/functional/Java17andUp/testng_170.xml, test/functional/Java18andUp/build.xml, test/functional/Java18andUp/playlist.xml, test/functional/Java18andUp/src/org/openj9/test/foreignMemoryAccess/TestCloseScope0.java, test/functional/Java18andUp/testng_180.xml
The change is to only enable the FFI specific test suites
on Java 18 given there is on backward compatibility between
Java 19 and Java 18 in terms of FFI APIs.
=> Disable the FFI specific test suites in Java 19

runtime/compiler/compile/J9Compilation.cpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/env/VMJ9Server.cpp, runtime/compiler/env/VMJ9Server.hpp, runtime/compiler/p/codegen/PPCPrivateLinkage.cpp
This fixes an issue with the code generated for containers with
-XX:+PortableSharedCache option. AOT code generated on P8 uses
pTOC and if the same container is used on P10 environment causes
a crash as pTOC is not there on P10. The fix will generate
materialize sequence of instructions when -XX:+PortableSharedCache
option is enabled and not pTOC.
Signed-off-by: Bhavani SN <bhavani.sn@ibm.com>
=> Fix usage of pTOC with portableSCC code run in P10 container

debugtools/DDR_VM/src/com/ibm/j9ddr/CompatibilityConstants29.dat, debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/ValueTypeHelper.java
This removes unnecessary uses of a constant that broke internal builds.
=> Remove dependencies on J9JavaAccessFlags.J9AccPermitsValue

jcl/src/java.base/share/classes/java/lang/System.java
For non-z/OS this shouldn't change anything, just moves code around.
=> z/OS for jdk18+ should use native.encoding like other platforms

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/elf/ELFDumpReader.java, debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/elf/ELFFileReader.java
Remove `ELFFileReader.getBaseAddress()` and don't rely on virtual addresses in executable program headers: They don't necessarily correspond to addresses where segments are loaded into a process.
Fixes: #15140.
=> Only add memory segments from core file to process view

runtime/bcutil/cfreader.c, runtime/nls/cfre/cfrerr.nls, runtime/nls/cfre/cfrerr_ca.nls, runtime/nls/cfre/cfrerr_cs.nls, runtime/nls/cfre/cfrerr_de.nls, runtime/nls/cfre/cfrerr_es.nls, runtime/nls/cfre/cfrerr_fr.nls, runtime/nls/cfre/cfrerr_hu.nls, runtime/nls/cfre/cfrerr_it.nls, runtime/nls/cfre/cfrerr_ja.nls, runtime/nls/cfre/cfrerr_ko.nls, runtime/nls/cfre/cfrerr_pl.nls, runtime/nls/cfre/cfrerr_pt_BR.nls, runtime/nls/cfre/cfrerr_ru.nls, runtime/nls/cfre/cfrerr_sk.nls, runtime/nls/cfre/cfrerr_sl.nls, runtime/nls/cfre/cfrerr_tr.nls, runtime/nls/cfre/cfrerr_zh.nls, runtime/nls/cfre/cfrerr_zh_CN.nls, runtime/nls/cfre/cfrerr_zh_TW.nls, runtime/oti/j9nonbuilder.h, runtime/verutil/cfrerr.c
provides version number of invalid class
fix #13347 
@fengxue-IS please review
=> Improve error message when loading an invalid class version

runtime/vm/gphandle.c
This commit fixes the check for the return code of j9sysinfo_get_env()
so that the environment variable "J9NO_DUMPS" work as expected when
"-Xdump:none" is specified.
Original PR in master: #15122
=> (0.33.0) Fix generateSystemDump() to make "J9NO_DUMPS" work

jcl/src/java.base/share/classes/openj9/internal/criu/InternalCRIUSupport.java, runtime/criusupport/criusupport.hpp, runtime/criusupport/exports.cmake, runtime/criusupport/uma/criusupport_exports.xml, runtime/jcl/common/criu.cpp, runtime/jcl/exports.cmake, runtime/jcl/uma/criu_exports.xml, test/functional/cmdLineTests/criu/criu_nonPortable.xml, test/functional/cmdLineTests/criu/src/org/openj9/criu/TimeChangeTest.java
Return the time in milliseconds elapsed between Checkpoint and Restore;
Add tests for `Timer.schedule(TimerTask task, long delay)` and `Timer.schedule(TimerTask task, Date time)`.
Related to https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/531 https://github.com/eclipse-openj9/openj9/issues/14211
=> Add InternalCRIUSupport.getCheckpointRestoreTimeDelta() & tests

runtime/compiler/compile/J9Compilation.cpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/env/VMJ9Server.cpp, runtime/compiler/env/VMJ9Server.hpp, runtime/compiler/p/codegen/PPCPrivateLinkage.cpp
This fixes an issue with the code generated for containers with
-XX:+PortableSharedCache option. AOT code generated on P8 uses
pTOC and if the same container is used on P10 environment causes
a crash as pTOC is not there on P10. The fix will generate
materialize sequence of instructions when -XX:+PortableSharedCache
option is enabled and not pTOC.
Added query apis in TRJ9VMBase class
Added isPortableSCCenabled for JIT server
Port of https://github.com/eclipse-openj9/openj9/pull/15095 for the 0.33 release.
Signed-off-by: Bhavani SN <bhavani.sn@ibm.com>
=> (0.33) Fix usage of pTOC with portableSCC code run in P10 container

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp, runtime/compiler/env/j9method.cpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp, runtime/compiler/optimizer/J9RecognizedCallTransformer.hpp
This provides the opportunity to convert the call into a completely typical `checkcast` with a compile-time constant class bound (`loadaddr`). Even if the class bound can't be constant-folded, or if for some reason we simply fail to fold it, a `checkcast` whose class bound is not constant at compile time should still be at least as good as a call to `Class.cast` regardless of whether the call is inlined.
When the cast fails, the innermost frame listed in the stack trace will identify the call to `Class.cast` rather than an explicit throw within `Class.cast` itself. Additionally, the exception message will be generated in the same way as for `checkcast` bytecode instructions, which may (and appears to currently) differ cosmetically from the message used in `Class.cast`. Neither of these …
=> Recognize Class.cast and transform calls to it into checkcast

runtime/oti/jclprots.h
Add `InternalCRIUSupport` native method declarations
Note: since current `jclprots.h` declaration files are not in sorted order, just append new addition at end of the file.
=> Add InternalCRIUSupport native method declarations

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
PR #2361 introduced a number of JIT performance enhancements for checkcasts
involving interface classes.  Two of the most significant changes were the
introduction of a one-slot, dynamic cache to cache the last successful instance
class that matched the cast class.  It also inlined the itable walk to determine
if the interface class implemented the cast class.
Each time a successful checkcast was performed the cache would be updated with
that result at runtime (it was an LRU cache).  This cache was implemented as a
single, 8-byte data snippet located in the code cache.  The performance of this
approach may be acceptable for checkcast sites that do not see more than one
instance class, or when there is only a single thread of execution along this
path.  However, in the presence of multiple …
=> Improve checkcast/instanceof performance for interfaces on x86/x64

runtime/compiler/env/ProcessorDetection.cpp, runtime/compiler/runtime/Runtime.cpp
Calls to feGetEnv are usually cached in static variables. There were a few cases where the variables weren't declared static and so more calls to getenv were being made than was necessary. These were mostly fixed in OMR PR https://github.com/eclipse/omr/pull/6545, but I also noticed two cases in OpenJ9 code that are addressed in this PR.
The call in initializeProcessorType is probably not much of a problem as it seems likely that the containing function is only called once per JVM instantiation. I've fixed it for completeness as there's hopefully not much downside and it will make any future code review for missed statics a little easier.
The read of TR_silentEnv in feGetEnv2 itself is hopefully ok for caching too - I couldn't see any reason to read it on every call.
Personal build ok: …
=> Ensure calls to feGetEnv are cached

jcl/src/java.base/share/classes/java/lang/J9VMInternals.java, jcl/src/java.base/share/classes/java/lang/System.java, test/functional/cmdLineTests/cmdLineTest_J9tests/j9tests_console19.xml, test/functional/cmdLineTests/cmdLineTest_J9tests/playlist.xml
Fixes https://github.com/eclipse-openj9/openj9/issues/15129
=> Add jdk19 support for stdout.encoding and stderr.encoding

runtime/vm/jvminit.c
Issue https://github.com/eclipse-openj9/openj9/issues/15214
=> When -Xcompressedrefs is specified, use that mode regardless of -Xmx

runtime/compiler/optimizer/VectorAPIExpansion.cpp
Handles newly added vector IL Opcodes (vmin and vmax) introduced in OMR
Depends on https://github.com/eclipse/omr/pull/6495
=> Implement vmin and vmax IL Opcodes

runtime/vm/jvminit.c
Issue https://github.com/eclipse-openj9/openj9/issues/15214
Cherry pick https://github.com/eclipse-openj9/openj9/pull/15218 for the 0.33 release.
=> (0.33) When -Xcompressedrefs is specified, use that mode regardless of -Xmx

runtime/compiler/optimizer/J9TransformUtil.cpp
Instance final fields of Reflect package classes are safe to
fold and results in significant performance boost in reflection
speed benchmarks.
=> Fold instance final fields of Boolean and Reflection classes

doc/release-notes/0.31/0.31.md, doc/release-notes/0.32/0.32.md, doc/release-notes/0.33/0.33.md, runtime/vm/jvminit.c
Also replace "Java" with "OpenJDK" in recent release notes to match the convention.
=> Deprecate -XX:+AllowNonVirtualCalls

jcl/src/java.base/share/classes/java/lang/Access.java
Add `j.l.Access.parkVirtualThread` methods
```
j.l.Access.parkVirtualThread()
j.l.Access.parkVirtualThread(nanos)
```
closes https://github.com/eclipse-openj9/openj9/issues/15213
=> Add j.l.Access.parkVirtualThread methods

runtime/compiler/env/j9method.cpp
In JDK8, some Invokers methods do not have the same signatures as
JDK11+. This results in failing to recognize these methods in the
JIT for special handling intended for them. This change will
allow recognizing the different versions of these methods.
=> Update j.l.invoke.Invokers methods for JDK8 compatibility

jcl/src/java.base/share/classes/java/lang/Access.java
JDK19 `unparkVirtualThread` adopts `BaseVirtualThread`.
This passes `java/lang/Thread/virtual/ThreadAPI.java#id0` https://github.com/eclipse-openj9/openj9/issues/15152#issuecomment-1148960818.
=> JDK19 unparkVirtualThread adopts BaseVirtualThread

runtime/jcl/common/jdk_internal_misc_ScopedMemoryAccess.cpp, runtime/oti/jclprots.h
**New definition (JDK19+):**
```
native boolean closeScope0(MemorySessionImpl session);
```
**Old definition:**
```
native boolean closeScope0(Scope scope, Scope.ScopedAccessError exception);
```
Also, it is illegal to set the current exception while holding VM exclusive
access. So, the NPE is set outside the scope of VM exclusive access.
=> Update ScopedMemoryAccess.closeScope0 for JDK19

test/functional/cmdLineTests/jvmtitests/decompilationtests.xml
Timeout increased from 300 to 600 seconds since decomp002 takes more time
on some machines. **Ref:** https://github.com/eclipse-openj9/openj9/issues/15245#issuecomment-1149087197.
Related: https://github.com/eclipse-openj9/openj9/issues/15245
=> Increase timeout for decompilation tests

test/functional/cmdLineTests/gcRegressionTests/gcRegressionTests.xml
Related: https://github.com/eclipse-openj9/openj9/issues/15235
=>   Disable regex usage since cmdlinetester does not correctly process it

jcl/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/LayoutStrPreprocessor.java, jcl/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ProgrammableInvoker.java, jcl/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/TypeLayoutCheckHelper.java
The change is to ensure that the FFI specific java code
in the incubator module only works for Java 17 & 18.
=> Exclude the FFI specific java code(Incubator) from Java19

runtime/gc_base/modronapi.cpp, runtime/gc_glue_java/ConcurrentMarkingDelegate.cpp
If caller of explicit GC (for example RAS) already obtained exclusive VM
access, checking if the thread needs to halt after completing the GC
could lead to a deadlock. For example exclusive VM access could prevent
an inspector thread to proceed, while also this thread just blocked
expecting to be inspected.
The fix is to make an exception and skip the halt check if we know that
we hold exclusive VM access.
=> Skip halt check after explict GC, with external exclusive VM access

doc/release-notes/0.33/0.33.md
This commit moves the item for early access builds of AArch64 macOS from
"Notable changes in this release" to "Known issues" of v0.33.0 release notes.
=> Move AArch64 macOS from "Notable changes in this release"

test/functional/DDR_Test/tck_ddrext.xml
=> Don't let JIT compile the methods we need to find in tests

runtime/compiler/z/codegen/S390PrivateLinkage.cpp
Port of https://github.com/eclipse-openj9/openj9/pull/15270 for the 0.33 release.
Fixes https://github.com/eclipse-openj9/openj9/issues/15220
Signed-off-by: Spencer Comin <spencer.comin@ibm.com>
=> (0.33) Check for newInstanceImpl before doing profile guided devirt on Z JIT

test/functional/cmdLineTests/SystemPropertiesTest/src/SysPropTest.java
Fixes https://github.com/eclipse-openj9/openj9/issues/15275
Related to https://github.com/eclipse-openj9/openj9/pull/14579
Tested on jdk19 AIX via grinder https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/883/ which passed.
Depending what gets merged first, https://github.com/eclipse-openj9/openj9/pull/15290 can not disable the test or this PR can be updated to remove the disable.
=> Fix SysPropTest for jdk19

runtime/compiler/control/CompilationThread.cpp
Prevent hangs when preparing the JIT for checkpoint; there are two different circumstances that can lead to a hang:
1. Active comp threads waiting for work will wait on the comp monitor; if the hook thread does not notify them, then it will wait indefinitely for those comp threads.
2. Comp threads actively compiling will try to acquire Exclusive VMAccess; if the hook thread does not release VMAccess, then it will wait indefinitely for those comp threads.
Fixes https://github.com/eclipse-openj9/openj9/issues/15191
=> Prevent hangs when preparing the JIT for checkpoint

jcl/src/java.base/share/classes/java/lang/ClassLoader.java
ClassLoader.registerAsParallelCapable() must be called from a
ClassLoader subclass.
Issue https://github.com/eclipse-openj9/openj9/issues/14600
=> jdk19 registerAsParallelCapable() may throw IllegalCallerException

doc/release-notes/0.33/0.33.md
Related: https://github.com/eclipse-openj9/openj9-docs/pull/942
=> Add a note about cgroup v2 support in the 0.33 release

runtime/compiler/optimizer/InlinerTempForJ9.cpp
To allow vectorAPI expansion to scalarize or vectorize Vector API
intrinsic methods, we need to make sure that inliner does not inline it.
This commit adds a check in inliner policy to disable inlining of
VectorAPI intrinsics during inlining.
=> Disable Inlining of VectorIntrinsic Methods

jcl/src/java.base/share/classes/java/lang/String.java
If substring is longer than string, then it should return -1 early since
it is impossible for the substring to be found in the original string.
This early return also avoids an assertion failure when compact strings
are enabled in the StringUTF16 indexOf helpers which checks that the
source string is longer than the substring.
fyi: @tajila @dchopra001 
Internal build: `job/Build_JDK11_s390x_linux_Personal/1253/`
Internal openjdk test run, with `-XX:+CompactStrings` option: `job/Grinder/25000/`
Internal failing test without this change: `job/Grinder/24991/`
Though trying to call `"ââ".indexOf("âââ")` in a Java program with the options `-esa -XX:+CompactStrings` will also show the error:
```
Exception in thread "main" java.lang.AssertionError …
```
=> Return early in String.indexOf if substring is longer than string

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp, runtime/compiler/aarch64/runtime/Recompilation.spp, runtime/compiler/runtime/Trampoline.cpp
We use 2 cache slots for interface calls and when the cache hit, `blr` instruction
is used for the call. The function for updating the callsite on recompilation
did not handle such case and failed to update it silently.
This commit adds the code to support interface call case.
Master PR: https://github.com/eclipse-openj9/openj9/pull/15242
=> (0.33) AArch64: Handle interface call case when patching call site on recompilation

jcl/src/java.base/share/classes/java/lang/Class.java
It's better to use NULL for the bootstrap loader when calling
forNameImpl() as the VM can access this loader directly without fetching
and checking the native loader from the class loader object.
Called out by a review comment
https://github.com/eclipse-openj9/openj9/pull/15328#pullrequestreview-1007542140
=> Simplify Class.forName(String, Class)

jcl/src/java.base/share/classes/java/lang/Thread.java, runtime/jcl/common/thread.cpp, runtime/jcl/exports.cmake, runtime/jcl/uma/se19_exports.xml, runtime/jcl/uma/se6_vm-side_natives_exports.xml, runtime/oti/jclprots.h
- Only export Thread.yield0 for Java19 through RegisterNatives
Depends on: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/461
=> Refactor Thread.yield API

runtime/criusupport/criusupport.cpp, runtime/nls/j9cl/j9jcl.nls
`CIRU` throws `RestoreException` when `checkpointRestoreTimeDelta` is negative.
=> CRIU throws RestoreException when checkpointRestoreTimeDelta is negative

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/tdump/zebedee/le/DsaStackFrame.java, jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/corereaders/zos/le/DsaStackFrame.java
Also terminate if a cycle is discovered.
Fixes: #14908.
=> Improve robustness of scanning SFXM chains

jcl/src/java.base/share/classes/java/lang/InternalConstantPool.java, jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java, runtime/gc_modron_startup/mminit.cpp, runtime/jcl/common/thread.cpp, runtime/oti/j9nonbuilder.h, runtime/oti/vmconstantpool.xml, runtime/vm/callin.cpp, runtime/vm/jvmfree.c, runtime/vm/vmthinit.c, runtime/vm/vmthread.cpp
=> Add initial VM structure and JCL stub for Continuation

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp, runtime/compiler/aarch64/runtime/PicBuilder.spp, runtime/compiler/runtime/Runtime.cpp, test/functional/cmdLineTests/jvmtitests/playlist.xml
This commit adds code for rewriting data in snippets for field watch
on AArch64 macOS.
Fixes: #14502
=> AArch64 macOS: Call fieldWatchHelper in rewriting data in snippets

jcl/src/java.base/share/classes/java/lang/Class.java
Cache Class.toString name
Repeated calls to Class.toString() on non-primitives requires
concatenation and can have adverse performance impacts.
=> Cache Class.toString name

runtime/include/jvmti.h.m4, runtime/jvmti/j9jvmti.tdf, runtime/jvmti/jvmtiCapability.c, runtime/jvmti/jvmtiEventManagement.c, runtime/jvmti/jvmtiHelpers.c, runtime/jvmti/jvmtiHook.c, runtime/oti/j9vm.hdf
=> add JVMTI callback/hook for virtualThread

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/BuildVersionCommand.java
It was not reading the `platform` field causing misinterpretation of the following fields.
The `sdk` field was read as the number of tools yielding unreasonable values (e.g. 11.3.0 is expressed as 0x000b0300 = 721664), with significant expense of both time and space.
Also, the decomposition of versions was incorrect due to off-by-one errors in the loop bounds (e.g. 11.3.0 was decomposed as 0.110.30).
(Discovered while investigating #15114).
=> Correct reading BuildVersionCommand from OSX core files

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp, runtime/compiler/aarch64/runtime/PicBuilder.spp, runtime/compiler/runtime/Runtime.cpp, test/functional/cmdLineTests/jvmtitests/playlist.xml
This commit adds code for rewriting data in snippets for field watch
on AArch64 macOS.
Original PR in master: #15300
=> (0.33.0) AArch64 macOS: Call fieldWatchHelper in rewriting data in snippets

runtime/include/jni.h.m4
See:
* 8286176: Add JNI_VERSION_19 to jni.h and JNI spec
Also a little tidying up: mostly trailing whitespace.
=> Add JNI_VERSION_19 for Java 19+

buildenv/jenkins/variables/defaults.yml
The tag `OpenSSL_1_1_1p` appeared today: https://github.com/openssl/openssl/tree/OpenSSL_1_1_1p.
=> Update openssl to version 1.1.1p

runtime/compiler/optimizer/IdiomRecognition.cpp
Previously, a static store could be marked negligible based on its uses in `TR_CISCTransformer::simpleOptimization()`, which could allow for the loop to be transformed in a way that removes the store.
Issue: #15319
=> Prevent improper removal of static store in idiom recognition

runtime/criusupport/criusupport.cpp, runtime/nls/j9cl/j9jcl.nls, test/functional/cmdLineTests/criu/src/org/openj9/criu/TimeChangeTest.java
* Removed `elapsedTime < (MILLIS_DELAY_AFTERCHECKPOINTDONE + MAX_TARDINESS_MS))` (and a few others) which depend on the checkpoint process time. This test mainly ensures that the scheduled task skips the JVM down time between checkpoint and restore, and won't be fired right after restore. This addresses https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/110#issuecomment-1157549598 & https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/462#issuecomment-1160364594;
* Set `systemReturnCode` w/ `vm->portLibrary->checkpointRestoreTimeDelta`, and to be printed out via `J9NLS_JCL_CRIU_NEGATIVE_CHECKPOINT_RESTORE_TIME_DELTA`. This addresses https://github.com/eclipse-openj9/openj9/pull/15232#discussion_r899135664.
FYI @keithc-ca 
=> CRIU fix Timer.schedule test and show checkpointRestoreTimeDelta value

runtime/compiler/codegen/CodeGenGPU.cpp, runtime/compiler/runtime/ClassUnloadAssumption.cpp
Changed 'TR::ILOpCode::NumAllIlOps' to 'TR::NumAllIlOps'. 
Casted the argument so the type is void*.
Signed-off-by: Manasha Vetrivelu <manasha.vetrivelu@ibm.com>
=> Fixing errors present when creating a build with PROD_WITH_ASSUMES enabled

runtime/oti/VMHelpers.hpp
Use constant 0x3 to only get 2 bits so sign extension won't give us an incorrect value.
`encodeUTF8CharI8` is used in `GetStringUTFRegion` and similar string bytes to modified UTF8 functions when compact strings is enabled and each character in the string can fit in 1 byte representations.
Without this fix, `encodeUTF8CharI8` can fail on byte values 0x80 to 0xFF, as shown in internal testing here: `job/Grinder/25181/`
Successful run with the fix: `job/Grinder/25186/`
fyi @pshipton
=> Fix conversion to UTF8 in encodeUTF8CharI8

runtime/compiler/net/CommunicationStream.hpp, runtime/compiler/runtime/Listener.cpp
The SSL connection needs to be closed before the underlying TCP socket.
=> Correctly close SSL connections in JITServer code

runtime/compiler/control/JITServerHelpers.cpp
Allow the client to reconnect immediately (instead of after up to 1 millisecond) when the reconnect time option is set to 0.
=> Correctly handle JIT client option -Xjit:reconnectWaitTimeMs=0

jcl/src/java.base/share/classes/java/lang/Class.java, test/functional/Java12andUp/build.xml, test/functional/Java12andUp/src/org/openj9/test/java_lang/Test_Class.java
Issue https://github.com/eclipse-openj9/openj9/issues/14598
Continuing to throw IllegalArgumentException as the cause for the UnsupportedOperationException is done for compatibility.
=> Class.arrayType() throws UnsupportedOperationException in jdk19+

runtime/oti/j9nonbuilder.h, runtime/vm/vmthread.cpp
**Reasons for pinning:**
```
public enum Pinned {
/** In native code */
NATIVE,
/** Holding monitor(s) */
MONITOR,
/** In critical section */
CRITICAL_SECTION
}
```
**Support for #15174 and #15175:**
- `J9VMThread->continuationPinCount` will support native methods in
`class Continuation`: `pin()` and `unpin()`. It will also be associated to
`Pinned.CRITICAL_SECTION`.
- `J9VMThread->ownedMonitorCount` will be associated to `Pinned.MONITOR`.
- `J9VMThread->callOutCount` will be associated to `Pinned.NATIVE`.
=> Loom Support: Pin Counters

test/functional/cmdLineTests/fips/build.xml, test/functional/cmdLineTests/fips/fips.xml, test/functional/cmdLineTests/fips/playlist.xml, test/functional/cmdLineTests/fips/src/org/openj9/test/fips/FIPSKeyExtractImport.java, test/functional/cmdLineTests/fips/src/org/openj9/test/fips/FIPSProvidersTest.java
This PR contains three tests in FIPS mode. `FIPSProviderTest` aims to ensure that a program in FIPS mode has 4 providers and they are the right ones. `FIPSKeyExtractImport` with `encrypt` args aims to make sure that importing secret keys work in FIPS mode. `FIPSKeyExtractImport` with `extractkey` args aims to check that extracting RSA keys work in FIPS mode.
=> Add tests in FIPS mode

test/functional/cmdLineTests/gcRegressionTests/gcRegressionTests_excludes.xml
Closes https://github.com/eclipse-openj9/openj9/issues/15238
Reverts part of https://github.com/eclipse-openj9/openj9/pull/15237
=> Re-include "Unload lots of classes" GC regression tests on jdk19

test/functional/cmdLineTests/gcRegressionTests/gcRegressionTests_excludes.xml
Tests were fixed by https://github.com/eclipse-openj9/openj9/pull/15255
Issue https://github.com/eclipse-openj9/openj9/issues/15235
Reverts part of https://github.com/eclipse-openj9/openj9/pull/15237
=> Un-exclude gcRegression check for memory corruption tests

runtime/bcutil/BuildResult.hpp, runtime/bcutil/ROMClassCreationContext.hpp, runtime/bcutil/defineclass.c, runtime/cfdumper/stubs.c, runtime/jcl/common/jcldefine.c, runtime/oti/bcutil.h
=> Check for duplicate class definitions when creating rom class

runtime/jvmti/jvmtiThread.c, runtime/jvmti/jvmtiTimers.c, runtime/oti/j9.h, runtime/oti/jvmtiInternal.h, runtime/oti/vmconstantpool.xml
Return JVMTI_ERROR_UNSUPPORTED_OPERATION from JVMTI functions that do not
accept virtual threads as their current thread or parameters.
Issue: #15183
=> Add error handling for JVMTI functions for Loom

runtime/compiler/aarch64/runtime/Recompilation.spp, runtime/jilgen/jilconsts.c
Reverts eclipse-openj9/openj9#15406
See https://github.com/eclipse-openj9/openj9/issues/15443#issuecomment-1168914790
Fixes https://github.com/eclipse-openj9/openj9/issues/15443
=> Revert "jilconst: don't redefine OMR_GC_CONCURRENT_SCAVENGER"

runtime/compiler/control/CompilationRuntime.hpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/HookedByTheJit.cpp, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/rossa.cpp, runtime/compiler/net/LoadSSLLibs.cpp, runtime/compiler/net/LoadSSLLibs.hpp, runtime/compiler/runtime/Listener.cpp, runtime/compiler/runtime/MetricsServer.cpp, runtime/compiler/runtime/MetricsServer.hpp
The new options `-XX:JITServerMetricsSSLKey` and `-XX:JITServerMetricsSSLCert` behave like their JITServer counterparts, automatically enabling SSL/TLS communication between the JITServer metrics server and clients like Prometheus.
Fixes: #15052
=> Add optional encryption to the JITServer metrics server

runtime/compiler/aarch64/runtime/Recompilation.spp, runtime/jilgen/jilconsts.c
This is a corrected version of #15406: When defined, continue to write `OMR_GC_CONCURRENT_SCAVENGER` to `jilvalues`.
For platforms that include `j9cfg.h`, avoid generating a duplicate, conflicting definition in `jilconsts`.
Add missing include in `aarch64/runtime/Recompilation.spp`.
=> jilconst: don't redefine OMR_GC_CONCURRENT_SCAVENGER

runtime/compiler/optimizer/VectorAPIExpansion.cpp
- reduction intrinsic for FP types returns long that is
a bit representation of that type. Therefore only cast is needed
=> Fix vector reduction for Float and Double

runtime/jcl/CMakeLists.txt, runtime/jcl/common/jdk_internal_vm_Continuation.cpp, runtime/jcl/exports.cmake, runtime/jcl/module.xml, runtime/jcl/uma/se19_objects.xml, runtime/oti/jclprots.h
- `Continuation.pin()`: Increment the counter to pin a continuation. Throws
`IllegalStateException` in case of an overflow.
- `Continuation.unpin()`: Decrement the counter to unpin a continuation. Throws
`IllegalStateException` in case of an underflow.
Related: #15174
=> Continuation: pin and unpin implementation

runtime/include/jvmti.h.m4
JvmtiCapabilities struct cannot have padding between fields.
=> Fix padding in jvmtiCapabilities structure

runtime/compiler/optimizer/BoolArrayStoreTransformer.cpp
On DLT compiles where type information is not available we must not truncate byte stores to 1-bit.
Fixes #15369
=> Make BoolArrayStoreTransformer iterate CFG for DLT compiles

test/functional/cmdLineTests/libpathTest/playlist.xml
Fix #15119 
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>
=> Disable libpathTestRtfChild on headless platforms

buildenv/jenkins/variables/defaults.yml
After https://github.com/eclipse-openj9/openj9/pull/15433 was merged,
1.1.1q on xmac no longer compiles. See also
https://github.com/eclipse-openj9/openj9/pull/15484#issuecomment-1175181647
The problem is already fixed in OpenSSL for the next release.
https://github.com/openssl/openssl/commit/f9e578e720
=> Use OpenSSL 1.1.1p for xmac

runtime/rasdump/javadump.cpp
Generating a java dump with `-Xint` in a VM configured with `--enable-jitserver` faults:
```
Thread 3 "Signal Reporter" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7f6d700 (LWP 1296761)]
JavaCoreDumpWriter::writeEnvironmentSection (this=0x7ffff7f6a130) at /home/keithc/space/openj9/jdk11/openj9/runtime/rasdump/javadump.cpp:1078
1078		if (0 != jitConfig->clientUID) {
(gdb) print jitConfig
$1 = (J9JITConfig *) 0x0
```
=> Add missing NULL-check for jitConfig

buildenv/docker/mkdocker.sh
Add cap_sys_admin capabilities to python3 to Ubuntu docker container.
=> Add python3 capabilities for CRIU to docker container

runtime/include/jvmti.h.m4
There is no definition of `JVMTI_VERSION_15` in the reference implementation.
Also tidy up
* remove trailing whitespace
* use tabs only for indentation
* format consistently
=> Remove unwanted definition of JVMTI_VERSION_15

runtime/gc_base/ObjectAccessBarrier.cpp, runtime/vm/description.c
1. Set backfillOffset of VT to instance size as normal classes.
2. Copy the VT hash code when doing copyObjectFields().
=> Do not set backfillOffset of VT to -1

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/JVMCheckpointException.java, jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/RestoreException.java
Native `setCurrentExceptionUTF()` requires a constructor w/ single message parameter.
fixes https://github.com/eclipse-openj9/openj9/issues/15524
A sample stack trace w/ this PR:
```
org.eclipse.openj9.criu.JVMCheckpointException: Blocking operation is not allowed in CRIU single thread mode.
at org.openj9.criu.TestSingleThreadModeCheckpointException$2.run(TestSingleThreadModeCheckpointException.java:77)
at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.lambda$registerPreSnapshotHook$3(CRIUSupport.java:471)
at openj9.criu/org.eclipse.openj9.criu.J9InternalCheckpointHookAPI$J9InternalCheckpointHook.runHook(J9InternalCheckpointHookAPI.java:116)
at openj9.criu/org.eclipse.openj9.criu.J9InternalCheckpointHookAPI.runHooks(J9InternalCheckpointHookAPI.java:80)
at …
```
=> CRIU add single parameter exception constructors to support native setCurrentExceptionUTF()

runtime/compiler/optimizer/VectorAPIExpansion.hpp
Enable Vector API Expansion on AArch64.
=> AArch64: Enable Vector API Expansion

runtime/bcutil/cfreader.c, runtime/nls/cfre/cfrerr.nls
See https://github.com/eclipse-openj9/openj9/pull/15053#pullrequestreview-1036454386
* fix related descriptions
* add `END NON-TRANSLATABLE` comment
=> Correct J9NLS_CFR_ERR_NEST_MEMBER_INVALID_REFERENCETYPE_DESCRIPTOR

test/TestConfig/resources/excludes/latest_exclude_20.txt
Add `openj9` exclude file `latest_exclude_20.txt` for Java 20
Copied from `latest_exclude_19.txt`
Related to https://github.com/eclipse-openj9/openj9/pull/15053
=> Add openj9 exclude file for Java 20

runtime/compiler/codegen/J9TreeEvaluator.cpp
PR #15079 made it possible for a checkcast node to have a runtime variable cast class, invalidating the assertion in `calculateInstanceOfOrCheckCastSequences`.
Fixes: #15449
Signed-off-by: Spencer Comin <spencer.comin@ibm.com>
=> Remove assert invalidated by "Recognize Class.cast and transform calls to it into checkcast"

runtime/compiler/optimizer/J9TransformUtil.cpp
- we would spuriously fail to fold loads of reference array
elements at odd positions when compressed references were enabled
because the alignment test looked for 8-byte alignment even though
only 4-byte alignment is really required
=> Fix reference array element alignment test for stable arrays

runtime/oti/ObjectMonitor.hpp, runtime/vm/ObjectMonitor.cpp, runtime/vm/monhelpers.c
In order to support if a `Continuation` is pinned, `ownedMonitorCount` is
- incremented when a monitor is successfully acquired; and
- decremented when a monitor is successfully released.
`ownedMonitorCount` is updated closer to the `lockword` modification.
**monitor entry points:**
1. `ObjectMonitor.hpp::inlineFastObjectMonitorEnter`
- `inlineFastInitAndEnterMonitor`: _increment_ counter
2. `ObjectMonitor.hpp::objectMonitorEnterNonBlocking`
- flat / lock reservation case: _increment_ counter
- `spinOnFlatLock`
- `inlineFastInitAndEnterMonitor`: _increment_ counter
- `spinOnTryEnter`
- inflated case: _increment_ counter
3. `ObjectMonitor.hpp::objectMonitorEnterBlocking`:
- inflated case: _increment_ counter
- `inlineFastInitAndEnterMonitor`: _increment_ counter
**monitor exit points:**
1. …
=> Loom Pinning: Manage J9VMThread->ownedMonitorCount

runtime/vm/BytecodeInterpreter.hpp, runtime/vm/OutOfLineINL.hpp, runtime/vm/callin.cpp
In order to support if a `Continuation` is pinned, `callOutCount` is
- incremented when a frame of a below type is build.
- decremented when a frame of a below type is removed.
**Frame types**, which have been accounted:
- `J9SF_FRAME_TYPE_JNI_NATIVE_METHOD`
- `J9SF_FRAME_TYPE_NATIVE_METHOD`
- Call-in frame
**TODOs** for the JIT (#15175):
- Increment `callOutCount` in `JNILinkage::buildJNICallOutFrame`.
- Decrement `callOutCount` in `JNILinkage::restoreJNICallOutFrame`.
- Related frame type: `J9SF_FRAME_TYPE_JIT_JNI_CALLOUT`.
Related: #15174
=> Loom Pinning: Manage J9VMThread->callOutCount

runtime/jcl/common/java_dyn_methodhandle.c, runtime/jcl/common/vm_scar.c
The current home of `clearNonZAAPEligibleBit` implementation in java_dyn_methodhandle.c
is only compiled if `J9VM_OPT_METHOD_HANDLE` is set. Moving the implementation to vm_scar.c
as a more generic home that is always compiled, to avoid any unresolved symbol errors
during linking when `J9VM_OPT_METHOD_HANDLE` is not set.
=> Relocate clearNonZAAPEligibleBit implementation to vm_scar.c

runtime/jcl/common/jdk_internal_vm_Continuation.cpp
Visual Studio warns of possible data loss converting from 'UDATA' to 'jboolean'.
=> Fix compiler warning

jcl/src/java.base/share/classes/jdk/internal/foreign/abi/DowncallLinker.java, jcl/src/java.base/share/classes/jdk/internal/foreign/abi/UpcallLinker.java, jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java, jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalUpcallHandler.java, jcl/src/java.base/share/classes/openj9/internal/foreign/abi/LayoutStrPreprocessor.java, jcl/src/java.base/share/classes/openj9/internal/foreign/abi/UpcallMHMetaData.java, jcl/src/jdk.incubator.foreign/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java, jcl/src/jdk.incubator.foreign/share/classes/openj9/internal/foreign/abi/InternalUpcallHandler.java, jcl/src/jdk.incubator.foreign/share/classes/openj9/internal/foreign/abi/LayoutStrPreprocessor.java, jcl/src/jdk.incubator.foreign/share/classes/openj9/internal/foreign/abi/TypeLayoutCheckHelper.java, jcl/src/jdk.incubator.foreign/share/classes/openj9/internal/foreign/abi/UpcallMHMetaData.java, test/functional/Java17andUp/playlist.xml, test/functional/Java18andUp/playlist.xml
The changes mainly include the java part of creating
the upcall stub & metadata which are required in the
FFI upcall against JEP424 in JDK19.
=> [Part 1/JDK19] FFI Upcall: creating the upcall stub (java part)

runtime/j9vm/javanextvmi.c, runtime/vm/extendedMessageNPE.cpp
NPE extended message generation missed `j9mem_free_memory()` calls
[Internal personal build](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/13581/)
fixes https://github.com/ibmruntimes/Semeru-Runtimes/issues/32
=> NPE extended message generation missed j9mem_free_memory calls

runtime/j9vm/javanextvmi.c, runtime/vm/extendedMessageNPE.cpp
NPE extended message generation missed `j9mem_free_memory()` calls
Cherry-pick https://github.com/eclipse-openj9/openj9/pull/15550
=> (0.33) NPE extended message generation missed j9mem_free_memory calls

runtime/oti/vmconstantpool.xml, runtime/vm/bindnatv.cpp, runtime/vm/callin.cpp
Added an assertion `VM_VMHelpers::classRequiresInitialization`;
Updated comments.
[An internal personal build](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/13599/)
There was no test failure reported due to the issue being addressed. It was discovered during static code reviewing.
=> Use internalRunStaticMethod to pass object pointer arguments

runtime/compiler/optimizer/BoolArrayStoreTransformer.cpp
The bytecode may have stored a `byte[]` reference into a `boolean[]` parameter slot, or vice versa, on a path that does not get translated into IL for the DLT compilation. In that case, the compiler could incorrectly treat certain `bstorei` nodes as though the array type is known based on the signature of a parameter.
=> Stop trusting parameter types for bastore in DLT

runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/J9Options.hpp, runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/control/JITServerHelpers.cpp, runtime/compiler/control/JITServerHelpers.hpp, runtime/compiler/env/J9PersistentInfo.hpp, runtime/compiler/net/CommunicationStream.hpp, runtime/compiler/net/StreamExceptions.hpp
If the JITServer is under very heavy load, the connection between it and
its clients may become overwhelmed, leading to stream failures from
socket read time outs in the client and consequently to large spikes in
client RSS. To remedy this:
- The default client socket timeout is now 30000ms.
- -XX:+JITServerLocalSyncCompiles is now on by default.
- If a connection is lost due to socket timeout on read, the client will
immediately try to reconnect once before starting the usual
exponential backoff in wait time.
Fixes: https://github.com/eclipse-openj9/openj9/issues/15396
=> Improve JITServer handling of socket timeouts

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java, runtime/jcl/common/jdk_internal_vm_Continuation.cpp, runtime/jcl/exports.cmake, runtime/jcl/uma/se19_exports.xml, runtime/oti/jclprots.h
`isPinned` returns true if the current continuation is pinned.
**TODO:** Add support for nested continuations, which will utilize
`ContinuationScope`.
Related: #15174
=> Continuation isPinned implementation

test/functional/cmdLineTests/SystemPropertiesTest/src/SysPropTest.java
AIX now works properly from 18.0.2, matching jdk19 behavior.
This fixes the cmdLineTester_SystemPropertiesTest_aix test.
Tested via grinder with the 0.33 18.0.2 build.
https://openj9-jenkins.osuosl.org/job/Grinder/1165/ - passed
The test fails on an 18.0.2 build without this change.
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_extended.functional_ppc64_aix_Release_testList_0/15/
=> Update SysPropTest to work on AIX with jdk18.0.2

test/functional/cmdLineTests/SystemPropertiesTest/src/SysPropTest.java
Cherry pick https://github.com/eclipse-openj9/openj9/pull/15292 and https://github.com/eclipse-openj9/openj9/pull/15588 for 0.33
=> (0.33) Update SysPropTest to work on AIX with jdk18.0.2

runtime/compiler/z/codegen/J9TreeEvaluator.cpp
Patch to use VFE1 feature instead of flag when checking if vector FMA is supported.
See discussion at https://github.com/eclipse/omr/pull/6615 as to why this is necessary.
=> Check VFE1 feature instead of flag when generating Math.fma on Z

runtime/compiler/x/env/J9CPU.cpp
=> Add AVX2 to supported feature tests

LICENSE, longabout.html
Use of musl was removed with https://github.com/eclipse-openj9/openj9/pull/3952
The earliest copyright date in OpenJ9/OMR source files is 1991 not 2017.
=> Remove musl license and update OpenJ9/OMR start copyright date

LICENSE, longabout.html
Use of musl was removed with https://github.com/eclipse-openj9/openj9/pull/3952
The earliest copyright date in OpenJ9/OMR source files is 1991 not 2017.
Cherry pick https://github.com/eclipse-openj9/openj9/pull/15597 for 0.33
=> (0.33) Remove musl license and update OpenJ9/OMR start copyright date

cdsadapter/README.md
The Eclipse Equinox project has been moved to the new github repo. Fix
the URL to point to the correct repo.
=> Fix obsolete link

runtime/compiler/optimizer/J9Optimizer.cpp, runtime/compiler/optimizer/VectorAPIExpansion.cpp
- remove unnecessary i2l when generating address
- invalidate class if it can't be either vectorized or scalarized
- print optLevel in verbose messages
- run OSRGuardRemoval afterwards
=> Apply performance and functional fixes to VectorAPIExpansion

runtime/compiler/z/codegen/S390PrivateLinkage.cpp
Previously support of vector registers were checked while creating a
private linkage, which would not be a good place to do so. It should be
set while initializing Code Generator Object. This PR removes that part
of code from OpenJ9.
=> Remove setting of Vector Supports in Linkage

runtime/jilgen/jilconsts.c, runtime/oti/j9nonbuilder.h
Move inline JIT GPR spill area declaration from J9CInterpreterStackFrame
into new struct J9JITGPRSpillArea.
Related: #15464
=> Abstract JIT GPR spill area

runtime/compiler/net/CommunicationStream.hpp
=> Handle EINTR errors in JITServer networking

test/functional/cmdLineTests/jvmtitests/jvmtitests_excludes_20.xml
See https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_s390x_linux_Personal/25 which encounter multiple failures of the form.
> functional/cmdLineTests/jvmtitests/jvmtitests_excludes_20.xml (No such file or directory)
=> Clone jvmti test exclusions from 19 for 20

runtime/gc_base/GCExtensions.hpp, runtime/gc_modron_startup/mminit.cpp, runtime/gc_modron_startup/mmparseXXgc.cpp
- Concurrent Scavenger can be run at any platform where it is enabled,
there is no extra check required
- There is no need to enforce usage Software Range Check Barruer on
platforms where HW is not available
- add extensions->softwareRangeCheckReadBarrierForced to indicate
-XXgc:softwareRangeCheckReadBarrier is requested explicitly, stop use
extensions->softwareRangeCheckReadBarrier for this purpose
=> Cleaning for Concurrent Scavenger initialization

runtime/jcl/common/jdk_internal_misc_ScopedMemoryAccess.cpp
Java_jdk_internal_misc_ScopedMemoryAccess_closeScope0 does not need to
search for the scope in non-java threads.
Closes: #15450
=> Walk threads that run java code only in closeScope0

runtime/compiler/ilgen/J9ByteCodeIlGenerator.hpp, runtime/compiler/ilgen/Walker.cpp, runtime/compiler/x/codegen/J9TreeEvaluator.cpp
ILGen:
- Pass `returnClassForAOT` as in `getClassFromConstantPool` which is required to retrieve class in non-SVM AOT compilation
- Pass cpindex in `findOrCreateClassSymbol` which is required for `TR_ClassAddress` relocation record
- When generating IL for `aconst_init`, if the class has a field which is also value type, the non-SVM AOT compilation is aborted in ILGen because the `cpIndex` for the field is unknown and it is required to materialize the class in AOT load
- Update `genWithField` methods and `genFlattenableWithField` to use `int32_t` instead of `uint16_t` for their cpIndex arguments
X86:
- Evaluate the class into a register for loadaddr under new
- Use ASSERT_FATAL if the classReg is NULL in non-SVM AOT
Fixes: #15423, #15424
Signed-off-by: Annabelle Huo …
=> Fix issues with non-SVM aconst_init AOT compilation

runtime/jcl/common/thread.cpp
Current code holds pointers to thread objects across the call to
allocate the returned array. This results in ptentially returning invalid
pointers if the allocation results in a GC.
=> Fix issue in java.lang.Thread.getThreads

runtime/jcl/common/thread.cpp, runtime/jvmti/jvmtiThread.c
This change impacts the following methods in JDK19+:
- `private static native Thread[] getThreads()`
- `jvmtiGetAllThreads`
Virtual threads are ignored by looking at `J9VMThread->carrierThreadObject`
instead of `J9VMThread->threadObject`.
Related: #15183
=>   Ignore VirtualThreads in jvmtiGetAllThreads and Thread.getThreads 

test/functional/Valhalla/playlist.xml, test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeGenerator.java, test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java
For issue #14741
- Fix bugs in ValueTypeGenerator.java/ValueTypeTests.java
- Enable verification when running valuetype tests
=> Allow verifier to run in valuetype tests

runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/control/JITServerHelpers.cpp, runtime/compiler/control/JITServerHelpers.hpp, runtime/compiler/env/J9ClassEnv.cpp, runtime/compiler/env/J9ClassEnv.hpp, runtime/compiler/net/CommunicationStream.hpp, runtime/compiler/net/MessageTypes.cpp, runtime/compiler/net/MessageTypes.hpp, runtime/compiler/runtime/JITClientSession.cpp, runtime/compiler/runtime/JITClientSession.hpp
`getDefaultValueSlotAddress()` returns the reference to the address of the default value instance for a value class.
[edited]
~If the class is initialized, devalue value instance for the class is allocated. When generating `aconst_init`, we can load from the default value slot.~
~- [x] Depends on https://github.com/eclipse/omr/pull/6530~
=> Add API getDefaultValueSlotAddress

runtime/gc_vlhgc/CopyForwardScheme.cpp
Currently MM_CopyForwardScheme::updateMarkMapAndCardTableOnCopy() throws
assertion unreachable for unexpected Card state. Replacing assertion
unreachable to assertion with message to get extra information and
simplify debugging
=> Enhance assertion to simplify debugging

runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/sharedCacheAPI/sca001.c
Fixes https://github.com/eclipse-openj9/openj9/issues/15649
Tested via https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1211
=> Allow for incompatible caches in JVMTI shared cache management test

runtime/compiler/optimizer/DynamicLiteralPool.cpp
This commit fixes a mismatch between the format string and the arguments
for performTransformation().
=> Fix a message in TR_DynamicLiteralPool::addNewAloadChild()

test/functional/cmdLineTests/criu/criuScript.sh, test/functional/cmdLineTests/criu/criu_keepCheckpoint.xml, test/functional/cmdLineTests/criu/src/org/openj9/criu/CRIUSimpleTest.java
- Fix cmdLineTester_criu_keepCheckpoint input arguments
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/14486
=> Fix cmdLineTester_criu_keepCheckpoint

jcl/src/java.base/share/classes/java/lang/Access.java
Set current thread to the carrier thread, run the task, and restore the initial thread afterwards.
Fix internal RTC 147936.
=> Implement Access.executeOnCarrierThread()

runtime/compiler/env/J9SharedCache.cpp, runtime/compiler/env/J9SharedCache.hpp, runtime/compiler/runtime/IProfiler.cpp
Before this change, each `TR_IPBCDataCallGraph` entry that is persisted can contain
up to 3 ROMClasses and their associates sampling frequencies. When loading from
SCC we need to convert from a ROMClass to a RAMClass. This is done with the
help of the `matchRAMclassFromROMclass()` frontend method, which first tries
the classloader of the method being compiled and then the bootstrap classloader.
If none of these attempts is successfull, we store NULL into the IProfiler entry
which is created from the SCC entry.
In this commit we change the mechanism to convert from a ROMClass to a RAMClass,
to match the mechanism that is used in AOT relocation records. Specifically, the
new code is using the mechanism that associates a classloader with the first class
that is loaded by that class loader …
=> Change how TR_IPBCDataCallGraph entries are persisted into SCC

runtime/jcl/common/thread.cpp, runtime/jcl/j9jcl.tdf, runtime/jvmti/jvmtiRawMonitor.c, runtime/oti/VMHelpers.hpp, runtime/oti/j9nonbuilder.h, runtime/oti/vm_api.h, runtime/vm/CRIUHelpers.cpp, runtime/vm/intfunc.c, runtime/vm/j9vm.tdf, runtime/vm/threadhelp.cpp, test/functional/cmdLineTests/criu/criu_nonPortable.xml, test/functional/cmdLineTests/criu/src/org/openj9/criu/CRIUTestUtils.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/TestDelayedOperations.java
Added `J9_SINGLE_THREAD_MODE_OP_INTERRUPT`;
Saved Thread instances to `delayedLockingOperationsRoot` queue;
`CRIUHelpers` refactoring ;
Added tests.
closes https://github.com/eclipse-openj9/openj9/issues/15538
=> CRIU delay Thread.interrupt() in single thread mode

runtime/verbose/errormessagehelper.c
The change is to resolve the crash issue specific to a stackmap
frame without any element in 'locals' and 'stack' when allocating
the memory of stackmap frame in the error message framework
during the runtime verification.
Fixes: #15639
=> Fix the crash issue with the error message framework in Verifier

runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/CompilationThread.hpp, runtime/compiler/control/J9Options.cpp, runtime/oti/j9nonbuilder.h, runtime/oti/vm_api.h, runtime/vm/CRIUHelpers.cpp, runtime/vm/intfunc.c
To make life simpler for end users CRIU mode can also implicitly enable JITServer client mode so that restored processes can seamlessly connect to a JITServer should one be available.
This PR accomplishes two things:
1. Implicitly enables JITServer when CRIU non-portable mode is enabled (and allows disabling via explicit `-XX:-UseJITServer`)
2. Delays remote compilations in non-portable mode until after the process is restored
Neither of the above happens in portable mode. Users can explicitly enable JITServer in portable mode via `-XX:+UseJITServer` if they wish. Delaying compilations until after restore doesn't make sense in portable mode since there is no limit on how many times the process can be checkpointed/restored.
Here's a summary of operations under various combinations of …
=> Enable JITServer in CRIU non-portable mode

jcl/src/java.base/share/classes/java/lang/StringBuffer.java, jcl/src/java.base/share/classes/java/lang/StringBuilder.java
In StringBuilder and StringBuffer, decompress() usually only works up
to the current data length. However, methods like move() can place
characters past the current length, so add a parameter to decompress()
in order to specify the number of characters that are decompressed.
Fixes issues with insert() method when compact strings is enabled and
the caller has compressed storage and the inserted object is not
compressed.
fyi: @pshipton
=> Add option to decompress() for variable length 

test/functional/cmdLineTests/criu/criu_nonPortable.xml
Disable testSystemNanoTime due to intermitten criu failures
=> Disable testSystemNanoTime due to intermitten criu failures

jcl/jpp_configuration.xml
Use `rt-compressed.sunJava20.jar` instead of `rt-compressed.sunJava19.jar` for `JAVA20`.
=> Update classpath for JAVA20

runtime/compiler/env/VMJ9.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/optimizer/J9Simplifier.cpp, runtime/compiler/x/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/J9CodeGenerator.cpp, test/functional/cmdLineTests/criu/criu_nonPortable.xml, test/functional/cmdLineTests/criu/playlist.xml, test/functional/cmdLineTests/criu/src/org/openj9/criu/TimeChangeTest.java
The attached patches
1. Fix the x86 codegen's `System.nanoTime()` implementation to do the right thing in checkpoint mode
2. Disable the Z codegen's implementation in checkpoint mode until it can be fixed to do the right thing
3. Add a test case to check that JIT compiled code containing calls to `System.nanoTime()` behaves as expected in checkpoint mode
Fixes #15513
=> Fix JIT System.nanoTime() in checkpoint mode

runtime/jvmti/jvmtiThreadGroup.c, runtime/oti/vmconstantpool.xml, test/functional/cmdLineTests/jvmtitests/jvmtitests_excludes_19.xml
The ThreadGroup class does not store its threads anymore and child groups
are separated into "groups" and "weaks" ThreadGroup arrays.
The child ThreadGroups array is populated from the ThreadGroup's "groups"
and "weaks" arrays, which are the child ThreadGroups that are strongly
and weakly reachable from the parent.
The threads array is constructed by iterating over all J9VMThreads and
adding the threads that belong in the given ThreadGroup.
The returned arrays are constructed while locking on the ThreadGroup
object.
Fixes: #15244
Issue: #15183
=> Update jvmtiGetThreadGroupChildren for java 19

runtime/jcl/common/jclcinit.c, runtime/jcl/common/thread.cpp, runtime/jcl/exports.cmake, runtime/jcl/uma/se19_exports.xml, runtime/oti/j9nonbuilder.h, runtime/vm/vmthinit.c
notifyJvmtiMountBegin() will be used to add a virtual thread to the list
and allocate thread local storage, while notifyJvmtiUnmountEnd() will be
used to remove a virtual thread from the list and deallocate thread
local storage. The list's root is a global jni ref to an empty virtual
thread to prevent references to it from becoming stale.
Issue: #15183
=> Add VirtualThread native stubs and the active VirtualThread list

runtime/compiler/control/J9Options.cpp
The JITServerLocalSyncCompiles option causes remote recompilations to
be scheduled after synchronous JIT compilations. This is incompatible
with FullSpeedDebug, which is supposed to disable recompilations.
=> Disable LocalSyncCompiles under FullSpeedDebug

runtime/compiler/control/CompilationThread.cpp
We now prefer to compile locally when local sync compilation
is enabled and the method in question is cold and synchronous.
A function was also passed the incorrect pc when adding a remote
compilation request. This was also fixed.
=> Prefer local compilations in more cases

jcl/src/java.base/share/classes/java/lang/Access.java, runtime/j9vm/exports.cmake, runtime/j9vm/j9vmnatives.xml, runtime/j9vm/javanextvmi.c, runtime/j9vm/module.xml, runtime/redirector/forwarders.m4
See https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_linux_OpenJDK/313 which says:
```
01:58:11  /home/jenkins/workspace/Build_JDKnext_x86-64_linux_OpenJDK/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:66: error: Access is not abstract and does not override abstract method isCarrierThreadLocalPresent(CarrierThreadLocal<?>) in JavaLangAccess
01:58:11  final class Access implements JavaLangAccess {
01:58:11        ^
```
Also required is a new JVM function: `JNIEXPORT jint JNICALL JVM_GetClassFileVersion(JNIEnv *, jclass)`.
=> Fix build errors in jdk20

runtime/compiler/x/env/J9CPU.cpp
AOT code embedded in containers needs to be able to run on a wide array
of processors. For this reason, the portable AOT code is allowed to
use only a subset of processor features, subset defined by the
SandyBridge architecture. Since AVX512 instructions are not supported
by SandyBridge, the AVX512F feature should be removed from the portable
set of features.
Issue: #15697
=> Remove AVX512F from features supported by portable CPU

runtime/gc_vlhgc/CopyForwardScheme.cpp
Add all known but unexpected card states to switch explicitly
Add assertion for each of them
=> Add extra assertions for unexpected Card states

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp, runtime/compiler/compile/J9SymbolReferenceTable.cpp, runtime/compiler/compile/J9SymbolReferenceTable.hpp, runtime/compiler/il/J9SymbolReference.cpp, runtime/compiler/ilgen/Walker.cpp, runtime/compiler/runtime/RelocationRecord.cpp, runtime/compiler/runtime/RelocationRecord.hpp, runtime/compiler/runtime/RelocationRuntime.hpp, runtime/compiler/runtime/Runtime.cpp
ILGen:
- aconst_init: Load the default value instance if the class is initialized. This enhancement can be disabled
by setting env variable `TR_DisableLoadStaticDefaultValueInstance`.
SymRef:
- Create symbol reference for default value instance of value class.
AOT (X86):
- Add new relocation record `TR_RelocationRecordStaticDefaultValueInstance`
to materialize the default value instance slot address on AOT load.
**Depends on** 
=> Load default value instance if the class is initialized

runtime/jcl/common/thread.cpp
The VirtualThread natives are needed to keep a list of every live virtual
thread for JVM TI. Since JVM TI agents can be attached at any time, enable
these natives by default.
Issue: #15183
=> Enable VirtualThread natives by default

runtime/jvmti/jvmtiForceEarlyReturn.c, runtime/jvmti/jvmtiStackFrame.c, runtime/jvmti/jvmtiThread.c, runtime/jvmti/jvmtiTimers.c, runtime/oti/j9.h, runtime/oti/jvmtiInternal.h
If the thread is a virtual thread, `ForceEarlyReturn*` and `PopFrame` JVMTI
functions should return `JVMTI_ERROR_OPAQUE_FRAME`.
Also, fixed the `entry/exit` tracepoints for `ForceEarlyReturn*` JVMTI functions.
`isSameOrSuperClassOf` is unable to handle `NULL` from the `*_OR_NULL` version.
Instead, use `J9VMJAVALANGBASEVIRTUALTHREAD` in `IS_VIRTUAL_THREAD`.
Ref: https://download.java.net/java/early_access/jdk19/docs/specs/jvmti.html
=> Return JVMTI_ERROR_OPAQUE_FRAME from ForceEarlyReturn* and PopFrame

runtime/vm/jvminit.c
=> Disable AVX register preservation on x86

runtime/vm/jvminit.c
Cherry pick https://github.com/eclipse-openj9/openj9/pull/15722 for the 0.33.1 release.
=> (0.33.1) Disable AVX register preservation on x86

runtime/compiler/x/env/J9CPU.cpp
AOT code embedded in containers needs to be able to run on a wide array
of processors. For this reason, the portable AOT code is allowed to
use only a subset of processor features, subset defined by the
SandyBridge architecture. Since AVX512 instructions are not supported
by SandyBridge, the AVX512F feature should be removed from the portable
set of features.
Issue: https://github.com/eclipse-openj9/openj9/issues/15697
Cherry pick https://github.com/eclipse-openj9/openj9/pull/15699 for the 0.33.1 release.
=> (0.33.1) Remove AVX512F from the features supported by our portable CPU description

runtime/compiler/control/CompilationThread.cpp
Assert from Issue:#15481
This assert should be eliminated because it is unnecessary.
When a compilation fails with an error code, a redefinition may happen right away, marking the compilation entry as unloaded, even though the compilation has failed.
So it's totally possible to have the entry marked as unloaded and the error code be something else than compilationInterrupted.
It's quite normal to get into shouldAbortCompilation with a different error code, thus this assert is invalid and can be deleted.
Signed-off-by: Manasha Vetrivelu <manasha.vetrivelu@ibm.com>
=> Deleted an unnecessary assert

runtime/compiler/optimizer/J9OptimizationManager.cpp, runtime/compiler/optimizer/VectorAPIExpansion.cpp
- fix two node reference count issues
- run verifyTrees every time the optimization runs
=> Fix node reference counts in VectorAPIExpansion

runtime/j9vm/javanextvmi.c, runtime/redirector/forwarders.m4
They all expect three parameters (not just one); see [jvm.h](https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/openj9/src/hotspot/share/include/jvm.h#L1150-L1160).
=> Correct signature of JVM_VirtualThread functions

runtime/oti/j9dump.h, runtime/oti/jvminit.h, runtime/rasdump/dmpsup.c, runtime/rasdump/javadump.cpp
* `-XX:-ShowNativeStackSymbols` - don't show any
* `-XX:+ShowNativeStackSymbols=basic` - show only those easily acquired
* `-XX:+ShowNativeStackSymbols=all` - show all available
As usual, last option on command line takes precedence. Issue: #15712.
=> Add options to control resolution of native stack symbols in java dumps

runtime/compiler/optimizer/EscapeAnalysis.cpp
In escape analyis while generating constant child of VSPLATS node, it
queries the IL API to get the opcode using the Vector IL instead of
Vector Element type. This resulted in us hitting fatal assert. This
commit fixes by supplying the element type to getOpCode query for
constant node.
=> Fix EA bug in generating VSPLATS

runtime/compiler/control/CompilationThread.cpp
Local synchronous compilation followed by remote recompilation
(LocalSyncCompiles) should not be attempted when the relevant method
is a DLT compilation, or when MimicInterpreterFrameShape has been set.
=> Add more remote recompilation guards

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java, runtime/oti/VMHelpers.hpp, runtime/oti/j9nonbuilder.h, runtime/oti/vm_api.h, runtime/oti/vmconstantpool.xml, runtime/vm/BytecodeInterpreter.hpp, runtime/vm/ContinuationHelpers.cpp, runtime/vm/ContinuationHelpers.hpp, runtime/vm/bindnatv.cpp
- Cache jitGPR data in J9VMContinuation
- Wrap `Continuation.execute` call to force yield after completion
- Build Callin frame during first enterContinuation call
- added helper to copy Continuation data into J9VMThread structure
Closes: #15464 
=> Add Continuation direct transition support

runtime/compiler/env/J9ClassEnv.hpp, runtime/compiler/env/VMJ9.cpp
Also check for interfaces, which don't have a VFT at all.
=> Check VFT bounds in TR_J9VMBase::getVFTEntry()

runtime/compiler/env/CHTable.cpp
Extending the defining class of an inlined method does not invalidate the bodies of methods defined by that class, which remain unchanged until/unless the class is actually redefined.
It's possible for a guard merged with an HCR guard to require a class extend assumption for its (non-HCR) virtual guard semantics. In that case, execution will continue on and create the class extend assumption in exactly the same way as it would without the merged HCR guard.
=> Stop registering class extend assumptions for HCR guards

runtime/compiler/optimizer/OSRGuardInsertion.cpp
Previously, if an HCR guard was merged into another virtual guard, it could be removed without taking into account the class whose redefinition it guards against. If no other removed HCR guard was sensitive to redefinition of the same class, then no redefinition assumption would be made for that class. If that class were later redefined, the JIT would fail to patch OSR guards within the method.
Additionally, use `performTransformation()` to make the removal optional like it is in the non-merged case above.
=> Add class for OSR redefinition when removing a merged HCR guard

runtime/compiler/env/j9fieldsInfo.cpp
There is a case where the number of object slots are greater than the number of bits in a word and `instanceDescription` is used as an immediate value instead of a pointer, such as when the class doesn't have any references. We need to break the loop in this case before `instanceDescription` is dereferenced as a pointer.
This fixes `openj9-jit-xopt/issues/529`
Thanks to Henry @hzongaro for tracking down the issue to hasReferneces change https://github.com/eclipse-openj9/openj9/pull/10651
=> Check if instanceDescription is an immediate value in loop

runtime/compiler/optimizer/VectorAPIExpansion.cpp, runtime/compiler/optimizer/VectorAPIExpansion.hpp
While generating the vector opcodes for loading and storing in vector
api expansion, we need to check if the vector supports is available on
Z. This commit adds that check in to supportedOnPlatform query.
=> Check for vector support on Z in supportedForPlatform

test/functional/Java19andUp/build.xml
Run the test (and with --enable-preview) for all java versions, not just
java 19.
=> Fix virtual thread test setup for jdk 20

debugtools/DDR_VM/src/com/ibm/j9ddr/view/dtfj/image/J9DDRImageProcess.java
The interface documentation says it should return the OS-specific signal number, not some abstract, platform-independent value.
Update the mapping to signal names accordingly.
Fixes: #15731.
=> Correct implementation of J9DDRImageProcess.getSignalNumber()

runtime/jcl/common/jclcinit.c, runtime/jcl/common/thread.cpp, runtime/jvmti/jvmtiExtensionMechanism.c, runtime/jvmti/jvmtiForceEarlyReturn.c, runtime/jvmti/jvmtiHelpers.c, runtime/jvmti/jvmtiLocalVariable.c, runtime/jvmti/jvmtiStackFrame.c, runtime/jvmti/jvmtiThread.c, runtime/jvmti/jvmtiThreadGroup.c, runtime/jvmti/jvmtiTimers.c, runtime/jvmti/jvmti_internal.h, runtime/jvmti/suspendhelper.cpp, runtime/oti/j9nonbuilder.h, runtime/oti/jvmtiInternal.h, runtime/oti/vmconstantpool.xml, test/functional/Java19andUp/playlist.xml, test/functional/Java19andUp/src/org/openj9/test/jep425/VirtualThreadTests.java
- Return the corresponding J9VMThread for a virtual thread from
getVMThread.
- Prevent the virtual thread from (un)mounting using the inspectorCount
approach.
- The (un)mountBegin/(un)mountEnd natives lock the mount/unmount section
and prevent inspectors from inspecting during that time.
- For a virtual thread, even the underlying J9VMThread is prevented from
terminating using the inspectorCount approach.
- Moved code from notifyJvmtiUnmountEnd to notifyJvmtiUnmountBegin for blocking
before unmount. Also, VirtualThread.carrierThread is set to NULL in unmount.
So, removing the VirtualThread from the linked list before the last unmount
in notifyJvmtiUnmountBegin seems correct.
- Block mount after yield if a virtual thread is being inspected.
- In getVMThread:
- targetThread will be NULL for …
=> Block Virtual Threads for JVMTI Inspection

runtime/jvmti/jvmtiThread.c, runtime/oti/j9nonbuilder.h
For virtual threads,
- Name is obtained from the thread object
- Priority is always JVMTI_THREAD_NORM_PRIORITY
- isDaemon is always JNI_TRUE
- Threadgroup is always java/lang/Thread$Constants.VTHREAD_GROUP if alive
- Context class loader is obtained the same way as from a platform thread
Fixes: #15761
Issue: #15183
=> Update jvmtiGetThreadInfo for Loom

runtime/jcl/common/jclcinit.c, runtime/jcl/common/thread.cpp, runtime/jvmti/j9jvmti.tdf, runtime/jvmti/jvmtiEventManagement.c, runtime/jvmti/jvmtiHelpers.c, runtime/jvmti/jvmtiHook.c, runtime/jvmti/jvmtiThread.c, runtime/jvmti/jvmti_internal.h, runtime/oti/j9nonbuilder.h, runtime/oti/jvmtiInternal.h, runtime/oti/vm_api.h, runtime/vm/intfunc.c, runtime/vm/jvmfree.c, runtime/vm/jvminit.c, runtime/vm/threadhelp.cpp, runtime/vm/vmthinit.c
- Add an array hidden field to java/lang/Thread as the TLS for a given
thread object (JDK19+). JDK18 and below will continue to use the OMR TLS
- Implement JVMTI TLS functions to store env-thread-pair TLS data
- Add tls pool to vm to allocate threads' tls arrays from
- (JDK19+) Lazy allocate a thread's TLS array at first use
(SetThreadLocalStorage and SetEventNotificationMode)
- (JDK19+) Free the TLS array at VMThread destroy and virtual thread end
- Lazy allocate TLS thread data blocks at first use
(SetThreadLocalStorage and SetEventNotificationMode)
- Implement new hook events for platform and virtual thread end to free
the thread data block allocated by a JVMTI env
Issue: #15183
=> Add thread local storage to java thread objects

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp, runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Implement the inlined version of java/lang/Math.min and max.
=> AArch64: Inline Math.min and max

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp, runtime/compiler/codegen/J9TreeEvaluator.cpp, runtime/compiler/p/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp
The case of castClass being a runtime variable was only for `instanceOf` nodes until #15079 (transforms Class.cast calls to checkCast nodes), for this new case we can inline superClassTest to improve performance. This part of common code is used by Z, P and AARCH64. 
This PR allows `checkCast` nodes in the case of variable castClass to inline superClassTest. 
It also adds array and interface checks for castClass before the superClassTest, if so skip superClassTest, for P and AARCH64. It's already implemented in Z.
Description issue: #15535
- ~Finish/check AARCH64 code (using/not-using `tbz/tbnz`, immediate `immr:imms`)~
- ~P handle unknown classDepth for superClassTest~
- ~Testing and benchmark performance~
=> Inline superClassTest for transformed checkCast nodes when castClass is runtime variable

runtime/jcl/CMakeLists.txt, runtime/jcl/common/jdk_internal_foreign_abi_UpcallStubs.cpp, runtime/jcl/exports.cmake, runtime/jcl/uma/se16_exports.xml, runtime/jcl/uma/se16_objects.xml, runtime/oti/j9nonbuilder.h, runtime/oti/jclprots.h, runtime/oti/vm_api.h, runtime/vm/CMakeLists.txt, runtime/vm/LayoutFFITypeHelpers.hpp, runtime/vm/OutOfLineINL_openj9_internal_foreign_abi_InternalUpcallHandler.cpp, runtime/vm/UpcallThunkMem.cpp, runtime/vm/UpcallVMHelpers.cpp, runtime/vm/ap64/UpcallThunkGen.cpp, runtime/vm/intfunc.c, runtime/vm/j9vm.tdf, runtime/vm/jvminit.c, runtime/vm/module.xml, runtime/vm/vmthinit.c, runtime/vm/wa64/UpcallThunkGen.cpp, runtime/vm/xa64/UpcallThunkGen.cpp, runtime/vm/xl64/UpcallThunkGen.cpp, runtime/vm/xr64/UpcallThunkGen.cpp, runtime/vm/xz64/UpcallThunkGen.cpp
The changes mainly include the following code for thunk generation:
1) the thunk memory allocation & release
2) the encoding of the native signature intended for thunk
3) the thunk generation (created by JIT)
=> [Part 2&3] FFI Upcall: generating thunk with the encoded signature

runtime/jvmti/j9jvmti.tdf, runtime/jvmti/jvmtiStackFrame.c, runtime/oti/j9nonbuilder.h, runtime/oti/vmconstantpool.xml, runtime/vm/intfunc.c
Adds `walkContinuationStackFrames` to internal functions so jvmti code can use it.
Adds a check for whether it's a virtual thread and not yielded or terminated.
If it is, use `walkContinuationStackFrames` to walk the continuation object.
Issue: https://github.com/eclipse-openj9/openj9/issues/15183 https://github.com/eclipse-openj9/openj9/issues/15759
=> Virtual threads support for jvmtiGetFrameCount

runtime/gc_glue_java/configure_includes/configure_linux_ztpf_390.mk
This update should only affect z/TPF platforms builds.
As part of an exercise to run a z/TPF openJ9 cross-compiled build on a
different version of Linux a binutils error was encountered because
runtime/gc_glue_java/configure_includes/configure_linux_ztpf_390.mk
was referencing the default installed assembler from the binutils.
However, the native binutils isn't compatible with the binutils that was
used to build the z/TPF cross-compiler.
The fix was to redirect the default glue configuration to use tpf-as
from the cross-compiler binutils installation instead of the native 
assembler installed with the different version of the Linux binutils. 
[no ci]
=> zTPF: Update gc glue configure to use tpf-as

runtime/compiler/codegen/J9CodeGenerator.cpp
When this flag is set, VP has determined that type constraints guarantee that the receiver has a large enough VFT.
=> Skip method test bound check when guard node is flagged in-bounds

runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/J9Options.hpp
This PR adds the ability to sleep before a checkpoint to allow the
compilation threads to compile the methods already present in the
compilation queue. It is important that the hook thread releases both
VM Access and the Compilation Monitor before sleeping; otherwise, the
compilation threads will not be able to empty the queue.
=> Add ability to sleep before checkpoint

runtime/vm/vmprops.c
As per the jdk8 JSR 337 Maintenance Release 4 spec
https://jcp.org/aboutJava/communityprocess/maintenance/jsr337/jsr337-mr4-changes.html
See also OpenJDK 8285497
https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/df84c26757ec70ef67fd94d1cfacd77f1b4c302f
Also related https://github.com/eclipse-openj9/openj9/pull/15784
=> Add java.specification.maintenance.version=4 jdk8 system property

runtime/zlib/inflate.c
Applied
https://github.com/madler/zlib/commit/eff308af425
https://github.com/madler/zlib/commit/1eb7682f845
=> Update zlib to fix CVE-2022-37434

runtime/vm/xz64/UpcallThunkGen.cpp
=> Add thunk/adapter for FFI Upcall on Z

test/functional/cmdLineTests/criu/criu_keepCheckpoint.xml, test/functional/cmdLineTests/criu/playlist.xml
- Add CRIURestoreNonPortableMode test for criu_keepCheckpoint
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/15814 https://github.com/adoptium/aqa-tests/pull/3951
=> Add CRIURestoreNonPortableMode test for criu_keepCheckpoint

test/functional/DDR_Test/build.xml, test/functional/DDR_Test/src/j9vm/test/ddrext/Constants.java
`JDK19+` adopts OpenJDK `java.lang.Thread`, `!j9classshape` output contains `eetop` while the output from earlier Java levels are `threadRef`.
Verified at a local run.
closes https://github.com/eclipse-openj9/openj9/issues/15252
=> JDK19+ j9classshape outputs eetop instead of threadRef

runtime/compiler/control/DLLMain.cpp, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/J9Options.hpp, runtime/compiler/control/rossa.cpp
When specifying multiple JIT options, currently only the last
JIT option will be in effect. Added a standalone alternative for
-Xjit:perfTool in -XX:+PerfTool to avoid clobbering pre-existing
JIT command line options.
New Options
**-XX:+PerfTool** Enables Perf Tool
**-XX:-PerfTool** Disables Perf Tool
Fixes: #14157
Signed-off-by: Ravali Yatham <ravaliyatham@gmail.com>
=> Add standalone JIT option -XX:[+|-]PerfTool

runtime/compiler/control/DLLMain.cpp, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/J9Options.hpp, runtime/compiler/control/rossa.cpp
When specifying multiple JIT options, currently only the last JIT option will be in effect. Added a standalone alternative for -Xjit:perfTool in -XX:+PerfTool to avoid clobbering pre-existing JIT command line options.
New Options
-XX:+PerfTool Enables Perf Tool
-XX:-PerfTool Disables Perf Tool
Cherry pick #15823 for 0.35
=> (0.35) Add standalone JIT option -XX:[+|-]PerfTool

runtime/jvmti/jvmtiHelpers.c, runtime/jvmti/jvmtiStackFrame.c
Refactors vm->internalVMFunctions to vmFuncs
Adds a continuation object parameter to jvmtiInternalGetStackTrace.
If targetThread is not null, the targetThread will be used, otherwise
check if continuation object is not null and use that.
In jvmtiGetStackTrace, adds a check for virtual thread, call
jvmtiInternalGetStackTrace with the corresponding arguments depending
on whether the thread is virtual or not.
Adds an assertion to getVMThread to ensure that targetThread will be
NULL for a virtual thread so the extra call to IS_VIRTUAL_THREAD can be
avoided.
Updates jvmtiGetFrameCount and jvmtiGetFrameLocation to remove the
unnecessary IS_VIRTUAL_THREAD call.
Updates the coding style of surrounding code
Issues: https://github.com/eclipse-openj9/openj9/issues/15759 …
=> Update jvmtiGetStackTrace to support virtual thread

runtime/jvmti/jvmtiExtensionMechanism.c, runtime/jvmti/jvmtiThread.c
GetOSThreadID: Throw JVMTI_ERROR_UNSUPPORTED_OPERATION for virtual
threads since this function is OpenJ9 specific, and we can dictate its
implementation.
InterruptThread: If virtual thread is unmounted i.e. targetThread is
NULL, then skip the targetThread->osThread related operations.
Due to the new synchronization for addressing the timing gap, the
virtual thread is pinned regardless whether it is mounted or not.
Fixes: #15763
=> Handle virtual threads in JVMTI GetOSThreadID & InterruptThread

runtime/jvmti/jvmtiClass.c, runtime/jvmti/jvmtiStackFrame.c
- Define vmFuncs only within the scope of its usage.
- Initialize local variables.
- Fix formatting.
- Use Assert_JVMTI_unreachable instead of Assert_JVMTI_true.
Related: #15788, #15813
=> Fix issues in recent PRs

runtime/vm/jniinv.c, runtime/vm/jvminit.c
Add a z/TPF OS VM exit hook to handle z/TPF unique processing.
The z/TPF OS level hook keeps the existing OpenJ9 code neat
and readable by hiding any irrelevant z/TPF specific 
processing, such as z/TPF unique native metric collections.
=> zTPF: Add VM z/TPF OS exit hook

jcl/src/java.base/share/classes/java/security/AccessController.java, test/functional/Java8andUp/src/org/openj9/test/java/security/Test_AccessController.java
Fix `doPrivilegedWithCombiner(action)` `context` for `domainCombiner` access
Fixed `doPrivilegedWithCombiner(action)` with `AccessControlContext` created via `doPrivilegedWithCombinerHelper()`;
Fixed the `doPrivilegedWithCombiner` test to perform permission check according to the caller's protection domain, not the upper `doPrivileged AccessControlContext`.
closes https://github.com/eclipse-openj9/openj9/issues/14803
related to [internal workitem](https://jazz103.hursley.ibm.com:9443/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/147318)
Manually verified the test in question, and also run [internal personal build](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/14157/)
=> Fix doPrivilegedWithCombiner(action) context for domainCombiner access

runtime/codert_vm/thunkcrt.c
`Q` type needs to be processed as `L` type. When it is missing in `j9ThunkEncodeSignature`, it could cause stack overflow.
=> Process Q type in signature

runtime/jvmti/jvmtiHelpers.c, runtime/jvmti/jvmtiStackFrame.c, runtime/jvmti/jvmti_internal.h, runtime/oti/VMHelpers.hpp, runtime/oti/j9nonbuilder.h, runtime/oti/vm_api.h, runtime/vm/ContinuationHelpers.cpp
In some cases the J9VMContinuation cannot be accessed through a j9object so we change the parameter of walkContinuationStackFrames to accept a J9VMContinuation pointer directly.
Adds declaration of J9VMContinuation to the top.
In the old implementation, if a carrier thread has a virtual thread mounted after getVMThread being called, the virtual thread will be walked. We fix this by adding a check for currentContinuation of the carrier thread. If the currentContinuation is not null, the info of the carrier thread has been swapped to the currentContinuation, so the
currentContinuation will be walked instead.
To facilitate other stackwalk-related functions, a generic stackwalk helper is added to walk a platform thread or a virtual thread. A virtual can be mounted or unmounted, if it's …
=> Fix stackwalk related jvmti functions

debugtools/DDR_VM/data/superset-constants.dat
Document how additions and removals of constants should be handled.
See also https://github.com/eclipse-openj9/openj9/pull/15611/files#r970106417.
=> Remove unwanted addition to superset-constants.dat

runtime/j9vm/j9vmnatives.xml, runtime/j9vm/module.xml, runtime/jcl/uma/java_lang_invoke_MethodHandleNatives_exports.xml, runtime/jcl/uma/se19_exports.xml
Fix compile error due to new `#include "VMHelpers.hpp"` in jcl code.
Remove obsolete exports that cause link errors:
```
JVM_GetModuleByPackageName
Java_java_lang_invoke_MethodHandleNatives_getConstant
Java_java_lang_VirtualThread_notifyJvmtiMountBegin
Java_java_lang_VirtualThread_notifyJvmtiMountEnd
Java_java_lang_VirtualThread_notifyJvmtiUnmountBegin
Java_java_lang_VirtualThread_notifyJvmtiUnmountEnd
Java_java_lang_VirtualThread_registerNatives
Java_jdk_internal_vm_Continuation_isPinnedImpl
```
=> Fix UMA build errors

jcl/src/java.base/share/classes/java/lang/Class.java
Method needed for compatibility reasons.
Method signature was changed in https://github.com/eclipse-openj9/openj9/pull/14063.
Resolves https://github.com/eclipse-openj9/openj9/issues/15884
=> Readd getConstantPool() method to Class.java

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/JITServerCompilationThread.cpp, runtime/compiler/env/J9SharedCache.cpp, runtime/compiler/runtime/JITClientSession.cpp, runtime/compiler/runtime/JITClientSession.hpp, runtime/compiler/runtime/JITServerAOTCache.cpp, runtime/compiler/runtime/JITServerAOTCache.hpp
The record creation methods of the JITServer AOT cache now check that
total record allocations do not exceed a configurable maximum before
creating new records. This should be correlated with the total
JITServer AOT cache memory usage, and so provide a bound on that value.
Fixes: https://github.com/eclipse-openj9/openj9/issues/15480
=> Limit JITServer AOT cache memory usage

jcl/src/java.base/share/classes/java/lang/Class.java
Method needed for compatibility reasons.
Port of https://github.com/eclipse-openj9/openj9/pull/15891
fyi @pshipton
=> (v0.35.0) Readd getConstantPool() method to Class.java

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java, runtime/j9vm/javanextvmi.cpp, runtime/oti/VMHelpers.hpp, runtime/oti/j9nonbuilder.h, runtime/oti/vm_api.h, runtime/vm/BytecodeInterpreter.hpp, runtime/vm/ContinuationHelpers.cpp, runtime/vm/bindnatv.cpp, runtime/vm/intfunc.c
=> Add Continuation cleanup API

runtime/compiler/optimizer/IdiomRecognition.cpp
In examining an array index for Idiom Recognition, `analyzeOneArrayIndex` checks whether the variable operand in a 'var + const' or 'const + var' expression is an induction variable.  On the other hand, if the expression is a simple variable, the analysis assumes the variable reference is acceptable.  However, it can happen that the variable used as the array index is not an induction variable which can result in an incorrect transformation.
Fixed this by adding a check that an array index that is a variable is also an induction variable.
Fixes #15474
=> Check whether array index variable is an induction variable

runtime/compiler/control/HookedByTheJit.cpp
The TR_X86ProcessorInfo struct is used in a bunch of asserts as sanity 
tests to ensure consistency with the Port Library. In a restore run, in 
non portable mode, the processor description acquired from the port 
library can change; therefore, the TR_X86ProcessorInfo struct also needs 
to be reinitialized.
Depends on https://github.com/eclipse/omr/pull/6695
Fixes https://github.com/eclipse-openj9/openj9/issues/15814
=> Reinitialize target process info on restore in nonportable mode

runtime/compiler/optimizer/IdiomRecognition.cpp
In examining an array index for Idiom Recognition, analyzeOneArrayIndex checks whether the variable operand in a 'var + const' or 'const + var' expression is an induction variable.  On the other hand, if the expression is a simple variable, the analysis assumes the variable reference is acceptable.  However, it can happen that the variable used as the array index is not an induction variable which can result in an incorrect transformation.
Fixed this by adding a check that an arrayindex that is a variable is also an induction variable.
Merges pull request #15870 to v0.35.0-release
Fixes #15474
FYI @pshipton
=> (0.35) Check whether array index variable is an induction variable

debugtools/DDR_VM/src/com/ibm/j9ddr/tools/ddrinteractive/Context.java
Fixes #15889
```
Problem running command:
java.nio.BufferOverflowException
at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:194)
at java.nio.ByteBuffer.put(ByteBuffer.java:867)
at com.ibm.j9ddr.tools.ddrinteractive.commands.TraceFileHeaderWriter.writeStartupSection(TraceFileHeaderWriter.java:331)
at com.ibm.j9ddr.tools.ddrinteractive.commands.TraceFileHeaderWriter.writeTraceFileHeader(TraceFileHeaderWriter.java:203)
at com.ibm.j9ddr.tools.ddrinteractive.commands.TraceFileHeaderWriter.createAndWriteTraceFileHeader(TraceFileHeaderWriter.java:164)
at com.ibm.j9ddr.tools.ddrinteractive.commands.SnapBaseCommand.createAndWriteTraceFileHeader(SnapBaseCommand.java:177)
at com.ibm.j9ddr.tools.ddrinteractive.commands.SnapBaseCommand.extractTraceData(SnapBaseCommand.java:88)
at …
```
=> Print full exception details if a jdmpview !-command throws an exception

runtime/vm/UpcallVMHelpers.cpp
The changes fix the cast issue with the values returned from native2InterpJavaUpcallImpl().
=> Fix the cast issue with return values in dispatcher for FFI upcall

buildenv/docker/mkdocker.sh
Update CRIU version from 3.16 to 3.17.
=> Update CRIU to v3.17 for OpenJ9 Ubuntu dockerfile

jcl/src/openj9.dataaccess/share/classes/com/ibm/dataaccess/DecimalData.java, jcl/src/openj9.dataaccess/share/classes/com/ibm/dataaccess/PackedDecimal.java
The new warning was added in https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/e90c809e0e89115a0ce8c03ff874c428058d560e.
=> Fix warnings in jdknext classified as "lossy-conversions"

test/functional/DDR_Test/src/j9vm/test/ddrext/Constants.java, test/functional/DDR_Test/src/j9vm/test/ddrext/junit/TestDDRExtensionGeneral.java, test/functional/DDR_Test/src/j9vm/test/ddrext/junit/TestFindExt.java, test/functional/DDR_Test/src/j9vm/test/ddrext/util/parser/MethodForNameOutputParser.java
Look for java/lang/Thread.sleep method with only one argument since the form with 2 arguments doesn't show up on the stack in jdk19.
Also change MethodForNameOutputParser.extractMethodAddress so we can choose the method instead of taking first matching.
Resolves https://github.com/eclipse-openj9/openj9/issues/15850
Tests done against `testDDRExtJunit_FindExtThread` in internal Jenkins server:
19: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/27697/
17: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/27708/
11: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/27711/
8: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/27712/
=> Change method to look for in testFindstackvalue

runtime/vm/CMakeLists.txt, runtime/vm/mz64/UpcallThunkGen.cpp
Add empty stub function implementations for upcall thunk generation support to allow OpenJ9 to build on z/OS with spec version >= 16.
Actual implementation of the upcall thunks to be implemented in the future.
=> Add zOS UpcallThunkGen function stubs

runtime/compiler/control/CompilationThread.cpp
This commit adds a call to pthread_jit_write_protect_np(1) at the end of TR::CompilationInfoPerThreadBase::compile() so that the JIT compilation thread always re-acquires the execution permission for JIT code cache.
Fixes: #14621
Fixes: #14635
Fixes: #14717
Fixes: #15315
Fixes: #15352
Fixes: #15518
Fixes: #15868
=> AArch64 macOS: Re-acquire execution permission in compilation threads

runtime/gc_vlhgc/IncrementalGenerationalGC.cpp, runtime/gc_vlhgc/SchedulingDelegate.cpp, runtime/gc_vlhgc/SchedulingDelegate.hpp
Add a missing capability to resize Eden at STW Global GC points.
=> Rebalance Eden after Global GC

runtime/gc/gctable.c, runtime/gc_base/gc_internal.h, runtime/gc_base/modronapi.cpp, runtime/gc_base/modronapi.hpp, runtime/oti/j9nonbuilder.h, runtime/oti/vmconstantpool.xml, runtime/vm/BytecodeInterpreter.hpp
For generational GC, local GC would not scan tenured Object, which dose
not contain any nursery reference, so if the continuation Object has
been tenured, next local GC might miss to scan it.
For GenCon and balanced GC, we need general post writebarrier to handle
the case. the barrier will be triggered after yieldContinuation.
this change does not cover concurrent Scavenger and metronome, which is
required read barrier.
=> Continuation Scan Update for generational GC or concurrent GC

runtime/compiler/control/CompilationThread.cpp
This commit adds a call to pthread_jit_write_protect_np(1) at the end of TR::CompilationInfoPerThreadBase::compile() so that the JIT compilation thread always re-acquires the execution permission for JIT code cache.
Original PR in master: #15907
=> (0.35.0) AArch64 macOS: Re-acquire execution permission in compilation threads

runtime/compiler/runtime/SignalHandler.c
This commit fixes indentation of jitARM64Handler() in SignalHandler.c. Tab and whitespace characters are mixed.
=> Fix indentation in JIT SignalHandler.c

jcl/src/java.base/share/classes/jdk/internal/foreign/abi/DowncallLinker.java, jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java, jcl/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ProgrammableInvoker.java
The changes aim to resolve the issues specific to session/scope
detected in jtreg tests to ensure the session/scopes are kept
alive for the owner thread in the native invocation in the
multithreading environment.
=> The session/scope fixes on the downcall handler in multithreading

jcl/src/java.base/share/classes/java/lang/StackWalker.java, jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java, runtime/jcl/common/java_lang_StackWalker.cpp, runtime/jcl/common/jclglob.h, runtime/jcl/common/thread.cpp, runtime/jcl/exports.cmake, runtime/jcl/uma/se19_exports.xml, runtime/oti/vm_api.h, test/functional/Java19andUp/src/org/openj9/test/jep425/VirtualThreadTests.java
- Add copyFieldsFromContinuation helper in VMHelpers.hpp
- Add locking mechanism on Continuation execution
- Fix Thread.getStackTraceImpl to support VirtualThread
Closes: #15758
=> Add support for VirtualThread getStackTrace

runtime/jvmti/jvmtiHelpers.c, runtime/jvmti/jvmtiThread.c, runtime/jvmti/jvmti_internal.h
Support for virtual threads added in the following JVMTI functions:
- GetOwnedMonitorInfo
- GetOwnedMonitorStackDepthInfo
- GetCurrentContendedMonitor
Related changes: #15857
GetThreadState and GetThreadInfo allow a NULL input thread. In such
a case, they should look at the current thread's object. Because using
the NULL input thread causes a seg fault. This has been fixed.
Related issue: #15759
Co-authored-by: Gengchen Tuo <gengchen.tuo@ibm.com>
Co-authored-by: Jack Lu <Jack.S.Lu@ibm.com>
=> Loom: Update JVMTI monitor functions

runtime/gc_vlhgc/IncrementalGenerationalGC.cpp, runtime/gc_vlhgc/SchedulingDelegate.cpp, runtime/gc_vlhgc/SchedulingDelegate.hpp
Reverts eclipse-openj9/openj9#14740
Seems to cause intermittent OOMs, as reported by https://github.com/eclipse-openj9/openj9/issues/15943
=> Revert "Rebalance Eden after Global GC"

runtime/jvmti/jvmtiLocalVariable.c, runtime/jvmti/jvmtiStackFrame.c
Adds virtual thread support for GetOrSetLocal and NotifyFramePop
As walkState->walkThread will be used by some jit functions after
stackwalk, we can't use walkContinuationStackFrames which will cause
dangling pointer. Instead we need to stack-allocate manually if a
J9VMContinuation needs to be walked, so we created a helper
getJ9VMContinuationToWalk to get the J9VMContinuation.
Also fix coding style of surrounding code
Issues: https://github.com/eclipse-openj9/openj9/issues/15759 https://github.com/eclipse-openj9/openj9/issues/15183
Co-authored-by: Babneet Singh <sbabneet@ca.ibm.com>
=> Update jvmtiGetOrSetLocal and jvmtiNotifyFramePop to support virtual threads

jcl/src/java.base/share/classes/java/lang/Access.java, jcl/src/java.base/share/classes/java/lang/Class.java, jcl/src/java.base/share/classes/java/lang/invoke/MethodTypeHelper.java, test/functional/Valhalla/build.xml, test/functional/Valhalla/playlist.xml, test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java
1. The following 5 methods become non-public in Class.java
isPrimitiveClass()
asPrimaryType()
asValueType()
isPrimaryType()
isPrimitiveValueType()
The public version of these 5 methods are added in Access.java
2. Add stub method Class.accessFlags()
Closes https://github.com/eclipse-openj9/openj9/issues/15929
=> Move value type public APIs in Class.java into Access.java

debugtools/DDR_VM/src/com/ibm/j9ddr/tools/PointerGenerator.java
Remove incorrect, duplicate description for "-c" option.
=> Correct help message for PointerGenerator

runtime/jcl/common/system.c, runtime/jcl/unix/syshelp.c, runtime/oti/j9port_generated.h, runtime/port/common/j9prt.tdf, runtime/port/sysvipc/j9sharedhelper.c, runtime/port/sysvipc/j9shmem.c, runtime/vm/CRIUHelpers.cpp, runtime/vm/jvminit.c
CRIU skips `j9sysinfo_get_username()`/`getpwuid()` to avoid checkpoint failure
When `SSSD` is enabled, `j9sysinfo_get_username()`/`getpwuid()` can cause checkpoint failure, these methods will be skipped if a checkpoint can be taken, `j9sysinfo_get_env()` is used instead;
Added `J9PortLibrary.isSafeSSSDMethod` which is equivalent to `!isCheckpointAllowed()`;
Removed obsoleted defines `ARM_EMULATED`, `CHORUS` & `J9PWENT`; 
Refactoring variable initialization, code format around code affected.
[Internal personal build](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/14268/)
Verified manually OpenLiberty checkpoint at `RHEL8` w/ `SSSD` enabled.
=> CRIU skips j9sysinfo_get_username/getpwuid to avoid checkpoint failure

runtime/compiler/control/J9Options.cpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/x/amd64/codegen/AMD64JNILinkage.cpp, runtime/compiler/x/codegen/J9TreeEvaluator.cpp, runtime/compiler/x/codegen/J9TreeEvaluator.hpp, runtime/compiler/x/runtime/X86LockReservation.nasm, runtime/jilgen/jilconsts.c
* Misc. JIT infrastructural changes to support Loom
* x64 inc/dec of `ownedMonitorCount` J9VMThread field on monitor enter/exit
* x64 inc/dec of `callOutCount` J9VMThread field for JNI dispatch
Issue: #15175
=> x64 JIT support for virtual threads (Loom)

runtime/compiler/env/J9VMEnv.cpp, runtime/compiler/env/J9VMEnv.hpp
To make `isVMInStartupPhase()` callable in OMR, it will need to be declared in `OMR::VMEnv` in such a way that `J9::VMEnv` overrides it. However, that new declaration and any use sites in OMR will not be able to use the current signature, which requires `J9JITConfig*`.
=> Add isVMInStartupPhase() overload taking compilation object

runtime/j9vm/javanextvmi.cpp
Enforce synchronization: Avoid mounting a virtual thread while unmounting.
Related: #15938 
=> Fix virtualThreadInspectorCount check

runtime/j9vm/exports.cmake, runtime/j9vm/j7vmi.c, runtime/j9vm/j9vmnatives.xml, runtime/jcl/common/thread.cpp, runtime/jcl/exports.cmake, runtime/jcl/uma/se6_vm-side_natives_exports.xml, runtime/oti/jclprots.h, runtime/oti/vmconstantpool.xml, runtime/redirector/forwarders.m4, runtime/vm/vmthread.cpp
Remove `j.l.Thread.stopImpl()`, and `Thread.stopCalled` for Java 20+.
Depends https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/497
=> JDK20 deprecates java.lang.Thread.stop()

jcl/src/java.base/share/classes/java/lang/ref/PhantomReference.java, jcl/src/java.base/share/classes/java/lang/ref/Reference.java, jcl/src/java.base/share/classes/java/lang/ref/SoftReference.java, jcl/src/java.base/share/classes/java/lang/ref/WeakReference.java
Added `sealed` and `permits PhantomReference, SoftReference, WeakReference, FinalReference`.
Updated `PhantomReference`, `SoftReference`, and `WeakReference` accordingly.
Fix [internal workitem](https://jazz103.hursley.ibm.com:9443/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/147612)
=> Fix JDK19 java.lang.ref.Reference signature

jcl/src/java.base/share/classes/java/lang/StringBuffer.java, jcl/src/java.base/share/classes/java/lang/StringBuilder.java, test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_StringBuffer.java, test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_StringBuilder.java
For StringBuilder and StringBuffer
Add tests for deleteCharAt with out of bound indices.
Fixes https://github.com/eclipse-openj9/openj9/issues/15897
Tested internally [here](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/28143/) running JCL_Test_SE80
=> Add missing bounds check to deleteCharAt

runtime/jvmti/jvmtiHelpers.c
targetThread is NULL only for virtual threads, as per the assertion in
getVMThread, when mustBeAlive is TRUE. vmThreadForTLS is only
used to acquire J9JavaVM in createThreadData and jvmtiTLSGet.
If targetThread is NULL, currentThread is passed to createThreadData
and jvmtiTLSGet for retrieving J9JavaVM in JDK19+.
Related: #15541
Related: #15183
=> Fix setEventNotificationMode for unmounted virtual threads

runtime/jvmti/jvmtiHelpers.c
A mounted virtual thread is associated to a valid J9VMThread.
For virtual threads, targetThread is non-null for PARKING and YIELDING
states. getVirtualThreadState has been updated to use carrier thread's
state whenever targetThread is non-null for a virtual thread. This
correctly returns the JVMTI_THREAD_STATE_SUSPENDED flag for virtual
threads.
Related: #15762
=> Update getVirtualThreadState to handle all mounted scenarios

runtime/gc_base/RootScanner.cpp, runtime/gc_glue_java/ConcurrentMarkingDelegate.cpp, runtime/gc_structs/VMThreadStackSlotIterator.cpp, runtime/gc_structs/VMThreadStackSlotIterator.hpp
Threads should be scanned as they normally would. If a thread is mounted
with a VirtualThread, then the virtual thread stack will be scanned, the
carrier thread stack will be stored in a continuation instance.
currentContinuation field of the J9vmThread point to either NULL or the
continuation with carrier thread stack(mounting with a VirtualThread
case). scanning currentContinuation if needed.
#depends: https://github.com/eclipse-openj9/openj9/pull/15603
#fix: https://github.com/eclipse-openj9/openj9/issues/15179
=> Loom: GC Thread scanning

doc/GuideForCommitters.md
=> Include JDK17 in OMR coordinated merge documentation

runtime/j9vm/exports.cmake, runtime/j9vm/j7vmi.c, runtime/j9vm/j9vmnatives.xml, runtime/jcl/common/thread.cpp, runtime/jcl/exports.cmake, runtime/jcl/uma/se6_vm-side_natives_exports.xml, runtime/oti/jclprots.h, runtime/redirector/forwarders.m4
Removed `j.l.Thread.suspendImpl()`, `resumeImpl()`, `JVM_ResumeThread()`, and `JVM_SuspendThread()` for `JDK20+`.
Depends https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/499
=> JDK20 deprecates java.lang.Thread.suspend() & resume()

runtime/jvmti/jvmtiThread.c
Return JVMTI_ERROR_INVALID_THREAD if the input thread parameter is not
a thread object.
Fixes: #15987
=> Fix jvmtiGetThreadState

runtime/include/jni.h.m4, runtime/j9vm/j7vmi.c, runtime/j9vm/jvm.c, runtime/redirector/redirector.c, runtime/vm/jniinv.c, runtime/vm/jnimisc.cpp, runtime/vm/jvminitcommon.c
`JNI_VERSION_20` was added in https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/5c4d9ed098d8a7d8faf6f2e2d60f2808367a5043.
=> Support JNI_VERSION_20 for jdk20+

runtime/codert_vm/xnathelp.m4, runtime/jilgen/jilconsts.c, runtime/oti/j9nonbuilder.h, runtime/oti/xhelpers.m4
This reverts PR #14632. A 10%+ performance
regression (issue #15716) reported on JDK 8
was isolated to #14632. Reverting this PR
should not have any function change, it
was only intended to support the Vector
API JEPs which have not yet been enabled
on x86 in OpenJ9. A previous attempt at
disabling just the extended vector register
preservation did not recoup the performance,
but only completely reverting this PR
restored the regression. This suggests
there is something with the way the helpers
have been restructured that is causing the
performance degradation. This PR will be
reverted while the cause is investigated.
=> Revert "Preserve ymm/zmm registers on x"

runtime/codert_vm/xnathelp.m4, runtime/jilgen/jilconsts.c, runtime/oti/j9nonbuilder.h, runtime/oti/xhelpers.m4
Port of #15999
This reverts PR #14632. A 10%+ performance
regression (issue #15716) reported on JDK 8
was isolated to #14632. Reverting this PR
should not have any function change, it
was only intended to support the Vector
API JEPs which have not yet been enabled
on x86 in OpenJ9. A previous attempt at
disabling just the extended vector register
preservation did not recoup the performance,
but only completely reverting this PR
restored the regression. This suggests
there is something with the way the helpers
have been restructured that is causing the
performance degradation. This PR will be
reverted while the cause is investigated.
=> (0.35.0) Revert "Preserve ymm/zmm registers on x"

runtime/bcutil/ROMClassBuilder.cpp, runtime/bcutil/defineclass.c, runtime/j9vm/javanextvmi.cpp, runtime/oti/j9nonbuilder.h
Simplify code by reducing use of the pattern `(versionShifted >> BCT_MajorClassFileVersionMaskShift)`.
=> Add BCT_JavaMajorVersionUnshifted()

CODE_OF_CONDUCT.md
Eclipse recommends to have this file as per the yearly release review.
https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/106
Copied the file from
https://github.com/eclipse/.github/blob/master/CODE_OF_CONDUCT.md
=> Add Eclipse suggested CODE_OF_CONDUCT.md

runtime/compiler/optimizer/LiveVariablesForGC.cpp
=> Prepare to use perform() API for TR_Liveness analysis

runtime/compiler/env/CHTable.cpp, runtime/compiler/env/CHTable.hpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/optimizer/OSRGuardInsertion.cpp, runtime/compiler/optimizer/OSRGuardRemoval.cpp
These are a few adjustments to remain compatible with OMR after the corresponding OMR commit.
=> Stop sharing TR_VirtualGuard between multiple guards with the same BCI

runtime/gc_api/GuaranteedNurseryRange.cpp, runtime/gc_base/GenerationalAccessBarrierComponent.cpp, runtime/gc_modron_standard/StandardAccessBarrier.cpp, runtime/gcchk/gcchk.cpp
getGuaranteedNurseryRange() in GCExtensionsBase is defind always no. There is no need to check J9VM_GC_GENERATIONAL (and technically this is wrong flag any way, OMR_GC_MODRON_SCAVENGER should be checked instead). This function is going to set output parameters to NULL if OMR_GC_MODRON_SCAVENGER is not defined
#depends https://github.com/eclipse/omr/pull/6715
=> Fix caller of getGuaranteedNurseryRange() and use new functions

runtime/compiler/z/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/S390PrivateLinkage.cpp
This commit adds necessary changes on Z needed to support Virtual
Threads.
1. Increment and decrement ownedMonitorCount in J9VMThread when JIT
compiled code on Z acquires and releases lock respectively.
2. Increment and decrement callOutCount in J9VMThread around JNI call
dispatch.
=> Z JIT Pinning Support

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java, test/functional/Java19andUp/src/org/openj9/test/jep425/VirtualThreadTests.java
Continuation class implementation expects IllegalStateException when
yielding a pinned Continuation. But VirtualThread class overrides
this behaviour and only returns false without throwing the exception
when yield fails.
- Allow the overriden onPinned method to perform non-throw behaviour
when the Continuation is pinned during yield.
- Update VirtualThread tests on new behaviour.
Rework of #15996 
=> Update Continuation.yield to use onPinned API

runtime/j9vm/javanextvmi.cpp, runtime/jcl/common/thread.cpp, runtime/jvmti/jvmtiExtensionMechanism.c, runtime/jvmti/jvmtiForceEarlyReturn.c, runtime/jvmti/jvmtiHelpers.c, runtime/jvmti/jvmtiLocalVariable.c, runtime/jvmti/jvmtiStackFrame.c, runtime/jvmti/jvmtiThread.c, runtime/jvmti/jvmtiThreadGroup.c, runtime/jvmti/jvmtiTimers.c, runtime/jvmti/jvmti_internal.h, runtime/jvmti/suspendhelper.cpp, runtime/oti/j9.h, runtime/oti/jvmtiInternal.h, runtime/vm/jnicsup.cpp
- Return JVMTI_ERROR_INVALID_THREAD if the input thread parameter is
not a thread object.
- Consolidate j.l.Thread and j.l.VirtualThread error-checking within
getVMThread. This avoids repeated NULL checking and potentially
fetching the current thread.
- Convert getVMThread's boolean input parameters to a bit field.
- More verbose naming used to avoid ambiguity: IS_JAVA_LANG_THREAD
and IS_JAVA_LANG_VIRTUALTHREAD.
Fixes: #15986
=> Fix JVMTI methods

runtime/vm/ContinuationHelpers.cpp
Add fence on yield to preserve HB for lock reservation
=> Add fence on yield to preserve HB for lock reservation

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
`X86Evaluator.hpp` is removed in eclipse/omr#6718
=> Remove include X86Evaluator.hpp

runtime/criusupport/criusupport.cpp
Perform checkpoint/restore GC instead of idle gc pre checkpoint
=> Perform checkpoint/restore GC instead of idle gc pre checkpoint

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp, runtime/compiler/runtime/RelocationRecord.cpp
TR_InlinedStaticMethod, TR_InlinedSpecialMethod, and TR_InlinedAbstractMethod were missed in the debug code that dumps out the relocation data. As the code stands, if the compiler generates these relocations, it will assert when trying to dump.
=> Add missing relos in dumpRelocationHeaderData

runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/J9Options.cpp
In order to avoid out-of-memory scenarios, the JIT reads the amount of
available physical memory before each compilation. To control the overhead
of the memory availability call, there is a caching mechanism that makes sure
that two such calls cannot be closer than 500ms.
When a compilation consumes most of the available memory for the JVM, it may fail,
and this is completely normal. However, many of the subsequent compilations
can also fail, thinking that there is very little memory available. In reality,
the memory expensive compilation that failed already released all its memory to the
OS, and the JIT is getting stale memory availability information from the caching
mechanism.
This PR implements two changes:
1. Bypass the caching mechanism and do a proper memory readout, if the JIT is …
=> Avoid compilation failures due to imprecision in memory availability readout

doc/compiler/README.md
Update TOC to include the doc on IL Opcodes
=> Doc: Update TOC to include the doc on IL Opcodes

jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/javacore/builder/javacore/JavaRuntimeBuilder.java
For DTFJ javacore,  the blocking object was incorrectly marked as the thread object.
Signed-off-by: Andrew Johnson andrew_johnson@uk.ibm.com
=> Fix blocking object to be the correct object

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
- Fix message for the !trylockAccess if block.
- Release lock access once Continuation's run phase is complete.
=> Release access once Continuation has completed its run phase

runtime/compiler/control/JITServerCompilationThread.cpp
Data structures of type TR_MethodToBeCompiled are allocated to hold compilation requests generated by the listener thread of JITServer. Compilation requests are queued by the listener thread and dequeued by compilation threads that work on them. As long as the connection between the client and server is maintained, the same TR_MethodToBeCompiled is reused by queuing back the compilation request. When the client-server connection is severed (maybe because the compilation queue at the client has become empty) the TR_MethodToBeCompiled structure should be placed into a pool, to be reused later. Currently, this is not happening for JITServer and such data structures are leaked.
This PR fixes the problem mentioned above by calling recycleCompilationEntry() at the appropriate places. …
=> Fix small memory leak at JITServer

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/runtime/RelocationRecord.cpp, runtime/compiler/runtime/RelocationRecord.hpp, runtime/compiler/runtime/RelocationRuntime.cpp, runtime/compiler/runtime/RelocationRuntime.hpp, runtime/compiler/runtime/SymbolValidationManager.cpp, runtime/compiler/runtime/SymbolValidationManager.hpp
This PR adds a new validation record for `isClassVisible`, checking to see if the answer returned by `isClassVisible` for a given set of inputs is the same in an AOT load run as it was during the AOT compile run. This PR will eventually complete the following tasks:
Closes: #4765
Signed-off-by: Dylan Tuttle <jdylantuttle@gmail.com>
=> Add validation record for isClassVisible

runtime/j9vm/javanextvmi.cpp, runtime/jcl/common/jclcinit.c, runtime/jcl/common/thread.cpp, runtime/jvmti/j9jvmti.tdf, runtime/jvmti/jvmtiHelpers.c, runtime/jvmti/jvmtiThread.c, runtime/jvmti/suspendhelper.cpp, runtime/oti/j9nonbuilder.h
This PR impacts the following JVMTI functions:
- [Resume|Suspend]Thread
- [Resume|Suspend]ThreadList
- [Resume|Suspend]AllVirtualThreads
The above functions have been either implemented or updated as per the
JVMTI doc:
https://download.java.net/java/early_access/jdk19/docs/specs/jvmti.html
Other changes:
- Added boolean inspectingLiveVirtualThreadList to synchronize between
[Resume|Suspend]AllVirtualThreads, JVM_VirtualThreadMountBegin-End and
JVM_VirtualThreadUnmountBegin-End.
- If a thread is suspended while waiting on the monitor, then the
monitor is released after waking up and before invoking
internalEnterVMFromJNI, where the thread will be halted until resumed.
After resuming, the monitor is acquired again. This helps avoid
deadlocks.
- Added hidden field isSuspendedByJVMTI in …
=> Support virtual threads in JVMTI Resume* and Suspend* functions

runtime/nls/dump/j9dmp.nls, runtime/rasdump/trigger.c
When Xdump:stack is used to dump stack trace filtered on an exception, this change along with the primary exception message, displays additional detail about the exception if any. This is similar to how javacore displays additional detail about an exception in 1TISIGINFO tag.
Fixes: #8435
Signed-off-by: Kabir Islam <kaislam1@in.ibm.com>
=> Add Exception message to Xdump stack agent output

runtime/gc_glue_java/ScavengerRootClearer.cpp, runtime/gc_vlhgc/CopyForwardScheme.cpp
Retrieve next continuation Link from old Object instead of forwarded Object in case old Object is dead.
fix: https://github.com/eclipse-openj9/openj9/pull/16069#issuecomment-1271956260
=> Fix Continuation collection issue

jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/corereaders/NewElfDump.java
We want `jpackcore` to include a loaded ELF file, even if no SONAME makes reference to it.
Fixes: #16079.
=> Include all ELF objects listed in FILE notes

runtime/j9vm/jvm.c
This commit fixes the captureCommandLine() code for macOS.
=> macOS: Fix captureCommandLine()

jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/javacore/parser/j9/section/thread/IThreadTypes.java, jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/javacore/parser/j9/section/thread/ThreadSectionParser.java, jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/javacore/parser/j9/section/thread/ThreadTagParser.java
Add additional tags
Parse context classloader information
Helps fix #16043 
Signed-off-by: Andrew Johnson <andrew_johnson@uk.ibm.com>
=> Fix parsing of Javacore stack traces

runtime/jcl/CMakeLists.txt
Fix warnings when using cmake 3.20 or newer.
See https://cmake.org/cmake/help/latest/policy/CMP0115.html.
=> cmake: source file extensions must be explicit

runtime/bcutil/cfreader.c, test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeGenerator.java
1. Valhalla is built on JDKNext which is Java 20 now. Update the code to check against Java 20.
2. Update the test code to generate Java 20 classes.
=> Update JDK version for Valhalla

runtime/oti/j9nonbuilder.h, runtime/vm/ContinuationHelpers.cpp, runtime/vm/ContinuationHelpers.hpp, test/functional/Java19andUp/playlist.xml
- Enable JIT in VirtualThread tests
- Disable testing on PPC due to known test failure
- PPC testing will be re-enabled with https://github.com/eclipse-openj9/openj9/pull/16014
=> Cache J9I2JState in J9VMContinuation during transition

runtime/vm/ContinuationHelpers.cpp, runtime/vm/ContinuationHelpers.hpp, test/functional/Java19andUp/playlist.xml
=> Init jitTOC on ppc64

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/DeadlockTest.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/TestDelayedOperations.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeCheckpointException.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeRestoreException.java
Rename registerPreSnapshotHook to registerPreCheckpointHook
=> Rename registerPreSnapshotHook to registerPreCheckpointHook

jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/corereaders/NewElfDump.java
Fixes: #16079.
Using the example in https://github.com/eclipse-openj9/openj9/issues/16079#issuecomment-1279202325, this latest change will include both these files:
```
/lib/x86_64-linux-gnu/libpthread.so.0
/lib/x86_64-linux-gnu/libpthread-2.27.so
```
=> Include libraries and symbolic links based on SONAMEs

runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/optimizer/J9CallGraph.hpp, runtime/compiler/optimizer/J9Inliner.cpp
...unless inliner has already proved that the receiver is an instance of a particular class that implements the expected interface. (However, it appears that it is currently difficult or maybe impossible to get such a bound despite `tryToRefineReceiverClassBasedOnResolvedTypeArgInfo()`).
A passing `vgnop`-based interface guard can guarantee the receiver type is as expected by the inlined body, but only if we already know before the guard that the receiver implements the expected interface. Here, an interface type bound is insufficient to know that, because bytecode verification does not guarantee any particular receiver type at `invokeinterface`.
As such, in the absence of a class (i.e. non-interface) type bound on the receiver, all targets must use profiled guard. Additionally, the …
=> Disallow nop guards for interface call sites

doc/release-notes/0.35/0.35.md
Updated the tables in the release notes.
[skip ci]
=> Updated 0.35 release notes tables

runtime/gc_base/modronapi.cpp, runtime/gc_glue_java/ScavengerDelegate.cpp, runtime/gc_modron_standard/StandardAccessBarrier.cpp, runtime/gc_modron_standard/StandardAccessBarrier.hpp
StandardAccessBarrier could be initialized before Global scavenger is set up, the field 
StandardAccessBarrier._scavenger need to be set after the Global scavenger is created.
=> Avoid to cache scavenger too early in StandardAccessBarrier

runtime/jvmti/jvmtiThread.c
Add missing NULL checks for threadholder in jvmti calls
=> Add missing NULL checks for threadholder in jvmti calls

doc/build-instructions/Build_Instructions_V11.md, doc/build-instructions/Build_Instructions_V17.md, doc/build-instructions/Build_Instructions_V18.md, doc/build-instructions/Build_Instructions_V8.md
* add missing line-continuation for jdk8
* remove advice to use `--with-freetype=<path>` with jdk11+ to avoid this error
> configure: error: 'valid values for --with-freetype are 'system' and 'bundled'
=> Remove uses of unsupported freetype configure options

jcl/src/java.base/share/classes/java/lang/Access.java
Add Access implementations:
```
public boolean isCarrierThreadLocalPresent(CarrierThreadLocal<?> carrierThreadlocal)
public <T> T getCarrierThreadLocal(CarrierThreadLocal<T> carrierThreadlocal)
public void removeCarrierThreadLocal(CarrierThreadLocal<?> carrierThreadlocal)
public <T> void setCarrierThreadLocal(CarrierThreadLocal<T> carrierThreadlocal, T carrierThreadLocalvalue)
```
closes https://github.com/eclipse-openj9/openj9/issues/16141
=> JDK19+ implements carrier thread local Access APIs

jcl/src/java.base/share/classes/java/lang/Access.java
Fix JDKNext duplicated Access API definitions
closes https://github.com/eclipse-openj9/openj9/issues/16162
=> Fix JDKNext duplicated Access API definitions

runtime/compiler/runtime/JITServerAOTCache.cpp, runtime/compiler/runtime/JITServerAOTCache.hpp, runtime/compiler/runtime/JITServerAOTSerializationRecords.hpp
The current JITServer AOT cache lacks any persistence mechanism. These changes add two functions
```c++
class JITServerAOTCache
{
...
bool writeCache(FILE *f) const;
static JITServerAOTCache *readCache(FILE *f, const std::string &name, TR_Memory &trMemory);
}
```
to the public cache interface that will read or write an entire cache to or from a particular file stream. A cache file header and versioning mechanism has also been introduced.
The added intrusive linked list traversals of the AOT cache maps allow cache serialization to be performed concurrently with other cache record storage and retrieval.
=> Add JITServer AOT cache persistence

runtime/jvmti/jvmtiClass.c
Solves https://github.com/eclipse-openj9/openj9/issues/15984
=> Convert last slash in hidden/anonymous class signatures to period

runtime/jcl/common/mgmtthread.c, runtime/util/thrinfo.c
Use carrierThreadObject instead of threadObject for Java 19.
For thread with a virtual thread mount that is waiting on a lock,
we should return the virtual thread object as lock object/owner.
Fixes #15941
=> Patch MXBean to support virtual threads

runtime/jcl/common/getstacktrace.c, runtime/jcl/common/thread.cpp, runtime/oti/jclprots.h
For threads with continuation mounted, check if the caller expects
the stacktrace from the virtual thread or carrier thread.
Fix: #15247 
=> Handle mounted CarrierThread in Thread.getStackTrace

runtime/jcl/common/mgmtthread.c
Fixes the typo introduced in #15956. `targetThread` should be used instead
of `currentThread` for retrieving the `threadObject`.
Related: https://github.com/eclipse-openj9/openj9/commit/ce4d4a3c5811ee3e446df6b066e9bbdfd39f2751#r87746489
Related: #14538
=> Get threadObject from targetThread in mgmtthread.c::getThreadInfo

runtime/jcl/common/system.c, runtime/oti/j9nonbuilder.h, runtime/oti/util_api.h, runtime/oti/vm_api.h, runtime/util/defarg.c, runtime/util/util.tdf, runtime/vm/vmbootlib.c, test/functional/cmdLineTests/SystemPropertiesTest/playlist.xml, test/functional/cmdLineTests/SystemPropertiesTest/src/SysPropRepeatDefinesTest.java, test/functional/cmdLineTests/SystemPropertiesTest/sysproprepeatdefinestest.xml
Add `getDefinedArgumentFromJavaVMInitArgs()` to look for the defined argument starting at the bottom of the `vmInitArgs->options` array; 
Refactor `getDefineArgument()` and its usages;
Replaced `getDefinedEncoding()` with `getDefinedArgumentFromJavaVMInitArgs()`;
Add a test.
[Internal personal build](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/14543/)
[Internal IBM Java 8 build](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=38956)
closes https://github.com/eclipse-openj9/openj9/issues/16080
=> Get defined argument from the bottom of the vmInitArgs->options array

jcl/src/java.base/share/classes/java/lang/String.java, jcl/src/java.base/share/classes/java/lang/StringBuffer.java, jcl/src/java.base/share/classes/java/lang/StringBuilder.java, test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_String.java, test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_StringBuffer.java, test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_StringBuilder.java
Add missing bounds check for offsetByCodePoints method in String, StringBuffer, and StringBuilder classes.
Add tests for offsetByCodePoints which result in out of bounds indices. 
Change a StringBuffer constructor to StringBuilder in StringBuilder test.
Fixes https://github.com/eclipse-openj9/openj9/issues/16188
Testing done on internal jenkins:
[Compile](https://hyc-runtimes-jenkins.swg-devops.com/job/Pipeline-Build-Test-Personal/14589/) - only difference between the commit used for the build and this PR is a copyright update.
`sanity.functional` tests running with `-XX:+CompactStrings`:
[JDK8](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29008/)
[JDK11](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29009/)
=> Missing bounds check for offsetByCodePoints

runtime/compiler/codegen/J9CodeGenerator.cpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/il/J9Node.cpp, runtime/compiler/il/J9Node.hpp, runtime/compiler/ilgen/Walker.cpp, runtime/compiler/optimizer/EscapeAnalysis.cpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/optimizer/SequentialStoreSimplifier.cpp, runtime/compiler/optimizer/UnsafeFastPath.cpp, runtime/compiler/optimizer/VarHandleTransformer.cpp, runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp, runtime/compiler/z/codegen/J9CodeGenerator.cpp, runtime/compiler/z/codegen/S390Register.cpp
Remove uses of expensive `TR::comp()` queries.  Refactor APIs to pass available Compilation objects where appropriate.
=> Remove some uses of TR::comp()

runtime/gc_glue_java/CompactSchemeFixupObject.cpp, runtime/gc_glue_java/CompactSchemeFixupObject.hpp, runtime/gc_glue_java/HeapWalkerDelegate.cpp, runtime/gc_glue_java/HeapWalkerDelegate.hpp, runtime/gc_glue_java/MarkingDelegate.cpp, runtime/gc_glue_java/MarkingDelegate.hpp, runtime/gc_glue_java/MetronomeDelegate.cpp, runtime/gc_glue_java/MetronomeDelegate.hpp, runtime/gc_glue_java/ScavengerDelegate.cpp, runtime/gc_glue_java/ScavengerDelegate.hpp, runtime/gc_modron_standard/StandardAccessBarrier.cpp, runtime/gc_realtime/RealtimeAccessBarrier.cpp, runtime/gc_realtime/RealtimeAccessBarrier.hpp, runtime/gc_vlhgc/CopyForwardScheme.cpp, runtime/gc_vlhgc/CopyForwardScheme.hpp, runtime/gc_vlhgc/GlobalMarkCardScrubber.cpp, runtime/gc_vlhgc/GlobalMarkCardScrubber.hpp, runtime/gc_vlhgc/GlobalMarkingScheme.cpp, runtime/gc_vlhgc/GlobalMarkingScheme.hpp, runtime/gc_vlhgc/WriteOnceCompactor.cpp, runtime/gc_vlhgc/WriteOnceCompactor.hpp
We use scanning the continuation object to trigger related preReadBarrier processing in order to handle concurrent case during Metronome GC, but for root scanning and tracing phase, the mounting carrier thread(mutator thread) has not been initialized for markObject. so update to use rememberObject instead of markObject for handling preCountinuationMount case.
depends on:https://github.com/eclipse-openj9/openj9/pull/16157
=> Handle continuation mounting case during Metronome GC

runtime/vm/BytecodeInterpreter.hpp, test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeUnsafeTestClasses.java, test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeUnsafeTests.java
Also add test case to catch the same error in the future
solves #16156
=> Fix assertion error in Unsafe.isFlattened

runtime/vm/threadhelp.cpp
Time compensation is not required for scenarios other than `waitTimed` and `timedout`, or `isThreadHaltedAtSingleThreadedMode`.
=> CRIU avoid unnecessary park() when a balancing unpark() occurred

test/functional/Java19andUp/playlist.xml, test/functional/Java19andUp/src/org/openj9/test/jep424/valist/ApiTests.java, test/functional/Java19andUp/src/org/openj9/test/jep424/valist/DowncallTests.java, test/functional/Java19andUp/src/org/openj9/test/jep424/valist/UpcallTests.java, test/functional/Java19andUp/src/org/openj9/test/jep424/valist/VaListUpcallMethodHandles.java
The changes update a few VaList test cases specific to
Linux/s390x which also apply to other platforms.
=> [JDK19]Update VaList test cases for Linux/s390x

runtime/compiler/optimizer/FearPointAnalysis.cpp, runtime/compiler/optimizer/FearPointAnalysis.hpp, runtime/compiler/optimizer/HCRGuardAnalysis.cpp, runtime/compiler/optimizer/OSRGuardInsertion.cpp
If a method we are compining contains the vector API intrinsic method call, set virtual guards kills fear fear flag to false which will prevent merging of Virtual guards with OSR guard and allows expansion of Vector API intrinsic methods.
=> Set VirtualGuard do not kill fear if has VectorAPIMethod

runtime/compiler/optimizer/EscapeAnalysis.cpp, runtime/compiler/optimizer/EscapeAnalysis.hpp, runtime/compiler/p/codegen/J9TreeEvaluator.cpp
With Lock Reservation and Nested Locks it's possible for a monExit to skip executing a lwsync(ppc). Yet EA disables AllocationFence nodes when it encounters a monExit or a synchronized call before the object which the AllocationFence is guarding escapes. This allows for cases where no lwsync is executed before references to the object is stored to the heap which might result in a crash when other threads attempt to read the object contents on weak memory coherency CPUs (PPC & AArch64).
Optimizer Changes:
This fix changes EA so that it will insert new AllocationFence nodes before monExit or volatile-access nodes that EA has decided can replace the original AllocationFence. The code generator can then optimize the generation of lwsync instructions so that only one lwsync is executed and …
=> Fix EA so that it does not assume monExit will always execute an lwsync

runtime/criusupport/criusupport.cpp, runtime/criusupport/j9criu.tdf, runtime/vm/CRIUHelpers.cpp
Move `checkpointNanoTimeMonotonic=j9time_nano_time()` before `TRIGGER_J9HOOK_VM_PREPARING_FOR_CHECKPOINT` which is closer to the stage JVM paused;
Move `checkpointNanoUTCTime=j9time_current_time_nanos()` as well.
Keep `Trc_CRIU_before_checkpoint()` and `Trc_CRIU_after_checkpoint()` close to `criu_dump()` for time measurement of the pre-checkpoint phase;
Add `Trc_CRIU_checkpoint_nano_times()` and `Trc_CRIU_restore_nano_times()` to record time compensation.
closes https://github.com/eclipse-openj9/openj9/issues/15991
=> CRIU nanoTimeMonotonicClockDelta calculation adjusted

runtime/compiler/env/J9PersistentInfo.hpp
The default name of the AOT cache that a client will request from a JITServer instance is now "default". Formerly it was nameless (the empty string).
Fixes: #16107
=> Give a name to the default JITServer AOT cache

runtime/vm/vmthread.cpp
As per RI, ThreadMXBean findMonitorDeadlockedThreads excludes virtual threads.
Fixes failing internal tests.
Testing done internally:
[Build](https://hyc-runtimes-jenkins.swg-devops.com/job/Build_JDK19_s390x_linux_Personal/44/)
[Sanity functional](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29113/)
[Extended functional](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29121/)
[Sanity openjdk](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29117/)
[Extended openjdk](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29123/)
[Rerun of failing tests](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29116/)
fyi: @babsingh @tajila
=> ThreadMXBean findMonitorDeadlockedThreads excludes virtual threads

runtime/criusupport/j9criu.tdf
Obsolete `Trc_CRIU_after_checkpoint` and reuse it with a new signature
Related https://github.com/eclipse-openj9/openj9/pull/16091#pullrequestreview-1162282005
=> Obsolete Trc_CRIU_after_checkpoint and reuse it with a new signature

test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_Thread.java, test/functional/VM_Test/src/j9vm/test/clinit/GetStaticDuringClinit.java, test/functional/VM_Test/src/j9vm/test/clinit/InvokeStaticDuringClinit.java, test/functional/VM_Test/src/j9vm/test/clinit/NewDuringClinit.java, test/functional/VM_Test/src/j9vm/test/clinit/PutStaticDuringClinit.java
Tested in grinders
jdk20: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1476/
jdk11: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1477
Fixes https://github.com/eclipse-openj9/openj9/issues/16213
=> Fix use of Thread.resume(), stop(), suspend() in tests for jdk20

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp, runtime/compiler/env/j9method.cpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp
- this method contains a simple check whether provided index is greater than 0 and less than provided upper bound. This check lands itself well to various JIT optimizations (e.g. moving out of a loop).
=> Inline jdk/internal/util/Preconditions.checkIndex

runtime/jvmti/jvmtiHelpers.c
If a virtual thread is not mounted and a continuation is being run
directly on a platform thread, then the continuation is considered
part of the platform thread, and the fields should not be swapped
with `J9VMContinuation->currentContinuation` to get the platform
thread details. This behaviour matches the RI.
Get platform thread details from `J9VMThread->currentContinuation`
IFF it is not mounted.
Fixes: #16240
=> Fix JVMTI ContFramePopTest

runtime/include/ffi_common.h, runtime/libffi/CMakeLists.txt, runtime/libffi/aarch64/ffi.c, runtime/libffi/aarch64/ffitarget.h, runtime/libffi/aarch64/internal.h, runtime/libffi/aarch64/sysv.S, runtime/libffi/closures.c, runtime/libffi/preconf/xr64/ffi.h, runtime/libffi/preconf/xr64/fficonfig.h, runtime/libffi/tramp.c
The changes aim to resolve the libffi related issue detected on jtreg FFI downcall & upcall
tests suites by replacing the outdated version on Aarch64 with the latest version in Github at
https://github.com/libffi/libffi/tree/master/src/aarch64 to better support the downcall & upcall
with struct in JEP389/424(Foreign Linker API) which is part of the Panama project.
The latest committed SHA: c6dc125afba294b9b9613392c492ae18df3ede84
=> Replace libffi/aarch64 with the latest version in GitHub

runtime/oti/j9port.h, runtime/port/sysvipc/j9shmem.c
Change the default SCC directory on Linux, AIX and MacOS to  $HOME/.cache/javasharedresources/
Depends on https://github.com/eclipse-openj9/openj9-docs/issues/1016
Closes #11417
=> Change the default SCC directory

jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassAbstractHelper.java
All constructors for java.net.URL have been deprecated by
* 8294241: Deprecate URL public constructors
=> Suppress deprecation warnings for jdk20+

runtime/vm/lookupmethod.c
Ensure that proper exception is thrown after a non-visible method is skipped during interface method resolution.
Related to internal issue 147613
=> Update interface method resolution

runtime/vm/xr64/UpcallThunkGen.cpp
This commit fixes getArgPointer() for AArch64.
=> AArch64: Fix getArgPointer() for FFI upcall

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/J9ObjectFieldOffsetIterator_V1.java
=> Fix DDR hiddenfield iterator

test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestOpenJ9DiagnosticsMXBean.java
Related to issue https://github.com/eclipse-openj9/openj9/issues/16253
=> Fix potential NPE in TestOpenJ9DiagnosticsMXBean.tearDown()

runtime/compiler/env/J9CompilerEnv.cpp, runtime/compiler/env/J9CompilerEnv.hpp, runtime/compiler/p/env/J9CPU.cpp, runtime/compiler/runtime/RelocationRuntime.cpp, runtime/compiler/z/env/J9CPU.cpp
This PR disables the TM feature when generating portable code. 
Fixes https://github.com/eclipse-openj9/openj9/issues/16009
=> Disable TM when generating portable code

runtime/compiler/optimizer/VectorAPIExpansion.cpp
Create a StackMemoryRegion object in VectorAPIExpansion so that the memory allocated to stack region during VectorAPIExpansion is released on completion of it.
=> Create a StackMemoryRegion object in VectorAPIExpansion

runtime/j9vm/javanextvmi.cpp
Currently, VirtualThread objects are appended to liveVirtualThreadList
in JVM_VirtualThreadMountBegin.
To assist GC with synchronizing while scanning continuations and
VirtualThread objects, VirtualThread objects are appended to
liveVirtualThreadList in JVM_VirtualThreadMountEnd.
This delay will prevent race conditions for the GC while scanning the
VirtualThread objects.
Related: #16290
Related: #16259
=> Delay appending VirtualThread objects to liveVirtualThreadList

runtime/oti/j9consts.h, runtime/oti/j9nonbuilder.h, runtime/vm/swalk.c
Prevent potential endless loop in the stack walker when examining the stack of a thread which has been interrupted when not at a safe point.
=> Stack walk loop breaker for ASGCT

runtime/include/zconf.h, runtime/include/zlib.h, runtime/zlib/compress.c, runtime/zlib/crc32.c, runtime/zlib/deflate.c, runtime/zlib/deflate.h, runtime/zlib/infback.c, runtime/zlib/inflate.c, runtime/zlib/inftrees.c, runtime/zlib/inftrees.h, runtime/zlib/trees.c, runtime/zlib/uncompr.c, runtime/zlib/zutil.c, runtime/zlib/zutil.h
Version 1.2.13 has these key updates from 1.2.12:
-    Fix a bug when getting a gzip header extra field with
inflateGetHeader(). This remedies
[CVE-2022-37434](https://nvd.nist.gov/vuln/detail/CVE-2022-37434).
-    Fix a bug in block type selection when Z_FIXED used. Now the
smallest block type is selected, for better compression.
-    Fix a configure issue that discarded the provided CC definition.
-    Correct incorrect inputs provided to the CRC functions. This
mitigates a bug in Java.
-    Repair prototypes and exporting of the new CRC functions.
-    Fix inflateBack to detect invalid input with distances too far.
The CVE is already fixed in 0.35 via [1]. The bug fix for Java is
already fixed in 0.33 via the extensions,  example [2].
[1] …
=> Update to zlib 1.2.13

test/functional/Valhalla/playlist.xml, test/functional/Valhalla/src/org/openj9/test/lworld/DDRBackfillLayouTest.java, test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTestClasses.java, test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java, test/functional/Valhalla/testng.xml, test/functional/cmdLineTests/valuetypeddrtests/flattened32bitRefBackfillTest.xml
1. Re-write testFlatLayoutsWithRecursiveLongs and
testACMPTestOnFastSubstitutableValueTypesVer2 using classes from Javac
instead of ASM generated classes.
2. Put the new classes in ValueTypeTestClasses, the class names of
ValueLong, DoubleLong, QuadLong and DoubleQuadLong now become 
org/openj9/test/lworld/ValueTypeTestClasses$ValueTypeLong,
org/openj9/test/lworld/ValueTypeTestClasses$ValueTypeDoubleLong,
org/openj9/test/lworld/ValueTypeTestClasses$ValueTypeQuadLong,
org/openj9/test/lworld/ValueTypeTestClasses$ValueTypeDoubleQuadLong.
3. Update the DDR tests to check for the new class names.
4. Split ValueTypeArrayTests from ValueTypeTests.
Closes #16291 #16292
Closes #16284
=> Re-write valueType sub-tests

runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/J9Options.hpp, runtime/compiler/control/JITServerCompilationThread.cpp, runtime/compiler/env/J9PersistentInfo.hpp, runtime/compiler/env/PersistentCollections.hpp, runtime/compiler/runtime/JITClientSession.cpp, runtime/compiler/runtime/JITServerAOTCache.cpp, runtime/compiler/runtime/JITServerAOTCache.hpp
This PR implements support for loading an AOT cache from a file and saving an AOT cache to a file. This is done by a compilation thread that works concurrently with other compilation threads that compile methods.
For reading, the sequence of actions is the following:
1. Compilation thread at the server reads compilation request from client and determines whether the client wants to use the AOTCache
2. Server checks its hashmap to see if the named cache already exists. If it exists, it will be used.
3. If desired cache does not exist, server checks if the persistence feature is enabled and whether a file for the desired cache exists.
4. If the AOT cache file exists, the server will memorize the name of the cache in a set, queue a special compilation request (with stream==0) and wake a …
=> Support for reading/writing a JITServer AOT cache in the background

runtime/compiler/runtime/JITServerAOTCache.cpp, runtime/compiler/runtime/JITServerAOTCache.hpp, runtime/compiler/runtime/JITServerAOTSerializationRecords.hpp
This PR cleans up some of the JITServer AOT cache reading code from the recent #15949. 
- A new cache read context struct simplifies passing around the relevant state when reading a cache file
- The various read functions for the individual cache records (other than `CachedAOTMethod`) have been consolidated into a single `AOTCacheRecord::readRecord` function template.
Related: #16109
=> Refactor JITServer AOT cache reading

test/functional/Valhalla/playlist.xml, test/functional/Valhalla/testng.xml
ValueTypeTestsJIT has the same class as ValueTypeTests. ValueTypeArrayTestsJIT has the same class as ValueTypeArrayTests. They can be removed from testng.xml
=> Remove ValueTypeArrayTestsJIT and ValueTypeTestsJIT from testng.xml

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
This PR stops generating a dmb instruction for allocationFence on AArch64 if the node is followed by monexit, for reducing memory synchronization.
=> AArch64: Stop generating a dmb for allocationFence when possible

test/functional/Java8andUp/src/org/openj9/test/attachAPI/TestAttachErrorHandling.java
Fix AttachAPI test `AssertJUnit.assertNotNull()`
closes https://github.com/eclipse-openj9/openj9/issues/16315
=> Fix AttachAPI test AssertJUnit.assertNotNull()

runtime/bcverify/staticverify.c
The check is unnecessary and throws a ClassFormatError when trying to verify a value class which calls a non-value class constructor.
=> Remove type checks for VT <init> method in constant pool

runtime/compiler/optimizer/IdiomTransformations.cpp
Fixes https://github.com/eclipse-openj9/openj9/issues/15855
=> Disable countDecimalDigits transformation for AOT compilations

runtime/compiler/compile/J9SymbolReferenceTable.cpp, runtime/compiler/compile/J9SymbolReferenceTable.hpp, runtime/compiler/optimizer/J9ValuePropagation.cpp, test/functional/Valhalla/playlist.xml, test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeArrayTests.java
The field offset from `TypeLayoutEntry` includes object header and the padding before the first field. The flattened array element field shadow symbol reference calculates the offset from the object header and expects the offset of the first field to be zero. The offset that is passed in to create the array element field shadow symbol should take into consideration of the padding.
=> Fix field offset in flattened array element access

buildenv/docker/mkdocker.sh, buildenv/jenkins/variables/defaults.yml
* [skip ci]
* added for openssl3 support
* eclipse-openj9/openj9#13686
=> Add perl-IPC-Cmd to CentOS6 docker container

runtime/vm/jvminit.c
`CRIURestoreNonPortableMode` is enabled by default
By default, not support checkpoint on a restored CRIU image.
=> CRIURestoreNonPortableMode is enabled by default

test/functional/Java17andUp/playlist.xml, test/functional/Java17andUp/src_170/org/openj9/test/jep389/valist/ApiTests.java, test/functional/Java17andUp/src_170/org/openj9/test/jep389/valist/DowncallTests.java, test/functional/Java17andUp/src_170/org/openj9/test/jep389/valist/UpcallTests.java, test/functional/Java17andUp/src_170/org/openj9/test/jep389/valist/VaListUpcallMethodHandles.java, test/functional/Java17andUp/testng_170.xml
The changes backport the same test suites in JEP424(JDK19) with the required APIs in JEP389/412(JDK17).
Note:
The PR is part of FFI downcall & upcall work at
eclipse-openj9/openj9#12412 and eclipse-openj9/openj9#15068.
=> [VaList/JDK17]Enable VaList related test suites on Power & zLinux

runtime/jcl/common/stdinit.c, runtime/jvmti/jvmtiThread.c, runtime/oti/j9nonbuilder.h
Set J9JavaVM->vthreadGroup in stdinit.c::standardInit to remove the
recursive dependency with JVMTI event callbacks, which causes an
infinite loop.
Closes: #16229
=> Fix jvmtiGetThreadInfo

runtime/compiler/optimizer/J9Optimizer.cpp, runtime/compiler/optimizer/OptimizationGroups.enum
The `profilingOpts` optimization strategy includes `profileGenerator` and `deadTreesElimination`.  The `profileGenerator` simply returns if the JProfiling mode is enabled, while the `deadTreesElimination` is intended to clean up trees that might have been introduced by `profileGenerator`, so it too is really only needed if JitProfilng mode is enabled.  However, the optimization strategy as a whole is being run if either JProfiling or JitProfiling is enabled.
Some optimization strategies run `compactLocals` very late, just before `profileOpts` is run.  Running `deadTreesElimination` after `compactLocals` might invalidate the analysis `compactLocals` has performed.  The `compactLocals` analysis is only run if JitProfiling mode is not enabled.
This changes uses of `profilingGroup` to only …
=> Use profilingOpts strategy under JitProfiling mode only

runtime/vm/xz64/UpcallThunkGen.cpp
When getArgPointer is invoked while an upcall is performed the gprIndex must be incremented if hidden parameters have to be accounted for. This commit implements the suggested change.
Fixes: #16214
=> Increment counter correctly in FFI Upcall on Z

runtime/j9vm/j9scar.tdf, runtime/j9vm/javanextvmi.cpp
The asserts verify that a virtual thread is only
- added once to the list; and
- removed IFF it was added to the list.
The previous and next fields of the virtual thread object are set to
null when it is removed from the list.
Tracepoints output important details to triage failures.
Related: https://github.com/eclipse-openj9/openj9/issues/16249
Related: https://github.com/eclipse-openj9/openj9/issues/16259
=> Add asserts and tracepoints in JVM_VirtualThread* functions

runtime/compiler/runtime/JITServerAOTCache.cpp, runtime/compiler/runtime/JITServerAOTCache.hpp
The JITServer AOT cache persistence code will now add a message to the verbose log explaining any serialization error that may have occurred.
Fixes: #16114
=> Improve JITServer AOT cache error logging

jcl/src/java.base/share/classes/java/lang/Class.java
=> Adds implementation for accessFlags() in Class.java

runtime/compiler/optimizer/VectorAPIExpansion.cpp, runtime/compiler/optimizer/VectorAPIExpansion.hpp
The return type of `jdk_internal_vm_vector_VectorSupport_fromBitsCoerced` can be either of Vector or Mask.
Change the type field of the `fromBitsCoerced` entry in the method table to `unknown` and update `visitNodeToBuildVectorAliases` to get the correct type for the call by checking the value of the 5th child node.
=> Fix the return type of VectorSupport.fromBitsCoerced

runtime/compiler/optimizer/J9ValuePropagation.cpp, runtime/compiler/optimizer/J9ValuePropagation.hpp
The verifier treats interface types as `java/lang/Object` even within array component types. In particular, when any parameter, instance or static field, or return type is declared with a signature naming an array of an interface type, its value is guaranteed to be a reference array, but not necessarily the named array type. For example, if a parameter is declared to be of type `List[]`, it can actually be any `Object[]`.
----
There is one preparatory refactoring commit:
- Factor VP interface type signature detection logic into its own method
=> Make VP erase interface types in array types from signatures

test/functional/cmdLineTests/jvmtitests/jvmtitests_excludes_20.xml
GetThreadGroupChildren was fixed by #15539.
The above PR removed the exclude for JDK19.
But, the exclude for JDK20 was not removed.
Related: #15244
=> Re-enable gtgc001 on JDK20

jcl/src/java.base/share/classes/java/lang/Object.java, runtime/util/final.c, runtime/vm/BytecodeInterpreter.hpp, runtime/vm/FastJNI_java_lang_Object.cpp, runtime/vm/bindnatv.cpp
=> Update Object.wait to use Blocker.begin/end for Java 19+

jcl/src/java.base/share/classes/java/lang/Class.java, test/functional/Java8andUp/src_110_up/org/openj9/test/java/lang/Test_Class.java
1. Add "primitive"/"value" for primitive VT and value classes.
2. Unset Valhalla modifiers before calling Modifier.toString()
3. Modify test_getModifiers_classTypes to recognize Modifer.IDENTITY
Closes #16327
Closes #16319
=> Unset Valhalla modifiers in Class.toGenericString()

jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
From jdk20 Thread.stop() throws UnsupportedOperationException.
Related to https://github.com/eclipse-openj9/openj9/issues/16213
=> Remove mention of ThreadDeath, which is unused and deprecated in jdk20

runtime/gc_glue_java/CompactDelegate.cpp, runtime/gc_glue_java/CompactSchemeFixupObject.cpp, runtime/gc_glue_java/CompactSchemeFixupObject.hpp, runtime/gc_glue_java/CompactSchemeFixupRoots.cpp, runtime/gc_glue_java/CompactSchemeFixupRoots.hpp, runtime/gc_vlhgc/WriteOnceCompactor.cpp, runtime/gc_vlhgc/WriteOnceCompactor.hpp
Once continuation Object is constructed, the Object would be added in global continuation lists and the "dead" Object would be collected by GC, since logically compaction would not collect any continuation Object in the list, so we piggyback heap fix up to rebuild the list to reduce the extra cycle to walk the old list for fixing up. But between the Object is created and added into the list, GC could be triggered and find the live Object, which has not be added in the list, it could cause a circular linklist case, so changing fix up the existing list instead of rebuilding the list for compaction.
fix:https://github.com/eclipse-openj9/openj9/issues/15938 (assertion failure in ContinuationObjectBuffer/List)
=> Fix up global continuation lists instead of rebuilding for compaction

runtime/compiler/optimizer/VectorAPIExpansion.cpp
- maskReductionCoerced intrinsic has element type Int for Float vectors and Long for Double vectors. For the sake of class verification we can leave _elementType field unset and it will be automatically derived from the child type (since they will be in the same class)
=> Handle maskReductionCoerced element type in VectorAPIExpansion

runtime/vm/wa64/UpcallThunkGen.cpp
Structs <= 8 bytes passed in argument position > 4 are passed on the stack for the Windows x64 calling convention.
Fixes #16235
=> Pass struct correctly in memory for Windows upcall thunk

runtime/libffi/aarch64/ffi.c
This commit fixes the libffi code for AArch64.
When a structure is passed as an argument in the stack, it has to be at the 8-byte boundary under a certain condition.  The next argument after the structure is also expected to be aligned at 8-byte boundary in the stack.
Fixes: #16336
=> AArch64 macOS: Fix alignment of structs passed in the stack

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalUpcallHandler.java, runtime/jcl/common/jdk_internal_foreign_abi_UpcallStubs.cpp, runtime/oti/j9nonbuilder.h, runtime/oti/jclprots.h, runtime/vm/OutOfLineINL_openj9_internal_foreign_abi_InternalUpcallHandler.cpp, runtime/vm/UpcallThunkMem.cpp, runtime/vm/j9vm.tdf, runtime/vm/jvminit.c, runtime/vm/vmthinit.c
The changes aim to address the OOM issue with thunk allocation on the platforms with a small page size (e.g. 4KB) by maintaining a circular thunk heap list in which case a new thunk heap is created only when there is no free thunk heap available in the list to allocate thunk.
=> [Jtreg/FFI]Fix the OOM issue with thunk allocation

runtime/jvmti/jvmtiThread.c
The jvmtiGetThreadInfo returns the invalid thread group in case of unstarted threads. A NULL targetThread indicates that the thread is either unstarted or terminated so this check is not sufficient to validate terminated threads.
The boolean check is updated in jvmtiGetThreadInfo to return a valid thread group for unstarted threads.
Fixes: #16226
Signed-off-by: Dipak Bagadiya <dipak.bagadiya@ibm.com>
=> Fix jvmtiGetThreadInfo to return correct thread group

test/functional/cmdLineTests/criu/criu.xml, test/functional/cmdLineTests/criu/criu_keepCheckpoint.xml, test/functional/cmdLineTests/criu/criu_nonPortable.xml, test/functional/cmdLineTests/criu/criu_nonPortableJDK11Up.xml, test/functional/cmdLineTests/criu/criu_random.xml, test/functional/cmdLineTests/criu/criu_security.xml
Update criu test to ignore tid issues
If CRIU can't acquire the origin thread IDs it will fail, nothing can be done about this. update tests to ignore this failure. Long term we may need to transform all tests to container tests.
=> Update criu test to ignore tid issues

runtime/criusupport/CMakeLists.txt, runtime/criusupport/criusupport.cpp, runtime/criusupport/module.xml, runtime/nls/j9cl/j9jcl.nls, runtime/oti/j9nonbuilder.h, runtime/vm/jvminit.c
Refactor CRIUSupport to eliminiate need for static linking
In order to remove the build dependency on libcriu we will dynamically load libcriu at runtime.
=> Refactor CRIUSupport to eliminiate need for static linking

runtime/j9vm/j9scar.tdf, runtime/j9vm/javanextvmi.cpp, runtime/oti/j9.h
Add assertions to virtual thread mount and unmount
Assert that only virtual threads can be added to the virtual thread
list. Add eye catcher for rootNode virtual thread to distinguish from
application virtual threads.
=> Add assertions to virtual thread mount and unmount 

test/functional/JIT_Test/playlist.xml
arch.s390x is invalid. We should use arch.390.
Since testJITServer is currently running and passing on zlinux, 
update platformRequirements to avoid confusion.
Signed-off-by: Lan Xia <Lan_Xia@ca.ibm.com>
=> Remove invalid arch.s390x

runtime/compiler/runtime/J9Profiler.cpp
While working on fixing the block frequnecy calculation when previous inlining may be different in [1], a bug was introduced so that a flag that would notify the caller of computeEffectiveCallerIndex upon successfully  matching BCI was never set. This commit fixes that bug.
[1]. https://github.com/eclipse-openj9/openj9/commit/9f404bec672945f99f74483df59cbcbc974453b0
=> Fix bug while computing effective caller index

runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp
No need to decrement reference count of address node in
`pdloadVectorEvaluatorHelper`, `pdstoreVectorEvaluatorHelper` and
`zdstoreiVectorEvaluatorHelper` evaluators because that happens in
`MemoryReference(TR::Node * rootLoadOrStore...)` on
`rootLoadOrStore->getOpCode().isIndirect()` path.
Comments in those evaluators have also been updated to reflect this.
=> Remove node refCount decrement in DAA evaluators

runtime/compiler/p/codegen/J9TreeEvaluator.cpp
The instanceOf while-loop body always performs the "transition to the next sequence". The while-loop condition allows last entry of the sequence to enter the loop (`(numSequencesRemaining == 1 && *iter != HelperCall)`), which doesn't happen in checkCast given no boolean output is possible from checkCast.
This causes the "transition to the next sequence" to be generated even if no subsequent sequence item exists. This is mostly harmless except if the non-initialized sequence array, by chance after allocating, has a value representing `HelperCall` in the "next" element. Where generating the "transition to the next sequence" uses a different path that generates harmful code, causing #13078.
The fix basically wraps the "transition to the next sequence" code with a `numSequencesRemaining > 0` …
=> Check sequence boundary before generating next sequence transition

runtime/vm/xr64/UpcallThunkGen.cpp
This commit cleans up UpcallThunkGen.cpp code for AArch64 for better readability.
- Rename the variable tempInt to argSize and resultSize.
- Stop using the variables useMoreGPRs and useMoreFPRs.
- Stop using the variables gprCount and fprCount.
=> AArch64: Clean up UpcallThunkGen.cpp

runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/control/JITServerHelpers.cpp, runtime/compiler/control/JITServerHelpers.hpp
The messages that are printed by a client JVM when the `-XX:+JITServerLogConnections` option is specified can sometimes be misleading. For instance, if a client starts, but there is no server available, the client will print a message saying that it lost connection to the server, where in fact, it was never connected to a server. In other cases there could be a transient error that one of the compilation thread experiences and the client will issue a "Lost connection to the server" message, but the other compilation threads continue to compile remotely just fine. This commit fixes the issues mentioned above.
Issue: #16381
=> Improve client JVM disconnect messages

runtime/j9vm/javanextvmi.cpp
Fix up potential stale pointer after GC
Fixes https://github.com/eclipse-openj9/openj9/issues/16351
=> Fix up potential stale pointer after GC

buildenv/jenkins/common/build.groovy, buildenv/jenkins/common/variables-functions.groovy, buildenv/jenkins/jobs/pipelines/Pipeline_Template.groovy, buildenv/jenkins/variables/defaults.yml
Update configuration for windows platform, switch bootjdk installation
directory to default location (home directory) for Windows machines.
Add optional error handling for intermittent failures.
=> Update OpenJ9 build for Windows

LICENSE, longabout.html, runtime/include/about.html, runtime/zlib/about.html
This should have been done with previous changes
https://github.com/eclipse-openj9/openj9/pull/16305 https://github.com/eclipse-openj9/openj9/pull/14835
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/16425 for 0.36
=> (0.36) Update LICENSE and about files for zlib 1.2.13, libffi

sourcetools/CMakeLists.txt, sourcetools/j9constantpool/CMakeLists.txt
* apply cmake classpath fix for sourcetools
* don't apply cmake classpath fix for j9vmcp
This is not compatible with the current content of the jdk11/openj9 branch; it must be merged concurrently with https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/599.
Fixes: https://github.com/eclipse-openj9/openj9/issues/16396.
=> Update cmake workarounds for jdk11

sourcetools/CMakeLists.txt, sourcetools/j9constantpool/CMakeLists.txt
Cherry-pick of #16435 for the 0.36.0 release.
=> (0.36.0) Update cmake workarounds for jdk11

runtime/bcverify/bcverify.c, runtime/bcverify/rtverify.c, runtime/oti/j9consts.h, runtime/verbose/errormessageframeworkrtv.c
The changes are to fix the issue with the flags setting intended for uninitializedThis
in the stackmaps so as to match the JVM Spec and the RI's behavior by explicitly
outputting the detailed error messages for the mismatch captured in the stackmaps.
Internal ref 147737
=> Rectify the flag setting for uninitializedThis in the stackmaps

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalUpcallHandler.java, runtime/jcl/common/jdk_internal_foreign_abi_UpcallStubs.cpp, runtime/oti/j9nonbuilder.h, runtime/oti/jclprots.h, runtime/vm/OutOfLineINL_openj9_internal_foreign_abi_InternalUpcallHandler.cpp, runtime/vm/UpcallThunkMem.cpp, runtime/vm/j9vm.tdf, runtime/vm/jvminit.c, runtime/vm/vmthinit.c
The changes aim to address the OOM issue with thunk allocation on
the platforms with a small page size (e.g. 4KB) by maintaining a thunk
heap list in which case a new thunk heap is created only when there
is no free thunk heap available in the list to allocate thunk.
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/16260 for 0.36
=> [FFI/0.36]Fix the OOM issue with thunk allocation

runtime/criusupport/criusupport.cpp, runtime/gc/gctable.c, runtime/gc_base/gc_internal.h, runtime/gc_base/modronapi.cpp, runtime/gc_modron_startup/mmparse.cpp, runtime/gc_realtime/Scheduler.hpp, runtime/oti/j9nonbuilder.h, runtime/vm/vmthread.cpp
Integrate CRIU support with new OMR GC APIs for thread pool adjustments, contract the thread pool for checkpoint and expand it for restore. 
For background, see https://github.com/eclipse/omr/pull/6831.
- Introduced `j9gc_prepare_for_checkpoint` and `j9gc_reinitialize_for_restore` APIs to consolidate GC specific routines used for checkpoint/restore
Report `J9NLS_GC_FAILED_TO_INSTANTIATE_TASK_DISPATCHER` on `j9gc_reinitialize_for_restore` failure
- Introduced `-XX:CheckpointGCThreads=` option to allow the user to tune checkpoint thread count
Depends on: https://github.com/eclipse/omr/pull/6831
=> GC Thread Pool Tuning for CRIU

runtime/bcverify/bcverify.c, runtime/bcverify/rtverify.c, runtime/oti/j9consts.h, runtime/verbose/errormessageframeworkrtv.c
The changes are to fix the issue with the flags setting intended for
uninitializedThis in the stackmaps so as to match the JVM Spec and
the RI's behavior by explicitly outputting the detailed error messages
for the mismatch captured in the stackmaps.
Cherry pick of #16423 for 0.36
=> [Verifier/0.36] Rectify the flag setting for uninitializedThis in the stackmaps

runtime/compiler/optimizer/EscapeAnalysis.cpp, runtime/compiler/optimizer/EscapeAnalysis.hpp
While performing analysis for flush elimination, `LocalFlushElimination::examineNode` called `TR::TreeTop::getEnclosingBlock` on the current `TR::TreeTop`.  As that method walks through the linked list chaining together the `TR::TreeTop`s to find the corresponding `BBStart`, calling it in nested loops becomes very expensive when large blocks are encountered.
Fixed this by passing the current block as an argument to `LocalFlushElimination::examineNode`.
Fixes #16353
=> Avoid calling getEnclosingBlock

runtime/gc_base/GCExtensions.cpp, runtime/gc_base/GCExtensions.hpp, runtime/gc_base/modronapi.cpp, runtime/gc_glue_java/MarkingSchemeRootClearer.cpp, runtime/gc_glue_java/MetronomeDelegate.cpp, runtime/gc_glue_java/ScavengerRootClearer.cpp, runtime/gc_modron_startup/mmparseXXgc.cpp, runtime/gc_vlhgc/CopyForwardScheme.cpp, runtime/gc_vlhgc/GlobalMarkingScheme.cpp, runtime/oti/VMHelpers.hpp
The Continuation Buffers/Lists keep all of "live" Continuation Objects
and be maintained by GC in order to free up the related native structure
and java stacks in case the Continuation Object has not been terminated
normally.
currently the global Virtual Thread List will keep all of unterminated
Continuation Objects traceable, so Continuation Buffers/Lists are not
useful for current case, can disable it by XXgc:disableContinuationList
for saving extra scan.
cycle.
- new XXgc options
disableContinuationList,
enaleContinuationList,
verifyContinuationList -- (default) verify if there is an exceptional
case.
=> Add Disable Global Continuation Lists option

runtime/compiler/optimizer/EscapeAnalysis.cpp, runtime/compiler/optimizer/EscapeAnalysis.hpp
While performing analysis for flush elimination, `LocalFlushElimination::examineNode` called `TR::TreeTop::getEnclosingBlock` on the current `TR::TreeTop`.  As that method walks through the linked list chaining together the `TR::TreeTop`s to find the corresponding `BBStart`, calling it in nested loops becomes very expensive when large blocks are encountered.
Fixed this by passing the current block as an argument to `LocalFlushElimination::examineNode`.
Merges changes from pull request #16455 to v0.36.0-release branch.
=> [0.36.0] Avoid calling getEnclosingBlock

runtime/compiler/aarch64/codegen/ARM64JNILinkage.cpp, runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
When building arguments to function calls, a non-clobberable register must be copied. Copying was only done for arguments passed by register, but non-clobberable registers holding arguments passed using the stack must be copied as well.
=> AArch64: Save non-clobberable argument register when passed using the stack

test/functional/cmdLineTests/criu/criuScript.sh
- Add GLIBC_TUNABLES values in criu cmdline tests
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/16382 This PR alone will not solve this issue, but it is required for portable test on various micro-architectures.
Signed-off-by: LongyuZhang <longyu.zhang@ibm.com>
=> Add GLIBC_TUNABLES values in criu cmdline tests

runtime/compiler/runtime/RelocationRuntime.cpp
The array of strings for relocation error types was missing a comma which meant that two entries were considered as one, and most error codes were misaligned.
=> Fix reloErrorCodeNames mistake

runtime/compiler/control/J9Options.cpp
The current default value for this option (50 ms) has been shown to cause a small footprint regression on Power. This commit changes the default value of `_updateFreeMemoryMinPeriod` to 300 ms on Power to eliminate the regression.
=> Set _updateFreeMemoryMinPeriod option to 300 ms on Power

runtime/gc_vlhgc/GlobalMarkingScheme.cpp
there is missing parameter for scanContinuationNativeSlots in VLHGC GlobalMarkingScheme, it would disable sync between concurrent scan and mounting continuation, then causes potential crash.
=> Fix missing parameter for scanContinuationNativeSlots

runtime/jvmti/jvmtiClass.c
JNI exceptions should not be pending upon return from a JVMTI function - the return value conveys success or failure.
Fixes: #16342
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/16483 to 0.36
=> (0.36) Clear pending exception after JVMTI class replacement

runtime/gc_vlhgc/GlobalMarkingScheme.cpp
there is missing parameter for scanContinuationNativeSlots in VLHGC GlobalMarkingScheme, it would disable sync between concurrent scan and mounting continuation, then causes potential crash.
=> (0.36.0) Fix miss parameter for scanContinuationNativeSlots

runtime/compiler/runtime/RelocationRuntime.cpp
The array of strings for relocation error types was missing a comma which meant that two entries were considered as one, and most error codes were misaligned.
=> Fix reloErrorCodeNames mistake (0.36.0)

test/functional/cmdLineTests/URLClassLoaderTests/playlist.xml
test excluded label to be removed from
https://github.com/eclipse-openj9/openj9/issues/11965 after merge.
Tested via grinders
alinux: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1718/
amac: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1719/
=> Remove aarch64 exclude of SCURLClassLoaderTests

runtime/compiler/control/CompilationRuntime.hpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/J9Options.hpp, runtime/compiler/control/JITClientCompilationThread.cpp
The `-Xaot:jitserverLoadExclude` and `-Xaot:jitserverStoreExclude` options reuse the existing method filtering framework so that clients can selectively exclude particular methods from AOT cache loading or storing in a connected JITServer.
Fixes: #15399
=> Add options for JITServer AOT caching exclusion

doc/processes/deprecation.md, doc/processes/release_process.md
This doc reflects the discussion between @DanHeidinga @pshipton @keithc-ca @0xdaryl and myself regarding the Eclipse OpenJ9 Deprecation Process.
=> Add Deprecation Process doc

runtime/compiler/control/HookedByTheJit.cpp
The original idle detection code contained a small bug: we want to transition from DEEPIDLE directly to ACTIVE state if the sampler finds two or more Java threads being active, but the code was checking for >2 (greater than 2 threads).
=> Exit DEEPIDLE state when two threads are active

runtime/gc_base/GCExtensions.cpp
Currently regular assertion is used in
MM_GCExtensions::releaseNativesForContinuationObject(). Replace it to assertion with message to simplify debugging process: print Continuation object address as well as address of J9VMContinuation structure.
=> Use assertion with message to simplify debugging

jcl/jpp_configuration.xml, runtime/cmake/options.cmake, runtime/include/j9cfg.h.in
Remove unused `OPENJDK_THREAD_SUPPORT` & `J9VM_OPT_OPENJDK_THREAD_SUPPORT`
=> Remove unused OPENJDK_THREAD_SUPPORT & J9VM_OPT_OPENJDK_THREAD_SUPPORT

runtime/compiler/optimizer/J9CFGSimplifier.cpp
Re-enable CFGSimplifier which has been disabled by [1].
The motivation for re-enabling it is that we want to use it for removing boundary check code from the loop when using Vector JEP.
When vectorizing library calls of `jdk.incubator.vector` package, there are many calls to `Preconditions.checkIndex()` [2] left in the loop. It checks if index is in the range and throws an OOB exception when the check fails. We want to take this boundary check code out of the loop. 
CFGSimplifier should be able to transform the boundary check pattern into a BNDCHK node [3] and we can let loopVersioner remove the BNDCHK from the loop.
The original issue with CFGSimplifier [4] seems to be already fixed by [5]. I am not able to reproduce it with multiple runs of system test using this commit. It seems that …
=> Re-enable CFGSimplifier

runtime/codert_vm/cnathelp.cpp, runtime/codert_vm/decomp.cpp, runtime/compiler/aarch64/codegen/CallSnippet.cpp, runtime/compiler/aarch64/runtime/Recomp.cpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/env/J2IThunk.cpp, runtime/compiler/runtime/ClassUnloadAssumption.cpp, runtime/compiler/runtime/J9CodeCache.cpp, runtime/compiler/runtime/RelocationRecord.cpp, runtime/compiler/runtime/RelocationRuntime.cpp, runtime/compiler/runtime/Trampoline.cpp, runtime/jcl/common/jdk_internal_foreign_abi_UpcallStubs.cpp, runtime/vm/UpcallThunkMem.cpp, runtime/vm/jvminit.c, runtime/vm/xr64/UpcallThunkGen.cpp
This commit rewrites API calls to `pthread_jit_write_protect_np()` for AArch64 macOS by `omrthread_jit_write_protect_disable/enable()` introduced by https://github.com/eclipse/omr/pull/6857.
=> Rewrite pthread_jit_write_protect_np()

buildenv/jenkins/variables/defaults.yml
CRIU testing does not run on cent6. We can still
run jdk8 on cent6 since there is no CRIU support
for 8 for the foreseeable future.
=> Don't run jdk11 xlinux testing on cent6

runtime/compiler/env/J9ObjectModel.cpp, runtime/compiler/env/J9ObjectModel.hpp, runtime/compiler/ilgen/Walker.cpp, runtime/compiler/optimizer/J9ValuePropagation.cpp, runtime/compiler/optimizer/J9ValuePropagation.hpp, test/functional/Valhalla/playlist.xml, test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeArrayTests.java
If the array constraint has a hint type, aaload and aastore helper calls can be transformed with a guard that checks if the array type is the hint type in runtime. If it is not, the slow path still calls the helper.
- If the type hint class is VT and it is flattened, transform the helper call with a guard to sym ref access on the fast path
- If the type hint class is VT and it is NOT flattened, transform the helper call with a guard to regular aaload/aastore on the fast path
- If the type hint class is identity class, transform the helper call with a guard to regular aaload/aastore on the fast path
Also add functional tests
- Test interface array and the interface has an single implementer
- Update the array tests with `initialOptLevel=warm` to have better test coverage on JIT'd methods.
=> Transform array element load and store using type hint

runtime/compiler/env/J9KnownObjectTable.cpp, runtime/compiler/env/J9KnownObjectTable.hpp, runtime/compiler/optimizer/J9TransformUtil.cpp, runtime/compiler/optimizer/J9TransformUtil.hpp
- derive array dimension from the signature
- create known object with a stable array rank that is equal to array's dimension
- when dereferencing stable array, create a known object that is stable array with rank-1 (unless new rank is 0).
=> Handle multi-dimensional stable arrays

runtime/compiler/runtime/Runtime.cpp
This commit enables fast_jitInstanceOf helper on AArch64.
=> AArch64: Enable fast_jitInstanceOf

runtime/bcverify/rtverify.c
The change is to update the top index of the live stack to ensure it is used correctly to compute the number of elements on 'stack' in generating the detailed error messages.
Fixes: #16523
=> Update the top index of the live stack in Verifier

jcl/src/java.base/share/classes/java/lang/String.java
If compact strings is enabled and the regex and searched strings compression differs, then accessing the backing array of the regex string will be done using the searched string's compression level. This gets us bogus values, and leads to erroneous non match when the regex string is compressed and searched string is not.
Thus we decompress the regex string in this case.
Fixes root cause of test failures mentioned in https://github.com/eclipse-openj9/openj9/pull/16452#issuecomment-1349617176
fyi @pshipton @dchopra001
=> Fix String.split when regex is compressed and searched string is not

runtime/gc_base/GCExtensions.cpp, runtime/gc_base/GCExtensions.hpp, runtime/gc_glue_java/CompactSchemeFixupObject.cpp, runtime/gc_glue_java/HeapWalkerDelegate.cpp, runtime/gc_glue_java/MarkingDelegate.cpp, runtime/gc_glue_java/MetronomeDelegate.cpp, runtime/gc_glue_java/ScavengerDelegate.cpp, runtime/gc_vlhgc/CopyForwardScheme.cpp, runtime/gc_vlhgc/GlobalMarkCardScrubber.cpp, runtime/gc_vlhgc/GlobalMarkingScheme.cpp, runtime/gc_vlhgc/WriteOnceCompactor.cpp, runtime/oti/VMHelpers.hpp
There is no need to scan any continuation Objects, which are marked finished, plus there could be potential race condition between continuation concurrent scan and continuation free up for finished Continuation Object.
fix:https://github.com/eclipse-openj9/openj9/issues/15939#issuecomment-1331427527
=> Avoid to scan the finished Continuation Object

runtime/compiler/optimizer/EscapeAnalysis.cpp
Flow Sensitive Escape Analysis will mark an `allocationFence` with `omitSync` set to true if it was needed by a single allocation that ended up being stack allocated.
On a subsequent pass of Escape Analysis, Local Flush Elimination might decide an `allocationFence` is needed at the same spot for another object allocation.  An assertion in `TR_LocalFlushElimination::examineNode` expects any existing `allocationFence` that it finds to have its `omitSync` set to false, which didn't account for the possibility that it might find one that had previously been disabled.
Fixed the problem by removing the assertion and allowing the `allocationFence` to be reactivated for the second object allocation.
Also added more information to some trace messages.
=> Allow allocationFence to be reenabled by Local Flush Elimination

runtime/criusupport/module.xml, runtime/vm/CRIUHelpers.cpp
The `clazz` field of a `J9Object` isn't generally wide enough to properly capture an object pointer: use `j9object_t` instead. This issue was highlighted by a couple of cast errors in builds configured using `--with-mixedrefs=no`:
```
CRIUHelpers.cpp:195:52: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
CRIUHelpers.cpp:334:44: error: cast from 'j9object_t {aka J9Object*}' to 'j9objectclass_t {aka unsigned int}' loses precision [-fpermissive]
```
Also add missing include directory required in UMA builds.
=> CRIU: correct type of pool elements in instanceObjects

runtime/compiler/optimizer/J9CallGraph.hpp, runtime/compiler/optimizer/J9Inliner.cpp
In f544293aaa4c38ef `findCallSiteTarget()` was updated to ensure that the interface is found before attempting `findCallSiteTargetImpl()`. This is necessary because `getClassFromMethod()` can return null in AOT. However, the resulting interface was used only for assertions that run after successfully finding a target, and `findCallSiteTargetImpl()` would repeat `getClassFromMethod()` to find the interface again, creating a second opportunity to fail and get null in AOT.
With this commit, the interface obtained by `findCallSiteTarget()` is now reused when actually selecting a target, since it's known to be non-null by the time we reach `findCallSiteTargetImpl()`.
Fixes #16400 (again)
=> Look for interface call targets using the known non-null interface

runtime/compiler/env/j9method.cpp
Early prototype handling of value type classes used `<init>` as a special factory method name distinct from its use as an instance initialization method name.  That has been dropped in favor of `<vnew>` as a factory method name for value type classes.  This change removes the special treatment of `<init>` as a value type factory method name from `TR_ResolvedJ9Method::isConstructor`.
Fixes #14959
=> Remove special treatment of <init> for value types

runtime/compiler/z/codegen/J9CodeGenerator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.hpp
Accelerate `CRC32C.updateBytes` and `CRC32C.updateDirectByteBuffers` recognized methods by inlining them with a vector assembly sequence.
The implementation is based on the bit-reflected algorithm described in Intel's whitepaper *"Fast CRC Computation for Generic Polynomials Using `PCLMULQDQ` Instruction"* [1] using equivalent Z instructions. The basic layout of the implementation is as follows:
- While there are more than 64B of data remaining, consume 64B chunks using 4 vectors in parallel, then
- while there are more than 16B of data remaining, consume 16B chunks using 1 vector, then
- if there is remaining data, call the original implementation on the remainder
Preliminary benchmarking shows approximately 22× speedup for 4kB and 16kB byte arrays, and no significant speedup or slowdown …
=> Accelerate CRC-32C calculation on Z

runtime/compiler/optimizer/EscapeAnalysis.cpp
Flow Sensitive Escape Analysis will mark an `allocationFence` with `omitSync` set to true if it was needed by a single allocation that ended up being stack allocated.
On a subsequent pass of Escape Analysis, Local Flush Elimination might decide an `allocationFence` is needed at the same spot for another object allocation.  An assertion in `TR_LocalFlushElimination::examineNode` expects any existing `allocationFence` that it finds to have its `omitSync` set to false, which didn't account for the possibility that it might find one that had previously been disabled.
Fixed the problem by removing the assertion and allowing the `allocationFence` to be reactivated for the second object allocation.
Also added more information to some trace messages.
This pull request delivers the change from …
=> [0.36.0] Allow allocationFence to be reenabled by Local Flush Elimination

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp, runtime/compiler/aarch64/codegen/J9CodeGenerator.hpp, runtime/compiler/runtime/Runtime.cpp
This commit enables fast_jitCheckAssignable helper on AArch64.
=> AArch64: Enable fast_jitCheckAssignable

runtime/gc_glue_java/ScavengerBackOutScanner.cpp
Fix backoutContinuationObjects missing to handle tenure region for ScavengerBackOut case.
fix: https://github.com/eclipse-openj9/openj9/issues/16538
=> Fix ContinuationObjectList ScavengerBackOut issue

doc/release-notes/0.36/0.36.md
https://github.com/eclipse-openj9/openj9-docs/issues/1037
Updated the release notes with the information related to deprecating of the support for running JDK 8 and 11 on CentOS 6.10
[skip ci]
=> Deprecate support for running JDK 8 and 11 on CentOS 6

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp, runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp, runtime/compiler/aarch64/env/J9CPU.cpp
Accelerate `CRC32C.updateBytes` and `CRC32C.updateDirectByteBuffers` recognized methods by inlining them with CRC32C instruction families if FEAT_CRC32 extension (which is mandatory for Armv8.1 or later) is available.
=> AArch64: Accelerate CRC-32C calculation

LICENSE, longabout.html
See also the 2022 update https://github.com/eclipse-openj9/openj9/commit/6504162f
=> Update top level OpenJ9 and OMR copyright to 2023

runtime/include/ibmjvmti.h, runtime/jvmti/j9jvmti.tdf, runtime/jvmti/jvmtiExtensionMechanism.c, runtime/nls/j9ti/jvmti.nls
The following JVMTI extension functions are implemented:
- **GetVirtualThread**: Gets the virtual thread corresponding to a
carrier thread.
- **GetCarrierThread**: Gets the carrier thread corresponding to a
virtual thread.
Related: #16168
Related: #16203
=> JVMTI Extension Functions: GetVirtualThread and GetCarrierThread

runtime/tests/shared/SharedCacheAPITest.cpp
This commit rewrites getCacheDir() in SharedCacheAPITest.cpp for
eliminating sprintf().
=> Stop using sprintf() in SharedCacheAPITest.cpp

runtime/gc_glue_java/ScavengerDelegate.cpp
Concurrent Scavenger use SCAN_REASON_SHOULDREMEMBER scanning for rememberedSet prune phase, fix continuation stackslot scanning issue for rememberedSet prune phase to avoid the remembered flag has been overwritten to reset.
we should break the stack walking after seeing this first time the flag being set to true, but it's not in our control since the iteration loop is in the stack walker. the related enhancement could be done in future release.
fix:https://github.com/eclipse-openj9/openj9/issues/16434
=> Fix continuation stackslot scanning issue in Concurrent Scavenger

runtime/compiler/control/CompilationRuntime.hpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/CompilationThread.hpp, runtime/compiler/env/j9method.cpp, runtime/compiler/env/j9method.h
TR_ResolvedRelocatableJ9Method::isCompilable should match what TR::CompilationInfoPerThreadBase::isMethodIneligibleForAot returns for a method. This override is necessary because methods in java/lang/invoke/* are marked ineligible from AOT compilations, and therefore isCompilable should also return false for these methods during AOT. This impacts what methods are considered for inlining.
Fixes: #16161, #14135
=> Override isCompilable for TR_ResolveRelocatableJ9Method

runtime/compiler/control/DLLMain.cpp, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/J9Options.hpp, runtime/compiler/runtime/MetaData.cpp, runtime/compiler/runtime/RelocationRuntime.cpp, runtime/oti/j9nonbuilder.h
Options passed to the JVM are consumed by the JIT in different places and at different points during the bootstrap process. However, often the string literals that are used for the comparison are scattered across various locations. This is particularly problematic for something like the CRIU feature where we may need to process options post restore.
This PR gathers all the string literals and puts them in an array. The reason for doing this, rather than just have them be a bunch of `#define`s in a header file, is so that for the CRIU feature post restore options processing, we can just iterate over the array and explicitly decide what we want to do with the option.
This PR introduces a new enum class called `TR::ExternalOptions`, wherein each enum value has a 1-1 mapping with the string …
=> Initial CRIU serviceability infrastructure

test/functional/JIT_Test/playlist.xml, test/functional/JIT_Test/src/jit/test/jitserver/JITServerTest.java
The JITServer AOT cache is currently not covered by the tests. Additional tests are added in the JITServer test suite testJITServer.
-The JITServer and the clients are run with an additional variation with JVM options for using shared class named test_jitscc and the AOT option JITServerUseAOTCache.
-An additional test in the test suite does actions like destroying the cache, recreating it and reusing it.
Issue: #15401
=> WIP:JITServer AOT cache testing

buildenv/jenkins/variables/defaults.yml
The RH8 machines are z15, the combination supports zlib hardware
compression/decompression. jdk11 currently fails pack200 testing in
sanity.openjdk due to zlib hardware compression/decompression, which we
are working to resolve in the future. jdk11+ fails java/util/zip/CloseInflaterDeflaterTest.java in jdk_util.
This change allows jdk8 to test on the RH8/z15 machines when
the ci.role.test label is added to the machines.
jdk8 uses a bundled zlib that doesn't support hardware
compressions/decompression, and doesn't run pack200 testing in
sanity.openjdk. Note pack200 was removed in jdk14.
Issue https://github.com/eclipse-openj9/openj9/issues/14948
See also https://github.com/eclipse-openj9/openj9/issues/16037
Testing sanity.openjdk
jdk8 …
=> Temporarily avoid zlinux jdk11+ testing on RH8

buildenv/jenkins/variables/defaults.yml
Reverts eclipse-openj9/openj9#16596
See https://github.com/eclipse-openj9/openj9/pull/16596#issuecomment-1401302242
=> Revert "Temporarily avoid zlinux jdk11+ testing on RH8"

test/functional/Java17andUp/playlist.xml, test/functional/Java19andUp/playlist.xml
The change is to enable the remaining FFI test suites which are still disabled
to have them executed on all supported platform given the issue with OpenJDK
MH.invokeBasic() was resovled in JIT via #14483.
=> [Test/FFI] Enable the FFI test suites in JDK17/19

test/functional/Java17andUp/src_170/org/openj9/test/jep389/upcall/UpcallMHWithMixedSigStruTests.java, test/functional/Java17andUp/src_170/org/openj9/test/jep389/upcall/UpcallMethodHandles.java, test/functional/Java19andUp/src/org/openj9/test/jep424/upcall/UpcallMHWithMixedSigStruTests.java, test/functional/Java19andUp/src/org/openj9/test/jep424/upcall/UpcallMethodHandles.java
The change is to change the alignment for the long type in the case of
the [int, double, long] struct on AIX as it proves to work in JDK19.
Fixes: #16561
=> [Test/FFI] Change the alignment of long in JDK17

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp, runtime/compiler/il/J9Node.cpp
Accelerate `CRC32.update`,  `CRC32.updateBytes` and `CRC32.updateByteBuffers` recognized methods in addition to CRC32C methods.
This acceleration shows ~6.5x speedup compared to the existing implementation using zlib on Linux. However, the zlib implementation is faster on Apple Silicon Mac as described in https://github.com/eclipse-openj9/openj9/issues/16584. Thus, this acceleration is disabled on Mac.
=> AArch64: Accelerate CRC-32 calculation

runtime/compiler/p/codegen/PPCPrivateLinkage.cpp, runtime/compiler/runtime/Runtime.cpp
CRC32C accelerated method was implemented in Power recently and this is in continuation with those changes which will enable accelerated crc32c method to be relocatable. This will enable the method to be called in both AOT and JIT modes. 
Signed-off-by: Bhavani S N [bhavani.sn@ibm.com]
=> Add helper function to create relocatable crc32c method

runtime/compiler/runtime/JITServerAOTCache.cpp, runtime/compiler/runtime/JITServerAOTCache.hpp, runtime/compiler/runtime/JITServerAOTSerializationRecords.hpp
These commits start to address #16482 by defining the basic thunk serialization types and adding them to the persistence framework. They also clean up the existing code very slightly. Once this is merged I can work on the next parts of the implementation (modifying record deserialization at the client to handle thunks and handling thunk caching/tracking during compilation at the server).
Attn @mpirvu.
=> Defining JITServer AOT cache thunks

runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp
Add comment explaining that writting 1 to MSB of M_4 supresses HW
overflow program interrupt.
=> Improve readability of pd shift vector evaluators

buildenv/jenkins/variables/defaults.yml
Since AIX 7.1 is EOL in April.
Doc issue https://github.com/eclipse-openj9/openj9-docs/issues/1043
=> Build AIX on AIX 7.2

runtime/jvmti/jvmtiClass.c
=> Only call fixHiddenOrAnonSignature in Java 17+

runtime/oti/j9nonbuilder.h, runtime/vm/CRIUHelpers.hpp, runtime/vm/jvminit.c, runtime/vm/vmthinit.c, runtime/vm/vmthread.cpp
Handle GC thread shutdown during checkpoint
Add synchronzation to the delayedLockingOperations path to handle the
case where the GC is shutting down its threads simulatneously.
=> Handle GC thread shutdown during checkpoint

runtime/compiler/control/HookedByTheJit.cpp, runtime/oti/j9nonbuilder.h, runtime/oti/vm_api.h, runtime/vm/ContinuationHelpers.cpp, runtime/vm/ContinuationHelpers.hpp, runtime/vm/intfunc.c
=> Support continuation stack in JIT code cache release

jcl/jpp_configuration.xml
This will eventually be required by https://github.com/ibmruntimes/openj9-openjdk-jdk.
=> Add preprocessor configuration for Java 21

jcl/src/java.base/share/classes/java/lang/Thread.java
There is no API that makes the name `null`, remove the needless use of `String.valueOf()`.
=> Simplify access to Thread name

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/AttachHandler.java, jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/Attachment.java, jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/WaitLoop.java, jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/MemoryNotificationThreadShutdown.java, jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/image/j9/BuilderShutdownHook.java, test/functional/cmdLineTests/cmdLineTest_J9tests/j9tests_firstThreadName.xml, test/functional/cmdLineTests/cmdLineTest_J9tests/playlist.xml, test/functional/cmdLineTests/cmdLineTest_J9tests/src/ThreadName.java
This avoids having a default name created.
Fixes https://github.com/eclipse-openj9/openj9/issues/16621
Built in https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/333/
Tested in https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1903 - passed
Also ran the test on a build without the fix, which failed.
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1904
=> Initialize thread names in thread constructors, don't call setName()

runtime/compiler/x/env/J9CPU.cpp
=> x86: Enable SSE 4.2 for vector compares

test/functional/Java17andUp/src_170/org/openj9/test/jep389/upcall/UpcallMHWithStructTests.java, test/functional/Java17andUp/src_170/org/openj9/test/jep389/upcall/UpcallMethodHandles.java, test/functional/Java19andUp/src/org/openj9/test/jep424/upcall/UpcallMHWithStructTests.java
The changes follow the same rules on the struct-based test cases on Windows & zLinux,
in which case the struct padding is not required in upcall. In addition to that, part of test
cases in JDK17 are updated to remove the unused test code in upcall.
Fixes: #16619
=> [Test/FFI] Remove the struct padding on Windows & zLinux

runtime/compiler/z/codegen/J9TreeEvaluator.cpp
The first branch to OOL of the acceleration implementation and the merge point from OOL were not included in the ICF, and the correct dependencies were not attached to the merge point. This opened up the possibility of register spills being inserted that would be missed if the first branch to OOL is taken. This patch resolves this issue by extending the ICF from the first branch to OOL to the merge point and moving all the dependencies to the merge point.
Fixes: #16560
Signed-off-by: Spencer Comin <spencer.comin@ibm.com>
=> Fix ICF and register dependencies in CRC-32C acceleration on Z

jcl/src/java.base/share/classes/java/lang/System.java, test/functional/cmdLineTests/cmdLineTest_J9tests/j9tests_consoleUpTo17.xml, test/functional/cmdLineTests/cmdLineTest_J9tests/src/DefaultCharset.java
Calling Charset.defaultEncoding() at startup initializes the default encoding before the jdk.charsets module is loaded.
There is no need to initialize the encoder on jdk11, the JVM starts up without it even when file.encoding is set to an invalid value.
Also set the fallback console Charset on jdk18+ to UTF8 instead of ASCII, since UTF8 is the default.
Fixes https://github.com/eclipse-openj9/openj9/issues/16586
Originally tested by https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/331/
Verified the added test using the previous build.
jdk8 https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1876
jdk11 https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1875
jdk17 https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1878
=> On jdk11+ don't call Charset.defaultEncoding() at startup

test/functional/cmdLineTests/cmdLineTest_J9tests/playlist.xml
cmdLineTest_J9test_firstThreadName not for openjdk, -Xdump is only for openj9
Fixes: #16641
Signed-off-by: sendaoYan <yansendao.ysd@alibaba-inc.com>
=> cmdLineTest_J9test_firstThreadName not for openjdk

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java, runtime/criusupport/CMakeLists.txt, runtime/criusupport/criusupport.cpp, runtime/criusupport/criusupport.hpp, runtime/criusupport/module.xml, runtime/nls/j9cl/j9jcl.nls, runtime/oti/j9nonbuilder.h, runtime/oti/vm_api.h, runtime/vm/jvminit.c, test/functional/cmdLineTests/criu/criu_nonPortable.xml, test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java
Restore options file and vm support
Introduce options file to provide the ability to supply cmdline options on restore. Initially only properties will be supported. Further support for JVM options will be added later.
=> Restore options file and vm support

runtime/codert_vm/thunkcrt.c, runtime/compiler/env/VMJ9.cpp, runtime/compiler/runtime/RelocationRecord.cpp, runtime/oti/jitprotos.h
In a non-AOT compilation, the JIT generates J2I Thunks and stores them into a VM Hash Table using the `j9ThunkNewSignature` API; it looks up existing thunks using the `j9ThunkLookupSignature` API. In an AOT compilation, the JIT does not uses these APIs, but rather simply stores the Thunks into the SCC using the signature of the method as the key.
The VM API will share the thunks for two different methods if all of the following is true:
1. They have the same return type
2. They have the same primitive type arguments
Therefore, if two methods have different object types, they can still use the same thunk. For example, `foo(IILMyObject;)V` and `bar(IILMyOtherObject;)V` can share the same thunk, but `baz(ILMyObject;I)V` cannot.
Because AOT compiles only used the signature of the method as …
=> Use VM criteria for J2I Thunk Sharing in AOT Compiles

runtime/compiler/control/CompilationRuntime.hpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/HookedByTheJit.cpp, runtime/compiler/control/rossa.cpp
This PR facilitates options processing post restore, specifically wrt to the number of compilation threads. In order to allow a user to change the number of compilation threads post restore, the JIT will likely have to create a set number of threads and then choose how many to actually allow to be activated.
However, because the current assumption is that the diagnostic thread ID is one more than the number of compilation threads, it complicates the code when taking into account that the number of compilation threads could change. Therefore, in this PR, the code is updated to use thread ID ranges rather than simply assuming the thread ID starts at 0 and goes up to the number of compilation threads.
=> Use ranges for compilation thread IDs

doc/release-notes/0.36/0.36.md
https://github.com/eclipse-openj9/openj9-docs/issues/1042
Updated information regarding 0.36.1 release.
[skip ci]
=> Update release notes 0.36.0

test/functional/cmdLineTests/criu/criu_nonPortable.xml
Make CRIU tests more resilient to OS failures
Fixes: https://github.com/eclipse-openj9/openj9/issues/16610
=> Make CRIU tests more resilient to OS failures

jcl/src/java.base/share/classes/java/lang/Access.java, jcl/src/java.base/share/classes/java/lang/System.java, jcl/src/java.base/share/classes/jdk/internal/foreign/abi/DowncallLinker.java, jcl/src/java.base/share/classes/jdk/internal/foreign/abi/UpcallLinker.java, jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java, jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalUpcallHandler.java, jcl/src/java.base/share/classes/openj9/internal/foreign/abi/LayoutStrPreprocessor.java, jcl/src/java.base/share/classes/openj9/internal/foreign/abi/UpcallMHMetaData.java, runtime/jcl/common/thread.cpp, runtime/jcl/exports.cmake, runtime/jcl/module.xml, runtime/jcl/uma/se20_exports.xml, test/functional/Java19andUp/build.xml, test/functional/Java19andUp/playlist.xml
The change is to update all FFI & `java.lang.Access` related java code in JDK20
for the moment to get them compiled as we have been working on the changes
to address the  latest APIs intended for JEP434 in JDK20 as follows:
Commit 1: JDK20 java.lang.Access new API
1) added `Access.in()` to support `Access.initialSystemIn()`
2) added the stub implementation of `Java_java_lang_Thread_ensureMaterializedForStackWalk`
Commit 2: Disable FFI related code for JDK20
=> Update FFI & Access related code in OpenJ9 for compilation in JDK20

jcl/src/java.base/share/classes/java/lang/Access.java, jcl/src/java.base/share/classes/java/lang/System.java, runtime/jcl/common/thread.cpp, runtime/jcl/exports.cmake, runtime/jcl/module.xml, runtime/jcl/uma/se20_exports.xml
JDK20 `java.lang.Access` new APIs
Also add `Access.in` to support `Access.initialSystemIn()`;
Added stub implementation of `Java_java_lang_Thread_ensureMaterializedForStackWalk`.
=> JDK20 java.lang.Access new APIs

runtime/compiler/optimizer/VectorAPIExpansion.cpp, runtime/compiler/optimizer/VectorAPIExpansion.hpp
Re-enable `blendIntrinsicHandler()` and generate `vbitselect` IL opcode when vector blend() operation is vectorized.
=> Enable vectorized blend() IL opcode

runtime/jvmti/jvmtiThread.c
(jthread)&walkVirtualThread is not a JNI ref, and it will not be
updated by the GC when VM access is released in
suspendhelper.cpp::suspendThread.
Now, JNI refs are used to pass virtual thread objects during JVMTI
suspend. This assures that the GC updates them.
Related: #16593
=> Use JNI refs for virtual thread objects during JVMTI suspend

doc/release-notes/0.36/0.36.md
https://github.com/eclipse-openj9/openj9-docs/issues/1047
Updated the release notes
[skip ci]
=> Updated 0.36.0 release note with OpenSSL memory leak limitation

runtime/compiler/optimizer/EscapeAnalysis.cpp, runtime/compiler/optimizer/EscapeAnalysis.hpp
This pull request contains two enhancements for investigation of the run time performance impact of Escape Analysis:
1. Check the setting of the `suppressEA` option to decide whether a particular candidate for stack allocation should be prevented from being stack allocated.  This can help test the effect on performance of individual opportunities for stack allocation.
2. Added dynamic debug counters to gauge the number of contiguous and non-contiguous stack allocation opportunities that were found.
There are also a number of minor clean-up items:
1. There are two `findIgnoreableUses` methods, one of which finds uses that can be ignored, the other which marks them as ignorable.  Renamed the second to `markUsesAsIgnorable` for clarity.  Also corrected the spelling of "ignorable."
2. Fixed …
=> Minor enhancements for performance investigation of Escape Analysis

runtime/vm/ContinuationHelpers.cpp
Temporary `J9VMThread`s are created to present `J9VMContinuation` thread data to the stackwalker.  Explicitly disable the JIT artifact cache on the temporary thread otherwise the stack walker will allocate a new 4K buffer for each temporary `J9VMThread` whose memory must be managed.
These threads exist to perform a single stack walk and the benefits of managing and using a JIT artifact cache appear to be limited.
Fixes: #16424
=> Disable JIT artifact cache for temporary J9VMThreads

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
The changes remove the restriction for any session regardless of the session's type
to ensure the memory of upcall stub is kept alive during the downcall.
Fixes: #16606
=> [FFI] Remove the restriction on all sessions in downcall

test/functional/cmdLineTests/criu/criu_nonPortable.xml
Fix CRIU test condition
Method deadlock test can output "Checkpoint blocked because thread" because thats the tracepoint printed when the checkpoint thread is waiting other threads to exit critical regions
=> Fix CRIU test condition

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp, runtime/compiler/codegen/J9CodeGenerator.cpp, runtime/compiler/codegen/J9CodeGenerator.hpp, runtime/compiler/p/codegen/J9TreeEvaluator.cpp, runtime/compiler/p/codegen/J9UnresolvedDataSnippet.cpp, runtime/compiler/runtime/RelocationRecord.cpp, runtime/compiler/x/codegen/J9TreeEvaluator.cpp, runtime/compiler/x/i386/codegen/IA32PrivateLinkage.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp
These were introduced a long time ago to allow a certain change to be toggled. The change was to stop generating runtime assumptions for patching class pointers on class redefinition, and to stop generating slower but more easily patchable instruction sequences to allow for those runtime assumptions. The patching was no longer needed because class redefinition had been made in-place.
As a result, `wantToPatchClassPointer()` and `hcrPatchClassPointers` are no longer necessary. They are removed, and all use sites now behave as though `hcrPatchClassPointers` is not set and `wantToPatchClassPointer()` returns false.
=> Remove wantToPatchClassPointer() and the hcrPatchClassPointers option

.copyrightignore, CODE_OF_CONDUCT.md
A copy of https://raw.githubusercontent.com/eclipse/.github/master/CODE_OF_CONDUCT.md
See the web version https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php
Similar to [the PR](https://github.com/eclipse-openj9/openj9/pull/13637) for the original code of conduct , we're asking all committers, and contributors, to approve, indicating they have read the updated code of conduct and approve the change. We're not looking for feedback on the wording, which is copied from the Eclipse Foundation.
=> Update the Eclipse code of conduct to version 2

buildenv/jenkins/common/build.groovy
Binaries help in analyzing the core file to debug the crash.
=> Collect binaries when the JVM crashes during a Jenkins build

runtime/compiler/aarch64/codegen/CallSnippet.cpp, runtime/compiler/aarch64/codegen/CallSnippet.hpp, runtime/compiler/arm/codegen/CallSnippet.cpp, runtime/compiler/arm/codegen/CallSnippet.hpp, runtime/compiler/control/HookedByTheJit.cpp, runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/control/rossa.cpp, runtime/compiler/env/J2IThunk.cpp, runtime/compiler/env/J2IThunk.hpp, runtime/compiler/env/J9PersistentInfo.hpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/env/VMJ9Server.cpp, runtime/compiler/env/VMJ9Server.hpp, runtime/compiler/p/codegen/CallSnippet.cpp, runtime/compiler/p/codegen/CallSnippet.hpp, runtime/compiler/p/codegen/PPCPrivateLinkage.cpp, runtime/compiler/runtime/JitRuntime.cpp, runtime/compiler/runtime/RelocationTarget.cpp, runtime/compiler/runtime/RelocationTarget.hpp, runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp, runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.hpp, runtime/compiler/x/codegen/X86PrivateLinkage.cpp, runtime/compiler/x/codegen/X86PrivateLinkage.hpp, runtime/compiler/x/runtime/X86RelocationTarget.cpp, runtime/compiler/x/runtime/X86RelocationTarget.hpp, runtime/compiler/z/codegen/S390J9CallSnippet.cpp, runtime/compiler/z/codegen/S390J9CallSnippet.hpp, runtime/compiler/z/codegen/S390PrivateLinkage.cpp
There are two types of J2I thunks the JIT generates; thunks for normal J2I transitions, and thunks for invokeExact J2I transitions. Thunks of the former kind are stored in a hashtable maintained in the VM whereas thunks of the latter kind are stored in a table maintained by the JIT. However, both thunks are referred to as "J2I Thunks", which, while technically correct, can be very confusing to a reader of the code.
This PR renames `TR_J2IThunk` (which was the data structure to describe invokeExact J2I Thunks) to `TR_MHJ2IThunk`. It also updates frontend queries to refer to invokeExact J2I thunks as MH J2I Thunks.
=> MH J2I Thunk API Nomenclature Clarification

runtime/jcl/common/system.c, runtime/vm/jvminit.c
Fixes https://github.com/eclipse-openj9/openj9/issues/16637
java -XX:+PrintFlagsFinal
```
[Global flags]
size_t MaxHeapSize                              = 2083651584                                {product} {ergonomic}
uint64_t MaxDirectMemorySize                      = 0                                         {product} {ergonomic}
```
=> Show 0 for MaxDirectMemorySize with PrintFlagsFinal when unset

test/functional/Java8andUp/src/org/openj9/test/attachAPI/AttachApiTest.java, test/functional/Java8andUp/src/org/openj9/test/attachAPI/TestJps.java
Replaced `runCommand` with `runCommandAndLogOutput` within `TestJps`; 
Changed `AttachApiTest` log level from `debug` to info.
Related https://github.com/eclipse-openj9/openj9/issues/11509
=> Add AttachAPI AttachApiTest info

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/MachoDumpReader.java
That list will be empty until stack walking is implemented.
Tested with the core file mentioned in #16674.
Fixes: #16674.
=> Return non-null list of stack frames

doc/compiler/jitserver/Problem.md
Add descriptions for new debugging options added to JITServer
=> Update JITServer problem determination documentation

runtime/gc_base/ObjectAccessBarrier.cpp, runtime/gc_base/ObjectAccessBarrier.hpp, runtime/gc_modron_standard/StandardAccessBarrier.hpp, runtime/gc_realtime/ConfigurationRealtime.cpp, runtime/gc_realtime/ConfigurationRealtime.hpp, runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp, runtime/gc_vlhgc/ConfigurationIncrementalGenerational.hpp
Current place of MM_Scavenger instantiation is
MM_ConfigurationGenerational::createDefaultMemorySpace(). It is relatively late in initialization path without any reason. Late creation required to have "Scavenger registration" in the classes created earlier. Moving Scavenger instantiation to
MM_ConfigurationGenerational::createGlobalCollector() makes more sense and resolves registration problem naturally. Method createGlobalCollector() is going to be renamed to createCollectors() to reflect the fact it might create not only Global, but Local collector too if necessary.
There is first step of refactoring:
- add _scavenger field initialization to Constructor of MM_StandardAccessBarrier
- move _extensions and _heap fields initialization to Constructor of MM_ObjectaccessBarrier
- duplicate …
=> Prepare to move Scavenger creation to createGlobalCollector()

runtime/compiler/env/VMJ9Server.cpp
The client thunk pointer should be returned from setJ2IThunk at the JITServer, not the (heap-allocated) server thunk pointer.
Attn @mpirvu. This fixes an issue that came up while testing #16650.
=> Fix JITServer thunk pointer handling issue

test/functional/JIT_Test/playlist.xml, test/functional/JIT_Test/src/jit/test/recognizedMethod/TestJavaUtilZipCRC32C.java, test/functional/JIT_Test/testng.xml
Test for correctness in accelerated CRC-32C calculation recently implemented for Z https://github.com/eclipse-openj9/openj9/pull/16379.
=> Add unit test for accelerated CRC32C.update on Z

runtime/gc/gctable.c, runtime/gc_base/gc_internal.h, runtime/gc_base/modronapi.cpp, runtime/gc_glue_java/ConfigurationDelegate.hpp, runtime/gc_glue_java/GlobalCollectorDelegate.cpp, runtime/gc_modron_startup/mminit.cpp, runtime/oti/j9nonbuilder.h
Initial set of changes to expand the GC thread pool beyond the dispatcher initialization done at VM startup. These changes are required by the consumed OMR GC dispatcher/configuration APIs called for restore.
- Converted reference obj list iteration count from `gcThreadCount` to `regionExtension->_maxListIndex`, this is more correct. This is the only instance in the code where iteration implies the listCount from GC thread count. This inference was not an issue as the lists are inited based on the GC thread count, however now that the thread count may change, it is incorrect to assume the list count from the thread count.
- Release restore thread's VM access for the duration of `reinitializeGCThreadCountForRestore`
- Introduced `j9gc_reinitializeDefaults` in `mminit`, this is meant to be …
=> Unbounded GC Thread Pool Expansion for CRIU Restore

buildenv/jenkins/variables/defaults.yml
The RH8 machines are z15, the combination supports zlib hardware compression/decompression. jdk11 currently fails pack200 testing in sanity.openjdk due to zlib hardware compression/decompression, which we are working to resolve in the future. jdk11+ fails java/util/zip/CloseInflaterDeflaterTest.java in jdk_util.
This change allows jdk8 to test on the RH8/z15 machines when the ci.role.test label is added to the machines.
jdk8 uses a bundled zlib that doesn't support hardware compressions/decompression, and doesn't run pack200 testing in sanity.openjdk. Note pack200 was removed in jdk14.
Issue https://github.com/eclipse-openj9/openj9/issues/14948
See also https://github.com/eclipse-openj9/openj9/issues/16037
Previous attempt was https://github.com/eclipse-openj9/openj9/pull/16596
=> Temporarily avoid zlinux jdk11+ testing on RH8 (2nd try)

runtime/gc_base/GCExtensions.cpp, runtime/gc_base/GCExtensions.hpp, runtime/gc_modron_standard/StandardAccessBarrier.hpp, runtime/gc_modron_startup/mminit.cpp, runtime/gc_realtime/ConfigurationRealtime.cpp, runtime/gc_realtime/ConfigurationRealtime.hpp, runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp, runtime/gc_vlhgc/ConfigurationIncrementalGenerational.hpp
- remove registerScavenger() methods
- remove createGlobalCollector() methods
- call createCollectors() instead of createGlobalCollector()
=> Cleanup after Scavenger instantiation refactoring

runtime/gc_glue_java/ConfigurationDelegate.hpp
Move init of `_maximumDefaultNumberOfGCThreads` field to ctor init list.
Config Delegate's field `_maximumDefaultNumberOfGCThreads` const declaration was removed in.
https://github.com/eclipse-openj9/openj9/pull/16666, init was left with declaration, this resulted in DDR compile errors:
```
[exec] "gc_glue_java/ConfigurationDelegate.hpp", line 67: error: data
member
[exec]           initializer is not allowed
[exec]    uintptr_t _maximumDefaultNumberOfGCThreads = 64;
```
=> Fix DDR Compilation of "gcddrstructs.ic"

buildenv/jenkins/variables/defaults.yml
Issue https://github.com/eclipse-openj9/openj9/issues/16701
Created https://github.com/adoptium/temurin-build/pull/3251 for the Adoptium pipelines.
Doc issue https://github.com/eclipse-openj9/openj9-docs/issues/1055
=> Build jdk19+ Windows with VS 2022

runtime/gc_structs/VMThreadSlotIterator.cpp, runtime/jcl/common/thread.cpp, runtime/jcl/exports.cmake, runtime/jcl/module.xml, runtime/jcl/uma/se19only_exports.xml, runtime/jcl/uma/se20_exports.xml, runtime/oti/j9nonbuilder.h, runtime/vm/vmthread.cpp
In JDK20, `extentLocalCache` is renamed to `scopedValueCache`.
JDK19 and JDK20 changes are completely segregated to avoid
cross-contamination if the implementation differs a lot across
JDK versions.
TODO: `Thread.findScopedValueBindings` needs to be implemented.
This is tracked in #16677.
Related: #16439
Fixes: #16657
=> Support for Scoped Values (JEP 429)

runtime/compiler/compile/J9Compilation.cpp, runtime/compiler/compile/J9Compilation.hpp, runtime/compiler/env/VMJ9Server.cpp, runtime/compiler/env/VMJ9Server.hpp, runtime/compiler/net/CommunicationStream.hpp, runtime/compiler/runtime/JITServerAOTCache.cpp, runtime/compiler/runtime/JITServerAOTCache.hpp, runtime/compiler/runtime/JITServerAOTDeserializer.cpp, runtime/compiler/runtime/JITServerAOTDeserializer.hpp, runtime/compiler/runtime/JITServerAOTSerializationRecords.hpp
These commits add J2I thunk handling to the JITServer AOT cache. The server now tracks any thunks created during the compilation of methods that will be stored in the JITServer AOT cache. These thunks are stored in the cache, and also serialized and sent in the `SerializedAOTMethod` records that are sent to the client. The client will deserialize these thunk records and store the thunks in their local shared class cache as necessary.
=> Implement JITServer AOT cache thunk handling

runtime/gc_modron_standard/StandardAccessBarrier.hpp
This is not functional change:
- add missed declarations for MM_MarkingScheme and MM_Scavenger to MM_StandardAccessBarrier
=> Add missed class declarations to StandardAccessBarrier.hpp

runtime/gc_glue_java/configure_includes/configure_zos_390.mk.ftl
They need to be explicitly set for Java 8 because the defaults were changed by https://github.com/eclipse/omr/pull/6250
With this change
`c89  -I.  -I../../../include -I../../include_core -I../../nls -I../../util/a2e/headers -DJ9ZOS390 -DLONGLONG -D_ALL_SOURCE -D_XOPEN_SOURCE_EXTENDED -D_POSIX_SOURCE -D__STDC_LIMIT_MACROS -DIBM_ATOE -DJ9ZOS39064 -Wc,DLL,EXPORTALL -c -Wc,"SERVICE(j20230215)" -Wc,"ARCH(7)" -O3 -Wc,"TUNE(10)" -Wc,"inline(auto,noreport,600,5000)" -Wl,compat=ZOSV1R13 -Wc,"langlvl(extc99)" -Wc,"xplink,rostring,FLOAT(IEEE,FOLD,AFP),enum(4)" -Wa,goff -Wc,NOANSIALIAS -Wc,"TARGET(zOSV1R13)" -Wc,"convlit(ISO8859-1)" -Wc,lp64 -Wa,"SYSPARM(BIT64)"   -o sysTranslate.o sysTranslate.c`
Before the change:
`c89  -I.  -I../../../include -I../../include_core -I../../nls …
=> Set proper z/OS Java 8 OMR compile options for compatibility and tuning

test/functional/Java19andUp/src/org/openj9/test/jep425/VirtualThreadTests.java
Print out stacktrace if it doesn't match expected.
Closes: #16722 
=> Add verbose output for VirtualThreadTests

test/functional/cmdLineTests/modularityddrtests/modularityddrtests17.xml
Command to get `LOGNAME` copied fom `modularityddrtests11.xml`.
=> Ensure LOGNAME is captured on z/OS

test/functional/TestUtilitiesJ9/src/org/openj9/test/attachAPI/TargetManager.java
Changed `TargetManager` log level from `debug` to `info`.
Related https://github.com/eclipse-openj9/openj9/issues/5450
=> Add AttachAPI TargetManager info

runtime/CMakeLists.txt
Tell newer versions of CMake that we expect the old behavior of CMP0079.
=> CMake: Silence warnings about CMP0079

jcl/src/java.base/share/classes/java/lang/Access.java
`Java 21` adds `JavaLangAccess.getUTF16Char()` & `countPositives()`
Required by https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/531
=> Java 21 adds JavaLangAccess.getUTF16Char() & countPositives()

runtime/compiler/compile/J9SymbolReferenceTable.cpp
This commit fixes the JIT trace output from the following functions:
- J9::SymbolReferenceTable::isFieldClassObject()
- J9::SymbolReferenceTable::isFieldTypeBool()
- J9::SymbolReferenceTable::isStaticTypeBool()
Fixes: #16708
=> Fix output from J9::SymbolReferenceTable functions

sourcetools/CMakeLists.txt, sourcetools/buildj9tools.mk
Otherwise, when building with a Java 20+ bootjdk we get these errors:
```
error: Source option 7 is no longer supported. Use 8 or later.
error: Target option 7 is no longer supported. Use 8 or later.
```
=> Stop using "javac -source 7 -target 7"

jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/plugins/impl/ClassScanner.java
Otherwise the inherited method (inappropriately) throws `UnsupportedOperationException`.
To reproduce, run `jdmpview` from jdk17 on any core file and use this command sequence:
```
> log com.ibm.java.diagnostics.plugins FINE
> plugins reload
```
the result is this:
```
FINE: Scanning path modules/openj9.dtfj in search of plugins
Feb 22, 2023 12:02:30 PM com.ibm.java.diagnostics.utils.plugins.impl.PluginManagerImpl lambda$listClassFiles$1
FINE: Error occurred scanning modules/openj9.dtfj/com/ibm/dtfj/utils/file/ImageSourceType.class
java.lang.UnsupportedOperationException: This feature requires ASM9_EXPERIMENTAL
at java.base/jdk.internal.org.objectweb.asm.ClassVisitor.visitPermittedSubclassExperimental(ClassVisitor.java:299)
at java.base/jdk.internal.org.objectweb.asm.ClassReader.accept(Cla …
```
=> ClassScanner should ignore "PermittedSubclasses" attribute in Java 17

runtime/gc_modron_startup/mminit.cpp
Change order in gcShutdownHeapManagement to match
gcStartupHeapManagement: shutdown GC Threads before Collector
=> Change order in gcShutdownHeapManagement

runtime/gc_modron_startup/mmparseXgcpolicy.cpp, runtime/nls/j9gc/j9modron.nls, test/functional/cmdLineTests/criu/playlist.xml
- Metronome and Balanced GC policies are currently unsupported with CRIU. JVM should report an error if these are specified while CRIU support is enabled. 
- Disable Metronome/Balanced test variants for CRIU tests.
- Add missing optavgpause test variant.
=> Handle Unsupported GC policies with CRIU 

runtime/compiler/build/files/common.mk, runtime/compiler/control/CMakeLists.txt, runtime/compiler/control/DLLMain.cpp, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/J9Options.hpp, runtime/compiler/control/OptionsPostRestore.cpp, runtime/compiler/control/OptionsPostRestore.hpp
This PR adds the initial framework and infrastructure needed to process options post restore.
* Ensure `_postRestoreOptionSets` is initialized
* Add framework to process JIT, JITServer, and externally documented options
* Add framework to compensate options that follow Policy 3 described in https://github.com/eclipse-openj9/openj9/issues/16714
~depends on https://github.com/eclipse/omr/pull/6886~ (merged)
depends on https://github.com/eclipse/omr/pull/6896
=> Initial Post Restore compiler options processing

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java, test/functional/Java19andUp/src/org/openj9/test/jep425/VirtualThreadTests.java
Matching the RI will allow us to run more OpenJDK tests without tweaking
them for our implementation and be better prepared to support
unimplemented/new features in the future.
- Move Continuation.yield state check to new yield0 method
- Update VirtualThreadTests to match impl change
Related: #16215 
=> Refactor Continuation.yield method naming to match RI

buildenv/jenkins/variables/defaults.yml
All builds default to using cmake, so checking for existence of the referenced jar is not helpful.
=> Remove unnecessary freemarker properties

runtime/j9vm/javanextvmi.cpp
While the mutex is held, that pointer is checked on line 356; if it was `NULL`, that changes on line 366. There's no need to check it again on line 372.
=> Remove redundant check that liveVirtualThreadList is non-null

doc/release-notes/0.37/0.37.md
https://github.com/eclipse-openj9/openj9/issues/16772
Created a draft 0.37.0 release note including the support for the com.sun.management.ThreadMXBean interface
[skip ci]
=> Release note 0.37.0-com.sun.management.ThreadMXBean interface

runtime/oti/j9nonbuilder.h, runtime/oti/vm_api.h, runtime/vm/CRIUHelpers.cpp, runtime/vm/CRIUHelpers.hpp, runtime/vm/intfunc.c, runtime/vm/j9vm.tdf, runtime/vm/jvminit.c
This prepares for options reloading via loadRestoreArguments().
=> CRIU internal JVM hook iterates J9Class and its ramMethods

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java, runtime/oti/vmconstantpool.xml, runtime/vm/BytecodeInterpreter.hpp
Continuation.execute is renamed to Continuation.enter.
Matching the RI will allow us to run more OpenJDK tests without
tweaking them for our implementation and be better prepared to
support unimplemented/new features in the future.
Related: #16688
Related: #16751
=> Rename Continuation.execute to match the RI

runtime/vm/jvminit.c
Moved the variable declaration at top of the scope.
Related https://github.com/eclipse-openj9/openj9/pull/16622#discussion_r1120098379
=> Fix variable declaration

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/env/j9method.cpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/optimizer/J9ValuePropagation.cpp
Several java/lang/Class methods, such as Class.isAnonymous, Class.hashCode(), etc. can often be determined at compile time, and is safe to do so if the class is a constant class that is known at compile time. This changeset introduces the following:
* Recognize various Class methods to be folded
* VP transformation that checks if the call can be folded, and obtains the values to replace the call node
=> Evaluate Class methods calls at compile time when possible

runtime/compiler/control/CompilationRuntime.hpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/HookedByTheJit.cpp, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/J9Options.hpp, runtime/compiler/runtime/JITClientSession.cpp
Experiments have shown that the stream of compilations from Java web applications subsides over time (as expected), but it doesn't go down to 0 even after many hours of load. The rare compilations that come after 30-60 minutes of load are very unlikely to improve throughput, and they only consume CPU cycles for no good reason. In a JITServer scenario this behavior has another negative effect: as long as the server continues to receive compilation requests from the client, it will hold on to the client session cache it builds inside. This commit adds some code that measures the "density of compilations" and when this metric shrinks under a threshold, first time compilations will be downgraded from warm to cold optlevel, while cold-->warm recompilations are postponed. Hot/scorching …
=> Downgrade/postpone compilations that are unlikely to improve throughput (0.38.0)

runtime/compiler/z/codegen/J9CodeGenerator.cpp
The CRC-32C acceleration works on the assumption the the array it is working on is contiguous. As arraylets break this assumption, they also break this acceleration.
=> Disable CRC-32C acceleration on Z when arraylets are enabled

runtime/criusupport/criusupport.cpp, runtime/gc_base/gc_internal.h, runtime/gc_base/modronapi.cpp, runtime/gc_modron_startup/mminit.cpp, runtime/gc_modron_startup/mmparse.cpp, runtime/gc_modron_startup/mmparse.h, runtime/nls/j9gc/j9modron.nls, runtime/oti/j9nonbuilder.h
- Now that there are multiple ways for GC restore to fail, the error message is set based on the failing GC component. j9gc_reinitialize_for_restore internally sets error message.
-  Introduced gcParseReconfigurableArguments to handle restore args and extended existing parser api to distinguish the argArray to parse.
- Added J9NLS_GC_FAILED_TO_REINITIALIZE_PARSING_RESTORE_OPTIONS error message for restore opt parsing failure.
=> GC Restore (CRIU): Introduce Restore Opts Parsing and Extend Failure Path Error Reporting

runtime/jvmti/jvmtiRawMonitor.c
JVMTI functions RawMonitorEnter and RawMonitorExit can be invoked
from Java code using native methods.
ownedMonitorCount is incremented for the current J9VMThread in
RawMonitorEnter after successfully acquiring the monitor, and
it is decremented for the current J9VMThread in RawMonitorExit
after successfully releasing the monitor.
This prevents virtual threads to yield if it owns a monitor.
Related: #16753
=> Pin virtual threads in JVMTI RawMonitorEnter and RawMonitorExit

runtime/oti/j9nonbuilder.h, runtime/oti/vm_api.h, runtime/vm/CRIUHelpers.cpp, runtime/vm/CRIUHelpers.hpp, runtime/vm/intfunc.c, runtime/vm/j9vm.tdf, runtime/vm/jvminit.c
This prepares for options reloading via loadRestoreArguments().
Cherry-pick 
* https://github.com/eclipse-openj9/openj9/pull/16622 - merged
* https://github.com/eclipse-openj9/openj9/pull/16791 - approved, running PR builds
=> (v0.38.0-release) CRIU internal JVM hook iterates J9Class and its ramMethods

runtime/jvmti/jvmtiExtensionMechanism.c
If no virtual thread is mounted on the targetThread i.e.
carrierThreadObject == threadObject, then return null
for the output virtual thread value.
Virtual thread is not pinned in this function. So, read
threadObject and carrierThreadObject once and store
their values to avoid inconsistency.
Related: #16688
Related: #16751
=> Fix jvmtiGetVirtualThread and make it more robust

debugtools/DDR_VM/src/com/ibm/j9ddr/StructureReader.java
The old default, 23, corresponds to a version that is no longer supported.
Previously, some corrupt core files would experience the error
> Failed to load alias map from resource: /com/ibm/j9ddr/StructureAliases23.dat
This will allow further progress for such core files.
=> Update default stream for reading core files

runtime/jvmti/jvmtiThread.c
JVMTI GetThreadState returns 0 (invalid state) for carrier threads
when a virtual thread is mounted over them. 0 indicates that the
thread has not started but this state is invalid for the carrier
threads when they have a virtual thread mounted.
Helper function getThreadState should not be given virtual thread
objects. It should only receive platform thread objects. Instead of
targetThread->threadObject which can be a virtual thread object, it is
given targetThread->carrierThreadObject to correctly evaluate the
state of carrier threads. This change should also be compatible with
all platform threads since carrierThreadObject is set only once during
thread creation, and it stays the same until thread termination.
Related: #16690
Signed-off-by: Dipak Bagadiya <dipak.bagadiya@ibm.com>
=> Fix GetThreadState to return correct state for carrier thread

runtime/jvmti/jvmtiHook.c
On zLinux, Assert_VM_mustNotHaveVMAccess is triggered from
internalAcquireVMAccessNoMutexWithMask when
jvmtiHookVirtualThreadMount invokes JNI->isVirtualThread from
the callback.
This happens because jvmtiHookVirtualThread[Mount|Unmount]
do not release VM access before invoking the callback.
In prepareForEvent, setting wantVMAccess to FALSE will release
VM access before invoking the callback. This fixes the above
assertion issue.
Related: #16752
=> Fix VM Access assertion for JVMTI VirtualThread[Mount|Unmount]

runtime/compiler/p/codegen/J9TreeEvaluator.cpp
Adding the missing break statement.  
Issue #11741
Signed-off by: Bhavani S N (bhavani.sn@ibm.com)
=> Adding missing break statement

runtime/vm/ObjectMonitor.cpp
Handle lock reservation in single thread mode
Cancel reservation on blocking enter in single thread mode to prevent throwing blocking exceptions on uncontended acquires.
=> Handle lock reservation in single thread mode

runtime/compiler/control/CompilationRuntime.hpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/DLLMain.cpp, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/J9Options.hpp, runtime/compiler/control/OptionsPostRestore.cpp, runtime/compiler/control/OptionsPostRestore.hpp, runtime/compiler/control/rossa.cpp, runtime/compiler/runtime/JITServerStatisticsThread.cpp
* Add the concept of Number of Allocated Threads
* In CRIU mode, the number of threads allocated is `TR::CompilationInfo::MAX_CLIENT_USABLE_COMP_THREADS` (unless it exceeds the number of code caches).
* In non-CRIU mode, the number of threads allocated is the same as the number of usable threads.
* Refactor JITServer options processing code so it can be reused post-restore
* Process JITServer options post restore
* Enable the post restore options processing code
=> Comp Threads and JIT Server options post restore

runtime/vm/ObjectMonitor.cpp
The variable was added by
https://github.com/eclipse-openj9/openj9/pull/16812 for use when defined(J9VM_OPT_CRIU_SUPPORT)
Fixes https://github.com/eclipse-openj9/openj9/issues/16818
=> Fix unused variable in ObjectMonitor.cpp

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties, jcl/src/java.base/share/classes/java/lang/System.java, test/functional/cmdLineTests/criu/criu_nonPortable.xml, test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSecurityManager.java
Enabling a SecurityManager currently unsupported when `-XX:+EnableCRIUSupport` is specified.;
Added tests to verify that` UnsupportedOperationException` is thrown when the `SecurityManager` is set programmatically or via `-Djava.security.manager`.
=> CRIU throws UnsupportedOperationException for SecurityManager

runtime/jvmti/jvmtiHook.c
On zLinux, Assert_VM_mustNotHaveVMAccess is triggered from
internalAcquireVMAccessNoMutexWithMask when jvmtiHookVirtualThreadMount
invokes JNI->isVirtualThread from the callback.
This happens because jvmtiHookVirtualThread[Mount|Unmount] do not
release VM access before invoking the callback.
In prepareForEvent, setting wantVMAccess to FALSE will release VM
access before invoking the callback. This fixes the above assertion issue.
Related: #16752
=> (0.37) Fix VM Access assertion for JVMTI VirtualThread[Mount|Unmount]

test/functional/Java8andUp/src/org/openj9/test/attachAPI/TestJps.java, test/functional/TestUtilities/src/org/openj9/test/util/StringUtilities.java
Created a unique needle with `tgtMgr.targetId` and `TargetVM/org.openj9.test.attachAPI.TargetVM` for
`testApplicationArguments`, `testJvmArguments` and `testComposedArguments`.
closes https://github.com/eclipse-openj9/openj9/issues/11509
closes https://github.com/eclipse-openj9/openj9/issues/5450
=> AttachAPI TestJps should search a unique needle

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties, jcl/src/java.base/share/classes/java/lang/System.java, test/functional/cmdLineTests/criu/criu_nonPortable.xml, test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSecurityManager.java
Enabling a SecurityManager currently unsupported when `-XX:+EnableCRIUSupport` is specified.;
Added tests to verify that` UnsupportedOperationException` is thrown when the `SecurityManager` is set programmatically or via `-Djava.security.manager`.
Cherry-pick 
* https://github.com/eclipse-openj9/openj9/pull/16806
=> (v0.38.0-release) CRIU throws UnsupportedOperationException for SecurityManager

runtime/compiler/control/J9Options.cpp
`Options::_catchSamplingSizeThreshold` is a field declared in OpenJ9 but initialized in omr project. The intent is to remove this field, but to avoid build breaking (or a coordinated merge) we first need to bring the declaration and initialization of this field into the same project.
=> Initialize _catchSamplingSizeThreshold in J9Options.cpp

runtime/vm/ObjectMonitor.cpp
(0.38) Handle lock reservation in single thread mode
Cancel reservation on blocking enter in single thread mode to prevent throwing blocking exceptions on uncontended acquires. This PR just attempts to cancel the reservation once and acquire the lock again. We only need to attempt the cancel once since its single thread mode.
=> (0.38) Handle lock reservation in single thread mode

runtime/jvmti/jvmtiThread.c
JVMTI GetThreadState returns 0 (invalid state) for carrier threads
when a virtual thread is mounted over them. 0 indicates that the
thread has not started but this state is invalid for the carrier
threads when they have a virtual thread mounted.
Helper function getThreadState should not be given virtual thread
objects. It should only receive platform thread objects. Instead of
targetThread->threadObject which can be a virtual thread object, it is
given targetThread->carrierThreadObject to correctly evaluate the
state of carrier threads. This change should also be compatible with
all platform threads since carrierThreadObject is set only once during
thread creation, and it stays the same until thread termination.
Related: #16690
=> (0.37) Fix GetThreadState to return correct state for carrier threads

doc/compiler/control/OptionsPostRestore.md, runtime/compiler/aarch64/runtime/Recomp.cpp, runtime/compiler/arm/runtime/Recomp.cpp, runtime/compiler/control/CompilationRuntime.hpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/CompilationThread.hpp, runtime/compiler/control/JITServerHelpers.cpp, runtime/compiler/control/OptionsPostRestore.cpp, runtime/compiler/control/OptionsPostRestore.hpp, runtime/compiler/control/RecompilationInfo.hpp, runtime/compiler/p/runtime/Recomp.cpp, runtime/compiler/x/runtime/Recomp.cpp, runtime/compiler/z/runtime/Recomp.cpp
* Ensure jit tracing occurs post restore 
* Process some remaining options
* Reinitialize number of processors post restore 
* Address Synchronous Compilation 
* Ensure methods can be excluded post restore 
* Address -Xnojit and -Xnoaot 
* Add doc for OptionsPostRestore
=> Post Restore Options Processing Continued

runtime/util/vmargs.c
With the introduction of vm->checkpointState.restoreArgsList it is possible that the args list passed into findArgInVMArgs(..) can be NULL. This PR adds a NULL check in additon to the count check as a fast path to exit
=> Add NULL check for VM args array

runtime/vm/ObjectMonitor.cpp
Fixes https://github.com/eclipse-openj9/openj9/issues/16685
=> Set thread blocked flag before triggering JVMTI Monitor Contended Enter

runtime/gc_realtime/MetronomeAlarmThread.cpp, runtime/gc_realtime/RealtimeGC.cpp, runtime/gc_realtime/Scheduler.cpp, runtime/gc_realtime/Scheduler.hpp, runtime/gc_realtime/SweepSchemeRealtime.cpp
Move some of Scheduler/Alarm specific initializaiton parameters that are stored in GCExtensions from Collector (RealtimeGC) to Scheduler.
Those parameter will now be initialized earlier. Specifically, timeWindowMicro will be initialized before its value is cached by Scheduler into window parameter.
All that to help window parameter be properly adjusted if beat parameter is changed by command line option.
=> Init Scheduler Window

doc/compiler/control/OptionsPostRestore.md, runtime/compiler/aarch64/runtime/Recomp.cpp, runtime/compiler/arm/runtime/Recomp.cpp, runtime/compiler/control/CompilationRuntime.hpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/CompilationThread.hpp, runtime/compiler/control/JITServerHelpers.cpp, runtime/compiler/control/OptionsPostRestore.cpp, runtime/compiler/control/OptionsPostRestore.hpp, runtime/compiler/control/RecompilationInfo.hpp, runtime/compiler/p/runtime/Recomp.cpp, runtime/compiler/x/runtime/Recomp.cpp, runtime/compiler/z/runtime/Recomp.cpp
Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/16838
The patch is almost identical except for `RecompilationInfo.hpp` where 
1. I had to resolve a merge conflict because https://github.com/eclipse-openj9/openj9/pull/16799 was not ported to 0.38.
2. I had to update the copyright because it was also updated in https://github.com/eclipse-openj9/openj9/pull/16799.
=> Post Restore Options Processing Continued (0.38)

runtime/j9vm/javanextvmi.cpp
The VirtualThread J9Hooks trigger callbacks which can utilize JVMTI
RawMonitors. The usage of JVMTI RawMonitors can conflict with the
J9JavaVM->liveVirtualThreadListMutex and lead to deadlocks. So,
these J9Hooks should be invoked after the liveVirtualThreadListMutex
is released to avoid deadlocks.
Related: #16826
=> Invoke VirtualThread J9Hooks after releasing VirtualThread List Mutex

runtime/j9vm/javanextvmi.cpp
The VirtualThread J9Hooks trigger callbacks which can utilize JVMTI
RawMonitors. The usage of JVMTI RawMonitors can conflict with the
J9JavaVM->liveVirtualThreadListMutex and lead to deadlocks. So,
these J9Hooks should be invoked after the liveVirtualThreadListMutex
is released to avoid deadlocks.
Related: #16826
Backport of #16856
=> (0.37) Invoke VirtualThread J9Hooks after releasing VirtualThread List Mutex

doc/compiler/control/OptionsPostRestore.md, runtime/compiler/control/CompilationRuntime.hpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/HookedByTheJit.cpp, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/J9Options.hpp, runtime/compiler/control/OptionsPostRestore.cpp, runtime/compiler/control/OptionsPostRestore.hpp
* Address `-Xrs` and `-Xtrace` post restore
* Reset start and elapsed time post restore
=> Post Restore Options Processing Part 4
