runtime/compiler/x/codegen/J9TreeEvaluator.cpp

The LEA mem-ref operand pointing to a label creates
a hidden virtual register which needs to be added
to the register dependency list.
Issue https://github.com/eclipse-openj9/openj9/issues/14654

Fix spill of hidden virtual-reg in StringLatin1.inflate

---

runtime/compiler/codegen/CodeGenGPU.cpp
runtime/compiler/il/ILOps.hpp

This PR fixes the `DEBUG` build of the JIT component.

Fix compilation errors in the JIT in debug mode

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/i386/codegen/J9TreeEvaluator.hpp

Move J9 specific i386 evaluators to OpenJ9

---

doc/release-notes/0.32/0.32.md

Update doc about JITServer support on Linux on Z

---

runtime/rastrace/method_trigger.c

Otherwise, [tracepoints introduced recently](#13933) in the implementation of the stack walker suppress output of `jstacktrace`.
Fixes: #14956.

Capture trace output mask for reuse in auxiliary tracepoints

---

runtime/criusupport/CMakeLists.txt
runtime/criusupport/criusupport.cpp
runtime/criusupport/module.xml
runtime/jvmti/heapify.cpp
runtime/oti/VMHelpers.hpp

Helperize the CRIU thread detection code.

Improve java thread test for dynamic heapification

---

runtime/compiler/net/LoadSSLLibs.cpp

Add OpenSSL 3 support to JITServer

---

runtime/rastrace/trctrigger.c

Ignore case when comparing -Xtrace trigger component names

---

runtime/compiler/control/CompilationThread.cpp
runtime/oti/vm_api.h
runtime/vm/CMakeLists.txt
runtime/vm/jvminit.c
runtime/vm/vmthread.cpp

Halt threads that are being attached in single thread mode

Halt threads that are being attached in single thread mode

---

runtime/compiler/control/CompilationThread.cpp
runtime/oti/vm_api.h
runtime/vm/CMakeLists.txt
runtime/vm/jvminit.c
runtime/vm/vmthread.c

Reverts eclipse-openj9/openj9#15000
See https://github.com/eclipse-openj9/openj9/pull/15000#issuecomment-1120204852

Revert "Halt threads that are being attached in single thread mode"

---

runtime/compiler/control/CompilationThread.cpp
runtime/oti/vm_api.h
runtime/vm/CMakeLists.txt
runtime/vm/jvminit.c
runtime/vm/vmthread.cpp

Halt threads that are being attached in single thread mode take 2

Halt threads that are being attached in single thread mode take 2

---

test/docs/OpenJ9TestUserGuide.md

Add document for auto excluding multiple tests

---

runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp
runtime/compiler/x/codegen/Instruction.hpp
runtime/compiler/x/codegen/J9UnresolvedDataSnippet.cpp
runtime/compiler/x/codegen/J9X86Instruction.cpp

Depends eclipse/omr#6488
FYI @0xdaryl 

Support instruction encoding override on x86

---

doc/release-notes/0.32/0.32.md

Issue https://github.com/eclipse-openj9/openj9/issues/15011

Add main thread stack size issue to the 0.32 release notes

---

buildenv/jenkins/jobs/infrastructure/Update-Reference-Repos.groovy

Add built-in node support to git cache update pipeline.

Add support for Jenkins built-in node

---

doc/compiler/README.md
doc/compiler/optimizer/ControlFlowOptimizationsSummary.md
doc/compiler/optimizer/GlobalOptimizationsSummary.md
doc/compiler/optimizer/LocalOptimizationsSummary.md
doc/compiler/optimizer/LoopOptimizationSummary.md

Added the following four documents on the summary of the JIT optimizations. These four documents are extracted
from the document written by Vijay - `"Summary of optimizations in the Testarossa JIT"` stored in Notes DB `InsideTRJIT`.
- LocalOptimizationsSummary.md
- GlobalOptimizationsSummary.md
- ControlFlowOptimizationsSummary.md
- LoopOptimizationSummary.md
Authored-By: Vijay Sundaresan <vijaysun@ca.ibm.com>

Add optimization summary documents

---

buildenv/jenkins/variables/defaults.yml

special.system doesn't run nightly so the excludes are no longer needed.

Remove special.system excludes from defaults.yml

---

runtime/nls/cfre/cfrerr_ca.nls
runtime/nls/cfre/cfrerr_cs.nls
runtime/nls/cfre/cfrerr_de.nls
runtime/nls/cfre/cfrerr_es.nls
runtime/nls/cfre/cfrerr_fr.nls
runtime/nls/cfre/cfrerr_hu.nls
runtime/nls/cfre/cfrerr_it.nls
runtime/nls/cfre/cfrerr_ja.nls
runtime/nls/cfre/cfrerr_ko.nls
runtime/nls/cfre/cfrerr_pl.nls
runtime/nls/cfre/cfrerr_pt_BR.nls
runtime/nls/cfre/cfrerr_sk.nls
runtime/nls/cfre/cfrerr_sl.nls
runtime/nls/cfre/cfrerr_tr.nls
runtime/nls/cfre/cfrerr_zh.nls
runtime/nls/cfre/cfrerr_zh_CN.nls
runtime/nls/cfre/cfrerr_zh_TW.nls

Files update for TR R8-EmergencyShip0517

Modify the translated PII files in nls folder 20220520

---

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/SecurityProviders.java

Signed-off-by: Alon Shalev Housfater <alonsh@ca.ibm.com>

Rename resetDigests to a generic resetCRIUSEC

---

.github/ISSUE_TEMPLATE/criu-issue.md
.github/ISSUE_TEMPLATE/snapshot_issue.md

Add issue template for CRIU issues, and delete the unused snapshot template.

Add CRIU issue template and delete snapshot template

---

runtime/nls/cfre/cfrerr_ca.nls
runtime/nls/cfre/cfrerr_cs.nls
runtime/nls/cfre/cfrerr_de.nls
runtime/nls/cfre/cfrerr_es.nls
runtime/nls/cfre/cfrerr_fr.nls
runtime/nls/cfre/cfrerr_hu.nls
runtime/nls/cfre/cfrerr_it.nls
runtime/nls/cfre/cfrerr_ja.nls
runtime/nls/cfre/cfrerr_ko.nls
runtime/nls/cfre/cfrerr_pl.nls
runtime/nls/cfre/cfrerr_pt_BR.nls
runtime/nls/cfre/cfrerr_sk.nls
runtime/nls/cfre/cfrerr_sl.nls
runtime/nls/cfre/cfrerr_tr.nls
runtime/nls/cfre/cfrerr_zh.nls
runtime/nls/cfre/cfrerr_zh_CN.nls
runtime/nls/cfre/cfrerr_zh_TW.nls

Files update for R8-EmergencyShip0527.

Modify the translated PII files in nls folder 20220530

---

runtime/tests/clinkerffi/downcall.h

Update the declaration of struct for FFI downcall tests

---

runtime/compiler/optimizer/SPMDParallelizer.cpp

Prevent use of vsplats opcode for unsupported datatype

---

buildenv/jenkins/jobs/infrastructure/copyrightCheck.groovy
buildenv/jenkins/jobs/infrastructure/lineEndingsCheck.groovy
buildenv/jenkins/jobs/infrastructure/signedOffByCheck.groovy

Allow jobs to run on user defined nodes.
Allow overwrite of the git repository cache.
Add support for private git repository.
Add clean workspace at the end of the build.

Paremeterize Pull Request related jobs

---

test/TestConfig/resources/excludes/feature_vtstandard_exclude.txt
test/functional/JavaAgentTest/playlist.xml

Use playlist.xml to exclude test in VT standard build

---

runtime/bcutil/cfreader.c
runtime/nls/cfre/cfrerr.nls
runtime/nls/cfre/cfrerr_ca.nls
runtime/nls/cfre/cfrerr_cs.nls
runtime/nls/cfre/cfrerr_de.nls
runtime/nls/cfre/cfrerr_es.nls
runtime/nls/cfre/cfrerr_fr.nls
runtime/nls/cfre/cfrerr_hu.nls
runtime/nls/cfre/cfrerr_it.nls
runtime/nls/cfre/cfrerr_ja.nls
runtime/nls/cfre/cfrerr_ko.nls
runtime/nls/cfre/cfrerr_pl.nls
runtime/nls/cfre/cfrerr_pt_BR.nls
runtime/nls/cfre/cfrerr_ru.nls
runtime/nls/cfre/cfrerr_sk.nls
runtime/nls/cfre/cfrerr_sl.nls
runtime/nls/cfre/cfrerr_tr.nls
runtime/nls/cfre/cfrerr_zh.nls
runtime/nls/cfre/cfrerr_zh_CN.nls
runtime/nls/cfre/cfrerr_zh_TW.nls
runtime/oti/j9nonbuilder.h
runtime/verutil/cfrerr.c

Port of https://github.com/eclipse-openj9/openj9/pull/15084 for the 0.33 release.

(0.33) Improve error message when loading an invalid class version

---

runtime/nls/cfre/cfrerr_ca.nls
runtime/nls/cfre/cfrerr_fr.nls
runtime/nls/cfre/cfrerr_it.nls
runtime/nls/cfre/cfrerr_pl.nls
runtime/nls/cfre/cfrerr_pt_BR.nls
runtime/nls/cfre/cfrerr_sk.nls
runtime/nls/cfre/cfrerr_sl.nls
runtime/nls/cfre/cfrerr_tr.nls
runtime/nls/cfre/cfrerr_zh.nls
runtime/nls/cfre/cfrerr_zh_CN.nls
runtime/nls/cfre/cfrerr_zh_TW.nls
runtime/nls/j9cl/j9jcl_cs.nls
runtime/nls/j9cl/j9jcl_es.nls
runtime/nls/j9cl/j9jcl_it.nls
runtime/nls/j9cl/j9jcl_ko.nls
runtime/nls/j9cl/j9jcl_pl.nls
runtime/nls/j9cl/j9jcl_zh.nls
runtime/nls/j9cl/j9jcl_zh_CN.nls
runtime/nls/j9vm/j9vm_cs.nls
runtime/nls/j9vm/j9vm_fr.nls
runtime/nls/j9vm/j9vm_it.nls
runtime/nls/j9vm/j9vm_pl.nls
runtime/nls/j9vm/j9vm_pt_BR.nls
runtime/nls/j9vm/j9vm_sk.nls
runtime/nls/j9vm/j9vm_sl.nls
runtime/nls/j9vm/j9vm_zh.nls
runtime/nls/j9vm/j9vm_zh_CN.nls

Files be updated in ICT pass 1.

Modify the translated PII files in nls folder 20220606

---

buildenv/jenkins/variables/defaults.yml

Tested via https://github.com/eclipse-openj9/openj9/issues/15051#issuecomment-1142201809
Also via the Semeru M1 build.

Compile Windows jdk8 with VS2017

---

doc/build-instructions/Build_Instructions_V8.md
doc/release-notes/0.33/0.33.md

See https://github.com/eclipse-openj9/openj9/pull/15233

Update build instructions and release notes for jdk8 VS2017

---

runtime/compiler/optimizer/VectorAPIExpansion.cpp

Depends on https://github.com/eclipse/omr/pull/6554

Create verbose option for VectorAPIExpansion

---

buildenv/jenkins/variables/defaults.yml

Cherry pick https://github.com/eclipse-openj9/openj9/pull/15233 for the 0.33 release.

(0.33) Compile Windows jdk8 with VS2017

---

runtime/nls/cfre/cfrerr_ca.nls
runtime/nls/cfre/cfrerr_fr.nls
runtime/nls/cfre/cfrerr_it.nls
runtime/nls/cfre/cfrerr_pl.nls
runtime/nls/cfre/cfrerr_pt_BR.nls
runtime/nls/cfre/cfrerr_sk.nls
runtime/nls/cfre/cfrerr_sl.nls
runtime/nls/cfre/cfrerr_tr.nls
runtime/nls/cfre/cfrerr_zh.nls
runtime/nls/cfre/cfrerr_zh_CN.nls
runtime/nls/cfre/cfrerr_zh_TW.nls
runtime/nls/j9cl/j9jcl_cs.nls
runtime/nls/j9cl/j9jcl_es.nls
runtime/nls/j9cl/j9jcl_it.nls
runtime/nls/j9cl/j9jcl_ko.nls
runtime/nls/j9cl/j9jcl_pl.nls
runtime/nls/j9cl/j9jcl_zh.nls
runtime/nls/j9cl/j9jcl_zh_CN.nls
runtime/nls/j9vm/j9vm_cs.nls
runtime/nls/j9vm/j9vm_fr.nls
runtime/nls/j9vm/j9vm_it.nls
runtime/nls/j9vm/j9vm_pl.nls
runtime/nls/j9vm/j9vm_pt_BR.nls
runtime/nls/j9vm/j9vm_sk.nls
runtime/nls/j9vm/j9vm_sl.nls
runtime/nls/j9vm/j9vm_zh.nls
runtime/nls/j9vm/j9vm_zh_CN.nls

Files be updated in ICT pass 1.
Cherry pick https://github.com/eclipse-openj9/openj9/pull/15231 for the 0.33 release.

(0.33) Modify the translated PII files in nls folder 20220606

---

test/functional/DDR_Test/tck_ddrext.xml

Cherry-pick #15282 for 0.33.0.

(0.33) Don't let JIT compile the methods we need to find in tests

---

buildenv/jenkins/jobs/infrastructure/Update-Reference-Repos.groovy

Add extensions repositories to setup nodes.
Parameterize the location of git reference repository.

Cache extensions repositories on setup nodes

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java

Issue https://github.com/eclipse-openj9/openj9/issues/15168
See also https://github.com/eclipse-openj9/openj9/issues/14600

  ClassLoader.registerAsParallelCapable() must handle null caller

---

buildenv/jenkins/jobs/pipelines/Pipeline-Initialize.groovy

The top level job timeout will take effect.
The `params.TIMEOUT_TIME` is not available to use in this pipeline. A timeout is not needed unless a `pipeline-build-test-spec-version` build is launched directly without a top level parent, which rarely or never happens.
Fixes https://github.com/eclipse-openj9/openj9/issues/15302

Remove hard coded pipeline-build-test-spec timeout of 20 hours

---

runtime/criusupport/criusupport.cpp

Use safePoint access in single thread mode when available

Use safePoint access in single thread mode when available

---

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/tdump/zebedee/le/DsaStackFrame.java
jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/corereaders/zos/le/DsaStackFrame.java

Cherry-pick #15317 for the 0.33.0 release.

(0.33) Improve robustness of scanning SFXM chains

---

runtime/nls/cfre/cfrerr_ca.nls
runtime/nls/cfre/cfrerr_cs.nls
runtime/nls/cfre/cfrerr_de.nls
runtime/nls/cfre/cfrerr_es.nls
runtime/nls/cfre/cfrerr_fr.nls
runtime/nls/cfre/cfrerr_hu.nls
runtime/nls/cfre/cfrerr_it.nls
runtime/nls/cfre/cfrerr_ja.nls
runtime/nls/cfre/cfrerr_ko.nls
runtime/nls/cfre/cfrerr_pl.nls
runtime/nls/cfre/cfrerr_pt_BR.nls
runtime/nls/cfre/cfrerr_sk.nls
runtime/nls/cfre/cfrerr_sl.nls
runtime/nls/cfre/cfrerr_tr.nls
runtime/nls/cfre/cfrerr_zh.nls
runtime/nls/cfre/cfrerr_zh_CN.nls
runtime/nls/cfre/cfrerr_zh_TW.nls

Files update for ship R11-ship0614.

Modify the translated PII files in nls folder 20220620

---

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/BuildVersionCommand.java

Cherry-pick #15357 for the 0.33.0 release.

(0.33) Correct reading BuildVersionCommand from OSX core files

---

runtime/nls/cfre/cfrerr_ca.nls
runtime/nls/cfre/cfrerr_cs.nls
runtime/nls/cfre/cfrerr_de.nls
runtime/nls/cfre/cfrerr_es.nls
runtime/nls/cfre/cfrerr_fr.nls
runtime/nls/cfre/cfrerr_hu.nls
runtime/nls/cfre/cfrerr_it.nls
runtime/nls/cfre/cfrerr_ja.nls
runtime/nls/cfre/cfrerr_ko.nls
runtime/nls/cfre/cfrerr_pl.nls
runtime/nls/cfre/cfrerr_pt_BR.nls
runtime/nls/cfre/cfrerr_sk.nls
runtime/nls/cfre/cfrerr_sl.nls
runtime/nls/cfre/cfrerr_tr.nls
runtime/nls/cfre/cfrerr_zh.nls
runtime/nls/cfre/cfrerr_zh_CN.nls
runtime/nls/cfre/cfrerr_zh_TW.nls

Files update for ship R11-ship0614.
Cherry pick https://github.com/eclipse-openj9/openj9/pull/15361 for 0.33

(0.33) Modify the translated PII files in nls folder 20220620

---

jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/plugins/impl/ClassScanner.java

See:
* 8282508: Updating ASM to 9.2 for JDK 19
Also tidy up:
* add missing `@Override` annotations
* format

Update ClassScanner to use ASM9 for Java 19+

---

jcl/src/java.base/share/classes/java/lang/String.java

Cherry-picked from https://github.com/eclipse-openj9/openj9/pull/15339#issuecomment-1161704916
fyi: @pshipton

(0.33.0) Return early in String.indexOf if substring is longer than string

---

buildenv/jenkins/variables/defaults.yml

Cherry-pick #15381 for the 0.33 release.

(0.33) Update openssl to version 1.1.1p

---

runtime/compiler/optimizer/SPMDParallelizer.cpp

(0.33.0) Prevent AutoSIMD seg-fault on defs from method entry

---

runtime/compiler/control/rossa.cpp
runtime/compiler/net/ClientStream.cpp
runtime/compiler/net/ClientStream.hpp
runtime/compiler/net/ServerStream.hpp
runtime/compiler/runtime/Listener.cpp

Fix unused arguments, declarations in SSL code

---

runtime/gc_vlhgc/VLHGCAccessBarrier.cpp

*data[i] does not resolve to what we want due to operator precedence,
so declare another variable copyArr=*data.
Causes a segfault if compact strings are enabled without this change. 
`j9vm.test.jni.CriticalRegionTest` as part of the `J9vmTest` in functional testing will fail if compact strings are enabled, for example by adding `-XX:+CompactStrings` to `EXTRA_OPTIONS` in a grinder run.

Fix operator precedence in copyStringCritical

---

runtime/gc_vlhgc/VLHGCAccessBarrier.cpp

*data[i] does not resolve to what we want due to operator precedence,
so declare another variable copyArr=*data.
Cherry-picked from https://github.com/eclipse-openj9/openj9/pull/15359
fyi @pshipton

(v0.33.0)Fix operator precedence in copyStringCritical

---

runtime/compiler/control/CompilationController.cpp
runtime/compiler/control/CompilationController.hpp

Reverts eclipse-openj9/openj9#15137
See https://github.com/eclipse-openj9/openj9/issues/15426#issuecomment-1167384633

Revert "Refactor TR::DefaultCompilationStrategy::processJittedSample"

---

runtime/vm/jnicsup.cpp

Fix tracepoints: entry tracepoint used as exit tracepoint

---

doc/compiler/README.md
doc/compiler/optimizer/OptimizerDesignFeatures.md

Authored-By: Vijay Sundaresan <vijaysun@ca.ibm.com>

Add Optimizer Design Feature Document

---

runtime/compiler/optimizer/IdiomRecognition.cpp

Cherry-pick of #15344 for 0.33
Fixes #15319

(0.33) Prevent improper removal of static store in idiom recognition

---

jcl/src/java.base/share/classes/java/lang/J9VMInternals.java

Re-order the shutdown hook sequence
The new implementation of Thread.getAllThreads() makes use of method
references. This requires that a new MethodHandleNatives$CallSiteContext
is created. This registers a PhantomCleanable with the commoncleaner and
circumvents what we are attempting to achieve with
CleanerShutdown.shutdownCleaner(). We can resolve this issue re-ordering
operations such that shutdownCleaner is the last operation before we
fallback to the sending the interrupt.
Fixes: https://github.com/eclipse-openj9/openj9/issues/15453
Related: https://github.com/eclipse-openj9/openj9/issues/15408

Re-order the shutdown hook sequence

---

doc/release-notes/0.33/0.33.md

Add new JITServer features in the 0.33.0 release notes

---

runtime/vm/module.xml

Add UMA makefile filter flag for ContinuationHelpers.cpp/hpp

---

runtime/compiler/net/ServerStream.cpp
runtime/compiler/net/ServerStream.hpp
runtime/compiler/runtime/Listener.cpp
runtime/compiler/runtime/MetricsServer.cpp

Factor out SSL context creation, improve SSL log message

---

test/functional/Java19andUp/build.xml
test/functional/Java19andUp/playlist.xml
test/functional/Java19andUp/src/org/openj9/test/jep425/VirtualThreadTests.java
test/functional/Java19andUp/testng_190.xml

Add basic testing for Continuation

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Options.cpp

Fix compilation thread number parsing error

---

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java

CRIU throws `UnsupportedOperationException` when `UnsatisfiedLinkError` occurred.
`isCRIUSupportEnabled()` returns `false` if the `j9criu29` library wasn't load successfully;
Set `errorMsg` to be returned via `CRIUSupport.getErrorMessage()`.
closes https://github.com/eclipse-openj9/openj9/issues/15554

CRIU throws UnsupportedOperationException when UnsatisfiedLinkError

---

.gitignore

Ignore `/.settings/` like OMR does.

Update ignored eclipse resources

---

test/functional/cmdLineTests/criu/playlist.xml

Disable multiple checkpoints test

Disable multiple checkpoints test

---

runtime/vm/createramclass.cpp

Ensure class flags are set before class is visible

---

test/functional/Java19andUp/playlist.xml

Exclude `Jep425Tests_testVirtualThread`
https://github.com/eclipse-openj9/openj9/issues/15650
https://github.com/eclipse-openj9/openj9/issues/15651
FYI @tajila 

Exclude Jep425Tests_testVirtualThread

---

runtime/rasdump/javadump.cpp

Currently javacore shows unowned for the threads waiting on
java/lang/J9VMInternals$ClassInitializationLock. This PR shows
the thread currently responsible for advancing the initialization
of a class using a separate label(Initializing thread).
Fixes: #284
Signed-off-by: Ravali Yatham <ravaliyatham@gmail.com>

Show owner of J9VMInternals$ClassInitializationLock in javacore

---

test/functional/Java19andUp/playlist.xml

Add -Xint to testVirtualThread, re-enable test

---

runtime/compiler/runtime/IProfiler.cpp

As explained in the discussion for PR #12405, due to a SCC race
condition, the class chain returned by `rememberClass()` may
not be found by a subsequent `offsetInSharedCacheFromPointer(classChain)`
operation, in which case an ASSERT_FATAL is raised.
The safe way to deal with this race is to test the presence of the
class chain with `isPointerInSharedCache(classChain, &cacheOffset)`
Fixes https://github.com/eclipse-openj9/openj9/issues/15703

Fix race condition related to IProfiler info persistence

---

runtime/vm/jvminit.c

Fix incorrect free in ensure hashed parsing

---

runtime/criusupport/criusupport.cpp

Force a GC pre-checkpoint Part1

---

runtime/compiler/x/env/J9CPU.cpp

Enable FMA extensions on x86

---

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/elf/ELFFileReader.java

Cherry-pick #15549 for the 0.33.1 release.

Avoid NullPointerException reading SONAME

---

runtime/compiler/control/J9Options.cpp

Parsing the JITServerLocalSyncCompiles option must come after
FullSpeedDebug has been set, so that LocalSyncCompiles can be disabled
in its presence.
Fixes: #15646

Delay LocalSyncCompiles option parsing

---

doc/release-notes/0.35/0.35.md

Created draft release note for 0.35.0
[skip ci]

Created draft release note for 0.35.0

---

buildenv/jenkins/variables/defaults.yml

Issue https://github.com/eclipse-openj9/openj9/issues/15582
See also
https://github.com/adoptium/temurin-build/pull/2992
https://github.com/ibmruntimes/temurin-build/pull/25

Compile Windows jdk11 with VS2019

---

README.md

Fix the broken URL in README.md

---

test/functional/cmdLineTests/libpathTest/playlist.xml

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

Update disabled platforms

---

runtime/vm/jvminit.c

Fixes https://github.com/eclipse-openj9/openj9/issues/15801

Enable Portable SCC detection on aarch64

---

runtime/jvmti/j9jvmti.tdf
runtime/jvmti/jvmtiStackFrame.c

* move new tracepoint to the end
* fix illegal C code (move declaration)

Fix issues in #15753

---

runtime/jvmti/jvmtiStackFrame.c

Refactors vm->internalVMFunctions to vmFuncs.
Adds check for virtual thread, if is virtual thread, get the
continuation object and walk it with `walkContinuationStackFrames`.
Issues: https://github.com/eclipse-openj9/openj9/issues/15759 https://github.com/eclipse-openj9/openj9/issues/15183

Update jvmtiGetFrameLocation to support virtual threads

---

runtime/zlib/inflate.c

Applied
https://github.com/madler/zlib/commit/eff308af425
https://github.com/madler/zlib/commit/1eb7682f845
Cherry pick https://github.com/eclipse-openj9/openj9/pull/15829 for 0.35

(0.35) Update zlib to fix CVE-2022-37434

---

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Implement the inlined version of java/lang/Math.fma.

AArch64: Inline Math.fma

---

runtime/gc_base/GCExtensions.cpp
runtime/gc_modron_startup/mmparseXXgc.cpp

Remove idleMinimumFree from extension base

Remove depracted idle tuning fields from extension base

---

runtime/vm/xr64/UpcallThunkGen.cpp

This commit adds functions for FFI upcall for AArch64 Linux/macOS.

FFI upcall thunk generation for AArch64

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/stackwalker/JITStackWalker.java
runtime/codert_vm/decomp.cpp
runtime/codert_vm/jswalk.c

For https://github.com/eclipse-openj9/openj9/issues/15861

Add Q type checks in decomp.cpp and jswalk.c

---

debugtools/DDR_VM/src/com/ibm/j9ddr/tools/ddrinteractive/commands/TraceFileHeaderWriter.java

Issue: #15892
Signed-off-by: Kevin Grigorenko <kevin.grigorenko@us.ibm.com>

Increase the size of the header buffer for the !snapformat command

---

runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/ContinuationHelpers.cpp
runtime/vm/intfunc.c

Add copyFieldsFromContinuation helper to internalVMFunctions

---

runtime/jvmti/jvmtiStackFrame.c

Traverse the thread list before acquireExclusiveVMAccess and after releaseExclusiveVMAccess to ensure virtual thread transition completion.
Update live thread check for virtual thread
Update surrounding code style
Issues: https://github.com/eclipse-openj9/openj9/issues/15759 https://github.com/eclipse-openj9/openj9/issues/15183

Update jvmtiGetThreadListStackTraces to support virtual threads

---

runtime/jvmti/jvmtiThread.c
runtime/jvmti/jvmti_internal.h
runtime/jvmti/suspendhelper.cpp

Addresses comments from #15903.

Make formatting consistent

---

runtime/rasdump/javadump.cpp

Sometimes it's useful to know the approximate time it takes to produce java dumps to gauge their overhead:
```
0SECTION       Javadump End section
NULL           =================================
1TIDMPCOMPLETE Dump completed: 2022/09/26 at 14:04:58:585
1TIDMPDURATION Approximate time to produce this dump: 2 ms
NULL           ---------------------- END OF DUMP -------------------------------------
```
Signed-off-by: Kevin Grigorenko <kevin.grigorenko@us.ibm.com>

Add java dump end date and approximate duration

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/x/amd64/codegen/AMD64JNILinkage.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.hpp
runtime/compiler/x/runtime/X86LockReservation.nasm
runtime/jilgen/jilconsts.c

Reverts eclipse-openj9/openj9#15552

Revert "x64 JIT support for virtual threads (Loom)"

---

runtime/gc_glue_java/ScavengerDelegate.cpp
runtime/gc_glue_java/ScavengerDelegate.hpp
runtime/gc_glue_java/ScavengerRootScanner.cpp
runtime/gc_glue_java/ScavengerRootScanner.hpp
runtime/gc_stats/CopyForwardStats.hpp

- Remove duplicated StartContinuationProcessing
- Fix missing MM_CopyForwardStats._continuationCandidates merge

Fix StartContinuationProcessing and verbosegc report issues

---

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java

Reverts eclipse-openj9/openj9#15996

Revert "Update Continuation.yield to use onPinned API"

---

runtime/j9vm/exports.cmake
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/javanextvmi.cpp
runtime/redirector/forwarders.m4
runtime/redirector/module.xml

Add stub implementation of JVM_VirtualThreadHideFrames()

---

runtime/j9vm/exports.cmake
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/javanextvmi.cpp
runtime/redirector/forwarders.m4

Add JVM_IsValhallaEnabled() for Valhalla builds

---

runtime/jcl/common/java_lang_J9VMInternals.cpp

A null throwable will be passed when a virtual thread is during
transition, in this case we simply return null and the caller
VirtualThread.asyncGetStackTrace() will treat a null return as retry and
other callers are not affected.
Also minor fix for coding style
Fixes #15937
FYI @fengxue-IS 

Fix J9VMInternals.getStackTrace() to return null for a null throwable

---

test/functional/Java19andUp/playlist.xml

Update VirtualThread test options/requirements

---

runtime/compiler/aarch64/codegen/ARM64JNILinkage.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

* Adjust J9VMThread ownedMonitorCount counters for ARM64 monenter/monexit
* Adjust J9VMThread callOutCount counters around ARM64 direct JNI dispatch

AArch64 JIT changes for virtual thread support

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/p/codegen/PPCJNILinkage.cpp

This commit adds changes to Power to support Virtual Threads.
This includes incrementing and decrementing ownedMonitorCount when locks are acquired or released.
Also callOutCount is incremented and decremented on JNI call outs.

JIT Pinning support for JDK19 on Power

---

buildenv/docker/mkdocker.sh
buildenv/jenkins/docker-nodes/jenkinsfile-build-container.groovy

Add CRIU support for zLinux

---

doc/build-instructions/Build_Instructions_V11.md
doc/build-instructions/Build_Instructions_V17.md
doc/build-instructions/Build_Instructions_V18.md
doc/build-instructions/Build_Instructions_V8.md

I'll copy the statement to all platforms and versions after the initial review.

Add information about the test and debug-image to build instructions

---

runtime/gc_base/modronapi.cpp

Add missing checkpoint GC checks

Add missing checkpoint GC checks

---

runtime/vm/FastJNI_java_lang_Object.cpp

`Fast_java_lang_Object_notify/notifyAll()` invoke `delayedLockingOperation()` instead at single thread mode.
closes https://github.com/eclipse-openj9/openj9/issues/16026

CRIU delayedLockingOperation for fast JNI notify/notifyAll

---

buildenv/jenkins/variables/defaults.yml

Update openssl to version 1.1.1r

---

runtime/vm/wa64/UpcallThunkGen.cpp
runtime/vm/xa64/UpcallThunkGen.cpp

Implement upcall thunk generation for Linux, macOS, and Windows.

X64 FFI upcall thunk generation

---

runtime/gc_glue_java/ScavengerRootClearer.cpp

Need to pass structure pointer instead of structure for the parameter of Assert_GC_true_with_message2().

Fix a typo

---

runtime/criusupport/criusupport.cpp

Call malloc_trim pre-checkpoint

Call malloc_trim pre-checkpoint

---

test/functional/Java19andUp/playlist.xml

Enable Gencon/Balanced/OptAvgPause GC policy in testing

---

runtime/compiler/runtime/JITClientSession.cpp

Fix check in JITServer AOT class chain compilation

---

runtime/compiler/optimizer/VectorAPIExpansion.hpp

Fix binary literal in VectorAPIExpansion.hpp

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9CallGraph.hpp
runtime/compiler/optimizer/J9Inliner.cpp

This is #16122 for 0.35, with the identical commits

(0.35) Disallow nop guards for interface call sites

---

jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java

Add stub unsafe methods

---

jcl/src/java.base/share/classes/com/ibm/oti/vm/VM.java

fixes: #2233
Signed-off-by: Alexey Anufriev <contact@alexey-anufriev.com>

Remove com.ibm.oti.vm.VM.PACKED_SUPPORT_ENABLED

---

runtime/jcl/common/thread.cpp

Use exclusive access correctly in getThreads

---

runtime/jcl/common/thread.cpp

Read thread count under lock in getThreads

---

runtime/vm/threadhelp.cpp

Fix `bool` constant values
Related https://github.com/eclipse-openj9/openj9/pull/16220#discussion_r1009678957

Fix bool constant values

---

runtime/compiler/codegen/J9TreeEvaluator.cpp
runtime/compiler/codegen/J9TreeEvaluator.hpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.hpp

Remove many deprecated and experimental features.  Miscellaneous code cleanup.

Clean up x86 monent/monexit inline sequences

---

jcl/src/java.base/share/classes/java/lang/Class.java

Add modifiers IDENTITY, VALUE and PRIMITIVE to the modifiers mask
Closes #16207

Update Class.getModifiers() to include new Valhalla modifiers

---

buildenv/jenkins/variables/defaults.yml

Issue: https://github.com/eclipse-openj9/openj9/issues/7633.

Update openssl to version 1.1.1s

---

test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLOpenJ9.xml

Add test for default SCC directory

---

test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTestClasses.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeUnsafeTests.java

Relies on https://github.com/eclipse-openj9/openj9/pull/15922 being merged
Part of solution of issue #15529

Add testing for VT hashcodes

---

runtime/jvmti/jvmtiThread.c

Re-organize code to acquire VM access before invoking releaseVMThread
in jvmtiGetThreadInfo.
Related: #15765
Fixes: #16250

jvmtiGetThreadInfo: releaseVMThread requires VM access

---

runtime/oti/j9consts.h
runtime/oti/j9nonbuilder.h
runtime/vm/swalk.c

Reverts eclipse-openj9/openj9#16288
See https://github.com/eclipse-openj9/openj9/pull/16288#issuecomment-1311000974

Revert "Stack walk loop breaker for ASGCT"

---

test/functional/Java17andUp/src_170/org/openj9/test/jep389/valist/DowncallTests.java
test/functional/Java17andUp/src_170/org/openj9/test/jep389/valist/UpcallTests.java
test/functional/Java17andUp/src_170/org/openj9/test/jep389/valist/VaListUpcallMethodHandles.java

Issue: https://github.com/eclipse-openj9/openj9/issues/16057.
FYI @ChengJin01

Update URLs in copyright notices

---

test/functional/Valhalla/src/org/openj9/test/lworld/DDRBackfillLayoutTest.java
test/functional/cmdLineTests/valuetypeddrtests/flattened32bitRefBackfillTest.xml

Fix spelling of DDRBackfillLayoutTest

---

runtime/vm/xr64/UpcallThunkGen.cpp

This commit partially removes macOS-specific code from FFI upcall for AArch64.
Linux and macOS use different layout for arguments passed in the stack. Arguments are always aligned at the 8-byte boundary in the stack on Linux, while macOS places arguments at 1/2/4/8-byte boundary depending on their types.
However, the arguments saved by the upcall thunk do not need to follow the layout when getArgPointer() knows it.
This commit changes the argument layout on macOS to "always at the 8-byte boundary" for the stack extended by the upcall thunk, to simplify the code.

AArch64: Simplify stack offsets for FFI upcall on macOS

---

test/functional/DDR_Test/src/j9vm/test/ddrext/Constants.java

Fixes https://github.com/eclipse-openj9/openj9/issues/16358
Tested in grinder https://openj9-jenkins.osuosl.org/job/Grinder/1515

Update DDR TestClassExt to expect 14 Object methods

---

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/JVMRestoreException.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/SystemRestoreException.java
runtime/criusupport/criusupport.cpp
runtime/nls/j9cl/j9jcl.nls
runtime/nls/j9cl/j9jcl_ca.nls
runtime/nls/j9cl/j9jcl_cs.nls
runtime/nls/j9cl/j9jcl_de.nls
runtime/nls/j9cl/j9jcl_es.nls
runtime/nls/j9cl/j9jcl_fr.nls
runtime/nls/j9cl/j9jcl_hu.nls
runtime/nls/j9cl/j9jcl_it.nls
runtime/nls/j9cl/j9jcl_ja.nls
runtime/nls/j9cl/j9jcl_ko.nls
runtime/nls/j9cl/j9jcl_pl.nls
runtime/nls/j9cl/j9jcl_pt_BR.nls
runtime/nls/j9cl/j9jcl_sk.nls
runtime/nls/j9cl/j9jcl_sl.nls
runtime/nls/j9cl/j9jcl_tr.nls
runtime/nls/j9cl/j9jcl_zh.nls
runtime/nls/j9cl/j9jcl_zh_CN.nls
runtime/nls/j9cl/j9jcl_zh_TW.nls
runtime/oti/j9nonbuilder.h
runtime/oti/vmconstantpool.xml
runtime/vm/exceptionsupport.c
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/CRIUTestUtils.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeCheckpointException.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeRestoreException.java

Introduce SystemCheckpointException

Introduce SystemCheckpointException

---

runtime/compiler/env/ProcessorDetection.cpp
runtime/compiler/z/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/env/J9CPU.cpp

Replace zNext with z16

---

runtime/compiler/runtime/J9Profiler.cpp

In case we are in estimate code size phase of inlining or inlining was different in previous profiling compilation, we prepare a call stack to find out the matching call stack in the profiling information. Previously it was just matching the method called at the call site to find out the matching call stack. This would be incorrect as we could have same call stack at multiple call sites and they would have different hotness. Current solution of computing effective caller index would simply find the first call stack that matches and does not inspect later ones. To fix that, we should also check the byte code index at the call site as that would provide us the correct information.
Consider the following Java method. 
```
public void returnArraysHashCode(byte[] arr) {
if (functionCall == 0) …
```

Inspect BCI as well while computing effective caller index

---

test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/criu_random.xml
test/functional/cmdLineTests/criu/criu_security.xml

Modify test conditions to allow for restore failure

Modify test conditions to allow for restore failure

---

doc/release-notes/0.36/0.36.md

Created draft 0.36.0 release notes
[skip ci]

Draft 0.36.0 release notes

---

runtime/j9vm/javanextvmi.cpp

This change fixes the below deadlock.
Thread 1 wants exclusive VM access but it is unable to acquire
exclusive VM access because Thread 2 also holds VM access.
Thread 2 is waiting to acquire liveVirtualThreadListMutex and
unable to proceed because Thread 1 holds liveVirtualThreadListMutex.
This prevents both threads to proceed and leads to a deadlock.
```
Thread 1: JVM_VirtualThreadMountEnd
-> Acquires VM Access and liveVirtualThreadListMutex
-> J9AllocateObject
-> Multiple GC frames
-> acquireExclusiveVMAccess
Thread 2: JVM_VirtualThreadMountEnd
-> Acquires VM Access
-> Blocked to enter liveVirtualThreadListMutex
```
Related: https://github.com/eclipse-openj9/openj9/issues/16340#issuecomment-1324095402

Invoke J9AllocateObject without acquiring liveVirtualThreadListMutex

---

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
runtime/jcl/common/jdk_internal_vm_Continuation.cpp
runtime/jcl/exports.cmake
runtime/jcl/uma/se19_exports.xml
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/ContinuationHelpers.cpp
runtime/vm/intfunc.c

Delay Continuation's native allocation to first mount

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp

Cherry pick of https://github.com/eclipse-openj9/openj9/pull/16392

(0.36) Check sequence boundary before generating next sequence transition

---

test/docs/OpenJ9TestUserGuide.md

- add instruction for platformRequirements

Update test user guide

---

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp

During the unsafe call transformation, the node that loads from ramStatics shares the same temp with the node that loads from the object. The sym ref for ramStatics is not collected but the sym ref used for object is collected. Therefore, they cannot share the same temp slots.
Split the blocks to add a block that calls the atomic helper that loads from ramStatics. The original atomic helper that loads from object is in another block. The return values from both helper calls are saved to the same temp.
Fixes: #15251

Fix unsafe call transformation

---

LICENSE
longabout.html
runtime/include/about.html
runtime/zlib/about.html

This should have been done with previous changes
https://github.com/eclipse-openj9/openj9/pull/16305
https://github.com/eclipse-openj9/openj9/pull/14835

Update LICENSE and about files for zlib 1.2.13, libffi

---

runtime/vm/UpcallVMHelpers.cpp

Add parentheses to the code in the upcall dispatcher

---

runtime/gc_vlhgc/MemorySubSpaceTarok.cpp
runtime/gc_vlhgc/MemorySubSpaceTarok.hpp
test/functional/cmdLineTests/criu/playlist.xml

Release free nursery pages in balanced GC

Release all free pages in balanced GC

---

runtime/compiler/optimizer/J9Inliner.cpp

Inline interface calls only when the named interface can be found

---

runtime/jvmti/jvmtiClass.c

JNI exceptions should not be pending upon return from a JVMTI function - the return value conveys success or failure.
Fixes: #16342

Clear pending exception after JVMTI class replacement

---

buildenv/jenkins/common/build.groovy
buildenv/jenkins/common/variables-functions.groovy
buildenv/jenkins/jobs/pipelines/Pipeline_Template.groovy
buildenv/jenkins/variables/defaults.yml

Update configuration for windows platform, switch bootjdk installation directory to default location (home directory) for Windows machines. Add optional error handling for intermittent failures.
Cherry pick https://github.com/eclipse-openj9/openj9/pull/16334 for 0.36

(0.36) Update OpenJ9 build for Windows

---

runtime/vm/jvminit.c

Related: https://github.com/eclipse-openj9/openj9/pull/16520#discussion_r1064751289

Assign variable after variable declaration

---

buildspecs/core.feature
buildspecs/j9.flags

Remove unused flag 'opt_openjdkThreadSupport'

---

runtime/compiler/optimizer/J9CFGSimplifier.cpp

Reverts eclipse-openj9/openj9#16459
See https://github.com/eclipse-openj9/openj9/issues/16536

Revert "Re-enable CFGSimplifier"

---

runtime/compiler/z/codegen/J9TreeEvaluator.cpp

Correctly handle residue bytes in inlineVectorizedStringIndexOf

---

test/functional/cmdLineTests/criu/criu_random.xml

- Fix cmdLineTester_criu_random_0 with JITServer
Closes: #16514
Signed-off-by: LongyuZhang <longyu.zhang@ibm.com>

Fix cmdLineTester_criu_random_0 with JITServer

---

runtime/gc_base/GCExtensions.cpp

There might be potential case that GC would happen between JVM_VirtualThreadUnmountBegin() and JVM_VirtualThreadUnmountEnd(), and last unmounted continuation Object is marked as "dead", but the related J9VMContinuation has not been freed up.
Relax the assertion for verifyContinuationList mode.
fix: https://github.com/eclipse-openj9/openj9/issues/16478

Fix assertion failure in verifyContinuationList mode

---

test/functional/Java19andUp/src/org/openj9/test/jep425/VirtualThreadTests.java

In test_VirtualthreadYieldResume, the wait time has been increased to
support the worst-case scenario where all virtual threads are executed
sequentially. The wait loop is dynamic i.e. it will exit if the virtual threads
finish early.
Fixes: #15651

Increase wait time in test_VirtualthreadYieldResume

---

LICENSE
longabout.html

Cherry pick of https://github.com/eclipse-openj9/openj9/pull/16575 for 0.36

(0.36) Update top level OpenJ9 and OMR copyright to 2023

---

runtime/gc_base/modronapi.cpp

Integrate CRIU support with new (OMR) Verbose GC APIs, invoke Verbose Manager to `prepareForCheckpoint` (close verbose logs) and `reinitializeForRestore` (reopen logs). For background, see https://github.com/eclipse/omr/pull/6850
Depends on: https://github.com/eclipse/omr/pull/6850
Fixes: https://github.com/eclipse-openj9/openj9/issues/15858

Verbose GC CRIU Support

---

runtime/jvmti/jvmtiClass.c

Fixes #16604
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/16613 for 0.36.1

(0.36.1) Only call fixHiddenOrAnonSignature in Java 17+

---

runtime/jcl/common/vm_scar.c

We allowed these changes to be merged internally, but they should have been made in the open.

Cosmetic improvements to vm_scar.c

---

jcl/src/java.base/share/classes/openj9/internal/criu/InternalCRIUSupport.java
jcl/src/java.base/share/classes/openj9/internal/criu/NotCheckpointSafe.java

* make field final
* simplify preprocessor conditions

Minor CRIU cleanup

---

runtime/compiler/net/ServerStream.cpp

Fix Misleading vlog message when using JITServer encryption.

---

buildenv/jenkins/variables/defaults.yml

Issue: https://github.com/eclipse-openj9/openj9/issues/7633.

Update openssl to version 1.1.1t

---

jcl/src/java.base/share/classes/java/lang/Class.java

Fixes https://github.com/eclipse-openj9/openj9/issues/16655

Make Class.getEnumConstantsShared() more robust

---

buildenv/jenkins/variables/defaults.yml

Issue https://github.com/eclipse-openj9/openj9/issues/15051
Change to adoptium pipelines https://github.com/ibmruntimes/temurin-build/pull/69

Build jdk8 Windows with VS 2019

---

test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestThreadMXBean.java

The comment inaccuracies were noticed reviewing #16698.

Fix a few comments

---

runtime/gc_modron_startup/mmparseXgcpolicy.cpp
runtime/nls/j9gc/j9modron.nls
test/functional/cmdLineTests/criu/playlist.xml

Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/16739

(0.38) Handle Unsupported GC policies with CRIU

---

debugtools/DDR_VM/src/com/ibm/j9ddr/AuxFieldInfo29.dat
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/J9ObjectHelper.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/GetCommandsTask.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/JavaVersionHelper.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/VirtualThreadsCommand.java

Add DDR command !vthreads to list virtual threads

---

runtime/compiler/build/files/common.mk
runtime/compiler/control/CMakeLists.txt
runtime/compiler/control/DLLMain.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/control/OptionsPostRestore.hpp

Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/16716

Initial Post Restore compiler options processing 0.38

---

runtime/jvmti/jvmtiExtensionMechanism.c

Remove unnecessary cast in jvmtiGetVirtualThread

---

runtime/criusupport/criusupport.cpp
runtime/gc_base/gc_internal.h
runtime/gc_base/modronapi.cpp
runtime/gc_modron_startup/mminit.cpp
runtime/gc_modron_startup/mmparse.cpp
runtime/gc_modron_startup/mmparse.h
runtime/nls/j9gc/j9modron.nls
runtime/oti/j9nonbuilder.h

Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/16771

GC Restore (CRIU): Introduce Restore Opts Parsing and Extend Failure (0.38)

---

runtime/jnichk/jnicbuf.c
runtime/jnichk/jnicheck.c
runtime/jnichk/jnicheck.h
runtime/jnichk/jnichk_internal.h
runtime/jnichk/jnicmem.c
runtime/jnichk/jnicwrappers.c
runtime/nls/jnck/jnichk.nls

Ensure env is not NULL when calling checked JNI functions

---

jcl/jpp_configuration.xml

Update source version for generated pConfig projects so eclipse will handle new syntax used in some places.
~(In draft mode pending distribution of an update to the eclipse plugins).~

Update jdkcompliance settings

---

runtime/jnichk/jnicbuf.c
runtime/jnichk/jnicheck.c
runtime/jnichk/jnicheck.h
runtime/jnichk/jnichk_internal.h
runtime/jnichk/jnicmem.c
runtime/jnichk/jnicwrappers.c
runtime/nls/jnck/jnichk.nls

Fixes #16665
Port of https://github.com/eclipse-openj9/openj9/pull/16760 for 0.38

(0.38) Ensure env is not NULL when calling checked JNI functions

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/DLLMain.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/control/OptionsPostRestore.hpp
runtime/compiler/control/rossa.cpp
runtime/compiler/runtime/JITServerStatisticsThread.cpp

Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/16769

Comp Threads and JIT Server options post restore 0.38

---

runtime/rasdump/dmpagent.c

Add z/TPF unique dump agent pre/post hooks.
The hooks provide access to dump agent types and dump agent identifiers.
The hooks also allow for users to provide data back to the dump agent processing.

Add z/TPF prehook and posthook dumpagent user exits

---

jcl/src/java.base/share/classes/java/lang/Access.java

Fixes #16871.
Also suppress a few warnings related to SecurityManager.

Implement JavaLangAccess.getLoaderNameID(ClassLoader)

---

runtime/vm/ContinuationHelpers.cpp

Use GC continuation list in walkAllStackFrames

---

test/functional/cmdLineTests/criu/playlist.xml

cherry-pick of https://github.com/eclipse-openj9/openj9/pull/16882

Stress CRIU GC Thread Pool Contract/Expand Routines (0.38)

---

runtime/vm/ContinuationHelpers.cpp

Addresses https://github.com/eclipse-openj9/openj9/pull/16884#discussion_r1135658099

Use PORTLIB constant

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/control/OptionsPostRestore.hpp

Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/16911 and https://github.com/eclipse-openj9/openj9/pull/16928

Post Restore Compiler Options 0.38

---

runtime/rasdump/javadump.cpp

If the restore arg list exists and is not length 0, print the restore args after user args when doing a java dump.
Move printing user args in javacore into a helper function to make it easier to print both original user args and restore args.
Port of https://github.com/eclipse-openj9/openj9/pull/16917
@tajila please review

(0.38.0) Add support for CRIU restore args in javadump

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/CoreInfoCommand.java

and also sort the environment variables.

Update jdmpview !coreinfo to print vm properties

---

runtime/gc_base/GCExtensions.hpp
runtime/gc_base/modronapi.cpp
runtime/gc_include/VerboseGCInterface.h
runtime/gc_modron_startup/GCVerboseInterface.cpp
runtime/gc_verbose_java/VerboseJava.cpp
runtime/gc_verbose_java/VerboseManagerJava.cpp
runtime/gc_verbose_java/VerboseManagerJava.hpp
runtime/oti/verbose_api.h
runtime/verbose/verbose.c

Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/16845

CRIU Verbose Logging Reinit/Reconfig for Restore (0.38)

---

runtime/gc_base/modronapi.cpp
runtime/gc_modron_startup/mminit.cpp
runtime/nls/j9gc/j9modron.nls

Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/16883

CRIU Invoke Global Collector Reinit (0.38)

---

runtime/nls/j9gc/j9modron.nls

Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/16938

Add Missing GC NLS Sample Input (0.38)

---

runtime/vm/BytecodeInterpreter.hpp

Add error handling to enterContinuationImpl

---

runtime/vm/BytecodeInterpreter.hpp

(0.37) Add error handling to enterContinuationImpl

---

runtime/compiler/aarch64/codegen/ForceRecompilationSnippet.cpp
runtime/compiler/aarch64/codegen/ForceRecompilationSnippet.hpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/control/J9Options.cpp

This commit implements EDO (exception directed optimization) for AArch64.

AArch64: Implement EDO

---

test/functional/cmdLineTests/criu/criu_nonPortable.xml

Disable method type deadlock test
Temporarily disable test while investigating cause

Disable method type deadlock test

---

buildenv/docker/aarch64-linux_CC/Dockerfile
buildenv/docker/armhf-linux_CC/Dockerfile
buildenv/docker/mkdocker.sh
buildenv/docker/test/Dockerfile

Closes https://github.com/eclipse-openj9/openj9/issues/16957

Use a non-root user in docker files

---

jcl/src/java.base/share/classes/java/lang/J9VMInternals.java

Only initialize valueObjectHashCode and positiveOnlyHashcodes once

Refactor valueHashCode to be more efficient

---

buildenv/jenkins/variables/defaults.yml

Update includes new github.com keys in known_hosts Infra issue 7871

Update to latest cent6 build container

---

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/JVMRestoreException.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/SystemCheckpointException.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/SystemRestoreException.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/package-info.java

Add package info for criu
Also update javadocs fir CRIUSupport.
Port of https://github.com/eclipse-openj9/openj9/pull/16927 for 0.38
Closes: https://github.com/eclipse-openj9/openj9/issues/16922

(0.38) Add package info for criu

---

jcl/src/openj9.dtfj/share/classes/module-info.java

Fixes https://github.com/eclipse-openj9/openj9/issues/16783
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/17064 for 0.38

(0.38) Export dtfj packages required for plugins

---

jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/ContextFactory.java
jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/commands/BaseCommand.java

Cherry-pick #17077 for the 0.38.0 release.

(0.38) Fix javadoc errors and add explicit constructors

---

runtime/bcutil/jimagereader.c

This change is made in order for the related OMR change to be merged without breaking the builds.
The related OMR change is https://github.com/eclipse/omr/pull/6940
Related to https://github.com/eclipse-openj9/openj9/pull/17073

Add temporary define of OMRPORT_MMAP_FLAG_ZOS_READ_MAPFILE

---

runtime/compiler/control/J9Options.cpp

Depends on https://github.com/eclipse/omr/pull/6934

AArch64: Enable arrayset optimizations

---

runtime/criusupport/criusupport.cpp

(0.38) Add full support for the ignore restoreargs option

(0.38) Add full support for the ignore restoreargs option

---

test/functional/cmdLineTests/variables.mk

- Fix cmdLineTests for JVM option setting
Closes #17173

Fix cmdLineTests for JVM option setting

---

runtime/oti/VMHelpers.hpp
runtime/vm/ContinuationHelpers.cpp

As part of synchronization between concurrent scanning and continuation mounting, the continuation mounting could be blocked by concurrent scanning, release vmaccess and waiting for current thread mutex, but there is timing hole between release vmaccess and enter the mutex, the notification of the mutex(the end of concurrent scanning) could be sent before the enter of current thread mutex, then cause the mounting thread would wait forever(hang).
Enter the mutex earlier in order to avoid the time hole.
fix: https://github.com/eclipse-openj9/openj9/issues/17163

Fix missing concurrent scan finish notification

---

runtime/vm/ContinuationHelpers.cpp

In weak memory model platforms, setContinuationFinished() and resetContinuationCarrierID() might be reordered during compiling or runtime, it would create a timing hole and confuse concurrent scanning, move setContinuationFinished() before readWriteBarrier() to avoid the reordering.
fix: https://github.com/eclipse-openj9/openj9/issues/17181

Avoid timing hole caused by instruction reordering

---

runtime/compiler/runtime/MethodMetaData.c

getFirstInlinedCallSiteWithByteCodeInfo can return NULL, yet the returned inlinedCallSite was being dereferenced without any checks, resulting in intermittent segmentation faults.
Closes: #14888

Add checks to prevent invalid address access in MethodMetaData

---

runtime/compiler/control/rossa.cpp

Cherry-picked from https://github.com/eclipse-openj9/openj9/pull/17132
FYI @tajila, @pshipton.

(0.38) Fix SCC AOT code validation in checkpoint-mode

---

runtime/shared_common/CacheMap.cpp
runtime/shared_common/j9shr.tdf

Add check for string length in getCachedUTFString()

---

runtime/shared_common/CacheMap.cpp
runtime/shared_common/j9shr.tdf

Port of https://github.com/eclipse-openj9/openj9/pull/17259 with appropriate copyright updates, for 0.38.

(0.38) Add check for string length in getCachedUTFString()

---

jcl/src/java.base/share/classes/java/lang/System.java

Fixes https://github.com/eclipse-openj9/openj9/issues/17248

Remove private system properties in jdk17+

---

doc/release-notes/0.38/0.38.md

Updated the release notes with the notable changes in 0.38.0 release.
[skip ci]

Update 0.38.0 release notes

---

runtime/vm/BytecodeInterpreter.hpp

If the target method of a MethodHandle INL invoked from compiled code has been compiled, the current code will run the method in the interpreter. This change will allow the compiled code to be executed.
Fixes: https://github.com/eclipse-openj9/openj9/issues/17321

Run compiled methods from MethodHandle INLs 

---

runtime/j9vm/javanextvmi.cpp
runtime/jcl/common/jclcinit.c
runtime/jcl/common/thread.cpp
runtime/jvmti/jvmtiHelpers.c
runtime/jvmti/jvmtiThread.c
runtime/jvmti/suspendhelper.cpp
runtime/oti/j9nonbuilder.h

Reverts eclipse-openj9/openj9#16943

Revert "Fix to handle suspend/resume of virtual/carrier threads"

---

runtime/oti/j9consts.h

See https://github.com/eclipse-openj9/openj9/pull/16420/files#r1185379534.

Remove unwanted, misleading comment

---

debugtools/DDR_VM/src/com/ibm/j9ddr/CompatibilityConstants29.dat
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/J9ConstantPoolCommand.java

Fix constant mapping in J9ConstantPoolCommand

---

runtime/gc_glue_java/ConfigurationDelegate.hpp

Refactor initializeHeapRegionDescriptorExtension by separating allocation and initialization of each individual object list. This results in cleaner and reusable code. These changes are part of larger changes to reinit object lists for restore (CRIU).

Refactor GC Object List Allocation/Initialization

---

runtime/j9vm/j7vmi.c
runtime/redirector/forwarders.m4

Fixes https://github.com/eclipse-openj9/openj9/issues/17389

Return false from JVM_DTraceIsSupported

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/view/dtfj/J9RASInfoBootstrapShim.java

IPv6 addresses are 16 bytes long, the pointer was being advanced as if they were only 6 bytes in length, leading to corruption noticed in https://github.com/eclipse-openj9/openj9/issues/17397#issuecomment-1545801256.
Also tidy up:
* add missing `@Override` annotations
* use `StandardCharsets`
* fix formatting

Fix handling of IPv6 addressed

---

test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeUnsafeTests.java

Dual header shape adds the ability to toggle dataAddr field based on GC policy. Enabling dual header shape toggles off dataAddr field for Gencon GC policy and disabling it toggles on the field. When toggled off, array header size with compressed refs for Gencon GC policy is 24 bytes and 16 bytes if toggled on.
Fixes: https://github.com/eclipse-openj9/openj9/issues/17359

Teach ValueTypeUnsafeTests about dual header shape

---

runtime/gc_base/GCExtensions.cpp
runtime/jcl/common/stdinit.c
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/ContinuationHelpers.cpp
runtime/vm/intfunc.c
runtime/vm/jvmfree.c
runtime/vm/jvminit.c

- Single per thread local cache to reduce need of alloc/free
- Add globalContinuationCacheArray for second tier caching
Signed-off-by: Jack Lu [Jack.S.Lu@ibm.com](mailto:Jack.S.Lu@ibm.com)

(0.39) Prototype Continuation caching

---

buildenv/jenkins/variables/defaults.yml

Issue: https://github.com/eclipse-openj9/openj9/issues/7633.

Update openssl to version 1.1.1u

---

buildenv/jenkins/common/pipeline-functions.groovy

related: https://github.com/adoptium/aqa-tests/issues/4580

Set LIGHT_WEIGHT_CHECKOUT to true

---

buildenv/jenkins/variables/defaults.yml

Cherry pick https://github.com/eclipse-openj9/openj9/pull/17468 for 0.39

(0.39) Update openssl to version 1.1.1u

---

.gitignore
doc/release-notes/0.39/0.39.md

Updated the release notes with the notable changes in 0.39.0 release.
[skip ci]

Update 0.39.0 release note

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java

The changes aim to prevent the downcall address from being
released unexpectedly by leveraging the existing code to
hold the downcall address during the downcall.
Fixes: #17524

[FFI/Jtreg_JDK20] Keep the downcall address alive for downcall (0.39)

---

runtime/rasdump/javadump.cpp

Fixed #17319
Port of https://github.com/eclipse-openj9/openj9/pull/17562 for 0.40

(0.40) Fix invalid OMR_PRI* usage on Windows

---

test/functional/cmdLineTests/jitserver/jitserverArgumentTesting.xml

See https://github.com/eclipse-openj9/openj9/issues/17572

Change JITserver Argument Testing Success Conditions

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Previously, `genSuperClassTest` checked whether the opcode of the class node representing a class is not loadaddr if a castClass is unknown at compile time and assumed that the class node was the second child of the node, which served as the first argument to the function. However, this assumption proved incorrect when the function was called from `VMarrayStoreCHKEvaluator`.
To address this issue, this commit modifies `genSuperClassTest` to accept a class node argument and perform the opcode check on that node instead.
Fixes #17581

AArch64: Add classNode argument to `genSuperClassTest`

---

runtime/vm/jvminit.c

Enable String Compression by default in OpenJ9

---

runtime/compiler/aarch64/codegen/J9SnippetDelegate.hpp
runtime/compiler/arm/codegen/J9SnippetDelegate.hpp
runtime/compiler/codegen/J9SnippetDelegate.hpp
runtime/compiler/codegen/SnippetDelegate.hpp
runtime/compiler/p/codegen/J9SnippetDelegate.hpp
runtime/compiler/x/codegen/J9SnippetDelegate.hpp
runtime/compiler/z/codegen/J9SnippetDelegate.hpp

All new J9SnippetDelegate.?pp file headers are affected.

Use correct copyright headers

---

runtime/jvmti/jvmtiHook.c

The shouldPostEvent check was missed for the JVMTI FramePop event in #16654.

Add shouldPostEvent check for JVMTI FramePop event 

---

runtime/gc_modron_startup/mminit.cpp
runtime/gc_modron_startup/mmparseXXgc.cpp

Double Deliver: https://github.com/eclipse-openj9/openj9/pull/17459

(0.40) Update Split List Forced Flag + Revert CRIU Thread Count Reinit

---

runtime/criusupport/criusupport.cpp

Related: https://github.com/eclipse-openj9/openj9/issues/15806

Fix delay checkpoint tracepoint arg

---

test/functional/Java8andUp/src/org/openj9/test/contendedfields/ContendedFieldsTests.java
test/functional/cmdLineTests/cmdLineTest_J9tests/j9tests_Java_common.xml
test/functional/cmdLineTests/cmdLineTest_J9tests/j9tests_exclude.xml
test/functional/cmdLineTests/gptest/cmdlineopttest_exclude.xml
test/functional/cmdLineTests/verboseVerification/cmdlineopttest_exclude.xml

Remove tests with -Xlockword:mode=minimizeFootprint

---

runtime/gc_base/ContinuationObjectBuffer.hpp
runtime/gc_base/OwnableSynchronizerObjectBuffer.hpp
runtime/gc_base/ReferenceObjectBuffer.hpp
runtime/gc_base/UnfinalizedObjectBuffer.hpp
runtime/gc_modron_standard/ContinuationObjectBufferStandard.cpp
runtime/gc_modron_standard/OwnableSynchronizerObjectBufferStandard.cpp
runtime/gc_modron_standard/ReferenceObjectBufferStandard.cpp
runtime/gc_modron_standard/UnfinalizedObjectBufferStandard.cpp

Double deliver: https://github.com/eclipse-openj9/openj9/pull/17648

(0.40) CRIU GC: Flush and Reset Buffers on Reinit

---

buildenv/jenkins/common/pipeline-functions.groovy

resolves: https://github.com/eclipse-openj9/openj9/issues/17697

Split sanity.openjdk into 3 parallel jobs

---

runtime/j9vm/jvm.c

Closes https://github.com/eclipse-openj9/openj9/issues/17383

JDK21 changes the units for JVM_Sleep

---

runtime/vm/BytecodeInterpreter.hpp

This change addresses a 1-2% perf regression with -Xint on
Linux IA32 and Windows AMD64 platforms for Java 8.
JIT to interpreter transition (j2iTransition) should not happen
with -Xint since the JIT is disabled.
j2iTransition code changes in https://github.com/eclipse-openj9/openj9/pull/17322 have unexpected compiler
side-effects which leads to a perf regression.
The work-around is to wrap the code changes from https://github.com/eclipse-openj9/openj9/pull/17322 with the
ifdef for OpenJDK MethodHandles (OJDK MHs) since these changes are
used IFF OJDK MHs are enabled.
Related: https://github.com/eclipse-openj9/openj9/pull/17322

Refactor changes from #17322 to resolve perf issues

---

buildenv/jenkins/common/variables-functions.groovy

Remove trailing && if present

---

runtime/compiler/compile/J9AliasBuilder.cpp

...to allow it to be deleted upstream.

Remove unnecessary use of unsafeArrayElementSymRefs()

---

runtime/compiler/runtime/MetaData.cpp
runtime/oti/j9nonbuilder.h

A prerequisite needed for https://github.com/eclipse-openj9/openj9/issues/17642

Add flag to indicate method was FSD compiled

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp

`J9::ARM64::PrivateLinkage::mapStack` does not properly align local objects without GC map index.
This commit updates `mapSingleAutomatic`, which is used from `mapStack`, to properly align local objects without GC map index. Also, `mapStack` function is changed to map 4 byte locals first, then 8 byte locals, and finally locals with size > 8 bytes.

AArch64: Align local objects to object alignment boundary

---

test/functional/cmdLineTests/jvmtitests/jvmtitests_excludes_22.xml

Added `jvmtitests_excludes_22.xml`

Add jvmtitests_excludes_22.xml

---

buildenv/jenkins/variables/defaults.yml

Port of https://github.com/eclipse-openj9/openj9/pull/17895 for 0.40

(0.40) Update to OpenSSL 1.1.1v

---

test/TestConfig/resources/excludes/latest_exclude_22.txt

JDK22 adds `latest_exclude_22.txt`

JDK22 adds latest_exclude_22.txt

---

runtime/jvmti/jvmtiStackFrame.c

JVMTI GetAllStackTraces only tracks live platform threads.
This change correctly and consistently derives the threadObject
from J9VMThread->carrierThreadObject in GetAllStackTraces for JDK19+.
Currently, J9VMThread->threadObject is used in some places, which is
incorrect since it can also point to a virtual thread.
Related: #17868

[JDK19+] Fix JVMTI GetAllStackTraces

---

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/Attachment.java
runtime/vm/bindnatv.cpp

Also correct javadoc for Attachment.loadAgentLibraryImpl().

Correct signature of Attachment.loadAgentLibraryImpl() in bindnatv.cpp

---

runtime/compiler/optimizer/J9Inliner.cpp

The code in J9Inliner.cpp that implemented certain heuristics to choose a class to inline based on profiling missed adding some SVM validations. This PR fixes this by wrapping the code that finds a candidate class in a heuristic region, and then adding the necessary profiled class and instanceof validations.
These heuristics are also disabled for non-SVM AOT. Normally this code is implicitly disabled as it only runs post-startup; however, it is possible for the VM to transition from startup to notstartup in the middle of a compilation, which could result in this code running in a non-SVM compilation which is not capable of generating the necessary validations.
Fixes https://github.com/eclipse-openj9/openj9/issues/17736

Fix SVM Assert caused by missing class validation

---

runtime/compiler/control/JITClientCompilationThread.cpp

Add missing break statement for switch case

---

test/functional/Valhalla/playlist.xml
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeGenerator.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeTests.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaUtils.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeGenerator.java
test/functional/Valhalla/testng.xml

Related to https://github.com/eclipse-openj9/openj9/issues/17234 https://github.com/eclipse-openj9/openj9/issues/17340 
This is the final change for the preload attribute
Fixes: https://github.com/eclipse-openj9/openj9/issues/17233

Preload tests + support for all Valhalla attributes

---

runtime/bcutil/test/dyntest/romclass_correctness.c

Discovered while reviewing #17788.

Remove unused TEST_xxx macros

---

README.md

The `beginner` label is not used.

Update README to refer to the "good first issue" label

---

runtime/bcutil/ClassFileWriter.cpp
runtime/cfdumper/main.c
runtime/util/rcdump.c
runtime/util/romclasswalk.c

I also added the value class modifier for classes and implicit modifier for <vnew>.
Related to https://github.com/eclipse-openj9/openj9/issues/17234

cfdump support for Valhalla ImplicitCreation Attribute

---

debugtools/DDR_VM/src/com/ibm/j9ddr/CompatibilityConstants29.dat
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/OptInfo.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/J9ROMClassHelper.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/RomClassWalker.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/J9BCUtil.java

Related to https://github.com/eclipse-openj9/openj9/issues/17234.

DDR support for Valhalla ImplicitCreation attribute

---

runtime/cfdumper/main.c

Fixes: https://github.com/eclipse-openj9/openj9/issues/17234

Fix ImplicitCreation cfdump support

---

runtime/compiler/runtime/ClassUnloadAssumption.cpp

Reverting per comments from @mpirvu in [issue 17734](https://github.com/eclipse-openj9/openj9/issues/17734#issuecomment-1691515317)

Revert "Update the assert to allow TR_UnloadedClassPicSite"

---

runtime/compiler/optimizer/IdiomRecognition.cpp

See eclipse/omr#7082
Depends on: eclipse/omr#7082

Refactor SupportsConst(I|L)Div to Supports(I|L)MulHigh

---

NOTICES.md

Closes https://github.com/eclipse-openj9/openj9/issues/18023

Add protobuf to the NOTICES.md

---

test/functional/cmdLineTests/fips/playlist.xml
test/functional/cmdLineTests/openssl/playlist.xml

- change FIPS to FIPS140_2
related: backlog/issues/1188

Update feature tag

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy

solves the issue after adding PR link

resolve personal builds jenkins issue

---

debugtools/DDR_VM/src/com/ibm/j9ddr/CompatibilityConstants29.dat
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/LinearDumper.java

Print NullRestricted flag for ddr classAndFlags

---

runtime/vm/jvminit.c

Backport of https://github.com/eclipse-openj9/openj9/pull/18085 to the 0.41 release branch.
JVM init path: `J9_CreateJavaVM`.
JVM exit paths: `protectedDestroyJavaVM` and `exitJavaVM`.
A segfault or other side-effects can happen if the JVM init and
exit paths execute concurrently.
The exit path can be taken if a shutdown signal is raised and the
shutdown handler is invoked. JVM shutdown signals are `SIGINT`, `SIGTERM`
and `SIGHUP`.
Preventing invocation of the exit path from the shutdown signal handler
until the JVM initialization completes resolves the above side-effects.
Related:
- #17101
- #17438

(0.41) Don't invoke shutdown signal handler until JVM init completes

---

test/functional/cmdLineTests/fips/playlist.xml
test/functional/cmdLineTests/openssl/playlist.xml

(v0.41.0-release) Update feature tag

---

runtime/vm/ContinuationHelpers.cpp
runtime/vm/jvminit.c

replace printf with j9tty_printf to remove platform specific modifiers

Updates Continuation profiling to use j9time_hires_clock

---

doc/release-notes/0.41/0.41.md

Created a draft release note for 0.41.0 release.
[skip ci]

Create draft 0.41.0 release note

---

buildenv/jenkins/variables/defaults.yml

Cherry pick of https://github.com/eclipse-openj9/openj9/pull/18108 for 0.41

(0.41) Update OpenSSL version to include fix for CVE-2023-4807

---

NOTICES.md

Cherry pick of the following for 0.41
https://github.com/eclipse-openj9/openj9/pull/18022
https://github.com/eclipse-openj9/openj9/pull/18029

(0.41) Add third party content to NOTICES.md

---

buildenv/jenkins/variables/defaults.yml

Change "ppc64_aix_linux" to "ppc64_aix"

AIX Valhalla builds should extend ppc64_aix

---

runtime/include/zconf.h
runtime/include/zlib.h
runtime/zlib/adler32.c
runtime/zlib/compress.c
runtime/zlib/crc32.c
runtime/zlib/deflate.c
runtime/zlib/deflate.h
runtime/zlib/gzguts.h
runtime/zlib/infback.c
runtime/zlib/inffast.c
runtime/zlib/inffast.h
runtime/zlib/inflate.c
runtime/zlib/inftrees.c
runtime/zlib/inftrees.h
runtime/zlib/trees.c
runtime/zlib/uncompr.c
runtime/zlib/zutil.c
runtime/zlib/zutil.h

Related https://github.com/eclipse-openj9/openj9/issues/17493

Update to zlib 1.3 to remove warnings from Clang in latest Xcode

---

buildenv/jenkins/variables/defaults.yml

Cherry-pick #18161 for the 0.41.0 release.

Update to openssl 3.0.11

---

doc/release-notes/0.41/0.41.md

Updated the release note for 0.41.0 release.
[skip ci]

Update 0.41.0 release note

---

runtime/cmake/J9vmGenAsm.cmake
runtime/jilgen/CMakeLists.txt

Addresses part of the problem described in #18232.

Ensure constgen is up-to-date before running it

---

runtime/jcl/common/thread.cpp

Addresses the post-merge feedback from #18255.

Remove the redundant check from the assertion

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy

Issue https://github.com/eclipse-openj9/openj9/issues/18111

In PR testing redefine `all` to exclude UNB platforms

---

test/functional/Valhalla/src_lw5/org/openj9/test/lworld/ValueTypeSystemArraycopyTests.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeSystemArraycopyTests.java

Modify tests to compile with lw5
Related https://github.com/eclipse-openj9/openj9/issues/18157

Split ValueTypeSystemArraycopyTests to src_lw5 and src_qtypes folders

---

test/functional/Java9andUp/src/org/openj9/test/stackWalker/StackWalkerTest.java

This should have been included in #18145.

Correct expected number of StackWalker options

---

jcl/src/java.base/share/classes/java/lang/System.java

Issue https://github.com/eclipse-openj9/openj9/issues/18401

jdk8,11 Ignore "allow" and "disallow" set in java.security.manager

---

buildspecs/linux_ppc-64_cmprssptrs_le.spec
buildspecs/linux_ppc-64_le.spec

Tested via [internal build](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=60306)

Compile IBM Java 8 plinux LE with gcc 11.2

---

runtime/gc_modron_startup/mgcalloc.cpp

Fixing compilation problem on AIX and Linux PPC BE

Fixing compilation problem

---

runtime/jvmti/jvmtiHelpers.c

Related: https://github.com/eclipse-openj9/openj9/pull/18421#discussion_r1389651213

Remove fall through comments from case statements with no code

---

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit adds vectorized String.hashCode() implementation to AArch64 code generator.

AArch64: Add vectorized String.hashCode() implementation

---

jcl/src/java.base/share/classes/com/ibm/oti/reflect/TypeAnnotationParser.java
jcl/src/java.base/share/classes/com/ibm/oti/vm/VM.java
jcl/src/java.base/share/classes/java/lang/Class.java
runtime/jcl/common/reflecthelp.c

Port to 0.42.0 release from https://github.com/eclipse-openj9/openj9/pull/18437

0.42.0: Append cp to method and field annotation data to fix redefinition inconsistencies

---

runtime/j9vm/javanextvmi.cpp
runtime/jvmti/CMakeLists.txt
runtime/jvmti/jvmtiHelpers.cpp
runtime/jvmti/jvmtiThread.cpp
runtime/jvmti/jvmti_internal.h
runtime/oti/vmconstantpool.xml

Backporting the following PRs:
- #18460
- #18459
- #18453

[0.43] Virtual Thread Support

---

test/functional/cmdLineTests/criu/src/org/openj9/criu/JDK11UpTimeoutAdjustmentTest.java

`CRIU` ensures the test thread prints `pass/fail` messages
close https://github.com/eclipse-openj9/openj9/issues/17909

CRIU ensures the test thread prints pass/fail messages

---

test/functional/cmdLineTests/criu/src/org/openj9/criu/TimeChangeTest.java

Fix 0.42 CRIU test compilation error

Fix 0.42 CRIU test compilation error

---

jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/CompilationMXBeanImpl.java
runtime/include/vmi.h
runtime/jcl/common/system.c
runtime/nls/j9cl/j9jcl.nls
runtime/util/vmargs.c
runtime/vm/jvminit.c
runtime/vm/vmifunc.c
runtime/vm/vmprops.c
test/functional/Java8andUp/src/org/openj9/test/vmArguments/VmArgumentTests.java

Issue https://github.com/eclipse-openj9/openj9/issues/18430
Cherry pick https://github.com/eclipse-openj9/openj9/pull/18582 for 0.42

(0.42) The java.compiler system property is obsolete in jdk21+

---

doc/release-notes/0.42/0.42.md

Created the release note for 0.42.0 release.
[skip ci]

Release note for 0.42.0 release

---

buildenv/docker/mkdocker.sh

* install CRIU support (except on Ubuntu 20.04)
* don't try to install non-existent libstdc++-static on CentOS:6
* update supported JDK versions
* remove redundant distribution check for CRIU on s390x
* limit CRIU support on s390x to Ubuntu 18.04

Docker: add support for Ubuntu 22.04

---

buildenv/jenkins/variables/defaults.yml

See
https://github.com/eclipse-openj9/openj9/pull/18724
https://github.com/eclipse-openj9/openj9/pull/18759

(0.43) Update OpenSSL to include CVE-2023-6129, CVE-2023-6237

---

NOTICES.md

Cherry pick of https://github.com/eclipse-openj9/openj9/pull/18785 for 0.43

(0.43) Update CRIU version to 3.18 in NOTICES

---

LICENSE
longabout.html
runtime/include/about.html

Cherry pick of https://github.com/eclipse-openj9/openj9/pull/18784 for 0.43

(0.43) Fix the zlib copyright to match the 1.2.13 version

---

jcl/src/java.base/share/classes/jdk/crac/Context.java
jcl/src/java.base/share/classes/module-info.java.extra
jcl/src/java.base/share/classes/openj9/internal/criu/InternalCRIUSupport.java

CRIU `jdk.crac` `API` follow-up changes

CRIU jdk.crac API follow-up changes

---

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/codegen/J9AheadOfTimeCompile.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/env/SharedCache.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/runtime/IProfiler.cpp
runtime/compiler/runtime/JITServerAOTDeserializer.cpp

This reverts commit 2abc8e7e63d05a07d1c97f7a04ffd91970b11226.

Revert "Modify SCC frontend to take class parameter"

---

buildenv/jenkins/variables/defaults.yml

Port of https://github.com/eclipse-openj9/openj9/pull/18852 to 0.43

(0.43) Update to openssl 3.0.13

---

doc/release-notes/0.43/0.43.md

Created the release note for 0.43.0 release.
[skip ci]

Release note for 0.43.0 release

---

runtime/vm/arm64cinterp.m4

See https://github.com/eclipse-openj9/openj9/pull/18903/files#r1481562770.

Add missing closing parenthesis

---

test/functional/DDR_Test/tck_ddrext.xml

Also move property definitions closer to where they're used.

Prefer <condition> over <if> for conditional properties

---

runtime/nls/j9gc/j9modron.nls

Adding periods at the end of messages

Minor corrections for checkpointthreads NLS

---

runtime/util/resolvehelp.c

From JVMS: If the symbolic reference names a class (not an interface), then
that class is a superclass of the current class.
Previously the algorithm for finding the invoked method for invokespecial
assumes that the class named through the bytecode symbolic reference is the
current class when it is actually the superclass of the current class. By
doing this it skips searching direct interfaces of the referenced class for
default interface methods.
Fixes: https://github.com/eclipse-openj9/openj9/issues/18705

 Treat invokespecial symbolic reference as superclass in method search

---

runtime/jcl/common/java_lang_StackWalker.cpp

Fix StackWalker.walkWrapperImpl walkState structure access

---

runtime/oti/j9nonbuilder.h

Addresses https://github.com/eclipse-openj9/openj9/pull/18964#discussion_r1492842191.
Related: #18964

Fix indentation: J9JavaVM.vThreadInterrupt

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/env/j9method.cpp

This reverts commit 4335656433ae2f13c98911fd02e6c014af79d410.
Fixes:  #18979

Revert "Recognize java/lang/StringCoding.implEncodeAsciiArray"

---

jcl/src/java.base/share/classes/module-info.java.extra
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/ManagementUtils.java
jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/PlatformMBeanProvider.java
jcl/src/jdk.management/share/classes/jdk/crac/management/CRaCMXBean.java
jcl/src/jdk.management/share/classes/jdk/crac/management/CRaCMXBeanImpl.java
jcl/src/jdk.management/share/classes/jdk/crac/management/package-info.java
test/functional/JLM_Tests/build.xml
test/functional/JLM_Tests/playlist.xml
test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestCRaCMXBean.java
test/functional/JLM_Tests/testng.xml
test/functional/cmdLineTests/criu/cracScript.sh
test/functional/cmdLineTests/criu/criu_nonPortable_jdk_crac.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestJDKCRAC.java

Add CRaCMXBean API to get the restore time and the uptime
since restore.
Issue: https://github.com/eclipse-openj9/openj9/issues/18842

Add CRaCMXBean API

---

test/functional/cmdLineTests/criu/criu_nonPortable.xml

Fixes: https://github.com/eclipse-openj9/openj9/issues/19003

Fix CRIU ghost file test

---

runtime/compiler/env/ClassLoaderTable.cpp

In `copyJ9UTF8()`, we now avoid throwing `std::bad_alloc()` if memory for a copy of a ROM class's name could not be allocated. We instead do not store the `TR_ClassLoaderInfo` for that class in the `_nameTable` in such situations. This parallels the treatment of the class loader info if a chain for the loader could not be found in the SCC.

Do not throw in ClassLoaderTable

---

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit adds accelerated implementation of StringLatin1.inflate to AArch64 codegen.

AArch64: Accelerate StringLatin1.inflate

---

runtime/ddr/vmddrstructs.properties

Validated in internal build 67120.

Remove duplicate typeoverride entries

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/compile/J9SymbolReferenceTable.hpp
runtime/compiler/ilgen/J9ByteCodeIlGenerator.hpp
runtime/compiler/ilgen/Walker.cpp

JIT must narrow byte/short/char before storing

---

test/functional/Java8andUp/playlist.xml

Issue https://github.com/eclipse-openj9/openj9/issues/19116

Exclude JCL_TEST_Java-Security on AIX

---

test/functional/cmdLineTests/criu/criuSoftmxScript.sh
test/functional/cmdLineTests/criu/criu_softmx.xml
test/functional/cmdLineTests/criu/playlist.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/SoftmxTest.java

Add supporting test cases and related testing scripts.
Softmx functionalities: https://github.com/eclipse-openj9/openj9/pull/18168
Functional changes: https://github.com/eclipse-openj9/openj9/pull/19037

CRIU Restore Softmx Functional Tests

---

jcl/src/java.base/share/classes/openj9/internal/criu/InternalCRIUSupport.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/SystemCheckpointException.java
runtime/jcl/common/criu.cpp
runtime/oti/j9nonbuilder.h
runtime/oti/jclprots.h
runtime/oti/vm_api.h
runtime/vm/CRIUHelpers.cpp
test/functional/cmdLineTests/criu/cracScript.sh
test/functional/cmdLineTests/criu/criuScript.sh
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/CRIUTestUtils.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestGhostFile.java

Orignal PRs:
https://github.com/eclipse-openj9/openj9/pull/19030
https://github.com/eclipse-openj9/openj9/pull/18945

(0.44) Add ghost file limit API

---

runtime/compiler/ilgen/Walker.cpp

When running on weakly ordered machines like PPC or AArch64 it is possible for non-final fields to be seen as NULL by other thread even when the fields are initialized by the constructor (`<init>`). In such cases it's up to the java program to use some sort of ordering mechanism if the results of the `<init>` must be seen by other threads before those threads are allowed to see the new object.
For StringBuffer and StringBuilder the JIT is removing null-checks to improve performance and therefore it is possible (for programs that fail to properly enforce ordering when multiple threads can see a new StringBuffer/StringBuilder instances) to crash trying to write to NULL.
One possible solution is to stop removing null-checks for those object types, but that would introduce a performance loss …

Ensure visibility of post-<init> field values for StringBuffer/Builder

---

runtime/compiler/z/codegen/J9TreeEvaluator.cpp

The TR_USEDUALTLH was introduced to block non zero init in TLH until performance analysis was done.
This never meant to be permanent and this PR removes it.

Z: Remove TR_USEDUALTLH env var

---

runtime/vm/vmprops.c

On Linux the encoding of the terminal seems to be unknown and isn't necessarily `locale charmap`. When converting command line arguments and the conversion fails using the default encoding, try UTF8 as well.
OpenJDK accepts UTF8 input.
A way to test this is to have a locale such as `zh_CN.gb18030` installed, and then run `LANG=zh_CN.gb18030 java -Dzz=〢€郎嗀秊㐀龦 -XshowSettings:properties -version`. The zz= characters should be UTF8 encoded. In a terminal using UTF8, and without this change the JVM fails to start with `Error: Could not create the Java Virtual Machine.`.

Fallback to UTF8 converting command line arguments

---

runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/VectorAPIExpansion.cpp

- add new parameter to load and store intrinsics
Related
https://github.com/eclipse-openj9/openj9/issues/18704
https://github.com/eclipse-openj9/openj9/issues/19078

Enable VectorAPI in Java 22

---

runtime/vm/vmprops.c

* invert an if statement to avoid repeating a test
* use `J9_ARE_ANY_BITS_SET()` instead of `J9_ARE_ALL_BITS_SET()` for testing a single bit
Noticed while reviewing #19185.

Minor improvements to vmprops.c

---

runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/VectorAPIExpansion.cpp

Port of https://github.com/eclipse-openj9/openj9/pull/18965

(0.44) Enable VectorAPI in Java 22

---

test/functional/cmdLineTests/criu/criu_nonPortable.xml

Related to: https://github.com/eclipse-openj9/openj9/issues/19181

Disable CRIU failure paths test

---

runtime/compiler/ilgen/Walker.cpp

Add default: label to a switch statement

---

buildspecs/core.feature
buildspecs/j9.flags
runtime/cmake/options.cmake
runtime/include/j9cfg.h.in

Port of https://github.com/eclipse-openj9/openj9/pull/19212

(0.44) Add JFR flags

---

doc/compiler/control/CheckpointRestoreCoordination.md
runtime/compiler/build/files/common.mk
runtime/compiler/control/CMakeLists.txt
runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/control/OptionsPostRestore.hpp
runtime/compiler/runtime/CMakeLists.txt
runtime/compiler/runtime/CRRuntime.cpp
runtime/compiler/runtime/CRRuntime.hpp
runtime/compiler/runtime/IProfiler.cpp

* Refactor Checkpoint/Restore code into its own class
* Add CR Runtime Thread
Parent issue: https://github.com/eclipse-openj9/openj9/issues/18866

Refactor Checkpoint/Restore Code into its own class

---

runtime/compiler/runtime/Runtime.cpp
runtime/compiler/x/codegen/AllocPrefetchSnippet.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/runtime/X86Codert.nasm

x86: Remove deprecated TR_EnableNewX86PrefetchTLH

---

runtime/vm/jvminit.c

When using the JITServer AOT cache and ignoring the local SCC, portable AOT is now enabled by default only if the JVM is running in a container, and only if there is no explicit `-XX:[+|-]PortableSharedCache` option present on the command line.
The `-XX:[+|-]PortableSharedCache` options are also now honoured when using the JITServer AOT cache (having the effect of explicitly enabling or disabling portable AOT) even if the SCC is disabled.

Refine JITServer AOT cache flag setting

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

To revert (more or less) to the old behavior, define the following environment variable: `TR_NodeEstimateNumerator=1`
The default value for the above knob is 4 for warm compilations and 1 for compilations performed at hot (or above) opt level.

Tweak inliner to improve compilation overhead

---

jcl/src/openj9.dtfj/share/classes/com/ibm/jvm/j9/dump/extract/Main.java

A new entry in the archive, `execution-log.txt` mirrors the output produced by running `jpackcore`, except for the line of the form
```
VM set to 00007F7BB00131F0
```
which is produced by native code, and the final line of output
```
jextract complete.
```
A sample `execution-log.txt` follows:
```
Execution log
=============
Loading dump file...
Read memory image from core.20240405.124341.94634.0001.dmp
Creating archive file: pack.zip
Adding "excluded-files.txt"
Adding "/lib/x86_64-linux-gnu/libz.so.1"
Adding "/lib/x86_64-linux-gnu/libnss_files.so.2"
Adding "/home/keithc/space/openj9/jdk21/build/normal/images/jdk/lib/default/libj9thr29.so"
Adding "/lib/x86_64-linux-gnu/libnsl.so.1"
Adding "/home/keithc/space/openj9/jdk21/build/normal/images/jdk/lib/default/libj9shr29.so"
Adding …
```

Include diagnostics in archive produced by jpackcore

---

buildenv/jenkins/variables/defaults.yml

Cherry pick https://github.com/eclipse-openj9/openj9/pull/19286 for 0.45

Update OpenSSL to include the fix for CVE-2024-2511

---

runtime/gc_base/StringTable.cpp
test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_String.java

Updates j9gc_createJavaLangString().
Issue https://github.com/eclipse-openj9/openj9/issues/19273

(0.45) Fix String creation to treat a modified UTF8 zero as ASCII

---

doc/release-notes/0.41/0.41.md
doc/release-notes/0.44/0.44.md

Created the release note for 0.44.0 release with the available issue details. Updated 0.41.0 release note based on a change documented in 0.44.0 release
[skip ci]

Release note for 0.44.0 release

---

jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/corereaders/NewElfDump.java
runtime/compiler/optimizer/SequentialStoreSimplifier.cpp
runtime/nls/verb/verbose.nls
runtime/nls/verb/verbose_ca.nls
runtime/nls/verb/verbose_cs.nls
runtime/nls/verb/verbose_de.nls
runtime/nls/verb/verbose_es.nls
runtime/nls/verb/verbose_fr.nls
runtime/nls/verb/verbose_hu.nls
runtime/nls/verb/verbose_it.nls
runtime/nls/verb/verbose_ja.nls
runtime/nls/verb/verbose_ko.nls
runtime/nls/verb/verbose_pl.nls
runtime/nls/verb/verbose_pt_BR.nls
runtime/nls/verb/verbose_ru.nls
runtime/nls/verb/verbose_sk.nls
runtime/nls/verb/verbose_sl.nls
runtime/nls/verb/verbose_tr.nls
runtime/nls/verb/verbose_zh.nls
runtime/nls/verb/verbose_zh_CN.nls
runtime/nls/verb/verbose_zh_TW.nls

Fix 49 typos in 21 files

---

runtime/gc_modron_startup/arrayCopy.cpp

Use native C++ data types, refactor functions for single return point, etc.

Cleaning arrayCopy.cpp

---

runtime/compiler/runtime/J9CodeCacheManager.cpp

The JIT attempts to allocate its code cache repository in close proximity of the JIT dll to avoid helper trampolines. 
A. If large pages are not used, the JIT requests an allocation in specified range with `J9PORT_VMEM_ADDRESS_HINT`. This performs a single mmap call and typically succeeds. If the call above did not reserve memory in the desired range, we unmap and then instruct the VM to use a "quick" method based on smaps. If that fails too, we ask for an allocation anywhere. 
B. If large pages are used, the JIT requests an allocation in the desired range and may repeat this allocation request after advancing the start address by one page each time it fails. If we still didn't allocate a segment in the desired region, we ask for an allocation anywhere.
The problem fixed by this commit …

Improve code cache allocation time

---

test/functional/Java9andUp/playlist.xml
test/functional/cmdLineTests/reflectCache/playlist.xml

Issues
https://github.com/eclipse-openj9/openj9/issues/19300
https://github.com/eclipse-openj9/openj9/issues/19301
https://github.com/eclipse-openj9/openj9/issues/19302
Testing via grinder
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3503 - passed

Temporarily exclude tests failing on jdk23

---

buildenv/jenkins/variables/defaults.yml

Avoid all-too-frequent build failures:
```
IOException caught during compilation: Deadlock condition if locked
```

Disable javac server on ppc64_aix

---

runtime/gc_base/ClassLoaderManager.cpp

Remove unnecessary spaces in MM_ClassloaderManager class

---

runtime/vm/createramclass.cpp

Fixes: https://github.com/eclipse-openj9/openj9/issues/19119

Ignore loading errors during value class preload

---

buildenv/jenkins/variables/defaults.yml
doc/build-instructions/Build_Instructions_V11.md
doc/build-instructions/Build_Instructions_V17.md
doc/build-instructions/Build_Instructions_V21.md
doc/build-instructions/Build_Instructions_V8.md

* avoid non-standard options `--openssl-version` and `--openssl-repo`
* update build configurations
* update build instructions

Use standard get_source.sh options

---

runtime/oti/j9consts.h
runtime/oti/j9nonbuilder.h
runtime/vm/jfr.cpp
runtime/vm/jvminit.c
runtime/vm/vm_internal.h

- thread local buffer management
- execution sample event

Early JFR framework

---

runtime/vm/CMakeLists.txt
runtime/vm/vm_internal.h

`JFR` `CMake` adds `jfr.cpp`
closes https://github.com/eclipse-openj9/openj9/issues/19431

JFR CMake adds jfr.cpp

---

buildenv/jenkins/variables/defaults.yml

Hopefully temporary until the machines at
UNB are restored.
Infra Issue 9282

Remove UNB Artifactory from builds

---

runtime/compiler/optimizer/J9ValuePropagation.cpp

The implementations of `String.indexOf` operations cast the target char to a byte if Latin-1 encoded Strings are involved.  The value might be cast to type byte by the caller or in the implementation itself, depending of the version of the JDK involved.  Value Propagation has to ensure that it uses signed byte comparisons if it transforms an `indexOf` involving a known `String`.
Fixes:  #18974

Use signed comparisons for Latin-1 encoded indexOf

---

runtime/compiler/runtime/DataCache.cpp

A `TR_VerboseLog::CriticalSection` is not acquired by this point in the function, so this log line should be writeLineLocked and not writeLine.

Replace writeLine usage with writeLineLocked

---

test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestManagementFactory.java

Issue https://github.com/eclipse-openj9/openj9/issues/18920
Test grinder https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3596/

Add debug output to testThreadMXBeanProxy

---

doc/release-notes/0.45/0.45.md

Created the release note for 0.45.0 release.
[skip ci]

Release note for 0.45.0 release

---

runtime/oti/j9nonbuilder.h
runtime/vm/jfr.cpp
runtime/vm/vm_internal.h

- global buffer management
- buffer walking API

Ongoing JFR work

---

buildenv/jenkins/variables/defaults.yml

Cherry pick of https://github.com/eclipse-openj9/openj9/pull/19571

(0.46) Update OpenSSL 3.0.13 to include CVE-2024-4741

---

jcl/src/java.base/share/classes/com/ibm/jit/JITHelpers.java
jcl/src/java.base/share/classes/java/lang/String.java
test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_String.java

Issue https://github.com/eclipse-openj9/openj9/issues/19543
Port of https://github.com/eclipse-openj9/openj9/pull/19565

(0.46) jdk11 always create compact Strings when possible

---

longabout.html
runtime/include/about.html
runtime/include/zconf.h
runtime/include/zlib.h
runtime/zlib/about.html
runtime/zlib/deflate.c
runtime/zlib/deflate.h
runtime/zlib/gzguts.h
runtime/zlib/inflate.c
runtime/zlib/inftrees.c
runtime/zlib/inftrees.h
runtime/zlib/trees.c
runtime/zlib/zutil.h

Issue https://github.com/eclipse-openj9/openj9/issues/19450
Compiling jdk11 on all platforms (except plinux)
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/532/
IBM Java 8 compiles worked, build 72176.

Update zlib to 1.3.1

---

README.md

Issue: https://github.com/eclipse-openj9/openj9/issues/19616
Co-authored-by: Henry Zongaro <zongaro@ca.ibm.com>
Co-authored-by: Tobi Ajila <atobia@ca.ibm.com>

Update the information in contributing to the project

---

buildenv/jenkins/variables/defaults.yml

See https://github.com/openssl/openssl/releases/tag/openssl-3.0.14.

Update to openssl 3.0.14

---

longabout.html
runtime/include/about.html
runtime/include/zconf.h
runtime/include/zlib.h
runtime/zlib/about.html
runtime/zlib/deflate.c
runtime/zlib/deflate.h
runtime/zlib/gzguts.h
runtime/zlib/inflate.c
runtime/zlib/inftrees.c
runtime/zlib/inftrees.h
runtime/zlib/trees.c
runtime/zlib/zutil.h

Issue https://github.com/eclipse-openj9/openj9/issues/19450
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/19612

(0.46) Update zlib to 1.3.1

---

jcl/src/java.base/share/classes/java/lang/Class.java
runtime/bcutil/cfreader.c
runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
runtime/vm/createramclass.cpp

These commits are ported from https://github.com/eclipse-openj9/openj9/pull/18558
Related to https://github.com/eclipse-openj9/openj9/issues/18157 https://github.com/eclipse-openj9/openj9/issues/18316 https://github.com/eclipse-openj9/openj9/issues/19459

VM updates for NullRestricted value types

---

runtime/gc_trace/TgcAllocation.cpp

Print pre-thread refresh and remaining size of TLHs for both zero and non-zero case.

TGC alloc stats for dual TLH

---

runtime/shared/shrclssup.c
test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-1.xml

Make option -Xshareclasses enable -XX:+ShareOrphans

---

buildspecs/aix_ppc-64_cmprssptrs.spec
buildspecs/j9.flags
buildspecs/linux_390-64_cmprssptrs.spec
buildspecs/linux_ppc-64_cmprssptrs_le.spec
buildspecs/linux_riscv64.spec
buildspecs/linux_riscv64_cmprssptrs.spec
buildspecs/linux_riscv64_cmprssptrs_cross.spec
buildspecs/linux_riscv64_cross.spec
buildspecs/linux_x86-64_cmprssptrs.spec
buildspecs/osx_x86-64_cmprssptrs.spec
buildspecs/win_x86-64_cmprssptrs.spec

Related to https://github.com/eclipse-openj9/openj9/pull/19698

Delete the unused build flag build_openj9JDK8

---

test/functional/RasapiTest/src/com/ibm/trace/tests/apptrace/TestJavaCoreAndSnap.java

Avoid NPE and AIOOBE exceptions in TestJavaCoreAndSnap

---

test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestManagementFactory.java

Related to https://github.com/eclipse-openj9/openj9/pull/19505
Issue https://github.com/eclipse-openj9/openj9/issues/18920

Avoid NPE in testThreadMXBeanProxy debug output

---

runtime/bcutil/ClassFileOracle.cpp
runtime/bcutil/ClassFileWriter.cpp
runtime/bcverify/bcverify.c
runtime/cfdumper/main.c
runtime/jcl/common/reflecthelp.c
runtime/jnichk/jnicbuf.c
runtime/jnichk/jnicheck.c
runtime/jvmti/jvmtiForceEarlyReturn.cpp
runtime/jvmti/jvmtiHelpers.cpp
runtime/jvmti/jvmtiLocalVariable.cpp
runtime/rastrace/method_trace.c
runtime/tests/jvmtitests/agent/strings.c
runtime/util/sendslot.c
runtime/verutil/chverify.c
runtime/vm/classsupport.c
runtime/vm/extendedMessageNPE.cpp
runtime/vm/jnicsup.cpp
runtime/vm/resolvesupport.cpp

Remove some value type q cases

---

runtime/compiler/optimizer/UnsafeFastPath.cpp

Transforming unsafe accesses to array accesses when a `ByteBufferHandle` operation method is on the inline call stack erroneously allows a read-only buffer to be mutated on big-endian systems. The `indexRO()` method checks for read-only buffers by loading the `ByteBuffer.isReadOnly` field with `Unsafe`. That's a boolean, which in an array would occupy one byte, but in a field it occupies four. Treating the load as an array access means that we only load the first byte, which on a big-endian system is the high byte and therefore always zero.
Fixes #19693

Ignore ByteBufferHandle operations in unsafe fast path

---

buildenv/jenkins/common/build.groovy

Enables the pipeline to fetch from dockerhub and other registries Infra issue 9128
Signed-off-by: Mahdi Ardekanian <mahdi@ibm.com>

Adds compatibility to get docker image from non-default registry

---

runtime/vm/segment.c

This PR fixes the logic that ensures file backed memory to include code cache segments. `allocateFixedMemorySegmentInList` is not invoked when allocating the code cache repository; `allocateMemoryForSegment` is. However, `allocateMemoryForSegment` is also invoked by `allocateFixedMemorySegmentInList`. Therefore, moving the logic to allocate file backed memory to `allocateMemoryForSegment` covers all memory types that need it.

Fix disclaiming logic to include code cache segments

---

runtime/bcverify/staticverify.c
runtime/codert_vm/decomp.cpp
runtime/codert_vm/jswalk.c
runtime/oti/vm_api.h
runtime/util/fieldutil.c
runtime/vm/ObjectFieldInfo.cpp
runtime/vm/ValueTypeHelpers.hpp
runtime/vm/bindnatv.cpp
runtime/vm/createramclass.cpp
runtime/vm/description.c
runtime/vm/resolvefield.cpp
runtime/vm/resolvesupport.cpp

Remove more q type cases and comments

---

runtime/j9vm/exports.cmake
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/javanextvmi.cpp
runtime/redirector/forwarders.m4

Add a stub for JVM_IsContainerized

---

runtime/vm/swalk.c

A segfault was observed with `-verbose:stackwalk=0` in #19744 where
`walkState->userData4` was `NULL`.

Add a NULL check for walkState->userData4

---

test/functional/cmdLineTests/jvmtitests/jvmtitests_hcr.xml

Related to https://github.com/eclipse-openj9/openj9/pull/19710
Issue https://github.com/eclipse-openj9/openj9/issues/19765
Issue https://github.com/eclipse-openj9/openj9/issues/19813

Add -XX:+EnableExtendedHCR to jvmtitests_hcr rc018, rtc001

---

test/functional/JavaAgentTest/playlist.xml
test/functional/cmdLineTests/jvmtitests/jvmtitests_hcr.xml

Related to https://github.com/eclipse-openj9/openj9/pull/19710
Issue https://github.com/eclipse-openj9/openj9/issues/19777
Issue https://github.com/eclipse-openj9/openj9/issues/19765
Issue https://github.com/eclipse-openj9/openj9/issues/19813
Backport of https://github.com/eclipse-openj9/openj9/pull/19819 and https://github.com/eclipse-openj9/openj9/pull/19822

(0.46) Add -XX:+EnableExtendedHCR to addtional tests

---

test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeTests.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java

Re-enable and fix ValueTypeTests

---

runtime/vm/exceptiondescribe.c

Add missing check for extensionClassLoader

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

This is an enhancement to inline arraycopy for reference arrays if copy size is less than 32 bytes (default), or 64 bytes, or 128 bytes. It leverages the enhancement that has been implemented for int arrays and long arrays in OMR. 
This enhancement can be disabled by setting an env variable `TR_DisableReferenceArrayCopyInlineSmallSizeWithoutREPMOVS` or using option `disableReferenceArrayCopyInlineSmallSizeWithoutREPMOVS`.
The inlinling will take place only if there is no NoArrayStoreCheckArrayCopy and it doesn't require barrier.

x86: Inline reference system array copy for smaller size

---

runtime/compiler/z/codegen/J9TreeEvaluator.cpp

The memory cleaning procedure has a bug. It cleans 256 blocks of code with `XC` command the uses `EX` to clean remainder (if there is any). The problem is that it uses `NILL` instruction to isolate `Length%256` value then subtract 1 from it to compensate for `XC` starting from zero effect. When the size value is over 16 bits long and it is a perfect factor of 256, the result of `NILL 0x00FF` the -1 would end with `0xFF`!
would cause cleaning extra 256 bytes of the TLH and if the allocation is close to the end of memory space, causes failures.
In this pr I did some code cleanup and improve register allocation as well as changing the memory cleaning procedure.
@r30shah

Z fix new alloc inlined memory zeroing

---

runtime/oti/j9.h
runtime/vm/classallocation.c
runtime/vm/jnicsup.cpp
runtime/vm/jvminit.c

Fixes: https://github.com/eclipse-openj9/openj9/issues/19854

Clear jni ids on anonClass unload

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/GetCommandsTask.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/FindInstances.java

Implement DDR Command: FindInstances

---

runtime/oti/j9.h
runtime/vm/classallocation.c
runtime/vm/jnicsup.cpp
runtime/vm/jvminit.c

Fixes: https://github.com/eclipse-openj9/openj9/issues/19854

(0.47) Clear jni ids on anonClass unload

---

runtime/jvmti/jvmtiHelpers.cpp

Related: https://github.com/eclipse-openj9/openj9/issues/18738#issuecomment-2218824062

Update VThread alive check to check continuation state

---

runtime/jvmti/jvmtiObject.c

- RI has removed support for virtual threads if an object monitor is
owned by a virtual thread.
- Support has also been removed for virtual threads that are waiting
be notified or own a monitor.
- Also, new tests show that waiting to be notified threads do not
repeat and only appear in one list. This has been corrected in OpenJ9.
- Update formatting in jvmtiObject.c to follow coding standards.
Fixes: #19497

Add virtual thread support for JVMTI GetObjectMonitorUsage

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9Inliner.hpp

Reverts eclipse-openj9/openj9#17969
Due to https://github.com/eclipse-openj9/openj9/issues/19947

Revert "Adjust arguments to Unsafe array operations while offheap is enabled"

---

runtime/bcverify/rtverify.c

Port from: https://github.com/eclipse-openj9/openj9/pull/19938

0.47: Verification check for invokeinterface receiver

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp

Cherry pick https://github.com/eclipse-openj9/openj9/pull/19851 for 0.47

(0.47) Fix build errors on Windows

---

buildenv/jenkins/common/build.groovy
buildenv/jenkins/variables/defaults.yml

Cherry pick the commits from
https://github.com/eclipse-openj9/openj9/pull/19811
https://github.com/eclipse-openj9/openj9/pull/19870
https://github.com/eclipse-openj9/openj9/pull/19933
Tested via https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/547

(0.47) Backport docker build support for x and p linux for jdk23

---

buildenv/jenkins/common/build.groovy

Handle "next" as a special case of non-integer.

Improve version check for using a docker image

---

runtime/codert_vm/cnathelp.cpp

- with snippets moved into warm code cache, offset from cold code to the snippet will be negative

Make offset from snippet to mainline code signed

---

.github/recommendation.js

Fix several variables for triagerX workflow
Issue: #19552

Fix triagerX workflow variable definition

---

runtime/j9vm/jvm.c

Backup and restore orignal LIBPATH on z/OS Java 21+
related to https://github.com/eclipse-openj9/openj9/pull/20007

Backup and restore orignal LIBPATH on z/OS Java 21+

---

.github/recommendation.js
.github/workflows/TriageClosedIssue.yml

Add issue number in open issue message
Issue: https://github.com/eclipse-openj9/openj9/issues/19552#issuecomment-2299823558

Add TriagerX open issue number

---

runtime/jcl/common/shared.c

This comment was out of date from https://github.com/eclipse-openj9/openj9/pull/19769

Update threading comment for getCpeTypeForProtocol

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp

For codegen of `Unsafe.setMemory()` on power, check if object type is known at compile time. If so, calculate and pass in final destination address to `setMemoryEvaluator()` by adjusting dest and destOffset if necessary (i.e.: offheap enabled and object is array) and then adding them. Otherwise, pass in base address and offset separately so that an array check and argument adjustments can be generated at runtime.
Depends on: https://github.com/eclipse/omr/pull/7145

Check if runtime array check is needed for Unsafe.setMemory() on PPC

---

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp

Recognized Call Transformer generates IL that implements an inline version of `StringUTF16.toBytes` for values in the range [0,0x3fffffff], and that falls back to calling the Java implementation otherwise.  In JDK levels up to 22, the Java implementation throws an `OutOfMemoryException` if the length is greater than 0x3fffffff.  JDK Level 23, however, was changed to throw an `OutOfMemoryException` if the length is greater than _or equal to_ 0x3fffffff.
This change alters the IL that Recognized Call Transformer generates to fall back to the Java implementation if the length is greater than or equal to 0x3fffffff, so that it will work with all JDK levels.
Port of pull request #20058 to v0.47.0-release branch

[0.47.0] Adjust bound for out-of-line call to StringUTF16.toBytes

---

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp
runtime/compiler/p/codegen/J9CodeGenerator.cpp
runtime/compiler/x/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9CodeGenerator.cpp

Disable vectorizedMismatch transformation when OffHeap is enabled

Disable vectorizedMismatch transformation for OffHeap

---

doc/release-notes/0.46/0.46.1.md

Created the draft release note for 0.46.1
[skip ci]

0.46.1 release note Draft

---

runtime/vm/module.xml

* add `port/common` to include path

Fix JFR build failure with UMA

---

runtime/vm/CRIUHelpers.cpp

Backport of https://github.com/eclipse-openj9/openj9/pull/20161

(0.48) Remove potential double free of syslog

---

runtime/compiler/optimizer/J9TransformUtil.cpp

Add loading the dataAddr pointer in `calculateElementAddress()` helper for OffHeap.

Insert loading dataAddr in calculateElementAddress for OffHeap

---

test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java

Update ValueTypeTests.testGCFlattened* to use null-restricted arrays.

Update ValueTypeTests.testGCFlattened* tests

---

.github/recommendation.js
.github/workflows/TriageClosedIssue.yml

Enable TriagerX recommendation comment on corresponding issues
Closes: https://github.com/eclipse-openj9/openj9/issues/20119

Enable TriagerX recommendation on corresponding issues

---

runtime/rastrace/trcengine.c
runtime/rastrace/trcmain.c

* tidy up formatting, indentation
* remove useless assignment (was part of #20172 at one point)

Minor cosmetic improvements to trace code

---

runtime/oti/xhelpers.m4

Only add note.GNU-stack on Linux

---

test/functional/cmdLineTests/criu/criu.xml
test/functional/cmdLineTests/criu/criu_jitserverAcrossCheckpoint.xml
test/functional/cmdLineTests/criu/criu_keepCheckpoint.xml
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/criu_nonPortableJDK11Up.xml
test/functional/cmdLineTests/criu/criu_nonPortableJDK20Up.xml
test/functional/cmdLineTests/criu/criu_nonPortable_RAS.xml
test/functional/cmdLineTests/criu/criu_nonPortable_jdk_crac.xml
test/functional/cmdLineTests/criu/criu_random.xml
test/functional/cmdLineTests/criu/criu_security.xml
test/functional/cmdLineTests/criu/criu_softmx.xml

Add CRIU test output failure condition "AOT load and compilation disabled post restore".
Issue: backlog_1503

Add CRIU test output failure condition with aot info

---

jcl/src/java.base/share/classes/java/lang/System.java
jcl/src/openj9.cuda/share/classes/com/ibm/cuda/Cuda.java

Fixes https://github.com/eclipse-openj9/openj9/issues/20353
Tested via grinder, which passed.
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3898

For jdk24 add @Restricted to System.load() and loadLibrary

---

LICENSE

See https://github.com/eclipse-openj9/openj9/pull/19612

Fix the zlib copyright end date

---

LICENSE

See https://github.com/eclipse-openj9/openj9/pull/19612
Cherry pick https://github.com/eclipse-openj9/openj9/pull/20379

(0.48) Fix the zlib copyright end date

---

runtime/vm/exceptiondescribe.c

Issue: https://github.com/eclipse-openj9/openj9/issues/20368

Update classloader when cached rom to ram entry is found

---

runtime/util/cphelp.c

Remove unused variable from cphelp.c

---

test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeArrayTests.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeGenerator.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java

Addressing https://github.com/eclipse-openj9/openj9/pull/20317#pullrequestreview-2355506301

Valhalla tests to use standard Java array convention

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy

Reverts eclipse-openj9/openj9#19518

Revert "Remove plinux from "all" when running PR builds"

---

runtime/j9vm/valhallavmi.cpp

Related to https://github.com/eclipse-openj9/openj9/issues/13182

Update error to match jtreg NullRestrictedArrayTest

---

runtime/ddr/typestubs.h
runtime/j9vm31/j9vm31.h
runtime/libffi/preconf/wi/ffi.h
runtime/oti/j9nonbuilder.h
runtime/tests/clinkerffi/downcall.h
runtime/tests/shared/SCTestCommon.h

Also correct some comments for `#elif`, `#else`, `#endif`.

Use C-style comments in header files that might be used in C code

---

.github/workflows/TriageClosedIssue.yml

Fix TriagerX workflow list of duplicate prAssignees
Closes: https://github.com/eclipse-openj9/openj9/issues/20425

Fix TriagerX workflow duplicate prAssignees

---

test/functional/Valhalla/playlist.xml

Add -Xdump debug option for ValueTypeTests

---

jcl/src/java.base/share/classes/java/lang/Class.java

Extract common code.
Fixes: #20428.

Update signature of Class.getPrimitiveClass(String) for Java 24+

---

runtime/compiler/env/J9ClassEnv.cpp

Fix incorrectly named variable in debug code

---

test/functional/Java9andUp/playlist.xml

Remove outdated tests for JDK 16

Remove outdated tests for JDK 16

---

.github/ISSUE_TEMPLATE/user-problem.md

Add a reference to jpackcore and articles which help find the system core.

Improve instructions for user raised issues

---

doc/compiler/aot/SymbolValidationManager.md

PR #5174 renamed the AOT Class Chains reference file. This PR adjusts sources to changes.

Update AOT Class Chains reference

---

runtime/jcl/common/com_ibm_oti_vm_VM.cpp
runtime/vm/jfr.cpp

Also fix bug in jfr buffer alloc for dynamic start

Fix deadlock in dynamic JFR start

---

runtime/gc_base/Wildcard.cpp
runtime/gc_base/Wildcard.hpp

Clean up Wildcard class code

---

runtime/gc_structs/CallSitesIterator.hpp

signed-off-by: lhu <linhu@ca.ibm.com>

Clean up CallSitesIterator class code

---

runtime/gc_structs/ClassStaticsDeclarationOrderIterator.hpp

Clean up ClassStaticsDeclarationOrderIterator class

---

runtime/gc_structs/ClassStaticsIterator.hpp

Clean up ClassStaticsIterator class

---

runtime/gc_base/FinalizableClassLoaderBuffer.hpp
runtime/gc_base/FinalizableObjectBuffer.hpp
runtime/gc_base/FinalizableReferenceBuffer.hpp

Add more code formatting suggested by late comment.

Code formatting for Finalizable*Buffer

---

buildspecs/aix_ppc-64.spec
buildspecs/cmprssptrs.feature
buildspecs/j9.flags
buildspecs/linux_390-64.spec
buildspecs/linux_aarch64.spec
buildspecs/linux_aarch64_cross.spec
buildspecs/linux_ppc-64.spec
buildspecs/linux_ppc-64_le.spec
buildspecs/linux_riscv64.spec
buildspecs/linux_riscv64_cross.spec
buildspecs/linux_x86-64.spec
buildspecs/linux_ztpf_390-64.spec
buildspecs/osx_x86-64.spec
buildspecs/win_x86-64.spec
buildspecs/zos_390-64.spec
runtime/gc_modron_startup/mmhelpers.cpp

new define J9VM_GC_SPARSE_HEAP_ALLOCATION for the build specs

Update Java8 build specs for off-heap

---

test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-1.xml

Add verbose to show more information for SCC CML test

---

runtime/j9vm/jvm.c

Remove vmSnapshotFilePath from J9SpecialArguments

---

doc/release-notes/0.48/0.48.md

Minor correction of the option name.
[skip ci]

0.48.0 release note-Minor correction

---

test/functional/Valhalla/src_lw5/org/openj9/test/lworld/ValueTypeTests.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java

Add a test case for System.identityHashCode in Valhalla

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp

Related to https://github.com/eclipse-openj9/openj9/pull/20552#issuecomment-2465659102

Missing null-restricted flag in MethodHandles initialization

---

runtime/compiler/optimizer/VectorAPIExpansion.cpp

Fix incorrect preprocessor conditional

---

jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/ManagementUtils.java
jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/PlatformMBeanProvider.java
jcl/src/jdk.management/share/classes/jdk/crac/management/CRaCMXBean.java
jcl/src/jdk.management/share/classes/jdk/crac/management/internal/CRaCMXBeanImpl.java
jcl/src/jdk.management/share/classes/module-info.java.extra

Issue https://github.com/eclipse-openj9/openj9/issues/20587

Move CRaCMXBeanImpl and export jdk.crac.management

---

runtime/vm/JFRConstantPoolTypes.cpp
runtime/vm/jfr.cpp

Also, check that threadObject is not NULL before dereference.

Prevent writes to free'd JFR buffer

---

jcl/src/jdk.management/share/classes/openj9/lang/management/OpenJ9DiagnosticsMXBean.java
jcl/src/jdk.management/share/classes/openj9/lang/management/internal/OpenJ9DiagnosticsMXBeanImpl.java
test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestOpenJ9DiagnosticsMXBean.java

There should be a getter to match the setter.
Issue https://github.com/eclipse-openj9/openj9/issues/20587

Add OpenJ9DiagnosticsMXBean.getDumpOptions

---

runtime/gc_structs/ConstantPoolObjectSlotIterator.cpp
runtime/gc_structs/ConstantPoolObjectSlotIterator.hpp

Clean up ConstantPoolObjectSlotIterator class

---

runtime/vm/JFRChunkWriter.cpp
runtime/vm/JFRChunkWriter.hpp

Back port of https://github.com/eclipse-openj9/openj9/pull/20616

(0.49) Add JFR InitialEnvironmentVariable support

---

runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/DLLMain.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9CompilationStrategy.cpp
runtime/compiler/control/MethodToBeCompiled.cpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/annotations/Annotations.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/ilgen/Walker.cpp
runtime/compiler/optimizer/IdiomRecognition.cpp
runtime/compiler/optimizer/IdiomTransformations.cpp
runtime/compiler/ras/kca_offsets_generator.cpp
runtime/compiler/runtime/GPUHelpers.cpp
runtime/compiler/runtime/IProfiler.cpp
runtime/compiler/runtime/JITServerROMClassHash.cpp
runtime/compiler/runtime/JitRuntime.cpp
runtime/compiler/runtime/MetaDataDebug.cpp
runtime/exelib/common/libhlp.c
runtime/vm/JFRChunkWriter.hpp
runtime/vm/linearswalk.c

Cherry pick https://github.com/eclipse-openj9/openj9/pull/20474 for 0.49

(0.49) Replace sprintf with snprintf in many places

---

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp
runtime/compiler/optimizer/UnsafeFastPath.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp

Replace all remaining instances of `J9VM_GC_ENABLE_SPARSE_HEAP_ALLOCATION` with `J9VM_GC_SPARSE_HEAP_ALLOCATION`

Update Offheap guard macro

---

runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/env/VMJ9.h

Reverts eclipse-openj9/openj9#20710

Revert "Add override to virtual methods of TR_J9SharedCache and TR_J9VMBase"

---

runtime/vm/jfr.cpp

Backport of https://github.com/eclipse-openj9/openj9/pull/20697

(0.49) Disable thread buffer writes after thread end

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp

From https://github.com/eclipse-openj9/openj9/pull/20700#discussion_r1868333340

Update true to TRUE to match parameter type BOOLEAN

---

runtime/vm/VMSnapshotImpl.cpp

Fix incorrect indentation in VMSnapshotImpl.cpp

---

runtime/vm/jfr.cpp

Port of https://github.com/eclipse-openj9/openj9/pull/20754

(0.49) Release VMAccess before performing JFR teardown

---

runtime/compiler/optimizer/VectorAPIExpansion.cpp

- do not use TR_enableMaskUnboxing environment option since the issue was fixed
- handle astore correctly when RHS is not aload
Original PR: https://github.com/eclipse-openj9/openj9/pull/20791

(0.49) Minor VectorAPI boxing fixes

---

runtime/oti/j9nonbuilder.h
runtime/vm/JFRChunkWriter.hpp
runtime/vm/JFRConstantPoolTypes.cpp
runtime/vm/JFRConstantPoolTypes.hpp
runtime/vm/jfr.cpp

- ->system seems to be replaced by the compiler
- = {0} initialization isn't supported by the compiler

(0.49) Make JFR compile on z/OS

---

runtime/bcutil/dynload.c
runtime/jcl/common/stdinit.c
runtime/oti/j9port_generated.h
runtime/util/cphelp.c
runtime/vm/VMSnapshotImpl.cpp
runtime/vm/VMSnapshotImpl.hpp
runtime/vm/classallocation.c
runtime/vm/jvmfree.c
runtime/vm/jvminit.c

Related: https://github.com/eclipse-openj9/openj9/issues/20612

Add classPathEntries to the VM snapshot

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
buildenv/jenkins/variables/defaults.yml

JDK24 build
This is to enable https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK24-Acceptance

JDK24 build

---

runtime/vm/stringhelpers.cpp

Fix type conversion error in stringhelpers.cpp

---

runtime/oti/j9nonbuilder.h

Reverts eclipse-openj9/openj9#20804

Revert "Downgrade isIndexableDataAddrPresent  to BOOLEAN"

---

runtime/compiler/z/codegen/J9CodeGenerator.cpp

Z: Moving variable declaration to the method top

---

runtime/nls/j9gc/j9modron.nls

NLS samples were missed for last two added messeges, adding them.

Add missed samples to NLS messages

---

runtime/vm/JFRConstantPoolTypes.hpp
runtime/vm/jfr.cpp
test/functional/cmdLineTests/jfr/build.xml
test/functional/cmdLineTests/jfr/jfr.xml
test/functional/cmdLineTests/jfr/metadata.blob
test/functional/cmdLineTests/jfr/playlist.xml
test/functional/cmdLineTests/jfr/src/org/openj9/test/VMAPITest.java
test/functional/cmdLineTests/jfr/src/org/openj9/test/WorkLoad.java

Also NULL free'd memory and memset allocated memory.
Backport of https://github.com/eclipse-openj9/openj9/pull/20834

(0.49) Add JFR test cases

---

test/functional/cmdLineTests/jfr/build.xml

Fix comment in JFR's cmdLineTests build.xml

---

runtime/vm/jfr.cpp

Related: https://github.com/eclipse-openj9/openj9/pull/20679

Add unloaded anonClass count to JFR ClassLoadingStatistics

---

buildenv/jenkins/common/pipeline-functions.groovy

Remove "-zos" suffix before checking whether the version is "next".

Correct handling of pull request builds for z/OS

---

runtime/vm/jfr.cpp

Related: https://github.com/eclipse-openj9/openj9/pull/20679
Back-port of https://github.com/eclipse-openj9/openj9/pull/20882

(0.49) Add unloaded anonClass count to JFR ClassLoadingStatistics

---

runtime/vm/JFRConstantPoolTypes.hpp

Backport of https://github.com/eclipse-openj9/openj9/pull/20910

(0.49) Use frameType info in JFR stackFrames

---

test/functional/cmdLineTests/libpathTest/playlist.xml

Indent consistently with tabs

---

runtime/compiler/optimizer/VectorAPIExpansion.cpp
runtime/compiler/optimizer/VectorAPIExpansion.hpp

Reverts eclipse-openj9/openj9#20972
See https://github.com/eclipse-openj9/openj9/issues/20995

Revert "Improve VectorAPI Expansion IL transformation phase"

---

runtime/gc_glue_java/ContractslotScanner.hpp

Replacing UDATA to uintptr_t and managing white spaces.

Adjust ContractslotScanner according Coding Standarts

---

runtime/gc/gctable.c
runtime/gc_base/gc_internal.h
runtime/gc_base/modronapi.cpp
runtime/gc_base/modronapi.hpp
runtime/oti/j9nonbuilder.h

JFR Event Collection needs it for group GCConfiguration field isExplicitGCDisabled

Add external j9gc_get_explicit_GC_disabled()

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9Inliner.hpp

Minor cleanup for #21024:
* use spaces, not tabs
* indent consistently

Adjust indentation

---

buildenv/jenkins/variables/defaults.yml

Signed-off-by: Kostas Tsiounis <kostas.tsiounis@ibm.com>

Bundle OpenSSL in all platforms

---

runtime/rasdump/trigger.c

When a message filter is specified, exceptions without a message should not match.
Fixes: #16531.

Fix filtering of events that trigger dumps

---

jcl/src/java.base/share/classes/java/lang/Class.java

Synchronization has been added to ensure safe initialization and safe
publication of `Class.allPermissionsPD`. This addresses the locking
contention on `Class.allPermissionsPD` in `Class.getProtectionDomain()`.
Fixes: #20351

Add synchronization for Class.allPermissionsPD

---

runtime/gc_vlhgc/CopyForwardScheme.cpp
runtime/gc_vlhgc/CopyForwardScheme.hpp

Clean up CopyForwardScheme class

---

test/functional/NativeTest/nativeTestSettings.mk
test/functional/NativeTest/playlist.xml

This change will consolidate two thrstatetests by updating playlist.xml and nativeTestSettings.mk 
Fixes : #21020
Signed-off-by: Denny Chacko Jacob <denny.cjacob@ibm.com>

Consolidating two thrstatetests

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

ArrayStoreCHK in x86 uses null check and OOL store path for nullSource stores, evaluating the destination address early to be used in either the mainline or OOL store paths. For OffHeap evaluating the destination address includes loading the dataAddr pointer, where having it alive across GC point (OOL ArrayTypeCheck) will cause a crash [1].
To defer the evaluation and loading the dataAddr into a register this consolidate the store paths for null and non-null stores and defers the destination address evaluation till before the store happens for OffHeap.
Side-effect of this is null stores performing a wrtbar/card-marking even thought it's not necessary but opted for instead of a second null check.
[1]
Reason of crashing is evaluating the dataAddr pointer into a collectable register. A …

Defer dataAddr eval & use mainline store for nullSource OffHeap x86 ArrayStoreCHK

---

runtime/bcverify/bcverify.c

Reset errorTargetFrameIndex at the begining of bytecode verification

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

Reverts eclipse-openj9/openj9#21119
See https://github.com/eclipse-openj9/openj9/pull/21119#issuecomment-2686054278

Revert "x86: Implement String.hashCode with vectorizedHashCode()"

---

runtime/j9vm/exports.cmake
runtime/j9vm/java11vmi.c
runtime/redirector/forwarders.m4

Stub JVM_GetProperties for jdk17+

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp

Improve the sequence that populates the dataAddr field to reduce a redundant branch when `needZeroInit` is false (aka heap is cleared).
Current:
```
cmp len 0
bgt nonZeroArrayLabel
b dataAddrInitDoneLabel
nonZeroArrayLabel:
store dataAddr in dataAddrField
dataAddrInitDoneLabel:
```
Improved:
```
cmp len 0
beq dataAddrInitDoneLabel
store dataAddr in dataAddrField
dataAddrInitDoneLabel:
```
When `needZeroInit` is true:
```
cmp len 0
beq zeroArrayLabel
store dataAddr in dataAddrField
b dataAddrInitDoneLabel
zeroArrayLabel:
store 0 in dataAddrField
dataAddrInitDoneLabel:
```
WIP: Testing

Update dataAddr populate sequence for inline allocation on P

---

runtime/gc_base/GCExtensions.hpp
runtime/gc_modron_startup/mmparseXXgc.cpp
runtime/gc_realtime/ConfigurationRealtime.cpp
runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp

Reverts eclipse-openj9/openj9#20821

Revert "Enable off-heap as default on Balanced GC"

---

runtime/jvmti/jvmtiObject.c

OpenJ9 should return a null entry for jthread* waiters; and jthread* notify_waiters; when their counts (waiter_count or notify_waiter_count) are 0.

GetObjectMonitorUsage waiter lists should be null for 0 waiters

---

runtime/vm/bindnatv.cpp

Addresses https://github.com/eclipse-openj9/openj9/pull/21197#discussion_r1978345120.

Update ifdef comments in bindnatv.cpp

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/bindnatv.cpp

Port from: https://github.com/eclipse-openj9/openj9/pull/21197 https://github.com/eclipse-openj9/openj9/pull/21257

(0.51) Support heap memory for ffi CaptureCallState

---

runtime/compiler/x/codegen/J9CodeGenerator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.hpp
test/functional/Java9andUp/playlist.xml

0.51 port of #21118
@hzongaro @pshipton

(0.51) x86: Implement fma intrinsic

---

test/functional/cmdLineTests/jfr/playlist.xml

- Remove JFR feature tag in playlist

Remove JFR:required tag in playlist

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

0.51 port of #21221
FYI @0xdaryl @pshipton

(0.51) x86: Implement String.hashCode with vectorizedHashCode()

---

test/functional/cmdLineTests/jfr/playlist.xml

- Remove JFR feature tag in playlist
related:https://github.com/eclipse-openj9/openj9/issues/21269

(v0.51.0)Remove JFR:required tag in playlist

---

jcl/src/java.base/share/classes/java/lang/System.java

Issue https://github.com/eclipse-openj9/openj9/issues/21204

For jdk24+ set the default encoding to UTF-8

---

jcl/src/java.base/share/classes/java/lang/System.java

Issue https://github.com/eclipse-openj9/openj9/issues/21204
Cherry pick https://github.com/eclipse-openj9/openj9/pull/21285

(0.51) For jdk24+ set the default encoding to UTF-8

---

runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp

Unintentionally removed by
https://github.com/eclipse-openj9/openj9/pull/21281

Restore #endif in createHeapWithManager

---

runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp

Reverts eclipse-openj9/openj9#21298
See https://github.com/eclipse-openj9/openj9/pull/21298#issuecomment-2706438373

Revert "Enable offheap on X and P"

---

runtime/compiler/env/ProcessorDetection.cpp
runtime/compiler/x/env/J9CPU.cpp
runtime/compiler/x/env/J9CPU.hpp

x86: check xcr0 in AOT compiles

---

runtime/compiler/control/JITServerCompilationThread.cpp

Under very rare circumstances, it is possible for a JITServer compilation thread processing a remote compilation request containing CH Table updates to side step processing the CH Table updates. The sequences of events that could lead to this is as follows:
1. compThreadID=0 processes request seqNo=2 (isCritical=0) (criticalSeqNo=1 lastProcessedCriticalReq=1)
2. compThreadID=1 processes request seqNo=1 (isCritical=1) (criticalSeqNo=0 lastProcessedCriticalReq=1)
3. compThreadID=1 discards request because seqNo=2 was processed first
4. compThreadID=0 requests full CH Table to initialize on the server
5. compThreadID=1 processes request seqNo=3 (isCritical=1) (criticalSeqNo=1 lastProcessedCriticalReq=1)
seqNo=1 and seqNo=3 contain CH Table updates; seqNo=2 does not. As such, on the client …

Ensure all JITServer compilation threads process CH Table Updates

---

runtime/shared_common/CompositeCache.cpp

Unprotect header when modifying extraStartupHints

---

runtime/compiler/optimizer/TreeLowering.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/libffi/arm/gentramp.sh

A couple repetitions of "of" were introduced in #21306, but there others as well.

Fix a few typos

---

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp

When inlining `StringLatin1.inflate` for OffHeap we call `generateConvertArrayElementIndexToOffsetTrees` to get the destination offset from the index. The offset needs to be used for the destination address tree, but the boundary check trees need to remain using the index in its comparisons.
This also fixes the issue of having the long-typed offset node used in the boundary check trees with int-typed nodes, breaking GlobalValuePropagation.
Also consolidate OffHeap and non-OffHeap paths.
Closes: #21229 
Closes: #21304
Testing...

Use index for boundary check and offset for dest in str.inflate OffHeap

---

runtime/vm/JFRChunkWriter.hpp
runtime/vm/JFRConstantPoolTypes.cpp
runtime/vm/ObjectMonitor.cpp
runtime/vm/jfr.cpp
test/functional/cmdLineTests/jfr/jfrevents.xml
test/functional/cmdLineTests/jfr/src/org/openj9/test/WorkLoad.java

- Fix Owner for JFR monitor enter
- Add tests to validate monitor enter events

Fix owner for JFR monitor enter

---

runtime/compiler/env/ProcessorDetection.cpp
runtime/compiler/x/env/J9CPU.cpp
runtime/compiler/x/env/J9CPU.hpp

(0.51) x86: check xcr0 in AOT compiles

---

runtime/vm/BytecodeInterpreter.hpp

backport of https://github.com/eclipse-openj9/openj9/pull/21359

(0.51) IMSE support for vthreads

---

runtime/oti/vmconstantpool.xml
runtime/vm/BytecodeInterpreter.hpp

- Throw InterruptedException on return fom vthread wait if interrupted field is set
- Add timeout value to vthread object

Fix Object.wait logic for vthread

---

runtime/rasdump/javadump.cpp
runtime/vm/BufferWriter.hpp
runtime/vm/JFRChunkWriter.cpp
runtime/vm/JFRChunkWriter.hpp
runtime/vm/JFRWriter.hpp
runtime/vm/jfr.cpp

(0.51) Backport of JFR ThreadDump and thread raw state changes

---

runtime/vm/BytecodeInterpreter.hpp
runtime/vm/jvminit.c

This PR backports the below PRs to the 0.51 release branch:
- #21427
- #21389
- #21428

(0.51) Enable yielding of pinned continuations by default

---

runtime/rasdump/javadump.cpp
runtime/vm/JFRChunkWriter.cpp

Fixes https://github.com/eclipse-openj9/openj9/issues/21431

Fix thread raw state format in dumps

---

runtime/rasdump/javadump.cpp
runtime/vm/JFRChunkWriter.cpp

Fixes https://github.com/eclipse-openj9/openj9/issues/21431

(0.51) Fix thread raw state format in dumps

---

jcl/src/java.base/share/classes/java/lang/System.java
runtime/j9vm/j7vmi.c
runtime/vm/vmprops.c

Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/804

Use extensions System.initProperties to help init jdk8 properties

---

runtime/compiler/control/CompilationThread.cpp

Under -XX:+DebugOnRestore, the compiler generates a bunch of FSD bodies pre-checkpoint, and then proacively recompiles them without FSD in the checkpoint hook. If the queue gets big, more than one compilation thread may be activated; compilations in parallel generally require a distinct code cache per thread. However, because the code caches are backed by Huge Pages (which means touching a small part of the page brings the entire page into RSS), multiple compilation threads can cause the code bodies to get fragmented across multiple code caches (rather than being compacted in a smaller set) ultimately increasing the total RSS memory footprint.
This change fixes this by only allowing one compilation thread pre-checkpoint (under -XX:+DebugOnRestore). While this increases the checkpoint …

Only allow one active comp thread pre-checkpoint under `-XX:+DebugOnRestore`

---

runtime/compiler/z/codegen/J9TreeEvaluator.cpp

Update StringLatin1.inflate and StringCoding.HasNegatives/CountPositives for
off-heap. Update the array access in the evaluators to get address to the data
portion of the array from dataAddr field when off-heap is enabled.

Enable StringLatin1 and StrinCoding accelerations for off-heap on z

---

jcl/src/java.base/share/classes/com/ibm/jit/JITHelpers.java
jcl/src/java.base/share/classes/java/lang/String.java
jcl/src/java.management/share/classes/java/lang/management/LockInfo.java
jcl/src/jdk.management/share/classes/com/ibm/virtualization/management/HypervisorMXBean.java
jcl/src/jdk.management/share/classes/com/sun/management/GarbageCollectionNotificationInfo.java
jcl/src/jdk.management/share/classes/com/sun/management/GcInfo.java

Also use of the word "top".
Related to https://github.ibm.com/runtimes/java-cr/issues/784

Remove inappropriate usage of <blockquote> in javadoc

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/control/rossa.cpp

CRIU: JIT should generate portable code by default

---

jcl/src/java.base/share/classes/java/lang/System.java
runtime/j9vm/j7vmi.c
runtime/vm/vmprops.c

Cherry pick https://github.com/eclipse-openj9/openj9/pull/21452

(0.51) Use extensions System.initProperties to help init jdk8 properties

---

jcl/src/java.base/share/classes/com/ibm/jit/JITHelpers.java
jcl/src/java.base/share/classes/java/lang/String.java
jcl/src/java.management/share/classes/java/lang/management/LockInfo.java
jcl/src/jdk.management/share/classes/com/ibm/virtualization/management/HypervisorMXBean.java
jcl/src/jdk.management/share/classes/com/sun/management/GarbageCollectionNotificationInfo.java
jcl/src/jdk.management/share/classes/com/sun/management/GcInfo.java

Also use of the word "top".
Cherry pick https://github.com/eclipse-openj9/openj9/pull/21461

(0.51) Remove inappropriate usage of <blockquote> in javadoc

---

runtime/oti/ContinuationHelpers.hpp
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/FastJNI_java_lang_Object.cpp

- A vthread can only be notified or interrupted, not both
- Move vthread notify code to helper function
- Refactor notify/notifyAll code to simplify logic

Update Object.notify/interrupt processing logic

---

runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp

Reference count check was added to avoid commoning of dataAddr pointer (first child of address node) by preventing early evaluation. However, this might create functional issues if a later instruction expects the child, and/or siblings of dataAddr pointer to be evaluated into a register. Checking the reference count individually prevents commoning of dataAddr pointer while maintaining functional correctness.

Fix early evaluation logic for address node of BCDCHK

---

runtime/util/sendslot.c

Prevent potential infinite loop in getSendSlotsFromSignature.
Related: #20577

Limit iterations of signature loop

---

runtime/jvmti/jvmtiThread.cpp

Update GetCurrentContendedMonitor to support JEP491

---

runtime/vm/FastJNI.cpp

Backport of https://github.com/eclipse-openj9/openj9/pull/21489

(0.51) Disable fast JNI wait if wait can unmount continuations.

---

runtime/vm/ContinuationHelpers.cpp

Adding assertions to verify virtual thread behaviour is valid. The expectation is that instead of hangs we will see assertion failures which will aid in the investigation of issues.

Add assertion for incompatible vthread states

---

runtime/vm/ContinuationHelpers.cpp

Adding assertions to verify virtual thread behaviour is valid. The expectation is that instead of hangs we will see assertion failures which will aid in the investigation of issues.
Backport of https://github.com/eclipse-openj9/openj9/pull/21519

(0.51) Add assertion for incompatible vthread states

---

runtime/vm/ContinuationHelpers.cpp
runtime/vm/monhelpers.c

- check to make sure that the owned monitor count is correct
- account for Object::wait when countng owne monitors
- ensure that when exiting a monitor the owner is valid

Add assertions for invalid vthread states part2

---

runtime/vm/ContinuationHelpers.cpp

- Adds missing monitor exit for flatlock case.

Fixes preparePinnedVirtualThreadForUnmount assertion

---

runtime/oti/j9nonbuilder.h
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/ContinuationHelpers.cpp
runtime/vm/threadhelp.cpp

Send vthread unblock notify for waiting platform thread

---

runtime/vm/ContinuationHelpers.cpp
runtime/vm/monhelpers.c

Backport https://github.com/eclipse-openj9/openj9/pull/21533 and https://github.com/eclipse-openj9/openj9/pull/21541

(0.52) Add assertions for invalid vthread states part2 

---

runtime/oti/j9nonbuilder.h
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/ContinuationHelpers.cpp
runtime/vm/threadhelp.cpp

(v0.52.0) Send vthread unblock notify for waiting platform thread

---

runtime/rasdump/dmpsup.c
runtime/rasdump/rasdump_internal.h

Cherry-pick https://github.com/eclipse-openj9/openj9/pull/21563 for 0.51.

Print Dynatrace core_pattern location in java dumps

---

runtime/rasdump/dmpsup.c
runtime/rasdump/rasdump_internal.h

Cherry-pick https://github.com/eclipse-openj9/openj9/pull/21563 for 0.52.

(0.52) Print Dynatrace core_pattern location in java dumps

---

runtime/compiler/runtime/RelocationRuntime.cpp

This is more or less a copy of the code in `OMR::Compilation::compile()` but adjusted to use the data from the `J9JITExceptionTable` after relocation.
Testing shows identical info (except for the cold call stuff that's printed out in the compile run, which isn't available at relo time):
AOT Compile:
```
(AOT warm) Compiling java/util/HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object;  OrdinaryMethod j9m=00000000000B6B98  t=101 compThreadID=0 memLimit=262144 KB freePhysicalMemory=1544423 MB
#INL: 9 methods inlined into af29ebb8 java/util/HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object; @ 00007F4A2DE06F48
#INL: #0: af29ebb8 #-1 inlined af29ebb8@56 -> a0e74e5a bcsz=13 java/util/HashMap.newNode(ILjava/lang/Object;Ljava/lang/Object;Ljava/util/Hash …
```

Add Verbose Inlining output for AOT Loads

---

runtime/compiler/env/VMJ9.cpp
runtime/jcl/common/com_ibm_oti_vm_VM.cpp
runtime/jcl/common/java_lang_StackWalker.cpp
runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
runtime/jcl/common/jdk_internal_foreign_abi_UpcallStubs.cpp
runtime/jcl/common/jithelpers.c
runtime/jcl/common/mgmtcompilation.c
runtime/jcl/common/mgmtthread.c
runtime/jcl/common/orbvmhelpers.c
runtime/jcl/common/sun_misc_Unsafe.cpp
runtime/jcl/common/thread.cpp
runtime/jextractnatives/jextractnatives.c
runtime/jvmti/jvmtiExtensionMechanism.c
runtime/oti/j9.h
runtime/tests/jni/critical.c
runtime/tests/jni/jnitest.c
runtime/tests/thread/testnatives/testnatives.c
runtime/vm/jnicsup.cpp

Conversions were not being done consistently: This improves the situation.

Add macros for converting between integer values and pointers

---

runtime/compiler/env/VMJ9.cpp

Remove unwanted closing parenthesis

---

runtime/compiler/optimizer/VectorAPIExpansion.cpp
runtime/compiler/optimizer/VectorAPIExpansion.hpp

Depends on https://github.com/eclipse-openj9/openj9/pull/21599

Report missing IL opcodes in VectorAPIExpansion

---

runtime/oti/ContinuationHelpers.hpp
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/ContinuationHelpers.cpp

Backport of https://github.com/eclipse-openj9/openj9/pull/2161 and https://github.com/eclipse-openj9/openj9/pull/21564

(0.52) Add missing frame build on failed wait re-entry 

---

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp

The transformation in recognized call transformer uses the original call as a fallback path. After generating tests and splitting blocks, its arguments generally come from temps created by `fixupCommoning`, but not all of the temps were guaranteed to be initialized before reaching the fallback path. Now they will be.

Ensure temps are initialized for StringLatin1.inflate([BI[BII)V

---

runtime/vm/ObjectMonitor.cpp

Backport of https://github.com/eclipse-openj9/openj9/pull/21618

(0.52) Ensure previous lock owner is a valid thread

---

runtime/util/sendslot.c

Prevent potential infinite loop in getSendSlotsFromSignature.
Related: #20577

(0.51) Limit iterations of signature loop

---

runtime/libffi/z/ffi64.c

In https://github.com/eclipse-openj9/openj9/pull/19988, changes were added to cache the ffi_type for same struct in downcall. LIBFFI on z/OS to handle the complex type arguments (An aggregate containning exactly two floating point values of same type) would look at the shape of the structure and change the type so that HLASM code that acts as an interface to downcall can arrange arguments correctly. With caching of the ffi_type, we were missing setting the flag for return type if we encounter the cached ffi_type object causing us to miss out setting up return values.

Add support for cached ffi_type object for z/OS

---

runtime/vm/VMSnapshotImpl.cpp

Remove references to the list of objects stored in J9Class->memberNames and reset J9Class->memberNames to fix the crash in RCP JDK17+.
Fixes: #20872
Co-authored-by: Babneet Singh sbabneet@ca.ibm.com
Co-authored-by: Tobi Ajila tobi_ajila@ca.ibm.com
Co-authored-by: Lige Zhou lige_zhou@ibm.com

RCP: Free references to a class memberNames

---

runtime/oti/j9nonbuilder.h
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/ContinuationHelpers.cpp

(0.52) Trigger contended monitor entered event on virtual threads

---

runtime/vm/BytecodeInterpreter.hpp
runtime/vm/ContinuationHelpers.cpp

(v0.52.0) Add JVMTI_EVENT_MONITOR_WAIT/ED event trigger for virtual threads

---

runtime/compiler/optimizer/EscapeAnalysis.cpp

For a reference to a field whose value number is one that might be used by a non-contiguous candidate, code in [`TR_EscapeAnalysis::fixupNode` called `fixupFieldAccessForNonContiguousAllocation`](https://github.com/eclipse-openj9/openj9/blob/c2a5143065daddb1d2b6be5af38a3e2357f64875/runtime/compiler/optimizer/EscapeAnalysis.cpp#L5715-L5719) unconditionally.  That would always transform the indirect field reference into a direct reference to the automatic variable representing that field of the candidate.
However, a candidate's value numbers can include references that might access the candidate, but do not necessarily.  For most objects, that would prevent the candidate from being stack allocated non-contiguously, but immutable objects can still be allocated discontiguously even in the …

Fix non-contiguous field only if base value number matches candidate

---

runtime/j9vm/java11vmi.c

Fetch `module` object reference after GC point
Moved `J9_JNI_UNWRAP_REFERENCE(module)` after `internalFindKnownClass()` which could trigger `GC` and invalidate the `module` object fetched before.
Related to
* https://github.com/eclipse-openj9/openj9/issues/18970

Fetch module object reference after GC point

---

runtime/jcl/common/mgmtmemory.c
runtime/oti/j9nonbuilder.h
runtime/vm/createramclass.cpp

Reverts eclipse-openj9/openj9#20896

Revert "WIP:RamClass: Segment allocation enhancements"

---

runtime/vm/JFRChunkWriter.cpp
runtime/vm/JFRChunkWriter.hpp
runtime/vm/JFRConstantPoolTypes.hpp
test/functional/cmdLineTests/jfr/jfrevents.xml

Reverts eclipse-openj9/openj9#21629

Revert "Add JFR NativeLibrary event"

---

buildenv/jenkins/variables/defaults.yml

Using 27 cleared sufficient space.

Set daysToKeepArtifacts to 27 instead of 21

---

runtime/gc_glue_java/MarkingDelegate.cpp
runtime/gc_glue_java/MarkingDelegate.hpp

the new API is only for Java 19 and above, update to avoid compiling issue for JVM under Java 19.

Fix compiling issue under Java 19

---

runtime/compiler/optimizer/JProfilingValue.cpp

This reverts commit 8bbc086990b8472e6e151f158a13c28c812441db, reversing changes made to a134afaba701a757b5f2e5a3e0605d12741428ad.
Related: #21256

(0.51) Revert "Merge pull request #21056 from vijaysun-omr/jprofiling1"

---

runtime/oti/ContinuationHelpers.hpp
runtime/vm/ContinuationHelpers.cpp

Immediately update vthread state during Object.notify

---

runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9method.h

Remove dead isStrictFP() functions

---

runtime/oti/ContinuationHelpers.hpp
runtime/vm/ContinuationHelpers.cpp

When a blocked continuation is cancelled or terminated,
it may still be placed on the VM/monitor blocked list.
Before freeing up the Continuation struct, it must be removed
from those lists to prevent having references to freed struct.

Handle blocking/waiting vthread being freed

---

runtime/vm/ContinuationHelpers.cpp

Addresses https://github.com/eclipse-openj9/openj9/pull/21721#discussion_r2069486081

Move helper call outside of trace assert

---

buildenv/jenkins/variables/defaults.yml

Related to https://github.com/eclipse-openj9/openj9/pull/21628

Set the default location for downloading the bootjdk on AIX

---

runtime/gc_vlhgc/CopyForwardScheme.cpp
runtime/gc_vlhgc/CopyForwardScheme.hpp

Reverts eclipse-openj9/openj9#20589

Revert "Do not add Own.Sync. object to the list if scan wasn't successfull"

---

buildenv/jenkins/variables/defaults.yml

Update the AIX jdk24 bootjdk link

---

runtime/oti/ContinuationHelpers.hpp
runtime/oti/j9nonbuilder.h
runtime/vm/ContinuationHelpers.cpp

Account for VirtualThread's SUSPENDED bit flag during transition

---

runtime/compiler/build/toolcfg/gnu/common.mk
runtime/makelib/targets.mk.linux.inc.ftl

Related to https://github.com/eclipse-omr/omr/pull/7747
Issue https://github.com/eclipse-openj9/openj9/issues/20956
Test build http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=93835

Set noexecstack when linking with uma

---

test/functional/Java21andUp/playlist.xml

Re-enable Jep425Tests_testVirtualThread on AIX and plinux

---

doc/release-notes/0.51/0.51.md

Also replace a non-public link.

Add release notes for system property changes

---

runtime/vm/JFRChunkWriter.hpp

Follow-up of
https://github.com/eclipse-openj9/openj9/pull/21832#discussion_r2081793677

Remove a redundent line

---

runtime/gc_vlhgc/CopyForwardScheme.cpp
runtime/gc_vlhgc/CopyForwardScheme.hpp

Reverts eclipse-openj9/openj9#21857

Revert "Do not add Own.Sync. object to the list if scan wasn't successful"

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp

...like the bootstrap/system loader already is.

Make the extension and application loaders available via TR_J9VMBase

---

runtime/vm/monhelpers.c

Correct data type, I_32 -> BOOLEAN, in monhelpers.c

---

runtime/vm/ContinuationHelpers.cpp
runtime/vm/monhelpers.c

Addresses: https://github.com/eclipse-openj9/openj9/pull/21877#issuecomment-2905151957

Refactor objectMonitorExit code format

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp

Reverts eclipse-openj9/openj9#21928
Issue: #21979

Revert "Make the extension and application loaders available via TR_J9VMBase"

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp

Cherry-pick of #21991 for 0.53
Fixes #21979

(0.53) Revert "Make the extension and application loaders available via TR_J9VMBase"

---

runtime/jvmti/jvmtiModules.c

Fixes https://github.com/eclipse-openj9/openj9/issues/22000

Fix add module read JNI return type

---

runtime/gc_modron_standard/StandardAccessBarrier.cpp

fields of the global-incremental stats struct.
In another [PR](https://github.com/eclipse-omr/omr/pull/7768), these fields are eventually merged with general copy stats of the concurrent increment, so that Verbose GC or heuristics report and use accurate total (background threads + barriers) number of copied bytes.

Read Barrier bytes stats

---

runtime/compiler/optimizer/VectorAPIExpansion.cpp
runtime/compiler/optimizer/VectorAPIExpansion.hpp

Reverts eclipse-openj9/openj9#22003
See https://github.com/eclipse-openj9/openj9/pull/22003#issuecomment-2945589884

Revert "Box and unbox all types in VectorAPIExpansion"

---

runtime/compiler/optimizer/JProfilingValue.cpp

In the process of finding values to profile, the method `TR_JProfilingValue::cleanUpAndAddProfilingCandidates` would insert calls to the `jProfileValueWithNullCHK` non-helper for `instanceof` and `checkcast` operations, with the child of each call being an indirect load of the `<vft-symbol>` for the value that is to be profiled.
During `TR_JProfilingValue::addProfilingTrees`, those calls would be transformed to guard the dereference of the indirect load with a test of whether the value is a null reference.
However, if generation of profiling trees is halted early during `TR_JProfilingValue::lowerCalls`, any value beneath the `jProfileValueWithNullCHK` will simply be left anchored in its original position, unguarded.  This can result in a segmentation fault if the value that was to be …

Defer generating dereference of vft-symbol in JProfilingValue

---

runtime/vm/ContinuationHelpers.cpp

- Use J9_LOCK_IS_FLATLOCKED macro instead of count check
- Move reserved check before setting newLockWord
Fix: #21955

Fix prepareForUnmount logic on blocking flatlocks

---

runtime/compiler/optimizer/VectorAPIExpansion.cpp

- generate mLongBitsToMask for fromBitsCoerced intrinsic when
MODE_BITS_COERCED_LONG_TO_MASK is passed

Support  MODE_BITS_COERCED_LONG_TO_MASK Vector API opcode

---

runtime/vm/ContinuationHelpers.cpp

This change addresses the first issue described in https://github.com/eclipse-openj9/openj9/issues/22070#issuecomment-2967760273
Related: https://github.com/eclipse-openj9/openj9/issues/21683
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/51767/

Set vthread BLOCKED state that could be missed in notifyVirtualThread

---

runtime/oti/xhelpers.m4
runtime/vm/jvminit.c

(0.53) x86: Reduce AVX-SSE mixing penalties

---

runtime/vm/jvminit.c

The logic was reversed.
Related: #21972

Fix -XX:[+|-]CacheMaps processing

---

runtime/oti/ContinuationHelpers.hpp
runtime/vm/ContinuationHelpers.cpp

Related to but does not solve https://github.com/eclipse-openj9/openj9/issues/22070

Set BLOCKED state with CAS to prevent race conditions

---

runtime/bcutil/CMakeLists.txt

A temporary workaround for https://github.com/eclipse-openj9/openj9/issues/21825.

Avoid internal compiler error on AIX

---

runtime/tests/port/j9vmemTest.c

Construct the test cases more realistically so that page size combinations only possible on Linux systems should only be created on Linux, and same for AIX.
Change the expected output to match the updated logic in code cache memory allocation.
Issue: https://github.com/eclipse-openj9/openj9/issues/22143

Update the FindValidPageSize Tests for Power

---

test/functional/VM_Test/playlist.xml

Issue https://github.com/eclipse-openj9/openj9/issues/22143#issuecomment-3045722163

Temporarily exclude xlpCodeCacheTests on AIX

---

runtime/compiler/optimizer/VectorAPIExpansion.cpp

- remove redundant work-around
- generate mand, mor, mxor

Generate binary Mask opcodes

---

runtime/vm/BytecodeInterpreter.hpp

When decompileing a blocked continuation, the return address will be patched to point to the decompile helper when we attempt to enter the continuation. This helper assumes the JIT resolve frame is still on the stack. Instead of popping the resolve frame just fetch the new address and leave the frame in place. The decompile helper will pop the frame.

Handle decompile paths when mounting a vthread

---

runtime/rasdump/javadump.cpp
runtime/vm/JFRConstantPoolTypes.hpp

Fixes https://github.com/eclipse-openj9/openj9/issues/22252

Use bigger buffers for getting CPU features so they aren't truncated

---

runtime/jcl/common/vectornatives.cpp
runtime/jcl/exports.cmake
runtime/oti/jclprots.h

Issue https://github.com/eclipse-openj9/openj9/issues/21945

Implement jdk25 VectorSupport_getCPUFeatures

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/env/PersistentAllocator.cpp
runtime/compiler/runtime/DataCache.cpp
runtime/compiler/runtime/IProfiler.cpp
runtime/compiler/runtime/J9CodeCacheManager.cpp

Depends on https://github.com/eclipse-omr/omr/pull/7858

Replace -Xjit:disclaimMemoryOnSwap with -Xjit:preferSwapForMemoryDisclaim

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

This commit generates vectorized inlined code for x86 for methods StringUTF16.indexOf([BI[BII)I and
JITHelpers.intrinsicIndexOfStringUTF16().

x86: Inline StringUTF16.indexOf([BI[BII)I

---

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp

Anchor the children of the newly created trees in the acceleration for vectorizedMismatch. This ensures the inliner will not erase the tree if a child is a function call.

Properly Anchor Children for vectorizedMismatch OffHeap

---

runtime/vm/BytecodeInterpreter.hpp

Reverts eclipse-openj9/openj9#22343
See https://github.com/eclipse-openj9/openj9/pull/22343#issuecomment-3157204498

Revert "Add J2I check in stackoverflow handling"

---

doc/release-notes/0.53/0.53.md

New JFR events added.
[skip ci]

Update 0.53 release notes-New JFR events

---

test/functional/DDR_Test/src/j9vm/test/ddrext/Constants.java
test/functional/DDR_Test/src/j9vm/test/ddrext/junit/TestDDRExtensionGeneral.java

Fixes https://github.com/eclipse-openj9/openj9/issues/21580
Tested via https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/4506/

Modify testDDRExt_General !whatis to use a different class

---

runtime/oti/ContinuationHelpers.hpp
runtime/oti/j9nonbuilder.h
runtime/oti/jvminit.h
runtime/vm/ContinuationHelpers.cpp
runtime/vm/jvminit.c

New XX option to wake up vthread unblocker after set time. Default to enable using 64ms.
Fixes: #22068

Add -XX:[+|-]UnblockerTimedWait option

---

runtime/oti/ContinuationHelpers.hpp
runtime/oti/j9nonbuilder.h
runtime/oti/jvminit.h
runtime/vm/ContinuationHelpers.cpp
runtime/vm/jvminit.c

New XX option to wake up vthread unblocker after set time. Default to enable using 64ms.
Backport of #22395

(v0.54.0) Add -XX:[+|-]UnblockerTimedWait option

---

doc/release-notes/0.54/0.54.md

Added release note for the 0.54.0 release.
[skip ci]

Update 0.54 release notes

---

buildenv/jenkins/variables/defaults.yml

Cherry-pick #22368 for the 0.55.0 release.

(0.55.0) Update to OpenSSL 3.5.2

---

runtime/compiler/z/codegen/J9CodeGenerator.cpp

This reverts commit 811595792558effbdca8f8afab9355dea63cf566.

Z: enable last iTable cache

---

runtime/compiler/optimizer/VectorAPIExpansion.cpp

- the method checks if a node was selected for vectorization or was already
vectorized (e.g. due to commoning)
- handle vload/vstore the same way as aload/astore except for the way we find
the original symbol reference

Fix handling already vectorized aload or astore in VectorAPIExpansion

---

buildenv/jenkins/variables/defaults.yml

Use default AdoptOpenJDK api url for 24

---

runtime/vm/vmthread.cpp

Depends on https://github.com/eclipse-omr/omr/pull/7895

Add options for setting spin/sleep parameter in park()

---

runtime/vm/OutOfLineINL_openj9_internal_foreign_abi_InternalUpcallHandler.cpp

The original code builds the native method frame after memory allocations which may fail and cause exceptions. This will lead to a corruption during stackwalking.
Fixes: https://github.com/eclipse-openj9/openj9/issues/21619
Backport of https://github.com/eclipse-openj9/openj9/pull/22536

(0.56) Build native method frame before exception throw

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java

Fix for Issue #21944
Fix for failing java/foreign/TestBufferStack.java test.
Replaced single HeapArgInfo with a thread-local Deque.
To track multiple argument sets for recursions.
For every downcall a new entry is pushed onto the stack.
The entry is removed from the stack after downcall completion.

Refactor HeapArgInfo to Support Recursive Downcalls

---

runtime/compiler/x/codegen/X86PrivateLinkage.hpp

Remove X86Register.hpp include

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java

Fix for Issue #21944
Fix for failing java/foreign/TestBufferStack.java test. 
Replaced single HeapArgInfo with a thread-local Deque. 
To track multiple argument sets for recursions.
For every downcall a new entry is pushed onto the stack. 
The entry is removed from the stack after downcall completion.
Backport https://github.com/eclipse-openj9/openj9/pull/22370

(v0.55.0-release) Refactor HeapArgInfo to Support Recursive Downcalls

---

runtime/gc_vlhgc/ParallelSweepSchemeVLHGC.cpp

Fix java8 compiling issue

---

runtime/vm/vmthread.cpp

Depends on https://github.com/eclipse-openj9/openj9-omr/pull/245

(0.56) Add options for setting spin/sleep parameter in park()

---

doc/release-notes/0.55/0.55.md

Added release note for the 0.55.0 release.
[skip ci]

Update 0.55 release notes

---

runtime/compiler/optimizer/J9EstimateCodeSize.cpp

This would allow object info propagation in cases where, for example, the necessary object info is obtained from a field prior to the invokedynamic/invokehandle operation.
There is a temporary workaround in place due to a functional issue we may run into during the compilation of
javax/imageio/stream/ImageInputStreamImpl.readLong()J. This functional issue surfaced as a result of the additional inlining of VarHandle operations that is made possible through the peeking ILGen. This workaround will be removed once the underlying issue is resolved.
This commit removes the need to enable this peeking behaviour using env variable TR_enablePeekingForMHInvokes. With the workaround in place, the peeking ILGen for invokedynamic/invokehandle-containing methods are now enabled by default.

Enable peeking ILGen for methods with resolved invokedynamic/handle

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/AbstractPointer.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/StructurePointer.java

* make several fields `final`
* rename `cacheSize` to `CACHE_SIZE`
* promote `nonNullFieldEA()` from `StructurePointer`
* reduce repetition of code patterns:
- use `nonNullAddressEC()` instead of repeating null checks
- use `getIntAtOffset()`, `getLongAtOffset()`, etc. instead of repeating code in those methods
Noticed opportunities while working on #22570.

DDR: Improve AbstractPointer

---

runtime/j9vm/javanextvmi.cpp

Make the minimal changes needed for `StructuredThreadDumpTest` to pass,
without fully implementing `jdk.internal.vm.ThreadSnapshot`.
Reorder operations so objects do not require a special frame for GC
protection when VM access is not held. This also resolves a crash.
Remove setting of `jdk.internal.vm.ThreadSnapshot.blockerObject` to avoid
a crash in `jdk.internal.vm.ThreadDumper`.
A full implementation of `ThreadSnapshot` is not required for release,
since it is an internal API used mainly for introspection in test code.
It can be developed gradually as further tests require support.
Related: #22220
Backport of https://github.com/eclipse-openj9/openj9/pull/22603

(0.55) [JDK25] Fix StructuredTaskScope/StructuredThreadDumpTest

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/gc/GCMixedObjectIterator_V1.java

Don't use `UDATA.longValue()` if the most significant bit might be set.
Fixes: #20758.

Fix GCMixedObjectIterator_V1
