doc/compiler/control/OptionsPostRestore.md
runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/control/OptionsPostRestore.hpp

Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/16852

Post Restore Options Processing Part 4 (0.38)

---

runtime/criusupport/criusupport.cpp
runtime/vm/CRIUHelpers.cpp
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java

The `index` is only for the system property entries;
Mark `-Xoptionsfile=` as consumed;
Added explicit failure exception and error messages.;
Minor refactoring for format consistence.
This was discovered while investigating the test failure https://github.com/eclipse-openj9/openj9/pull/16775#issuecomment-1462042170
Initially, the test passed even though the `success` output string didn't appear due to an NPE such as
```
Exception in thread "main" java.lang.NullPointerException
at java.base/java.lang.System.setProperty(System.java:633)
at openj9.criu/org.eclipse.openj9.criu.CRIUSupport.setRestoreJavaProperties(CRIUSupport.java:600)
at openj9.criu/org.eclipse.openj9.criu.J9InternalCheckpointHookAPI$J9InternalCheckpointHook.runHook(J9InternalCheckpointHookAPI.java:116)
at …
```

CRIU getRestoreSystemProperites() skips non system property entries

---

runtime/jvmti/jvmtiHelpers.c
runtime/jvmti/jvmtiThread.c

(jthread)&threadObject is not a JNI ref, and it will not be
updated by the GC when VM access is released in
jvmtiHelpers.c::getVirtualThreadState.
Non-null thread refs are directly passed to getVirtualThreadState.
A local ref is created for currentThread->threadObject before it is
passed to getVirtualThreadState. This assures that the GC updates
the virtual thread object which is passed to getVirtualThreadState.
In getVirtualThreadState, the virtual thread object is refected
after VM access is re-acquired to prevent access to a stale object.

Pass valid JNI refs to getVirtualThreadState

---

runtime/jvmti/jvmtiHelpers.c
runtime/jvmti/jvmtiThread.c

(jthread)&threadObject is not a JNI ref, and it will not be
updated by the GC when VM access is released in
jvmtiHelpers.c::getVirtualThreadState.
Non-null thread refs are directly passed to getVirtualThreadState.
A local ref is created for currentThread->threadObject before it is
passed to getVirtualThreadState. This assures that the GC updates
the virtual thread object which is passed to getVirtualThreadState.
In getVirtualThreadState, the virtual thread object is refected
after VM access is re-acquired to prevent access to a stale object.
Backport of https://github.com/eclipse-openj9/openj9/pull/16877

(0.37) Pass valid JNI refs to getVirtualThreadState

---

runtime/criusupport/criusupport.cpp
runtime/gc_base/modronapi.cpp
runtime/oti/j9nonbuilder.h
runtime/oti/jvminit.h

A breakpoint set during a pre-checkpoint or post-restore hook will cause Java to hang because the JDWP threads are suspended at that time. This change will delay the suspending of JDWP threads for pre-checkpoint hooks and resume them early for post-restore hooks if VM is run with the JDWP agentlib loaded.
JDK17 sanity.functional testing running internally [here.](https://hyc-runtimes-jenkins.swg-devops.com/job/Pipeline-Build-Test-Personal/15437/)
fyi @tajila @JasonFengJ9

Ensure JDWP threads are not halted when hooks run for CRIU

---

test/functional/cmdLineTests/criu/playlist.xml

Extend existing cmdLineTester_criu_nonPortableRestore test case with GC threading opts variation to stress GC thread pool contraction and expansion.
- -Xgcthreads1 will test unbounded thread pool expansion as the thread pool will need to be reinited at restore
- -Xgcthreads64 -XX:CheckpointGCThreads=1 will force 63 threads to shutdown during checkpoint

Stress CRIU GC Thread Pool Contract/Expand Routines

---

jcl/src/java.base/share/classes/java/lang/Access.java
runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp

Correctly generate method signatures for lambda functions that take Q type arguments
For #13182 (fixes error in WithFieldAccessorTest)

Fix Q types in lambda signature generation

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp

Backporting missing break fix from #16471 to 0.38 release.
Closes https://github.com/eclipse-openj9/openj9/issues/11741

(0.38) Adding the missing break statement

---

doc/release-notes/0.37/0.37.md

Closes https://github.com/eclipse-openj9/openj9/issues/16824
Updated the release note with tokenlabel support for SunPKCS11 configuration on Linux on Z based on https://github.com/eclipse-openj9/openj9-docs/issues/1057
[skip ci]

Update release note 0.37.0 with tokenlabel support on Linux Z

---

runtime/criusupport/criusupport.cpp
runtime/nls/j9vm/j9vm.nls
runtime/oti/j9nonbuilder.h
runtime/oti/j9trace.h
runtime/oti/jvminit.h
runtime/oti/vm_api.h
runtime/rastrace/j9rastrace.h
runtime/rastrace/method_trace.c
runtime/rastrace/trcengine.c
runtime/vm/CRIUHelpers.cpp
runtime/vm/jvminit.c
runtime/vm/rastrace.c
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/criu_nonPortable_Xtrace.xml
test/functional/cmdLineTests/criu/playlist.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java

* Refactored trace initialization to be used by VM startup and CRIU restore using an options file;
* Added `RasGlobalStorage->criuRestoreInitializeTrace()`;
* Added `setRAMClassExtendedMethodFlagsHelper()` used by `hookRAMClassLoad()` and `addInternalJVMClassIterationRestoreHook()`;
* Set `methodTriggerType->runtimeModifiable` to true for CRIU;
* Moved some trace initialization code into `traceInitializationHelper()` for VM startup and CRIU restore using an options file;
* Added a parameter `J9VMInitArgs` for `initializeTraceOptions()`;
* Added a test to verify `-Xtrace:print={j9vm.40}`, `-Xtrace:print=mt,methods=java/lang/System.getProperties()`, `-Xtrace:trigger=method{java/lang/System.getProperties,javadump}`.
Depends 
* https://github.com/eclipse-openj9/openj9/pull/16622 …

CRIU restore loads trace options with registerRestoreOptionsFile()

---

runtime/vm/ObjectMonitor.cpp

Fixes https://github.com/eclipse-openj9/openj9/issues/16685

(0.37) Set thread blocked flag before triggering JVMTI Monitor Contended Enter

---

runtime/criusupport/criusupport.cpp
runtime/gc_base/modronapi.cpp
runtime/oti/j9nonbuilder.h
runtime/oti/jvminit.h

A breakpoint set during a pre-checkpoint or post-restore hook will cause Java to hang because the JDWP threads are suspended at that time. This change will delay the suspending of JDWP threads for pre-checkpoint hooks and resume them early for post-restore hooks if VM is run with the JDWP agentlib loaded.
Port of https://github.com/eclipse-openj9/openj9/pull/16653 to 0.38.0
fyi @tajila

(v0.38.0)Ensure JDWP threads are not halted when hooks run for CRIU

---

runtime/jcl/common/vm_scar.c
runtime/oti/jvminit.h

The startup stage OFFLOAD_JCL_PRECONFIGURE is unused.

Delete remnant of OFFLOAD support that was missed

---

runtime/oti/jvminit.h

Noticed with the introduction of `FIND_AND_CONSUME_NEXT_ARG_FORWARD` in #16775.

Add missing parentheses in macro definitions

---

runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp

- 'or' in the assert should be 'and'.
Fixes https://github.com/eclipse-openj9/openj9/issues/11745
- Ternary operator in `generateVectorPackedToBinaryConversion` is not
needed since the result is the same.
Fixes https://github.com/eclipse-openj9/openj9/issues/11744

Remove redundant check and fix assert condition in DAA evaluators

---

runtime/vm/ContinuationHelpers.cpp

Back port of #16884 
Closes: #15189 

(0.37) Use GC continuation list in walkAllStackFrames

---

runtime/criusupport/criusupport.cpp
runtime/nls/j9vm/j9vm.nls
runtime/oti/j9nonbuilder.h
runtime/oti/j9trace.h
runtime/oti/jvminit.h
runtime/oti/vm_api.h
runtime/rastrace/j9rastrace.h
runtime/rastrace/method_trace.c
runtime/rastrace/trcengine.c
runtime/vm/CRIUHelpers.cpp
runtime/vm/jvminit.c
runtime/vm/rastrace.c
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/criu_nonPortable_Xtrace.xml
test/functional/cmdLineTests/criu/playlist.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java

* Refactored trace initialization to be used by VM startup and CRIU restore using an options file;
* Added `RasGlobalStorage->criuRestoreInitializeTrace()`;
* Added `setRAMClassExtendedMethodFlagsHelper()` used by `hookRAMClassLoad()` and `addInternalJVMClassIterationRestoreHook()`;
* Set `methodTriggerType->runtimeModifiable` to true for CRIU;
* Moved some trace initialization code into `traceInitializationHelper()` for VM startup and CRIU restore using an options file;
* Added a parameter `J9VMInitArgs` for `initializeTraceOptions()`;
* Added a test to verify `-Xtrace:print={j9vm.40}`, `-Xtrace:print=mt,methods=java/lang/System.getProperties()`, `-Xtrace:trigger=method{java/lang/System.getProperties,javadump}`.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/16775 …

(v0.38.0-release) CRIU restore loads trace options with registerRestoreOptionsFile()

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/control/OptionsPostRestore.hpp

Since JITServer is enabled implicitly in Non Portable Mode, specifying `-XX:-UseJITServer` should disable it post-restore.
Additionally, if `-Xshareclasses:disableOnRestore` is specified, disable AOT (see https://github.com/eclipse-openj9/openj9/issues/16868).

Add support to disable JITServer and AOT post restore

---

runtime/vm/CRIUHelpers.cpp
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/EnvVarFileTest.java

Add support for -Xrs on restore
This PR adds support for -Xrs on restore. Given that its imposible to support -Xrs in the same manner on restore that it is supported at startup (because there may be frames on the stack with signal handlers already installed that cannot be removed on restore) this change requires that "onRestore" is appended to the option.
For example: -Xrs:sync -> -Xrs:syncOnRestore, -Xrs -> -Xrs:onRestore, ..

Add support for -Xrs on restore

---

runtime/gc_base/GCExtensions.hpp
runtime/gc_base/modronapi.cpp
runtime/gc_include/VerboseGCInterface.h
runtime/gc_modron_startup/GCVerboseInterface.cpp
runtime/gc_verbose_java/VerboseJava.cpp
runtime/gc_verbose_java/VerboseManagerJava.cpp
runtime/gc_verbose_java/VerboseManagerJava.hpp
runtime/oti/verbose_api.h
runtime/verbose/verbose.c

Implementation to support CRIU Verbose GC logging.
> Verbose GC logging must be properly initialized and reconfigured, taking into account both restore options and initial verbose configuration at startup. There are multiple configuration scenarios possible depending on whether logging is enabled/disabled (pre/post restore) and the options provided at each phase.
- Introduced reinitalizationInProgress GC Extensions API, this is queried by GC to check if we're in the middle of restore reinit
- Introduced checkOptsAndInitVerbosegclog in verbose function table, high level method to check opt args and init verbose
- fileOpenMode implemented for VerboseManagerJava to signify that verbose file writers must append during reinit
Related: …

CRIU Verbose Logging Reinit/Reconfig for Restore

---

runtime/gc_base/modronapi.cpp
runtime/gc_modron_startup/mminit.cpp
runtime/nls/j9gc/j9modron.nls

- Invoke newly introduced Global Collector reinit API in OMR.
- reset parSweepChunkSize to allow sweep to reinit. 
- verify thread count being set at restore time to enure that its greater than the checkpoint thread count.
- WARN with J9NLS_GC_THREAD_VALUE_MUST_BE_ABOVE_WARN
Depends on: https://github.com/eclipse/omr/pull/6925

CRIU Invoke Global Collector Reinit 

---

test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/criu_nonPortable_Xtrace.xml

CRIU tests use `success` and explicit `failure` conditions before `checkpoint`
Removed `bytecode static method` to accommodate both bytecode and jitted methods.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/16913

(v0.38.0-release) CRIU tests use success and explicit failure conditions before checkpoint

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/OptionsPostRestore.cpp

If `-Xdump` is specified to dump on exception post-restore (but not pre-checkpoint), then invalidate all compilations, since they will not have been generated to support it.

Invalidate compiles if -Xdump on exception is specified post restore

---

runtime/nls/j9gc/j9modron.nls

Add sample input to J9NLS_GC_THREAD_VALUE_MUST_BE_ABOVE_WARN
Related to https://github.com/eclipse-openj9/openj9/pull/16883#discussion_r113878435

Add Missing GC NLS Sample Input

---

doc/compiler/jitserver/README.md

A link to the Problem Determination guide for jitserver contained a typo.  This change corrects that link.

Correct link to jitserver Problem Determination guide

---

jcl/src/java.base/share/classes/openj9/internal/criu/security/CRIUConfigurator.java

When making use of the CRIU feature for a fast startup it has been found
that fetching algorithms is quite slow from the providers installed.
This update saves all algorithms available in all providers prior to
a checkpoint being taken. This cache then becomes available for callers
after a restore has taken place.
Any updates to the security providers order made via the Security
classes triggers the invalidation of this cache.
This update is needed for https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/565
Signed-off-by: Jason Katonica <katonica@us.ibm.com>

Cache Security Algorithms For CRIU Startup

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp

generateReportFieldAccessOutlinedInstructions incorrectly believes that when it is run on a awrtbar/awrtbari node and compressed refs is active, it is being passed a compressed object address to pass into a call to the VM. In reality, it is being given an uncompressed object address and the VM is expecting an uncompressed value. This causes a problem where a stw instruction is used to store a 64 bit value.
This change removes the special case handling of a compressed ref value for calculating elementSize. By default, convertTypeToSize already returns the correct value of 8 for 64 bit (and 4 for 32 bit).
Issue: #16750

(0.37) Fixing wrong address elementSize calculation

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp

generateReportFieldAccessOutlinedInstructions incorrectly believes that when it is run on a awrtbar/awrtbari node and compressed refs is active, it is being passed a compressed object address to pass into a call to the VM. In reality, it is being given an uncompressed object address and the VM is expecting an uncompressed value. This causes a problem where a stw instruction is used to store a 64 bit value.
This change removes the special case handling of a compressed ref value for calculating elementSize. By default, convertTypeToSize already returns the correct value of 8 for 64 bit (and 4 for 32 bit).
Issue: #16750
Port of https://github.com/eclipse-openj9/openj9/pull/16925

(0.38) Fixing wrong address elementSize calculation

---

debugtools/DDR_VM/src/com/ibm/j9ddr/AuxFieldInfo29.dat
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/CoreInfoCommand.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/view/dtfj/java/DTFJJavaRuntime.java
runtime/oti/j9nonbuilder.h
runtime/vm/rasdump.c

The jdmpview `info system` output includes the JavaRuntime version. Also include the product name in the !coreinfo output.
Only OpenJ9 builds have a product name.
Closes https://github.com/eclipse-openj9/openj9/issues/16930

Include the product name in the DTFJ JavaRuntime version

---

runtime/rastrace/trcengine.c
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java

Add support for `-Xtrace:maximal=mt,methods=java/lang/System.setProperties(),output=traceOutput.txt`;
Added a test.

CRIU restore setup Xtrace output file

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/env/VMJ9.cpp
runtime/nls/j9vm/j9vm.nls
runtime/oti/j9dump.h
runtime/oti/j9nonbuilder.h
runtime/oti/jvminit.h
runtime/rasdump/dmpsup.c
runtime/shared_common/shrinit.cpp
runtime/shared_common/shrinit.h
runtime/vm/CRIUHelpers.cpp
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/criu_nonPortable_RAS.xml
test/functional/cmdLineTests/criu/playlist.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java

Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/16926 which requires the following PR
* https://github.com/eclipse-openj9/openj9/pull/16921 there is 0.38 PR
* * https://github.com/eclipse-openj9/openj9/pull/16947

(v0.38.0-release) CRIU restore with -Xdump using CRIUSupport.registerRestoreOptionsFile() 

---

runtime/compiler/build/files/common.mk

OMR pull request eclipse/omr#6577 renames `RegisterCandidate.cpp` to `OMRRegisterCandidate.cpp`, and adds a new file, `OMRGlobalRegister.cpp`. Both of these files are located in `omr/compiler/optimizer`.  This change updates the OpenJ9 `common.mk` file that is used by older versions of the build infrastructure to compile those files.

Update common.mk to compile new OMR Register Allocator files

---

runtime/rastrace/trcengine.c
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java

Add support for `-Xtrace:maximal=mt,methods=java/lang/System.setProperties(),output=traceOutput.txt`;
Added a test.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/16944

(v0.38.0-release) CRIU restore setup Xtrace output file

---

runtime/oti/j9nonbuilder.h
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/CMakeLists.txt
runtime/vm/UpcallExceptionHandler.cpp
runtime/vm/UpcallVMHelpers.cpp
runtime/vm/vmthread.cpp
test/functional/Java17andUp/src_170/org/openj9/test/jep389/upcall/InvalidUpCallTests.java
test/functional/Java17andUp/src_170/org/openj9/test/jep389/upcall/UpcallMethodHandles.java
test/functional/Java17andUp/testng_170.xml
test/functional/Java19andUp/src/org/openj9/test/jep424/upcall/InvalidUpCallTests.java
test/functional/Java19andUp/src/org/openj9/test/jep424/upcall/UpcallMethodHandles.java
test/functional/Java19andUp/testng_190.xml

The change exploits setjmp/longjmp to return back to the call-out frame
by skipping the native function when an exception triggered by the upcall
method is captured in the dispatcher.

[FFI] Handling the captured exceptions for the upcall method

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/OptionsPostRestore.cpp

The VM sets `vm->sharedCacheAPI->xShareClassCacheDisabledOnCRIURestore` when -Xshareclasses:disableOnRestore post-restore. Rather than parsing the option directly, the compiler should just use this field.

Use sharedCacheAPI to determine -Xshareclasses:disableOnRestore

---

runtime/compiler/p/codegen/PPCPrivateLinkage.cpp

Backport  #16813 to 0.38 release

(0.38) Disable CRC32C optimization when arraylets are enabled on Power

---

debugtools/DDR_VM/src/com/ibm/j9ddr/AuxFieldInfo29.dat
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/CoreInfoCommand.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/view/dtfj/java/DTFJJavaRuntime.java
runtime/oti/j9nonbuilder.h
runtime/vm/rasdump.c

The jdmpview `info system` output includes the JavaRuntime version.
Also include the product name in the !coreinfo output.
Only OpenJ9 builds have a product name.
Issue https://github.com/eclipse-openj9/openj9/issues/16930
Update jdmpview !coreinfo to print vm properties and also sort the environment variables.
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/16931 and https://github.com/eclipse-openj9/openj9/pull/16941 for 0.38

(0.38) Include the product name in the DTFJ JavaRuntime version, print vm props

---

runtime/jvmti/jvmtiThread.c

Fix GetCurrentContendedMonitor on mounted CarrierThread

---

runtime/jvmti/jvmtiThread.c

Back port of #16983
Closes: #16997 

(0.37) Fix GetCurrentContendedMonitor on mounted CarrierThread

---

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/SystemRestoreException.java
runtime/compiler/optimizer/SimplifierHandlers.hpp
runtime/compiler/optimizer/SimplifierTable.enum
runtime/compiler/p/runtime/J9PPCCRC32C_constants.h
test/functional/Java11andUp/src/org/openj9/test/crc32c/TestJavaUtilZipCRC32C.java

A few new files were added since #16322 with URLs from the old copyright notice.

Reference openjdk.org instead of openjdk.java.net

---

runtime/gc_modron_startup/mminit.cpp
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/CRIUHelpers.cpp
runtime/vm/intfunc.c

Add a javaVM variant of isCheckpointAllowed
Some JVM components need to query if checkpoint is allowed before VM threading is initialized.
Fixes https://github.com/eclipse-openj9/openj9/issues/16976

(0.38) Add a javaVM variant of isCheckpointAllowed

---

runtime/gc_base/module.xml

Required to enable CRIU support since #16666.

Add missing include path for UMA build

---

runtime/rasdump/dmpsup.c
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/criu_nonPortable_RAS.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java

Replaced `FIND_AND_CONSUME_VMARG` with `FIND_AND_CONSUME_ARG`;
Replaced `GET_INTEGER_VALUE` with `GET_INTEGER_VALUE_ARGS`;
Update the test.

CRIU configureDumpAgents() macros apply J9VMInitArgs

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h

`Thread.currentThread` can be changed by JCL in JDK19 and up. Set it as volatile for JDK19 and up.
Add `isJ9VMThreadCurrentThreadImmutable` in FrontEnd to query whether or not `Thread.currentThread` is immutable based on `JAVA_SPEC_VERSION`.
Issue #16258

Remove setImmutableField on currentThread for JDK19 and up

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h

`Thread.currentThread` can be changed by JCL in JDK19 and up. Set it as volatile for JDK19 and up.
Add `isJ9VMThreadCurrentThreadImmutable` in FrontEnd to query whether or not `Thread.currentThread` is immutable based on `JAVA_SPEC_VERSION`.
Cherry-picked:
Fixes #16258

(v0.37.0-release) Remove setImmutableField on currentThread for JDK19 and up

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/env/VMJ9.cpp
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/criu_nonPortable_RAS.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java

Restore JIT `J9HookDisable` `J9HOOK_VM_EXCEPTION_CATCH`/`J9HOOK_VM_EXCEPTION_THROW`;
Update tests.
closes https://github.com/eclipse-openj9/openj9/issues/16958

CRIU requires Xdump::dynamic to support exception throw/catch options

---

test/functional/cmdLineTests/criu/criu_nonPortableJDK11Up.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/JDK11UpTimeoutAdjustmentTest.java

Fixed a time unit output;
Added time measurement tests w/o C/R involved;
Added more verbose messages.
Related https://github.com/eclipse-openj9/openj9/issues/16907 https://github.com/eclipse-openj9/openj9/issues/16643

CRIU JDK11UpTimeoutAdjustmentTest add verbose test output

---

jcl/src/java.base/share/classes/openj9/internal/criu/security/CRIUConfigurator.java

When making use of the CRIU feature for a fast startup it has been found
that fetching algorithms is quite slow from the providers installed.
This update saves all algorithms available in all providers prior to
a checkpoint being taken. This cache then becomes available for callers
after a restore has taken place.
Any updates to the security providers order made via the Security
classes triggers the invalidation of this cache.
This update is needed for https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/565
Signed-off-by: Jason Katonica <katonica@us.ibm.com>

Cache Algorithms For CRIU Startup

---

buildenv/docker/mkdocker.sh

* bootjdk versions may not be supported for building
* use openj9 bootjdk for jdk18

Add support for jdk20 in mkdocker.sh and remove jdk18

---

runtime/gc_glue_java/ScavengerDelegate.cpp

function isCurrentPhaseConcurrent() is only available under OMR_GC_CONCURRENT_SCAVENGER.

Fix the 32-bit compile issue in ScavengerDelegate.cpp

---

test/functional/Java20andUp/build.xml
test/functional/Java20andUp/playlist.xml

The changes temporarily disable all FFI specific
test suites as we might need to update them
accordingly in OpenJDK & OpenJ9 once the new
changes for OpenJDK are merged to the HEAD
repository.

Disable FFI specific test suites for JDK21

---

runtime/jcl/common/system.c
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/UsernameTest.java

When checkpoints are possible we avoid calling `j9sysinfo_get_username` but don't fall back to `j9sysinfo_get_env` as intended. Fix it by making sure that path will be taken in this case.

Fix getting username from env in checkpoint mode

---

runtime/rasdump/dmpsup.c
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/criu_nonPortable_RAS.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java

Replaced `FIND_AND_CONSUME_VMARG` with `FIND_AND_CONSUME_ARG`;
Replaced `GET_INTEGER_VALUE` with `GET_INTEGER_VALUE_ARGS`;
Update the test.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/17006

(v0.38.0-release) CRIU configureDumpAgents() macros apply J9VMInitArgs

---

runtime/compiler/CMakeLists.txt
runtime/compiler/build/files/common.mk
runtime/compiler/control/CMakeLists.txt
runtime/compiler/control/CompilationStrategy.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/CompileBeforeCheckpoint.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9CompilationStrategy.cpp
runtime/compiler/control/J9CompilationStrategy.hpp
runtime/compiler/control/J9Recompilation.cpp
runtime/compiler/control/J9Recompilation.hpp
runtime/compiler/control/RecompilationInfo.hpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/runtime/HWProfiler.cpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JitRuntime.cpp

- using CompilationController directly from OMR
- making CompilationStrategy extensible class
Signed-off-by: Tao Guan <james_mango@yahoo.com>

Refactor CompilationStrategy and CompilationController

---

runtime/rasdump/dmpsup.c
runtime/rasdump/j9dmp.tdf
runtime/rastrace/j9trc.tdf
runtime/rastrace/trcengine.c
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/criu_nonPortable_RAS.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java

Invoke `startTraceWorkerThread()` before checking `traceMethodTable`/`triggerOnMethods`;
Added tracepoints;
Added a test.

CRIU Xtrace prepares the trace output file

---

test/functional/Java17andUp/src_170/org/openj9/test/jep389/upcall/InvalidUpCallTests.java
test/functional/Java17andUp/src_170/org/openj9/test/jep389/upcall/UpcallMethodHandles.java
test/functional/Java19andUp/src/org/openj9/test/jep424/upcall/InvalidUpCallTests.java
test/functional/Java19andUp/src/org/openj9/test/jep424/upcall/UpcallMethodHandles.java
test/functional/Java20andUp/src/org/openj9/test/jep434/upcall/InvalidUpCallTests.java
test/functional/Java20andUp/src/org/openj9/test/jep434/upcall/UpcallMethodHandles.java

The changes add one test case to validate the exception handling code in the nested upcall.
Fixes: #16962

[FFI/Test] Add an exception case for the nested upcall

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/control/JITServerHelpers.hpp
runtime/compiler/control/OptionsPostRestore.cpp

With JITServer Technology, each client JVM has a unique ID that is generated during JVM bootstrap. When checkpointing a JVM that is supposed to be used in client mode, this client UID gets baked into the JVM snapshot, and all JVM processes that are restored from this snapshot will have the same UID, which confuses the server. This comit re-generates the client UID during the snapshot restore operation so that different clients will have different UIDs.
Issue: #17022

Re-generate client UID after CRIU restore operation

---

runtime/rasdump/dmpsup.c
runtime/rasdump/j9dmp.tdf
runtime/rastrace/j9trc.tdf
runtime/rastrace/trcengine.c

Added `Trc_trcengine_criu_criuRestoreInitializeTrace_Entry` & `Trc_trcengine_criu_criuReloadXDumpAgents_Entry`;
Updated `Trc_trcengine_criu_criuRestoreInitializeTrace_Exit` & `Trc_trcengine_criu_criuReloadXDumpAgents_Exit`.
Related https://github.com/eclipse-openj9/openj9/pull/17017

Add paired TraceEntry

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/control/JITServerHelpers.hpp
runtime/compiler/control/OptionsPostRestore.cpp

With JITServer Technology, each client JVM has a unique ID that is generated during JVM bootstrap. When checkpointing a JVM that is supposed to be used in client mode, this client UID gets baked into the JVM snapshot, and all JVM processes that are restored from this snapshot will have the same UID, which confuses the server. This comit re-generates the client UID during the snapshot restore operation so that different clients will have different UIDs.
Issue: #17022

Re-generate client UID after CRIU restore operation (0.38.0)

---

runtime/rasdump/dmpsup.c
runtime/rasdump/j9dmp.tdf
runtime/rastrace/j9trc.tdf
runtime/rastrace/trcengine.c
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/criu_nonPortable_RAS.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java

Invoke `startTraceWorkerThread()` before checking `traceMethodTable`/`triggerOnMethods`;
Added tracepoints;
Added a test.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/17017
* https://github.com/eclipse-openj9/openj9/pull/17057

(v0.38.0-release) CRIU Xtrace prepares the trace output file

---

jcl/src/java.base/share/classes/jdk/internal/foreign/abi/UpcallLinker.java
runtime/j9vm/exports.cmake
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/javanextvmi.cpp
runtime/j9vm/module.xml
runtime/redirector/forwarders.m4
runtime/redirector/module.xml

`JVM_VirtualThreadMount` invokes `JVM_VirtualThreadMountBegin` if `hide` is `true`, otherwise `JVM_VirtualThreadMountEnd`;
Similarly for `JVM_VirtualThreadUnmount`;
Added stub methods UpcallLinker.makeFactory().
Related https://github.com/eclipse-openj9/openj9/issues/16984
Required by https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/572

JDK21 adds JVM_VirtualThreadMount/JVM_VirtualThreadUnmount

---

jcl/src/openj9.dtfj/share/classes/module-info.java

Issue https://github.com/eclipse-openj9/openj9/issues/16783
A test plugin installed via `-Dcom.ibm.java.diagnostics.plugins` uses the following classes:
```
import com.ibm.java.diagnostics.utils.IContext;
import com.ibm.java.diagnostics.utils.commands.BaseCommand;
import com.ibm.java.diagnostics.utils.commands.CommandException;
import com.ibm.java.diagnostics.utils.plugins.DTFJPlugin;
```

Export dtfj packages required for plugins

---

test/functional/Java17andUp/src_170/org/openj9/test/jep389/upcall/UpcallMethodHandles.java
test/functional/Java19andUp/src/org/openj9/test/jep424/upcall/UpcallMethodHandles.java

The PR restores the fixed test code in
addDoubleAndIntDoubleLongFromStruct() for AIX in JD17 & 19
in https://github.com/eclipse-openj9/openj9/pull/16835 which 
was incidentally overwritten by the outdated test code introduced
in https://github.com/eclipse-openj9/openj9/pull/17014/.
Fixes: #17071

[FFI/Test] Restore the fix for addDoubleAndIntDoubleLongFromStruct

---

jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/ContextFactory.java
jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/commands/BaseCommand.java

Fix javadoc errors seen in https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_Personal/47.
Also
* tidy up

Fix javadoc errors and add explicit constructors

---

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
runtime/compiler/control/HookedByTheJit.cpp
runtime/gc_base/GCExtensions.hpp
runtime/j9vm/javanextvmi.cpp
runtime/jcl/common/jclcinit.c
runtime/jcl/common/thread.cpp
runtime/jvmti/jvmtiHelpers.c
runtime/jvmti/jvmtiThread.c
runtime/oti/VMHelpers.hpp
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/oti/vmconstantpool.xml
runtime/vm/ContinuationHelpers.cpp
runtime/vm/intfunc.c
runtime/vm/vmthinit.c

Removes use of `liveVirtualThreadList/liveVirtualThreadListMutex` in the VM and rely on GC's Continuation list.
This design uses an atomic based RW lock with busy waiting for vthread access during mounted/unmount transition.
Global access in JVMTI is a slow path and done through Exclusive VM Access which doesn't require additional locking.
mutual dependency: 
jdk19: https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/83
jdk20: https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/32
jdknext: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/574
Fixes: #16728 

Refactor VirtualThread synchronization design

---

runtime/compiler/optimizer/J9ValuePropagation.cpp

The `arraycmp` operation produces a result of zero if the memory being compared is equal, one if the first operand is less than the second, or two if the second operand is less than the first.  The transformation of `<object{Equality|Inequality}Comparison>` used `arraycmp` assuming that the result would be zero for equality or one for inequality.  This change adds an `icmpeq` or `icmpne` to compare the result of the `arraycmp` with zero in order to yield a value in the expected range:  {0,1}.

Test result of arraycmp for value type comparison

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java

The changes check the life cycle of the surrounding scope of the downcall
function address to guarantee the validity of the scope during the downcall.
Fixes: #17062

[FFI/Jtreg] Validate the downcall function address in JDK20

---

runtime/compiler/control/HookedByTheJit.cpp

Correctly ifdef Java19 code

---

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
runtime/compiler/control/HookedByTheJit.cpp
runtime/gc_base/GCExtensions.hpp
runtime/j9vm/javanextvmi.cpp
runtime/jcl/common/jclcinit.c
runtime/jcl/common/thread.cpp
runtime/jvmti/jvmtiHelpers.c
runtime/jvmti/jvmtiThread.c
runtime/oti/VMHelpers.hpp
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/oti/vmconstantpool.xml
runtime/vm/ContinuationHelpers.cpp
runtime/vm/intfunc.c
runtime/vm/vmthinit.c

Removes use of liveVirtualThreadList/liveVirtualThreadListMutex in the VM and rely on GC's Continuation list.
This design uses an atomic based RW lock with busy waiting for vthread access during mounted/unmount transition.
Global access in JVMTI is a slow path and done through Exclusive VM Access which doesn't require additional locking.
mutual dependency:
https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/87
Port of #16855 and #17086

(0.37) Refactor VirtualThread synchronization design

---

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
runtime/gc_base/GCExtensions.cpp
runtime/oti/VMHelpers.hpp
runtime/oti/j9nonbuilder.h
runtime/oti/vmconstantpool.xml
runtime/vm/ContinuationHelpers.cpp

The state of Continuation is mainly used for synchronizing continuation mounting/unmount and continuation scanning, in order to prevent potential timing hole to view/update the state around new/delete the native structure, the state is relocated from native structure to continuation Object.
accessing the state from native methods via vmconstantpool.
issue: https://github.com/eclipse-openj9/openj9/issues/17058

Relocate state of Continuation from native structure to Object

---

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
runtime/gc_base/GCExtensions.cpp
runtime/oti/VMHelpers.hpp
runtime/oti/j9nonbuilder.h
runtime/oti/vmconstantpool.xml
runtime/vm/ContinuationHelpers.cpp

The state of Continuation is mainly used for synchronizing continuation mounting/unmount and continuation scanning, in order to prevent potential timing hole to view/update the state around new/delete the native structure, the state is relocated from native structure to continuation Object.
accessing the state from native methods via vmconstantpool.
fix: https://github.com/eclipse-openj9/openj9/issues/17058
backport: https://github.com/eclipse-openj9/openj9/pull/17081

(0.37.0)Relocate state of Continuation from native structure to Object

---

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/CommonDirectory.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/FileLock.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/IPC.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/WaitLoop.java
jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9VirtualMachine.java
test/functional/Java8andUp/src/org/openj9/test/fileLock/NativeFileLock.java

Added a system property `com.ibm.tools.attach.disableFileLockWatchdog`;
Setting `-Dcom.ibm.tools.attach.useFileLockWatchdog=[true|false]` takes precedence, if no such system property is specified, always set false on `z/OS`, defaults to true on non-z/OS platforms.
Related [RTC 148596](https://jazz103.hursley.ibm.com:9443/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/148596)
This fixes the zOS usage w/ multiple JVMs running under different user IDs.
Since this issue wasn't seen on other platforms, it is intended to not introduce behaviour differences for non zOS systems unless `-Dcom.ibm.tools.attach.useFileLockWatchdog=false` is specified.
I think this option can be an internal undocumented unless there is actual usage.

zOS AttachAPI doesn't use FileLockWatchdogTask for CommonControlFiles

---

runtime/ddr/gcddr.cpp

GC MemoryPoolHybrid is being removed in OMR, all references to it must also be removed in OpenJ9.

Update GC DDR to Remove Unused GC MemoryPoolHybrid

---

runtime/codert_vm/arm64nathelp.m4

This commit adds lines in NEW_DUAL_MODE_HELPER for saving the return address in VMThread->jitReturnAddress.
Fixes #14530

AArch64: Save return address in VMThread in NEW_DUAL_MODE_HELPER

---

jcl/src/java.base/share/classes/java/lang/Access.java

`valhalla` enable `java/lang/Access` methods
required by https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/pull/7

valhalla enable java/lang/Access methods

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/net/CommunicationStream.cpp
runtime/compiler/net/CommunicationStream.hpp

This fix is proposed for the Issue #17003 and is composed of 2 parts:
1. Using the  MethodToBeCompiled->_compilationAttemptsLeft counter the client will locally compile the method after the MAX_COMPILE_ATTEMPTS has reached.
2. In the readOnceBlocking code if the same read error is encountered more than 3 times then we assume that there is something wrong with the server accepting requests from the client and hence do all further method compilation locally and retry after waitTime as in the case of retry logic for connection failures.

Handling of non-TLS client connect failures to an encrypted JITServer

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.cpp
runtime/compiler/net/MessageTypes.hpp
runtime/compiler/runtime/JITClientSession.hpp

Two frontend queries that are specific to CRIU, `inSnapshotMode()` and `isSnapshotModeEnabled()` need to be overridden with JITServer specific implementation that fetches the required information from the client.
Three new fields were added to the `ClientSessionData.VMInfo` struct which caches information per client:
bool _inSnapshotMode;
bool _isSnapshotModeEnabled;
bool _isNonPortableRestoreMode;
`_isSnapshotModeEnabled` and `_isNonPortableRestoreMode` can be cached from the very first response of the client, because they get set when the VM is initialized and never change their value.
`_inSnapshotMode` requires special handling: if the client runs in portable restore mode, then this field is always true. If the client runs in non-portable restore mode, then this field starts as true, …

Provide JITServer implementation for CRIU specific FE queries

---

runtime/vm/ValueTypeHelpers.cpp

Some entries in the FCC have their clazz field set to null, these null classes should not be dereferenced
For #13182 (fixes error in UninitializedInlineFieldsTest, as well as other tests)

Ignore null classes when searching the FCC

---

runtime/compiler/control/CompileBeforeCheckpoint.cpp

The following deadlock is possible:
1. Comp thread read-enters class unload mutex
2. Checkpointing thread acquires comp monitor
3. Comp thread blocks trying to acquire comp monitor
4. Checkpointing thread blocks trying to write-enter class unload mutex
The reason the Checkpointing thread acquires the class unload mutex is to prevent class unloading while it collects methods. However, a read-acquire is sufficient for this task.
Therefore, having the Checkpointing thread do a read-acquire will prevent the deadlock since it will not block waiting to enter.

Read-acquire Class Unload Mutex for compilation before checkpoint

---

runtime/compiler/control/CompileBeforeCheckpoint.cpp

Fixes build break described in https://github.com/eclipse-openj9/openj9/pull/17136#issuecomment-1502471086

Remove empty parentheses when constructing TR::ClassUnloadMonitorCriticalSection object

---

doc/compiler/aot/RelocationRecords.md

The actual purpose of the TR_BodyInfoAddress and TR_BodyInfoAddressLoad relocations is to relocate the address of the recompilation counter, which is (and must remain) the first field of the
TR_PersistentJittedBodyInfo. The docs should mention this fact.
Attn @mpirvu.

Clarify usage of the body info address relocations

---

runtime/compiler/control/CompileBeforeCheckpoint.cpp

Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/17136 and https://github.com/eclipse-openj9/openj9/pull/17143 (squashed into one commit)

Read-acquire Class Unload Mutex for compilation before checkpoint (0.38)

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.cpp
runtime/compiler/net/MessageTypes.hpp
runtime/compiler/runtime/JITClientSession.hpp

Two frontend queries that are specific to CRIU, `inSnapshotMode()` and `isSnapshotModeEnabled()` need to be overridden with JITServer specific implementation that fetches the required information from the client.
Three new fields were added to the `ClientSessionData.VMInfo` struct which caches information per client:
bool _inSnapshotMode;
bool _isSnapshotModeEnabled;
bool _isNonPortableRestoreMode;
`_isSnapshotModeEnabled` and `_isNonPortableRestoreMode` can be cached from the very first response of the client, because they get set when the VM is initialized and never change their value.
`_inSnapshotMode` requires special handling: if the client runs in portable restore mode, then this field is always true. If the client runs in non-portable restore mode, then this field starts as true, …

Provide JITServer implementation for CRIU specific FE queries (0.38.0)

---

runtime/jcl/common/sigusr2.c
runtime/oti/jvminit.h
runtime/vm/jvminit.c

The default setting is -XX:+HandleSIGUSR2.
-XX:-HandleSIGUSR2 allows a user to install a signal handler for
SIGUSR2 without relying upon signal handler chaining (jsig).

Add support for -XX:[+|-]HandleSIGUSR2

---

runtime/jcl/common/sigusr2.c
runtime/oti/jvminit.h
runtime/vm/jvminit.c

The default setting is -XX:+HandleSIGUSR2.
-XX:-HandleSIGUSR2 allows a user to install a signal handler for
SIGUSR2 without relying upon signal handler chaining (jsig).

(0.38) Add support for -XX:[+|-]HandleSIGUSR2

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java
jcl/src/java.base/share/classes/java/lang/System.java
runtime/jcl/common/system.c

Fixes https://github.com/eclipse-openj9/openj9/issues/16964
I didn't make all the code jdk20+ specific because it looks like there is a backport in https://bugs.openjdk.org/browse/JDK-8290313 so we may be backporting the change to jdk8+ when we get the appropriate OpenJDK levels, after the 2nd quarter releases.

Print warning when java.io.tmpDir does not exist

---

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUDumpPermission.java

Trailing whitespace noted in generated javadoc; see eclipse-openj9/openj9-docs#1082.
Also fix punctuation in a few places.

Minor javadoc fixes

---

jcl/src/java.base/share/classes/java/lang/System.java

OPENJDK_METHODHANDLES is defined for Java 17 and higher (see [jpp_configuration.xml](https://github.com/eclipse-openj9/openj9/blob/master/jcl/jpp_configuration.xml#L134)).

Remove redundant tests of OPENJDK_METHODHANDLES

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/bindnatv.cpp

The changes handle the case of the CaptureCallState (one of the
linker options) introduced in JD20 to save the execution state
after performing the downcall. 
Fixes: #17104

[FFI/JDK20_Jtreg] Handle CaptureCallState in the downcall handle

---

runtime/oti/j9nonbuilder.h
runtime/vm/UpcallVMHelpers.cpp

The changes normalize the arguments less than 32bit in the upcall
dispatcher to ensure the correct value is passed over to the upcall
method and saved upon return.
Fixes: #17128

[FFI/JDK20_Jtreg] Normalize the arguments in the upcall dispatcher

---

runtime/jcl/common/clsldr.cpp

`ClassLoader.defineClassImpl1()` is only accessible to privileged code that is either in the `java.lang` package or that has access to `JavaLangAccess`, so we cannot subject the class name to the normal validation rules, otherwise in jdk21 since
[8304846: Provide a shared utility to dump generated classes defined via Lookup API](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/7dc79c2c1838708db518e4fec8ef40d8a2e629d2)
defining a class like 'java/lang/invoke/BoundMethodHandle$Species_LL' fails
```
java.lang.InternalError
at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:509)
at java.base/java.lang.Access.defineClass(Access.java:347)
at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2512)
at …
```

Never validate class names provided via privileged API for jdk21+

---

runtime/vm/FastJNI_java_lang_System.cpp

Fast_java_lang_System_arraycopy is dead code,
as it is no longer called anywhere

Remove Fast_java_lang_System_arraycopy

---

doc/release-notes/0.38/0.38.md

https://github.com/eclipse-openj9/openj9/issues/17146
Created a draft release notes for 0.38.0 release
[skip ci]

Create draft 0.38.0 release note

---

buildenv/jenkins/variables/defaults.yml

The tag OpenSSL_1_1_1t+CVEs1 is created on the current head of the [OpenSSL_1_1_1-stable](https://github.com/ibmruntimes/openssl/tree/OpenSSL_1_1_1-stable) branch, which includes the following.
CVE-2023-0464 alternative fix
CVE-2023-0465
CVE-2023-0466
See also https://github.com/ibmruntimes/temurin-build/pull/78

Update OpenSSL with additional CVE fixes to 1.1.1t

---

runtime/vm/jnicsup.cpp

DirectByteBuffer accepts long capacity in jdk21+

---

jcl/src/java.base/share/classes/com/ibm/oti/vm/ORBBase.java
jcl/src/java.base/share/classes/com/ibm/oti/vm/ORBVMHelpers.java
jcl/src/java.base/share/classes/java/lang/Class.java
jcl/src/java.base/share/classes/java/lang/ClassLoader.java
jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
jcl/src/java.base/share/classes/java/lang/Object.java
jcl/src/java.base/share/classes/java/lang/System.java
jcl/src/java.base/share/classes/java/lang/invoke/VarHandle.java
jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalUpcallHandler.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/MemoryMXBeanImpl.java
jcl/src/java.management/share/classes/java/lang/management/MemoryMXBean.java
jcl/src/jdk.jcmd/share/classes/openj9/tools/attach/diagnostics/attacher/AttacherDiagnosticsProvider.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassHelperFactory.java
jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassHelperFactoryImpl.java

(Motivated by https://github.com/eclipse-openj9/openj9/pull/17152#discussion_r1163071253).
* remove space after `]`, e.g. in `/*[IF ...] */`
* remove space before `[`, e.g in `/* [MSG ...]*/`

Remove unwanted spaces in preprocessor directives

---

buildenv/jenkins/variables/defaults.yml

The tag OpenSSL_1_1_1t+CVEs1 is created on the current head of the [OpenSSL_1_1_1-stable](https://github.com/ibmruntimes/openssl/tree/OpenSSL_1_1_1-stable) branch, which includes the following.
CVE-2023-0464 alternative fix
CVE-2023-0465
CVE-2023-0466
Cherry pick https://github.com/eclipse-openj9/openj9/pull/17161 for 0.37

(0.37) Update OpenSSL with additional CVE fixes to 1.1.1t

---

buildenv/jenkins/variables/defaults.yml

The tag OpenSSL_1_1_1t+CVEs1 is created on the current head of the [OpenSSL_1_1_1-stable](https://github.com/ibmruntimes/openssl/tree/OpenSSL_1_1_1-stable) branch, which includes the following.
CVE-2023-0464 alternative fix
CVE-2023-0465
CVE-2023-0466
Cherry pick https://github.com/eclipse-openj9/openj9/pull/17161 for 0.38

(0.38) Update OpenSSL with additional CVE fixes to 1.1.1t

---

runtime/vm/BytecodeInterpreter.hpp
runtime/vm/jvminit.c

CRIU doesn't set `J9_EXTENDED_RUNTIME_DEBUG_MODE` by default which was enabled to support `Xtrace` after restore;
Enabled `DO_HOOKS` to include `reportMethodEnter`.
[jdk17-base-f9950fe-0412](https://github.com/JasonFengJ9/openj9/tree/base-f9950fe) - current codebase
[jdk17-enhancebi-0412](https://github.com/JasonFengJ9/openj9/tree/enhancebi) - this PR
[jdk17-criunobi-0412](https://github.com/JasonFengJ9/openj9/tree/criunobi) - Revert `J9_EXTENDED_RUNTIME_DEBUG_MODE` completely
```
Results for ol-instanton-test-pingperf-restore-deployment:jdk17-base-f9950fe-0412
StartupTime	avg= 799	min= 761	max= 856	stdDev=20.7	maxVar=12.5%	confInt=0.54%	samples= 63
Outlier values:  892
Application	avg= 232	min= 209	max= 263	stdDev=12.0	maxVar=25.8%	confInt=1.08%	samples= 63
Outlier values:  335 …
```

CRIU not set J9_EXTENDED_RUNTIME_DEBUG_MODE and enable DO_HOOKS

---

runtime/compiler/control/rossa.cpp

In checkpoint mode we need to downgrade the target processor to allow for portability of not only JIT code but also AOT code. Internally we maintain two separate target processors, `target` for JIT compiled code and `relocatableTarget` for AOT compiled code and SCC validation. In checkpoint mode we downgrade `target` but not `relocatableTarget`, and we do this after validating the SCC.
This patch fixes the problem by downgrading `relocatableTarget` and moving the code to just before SCC validation.
Fixes #17020
Fixes #17082

Fix SCC AOT code validation in checkpoint-mode

---

runtime/vm/BytecodeInterpreter.hpp
runtime/vm/jvminit.c

CRIU doesn't set `J9_EXTENDED_RUNTIME_DEBUG_MODE` by default which was enabled to support `Xtrace` after restore;
Enabled `DO_HOOKS` to include `reportMethodEnter`.
cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/17159

(v0.38.0-release) CRIU not set J9_EXTENDED_RUNTIME_DEBUG_MODE and enable DO_HOOKS

---

doc/release-notes/0.37/0.37.md

Includes changes from
https://github.com/eclipse-openj9/openj9/pull/16784
https://github.com/eclipse-openj9/openj9/pull/16825
https://github.com/eclipse-openj9/openj9/pull/17178
https://github.com/eclipse-openj9/openj9/pull/17179

Copy the 0.37 release notes to the 0.37 branch

---

test/functional/Java19andUp/src/org/openj9/test/jep425/VirtualThreadTests.java
test/functional/Java20andUp/src/org/openj9/test/jep425/VirtualThreadTests.java

The wait time has been increased from 500 ms to 10000 ms. This should
give the virtual thread sufficient time to park on slower machines.
Fixes: #16722

Increase wait time in test_YieldedVirtualThreadGetStackTrace

---

doc/compiler/runtime/JITHooks.md

Update this document with other hooks of interest to the JIT, as well as a note on the importance of the `J9HookDisable` API used to test whether a hook is enabled (based on the discussion in https://github.com/eclipse-openj9/openj9/pull/16960).

Update JIT Hooks Document

---

runtime/gc/gctable.c
runtime/gc_base/gc_internal.h
runtime/gc_base/modronapi.cpp
runtime/gc_modron_startup/mminit.cpp
runtime/gc_realtime/Scheduler.hpp
runtime/oti/j9nonbuilder.h

Update GC CRIU checkpoint and restore routines based on refactoring done in upstream OMR: https://github.com/eclipse/omr/pull/6947.
- Replace configuration reinitializeGCThreadCountForRestore and adjustGCThreadCountForCheckpoint calls with single reinitializeForRestore call.
- Invoke the dispatcher directly to expand/contract thread pool
- Update the GC thread count in j9gc_reinitializeDefaults 
Depends on https://github.com/eclipse/omr/pull/6947

Refactor GC CRIU Routines

---

runtime/compiler/env/VMJ9.cpp

Check option `disableRecognizeCurrentThread` and environment variable `TR_DisableRecognizeCurrentThread` on whether or not to inline `Thread.currentThread`. 
Depends on

Check options on whether or not to inline Thread.currentThread

---

test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_ThreadGroup.java

Issue https://github.com/eclipse-openj9/openj9/issues/16920
See in particular https://github.com/eclipse-openj9/openj9/issues/16920#issuecomment-1469014460
There are other failures, but I don't know when I'll have a chance to work on them.
Fixes https://github.com/eclipse-openj9/openj9/issues/16779

Avoid hang in Test_ThreadGroup.test_remove() on jdk21

---

runtime/include/jni.h.m4
runtime/j9vm/j7vmi.c
runtime/j9vm/jvm.c
runtime/redirector/redirector.c
runtime/vm/jnimisc.cpp
runtime/vm/jvminitcommon.c

Added upstream in
* [8304919: Implementation of Virtual Threads](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/1edf1e6ea5b6bcb6a9f2df18d6c98eb4e0a86865)

Support JNI_VERSION_21 for jdk21+

---

runtime/vm/gphandle.c

When handling SIGBUS, or ABEND on z/OS, the stack walk from sigBusHandler() ignores the Unsafe class when looking for a java/nio caller class. From Java 17, Unsafe options are wrapped with ScopedMemoryAccess, which also needs to be ignored.
Internal issue runtimes/openj9-openjdk-jdk17-zos/issues/514
On z/OS, the following test case demonstrates the problem
```
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.ByteBuffer;
import java.nio.MappedByteBuffer;
import java.nio.channels.FileChannel;
public class TruncateTest {
static final long INITIAL_FILE_SIZE = 32000L;
static final long TRUNCATED_FILE_SIZE = 512L;
public static void main(String [] args) throws IOException, InterruptedException {
File blah = File.createTempFile("blah", null); …
```

Ignore ScopedMemoryAccess in isCallerClassJavaNio()

---

doc/release-notes/0.38/0.38.md

Closes https://github.com/eclipse-openj9/openj9/issues/16788
Updated the document with support for running OpenJDK 8 and OpenJDK 11 on CentOS 6.10 is deprecated
[skip ci]

Update 0.38.0 release note

---

runtime/compiler/x/runtime/X86Codert.nasm

x86: Preserve xmm4 in fpRem helper

---

runtime/vm/jvminit.c

Items will be added to cp, when remaped to -agentlib:instrument
Fixes https://github.com/eclipse-openj9/openj9/issues/13874

Stop adding -javaagent to classpath

---

runtime/gc_realtime/Scheduler.cpp
runtime/gc_realtime/Scheduler.hpp

Intermediate changes required to  commit upstream OMR changes to base class MM_ParallelDispatcher.
see https://github.com/eclipse/omr/pull/6954

Prepare MM_Scheduler for OMR Base Class Changes

---

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
runtime/oti/vm_api.h
runtime/oti/vmconstantpool.xml
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/ContinuationHelpers.cpp
runtime/vm/bindnatv.cpp

Currently there two independent flags started and finished in Continuation Object, the similar bitwise flags also in continuation.state, merge started and finished flags into continuation.state.

Merge started and finished flags into continuation.state

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

Each intermediate result in a `LambdaForm` is stored in an auto. Given the final static field load at the beginning of a customized `LambdaForm`, method handle transformer is able to determine a known object for the result of loading final fields from the `MethodHandle`, and it can e.g. refine an `invokeBasic()` call using one into a direct call. It can't add the known object index to the auto that represents the receiver of such a call, since generally an auto can't have a known object index, but it does set the known object index directly on the node.
Until now the only way that inliner has been able to find a known object index for an argument (other than `<javaLangClassFromClass>` of `loadaddr`) has been from the symref, so it would fail to see that the argument is a known object, …

Fix inlining when the root method is a customized LambdaForm

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

If this type info is missing, `validateAndPropagateArgsFromCalleeSymbol()` can give up, in which case we can fail to inline even trivial methods due to what appears to be a type incompatibility.
In particular, this would cause the actual array access to fail to be inlined for array getter (and probably also setter) MethodHandles.

Create prex arg info from callee symbol for array-typed parameters

---

runtime/j9vm/java11vmi.c
runtime/util/module.tdf

JDK21 sets `bootclassloader.unnamedModule` after `java.base` module creation
`JVM_SetBootLoaderUnnamedModule()` saves the `unnamedModule` to `J9JavaVM->unamedModuleForSystemLoader->moduleObject` since `bootclassloader` hasn't finished the initialization yet;
`bootclassloader.unnamedModule` is set after `java.base` module creation within `JVM_DefineModule()`.
The Java stacktrace
```
4XESTACKTRACE                at jdk/internal/loader/BootLoader.setBootLoaderUnnamedModule0(Native Method) <-- systemClassLoader->classLoaderObject is null
4XESTACKTRACE                at jdk/internal/loader/BootLoader.<clinit>(BootLoader.java:68)
4XESTACKTRACE                at sun/nio/fs/UnixNativeDispatcher.<clinit>(UnixNativeDispatcher.java:816)
4XESTACKTRACE                at …
```

JDK21 sets bootclassloader.unnamedModule after java.base module creation

---

runtime/j9vm/exports.cmake
runtime/j9vm/j7vmi.c
runtime/j9vm/j9vmnatives.xml
runtime/redirector/forwarders.m4

These functions are no longer required by Java 21:
* JVM_IsThreadAlive
* JVM_VirtualThreadMountBegin
* JVM_VirtualThreadMountEnd
* JVM_VirtualThreadUnmountBegin
* JVM_VirtualThreadUnmountEnd
See https://github.com/eclipse-openj9/openj9/pull/16985#discussion_r1146431459

Stop exporting functions not needed for Java 21

---

runtime/vm/BytecodeInterpreter.hpp

jitStackFrameFlags is reset as soon as it is read to prevent issues.
Related: #16741

Reset jitStackFrameFlags ASAP in OJDK MH INLs

---

runtime/j9vm/javanextvmi.cpp
runtime/vm/ContinuationHelpers.cpp

Continuation cleanup have been moved to the last yield location to support future optimization on skipping JVMTI operation.
Depends on https://github.com/eclipse-openj9/openj9/issues/17058

Move freeContinuation to yieldContinuation

---

runtime/j9vm/jvm.c
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/sunvmi/sunvmi.c
runtime/vm/jvminit.c

Fixes https://github.com/eclipse-openj9/openj9/issues/17198
Tested in an [internal build](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=49893) and also manually tested it fixes the immediate problem of loading j9thr from the wrong location. This [extended test](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=58492775) should start passing with this change.

Don't reload j9thr from the wrong location

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
runtime/vm/UpcallVMHelpers.cpp

[FFI/JDK20_Jtreg] Fix the issue with the arguments/return value
The changes resolve the issue with the pointer for the
passed-in arguments in upcall and the return value in
downcall by wrapping them up as an unbounded memory
segment to pass the boundary check as specified in JDK20.
Fixes: #17078

[FFI/JDK20_Jtreg] Fix the issue with the arguments/return value

---

test/functional/RasapiTest/build.xml

We don't see failures in PR testing because this test is currently disabled. However, trying to build locally it fails for jdk21 because `javac` no longer supports 1.7:
```
[javac] error: Source option 7 is no longer supported. Use 8 or later.
[javac] error: Target option 7 is no longer supported. Use 8 or later.
```

Update source/target versions to 8

---

test/TestConfig/resources/excludes/latest_exclude_21.txt

Fixes https://github.com/eclipse-openj9/openj9/issues/16920
Turns out https://github.com/eclipse-openj9/openj9/pull/17216 was unnecessary but it seems a worthwhile change for the next time we forget to copy the excludes for the latest version.

Copy functional test excludes for 21 from 20

---

runtime/makelib/targets.mk.ftl
runtime/makelib/targets.mk.linux.inc.ftl
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/CMakeLists.txt
runtime/vm/CRIUBytecodeInterpreterCompressed.cpp
runtime/vm/CRIUBytecodeInterpreterFull.cpp
runtime/vm/jvminit.c

`CRIU` `BytecodeInterpreter` enables `DO_HOOKS`
`criuBytecodeLoopCompressed`/`criuBytecodeLoopFull` are used when `CRIU` is enabled.

CRIU BytecodeInterpreter enables DO_HOOKS

---

runtime/makelib/targets.mk.ftl
runtime/makelib/targets.mk.linux.inc.ftl
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/CMakeLists.txt
runtime/vm/CRIUBytecodeInterpreterCompressed.cpp
runtime/vm/CRIUBytecodeInterpreterFull.cpp
runtime/vm/jvminit.c

`CRIU` `BytecodeInterpreter` enables `DO_HOOKS`
`criuBytecodeLoopCompressed`/`criuBytecodeLoopFull` are used when `CRIU` is enabled.
cherry-pick 
* https://github.com/eclipse-openj9/openj9/pull/17245

(v0.38.0-release) CRIU BytecodeInterpreter enables DO_HOOKS

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp

This commit changes code generation for method prologue and epilogue to use the register pair instructions (stp and ldp) for saving and restoring preserved registers when applicable.

AArch64: Use stp/ldp instructions for preserved registers

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit removes a TODO comment in TreeEvaluatorTable initialization. ArrayCopyBNDCHK evaluator for AArch64 is implemented in the OMR project.

AArch64: Remove a TODO comment for ArrayCopyBNDCHK

---

runtime/compiler/net/CommunicationStream.hpp

...to prevent git from dropping increments on merge/rebase. Personally I've had an increment lost from my local commits on rebase, but worse is the possibility that one could be lost when merging a PR after review.

Add unique ID comment to CommunicationStream::MINOR_NUMBER

---

runtime/compiler/env/J9ClassEnv.cpp

Previously it would try to dereference the class on the server.

Make J9::ClassEnv::getArrayElementWidthInBytes() work in JITServer

---

runtime/vm/CRIUBytecodeInterpreterCompressed.cpp
runtime/vm/CRIUBytecodeInterpreterFull.cpp

`CRIU` `BytecodeInterpreter` requires `J9VM_OPT_CRIU_SUPPORT`
`CRIUBytecodeInterpreterCompressed.cpp` and `CRIUBytecodeInterpreterFull.cpp` are only compiled if `J9VM_OPT_CRIU_SUPPORT` is defined.
This fixes the compilation error of internal Java 8 UMA `AIX/LinuxPPC` platforms.
[J9 Java [AIX64 Compressed Pointers] 80 Compile](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=58838390)
```
1586-491 (?) COMPILER LIMIT EXCEEDED: Insufficient virtual storage.
```
[J9 Java [Linux PPC] 80 Compile](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=58841519)
```
"../include/ffi.h", line 186.27: 1540-0840 (W) The integer literal "9223372036854775807" is out of range.
"../include/ffi.h", line 187.3: 1540-0859 (S) #error directive: "no 64-bit data type supported".
make[2]: *** …
```

CRIU BytecodeInterpreter requires J9VM_OPT_CRIU_SUPPORT

---

doc/compiler/control/OptionsPostRestore.md
runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/OptionsPostRestore.cpp
test/functional/cmdLineTests/criu/build.xml
test/functional/cmdLineTests/criu/criuJitServerScript.sh
test/functional/cmdLineTests/criu/criu_jitserverAcrossCheckpoint.xml
test/functional/cmdLineTests/criu/criu_jitserverPostRestore.xml
test/functional/cmdLineTests/criu/playlist.xml
test/functional/cmdLineTests/jitserver/build.xml
test/functional/cmdLineTests/jitserver/jitserverArgumentTesting.xml
test/functional/cmdLineTests/jitserver/jitserverScript.sh
test/functional/cmdLineTests/jitserver/jitserverconfig.sh
test/functional/cmdLineTests/jitserver/playlist.xml

This PR updates the how a JVM Client will connect to a JITServer in the context of CRIU as outlined in the following table; ✅ means the JVM will connect to a JITServer instance and ❌ means it won't.
||Non-Portable CRIU Pre-Checkpoint|Non-Portable CRIU Post-Restore|Portable CRIU Pre-Checkpoint|Portable CRIU Post-Restore|
|--|--|--|--|--|
|No Options Pre-Checkpoint; No Options Post-Restore|:x:|:x:|:x:|:x:|
|No Options Pre-checkpoint; `-XX:+UseJITServer` Post-Restore|:x:|:white_check_mark:|:x:|:white_check_mark:|
|`-XX:+UseJITServer` Pre-Checkpoint; No Options Post-Restore|:x:|:white_check_mark:|:white_check_mark:|:white_check_mark:|
|`-XX:+UseJITServer` Pre-Checkpoint; `-XX:-UseJITServer` Post-Restore|:x:|:x:|:white_check_mark:|:x:|
|`-XX:-UseJITServer` Pre-Checkpoint; `-XX:+UseJITServer` …

Enable JITServer post-restore only if explicitly specified

---

test/functional/Java20andUp/playlist.xml
test/functional/Java21andUp/playlist.xml

The changes remove Hotspot in the playlist script
as these tests are only intended for OpenJ9.
Fixes: #17288

[FFI/Test] Remove Hotspot in playlist.xml

---

runtime/gc_realtime/Scheduler.cpp
runtime/gc_realtime/Scheduler.hpp

- General formatting clean up for Scheduler
- Follow up to https://github.com/eclipse-openj9/openj9/pull/17229: revert intermediate changes (run method) and move recomputeActiveThreadCountForTask to prepareThreadsForTask

GC Scheduler Cleanup

---

runtime/jcl/common/reflecthelp.c

Preserve array for permitted subtype accross alloc
Preserve the string array for permitted subtypes across array element allocations.
Related to: https://github.com/eclipse-openj9/openj9/issues/17254

Preserve array for permitted subtype accross alloc

---

runtime/jvmti/jvmtiExtensionMechanism.c

While enabling serviceability VThreadTest, new behaviour was noticed
for jvmtiGetCarrierThread:
- It allows a NULL virtual thread and does not throw an error.
- For a NULL virtual thread, the current J9VMThread is inspected for
deriving the carrier thread if a virtual thread is mounted.
Related: #16168

[JDK20] Update jvmtiGetCarrierThread

---

runtime/jvmti/jvmtiStackFrame.c

`haltThreadForInspection` can release VM access. So, `threadObject` should
be set after `haltThreadForInspection` to stop the GC from relocating it.
Related: #16688

Fix jvmtiGetStackTrace

---

runtime/vm/vmhook.c

Use of the `can_generate_sampled_object_alloc_events` JVMTI capability must disable safe point OSR because the event would be sent when not at an OSR safe point, leading to assertions or hangs.
Fixes: #16480

Disable safe point OSR if sampled object allocate hook is used

---

runtime/j9vm/javanextvmi.cpp
runtime/jcl/common/jclcinit.c
runtime/jcl/common/thread.cpp
runtime/jvmti/jvmtiHelpers.c
runtime/jvmti/jvmtiThread.c
runtime/jvmti/suspendhelper.cpp
runtime/oti/j9nonbuilder.h

JVMTI treats a virtual thread and its carrier thread as two separate threads.
If JVMTI suspends a virtual thread, then its carrier thread
should not be suspended and vice-versa. Similarly, if JVMTI resumes
a virtual thread, then its carrier thread should not be resumed and
vice-versa.
In OpenJ9, currently, a mounted virtual thread and its carrier thread
shared the same J9VMThread. The thread state is derived from the
J9VMThread. Due to the sharing of the J9VMThread in the mounted
state, if a mounted virtual thread is suspended, then the JVMTI
functions will also reflect that its carrier thread is suspended.
Currently, "isSuspendedByJVMTI" is the hidden field that holds
the suspend status for the virtual thread only, now it made
available for carrier thread too, i.e., the scope has changed …

Fix to handle suspend/resume of virtual/carrier threads

---

runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp
runtime/nls/j9gc/j9modron.nls

Balanced GC policy will throw an "Assert_MM_unimplemented" " assertion when using the option "Xgc:hierarchicalScanOrdering" with "Xgcpolicy:balanced". Instead, output a warning message rather than asserting due to the unsupported option.
Fixes: https://github.com/eclipse-openj9/openj9/issues/17016

Add Unsupported Warning for Hierarchical Scan Ordering with Balanced

---

runtime/compiler/z/codegen/J9CodeGenerator.cpp

When balanced GC policy is in effect, array lets can be generated. The codegen optimization where we inline StringLatin1.inflate is not compatible in such a scenario. Therefore, this PR disables that optimization when arraylets can be generated.

Don't inline StringLatin1.inflate when array lets can be generated

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp

The `invokeinterface` bytecode instruction can call methods of `Object`, including those declared final, which the VM leaves out of vtables in order to save space. Those methods must therefore be special-cased and dispatched directly.
Historically PicBuilder had no support for this special-case direct dispatch, and so it was not possible for the JIT compiler to generate code for an unresolved `invokeinterface` instruction if its constant pool entry could later resolve to a final method of `Object`. To prevent that situation, the compiler took advantage of the fact that `Object`'s final methods are known in advance, and it's possible to predict precisely whether resolution will find one just by looking at the name and signature of the callee. So whenever the name and signature matched …

Stop failing compilations due to final Object invokeinterface

---

jcl/jpp_configuration.xml

Remove `JAVA19` `pConfig` & `JAVA21` uses `rt-compressed.sunJava21.jar`

Remove JAVA19 pConfig & JAVA21 uses rt-compressed.sunJava21.jar

---

runtime/jcl/common/getstacktrace.c
runtime/jcl/common/thread.cpp

This removes JCL's dependency on `VirtualThread.notifyJvmti*` functions.

Refactor getStackTraceImpl to remove use of VThreadInspector

---

buildenv/jenkins/variables/defaults.yml

No builds are available from Adoptium for these platforms.

Use a recent OMR acceptance build as bootjdk for AIX and for s390x Linux

---

test/functional/cmdLineTests/criu/criuJitServerScript.sh
test/functional/cmdLineTests/criu/criu_jitserverAcrossCheckpoint.xml
test/functional/cmdLineTests/criu/criu_jitserverPostRestore.xml
test/functional/cmdLineTests/criu/playlist.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java
test/functional/cmdLineTests/jitserver/jitserverArgumentTesting.xml
test/functional/cmdLineTests/jitserver/jitserverScript.sh

In this PR 
* The jitserver tests are a bit more verbose to help with failures
* A sleep to is added to `jitOptionsTest` to ensure that the JVM has time to produce the output needed for a success condition
* The `Test Metrics Disabled` test is removed as it is not all that useful
Fixes https://github.com/eclipse-openj9/openj9/issues/17311
Fixes https://github.com/eclipse-openj9/openj9/issues/17324
Fixes https://github.com/eclipse-openj9/openj9/issues/17333

Make JITServer CRIU tests more robust

---

runtime/compiler/compile/J9AliasBuilder.cpp
runtime/compiler/compile/J9SymbolReferenceTable.cpp

For JDK19 and up, `CurrentThread` could be modified by any method calls. Set `CurrentThread` sym ref in `defaultMethodDefAliases`. 
Also removed `setVolatile` on `CurrentThread` symbol which is not needed.

Set CurrentThread sym ref in defaultMethodDefAliases

---

jcl/src/java.base/share/classes/java/lang/Access.java

Reverts eclipse-openj9/openj9#17341

Revert "Restore @Override annotation for Access.getLoaderNameID()"

---

runtime/vm/UpcallVMHelpers.cpp

The fields are of type `long`; no need to truncate to `U_32`.

Correct types for min, length in memory segment objects

---

runtime/vm/jvminit.c

Noticed while reviewing #17306: Lines 1363 and 3540 should use the same condition.

Correct condition for preparing offloading library

---

doc/build-instructions/Build_Instructions_V8.md

freetype is automatically included in jdk8 builds since https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/631
Obsoletes https://github.com/eclipse-openj9/openj9/pull/17329

Remove obsolete references to freetype in jdk8 build instructions

---

runtime/jcl/common/sun_misc_Perf.c

Rather than asserting they are unimplemented.
Fixes https://github.com/eclipse-openj9/openj9/issues/17366

Throw UnsupportedOperationException in sun.misc.Perf.attach natives

---

debugtools/DDR_VM/src/com/ibm/j9ddr/CompatibilityConstants29.dat

It was needlessly added in #15404. Also restore order.

Remove unnecessary compatibility constant J9DescriptionCpTypeShift

---

runtime/j9vm/jvm.c

JVM_LoadLibrary() is used to load JNI libraries from jdk17.
Fixes https://github.com/eclipse-openj9/openj9/issues/17285
The library being loaded needs to exist to get the better message. With this change you get an error message to explain why the load failed.
`Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to load library ("/home/pete/openj9-openjdk-jdk17/build/linux-x86_64-server-release/images/jdk/lib/libabc.so") /home/pete/openj9-openjdk-jdk17/build/linux-x86_64-server-release/images/jdk/lib/libabc.so: file too short
`
`Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to load library ("/home/pete/openj9-openjdk-jdk17/build/linux-x86_64-server-release/images/jdk/lib/libabc.so") /home/pete/openj9-openjdk-jdk17/build/linux-x86_64-server-release/images/j …

Provide a better error message for failed library loads on jdk17+

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/stackmap/StackMap.java

- Merge handling of static/non-static calls
- Fix bug parsing array arguments
- Simply control flow
Fixes https://github.com/eclipse-openj9/openj9/issues/16804

DDR: Fix function call parsing in StackMap

---

runtime/gc_base/GCExtensions.cpp
runtime/jcl/common/stdinit.c
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/ContinuationHelpers.cpp
runtime/vm/intfunc.c
runtime/vm/jvmfree.c
runtime/vm/jvminit.c

- Single per thread local cache to reduce need of alloc/free
- Add globalContinuationCacheArray for second tier caching

Prototype Continuation caching

---

runtime/vm/jniinv.c
runtime/vm/jvminit.c

JVM init path: J9_CreateJavaVM.
JVM exit paths: protectedDestroyJavaVM and exitJavaVM.
A segfault can happen if JVM init and exit paths execute concurrently.
This can happen if a shutdown signal is raised and the shutdown handler
is invoked. JVM shutdown signals are SIGINT, SIGTERM and SIGHUP.
The JVM exit paths wait or spin until the JVM has successfully initialized.
This should prevent clean up (freeing of memory) until the JVM has
successfully initialized, and resolve the associated segfaults.
Internal issue: 148771

Sync JVM init and exit paths

---

runtime/j9vm/exports.cmake
runtime/j9vm/j7vmi.c
runtime/j9vm/j9scar.tdf
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/jvm.c
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/redirector/forwarders.m4
runtime/vm/intfunc.c
runtime/vm/vmbootlib.c

- JVM_LoadLibrary / JVM_OnloadLibrary needs to invoke j9sl_open_shared_library and j9sl_close_shared_library respectively to handle potential 31-bit targets.
- OMRPORT_SLOPEN_ATTEMPT_31BIT_OPEN needs to be specified if -XX:+Enable3164Interoperability is specified.
- JVM_FindLibraryEntry needs to invoke j9sl_lookup_name to handle function lookups of 31-bit target.
- Add utility function used by NativeLibraries to invoke JNI_OnLoad or JNI_OnUnload functions in 31-bit native interoperability targets. This requires mapping to the corresponding 31-bit JavaVM object handle, along with invoking CEL4RO31 (via ffi) to the corresponding target function.

Add 31-64 interop support for JVM_ funcs for JDK17+

---

runtime/compiler/build/files/common.mk
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/J9Recompilation.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/ilgen/IlGenerator.cpp
runtime/compiler/optimizer/CMakeLists.txt
runtime/compiler/optimizer/CatchBlockProfiler.cpp
runtime/compiler/optimizer/CatchBlockProfiler.hpp
runtime/compiler/optimizer/EstimateCodeSize.cpp
runtime/compiler/optimizer/EstimateCodeSize.hpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9EstimateCodeSize.cpp
runtime/compiler/optimizer/J9Optimizer.cpp
runtime/compiler/runtime/J9Profiler.cpp
runtime/compiler/runtime/J9Profiler.hpp

This optimization inserts a counter in the basic blocks that catch exceptions. The counter is stored in the `TR_PersistentMethodInfo` struct attached to the method being compiled.
The value of this counter is queried by the inliner, and if its value exceeds a threshold (`TR::Options::_catchBlockCounterThreshold`), the JIT inlines more aggressively on the `throw` path in order to facilitate the replacement of the `throw` instruction with a `goto` instruction. This mechanism is refered to as Exception Directed Optimization (EDO) in the literature.
This commit is intended to replace the old EDO mechanism, which used a special profiling compilation for measuring catch block frequency. With the current approach, every method will measure catch block frequency (if catch blocks exist), so an …

Add new optimization catchBlockProfiler

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
jcl/src/java.base/share/classes/openj9/internal/foreign/abi/UpcallMHMetaData.java
runtime/tests/clinkerffi/CMakeLists.txt
runtime/tests/clinkerffi/downcall.c
runtime/tests/clinkerffi/module.xml
runtime/tests/clinkerffi/upcall.c
test/functional/Java17andUp/src_170/org/openj9/test/jep389/downcall/InvalidDownCallTests.java
test/functional/Java17andUp/src_170/org/openj9/test/jep389/upcall/InvalidUpCallTests.java
test/functional/Java20andUp/src/org/openj9/test/jep434/downcall/InvalidDownCallTests.java
test/functional/Java20andUp/src/org/openj9/test/jep434/upcall/InvalidUpCallTests.java
test/functional/Java21andUp/src/org/openj9/test/jep442/downcall/InvalidDownCallTests.java
test/functional/Java21andUp/src/org/openj9/test/jep442/upcall/InvalidUpCallTests.java

The changes remove the check on MemoryAddress.NULL(JDK17)
MemorySegment.NULL(JDK20) for the pointer argument/return
value as this type of segment/address is acceptable in the
native function, depending upon how the segment/address
is used.
Fixes: #17400

[Jtreg/FFI] Remove the null segment check for pointer

---

runtime/vm/jniinv.c
runtime/vm/jvminit.c

JVM init path: J9_CreateJavaVM.
JVM exit paths: protectedDestroyJavaVM and exitJavaVM.
A segfault can happen if JVM init and exit paths execute concurrently. This can happen if a shutdown signal is raised and the shutdown handler is invoked. JVM shutdown signals are SIGINT, SIGTERM and SIGHUP.
The JVM exit paths wait or spin until the JVM has successfully initialized.
This should prevent clean up (freeing of memory) until the JVM has successfully initialized, and resolve the associated segfaults.
Internal issue: 148771
Backport of https://github.com/eclipse-openj9/openj9/pull/17101

(0.39) Sync JVM init and exit paths

---

runtime/j9vm/javanextvmi.cpp
runtime/jcl/common/jclcinit.c
runtime/jcl/common/thread.cpp
runtime/jvmti/jvmtiHelpers.c
runtime/jvmti/jvmtiThread.c
runtime/jvmti/suspendhelper.cpp
runtime/oti/j9nonbuilder.h

JVMTI treats a virtual thread and its carrier thread as two separate threads. If JVMTI suspends a virtual thread, then its carrier thread should not be suspended and vice-versa. Similarly, if JVMTI resumes a virtual thread, then its carrier thread should not be resumed and vice-versa.
In OpenJ9, currently, a mounted virtual thread and its carrier thread shared the same J9VMThread. The thread state is derived from the J9VMThread. Due to the sharing of the J9VMThread in the mounted state,if a mounted virtual thread is suspended, then the JVMTI functions will also reflect that its carrier thread is suspended.
Currently, "isSuspendedByJVMTI" is the hidden field that holds the suspend status for the virtual thread only, now it made available for carrier thread too, i.e. the scope has changed …

(0.39) Fix to handle suspend/resume of virtual/carrier threads

---

runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/ValueTypeHelpers.cpp
runtime/vm/intfunc.c

https://github.com/eclipse-openj9/openj9/pull/17394 has added new flag 
`J9VM_OPT_VALHALLA_FLATTENABLE_VALUE_TYPES` for flattenable value types. 
The value object code is under the existing `J9VM_OPT_VALHALLA_VALUE_TYPES`. 
Add new API `areFlattenableValueTypesEnabled()` for JIT.
issue #17235

Add areFlattenableValueTypesEnabled() for JIT

---

runtime/vm/BytecodeInterpreter.hpp
runtime/vm/ValueTypeHelpers.hpp

- Create VM_ValueTypeHelpers::copyFlattenableArray
function and call it instead of
VM_ArrayCopyHelpers::referenceArrayCopy when
copying flattened or primitive arrays
- Throw a NPE instead of an ASE in
doReferenceArrayCopy when an attempt is made to
copy a null object into an array of primitive
value types
for #13182

Correctly handle primitive VTs in System.arraycopy

---

runtime/vm/ValueTypeHelpers.hpp

See https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_linux_OpenJDK8/59/:
```
In file included from /home/jenkins/workspace/Build_JDK8_x86-64_linux_OpenJDK8/openj9/runtime/vm/ValueTypeHelpers.cpp:23:0:
23:24:52  /home/jenkins/workspace/Build_JDK8_x86-64_linux_OpenJDK8/openj9/runtime/vm/ValueTypeHelpers.hpp: In static member function 'static I_32 VM_ValueTypeHelpers::copyFlattenableArray(J9VMThread*, MM_ObjectAccessBarrierAPI, MM_ObjectAllocationAPI, j9object_t, j9object_t, I_32, I_32, I_32)':
23:24:52  /home/jenkins/workspace/Build_JDK8_x86-64_linux_OpenJDK8/openj9/runtime/vm/ValueTypeHelpers.hpp:596:12: error: unused variable 'destComponentClass' [-Werror=unused-variable]
23:24:52     J9Class *destComponentClass = ((J9ArrayClass *)destClazz)->componentType;
23:24:52 …
```

Fix compile error due to unused variable

---

runtime/compiler/control/HookedByTheJit.cpp

`J9::Options::_compilationDelayTime` is expressed in seconds, but in some parts of the code is used as if expressed in milliseconds.
Fixes: #17431

Fix bug related to J9::Options::_compilationDelayTime unit

---

runtime/vm/jniinv.c
runtime/vm/jvminit.c

Reverts eclipse-openj9/openj9#17101.
See https://github.com/eclipse-openj9/openj9/issues/17426#issuecomment-1554619587 for the reason to revert.

Revert "Sync JVM init and exit paths"

---

runtime/vm/jniinv.c
runtime/vm/jvminit.c

Reverts eclipse-openj9/openj9#17417.
See https://github.com/eclipse-openj9/openj9/issues/17426#issuecomment-1554619587 for the reason to revert.

Revert "(0.39) Sync JVM init and exit paths"

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

callMustBeInlinedRegardlessOfSize is never overriden from its base implementation and therefore always
returns false. This commit removes 2 existing callsites of callMustBeInlinedRegardlessOfSize.
This commit is apart of eclipse/omr#6148 effort to deprecate callMustBeInlinedRegardlessofSize

Simplify callMustBeInlinedRegardlessOfSize calls

---

runtime/compiler/runtime/RelocationRuntime.cpp
runtime/compiler/runtime/RelocationRuntime.hpp
runtime/nls/jitm/j9jit.nls

The PR adds a new feature flag to ensure that there isn't a CH Table Opts mismatch. Specifically, if CH Table opts were enabled in the compile run, then it also needs to be enabled in the load run.
Very likely the cause of https://github.com/eclipse-openj9/openj9/issues/17250.

Add CH Table AOT Feature Flag

---

jcl/src/java.base/share/classes/module-info.java.extra
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java

CRIU restore clears `InetAddress.cache`
A post-restore hook `clearInetAddressCache()` is added to clear `InetAddress.cache`.
This change prevents JVM DNS cache before checkpoint which might cause DNS resolution timeout after the CRIU image is restored at a different environment.
Related
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/604

CRIU restore clears InetAddress.cache

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/control/rossa.cpp
runtime/nls/jitm/j9jit.nls

The fix proposes to handle code cache allocation in environments with low physical memory.
For this we need to check the available physical memory first during the initialization when code cache related values are configured and then another time when the actual allocation happens.
The method `TR::CompilationInfo::computeFreePhysicalMemory(bool &incompleteInfo)` can be reused for this purpose.
1. Provide a user option to set `codetotalPercentage=` which will be percentage of available memory to be used for code cache if the available free memory is less than 512MB. The percentage defaults is set to 50% so that we leave enough for the JVM.
2. In `OMR::CodeCacheManager::carveCodeCacheSpaceFromRepository(size_t segmentSize `calculate available physical memory and perform new code cache …

Handle code cache alloction for low memory

---

runtime/compiler/p/codegen/PPCJNILinkage.cpp
runtime/compiler/runtime/Runtime.cpp

This issue was caused as one of the special crc32 routine was not AOT-enabled. Adding code to enable AOT for all related methods.
Closes: https://github.com/eclipse-openj9/openj9/issues/17444

Adding helper functions for crc32 special routines to enable optimizations in AOT

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp

This is mostly important for fabricated field shadows, but since it's there we might as well set it on the regular field shadows as well.

Set symbol declared class for field shadows

---

runtime/vm/vmprops.c

Java 8:
* changed upstream in jdk8u382-b02
* [8303028: Update system property for Java SE specification maintenance version](https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/d18bd3f730c88281f30852ba49c6074b512cafee)
Java 11:
* [8285497: Add system property for Java SE specification maintenance version](https://github.com/ibmruntimes/openj9-openjdk-jdk11/commit/530f958c7b5947fad3f7e2d6192fee2d235bdd14)

Add/update java.specification.maintenance.version

---

runtime/j9vm/java11vmi.c

Otherwise an error is produced by -Xcheck:jni, which can be triggered by compiling/running on jdk11+ via `java Source.java`.
<JNI GetStaticMethodID: com/sun/tools/javac/launcher/Main.main ([Ljava/lang/String;)V>
JVMJNCK044E JNI error in CallObjectMethod/CallObjectMethodV: Method is static
JVMJNCK077E Error detected in
jdk/internal/misc/VM.getRuntimeArguments()[Ljava/lang/String;

Call static method VM.getVMArgs() from JNI as a static method

---

runtime/gc_base/ContinuationObjectList.cpp
runtime/gc_base/ContinuationObjectList.hpp
runtime/gc_base/OwnableSynchronizerObjectList.cpp
runtime/gc_base/OwnableSynchronizerObjectList.hpp
runtime/gc_base/ReferenceObjectList.cpp
runtime/gc_base/ReferenceObjectList.hpp
runtime/gc_base/UnfinalizedObjectList.cpp
runtime/gc_base/UnfinalizedObjectList.hpp
runtime/gc_glue_java/ConfigurationDelegate.hpp
runtime/gc_glue_java/HeapRegionDescriptorStandardExtension.hpp

Move allocation and init of object lists from high level Config Delegate to the each individual list class.

Rework RegionExtenstion/Object List Initialization 

---

test/functional/cmdLineTests/criu/src/org/openj9/criu/TestResult.java

Correct SPDX license identifiers
Related https://github.com/eclipse-openj9/openj9/pull/17473#discussion_r1212069111

Correct SPDX license identifiers

---

runtime/gc_base/ContinuationObjectList.cpp
runtime/gc_base/OwnableSynchronizerObjectList.cpp
runtime/gc_base/ReferenceObjectList.cpp
runtime/gc_base/UnfinalizedObjectList.cpp

`new[]()` not supported on older compilers. Instead, just calling
`new()` in a loop for every element of the array.

Fix array constructor for Object Lists

---

runtime/compiler/compile/J9Compilation.hpp
runtime/compiler/ilgen/IlGenerator.cpp
runtime/compiler/optimizer/J9EstimateCodeSize.cpp

A user experienced a compile time crash in setHandlerInfoWithOutBCInfo() because a bytecode index to a catch handler is above the 2^16th limit that normally applies for Java methods. This limit can be exceeded in rare cases after the JVM expands the method size on load. A good example of this would be when the VM inlines a "jsr" bytecode. Because the handler index is larger then 2^16th the offset is truncated when it is placed into the 16bit integer that we were using to record the offset. This fix will expand the size of variables used to hold bytecode offsets to be 32bits. This change also prevents a negative array index in genExceptionHandlers() when a try region starts at bytecode index 0.

Expand bytecode offset variables to 32bit

---

doc/compiler/aot/RelocationRecords.md
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/codegen/J9CodeGenerator.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/optimizer/CatchBlockProfiler.cpp
runtime/compiler/p/codegen/ForceRecompilationSnippet.cpp
runtime/compiler/p/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/p/runtime/PPCRelocationTarget.cpp
runtime/compiler/runtime/RelocationRecord.cpp
runtime/compiler/runtime/RelocationRecord.hpp
runtime/compiler/runtime/RelocationRuntime.hpp
runtime/compiler/runtime/Runtime.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp

These patches implement the `TR_CatchBlockCounter` and `TR_StartPC` relocations, so that EDO can be enabled during AOT compilations. See https://github.com/eclipse/omr/pull/6956 for the associated `omr` PR.
This PR depends on https://github.com/eclipse-openj9/openj9/pull/16854 and https://github.com/eclipse/omr/pull/6956. Note that these changes include a new file `runtime/compiler/optimizer/CatchBlockProfiler.cpp`. That file is identical to the one in https://github.com/eclipse-openj9/openj9/pull/16854, except for the addition of the lines
```c++
_catchBlockCounterSymRef->getSymbol()->setIsCatchBlockCounter();
_catchBlockCounterSymRef->getSymbol()->setNotDataAddress();
```
These need to be set so that the catch block counter relocation records get created in the appropriate places in …

Enable EDO during AOT compilation

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/CoreInfoCommand.java
runtime/oti/j9nonbuilder.h
runtime/vm/rasdump.c
runtime/vm/vmprops.c

Improve `!coreinfo` command to continue despite encountering faults trying to read information from the core file.
Fixes: #17397.

Put select system property names and values in allocated memory

---

runtime/oti/j9port_generated.h
runtime/port/sysvipc/j9sharedhelper.c
runtime/port/sysvipc/j9shmem.c
runtime/vm/CRIUHelpers.cpp
runtime/vm/jvminit.c

CRIU skips `j9sysinfo_get_username()`/`getpwuid()` if `isCheckPointAllowed` 
`portLibrary->finalRestore` was `false` by default when `CRIU` is not enabled, this skips `j9sysinfo_get_username()`/`getpwuid()` unnecessarily for `non-criu` applications.
Now `portLibrary->isCheckPointAllowed` is equivalent to `vmFuncs->isCheckpointAllowed()` which is true if `CRIU` is enabled and `javaVM->checkpointState.isCheckPointAllowed` is `true` as well.
closes https://github.com/eclipse-openj9/openj9/issues/17471
FYI @hangshao0 

CRIU skips j9sysinfo_get_username()/getpwuid() if isCheckPointAllowed

---

runtime/compiler/z/codegen/J9TreeEvaluator.cpp

In case of balanced GC policy, we generated code for awrtbar where in case of Non-NULL object stored into array object, it will re performing storing to avoid branching around which may have been cheaper. This re performing storing in the same object field twice for awrtbarrier somehow causing issue in unit test for PingPong using virtual threads where we end up with incorrect state in the array of ForkJoinTask causing one of the producer or consumer thread to be in waiting state. Change in this commit inserts the branch around the second store where we would jump to in case on runtime we encounter the null object store which can bypass costly write barrier checks.
Fixes: https://github.com/eclipse-openj9/openj9/issues/17255

Insert branch around re performing store for awrtbar

---

runtime/compiler/x/codegen/J9CodeGenerator.cpp
runtime/compiler/x/codegen/J9CodeGenerator.hpp

Add getNanoTimeTemp() to OpenJ9 as the first step of migrating it out of OMR
Issue: [omr #5133](https://github.com/eclipse/omr/issues/5133)

Add getNanoTimeTemp() to OpenJ9

---

runtime/compiler/z/codegen/J9TreeEvaluator.cpp

In case of balanced GC policy, we generated code for awrtbar where in case of Non-NULL object stored into array object, it will re performing storing to avoid branching around which may have been cheaper. This re performing storing in the same object field twice for awrtbarrier somehow causing issue in unit test for PingPong using virtual threads where we end up with incorrect state in the array of ForkJoinTask causing one of the producer or consumer thread to be in waiting state. Change in this commit inserts the branch around the second store where we would jump to in case on runtime we encounter the null object store which can bypass costly write barrier checks.

0.39.0: Insert branch around re performing store for awrtbar

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java

The changes rework the previous fix at https://github.com/eclipse-openj9/openj9/pull/17074
by performing the scope check before returning the valid
downcall address in `invokeNative()` to avoid any timing
issue with the downcall address.
Note:
The scope check is only intended for JDK20+ as explained
at https://github.com/eclipse-openj9/openj9/issues/17062.
Fixes: #17524

[FFI/Jtreg_JDK20] Validate the downcall address with the scope check (0.39)

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java

The changes rework the previous fix at https://github.com/eclipse-openj9/openj9/pull/17074
by performing the scope check before returning the valid
downcall address in `invokeNative()` to avoid any timing
issue with the downcall address.
Note:
The scope check is only intended for JDK20+ as explained
at https://github.com/eclipse-openj9/openj9/issues/17062.
Fixes: #17524

[FFI/Jtreg_JDK20] Validate the downcall address with the scope check (0.40)

---

test/functional/cmdLineTests/openssl/playlist.xml

Excluded cmdLineTester_CryptoTest in FIPS mode, as per the conversation found in issue #16902.
Signed-off-by: Paritosh Kumar <paritkum@in.ibm.com>

Exclude cmdLineTester_CryptoTest in FIPS mode

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Options.cpp

EDO is disabled on aarch64 until the problems identified in the linked issue can be resolved.
Fixes: #17535

Disable EDO under AOT/JITServer on aarch64

---

runtime/compiler/aarch64/codegen/CallSnippet.cpp
runtime/compiler/aarch64/codegen/ForceRecompilationSnippet.cpp
runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp
runtime/compiler/aarch64/codegen/J9UnresolvedDataSnippet.cpp
runtime/compiler/arm/codegen/ARMHelperCallSnippet.cpp
runtime/compiler/arm/codegen/CallSnippet.cpp
runtime/compiler/arm/codegen/J9UnresolvedDataSnippet.cpp
runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/codegen/J9WatchedInstanceFieldSnippet.cpp
runtime/compiler/codegen/J9WatchedStaticFieldSnippet.cpp
runtime/compiler/p/codegen/CallSnippet.cpp
runtime/compiler/p/codegen/ForceRecompilationSnippet.cpp
runtime/compiler/p/codegen/J9PPCInstruction.cpp
runtime/compiler/p/codegen/J9PPCSnippet.cpp
runtime/compiler/p/codegen/J9UnresolvedDataSnippet.cpp
runtime/compiler/p/codegen/PPCRecompilationSnippet.cpp
runtime/compiler/p/codegen/StackCheckFailureSnippet.cpp
runtime/compiler/runtime/HWProfiler.cpp
runtime/compiler/x/codegen/AllocPrefetchSnippet.cpp
runtime/compiler/x/codegen/CallSnippet.cpp
runtime/compiler/x/codegen/CheckFailureSnippet.cpp
runtime/compiler/x/codegen/ForceRecompilationSnippet.cpp
runtime/compiler/x/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/x/codegen/RecompilationSnippet.cpp
runtime/compiler/z/codegen/ForceRecompilationSnippet.cpp
runtime/compiler/z/codegen/J9S390Snippet.cpp
runtime/compiler/z/codegen/J9UnresolvedDataSnippet.cpp
runtime/compiler/z/codegen/S390AOTRelocation.cpp
runtime/compiler/z/codegen/S390J9CallSnippet.cpp

Replace all TR::ExternalRelocation allocations throughout with a factory method.
Take this opportunity to clean up the wildly inconsistent source formatting for all these allocation sites as well.

Use factory method for ExternalRelocations

---

runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/env/J9ObjectModel.cpp
runtime/compiler/env/J9ObjectModel.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/ilgen/IlGenerator.cpp
runtime/compiler/ilgen/Walker.cpp
runtime/compiler/optimizer/J9ValuePropagation.cpp
runtime/compiler/runtime/JITClientSession.cpp
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java

- Check `areFlattenableValueTypesEnabled` before checking if element is flattened
- Check if `Q` signature is supported or not before using `Q` signature to determine if the element is a value type
- This change is intended to lay the foundation to support the two cases: `Q` signature is supported and `Q` signature is not supported. This change does not handle the case where `Q` signature is not supported. At the moment as long as flattenable value types are enabled, `Q` signature is still supported
- Remove special handling on checking primitive value type in `genCheckcast` and disable `testCheckCastValueTypeOnNull` since the latest spec doesn't require special handling on null restricted value types.

Check flattenable value types and if Q signature is supported

---

buildenv/jenkins/variables/defaults.yml

Related to
https://github.com/adoptium/infrastructure/pull/3014
https://github.com/adoptium/infrastructure/issues/3083
This was tested with openssl 3.0.9 in https://github.com/eclipse-openj9/openj9/pull/14900

Update aarch64_linux build docker image to support building openssl 3

---

runtime/gc_vlhgc/SchedulingDelegate.cpp

After some GCs, the number of Free regions could be smaller than desired number of Eden regions, which causes the number of reserved Regions is smaller than 0(reserved Region size = Free Region size - Eden Region size), correct Eden region size = Free region size for the case.
fix: https://github.com/eclipse-openj9/openj9/issues/16413

Correct Balanced GC Eden size reporting for Mxbean

---

runtime/compiler/env/J9IO.cpp
runtime/compiler/ras/InternalFunctions.cpp

Add guard macros to J9IO.cpp and InternalFunctions.cpp to prevent z/TPF from redefining vfprintf to atoe_vfprintf.

For z/TPF disable ATOE mappings in J9IO and InternalFunctions

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java

The changes aim to prevent the downcall address from being
released unexpectedly by leveraging the existing code to
hold the downcall address during the downcall.
Fixes: #17524

[FFI/Jtreg_JDK20] Keep the downcall address alive for downcall

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java

The changes aim to prevent the downcall address from being
released unexpectedly by leveraging the existing code to
hold the downcall address during the downcall.
Fixes: #17524

[FFI/Jtreg_JDK20] Keep the downcall address alive for downcall (0.40)

---

runtime/rasdump/javadump.cpp

Fixes #17319
Verified on Windows:
```
1TIDMPDURATION Approximate time to produce this dump: 235 ms
```

Fix invalid OMR_PRI* usage on Windows

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9Inliner.hpp

- implementation of some APIs relies on the methods to be inlined even in cold blocks

Respect forceInline in cold blocks for some methods

---

runtime/nls/port/port.nls

The NLS message is used in https://github.com/eclipse/omr/pull/7029.
Related: https://github.com/eclipse/omr/issues/7021

Add NLS message: J9NLS_PORT_RUNNING_IN_CONTAINER_FAILURE

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/env/J9PersistentInfo.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/runtime/RelocationRuntime.cpp
runtime/compiler/runtime/RelocationRuntime.hpp

AOT methods compiled with SVM and received by the client from a JITServer AOT cache are now able to be relocated immediately.  Under the current defaults (if we detect that the current JVM is a JITServer client and the JITServer AOT cache deserializer is active) such methods will now always be relocated immediately. Formerly, such methods would always be stored in the local shared class cache and their count would be set to 0 so that they could be loaded from the local SCC on a subsequent invocation. This was done to avoid a particular assert documented in [this comment](https://github.com/eclipse-openj9/openj9/issues/17392#issue-1706225020) and alluded to in comments in the code that have been removed by these patches.
Such methods can be relocated immediately now because the relevant …

Permit JITServer AOT cache methods compiled with SVM to be immediately relocated at the client

---

runtime/compiler/optimizer/IdiomTransformations.cpp

In the case of a single non-constant delimiter, it's possible for the pattern to match when the original load and comparison look as follows:
n56n      istore  elem
n55n        b2i
n54n          bloadi <array-shadow>
...
n60n      istore tmpDelim
n59n        b2i
n58n          i2b
n57n            iload delim
n65n      ificmpeq --> block_EXIT
n55n        ==>b2i
n59n        ==>b2i
With such a match, the `booltable` node of the pattern graph corresponds to the `ificmpeq` node of the target graph. The transformer function for `TRT2` (`CISCTransform2FindBytes`) finds this target node and from there it uses the second child as the delimiter, but instead of the `b2i` that one might expect, that second child is a variable (`tmpDelim`) that has been matched up with the store node (`n60n` in this …

Avoid generating store of uninitialized auto when reducing TRT2

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/runtime/SymbolValidationManager.cpp
runtime/compiler/runtime/SymbolValidationManager.hpp

The _valueToSymbolMap generated at the JITServer itself is not useful to clients. It is used in the creation of relocation records during code generation and is unused afterward, including during method relocation.

Do not send SVM map to JITServer clients

---

test/functional/cmdLineTests/criu/criu.xml
test/functional/cmdLineTests/criu/criuCatVlog.sh
test/functional/cmdLineTests/criu/criuJitServerScript.sh
test/functional/cmdLineTests/criu/criu_jitPostRestore.xml
test/functional/cmdLineTests/criu/criu_jitserverAcrossCheckpoint.xml
test/functional/cmdLineTests/criu/criu_jitserverPostRestore.xml
test/functional/cmdLineTests/criu/criu_keepCheckpoint.xml
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/criu_nonPortableJDK11Up.xml
test/functional/cmdLineTests/criu/playlist.xml

Sometimes, a restore can fail in a known way, in which case the test is set to pass; however, this causes subsequent tests that depend on the output of this test to fail. This PR adds a new script to wrap the `cat` commands that test for certain Jitserver characteristics post restore. This wrapper script will check the output of the previous test if the vlog to cat does not exist, and outputs a message that causes the test to pass if the previous test failed in one of the known ways.
This PR also modifies the existing criu scripts to take in an additional parameter to not delete the `testOutput` file if subsequent tests need it.
Fixes https://github.com/eclipse-openj9/openj9/issues/17367

Fix Intermittent vlog not found CRIU Jitserver test failures

---

runtime/vm/jvminit.c

Reverts eclipse-openj9/openj9#16452
Reverting due to https://github.com/eclipse-openj9/openj9/issues/17598

Revert "Enable String Compression by default in OpenJ9"

---

runtime/nls/port/port.nls

Backport of https://github.com/eclipse-openj9/openj9/pull/17560.

[0.40] Add NLS message: J9NLS_PORT_RUNNING_IN_CONTAINER_FAILURE

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/StringPeepholes.cpp
runtime/shared_common/OSCachemmap.cpp
test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestOpenJ9DiagnosticsMXBean.java
test/functional/JLM_Tests/src/org/openj9/test/management/JvmCpuMonitorMXBeanTest.java

Noticed one instance in [test log](https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_extended.functional_ppc64_aix_Personal_testList_0/1/consoleFull) for https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/57.

Fix several mis-spellings of 'starting'

---

runtime/compiler/optimizer/IdiomTransformations.cpp

This is #17546 for 0.40, with the identical commit d33313e.

(0.40) Avoid generating store of uninitialized auto when reducing TRT2

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

The tree evaluator for multianewarray on X and Z has an optimisation for 0 length arrays that generate inline code for allocating the array. This code assumes that the new array will always have at least two dimensions, however the VM spec permits multianewarray to be used for 1 dimensional arrays. This does not appear to be used by javac, but can appear in code generated by other languages, e.g. Groovy.
This commit updates the evaluator on X to check the number of dimensions. For arrays of dimension 2 or more the original code is used with inline allocation where possible, and for 1 dimensional arrays the much simpler code from P is used which simply calls the helper.
TODO: Equivalent change for Z

Handle 1D arrays with multianewarray

---

runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/net/CommunicationStream.hpp

The implementations of `TR_J9SharedCacheVM::isGetImplInliningSupported` and `TR_J9SharedCacheVM::isGetImplAndRefersToInliningSupported` return false unconditionally, preventing inlining of `java/lang/ref/Reference.refersTo` and `java/lang/ref/Reference.getImpl` under AOT compilation.  This change removes the implementations of those methods in `TR_J9SharedCacheVM` to allow inlining to happen under AOT, with an additional test in `TR_J9VM::inlineNativeCall` of whether the 'referent' field's offset could not be retrieved - which can occur under AOT with no symbol validation manager.

Allow Reference.refersTo to be inlined under AOT

---

jcl/jpp_configuration.xml

Will be needed once
* [8306584: Start of release updates for JDK 22](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/a21367db0fbe574ca1b7964604236bb3aa5d0a88)
is merged into the openj9-staging branch.

Add preprocessor configuration for Java 22

---

runtime/compiler/control/JITClientCompilationThread.cpp

As another step toward eliminating the need for a local shared class cache when using the JITServer AOT cache feature, we now relocate AOT methods received from the JITServer at the client before storing them in the SCC.

Switch JITServer AOT method load/relocate order

---

runtime/gc_modron_startup/mminit.cpp
runtime/gc_modron_startup/mmparseXXgc.cpp

- Set list split forced flags during cmdline parsing, now required by upstream GC params init API.
- Revert GC thread count init behaviour: recompute the default thread count when the explicit thread count is invalid.

Update Split List Forced Flag + Revert CRIU Thread Count Reinit

---

jcl/src/java.base/share/classes/java/lang/Access.java
runtime/j9vm/exports.cmake
runtime/j9vm/j9scar.tdf
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/javanextvmi.cpp
runtime/oti/VMHelpers.hpp
runtime/redirector/forwarders.m4

`JDK21` adds `PreviewFeature` APIs and JVM methods
Added the following PreviewFeature APIs:
```
stringConcatCoder(char value)
stringBuilderConcatMix(long lengthCoder, StringBuilder sb)
stringBuilderConcatPrepend(long lengthCoder, byte[] buf, StringBuilder
sb)
```
Also added `JVM_PrintWarningAtDynamicAgentLoad`.
Rebased on 
* https://github.com/eclipse-openj9/openj9/pull/17125
required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/608

JDK21 adds PreviewFeature APIs and JVM methods

---

runtime/compiler/control/JITClientCompilationThread.cpp

When set, the TR_disableRemoteAOTMethodStorage environment variable instructs a JITServer client not to store AOT methods received from the JITServer in the local shared class cache.

Add TR_disableRemoteAOTMethodStorage env var

---

runtime/vm/jvminit.c

Swap the order of the conditionals in jvminit.c so that debug interpreter will always be used when debug is enabled instead of only when checkpoint is not enabled.
Without this, the interpreter will run into `unimplementedBytecode` when checkpoint is enabled and hitting a breakpoint made with a debugging agent like JDWP.
@tajila @JasonFengJ9 can you please take a look?

Use debug interpreter unconditionally when debug is enabled with CRIU

---

runtime/gc_base/ContinuationObjectList.cpp
runtime/gc_base/ContinuationObjectList.hpp
runtime/gc_base/OwnableSynchronizerObjectList.cpp
runtime/gc_base/OwnableSynchronizerObjectList.hpp
runtime/gc_base/ReferenceObjectList.cpp
runtime/gc_base/ReferenceObjectList.hpp
runtime/gc_base/UnfinalizedObjectList.cpp
runtime/gc_base/UnfinalizedObjectList.hpp
runtime/gc_glue_java/ConfigurationDelegate.hpp
runtime/gc_glue_java/HeapRegionDescriptorStandardExtension.hpp

HeapRegionDescriptorExtensions contain multiple array of obj lists which are inited at startup based on the startup thread count. These must be reinitialized during restore (CRIU) according to the new GC thread
count. Specifically, when the thread count is increased, it is necessary to divide the region object lists. This is required to improve parallelism with GC threads and ultimately improve GC performance for the restore environment. For background, see https://github.com/eclipse/omr/issues/6888 (Compensate for Thread Count Change).

GC CRIU: Reinit HeapRegionDescriptorExtensions (Region Obj Lists)

---

runtime/oti/vm_api.h
runtime/vm/CMakeLists.txt
runtime/vm/threadpark.cpp
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeCheckpointException.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeRestoreException.java

`CRIU` throws `JVMCRIUException` in single threaded mode if parks w/o timeout
The `checkpoint`/`restore` thread can't park indefinitely, a `JVMCRIUException` is to be thrown instead;
Added tests.

CRIU throws JVMCRIUException in single threaded mode if parks no timeout

---

runtime/gc_base/ContinuationObjectList.cpp
runtime/gc_base/ContinuationObjectList.hpp
runtime/gc_base/OwnableSynchronizerObjectList.cpp
runtime/gc_base/OwnableSynchronizerObjectList.hpp
runtime/gc_base/ReferenceObjectList.cpp
runtime/gc_base/ReferenceObjectList.hpp
runtime/gc_base/UnfinalizedObjectList.cpp
runtime/gc_base/UnfinalizedObjectList.hpp
runtime/gc_glue_java/ConfigurationDelegate.hpp
runtime/gc_glue_java/HeapRegionDescriptorStandardExtension.hpp

Double Deliver: https://github.com/eclipse-openj9/openj9/pull/17614

(0.40) GC CRIU: Reinit HeapRegionDescriptorExtensions (Region Obj Lists)

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp

This commit adds debug counters to instruction stream generated for interface call dispatching through `buildInterfaceCall` function. Debug counters are also added to instructions for calling interface through static PICs.

AArch64: Add debug counters to interface call dispatching sequence

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
test/functional/JIT_Test/playlist.xml
test/functional/JIT_Test/src/jit/test/tr/BNDCHKImplicitNull/BNDCHKImplicitNullTest.java
test/functional/JIT_Test/testng.xml

When the evaluator for bound check on arrays generates code to decompress pointers, it incorrectly sets the implicit exception point to be the load of the pointer decompression. This causes the garbage to collector to crash because it uses the wrong GC atlas.
This commit correctly handles this case but the implicit exception point on the cmp [mem] [reg] which actually loads the length field of an array.
Issue: #17171

Fix incorrect exception info in BNDCHK evaluator

---

runtime/oti/vm_api.h
runtime/vm/CMakeLists.txt
runtime/vm/threadpark.cpp
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeCheckpointException.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeRestoreException.java

`CRIU` throws `JVMCRIUException` in single-threaded mode if parks w/o timeout
The `checkpoint`/`restore` thread can't park indefinitely, a `JVMCRIUException` is to be thrown instead;
Added tests.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/17573
Resolved a merging conflict:
```
test/functional/cmdLineTests/criu/criu_nonPortable.xml
```

(v0.40.0-release) CRIU throws JVMCRIUException in single threaded mode if parks no timeout

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit replaces the call to isHeapObjectWrtBar() in VMCardCheckEvaluator() by chkHeapObjectWrtBar().
Fixes: #17617

AArch64: Fix a check in VMCardCheckEvaluator()

---

runtime/gc_base/ContinuationObjectBuffer.hpp
runtime/gc_base/OwnableSynchronizerObjectBuffer.hpp
runtime/gc_base/ReferenceObjectBuffer.hpp
runtime/gc_base/UnfinalizedObjectBuffer.hpp
runtime/gc_modron_standard/ContinuationObjectBufferStandard.cpp
runtime/gc_modron_standard/OwnableSynchronizerObjectBufferStandard.cpp
runtime/gc_modron_standard/ReferenceObjectBufferStandard.cpp
runtime/gc_modron_standard/UnfinalizedObjectBufferStandard.cpp

Address the particular scenario when a buffer is empty and in a reset state during its reinitialization.
Due to the update of _maxObjectCount by reinitializeForRestore, it becomes necessary to reset the buffer once more in order to update the _objectCount. During reset, _objectCount is set to _maxObjectCount (to appear full to force init on next add).

CRIU GC: Flush and Reset Buffers on Reinit

---

test/functional/Java8andUp/src/org/openj9/test/java/lang/reflect/Test_Executable.java

Modifiers were updated to include flags `SYNTHETIC` and `MANDATED` as required by the Java language specification; see
* https://bugs.openjdk.org/browse/JDK-8292275
Fixes: #17665.

Update test expectations for parameter modifiers

---

test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeCheckpointException.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeRestoreException.java

`CRIU` tests require only one `Pre-checkpoint` message
The messages after a checkpoint can't be required due to the known intermittent CRIU checkpoint errors.
close https://github.com/eclipse-openj9/openj9/issues/17657

CRIU tests require only one Pre-checkpoint message

---

runtime/shared/shrclssup.c
test/functional/cmdLineTests/shareClassTests/SCCMLTests/testSCCMLSoftmx.xml

1. Add call of j9shr_guaranteed_exit() if j9shr_init() returns J9VMDLLMAIN_SILENT_EXIT_VM on z/OS for persistent cache.
2. Add testing code.
Fixes #17628

Flush SCC modification from CML utility to file on disk on z/OS

---

runtime/gc_vlhgc/VLHGCAccessBarrier.cpp

There is missed check for compressed string in
MM_VLHGCAccessBarrier::jniReleaseStringCritical() - there is check that compressed strings are enabled. It assumes if strings compression is enabled every single one should be compressed (not true in general). Also added missed check is string compression is enabled to MM_VLHGCAccessBarrier::jniGetStringCritical()
Issue eclipse-openj9#17598

(0.40) Add missed check for compressed string

---

jcl/src/java.base/share/classes/module-info.java.extra
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeRestoreException.java

CRIU skips `clearInetAddressCache()` if `InetAddress` is not initialized
`InetAddress` static initializer invokes `SharedSecrets.setJavaNetInetAddressAccess()`, if
`SharedSecrets.javaNetInetAddressAccess` is `null`, `InetAddress` hasn't been initialized yet. In such case,
`SharedSecrets.getJavaNetInetAddressAccess().clearInetAddressCache()` is not invoked.
Updated the test.
closes https://github.com/eclipse-openj9/openj9/issues/17599

CRIU skips clearInetAddressCache() if InetAddress is not initialized

---

runtime/compiler/control/J9Options.cpp

PR #17425 introduced a change for limiting the total size of the Code Cache to no more than 25% of available physical memory. This is done based on the output from the `computeAndCacheFreePhysicalMemory()` function. This function takes into consideration the amount of physical memory installed on the machine and the limits imposed by cgroups, but also looks at how much free physical memory is available (not used by other proceses) at the moment of the call. Thus, if there is a transient and very narrow spike of memory usage by some other process when our JVM starts, the JVM may think that it has very limitted physical memory and allocate a very small code cache repository.
This commit changes the function used for computing physical memory to `omrsysinfo_get_addressable_physical_memory()` …

Change API used for computing code cache size in low memory environments

---

runtime/j9vm/j9memcategories.c
runtime/j9vm/jvm.c

Reset the runtime-filled memory category information if DestroyJavaVM succeeds.
Fixes: #17267

Reset memory categories on successful DestroyJavaVM

---

jcl/src/java.base/share/classes/module-info.java.extra
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeRestoreException.java

CRIU skips `clearInetAddressCache()` if `InetAddress` is not initialized
`InetAddress` static initializer invokes `SharedSecrets.setJavaNetInetAddressAccess()`, if
`SharedSecrets.javaNetInetAddressAccess` is `null`, `InetAddress` hasn't been initialized yet. In such case,
`SharedSecrets.getJavaNetInetAddressAccess().clearInetAddressCache()` is not invoked.
Updated the test.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/17646

(v0.40.0-release) CRIU skips clearInetAddressCache() if InetAddress is not initialized

---

test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeCheckpointException.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeRestoreException.java

`CRIU` tests require only one `Pre-checkpoint` message
The messages after a checkpoint can't be required due to the known intermittent CRIU checkpoint errors.
Cherry-pick https://github.com/eclipse-openj9/openj9/pull/17659
This is a test-only change that can help 0.40.0 build triage.

(v0.40.0-release) CRIU tests require only one Pre-checkpoint message

---

runtime/compiler/optimizer/EscapeAnalysis.cpp
runtime/compiler/optimizer/EscapeAnalysis.hpp
runtime/compiler/optimizer/EscapeAnalysisTools.cpp
runtime/compiler/optimizer/EscapeAnalysisTools.hpp

When Escape Analysis generates fake calls to `<eaEscapeHelper>` for OSR induction points or to guard calls that it has peeked when HCR is enabled, it passes loads of live locals and pending push temporaries on the `<eaEscapeHelper>` calls.  However, in the process of generating those loads, it doesn't check for duplicates, so there might be many redundant loads.  This change uses a `TR_BitVector` to track which locals and pending push temporaries need to be loaded for a call to `<eaEscapeHelper>` to avoid redundant loads.
Further, when Escape Analysis generates heapification code for an object, it will add a store at the method entry to zero initialized any temporary variable that might hold a reference to that heapified object.  However, it does that at each heapification point, so it …

Avoid redundant loads and stores in Escape Analysis

---

runtime/jvmti/jvmtiHeap.c
runtime/shared_common/OSCache.cpp

These unused counters are causing compiler errors in the latest version of XCode. 
Related to https://github.com/eclipse-openj9/openj9/issues/17493

Remove unused counters

---

test/functional/cmdLineTests/criu/criu_nonPortable.xml

CRIU tests pass if the original thread IDs can't be acquired
Added missing success conditions:
```
<output type="success" caseSensitive="yes" regex="no">Thread pid
mismatch</output>
<output type="success" caseSensitive="yes" regex="no">do not match
expected</output>
```
closes https://github.com/eclipse-openj9/openj9/issues/17692

CRIU tests pass if the original thread IDs can't be acquired

---

test/functional/cmdLineTests/criu/criu_nonPortable.xml

CRIU tests pass if the original thread IDs can't be acquired
Added missing success conditions:
```
<output type="success" caseSensitive="yes" regex="no">Thread pid
mismatch</output>
<output type="success" caseSensitive="yes" regex="no">do not match
expected</output>
```
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/17695
This is a test-only change which could help 0.40.0 milestone 2 build triage.

(v0.40.0-release) CRIU tests pass if the original thread IDs can't be acquired

---

runtime/vm/jvminit.c

Reverts eclipse-openj9/openj9#17602 to re-instate https://github.com/eclipse-openj9/openj9/pull/16452

Enable String Compression by default in OpenJ9

---

jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/RuntimeMXBeanImpl.java

Fixes https://github.com/eclipse-openj9/openj9/issues/17691

Return an unmodifiableList from RuntimeMXBean.getInputArguments()

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp

Fix the initialization code of static `tracePIC` flag so that the flag is enabled even if `TR_TraceCG` is not set when the environment variable `TR_TracePIC` is checked.

AArch64: Fix the flag to enable trace of PICs

---

buildenv/jenkins/common/pipeline-functions.groovy

resolves: https://github.com/eclipse-openj9/openj9/issues/17697
Cherry pick https://github.com/eclipse-openj9/openj9/pull/17698 for 0.40

(0.40) Split sanity.openjdk into 3 parallel jobs

---

runtime/jcl/common/stdinit.c
runtime/oti/j9nonbuilder.h
runtime/oti/jvminit.h
runtime/vm/ContinuationHelpers.cpp
runtime/vm/jvmfree.c
runtime/vm/jvminit.c

Allow manual setting of Continuation Tier 1/2 cache size.
This change also increases the default T2 size by 2.

Add -XX:continuationCache option

---

jcl/src/java.base/share/classes/java/lang/invoke/MethodHandleResolver.java

**Update MethodHandles.Lookup to IMPL_LOOKUP.in**
If a privileged class object is passed to MethodHandles.Lookup, it will throw an Illegal Argument Exception.
To address this issue and bypass the privileged method, using IMPL_LOOKUP instead of MethodHandles.Lookup.
The IMPL_LOOKUP is a package-protected version of Lookup that skips checkUnprivilegedLookupClass.
Fixes: #14544
Signed-off-by: Dipak Bagadiya [dipak.bagadiya@ibm.com](mailto:dipak.bagadiya@ibm.com)

Fix illegal lookupClass error caused by MethodHandles.Lookup method

---

jcl/src/java.base/share/classes/java/lang/Class.java

1. Simple Name of an unnamed class is an empty string.
2. Canonical Name of an unnamed class is null.
closes #17630

Add implementation of Class.isUnnamedClass()

---

jcl/jpp_configuration.xml
jcl/src/java.base/share/classes/java/lang/Access.java

`JDK22` removes `JavaLangAccess.fastUUID()`
Updated `JAVA22` `JAVA_SPEC_VERSION=22`.
closes https://github.com/eclipse-openj9/openj9/issues/17721

JDK22 removes JavaLangAccess.fastUUID()

---

jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/ManagementUtils.java
jcl/src/java.management/share/classes/sun/management/LazyCompositeData.java
jcl/src/java.management/share/classes/sun/management/LockInfoCompositeData.java
jcl/src/java.management/share/classes/sun/management/MappedMXBeanType.java
jcl/src/java.management/share/classes/sun/management/MemoryNotifInfoCompositeData.java
jcl/src/java.management/share/classes/sun/management/MemoryUsageCompositeData.java
jcl/src/java.management/share/classes/sun/management/MonitorInfoCompositeData.java
jcl/src/java.management/share/classes/sun/management/StackTraceElementCompositeData.java
jcl/src/java.management/share/classes/sun/management/ThreadInfoCompositeData.java
jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/PlatformMBeanProvider.java
jcl/src/jdk.management/share/classes/com/sun/management/HotSpotDiagnosticMXBean.java
jcl/src/jdk.management/share/classes/com/sun/management/VMOption.java
jcl/src/jdk.management/share/classes/com/sun/management/internal/ExtendedHotSpotDiagnostic.java
jcl/src/jdk.management/share/classes/com/sun/management/internal/Flag.java
jcl/src/jdk.management/share/classes/com/sun/management/internal/HotSpotDiagnostic.java
jcl/src/jdk.management/share/classes/com/sun/management/internal/VMOptionCompositeData.java

This will allow us to enable a JTReg test for Structured Concurrency.
JTReg test: StructuredTaskScope/StructuredThreadDumpTest
Related: #17634

Support HotSpotDiagnosticMXBean in OpenJ9 JDK21+

---

jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/ManagementUtils.java

The registration call was removed in eclipse-openj9#17709 due to a false
assumption. It has been added back since it is still required.
Refs:
- https://github.com/eclipse-openj9/openj9/pull/17709#discussion_r1246811609
- https://github.com/eclipse-openj9/openj9/pull/17709#discussion_r1247964717

Restore OpenJ9DiagnosticsMXBean registration call in ManagementUtils

---

runtime/compiler/z/codegen/J9TreeEvaluator.cpp

The existing multianewarray evaluator assumes at least 2 dimensions which is consistent with normal usage. However the spec permits 1D arrays and this is exploited by some languages, e.g. Groovy.
See https://github.com/eclipse-openj9/openj9/issues/17360 for more background and https://github.com/eclipse-openj9/openj9/pull/17358 for the corresponding change on X

Allow multianewarray for 1D arrays on Z

---

test/functional/Java21andUp/src/org/openj9/test/jep425/VirtualThreadTests.java

https:
//github.com/ibmruntimes/openj9-openjdk-jdk/commit/1edf1e6ea5b6bcb6a9f2df18d6c98eb4e0a86865 removed the lambda call in VirtualThread.run() method and added @hidden annotation to yieldContinuation(). These changes reduced frame counts of stacktraces in VirtualThreadTests.java.
Fixes https://github.com/eclipse-openj9/openj9/issues/17280

Correct JDK21 Jep425Tests_testVirtualThread

---

runtime/shared_common/OSCachesysv.cpp

It is possible that the semaphore is removed from the system by another
process and the JVM could reach this assertion. On z/OS, this assertion
leads the JVM to exit on core dumps, which is undesirable. The design
is to ignore the startup error of default SCC and continue without using
the SCC. The assertion message is:
```
j9shr.2038          Exit       <OSCache enterMutex failed - j9shsem_wait
failed with error = -328433
j9shr.1009   *   ** ASSERTION FAILED **
at /openj9/runtime/shared_common/OSCachesysv.cpp:1211: ((0 ))
```

Remove unnecessary assertion at OSCachesysv.cpp:1211

---

runtime/gc_base/StringTable.cpp

`j9gc_createJavaLangString` protects string objects across GC points
Added `PUSH_OBJECT_IN_SPECIAL_FRAME`/`POP_OBJECT_IN_SPECIAL_FRAME` pairs.
closes https://github.com/eclipse-openj9/openj9/issues/17738
FYI @dmitripivkine 

j9gc_createJavaLangString protects string objects across GC points

---

runtime/gc_base/StringTable.cpp

`j9gc_createJavaLangString` protects string objects across GC points
Added `PUSH_OBJECT_IN_SPECIAL_FRAME`/`POP_OBJECT_IN_SPECIAL_FRAME` pairs.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/17744

(v0.40.0-release) j9gc_createJavaLangString protects string objects across GC points

---

runtime/vm/rasdump.c

This commit replaces the calls to j9time_current_time_millis() in populateRASNetData() by calls to omrtime_hires_clock().
Fixes: #17719

Use omrtime_hires_clock() in populateRASNetData()

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
buildenv/jenkins/variables/defaults.yml

JDK versions that are no longer supported are removed or substituted from files pertaining to the build environment.
Temporary BootJDK20 URLs are, also, removed since Semeru 20 is now released and all platforms can now use the default parameterized API link.
Signed-off by: Kostas Tsiounis [kostas.tsiounis@ibm.com](mailto:kostas.tsiounis@ibm.com)

Clean up old JDK version and remove temporary urls

---

runtime/gc/gctable.c
runtime/gc_base/GCExtensions.hpp
runtime/gc_base/gc_internal.h
runtime/gc_base/modronapi.cpp
runtime/gc_base/modronapi.hpp
runtime/gc_glue_java/MarkingSchemeRootClearer.cpp
runtime/gc_glue_java/ScavengerRootClearer.cpp
runtime/gc_modron_startup/mmparseXXgc.cpp
runtime/gc_vlhgc/CopyForwardScheme.cpp
runtime/gc_vlhgc/GlobalMarkingScheme.cpp
runtime/oti/j9nonbuilder.h
runtime/vm/ContinuationHelpers.cpp

Currently GC maintain the global continuation lists contain all of
"live" continuation Object for releasing native resource(exceptional
case), jvmti retrieving all continuation and JIT code cache reclaim
processing.
keep less items in the list would reduce time to refresh/iterate the list.
- new Java Option -XXgc:AddContinuationInListOnFirstMount (default, would not add unstarted continuation in the list) and -XXgc:AddContinuationInListOnCreated.
- remove not only "dead" but also finished continuation during refreshing list.

Minimize continuation Object size in continuation list

---

test/functional/Valhalla/build.xml

Update source build version for Valhalla to JDK22

Update source build version for Valhalla to JDK22

---

runtime/gc_vlhgc/GlobalMarkCardScrubber.cpp
runtime/gc_vlhgc/GlobalMarkCardScrubber.hpp
runtime/gc_vlhgc/GlobalMarkDelegate.cpp
runtime/gc_vlhgc/GlobalMarkDelegate.hpp
runtime/gc_vlhgc/GlobalMarkingScheme.cpp
runtime/gc_vlhgc/GlobalMarkingScheme.hpp
runtime/gc_vlhgc/IncrementalGenerationalGC.cpp

The j9time_current_time_millis() uses UNIX gettimeofday() function, and is therefore non-monotonic and error-prone.
We turn to use monotonic j9time_hires_clock() function call.
Issue: #17706

Replace j9time_current_time_millis() with j9time_hires_clock() in gc

---

runtime/rasdump/dmpsup.c
runtime/rasdump/javadump.cpp
runtime/rasdump/rasdump_internal.h

A very common Linux `kernel.core_pattern` is [`|/opt/dynatrace/oneagent/agent/rdp`](https://www.dynatrace.com/support/help/platform-modules/applications-and-microservices/profiling-and-optimization/crash-analysis#linux-core-dump-handling) installed by the 3rd party monitoring product Dynatrace. When `rdp` is installed, it saves off the previous `kernel.core_pattern` into `/opt/dynatrace/oneagent/agent/conf/original_core_pattern`. When `rdp` handles a core dump, it first processes it internally, and then sends the core dump to the program in `original_core_pattern`.
Therefore, it's very common to see the following in a javacore:
```
2CISYSINFO     /proc/sys/kernel/core_pattern = |/opt/dynatrace/oneagent/agent/rdp
```
However, that doesn't really help understand where the core dump went …

Print Dynatrace original_core_pattern in javacore if available

---

runtime/vm/ValueTypeHelpers.hpp

When calling loadFlattenableArrayElement it is possible that destObject gets moved by the GC. We can get the new, correct address by pushing and popping destObject in a special frame.
Fixes #17675

Follow moved destObject in copyFlattenableArray

---

runtime/codert_vm/dlt.c
runtime/oti/VMHelpers.hpp
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/OutOfLineINL.hpp
runtime/vm/exceptionsupport.c

Reset the field on entry to the interpreter and remove unnecessary clearing and resetting throughout the code.
Related: #16741

Simplify use of jitStackFrameFlags

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.cpp
runtime/compiler/net/MessageTypes.hpp
runtime/compiler/optimizer/InterpreterEmulator.cpp

Invokedynamic call resolution can either result in a valid entry
in the CallSite table if successful, or an exception object
otherwise. The call site table entry is a two element array
containing the MemberName and appendix objects necessary for
constructing a resolved invokedynamic call. The exception object
would not be an array type object, and therefore it is sufficient
to check if the entry obtained from the CallSite table is an array
instance to determine if the resolution was successful.
This changeset handles the cases when we have an invalid entry
in the CallSite table that results in either failed inlining or
failed compilation, depending on whether the invokedynamic is part
of the inlining candidate or the root method, respectively.
Issue: #16965

Abort compilations for exceptions during invokedynamic resolution

---

runtime/bcutil/ClassFileOracle.cpp
runtime/bcutil/ClassFileOracle.hpp
runtime/bcutil/ROMClassBuilder.cpp
runtime/bcutil/ROMClassWriter.cpp
runtime/bcutil/ROMClassWriter.hpp
runtime/bcutil/attrlookup.gperf
runtime/bcutil/attrlookup.h
runtime/bcutil/cfreader.c
runtime/nls/cfre/cfrerr.nls
runtime/oti/cfr.h
runtime/oti/j9javaaccessflags.h
runtime/oti/j9modifiers_api.h
runtime/oti/j9nonbuilder.h
runtime/oti/util_api.h
runtime/oti/vm_api.h
runtime/util/optinfo.c
runtime/vm/createramclass.cpp

- Add attributes to attribute hash table (attrlookup.gperf)
- Read attributes from classfile (cfreader.c)
- Store attributes in ClassFileOracle object (ClassFileOracle.cpp)
- Set new flags in ROMClass (ROMClassBuilder.cpp)
- Allow new attributes to be serialized (ROMClassWriter.cpp)
- Preload classes marked for preloading (createramclass.cpp)
For issues #17233 and #17234

Add Preload and ImplicitCreation attributes

---

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
runtime/criusupport/criusupport.cpp
runtime/criusupport/criusupport.hpp
runtime/criusupport/exports.cmake
runtime/criusupport/j9criu.tdf
runtime/criusupport/uma/criusupport_exports.xml

CRIU `init()` invokes `setupJNIFieldIDsAndCRIUAPI()`
Added a native `CRIUSupport.setupJNIFieldIDsAndCRIUAPI()`;
If there is a problem loading `j9criu29` library and associated methods, the `criu.SystemCheckpointException` is thrown.

CRIU init() invokes setupJNIFieldIDsAndCRIUAPI()

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalUpcallHandler.java
jcl/src/java.base/share/classes/openj9/internal/foreign/abi/UpcallMHMetaData.java
runtime/oti/vmconstantpool.xml
runtime/vm/OutOfLineINL_openj9_internal_foreign_abi_UpCallMHMetaData.cpp
runtime/vm/UpcallVMHelpers.cpp

The changes validate the pointer address against
the alignment value of its target layout introduced
in JDK21 if exists to ensure the pointer segment
with the valid alignment & size is passed-in or
returned during the downcall/upcall.
Note:
The changes aim to unify the validation methods in
java shared by downcall & upcall with MH filters,
in which case there is no need to do call-ins to
capture the exceptions/invalid cases in the dispatcher.
Thus, it is easy to extend the validation in java
without modifying the code in the dispatcher. 
Fixes: #17686

[FFI/Jtreg_JDK21] Validate the alignment of the pointer address

---

test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_Thread.java

Remove `test_countStackFrames` to pass `JDK22` test compilation
`JDK22` removed `java.lang.Thread.countStackFrames()`.
closes https://github.com/eclipse-openj9/openj9/issues/17772

Remove test_countStackFrames to pass JDK22 test compilation

---

runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/optimizer/EscapeAnalysis.cpp
runtime/compiler/optimizer/EscapeAnalysis.hpp
test/functional/Valhalla/playlist.xml
test/functional/Valhalla/src/org/openj9/test/lworld/NullRestrictedTypeOptTests.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeOptTests.java
test/functional/Valhalla/testng.xml

These changes enable support for stack allocation of instances of value type classes in escape analysis.  The changes are staged through a sequence of commits to aid in reviewing:
1. Commit 16d4e5ec4ac4d9bc390ebb2c8fb2229de283abb2 adds support for contiguous stack allocation of instances of value type classes
2. Commit 075335a1a65d53146590de54071cd3a6c6c91e14 adds support for non-contiguous stack allocation of instances of value type classes
3. Commit c2951330f46ea107e6d401e1154d51d3bedfeeef adds support for cold block heapification of instances of value type classes
4. Commit 404cd86f5cd9c6c651c3eee86b608cf104c7df86 adds special "harmless" recognition of array element load operations through calls to helper or non-helper methods
5. Commit 453a61a077717d12b4463a984cb1e872b4db8c66 adds …

Enable value types escape analysis

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/net/ClientStream.cpp
runtime/compiler/net/ClientStream.hpp

When encryption is enabled for a JITServer client post CRIU restore, the client needs to update its SSL configuration with the newly provided certificate. This is done in `ClientStream::static_init()` function which needs to be called during `processOptionsPostRestore()`.
Moreover, if SSL encryption was specified pre-checkpoint, the hook that gets executed, `TR::CompilationInfo::prepareForCheckpoint()`, will delete the existing SSL context and any existing certificate.
Issue: #17786

Initialize JITServer SSL context post CRIU restore

---

runtime/compiler/optimizer/J9EstimateCodeSize.cpp
runtime/compiler/optimizer/J9EstimateCodeSize.hpp
runtime/compiler/optimizer/J9Inliner.hpp

Lowering the estimated weight of callees by the empirically derived factor of 0.75 encourages inlining of callees where further optimizations can be unlocked due to the constant args being passed to the callees. Here are a few examples where this weight reduction can help:
* failed inlining because size estimate for a target is blown up because the callee being considered for inlining is already compiled at a higher opt level than the caller, despite there being possible benefits being unlocked by inlining
* encourage inlining certain methods that may have been just over the size limit for being considered for inlining, despite the constant args providing opportunities for compile-time folding
This size adjustment happens early on during ECS, overcoming the size threshold check during …

Adjust call target weight estimate for callees with const args

---

runtime/gc_base/GCExtensions.hpp

Related: #17554
Currently, the default mode is “onStarted”. This adds the continuation
to the list only when the VirtualThread (or the Continuation) starts.
The “onCreated” mode adds to the list as soon as the VirtualThread
(or the Continuation) object is created. This mode is needed if JVMTI
is used. So, the default is changed to “onCreated” until we can
dynamically determine that JVMTI won’t be used.
With “onStarted” as default, the following failures started to occur
last week:
- #17784
- #17791 (intermittent)
- #17782 (intermittent)

Update the default mode for adding to the continuation list

---

runtime/jvmti/jvmtiThread.c

Previously, StopThread returned JVMTI_ERROR_UNSUPPORTED_OPERATION for
a virtual thread.
In JDK21, StopThread includes support for virtual threads as per the
JVMTI specification:
- Error if a virtual thread is not suspended and not the current
thread.
- Error if a virtual thread is unomunted since it won't be able to
throw an asynchronous exception from the current frame.
Related:
- #17717
- #17718
Also, StopThread should not clear the
J9_PUBLIC_FLAGS_HALT_THREAD_JAVA_SUSPEND flag. This behaviour is not
documented in the JVMTI specification. It causes incorrect behaviour
for ResumeThread when the following sequence of JVMTI functions are
invoked: SuspendThread -> StopThread -> ResumeThread.

[JDK21] Add support for JVMTI StopThread

---

runtime/oti/j9nonbuilder.h
runtime/tests/clinkerffi/CMakeLists.txt
runtime/tests/clinkerffi/module.xml
runtime/tests/clinkerffi/upcall.c
runtime/vm/UpcallVMHelpers.cpp
test/functional/Java17andUp/src_170/org/openj9/test/jep389/upcall/UpcallMHWithStructTests.java
test/functional/Java17andUp/src_170/org/openj9/test/jep389/upcall/UpcallMethodHandles.java
test/functional/Java20andUp/src/org/openj9/test/jep434/upcall/UpcallMHWithStructTests.java
test/functional/Java20andUp/src/org/openj9/test/jep434/upcall/UpcallMethodHandles.java
test/functional/Java21andUp/src/org/openj9/test/jep442/upcall/UpcallMHWithStructTests.java
test/functional/Java21andUp/src/org/openj9/test/jep442/upcall/UpcallMethodHandles.java

The changes perform the sign extension operation
on the negative byte/short value to guarantee
the negative value to be accessed correctly
during the upcall.
Fixes: #17779

[FFI/Jtreg_JDK21] Sign extend the negative byte/short for upcall

---

test/functional/cmdLineTests/criu/criuCatVlog.sh

Check if the previous test failed when checking the vlog regardless of whether the vlog exists or not; if a vlog is specified pre-checkpoint then it will exist post-restore even if the restore fails for one of the known reasons.
Fixes https://github.com/eclipse-openj9/openj9/issues/17729

Check if prev test failed when checking vlog

---

jcl/src/java.base/share/classes/java/lang/Class.java

JDK22 adds `Class.forPrimitiveName(typeName)`
Returns the Class object with the given primitive type name. If the name is not associated with a primitive type, `null` is returned.
closes https://github.com/eclipse-openj9/openj9/issues/17801

JDK22 adds Class.forPrimitiveName(typeName)

---

jcl/src/java.base/share/classes/java/lang/Access.java

Removed special case for 20 since 20 is no longer supported.
Obsoletes https://github.com/eclipse-openj9/openj9/pull/17362

Restore @Override annotation for Access.getLoaderNameID()

---

buildenv/jenkins/variables/defaults.yml

Includes fix for CVE-2023-3446.

Update OpenSSL to the 1.1.1 July 19 CVE level

---

buildenv/jenkins/variables/defaults.yml

The archived jdk20 builds for AIX and zLinux are no longer available.
Similar changes to https://github.com/eclipse-openj9/openj9/pull/17756

(0.40) Use jdk19 to build jdk20

---

buildenv/jenkins/variables/defaults.yml

Includes fix for CVE-2023-3446.
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/17828 for 0.40

(0.40) Update OpenSSL to the 1.1.1 July 19 CVE level

---

jcl/jpp_configuration.xml

Attempts to build Java 20 from the master branch would fail anyway since #17833 landed. With this, the failure will just occur sooner.

Remove JAVA20 from jpp_configuration.xml

---

runtime/compiler/optimizer/VectorAPIExpansion.cpp

- it is safe(and currenlty necessary) to set isInternalPointer on each aladd generated by VectorAPIExpansion since they all point to an array element

Set isInternalPointer on each aladd in VectorAPIExpansion

---

runtime/vm/extendedMessageNPE.cpp
test/functional/Java14andUp/src/org/openj9/test/jep358/NPEMessageTests.java

NPE extended message handle `long`/`double` array parameters
The `long` or `double` array doesn't need an extra slot, handled this corner case at `initStackFromMethodSignature()`;
Added tests.
closes https://github.com/eclipse-openj9/openj9/issues/17247

NPE extended message handle long/double array parameters

---

runtime/bcutil/ROMClassCreationContext.hpp
runtime/util/hshelp.c

Currently, Object is marked unmodifiable if extended HCR is enabled.
This change allows Object to be modified, but disallows use of the
extensions on Object.
Fixes: #17454

Allow Object to be modifiable in extended HCR

---

runtime/jvmti/jvmtiStackFrame.c

Previously, PopFrame returned JVMTI_ERROR_OPAQUE_FRAME for a virtual
thread.
In JDK21, PopFrame includes support for virtual threads as per the
JVMTI specification:
- Error if a virtual thread is not suspended and not the current
thread.
- Error if a virtual thread is unomunted since it won't be able to
pop the current frame.
- For a carrier thread with a virtual thread mounted, the details of
the carrier thread are derived from targetThread->currentContinuation.
Related:
- #17715
- #17716
Also, there is no need to halt and resume a thread for inspection since
PopFrame expects the thread to be suspended as per the JVMTI spec. If a
thread is not suspended, it returns JVMTI_ERROR_THREAD_NOT_SUSPENDED.

[JDK21] Add support for JVMTI PopFrame

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

A new version of `loadAddressConstant` API was added to AArch64 codegen in OMR. This commit updates J9TreeEvaluator.cpp and ARM64PrivateLinkage.cpp to use the new version of the API.

AArch64: Replace old loadAddressConstant calls to new APIs

---

doc/build-instructions/Build_Instructions_V11.md
doc/build-instructions/Build_Instructions_V17.md
doc/build-instructions/Build_Instructions_V20.md
doc/build-instructions/Build_Instructions_V8.md

It is not clear from the existing instructions where to download `mkdocker.sh` for local Linux builds.
Thanks @Narendra-Datar for pointing this out.

Add download mkdocker.sh for local linux build instructions

---

doc/compiler/aot/RelocationRecords.md
runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/p/runtime/PPCRelocationTarget.cpp
runtime/compiler/runtime/J9Runtime.hpp
runtime/compiler/runtime/MetaData.cpp
runtime/compiler/runtime/RelocationRecord.cpp
runtime/compiler/runtime/RelocationRecord.hpp
runtime/compiler/runtime/RelocationRuntime.cpp
runtime/compiler/runtime/RelocationRuntime.hpp
runtime/compiler/runtime/Runtime.cpp
runtime/compiler/z/codegen/S390AOTRelocation.cpp

There are two different types of method enter/exit tracing available:
1. `-Xtrace:print=mt,methods=...`
2. JVMTI method enter/exit hooks
If either of these types of tracing are possible, then the ILGenerator generates IL containing `TR::MethodEnterHook` and/or `TR::MethodExitHook` op codes. Later on in the compilation, `TR_J9VMBase::lowerMethodHook` is invoked on these op codes. 
If `-Xtrace` is specified on a particular method, then the compiler generates a call to the appropriate helper [1]. Otherwise, if the JVM may have to report method enter/exit hooks to a JVMTI agent, then a runtime test is generated [2].
Like the JIT case, if either of these types of tracing are possible, then the ILGenerator generates IL containing `TR::MethodEnterHook` and/or `TR::MethodExitHook` op codes, on …

Make AOT Compilation generate the same code as JIT Compilation for enter/exit tracing

---

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
runtime/jvmti/jvmtiHelpers.c

Java methods tagged with the JvmtiMountTransition annotation are
involved in transitioning between carrier to virtual threads, and
vice-versa.
These methods are not part of the thread's scope. So, they are skipped
during introspection by the following JVMTI functions:
- ForceEarlyReturn
- NotifyFramePop
- Local Variable (GetOrSetLocal)
This PR allows us to match the RI in `jvmti/vthread/MethodExitTest`.
Related #17490
Closes #17758

Skip methods with JvmtiMountTransition annotation in findDecompileInfo

---

runtime/criusupport/criusupport.cpp
runtime/criusupport/j9criu.tdf
runtime/vm/exceptionsupport.c
runtime/vm/j9vm.tdf
test/functional/cmdLineTests/criu/criu_nonPortable.xml

CRIU triggers `javacore` dump in case of blocking operation disallowed
Blocking operation is not allowed in CRIU single thread mode, JVM throws `JVMCheckpointException` or `JVMRestoreException`, in addition, triggers a `javacore` dump which could be used to identify application code causing
the blocking.
Additional note about the `char*` cast invoking `triggerOneOffDump()`:
`triggerOneOffDump()` has a few other usages in `c` files; no `cast` is required.
`c++` compilation failed due to `error: ISO C++ forbids converting a string constant to 'char*' [-Werror=write-strings]`.
Refactoring triggerOneOffDump() parameters require changes in a few other methods including OMR helpers:
* https://github.com/eclipse-openj9/openj9/issues/17858

CRIU triggers javacore dump in case of blocking operation disallowed

---

runtime/codert_vm/cnathelp.cpp
runtime/j9vm/java11vmi.c
runtime/jcl/common/java_lang_Class.cpp
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/j9vm.tdf
runtime/vm/visible.c

Hidden nest member is not in the nestmember attribute of the nest host.
If extensions are enabled and the nest host is redefined, the nest host
of hidden nest member is not updated. Do not cache nest host into
class->nestHost in this case so that the nest host will always be found
in the class table for hidden nest members.

Do not cache nesthost of hidden nestmate classes if extension enabled

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/runtime/J9Runtime.hpp

Fix typo in variable identifier "TR_InlinedSiteHastTableEntry"
The identifier "TR_InlinedSiteHastTableEntry" was mistakenly misspelled as "TR_InlinedSiteHashTableEntry" in various parts of the codebase. This typographical error caused confusion and inconsistencies throughout the project.
This commit addresses the issue by correcting the typo and renaming the variable to "TR_InlinedSiteHashTableEntry" consistently throughout the project.
By using the correct identifier, we improve code readability and maintain consistency, reducing the potential for future errors and misunderstandings in the codebase.
Closes: https://github.com/eclipse-openj9/openj9/issues/17450
Signed-off-by: prajwalbandak [prajwalbandak777@gmail.com](mailto:prajwalbandak777@gmail.com)

Rename TR_InlinedSiteHastTableEntry to TR_InlinedSiteHashTableEntry.

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalUpcallHandler.java
jcl/src/java.base/share/classes/openj9/internal/foreign/abi/LayoutStrPreprocessor.java
jcl/src/java.base/share/classes/openj9/internal/foreign/abi/UpcallMHMetaData.java
runtime/nls/j9vm/j9vm.nls
runtime/oti/j9nonbuilder.h
runtime/tests/clinkerffi/CMakeLists.txt
runtime/tests/clinkerffi/downcall.c
runtime/tests/clinkerffi/module.xml
runtime/tests/clinkerffi/upcall.c
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/UpcallVMHelpers.cpp
runtime/vm/bindnatv.cpp
runtime/vm/vmthread.cpp
test/functional/Java21andUp/src/org/openj9/test/jep442/downcall/PrimitiveTypeTests1.java
test/functional/Java21andUp/src/org/openj9/test/jep442/downcall/PrimitiveTypeTests2.java
test/functional/Java21andUp/src/org/openj9/test/jep442/upcall/InvalidUpCallTests.java
test/functional/Java21andUp/src/org/openj9/test/jep442/upcall/UpcallMethodHandles.java

The changes aim to capture the linker option intended for
the trivial downcall during the upcall given the option is
only used to enable the trivial downcall without upcall
involved.
Fixes: #17820
Note:
The changes with related test cases cover two aspects separately:
[1] remove the VMAccess in the downcall for the benefit of the JIT.
[2] capture the invalid linker option in upcall dispatcher and throw
out the exception after jumping back to the downcall site.

[FFI/Jtreg_JDK21] Detect the downcall linker option in upcall

---

runtime/jvmti/jvmtiForceEarlyReturn.c
runtime/jvmti/jvmtiStackFrame.c

Previously, ForceEarlyReturn returned JVMTI_ERROR_OPAQUE_FRAME for a
virtual thread.
In JDK21, ForceEarlyReturn includes support for virtual threads as
per the JVMTI specification:
- Error if a virtual thread is not suspended and not the current
thread.
- Error if a virtual thread is unmounted since it won't be able to
force an early return.
- For a carrier thread with a virtual thread mounted, the details of
the carrier thread are derived from targetThread->currentContinuation.
Also, there is no need to halt and resume a thread for inspection since
ForceEarlyReturn expects the thread to be suspended as per the JVMTI
spec. If a thread is not suspended,
it returns JVMTI_ERROR_THREAD_NOT_SUSPENDED.
Related: #17713

[JDK21] Add support for JVMTI ForceEarlyReturn

---

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp
runtime/compiler/aarch64/codegen/J9CodeGenerator.hpp

This commit adds `callUsesHelperImplementation` query function to AArch64 code generator which overrides OMR's implementation. The function returns true if a Java method call is implemented using an internal runtime helper.[
Depends on https://github.com/eclipse/omr/pull/7077
See https://github.com/eclipse-openj9/openj9/pull/6908 for the reason why this query is needed for JITServer.

AArch64: Override callUsesHelperImplementation function

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/runtime/J9CodeCacheManager.cpp
runtime/compiler/runtime/J9CodeCacheManager.hpp

When running in low memory environment like containers with limited memory, code cache allocation needs to consider the available free memory before allocating new cache. A new check to confirm safe memory limits before carving new code cache.

Handle code cache allocation when available memory becomes low

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/codegen/CallSnippet.cpp

Historically, method calls generated under AOT have been handled as unresolved calls. However, it is no longer true when the Symbol Validation Manager is enabled.
This commit changes AArch64 codegen to generate unresolved calls if `isResolvedDirectDispatchGuaranteed()` query returns false. Also, this commit removes an unnecessary TR_MethodObject relocation from CallSnippets.

AArch64: Fix direct calls under JITServer and SVM

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/codegen/CallSnippet.cpp

This commit updates `TR::ARM64CallSnippet::generateInvokeExactJ2IThunk` to get thunk helper address through front end so that it can obtain correct values in remote compilation mode.
This commit also updates `J9::ARM64::PrivateLinkage::buildVirtualDispatch` to add the thunk to the table through front end so that it can update the client side thunk table.

AArch64: Fix thunk generation to support JITServer

---

runtime/bcutil/ClassFileWriter.cpp
runtime/cfdumper/main.c
runtime/oti/util_api.h
runtime/util/optinfo.c
runtime/util/rcdump.c
runtime/util/romclasswalk.c
runtime/vm/createramclass.cpp

Also rename getNumberOfPreloadClassesPtr to getPreloadInfoPtr to clarify behavior.
Related to: https://github.com/eclipse-openj9/openj9/issues/17233
Part of these changes came from the work @ehrenjulzert drafted https://github.com/eclipse-openj9/openj9/pull/17787. I split up the commit to commit the attribute support separately. Thanks Ehren!

cfdump support for Valhalla preload attribute

---

runtime/vm/BytecodeInterpreter.hpp

The arraycopy INL builds a frame for many error cases and the value type case which may require allocation. Simplifying the code so the frame is always built early greatly simplifies the code and corrects a problem introduced in #17732 (INL frame build, tear down and rebuild is no longer allowed in general and I missed a case here). It also appear to fix the reported issue, though I'm not entirely sure why.
Also fix a missing frame build in the Thread interrupted INL.
Fixes: #17875

Simplify INL frame build in System.arraycopy

---

runtime/compiler/runtime/JITClientSession.hpp

This commit fixes the type of _timeOfLastPurge in ClientSessionHT from uint64_t to int64_t.
The field is used to store the return value from j9time_current_time_millis(), whose type is int64_t.

Fix the type of _timeOfLastPurge in ClientSessionHT

---

runtime/compiler/control/JITClientCompilationThread.cpp

This commit updates JITClientCompilationThread to flush icache after copying instructions to code cache when handling `VM_setInvokeExactJ2IThunk` messages.
I and @knn-k have been investigating an intermittent crash with jitserver client VM on AArch64 Linux. The issue seems to be resolved with this change.

JITServer: Flush ICache after constructing invokeExactJ2IThunk

---

runtime/compiler/aarch64/codegen/CallSnippet.cpp

This commit updates `TR::ARM64CallSnippet::generateVIThunk` to use front end query to determine the type of memory where VI thunk instructions are stored.

AArch64: Use front end query when allocating VI Thunks

---

runtime/compiler/aarch64/codegen/ARM64Recompilation.cpp

OpenJ9 #7044 introduced `getExistingJittedBodyInfo()`. This commit updates `TR_ARM64Recompilation::getExistingMethodInfo` to use it.

AArch64: Get existing method info from the J9Method instead of startPC

---

runtime/compiler/optimizer/J9EstimateCodeSize.cpp

Weight adjustments done during ECS based on arg count and whether args are load consts or boxed primitive can have a negative impact on certain workloads due to overly aggressive inlining. They are now guarded within environment variables.

Disable certain weight adjustments during early ECS

---

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/Attachment.java
runtime/vm/BytecodeInterpreter.hpp

Change `Attachment.loadAgentLibrary()` to a public static method
Added a dummy arg for the native loadAgentLibraryImpl() to ensure that the current native method has the ClassLoader instance as its second argument required by `jnimisc.cpp:getCurrentClassLoader()`.
related to
* https://github.com/eclipse-openj9/openj9/issues/17500

Change Attachment.loadAgentLibrary() to a static method

---

runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/env/j9methodServer.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp

- if method annotated IntrinsicCandidate is not a recognized
method and, therefore, most likely not treated as an intrinsic
it's probably beneficial to inline it
- force inlining of methods annotated as IntrinsicCandidate
unless they are recognized methods
- this inlining can be disabled with -Xjit:disableInliningUnrecognizedIntrinsics
Depends https://github.com/eclipse/omr/pull/7080

Inline IntrinsicCandidate methods

---

test/functional/Java21andUp/src/org/openj9/test/jep425/VirtualThreadTests.java

The wait time has been increased from 500 ms to 10000 ms. This should
give the virtual thread sufficient time to park on slower machines.
This impacts the following tests:
- test_synchronizedBlockFromVirtualthread
- test_jniFromVirtualthread
test_YieldedVirtualThreadGetStackTrace was earlier updated
in #17194.
Fixes: #17924

[JDK21+] Increase wait time in VirtualThreadTests

---

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/DiagnosticUtils.java
runtime/j9vm/javanextvmi.cpp
runtime/jvmti/j9jvmti.tdf
runtime/jvmti/jvmtiStartup.c
runtime/oti/j9nonbuilder.h
runtime/vm/BytecodeInterpreter.hpp

Implement JEP 451: Prepare to Disallow the Dynamic Loading of Agents
Print warning message when loading an agent via `AttachAPI` `loadAgentLibraryImpl()` if `-XX:+EnableDynamicAgentLoading` is not specified, and the agent wasn't loaded before;
Added `isAgentLibraryLoaded()` to determine if an agent has been loaded already;
Implemented `JVM_PrintWarningAtDynamicAgentLoad()`;
Added `jcmd` command `JVMTI.agent_load` to support openjdk test `test/jdk/com/sun/tools/attach/warnings/DynamicLoadWarningTest.java`;
Updated a few trace points within `loadAgentLibraryGeneric()`.
This passes [an internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34281/console) `openjdk` `test/jdk/com/sun/tools/attach/warnings/DynamicLoadWarningTest.java` w/
* …

Implement JEP 451: Prepare to Disallow the Dynamic Loading of Agents

---

test/functional/VM_Test/playlist.xml
test/functional/VM_Test/src/com/ibm/j9/cfdump/tests/lineardump/LinearDumpTests.java

Issue https://github.com/eclipse-openj9/openj9/issues/10917
Tested jdk8 all platforms in https://openj9-jenkins.osuosl.org/job/Grinder/2675/ which passed.

Update LinearDumpTests.testInvalidClassFile() and enable CFdumptest

---

test/functional/JIT_Test/playlist.xml
test/functional/cmdLineTests/criu/playlist.xml
test/functional/cmdLineTests/jitserver/playlist.xml

This commit enables JITServer tests on AArch64 Linux.

Enable JITServer tests on AArch64 Linux

---

debugtools/DDR_VM/data/superset-constants.dat
runtime/bcutil/ROMClassBuilder.cpp
runtime/oti/j9javaaccessflags.h

- Reorganized these values to be more readable
- Deleted the unused values:
#define J9AccMandated 0x8000
#define J9AccClassReferenceShift 0x1C
#define J9AccClassUnused400 0x400 <-- I don't think these placeholders are really helping anyone
#define J9AccClassUnused200 0x200
Related to https://github.com/eclipse-openj9/openj9/issues/17785

Reorder j9javaaccessflags.h and remove unused flags

---

runtime/codert_vm/decomp.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/jvmti/jvmtiClass.c

It is no longer possible for a JIT compilation to observe surprising changes due to concurrent class redefinition. In particular, within a given compilation:
- Resolved CP (constant pool) entries remain resolved.
- Class/method pointers in resolved CP entries do not change.
- The ROM class of any given J9Class does not change.
Fixes #12265

Ensure all JIT compilations are paused during class redefinition

---

runtime/vm/BytecodeInterpreter.hpp

The changes follow the latest update for the error code layout in JDK21 at
https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/src/java.base/share/classes/jdk/internal/foreign/abi/CapturableState.java to ensure all error code required on Windows
are saved correctly in order in the error code segment.
Fixes: #17873

[FFI/Jtreg_JDK21] Store the error codes correctly on Windows

---

runtime/compiler/codegen/J9CodeGenerator.hpp
runtime/compiler/p/codegen/PPCJNILinkage.cpp
runtime/compiler/p/codegen/PPCPrivateLinkage.cpp

When running portable code (CRIU or PortableAOT) on PWR10 CPUs and a method needs to save all non-volatile registers so that GC has access to them (i.e. methods with a Direct-to-JNI call-out) this issue can occur. 1) The portable code will be compiled for PWR8 and therefor does not save R16 since it is dedicated to the PTOC and therefore can never contain a collectible obj ref. 2) A method lower on the stack could have been compiled for PWR10 and used R16 to hold a collectible obj ref. Now if a GC cycle occurs while executing in the JNI code, the GC will retrieve the saved non-volatile registers from the frame of the portable code method (R17-R31). Then it walks the stack looking for collectible references. When it encounters a frame for a PWR10 compiled method that has marked R16 as …

Fix GC crash when running portable code on PWR10 CPUs

---

runtime/compiler/codegen/J9CodeGenerator.cpp

This ensures that code generators will not generate an unnecessary shift instruction, even if they make no effort to detect compression sequences for null constants.
It's still always possible to traverse through the sequence to find the original (null) reference.
Additionally, propagate the null/non-null flags from the reference node to all of the integer-typed nodes in the sequence rather than only the truncation (`l2i`), and also flag the long value immediately prior to truncation as having zero in its high half. These properties hold, so the flags might as well be set.

Avoid shifting null constants in compression sequences

---

runtime/compiler/control/J9Options.cpp

- https://github.com/eclipse-openj9/openj9/pull/17222 seems to cause a slowdown
- disable for further performance investigation

Disable inlining of intrinsics

---

jcl/src/java.base/share/classes/java/lang/PinnedThreadPrinter.java
jcl/src/java.base/share/classes/java/lang/StackWalker.java
runtime/jcl/common/java_lang_StackWalker.cpp
runtime/oti/vmconstantpool.xml

- New internal StackWalker flag J9_GET_MONITORS to include monitor entry info
into StackFramesImpl structure.
- New protected getMonitors() API to retrieve monitor entry info.
If the new StackWalker flag is set, the monitor info will be fetched before
parsing each stackframe and monitors will be added to the matching
StackFrameImpl structure's monitors array based on stack depth.
This will be used by PinnedThreadPrinter class to output the stack's acquired
monitors' state.
Fix: #17860 

Add support for jdk.tracePinnedThreads system property

---

test/functional/cmdLineTests/criu/criu.xml
test/functional/cmdLineTests/criu/criu_jitPostRestore.xml
test/functional/cmdLineTests/criu/criu_jitserverAcrossCheckpoint.xml
test/functional/cmdLineTests/criu/criu_jitserverPostRestore.xml
test/functional/cmdLineTests/criu/criu_keepCheckpoint.xml
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/criu_nonPortableJDK11Up.xml
test/functional/cmdLineTests/criu/criu_nonPortable_RAS.xml
test/functional/cmdLineTests/criu/criu_random.xml
test/functional/cmdLineTests/criu/criu_security.xml

CRIU tests add failure condition when a `javacore` is requested
CRIU tests fail if a `javacore` file is requested.
related 
* https://github.com/eclipse-openj9/openj9/pull/17859#issuecomment-1658366404

CRIU tests add failure condition when a javacore is requested

---

runtime/compiler/env/j9method.cpp

Fixes the issue mentioned in 17931.TR_ResolvedJ9Method::isCompilable() accesses some fields from JavaVM and it's not safe to use as is in out-of-process compilations.
As described in the issue https://github.com/eclipse-openj9/openj9/issues/17931, the deleted "doPrivileged" code is redundant since the base class method TR_ResolvedJ9MethodBase::isCompilable() already filters those methods out.
Closes: ##17931

isCompilable() fix for JITServer

---

runtime/compiler/aarch64/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/arm/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/p/codegen/J9AheadOfTimeCompile.cpp

https://github.com/eclipse-openj9/openj9/pull/17621 adjusted where the relo flags are set (not to be confused with the flags described by `RELOCATION_CROSS_PLATFORM_FLAGS_MASK`). The `TR_ASSERT_FATAL` in `TR_RelocationRecord::setReloFlags` was updated accordingly, but all the `TR_ASSERT`s sprinkled in the code that initializes the header of the binary relo record was missed.
This PR removes these `TR_ASSERT`s because in addition to be incorrect, they are also redundant; `TR_RelocationRecord::setReloFlags` already has a `TR_ASSERT_FATAL`.
Fixes https://github.com/eclipse-openj9/openj9/issues/17950

Remove incorrect TR_ASSERTs related to the reloFlags

---

runtime/compiler/optimizer/IdiomRecognition.cpp
runtime/compiler/optimizer/IdiomRecognition.hpp
runtime/compiler/optimizer/IdiomTransformations.cpp

There are uses of `TR_ASSERT()` in idiom recognition that check for cases that are not necessarily impossible and that are handled conservatively in builds where `TR_ASSERT()` is not checked. Assertions are not a good way to detect and report these cases, since assertion failure is not likely to be due to a bug.
This commit removes a number of these assertions. Now the conservative logic will apply in all builds. When it does, a static debug counter will be incremented, and (when tracing idiom recognition) a message will be printed to the log.
Anyone who wants to look for transformations that have been prevented due to incomplete support for a particular case can use the new static debug counters.
Additionally, use `dumpOptDetails()` to trace when a transformer fails. In that case it's …

Remove unnecessary idiom recognition assertions

---

runtime/compiler/runtime/J9Runtime.hpp
runtime/compiler/runtime/RelocationRecord.cpp
runtime/compiler/runtime/RelocationRecord.hpp

The `_flags` field of the `TR_RelocationRecordBinaryTemplate` struct is 16 bits wide. This was to ensure that the relocation infrastructure could store more than 4 bits of Relocation Flags (the other 4 bits are reserved for the Cross Platform Flags).
The code in `TR_RelocationRecord::setReloFlags` did some validation to ensure that the bits did not overlap; however, it did so using a uint8_t which could lose some bits due to a shift. This PR fixes this by ensuring a `uint16_t` is used.
This PR also changes how the flags are set; existing flags in the raw relocation record are now preserved.

Ensure flags stored to raw relo record is 16 bits

---

runtime/bcutil/cfreader.c
runtime/nls/cfre/cfrerr.nls
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeGenerator.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeTests.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaUtils.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeGenerator.java

- class verification check to make sure ImplicitCreation attribute is in a non-abstract value class
- tests for ImplicitCreation class verification
Related to: https://github.com/eclipse-openj9/openj9/issues/17234

ImplicitCreation atribute tests, value class flag verification

---

runtime/bcutil/ROMClassBuilder.cpp
runtime/bcutil/j9bcu.tdf

Since Java 1.5 this flag has been part of modifiers
Fixes: https://github.com/eclipse-openj9/openj9/issues/17785

Remove synthetic flag from extraModifiers

---

runtime/compiler/runtime/ClassUnloadAssumption.cpp

It is possible that an entry of `TR_UnloadedClassPicSite` (kind = `RuntimeAssumptionOnClassUnload`) remains if the `TR_UnloadedClassPicSite` references a J9Method in the pre-prolog. The J9Method in the pre-prolog is for the helper to know what method to execute for a revert to the interpreter. This address needs to be patched on a redefinition.
Fixes #17734

Update the assert to allow TR_UnloadedClassPicSite

---

test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeGenerator.java

"If a class other than java/lang/Object has neither its ACC_IDENTITY flag nor its ACC_VALUE flag set, then its ACC_ABSTRACT flag must be set." (https://cr.openjdk.org/~dlsmith/jep401/jep401-20230404/specs/value-objects-jvms.html#jvms-4.7.31)
This isn't currently enforced in openj9. I also removed ACC_PUBLIC flags that are not needed.

Valhalla test classes must either have ACC_VALUE or ACC_IDENTITY flag

---

NOTICES.md
buildenv/jenkins/variables/defaults.yml
doc/build-instructions/Build_Instructions_V11.md
doc/build-instructions/Build_Instructions_V17.md
doc/build-instructions/Build_Instructions_V20.md
doc/build-instructions/Build_Instructions_V8.md

Update the notices file with the new license for v3. Updated the build instructions.
https://www.openssl.org/source/apache-license-2.0.txt

Update to openssl 3.0.10

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

JITServer communicates with clients and retrieves certain values, like `objectAlignmentInBytes`, to maintain consistent values for each client. In this context, these per-client values can't be treated as constants, and any `static` keywords on variables should be removed if those values are being assigned.

AArch64: Remove inappropriate static keywords from variables

---

runtime/bcutil/ClassFileOracle.cpp
runtime/nls/cfre/cfrerr.nls
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeGenerator.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeTests.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaUtils.java

- throw error in vm if there is a NullRestricted attribute in primitive or array field
- verification test for multiple NullRestricted attributes in a field
- verification test for NullRestricted attribute in primitive and array fields
Related to https://github.com/eclipse-openj9/openj9/issues/17340

NullRestricted attribute cant be in primitive or array field

---

runtime/shared_common/j9shr.tdf

As mentioned in https://github.com/eclipse-openj9/openj9/pull/17945#discussion_r1305637158, the template parameter here should be `%zd` and not `%d`.
Attn @mpirvu @keithc-ca.

Fix JITServer AOT SCC layer trace template

---

runtime/jvmti/jvmtiExtensionMechanism.c
runtime/jvmti/jvmtiHelpers.c
runtime/jvmti/jvmtiStackFrame.c
runtime/jvmti/jvmti_internal.h

Java methods tagged with the JvmtiMountTransition annotation are
involved in transitioning between carrier to virtual threads, and
vice-versa.
These methods are not part of the thread's scope. So, they should be
skipped during introspection by all the relevant JVMTI functions.
This commit covers the remaining JVMTI functions which need to skip
methods tagged with the JvmtiMountTransition annotation.
Fixes: #17520

Skip methods with JvmtiMountTransition annotation

---

NOTICES.md

Added the ones I can find references to in OpenJ9 test code. There is a list at https://github.com/eclipse-openj9/openj9/blob/master/test/docs/DependentLibs.md
See suggestions at
https://www.eclipse.org/projects/tools/documentation.php?id=technology.openj9#notice
Also https://github.com/adoptium/TKG/blob/master/scripts/getDependencies.pl which contains items used outside of the OpenJ9 project, and https://openj9-jenkins.osuosl.org/job/systemtest.getDependency

Add third party content used for testing to NOTICES.md

---

runtime/oti/j9javaaccessflags.h
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/resolvesupport.cpp
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeGenerator.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeTests.java

- putstatic and putfield throw NullPointerException if a field is being set to null that has a NullRestricted attribute
- tests for putfield and putstatic

NullRestricted: putstatic and putfield throw NPE on null assignment

---

buildenv/jenkins/common/variables-functions.groovy
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy

It del func in variable-functions and make it through CUSTOM_DESCRIPTION

resolve hardcoded github.com in variable-functions

---

runtime/compiler/control/JITClientCompilationThread.cpp

Remotely-compiled AOT methods will now be stored in the local SCC by default if the JITServer AOT cache is not being used. This avoids failures in certain tests that implicitly assume that such methods will be stored in the local SCC.

Expand default local storage of remote AOT methods

---

runtime/gc_base/IndexableObjectAllocationModel.cpp
runtime/gc_glue_java/ArrayletObjectModel.cpp
runtime/gc_glue_java/ArrayletObjectModel.hpp
runtime/gc_include/ObjectAllocationAPI.hpp
runtime/gc_structs/FlattenedContiguousArrayIterator.hpp

J9ARRAYCLASS_GET_STRIDE() returns the element size, and could return 0 when flattened is enabled and the class is empty.
We should fix this somehow. Currently we hard set the stride to 1 inside division when it is 0.

SIGFPE for flattened array of value type that has no fields

---

runtime/jcl/common/java_lang_ref_Finalizer.c
runtime/sunvmi/sunvmi.c

The JCL code expects that when System.GC() is called a GC occurs and finalizable objects are finalized. Historically, J9 has never provided this guarantee. We have often had to modify tests to ensure a GC is triggered at the appropriate time. Increasingly, we are finding that more and more tests rely on this behaviour, and most importantly, core JCL code now relies on this behaviour. This PR ensures that a call to System.gc() triggers a GC and runs finalization.

Add stronger guarantees to System.gc()

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/il/J9MethodSymbol.cpp
runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp

java.lang.Math.multiplyHigh has been an intrinsic candidate in the Java class library since JDK17. There is a single opcode which implements the functionality of multiplyHigh. This provides an opportunity to simplify calls to multiplyHigh much like other Math methods (abs, min, max, etc).
This commit adds the following:
+ The recognition of java.lang.Math.multiplyHigh as a recognized method.
+ The replacement of calls to java.lang.Math.multiplyHigh with a single lmulh node as part of RecognizedCallTransformer

Recognize @IntrinsicCandidate java.lang.Math.multiplyHigh

---

runtime/compiler/control/JITClientCompilationThread.cpp

If the option -XX:+JITServerAOTCacheDelayMethodRelocation is in effect, then we delay the relocation of received AOT methods by default. When this is the case, we should also store these methods in the local SCC so that they will be available to be relocated later.

Store JITServer AOT methods if they are delayed

---

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
runtime/oti/ContinuationHelpers.hpp
runtime/oti/vmconstantpool.xml
runtime/vm/ContinuationHelpers.cpp

When a virtual thread is mounted, the corresponding carrier thread
unmounts and no longer runs. Similarly, when a virtual thread is
unmounted, the corresponding carrier thread mounts and resumes its
operations.
When a virtual thread is mounted, the `scopedValueCache` for the carrier
thread is stored in the `Continuation` object's `scopedValueCache` field.
When a virtual thread is unmounted, the carrier thread's
`scopedValueCache`, which is stored in the `Continuation` object's
`scopedValueCache` field, is swapped with `J9VMThread->scopedValueCache`.
This assures a one to one mapping between a `java.lang.Thread` and
`scopedValueCache`. The live thread's `scopedValueCache` is always kept in
`J9VMThread->scopedValueCache` whereas the unmounted thread's
`scopedValueCache` is stored in the …

Store J9VMThread->scopedValueCache in the Continuation object

---

debugtools/DDR_VM/src/com/ibm/j9ddr/CompatibilityConstants29.dat
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/J9BCUtil.java

- include internal modifiers for fields in rom class dump
- fix incorrectly ordered arguments of dumpModifers method
- print NullRestricted field modifier in ddr rom class dump

ddr support for Valhalla NullRestricted attribute

---

runtime/j9vm/javanextvmi.cpp
runtime/redirector/forwarders.m4

The stub had the wrong signature: this corrects it and provides an implementation.
Fixes: #17996.

Implement JVM_LoadZipLibrary()

---

runtime/compiler/runtime/RelocationRecord.cpp

The issue is `TR_RelocationRecordSymbolFromManager::activatePointer` creates `TR_UnloadedClassPicSite` for a J9Method in the pre-prologue of the current method body. The class of the J9Method is the same as the class of the current method body. In this case, the class unload assumption is not needed because once the class is unloaded, no code will ever reach the J9Method in the pre-prologue.
Fixes: #17734

Do not create class unload PIC site assumption if not required

---

runtime/bcutil/ClassFileWriter.cpp
runtime/cfdumper/main.c

I compiled this using https://github.com/openjdk/valhalla/tree/lw5
```
class Test {
static FieldTest! ft;
}
value class FieldTest {
public implicit FieldTest();
}
```
```
$~/openj9builds/openj9-openjdk-jdk.valuetypes/build/macosx-aarch64-server-release/vm/runtime/cfdump -t Test.class
Wrote 267 bytes to output file Test.j9class
$ ~/openj9builds/openj9-openjdk-jdk.valuetypes/build/macosx-aarch64-server-release/vm/runtime/cfdump Test.j9class 
class Test extends java.lang.Object
{
static FieldTest! ft;
void <init>();
}
```
```
~/openj9builds/openj9-openjdk-jdk.valuetypes/build/macosx-aarch64-server-release/vm/runtime/cfdump -d Test.class
…
Fields (1):
Name: 9 -> ft
Signature: 10 -> LFieldTest;
Access Flags: 0x8 ( 
access: default …
```

NullRestricted Valhalla attribute cfdump support

---

test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeArrayTests.java

This change defines some simple unit tests that create arrays of value classes and null restricted value classes, where the classes have no fields.  The objective is to ensure that allocation, assignment and comparison of flattened arrays whose elements are of length zero does not result in unexpected failures.
related to #14027

Define unit tests involving arrays of empty value types

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
buildenv/jenkins/variables/defaults.yml

* remove jdk20 from list of current releases
* add alinux as another alias for aarch64_linux (matches intent of https://github.com/eclipse-openj9/openj9/pull/18055#issuecomment-1703115972)
* fix typo
* indent consistently

Update jenkins pipeline

---

runtime/compiler/x/env/J9CPU.cpp

AVX512-CD is required for leading zero bit count
Related: eclipse/omr#7103

x86: Enable AVX512-CD

---

runtime/compiler/optimizer/IdiomRecognition.cpp
runtime/compiler/optimizer/IdiomTransformations.cpp

`arraycmp` opcode with `arrayCmpLen` flag set is replaced with the opcode `arraycmplen` in https://github.com/eclipse/omr/pull/6983.

Use arraycmplen opcode

---

runtime/vm/jvminit.c

JVM init path: `J9_CreateJavaVM`.
JVM exit paths: `protectedDestroyJavaVM` and `exitJavaVM`.
A segfault or other side-effects can happen if the JVM init and
exit paths execute concurrently.
The exit path can be taken if a shutdown signal is raised and the
shutdown handler is invoked. JVM shutdown signals are `SIGINT`, `SIGTERM`
and `SIGHUP`.
Preventing invocation of the exit path from the shutdown signal handler
until the JVM initialization completes resolves the above side-effects.
Related:
- #17101
- #17438

Don't invoke shutdown signal handler until JVM init completes

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

Guard a call to VMwrtbarWithoutStoreEvaluator (which is only compatible with non-realtime GC) to ensure it is not called under realtime GC.
Issue: #15440

Guard a call to VMwrtbarWithoutStoreEvaluator

---

test/functional/VM_Test/src/j9vm/test/jni/CriticalRegionTest.java

Fixes https://github.com/eclipse-openj9/openj9/issues/18077
5 x 6x grinder https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/2873/ - passed

In CriticalRegionTest System.gc once, testAcquireAndGC timeout 10sec

---

test/functional/cmdLineTests/criu/criuJitServerScript.sh
test/functional/cmdLineTests/criu/criu_jitserverPostRestore.xml
test/functional/cmdLineTests/criu/jitserversslconfig.sh

Add tests to the existing `criu` and `jitserver` tests under `cmdLineTest` for checking/verifying SSL connections with JITServer.
Closes: ##17967

Add criu tests to verify JITServer with SSL

---

runtime/compiler/p/codegen/CallSnippet.cpp
runtime/compiler/p/codegen/PPCRecompilation.cpp

This commit updates:
1. `TR::PPCCallSnippet::generateVIThunk` to use the right front end query. 
2. To use `GetExistingMethodInfo` instead of using startPC in `TR_PPCRecompilation::getExistingMethodInfo`
Related PRs for AArch64/z:
1. Use front end query when allocating VI Thunks
https://github.com/eclipse-openj9/openj9/pull/17904 (AArch64)
https://github.com/eclipse-openj9/openj9/pull/6910 (z)
2. Get existing method info from the J9Method instead of startPC
https://github.com/eclipse-openj9/openj9/pull/17915 (AArch64)
https://github.com/eclipse-openj9/openj9/pull/7044 (z)

Added the usage of right front end queries and getExistingJittedBodyInfo on Power

---

runtime/gc_modron_startup/mmparseXgc.cpp

Arraylet Double Mapping feature is not supported for all platforms. Current behaviour is return "unsupported option error". This prevents to use the same Java command line across platforms.
New behaviour is to ignore -Xgc:enableArrayletDoubleMapping and -Xgc:disbleArrayletDoubleMapping silently on platforms where this feature is not supported.

Ignore -Xgc:enableArrayletDoubleMapping silently

---

runtime/gc_modron_startup/mmparseXgc.cpp

Arraylet Double Mapping feature is not supported for all platforms. Current behaviour is return "unsupported option error". This prevents to use the same Java command line across platforms.
New behaviour is to ignore -Xgc:enableArrayletDoubleMapping and -Xgc:disbleArrayletDoubleMapping silently on platforms where this feature is not supported.

(v0.41.0-release) Ignore -Xgc:enableArrayletDoubleMapping silently

---

buildenv/jenkins/common/variables-functions.groovy

Console log Extra options specified as build parameters
Change behaviour to append extra options after spec options

Fix set_build_extra_options() API for wrapper job

---

buildenv/jenkins/common/variables-functions.groovy

Set default VARIABLE_FILE parameter

---

runtime/compiler/ilgen/Walker.cpp
test/functional/Valhalla/playlist.xml
test/functional/Valhalla/src/org/openj9/test/lworld/NullRestrictedTypeOptTests.java

Add NullCHK when storing value into NullRestricted field.
This applies to `putfield`, `putstatic`, and `withfield`.
Related: #17340

Add NullCHK when storing value into NullRestricted field

---

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
test/functional/Java21andUp/src/org/openj9/test/jep425/VirtualThreadTests.java

Add @Hidden annotation to Continuation enter/yield methods

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

Move a call to decReferenceCount out of an else block because a case existed where the `indexChild` of the `BNDCHKwithSpineCHKEvaluator` node wasn't having its reference count decremented
Closes: #15436

Move decReferenceCount out of else block

---

runtime/ddr/dummy_headers/string.h

Add DDR dummy header size_t strlen(const char *str)
Fix DDR compilation error:
```
"../oti/VMHelpers.hpp", error: identifier "strlen" is undefined.
```
[Internal J9 Java [Linux Hammer Compressed Pointers] 80 Create source.zip failure](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=68402960)
related to 
* https://github.com/eclipse-openj9/openj9/pull/17618
FYI @tajila 

Add DDR dummy header size_t strlen(const char *str)

---

runtime/vm/BytecodeInterpreter.hpp

The existing code fails to remove the generic special frame if triggering the frame pop hook doesnt require us to run the async check.

Fix sequence after frame pop query

---

runtime/jvmti/jvmtiStackFrame.c

Without the `J9_STACKWALK_ITERATE_FRAMES` flag, the `genericFrameIterator`
is not invoked. If there are methods with the `JvmtiMountTransition`
annotation on the stack, they won't be ignored because the
`genericFrameIterator` (`frameWalkFunction`) does not get invoked.
Related: #17871

Set the ITERATE_FRAMES flag to invoke the frameWalkFunction

---

buildenv/jenkins/variables/defaults.yml

alinux can't move to 11.2 due to https://github.com/eclipse-openj9/openj9/issues/15390
For testing see the following. Ignore the linux builds on jdk8,11. This build was done with a different commit that modified all versions.
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/431/
jdk11 will move once we have a new OpenJDK level that compiles, expected in a future 11.0.21 update.
jdk8 will move once Adoptium provides a xlinux centos6 container with the required gcc version, although we can consider moving other platforms earlier. They all work.

Compile Windows jdk8+ with VS2022, move jdk17 x,p,zlinux to gcc 11.2

---

runtime/vm/BytecodeInterpreter.hpp
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeGenerator.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeTests.java

- withfield NPE check for NullRestricted attribute
- rename Valhalla attribute bytecode tests for clarity

NullRestricted field throws NPE on null assignment in withfield

---

jcl/src/java.base/share/classes/java/lang/PinnedThreadPrinter.java
jcl/src/java.base/share/classes/java/lang/StackWalker.java
runtime/j9vm/exports.cmake
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/java11vmi.c
runtime/j9vm/javanextvmi.cpp
runtime/j9vm/module.xml
runtime/jcl/common/java_lang_StackWalker.cpp
runtime/redirector/forwarders.m4
runtime/redirector/module.xml

* add `StackWalker.Option.DROP_METHOD_INFO`
* add stub for `JVM_ExpandStackFrameInfo()`
* update signatures of `JVM_CallStackWalk()` and `JVM_MoreStackWalk()`
Various general improvements to `StackWalker`:
* make all fields `final`
* don't retain `Set<Option>` (all needed information is in `flags`)
* add `newInstanceWithMonitors()` for use by `PinnedThreadPrinter`
Fixes https://github.com/eclipse-openj9/openj9/issues/18100.

StackWalker updates for Java 22

---

runtime/gc/gctable.c
runtime/gc_base/gc_internal.h
runtime/gc_base/modronapi.cpp
runtime/gc_base/modronapi.hpp
runtime/oti/j9nonbuilder.h

Inter-module GC API for cumulative thread allocation stats. Just a wrapper for an existing API in OMR GC.

Cumulative thread allocaton stats

---

test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestOperatingSystemMXBean.java

null is a valid value when the hardware model can't be retrieved.

Fix TestOperatingSystemMXBean HardwareModel test

---

test/functional/Valhalla/playlist.xml
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeSystemArraycopyTests.java
test/functional/Valhalla/testng.xml

Add tests for Value Type `System.arraycopy` transformation

Add tests for Value Type System.arraycopy transformation

---

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
jcl/src/java.base/share/classes/java/lang/StackWalker.java
runtime/jcl/common/java_lang_StackWalker.cpp
runtime/oti/vmconstantpool.xml

Fixes: https://github.com/eclipse-openj9/openj9/issues/18146.
* copy flags from StackWalker to StackFrameImpl objects
* thrown UnsupportedOperationException as appropriate
* skip collecting method details if DROP_METHOD_INFO was specified
Tidy up:
* use parentheses consistently
* use J9_ARE_ANY_BITS_SET for testing a single bit
* cast carefully

Implement StackWalker.Option.DROP_METHOD_INFO

---

runtime/jvmti/heapify.cpp

The current thread may release and reacquire VM access during the heapification process. Marking the current thread halted causes a hang in this case.
Related: #18134

Do not mark the current thread halted during heapification

---

runtime/oti/jvminit.h
runtime/vm/jvminit.c

Related to https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/664

Consume -XX:[+/-]UseZlibNX options in OpenJ9 builds

---

runtime/jvmti/jvmtiHelpers.c

If a virtual thread is mounted on a carrier thread, then the carrier
thread is considered implicitly parked.
We match the RI behaviour and pass `vthread/ThreadStateTest` with
these changes.
Related: #18054

Update getThreadState to handle unmounted carrier thread

---

buildenv/jenkins/variables/defaults.yml

Excluded the problematic test
https://github.com/adoptium/aqa-tests/pull/4780

Allow zlinux testing to run on rhel8

---

runtime/jcl/common/mgmtthread.c

If a virtual thread is mounted on a carrier thread, then `blocker` and
`blockerOwner` are the virtual thread, and the `vmstate` is `WAITING` for
the carrier thread. This behaviour matches the RI, and it also allows
us to pass the `virtual/CarrierThreadWaits` (JTreg test).
Related: #18051

Handle unmounted carrier thread in ThreadMXBeanImpl.getThreadInfo

---

runtime/nls/j9vm/j9vm.nls
runtime/oti/j9javaaccessflags.h
runtime/vm/ClassInitialization.cpp
runtime/vm/createramclass.cpp
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeGenerator.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeTests.java

- NullRestricted fields must be a value type with an ImplicitCreation attribute that has the ACC_DEFAULT flag set. For non-static fields this should be checked during class creation and for static fields during the preparation stage of linking.
- This pr also adds static NullRestricted fields to the flattenedClassCache to make the described failure possible. Changes to allow non-static NullRestricted fields to be flattened will come in a later pull request.
- Move ImplicitCreation flag declarations because flags are no longer part of extramodifiers, and correct default flag value

NullRestricted attribute field class checks

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Add missing default cases to switch statements which were causing "enumeration values not handled in switch" warnings on [`aarch64_mac` OpenJ9 builds](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/18194/). These additions (along with a few corresponding additions in [OMR](https://github.com/eclipse/omr/pull/7123)) fix the warnings without changing the behaviour of the code. This, of course, assumes that there are no switch cases that should be handled but aren't.
This PR contributes to (but does not close) #14859.

Add missing default cases to switch statements

---

runtime/oti/j9.h
runtime/vm/createramclass.cpp

Flatten non-static NullRestricted fields

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/codegen/CallSnippet.cpp
runtime/compiler/aarch64/codegen/CallSnippet.hpp
runtime/compiler/aarch64/runtime/PicBuilder.spp
runtime/compiler/runtime/Trampoline.cpp

This commit extends the existing interface call dispatching code of AArch64 codegen to exploit cached lastITable field in J9Class. `buildInterfaceCall` function is updated to generate The code for lastITable cache lookup after the code for checking the second PIC slot. Until the second slot is populated, lastITable cache lookup always fails to avoid filling PIC slots with infrequent call targets. See OpenJ9 #8390 for more details.
After the second slot is filled, the lastITable cache lookup is enabled by patching the b.al (branch always) instruction in the lookup code to b.ne (branch if not equal).
Recompilation code is also updated to properly handle the new instruction sequence generated by updated `buildInterfaceCall` function.
Resolves …

AArch64: Use lastITable cache for interface call dispatching

---

test/functional/cmdLineTests/forceLazySymbolResolution/playlist.xml
test/functional/cmdLineTests/jvmtitests/playlist.xml

https://github.com/eclipse-openj9/openj9/issues/10917
Enabling below test cases 
- cmdLineTester_forceLazySymbolResolution
[Grinder JDK17 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/35100/console)
- cmdLineTester_jvmtitests_hcr_OSRG_nongold
[Grinder JDK17 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/35098/console)
[Grinder JDK17 x86-64_mac](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/35099/console)
[Grinder JDK17 x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/35097/console)
@llxia 
Signed-off-by: Kapil Powar [kapil.powar@in.ibm.com](mailto:kapil.powar@in.ibm.com)

Enable disabled tests

---

runtime/oti/jvminit.h
runtime/vm/jvminit.c

Related to https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/664
Cherry pick https://github.com/eclipse-openj9/openj9/pull/18164 for 0.41

(0.41) Consume -XX:[+/-]UseZlibNX options in OpenJ9 builds

---

runtime/bcutil/bcutil.c
runtime/bcverify/bcverify.c
runtime/compiler/control/DLLMain.cpp
runtime/gc_modron_startup/mminit.cpp
runtime/jcl/common/vm_scar.c
runtime/oti/j9nonbuilder.h
runtime/oti/verbose_api.h
runtime/oti/vm_api.h
runtime/verbose/verbose.c
runtime/vm/dllsup.c
runtime/vm/intfunc.c
runtime/vm/jvminit.c

Continue the effort to fix AIX warnings about converting string literals to mutable char pointers by adding a 'const' qualifier to J9VMDllLoadInfo::fatalErrorStr.
This PR contributes to (but does not close) #14859.

Make J9VMDllLoadInfo::fatalErrorStr 'const'

---

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp

When we transform a StringUTF16.toBytes() into a newarray and a call to String.decompressedArrayCopy(), we neglected to add an allocationFence. This change will introduce an allocationFence after the decompressedArrayCopy() call to ensure that all threads see the new contents of memory on weak memory coherency machines like POWER and AArch64.

Fix a missing allocationFence in process_java_lang_StringUTF16_toBytes()

---

runtime/j9vm/java11vmi.c
runtime/redirector/forwarders.m4

See
* [8316456: StackWalker may skip Continuation::yield0 frame mistakenly](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/8b4c6af1080ba01c4e35ed0ebc1e6d74bfd47056)

Adjust signature of JVM_MoreStackWalk() for jdk22

---

runtime/j9vm/java11vmi.c

Backport of #18185.
Currently, in comparison to the RI, OpenJ9 shows a different output for
-XshowSettings:system outside a container because our
JVM_IsUseContainerSupport implementation differs from the RI.
This PR matches the latest RI behaviour for JVM_IsUseContainerSupport.
The RI returns TRUE from JVM_IsUseContainerSupport IFF
-XX:+UseContainerSupport is specified. This option is enabled by
default.
Currently, we return TRUE from JVM_IsUseContainerSupport if
-XX:+UseContainerSupport is specified && we are inside a container.
The return value of JVM_IsUseContainerSupport determines the output
of -XshowSettings:system.
If JVM_IsUseContainerSupport returns FALSE, -XshowSettings:system has
the below output:
Operating System Metrics:
No metrics available for this platform
If …

(0.41) Update JVM_IsUseContainerSupport

---

buildenv/jenkins/common/build.groovy

None were collected in https://openj9-jenkins.osuosl.org/job/Build_JDK21_aarch64_linux_gcc11_Personal/1; this should fix that.

Collect debuginfo files to help diagnose omr_ddrgen failures with gcc11

---

jcl/jpp_configuration.xml

Eclipse 2023-09 supports the Java 21 execution environment with a [patch available in the marketplace](https://marketplace.eclipse.org/content/java-21-support-eclipse-2023-09-429).

Update jdkcompliance for JAVA21 and JAVA22

---

jcl/src/java.base/share/classes/java/lang/Access.java

`CarrierThreadLocal` is already imported on line 70.

Remove redundant import

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

Instructions with 32-bit immediate values may
not be generated using the 64-bit codegen API.
Issue: #18002

x86: Fix incorrect use of codegen API

---

test/functional/cmdLineTests/dumpromtests/playlist.xml

https://github.com/eclipse-openj9/openj9/issues/10917
Enabling below test case `cmdLineTester_dumpromclasstests`
Grinder test links
[aix_ppc-64 JDK8](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/35217/)
[aix_ppc-64 JDK11](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/35211/)
[aix_ppc-64 JDK17](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/35215/)
@llxia
Signed-off-by: Kapil Powar [kapil.powar@in.ibm.com](mailto:kapil.powar@in.ibm.com)

re-enable cmdLineTester_dumpromclasstests

---

runtime/compiler/env/VMJ9.cpp
runtime/compiler/z/env/J9CPU.cpp

The `OMR_FEATURE_S390_TE` flag will be removed by https://github.com/eclipse/omr/pull/7112. This commit removes `OMR_FEATURE_S390_TE` and uses the new constrained and non-constrained transactional execution facility flags.
Relies on https://github.com/eclipse/omr/pull/7112

Z: Use new transactional execution facility flags

---

runtime/vm/segment.c

When a new code cache needs to be allocated, first the VM allocates a memory segment and then the JIT allocates a TR::CodeCache structure. Finally, the JIT writes a pointer to the TR::CodeCache structure at the beginning of the memory segment.
After the code cache segment has been added to the corresponding VM segment list, but before the JIT had the chance to write the TR::CodeCache pointer, a Java application thread could inquire about memory consumption stats (with MXBeans) which could lead to the VM reading a random value for the TR::CodeCache pointer and crash
when dereferencing the bad pointer.
The solution is to write a NULL pointer at the begining of the code cache segment as soon as that segment is allocated. Thus, a third party could see either NULL (which is checked against by …

Fix code cache segment race condition

---

test/functional/cmdLineTests/loadLibraryTest/build.xml
test/functional/cmdLineTests/loadLibraryTest/loadLibraryTestAIX.xml
test/functional/cmdLineTests/loadLibraryTest/playlist.xml
test/functional/cmdLineTests/loadLibraryTest/src/org/openj9/test/loadLibrary/TestLoadLibraryAIX.java

Add `AIX` `sun.font.FontManagerNativeLibrary.load()` test
related 
* https://github.com/eclipse-openj9/openj9/issues/17759
The `UnsatisfiedLinkError` was fixed initially (via an extension repo JCL patch), however the change was overridden by OpenJDK updates, and the error in `extended.openjdk` was marked as infra issues.
This `sanity.functional` test can detect such regression earlier and is easier for triaging. 

Add AIX sun.font.FontManagerNativeLibrary.load() test

---

runtime/jit_vm/cthelpers.cpp
runtime/oti/j9protos.h

This is required for implementing the JIT inlining behaviour expected for the methods annotated by `@ChangesCurrentThread`.
Issue: #17519

Add CT helper to check for ChangesCurrentThread annotation

---

runtime/vm/segment.c

`allocateVirtualMemorySegmentInListInternal` has been changed to write NULL into the code cache segment in #18212. The change does not include `omrthread_jit_write_protect_disable` and `omrthread_jit_write_protect_enable` calls before and after writing to the memory, which results in the crash on Apple Silicon Mac.
This commit inserts `omrthread_jit_write_protect_disable` and `omrthread_jit_write_protect_enable` appropriately.

Enable write permission before writing into CodeCache segment

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/gc_base/RootScanner.cpp
runtime/gc_glue_java/ConcurrentMarkingDelegate.cpp
runtime/gc_structs/VMThreadStackSlotIterator.cpp
runtime/gc_structs/VMThreadStackSlotIterator.hpp
runtime/jcl/common/getstacktrace.c
runtime/jvmti/jvmtiHelpers.c
runtime/oti/ContinuationHelpers.hpp
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/ContinuationHelpers.cpp

`threadObject` is required in `jvmtiFollowReferences` to get thread
specific details such as the `TID`.
So, `threadObject` needs to be passed via `walkContinuationStackFrames`
so that it is accessible in `jvmtiFollowReferences`.
`walkContinuationStackFrames` is invoked either for a
**[1]** `J9VMContinuation` in the `Continuation` object or
**[2]** `J9VMThread->currentContinuation`.
In **[1]**, if the `Continuation` is fully mounted, then it stores the state
of the `CarrierThread`. Otherwise, it stores the state of the
`VirtualThread`.
In **[2]**, if `J9VMThread->currentContinuation` is not NULL, then it stores
the state of the `CarrierThread` because the `VirtualThread` is mounted on
the `J9VMThread`. The `CarrierThread` is retrieved from
`J9VMThread->carrierThreadObject`.
We have …

Pass threadObject to walkContinuationStackFrames

---

runtime/compiler/optimizer/EscapeAnalysisTools.cpp

The calls to `TR_EscapeAnalysisTools::processSymbolReferences` load references to symRefs that are live in order to create fake escapes for those symRefs at that point.  Determining whether a symRef is live relies on a `TR_BitVector` that lists the symRefs that are dead at that point in the IL.  For autos, that `TR_BitVector` was being retrieved by calling `TR_OSRMethodData::getLiveRangeInfo()`, but for pending push symRefs, `TR_OSRMethodData::getPendingPushLivenessInfo()` was being called.  When `OSRDefAnalysis` builds the vector of dead symRefs for both autos and pending pushes, it stores them in the `LiveRangeInfo` of the `TR_OSRMethodData`; the `PendingPushLivenessInfo` actually contains information about which pending push symRefs are live at particular points, not those that are …

Use getLiveRangeInfo to find pending push symRefs that are dead

---

runtime/jit_vm/cthelpers.cpp

Noticed a new occurrence of the pattern in #18222: The return type of `methodContainsRuntimeAnnotation()` is `BOOLEAN` so no comparison is needed to produce the desired return value.

Remove redundant comparisons with FALSE

---

runtime/bcutil/j9bcu.tdf
runtime/gc_base/ClassLoaderManager.cpp
runtime/gc_glue_java/MetronomeDelegate.cpp
runtime/jvmti/jvmtiClass.c
runtime/oti/j9nonbuilder.h
runtime/vm/VMAccess.cpp

Work by @jdmpapin with a couple of fixes from me.
Fixes: #18076

Fix crash in prepareToFixMemberNames

---

test/functional/cmdLineTests/criu/criu_jitserverPostRestore.xml

Recently added CRIU tests are failing in some cases because of the `required` condition, which will never succeed if we don't have a vlog because of cases like when CRIU can't acquire the original thread IDs. In such cases the output with have something similar to:
```
[OUT] pie: 3450382: Error (criu/pie/restorer.c:1833): Unable to create a thread: 3450384
[OUT] pie: 3450384: Error (criu/pie/restorer.c:598): Thread pid mismatch 3450384/3450383
[OUT] pie: 3450384: Error (criu/pie/restorer.c:651): Restorer abnormal termination for 3450382
[OUT] Error (criu/cr-restore.c:2536): Restoring FAILED.
[OUT] Error (criu/cr-restore.c:1494): 3450382 exited, status=1
```
The tests conditions needs to be altered to adapt to this expected scenario and silently succeed in such cases.
Fixes: …

Fix Criu test failures for JITServer SSL Tests

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/runtime/IProfiler.cpp

Two new -Xjit options are introduced which can be used to control the number of buckets in the two hash tables used by IProfiler:
-Xjit:iprofilerBcHashTableSize=
-Xjit:iprofilerMethodHashTableSize=
Note that these hash tables are not dynamically resizeable. This commit does not change the default values for these two hash tables.

Add options for sizing the IProfiler hash tables

---

jcl/src/java.base/share/classes/openj9/internal/criu/InternalCRIUSupport.java
runtime/criusupport/criusupport.cpp
runtime/jcl/common/criu.cpp
runtime/jcl/exports.cmake
runtime/jcl/uma/criu_exports.xml
runtime/oti/j9nonbuilder.h
runtime/oti/jclprots.h
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/TimeChangeTest.java

CRIU adds `InternalCRIUSupport.getLastRestoreTime()`
Retrieve the time when the last restore occurred. In the case of multiple restores the previous times are overwritten.
The times returned are in milliseconds since the start of the epoch, `-1` if restore has not occurred;
Added a test `testGetLastRestoreTime()`.
closes https://github.com/eclipse-openj9/openj9/issues/18105

CRIU adds InternalCRIUSupport.getLastRestoreTime()

---

runtime/gc_base/IndexableObjectAllocationModel.hpp
runtime/gc_glue_java/ArrayletObjectModel.cpp
runtime/gc_glue_java/ArrayletObjectModel.hpp
runtime/gc_glue_java/ObjectModelDelegate.hpp

0-length arrays have Discontiguous layout.
Currently detection of 0-length arrays based on dataSizeInBytes. There is not good enough for 0-stride arrays obviously (have dataSizeInBytes equal 0). All 0-stride arrays should be treated as Contiguous with exception of 0-length 0-stride should be Discontiguous. Passing of numberOfElements helps to solve this problem, dataSizeInBytes is not required to be passed any more.

Add numberOfElements parameter to getArrayletLayout()

---

jcl/src/java.base/share/classes/java/lang/invoke/MethodType.java
jcl/src/java.base/share/classes/java/lang/invoke/MethodTypeHelper.java

MethodHandleResolver.resolveInvokeDynamic (linkage) relies upon
MethodType.fromMethodDescriptorString to derive the MethodType from
the method descriptor string.
Enabling OJDK's MethodType.fromMethodDescriptorString in OpenJ9 JDK11
causes an AccessControlException, which makes it unsuitable for usage
during linkage.
resolveInvokeDynamic (linkage) can employ its own approach to derive
the MethodType from the method descriptor string.
To resolve the AccessControlException, a helper method is derived from
OJ9's MethodType.fromMethodDescriptorString, and it is utilized in
MethodHandleResolver.
The helper also enables a Map based cache per ClassLoader in both
implementations. Currently, the cache is only available in OJ9 MHs.
Related: #14555

[JDK11] Fix AccessControlException in resolveInvokeDynamic

---

runtime/gc_base/IndexableObjectAllocationModel.hpp
runtime/gc_glue_java/ArrayletObjectModel.cpp
runtime/gc_glue_java/ArrayletObjectModel.hpp
runtime/gc_glue_java/ObjectModelDelegate.hpp

Reverts eclipse-openj9/openj9#18268

Revert "Add numberOfElements parameter to getArrayletLayout()"

---

jcl/src/java.base/share/classes/java/lang/invoke/MethodTypeHelper.java

This class is also used for Java 8, so the comment that says `@since Java 11` is misleading.
Also, organize imports, tidy up whitespace.

Remove misleading comment

---

runtime/jcl/common/thread.cpp
runtime/oti/vmconstantpool.xml

Walk the stack frames to look for the `runWith()` method and get
its first argument, which should be an instance of
`java.lang.ScopedValue$Snapshot`.
Closes: #16677
Closes: #17402
Co-authored-by: Gengchen Tuo <gengchen.tuo@ibm.com>

Implement Thread.findScopedValueBindings()

---

buildenv/jenkins/common/build.groovy
buildenv/jenkins/common/variables-functions.groovy
buildenv/jenkins/variables/defaults.yml

The internal Artifactory server is forcing
the use a buildName prefix. This adds the option
to have a buildName prefix. However, we don't need
this at the OpenJ9 Jenkins farm so defaults.yml
sets the option to empty string.

Jenkins: Add option to prefix Artifactory build names

---

buildenv/jenkins/common/build.groovy

In the orignal change to add support for multiple
Artifactory servers, including servers behind a VPN
(https://github.com/eclipse-openj9/openj9/pull/8817), I made a note that buildInfo cannot be published
to VPN'd servers because while the artifacts are pushed
from the node, the buildInfo is pushed from the Controller
and therefore would fail to push if the Controller could
not see the Artifactory server behind the VPN. Since that
change, we've move the UNB VPN connection directly onto our
Controller node, this means we can now publish buildInfo to
the UNB server. This essentially means that as of today, we
can push buildInfo to all servers.
Note we still need the Artifactory vpn config info for other
parts of the code.
Also note that the if condition  written prior to
this change was …

Jenkins: Always publish buildInfo to Artifactory

---

test/functional/cmdLineTests/jitserver/jitserverArgumentTesting.xml
test/functional/cmdLineTests/jitserver/jitserverScript.sh
test/functional/cmdLineTests/jitserver/jitserversslconfig.sh

Add tests to the existing `jitserver` tests under `cmdLineTest` for checking/verifying SSL connections with JITServer. This is part 2 for the work done in #17985 .
Closes: ##17967

Add tests to verify JITServer with SSL

---

runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/ilgen/Walker.cpp

Update `genAconst_init` to check `NullRestricted` attribute
Related: #18170

Update genAconst_init to check NullRestricted attribute

---

runtime/gc_modron_startup/mminit.cpp
runtime/gc_modron_startup/mmparse.cpp
runtime/gc_modron_startup/mmparse.h

Give the user functionality to specify softmx inside an option file for CRIU restore.
Note here we separate gcParseReconfigurableArguments() into gcParseSovereignArguments() and gcParseReconfigurableCommandLine() to distinguish SovereignArguments from general command line options.
Signed-off-by: Frank Kang frank.kang@ibm.com

Parse softmx on CRIU restore side

---

runtime/compiler/optimizer/J9Optimizer.cpp

The default optimization strategy for the warm optimization level is `cheapWarmStrategyOpts`, while the older, `warmStrategyOpts` is not used (unless a specific option is given). This commit renames
warmStrategyOpts to oldWarmStrategyOpts
and
cheapWarmStrategyOpts to warmStrategyOpts

Renamed warm strategy opts

---

runtime/gc_base/ReferenceChainWalker.cpp

Base on comment for _trackVisibleStackFrameDepth "Should the stack walker be told to track the visible frame depth. Default false, should set to true when doing JVMTI walks that report stack slots", need to pass _trackVisibleStackFrameDepth for scanContinuationSlots().

Need to pass _trackVisibleStackFrameDepth for scanContinuationSlots()

---

runtime/compiler/optimizer/J9ValuePropagation.cpp
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeArrayTests.java

If the value being stored is NULL and the destination array component is null restricted in runtime, a NPE is expected
to throw. Therefore, when the array component type is not known to be identity type in compilation time, a NULLCHK
on store value is required.
Also add two test cases to test storing NULL into null restricted array, and update the class name in the tests to primitive class to reflect more accurately the type of the class.

Insert Null value check if array component type is unknown during compilation time

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/p/codegen/PPCPrivateLinkage.cpp
runtime/compiler/p/runtime/PPCHWProfiler.cpp
runtime/compiler/p/runtime/PPCRelocationTarget.cpp

Add missing default cases to switch statements which were causing "enumeration values not handled in switch" warnings on [ppc64_aix OpenJ9 builds](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/18289/). These additions (along with a few corresponding additions in [OMR](https://github.com/eclipse/omr/pull/7124)) fix the warnings without changing the behaviour of the code. This, of course, assumes that there are no switch cases that should be handled but aren't.
This PR also fixes the indentation of some of the switch statements to make them consistent with our code indentation standard.
This PR contributes to (but does not close) #14859.

Add default cases to PPC switch statements

---

runtime/nls/shrc/j9shr.nls

The control file open or lock failure is usually caused by incorrect permissions. Add a sentence on the permission issue in the error message.

Improve the error message on SCC control file open/lock failure

---

runtime/gc_base/IndexableObjectAllocationModel.hpp
runtime/gc_glue_java/ArrayletObjectModel.cpp
runtime/gc_glue_java/ArrayletObjectModel.hpp
runtime/gc_glue_java/ObjectModelDelegate.hpp

All 0-length arrays must have Discontiguous layout. Currently detection of 0-length arrays based on dataSizeInBytes. There is not good enough for 0-stride arrays obviously (have dataSizeInBytes equal 0). All 0-stride arrays should be treated as Contiguous with exception of 0-length 0-stride should be Discontiguous. In order to get proper result the code needs to be refactored.

Make 0-length 0-stride array discontiguous

---

runtime/codert_vm/arm64nathelp.m4
runtime/oti/arm64helpers.m4

This commit introduces SAVE_LR and RESTORE_LR macros and replaces some of SAVE_FPLR and RESTORE_FPLR.
FP (x29) register is handled by SAVE/RESTORE_PRESERVED_REGS and SAVE_RESTORE_C_NONVOLATILE_REGS.

AArch64: Stop saving/restoring x29 in unnecessary cases

---

runtime/vm/callin.cpp

Currently we set `thread.started = true` for system threads before running the constructor. This causes a race condition where the thread object may be made visible while it is being constructed potentially causing NPEs.

Set thread.started after running <init>

---

runtime/gc_modron_startup/mmparseXXgc.cpp

Because packetListSplitForced, cachelistsplit, and splitfreelistamount are moved from config to extbase, we need to change the usage here.
Signed off by: Frank.Kang@ibm.com

Change In Config Due To Moving Forced Flags to Extbase

---

runtime/bcutil/ClassFileWriter.hpp
runtime/bcutil/ROMClassBuilder.cpp
runtime/bcutil/ROMClassBuilder.hpp
runtime/oti/j9javaaccessflags.h
runtime/sunvmi/sunvmi.c
runtime/vm/NativeHelpers.cpp

This patch fixes both eclipse-openj9/openj9#14553 and eclipse-openj9/openj9#18245. When OJDK MHs are enabled for JDK11, the Hidden attribute for InjectedInvoker classes caused getStackClass and getCallerClass to return the incorrect class. The solution is to not iterate over InjectedInvoker classes despite them having the J9AccMethodFrameIteratorSkip modifier set due to the Hidden attribute.
Closes: eclipse-openj9/openj9#14553 eclipse-openj9/openj9#18245

Do not skip InjectedInvoker class in getCallerClass and getStackClass

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java
jcl/src/java.base/share/classes/java/lang/System.java

Checks can be done on the JCL side. Adds ClassLoader.loadZOSLibray().
Issue https://github.ibm.com/runtimes/openj9-openjdk-jdk17-zos/issues/843/

Don't check JNI absolute paths on z/OS, for loading datasets

---

runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/env/j9methodServer.hpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp

A method annotated with `@ChangesCurrentThread` must not be inlined unless its caller is also annotated with `@ChangesCurrentThread`. This annotation is only to be obeyed for JCL methods.
Issue: #17519

Support ChangesCurrentThread annotation in the JIT

---

jcl/src/java.base/share/classes/java/lang/Class.java

This method is used during initialization of a Null-Restricted array. This addition makes NullRestrictedTypeOptTests in the src_lw5 folder pass.
Related https://github.com/eclipse-openj9/openj9/issues/17340 and https://github.com/eclipse-openj9/openj9/pull/18275

Support for java.lang.Class.asNullRestrictedType

---

runtime/compiler/control/rossa.cpp

Pull request represents z/TPF OS platform specific updates to code cache strategy.
z/TPF has a second 64-bit heap region managed by the mmap function which allows Java processes to work better with traditional non-java applications. The update enables processes to detect whether the feature is enabled and to allocate the JIT code cache from it based on a heuristic meaningful only to z/TPF.  The fallback is to use the other pre-existing 64-bit heap reagion limited by a MAXXMMES system heap configuration unique to the z/TPF platform.

Update z/TPF code cache strategy

---

runtime/gc_verbose_old_events/VerboseEventGCStart.cpp

Last Responder thread can be NULL in the case of Safe Point Exclusive. Check pointer for NULL and leave thread name empty.

Allow Last Responder thread pointer to be NULL

---

test/functional/Valhalla/src_lw5/org/openj9/test/lworld/ValueTypeTests.java

Add refactored tests:
- testCreateArrayPoint2D
- testCreateArrayFlattenedLine2D
- testCreateArrayTriangle2D
Added and renamed tests to better reflect intention:
- testCreateValueInt -> testCreateFlattenedValueInt
- testCreateValueLong -> testCreateFlattenedValueLong
- testCreateValueDouble -> testCreateFlattenedValueDouble
- testCreateValueFloat -> testCreateFlattenedValueFloat
- testCreateValueObject -> testCreateFlattenedValueObject
These tests will not be added to the lw5 ValueTypeTests. Instead I have added the classes they were generating in the qtypes tests:
- testCreateAssortedValueWithLongAlignment
- testCreateAssortedRefWithLongAlignment
- testCreateLayoutsWithPrimitives
- testCreateFlatLayoutsWithValueTypes
- testCreateAssortedValueWithObjectAlignment
- …

Add test classes for lw5 ValueTypeTests

---

runtime/compiler/control/JITClientCompilationThread.cpp

The client's response to the `VM_getMemberNameMethodInfo` message from the server is expected to include a `bool ok` value when received by the server. The client now conforms to this expectation.
Formerly, the client would send a `uintptr_t` value (unnecessarily converting the `bool` return value of `getMemberNameMethodInfo`) and this would trigger an assert here:
https://github.com/eclipse-openj9/openj9/blob/06c3abcca73751a569836b2df970873366b50312/runtime/compiler/env/VMJ9Server.cpp#L2310
at the server when using a debug build.

Fix mismatched JITServer message type

---

runtime/gc_base/GCExtensions.cpp
runtime/gc_base/GCExtensions.hpp
runtime/gc_modron_startup/mminit.cpp
runtime/gc_modron_startup/mmparseXXgc.cpp

There is kind of the problem Service observes often - an attempt to launch JVM is failed due Object Heap initialization error. For example there are multiple cases for Windows users trying to use harge heaps with Compressed Refs JVM. Generation of system core for investigation is problematic because this failure occurs very early in JVM startup. Adding debug non-published option
-XXgc:forceGPFOnHeapInitializationError to help Service investigate this kind of the problem.

Add debug option to force GPF on heap initialization error

---

test/functional/Java22andUp/build.xml
test/functional/Java22andUp/playlist.xml

`JDK22+` disable `JEP 454` tests
`JDK` next extension `openj9` branch and `Valhalla` don't have the latest OpenJDK API updates yet.
Related to https://github.com/eclipse-openj9/openj9/issues/18349
Signed-off-by: Jason Feng fengj@ca.ibm.com

JDK22+ disable JEP 454 tests

---

runtime/compiler/CMakeLists.txt

A bug in libunwind on x86_64-macOS results in intermittent crashes from libunwind if a C++ exception is thrown from
`OMR::Compilation::failCompilation`.  In order to work around the problem, the JIT compiler needs to be compiled with `-fno-omit-frame-pointer` on that combination of CPU and operating system.
That option will be used only on JDK 22 or later builds for now, while the impact on compile-time and start-up performance is evaluated.
Fixes #18321

Use -fno-omit-frame-pointer on x86_64-mac JIT builds

---

runtime/jcl/common/mgmtthread.c
test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestThreadMXBean.java

Fix interpreter transition in getThreadAllocatedBytes. Also use parameterized variant of the API to support JDK8.

Fix interpreter transition in getThreadAllocBytes

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit stops the JIT assigning the x18 register.

AArch64 macOS: Stop assigning x18

---

runtime/compiler/optimizer/J9Simplifier.cpp

The convertCurrentTimeMillis() function was recreating a currentTimeMillis() call into a new call target which would be replaced in codegen with a Z specific instruction. To convert the results into milliseconds the value has to be divided by a constant and the tree was incorrectly converted into an ldiv with a call child that is not anchored which allowed dead trees elimination to remove the treetop resulting in the the ldiv to be moved in a way that would change the semantic of the java method.

Fix Tree Simplifier convertCurrentTimeMillis()

---

buildenv/jenkins/ARTIFACTORY.md

Curl wrapper needs to use the 'new' OSU Artifactory url or else it will not redirect to the UNB mirror site

Update Artifactory doc with new OSU Art URL

---

jcl/src/java.base/share/classes/java/lang/Access.java
jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
test/functional/Java22andUp/build.xml
test/functional/Java22andUp/playlist.xml

`JDK22+` add latest APIs for `Valhalla` & enable `JEP` `454` tests
`Valhalla` extension repo now has the latest `openjdk` updates.
closes https://github.com/eclipse-openj9/openj9/issues/18349

JDK22+ add latest APIs for Valhalla & enable JEP 454 tests

---

runtime/compiler/optimizer/EscapeAnalysisTools.cpp

`TR_EscapeAnalysisTools::processSymbolReferences` uses a `BitVector` to accumulate the symbol reference numbers for symbols that are to be loaded on an `<eaEscapeHelper>` call.  In walking through the set of defining symbols associated with a particular local symbol, the code was adding the reference number for the original symbol to the `BitVector` of symbols to be loaded for the `<eaEscapeHelper>` call rather than the reference numbers for the associated defining symbols.  That can lead Escape Analysis to miss potential escapes of references through induce OSR blocks or peeked calls.
This fixes a problem that was introduced in commit eddbd1b, at [line 156 of EscapeAnalysisTools.cpp](https://github.com/eclipse-openj9/openj9/commit/eddbd1b7abb9ced535e009e124d20b3aceafbef0#diff-0858e6725bce …

Use defining symrefs from defining map for <eaEscapeHelper> call

---

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp
runtime/compiler/codegen/J9CodeGenerator.hpp
runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp
runtime/compiler/optimizer/J9RecognizedCallTransformer.hpp
runtime/compiler/p/codegen/J9CodeGenerator.cpp
runtime/compiler/x/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9CodeGenerator.cpp

This patch adds `ArraysSupport.vectorizedMismatch` as a recognized method. If the `arraycmp` IL opcode is supported, `vectorizedMismatch` call nodes are transformed to a functionally equivalent tree using `arraycmp`.
`vectorizedMismatch` is functionally equivalent to:
```
lengthInBytes = length << log2ArrayIndexScale
mask = (log2ArrayIndexScale<2) ? 3 : 7
n = lengthInBytes & ~(mask)
res = arrayCmpLen(a+aOffset, b+bOffset, n)
if (res == n)  // no mismatch found
return ~((lengthInBytes & mask) >> log2ArrayIndexScale)
else           // mismatch found
return res >> log2ArrayIndexScale
```
Therefore the call nodes can be translated like so:
```
n9n    icall  jdk/internal/util/ArraysSupport.vectorizedMismatch(Ljava/lang/Object;JLjava/lang/Object;JII)I
n3n      <a>
n4n      <aOffset>
n5n …
```

Accelerate ArraysSupport.vectorizedMismatch in IL

---

runtime/j9vm/javanextvmi.cpp

Removing the check prevents any incorrect referencing without VMAccess while GC is modifying the threadObject reference.
Fixes: #18353 

Remove redundant assertion to avoid acquiring VMAccess

---

runtime/compiler/control/HookedByTheJit.cpp

By default, OpenJ9 uses an "implicit" shared class cache (SCC) that is used to cache "bootstrap" classes and methods. Currently, methods whose class is not present in the SCC receive a high initial invocation count (3000/3000 for loopless/loopy method) in order to improve steady state throughput. However, this could affect start-up time of applications because methods are interpreted for too long before being JIT compiled.
The presence of `-Xshareclasses` on the command line is a sign that the user cares about start-up time and OpenJ9 automatically lowers the invocations counts to 1000/250. However, with the implicit SCC (no -Xshareclasses command line option), application classes are not cached and methods belonging to those classes will receive a large initial invocation count …

Reduce counts when class of method is not in SCC

---

runtime/jcl/common/mgmtruntime.c
runtime/jcl/j9jcl.tdf
runtime/vm/jvminit.c
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/TimeChangeTest.java

CRIU adds time compensation for `RuntimeMXBean.getUptime()`
Adjusted `RuntimeMXBean.getUptime()` with `checkpointState.checkpointRestoreTimeDelta`;
Added a test.
closes https://github.com/eclipse-openj9/openj9/issues/18106

CRIU adds time compensation for RuntimeMXBean.getUptime()

---

test/functional/Valhalla/src_lw5/org/openj9/test/lworld/ValueTypeTests.java

testCreateLargeValueObjectAndMegaValueObject
testCreateLargeRefObjectAndMegaRefObject
testAssortedValueWithLongAlignment
testAssortedRefWithLongAlignment
testAssortedValueWithObjectAlignment
testAssortedRefWithObjectAlignment
testAssortedValueWithSingleAlignment
testAssortedRefWithSingleAlignment
testStaticFieldsWithSingleAlignment
testStaticFieldsWithLongAlignment
testStaticFieldsWithObjectAlignment
testGCFlattenedPoint2DArray
testGCFlattenedValueArrayWithSingleAlignment
testGCFlattenedValueArrayWithObjectAlignment
testGCFlattenedValueArrayWithLongAlignment
testGCFlattenedLargeObjectArray
testGCFlattenedMegaObjectArray
testInvalidNestedField <- replaced by preload tests in ValhallaAttributeTests testNullWritesOnNonNullableArrays <- this will be added to ValhallaAttributeTests once …

Part 3 of adding lw5 ValueTypeTests

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit stops the JIT assigning the x18 register on AArch64 macOS.
Original PR in master: #18351

(0.41) AArch64 macOS: Stop assigning x18

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/codegen/J9CodeGenerator.hpp
runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/compile/J9SymbolReferenceTable.hpp
runtime/compiler/il/J9Node.cpp
runtime/compiler/il/J9Node.hpp
runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp
runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp
runtime/compiler/x/codegen/CallSnippet.cpp
runtime/compiler/x/codegen/J9CodeGenerator.cpp
runtime/compiler/x/codegen/J9CodeGenerator.hpp
runtime/compiler/x/codegen/X86PrivateLinkage.cpp
runtime/compiler/x/codegen/X86PrivateLinkage.hpp

...by avoiding breaking the block containing the original call. There isn't much opportunity to optimize the inline logic anyway, so it's better to keep the IL neater.
On code generators that support doing so (initially just x86-64), calls to `linkToStatic`, `linkToSpecial`, and `invokeBasic` that have not been refined are now changed in-place into calls to a new JIT non-helper `<jitDispatchJ9Method>`, which takes the callee `J9Method` as an additional (first) argument. It has JIT private linkage, but the extra argument is treated specially so that the other arguments are passed in exactly the way expected by (any JIT-compiled body for) the actual callee. The code generator generates a sequence that determines whether the callee is compiled and jumps to the JIT entry point if it is. …

Improve MethodHandle direct dispatch J2I-prevention transformations

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/env/VMJ9.cpp

Fix an AIX warning concerning tautological comparisons (i.e. boolean comparisons which will always evaluate to the same value) by eliminating them. In both situations, variables with type `UDATA` (which is an unsigned data type and would therefore never be negative) were compared with zero.

Eliminate tautological comparisons

---

test/functional/cmdline_options_testresources/src/com/ibm/j9/getcallerclass/TestGroup.java
test/functional/cmdline_options_testresources/src_80/com/ibm/j9/getcallerclass/ReflectionMHTests.java
test/functional/cmdline_options_testresources/src_90/com/ibm/j9/getcallerclass/ReflectionMHTests.java

This patch addresses eclipse-openj9/openj9#14989 for ojdk11 MHs. Hidden Classes changed InjectedInvoker class signatures. This patch updates the test case to support pre-hidden-class signatures.

Adapt getCallerClass MH tests for ojdk11 MHs

---

runtime/vm/swalk.c

First 8 JNI local refs are directly stored inside the `J9SFJNINativeMethodFrame` before allocating `J9JNIReferenceFrame` to store additional references. StackWalker should check if the object pushes from method frame is JNI local when walking O-Slots.
Related: #17712 

Recognize JNI local refs in JNINativeMethodFrames

---

runtime/gc_base/ReferenceChainWalker.cpp

JNI Local References could be found on the stack(first 8 of them) or from GC_VMThreadJNISlotIterator (vmThread->jniLocalReferences). need to update MM_ReferenceChainWalker::doVMThreadSlot() to report J9GC_ROOT_TYPE_JNI_LOCAL type for the case  walkState->slotType = J9_STACKWALK_SLOT_TYPE_JNI_LOCAL.
relate: https://github.com/eclipse-openj9/openj9/pull/18378 and https://github.com/eclipse-openj9/openj9/issues/17712

Fix JNI Local Reference reporting issue

---

runtime/compiler/runtime/J9CodeCacheManager.cpp

Code cache allocation sizes are calculated and rounded up to the page size available on the system. When large pages/huge pages are enabled, and page size >= 1GB, this can cause the code cache size calculation to go wrong. 
When codecachetotal is lesser than the page size, it makes the size of code cache segment bigger than the total code cache size (default 256MB for a 64-bit VM).
If large pages are enabled, page size should be recalculated to a smaller value if required. Also a warning message should be printed in the verbose output.
Closes: ##18274

Fix code cache allocation with large pages enabled

---

runtime/compiler/x/codegen/J9X86Instruction.hpp

Add `const` to `Instruction::description` for consistency with `Instruction::description` in OMR as proposed in [omr #7107](https://github.com/eclipse/omr/pull/7107).

Add 'const' to return type of Instruction::description

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp

Fix AIX warning concerning an implicit conversion of NULL to int32_t. The null was being passed into generateSrc1Instruction, which was expecting an immediate of type int32_t. Other calls to this function in this same file pass a 0 to this parameter, so it seems sensible to do the same here for consistency.

Replace NULL with 0 in call to generateSrc1Instruction

---

test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestThreadMXBean.java

Add new test cases to verify non-current thread paths.
Depends on https://github.com/eclipse/omr/pull/7163

Add addition testing for ThreadMXBean thread alloc

---

runtime/jcl/common/mgmtinit.c
runtime/jcl/common/mgmtmemory.c
runtime/jcl/j9jcl.tdf

new tracepoints are added for the memory usage of memory pools (both heap memory and nonHeap memory, before GC and after GC) in order to identify/isolate potential inconsistent memory usage case.
- Add level 6 tracepoint to record memory usages for every memory pools at both before GC and after GC.
- Add exception tracepoint for in case the memory pool usages are inconsistent.
related to: https://github.com/eclipse-openj9/openj9/issues/17769

Tracepoints for the memory usage of memory pools

---

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java

Add System.gc() before checkpointJVMImpl to ensure that 
the thread GC environment exists during restore.
Issue: https://github.com/eclipse-openj9/openj9/issues/17731

Ensure thread GC environment exists during restore

---

runtime/gc_base/ReferenceChainWalker.cpp

We could not pass walkState parameter to jvmti callback for JNI local reference on stack (except normal Stack slot), it could cause jvmti crash, so pass walkState == NULL for the case.
fix: https://github.com/eclipse-openj9/openj9/issues/18392

Pass NULL walkState to jvmti callback for JNI local reference on stack

---

test/functional/Java21Only/testng_210.xml
test/functional/Java22andUp/src/org/openj9/test/jep454/downcall/UnionStructTests.java
test/functional/Java22andUp/src/org/openj9/test/jep454/downcall/UnionTests.java
test/functional/Java22andUp/src/org/openj9/test/jep454/upcall/UpcallMHWithUnionStructTests.java
test/functional/Java22andUp/src/org/openj9/test/jep454/upcall/UpcallMHWithUnionTests.java
test/functional/Java22andUp/src/org/openj9/test/jep454/upcall/UpcallMethodHandles.java
test/functional/Java22andUp/testng_220.xml

The changes add all the same test suites intended
for union in JDK21 to JDK22 with the updated APIs
introduced in JDK22.

[FFI/Test_JDK22] Add test suites intended for union

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/control/OptionsPostRestore.hpp

Making a new option, `-XX:[+/-]IProfileDuringStartupPhase`, that enforce/disable IProfiler during the startup phase. 
If the option is not used the default existing algorithm will determine the behaviour.
This option will replaces the `TR_DisableNoIProfilerDuringStartupPhase` environment variable and overrides `-Xjit:noIProfilerDuringStartupPhase`.
This option will be used in cold-runs/`populate_scc` scripts to ensure more IProfiler information are being collected and stored in the SCC.
Docs: https://github.com/eclipse-openj9/openj9-docs/issues/1204

Add option to enforce/disable IProfiler during startup phase

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/il/J9MethodSymbol.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/UnsafeFastPath.cpp

Method recognition has been updated for the following three cases:
As of JDK12, `ConcurrentHashMap.tabAt` now calls `Unsafe.getReferenceAcquire` instead of `Unsafe.getObjectVolatile`. `Unsafe.getReferenceAcquire` is now recognized so it triggers the Unsafe Fast Path opt.
As of JDK12, `ConcurrentHashMap.setTabAt` now calls `Unsafe.putReferenceRelease` instead of `Unsafe.putObjectVolatile`. `Unsafe.putReferenceRelease` is also now recognized for Unsafe Fast Path.
As of JDK15, the signature for `HashMap.getNode` no longer has an int parameter. An entry for this case has been added so the method is forced to be inlined like it was before.

Updated recognized methods for newer JDKs

---

jcl/src/java.base/share/classes/java/lang/System.java

Fixes https://github.com/eclipse-openj9/openj9/issues/18405

Don't cache instances of TemporaryLoggerFinder

---

runtime/nls/j9vm/j9vm.nls
runtime/oti/j9nonbuilder.h
runtime/oti/jvminit.h
runtime/vm/jvminit.c

If `-XX:Compatibility=elasticsearch` is specified:
* recognize `-XX:+UseG1GC` and `-XX:-UseG1GC`
* include flags `G1HeapRegionSize`, `G1ReservePercent`, `InitiatingHeapOccupancyPercent` and `UseG1GC` in `-XX:+PrintFlagsFinal` output (`G1HeapRegionSize` is derived from `MaxHeapSize`)
If `-XX:Compatibility=` is specified more than once, or with a mode other than `"elasticsearch"` (not case-sensitive), the JVM will refuse to start.
Issue: #18265.

Add support for -XX:Compatibility=elasticsearch

---

test/functional/Jsr292/src/com/ibm/j9/jsr292/LookupAPITests_Find.java

This patch fixes eclipse-openj9/openj9#14987. OJDK MHs use OJDK's version of `findSpecial`. Before JEP 274, which was implemented for Java 9, `findSpecial` did not support interface method access. This patch handles the `IllegalAccessException` that is thrown for OpenJ9 with OJDK MHs enabled.
Closes: eclipse-openj9/openj9#14987

Adapt cross package interface test to correctly handle Java 8

---

buildspecs/win_x86-64.spec
buildspecs/win_x86-64_cmprssptrs.spec
buildspecs/win_x86.spec

Compile Windows with VS2022.
Tested via [internal build](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=60371)

Update graph_tool_script.build in Windows specs to msvc2022

---

test/functional/cmdline_options_testresources/src_80/com/ibm/j9/getcallerclass/ReflectionMHTests.java

This patch addresses eclipse-openj9/openj9#14989 for ojdk8 MHs by matching the MH class to the InjectedInvoker template class.

Adapt getCallerClass MH tests for ojdk8 MHs

---

test/functional/cmdLineTests/jitserver/jitserverArgumentTesting.xml

Due to time delays between SSL context initialization at the server and and the client program exiting too soon, the SSL tests were failing. The failure happens due to:
Required condition was not found: [Output match: Connected to a server] As the client did not connect to the server as expected.
This fix will check the condition for the connection established with the server and compile synchronously.
Closes: ##18308

Fix SSL Test Failure due to client exiting too soon during remote compile

---

runtime/jvmti/jvmtiHelpers.c
runtime/vm/ContinuationHelpers.cpp

Stale objects can manifest many issues. In this case, stale objects
cause complex and intermittent synchronization issues.
Related: https://github.com/eclipse-openj9/openj9/issues/17865
Related: https://github.com/eclipse-openj9/openj9/issues/17869
Related: https://github.com/eclipse-openj9/openj9/issues/18370

Re-fetch objects after VM access is released and reacquired

---

runtime/gc_modron_startup/mgcalloc.cpp

Use assertion with message to provide extra information to simplify debugging in the case of heap corruption failure.

Use assertion with message for object allocation sanity checks

---

buildenv/jenkins/variables/defaults.yml

Cherry pick https://github.com/eclipse-openj9/openj9/pull/18423 for 0.41

(0.41) Update OpenSSL with the fix for CVE-2023-5678

---

runtime/tests/port/j9strTest.c

The implementation of atoe_vsnprintf has been updated in omr PR:[#7158](https://github.com/eclipse/omr/pull/7158) This test needs to get updated to match those changes.
Signed-off-by: ehsan kiani far ehsan.kianifar@gmail.com

Z: Update vsnprintf test to match the omr atoe_util changes

---

jcl/src/java.base/share/classes/java/lang/Throwable.java

`JDK22+` add `Throwable.jfrTracing`
close https://github.com/eclipse-openj9/openj9/issues/18427

JDK22+ add Throwable.jfrTracing

---

jcl/src/java.base/share/classes/java/lang/Access.java

New tests were added in
* [8319436: Proxy.newProxyInstance throws NPE if loader is null and interface not visible from class loader](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/632f56c297a11578b8638460f63ba71a1928933a)
that will pass `null` to `getLoaderNameID()`; see [test/jdk/java/lang/reflect/Proxy/ClassRestrictions.java](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/632f56c297a11578b8638460f63ba71a1928933a/test/jdk/java/lang/reflect/Proxy/ClassRestrictions.java#L100).

Tolerate null in getLoaderNameID()

---

runtime/j9vm/javanextvmi.cpp
runtime/j9vm/jvm.c
runtime/jvmti/jvmtiStackFrame.c
runtime/vm/ContinuationHelpers.cpp

**1. Update acquireVThreadInspector and enterVThreadTransitionCritical**
VM is entered by the invocation of `internalEnterVMFromJNI`.
VM is exited by the invocation of `internalExitVMToJNI`.
VM is always entered before `acquireVThreadInspector` and
`enterVThreadTransitionCritical` are invoked.
In these functions, the goal can be achieved by just releasing
and re-acquiring VM access. The new changes just release and
re-acquire VM access instead of exiting and entering the VM.
This has less overhead.
Addresses: https://github.com/eclipse-openj9/openj9/pull/18420#issuecomment-1802476741
**2. Update error handling in JVMTI NotifyFramePop**
Return `JVMTI_ERROR_THREAD_NOT_SUSPENDED` if the thread was not
suspended and was not the current thread.
For virtual threads, `VirtualThread.state` is …

Virtual Thread Support

---

jcl/src/java.base/share/classes/java/lang/Thread.java

Related to: eclipse-openj9/openj9#16659

Clear vmthread from thread object at shutdown

---

buildenv/jenkins/variables/defaults.yml

Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/726

Compile jdk8, 11 alinux with gcc 10.3, p,zlinux with gcc 11.2

---

runtime/compiler/control/CompilationThread.cpp

To save compilation time, this commit disables the idiomRecognition optimization on x86 for optimization levels "warm" and below. Performance experiments have shown that CPU consumed by compilation threads reduces by about 4% while there is no effect on throughput. This change can be disabled at runtime by defining the following environment variable: TR_EnableIdiomRecognitionAtWarm=1 The chage will not apply for AOT compilations, for compilations before CRIU checkpoint or under -Xtune:throughput mode.

Disable idiomRecognition on x86 for warm opt levels

---

runtime/compiler/p/codegen/J9CodeGenerator.cpp

Fix plinux warning concerning a comparison of a non-pointer to NULL by replacing the NULL with 0. `getHeapBase()` returns a value of type `intptr_t`, which is an integer value and therefore can not be NULL. Since the variable being returned, `_heapBase`, it is initialized to 0 in [omr/compiler/control/OMROptions.hpp](https://github.com/eclipse/omr/blob/4aa604baf16d8ef55fb13c3b5243984e8edf00a1/compiler/control/OMROptions.hpp#L1407), it seems sensible to compare its value to 0 instead of NULL.

Fix comparison of non-pointer to NULL

---

runtime/compiler/compile/J9Compilation.cpp

Fix AIX warnings concerning comparisons between two enum values of different types by explicitly casting one value into the type of the other.

Add explicit enum casts to prevent warnings

---

jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
test/functional/Jsr292/src/com/ibm/j9/jsr292/LookupAPITests_Find.java

This patch closes eclipse-openj9/openj9#14987. OpenJ9 MHs' `checkSpecialAccess` incorrectly supported JEP 274 for all Java versions despite JEP 274 targeting Java 9+.
Closes: eclipse-openj9/openj9#14987

Conform to pre JEP 274 for OpenJ9 MHs

---

runtime/bcverify/vrfyhelp.c

The changes aim to capture the corner case when
the specified field doesn't exist in the current
class or it is intentionally accessed by a hostile
subclass prior to its superclass's initialization
when it belongs to one of the superclasses.
Related: #16524

[Verifier] Fix the field access issue with putfield/getfield

---

runtime/j9vm/javanextvmi.cpp
runtime/j9vm/jvm.c
runtime/jvmti/jvmtiThread.c

Currently, the halt flag is set in VirtualThread MountEnd if a virtual
thread is suspended via JVMTI, and in VirtualThread UnmountEnd if a
carrier thread is suspended via JVMTI.
In the above approach, the halt flag is set too late. As soon as the
continuation swaps the J9VMThread context, the thread begins execution
and is capable of triggering JVMTI events.
To avoid the above issue, the above steps are moved into VirtualThread
MountBegin and UnmountBegin. This prevents the continuation to swap
the J9VMThread context.
Currently, the halt flag is set without invoking
exitVThreadTransitionCritical. This prevents JVMTI to resume the halted
thread and cause a hang. The new approach spins, invokes
exitVThreadTransitionCritical  and releases VM access to allow JVMTI to
resume the suspended …

Spin during VirtualThread MountBegin and UnmountBegin

---

runtime/bcutil/ROMClassWriter.cpp
runtime/codert_vm/decomp.cpp
runtime/jvmti/CMakeLists.txt
runtime/jvmti/jvmtiHelpers.cpp
runtime/jvmti/jvmti_internal.h

The breakpoint handling code was only fixing stacks actively running on
a thread. The stacks for continuations also need to be fixed.
Fixes: https://github.com/eclipse-openj9/openj9/issues/18088

Fix continuation stacks when breakpointing

---

longabout.html
runtime/include/about.html
runtime/libffi/about.html
runtime/libffi/powerpc/ffi_darwin.c

The change simply adopts the fix at libffi/libffi#805
to resolve the the issue with the nested struct in libffi on AIX.
Related: #18287
Note:
The changes should be kept in sync with the code at libffi/libffi#805
if any update.

[FFI/Jreg_JDK21] Fix the issue with the nested struct in libffi

---

runtime/criusupport/criusupport.cpp
runtime/criusupport/j9criu.tdf
test/functional/TestUtilities/src/org/openj9/test/util/TimeUtilities.java
test/functional/cmdLineTests/cmdLineTest_J9tests/build.xml
test/functional/cmdLineTests/cmdLineTest_J9tests/j9tests_elapsedTime.xml
test/functional/cmdLineTests/cmdLineTest_J9tests/playlist.xml
test/functional/cmdLineTests/cmdLineTest_J9tests/src/ElapsedTime.java
test/functional/cmdLineTests/criu/build.xml
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/TimeChangeTest.java

CRIU `checkpointRestoreTimeDelta` adjustment & add time compensation tests
Adjusted `J9JavaVM->checkpointState.checkpointRestoreTimeDelta` and `J9PortLibrary->nanoTimeMonotonicClockDelta` calculation;
Added tests for CRIU and non-CRIU scenarios.
related to https://github.com/eclipse-openj9/openj9/pull/18235

CRIU checkpointRestoreTimeDelta adjustment & add time compensation tests

---

runtime/criusupport/criusupport.cpp
test/functional/cmdLineTests/criu/src/org/openj9/criu/CRIUTestUtils.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/JDK11UpTimeoutAdjustmentTest.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestConcurrentMode.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestMachineResourceChange.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeCheckpointException.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeRestoreException.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TimeChangeTest.java

CRIU tests get accurate pre-checkpoint time
Use `CRIUTestUtils.prepareCheckPointJVM()` to avoid potential long disk file-related API calls before taking the pre-checkpoint time.
[100x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/35917/console) - no failure reproduced, a few infra errors.
closes https://github.com/eclipse-openj9/openj9/issues/18384

CRIU tests get accurate pre-checkpoint time

---

test/functional/Java22andUp/src/org/openj9/test/jep454/downcall/PrimitiveTypeTests1.java
test/functional/Java22andUp/src/org/openj9/test/jep454/downcall/PrimitiveTypeTests2.java
test/functional/Java22andUp/src/org/openj9/test/jep454/upcall/InvalidUpCallTests.java

A parameter was added in
* [8254693: Add Panama feature to pass heap segments to native code](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/3c1c081e4410d872bea0caabf5556eba111befcd)

Update uses of Linker.Option.critical() in tests

---

runtime/codert_vm/decomp.cpp

walkContinuationStackFrames has the NULL check included. The callback for deleting decompilation records does not walk the stack, so it needs to add the NULL check.

Add NULL check for continuation struct

---

runtime/jvmti/jvmtiHelpers.cpp
runtime/oti/vmconstantpool.xml

`java.lang.Thread.container` is added in `vmconstantpool.xml`.
Accessing `java.lang.Thread.container` as a known field simplifies
and fixes the incorrect error handling in `getVirtualThreadState`.

Make java.lang.Thread.container a known field

---

runtime/jvmti/CMakeLists.txt
runtime/jvmti/jvmtiThread.cpp
runtime/jvmti/jvmti_internal.h

This will simplify future changes for virtual thread support.

Convert jvmtiThread.c to jvmtiThread.cpp

---

jcl/src/java.base/share/classes/java/lang/System.java

The OpenJDK change has been backported to jdk11.
See https://github.com/eclipse-openj9/openj9/pull/18406

jdk11 - Don't cache instances of TemporaryLoggerFinder

---

jcl/src/java.base/share/classes/java/lang/System.java

The OpenJDK change has been backported to jdk11.
See https://github.com/eclipse-openj9/openj9/pull/18406
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/18462 for 0.43

(0.43) jdk11 - Don't cache instances of TemporaryLoggerFinder

---

test/functional/cmdLineTests/cmdLineTest_J9tests/src/ElapsedTime.java
test/functional/cmdLineTests/criu/criu_nonPortableJDK11Up.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/TimeChangeTest.java

Remove `Object.wait(timeout)` tests
The spurious wakeup breaks the time measurement.
close https://github.com/eclipse-openj9/openj9/issues/18456

Remove Object.wait(timeout) tests

---

jcl/src/java.base/share/classes/com/ibm/oti/reflect/TypeAnnotationParser.java
jcl/src/java.base/share/classes/com/ibm/oti/vm/VM.java
jcl/src/java.base/share/classes/java/lang/Class.java
runtime/jcl/common/reflecthelp.c

Related to https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/705 and https://github.com/eclipse-openj9/openj9/issues/17265

Append cp to method and field annotation data to fix redefinition inconsistencies

---

runtime/j9vm/javanextvmi.cpp

`J9VMThread->threadObject` can be modified between
`JVM_VirtualThreadHideFrames`'s first invocation with `hide=true` and
second invocation with `hide=false`. Synchronization to prevent JVMTI
operations is acquired between these two invocations. This prevents
JVMTI functions to see an unstable `J9VMThread->threadObject`.
Related: eclipse-openj9#17865
Related: eclipse-openj9#17869
Related: eclipse-openj9#18370

Add JVMTI synchronization in JVM_VirtualThreadHideFrames

---

test/functional/cmdLineTests/criu/playlist.xml

`CRIU` disable tests on `ppc64le` platform temporarily

CRIU disable tests on ppc64le platform temporarily

---

runtime/codert_vm/decomp.cpp

walkContinuationStackFrames has the NULL check included. The callback for deleting decompilation records does not walk the stack, so it needs to add the NULL check.

(0.42) Add NULL check for continuation struct

---

jcl/src/java.base/share/classes/com/ibm/oti/reflect/TypeAnnotationParser.java
jcl/src/java.base/share/classes/com/ibm/oti/vm/VM.java
jcl/src/java.base/share/classes/java/lang/Class.java
runtime/jcl/common/reflecthelp.c

Port to 0.43.0 from https://github.com/eclipse-openj9/openj9/pull/18437

0.43.0: Append cp to method and field annotation data to fix redefinition inconsistencies

---

runtime/j9vm/javanextvmi.cpp
runtime/jvmti/CMakeLists.txt
runtime/jvmti/jvmtiHelpers.cpp
runtime/jvmti/jvmtiThread.cpp
runtime/jvmti/jvmti_internal.h
runtime/oti/vmconstantpool.xml

Backporting the following PRs:
- #18460
- #18459
- #18453

[0.42] Virtual Thread Support

---

runtime/codert_vm/decomp.cpp

walkContinuationStackFrames has the NULL check included. The callback for deleting decompilation records does not walk the stack, so it needs to add the NULL check.

(0.43) Add NULL check for continuation struct

---

runtime/gc_base/GCExtensions.cpp
runtime/gc_base/GCExtensions.hpp
runtime/gc_modron_startup/mminit.cpp
runtime/gc_modron_startup/mmparse.cpp
runtime/oti/jvminit.h

Adjust heap size for CRIU restore
When we snapshot on a machine with higher physical memory and restore on one
with lower physical memory, the InstantOn JVM heap size will be larger than
a usual JVM run on the restore machine. And the momory usage will be abnormally
higher.
Update the extension with the correct physical memory limit and utilize the
existing softmax mechanism to solve the problem. Note we only update the softmax
if it is smaller than the Xmx size. If it is smaller than the
Xms size, then we upscale the softmx to match with the Xms size.
Related:
https://github.com/eclipse-openj9/openj9/issues/17596
Detailed behavior table:
https://github.com/eclipse-openj9/openj9/issues/18217#issuecomment-1799794593
Signed-off-by: Frank Kang <frank.kang@ibm.com>

InstantOn adjust heap size with restore machine 

---

buildenv/jenkins/variables/defaults.yml

See https://github.com/eclipse-openj9/openj9/pull/18477

Use the new centos6 image to build xlinux with gcc 11.2

---

test/functional/JIT_Test/src/jit/test/tr/chtable/VirtualGuardTest.java

This add few debug information to collect in order to debug further the issue https://github.com/eclipse-openj9/openj9/issues/14469 which is not reproducible locally. The issue happens due to the intermediate state set in between the testcase from Task A to Task B and exits. This commit will also let the testcase run one another time so it will skip the intermediate state.
Signed-off-by: Bhavani SN (bhavani.sn@ibm.com)

Log task start time to verify delays and modify the loop to skip intermediate state

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit fixes `inlineStringHashCode` so that `savedLengthReg` is copied to `lengthReg` when the reference count of`lengthNode` is > 1.
Resolves #18506.

AArch64: Fix String.hashCode() implementation

---

doc/release-notes/0.41/0.41.md

Updated the release note for 0.41.0 release. New change related to getThreadAllocatedBytes MXBean API support backported from 0.42.0 release.
[skip ci]

Update 0.41.0 release note

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/infra/J9Monitor.cpp
runtime/compiler/infra/J9Monitor.hpp
runtime/compiler/infra/J9MonitorTable.cpp
runtime/compiler/infra/J9MonitorTable.hpp
runtime/compiler/infra/RWMonitor.cpp
runtime/compiler/infra/RWMonitor.hpp
runtime/compiler/runtime/ClassUnloadAssumption.cpp
runtime/compiler/runtime/RuntimeAssumptions.hpp

Work towards fixing AIX warnings about assigning string literals to non-const char pointers by adding a 'const' qualifier to string parameters in getInstanceFieldOffset related functions, TR_AddressSet::traceDetails, and J9::Monitor::create.
Contributes to (but does not close) #14859

Add 'const' qualifier to some string parameters

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp

This patch fixes eclipse-openj9/openj9#14984.
For Java 10-, private interface lookups should fail with a `IncompatibleClassChangeError` that is caught and wrapped in a `IllegalAccessException`. For OJ9 MHs, the `IllegalAccessException` is thrown in `findInterface` based on Java-code guards on method modifiers. For OJDK MHs, the `IncompatibleClassChangeError` is expected from a call to `MethodHandleNatives.resolve` and wrapped.
This patch ensures that the correct error is thrown for private interfaces during method lookup for Java 11- with OJDK MHs.
Issues: eclipse-openj9/openj9#14984

Conform to spec for interface resolution for OJDK MHs

---

runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/compile/J9SymbolReferenceTable.hpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/jitsupport.cpp
runtime/oti/j9nonbuilder.h

Work towards fixing AIX warnings about assigning string literals to non-const char pointers by adding 'const' qualifiers to some string variables and parameters in runtime/compiler/compile and `j9jit_printf` related functions.

Fix string literal conversion warnings in compile and oti

---

runtime/jvmti/jvmtiBreakpoint.c
runtime/jvmti/jvmtiExtensionMechanism.c
runtime/jvmti/jvmtiField.c
runtime/jvmti/jvmtiMethod.c
runtime/jvmti/jvmtiWatchedField.c
runtime/oti/j9nonbuilder.h
runtime/oti/jvmtiInternal.h
runtime/vm/classallocation.c
runtime/vm/jnicsup.cpp

If the -XX:+KeepJNIIDs option is specified, invalidate IDs for unloaded classes rather than freeing them.
Detect invalidated IDs in JVMTI calls and return the appropriate error.
JNI calls may be updated in a future PR (we will need to decide how to handle invalid IDs in those cases as there is no standard error handling mechanism in JNI).
Related: #17466

Invalidate JNI IDs for unloaded classes

---

buildspecs/linux_ppc-64.spec
buildspecs/linux_ppc-64_cmprssptrs.spec
buildspecs/linux_ppc.spec

This only affects the Bytecode and MH interpreter compilation, everything else uses XLC.
Tested via internal build 61392.

Use gcc 11.2 for plinux BE IBM builds

---

test/functional/TestUtilities/src/org/openj9/test/util/TimeUtilities.java
test/functional/cmdLineTests/cmdLineTest_J9tests/src/ElapsedTime.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TimeChangeTest.java

Disable maximum elapsed time tests
The maximum elapsed time is not always guaranteed on some platforms.
Related
* https://github.com/eclipse-openj9/openj9/issues/18487
* https://github.com/eclipse-openj9/openj9/issues/18513
FYI @tajila 

Disable maximum elapsed time tests

---

runtime/criusupport/criusupport.cpp
test/functional/cmdLineTests/criu/playlist.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/CRIUTestUtils.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/JDK11UpTimeoutAdjustmentTest.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestConcurrentMode.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestMachineResourceChange.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeCheckpointException.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestSingleThreadModeRestoreException.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TimeChangeTest.java

Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/18425
* https://github.com/eclipse-openj9/openj9/pull/18469
* https://github.com/eclipse-openj9/openj9/pull/18457

(v0.43.0-release) elapsed time tests

---

test/functional/Valhalla/build.xml
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeGenerator.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeTests.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaUtils.java
test/functional/Valhalla/src_lw5/org/openj9/test/lworld/ValueTypeGenerator.java
test/functional/Valhalla/src_lw5/org/openj9/test/lworld/ValueTypeTests.java

The latest commits in lw5 add a new flag -XDenableNullRestrictedTypes to compile uses of nullrestricted fields. The bytecodes aconst_init and withfield are also removed as is the <vnew> method.
To support these changes this pr:
- remove withfield test ValhallaAttributeTests.testWithFieldStoreNullToNullRestrictedField
- add test ValhallaAttributeTests.testPutFieldNullToValueTypeField to test setting null to a nonrestricted value type field
- remove ValueTypeTests.testCheckCastValueTypeOnNonNullType - this doesn't apply to the new world, nullrestricted behavior can only be set for fields
- replaces all uses of ACONST_INIT and WITHFIELD in ValueTypeTests
- remove TODO comments in ValueTypeTests that were placeholders for withfield tests. In the new version it is not possible to set field …

Update Valhalla tests to compile with lw5 head

---

runtime/jvmti/jvmtiClass.c

The current flag does nothing - use the flag that's used in other similar callers throughout the VM.
Fixes: #18482

Use correct GC flag in HCR dark matter cleanup

---

runtime/jvmti/jvmtiClass.c

The current flag does nothing - use the flag that's used in other similar callers throughout the VM.
Fixes: #18482
Cherry pick https://github.com/eclipse-openj9/openj9/pull/18540 for 0.42

(0.42) Use correct GC flag in HCR dark matter cleanup

---

runtime/shared_common/CacheMap.cpp
runtime/shared_common/CacheMap.hpp
runtime/shared_common/CompositeCache.cpp
runtime/shared_common/CompositeCacheImpl.hpp

Add an parameter to SH_CompositeCacheImpl::reset() to indicate whether the SCC can be unlocked by it or not. When updating romClass resources or doing stale marking, the SCC should always be locked. Do not unlock the SCC in these 2 cases.
Fixes #18526

Add an additional param to SH_CompositeCacheImpl::reset()

---

runtime/shared_common/CacheMap.cpp
runtime/shared_common/CacheMap.hpp
runtime/shared_common/CompositeCache.cpp
runtime/shared_common/CompositeCacheImpl.hpp

Add an parameter to SH_CompositeCacheImpl::reset() to indicate whether the SCC can be unlocked by it or not. When updating romClass resources or doing stale marking, the SCC should always be locked. Do not unlock the SCC in these 2 cases.
Fixes #18526
Port of https://github.com/eclipse-openj9/openj9/pull/18548

(v0.42) Add an additional param to SH_CompositeCacheImpl::reset()

---

runtime/shared_common/CacheMap.cpp
runtime/shared_common/CacheMap.hpp
runtime/shared_common/CompositeCache.cpp
runtime/shared_common/CompositeCacheImpl.hpp

Add an parameter to SH_CompositeCacheImpl::reset() to indicate whether the SCC can be unlocked by it or not. When updating romClass resources or doing stale marking, the SCC should always be locked. Do not unlock the SCC in these 2 cases.
Fixes #18526
Port of https://github.com/eclipse-openj9/openj9/pull/18548

(v0.43) Add an additional param to SH_CompositeCacheImpl::reset()

---

jcl/src/java.base/share/classes/java/lang/Access.java
jcl/src/java.base/share/classes/java/lang/Class.java

`JDK22+` adds `JavaLangAccess.findMethod(isPublic, methodName, parameters)`
`getMethodHelper()` is updated to take the method type to be searched.
Required by latest OpenJDK updated
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/706
[JEP 463: Implicitly Declared Classes and Instance Main Methods (Second Preview)](https://openjdk.org/jeps/463)

JDK22+ adds JavaLangAccess.findMethod(isPublic, methodName, parameters)

---

jcl/src/java.base/share/classes/java/lang/invoke/MethodHandleResolver.java

This patch addresses eclipse-openj9/openj9#14985.
For MethodHandles to private interface methods, the RI erroneously initializes the MethodHandle to have an InvokeInterface reference kind, leading to an invoke-time AbstractMethodError throw.
As per the spec, OpenJ9 initializes MethodHandles to private interface methods to have an InvokeSpecial reference kind which does not throw the error.
This distinction causes a test failure for a test reported in eclipse-openj9/openj9#14985. Though not-spec compliant, the test expects an AbstractMethodError to be thrown to conform to the RI behaviour in JDK8. For OpenJ9 MHs, MethodHandles.unreflect identifies private interface methods and installs an AbstractMethodError-thrower MH. This patch sets up a MethodHandleResolver method that installs the …

Match RI behaviour for unrelfect with OpenJDK MHs in JDK8

---

test/functional/Valhalla/src_lw5/org/openj9/test/lworld/ValueTypeGenerator.java
test/functional/Valhalla/src_lw5/org/openj9/test/lworld/ValueTypeTests.java

makeRef and makeGenericValue can be combined since they both use `<init>` now

Simplify lw5 tests after removal of aconst_init and withfield

---

jcl/src/java.base/share/classes/java/lang/Access.java
jcl/src/java.base/share/classes/java/lang/Class.java

JDK22+ update `Access.findMethod(publicOnly, methodName, parameters)`
Search either `public` method only or all methods;
Removed unused `Access.getMethodOrNull()`.
related
* https://github.com/eclipse-openj9/openj9/pull/18555#discussion_r1414532786

JDK22+ update Access.findMethod(publicOnly, methodName, parameters)

---

jcl/src/java.base/share/classes/java/lang/Compiler.java
runtime/tests/access/CMakeLists.txt
runtime/tests/access/compiler.cpp
runtime/tests/access/module.xml
test/functional/DDR_Test/playlist.xml
test/functional/DDR_Test/src/j9vm/test/corehelper/CoreGen.java
test/functional/JIT_Test/build.xml
test/functional/JIT_Test/playlist.xml
test/functional/JIT_Test/src/jit/test/jar/JarTestClassLoader.java
test/functional/JIT_Test/src/jit/test/jar/ZipTestClassLoaderMT.java
test/functional/Java8andUp/playlist.xml
test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_Compiler.java
test/functional/TestUtilities/src/org/openj9/test/util/CompilerAccess.java
test/functional/TestUtilities/src/org/openj9/test/util/VersionCheck.java
test/functional/UnsafeTest/playlist.xml
test/functional/UnsafeTest/src_90/org/openj9/test/unsafe/MainTester.java

Update tests to avoid using java.lang.Compiler directly.
Issue: #18430.
Depends on changes to extension repositories to include new shared library in test-image:
* https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/720
* https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/736
* https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/291
* https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/86
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/708
Those changes can safely be merged before this because libraries are only include in test-image if they exist.

Remove java.lang.Compiler from Java 21+

---

runtime/vm/ContinuationHelpers.cpp

For weak memory ordering system such as PowerPC, we need to writeBarrier between resetting the state of continuation(set the state to unmounted) and freeing continuation/postUnmountContinuation during continuation unmounting to avoid potential assert/issue caused by inconsist state (in case the instructions are reordered).
related: https://github.com/eclipse-openj9/openj9/issues/16728

Need writeBarrier between resetting the state and freeContinuation

---

runtime/oti/j9nonbuilder.h
runtime/oti/jvminit.h
runtime/vm/CRIUHelpers.cpp
runtime/vm/jvminit.c
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/playlist.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/DeadlockTest.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/JDK11UpTimeoutAdjustmentTest.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestConcurrentMode.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestResult.java

Configure the checkpoint safety wait time with 
-XX:maxRetryForNotCheckpointSafe= and 
-XX:sleepMillisecondsForNotCheckpointSafe=, and increase 
the default checkpoint safety wait time from 1 ms to 1 
s.
Configure the checkpoint safety wait time for the 
re-enabled MethodTypeDeadlockTest to be 2 s to allow the 
threads to initialize a class, and fix the failure in 
the MethodTypeDeadlockTest that occurs due to an 
insufficient checkpoint safety wait time for the threads 
initializing a class.
Fix the race condition in MethodTypeDeadlockTest for the
shared resource testResult.lockStatus by modifying its
type from volatile int to AtomicInteger, and avoid the
test from timing out when the main thread is blocked
while waiting for testResult.lockStatus to reflect the
count of the worker …

Configure the wait time for checkpoint safety

---

test/functional/JIT_Test/playlist.xml
test/functional/Java8andUp/playlist.xml

Update tests to use `$(ADD_JVM_LIB_DIR_TO_LIBPATH)` as appropriate.
All failures noted in https://github.com/eclipse-openj9/openj9/pull/18571#issuecomment-1844203234 and https://github.com/eclipse-openj9/openj9/pull/18571#issuecomment-1845415859 are for `JCL_Test_SE80` or `testJITServer` which are corrected by this and now pass; see grinders:
* https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3103
* https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3110

Adapt tests for removal of java.lang.Compiler

---

jcl/src/java.base/share/classes/java/lang/Compiler.java
runtime/tests/access/CMakeLists.txt
runtime/tests/access/compiler.cpp
runtime/tests/access/module.xml
test/functional/DDR_Test/playlist.xml
test/functional/DDR_Test/src/j9vm/test/corehelper/CoreGen.java
test/functional/JIT_Test/build.xml
test/functional/JIT_Test/playlist.xml
test/functional/JIT_Test/src/jit/test/jar/JarTestClassLoader.java
test/functional/JIT_Test/src/jit/test/jar/ZipTestClassLoaderMT.java
test/functional/Java8andUp/playlist.xml
test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_Compiler.java
test/functional/TestUtilities/src/org/openj9/test/util/CompilerAccess.java
test/functional/TestUtilities/src/org/openj9/test/util/VersionCheck.java
test/functional/UnsafeTest/playlist.xml
test/functional/UnsafeTest/src_90/org/openj9/test/unsafe/MainTester.java

Cherry-pick #18571 and #18578 for the 0.42.0 release branch.

Remove java.lang.Compiler for Java 21+

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/CHTable.hpp
runtime/compiler/env/J2IThunk.cpp
runtime/compiler/env/J2IThunk.hpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/env/annotations/AnnotationBase.hpp
runtime/compiler/env/annotations/Annotations.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/runtime/JitRuntime.cpp

Work towards fixing AIX warnings about assigning string literals to non-const char pointers by adding 'const' qualifiers to some string variables and parameters (or worst case scenario, casting to (char *)) in runtime/compiler/env.
**This PR depends on:**
- **Step 1:**
- #18083
- #18455
**and must be merged in coordination with https://github.com/eclipse/omr/pull/7186**

Fix string literal conversion warnings in env

---

jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/CompilationMXBeanImpl.java
runtime/include/vmi.h
runtime/jcl/common/system.c
runtime/nls/j9cl/j9jcl.nls
runtime/util/vmargs.c
runtime/vm/jvminit.c
runtime/vm/vmifunc.c
runtime/vm/vmprops.c
test/functional/Java8andUp/src/org/openj9/test/vmArguments/VmArgumentTests.java

Closes https://github.com/eclipse-openj9/openj9/issues/18430
Test build and VmArgumentTests passing results for jdk11, 21
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/459/
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3118
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3119/

The java.compiler system property is obsolete in jdk21+

---

jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/CompilationMXBeanImpl.java
runtime/include/vmi.h
runtime/jcl/common/system.c
runtime/nls/j9cl/j9jcl.nls
runtime/util/vmargs.c
runtime/vm/jvminit.c
runtime/vm/vmifunc.c
runtime/vm/vmprops.c
test/functional/Java8andUp/src/org/openj9/test/vmArguments/VmArgumentTests.java

Issue https://github.com/eclipse-openj9/openj9/issues/18430
Cherry pick https://github.com/eclipse-openj9/openj9/pull/18582 for 0.43

(0.43) The java.compiler system property is obsolete in jdk21+

---

runtime/criusupport/criusupport.cpp
runtime/oti/j9nonbuilder.h
runtime/oti/jvminit.h
runtime/vm/jvminit.c
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/playlist.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/DeadlockTest.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/JDK11UpTimeoutAdjustmentTest.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestConcurrentMode.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestResult.java

Configure the checkpoint safety wait time with 
-XX:maxRetryForNotCheckpointSafe= and 
-XX:sleepMillisecondsForNotCheckpointSafe=, and increase 
the default checkpoint safety wait time from 1 ms to 1 
s.
Configure the checkpoint safety wait time for the 
re-enabled MethodTypeDeadlockTest to be 2 s to allow the 
threads to initialize a class, and fix the failure in 
the MethodTypeDeadlockTest that occurs due to an 
insufficient checkpoint safety wait time for the threads 
initializing a class.
Fix the race condition in MethodTypeDeadlockTest for the
shared resource testResult.lockStatus by modifying its
type from volatile int to AtomicInteger, and avoid the
test from timing out when the main thread is blocked
while waiting for testResult.lockStatus to reflect the
count of the worker …

(0.43) Configure the wait time for checkpoint safety 

---

buildenv/jenkins/common/variables-functions.groovy

When determining the OS, we look to the labels.
A while back we switched from sw.os.osx labels to
sw.os.mac. This was missed.
Related #13937 and infra 7907

Update baseOS from osx to mac

---

test/functional/Java22andUp/playlist.xml

Valhalla disables JDK22+ Jep454Tests temporarily
`Valhalla` extension repo is well behind OpenJDK head, and doesn't support some latest APIs. Disabled Jep454Tests temporarily until the valhalla project is updated w/ a recent OpenJDK tag.
related
* https://github.com/eclipse-openj9/openj9/issues/18583
FYI @hangshao0 

Valhalla disables JDK22+ Jep454Tests temporarily

---

runtime/compiler/p/codegen/CallSnippet.cpp
runtime/compiler/p/codegen/J9UnresolvedDataSnippet.cpp

Fix AIX warnings concerning values with type `int16_t` that are too small to be pointers being cast into pointers of type `(uint8_t *)` by adding an intermediate cast to `uintptr_t`.

Add intermediate casts so values are large enough for pointer cast

---

runtime/compiler/p/codegen/PPCRecompilation.cpp
runtime/compiler/runtime/JitRuntime.cpp

Fix AIX warnings concerning integers being shifted beyond the width of their type by casting them (or removing casts) so that they can accommodate the shifts. Additional fixes in [omr #7134](https://github.com/eclipse/omr/pull/7134).

Fix casts to ensure variables are wide enough to accommodate shifts

---

doc/compiler/control/OptionsPostRestore.md
runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/HookedByTheJit.cpp

* Coordinate the Sampler Thread across a Checkpoint/Restore
* Reset the Start and Elapsed Time in the Restore Hook
Part of https://github.com/eclipse-openj9/openj9/issues/16853

Coordinate Sampler Thread across a Checkpoint/Restore

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/DLLMain.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/ilgen/IlGenerator.cpp
runtime/compiler/ilgen/J9ByteCodeIlGenerator.hpp
runtime/compiler/ilgen/Walker.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/ras/kca_offsets_generator.cpp
runtime/compiler/runtime/ClassUnloadAssumption.cpp
runtime/compiler/runtime/IProfiler.cpp
runtime/compiler/runtime/J9CodeCacheManager.cpp
runtime/compiler/runtime/J9Profiler.cpp
runtime/compiler/runtime/JitRuntime.cpp
runtime/compiler/runtime/RelocationRecord.cpp
runtime/compiler/runtime/RelocationRecord.hpp
runtime/compiler/runtime/RelocationRuntime.cpp
runtime/compiler/runtime/RelocationRuntime.hpp
runtime/compiler/runtime/RelocationRuntimeLogger.cpp
runtime/compiler/runtime/RelocationRuntimeLogger.hpp
runtime/compiler/runtime/RuntimeAssumptions.hpp

Work towards fixing AIX warnings about assigning string literals to non-const char pointers by adding 'const' qualifiers to some string variables and parameters (or worst case scenario, casting to (char *)) in compile, runtime, control, and ras.
**This PR depends on:**
- **Step 1:**
- https://github.com/eclipse-openj9/openj9/pull/18083
- https://github.com/eclipse-openj9/openj9/pull/18455
- **Step 2:**
- https://github.com/eclipse-openj9/openj9/pull/18467
- https://github.com/eclipse/omr/pull/7186
**and must be merged in coordination with https://github.com/eclipse/omr/pull/7187**

Fix string literal conversion warnings in ilgen, runtime, control, ras

---

runtime/compiler/codegen/CodeGenGPU.cpp
runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/codegen/J9CodeGenerator.hpp
runtime/compiler/il/J9DataTypes.cpp
runtime/compiler/il/J9DataTypes.hpp
runtime/compiler/il/J9Symbol.cpp
runtime/compiler/il/J9SymbolReference.cpp
runtime/compiler/runtime/RelocationRuntime.hpp

Work towards fixing AIX warnings about assigning string literals to non-const char pointers by adding 'const' qualifiers to some string variables and parameters (or worst case scenario, casting to `(char *)`) in runtime/compiler/codegen and runtime/compiler/il.
**This PR must be merged in coordination with https://github.com/eclipse/omr/pull/7185**

Fix string literal conversion warnings in codegen and il

---

test/functional/cmdLineTests/criu/playlist.xml

Re-enable criu_nonPortableRestore tests on s390x as the 
test labels were removed from the internal IBM s390x 
machines that seem to have CRIU setup incorrectly.
Issue: https://github.com/eclipse-openj9/openj9/issues/18570

(0.43) Re-enable criu_nonPortableRestore tests on s390x

---

test/functional/cmdLineTests/criu/playlist.xml

Re-enable criu_nonPortableRestore tests on s390x as the 
test labels were removed from the internal IBM s390x 
machines that seem to have CRIU setup incorrectly.
Issue: https://github.com/eclipse-openj9/openj9/issues/18570

Re-enable criu_nonPortableRestore tests on s390x

---

runtime/jvmti/jvmtiClass.c
runtime/oti/j9nonbuilder.h
runtime/vm/VMAccess.cpp

This is to prevent requestExclusiveVMAccessMetronomeTemp (used from alarm thread) from blocking if exclusive VM access is already requested prior to calling a system GC. This prevention
(synchronizeRequestsFromExternalThread) already works for plain exclusive, but not if safePoint is acquired (since it does not set exclusiveAccessState to J9_XACCESS_EXCLUSIVE).
While proper solution might be around fixing
synchronizeRequestsFromExternalThread to account for safePointState and how exclusiveAccessState is changed during safePoint acquire, it would require more time to get it right.
This solution is a workaround where there is an additional flag that is to be set by after safePoint is acquired and before GC is invoked. That flag will be checked by requestExclusiveVMAccessMetronomeTemp before …

Prevent requesting exclusive, if already acquired

---

doc/build-instructions/Build_Instructions_V11.md
doc/build-instructions/Build_Instructions_V17.md
doc/build-instructions/Build_Instructions_V21.md
doc/build-instructions/Build_Instructions_V8.md

Build for AArch64 macOS requires the option --with-noncompressedrefs until the platform supports compressed references.

Add --with-noncompressedrefs for AArch64 macOS in Build Instructions

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/runtime/J9Runtime.hpp

Reverts eclipse-openj9/openj9#18269 due to issue #18626

Revert "Fix implicit conversion causing truncation warnings"

---

runtime/jvmti/jvmtiClass.c
runtime/oti/j9nonbuilder.h
runtime/vm/VMAccess.cpp

Propagation of https://github.com/eclipse-openj9/openj9/pull/18606

(0.42) Prevent requesting exclusive, if already acquired

---

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit implements a vectorized version of JITHelpers.intrinsicIndexOfLatin1 and intrinsicIndexOfUTF16 on AArch64 codegen.
Depends on https://github.com/eclipse/omr/pull/7203.

AArch64: Add vectorized implementation of intrinsicIndexOf helper functions

---

runtime/compiler/optimizer/DataAccessAccelerator.cpp
runtime/compiler/optimizer/EscapeAnalysis.cpp
runtime/compiler/optimizer/EscapeAnalysis.hpp
runtime/compiler/optimizer/IdiomRecognition.cpp
runtime/compiler/optimizer/IdiomRecognition.hpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9Inliner.cpp
runtime/compiler/optimizer/J9ValuePropagation.cpp
runtime/compiler/optimizer/SignExtendLoads.cpp
runtime/compiler/optimizer/StringPeepholes.cpp
runtime/compiler/optimizer/VPBCDConstraint.cpp
runtime/compiler/optimizer/VPBCDConstraint.hpp
runtime/compiler/p/codegen/CallSnippet.cpp
runtime/compiler/p/codegen/ForceRecompilationSnippet.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/p/codegen/J9UnresolvedDataSnippet.cpp
runtime/compiler/p/codegen/PPCRecompilationSnippet.cpp
runtime/compiler/p/codegen/StackCheckFailureSnippet.cpp
runtime/compiler/p/runtime/PPCHWProfilerAIX.cpp

Work towards fixing AIX warnings about assigning string literals to non-const char pointers by adding 'const' qualifiers to some string variables and parameters (or worst case scenario, casting to (char *)) in optimizer and p.
This PR contributes to (but does not close) https://github.com/eclipse-openj9/openj9/issues/14859
**This PR depends on:**
- **Step 1:**
- https://github.com/eclipse-openj9/openj9/pull/18083
- https://github.com/eclipse-openj9/openj9/pull/18455
- **Step 2:**
- https://github.com/eclipse-openj9/openj9/pull/18467
- https://github.com/eclipse/omr/pull/7186
- **Step 3:**
- https://github.com/eclipse-openj9/openj9/pull/18470
- https://github.com/eclipse/omr/pull/7187

Fix string literal conversion warnings in optimizer, p

---

runtime/gc_modron_startup/mminit.cpp
runtime/gc_modron_startup/mmparse.cpp
runtime/gc_modron_startup/mmparseXgc.cpp

Set gcThreadCountSpecified if either -Xgcthreads or -Xgcmaxthreads is specified, and use gcThreadCountForced to distinguish between the 2 options. This is a part of the fix that will allow -Xgcmaxthreads to work as expected (another OMR change is needed to make use of now properly set gcThreadCountSpecified flag).
Aslo, allow -Xgcmaxthreads to be specified on restore VM too, and make sure that whichever is the last one wins (in any combination of those 2 options being or not beign specified on snapshot or restore side). Parsing of -Xgcmaxthreads handles it, since it's the latter one that gets processed in the code.
There is also a change in behavior for restore VM. Previosly, if -Xgcthreads was specified on snapshot side, it would be ignored on restore side and the thread count would be …

Set gcThreadCountSpecified and allow -Xgcmaxthreads for restore VM

---

runtime/vm/ContinuationHelpers.cpp

-Replace `do_{_if_(condition)_{_..._continute;_}_}while_{false};` with
`for(;;)_{_if_(condition)_{...}_else{break;_}_}` for an infinite loop
with a break logic to handle waiting concurrent gc finish during
continuation mounting. compiler might generate wrong logic for
do_while infinite loop.
-fix small hole during mounting synchronization with concurrent
scanning(for the case concurrent scanning start just before resetting
pendingmount flag-before reading the value of state for atomic update)
- new assertion check for catching issue earlier.
fix: https://github.com/eclipse-openj9/openj9/issues/16728#issuecomment-1843799810 [ISSUE3]

Fix PowerPC specific issues

---

runtime/vm/ContinuationHelpers.cpp

-Replace do_{_if_(condition)_{_..._continute;_}_}while_{false}; with
for(;;)_{_if_(condition)_{...}_else{break;_}_} for an infinite loop
with a break logic to handle waiting concurrent gc finish during
continuation mounting. compiler might generate wrong logic for
do_while infinite loop.
-fix small hole during mounting synchronization with concurrent
scanning(for the case concurrent scanning start just before resetting
pendingmount flag-before reading the value of state for atomic update)
- new assertion check for catching issue earlier.
Port of https://github.com/eclipse-openj9/openj9/pull/18637 for 0.42

(0.42) Fix PowerPC specific issues

---

runtime/vm/ContinuationHelpers.cpp

-Replace do_{_if_(condition)_{_..._continute;_}_}while_{false}; with
for(;;)_{_if_(condition)_{...}_else{break;_}_} for an infinite loop
with a break logic to handle waiting concurrent gc finish during
continuation mounting. compiler might generate wrong logic for
do_while infinite loop.
-fix small hole during mounting synchronization with concurrent
scanning(for the case concurrent scanning start just before resetting
pendingmount flag-before reading the value of state for atomic update)
- new assertion check for catching issue earlier.
Port of https://github.com/eclipse-openj9/openj9/pull/18637 for 0.43

(0.43) Fix PowerPC specific issues

---

runtime/vm/ContinuationHelpers.cpp

Currently, recycled continuations are reset and initialized in
`freeContinuation` at the end of their use. There are also gaps where
the recycled continuation might retain old values and not be properly
reset.
The above approach leads to corruption and segfaults as seen in
the `runJavaThread` failure reported in #16728.
To fix the above crash, all continuations (new and recycled) are
initialized and reset in `createContinuation` just before the
continuation begins execution.
Related: #16728

Initialize recycled continuations in createContinuation before usage

---

runtime/vm/ContinuationHelpers.cpp

Currently, recycled continuations are reset and initialized in
`freeContinuation` at the end of their use. There are also gaps where
the recycled continuation might retain old values and not be properly
reset.
The above approach leads to corruption and segfaults as seen in
the `runJavaThread` failure reported in #16728.
To fix the above crash, all continuations (new and recycled) are
initialized and reset in `createContinuation` just before the
continuation begins execution.
Related: #16728

(0.42) Initialize recycled continuations in createContinuation before usage

---

runtime/vm/ContinuationHelpers.cpp

Currently, recycled continuations are reset and initialized in
`freeContinuation` at the end of their use. There are also gaps where
the recycled continuation might retain old values and not be properly
reset.
The above approach leads to corruption and segfaults as seen in
the `runJavaThread` failure reported in #16728.
To fix the above crash, all continuations (new and recycled) are
initialized and reset in `createContinuation` just before the
continuation begins execution.
Related: #16728

(0.43) Initialize recycled continuations in createContinuation before usage

---

runtime/j9vm/exports.cmake
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/javanextvmi.cpp
runtime/redirector/forwarders.m4

JDK next adds `JVM_VirtualThreadDisableSuspend`
This fixes JDK next abuild failure https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_OpenJDK/446/consoleFull
```
23:44:10  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/native/java.base/libjava/VirtualThread.o:(.data.rel+0x88): undefined reference to `JVM_VirtualThreadDisableSuspend'
23:44:10  collect2: error: ld returned 1 exit status
```

JDK next adds JVM_VirtualThreadDisableSuspend

---

runtime/j9vm/exports.cmake
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/javanextvmi.cpp
runtime/j9vm/module.xml
runtime/redirector/forwarders.m4
runtime/redirector/module.xml

`JDK23` adds `JVM_VirtualThreadDisableSuspend`
`JVM_VirtualThreadDisableSuspend` was added for `JDK23` instead.
Related to 
* https://github.com/eclipse-openj9/openj9/pull/18663#issuecomment-1865175406

JDK23 adds JVM_VirtualThreadDisableSuspend

---

buildenv/jenkins/common/build.groovy

This allows the `GSKit` binaries to be downloaded from `Artifactory`, using the appropriate credentials, during the `OpenJDK` build process.
Signed-off by: Kostas Tsiounis [kostas.tsiounis@ibm.com](mailto:kostas.tsiounis@ibm.com)

Use credentials to load GSKit binaries from Artifactory

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/optimizer/EscapeAnalysis.cpp

AOT now takes care of generating the `TR_Inlined*Method` relocations for inlined methods without corresponding guards, so we can remove guards without creating stand-ins.

Delete now-unnecessary TR_Removed*Guard guard kinds

---

runtime/jvmti/jvmtiHelpers.cpp

Inconsistent indentation noticed in #18660.

Fix indentation, whitespace and comment folding

---

runtime/compiler/runtime/JITClientSession.cpp

The JITServer expects that the shared ROM class cache will have been initialized only if the `_clientSessionMap` is empty.
Fixes #18631.

Shut down ROM class cache if purging all clients

---

runtime/makelib/targets.mk.linux.inc.ftl

This makes UMA builds consistent with cmake builds.

UMA: Use DWARF version 4 on Linux

---

runtime/jvmti/jvmtiHook.c

This will fix the crash in #18621.
Co-authored-by: Graham Chapman <graham_chapman@ca.ibm.com>
Co-authored-by: Babneet Singh <sbabneet@ca.ibm.com>

Add a NULL check on threadObject in destroyThreadData

---

runtime/jvmti/jvmtiHook.c

This will fix the crash in #18621.
Backport of https://github.com/eclipse-openj9/openj9/pull/18688.
Co-authored-by: Graham Chapman [graham_chapman@ca.ibm.com](mailto:graham_chapman@ca.ibm.com)
Co-authored-by: Babneet Singh [sbabneet@ca.ibm.com](mailto:sbabneet@ca.ibm.com)

(0.42) Add a NULL check on threadObject in destroyThreadData

---

runtime/jvmti/jvmtiHook.c

This will fix the crash in #18621.
Backport of https://github.com/eclipse-openj9/openj9/pull/18688.
Co-authored-by: Graham Chapman [graham_chapman@ca.ibm.com](mailto:graham_chapman@ca.ibm.com)
Co-authored-by: Babneet Singh [sbabneet@ca.ibm.com](mailto:sbabneet@ca.ibm.com)

(0.43) Add a NULL check on threadObject in destroyThreadData

---

test/functional/cmdLineTests/jvmtitests/jvmtitests_hcr.xml

The test fails regularly and fixing it is in the backlog.
Issue https://github.com/eclipse-openj9/openj9/issues/14115
Tested via https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3159 the test runs but rc021 does not.

Exclude jvmtitests_hcr rc021

---

runtime/makelib/targets.mk.ftl

As part of a Pull Request in the OMR Repository it was realized that J9ZTPF guard macros should not be used in the OMR Repository.   Instead, as part of building OMR with OpenJ9 for z/TPF that the OMRZTPF guard macro should be turned on in the OpenJ9 build for z/TPF.
This pull request is simply proposing we define OMRZTPF in the runtime/makelib/targets.mk.ftl for the z/TPF spec only.

Need to define OMRZTPF guard macro to openJ9 UMA build for z/TPF

---

runtime/oti/j9dump.h
runtime/oti/jvminit.h
runtime/rasdump/dmpsup.c
runtime/rasdump/javadump.cpp

Add -XX:[+|-]ShowUnmountedThreadStacks option
Refactor RasDumpGlobalStorage.showNativeSymbols field into a bit flag dumpFlags
Add new J9RAS_JAVADUMP_SHOW_UNMOUNTED_THREAD_STACKS bit flag

Add Unmounted Thread info to javacore

---

runtime/oti/j9dump.h
runtime/oti/jvminit.h
runtime/rasdump/dmpsup.c
runtime/rasdump/javadump.cpp

Refactor RasDumpGlobalStorage.showNativeSymbols field into a bit flag dumpFlags Add new J9RAS_JAVADUMP_SHOW_UNMOUNTED_THREAD_STACKS bit flag
Add VThread info to javacore
- Fix writeThreadName API to correctly reflect mounted virtual thread name
- Add new tag for virtual thread related info
- Move get VThread name code inside j9sig_protect call
Port of https://github.com/eclipse-openj9/openj9/pull/18218

(0.43) Add -XX:[+|-]ShowUnmountedThreadStacks option

---

jcl/src/java.base/share/classes/java/lang/PinnedThreadPrinter.java

`JDK23` adds `PinnedThreadPrinter.(out, reason, printAll)`
Added `static void printStackTrace(PrintStream out, Continuation.Pinned reason, boolean printAll)`
closes https://github.com/eclipse-openj9/openj9/issues/18715

JDK23 adds PinnedThreadPrinter.(out, reason, printAll)

---

runtime/bcutil/ROMClassBuilder.cpp
runtime/bcutil/defineclass.c

In JDK22, `MethodHandleProxies.asInterfaceInstance` was reimplemented
using a more direct `MethodHandle` approach to improve performance.
This approach introduces hidden classes which have an interface for
its host class.
In this case, the hidden and host class don't need to exist in the
same package, and they can have different packages.
Two operations have been updated to accommodate the above changes:
**[1]** In `ROMClassBuilder::handleAnonClassName`, the host class's package
is not appended to the hidden class if the class name already has a
package.
**[2]** In `internalDefineClass`, hidden and host class are allowed to have
different package names if the host class is an interface.
**[1]** solves the `NoClassDefFoundError` seen in the below issues:
- #18694
- #18698
- #18699
- #18700 …

Support reimplemented MethodHandleProxies.asInterfaceInstance

---

runtime/util/romclasswalk.c

If a ROM class has no methods, the CP NAS section should have size zero. Before, the section size would be calculated unconditionally based on the location of the `J9ROMCLASS_ROMMETHODS` of the ROM class. When the `romMethods` field is a null SRP, that would result in a negative pointer difference that would then wrap to a very large `U_32` value.
Signed-off-by: Christian Despres

Fix erroneously large section size in ROM walk

---

runtime/util/romclasswalk.c

The allSlotsInROMClassDo() function now visits every slot in a J9ROMClass header.

Visit certain unvisited ROMClass header slots

---

jcl/src/java.base/share/classes/java/lang/Access.java

`JDK23` `Thread.blockedOn(Interruptible)` changed to `static`
required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/723

JDK23 Thread.blockedOn(Interruptible) changed to static

---

jcl/src/java.base/share/classes/java/lang/Class.java

It was part of a preview feature that is not present in Java 22+.
See:
* https://bugs.openjdk.org/browse/JDK-8319044
* https://github.com/ibmruntimes/openj9-openjdk-jdk22/commit/fbb1f0a307c9ef2e3def4f689a4792d9ccf581ad

Remove Class.isUnnamedClass() from Java 22+

---

debugtools/DDR_VM/src/com/ibm/j9ddr/tools/ddrinteractive/commands/TraceFileHeaderWriter.java

Recognize AArch64 and RISC-V in DDR TraceFileHeaderWriter

---

runtime/compiler/control/HookedByTheJit.cpp

PR #18356 introduced a change to reduce the counts of a method whose class is not in the shared class cache (SCC), if SCC is enabled and the load of that class happens during start-up. This change improves performance of some short running benchmarks from the DaCapo suite (when run with default options), but was discovered to also cause a small (2-3%) throughput regression when running the Daytrader benchmark on top of tWAS.
This commit restricts the change from PR #18356 to just environments that use an implicit SCC (by default, OpenJ9 creates an implict SCC that is only allowed to to store bootstrap classes).

Reduce counts only for implict SCC

---

test/functional/cmdLineTests/valuetypeddrtests/build.xml
test/functional/cmdLineTests/valuetypeddrtests/playlist.xml

related: https://github.com/eclipse-openj9/openj9/pull/18597#issuecomment-1885142840

Fix asm.jar path mismatch in valuetype tests

---

runtime/j9vm/exports.cmake
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/javanextvmi.cpp
runtime/j9vm/module.xml
runtime/redirector/forwarders.m4

The function will be needed in the next jdk22 build; see
* [8311218: fatal error: stuck in JvmtiVTMSTransitionDisabler::VTMS_transition_disable](https://github.com/ibmruntimes/openj9-openjdk-jdk22/commit/a5df744ebd27e3798a2026cc6fda50edb09e16f9)
The back-port to jdk22 was anticipated in https://github.com/eclipse-openj9/openj9/issues/18671.

Make JVM_VirtualThreadDisableSuspend() available for jdk22

---

runtime/compiler/optimizer/J9Simplifier.cpp

Tree Simplification recognizes an indirect load that gets a `java/lang/Class` from a `j9Class` pointer, and then gets the `j9Class` pointer from that `java/lang/Class`, can be simplified to refer to the original `j9Class` pointer itself.  However, that introduces an `l2a` operation which causes problems for Code Generation's `l2aEvaluators`, as they assume that `l2a` operations are only used for compressed references.  Until the two different kinds of conversions of integers to addresses can be distinguished from one another &mdash; as described in eclipse/omr#6508 &mdash; this transformation in Tree Simplification will be disabled.

Disable simplifying j9Class to j.l.Class to j9Class

---

runtime/compiler/optimizer/J9Simplifier.cpp

Tree Simplification recognizes an indirect load that gets a `java/lang/Class` from a `j9Class` pointer, and then gets the `j9Class` pointer from that `java/lang/Class`, can be simplified to refer to the original `j9Class` pointer itself.  However, that introduces an `l2a` operation which causes problems for Code Generation's `l2aEvaluators`, as they assume that `l2a` operations are only used for compressed references.  Until the two different kinds of conversions of integers to addresses can be distinguished from one another &mdash; as described in eclipse/omr#6508 &mdash; this transformation in Tree Simplification will be disabled.
This delivers the contents of pull request #18743 to the 0.43.0-release branch.

[0.43.0] Disable simplifying j9Class to j.l.Class to j9Class

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/J9ObjectFieldOffsetIterator_V1.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/ObjectFieldInfo.java
runtime/vm/createramclass.cpp
test/functional/Valhalla/playlist.xml
test/functional/cmdLineTests/valuetypeddrtests/flattened32bitRefBackfillTest.xml
test/functional/cmdLineTests/valuetypeddrtests/flattenedvaluetypeddrtests_lw5.xml
test/functional/cmdLineTests/valuetypeddrtests/unflattenedvaluetypeddrtests.xml

- Create copy flattenedvaluetypeddrtests
- Modify valuetypeddrtests to work with lw5
- Add checks for lw5 attributes to ddr and vm
The lw5 tests can be run manually by including changes from https://github.com/eclipse-openj9/openj9/pull/18558 and using a build of https://github.com/openjdk/valhalla/tree/lw5 as `TEST_JDK_HOME` while running `make compile`

valuetypeddrtests with Valhalla lw5

---

runtime/jvmti/jvmtiClass.c

Eliminating dark matter before determining classes to recreate prevents
dying and unloaded classes to be encountered while recreating RAM
classes.
Related: #18750

Eliminate dark matter before determining classes to recreate

---

runtime/jvmti/jvmtiClass.c

Eliminating dark matter before determining classes to recreate prevents
dying and unloaded classes to be encountered while recreating RAM
classes.
Port of #18752
Fixes: #18750

(0.43) Eliminate dark matter before determining classes to recreate

---

runtime/compiler/ilgen/Walker.cpp
test/functional/Valhalla/playlist.xml

There is a corner case where the flattened field count can be 0. For example,
```
class B {}
class A {
B field;
}
```
If `field` is flattened in class A, the flattened field count in `TR::TypeLayout` for A is 0 in this case.
The spec on `putfield` requires
- NPE is thrown if object ref is null
- NPE is thrown if the field is null restricted field and the value being stored is null
Fixes: #18742

Check null value and null object ref in zero flattened field count

---

test/functional/cmdLineTests/criu/criu_nonPortable.xml

Generate core file when testMXBeanUpTime fails due to a 
timeout during checkpoint to know if a thread is blocked 
while it is running checkpoint unsafe code. The test 
failure is not reproducible locally or in a grinder.
Issue: https://github.com/eclipse-openj9/openj9/issues/18670

Generate core file when testMXBeanUpTime fails

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp

This avoids asserts in `TR_LowPriorityCompQueue::incStatsReqQueuedToLPQ` and `TR_LowPriorityCompQueue::incStatsCompFromLPQ` triggering.
Fixes: #18727

Add stat tracking for JITServer LPQ compilations

---

buildenv/jenkins/variables/defaults.yml

See also https://github.com/eclipse-openj9/openj9/pull/18766

(0.43) Use jdk21 to build jdk21 and later versions

---

jcl/src/java.base/share/classes/java/lang/System.java

The OpenJDK change was added in 21.0.2
Related to
https://github.com/eclipse-openj9/openj9/pull/18406
https://github.com/ibmruntimes/openj9-openjdk-jdk21/commit/dd964e7a71b
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/18768 for 0.43

(0.43) Don't cache instances of TemporaryLoggerFinder for jdk21

---

jcl/src/java.base/share/classes/java/lang/PinnedThreadPrinter.java

Extend #18716 to Java 22.
Acceptance build is failing (e.g. https://openj9-jenkins.osuosl.org/job/Build_JDK22_x86-64_linux_OpenJDK22/27):
```
[2024-01-19T04:30:05.994Z] /home/jenkins/workspace/Build_JDK22_x86-64_linux_OpenJDK22/src/java.base/share/classes/java/lang/VirtualThread.java:205: error: method printStackTrace in class PinnedThreadPrinter cannot be applied to given types;
[2024-01-19T04:30:05.994Z]                     PinnedThreadPrinter.printStackTrace(System.out, reason, printAll);
[2024-01-19T04:30:05.994Z]                                        ^
[2024-01-19T04:30:05.994Z]   required: PrintStream,boolean
[2024-01-19T04:30:05.994Z]   found:    PrintStream,Pinned,boolean
[2024-01-19T04:30:05.994Z]   reason: actual and formal argument lists differ in length
```

JDK22 adds PinnedThreadPrinter.printStackTrace(out, reason, printAll)

---

jcl/src/java.base/share/classes/java/lang/System.java

The OpenJDK change was added in 21.0.2
Related to
https://github.com/eclipse-openj9/openj9/pull/18406
https://github.com/ibmruntimes/openj9-openjdk-jdk21/commit/dd964e7a71b
openj9-staging needs to be promoted when this is merged.

Don't cache instances of TemporaryLoggerFinder for jdk21

---

doc/release-notes/0.42/0.42.md

https://github.com/eclipse-openj9/openj9-docs/issues/1244
0.42.0 release note updated with the new option -XX:[+|-]CRIUSecProvider
[skip ci]

0.42.0 Release note updated -XX:[+|-]CRIUSecProvider option

---

runtime/jcl/common/jclreflect.c
runtime/jvmti/jvmtiHeap.c
runtime/vm/KeyHashTable.c
runtime/vm/stringhelpers.cpp

Cast `J9JAVAARRAYOFBYTE_LOAD()` to `U_8` where appropriate.
Fixes: #18791.

Fix interpretation of compressed strings

---

runtime/jcl/common/jclreflect.c
runtime/jvmti/jvmtiHeap.c
runtime/vm/KeyHashTable.c
runtime/vm/stringhelpers.cpp

Cherry-pick https://github.com/eclipse-openj9/openj9/pull/18797 for the 0.43.0 release.

(0.43) Fix interpretation of compressed strings

---

runtime/compiler/runtime/JITClientSession.cpp

In #18656, I did not check to see if any clients were actually deleted in the purge operation. If none were, then the shared ROM class cache would necessarily have been shut down already. Attempting to shut it down again would lead to a segfault. Checking if the purge operation was responsible for deleting the last clients before shutting down the shared ROM class cache avoids this issue.
Attn @mpirvu.

Ensure ROM class cache shutdown is necessary

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/runtime/J9ValueProfiler.hpp

This PR fixes two bugs relating to inlining that prevented the inlining of clearly beneficial candidates.
Previously, if the linked list in `TR_LinkedListProfilerInfo` contained two
nodes, then adding a third one would result in a memory leak as the
third node was not added to the end of the list, but rather as the next
node of the first node. This meant that there was no longer any pointer
to the original second node in the list. This PR fixes this by ensuring 
that a new node is always added to the end of the list.
The estimated code size of methods can be negative; this is to indicate
that the method is a good candidate for inlinling. However, the logic in
weighCallSite, which contains several heuristics that adjust the size of
a candidate method, used a variable of type uint32_t.
The …

Fix Inlining Bugs

---

runtime/vm/createramclass.cpp

In JDK22, `MethodHandleProxies.asInterfaceInstance` was reimplemented
using a more direct `MethodHandle` approach to improve performance.
This approach introduces hidden classes which have an interface for
its host class. A dynamic module is created for each such hidden
class. This PR correctly finds and sets `java.lang.Class.module` for
such hidden classes.
Fixes: #18718

Find modules for MHProxies.asInterfaceInstance's hidden classes

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/runtime/IProfiler.cpp
runtime/compiler/runtime/IProfiler.hpp

* Update the IProfiler to use a Lifetime State rather than a special buffer to indicate shutdown
* Coordinate the IProfiler Thread across a Checkpoint/Restore
* Allow the IProfiler thread to finish processing all outstanding buffers prior to suspending itself
Part of https://github.com/eclipse-openj9/openj9/issues/16853

Coordinate IProfiler Thread across a Checkpoint/Restore

---

runtime/j9vm/javanextvmi.cpp
runtime/redirector/forwarders.m4

In jdk23+ these now implement static methods:
* `JVM_VirtualThreadDisableSuspend()`
* `JVM_VirtualThreadHideFrames()`
See https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/b219248e70dda501605ae717ac12a5b171bddb5b.

Update signature of virtual thread support functions for jdk23+

---

runtime/bcutil/ROMClassBuilder.cpp
runtime/bcutil/ROMClassCreationContext.hpp
runtime/jcl/common/jcldefine.c

This patch fixes eclipse-openj9/openj9#18757.
In JDK8 and JDK11 with OpenJDK MethodHandles, MH creation uses defineAnonymousClass which passes a null class name downstream for ROM class creation. The previous check and flag-setting indicating that LambdaForms should not be held in the SCC relies on a class name being non-null. This patch pushes further downstream the flag-setting for omitting LambdaForms from the SCC to ensure that the class name is known (non-null) and available for comparison.
Issues: eclipse-openj9/openj9#18757

Do not add LambdaForm classes to SCC with OJDK MHs

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/J9ObjectModel.cpp
runtime/compiler/env/J9ObjectModel.hpp
runtime/compiler/optimizer/J9TransformUtil.cpp
runtime/compiler/optimizer/J9TransformUtil.hpp
runtime/compiler/runtime/JITClientSession.hpp
runtime/gc/gctable.c
runtime/gc_base/gc_internal.h
runtime/gc_modron_startup/mmhelpers.cpp
runtime/oti/j9nonbuilder.h

Add helper functions to generate IL for array access and queries to check if off heap allocation is enabled. This includes minimum set of off heap changes needed to unblock https://github.com/eclipse-openj9/openj9/pull/17969. 
depends on https://github.com/eclipse/omr/pull/7150

Add helper functions for off heap technology changes

---

jcl/src/jdk.management/share/classes/com/ibm/lang/management/JvmCpuMonitorMXBean.java
jcl/src/jdk.management/share/classes/com/ibm/lang/management/OperatingSystemMXBean.java
jcl/src/jdk.management/share/classes/com/ibm/virtualization/management/GuestOSMXBean.java
jcl/src/jdk.management/share/classes/com/ibm/virtualization/management/HypervisorMXBean.java
jcl/src/jdk.management/share/classes/openj9/lang/management/OpenJ9DiagnosticsMXBean.java

The tables have no headers, which is an accessibility check violation.

Remove javadoc tables used for code examples

---

runtime/compiler/env/j9methodServer.cpp

Methods that are annotated with @ChangesCurrentThread may receive special treatment from the inliner. This is a feature present only in Java21 and up. When creating a resolvedMethod mirror, the client retrieves the information related to @ChangesCurrentThread annotation and packs it into the message sent back to the server. Current code contained a bug where the information related to this annotation is not unpacked at the server. The net effect was that the inliner refused to inline some methods, reducing throughput. This commit rectifies the problem, by correctly unpacking the information related to the ChangesCurrentThread annotation.

Fix JITServer bug related to ChangesCurrentThread annotation

---

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/codegen/J9AheadOfTimeCompile.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/env/SharedCache.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/runtime/IProfiler.cpp
runtime/compiler/runtime/JITServerAOTDeserializer.cpp

The high-level shared class cache interface currently supports a number of queries like
https://github.com/eclipse-openj9/openj9/blob/d15ef63fcb72fc518415b4e4ee96c479002b2695/runtime/compiler/env/J9SharedCache.cpp#L716
These queries (`offsetInSharedCacheFromROMMethod` is another) are sometimes used directly, and sometimes form the basis of other queries like
https://github.com/eclipse-openj9/openj9/blob/d15ef63fcb72fc518415b4e4ee96c479002b2695/runtime/compiler/codegen/J9AheadOfTimeCompile.cpp#L155
A typical use of these methods is this:
https://github.com/eclipse-openj9/openj9/blob/d15ef63fcb72fc518415b4e4ee96c479002b2695/runtime/compiler/codegen/J9AheadOfTimeCompile.cpp#L552-L554
Whenever we use these methods we always have something like a `TR_OpaqueClassBlock *` (ultimately a `J9Class …

Modify SCC queries to take non-persistent parameters

---

jcl/src/jdk.management/share/classes/com/ibm/lang/management/JvmCpuMonitorMXBean.java
jcl/src/jdk.management/share/classes/com/ibm/lang/management/OperatingSystemMXBean.java
jcl/src/jdk.management/share/classes/com/ibm/virtualization/management/GuestOSMXBean.java
jcl/src/jdk.management/share/classes/com/ibm/virtualization/management/HypervisorMXBean.java
jcl/src/jdk.management/share/classes/openj9/lang/management/OpenJ9DiagnosticsMXBean.java

The tables have no headers, which is an accessibility check violation.
Cherry pick https://github.com/eclipse-openj9/openj9/pull/18826 for 0.43

(0.43) Remove javadoc tables used for code examples

---

test/functional/DDR_Test/src/j9vm/test/ddrext/SetupConfig.java
test/functional/DDR_Test/tck_ddrext.xml

Loading ImageFactory will export most of the packages needed.
Tested in https://openj9-jenkins.osuosl.org/job/Grinder/3194.

Remove the need for numerous '--add-exports=openj9.dtfj' options
