eclipse-openj9/openj9

jcl/src/java.base/share/classes/java/lang/Class.java
runtime/jcl/common/java_lang_Class.cpp

Unnamed classes permit main methods that are not public. The internal getMethodImpl only returns public methods, this needs to be updated.

Update internal getMethodHelpers unnamed classes

---

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/compile/AOTClassInfo.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/env/ClassLoaderTable.cpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/env/SharedCache.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/runtime/IProfiler.cpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp
runtime/compiler/runtime/JITServerAOTDeserializer.cpp
runtime/compiler/runtime/SymbolValidationManager.cpp
runtime/compiler/runtime/SymbolValidationManager.hpp

The `rememberClass` function now returns the offset to the class chain that it creates or finds in the local SCC, instead of returning the chain directly. Instead of returning `NULL` when class remembering fails, it now returns the value `0`. The offset of a class chain can never be zero in the local SCC, because that offset is always encoded with `encodeOffsetFromEnd` by `isPointerInSharedCache`, which means that the resulting value will always be odd:
https://github.com/eclipse-openj9/openj9/blob/c6df01b2e48aafb5305d6f26ab649c7c20e6b2dc/runtime/compiler/env/J9SharedCache.hpp#L363-L364
Various structures that previously stored class chain pointers now instead store offsets instead.

Modify rememberClass to return the offset to the class chain identifying the class

---

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/codegen/J9AheadOfTimeCompile.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/env/SharedCache.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/runtime/IProfiler.cpp
runtime/compiler/runtime/JITServerAOTDeserializer.cpp

This is a resubmission of #18821. These changes eliminate the direct use of `offsetInSharedCacheFromROMClass` during compilation in order to support #18301, as this query is difficult to fulfill using information available at the server when compiling for the JITServer AOT cache and a local SCC is not available.
The previous PR caused test failures because the method definition in that PR corresponding to this one here:
```
virtual bool isClassInSharedCache(J9Class *clazz, uintptr_t *cacheOffset = NULL)
{ return isClassInSharedCache(reinterpret_cast<TR_OpaqueClassBlock *>(clazz), cacheOffset); }
```
was 
```
virtual bool isClassInSharedCache(J9Class *clazz, uintptr_t *cacheOffset = NULL)
{ return isClassInSharedCache(reinterpret_cast<TR_OpaqueClassBlock *>(clazz)); }
```
which had the …

Modify SCC frontend to take class parameter

---

runtime/gc_vlhgc/CopyForwardScheme.cpp
runtime/gc_vlhgc/CopyScanCacheChunkVLHGCInHeap.cpp

For Balanced GC, min/max copy-cache size bounds used by GC threads for Copy-Forward caches are currently identical to min/max TLH size bounds used by mutator threads. This is rigid and problematic if we want to increase TLH sizes for large systems with large allocation rate, since too large copy-cache sizes may lead to suboptimal parallelism in GC.
Gencon's Scavenge already uses separate bounds, and this change will make Copy-Forward to use the same bounds as Scavenge (and also be able to use separate options to change the default values).
Default max size will remain unchanged - 128KB.
Default min size will increase to 8K from 768bytes, but this is a good change since 8K is already a tuned value, while too low value may cause too much activity/contention on the scan queue.

Detach copy-cache size bounds from TLH size bounds for Balanced

---

runtime/compiler/env/J9SharedCache.cpp

In rememberClass we must use isPointerInSharedCache in all circumstances to avoid a potential race condition where a chain has been stored successfully in the SCC but its offset is not yet available.

Use isPointerInSharedCache to avoid race condition

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/CompilationThread.hpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/J9PersistentInfo.hpp
runtime/compiler/runtime/JITServerAOTDeserializer.cpp
runtime/compiler/runtime/JITServerAOTDeserializer.hpp

Compilation threads must be able to detect whether or not a concurrent JITServer AOT cache deserializer reset has occurred during the course of deserializing a particular method. This check must be performed before any lookup or store operation involving the deserializer's internal caches. The methods of the deserializer now detect and report that such a reset has occurred by first acquiring the relevant deserializer monitor, checking the new _deserializerWasReset flag in the ongoing compilation's TR::CompilationInfoPerThread, and setting a &wasReset flag passed in to the method if such a reset occurred.
The _deserializerWasReset flag is set for every compilation thread by the thread doing the resetting, when it is guaranteed to have exclusive access to the deserializer's caches. Each …

Implement more robust deserializer reset detection

---

test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestThreadMXBean.java

Fixes https://github.com/eclipse-openj9/openj9/issues/18877
jdk11 and jdk17 need to be promoted when this is merged.
Tested via grinders, which passed.
11: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3205/
17: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3206/

Update TestThreadMXBean test for TotalThreadAllocatedBytes

---

runtime/gc_base/GCExtensions.hpp
runtime/gc_glue_java/ConfigurationDelegate.hpp
runtime/gc_modron_startup/mminit.cpp
runtime/gc_modron_startup/mmparse.cpp
runtime/nls/j9gc/j9modron.nls

CheckpointGCthreadCount conflicts with gcThread Warning
CheckpointGCthreadCount is expected to be no larger than
the number of gc threads.
We have two cases here:
1. If the user doesn't set the checkpointGCthreadCount,
the amount is adjusted to match the number of gc threads
2. If the user sets the checkpointGCthreadCount, a warning
is generated and the checkpointGCthreadCount is ignored
Signed off by: Frank.Kang@ibm.com

Warning when checkpointGCthreadCount conflicts with gcThread

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9ValuePropagation.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp

[Intrinsic methods for indexOf(char) in JITHelpers class](https://github.com/eclipse-openj9/openj9/blob/7bbeb0f43dcf2ac8677928512e1c134b14ae4f46/jcl/src/java.base/share/classes/com/ibm/jit/JITHelpers.java#L679-L712) is not used in JDK17+ because OpenJDK's `java/lang/String` class is used.
OpenJDK class library has intrinsic methods in `java/lang/StringLatin1` and `java/lang/StringUTF16` classes. The logic of those intrinsic methods are identical to those of JITHelpers class except that they are defined as static methods. This commit adds intrinsic methods of StringLatin1 and StringUTF16 to the recognized method table and update x/p/z/aarch64 codegen to generate the specialized instruction sequence which already exists for JITHelpers methods.
Related issue: …

Accelerate String.indexOf(char) in JDK17+

---

buildenv/jenkins/variables/defaults.yml

Tested jdk8 via https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/488/ where all of sanity/extended.functional,sanity/extended.system,sanity.openjdk passed.
```
15:09:24  * Toolchain:      xlc (IBM XL C/C++)
15:09:24  * C Compiler:     Version 16.1.0 (at /opt/IBM/xlC/16.1.0/bin/xlclang)
15:09:24  * C++ Compiler:   Version 16.1.0 (at /opt/IBM/xlC/16.1.0/bin/xlclang++)
```

Compile AIX jdk8 with xlclang 16.1

---

runtime/compiler/env/VMJ9.h
runtime/compiler/runtime/RelocationRuntime.cpp
runtime/compiler/runtime/RelocationRuntime.hpp

An alternate SCC frontend may now be passed to the relocation runtime, which will be used for the duration of relocation. This isn't directly useful, but #18301 will need this to override the shared class cache interface used during relocation.

Allow SCC to be overridden during relocation

---

runtime/vm/profilingbc.c

Currently flushForClassesUnload() is registred for J9HOOK_VM_CLASSES_UNLOAD and J9HOOK_VM_ANON_CLASSES_UNLOAD both. However it is not necessary, Anonymous classes are included to general classes unloaded report. So, there is enough to subscribe to J9HOOK_VM_CLASSES_UNLOAD only.

Preventing flushForClassesUnload() to be called twice

---

runtime/compiler/env/ClassLoaderTable.cpp
runtime/compiler/env/ClassLoaderTable.hpp
runtime/compiler/runtime/JITServerAOTDeserializer.cpp

The persistent class loader table will now track the name of the first-loaded class of particular class loaders whenever `getJITServerUseAOTCache()` is true, including when a local SCC is not present. If the ROM class of the first-loaded class happens to be shared, the table will save a pointer to its name in the local SCC. Otherwise, we create a persistent copy of the name.
A query function `lookupClassNameAssociatedWithClassLoader` has been added to look up only the class name associated to a class loader. Presently it is unused, but it will be useful in https://github.com/eclipse-openj9/openj9/pull/18301.
The `isROMClassInSharedCache` query function is now public. I was a little too ambitious making it private in https://github.com/eclipse-openj9/openj9/pull/18821 - it's still …

Support persistent class loader name tracking in all cases when JITServer AOT cache is active

---

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/codegen/J9AheadOfTimeCompile.hpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/env/SharedCache.hpp

The new `isMethodInSharedCache` method in the shared class cache API will determine whether or not the `J9ROMMethod` underlying a `J9Method` is in the SCC, and will return its offset to the caller through the `uintptr_t *offset` input if so. I added an `INVALID_ROM_METHOD_OFFSET` constant to parallel `INVALID_CLASS_CHAIN_OFFSET` as well, but it isn't used much at the moment.
The `isROMMethodInSharedCache` and `offsetInSharedCacheFromROMMethod` methods are now forbidden from being called at the server. These should only be called at a client, when working directly with the underlying shared classes implementation.
In future, as part of #18301, I will be overriding `isMethodInSharedCache` at the server so we can look up the offset of the server's `AOTCacheMethodRecord` using the `J9Method …

Modify SCC frontend to take method parameter

---

runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/env/SharedCache.hpp
runtime/compiler/runtime/IProfiler.cpp
runtime/compiler/runtime/RelocationRecord.cpp
runtime/compiler/runtime/SymbolValidationManager.cpp

The `lookupClassLoaderAssociatedWithClassChain(void *chain)` method attempts to find a `J9ClassLoader *` whose class chain (i.e., the class chain of its first loaded class) matches the given class chain. This new method is roughly analogous to the already-existing
```
virtual TR_OpaqueClassBlock *lookupClassFromChainAndLoader(uintptr_t *chainData, void *classLoader);
```
in the shared cache interface, which also looks up a dynamic JVM entity after being given some persistent data. For now, all it does is query the `persistentClassLoaderTable()` for the class loader associated to the class chain.
This is needed for #18301, since part of that PR involves overriding `void *pointerFromOffsetInSharedCache(uintptr_t offset)` so that instead of returning the class chain associated to a class …

Add class loader lookup method to SCC interface

---

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/codegen/J9AheadOfTimeCompile.hpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/runtime/JITServerAOTDeserializer.cpp
runtime/compiler/runtime/SymbolValidationManager.cpp
runtime/compiler/runtime/SymbolValidationManager.hpp

A new storeWellKnownClasses method in J9SharedCache is now responsible for storing a well-known classes object in the SCC.
The J9::AheadOfTimeCompile::offsetInSharedCacheFromPointer has been renamed offsetInSharedCacheFromWellKnownClasses, as getting the offset of the well-known classes object stored in the SVM is currently its sole responsibility.

Add explicit well-known classes SCC handling

---

runtime/vm/jnifield.cpp

For consistency, mask the boolean value (so it's 0 or 1) before calling the hook.
Related: #16498

Mask JNI boolean value earlier in setBooleanField

---

doc/release-notes/0.43/0.43.md

Support for this API is added on z/OS platforms in this release
[skip ci]

Support for com.sun.management.ThreadMXBean.getThreadAllocatedBytes()

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/runtime/RelocationRuntime.cpp
runtime/compiler/runtime/RelocationRuntime.hpp

A client will now send a `TR_AOTHeader` as part of its VM info whenever the AOT cache as been requested to be used. As we currently only create and enable the deserializer with a local SCC present, this should not change any current behaviour.
The new TR_RelocationRuntime::fillAOTHeader is responsible for filling in a new TR_AOTHeader. Actual allocation of this header is still handled by TR_SharedCacheRelocationRuntime::createAOTHeader.

Send AOT header to server whenever JITServer AOT cache is requested

---

test/functional/CacheManagement/src/tests/sharedclasses/TestUtils.java

CacheManagement test creates multiple shared caches. SimpleApp has a few classes only, so it is not necessary to run it with 300MB (default size) shared caches. Using 300MB could fail on machines running low on disk space.

Use a small shared cache size for SimpleApp in CacheManagement test

---

runtime/vm/CRIUHelpers.cpp

This patch fixes eclipse-openj9/openj9#18800.
When the CRIUSupport APIs were moved into java.base, the line that previously registered the j9criu module for tracing was not removed. Therefore, the j9vm module is being double registered, causing downstream effects in the tracing mechanism. This patch removes the registration during the CRIU API setup phase.
Issues: eclipse-openj9/openj9#18800

Avoid double module trace registration after CRIU move to java.base

---

jcl/src/java.base/share/classes/java/lang/StackWalker.java
runtime/jcl/common/java_lang_StackWalker.cpp

Add J9_GET_CALLER_CLASS flag to identify StackWalker.getCallerClass().
Fixes: #18697

Override -XX:+ShowHiddenFrames option in getCallerClass API

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java
jcl/src/java.base/share/classes/java/lang/System.java

This was previously attempted via
https://github.com/eclipse-openj9/openj9/pull/18402 but it didn't work for jdk8.
Fixes https://github.com/eclipse-openj9/openj9/issues/18900
Doc issue https://github.com/eclipse-openj9/openj9-docs/issues/1279
Created a jdk8 and 11 build with this change at https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/490/
Manually checked jdk8 and it's working.

jdk8 Ignore "allow" and "disallow" set in java.security.manager

---

doc/release-notes/0.43/0.43.md

Created the release note for 0.43.0 release. Added Windows builds compile update
[skip ci]

Release note for 0.43.0 release update

---

buildenv/jenkins/variables/defaults.yml

jdk21+ only supports macOS 11+. Since there is no test issue for jdk21 at the moment, jdk21 isn't excluded for testing on 10.15 machines in order to have more test machines available.
Closes https://github.com/eclipse-openj9/openj9/issues/18909

Avoid testing xmac jdk22+ on sw.os.mac.10_15

---

runtime/bcutil/ROMClassWriter.cpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/control/JITServerHelpers.hpp
runtime/compiler/runtime/JITServerAOTDeserializer.cpp

When ROM classes are packed to be sent to the JITServer, we now perform two additional transformations, in addition to the existing string inlining:
1. The return bytecodes in the ROM class are fixed up if the class is not shared.
2. Any inlined debug info is stripped from the ROM class
Both of these are necessary to ensure that the packed representations of shared and non-shared versions of the same ROM class are identical. Otherwise, the difference in representations will cause them to have different hashes, and that will effectively prevent us from sharing code between JITServer clients that have different mixes of shared and non-shared classes.

Modify ROMclass packing to normalize more

---

runtime/j9vm/asgct.cpp
runtime/oti/j9nonbuilder.h
runtime/vm/classallocation.c

Move the asyncGetCallTraceUsed flag from the J9JavaVM to J9ClassLoader so only methodIDs that have been handed out by AsyncGetCallTrace are retained.

Optimize AsyncGetCallTrace methodID retention

---

runtime/compiler/control/rossa.cpp
runtime/compiler/runtime/JITServerAOTDeserializer.cpp
runtime/compiler/runtime/JITServerAOTDeserializer.hpp

The JITServerAOTDeserializer is now two classes. The base JITServerAOTDeserializer defines some common operations and functionality, and the derived JITServerLocalSCCAOTDeserializer implements the required deserialization and caching.

Define a base and derived deserializer class

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/runtime/J9Runtime.hpp
runtime/compiler/runtime/MetaData.cpp
runtime/compiler/runtime/RelocationRuntime.cpp
test/functional/cmdLineTests/criu/playlist.xml

* Generate FSD code pre-checkpoint under `-XX:+DebugOnRestore`; reset to non-FSD code post-restore
* Add `-XX:+DebugOnRestore` variation for some CRIU tests

Generate FSD code pre-checkpoint under -XX:+DebugOnRestore

---

doc/release-notes/0.43/0.43.md

For the linux compiler updates, there were 2 more PRs. Updated the release note.
[skip ci]

Updated 0.43.0 release note-Additional PRs

---

jcl/src/java.base/share/classes/java/lang/System.java

`CRIU` adds `org.eclipse.openj9.criu.isCRaCCapable` for `CRAC_SUPPORT`
This provides a system property to determine if `CRaC` support is available.

CRIU adds org.eclipse.openj9.criu.isCRaCCapable for CRAC_SUPPORT

---

runtime/jvmti/jvmtiHelpers.cpp

New behaviour was noticed in JTREG `GetThreadStateMountedTest`.
An unmounted carrier thread is considered implicitly parked,
and all other bits except `ALIVE` and `SUSPENDED` are removed from
the bitmask.
Related: #18810

Update JVMTI GetThreadState for an unmounted carrier thread

---

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/compile/J9Compilation.hpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp
runtime/compiler/runtime/JITServerAOTSerializationRecords.hpp
runtime/compiler/runtime/SymbolValidationManager.cpp

A new `_useServerOffsets` field in `VMInfo` has been added. It will be set when a client wants its local SCC (whether or not it exists) to be ignored during JITServer AOT cache compilations. Currently the client always sets this field to false.
The methods of `TR_J9JITServerSharedCache` and the handling of the well-known classes object in the SVM and AOT relocation header initialization have been modified so that it we are compiling an AOT cache store and are ignoring the client's local SCC, we now consult the JITServer AOT cache and use the `idAndType` of its records in place of local SCC offsets.
Various client-server messages have been modified to accommodate the changes in server compilation. The client will either test for a local SCC before accessing it, or the server will send an …

Support ignoring the client's local SCC when compiling a JITServer AOT cache store

---

runtime/gc_vlhgc/MemorySubSpaceTarok.cpp

OMR's acquireExclusiveVMAccessForGC is about to stop calling
flushCachesForGC, so it will lose a parameter that controls it.
This change just removes that actual argument at the call site,
what is safe to due, since that actual value is exactly what
the default value is.

Remove flushCaches param from acquireExclusiveVMAccessForGC

---

runtime/oti/j9protos.h

It made reference to `MEMORY_TYPE_MASK` which is not defined.

Remove unused macro SEGMENT_TYPE

---

runtime/jcl/common/java_lang_StackWalker.cpp

Reverts eclipse-openj9/openj9#18926
Reverting due to https://github.com/eclipse-openj9/openj9/issues/18961

Revert "Fix StackWalker.walkWrapperImpl walkState structure access"

---

runtime/vm/MHInterpreter.hpp
runtime/vm/MHInterpreter.inc

Fix MethodHandle setting of static and instance fields to behave in the same way as bytecodes and JNI.
Related: #16498

Narrow 32 bit values when setting fields in MHInterpreter

---

runtime/compiler/optimizer/DynamicLiteralPool.cpp

In DynamicLiteralPool optimization, we add `aload` node denoting the address of literal base as a child of certain nodes when certain constant normalization is needed. For example, when OpenJ9 recognizes and inlines `floatToIntBits` or `doubleToLongBits`, it uses the fbits2i and dbits2l nodes respectively. Java specification requires those method to return normalize/canonical NaN value if the floating point operand is NaN. Dynamic Literal Pool optimization would attach an aload node denoting address of literal pool base to such nodes. In case when we are inlining `floatToRawIntBits` / `doubleToRawLongBits` , we are not required to return the normalize for of NaN for all NaN operands and simply return the raw bits representing floating point value. In such case, DynamicLiteralPool …

Check normalizedNaN flag on (d/f)bits2(l/i) nodes

---

runtime/jvmti/jvmtiThread.cpp
runtime/oti/j9nonbuilder.h

JVMTI InterruptThread needs to invoke j.l.VirtualThread.interrupt()
to interrupt a virtual thread as per the RI.
Related: #18810

Update JVMTI InterruptThread for virtual threads

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/control/rossa.h
runtime/compiler/env/ClassLoaderTable.cpp
runtime/compiler/env/ClassLoaderTable.hpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/exceptions/AOTFailure.hpp
runtime/compiler/runtime/JITServerAOTDeserializer.cpp
runtime/compiler/runtime/JITServerAOTDeserializer.hpp

The new `JITServerNoSCCAOTDeserializer` will deserialize methods received from the JITServer AOT cache without consulting the local SCC. It does this by following the procedure that the `JITServerLocalSCCAOTDeserializer` does, roughly - it resolves each type of record into a corresponding dynamic JVM entity, does a certain amount of validation of those entities, and caches those entities. In contrast to the existing deserializer, it will not store a persistent representation of those entities in the local SCC, and instead of updating the offsets in the relocation records of methods with local SCC offsets, it will instead update them with the `idAndType` of the serialization record associated to those offsets.
The `TR_J9DeserializerSharedCache` is a `TR_J9SharedCache` derived class that …

Implement a deserializer and shared cache interface that ignores the local SCC

---

runtime/jvmti/jvmtiThread.cpp

Introduced in https://github.com/eclipse-openj9/openj9/pull/18964.

Fix compile error for JAVA_SPEC_VERSION < 19

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/env/j9method.cpp

This commit introduces StringCoding.implEncodeAsciiArray (introduced in Java 17+) as a recognized method in the JIT compiler.

Recognize StringCoding.implEncodeAsciiArray in the JIT compiler

---

runtime/compiler/control/JITServerHelpers.cpp
runtime/oti/j9nonbuilder.h
runtime/util/romclasswalk.c

The content of the `varHandleMethodTypeLookupTable` is now walked in `allSlotsInROMClassDo`.
The relevant section of the ROM class writer code is here, I believe:
https://github.com/eclipse-openj9/openj9/blob/6a6d7afd73759f7bf4c786055bcb02bb35343030/runtime/bcutil/ROMClassWriter.cpp#L887-L910
I think the individual slots are `"cpIndex"`, but I'm unsure. I also made up the new section name `"varHandleMethodTypeLookupTable"`.
I also updated some of the documentation surrounding `JITServerHelpers::packROMClass`.
Fixes: https://github.com/eclipse-openj9/openj9/issues/18957

Add var handle method type lookup table walking

---

runtime/jcl/common/java_lang_StackWalker.cpp

After a thread's stackWalkState is used, we don't reset the fields to 0 but expects future code uses to set the parameters to the expected value before calling walkStackFrames.
This change fixes walkWrapperImpl where userData1 is not properly set.
Fixes: #18696 
Fixes: #18961

Correctly initialize walkState values when calling walkStackFrames

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/env/ClassLoaderTable.cpp
runtime/vm/jvminit.c

This fixes a build break on platforms that don't have JITServer enabled by default.

Protect JITServer code with `#if defined(J9VM_OPT_JITSERVER)`

---

runtime/j9vm/java11vmi.c

On all platforms, the messages would be lost, because either the first byte or the second byte is 0 (part of the 16-bit length field).
Also, add the missing final 'd' in "already been defined".

Fix bad casts from 'J9UTF8 *' to 'char *'

---

test/functional/JLM_Tests/build.xml

Exclude TestCRaCMXBean for jdk8 as CRAC_SUPPORT is not
enable for jdk8.
Issue: https://github.com/eclipse-openj9/openj9/issues/18842

Exclude TestCRaCMXBean for jdk8

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp

implEncodeAsciiArray is equivalent to Java 11's US_ASCII.encodeASCII converter method. Acceleration for this routine already exists in OMR. This commit introduces this routine to the JIT compiler.

Recognize java/lang/StringCoding.implEncodeAsciiArray

---

runtime/sunvmi/sunvmi.c

The serialization filter may be loaded by the extension classloader and this loader needs to be ignored when determining the latest user defined loader. jdk9+ already does this, although for jdk9+ it's called the platform classloader.

Ignore extension classloader in JVM_LatestUserDefinedLoader on jdk8

---

jcl/src/java.base/share/classes/openj9/internal/criu/InternalCRIUSupport.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/SystemCheckpointException.java
runtime/jcl/common/criu.cpp
runtime/oti/j9nonbuilder.h
runtime/oti/jclprots.h
runtime/oti/vm_api.h
runtime/vm/CRIUHelpers.cpp
test/functional/cmdLineTests/criu/cracScript.sh
test/functional/cmdLineTests/criu/criuScript.sh
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/CRIUTestUtils.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/TestGhostFile.java

Also fixed the criu_dump failure path, it was being hidden by calls to
query time.
Re-ordered the restore hooks so they always occur, even if criu_dump
fails.
Fixed the CRIUSupport exceptions which did not have the System version.
Updated tests to output log file if checkpoint fails.

Add ghost file limit API

---

runtime/compiler/il/J9MethodSymbol.cpp
runtime/compiler/il/J9MethodSymbol.hpp
runtime/compiler/ilgen/Walker.cpp

- Add a list of known methods that do not access flattened arrays
- Check in ILGen to avoid flattened array element load/store helper calls if the methods do not access flattened arrays
**Depends on**

Add and utilize methods that do not access flattened arrays

---

test/functional/JLM_Tests/playlist.xml

Exclude testCRaCMXBean for ibm builds as vmfarm uses a
fixed TKG version, which does not have the CRAC change.
Issue: https://github.com/eclipse-openj9/openj9/issues/18842

Exclude testCRaCMXBean for ibm builds

---

runtime/sunvmi/sunvmi.c

The serialization filter may be loaded by the extension classloader and this loader needs to be ignored when determining the latest user defined loader. jdk9+ already does this, although for jdk9+ it's called the platform classloader.
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/18984 for 0.44

(0.44) Ignore extension classloader in JVM_LatestUserDefinedLoader on jdk8

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
runtime/oti/j9nonbuilder.h
runtime/vm/BytecodeInterpreter.hpp

The tiny changes modify the constant used to
identify the heap address in downcall to avoid
any potential conflict with the address value
passed to downcall.
Fixes: #18999

[FFI/Jtreg_JDK22] Change the value of the heap address identifier

---

jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
jcl/src/java.base/share/classes/module-info.java.extra
runtime/j9vm/java11vmi.c
runtime/nls/j9vm/j9vm.nls
test/functional/cmdLineTests/criu/build.xml

`CRIU` adds unqualified `exports` `java.base/jdk.crac` when `CRaC` is enabled
Use `Module.implAddExports("jdk.crac")` to export `java.base/jdk.crac` unconditionally when the `CRaC` is enabled;
Refactored `throwExceptionHelper(currentThread, errCode)`;
Also fixed `addPackageDefinition()` usage in `JVM_AddModulePackage()`.
Resolve RTC workitem 150440.

CRIU adds unqualified exports java.base/jdk.crac when CRaC is enabled

---

runtime/j9vm/java11vmi.c

Add `throwExceptionHelper` default case
Default case is `Assert_SC_unreachable()`.

Add throwExceptionHelper default case

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp

- Treat `linkToNative()` as signature-polymorphic.
- Pass an extra argument to reserve space for the appendix.
- Always compile-time resolve to ensure the extra argument is passed.

Recognize linkToNative() in the JIT compiler to allow J2I calls

---

runtime/gc_base/RootScanner.cpp
runtime/gc_base/RootScanner.hpp

GC scans System and Application class loaders seperately as permanent roots. Scanning of the modules has been missed for this path.
related https://github.com/eclipse-openj9/openj9/issues/18805

Add missed scan for modules in System and Application class loaders

---

runtime/j9vm31/j9cel4ro64.c
runtime/j9vm31/j9cel4ro64.h
runtime/j9vm31/jniinv.cpp
runtime/j9vm31/jnimisc.cpp

The existing implementation for various Invocation APIs and *StringPlatform* functions calls CEL4RO64 to load and query the target function on each invocation. By caching the target function pointer, we avoid the redundant load/queries.
Also, reduce malloc/free usage on common CEL4RO64 call and query paths.

Cache Invocation API function descriptors in libjvm31 wrapper

---

runtime/compiler/compile/J9Compilation.cpp

This commit recognizes StringCoding.implEncodeAsciiArray() as a converter method in the JIT, thus enabling calls to the routine to be inlined into `arraytranslate` nodes.

Recognize StringCoding.implEncodeAsciiArray() as a converter method

---

runtime/nls/j9vm/j9vm.nls
runtime/vm/jvminit.c
test/functional/cmdLineTests/ignoreUnrecognizedVMOptions/deprecatedvmoptions.xml
test/functional/cmdLineTests/ignoreUnrecognizedVMOptions/playlist.xml

`JDK22+` print deprecation warning messages
Deprecation warning messages are printed when `-Xdebug/-Xnoagent` are specified at `JDK22+` command line options;
Added a test.
Note: 
JDK22 RI `java -debug -Xdebug -Xnoagent -version` output:
```
Warning: -debug option is deprecated and may be removed in a future release.
OpenJDK 64-Bit Server VM warning: Option -Xdebug was deprecated in JDK 22 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: Option -Xnoagent was deprecated in JDK 22 and will likely be removed in a future release.
```
OpenJ9 JVM already prints a deprecation warning message for `-debug`
```
Warning: -debug option is deprecated and may be removed in a future release.
```
which is from JCL native.
close …

JDK22+ print deprecation warning messages

---

jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
jcl/src/java.base/share/classes/module-info.java.extra
runtime/j9vm/java11vmi.c
runtime/nls/j9vm/j9vm.nls
test/functional/cmdLineTests/criu/build.xml

`CRIU` adds unqualified `exports` `java.base/jdk.crac` when `CRaC` is enabled
Use `Module.implAddExports("jdk.crac")` to export `java.base/jdk.crac` unconditionally when the `CRaC` is enabled;
Refactored `throwExceptionHelper(currentThread, errCode)`;
Also fixed `addPackageDefinition()` usage in `JVM_AddModulePackage()`.
Cherry-Pick
* https://github.com/eclipse-openj9/openj9/pull/18959
* https://github.com/eclipse-openj9/openj9/pull/19019

(v0.44.0-release) CRIU adds unqualified exports java.base/jdk.crac when CRaC is enabled

---

jcl/src/java.base/share/classes/com/ibm/oti/util/Util.java
jcl/src/java.base/share/classes/com/ibm/oti/vm/VM.java
jcl/src/java.base/share/classes/java/security/AccessControlContext.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/Advertisement.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/AttachHandler.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/Attachment.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/CommonDirectory.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/IPC.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/CompilationMXBeanImpl.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/ManagementUtils.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/RuntimeMXBeanImpl.java
jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/ExtendedOperatingSystemMXBeanImpl.java
jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Dump.java
jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Log.java
jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Trace.java
jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassHelperFactoryImpl.java

Add `VM.internalGetProperties()` helper method
It is equivalent to `VM.getVMLangAccess().internalGetProperties()`;
Updated all references.
Related to 
* https://github.com/eclipse-openj9/openj9/pull/18996

Add VM.internalGetProperties() helper method

---

jcl/src/java.base/share/classes/com/ibm/oti/util/Util.java
jcl/src/java.base/share/classes/com/ibm/oti/vm/VM.java
jcl/src/java.base/share/classes/java/security/AccessControlContext.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/Advertisement.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/AttachHandler.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/Attachment.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/CommonDirectory.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/IPC.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/CompilationMXBeanImpl.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/ManagementUtils.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/RuntimeMXBeanImpl.java
jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/ExtendedOperatingSystemMXBeanImpl.java
jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Dump.java
jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Log.java
jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Trace.java
jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassHelperFactoryImpl.java

Add `VM.internalGetProperties()` helper method
It is equivalent to `VM.getVMLangAccess().internalGetProperties()`;
Updated all references.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/19032

(v0.44.0-release) Add VM.internalGetProperties() helper method

---

runtime/j9vm31/j9cel4ro64.h

Add parens to CEL4RO64 control block lengths macro expressions.

Add parens to CEL4RO64 control block lengths macro expressions

---

runtime/vm/ValueTypeHelpers.hpp
runtime/vm/createramclass.cpp

Allow J9ClassCanSupportFastSubstitutability for double and float. No need to consider NaN. Directly compare the values of double and float.
Fixes #18993

Update ValueType comparison

---

runtime/nls/j9vm/j9vm.nls
runtime/vm/jvminit.c
test/functional/cmdLineTests/ignoreUnrecognizedVMOptions/deprecatedvmoptions.xml
test/functional/cmdLineTests/ignoreUnrecognizedVMOptions/playlist.xml

`JDK22+` print deprecation warning messages
Deprecation warning messages are printed when `-Xdebug/-Xnoagent` are specified at `JDK22+` command line options;
Added a test.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/19028

(v0.44.0-release) JDK22+ print deprecation warning messages

---

jcl/src/java.base/share/classes/java/lang/Class.java

Expected by test added in jdk23:
* [8322878: Including sealing information Class.toGenericString()](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/b4b9b060210dccfa145f38e2d98c91949adb53cc)
Fixes: #19033.

Include sealed/non-sealed as appropriate for Class.toGenericString()

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/env/j9method.cpp

implEncodeAsciiArray is equivalent to Java 11's US_ASCII.encodeASCII converter method. Acceleration
for this routine was added in OMR PR 7271. This commit introduces this API and enables the acceleration the JIT compiler.
Double delivery of https://github.com/eclipse-openj9/openj9/pull/18983/ and https://github.com/eclipse-openj9/openj9/pull/19025/
Related to https://github.com/eclipse-openj9/openj9-omr/pull/199

(0.44) Recognize StringCoding.implEncodeAsciiArray() as a converter method

---

runtime/jvmti/jvmtiHelpers.cpp
runtime/oti/VMHelpers.hpp

In JDK19+, multiple thread objects can be associated to a J9VMThread:
a virtual thread and its carrier thread.
If a virtual thread is mounted, then the carrier thread is unmounted and
vice-versa. In such cases, J9VMThread's state should not be used to
determine if a thread object is interrupted.
Instead, Thread.interrupted is used to determine if a thread object is
interrupted.
If a mounted thread is suspended, only set Thread.interrupted to TRUE
and do not wake/interrupt the thread. This behaviour is expected in
`GetThreadStateMountedTest`, which is a test added for virtual threads
in JDK22. These changes are only added for virtual threads in JDK19+.
Related: #18810

Fix virtual thread interrupts

---

runtime/compiler/optimizer/J9ValuePropagation.cpp

Avoid sign extension when assigning an 8bit value to an int32_t variable.
Issue: https://github.com/eclipse-openj9/openj9/issues/18974

Fix transformIndexOfKnownString to handle 8bit characters properly

---

test/functional/JLM_Tests/build.xml
test/functional/JLM_Tests/testng.xml
test/functional/JLM_Tests/testng_filter.xsl

Fix JLM_Tests build for windows by excluding tests in
testng.xml with xslt instead of awk, which is not
accessible on the windows machines.
Issue: https://github.com/eclipse-openj9/openj9/issues/18998

Fix JLM_Tests build for windows

---

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/AttachHandler.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/CommonDirectory.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/IPC.java

`AttachAPI` updates control file access time for long running applications 
Added a system property `com.ibm.tools.attach.fileAccessUpdateTime` for `sleepDays` which has a default value `8` (days);
Added a daemon thread to update `AttachAPI` control files every `sleepDays`.
close https://github.com/eclipse-openj9/openj9/issues/18720

AttachAPI updates control file access time for long running applications

---

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/AttachHandler.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/CommonDirectory.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/IPC.java

`AttachAPI` updates control file access time for long running applications 
Added a system property `com.ibm.tools.attach.fileAccessUpdateTime` for `sleepDays` which has a default value `8` (days);
Added a daemon thread to update `AttachAPI` control files every `sleepDays`.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/18996

(0.44.0) AttachAPI updates control file access time for long running applications

---

runtime/compiler/optimizer/J9ValuePropagation.cpp

Avoid sign extension when assigning an 8bit value to an int32_t variable.
Master PR: https://github.com/eclipse-openj9/openj9/pull/19044
Issue: https://github.com/eclipse-openj9/openj9/issues/18974

(0.44) Fix transformIndexOfKnownString to handle 8bit characters properly

---

test/functional/cmdLineTests/criu/src/org/openj9/criu/CRIUTestUtils.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/JDK11UpTimeoutAdjustmentTest.java

`CRIU` time compensation tests reset `TestResult.lockStatus`
Updated `CRIUTestUtils.showThreadCurrentTime()` and `JDK11UpTimeoutAdjustmentTest.showMessages()`.
Related 
* https://github.com/eclipse-openj9/openj9/issues/18557

CRIU time compensation tests reset TestResult.lockStatus

---

test/functional/JLM_Tests/build.xml
test/functional/JLM_Tests/playlist.xml
test/functional/JLM_Tests/testng-crac.xml
test/functional/JLM_Tests/testng.xml

This eliminates the need to use `awk` or `<xslt>` each of which has lead to problems.

Move CRaC tests to separate suite

---

runtime/gc_trace/TgcAllocation.cpp

Report core TLH/allocation-cache stats per thread via -Xtgc:allocation. We already report cumulative stats, but it could be useful to know what are the hungry threads, and how their TLH's change size.
The new stats are hooked to mutator cache flushing at GC start, before they are cleared by the flush.

TGC allocation stats per thread

---

runtime/compiler/runtime/JITServerAOTDeserializer.cpp

Attn @mpirvu. Related to https://github.com/eclipse-openj9/openj9/issues/18990.

Add missing critical section to deserializer reset

---

runtime/compiler/control/JitDump.cpp

Previously the JIT dump would recompile the "current method," which is sensitive to ongoing IL generation. If the compiler crashed during IL generation for an inlined method, then only that inlined method would be recompiled.
Now the JIT dump will always recompile the outermost method so that there will be a chance of reproducing IL generator crashes even if they are related to inlining.

Recompile the outermost method in JIT dump when compilation crashes

---

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/AttachHandler.java
jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9VirtualMachine.java
jcl/src/jdk.jcmd/share/classes/openj9/tools/attach/diagnostics/tools/Jcmd.java
jcl/src/jdk.jcmd/share/classes/openj9/tools/attach/diagnostics/tools/Util.java
test/functional/Java8andUp/src/org/openj9/test/attachAPI/TestJcmd.java

`AttachAPI` `jcmd` supports `VMID` query via Java process display names
Allow `jcmd` to accept the full/partial display name, and find its corresponding `VMIDs`;
Also accept `pid 0`, and send the `jcmd` command to all Java processes detected by current `jcmd`;
Add tests.
closes https://github.com/eclipse-openj9/openj9/issues/19045
Similar changes can be made to other AttachAPI-based tools, which I will implement in a separate PR.

AttachAPI jcmd supports VMID query via Java process display names

---

test/functional/JLM_Tests/playlist.xml

- exclude `JLM_Tests_interface`, `JLM_Tests_IBMinternal`, `testCRaCMXBean`,`JLM_Tests_class`,`testSoftMxLocal` for FIPS.
related:[github_ibm/runtimes/backlog/issues/1371](https://github.ibm.com/runtimes/backlog/issues/1371)

Exclude JLM_Tests for FIPS

---

runtime/compiler/control/OptionsPostRestore.cpp

Ensure the new Client UID generated in the post restore options processing code is different from the UID generated pre-checpoint. Also Print out the old and new Client UIDs.
This may fix https://github.com/eclipse-openj9/openj9/issues/17474, but at the very least it'll add a few more diagnostics to help with it if it doesn't.

Ensure Client UID is different on restore

---

runtime/compiler/optimizer/JProfilingRecompLoopTest.cpp
runtime/compiler/optimizer/JProfilingRecompLoopTest.hpp
runtime/compiler/optimizer/JProfilingValue.cpp

JProfilingValue: Check if the block frequency info exist before generating the test on whether or not the method is queued for recompilation.
JProfilingRecompLoopTest: Do not perform if the block frequency info does not exist because JProfilingRecompLoopTest relies on the counters created in the block frequency info.

Check if block frequency info exist before generating test

---

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/AttachHandler.java
jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9VirtualMachine.java
jcl/src/jdk.jcmd/share/classes/openj9/tools/attach/diagnostics/tools/Jcmd.java
jcl/src/jdk.jcmd/share/classes/openj9/tools/attach/diagnostics/tools/Util.java
test/functional/Java8andUp/src/org/openj9/test/attachAPI/TestJcmd.java

`AttachAPI` `jcmd` supports `VMID` query via Java process display names
Allow `jcmd` to accept the full/partial display name, and find its corresponding `VMIDs`;
Also accept `pid 0`, and send the `jcmd` command to all Java processes detected by current `jcmd`;
Add tests.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/19069

(0.44) AttachAPI jcmd supports VMID query via Java process display names

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/compile/J9SymbolReferenceTable.hpp
runtime/compiler/ilgen/J9ByteCodeIlGenerator.hpp
runtime/compiler/ilgen/Walker.cpp

This commit ensures compliance with JVM spec regarding the handling of putstatic/putfield/withfield opcodes. This involves correctly narrowing integer values when storing them into fields of smaller types such as bool, byte, char, and short. For byte and short fields, narrowing involves conversion from integer to byte/short, then back to integer. For bool and char types, which are unsigned, narrowing entails ANDing the value with a mask matching the type width.
Issue: #16498
Port of https://github.com/eclipse-openj9/openj9/pull/18904 for 0.44

(0.44) JIT must narrow byte/short/char before storing

---

test/functional/JLM_Tests/playlist.xml

-exclude `JLM_Tests_interface`, `JLM_Tests_IBMinternal`,`JLM_Tests_class`,`testSoftMxLocal` for FIPS.
related:github_ibm/runtimes/backlog#1371

(v0.44.0-release) Exclude JLM_Tests for FIPS

---

runtime/nls/j9vm/j9vm.nls
runtime/vm/CRIUHelpers.cpp
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/EnvVarFileTest.java
test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java

Support transition to debug interpreter on restore when
the transition is requested with an env var file or an
options file.
Issue: https://github.com/eclipse-openj9/openj9/issues/17642
Co-authored-by: Tobi Ajila <atobia@ca.ibm.com>

Support transition to debug interpreter on restore

---

test/functional/cmdLineTests/criu/criuCatVlog.sh

Delete the vlog to cat after cat-ing. This cleans up the workspace and also prevents subsequent tests from incorrectly reading this vlog in case that test was a failed restore for known reasons.
Fixes https://github.com/eclipse-openj9/openj9/issues/17748

Delete vlog in criuCatVlog.sh

---

runtime/gc_vlhgc/HeapRegionManagerVLHGC.cpp
runtime/gc_vlhgc/HeapRegionManagerVLHGC.hpp

There was a gcEnd condition check patch for calculating memorypool usage at the end of GC due to the increment logic age for regions happened after getHeapMemorySnapshot(), but incrementing region's age has been updated to be called before getHeapMemorySnapshot(), condition check for gcEnd is unnecessory, also the condition check would cause incorrect memory usages for eden, reserved and survivor pools in Global Marking Phase case.

Correct memorypool usage calculating for GMP case

---

runtime/rasdump/javadump.cpp

- Remove NULL line for unstarted/finished Continuations
- Remove unclear "mounted" state for swapped continuations where the unmounted carrier is printed.

Fix javacore unmounted threads output

---

jcl/src/java.base/share/classes/openj9/internal/criu/InternalCRIUSupport.java

`InternalCRIUSupport`'s `isNativeLoaded` method has useful functionality but is currently dead code. This patch appropriately calls `isNativeLoaded` when checking in `isCRIUSupportEnabledAndNativeLoaded` and `isCRaCorCRIUSupportEnabledAndNativeLoaded`.

Use isNativeLoaded when checking if CRIU and CRaC are enabled

---

runtime/gc_api/HeapRootScanner.cpp
runtime/gc_base/RootScanner.cpp
runtime/gc_base/RootScanner.hpp
runtime/gc_glue_java/MarkingDelegate.cpp
runtime/gc_glue_java/MarkingDelegate.hpp
runtime/gc_glue_java/MetronomeDelegate.cpp
runtime/gc_glue_java/MetronomeDelegate.hpp
runtime/gc_vlhgc/ClassLoaderRememberedSet.cpp
runtime/gc_vlhgc/ClassLoaderRememberedSet.hpp
runtime/gc_vlhgc/CopyForwardScheme.cpp
runtime/gc_vlhgc/GlobalMarkingScheme.cpp
runtime/gc_vlhgc/WriteOnceCompactor.cpp

Extension Cladss Loader can not be unloaded and can be treated as a permanent root the same way as System and Application Class Loaders.

Add Extension Class Loader to permanent roots

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/env/J9PersistentInfo.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/LoadSSLLibs.cpp
runtime/compiler/net/LoadSSLLibs.hpp
runtime/compiler/runtime/Listener.cpp
runtime/compiler/runtime/MetricsServer.cpp
test/functional/JIT_Test/src/jit/test/jitserver/JITServerTest.java
test/functional/cmdLineTests/criu/criuJitServerScript.sh
test/functional/cmdLineTests/jitserver/jitserverArgumentTesting.xml
test/functional/cmdLineTests/jitserver/jitserverScript.sh

Kubernetes can use liveness and readiness probes to check
a pod's health. For a TCP port, the kubelet attempts to open a
socket to the container on the specified port. If a connection
can be established, the container is considered healthy.
The JITServer did not have a dedicated port for health probes;
instead, the main communication port (default 38400) could be
used for this purpose. However, this solution is not ideal
when communication between the client and server is encrypted
with OpenSSL. Starting with OpenSSL 3.0, if one of the participants
closes the connection without notifying the other party, the
OpenSSL library will log error messages like:
"A0F04FE4FE7F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:320"
Since the health …

 Add dedicated health port for JITServer

---

runtime/compiler/env/ClassLoaderTable.cpp

In copyJ9UTF8(), we now avoid throwing std::bad_alloc() if memory for a copy of a ROM class's name could not be allocated. We instead do not add the TR_ClassLoaderInfo into the _nameTable in such situations. This parallels the treatment of the class loader info if a chain for the loader could not be found in the SCC.

(0.44) Do not throw in ClassLoaderTable

---

runtime/compiler/runtime/JITServerAOTDeserializer.cpp

A missing critical section has been added to `JITServerAOTDeserializer::reset()`.

(0.44) Add missing critical section to deserializer reset

---

runtime/gc_base/ReferenceChainWalker.cpp
runtime/gc_base/RootScanner.cpp
runtime/gc_base/RootScanner.hpp
runtime/gc_glue_java/MarkingSchemeRootClearer.cpp
runtime/gc_glue_java/ScavengerRootClearer.cpp
runtime/gc_glue_java/ScavengerRootClearer.hpp
runtime/gc_modron_standard/RootScannerReadBarrierVerifier.cpp
runtime/gc_realtime/RealtimeMarkingSchemeRootClearer.hpp
runtime/gc_realtime/RealtimeRootScanner.cpp
runtime/gc_realtime/RealtimeRootScanner.hpp
runtime/gc_vlhgc/CopyForwardScheme.cpp
runtime/gc_vlhgc/GlobalMarkingScheme.cpp

Currently RootScanner class stores omrvm. However it is always used to get javavm. So, reasonable solution to store javavm instead to avoid multiple casts.
This PR does not have any functional change.

Replace omrvm to javavm for RootScanner class

---

jcl/src/java.base/share/classes/jdk/crac/Core.java
jcl/src/java.base/share/classes/openj9/internal/criu/InternalCRIUSupport.java

Add some error messages as org.crac eats exceptions making it very difficult to understand the issue at hand.
Add some properties to override default criu capabilities.
Original PR:
https://github.com/eclipse-openj9/openj9/pull/19046

(0.44) Update CRaC options

---

runtime/gc_base/ReferenceChainWalker.cpp
runtime/gc_base/RootScanner.cpp
runtime/gc_base/RootScanner.hpp
runtime/gc_glue_java/MarkingSchemeRootClearer.cpp
runtime/gc_glue_java/ScavengerRootClearer.cpp
runtime/gc_glue_java/ScavengerRootClearer.hpp
runtime/gc_modron_standard/RootScannerReadBarrierVerifier.cpp
runtime/gc_realtime/RealtimeMarkingSchemeRootClearer.hpp
runtime/gc_realtime/RealtimeRootScanner.cpp
runtime/gc_realtime/RealtimeRootScanner.hpp
runtime/gc_vlhgc/CopyForwardScheme.cpp
runtime/gc_vlhgc/GlobalMarkingScheme.cpp

Reverts eclipse-openj9/openj9#19141 due to https://github.com/eclipse-openj9/openj9/pull/19141#issuecomment-1998677574

Revert "Replace omrvm to javavm for RootScanner class"

---

jcl/src/java.base/share/classes/java/lang/Class.java

Anon class (simple name is null) cannot be referenced by name from the inner class attribute of its enclosing class. In this case, there is no need to search for the class name in the inner class attribute.
Closes #19016

Add simple class name check in checkInnerClassAttrOfEnclosingClass()

---

jcl/src/java.base/share/classes/java/lang/Access.java
runtime/j9vm/exports.cmake
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/java11vmi.c
runtime/j9vm/javanextvmi.cpp
runtime/j9vm/module.xml
runtime/redirector/forwarders.m4

`JDK23` adds `Access.addEnableNativeAccess(moduleLayer, moduleName)`
Also added `JVM_GetCDSConfigStatus()` stub method that returns false unconditionally since OpenJ9 doesn't support `CDS`.
Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/755
Related to
* https://github.com/eclipse-openj9/openj9/issues/19144

JDK23 adds Access.addEnableNativeAccess(moduleLayer, moduleName)

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/env/J9PersistentInfo.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/LoadSSLLibs.cpp
runtime/compiler/net/LoadSSLLibs.hpp
runtime/compiler/runtime/Listener.cpp
runtime/compiler/runtime/MetricsServer.cpp
test/functional/JIT_Test/src/jit/test/jitserver/JITServerTest.java
test/functional/cmdLineTests/criu/criuJitServerScript.sh
test/functional/cmdLineTests/jitserver/jitserverArgumentTesting.xml
test/functional/cmdLineTests/jitserver/jitserverScript.sh

Kubernetes can use liveness and readiness probes to check
a pod's health. For a TCP port, the kubelet attempts to open a
socket to the container on the specified port. If a connection
can be established, the container is considered healthy.
The JITServer did not have a dedicated port for health probes;
instead, the main communication port (default 38400) could be
used for this purpose. However, this solution is not ideal
when communication between the client and server is encrypted
with OpenSSL. Starting with OpenSSL 3.0, if one of the participants
closes the connection without notifying the other party, the
OpenSSL library will log error messages like:
"A0F04FE4FE7F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:320"
Since the health …

(0.44.0) Add dedicated health port for JITServer

---

test/functional/cmdLineTests/criu/criuSoftmxScript.sh
test/functional/cmdLineTests/criu/criu_softmx.xml
test/functional/cmdLineTests/criu/playlist.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/SoftmxTest.java

Add supporting test cases and related testing scripts.
Softmx functionalities: #18168
Functional changes: #19037

CRIU Restore Softmx Functional Tests

---

jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/ExtendedGarbageCollectorMXBeanImpl.java

GCInfo contains a set of memory usages for all of memoryPools(both Heap
and NonHeap),java function buildGCInfo() retrieve a list of MemoryPools'
names and a list of Usages internally and generate the set of memory
usages, in some platforms(ex. MacOS) the order for the list of names and
for the list of usages might be different, the root cause is that we use
ManagementFactory.getMemoryPoolMXBeans() retrieve a copy of the list
MemoryPools and the copy list might be the different order than original
list for curtain platform, update to use the api
ExtendedMemoryMXBeanImpl.getInstance().getMemoryPoolMXBeans(false)
to retrieve original list to avoid misorder issue.
fix: https://github.com/eclipse-openj9/openj9/issues/12754

Fix wrong memoryPool names of memory usage in GCInfo

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/env/J9PersistentInfo.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.cpp
runtime/compiler/net/MessageTypes.hpp

If a JITServer client uses `-XX:+JITServerAOTCacheIgnoreLocalSCC`, servers that client connects to will now
1. Fail a compilation completely if the client requests an AOT cache store and the server cannot set up the compilation as an AOT cache store or load, and
2. Report the state of the server's AOT cache if (1) occurs, so the client will not continue to send AOT cache requests to that server if those requests could not possibly be fulfilled.
The client tracks the state of the current server's AOT cache with the persistent info properties `doNotRequestJITServerAOTCacheStore()` and `doNotRequestJITServerAOTCacheLoad()`. Since a particular server's cache will never become able to complete AOT cache loads or stores partway through a connection (e.g., the server's cache never shrinks in …

Enable per-connection JITServer AOT cache disabling

---

runtime/gc_vlhgc/HeapRegionManagerVLHGC.cpp
runtime/gc_vlhgc/HeapRegionManagerVLHGC.hpp

There was a gcEnd condition check patch for calculating memorypool usage at the end of GC due to the increment logic age for regions happened after getHeapMemorySnapshot(), but incrementing region's age has been updated to be called before getHeapMemorySnapshot(), condition check for gcEnd is unnecessory, also the condition check would cause incorrect memory usages for eden, reserved and survivor pools in Global Marking Phase case.
-cleanup the format base on the coding standard
UDATA to uintptr_t
"<type>*" to "<type> *"
Port of https://github.com/eclipse-openj9/openj9/pull/19063 to 0.44

(0.44) Correct memorypool usage calculating for GMP case

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/env/J9PersistentInfo.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.cpp
runtime/compiler/net/MessageTypes.hpp

If a JITServer client uses `-XX:+JITServerAOTCacheIgnoreLocalSCC`, servers that client connects to will now
1. Fail a compilation completely if the client requests an AOT cache store and the server cannot set up the compilation as an AOT cache store or load, and
2. Report the state of the server's AOT cache if (1) occurs, so the client will not continue to send AOT cache requests to that server if those requests could not possibly be fulfilled.
The client tracks the state of the current server's AOT cache with the persistent info properties `doNotRequestJITServerAOTCacheStore()` and `doNotRequestJITServerAOTCacheLoad()`. Since a particular server's cache will never become able to complete AOT cache loads or stores partway through a connection (e.g., the server's cache never shrinks in …

(0.44) Enable per-connection JITServer AOT cache disabling

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/types/I16.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/types/I32.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/types/I64.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/types/I8.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/types/IDATA.java

For negative values, the `div()`, `mod()`, and `rightShift()` methods would sometimes return bad values.
For example, -10 is represented as 0xFFFFFFF6L in the data field of an `I32` object (or in a `IDATA` object for 32-bit dumps).
* `div(5)` would return 0x33333331(858993457) instead of -2
* `mod(5)` would return 1 instead of 0
* `rightShift(0)` would return -1 instead of -10

DDR: correct some operations for signed types

---

test/functional/cmdLineTests/jvmtitests/build.xml

Correctly disable Java21andUp JVMTI tests for JDK8

---

runtime/oti/VMHelpers.hpp

Update thread interrupt helpers to adopt internalSuspendState

---

runtime/compiler/net/LoadSSLLibs.hpp

Older OpenSSL versions may not have this constant available, causing compilation failures when compiling with those versions. Supplying the definition of this constant if it is not present fixes the build issues.

Define OpenSSL error constant if not present

---

test/functional/cmdLineTests/loadLibraryTest/playlist.xml

Issue https://github.com/eclipse-openj9/openj9/issues/18975

Exclude cmdLineTester_loadLibraryTests on Windows jdk22+

---

buildspecs/j9.flags
runtime/cmake/options.cmake
runtime/compiler/control/CompilationThread.cpp
runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp
runtime/j9vm/asgct.cpp
runtime/oti/j9nonbuilder.h
runtime/vm/extendedMessageNPE.cpp

They are problematic on z/OS where conversion to EBCDIC will fail.

Don't use non-ASCII characters in text files

---

runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp
runtime/compiler/runtime/JITServerAOTCache.cpp

The JITServer AOT cache will now refuse to generate class records for array ROM classes. This is relevant for clients running with -XX:+JITServerAOTCacheIgnoreLocalSCC - with this option disabled, the fact that array classes cannot be persisted in the local SCC acts as an implicit barrier to their ROM classes ever reaching the AOT cache. Without that option, the AOT cache must explicitly check that the given ROM class is not an array ROM class.
In future, the AOT cache should be extended with support for array classes. For now, this change prevents excessive AOT cache deserialization failures from occurring at JITServer clients running with -XX:+JITServerAOTCacheIgnoreLocalSCC due to the nonsensical class records the cache previously generated for array classes.
Related: …

(0.44) Refuse to generate array class serialization records

---

debugtools/DDR_VM/src/com/ibm/j9ddr/tools/PointerGenerator.java
debugtools/DDR_VM/src/com/ibm/j9ddr/tools/StructureStubGenerator.java

The test of whether a field is present must be deferred until a specific system dump is being accessed.
Structure stubs must include all fields optional or otherwise. The structure class generated dynamically will only include those fields actually present in the JVM that produced the system dump. Accesses to missing fields will trigger a `NoSuchFieldError` which will be replaced by `NoSuchFieldException` by the related pointer class.
Pointer classes must support the scenario where a field is not present in the executing JVM, but is present in a system dump being analyzed.

DDR: always generate optional fields

---

jcl/src/java.base/share/classes/java/lang/Access.java
jcl/src/java.base/share/classes/java/lang/System.java

`JDK23` adds `java.lang.Access.allowSecurityManager()`
Removed `!INLINE-TYPES` since `valhalla` is still in JDK 22 level.
closes https://github.com/eclipse-openj9/openj9/issues/19208
Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk/tree/openj9-staging

JDK23 adds java.lang.Access.allowSecurityManager()

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
runtime/jcl/exports.cmake
runtime/jcl/uma/java_lang_invoke_MethodHandleNatives_exports.xml
runtime/jvmti/jvmtiClass.c
runtime/oti/j9nonbuilder.h
runtime/oti/jclprots.h
runtime/oti/util_api.h
runtime/util/hshelp.c
runtime/vm/createramclass.cpp
runtime/vm/jvminit.c

In class redefinition the affected `MemberName` objects were previously identified by iterating over all objects in the heap. The heap walk also necessitated a GC cycle to eliminate dead objects, which could otherwise cause the fix-up to crash.
This heap walk and GC cycle were causing a significant performance regression in redefinition for builds using OpenJDK `MethodHandle`s (i.e. Java 17+) vs. ones using J9 `MethodHandle`s. The regression was especially drastic in fast HCR mode, where no other heap walk is necessary and therefore the time taken for redefinition should be largely independent of the number of objects in the heap.
Now instead each `J9Class` has a list of JNI weak global references to all of the `MemberName` objects that are resolved (i.e. have `vmtarget` set) to a member …

Avoid heap walk and GC for MemberName fix-up on class redefinition

---

runtime/oti/vm_api.h
runtime/vm/KeyHashTable.c
runtime/vm/j9vm.tdf
runtime/vm/jvminit.c

from classHashTable when its associated rom class is unloaded. This will prevent errors that could occur when accessing the package entry with an invalid rom class.
Fixes: https://github.com/eclipse-openj9/openj9/issues/18907

Remove generated MHProxy package entries

---

runtime/oti/j9.h
runtime/oti/j9nonbuilder.h
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/createramclass.cpp

Reuse value for J9ClassIsPrimitiveValueType to J9ClassAllowsInitialDefaultValue for lw5.
Set J9ClassAllowsInitialDefaultValue when class has an ImplicitCreation attribute set
to indicate that default values should be set during initialization.
Related https://github.com/eclipse-openj9/openj9/issues/17234

Set default values for implicit value classes

---

runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/compile/J9Compilation.hpp
runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/J9KnownObjectTable.cpp
runtime/compiler/ilgen/IlGenerator.cpp
runtime/compiler/ilgen/J9ByteCodeIlGenerator.hpp
runtime/compiler/ilgen/Walker.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.cpp
runtime/compiler/net/MessageTypes.hpp
runtime/compiler/optimizer/HCRGuardAnalysis.cpp
runtime/compiler/optimizer/InterpreterEmulator.cpp
runtime/compiler/optimizer/InterpreterEmulator.hpp
runtime/compiler/optimizer/J9TransformUtil.cpp
runtime/compiler/optimizer/J9TransformUtil.hpp
runtime/compiler/optimizer/OSRGuardInsertion.cpp
runtime/compiler/optimizer/StringPeepholes.cpp

This series consists of some initial preparations for expanded static final field folding (SFFF) in `InterpreterEmulator`, primarily in the two ways mentioned in the title. Brief summary of each commit:
- Make `KnownObjectTable::addStableArray()` safe to call on the server: *needed for the following refactoring*
- Refactor static final field folding for reuse in `InterpreterEmulator`: *exposes SFFF logic that will facilitate later guarded/speculative folding in inliner*
- Declare `isFearPointPlacementUnrestricted()`: *names a concept that will be needed later for early guarded folding*
- Delete unused flags in the IL generator held over from multitenancy: *minor cleanup prior to record/replay*
- Record/replay `InterpreterEmulator` constants: *ensures consistency between inliner and IL, …

Refactor SFFF for InterpreterEmulator and record/replay InterpreterEmulator constants

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy

Reverts eclipse-openj9/openj9#18325

Revert "In PR testing redefine `all` to exclude UNB platforms"

---

runtime/compiler/env/J9SharedCache.cpp

When ignoring the client's SCC, if a server performs an AOT compilation that is not an AOT cache compilation for a client (possible if the client has a valid local SCC) it may cache valid class chain offsets for classes in the client's session data. If the server then performs an AOT cache store for that client, it may receive an invalid class chain from the client for a class that already has a valid cached class chain offset, since the client will be ignoring its local SCC for such a compilation. This situation is valid, and should not trigger the fatal assert in TR_J9JITServerSharedCache::rememberClass() that detects a mismatch between the cached and received class chain offset. That fatal assert is now disabled for AOT cache stores when the server is ignoring the client's SCC.
This …

Relax condition on JITServer rememberClass assert

---

runtime/compiler/env/J9SharedCache.cpp

When ignoring the client's SCC, if a server performs an AOT compilation that is not an AOT cache compilation for a client (possible if the client has a valid local SCC) it may cache valid class chain offsets for classes in the client's session data. If the server then performs an AOT cache store for that client, it may receive an invalid class chain from the client for a class that already has a valid cached class chain offset, since the client will be ignoring its local SCC for such a compilation. This situation is valid, and should not trigger the fatal assert in TR_J9JITServerSharedCache::rememberClass() that detects a mismatch between the cached and received class chain offset. That fatal assert is now disabled for AOT cache stores when the server is ignoring the client's SCC.
This …

Relax condition on JITServer rememberClass assert (0.44)

---

runtime/oti/vm_api.h
runtime/vm/KeyHashTable.c
runtime/vm/j9vm.tdf
runtime/vm/jvminit.c

from classHashTable when its associated rom class is unloaded. This will prevent errors that could occur when accessing the package entry with an invalid rom class.
Backport from: https://github.com/eclipse-openj9/openj9/pull/19159

(0.45) Remove generated MHProxy package entries

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h

The `TR::CompilationInfoPerThread` is now cached in `TR_J9DeserializerSharedCache` to avoid the use of `TR::compInfoPT`. The handling of the `TR_J9DeserializerSharedCache` object itself has changed to accommodate this - there is now a `_deserializerSharedCache` in `TR_J9VMBase` (to have these objects be exclusive to one compilation thread) and the `_deserializerSharedCache` in `TR::CompilationInfo` has been removed.

Cache compInfoPT in JITServer deserializer SCC interface

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/env/J9PersistentInfo.hpp
runtime/compiler/runtime/Listener.cpp

The `-XX:JITServerPort=<port>` and `-XX:JITServerHeathProbePort=<port>` options both now support the port value 0. When this port is specified, a random unassigned port will be assigned to the relevant socket, and this bound port will be reported in the JITServer verbose log.
This behaviour when port 0 is specified matches that of the underlying `bind()` network function.
Related: https://github.com/eclipse-openj9/openj9/issues/14706

Allow JITServer communication and health port 0

---

jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9VirtualMachine.java
jcl/src/jdk.jcmd/share/classes/openj9/tools/attach/diagnostics/attacher/AttacherDiagnosticsProvider.java
jcl/src/jdk.jcmd/share/classes/openj9/tools/attach/diagnostics/tools/Jcmd.java
jcl/src/jdk.jcmd/share/classes/openj9/tools/attach/diagnostics/tools/Util.java
test/functional/Java8andUp/playlist.xml
test/functional/Java8andUp/src/org/openj9/test/attachAPI/TestJcmd.java
test/functional/Java8andUp/src/org/openj9/test/attachAPI/TestJps.java
test/functional/Java9andUp/playlist.xml
test/functional/TestUtilitiesJ9/src/org/openj9/test/attachAPI/AttachApiTest.java
test/functional/TestUtilitiesJ9/src/org/openj9/test/attachAPI/TargetManager.java
test/functional/TestUtilitiesJ9/src/org/openj9/test/attachAPI/TargetVM.java

`AttachAPI Jcmd` retry attaching in case of `SocketException`
`AttachAPI Jcmd` retry attaching in case of `SocketException` on `Windows` platform;
Retry time is `3` by default or a value specified via a system property `com.ibm.tools.attach.retry`;
Enabled `-Dcom.ibm.tools.attach.logging=yes` for `AttachAPI` utility tests;
Also enabled `TargetManager.doLogging`.
closes https://github.com/eclipse-openj9/openj9/issues/19165

AttachAPI Jcmd retry attaching in case of SocketException

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/ilgen/Walker.cpp

Boxed primitive classes have a method that unboxes their value, which are implemented as simple getter methods. These methods are marked as @IntrinsicCandidates, intended for simplification by the compiler.
This commit recognizes the primitive unboxing methods and generates simplified IL during IL generation instead of emitting the call where possible.

Optimize primitive unboxing method calls

---

runtime/shared/shrclssup.c

If a JITServer AOT cache client is ignoring its local SCC for AOT cache compilations, then the temporary writable SCC layer that might otherwise be created (if the client has a readonly local SCC and is running in containers) is redundant and does not in fact need to be created.

Disable temporary SCC layer if ignoring local SCC

---

test/functional/Java8andUp/playlist.xml

FIPS disable JCL_TEST_Java-Security tests
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/19010

(v0.44.0-release) FIPS disable JCL_TEST_Java-Security tests

---

test/functional/Java8andUp/playlist.xml

FIPS disable JCL_TEST_Java-Security tests
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/19010

(v0.45.0-release) FIPS disable JCL_TEST_Java-Security tests

---

runtime/gc_check/CheckCycle.cpp

Use the existing midscavenge logic when concurrent scavenge
is in progress, and hide the detected forwarded pointer messages.
Signed off by: Frank.Kang@ibm.com

Detect forward pointers in gc check for concurrent scavenge

---

jcl/src/jdk.jcmd/share/classes/openj9/tools/attach/diagnostics/tools/Util.java
test/functional/Java8andUp/src/org/openj9/test/attachAPI/TestJcmd.java
test/functional/Java8andUp/src/org/openj9/test/attachAPI/TestJps.java
test/functional/TestUtilitiesJ9/src/org/openj9/test/attachAPI/AttachApiTest.java

`AttachApiTest` `runCommandAndLogOutput()` recreates `commandLineArgs`
Restored `Collections.singletonList()` passed to `runCommandAndLogOutput()`;
Fixed a typo.

AttachApiTest runCommandAndLogOutput() recreates commandLineArgs

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/runtime/CRRuntime.cpp
runtime/compiler/runtime/DataCache.cpp
runtime/compiler/runtime/DataCache.hpp
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/CRIUHelpers.cpp
runtime/vm/intfunc.c
runtime/vm/jvminit.c
runtime/vm/segment.c

This commit will periodically disclaim memory for data cache (metadata) segments to a backing file. The points where the disclaim operations are issued are based on internal JIT heuristics, but the frequency cannot exceed certain values that are controlled by: `-Xjit:minTimeBetweenMemoryDisclaims=` (ms)
Disclaiming of metadata can be disabled with:
`-Xjit:disableDataCacheDisclaiming`
Disclaiming is performed only on Linux kernels >= 5.4

Disclaim memory for metadata segments

---

runtime/cmake/platform/os/zos.cmake

In order to create compiler pseudo assembly listing .lst files.
https://www.ibm.com/docs/en/zos/2.4.0?topic=options-list-nolist
https://www.ibm.com/docs/en/zos/2.4.0?topic=options-offset-nooffset
https://www.ibm.com/docs/en/zos/2.4.0?topic=options-gonumber-nogonumber

Add "-Wc,list(),offset,gonumber" compile options on z/OS

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/runtime/IProfiler.cpp

When a non-comp thread invokes `acquireVMaccessIfNeeded`, the function
silently returns, because it assumes that a non-comp thread should
already have had VMAccess. This is particularly problematic when using
`TR::VMAccessCriticalSection`, as it is not at all obvious that the
current thread may not actually have VMAccess. Furthermore, there are
legitmate circusmtances when a non-comp thread will not have VMAccess
Additionally, this PR includes:
* Enforce VMAccess when calling `compileMethod`
* Use `TR::VMAccessCriticalSection` in `dumpIPBCDataCallGraph`
Enables https://github.com/eclipse-openj9/openj9/pull/18982

Fix acquireVMaccessIfNeeded for Non-Compiler Threads

---

runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/runtime/JITServerAOTCache.cpp

On completing an AOT cache store, the JITServer will now always send the freshly-compiled method to the client.
Signed-off-by: Christian Despres

Always send fresh AOT cache method to client

---

test/functional/cmdLineTests/sigxfszHandlingTest/runSIGXFSZTest.sh

VM changes seem to exceed the limit of 4000 and the SIGXFSZ signal occurs on Ubuntu before the test can run System.out.println().
Fixes https://github.com/eclipse-openj9/openj9/issues/19276
[Internal testing 1](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=68909) and [grinder](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=68912)
[Internal testing 2](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/39520) and on the [same machine](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/39521/)
without this change it [failed](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/39519/)

Set a higher ulimit -f setting for sigxfszHandlingTest

---

runtime/vm/jnicsup.cpp

Initialize subclass as initial class before main method to
match the RI and align with section 5.2 Java Virtual Machine
Startup in the spec.
Issue: https://github.com/eclipse-openj9/openj9/issues/19140

Initialize subclass as initial class before main method

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit removes some lines that call target().is64Bit(). AArch64 always runs in the 64-bit mode, and those checks are not needed.

AArch64: Remove unnecessary calls to target().is64Bit()

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/env/J9ObjectModel.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp

A number of off-heap commits:
- Guard dataAddr intializations in inline array allocation routines with the new macro `J9VM_GC_ENABLE_SPARSE_HEAP_ALLOCATION`.
- Update local array object allocation sequence to populate dataAddr field
- Increase numDeps size if populating dataAddr field
- Disable arraylet support if offheap allocation is enabled
- ~~Update isDiscontiguousArray(...) query, If off heap allocation is enabled this query should always return false.~~

Off Heap Changes

---

runtime/compiler/env/J9DebugEnv.cpp

This commit enables JIT breakpoint on macOS.

Enable JIT breakpoint on macOS

---

test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/criu_nonPortableJDK11Up.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/TimeChangeTest.java

CRIU timer time compensation tests use `TestResult.lockStatus`
Remove hard-coded `Thread.sleep()`;
Check `TestResult.lockStatus.get() == 0` if the time task thread finished;
Specify `unusedArgument` for `criuScript.sh` unused parameter `$5` - `the APP ARGS`;
Enable `KEEP_TEST_OUTPUT` for `testMillisDelayBeforeCheckpointDone` and `testMillisDelayAfterCheckpointDone`.
Related to
* https://github.com/eclipse-openj9/openj9/issues/18527
The initial time-out occurred at
```
[ERR] /home/jenkins/workspace/Test_openjdk22_j9_sanity.functional_aarch64_linux_Release_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh: line 41: 991547 Killed    
```
There was little diagnosis info, this PR also added trace points and kept the test output file.
Signed-off-by: Jason Feng …

CRIU timer time compensation tests use TestResult.lockStatus

---

buildenv/jenkins/variables/defaults.yml

Cherry pick https://github.com/eclipse-openj9/openj9/pull/19286 for 0.44

(0.44) Update OpenSSL to include the fix for CVE-2024-2511

---

runtime/gc_base/StringTable.cpp
test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_String.java

Updates j9gc_createJavaLangString().
Fixes https://github.com/eclipse-openj9/openj9/issues/19273

Fix String creation to treat a modified UTF8 zero as ASCII

---

runtime/gc_base/StringTable.cpp
test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_String.java

Updates j9gc_createJavaLangString().
Issue https://github.com/eclipse-openj9/openj9/issues/19273

(0.44) Fix String creation to treat a modified UTF8 zero as ASCII

---

runtime/vm/jnimisc.cpp
runtime/vm/vm_internal.h

Add declarations in `vm_internal.h` so they can also be used in `ArrayCopyHelpers.cpp`.
Fixes an oversight in #19263.

Make javaOffloadSwitch(On|Off)WithReason functions global

---

runtime/gc_modron_startup/arrayCopy.cpp

Update referenceArrayCopy helper to use getArrayObjectDataAddress when calculating source and destination index.

Use getArrayObjectDataAddress in referenceArrayCopy to calculate index

---

runtime/bcverify/bcverify.c
runtime/bcverify/rtverify.c
runtime/verbose/errormessageframeworkrtv.c

The changes aim to rectify the situation when there is
literally no valid type data to be displayed on the empty
stack after a bunch of manipulations (e.g. pop) to prevent
any garbage data from being decoded in the error message
framework so as to match the RI's behavior.

[Verifier] Prevent displaying the garbage type on the empty stack

---

runtime/compiler/il/J9Node.cpp

The JNI argument setup in processJNICall() will add another level of indirection for object arguments by placing the argument into a stack slot and passing a pointer to the slot as the JNI argument. Is some cases the argument object is already a load of a stack slot, in which case we try and avoid creating a new temporary stack slot to hold the argument value. But in such cases it's possible that the slot has since been overwritten with some other value causing an incorrect argument to be passed to the JNI method. This fix will only allow using an existing stack slot (auto) when the reference count is 1 because only then can we be assured that the slot has not been overwritten.

Fix JNI argument setup when ref count is not 1

---

runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/control/rossa.h
runtime/compiler/exceptions/PersistenceFailure.hpp

This compilation failure type is thrown if errors related to creating JITServer AOT cache serialization records occur during compilation. Formerly, this type of failure did not have a specific exception associated to it, and would be reported as a generic compilationFailure.

Add AOTCachePersistenceFailure, associated compErrCode

---

runtime/compiler/control/CompilationThread.cpp

Depends on: https://github.com/eclipse/omr/pull/7309

Print footprint statistics using verbose #METHOD STATS

---

runtime/gc_base/StringTable.cpp
runtime/gc_base/StringTable.hpp

This patch fixes a include-order dependency in StringTable.cpp. StringTable.hpp relies on j9protos.h which it transitively has access to through the include order in StringTable.cpp. This patch includes j9protos.h explicitly in StringTable.hpp and alters StringTable.cpp includes to conform to the OMR coding standards.

Add j9protos.h to StringTable.hpp

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit fixes BNDCHKwithSpineCHK for AArch64.
Address calculation must use the 64-bit instruction.

AArch64: Fix BNDCHKwithSpineCHK

---

runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/env/VMJ9.cpp

Under -XX:+DebugOnRestore, the JIT generates FSD code. This is problematic for AOT as either:
1. An existing SCC will fail validation, since the AOT code therein will not have been generated with FSD, or
2. An unpopulated SCC will contain FSD code, which will be useless for any JVM that does not have FSD enabled
This commit delays AOT validation until after restore; this ensures that AOT code from the SCC can be loaded post-restore, and that any code added to the SCC is maximally sharable.
Parent issue: https://github.com/eclipse-openj9/openj9/issues/18866

Delay AOT validation until restore under -XX:+DebugOnRestore

---

runtime/gc_base/StringTable.cpp
test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_String.java

LATIN1 String constants were only created in jdk17 and later. The JCL for jdk11 creates LATIN1 Strings and the VM needs to match.
Issue https://github.com/eclipse-openj9/openj9/issues/19334
Grinder showing the new test fails without this fix.
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3482

jdk11 should create LATIN1 String constants

---

runtime/gc_base/ClassLoaderManager.cpp
runtime/gc_base/ClassLoaderManager.hpp

Use uintptr_t instead of UDATA, fix formatting etc.

Clean up MM_ClassLoaderManager class

---

runtime/gc_base/StringTable.cpp
test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_String.java

LATIN1 String constants were only created in jdk17 and later. The JCL for jdk11 creates LATIN1 Strings and the VM needs to match.
Issue https://github.com/eclipse-openj9/openj9/issues/19334
Port of https://github.com/eclipse-openj9/openj9/pull/19337 for 0.45

(0.45) jdk11 should create LATIN1 String constants

---

runtime/gc_base/StringTable.cpp
test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_String.java

LATIN1 String constants were only created in jdk17 and later. The JCL for jdk11 creates LATIN1 Strings and the VM needs to match.
Issue https://github.com/eclipse-openj9/openj9/issues/19334
Port of https://github.com/eclipse-openj9/openj9/pull/19337 for 0.44

(0.44) jdk11 should create LATIN1 String constants

---

jcl/src/java.base/share/classes/java/lang/Access.java

JDK23 JavaLangAccess APIs updates
Added:
```
public int getCharsLatin1(long i, int index, byte[] buf);
public int getCharsUTF16(long i, int index, byte[] buf);
public void putCharUTF16(byte[] val, int index, int c);
public long stringConcatHelperPrepend(long indexCoder, byte[] buf,
String value);
public long stringConcatMix(long lengthCoder, char value);
public int stringSize(long x);
```
Removed:
```
public long stringConcatCoder(char value);
public long stringBuilderConcatMix(long lengthCoder, StringBuilder sb);
public long stringBuilderConcatPrepend(long lengthCoder, byte[] buf,
StringBuilder sb);
```
Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/776

JDK23 JavaLangAccess APIs updates

---

buildenv/jenkins/variables/defaults.yml

This is to show junit report in the test builds for jtreg tests.
related: https://github.com/adoptium/aqa-tests/issues/5206

set test_keep_reportdir to true for extended.functional

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java
test/functional/cmdLineTests/reflectCache/playlist.xml

The following Java system properties are impacted:
- `reflect.cache`
- `java.lang.ClassLoader.lazyInitialization`
`toLowerCase()` generates a `LambdaForm` for the associated `invokedynamic`.
`LambdaForm` generation code relies on `ClassLoader.bootstrapClassLoader`,
which is `NULL` and no longer initialized in JDK23. This causes a NPE.
In JDK23+, the above two Java system properties are no longer processed
with `toLowerCase()` since they are undocumented and only used for
debugging. This prevents a NPE.
Related: #19301

Rework processing of Java system properties in java.lang.ClassLoader

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/il/J9MethodSymbol.cpp

The Unsafe.allocateUninitializedArray0 does not require zero init. This change skip zero initialization for Unsafe.allocateUninitializedArray0.

Skip zero initialization for Unsafe.allocateUninitializedArray0

---

runtime/gc_base/RootScanner.cpp
runtime/gc_base/RootScanner.hpp
runtime/gc_glue_java/ScavengerBackOutScanner.cpp
runtime/gc_glue_java/ScavengerBackOutScanner.hpp
runtime/gc_glue_java/ScavengerDelegate.cpp
runtime/gc_glue_java/ScavengerRootClearer.hpp

Due to no completeScan for scavenge backout(there are no need to fixup the references for regular objects in evacurated regions), the native stack references of unmounted continuation Objects might still point to the reversedForwardedObject in survior or tenure regions, it would cause the Assertion in following global GC.
- scanContinuationNativeSlots for the continuation Objects during reverseForwardedObject.
- there is no need backoutContinuationObjects processing, instead, just backout continuation list in new regions.
- -Xgc:fvtest=forceScavengerBackout (for testing/debug only) is triggered wrong location(should not be triggered after continuationObjects processing, there is no more new allocation needed and no possible backout in real cases), do not use …

Fixup stack references of unmounted continuation for scavenge backout

---

jcl/jpp_configuration.xml
jcl/src/java.base/share/classes/java/lang/Object.java

JDK23 update `Blocker.begin()/end()`
Updated `jpp_configuration.xml to refer rt-compressed.sunJava22.jar` & `rt-compressed.sunJava23.jar`.
Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/782

JDK23 update Blocker.begin()/end()

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/MethodToBeCompiled.cpp
runtime/compiler/control/MethodToBeCompiled.hpp

When checking for the eligibility of a method to be JITServer AOT cache stored or loaded, we now check that the flag `_doNotAOTCompile` is not set in all cases. (This flag was also renamed, from the somewhat misleading `_doNotUseAotCodeFromSharedCache`). This has the effect of ensuring that when any unrecoverable AOT-related method compilation failures occur, JITServer clients will not request that those methods be JITServer AOT cache compiled during a subsequent compilation attempt.

Fix JITServer AOT cache compilation retry logic

---

runtime/gc_base/RootScanner.cpp
runtime/gc_base/RootScanner.hpp
runtime/gc_glue_java/ScavengerBackOutScanner.cpp
runtime/gc_glue_java/ScavengerBackOutScanner.hpp
runtime/gc_glue_java/ScavengerDelegate.cpp
runtime/gc_glue_java/ScavengerRootClearer.hpp

Due to no completeScan for scavenge backout(there are no need to fixup the references for regular objects in evacurated regions), the native stack references of unmounted continuation Objects might still point to the reversedForwardedObject in survior or tenure regions, it would cause the Assertion in following global GC.
- scanContinuationNativeSlots for the continuation Objects during reverseForwardedObject.
- there is no need backoutContinuationObjects processing, instead, just backout continuation list in new regions.
- -Xgc:fvtest=forceScavengerBackout (for testing/debug only) is triggered wrong location(should not be triggered after continuationObjects processing, there is no more new allocation needed and no possible backout in real cases), do not use …

(0.45) Fixup stack references of unmounted continuation for scavenge backout

---

jcl/src/java.base/share/classes/java/lang/J9VMInternals.java

Change fastIdentityHashCode so the interpreter path is identical to what it was before #19172 was merged.
javanext/issues/438

Possible fix for perf regression

---

jcl/src/jdk.management/share/classes/com/ibm/virtualization/management/GuestOSMXBean.java
jcl/src/jdk.management/share/classes/com/ibm/virtualization/management/GuestOSMemoryUsage.java
jcl/src/jdk.management/share/classes/com/ibm/virtualization/management/GuestOSProcessorUsage.java
jcl/src/jdk.management/share/classes/com/ibm/virtualization/management/HypervisorMXBean.java

Clarify the support statement for HypervisorMXBean and GuestMXBean given that VMWare support is not open source.

VMWare support is not open source, clarify Hypervisor/Guest MXBean

---

test/functional/Java9andUp/playlist.xml
test/functional/Java9andUp/src/org/openj9/test/varhandle/VarHandleUtilTests.java

The test has been updated to reflect the new spec changes related
to alignment promises which cannot be guaranteed.
See https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/4c9db1acce69d65ec6af73ca794f9ca44ceb0930 for more details.
Closes: #19302

Fix the VarHandle test for JDK23

---

jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Dump.java

If there is a SecurityManager installed then the os.name system property is not available by default.

Avoid AccessControlException in com.ibm.jvm.Dump.<clinit>

---

jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Dump.java

If there is a SecurityManager installed then the os.name system property is not necessarily available.
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/19394

(0.45) Avoid AccessControlException in com.ibm.jvm.Dump.<clinit>

---

test/functional/cmdLineTests/loadLibraryTest/playlist.xml

Issue https://github.com/eclipse-openj9/openj9/issues/18975
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/19171

(0.45) Exclude cmdLineTester_loadLibraryTests on Windows jdk22+

---

buildenv/jenkins/jobs/infrastructure/Cleanup-Nodes.groovy

The Cleanup-Nodes.groovy script tries to delete all datasets in the zos system including some important ones needed for compiles.
This way we can ensure we delete the ones from jvm crashes alone.

Delete only datasets created from JVM crashes 

---

runtime/compiler/env/ClassLoaderTable.cpp

When removing entries from the class loader table during class unloading, the current implementation uses the wrong shared cache API `isPointerInSharedCache()` (which is only intended for the metadata section of the SCC) to check whether the class loader identifying name string is stored in the SCC or in the persistent allocator heap. This can result in a fatal assertion when using both the JITServer AOT cache and the local SCC, as well as memory corruption since SCC memory ranges get added to the persistent allocator free lists. This commit fixes the issue by using the correct API `isPtrToROMClassesSectionInSharedCache()`.

Fix fatal assertion in class loader table during class unload

---

runtime/gc_trace/TgcAllocation.cpp

Add a couple of columns in TGC allocation stats report for single object allocations (directly from heap, rather then from TLH).
This is for per-thread report. Cumulative report for such allocations already exists.

TGC alloc non-tlh per thread

---

test/functional/JIT_Test/playlist.xml
test/functional/Java8andUp/playlist.xml
test/functional/UnsafeTest/playlist.xml

Close https://github.com/eclipse-openj9/openj9/issues/19390
Added native tag to the following tests:
- JCL_Test
- JCL_Test_none_SCC
- jit_jar
- UnsafeTests

add native tag to tests

---

jcl/src/java.base/share/classes/jdk/internal/foreign/abi/UpcallLinker.java
test/TestConfig/resources/excludes/latest_exclude_21.txt
test/functional/Java21Only/build.xml
test/functional/Java21Only/playlist.xml
test/functional/Java21Only/src/org/openj9/test/jep442/downcall/InvalidDownCallTests.java
test/functional/Java21Only/src/org/openj9/test/jep442/downcall/MultiThreadingTests2.java
test/functional/Java21Only/src/org/openj9/test/jep442/downcall/StructTests1.java
test/functional/Java21Only/src/org/openj9/test/jep442/downcall/StructTests2.java
test/functional/Java21Only/src/org/openj9/test/jep442/downcall/UnionStructTests.java
test/functional/Java21Only/src/org/openj9/test/jep442/downcall/UnionTests.java
test/functional/Java21Only/testng_210.xml

The changes only enable the downcall specific tests for primitives
on z/OS to ensure FFI functionally works as expected given the
related code issues with the remaining test cases have not yet been
resolved on z/OS.
Related: [Internal 441](https://github.ibm.com/runtimes/javanext/issues/441)

[FFI_JDK21/Test] Enable the downcall tests for primitives on z/OS

---

jcl/src/java.base/share/classes/java/lang/Object.java

Previous jdk23 builds were hanging, it's looking better with this change to match OpenJDK.
[8329593: Drop adjustments to target parallelism when virtual threads](https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/782/commits/e592d365bdcf133bc740531eba65f5bc01cedd0d)
Related to https://github.com/eclipse-openj9/openj9/pull/19374
Hanging builds https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK23-with-System/5/
First PR build https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/517/

jdk23 Blocker.begin() in Object.wait is only called for virtual threads

---

runtime/jcl/common/jdk_internal_misc_ScopedMemoryAccess.cpp
runtime/oti/j9nonbuilder.h
runtime/vm/AsyncMessageHandler.cpp
runtime/vm/jvminit.c
runtime/vm/vmthinit.c

There are gaps where async exceptions are not processed in time (e.g.
JIT compiled code in a loop). Threads will wait in `closeScope0` until
`J9VMThread->scopedError` (async exception) is transferred to
`J9VMThread->currentException`. The wait prevents a `MemorySession` to be
closed until no more operations are being performed on it.
Related: https://github.com/eclipse-openj9/openj9/issues/13211

ScopedMemoryAccess closeScope0 synchronization

---

jcl/src/java.base/share/classes/java/lang/PinnedThreadPrinter.java

`JDK21` adds `PinnedThreadPrinter.printStackTrace(out, reason, printAll)`
Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/150

JDK21 adds PinnedThreadPrinter.printStackTrace(out, reason, printAll)

---

jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/ExtendedThreadMXBeanImpl.java
test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestThreadMXBean.java

To match OpenJDK.
https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/5b83d98d6fc1
This should be merged at the same time as jdk8 acceptance is promoted.
Doc issue https://github.com/eclipse-openj9/openj9-docs/issues/1326

Add ThreadMXBean.getTotalThreadAllocatedBytes() impl, and jdk8 support

---

jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/ExtendedThreadMXBeanImpl.java

Related to https://github.com/eclipse-openj9/openj9/pull/19436

Only @Override getTotalThreadAllocatedBytes in OpenJ9 builds

---

runtime/compiler/optimizer/J9ValuePropagation.cpp

The implementations of String.indexOf operations cast the target char to a byte if Latin-1 encoded Strings are involved.  The value might be cast to type byte by the caller or in the implementation itself, depending on the JDK version.
Value Propagation has to ensure that it uses signed byte comparisons if it transforms an indexOf involving a known String to replicate the run-time behaviour that otherwise would have resulted, regardless of JDK version.
Port of OpenJ9 pull request #19428 to v0.44.0-release branch.
Fixes:  #18974

(0.44) Use signed comparisons for Latin-1 encoded indexOf in VP

---

runtime/gc_glue_java/ConfigurationDelegate.hpp

We need to reset the root of global lists(unfinalizedObjectLists,
OwnableSynchronizerObjectLists, ContinuationObjectLists) for rebuilding
the lists(array of sublists, the size of array match to gcThreadCount),
in case the gcThreadCount in restore env is more than the gcThreadCount
in original env.
Backup and reset root of global lists before reinitializeForRestore
and restore the root of global lists if the lists were not rebuilt
during reinitializeForRestore.
fix:https://github.com/eclipse-openj9/openj9/issues/19421

Fix resetting global lists issue in CRIU reinitializeForRestore

---

longabout.html
runtime/include/about.html
runtime/zlib/about.html

zlib was updated via https://github.com/eclipse-openj9/openj9/pull/18137 but the doc was not updated to match.

Update zlib version in doc to match version used

---

longabout.html
runtime/include/about.html
runtime/zlib/about.html

zlib was updated via https://github.com/eclipse-openj9/openj9/pull/18137 but the doc was not updated to match.
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/19451

(0.44) Update zlib version in doc to match version used

---

longabout.html
runtime/include/about.html
runtime/zlib/about.html

zlib was updated via https://github.com/eclipse-openj9/openj9/pull/18137 but the doc was not updated to match.
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/19451

(0.45) Update zlib version in doc to match version used

---

runtime/cmake/platform/os/win.cmake
runtime/compiler/CMakeLists.txt

On Windows, automatic dependency tracking for `ASM_NASM` files doesn't play nicely with `fixpath.sh`. Remove the `nasm` options that would produce `*.d` files (`cmake` silently treats missing `*.d` files as if they were empty).
I tested this with cmake version 3.28.3 (the current default from cygwin setup) and with version 3.18.0 (built locally from source) which predates the introduction of automatic dependency tracking for `ASM_NASM` files.
Fixes #19410.

cmake: disable automatic dependency tracking for .nasm files

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/env/PersistentAllocator.cpp
runtime/compiler/env/PersistentAllocator.hpp
runtime/compiler/env/PersistentAllocatorKit.hpp
runtime/compiler/runtime/IProfiler.cpp
runtime/compiler/runtime/IProfiler.hpp
runtime/compiler/runtime/JITServerIProfiler.cpp
runtime/compiler/runtime/JITServerIProfiler.hpp

This commit allocates memory for IProfiler data using a dedicated persistent memory allocator. 
This allocator is instructed to use mmap and to back the allocator memory by a file or swap.
Heuristics dictate when to issue the disclaim operations.
The disclaim can be disabled with -Xjit:disableIprofilerDataDisclaiming

Disclaim IProfiler memory

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/env/j9methodServer.hpp
runtime/compiler/net/CommunicationStream.hpp

Otherwise gcc 13 reports a narrowing warning on line 2676 of `j9methodServer.cpp`.
The only use of the constructor provides an argument of type `int32_t`.

TR_J9ServerMethod: change type of cpIndex to match usage

---

runtime/vm/gphandle.c

This commit changes the output of floating point values in writeGPInfo(). Floating point values are printed as "registerName value", and this commit changes it to "registerName=value" to align with outputs of other kinds.

Fix the output of floating point values in writeGPInfo()

---

runtime/compiler/env/PersistentAllocator.cpp

Rationale: Older compilers do not understand the range-based loop even though it's part of the C++-11 standard.

Change "for" loop from range-based to iterator based

---

runtime/compiler/x/amd64/codegen/AMD64JNILinkage.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/X86PrivateLinkage.cpp

Swept through x86 codegen and replaced XORRegReg with XOR4RegReg when used to zero a register
Closes #19236
Signed-off-by: Ryan Stevens <restevens52@gmail.com>

Use 32-bit XOR to zero registers in x64

---

runtime/vm/extendedMessageNPE.cpp
runtime/vm/j9vm.tdf

`NPE` extended message skips `npePC` that is `BYTECODE_TEMP_CHANGED`
`npePC` is expected to be the bytecode offset where the `NPE` message will be generated. Skip the NPE extended message generation when it is `BYTECODE_TEMP_CHANGED`.
closes https://github.com/eclipse-openj9/openj9/issues/19163

NPE extended message skips npePC that is BYTECODE_TEMP_CHANGED

---

runtime/compiler/runtime/CRRuntime.cpp

Add required includes to avoid uses of incomplete types `TR::CompilationInfoPerThread` and `TR_IProfiler`.

Fix compile errors with JIT server disabled

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/j9method.cpp

Native call to java/lang/Class.getStackClass from the methods that are
being inlined in another method can be folded to load of JavaLangClass
from J9Class pointer when the inlined index of the caller of the
getStackClass is higher than the known constant argument to
getStackClass.

Inline native call to java/lang/Class.getStackClass when possible

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/VirtualThreadsCommand.java

Continuation objects are added to GC list on create, which may not
yet be assoicated with vthread object yet at time when coredump is
generated. DDR needs to correctly handle null vthread reference.
Fix: #18859 

Fix !vthreads command error with uninitialized Continuations

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

For callees annotated with @IntrinsicCandidate, we shoud ignore any later redefinition as these methods are meant to have special handling for performance reasons. This annotation is only used in JCL code.

Skip HCR guards for inlining intrinsifiable methods

---

runtime/j9vm/java11vmi.c

Thread 1 creates java.base:
- acquires module (classLoaderModuleAndLocationMutex) mutex
- acquires class mutex (classTableMutex) to update all bootstrap classes
Thread 2 loads a class
- aquires class mutex
- acquire module mutex to search for class location
There is a scenario where Thread 1 acquires module mutex, then thread 2 acquires class mutex. Thread 1 cannot complete creating java.base because it needs the class mutex and Thread 2 cannot complete class loading because it needs the module mutex.
Related: https://github.com/eclipse-openj9/openj9/issues/19439
Proposed solution is for Thread 1 to acquire the class mutex first if it is known that it will be needed.

Prevent deadlock in java.base creation

---

doc/build-instructions/Build_Instructions_V8.md

Java 8 builds on Windows fail without it. It was inadvertently removed via #17603.

Restore advice for setting INCLUDE environment variable

---

runtime/jvmti/jvmtiThreadGroup.c

While acquiring exclusive VM access, VM access can be released.
GC might relocate threadGroupObject when VM access is released.
threadGroupObject is refetched to avoid a stale object.
Fixes: #19438

Fix stale object in jvmtiGetThreadGroupChildren

---

runtime/compiler/il/J9MethodSymbol.cpp

Converting numbers to string does nor require zero memory allocation as it overwrite the whole memory. The Integer.toString is an intrinsic candidate which makes it safer to do this optimization. We inline the "getChars" method for both Integer and Long classes [here](https://github.com/eclipse-openj9/openj9/blob/0db560ffdcfc6bad37f6382fddf50fdb3f22b788/runtime/compiler/z/codegen/J9CodeGenerator.cpp#L3956) which does the to string conversion!
I looked into some real world applications and this change does not have a significant impact on nonZeroTLH utilization but since it is easy enough, I decided to raise this PR.
@r30shah Please let me know if this change looks okay to you.

Use non zero tlh for int and long to string

---

runtime/gc_structs/VMThreadStackSlotIterator.cpp

GC Thread scanContinuationNativeSlots via walkContinuationStackFrames(), new threadObject parameter is required for calling walkContinuationStackFrames, retrieving the virtual thread Object during GC might trigger a read barrier in concurrent scavenger mode, because threadObject is not neccessary for GC case, so pass NULL as threadObject for call function walkContinuationStackFrames() to aviod the potential assertion.
fix: https://github.com/eclipse-openj9/openj9/issues/19486

Pass NULL as threadObject to walkContinuationStackFrames in GC

---

jcl/src/java.base/share/classes/java/lang/Access.java

`JDK23` adds `JavaLangAccess.initialSystemErr()`
Decorated `@OverRide` with `!INLINE-TYPES` because `Valhalla` extension repo doesn't have latest openjdk update yet.
This fixes JDK23 abuild failure - https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_linux_OpenJDK/660/consoleFull

JDK23 adds JavaLangAccess.initialSystemErr()

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.cpp
runtime/compiler/net/MessageTypes.hpp

After work to improve constant field folding, the number of VM_isClassLibraryClass messages increased a lot affecting the CPU overhead of the client.
This commit reimplements the `TR_J9ServerVM::isClassLibraryClass()` frontend query taking advantage of the caches maintained by JITServer and eliminating said messages completely.

Eliminate VM_isClassLibraryClass messages for JITServer

---

runtime/include/j9cfg.h.ftl
runtime/include/j9cfg.h.in
runtime/vm/jvminit.c

Fixes: https://github.com/eclipse-openj9/openj9/issues/19395

Add new feature flag J9VM_OPT_PORTABLE_SHARED_CACHE to guard portable shared class flag variable

---

runtime/compiler/z/codegen/J9TreeEvaluator.cpp

`ETND` does not take a source register.
While investigating https://github.com/eclipse-openj9/openj9/issues/14054 I ran into a SIGILL failure. The illegal instruction was encoded as B2EC0011. From the jitdump, this corresponds to `ETND GPR1,GPR1`. `ETND` only operates on one register encoded in bits 24-27 of the instruction, and bits 28-31 should be left 0 [1]. `ETND` is encoded by `TR::S390RRInstruction::generateBinaryEncoding()`, where the second register operand, when it exists, is encoded into bits 28-31 [2], leading to an incorrectly encoded `ETND`. By not unnecessarily passing `codeReg` as a source register when the `ETND` is generated, we avoid the incorrect encoding.
[1] https://hurgsa.ibm.com:7191/projects/h/hlasmhursley/public/SA22-7832-13/0705103.htm
[2] …

Z: Don't pass sreg to ETND

---

runtime/compiler/runtime/JITServerAOTDeserializer.cpp
runtime/compiler/runtime/JITServerAOTDeserializer.hpp

When deserializing a method from the JITServer AOT cache, the client, if ignoring its local SCC, must ensure that all serialization records referred to by that method are still valid. This is necessary to fulfill the requests for cached data that the TR_J9DeserializerSharedCache will make of the deserializer during the relocation of that method.
A few verbose log lines related to class loader deserialization failures due to class loader invalidation were also added.
Fixes: https://github.com/eclipse-openj9/openj9/issues/19461

Ensure all necessary cached JITServer AOT cache records are valid during deserialization

---

runtime/shared_common/shrinit.cpp

Noticed while reviewing #19399; see https://github.com/eclipse-openj9/openj9/pull/19399#discussion_r1586793937.

Correct condition for printing portable shared cache option help

---

runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/control/JITServerHelpers.hpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp
runtime/compiler/runtime/JITServerAOTCache.cpp
runtime/compiler/runtime/JITServerAOTCache.hpp
runtime/compiler/runtime/JITServerAOTDeserializer.cpp
runtime/compiler/runtime/JITServerAOTSerializationRecords.hpp
runtime/compiler/runtime/JITServerROMClassHash.cpp
runtime/compiler/runtime/JITServerROMClassHash.hpp

~~This draft PR implements object array class support for JITServer AOT cache. Currently untested.~~
This PR enables AOT cache serialization and load for methods that refer to array classes in their relocation and validation records, specifically object arrays and multidimensional primitive arrays. Since such classes share the same ROMClass named `[L`, we disambiguate them in the AOT cache by using the full array class signature instead of the ROMClass name. We build the ROMClass hash for an array class by combining the ROMClass hash of the `[L` object array class, the ROMClass hash of the base component class, and the number of array dimensions.

JITServer AOT cache array class support

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp

JITServer clients will now periodically call `malloc_trim(0)`, at a configurable interval set by the new option
`-Xjit:jitserverMallocTrimInterval=<time in ms>`. The default is every 30s (30000ms). Setting the interval to 0 will disable the feature entirely.

Periodically issue malloc_trim at JITServer client

---

runtime/compiler/runtime/Runtime.cpp

This commit removes obsolete JIT helper entries for arraycopy.

AArch64: Remove obsolete JIT helper entries for arraycopy

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp

For the recognized method `JITHelpers.intrinsicIndexOfLatin1`, the ch parameter is meant to be interpreted as an unsigned byte with a value of 0x00-0xFF. However, it gets passes into the method as a signed byte. This means for values 0x80-0xFF the data is sign extended inside of the register.
The fast path code generated by `inlineIntrinsicIndexOf_P10` has a check the checks if the bits other than the lowest 8 bits are 0 and returns -1 early if this is the case. But, this check is wrong. It is possible to have a valid parameter where there upper bits are not 0 due to the sign extension.
This fix removes the check and instead zeros out the bits other than the lowest 8 bits. This is safe to do since it is known in advance that the byte data is meant to be interpreted as an unsigned byte and …

Remove incorrect check in fast path indexOf code

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp

For the recognized method `JITHelpers.intrinsicIndexOfLatin1`, the ch parameter is meant to be interpreted as an unsigned byte with a value of 0x00-0xFF. However, it gets passes into the method as a signed byte. This means for values 0x80-0xFF the data is sign extended inside of the register.
The fast path code generated by `inlineIntrinsicIndexOf_P10` has a check the checks if the bits other than the lowest 8 bits are 0 and returns -1 early if this is the case. But, this check is wrong. It is possible to have a valid parameter where there upper bits are not 0 due to the sign extension.
This fix removes the check and instead zeros out the bits other than the lowest 8 bits. This is safe to do since it is known in advance that the byte data is meant to be interpreted as an unsigned byte and …

(0.44.0) Removes incorrect check in fast path indexOf code

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy

The plinux machine doesn't boot and it's unlikely to be working any time soon.

Remove plinux from "all" when running PR builds

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/UnsafeFastPath.cpp

VarHandle operation methods are mostly calls to Unsafe methods, which under certain circumstances can be folded into simple loads and stores in UnsafeFastPath as we can determine the object base and offsets at compile time. In other cases, we can unlock the fast paths for the Unsafe operations by setting the appropriate flags for CodeGen to inline the intrinsics if the platform supports the operations.
~In draft state while I perform further testing and performance investigations.~

Optimize OpenJDK VarHandle operation methods

---

runtime/tests/port/j9sockTest.c

This commit removes extraneous parentheses in j9sockTest.c for avoiding a compiler warning.

Remove extraneous parentheses in j9sockTest.c

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/InterpreterEmulator.cpp
runtime/compiler/optimizer/MethodHandleTransformer.cpp

The `MethodHandle` can be found without knowing the result of this call because it's looked up based on the original `VarHandle` reference, not the one from `directVarHandleTarget()`, and this is enough to allow the inliner to inline the entire access.
Additionally, the compiler has been failing to determine the result anyway. The logic deleted here would give up whenever the `VarHandle` was an instance of a subclass, which it seems is always the case.
Nothing looks for `directVarHandleTarget()` anymore, so it will no longer be recognized. But `asDirect()` will continue to be recognized for `isJSR292SmallGetterMethod()`.

Stop predicting VH.asDirect()/directVarHandleTarget() during inlining

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/runtime/MetaData.cpp

- identify last warm instruction during instruction selection
- the code is only enabled if -Xjit:splitWarmAndColdBlocks option is on

Split warm and cold blocks

---

runtime/jcl/common/shared.c
runtime/jcl/j9jcl.tdf
test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-5.xml
test/functional/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml

Use the port library to check if path leads to a directory or file to support jar files that may not have the typical *.jar ending.
Fixes: https://github.com/eclipse-openj9/openj9/issues/19378

Check file type for shared class cache jar files

---

runtime/jcl/common/shared.c
runtime/jcl/j9jcl.tdf
test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-5.xml
test/functional/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml

Port solution for https://github.com/eclipse-openj9/openj9/issues/19378 to 0.46
The change in the master branch is https://github.com/eclipse-openj9/openj9/pull/19380
Use the port library to check if path leads to a directory or file to support jar files that may not have the typical *.jar ending.

(0.46.0) Check file type for shared class cache jar files

---

jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
jcl/src/jdk.management/share/classes/module-info.java.extra
test/functional/JLM_Tests/build.xml
test/functional/JLM_Tests/playlist.xml
test/functional/cmdLineTests/criu/build.xml

Export `jdk.management/jdk.crac.management` only when `CRaC` is enabled
Use reflection to get module `jdk.management`, export `jdk.crac.management` unconditionally, only when `CRaC` is enabled, assuming module `jdk.management` is to be loaded when `CRaC` is enabled;
Updated tests with `--add-exports jdk.management/jdk.crac.management=ALL-UNNAMED`.
closes https://github.com/eclipse-openj9/openj9/issues/19534

Export jdk.management/jdk.crac.management only when CRaC is enabled

---

doc/build-instructions/Build_Instructions_V11.md
doc/build-instructions/Build_Instructions_V17.md
doc/build-instructions/Build_Instructions_V21.md
doc/build-instructions/Build_Instructions_V8.md

This commit adds a comment in build instructions that non-cmake build is not supported on AArch64 macOS.
[skip ci]

Add comment on non-cmake build on AArch64 macOS

---

jcl/src/java.base/share/classes/java/lang/J9VMInternals.java

The need for the `jdk.management` module should due to application requirements, not just that support for `CRaC` is enabled.

Don't throw an exception unnecessarily

---

doc/release-notes/0.44/0.44.md

https://github.com/eclipse-openj9/openj9-docs/issues/1341
The -XX:+CompactStrings option is having an adverse impact on the indexOf() method results
[skip ci]

Added a new Known limitation in 0.44.0 and 0.45.0 release note

---

runtime/libffi/z/ffi64.c
runtime/libffi/z/sysvz64.s

Adds support for passing struct type arguments and receiving struct type returns in libffi
- Struct arguments are now properly loaded into registers and the argument area in sys64z.s
- Struct returns are now appropriately handled in sys64z.s
- Doesn't pad argument buffer in ffi_prep_args to save space.
Signed-off-by: Austin Wells <austin.wells@mail.utoronto.ca>

Update struct support in embedded libffi

---

runtime/shared/shrclssup.c

SCC is enabled by default when -Xshareclasses is not specified in the CML. cacheDirPerm should be set to J9SH_DIRPERM_ABSENT in this case.
Closes #19328

(0.46)cacheDirPerm should be set if -Xshareclasses is not specified

---

runtime/compiler/runtime/IProfiler.cpp

IProfiler for JITServer was disabled by mistake by PR #19355 causing a severe performance degradation. This commit re-enables the usage of IProfiler.

(0.46.0) Re-enable IProfiler for JITServer

---

runtime/gc_glue_java/ScavengerBackOutScanner.cpp
runtime/gc_glue_java/ScavengerBackOutScanner.hpp
runtime/gc_glue_java/ScavengerDelegate.cpp

In https://github.com/eclipse-openj9/openj9/pull/19388, we are fixing up stack references of unmounted continuation for scavenge backout during reverseForwardedObject(), but the fixup would depend on the related resverseForwardedPointer installed, so the scan for fix-up need to be done after all resverseForwardedPointer are installed, otherwise some fix-up would miss.
Using backoutContinuationObjects() to scan/fixup all of continuation stack references in evacuate region.

Fix the references in continunation java stacks for scavenger backout

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/runtime/MetaData.cpp

- identify last warm instruction during instruction selection
- the code is only enabled if -Xjit:splitWarmAndColdBlocks option is on

(0.46) Split warm and cold blocks

---

test/TestConfig/resources/excludes/latest_exclude_21.txt
test/functional/Java21Only/src/org/openj9/test/jep442/downcall/MultiThreadingTests2.java
test/functional/Java21Only/src/org/openj9/test/jep442/downcall/StructTests1.java
test/functional/Java21Only/src/org/openj9/test/jep442/downcall/StructTests2.java

The change enables the excluded tests specific to the default
library loading and struct given the related issues have been
resolved via https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/159 and https://github.com/eclipse-openj9/openj9/pull/19468.
Related: [Internal 441](https://github.ibm.com/runtimes/javanext/issues/441)

[FFI_test] Enable the excluded tests on z/OS in JDK21

---

runtime/compiler/runtime/J9CodeCacheManager.cpp

In order to eliminate helper trampolines, OpenJ9 tries to allocate the code cache in the vicinity of the JIT dll. This intention is signalled by using a preferredStartAddress when calling allocateCodeCacheSegment(). Currently, only x86-64 uses this approach.
This commit implements the following changes:
- For Linux, we increase the search space to almost 2GB. Also, we prefer to start with an approach that uses the smaps pseudofile to find memory ranges where the code cache could be allocated.
- For Windows, we keep a smaller memory search space because smaps are not available to speed up the search process.
- We compute a preferred alignment and pass that to the VM. For x86-64 this alignment is 2 MB, i.e. the size of large pages used by the Transparent Huge Page (THP) mechanism. The …

(0.46.0) Changes to the code cache repository allocation code

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp

* Call NoZeroInit anewarray helper when appropriate on x86
* Misc. x86 allocation path improvements
* Remove obsolete TR_EnableNewAllocationProfiling code
* Misc. x86 allocation path improvements
* Cleanup x86 object initialization path
* Move x86 inlined allocation verification out of line
* Move off-heap dataAddr allocation into a separate function
* Use ScratchRegisterManager in x86 inline allocations
* Misc. code cleanup for readability
* Remove allocated object cache line alignment code on Power and x86
* Remove deprecated shouldAlignTLHAlloc() checks on TR::Nodes
* Compare variable array sizes as 32-bits for x86 inline allocations
* Add knobs to disable x86 object allocation features
* Misc. readability and formatting improvements to x86 inline allocation
* Do not perform zero …

Improve x86 inline object allocations

---

runtime/compiler/codegen/J9CodeGenerator.hpp
runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/z/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.hpp

`ArraysSupport.vectorizedHashCode` [1] is an intrinsic candidate introduced in JDK21. The hash function used is the same as the one used for hashing Strings, so this change leverages that by recognizing `ArraysSupport.vectorizedHashCode` and using the preexisting accelerated implementation of `String.hashCode`.
[1] https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/src/java.base/share/classes/jdk/internal/util/ArraysSupport.java#L200

Z: Accelerate ArraysSupport.vectorizedHashCode

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/control/OptionsPostRestore.hpp
runtime/compiler/env/J2IThunk.cpp
runtime/compiler/runtime/CRRuntime.cpp
runtime/compiler/runtime/J9CodeCache.cpp
runtime/compiler/runtime/J9CodeCache.hpp
runtime/compiler/runtime/J9CodeCacheManager.cpp
runtime/compiler/runtime/J9CodeCacheManager.hpp
runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp
runtime/compiler/x/codegen/X86PrivateLinkage.cpp

- use the same heuristcs for code cache disclaim as for data cache
- disclaim starting from the cold code
- move stack overflow outline instructions into the warm area to increase disclaim efficiency
- code is enabled with -Xjit:enableCodeCacheDisclaiming

Disclaim Cold Code Cache

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/compile/J9SymbolReferenceTable.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/ilgen/IlGenerator.cpp
runtime/compiler/ilgen/Walker.cpp
runtime/compiler/optimizer/EscapeAnalysis.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9ValuePropagation.cpp

This change generates inline IL in Value Propagation for references to `Class.getComponentType()`.  That method was previously only inlined if the Class was known at compile-time.  If the Class is known to be an array class at compile-time, the generated IL will load the `<componentClass>` from the `j9ArrayClass`; otherwise, it will generate a run-time test of whether the Class is an array class before returning the `<componentClass>` or a null reference.
Calls to `Object.getClass()` are also marked as non-null during IL generation as that method is known to always return a non-null reference.  That exposes opportunities to optimize uses of `Class` objects that require the reference to be known to be non-null, including inlining calls to `Class.getComponentType()` in Value Propagation. …

Inline Class.getComponentType and refactor IL generation to access classDepthAndFlags field of j9Class

---

runtime/gc_glue_java/ScavengerBackOutScanner.cpp
runtime/gc_glue_java/ScavengerBackOutScanner.hpp
runtime/gc_glue_java/ScavengerDelegate.cpp

In https://github.com/eclipse-openj9/openj9/pull/19388, we are fixing up stack references of unmounted continuation for scavenge backout during reverseForwardedObject(), but the fixup would depend on the related resverseForwardedPointer installed, so the scan for fix-up need to be done after all resverseForwardedPointer are installed, otherwise some fix-up would miss.
Using backoutContinuationObjects() to scan/fixup all of continuation stack references in evacuate region.
Port of https://github.com/eclipse-openj9/openj9/pull/19559

(0.46) Fix the references in continunation java stacks for scavenger backout

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/CompilationThread.hpp
runtime/compiler/control/CompileBeforeCheckpoint.cpp
runtime/compiler/control/CompileBeforeCheckpoint.hpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9CompilationStrategy.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/MethodToBeCompiled.cpp
runtime/compiler/control/MethodToBeCompiled.hpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/runtime/CRRuntime.cpp
runtime/compiler/runtime/CRRuntime.hpp
runtime/compiler/runtime/IProfiler.hpp

This PR includes several heuristics to minimize the performance impact of `-XX:+DebugOnRestore`:
- Generate FSD compilations pre-checkpoint
- Compile "important" methods pre-checkpoint
- "important" methods are those that are in the SCC, that would have
been loaded at scount=20
- These "important" methods are compiled without FSD enabled
- Compile failed compilations pre-checkpoint as opposed to post-restore
- Reset environment after proactive compilation 
- Don't change JVM Phase pre-checkpoint
- Enable IProfiling during startup; because SCC validation occurs post
restore, there is no persistent IProfiling data to pull from
- Turn off IProfiling on restore so that the normal heuristics can turn
it back on post-startup
- Trigger recomps pre-checkpoint 
Parent issue …

Heuristics to minimize performance impact of `-XX:+DebugOnRestore`

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/control/OptionsPostRestore.hpp
runtime/compiler/env/J2IThunk.cpp
runtime/compiler/runtime/CRRuntime.cpp
runtime/compiler/runtime/J9CodeCache.cpp
runtime/compiler/runtime/J9CodeCache.hpp
runtime/compiler/runtime/J9CodeCacheManager.cpp
runtime/compiler/runtime/J9CodeCacheManager.hpp
runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp
runtime/compiler/x/codegen/X86PrivateLinkage.cpp

- use the same heuristcs for code cache disclaim as for data cache
- disclaim starting from the cold code
- move stack overflow outline instructions into the warm area to increase disclaim efficiency
- code is enabled with -Xjit:enableCodeCacheDisclaiming
Port of https://github.com/eclipse-openj9/openj9/pull/19397

(0.46) Disclaim Cold Code Cache

---

runtime/compiler/p/codegen/J9CodeGenerator.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp

Adds support for replacing calls to StringLatin1.inflate with hand tuned assembly that takes advantage of vector instructions and wider loads and stores.
StringLatin1.inflate is recognized and intentionally prevented from being inlined. During codegen, the call is changed to custom assembly instead of generating a callout.
Changes apply to 64 bit Big/Little endian on Power 8 and later.
New behavior can be disabled with the TR_DisableStringInflateIntrinsic environment variable.
These changes use the `vmrghb` and `vmrglb` instructions so they are dependent on this OMR PR that adds support for them:
https://github.com/eclipse/omr/pull/7329

Added fast implementation of StringLatin1.inflate

---

jcl/src/java.base/share/classes/com/ibm/jit/JITHelpers.java
jcl/src/java.base/share/classes/java/lang/String.java
test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_String.java

Issue https://github.com/eclipse-openj9/openj9/issues/19543
Some testing at https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/529/
There was one unrelated failure, an old known issue https://github.com/eclipse-openj9/openj9/issues/16608#issuecomment-2134284248

jdk11 always create compact Strings when possible

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp

* Call NoZeroInit anewarray helper when appropriate on x86
* Misc. x86 allocation path improvements
* Remove obsolete TR_EnableNewAllocationProfiling code
* Misc. x86 allocation path improvements
* Cleanup x86 object initialization path
* Move x86 inlined allocation verification out of line
* Move off-heap dataAddr allocation into a separate function
* Use ScratchRegisterManager in x86 inline allocations
* Misc. code cleanup for readability
* Remove allocated object cache line alignment code on Power and x86
* Remove deprecated shouldAlignTLHAlloc() checks on TR::Nodes
* Compare variable array sizes as 32-bits for x86 inline allocations
* Add knobs to disable x86 object allocation features
* Misc. readability and formatting improvements to x86 inline allocation
* Do not perform zero …

(0.46.0) Improve x86 inline object allocations

---

runtime/gc_glue_java/MarkingSchemeRootClearer.cpp
runtime/gc_glue_java/ScavengerBackOutScanner.cpp
runtime/gc_glue_java/ScavengerRootScanner.cpp

the Objects, which have been copied to survivor or tenure during concurrent scavenge, would not roll back for back out case, so in the following global marking, we need to update the forwardObject in the continuation list.

Fixup continuation lists for concurrent scavenge backout case

---

runtime/bcutil/ClassFileOracle.cpp
runtime/bcutil/ClassFileOracle.hpp

jdk/internal/vm/annotation/NullRestricted
jdk/internal/vm/annotation/ImplicitlyConstructible
jdk/internal/vm/annotation/LooselyConsistentValue
Related to https://github.com/eclipse-openj9/openj9/issues/19459

VM support for value type annotations

---

runtime/compiler/z/codegen/J9TreeEvaluator.cpp

For short arrays the hash must be calculated with signed arithmetic rather than unsigned as for chars. Additionally we were using the incorrect instruction for unpacking signed 16-bit elements into vectors. This commit resolves both  of these issues.
Resolves https://github.com/eclipse-openj9/openj9/issues/19590

Z: Correct sign for vectorizedHashCode

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/compile/J9SymbolReferenceTable.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/ilgen/IlGenerator.cpp
runtime/compiler/ilgen/Walker.cpp
runtime/compiler/optimizer/EscapeAnalysis.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9ValuePropagation.cpp

This change generates inline IL in Value Propagation for references to `Class.getComponentType()`.  That method was previously only inlined if the Class was known at compile-time.  If the Class is known to be an array class at compile-time, the generated IL will load the `<componentClass>` from the `j9ArrayClass`; otherwise, it will generate a run-time test of whether the Class is an array class before returning the `<componentClass>` or a null reference.
Calls to `Object.getClass()` are also marked as non-null during IL generation as that method is known to always return a non-null reference.  That exposes opportunities to optimize uses of `Class` objects that require the reference to be known to be non-null, including inlining calls to `Class.getComponentType()` in Value Propagation. …

[0.46.0] Inline Class.getComponentType and refactor IL generation to access classDepthAndFlags field of j9Class

---

runtime/compiler/il/J9MethodSymbol.cpp

The BigInteger.toByteArray implementation in OpenJ9 doesn't depend on zero-initialization and it is currently safe to skip that operation in that context. The Apache Harmony BigInteger implementation relies on zero-init and returns the wrong result without it. This patch limits skipping of zero-init (and NULL and bounds checks, to be conservative) for BigInteger.toByteArray to OpenJ9 builds.
Follow-up to https://github.com/eclipse-openj9/openj9/pull/19556.

Skip BigInteger zero-init & checks for OpenJ9 only

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/il/J9MethodSymbol.cpp

This patch recognizes the following BigInteger methods:
* BigInteger.BigInteger(long): void
* BigInteger.toByteArray(): byte[]
* BigInteger.stripLeadingZeroBytes(byte[], int, int): int[]
* BigInteger.stripLeadingZeroBytes(int, byte[], int, int): int[]
and skips array zero-initialization, NULL, and bounds checks in these methods.
Cherry-picked from https://github.com/eclipse-openj9/openj9/pull/19556

(0.46.0) Skip zero-init, checks for some BigInteger methods

---

runtime/compiler/control/J9Options.cpp

This change makes the option `-XX:+JITServerUseAOTCache` unnecessary at the server; note that clients are still required to set that option to opt-in to the use of the AOT cache. The `-XX:-JITServerUseAOTCache` option may still be used at the server to disable the AOT cache as before.
This change also has the effect of making ROM class sharing at the server the default.

Enabled AOT cache at server by default

---

runtime/compiler/control/J9Options.cpp

This change makes the option -XX:+JITServerUseAOTCache unnecessary at the server; note that clients are still required to set that option to opt-in to the use of the AOT cache. The -XX:-JITServerUseAOTCache option may still be used at the server to disable the AOT cache as before.
This change also has the effect of making ROM class sharing at the server the default.

(0.46) Enabled AOT cache at server by default

---

runtime/compiler/build/files/common.mk
runtime/compiler/compiler.mk

Must include `mkconstants.mk` in order to use those build flags.
Otherwise, the LIT library has unresolved references and fails to load:
```
libj9jit29.so: undefined symbol: _ZN2TR9CRRuntime25purgeMemoizedCompilationsEv
```

UMA: fix references to flags j9vm_opt_criuSupport, j9vm_opt_jitserver

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/x/codegen/AllocPrefetchSnippet.cpp
runtime/compiler/x/env/J9CPU.cpp

* Add support for new recognized processors to CPU inquiry check.  The code affected is a validation method that ensures the port library's determination of the CPU id matches the JIT's determination of the CPU.
* Prefer to disable TLH allocation prefetching by default post-Skylake

Prefer to disable TLH allocation prefetching by default post-Skylake

---

runtime/compiler/build/files/common.mk.ftl
runtime/compiler/compiler.mk

Including `mkconstants.mk` (in #19621) interferes with proper configuration on some platforms: convert `build/files/common.mk` to a freemarker template to apply those build flags.

UMA: fix references to flags opt_criuSupport, opt_jitserver (v2)

---

buildenv/jenkins/variables/defaults.yml

This cherry-picks #19620 for the 0.46.0 release.

(0.46) Update to openssl 3.0.14

---

runtime/jcl/common/jcldefine.c

This patch simply removes an else-after-goto and conforms the enclosing if-statement conditions to the coding standards.

Remove redundant else in defineClassCommon

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/x/codegen/AllocPrefetchSnippet.cpp
runtime/compiler/x/env/J9CPU.cpp

* Add support for new recognized processors to CPU inquiry check.  The code affected is a validation method that ensures the port library's determination of the CPU id matches the JIT's determination of the CPU.
* Prefer to disable TLH allocation prefetching by default post-Skylake

(0.46.0) Prefer to disable TLH allocation prefetching by default post-Skylake

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/gcchk/gcchk.cpp

jitCodeCache reclamation would be triggered by GC cycle end event,
For scavenge backout case, at the end of cycle, heap would be rolled
back to before scavenge cycle start, and another global GC would start
right after the end of backout scavenge, so there is no need to do
jitCodeCache reclamation at the end of backout scavenge.
also from Java21 the partial reclamation(related with virtualThread)
processing has been split to move to clearable phase of GC in order to improve the processing performance
(PR:https://github.com/eclipse-openj9/openj9/pull/17527), but for scavenge backout case, the backout only could happen before the first part of reclamation processing(the processing would never get a chance to run for the case), without the first part  reclamation processing, the second part …

Skip jitCodeCache reclamation for scavenge backout case

---

runtime/include/zconf.h
runtime/zlib/deflate.h
runtime/zlib/inflate.h

Move the definition of `NO_GZIP` to `zconf.h` (see #14810).

Reduce modifications to zlib source code

---

buildenv/jenkins/common/build.groovy
buildenv/jenkins/variables/defaults.yml

Retry the build if "IOException caught during compilation: Resource deadlock avoided" occurs.

Define a fail_pattern for alinux, amac, xmac builds

---

runtime/compiler/ilgen/IlGenerator.cpp
runtime/compiler/ilgen/Walker.cpp

This commit includes the following two changes in ILGen:
1.
If the class is unresolved, `genInstanceof` anchors `instanceof` under a `treetop` node. Then the anchored `instanceof` treetop appears after the callTree and it commons with
the `instanceof` node under the `ZEROCHK` in `geninterface`.
This causes a problem because `expandUnresolvedClassInstanceof` does not expect the treetop that has the anchored `instanceof` to have already been evaluated when it appears under ZEROCHK. The transformation in `expandUnresolvedClassInstanceof` will not function correctly.
Therefore, the anchored `instanceof` treetop needs to be moved up before ZEROCHK.
2.
If the receiver of the `instanceof` is non-null, there is no need to transform the `instanceof` into two cases: the null case and the non-null …

Move anchored instanceof to the correct position

---

runtime/j9vm/javanextvmi.cpp
runtime/jvmti/jvmtiHelpers.cpp
runtime/jvmti/jvmtiThread.cpp
runtime/jvmti/suspendhelper.cpp
runtime/vm/ContinuationHelpers.cpp

- Add new state -2 when vthread suspends under transition
- Refactor state checks to match new design
- Add assertion on expected states for easier triaging
Note:
This design doesn't account for cases where a JVMTI agent tries to accesses a suspended vthread while resuming it simultaneously. This will lead to undefined behaviour of the JVM.
Fixes: #18675

Update sync logic between vthreadInspectorCount & internalSuspendState

---

runtime/j9vm/javanextvmi.cpp
runtime/jvmti/jvmtiHelpers.cpp
runtime/jvmti/jvmtiThread.cpp
runtime/jvmti/suspendhelper.cpp
runtime/vm/ContinuationHelpers.cpp

- Add new state -2 when vthread suspends under transition
- Refactor state checks to match new design
- Add assertion on expected states for easier triaging
Note:
This design doesn't account for cases where a JVMTI agent tries to accesses a suspended vthread while resuming it simultaneously. This will lead to undefined behaviour of the JVM.
Backport of #19564

(0.46) Update sync logic between vthreadInspectorCount & internalSuspendState

---

runtime/compiler/ilgen/IlGenerator.cpp
runtime/compiler/ilgen/Walker.cpp

This PR ports https://github.com/eclipse-openj9/openj9/pull/19604 to 0.46
-------
This commit includes the following two changes in ILGen:
1.
If the class is unresolved, `genInstanceof` anchors `instanceof` under a `treetop` node. Then the anchored `instanceof` treetop appears after the callTree and it commons with
the `instanceof` node under the `ZEROCHK` in `geninterface`.
This causes a problem because `expandUnresolvedClassInstanceof` does not expect the treetop that has the anchored `instanceof` to have already been evaluated when it appears under ZEROCHK. The transformation in `expandUnresolvedClassInstanceof` will not function correctly.
Therefore, the anchored `instanceof` treetop needs to be moved up before ZEROCHK.
2.
If the receiver of the `instanceof` is non-null, there is no …

(0.46) Move anchored instanceof to the correct position

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9Inliner.hpp

If the J9Class for `java/lang/Class` is available to the compiler, the IL it generates inline for `Unsafe.{get|put}{int|long|Object}*` tests whether the Object being accessed is null (for native memory references), has the low-order bit set for the specified offset and whether its J9Class is that of `java/lang/Class`, in that order. Those tests are trying to distinguish whether a static field is being accessed, which requires different code to access the memory than all the other cases.
For both instance fields and static fields, the Object will be a non-null reference.  However, the low-order bit of the offset will never be set for instance fields.  Therefore, what is likely the most common usage would benefit from having the low-order offset bit tested first.
This commit changes the …

Change order of tests for inline Unsafe.{get|put}* calls

---

runtime/gc_base/ClassLoaderManager.cpp
runtime/gc_base/ClassLoaderManager.hpp

Currently there is a N-square search behaviour during Anonymous classes unloading - search for the segment where ROM class for unloaded RAM class is stored. This general segments walk can introduce delays if there is a large number of Anonumous classes loaded. This PR introduces fast path can be attempted to find ROM class. There is a high possibility that the ROM segment we are looking for is the next one for RAM class segment. So, this segment can be checked first. If fast path search was not succesful an existed slow path is going to be used. Also can be a case when ROM class is not stored in Anonymous classloader, for example for Indexable, there is no reason to even search it.

Add optimization to ROM class search for Anonymous classes unloading

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9Inliner.hpp

If the J9Class for `java/lang/Class` is available to the compiler, the IL it generates inline for `Unsafe.{get|put}{int|long|Object}*` tests whether the Object being accessed is null (for native memory references), has the low-order bit set for the specified offset and whether its J9Class is that of `java/lang/Class`, in that order. Those tests are trying to distinguish whether a static field is being accessed, which requires different code to access the memory than all the other cases.
For both instance fields and static fields, the Object will be a non-null reference.  However, the low-order bit of the offset will never be set for instance fields.  Therefore, what is likely the most common usage would benefit from having the low-order offset bit tested first.
This commit changes the …

[0.46.0] Change order of tests for inline Unsafe.{get|put}* calls

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/runtime/DataCache.cpp
runtime/compiler/runtime/HWProfiler.cpp
runtime/compiler/runtime/J9CodeCache.cpp

Found using the command `grep -A 2 -rI -e 'TR_VerboseLog::writeLine' | grep -e '\\n"'` in `openj9/`.

Remove redundant vlog newlines

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/gcchk/gcchk.cpp

jitCodeCache reclamation would be triggered by GC cycle end event,
For scavenge backout case, at the end of cycle, heap would be rolled
back to before scavenge cycle start, and another global GC would start
right after the end of backout scavenge, so there is no need to do
jitCodeCache reclamation at the end of backout scavenge.
also from Java21 the partial reclamation(related with virtualThread)
processing has been split to move to clearable phase of GC in order to improve the processing performance
(PR:https://github.com/eclipse-openj9/openj9/pull/17527), but for scavenge backout case, the backout only could happen before the first part of reclamation processing(the processing would never get a chance to run for the case), without the first part  reclamation processing, the second part …

(0.46) Skip jitCodeCache reclamation for scavenge backout case

---

runtime/gc_glue_java/MarkingSchemeRootClearer.cpp
runtime/gc_glue_java/ScavengerBackOutScanner.cpp
runtime/gc_glue_java/ScavengerRootScanner.cpp

the Objects, which have been copied to survivor or tenure during concurrent scavenge, would not roll back for back out case, so in the following global marking, we need to update the forwardObject in the continuation list.
Cherry pick https://github.com/eclipse-openj9/openj9/pull/19562

(0.46) Fixup continuation lists for concurrent scavenge backout case

---

runtime/compiler/optimizer/VectorAPIExpansion.cpp

Previous changes by to support offheap resulted in wrong generated trees, this fixes it.
Original changes:
https://github.com/eclipse-openj9/openj9/commit/566a656bece4538bcbc13a8d09c55e4cdbd8f37a
Tests: https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/22647/
Original trees:
```
aladd
arrayRef
ladd
headerSize
index (or shift)
```
After changes:
```
aladd
arrayRef
ladd
headerSize
ladd
index (or shift)
null
```
After this fix (non offheap case):
```
aladd
arrayRef
ladd
headerSize
index (or shift)
```
Issue was instead of passing the index/shift node to the helper we passed the `ladd` with one child being the index/shift.
Closes: https://github.com/eclipse-openj9/openj9/issues/19661

Fix vectorAPI address node helper after offheap changes

---

runtime/rasdump/javadump.cpp

To assist with gathering context information for problem determination on z/TPF several fields dealing with system memory configuration and other settings are added to the Javacore for z/TPF only.  The added sub-section is especially useful for determining if system limits were reached, and it can also be used for sizing system resources to run Java applications on z/TPF.

Add z/TPF specific configuration diagnostic information to Javacore

---

runtime/nls/j9vm/j9vm.nls
runtime/oti/j9nonbuilder.h
runtime/oti/jvminit.h
runtime/vm/vmprops.c

`JEP471` sets system property according to the command line option value
`--sun-misc-unsafe-memory-access=value` which is expected to be "allow", "warn", "debug" or "deny";
Set a system property `sun.misc.unsafe.memory.access` with the value specified via `--sun-misc-unsafe-memory-access=value`.
Verified locally that `sun/misc/UnsafeMemoryAccessWarnings.java` passes.
issue https://github.com/eclipse-openj9/openj9/issues/19583

JEP471 sets system property according to the command line option value

---

runtime/compiler/optimizer/MethodHandleTransformer.cpp

It's possible for the `MethodHandle` to be null, in which case the attempt to load its `type` field would result in an unexpected segfault.
Fixes #19546

Generate a NULLCHK when transforming checkExactType() into ZEROCHK

---

runtime/gc_modron_startup/mgcalloc.cpp

Currently it is wrong order of parameters in assertion message, requested and really allocated bytes should be swapped. Also change name of local variable accordingly.

Fix order of parameters in assertion message

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

In generating inline IL for `Unsafe.get*` and `Unsafe.put*` methods in the case where no conversion is needed, the blocks that test whether the object reference is null or whether the object's type is `java/lang/Class` had their frequencies set to `VERSIONED_COLD_BLOCK_COUNT`, copied from the indirect access block.  However, unlike the indirect access block, those two blocks were not marked explicitly as cold.  This change corrects that.

Mark unlikely blocks as cold for Unsafe.{get|put}*

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

In generating inline IL for `Unsafe.get*` and `Unsafe.put*` methods in the case where no conversion is needed, the blocks that test whether the object reference is null or whether the object's type is `java/lang/Class` had their frequencies set to `VERSIONED_COLD_BLOCK_COUNT`, copied from the indirect access block.  However, unlike the indirect access block, those two blocks were not marked explicitly as cold.  This change corrects that.
This is a port of pull request #19676 to the v0.46.0-release branch.

[0.46.0] Mark unlikely blocks as cold for Unsafe.{get|put}*

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/UnsafeFastPath.cpp

This PR reverts #19535, effectively reapplying #19234.
But before that, it fixes two problems in the determination of the address to use when unsafe fast path transforms an access to a static field via `VarHandle` with OpenJDK `VarHandle`s. Applying these fixes first allows them to be kept separate from the revert commit without reintroducing the bugs between commits.
First, for `getAnd{Set,Add}{Int,Long}` intrinsics accessing static fields, the address should be
object.vmRef.ramStatics + (offset & ~J9_SUN_FIELD_OFFSET_MASK)
but with OpenJDK `VarHandle`s it would instead be `(object + offset)`, as though for an instance field. So the access would produce an incorrect result and almost certainly corrupt the `java/lang/Class` instance or something near it in the heap.
Unsafe fast path …

Reapply "Optimize OpenJDK VarHandle operation methods"

---

runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp

VM_getClassFromSignature messages account for 10-11% of all messages exchanged between client and server. Such messages are sent when the server calls getClassFromSignature() to obtain a j9class pointer starting from a class name. This commit is based on the observation that primitive types, like I, Z, B, etc., do not have an associate j9class, so the answer from the getClassFromSignature() query is always NULL. This change reduces the number of VM_getClassFromSignature messages by 33-35%

Reduce number of VM_getClassFromSignature messages for JITServer

---

debugtools/DDR_VM/src/com/ibm/j9ddr/VMDataFactory.java
debugtools/DDR_VM/src/com/ibm/j9ddr/view/dtfj/image/J9DDRImageProcess.java
debugtools/DDR_VM/src/com/ibm/j9ddr/view/dtfj/image/J9RASImageDataFactory.java

On z/OS, a system dump may contain information about multiple processes in multiple address spaces: Not all of them need have Java runtimes. Those without a Java runtime were not being handled properly
`VMDataFactory.getVMData()` may return `null` (see [here](https://github.com/eclipse-openj9/openj9/blob/v0.45.0-release/debugtools/DDR_VM/src/com/ibm/j9ddr/VMDataFactory.java#L112)) which needs to be handled properly. Some places, (e.g. [`J9DDRImageProcess.getRuntimes()`](https://github.com/eclipse-openj9/openj9/blob/v0.45.0-release/debugtools/DDR_VM/src/com/ibm/j9ddr/view/dtfj/image/J9DDRImageProcess.java#L368)) would throw `NullPointerException` which then causes `J9DDRCorruptData` to be included in the resulting iterator.
Also:
* remove redundant checking for cached results
* remove …

DDR: Improve handling of processes with no JRE

---

buildenv/jenkins/variables/defaults.yml

Until https://github.com/eclipse-openj9/openj9/issues/19694 is resolved.
Related to https://github.com/eclipse-openj9/openj9/pull/19663

Continue using jdk21 as the boot jdk for jdk23+

---

runtime/bcutil/ClassFileOracle.cpp
test/functional/Valhalla/build.xml
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeGenerator.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaUtils.java
test/functional/Valhalla/src_lw5/org/openj9/test/lworld/ValueTypeGenerator.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/NullRestrictedTypeOptTests.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeArrayTests.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeGenerator.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeSystemArraycopyTests.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTestClasses.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeUnsafeTests.java

- update Valhalla tests to use NullRestricted annotations instead of primitive
- don't allow @NullRestricted annotation for arrays or primitive types
this won't compile without https://github.com/eclipse-openj9/openj9/pull/19631#pullrequestreview-2099915816
Fixes: https://github.com/eclipse-openj9/openj9/issues/19459

Fix Valhalla test compilation

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/il/J9MethodSymbol.cpp

These methods are currently safe to skip.

Skip bounds checks in BigInteger bit{Count,Length}

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
runtime/oti/j9nonbuilder.h
runtime/vm/BytecodeInterpreter.hpp

The changes aim to avoid the conflicts of the native address
imposed by users by check the existence of the heap base to
determine whether a heap array rather than a native array
is passed down to native.
Fixes: #19005

[FFI/JDK22+] Remove the heap argument identifier in downcall

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/il/J9MethodSymbol.cpp

These methods are currently safe to skip.
Picked from https://github.com/eclipse-openj9/openj9/pull/19688

(0.46) Skip bounds checks in BigInteger bit{Count,Length}

---

jcl/jpp_configuration.xml
test/TestConfig/resources/excludes/latest_exclude_24.txt
test/functional/cmdLineTests/jvmtitests/jvmtitests_excludes_24.xml

`JDK24` bring up
Added `JPP flag JAVA24`;
Added `jvmtitests_excludes_24.xml`;
Added `latest_exclude_24.txt`.
Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/806

JDK24 bring up

---

test/README.md
test/functional/Valhalla/playlist.xml
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeTests.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeGenerator.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java

After this change set the Valhalla more tests should be passing. Tests that are not passing are disabled for now.
This change should be merged after https://github.com/eclipse-openj9/openj9/pull/19646
Changes include:
- removing unused code from ValueTypeTests including the myUnsafe field
- Replace q signatures with L. Mark all generated value fields as NullRestricted. Previously all value classes were marked as primitive, this most closely matches the behavior.
- Remove and modify a few tests in ValueTypeTests, disable remaining
The following issues and comments have been created to track the excluded tests:
- https://github.com/eclipse-openj9/openj9/issues/19692
- https://github.com/eclipse-openj9/openj9/issues/19460#issuecomment-2163847738
- …

Valhalla test updates and disable failing tests

---

test/functional/Java21Only/src/org/openj9/test/jep442/downcall/PrimitiveTypeTests1.java
test/functional/Java21Only/src/org/openj9/test/jep442/downcall/PrimitiveTypeTests2.java
test/functional/Java22andUp/src/org/openj9/test/jep454/downcall/PrimitiveTypeTests1.java
test/functional/Java22andUp/src/org/openj9/test/jep454/downcall/PrimitiveTypeTests2.java

The changes ensure the native strings are correctly converted by
leveraging the existing FFI methods with the encoding mode specified
prior to downcall on z/OS.
Related: [Internal 445](https://github.ibm.com/runtimes/javanext/issues/445)

[FFI/Test_JDK21+] Convert the native string for downcall on z/OS

---

test/functional/IllegalAccessError_for_protected_method/playlist.xml

- Split IllegalAccessProtectedMethodTest due to extendedHCR setting
Fixes: https://github.com/adoptium/aqa-tests/issues/5393

Split IllegalAccessProtectedMethodTest to openj9 and hotspot variant

---

test/functional/IllegalAccessError_for_protected_method/playlist.xml

- Cherry-pick for Split IllegalAccessProtectedMethodTest due to extendedHCR setting
- Related PR: https://github.com/eclipse-openj9/openj9/pull/19717

(0.46) Split IllegalAccessProtectedMethodTest to openj9 and hotspot variant

---

runtime/port/zos390/j9mprotect.s
runtime/port/zos390/j9munprotect.s

The two files `runtime/port/zos390/j9mprotect.s` and `runtime/port/zos390/j9munprotect.s` seems to have 2 newlines at the end of the file. This removes the extraneous one so that it only has the single newline, that should be in accordance with the typical guidelines.

Remove extra newline chars from j9mprotect/j9munprotect.s

---

runtime/rasdump/dmpsup.c

Make Windows consistent with other platforms; there's no need to use a different name (the macro defined in `omrsig.h` will be removed).

Use sighandler_t instead of sig_handler_t

---

runtime/bcutil/ROMClassBuilder.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/control/JITServerHelpers.hpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/env/PersistentCollections.hpp
runtime/compiler/env/SharedCache.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/runtime/IProfiler.cpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp
runtime/compiler/runtime/JITServerAOTCache.cpp
runtime/compiler/runtime/JITServerAOTCache.hpp
runtime/compiler/runtime/JITServerAOTDeserializer.cpp
runtime/compiler/runtime/JITServerAOTDeserializer.hpp
runtime/compiler/runtime/JITServerAOTSerializationRecords.hpp
runtime/compiler/runtime/JITServerROMClassHash.cpp
runtime/compiler/runtime/JITServerROMClassHash.hpp
runtime/compiler/runtime/RelocationRecord.cpp
runtime/compiler/runtime/SymbolValidationManager.cpp
runtime/oti/util_api.h
runtime/util/shchelp_j9.c

This PR implements support for correctly and reliably serializing and deserializing/loading JITServer AOT cache methods that are defined by or refer to classes generated at runtime.
The current list of recognized types of generated classes includes:
- Lambda classes;
- Dynamic proxy classes;
- Generated reflection accessors.
In each of these cases, the generated class name consists of a deterministic prefix followed by a suffix that can vary across JVMs.
Generated classes are identified across client JVMs using the combination of: the class loader ID (name of its first loaded class), the deterministic class name prefix, and the deterministic ROMClass hash. The latter is computed after re-packing the ROMClass to truncate all the instances of the class name string down to the deterministic …

Support lambdas and other generated classes in JITServer AOT cache

---

runtime/bcutil/ClassFileOracle.cpp
runtime/bcutil/ClassFileOracle.hpp
runtime/bcutil/ROMClassCreationContext.cpp
runtime/bcutil/romphase.h
runtime/vm/createramclass.cpp
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java

- add back missing error handling for value type inheritance
- remove stale heavy/light abstract class logic
- re-enable tests and remove heavy/light naming
Related to https://github.com/eclipse-openj9/openj9/issues/19692

Fix and enable heavy/light value type tests

---

runtime/compiler/z/codegen/J9TreeEvaluator.cpp

We inline the multi array allocation when the size of first or second dimension is zero but the instruction don't set the zero size filed of the new object. This is not a problem when we allocate from zeroed memory but if the memory is not zeroed, it causes problems.
In this PR I add instructions to explicitly set size filed to zero.

Z: Zero multi array size when batch clear is disabled.

---

jcl/src/java.base/share/classes/java/lang/ref/ReferenceQueue.java

`CRIU` adds `NotCheckpointSafe` at `java/lang/ref/ReferenceQueue.poll`
Address `JVMCheckpointException: Blocking operation is not allowed in CRIU single thread mode`.
closes https://github.com/eclipse-openj9/openj9/issues/19653

CRIU adds NotCheckpointSafe at java/lang/ref/ReferenceQueue.poll

---

doc/build-instructions/Build_Instructions_V11.md
doc/build-instructions/Build_Instructions_V17.md
doc/build-instructions/Build_Instructions_V21.md
doc/build-instructions/Build_Instructions_V8.md

Previous named anchor referenced an invalid header string to link to the Docker instructions.

Fix broken named anchor for Docker in build instructions

---

buildenv/jenkins/common/build.groovy

adds .ssh folder additionally and prevents public key error while cloning git repositories. In this way we can have needed key added to host machine and then run docker and having needed keys ready when it is not presented in the image related: infra 9291

Mounts .ssh folder in docker and avoids git key error

---

runtime/oti/zhelpers.m4
runtime/port/zos390/j9gs_load_gscb.s
runtime/port/zos390/j9gs_store_gscb.s

Some errors were being seen while compiling some `.s` files for Open XL with z/OS. With some further investigation it was seen that some of these errors were also present with XLC, however the return code 4 was being ignored and continued building anyways. Open XL sees this return code and hard stops the compilation and reports it as an error, these changes address these problems.
---
Error information for more context: 
```bash
74          DROP  R2
ASMA045W Register or label not previously used - R2
ASMA435I Record 53 in openj9/runtime/port/zos390/j9gs_load_gscb.s
on volume:
75          DROP  R1
ASMA045W Register or label not previously used - R1
ASMA435I Record 54 inopenj9/runtime/port/zos390/j9gs_load_gscb.s
on volume:
76          DROP  R0
ASMA045W Register or label not previously used …
```

Assembly fixes for Open XL compliance

---

runtime/compiler/optimizer/IdiomRecognitionUtils.cpp

The tree and block verification errors were because the array object node was being reused for array access during idiom transformations. Using array object node duplicate fixes the errors.

Fix for tree verification error and block verification error

---

runtime/compiler/control/J9Options.cpp

Performance analysis and measurement on multiple workloads suggests that enabling TLH prefetching by default on Skylake is suboptimal.  Only enable by default up until the Broadwell microarchitecture.

Disable x86 TLH prefetch by default after Broadwell

---

runtime/compiler/control/J9Options.cpp

Performance analysis and measurement on multiple workloads suggests that enabling TLH prefetching by default on Skylake is suboptimal.  Only enable by default up until the Broadwell microarchitecture.

(0.46.0) Disable x86 TLH prefetch by default after Broadwell

---

jcl/src/java.base/share/classes/java/lang/ref/ReferenceQueue.java

`CRIU` adds `NotCheckpointSafe` at `java/lang/ref/ReferenceQueue.poll`
Address `JVMCheckpointException: Blocking operation is not allowed in CRIU single thread mode`.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/19739

(v0.46.0-release) CRIU adds NotCheckpointSafe at java/lang/ref/ReferenceQueue.poll

---

runtime/jvmti/jvmtiClass.c
runtime/util/hshelp.c
test/functional/IllegalAccessError_for_protected_method/playlist.xml
test/functional/JavaAgentTest/playlist.xml
test/functional/cmdLineTests/jvmtitests/decompilationtests.xml
test/functional/cmdLineTests/jvmtitests/fieldwatchtests.xml
test/functional/cmdLineTests/jvmtitests/jvmtitests.xml
test/functional/cmdLineTests/jvmtitests/jvmtitests_Java11andUp.xml
test/functional/cmdLineTests/jvmtitests/jvmtitests_Java21andUp.xml
test/functional/cmdLineTests/jvmtitests/jvmtitests_hcr.xml
test/functional/cmdLineTests/jvmtitests/playlist.xml

The current implementation emits a warning message when a JVMTI operation suceeds.
Also, clear breakpoints unconditionally when a class is redefined.

Clear breakpts in class redef and fix HCR warning

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/env/J9KnownObjectTable.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/InterpreterEmulator.cpp
runtime/compiler/optimizer/J9Inliner.cpp
runtime/compiler/runtime/JITServerIProfiler.cpp
runtime/compiler/runtime/RelocationRuntime.cpp
runtime/compiler/runtime/SymbolValidationManager.cpp
runtime/compiler/runtime/SymbolValidationManager.hpp

Avoid using the thread-local variable `TR::compInfoPT` (mostly through `TR::CompilationInfo::getStream()`) in contexts where the `compInfoPT` or the `Compilation` is readily available. TLS accesses in dynamically loaded shared libraries (such as the JIT) can have non-negligible overhead.

Reduce unnecessary TLS usage in JITServer code

---

runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/env/J9ObjectModel.cpp
runtime/compiler/env/J9ObjectModel.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9method.h
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/env/j9methodServer.hpp
runtime/compiler/ilgen/Walker.cpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/ValueTypeHelpers.cpp
runtime/vm/ValueTypeHelpers.hpp
runtime/vm/intfunc.c
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeGenerator.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java

- isNameOrSignatureQType
- isClassRefQtype
- isFieldQType
- isQDescriptorForValueTypesSupported

Remove internal qtype methods

---

runtime/jvmti/jvmtiClass.c
runtime/util/hshelp.c
test/functional/IllegalAccessError_for_protected_method/playlist.xml
test/functional/JavaAgentTest/playlist.xml
test/functional/cmdLineTests/jvmtitests/decompilationtests.xml
test/functional/cmdLineTests/jvmtitests/fieldwatchtests.xml
test/functional/cmdLineTests/jvmtitests/jvmtitests.xml
test/functional/cmdLineTests/jvmtitests/jvmtitests_Java11andUp.xml
test/functional/cmdLineTests/jvmtitests/jvmtitests_Java21andUp.xml
test/functional/cmdLineTests/jvmtitests/jvmtitests_hcr.xml
test/functional/cmdLineTests/jvmtitests/playlist.xml

The current implementwation emits a warning message when a JVMTI operation suceeds.
Also, clear breakpoints unconditionally when a class is redefined as required by the spec.
Fixes: https://github.com/eclipse-openj9/openj9/issues/19691
Backport of https://github.com/eclipse-openj9/openj9/pull/19710

(0.46) Clear breakpts in class redef and fix HCR warning

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/env/J9ClassEnv.hpp
runtime/compiler/env/JITServerPersistentCHTable.cpp
runtime/compiler/env/JITServerPersistentCHTable.hpp
runtime/compiler/ilgen/Walker.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.cpp
runtime/compiler/net/MessageTypes.hpp
runtime/compiler/optimizer/J9TransformUtil.cpp
runtime/compiler/runtime/RuntimeAssumptions.hpp
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/intfunc.c
runtime/vm/resolvefield.cpp

- Add `dontFoldStaticFinalFields={}` JIT option
- Add missing newline to an IL generator log message
- Expand Java 17+ aggressive SFFF from `VarHandle` to all types
- Fold primitive-typed static final fields more aggressively
This depends on eclipse/omr#7376

Make static final field folding more aggressive

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/optimizer/J9TransformUtil.cpp
runtime/compiler/optimizer/J9TransformUtil.hpp
runtime/compiler/optimizer/J9ValuePropagation.cpp
runtime/compiler/optimizer/J9ValuePropagation.hpp

TODO
Depends on https://github.com/eclipse/omr/pull/7391
Example transformation trees
Before:
```
n816n     BBStart <block_50> (freq 18252)                                                     [    0x736558e0eec0] bci=[8,31,1293] rc=0 vc=214 vn=- li=- udi=- nc=0
n366n     treetop                                                                             [    0x736558e06220] bci=[8,28,1291] rc=0 vc=243 vn=- li=- udi=- nc=1
n365n       call  jdk/internal/misc/Unsafe.copyMemory0(Ljava/lang/Object;JLjava/lang/Object;JJ)V[#480  final native special Method] [flags 0x20500 0x0 ] ()  [    0x736558e061d0] bci=[8,28,1291] rc=1 vc=243 vn=- li=- udi=- n>
n359n         aload  <temp slot 10>[#532  Auto] [flags 0x20000007 0x0 ] (X!=0 )               [    0x736558e05ff0] bci=[8,19,1291] rc=1 vc=243 vn=- …
```

Update Unsafe.copyMemory transformation to support offheap

---

jcl/src/java.base/share/classes/java/lang/System.java
runtime/jcl/common/system.c

As part of better handling of JEP400 constraints on z/OS, the com.ibm.autocvt property is added to control whether we convert input file I/O based on file tagging. If not explicitly specified, the property defaults to true, unless file.encoding is set to COMPAT.

Add new com.ibm.autocvt property for z/OS file tagging support

---

buildenv/jenkins/variables/defaults.yml

Cherry pick https://github.com/eclipse-openj9/openj9/pull/19776

(0.46) Update OpenSSL 3.0.14 to include the fix for CVE-2024-5535

---

runtime/compiler/control/CompilationThread.cpp

Changed TR_VerboseLog::writeLineLocked() into
TR_VerboseLog::writeLine() because we are already in a TR_VerboseLog::CriticalSection

Eliminate redundant vlog lock

---

test/functional/cmdLineTests/jvmtitests/jvmtitests_hcr.xml

Resolves https://github.com/eclipse-openj9/openj9/issues/19778
Port of https://github.com/eclipse-openj9/openj9/pull/19792

(0.46) Add required options to failing HCR tests

---

jcl/src/java.base/share/classes/com/ibm/jit/JITHelpers.java

The method JITHelpers.canEncodeAsLatin1() is used only by the String implementation before Java 17.

Remove JITHelpers.canEncodeAsLatin1() from Java 17+

---

test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaUtils.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/DDRValueTypeTest.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeGenerator.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java

- Remove ACONST_INIT and WITHFIELD bytecode uses from tests
- Consolidate value and reference class generator creation methods now that both use <init> and putfield
- Remove wither tests. There is no equivalent behavior in the new spec.
- Remove testWithFieldOnNonValueType, testWithFieldOnNull, testWithFieldOnNonExistentClass, testUnresolvedWithFieldUse
Related to https://github.com/eclipse-openj9/openj9/issues/18316

Remove withfield/aconst_init from ValueTypeTests

---

runtime/compiler/net/Message.cpp

The extra comment line in this file generates a clang warning, because two start-of-block-comment `/*` tokens are ended by a single end-of-block-comment `*/` token at the end of the copyright header.

Remove redundant comment line in header

---

runtime/compiler/env/j9methodServer.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp

- This store of `NULL` in `address` in `TR_ResolvedRelocatableJ9JITServerMethod::staticAttributes` is unnecessary, as the same store occurs later on in that function if `fieldInfoCanBeUsed` is false and `address` is not `NULL`. It has been removed, which also eliminates a clang error - it is wary of converting a `(U_32)0` value to a `void *` value.
- The `weight` check in `TR_MultipleCallTargetInliner::scaleSizeBasedOnBlockFrequency` is supposed to guard against the UB of casting a floating-point value outside the int32_t range to an int32_t. The value `0x7fffffff` (decimal 2147483647) is not exactly representable as a 32-bit float; both gcc and clang convert it to the float value 2147483648.0 (one more than the literal). The added explicit `(float)` cast eliminates a clang warning about …

Fix various cast errors

---

runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/env/j9methodServer.hpp
runtime/compiler/runtime/RelocationRuntime.hpp

Various virtual methods in derived classes override their base counterparts but are missing an override specifier. Clang warns about this, and so fails to compile with -Werror.

Add override specifier to virtual declarations

---

runtime/compiler/runtime/MetricsServer.cpp

A static_assert declaration without a string literal message is only available in C++17. This causes a compilation error in clang, as the compiler is built with the C++11 standard.

Modify static assert to be C++11 conformant

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/ilgen/Walker.cpp

StringBuilder.toString calls String(StringBuilder) which calls String(AbstractStringBuilder, void)
which calls Array.copyOfRange which calls
Array.copyOfRangeByte.
In this chain we can skip Zero alloc.

Skip zero init when copied array is the result of StringBuilder.toString

---

runtime/libffi/closures.c
runtime/shared_common/CacheMap.cpp
runtime/shared_common/ScopeManagerImpl.cpp
runtime/shared_common/j9shr.tdf
runtime/tests/shared/ByteDataTest.cpp

As part of the ongoing effort to enable warnings as errors, fix warnings in runtime/shared_common, runtime/libffi, and runtime/tests/shared, which appear on plinux builds on GCC 13

Fix warnings in shared_common, libffi, tests/shared

---

runtime/gc_base/GCExtensions.hpp
runtime/gc_glue_java/EnvironmentDelegate.hpp
runtime/gc_glue_java/MarkingDelegate.cpp
runtime/gc_glue_java/ScavengerDelegate.cpp
runtime/gc_modron_standard/ContinuationObjectBufferStandard.cpp
runtime/gc_stats/ContinuationStats.hpp
runtime/gc_stats/VLHGCIncrementStats.hpp
runtime/gc_verbose_handler_standard_java/VerboseHandlerOutputStandardJava.cpp
runtime/gc_verbose_handler_standard_java/VerboseHandlerOutputStandardJava.hpp
runtime/gc_verbose_handler_vlhgc/VerboseHandlerOutputVLHGC.cpp
runtime/gc_verbose_handler_vlhgc/VerboseHandlerOutputVLHGC.hpp
runtime/gc_vlhgc/ContinuationObjectBufferVLHGC.cpp
runtime/gc_vlhgc/CopyForwardScheme.cpp
runtime/gc_vlhgc/CopyForwardSchemeTask.hpp
runtime/gc_vlhgc/EnvironmentVLHGC.hpp
runtime/gc_vlhgc/GlobalMarkingScheme.cpp

Report total alive and started continuation Objects in mem-info of verbosegc log.
- piggyback iterateAllContinuationObjects(), which is designed to help improving the performance of jit code cache reclamation, to collect total and started numbers of continuation at the end of GC.
- report tag continuationObjects in <mem-info> of verbase gc if total alive continuation Objects isn't 0.
limitation of this changes:
in case iterateAllContinuationObjects() helper is not run, no counts would be collected and reported, such as
case1: scavenger backout case
case2: disable jitcodecacheReclaim feature
case3: there is no need jitcodecachereclamation for the cycle case4: runtime GC (there is no iterateAllContinuationObjects() helper in runtime GC).
depends on: https://github.com/eclipse/omr/pull/7386 …

Report live continuation Objects in verbosegc

---

test/functional/JavaAgentTest/playlist.xml

Issue https://github.com/eclipse-openj9/openj9/issues/19777
Tested on zlinux and Windows via https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3739/, which passed.
This may be reverted once the JIT fix https://github.com/eclipse-openj9/openj9/issues/19777#issuecomment-2209507409 is ready.

-XX:+EnableExtendedHCR TestRefreshGCSpecialClassesCache JIT_ON modes

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/PersistentAllocator.cpp
runtime/compiler/env/PersistentAllocator.hpp
runtime/compiler/net/MessageBuffer.cpp
runtime/compiler/net/MessageBuffer.hpp

A global, reference-counted allocator is now created at JITServer clients that is used to allocate the memory used by the internal MessageBuffer storage buffer during client/server communication. This allocator's memory segments are disclaimed if the number of connections to the server drops to zero, and the compiler will also periodically attempt to destroy the allocator entirely.

Use custom allocator for JITServer client MessageBuffers

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/env/J9KnownObjectTable.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/InterpreterEmulator.cpp
runtime/compiler/optimizer/J9Inliner.cpp
runtime/compiler/runtime/JITServerIProfiler.cpp
runtime/compiler/runtime/RelocationRuntime.cpp
runtime/compiler/runtime/SymbolValidationManager.cpp
runtime/compiler/runtime/SymbolValidationManager.hpp

Reverts eclipse-openj9/openj9#14931 due to the large number of test failures.

Revert "Reduce unnecessary TLS usage in JITServer code"

---

runtime/jcl/common/shared.c
runtime/jcl/j9jcl.tdf

Previously getCpeTypeForProtocol was being called regardless of whether the URL was cached causing extra calls to j9file_attr.
Related to https://github.com/eclipse-openj9/openj9/pull/19380

Call getCpeTypeForProtocol only if URL is not cached

---

runtime/compiler/runtime/J9CodeCache.cpp
runtime/compiler/runtime/J9CodeCache.hpp

Existing code disclaims the cold code between
`coldCodeAlloc` and `coldCodeAllocBase`.
However, if the amount of cold code is larger than the amount of warm code, we will ask to disclaim some parts of the segment which was allocated with THP. This will disable the THP setting and lower throughput.
This commit also introduces two new code cache fields that are used to memorize the start and end of the section forced to use small pages and that should be subject to disclaiming.
Signe-off-by: Marius <mpirvu@ca.ibm.com>

Fixes to code cache disclaiming

---

runtime/ddr/CMakeLists.txt

The gcc flag `-femit-class-debug-always` flag is necessary for the `j9ddr_misc` target to compile successfully. There is no exact match for this flag in clang, but the `-fno-eliminate-unused-debug-types` provides the correct subset of functionality when compiling with clang.

Add debug type flag if compiling with clang

---

runtime/compiler/env/CpuUtilization.cpp
runtime/compiler/env/CpuUtilization.hpp

The JIT computes and displays in the verbose log the CPU consumed by the JVM process. It has been observed that when two readouts happen too close from one another, the values returned by the OS lose precision and the JVM may appear to use less CPU than in reality.
This commit prevents updating the JVM CPU values more frequently than every 100 ms.

Do not update JVM CPU utilization too often

---

runtime/j9vm/java11vmi.c
runtime/j9vm/javanextvmi.cpp
runtime/redirector/forwarders.m4

An implementation of `JVM_IsContainerized` has been added.
The signature of `JVM_IsUseContainerSupport` has been corrected.
Closes: #19801

Implement JVM_IsContainerized and fix JVM_IsUseContainerSupport

---

runtime/compiler/optimizer/IdiomTransformations.cpp
runtime/compiler/optimizer/J9ValuePropagation.cpp

Change all uses of arraycmp to take a 64 bit length child instead of 32 bits.
Relies on https://github.com/eclipse/omr/pull/7313

Extend arraycmp length child

---

doc/GuideForCommitters.md

The description of coordinated merges in the Guide for Committers indicates that the tips of the master and openj9 branches in the openj9-omr repository should be compared to avoid promoting changes that have not passed an OMR Acceptance build.  However, even if the tips of those branches are the same, it might be that the tip of the master branch in the omr repository does not match the tip of the master branch in the openj9-omr repository.  Performing a coordinated merge in that circumstance would also promote changes that have not passed an OMR acceptance build.
Added that case to the list of branches to compare.
[skip ci]

Clarify which branches should be compared

---

runtime/oti/vm_api.h
runtime/vm/BufferWriter.hpp
runtime/vm/CMakeLists.txt
runtime/vm/JFRChunkWriter.cpp
runtime/vm/JFRChunkWriter.hpp
runtime/vm/JFRConstantPoolTypes.cpp
runtime/vm/JFRConstantPoolTypes.hpp
runtime/vm/JFRUtils.hpp
runtime/vm/JFRWriter.hpp
runtime/vm/exceptiondescribe.c
runtime/vm/jfr.cpp
runtime/vm/vm_internal.h

- modify iterateStackTraceImpl to take array instead of exception object as a walkback
- add buffer writer API
- add JFRChunkWriter API
- add JFR ConstantPool types for type dictionary
- add execution sample JAva native for testing purposes

JFR Writer part 2

---

runtime/compiler/runtime/Runtime.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.hpp
runtime/compiler/z/codegen/J9UnresolvedDataSnippet.cpp
runtime/compiler/z/codegen/J9UnresolvedDataSnippet.hpp
runtime/compiler/z/runtime/PicBuilder.m4

This commits ports changes to add Fences after volatile field stores which was committed to snapshot repository with additional changes to fix the compilation failures reported by assembler on z/OS. 

Add Fences after Volatile Field Stores

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp

This patch:
- fixes the default constructor for LocalJ9UTF8Buffer by initializing its members
- uses direct construction for LocalJ9UTF8Buffer instantiation
- avoids full buffer initialization for static name and signature buffers
- uses J9ArrayClass::arity rather than loops to determine array dimensions

Fix LocalJ9UTF8Buffer initialization

---

runtime/bcutil/ComparingCursor.cpp
runtime/vm/exceptiondescribe.c

1. The romclass comparsion should include the ROM_CLASS_MODIFIERS.
2. For a ROMClass from SCC, its rom memory segment always belongs to the bootstrap class loader. But the class might not be actually loaded by the bootstrap loader. Search all live class loaders to find its defining class loader and the corresponding J9Class.
Fixes #19781

Fix romclass comparison and J9Class lookup given a romclass

---

runtime/oti/vmconstantpool.xml
runtime/vm/BytecodeInterpreter.hpp

OJDK MH INLs: `linkToStaticSpecial`, `linkToVirtual` and `linkToInterface`
pop the top element from the stack before executing the target method.
The top element is an instance of `MemberName`. These native INLs don't
show up on the stack, and when we pop a frame, we drop to the frame
which exists before these INLs. A crash happens if the element popped
by the OJDK MH INLs is not restored after a frame is popped. To
prevent the crash, the removed element is restored after a frame is
popped.
RTC Issue 151332

Restore MemberName on stack for linkTo* methods after PopFrame

---

buildenv/jenkins/jobs/infrastructure/promote_repo.groovy

Promote job often fails on this clone.
If it still fails, we should swith to ssh urls.
Issue infra 9264

Change to sh clone with reference repo

---

runtime/compiler/build/files/common.mk.ftl

https://github.com/eclipse/omr/pull/7349 added a new file called OMRRSSRegion.cpp. Although this file was added to the CMakeLists.txt for OMR, there does not exist a common UMA config to add this file. As such, the OpenJ9 build when using UMA is broken.
This commit fixes this by adding this file to the UMA config.

Fix Internal Build Breaks caused by OMR 7349

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp

Introduced in #19773:
```
c:\space\jdk21\openj9\runtime\jcl\common\java_lang_invoke_MethodHandleNatives.cpp(521): error C2220: the following warning is treated as an error
c:\space\jdk21\openj9\runtime\jcl\common\java_lang_invoke_MethodHandleNatives.cpp(521): warning C4244: '+=': conversion from 'UDATA' to 'U_32', possible loss of data
```

Fix build errors on Windows

---

runtime/j9vm/javanextvmi.cpp
test/functional/Valhalla/playlist.xml
test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaAttributeTests.java

Related to: https://github.com/eclipse-openj9/openj9/issues/19460

Implement JVM_IsImplicitlyConstructibleClass

---

runtime/libffi/preconf/mz64/ffi.h
runtime/libffi/z/ffi64.c
runtime/libffi/z/sysvz64.s
runtime/vm/LayoutFFITypeHelpers.cpp
runtime/vm/LayoutFFITypeHelpers.hpp
runtime/vm/OutOfLineINL_openj9_internal_foreign_abi_InternalDowncallHandler.cpp

XPLINK on z/OS requires a special treatment for structs which with two
members whose base type are same, either float or double. Such
parameters are passed to the function as complex type and available FPRs
will be used.
Changes in this PR adds support for two new types in libffi -
FFI_TYPE_STRUCT_FF and FFI_TYPE_STRUCT_DD and also uses it in J9 similar
to how FFI_TYPE_STRUCT is used as for J9 it shouldn't be different. It
is just that libffi needs to know if the argument type or return type
are considered complex on XPLINK to make sure that appropriate FPRs if
available are used to pass parameters or read return values from.
J9 does not need to do the analysis for complex types, that work is done
when platform dependant prep_cif is called when initializing the cif
object.
Signed-off-by: …

Add support for FFI_TYPE_STRUCT_FF/DD on z/OS

---

runtime/compiler/control/HookedByTheJit.cpp
test/functional/JavaAgentTest/playlist.xml

Previously, the redefinition hook would determine the relationship between the old/new and stale/fresh status of redefined classes by checking for `TR_EnableHCR`. This was a proxy for debug mode, in which fast HCR is off because redefinition will OSR and discard the entire code cache. Until recently, this determination was accurate because in debug mode the VM would always redefine classes out-of-place to allow for "extended HCR." However, extended HCR is now being deprecated, and as of 704a781a1e6a, by default it's off and redefinition is in-place.
If a class was redefined in-place unexpectedly, the hook would mix up the old and the new class, which would result in an incorrect CH table state.
Rather than try to predict whether redefinition is supposed to be done in-place, the hook will …

JIT: Detect in-place redefinition based on J9JITRedefinedClass

---

runtime/j9vm/module.xml
runtime/redirector/module.xml

Group `jdk24` was defined, but not referenced in #19803.

Export JVM_IsContainerized() in UMA builds

---

runtime/oti/vm_api.h
runtime/vm/UpcallThunkMem.cpp
runtime/vm/jvminit.c
runtime/vm/vm_internal.h

The changes move the code intended for the release of thunk heap
to `UpcallThunkMem.cpp` so as to consolidate the code specific to
the thunk heap operations to one place, which includes:
1) move `freeUpcallMetaDataDoFn()` to `UpcallThunkMem.cpp`
2) move alll the code with the release of the thunk heap
in `freeJavaVM()` to `releaseThunkHeap()` at `UpcallThunkMem.cpp`
Related: #19714

[FFI] Adjust the code with the release of the thunk heap

---

runtime/gc_modron_startup/mminit.cpp
runtime/jcl/common/sun_misc_Unsafe.cpp
runtime/oti/UnsafeAPI.hpp
runtime/oti/j9nonbuilder.h
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/vmthread.cpp

Set unsafe header offsets to zero when large offheap arrays are enabled.
Replace assertation with exception in `compareAndExchangeObject` due
avoid trace header includes in UnsafeAPI.hpp as that file is used in
various modules.

Array base offset zero

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/env/J9KnownObjectTable.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/InterpreterEmulator.cpp
runtime/compiler/optimizer/J9Inliner.cpp
runtime/compiler/runtime/JITServerIProfiler.cpp
runtime/compiler/runtime/RelocationRuntime.cpp
runtime/compiler/runtime/SymbolValidationManager.cpp
runtime/compiler/runtime/SymbolValidationManager.hpp

Avoid using the thread-local variable TR::compInfoPT (mostly through TR::CompilationInfo::getStream()) in contexts where the compInfoPT or the Compilation is readily available. TLS accesses in dynamically loaded shared libraries (such as the JIT) can have non-negligible overhead.
A resubmission of #14931. That PR also avoided using TLS in the methods of the J9::KnownObjectTable by accessing that class's comp() object to retrieve a JITServer::ServerStream. However, that is (not at all obviously) unsafe to do in that context, because some methods of the J9::KnownObjectTable may be called during the initialization of that very comp() object.
Fixes: #19809

Reduce unnecessary TLS usage in JITServer code (resubmission)

---

buildenv/jenkins/common/build.groovy
buildenv/jenkins/variables/defaults.yml

For 86-64_linux and jdk17+ builds adoptopenjdk/centos7_build_image do not have cuda headers and build fails. This will create an image on the fly based on adopt image and build wont fail. related infra 9292

docker+cuda workaround for 86-64_linux and jdk17+

---

runtime/compiler/optimizer/IdiomRecognitionUtils.cpp

These checks were accidentally removed in
`Update IdiomRecognitionUtils.cpp to use new TransformUtil APIs` commit.
Fixes: https://github.com/eclipse-openj9/openj9/issues/19666

Add missing checks to convert store to load

---

runtime/jvmti/jvmtiRawMonitor.c
runtime/jvmti/jvmtiThreadGroup.c

JVMTI `GetThreadState` uses `Thread.interrupted` to interpret the
thread's state. If a thread is interrupted while waiting for
a monitor in JVMTI `RawMonitorWait`, then it's `Thread.interrupted`
field needs to be updated. This allows JVMTI `GetThreadState` to
return the correct thread state.
Use `JVMTI_ERROR_INTERNAL` (universal error) for the CRIU error
case.
Fixes: #19498

Update Thread.interrupted in JVMTI RawMonitorWait

---

runtime/jvmti/jvmtiRawMonitor.c
runtime/jvmti/jvmtiThreadGroup.c

JVMTI `GetThreadState` uses `Thread.interrupted` to interpret the
thread's state. If a thread is interrupted while waiting for
a monitor in JVMTI `RawMonitorWait`, then it's `Thread.interrupted`
field needs to be updated. This allows JVMTI `GetThreadState` to
return the correct thread state.
Use `JVMTI_ERROR_INTERNAL` (universal error) for the CRIU error
case.
Fixes: #19498

(0.47) Update Thread.interrupted in JVMTI RawMonitorWait

---

runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/control/JITServerHelpers.hpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/runtime/JITServerAOTCache.cpp
runtime/compiler/runtime/JITServerAOTDeserializer.cpp
runtime/compiler/runtime/JITServerAOTDeserializer.hpp
runtime/compiler/runtime/JITServerSharedROMClassCache.cpp
runtime/compiler/runtime/JITServerSharedROMClassCache.hpp

If a JITServer client has a cached hash for a ROMClass, it may now send this hash to the server to avoid the server having to re-hash (and possibly re-pack) the ROMClass received from the client. The server will store this cached hash in its shared ROMClass cache. Currently, only the stored hashes of generated classes are sent to the server.

Send cached J9ROMClass hashes to JITServer

---

runtime/compiler/control/HookedByTheJit.cpp

If the JVM is in JITServer client mode, GCR counting will be enabled even during JIT startup phases (but not during JVM startup phase which only happens once). This allows GCR recompilations to happen sooner, improving rampup. In client mode there is a lesser risk that GCR recompilation overhead will impact the throughput of the JVM.
This change can be overridden by using the following environment variable:
export TR_LookAtJitStateForGCREnablement=1

Do not look at JIT startup state for turning GCR on/off

---

runtime/compiler/il/J9Node.cpp

The corresponding assert in `omr/compiler/il/OMRNode.cpp` was updated in the same way as this PR in https://github.com/eclipse/omr/pull/7345.
Fixes: #19836

Update _unionPropertyA assert

---

runtime/tests/jvmtitests/agent/CMakeLists.txt
runtime/tests/jvmtitests/src/CMakeLists.txt

Having confirmed that exporting symbols is required for jvmtitests,
this change adds an Open XL conditional for the flag EXPORTALL
(-fvisibility=default).

Add Open XL equivalent for EXPORTALL in jvmtitests

---

runtime/vm/BufferWriter.hpp
runtime/vm/JFRChunkWriter.cpp
runtime/vm/JFRChunkWriter.hpp

* avoid using new/delete so libstdc++.so is not needed at runtime
* tidy up
With JFR enabled, `libstdc++.so` is required by `libj9vm29.so`, which we don't want. UMA builds just fail because that library is not made available to the linker.

Inline VM_JFRConstantPoolTypes into VM_JFRChunkWriter

---

test/functional/NativeTest/nativeTestSettings.mk

Since the switch to using "mixed references", there no longer is a "compressedrefs" folder.

Correct path to libj9ifa29.so for Java 11+

---

runtime/compiler/runtime/JITServerAOTCache.cpp
runtime/compiler/runtime/JITServerAOTCache.hpp
runtime/compiler/runtime/JITServerAOTSerializationRecords.hpp

- The `AOTCacheRecord::setSubrecordPointers` method is now protected, instead of private. This works around a bug in clang. Without this, the invocation of `setSubrecordPointers` in the `AOTCacheRecord::readRecord<>` template method fails; clang complains that `setSubrecordPointers` is a private method of `AOTCacheRecord`. This shouldn't matter at all, as a method of `AOTCacheRecord` ought to be able to call the private methods of the `AOTCacheRecord` class itself, but clang issues an erroneous access error anyway.
- Instead of having an `AOTCacheListRecord` class from which the `AOTCacheClassChainRecord` and `AOTCacheWellKnownClassesRecord` classes are derived, those classes now derive from the base `AOTCacheRecord` class and declare their own methods separately. Some code duplication …

Improve JITServer AOT cache implementation portability

---

buildenv/jenkins/common/build.groovy

When SDK_VERSION is non-numeric (e.g next) then cuda workaround fails as we are trying to compare it with 17 for xlinux. This change aims to solve that issue by taking care of `next` separately.

Fix error when param SDK_VERSION is not numeric

---

runtime/libffi/z/sysvz64.s

R0's value is used to calculate a branch offset. This value can be between 0 and 3. Due to the nature of how complex types are passed in registers, it's possible to increment this value beyond 3. This commit adds some support code to cap that value at 3 before any branch offsets are computed.

Cap R0's value to 3 when handling complex structs in sysvz64.s

---

runtime/jvmti/jvmtiObject.c

Related: https://github.com/eclipse-openj9/openj9/pull/19871#discussion_r1686758594

Fix compiler error, unused variable: currentThread

---

runtime/j9vm/j7vmi.c
runtime/jcl/common/jcldefine.c
runtime/nls/j9vm/j9vm.nls
runtime/oti/j9nonbuilder.h
runtime/vm/classsupport.c

Class names are stored as a UTF8 string and length is represented by
two bytes
Port to 0.46: https://github.com/eclipse-openj9/openj9/pull/19898

Enforce maximum name size during class loading

---

runtime/jvmti/jvmtiObject.c

- RI has removed support for virtual threads if an object monitor is
owned by a virtual thread.
- Support has also been removed for virtual threads that are waiting
be notified or own a monitor.
- Also, new tests show that waiting to be notified threads do not
repeat and only appear in one list. This has been corrected in OpenJ9.
- Update formatting in jvmtiObject.c to follow coding standards.
Fixes: #19497
Backport of https://github.com/eclipse-openj9/openj9/pull/19871

(0.47) Add virtual thread support for JVMTI GetObjectMonitorUsage

---

runtime/jvmti/jvmtiHelpers.cpp

Check if the continuation is finished to determine more accurately if a virtual thread is alive.
Related: https://github.com/eclipse-openj9/openj9/issues/18738#issuecomment-2218824062
Backport of #19842

(0.47) Update VThread alive check to check continuation state

---

runtime/j9vm/j7vmi.c
runtime/jcl/common/jcldefine.c
runtime/nls/j9vm/j9vm.nls
runtime/oti/j9nonbuilder.h
runtime/vm/classsupport.c

Class names are stored as a UTF8 string and length is represented by
two bytes
Port from https://github.com/eclipse-openj9/openj9/pull/19895

0.46: Enforce maximum name size during class loading

---

runtime/j9vm/j7vmi.c
runtime/jcl/common/jcldefine.c
runtime/nls/j9vm/j9vm.nls
runtime/oti/j9nonbuilder.h
runtime/vm/classsupport.c

Class names are stored as a UTF8 string and length is represented by
two bytes
Port from https://github.com/eclipse-openj9/openj9/pull/19895

0.47: Enforce maximum name size during class loading

---

jcl/src/java.base/share/classes/java/lang/String.java
test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_String.java

Also, return the original String in the fast paths when nothing is replaced.
Issue https://github.com/eclipse-openj9/openj9/issues/19903

String.replaceAll() fast path must check regex is compressed

---

jcl/src/java.base/share/classes/java/lang/String.java
test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_String.java

Also, return the original String in the fast paths when nothing is replaced.
Issue https://github.com/eclipse-openj9/openj9/issues/19903

(0.46) String.replaceAll() fast path must check regex is compressed

---

jcl/src/java.base/share/classes/java/lang/String.java
test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_String.java

Also, return the original String in the fast paths when nothing is replaced.
Issue https://github.com/eclipse-openj9/openj9/issues/19903

(0.47) String.replaceAll() fast path must check regex is compressed

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9Inliner.hpp

In this contribution, the following adjustments have been made to the arguments that are passed in to Unsafe.get(), Unsafe.put(), and Unsafe.compareAndSwap() when offheap/balanced GC policy is in use:
- The dataAddr pointer is loaded and passed in as the base address of the object being operated on
- ~The array header size is subtracted from the offset~ 
_no longer necessary due to this change_: https://github.com/eclipse-openj9/openj9/pull/19326/
This is to account for the differing array shape under offheap/balanced GC policy as opposed to the default (gencon).
In addition, as a performance improvement for both the offheap and gencon cases, when the object type is known at compile time, we can eliminate unnecessary lowtag, class, and array checks that are currently performed at runtime …

Adjust arguments to Unsafe array operations while offheap is enabled

---

jcl/src/java.base/share/classes/java/lang/Access.java

JDK24 removes `JavaLangAccess.stringConcatHelperPrepend()`
This resolves JDK next abuild compilation failure - https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_OpenJDK/591/consoleFull
```
00:11:10  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:425: error: method does not override or implement a method from a supertype
00:11:10  	@Override
00:11:10  	^
00:11:10  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:427: error: no suitable method found for prepend(long,byte[],String)
00:11:10  		return StringConcatHelper.prepend(indexCoder, buf, value);
``` …

JDK24 removes JavaLangAccess.stringConcatHelperPrepend()

---

runtime/compiler/z/codegen/J9TreeEvaluator.cpp

Repurpose registers when no longer needed.
Remove unused registers.
Use scratch register manager inside genHeapAlloc

Z: remove unused and redundant register from object evaluator

---

runtime/bcverify/rtverify.c
runtime/oti/bytecodewalk.h

Throw an error during bytecode verification if the receiver of invokeinterface is a reference array.
Fix: #19756

Error if invokeinterface receiver is reference array

---

jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java

- update comments using primitive language
- remove stale methods getReferenceVolatile and getReference
- add methods hasNullMarker and nullMarkerOffset to match RI
Related: https://github.com/eclipse-openj9/openj9/issues/19677

Update Unsafe value type comments and Java methods

---

runtime/j9vm/j9scar.tdf
runtime/j9vm/jvm.c

`JDK17+` `JVM_LoadLibrary()` opens shared library via `J9PORT_SLOPEN_DECORATE`
`j9sl_open_shared_library()` with the flag `J9PORT_SLOPEN_DECORATE` expects the incoming library name to be platform independent, i.e., it must not contain any prefix or file extension. A path to the library is supported.
Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/814
* https://github.com/ibmruntimes/openj9-openjdk-jdk23/pull/13
closes https://github.com/eclipse-openj9/openj9/issues/19344

JDK17+ JVM_LoadLibrary() opens shared library via J9PORT_SLOPEN_DECORATE

---

runtime/j9vm/j9scar.tdf
runtime/j9vm/jvm.c

`JDK17+` `JVM_LoadLibrary()` opens shared library via `J9PORT_SLOPEN_DECORATE`
`j9sl_open_shared_library()` with the flag `J9PORT_SLOPEN_DECORATE` expects the incoming library name to be platform independent, i.e., it must not contain any prefix or file extension. A path to the library is supported.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/19861

(v0.47.0-release) JDK17+ JVM_LoadLibrary() opens shared library via J9PORT_SLOPEN_DECORATE

---

runtime/j9vm/jvm.c

This corrects an oversight in #14739 which changed the signature, but not the body of the function.

JVM_LoadLibrary: respect throwOnFailure in jdk11

---

runtime/gc_modron_startup/mminit.cpp

There is little expected benefit with concurrentmark if you are running on a single-CPU machine/environment. On the other hand, you could gain some benefits with noConcurrentMark: 1) no interference from background marking thread; 2) shorter write-barrier path-length: for certain workloads, this provides substantial performance benefits (e.g. Spark TPC-DS q72 in particular).

Treat single CPU as if -Xgc:noConcurrentMark were set

---

runtime/jcl/common/system.c

The z/OS specific com.ibm.autocvt property should default to true only if the file.encoding property is unset. If file.encoding is set to a specific charset or COMPAT, then we disable auto conversion to retain the same behaviour as JDK17 and earlier releases.

Update com.ibm.autocvt to default to true unless file.encoding is set

---

jcl/src/java.base/share/classes/java/lang/Access.java

`JDK24` removes `JavaLangAccess.stringSize(long x)`
Resolve jdk head stream abuild compilation error:
```
23:58:58  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:432: error: cannot find symbol
23:58:58  		return Long.stringSize(x);
23:58:58  		           ^
23:58:58    symbol:   method stringSize(long)
```
The openjdk change in question is https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/489b87654d9b6953227a951423d74cbfdc3c20d7

JDK24 removes JavaLangAccess.stringSize(long)

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp

wherever it is appropriate (and intended), isIndexableDataAddrPresent is changed into isOffheapAllocationEnabled.

Change to use isOffheapAllocationEnabled query

---

jcl/src/java.base/share/classes/java/lang/Access.java

See [8336254: Virtual thread implementation + test updates](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/c9e87eb05f0703b880088d2eec1393d64aef078e).

JDK24 removes JavaLangAccess.executeOnCarrierThread()

---

test/functional/Java8andUp/build.xml
test/functional/Java8andUp/playlist.xml
test/functional/Java8andUp/testng.xml
test/functional/Java8andUp/testng_thread.xml
test/functional/cmdLineTests/jvmtitests/build.xml

- Thread functions are removed for JDK 23, extract test to JDK 22 and under
Related Issue and PRs: https://github.com/eclipse-openj9/openj9/issues/18758 https://github.com/ibmruntimes/openj9-openjdk-jdk23/pull/16 and https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/818

Extract Thread Test to JDK 22 and under

---

runtime/bcverify/rtverify.c
runtime/oti/bytecodewalk.h

Throw an error during bytecode verification if the receiver of invokeinterface is a reference array
Port from: https://github.com/eclipse-openj9/openj9/pull/19877

0.47: Error if invokeinterface receiver is reference array

---

buildenv/jenkins/variables/defaults.yml

Now that plinux build moved to docker, we can set cuda level to `cuda_default` as we use for others like xlinux. With that we can also remove `cuda_9` which only plinux is using.

Sets cuda_default for p Linux and removes cuda_9

---

runtime/vm/vmthread.cpp

Currently, they are set according to how many CPUs there are online. However, it makes more senses to set them according to how many CPUs
JVM is going to run. Such that, we can take advantages of single-CPU
scenarios (be it numactl or container).

Set spin-counts right

---

test/functional/cmdLineTests/jvmtitests/build.xml

Remove the duplicate exclude for GetThreadListStackTracesExtendedTest.
Issue: https://github.com/eclipse-openj9/openj9/pull/19918#discussion_r1697151877

Remove duplicate exclude in jvmtitests

---

runtime/gc_base/GCExtensions.cpp
runtime/oti/j9nonbuilder.h

Looks like J9JavaVM->gcInfo field and J9GCVMInfo, J9GCThreadInfo structs are not used and can be deleted.

Remove unused J9GCVMInfo and J9GCThreadInfo

---

runtime/vm/JFRWriter.hpp

Correct spelling of METADATA_BLOB_FILE_ENVVAR

---

doc/release-notes/0.46/0.46.md

https://github.com/eclipse-openj9/openj9-docs/issues/1330
Updated the draft release note that includes the known issues related to -XX:+ShareOrphans
[skip ci]

Update 0.46.0 release note

---

test/functional/VM_Test/src/j9vm/runner/Runner.java
test/functional/VM_Test/src/j9vm/test/javahome/JavaHomeTestRunner.java

Also reorganize and tidy up.
This was motivated by messages like
```
[2024-07-26T07:59:06.968Z] Runner couldn't determine underlying architecture. Got OS Arch:aarch64
```
A recent example can be seen in [a JDK acceptance build](https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.functional_aarch64_linux_OpenJDK23_testList_0/5/consoleText).

Add support for aarch64 to j9vm.runner.Runner

---

test/functional/Java21andUp/src/org/openj9/test/jep425/VirtualThreadTests.java

JDK24 removed VirtualThreads.park() from the stack trace in
* [8336254: Virtual thread implementation + test updates](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/c9e87eb05f0703b880088d2eec1393d64aef078e)
reducing the stack from 6 to 5 elements.
A recent failure can be seen in https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJDKnext/284.

Update number of frames for test_YieldedVirtualThreadGetStackTrace

---

runtime/bcverify/rtverify.c

Rework fix for https://github.com/eclipse-openj9/openj9/issues/19756 to address invokeinterface array receiver type and internal test suites.
0.47: https://github.com/eclipse-openj9/openj9/pull/19946

Verification check for invokeinterface receiver

---

test/functional/cmdLineTests/jfr/build.xml

Use include tag instead of filename tag.
Remove *.mk selector since it does not match any file.
Fix: https://github.com/eclipse-openj9/openj9/issues/19950

Fix cmdLineTester_jfr

---

runtime/util/hshelp.c

jitClassRedefineEvent is updated to include an explicit check for FSD being enabled.
The result of this is the code cache is tossed out if either HCR extensions are enabled or FSD mode is enabled.
Issue: https://github.com/eclipse-openj9/openj9/issues/19813

Adds FSD check to jitClassRedefineEvent

---

test/functional/Java8andUp/build.xml
test/functional/Java8andUp/playlist.xml
test/functional/Java8andUp/testng.xml
test/functional/Java8andUp/testng_thread.xml
test/functional/cmdLineTests/jvmtitests/build.xml

This cherry-picks #19918 and #19940 for the 0.47.0 release branch.

(0.47) Extract Thread Test to JDK 22 and under

---

runtime/compiler/runtime/IProfiler.cpp

Interpreter profiling is uses lockless mechanisms that allow for some races to occur. The outcome of these races is some small memory leak.
When adding new profiling info to the IProfiler hashtable, we first determine if an entry with the same pc exists (pc is the key) and if not, we allocate memory for a new entry and then add the entry to the head of the linked list of the corresponding bucket of the IP hashtable. It turns out that allocating memory for a new entry is relatively expensive, and in this window of time another thread could perform the same check, deciding to add a new entry with the same pc.
This commit performs another check just before adding to the linked list of the bucket. This reduces the likelihood of two threads adding entries with the same pc.

Make IProfiler race conditon less likely

---

doc/release-notes/0.46/0.46.md

Updated the release note with the remaining issues in 0.46.0 release
[skip ci]

Updated 0.46.0 Release note with new features

---

runtime/vm/JFRChunkWriter.cpp
runtime/vm/JFRChunkWriter.hpp
runtime/vm/JFRConstantPoolTypes.cpp
runtime/vm/JFRConstantPoolTypes.hpp

- Add default entries for empty stack traces and unknown native methods.
- Add missing free for stackframe entries after writing chunk.
- Iterate the stack trace one before to get the real size.
- JFR readers do not accepts UDATA_MAX values for BCI and line numers, so use 0 instead if values are unknown.
- Add support for writing intermediate jfr files, currently we use this for debugging. But there are JFR modes that require this.
- Add compressedInts flag to chunk writer.
There is more work to be done for handling internal native functions as well as fixing the timestamps this will be addressed in a future PR.

JFR Writer fixes part1

---

runtime/oti/FFIUpcallThunkGenHelpers.hpp

Making FFI Upcall's helper methods static causes compilation failures on certain platforms and build levels as the compiler expects the methods to be used internally. This commit removes that requirement.

Don't make upcall helper methods static on Z

---

runtime/compiler/runtime/IProfiler.cpp
runtime/compiler/runtime/IProfiler.hpp

This commit implements the following changes:
- `operator new` was defined in every class derived from TR_IPBytecodeHashTableEntry After this commit there will be only one definition of `operator new` provided by the base class TR_IPBytecodeHashTableEntry and all derived classes will use the same definition. The same applies for `operator delete`
- `operator delete` used to do nothing. After this commit `operator delete` will use the IProfiler persistent memory deallocator to free memory. Note that freed memory goes into a pool, to be reused later.
- For 64-bit environments, `operator new` used to ensure aligned allocations by adding four bytes the size needed and then rounding up on a 8 byte boundary. This is not needed, because the persistent allocator already makes sure that …

Changes for new/delete used by IProfiler

---

runtime/compiler/z/runtime/Math.m4
runtime/compiler/z/runtime/PicBuilder.m4
runtime/compiler/z/runtime/Recompilation.m4
runtime/compiler/z/runtime/ValueProf.m4

Similar to previously fixed Open XL errors, there were some more m4 files that generated extra newlines at the end of the generated assembly files. These changes make the tweaks to address this so as to only leave a single newline at the end of these generated assembly files.

Remove extra newlines in generated assembly files

---

runtime/gc_modron_startup/mminit.cpp

Reverts eclipse-openj9/openj9#19919

Revert "Treat single CPU as if -Xgc:noConcurrentMark were set"

---

runtime/rasdump/javadump.cpp

The `-Xjit` and `-Xaot` args being ignored because there are multiple `-Xjit` or `-Xaot` arguments (only the last one will be considered), or because there exists `-Xnojit`, `-Xnoaot`, or `-Xint` (ignores the arguments before the in the command line option) will be displayed in the IGNOREDARGS list during the core dump.
Fixes #19742

Display ignored -Xjit and -Xaot args in IGNOREDARGS list

---

runtime/j9vm/jvm.c

Currently Java 21 and up on z/OS build with system zlib under /lib.
Append it to LIBPATH so that system zlib can be resolved.
[Internal issue](https://github.ibm.com/runtimes/openj9-openjdk-jdk21-zos/issues/299)

Append /lib to LIBPATH if it is not present on z/OS Java 21+

---

jcl/jpp_configuration.xml
jcl/src/java.base/share/classes/java/lang/Access.java

`JDK24` adds `JavaLangAccess.stringConcat1()`
Also updated `jpp_configuration.xml` to refer `rt-compressed.sunJava24.jar`.
Resolve JDK next abuild compilation failure https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_OpenJDK/611/consoleFull
```
00:10:00  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:70: error: Access is not abstract and does not override abstract method stringConcat1(String[]) in JavaLangAccess
00:10:00  final class Access implements JavaLangAccess {
```

JDK24 adds JavaLangAccess.stringConcat1()

---

runtime/compiler/runtime/RelocationRuntime.cpp

- if TR_InstallAOTToCold option is on, install AOT methods into the cold part of the code cache
Depends on: https://github.com/eclipse/omr/pull/7440

Install AOT methods into cold code

---

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp

The implementation of `StringUTF16.toBytes` will throw a `NegativeArraySizeException` if the specified array length is negative or an `OutOfMemoryError` if the length is 2^30 or greater.  The IL for the inline implementation that the JIT compiler generates for that recognized method could throw a `NegativeArraySizeException` in situations where the actual implementation would throw an `OutOfMemoryError`.
This change calls the actual implementation if the array length is outside the range [0,0x3fffffff] to ensure that the behaviour is always as expected in exceptional situations.
Fixes #19309

Fall back to out-of-line call to StringUTF16.toBytes

---

doc/compiler/jitserver/Problem.md
runtime/compiler/env/VMJ9Server.cpp

The method getLineNumberForMethodAndByteCodeIndex, in the base VM frontend, is supposed to retrieve the line number corresponding to a method and byte codex index from the method's associated ROM method. At the server, these line numbers are not directly accessible, so the server must request this information from the client whenever that method is called.
These line numbers appear to be used only when generating compilation logs. The most notable use of this method for that purpose is in dumping IL trees - for every line of this dump, this method will be called. Even this network overhead is not usually significant. However, if the method being compiled at the server is very large, at a high optimization level, and has many trace options enabled, these line number messages can slow the …

Allow JITServer to ignore line number requests

---

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp

The implementation of `StringUTF16.toBytes` will throw a `NegativeArraySizeException` if the specified array length is negative or an `OutOfMemoryError` if the length is 2^30 or greater.  The IL for the inline implementation that the JIT compiler generates for that recognized method could throw a `NegativeArraySizeException` in situations where the actual implementation would throw an `OutOfMemoryError`.
This change calls the actual implementation if the array length is outside the range [0,0x3fffffff] to ensure that the behaviour is always as expected in exceptional situations.
Port of pull request #19953 to v0.47.0-release branch for issue #19309

(0.47.0) Fall back to out-of-line call to StringUTF16.toBytes

---

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp

The implementation of `StringUTF16.toBytes` will throw a `NegativeArraySizeException` if the specified array length is negative or an `OutOfMemoryError` if the length is 2^30 or greater.  The IL for the inline implementation that the JIT compiler generates for that recognized method could throw a `NegativeArraySizeException` in situations where the actual implementation would throw an `OutOfMemoryError`.
This change calls the actual implementation if the array length is outside the range [0,0x3fffffff] to ensure that the behaviour is always as expected in exceptional situations.
Port of pull request #19953 to v0.48.0-release branch for issue #19309

(0.48.0) Fall back to out-of-line call to StringUTF16.toBytes

---

runtime/compiler/control/JITClientCompilationThread.cpp

If the JIT option enableJITServerFollowRemoteCompileWithLocalCompile is enabled for a particular method, a JITServer client will compile that method again, locally, whenever it receives a compiled version of the method from the server. The start and end of this compilation are now noted in the verbose log if TR_VerboseJITServer is enabled.

Log local-following-remote compilations

---

runtime/compiler/env/j9method.cpp

The `TR_ResolvedJ9Method::vTableSlot()` would formerly assert that the `_vTableSlot` of the resolved method was not zero before returning its value. This is not particularly helpful, as none of the existing code assumes that the `vTableSlot()` will be valid when calling this method, and there are certain kinds of resolved methods that may legitimately have a `_vTableSlot` of zero.
This assert would (unnecessarily) fire in particular in the handling of the `ResolvedMethod_getMultipleResolvedMethods` message at a JITServer client. Removing it eliminates the resulting crash in debug/prod-with-assumes builds.
Fixes: https://github.com/eclipse-openj9/openj9/issues/19983

Avoid vTableSlot assertion at JITServer client

---

runtime/rasdump/javadump.cpp

-Xjit and -Xaot args will not be incorrectly listed as ignored in the IGNOREDARGS list when -XX:+MergeCompilerOptions is used.

In IGNOREDARGS list -Xjit and -Xaot args will not be incorrectly listed as ignored

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/runtime/RelocationRuntime.cpp

Current code for x86 disables TLH prefething globally for Intel CPUs newer than Broadwell architecture and enables it globally for Broadwell or older CPUs.
If a container image is generated on a newer architecture, then TLH prefetch will be off and this information is written into the AOT header for the shared class cache embedded in the container. If that container image is run on an older architecture, the JVM will set TLH prefetch off, and the AOT compatibility check will fail, rendering the embedded AOT code useless.
This commit disables TLH prefething for portable AOT code.

Disable TLH prefetching for portable AOT code

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/runtime/CRRuntime.cpp
runtime/compiler/runtime/CRRuntime.hpp
runtime/compiler/runtime/IProfiler.cpp
runtime/compiler/runtime/IProfiler.hpp

This PR adds a few improvements under `-XX:+DebugOnRestore`:
* Add verbose output at checkpoint
* Drop IProfier buffers precheckpoint
* Delay JVM phase change post-restore

Footprint Improvements under `-XX:+DebugOnRestore`

---

runtime/libffi/z/sysvz64.s

Incorrect branch was taken when there is a struct parameter which should be in GPR3. The incorrect branch was causing it to store the third struct parameter in GPR2 instead of GPR3.

Fix a corner case with libffi on z/OS to handle Structs

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/runtime/RelocationRuntime.cpp

Current code for x86 disables TLH prefething globally for Intel CPUs newer than Broadwell architecture and enables it globally for Broadwell or older CPUs.
If a container image is generated on a newer architecture, then TLH prefetch will be off and this information is written into the AOT header for the shared class cache embedded in the container. If that container image is run on an older architecture, the JVM will set TLH prefetch off, and the AOT compatibility check will fail, rendering the embedded AOT code useless.
This commit disables TLH prefething for portable AOT code.

(0.46.1) Disable TLH prefetching for portable AOT code

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/runtime/RelocationRuntime.cpp

Current code for x86 disables TLH prefething globally for Intel CPUs newer than Broadwell architecture and enables it globally for Broadwell or older CPUs.
If a container image is generated on a newer architecture, then TLH prefetch will be off and this information is written into the AOT header for the shared class cache embedded in the container. If that container image is run on an older architecture, the JVM will set TLH prefetch off, and the AOT compatibility check will fail, rendering the embedded AOT code useless.
This commit disables TLH prefething for portable AOT code.

(0.47.0) Disable TLH prefetching for portable AOT code

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/runtime/RelocationRuntime.cpp

Current code for x86 disables TLH prefething globally for Intel CPUs newer than Broadwell architecture and enables it globally for Broadwell or older CPUs.
If a container image is generated on a newer architecture, then TLH prefetch will be off and this information is written into the AOT header for the shared class cache embedded in the container. If that container image is run on an older architecture, the JVM will set TLH prefetch off, and the AOT compatibility check will fail, rendering the embedded AOT code useless.
This commit disables TLH prefething for portable AOT code.

(0.48.0) Disable TLH prefetching for portable AOT code

---

runtime/j9vm/jvm.c

Fix JDK11 Windows compilation error
```
01:10:58.774  c:\workspace\openjdk-build\workspace\build\src\openj9\runtime\j9vm\jvm.c(4089): error C2065: 'attemptedLoad': undeclared identifier
01:10:58.774  make[6]: *** [runtime/j9vm/CMakeFiles/jvm.dir/build.make:176: runtime/j9vm/CMakeFiles/jvm.dir/jvm.c.obj] Error 2
```

Fix JDK11 Windows compilation error

---

runtime/j9vm/jvm.c

Fix JDK11 Windows compilation error
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/20054

(0.48.0) Fix JDK11 Windows compilation error

---

runtime/oti/j9nonbuilder.h
runtime/vm/CMakeLists.txt
runtime/vm/LayoutFFITypeHelpers.cpp
runtime/vm/LayoutFFITypeHelpers.hpp
runtime/vm/LayoutFFITypeTable.cpp
runtime/vm/jvminit.c
runtime/vm/vm_internal.h

The changes aim to optimize the existing code to avoid
creating duplicate ffi_type for the same structs regardless
of nested structs in downcall to minimize the native
memory allocation for ffi_types with the arguments and
the return type.
Fixes: #19714

[FFI] Avoid duplicating ffi_type for the same struct in downcall

---

runtime/oti/j9nonbuilder.h
runtime/oti/j9vm.hdf
runtime/vm/BufferWriter.hpp
runtime/vm/JFRChunkWriter.cpp
runtime/vm/JFRChunkWriter.hpp
runtime/vm/JFRConstantPoolTypes.cpp
runtime/vm/JFRConstantPoolTypes.hpp
runtime/vm/JFRUtils.hpp
runtime/vm/jfr.cpp
runtime/vm/threadhelp.cpp

Set the ticks/second parameter in the chunk header. This indicates which granularity we report timestamps (millis, micros or nanos). Note, this is not to be confused with the event startime which is always milliseconds.
Also, chage threadsleep event to report on after the sleep as concluded which matches RI behaviour. The actual sleep duration must be recorded.

Fix JFR timestamps

---

runtime/compiler/control/HookedByTheJit.cpp
test/functional/JavaAgentTest/playlist.xml

Backport of https://github.com/eclipse-openj9/openj9/pull/19824

(0.47) JIT: Detect in-place redefinition based on J9JITRedefinedClass

---

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp

Recognized Call Transformer generates IL that implements an inline version of `StringUTF16.toBytes` for values in the range [0,0x3fffffff], and that falls back to calling the Java implementation otherwise.  In JDK levels up to 22, the Java implementation throws an `OutOfMemoryException` if the length is greater than 0x3fffffff.  JDK Level 23, however, was changed to throw an `OutOfMemoryException` if the length is greater than _or equal to_ 0x3fffffff.
This change alters the IL that Recognized Call Transformer generates to fall back to the Java implementation if the length is greater than or equal to 0x3fffffff, so that it will work with all JDK levels.
Fixes:  #20021

Adjust bound for out-of-line call to StringUTF16.toBytes

---

jcl/src/java.base/share/classes/java/lang/Access.java
jcl/src/java.base/share/classes/java/lang/System.java

JDK24 requires new `JavaLangAccess.ensureNativeAccess()`
Also requires `System.codeSource(Class<?> callerClz)`.
This resolves JDK next abuild compilation failures:
```
00:43:02  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/src/java.base/share/classes/java/lang/Module.java:314: error: cannot find symbol
00:43:02                  URL url = System.codeSource(currentClass);
00:43:02  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:70: error: Access is not abstract and does not override abstract method ensureNativeAccess(Module,Class<?>,String,Class<?>,boolean) in JavaLangAccess
```

JDK24 requires new JavaLangAccess.ensureNativeAccess()

---

runtime/libffi/z/sysvz64.s
runtime/oti/j9nonbuilder.h
runtime/vm/CMakeLists.txt
runtime/vm/LayoutFFITypeHelpers.cpp
runtime/vm/LayoutFFITypeHelpers.hpp
runtime/vm/LayoutFFITypeTable.cpp
runtime/vm/jvminit.c
runtime/vm/vm_internal.h

The changes aim to optimize the existing code to avoid
creating duplicate ffi_type for the same structs regardless
of nested structs in downcall to minimize the native
memory allocation for ffi_types with the arguments and
the return type.
Note:
Cherry pick of #20042, #19988 for 0.48

[FFI/0.48] Avoid duplicating ffi_type for the same struct in downcall

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp

When running AOT compilation without SVM, there's no information for the guess tests to be patched later, hence disable generating the inlined guess tests.
Closes: #18972

Disable inlined instanceOf guess tests for AOT non-SVM compilations

---

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp

Recognized Call Transformer generates IL that implements an inline version of `StringUTF16.toBytes` for values in the range [0,0x3fffffff], and that falls back to calling the Java implementation otherwise.  In JDK levels up to 22, the Java implementation throws an `OutOfMemoryException` if the length is greater than 0x3fffffff.  JDK Level 23, however, was changed to throw an `OutOfMemoryException` if the length is greater than _or equal to_ 0x3fffffff.
This change alters the IL that Recognized Call Transformer generates to fall back to the Java implementation if the length is greater than or equal to 0x3fffffff, so that it will work with all JDK levels.
Port of pull request #20058 to v0.48.0-release branch

[0.48.0] Adjust bound for out-of-line call to StringUTF16.toBytes

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/runtime/JITServerAOTDeserializer.cpp
runtime/compiler/runtime/JITServerAOTDeserializer.hpp

When a class is redefined, the old, invalidated RAM methods may be held in the "oldClass" or the "newClass", depending on whether or not the class was redefined in-place. To ensure that all the old RAM methods from the redefined class are purged from the JITServer AOT deserializer's caches, and to avoid having to detect the type of redefinition, both the old and new classes are now invalidated.
The incomplete invalidation of classes is not currently a problem, as the only place the deserializer's method cache is queried for a stored RAM method during relocation happens to be reachable only if the defining class has not been invalidated. This change avoids a possible bug that would arise if this were ever not the case.

Ensure deserializer class invalidation is complete

---

.gitattributes

This PR fixes functional compilation issues seen due to improper tagging of jar/war/keystore files on JDK21. Hence tagging these extension files as binary.
Verification : Grinder_CR/22174

Tag jar/keystore files as binary

---

runtime/compiler/env/J9ClassEnv.hpp
runtime/compiler/env/J9ObjectModel.hpp
runtime/compiler/optimizer/J9ValuePropagation.cpp
runtime/oti/vm_api.h
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/ValueTypeHelpers.hpp
test/functional/Valhalla/src_lw5/org/openj9/test/lworld/NullRestrictedTypeOptTests.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java

Corrects all cases of "null restricted" that are not fixed in https://github.com/eclipse-openj9/openj9/pull/19911

Correct "null restricted" to null-restricted

---

runtime/compiler/optimizer/J9TransformUtil.cpp

UnsafeFastPath generates the wrong tree when inlining the `JITHelpers.getByteFromArrayByIndex()` call in `String.hashCodeImplCompressed()` as it uses `calculateOffsetFromIndexInContiguousArray()` which adds the header-size to the trees [1]. This fix prevent inserting the header-size addition if OffHeap is in use.
[1]
Before
```
n25n        aload  java/lang/String.helpers Lcom/ibm/jit/JITHelpers;[#409  notAccessed final Static] (obj1) [flags 0xa0307 0x0 ]  [    0x70ed200b5040] bci=[-1,22,3136] rc=3 vc=4 vn=- li=- udi=- nc=0
n29n        icall  com/ibm/jit/JITHelpers.getByteFromArrayByIndex(Ljava/lang/Object;I)B[#413  final virtual Method -512] [flags 0x20500 0x0 ] ()  [    0x7c78f8765180] bci=[-1,31,3136] rc=2 vc=0 vn=- li>
n26n          aload  java/lang/String.helpers …
```

Fix calculareOffsetFromIndex for OffHeap

---

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/LayoutStrPreprocessor.java
runtime/oti/j9nonbuilder.h
runtime/vm/LayoutFFITypeHelpers.hpp

[FFI] Fix the issue with the struct FF/DD in upcall on z/OS
The changes resolve the issue with the register mapping for the
struct FF/DD or its variants in upcall on z/OS by categorizing
them into ALL_SP/ALL_DP placed on FPRs while other non-complex
type are categorized into AGGREGATE_OTHER placed on GPRs.
Fixes: #19952

[FFI] Fix the issue with the struct FF/DD in upcall on z/OS

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9Inliner.hpp

Updated version of https://github.com/eclipse-openj9/openj9/pull/17969 that addresses https://github.com/eclipse-openj9/openj9/issues/19947.

Adjust arguments to Unsafe array operations while offheap is enabled (FIXED)

---

test/functional/JIT_Test/src/jit/test/jitserver/JITServerTest.java

Part of the teardown process in the JITServer tests involves waiting for the server and client to shut down in an orderly fashion. Occasionally this can (legitimately) take longer than 30s for the client, the previous maximum. This causes the test to forcibly destroy the process and mark the test as having failed. We now wait for up to one minute for these processes to finish.

Wait up to 1 minute in JITServer test

---

debugtools/DDR_VM/src/com/ibm/j9ddr/AuxFieldInfo29.dat

Declare a fictitious (and unused) field to simulate the existence of that structure in system dumps from JVMs that predate its introduction.
Fixes: #19934.

Ensure that J9JITGPRSpillArea is available

---

debugtools/DDR_VM/src/com/ibm/j9ddr/AuxFieldInfo29.dat

Cherry-pick https://github.com/eclipse-openj9/openj9/pull/20097 for the 0.46.1 release.

(0.46.1) Ensure that J9JITGPRSpillArea is available

---

debugtools/DDR_VM/src/com/ibm/j9ddr/AuxFieldInfo29.dat

Cherry-pick https://github.com/eclipse-openj9/openj9/pull/20097 for the 0.48.0 release.

(0.48.0) Ensure that J9JITGPRSpillArea is available

---

buildenv/jenkins/variables/defaults.yml

To include fix for CVE-2024-6119.
See https://github.com/openssl/openssl/blob/openssl-3.0/CHANGES.md#changes-between-3014-and-3015-3-sep-2024.

Update to openssl 3.0.15

---

runtime/j9vm/exports.cmake
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/javanextvmi.cpp
runtime/redirector/forwarders.m4

JDK24 adds `JVM_IsStaticallyLinked(void)`
Support [[JDK-8333301] Remove static builds using --enable-static-build](https://bugs.openjdk.org/browse/JDK-8333301?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aworklog-tabpanel)
Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/836

JDK24 adds JVM_IsStaticallyLinked(void)

---

buildenv/jenkins/variables/defaults.yml

Cherry-pick https://github.com/eclipse-openj9/openj9/pull/20098 for the 0.46.1 release.

(0.46.1) Update to openssl 3.0.15

---

buildenv/jenkins/variables/defaults.yml

Cherry-pick https://github.com/eclipse-openj9/openj9/pull/20098 for the 0.47 release.

(0.47.0) Update to openssl 3.0.15

---

buildenv/jenkins/variables/defaults.yml

Cherry-pick https://github.com/eclipse-openj9/openj9/pull/20098 for the 0.48 release.

(0.48.0) Update to openssl 3.0.15

---

runtime/compiler/env/j9method.cpp

...for consistency with other private methods and generally other methods that don't appear in the vtable. Previously the vtable slot would have been `J9VTABLE_INVOKE_PRIVATE_OFFSET`.

Set TR_ResolvedMethod vtable slot to zero for private invokevirtual

---

runtime/j9vm/jvm.c

1. Revert #https://github.com/eclipse-openj9/openj9/pull/20014.
2. Fix compile error that origLibpath is not defined on z/OS Java 21.
3. Call iconv_init() in JNI_CreateJavaVM_impl() before the first use of
getenv() on z/OS.
[Internal issue](https://github.ibm.com/runtimes/openj9-openjdk-jdk21-zos/issues/299)

Fix compile error and add iconv_init() call

---

jcl/src/java.base/share/classes/java/lang/Access.java

JDK24 adds `JavaLangAccess.concat(String, Object, String)`
Resolve JDK next compilation error:
```
03:42:20  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:70: error: Access is not abstract and does not override abstract method concat(String,Object,String) in JavaLangAccess
03:42:20  final class Access implements JavaLangAccess {
```

JDK24 adds JavaLangAccess.concat(String, Object, String)

---

runtime/compiler/runtime/SymbolValidationManager.cpp

If the option TR_IgnoreAssert is enabled for a particular compilation and the environment variable TR_svmAssertionsAreFatal is not set, SVM assertions will now be non-fatal even in DEBUG or PROD_WITH_ASSUMES builds. This matches the behaviour of normal TR_ASSERT assertions, aside from the possibility of overriding TR_IgnoreAssert with that environment variable.

Allow SVM assertions to be ignored

---

runtime/compiler/control/CompileBeforeCheckpoint.cpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/runtime/CRRuntime.cpp
runtime/compiler/runtime/CRRuntime.hpp

If debug is specified on restore, ensure that any proactively compiled
JNI Methods are reset to their original address.
JNI methods are not compiled under FSD, but they are compiled
proactively in the checkpoint hook. However, if debug is specified on
restore, all proactively compiled methods, except for JNI thunks, get
invalidated. Thus, the extra field of the J9Method of a JNI method
needs to get reset to whatever the VM initialized them to originally.
This is necessary to ensure an environment that is consistent with FSD
mode. The invalidation of proactively compiled non-JNI methods (which
are non-FSD bodies) ensure that non-FSD code does not execute
post-restore. At the checkpoint hook, only FSD bodies are on the stacks
of the threads; although the compiler currently does not reuse …

Reset JNI Addresses if FSD on restore

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9method.h
runtime/compiler/optimizer/InterpreterEmulator.cpp

...in `TR_ResolvedMethod`.
Additionally:
- Delete commented code in `vTableSlot()`.
- Remove `TR_ResolvedRelocatableJ9Method::virtualCallSelector()`. This override just forwarded to the base implementation.
- Stop using `virtualCallSelector()` to determine the vtable slot to pass to the constructor when instantiating `TR_J9MutableCallSite`. Instead just pass -1 like we do for other call sites that don't use the slot.

Remove unused cpIndex parameter of vTableSlot(), virtualCallSelector()

---

runtime/compiler/control/CompileBeforeCheckpoint.cpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/runtime/CRRuntime.cpp
runtime/compiler/runtime/CRRuntime.hpp

If debug is specified on restore, ensure that any proactively compiled JNI Methods are reset to their original address.
JNI methods are not compiled under FSD, but they are compiled proactively in the checkpoint hook. However, if debug is specified on restore, all proactively compiled methods, except for JNI thunks, get invalidated. Thus, the extra field of the J9Method of a JNI method needs to get reset to whatever the VM initialized them to originally.
This is necessary to ensure an environment that is consistent with FSD mode. The invalidation of proactively compiled non-JNI methods (which are non-FSD bodies) ensure that non-FSD code does not execute post-restore. At the checkpoint hook, only FSD bodies are on the stacks of the threads; although the compiler currently does not reuse …

Reset JNI Addresses if FSD on restore (0.48)

---

runtime/compiler/optimizer/J9TransformUtil.cpp

It's true that final methods of `Object` and private methods are not in the vtable and must be dispatched directly even though they're called using `invokevirtual`. However, those methods won't be encountered here because the `MemberName` would be of kind `MH_REF_INVOKESPECIAL`, and the dispatch would be carried out by `linkToSpecial()`.

Remove outdated comment and logic from refineMethodHandleLinkTo()

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

When inlining `Unsafe.compareAndSwap` (`compareAndSet`) while using OffHeap ignore the special callers cases which skips generating checks for inlining.
The special callers require OffHeap array checks but no low-tag checks, the different treatment of that will be coded into `createUnsafeCASCallDiamond` later on.

Generate checks for all callers in OffHeap when inlining Unsafe.CAS

---

runtime/oti/j9.h
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/FastJNI_java_lang_Class.cpp
runtime/vm/createramclass.cpp
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java

- Don't set J9ClassHasIdentity for interfaces
- Update Object.isIdentity to match ri
Discussed with @a7ehuo and we decided the clearest meaning for J9ClassHasIdentity is to exclude interfaces fyi @hangshao0

J9ClassHasIdentity should not be set for interfaces

---

runtime/compiler/optimizer/J9RecognizedCallTransformer.hpp

This method no longer generates any control flow. Instead it generates an unconditional virtual dispatch using `dispatchVirtual()`. Update the doc comment for consistency with 425a1f1da0, 830016e675, and fc9e39d53f.

Correct outdated linkToVirtual() J2I-avoidance transformation comment

---

runtime/oti/j9.h
runtime/vm/classsupport.c
runtime/vm/createramclass.cpp

Always create a nullable array before a null-restricted array to better align with JIT assumptions that the nullable array should exist. See discussion https://github.com/eclipse-openj9/openj9/issues/19914#issuecomment-2311388833
I also defined J9CLASS_GET_NULLRESTRICTED_ARRAY outside of J9VM_OPT_VALHALLA_FLATTENABLE_VALUE_TYPES for JIT use https://github.com/eclipse-openj9/openj9/pull/20112#discussion_r1750553860
fyi @a7ehuo 
Related to https://github.com/eclipse-openj9/openj9/issues/17340

Always create nullable array before null-restricted

---

jcl/src/java.base/share/classes/java/lang/Access.java

JDK24 `JavaLangAccess` adds `stringCoder()/virtualThreadDefaultScheduler()`
Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/839

JDK24 JavaLangAccess adds stringCoder()/virtualThreadDefaultScheduler()

---

test/functional/cmdLineTests/criu/playlist.xml

Reverts eclipse-openj9/openj9#18469
related: https://github.com/eclipse-openj9/openj9/issues/18468

Revert "CRIU disable tests on ppc64le platform temporarily"

---

runtime/vm/JFRChunkWriter.cpp
runtime/vm/JFRChunkWriter.hpp
runtime/vm/JFRConstantPoolTypes.hpp
runtime/vm/j9vm.tdf
runtime/vm/jfr.cpp

Add support for:
- PhysicalMemory
- CPUInformation
- OSInformation
- VirtualizationInformation

More JFR events support

---

doc/release-notes/0.47/0.47.md

Created 0.47.0 release note and updated with the available content specific to 0.47.0 release.
[skip ci]

0.47.0 release note

---

buildenv/jenkins/common/build.groovy

It checks for `centos7_build_image_cuda` image existance on the node locally and only create it when can not find the image on it. related: #infra-9829

resolves the fill of space due to docker images pile up

---

runtime/oti/UnsafeAPI.hpp

Backport of https://github.com/eclipse-openj9/openj9/pull/20141

(0.48) Use unsigned indexes for unsafe array access

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

Add a NULL test to the sequence of runtime tests performed before calling `Unsafe.compareAndSwap()` to ensure that when offheap is enabled, we don't try to load `dataAddr` from a NULL reference.

Generate runtime NULL test for Unsafe.compareAndSwap()

---

runtime/bcutil/ROMClassBuilder.cpp
runtime/oti/j9javaaccessflags.h
runtime/shared_common/OSCache.hpp

Taking over from https://github.com/eclipse-openj9/openj9/pull/19637
Documentation  update: https://github.com/eclipse-openj9/openj9-docs/issues/1406

Add flag to indicate if ROMclass is from SCC

---

runtime/include/jni.h.m4
runtime/j9vm/j7vmi.c
runtime/j9vm/jvm.c
runtime/redirector/redirector.c
runtime/vm/jnimisc.cpp
runtime/vm/jvminitcommon.c

See also [openjdk](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/76f4981979e23822e3c1caaae3037c1e15942418/src/java.base/share/native/include/jni.h#L2005).

Add and support JNI_VERSION_24 for Java 24+

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp

This commit fixes build errors with J9CLASS_DEPTH() in java_lang_invoke_MethodHandleNatives.cpp.
Fixes: #20170

Fix "statement has no effect" with J9CLASS_DEPTH()

---

jcl/src/java.base/share/classes/java/lang/System.java
test/functional/cmdline_options_testresources/src_90/com/ibm/j9/getcallerclass/ReflectionMHTests.java

In JEP 416, core reflection was re-implemented with Method Handles with the purpose of simplifying adding new language features. While analyzing performance of workload based on large enterprise based application, I observed that this was causing visible performance degradation. Disabling the use of direct method handles for reflection calls while we are working on improving the performance with direct method handles.

Disable use of method handle for core reflection in JDK21

---

runtime/compiler/optimizer/J9Optimizer.cpp

If Simplifier detects trivial conditional branches where the fallthrough
block is a goto block to the branch target it can remove said branches
and leave behind a goto block. The resulting CFG can then potentially
be cleaned up by RedundantGotoElimination. Running these two opts
before BlockSplitter allows these trivial conditional branches to be
completely optimized away before BlockSplitter gets a change to run and
potentially duplicate blocks that hide the opportunity and make it
harder to detect and eliminate later.
This PR inserts Simplifer and RedundantGotoElimination passes before
BlockSplitter and moves all 3 after VP, which typically detects
opportunities that result in dead code, which when removed, results
in the trivial conditional branches that we're interested in.
This PR is …

Add extra Simplifier & gotoElim passes to warm/hot

---

debugtools/DDR_VM/src/com/ibm/j9ddr/CompatibilityConstants29.dat
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/ValueTypeHelper.java

Remove DDR uses of J9ClassIsPrimitiveValueType

---

test/functional/cmdLineTests/xxargtest/XXArgumentTesting.xml
test/functional/cmdLineTests/xxargtest/XXArgumentTesting_j9.xml
test/functional/cmdLineTests/xxargtest/playlist.xml

Move j9 specific subtests to XXArgumentTesting_j9
Closes: #19966

Fix testXXArgumentTesting

---

test/functional/cmdLineTests/xxargtest/XXArgumentTesting.xml
test/functional/cmdLineTests/xxargtest/XXArgumentTesting_j9.xml
test/functional/cmdLineTests/xxargtest/playlist.xml

Cherry-pick 4a6636a98f561cba48425d88357af63fa0460030
Move j9 specific subtests to XXArgumentTesting_j9
Issues: #19966

(v0.48.0) Fix testXXArgumentTesting

---

runtime/nls/shrc/j9shr.nls
runtime/oti/j9nonbuilder.h
runtime/shared_common/include/SCQueryFunctions.h
runtime/shared_common/shrinit.cpp
runtime/util/hshelp.c
runtime/vm/exceptiondescribe.c

Create a hash table and access mutex to cache romClass to ramClass mappings from exceptiondescribe.c:findJ9ClassForROMClass. This saves time iterating over multiple class loaders to find a ram class. Entries will be deleted when a class is unloaded or redefined.
Port from https://github.com/eclipse-openj9/openj9/pull/20169

(0.48) Cache rom to ram mappings for exception backtrace

---

runtime/gc_structs/ClassLoaderClassesIterator.cpp
runtime/gc_structs/ClassLoaderClassesIterator.hpp

- Do proper initialization of state machine before use it for walk.
- Move check that list is switched to super Classloader to proper place to cancel walk on individual list, not for all lists.
relates to https://github.com/eclipse-openj9/openj9/issues/20150

Fix array lists walk in ClassLoaderClasses Iterator

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/ras/kca_offsets_generator.cpp
runtime/compiler/runtime/J9ValueProfiler.hpp

In order to allow `OMR_WARNINGS_AS_ERRORS` to be enabled across the JIT, disable `-Winvalid-offsetof` while [work is done](https://github.com/eclipse-openj9/openj9/issues/18328) to refactor relevant classes to be standard-layout type so offsetof can be used without crashing the build on AIX.

Disable -Winvalid-offsetof in J9Options, kca_offsets_generator, J9ValueProfiler

---

jcl/src/java.base/share/classes/java/lang/System.java
test/functional/cmdline_options_testresources/src_90/com/ibm/j9/getcallerclass/ReflectionMHTests.java

Given that switching to old reflection was causing a functional issue
when trying to use Virtual Thread, I am opening up this PR to revert it
back. See https://github.com/eclipse-openj9/openj9/issues/20200 for more
details.
Reverts https://github.com/eclipse-openj9/openj9/pull/20159

Revert changes that disables use of Method Handle for core reflection

---

runtime/compiler/control/J9Options.cpp

Revert part of a change to add GCC and Clang directives disabling `-Winvalid-offsetof` warnings in `J90ptions`, `kca_offsets_generator`, and `J9ValueProfiler`, because there was no warning in `J9Options`
Partially reverts #18313

Remove no-op disable of -Winvalid-offsetof in J9Options

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.cpp
runtime/compiler/net/MessageTypes.hpp
runtime/compiler/optimizer/InterpreterEmulator.cpp
runtime/compiler/optimizer/J9EstimateCodeSize.cpp
runtime/compiler/optimizer/J9TransformUtil.cpp

This changeset enables inlining of SegmentViewVarHandle operations
that have been introduced in JDK21 through the following:
* ~Enable static final field folding for field types involved in such
VarHandle operations: ValueLayout, ValueLayouts, MemorySegment~
* Add recognized method info for
ValueLayouts$AbstractValueLayout.accessHandle and MemorySegment methods
* Add VM API getLayoutVarHandle to obtain the layout VH object info
* Add getReturnValue handler in InterpreterEmulator to evaluate the
result of accessHandle()
* During ECS, set NeedsPeekingHeuristics to true for the caller of
MemorySegment methods so that the final field loads in the caller
that are relevant for obtaining the layout VH can be folded.
* Finally, ECS now sets MemorySegment methods to iterate with
state in the …

Inline SegmentViewVarHandle operations in JDK21+

---

.gitattributes

This PR tags below file as binary
https://github.com/eclipse-openj9/openj9/blob/master/test/functional/cmdLineTests/jvmtitests/jars/test.fil

Tag test.fil file as binary

---

buildenv/jenkins/common/variables-functions.groovy

Run functional and openjdk test buckets for sanity keyword.
Continue to run functional for extended keyword.

Add openjdk test group to 'sanity' keyword for PR builds

---

runtime/shared_common/shrinit.cpp
runtime/util/hshelp.c

- Declare variables first in romToRam entry removal
- Correctly free romToRam hash table and mutex
https://github.com/eclipse-openj9/openj9/pull/20169#discussion_r1766925674
Port to 0.48: https://github.com/eclipse-openj9/openj9/pull/20197

romToRam cache follow up

---

runtime/shared_common/shrinit.cpp
runtime/util/hshelp.c

Port from https://github.com/eclipse-openj9/openj9/pull/20196

(0.48) romToRam cache follow up

---

test/functional/cmdLineTests/criu/playlist.xml

related:https://github.ibm.com/runtimes/backlog/issues/1525

Remove CRIU required in cmdLineTester_criu_jitserverAcrossCheckpoint

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/runtime/CRRuntime.cpp
runtime/compiler/runtime/CRRuntime.hpp
test/functional/cmdLineTests/criu/criu_jitPostRestore.xml

https://github.com/eclipse-openj9/openj9/pull/19754 adds VM Support for Debug On Restore. As the code stands, this will result in the JIT invalidating all code post-restore because it is unable to distinguish between FSD mode caused by the VM or the user.
This PR fixes this by adding the following changes:
* Cache the status of certain runtime events
* Return early from isFSDNeeded under `-XX:+DebugOnRestore`
Depends on https://github.com/eclipse-openj9/openj9/pull/19754 (specifically the update to the `isDebugOnRestoreEnabled` API).

Ensure JIT/AOT code is not invalidated post-restore under `-XX:+DebugOnRestore`

---

runtime/port/common/j9prt.tdf

It was j9mem, which seems a copy/paste error, it should be j9hypervisor.

Fix the group for tracepoint Trc_PRT_j9hypervisor_vendor_init_exit

---

runtime/gc_base/ClassLoaderManager.hpp

ROM class for Anonymous class might be stored in Shared Classes Cache. Such ROM class can not be unloaded, so skip an attempt.

Skip unloading of ROM class for Anonymous if it is in SCC

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/runtime/CRRuntime.cpp
runtime/compiler/runtime/IProfiler.cpp
runtime/gc_modron_startup/mminit.cpp
runtime/gc_modron_startup/mmparseXgcpolicy.cpp
runtime/jcl/common/criu.cpp
runtime/jcl/common/system.c
runtime/jcl/unix/syshelp.c
runtime/jvmti/jvmtiCapability.c
runtime/jvmti/jvmtiHook.c
runtime/jvmti/jvmtiStartup.c
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/shared_common/shrinit.cpp
runtime/vm/CRIUHelpers.cpp
runtime/vm/intfunc.c
runtime/vm/jvminit.c
runtime/vm/lookuphelper.c
runtime/vm/vmhook.c

Refactor a few CRIU APIs to take `J9JavaVM*` instead of `J9VMThread*`
The currentThread passed into `isCRaCorCRIUSupportEnabled(J9VMThread*)`, `isCheckpointAllowed(J9VMThread*)` and
`isDebugOnRestoreEnabled(J9VMThread*)` are just for redirection of `currentThread->javaVM`, changed the APIs to take `J9JavaVM*` directly.
Related to 
* https://github.com/eclipse-openj9/openj9/pull/20202#discussion_r1768809654
Note: there are other CRIU APIs that could also take `J9JavaVM*` instead of `J9VMThread*`, only those related to https://github.com/eclipse-openj9/openj9/pull/20202 are refactored here.

Refactor a few CRIU APIs to take J9JavaVM* instead of J9VMThread*

---

runtime/compiler/ilgen/Walker.cpp

When stashing arguments for OSR at an `invokedynamic` or `invokehandle` bytecode instruction, the callee usually has an extra parameter (the appendix, if it's non-null). If the call is unresolved, it expects two extra parameters instead (the appendix and a `MemberName`). For the purpose of stashing, these are all ignored because they're not on the stack just prior to running the invoke bytecode instruction. However, in these cases `stashArgumentsForOSR()` has been ignoring the top one or two elements of the stack as well, as though the extra arguments were already pushed. However, they haven't actually been pushed at this point, so we would simply fail to stash the last one or two regular arguments. Failure to stash could cause stack slots to appear falsely to be dead, and they could …

Stash all invokedynamic and invokehandle arguments for OSR

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/ilgen/Walker.cpp

...instead of in the caller.
This method is also called from `stashArgumentsForOSR()`, which neglected to set the flag. Because the flag wasn't set, the symbol reference was available for reuse, and it would be reused even if the `invokehandle` instruction became resolved before `genInvokeHandle()`. In that case, `genInvokeHandle()` would see `isUnresolved=false`, so it would push only the appendix (if non-null), but then it would get the dummy `linkToStatic` symbol reference, which expects more arguments.
This flag is now set in `findOrCreateHandleMethodSymbol()`. There's no reason to allow a caller to forget to set the flag.

Set dummy resolved method flag in findOrCreateHandleMethodSymbol()

---

runtime/rastrace/trcmain.c

This commit fixes a build error with runtime/rastrace/trcmain.c.
Fixes: #20171

Fix "storing the address of local variable" in trcmain.c

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

Using `hasSymbolReference()` to check for the existence of a symref before calling `getSymbolReference()` to avoid the assertion in `getSymbolReference()` (`self()->hasSymbolReference()`) being triggered.

Check the SymbolReference in the Inliner Before Accessing It

---

runtime/compiler/aarch64/codegen/ARM64JNILinkage.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit replaces the use of magic numbers for the limitation immediate for dmb instructions with the `AArch64BarrierLimitation` enum.
NOTE: Requires coordinated merge with https://github.com/eclipse/omr/pull/7465

AArch64: Use dmb limitation enum

---

runtime/compiler/runtime/RelocationRuntime.cpp
runtime/gc_modron_startup/mminit.cpp

It is the 2nd time I am doing this. Previously, it was reverted due to a performance regression due to incompatible AOT code. In fact, AOT code (generated on running multiple CPUs) are actually compatible. So, SCC loading check is changed to accommodate this specific combination.
Previous commit message: There is little expected benefit with concurrentmark if you are running on a single-CPU machine/environment. On the other hand, you could gain some benefits with noConcurrentMark: 1) no interference from background marking thread; 2) shorter write-barrier path-length: for certain workloads, this provides substantial performance benefits (e.g. Spark TPC-DS q72 in particular).

Treat single CPU as if -XnoConcurrentMark were set

---

runtime/compiler/runtime/SymbolValidationManager.cpp
runtime/compiler/z/codegen/InMemoryLoadStoreMarking.cpp
runtime/compiler/z/codegen/InMemoryLoadStoreMarking.hpp
runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp
runtime/compiler/z/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/S390J9CallSnippet.cpp
runtime/compiler/z/codegen/S390PrivateLinkage.cpp

Suppresses warnings when building on OpenXL
Warnings:
- uninitialized variables
- C++ 11 ISO does not allow conversion from string literal to char *
- unused statements
- assignments inside if clause
- unhandled enums in switch
R29 build: https://hyc-runtimes-jenkins.swg-devops.com/job/jvm.29.personal/34216/

Warnings Cleanup

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

Changed the numDeps parameter so that it is always greater or equal to the number of post conditions added. Avoiding the assertion `TR_ASSERT(newCursor <= _numPostConditions, "Too many dependencies");` being triggered.

Prevent Assertion Fail Caused by Incorrect numDeps

---

test/functional/cmdLineTests/criu/playlist.xml

related:https://github.com/eclipse-openj9/openj9/issues/20243

Exclude cmdLineTester_criu_jitserverAcrossCheckpoint for jdk8

---

runtime/bcutil/cfreader.c
runtime/bcverify/staticverify.c
runtime/oti/bcverify_api.h
runtime/verutil/chverify.c
runtime/vm/resolvesupport.cpp

This is from an old value types specification for ReferenceType which is no longer in use https://cr.openjdk.org/~dlsmith/jep401/jep401-20211220/specs/primitive-classes-jvms.html#jvms-4.3.2. 

Remove old ReferenceType error handling for value types

---

runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/control/OptionsPostRestore.hpp
runtime/nls/jitm/j9jit.nls

Post-Restore, the `AOT load and compilation disabled post restore.` can be printed out either because AOT was disabled due to options/factors pre-checkpoint or options/factors post-restore. This PR adds a new NLS message to distinguish between these two scenarios.
https://github.com/eclipse-openj9/openj9/issues/20233

Distinguish why AOT is disabled post-restore

---

runtime/compiler/ilgen/Walker.cpp

This is a cherry-pick of #20232 for 0.48.
Fixes #19369

(0.48) Stash all invokedynamic and invokehandle arguments for OSR

---

runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/control/OptionsPostRestore.hpp
runtime/nls/jitm/j9jit.nls

Post-Restore, the `AOT load and compilation disabled post restore.` can be printed out either because AOT was disabled due to options/factors pre-checkpoint or options/factors post-restore. This PR adds a new NLS message to distinguish between these two scenarios.
Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/20241
Fixes https://github.com/eclipse-openj9/openj9/issues/20233

(0.48) Distinguish why AOT is disabled post-restore

---

runtime/gc_modron_startup/mmparseXgc.cpp
test/functional/cmdLineTests/gcsuballoctests/gcsuballoctests.xml

1. Use VMEM_ALLOC_QUICK by default for allocateRegion in allocate_memory32
2. Adds -Xgc:suballocatorQuickAllocDisable option that disables the default VMEM_ALLOC_QUICK
3. Adds -Xgc:suballocatorIncrementSize option that replaces the HEAP_SIZE_BYTES macro and controls the heap increment size
4. Adds sanity.functional tests
Addresses: https://github.com/eclipse/omr/issues/7190
Depends on: https://github.com/eclipse/omr/pull/7472

Add Xgc options for suballocator heap size and quick allocation

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

When using the node in a null or low-tag check blocks we need to duplicate the node as the node itself may still be used in the callNode/callTree and refCount won't be correct for the new block.

Fix inline Unsafe CAS reference count

---

runtime/jvmti/jvmtiStartup.c

`-agentpath:` libraries require no path/name decoration
The agent library specified via `-agentpath:` has an absolute path/name, it should not be decorated again during the agent library loading;
For `-agentpath:` option in the restore option file, compare the actual platform-dependent library name.
Related
* https://github.com/eclipse-openj9/openj9/pull/19754
closes https://github.com/eclipse-openj9/openj9/issues/20194

-agentpath: libraries require no path/name decoration

---

runtime/vm/CRIUHelpers.cpp
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/TimeChangeTest.java

There is a race condition on the existence of the `criu restore` process and retrieving its start time, when `--restore-detached` is passed to `criu restore`. This patch restrict retrieving the process start time to restoring via CRaC which is not affected.
Issues: eclipse-openj9/openj9#20214

Restrict getting the restore process start time to CRaC API

---

runtime/oti/xhelpers.m4

* remove `.arch` directive
* add `.section .note.GNU-stack,"",@progbits` at end of file
Fixes: #20274.
Also tested internally in build 79030.

Fix x86 assembly source issues with gcc 13

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/runtime/CRRuntime.cpp
runtime/compiler/runtime/CRRuntime.hpp

https://github.com/eclipse-openj9/openj9/pull/19754 adds VM Support for Debug On Restore. As the code stands, this will result in the JIT invalidating all code post-restore because it is unable to distinguish between FSD mode caused by the VM or the user.
This PR fixes this by adding the following changes:
* Cache the status of certain runtime events
* Return early from isFSDNeeded under `-XX:+DebugOnRestore`
Depends on https://github.com/eclipse-openj9/openj9/pull/20191

(0.48) Ensure JIT/AOT code is not invalidated post-restore under `-XX:+DebugOnRestore`

---

runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/decompResolveFrame/decomp003.c
runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/decompResolveFrame/decomp005.c
runtime/tests/port/j9vmemTest.c
runtime/vm/CMakeLists.txt
runtime/vm/jvminit.c

runtime/tests/jsig/main.c : dlfcn.h needs to be defined before defines for dllfree()/dllload() due to conflicting type definitions decomp003.c/decomp005.c : strcasecmp() implict function declaration needs strings.h j9vmemTest.c : -Wimplicit-int , missing type specifier that defaults to "int"
jvminit.c : atoe_enableFileTagging() implicit function declaration requires atoe.h
runtime/vm/CMakeLists.txt : Added appropriate conditionals to apply correct flags for Open XL suggested by compiler team. Hooks are not implemented for Open XL.

Open XL header includes and vm flag fixup

---

runtime/oti/xhelpers.m4

* remove ".arch" directive
* add .section .note.GNU-stack,"",@progbits at end of file
This is a replay of #20278 and #20284 for the 0.48 release.

(0.48) Fix x86 assembly source issues with gcc 13

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/runtime/CRRuntime.cpp
runtime/compiler/runtime/IProfiler.cpp
runtime/gc_modron_startup/mminit.cpp
runtime/gc_modron_startup/mmparseXgcpolicy.cpp
runtime/jcl/common/criu.cpp
runtime/jcl/common/system.c
runtime/jcl/unix/syshelp.c
runtime/jvmti/jvmtiCapability.c
runtime/jvmti/jvmtiHook.c
runtime/jvmti/jvmtiStartup.c
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/shared_common/shrinit.cpp
runtime/vm/CRIUHelpers.cpp
runtime/vm/intfunc.c
runtime/vm/jvminit.c
runtime/vm/lookuphelper.c
runtime/vm/vmhook.c

The agent library specified via `-agentpath:` has an absolute path/name, it should not be decorated again during the agent library loading;
For `-agentpath:` option in the restore option file, compare the actual platform-dependent library name.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/20202
The currentThread passed into `isCRaCorCRIUSupportEnabled(J9VMThread*)`, `isCheckpointAllowed(J9VMThread*)` and
`isDebugOnRestoreEnabled(J9VMThread*)` are just for redirection of `currentThread->javaVM`, changed the APIs to take `J9JavaVM*` directly.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/20205
Note: these two PRs were in last night's builds, and no failure seems related to those changes.
In addition, there were merging conflicts, verified in a personal build …

(0.48) -agentpath: libraries require no path/name decoration & Refactor a few CRIU APIs to take J9JavaVM* instead of J9VMThread*

---

jcl/src/java.base/share/classes/java/lang/System.java

Attempt to reload the library in case of `UnsatisfiedLinkError`
When an `UnsatisfiedLinkError` is thrown because the library was already loaded in another classloader, run `gc()` to unload the unreachable classloaders, and reload the library again.
Java 8/11 `UnsatisfiedLinkError` message `already loaded in another classloader` is from
https://github.com/eclipse-openj9/openj9/blob/0027b8193413e99fd9747ddbd84750ffc14ba4d1/runtime/vm/vmbootlib.c#L518-L519
Java 17+ is from https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/4a311794a42998359c859814c645398be928e19a/src/java.base/share/classes/jdk/internal/loader/NativeLibraries.java#L206-L209
```
// cannot be loaded by other class loaders
if (loadedLibraryNames.contains(name)) {
throw new UnsatisfiedLinkError("Native Library " + name +
" …
```

Attempt to reload the library in case of UnsatisfiedLinkError

---

runtime/vm/rasdump.c

```
openj9/runtime/vm/rasdump.c:652:8: warning: unused variable 'fd'
[-Wunused-variable]
14:20:44    652 |         IDATA fd = -1;
14:20:44        |               ^~
```

Remove unused variable on AIX in rasdump.c

---

runtime/oti/j9.h
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/createramclass.cpp
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeSystemArraycopyTests.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeUnsafeTests.java

Update ValueTypeUnsafeTests  tests to use flattenable array.
Update ValueTypeSystemArraycopyTests to test System.arrayCopy
between nullable and null-restricted arrays.
Fixes: https://github.com/eclipse-openj9/openj9/issues/20223
Fixes: https://github.com/eclipse-openj9/openj9/issues/20253

Remove flattening flag from nullable arrays

---

jcl/src/java.base/share/classes/java/lang/JFRHelpers.java
jcl/src/java.base/share/classes/java/lang/System.java
runtime/jcl/common/jdk_jfr_internal_JVM.cpp
runtime/jcl/exports.cmake
runtime/jcl/uma/jfr_exports.xml

This PR does the bare minimum to enable JFR logging capabilities for debugging purposes. Full support will be addded in a later PR.
Also, fix the JNI method signatures

Implement initial logging JNI natives

---

jcl/src/java.base/share/classes/java/lang/System.java

Attempt to reload the library in case of `UnsatisfiedLinkError`
When an `UnsatisfiedLinkError` is thrown because the library was already loaded in another classloader, run `gc()` to unload the unreachable classloaders, and reload the library again.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/20265

(0.48) Attempt to reload the library in case of UnsatisfiedLinkError

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp

Adds support for the following recognized methods:
```
CompareAndExchangeObject     //JDK11
CompareAndExchangeReference  //JDK17,21
CompareAndExchangeInt        //JDK11,17,21
CompareAndExchangeLong       //JDK11,17,21
```
Similar to their CompareAndSet counterparts, the JIT acceleration does not support CAE on static fields so the createUnsafeCASCallDiamond function was updated to also work on the CAE methods.
The accelerated CAE code was built on top of the existing accelerated CAS support on both Power and X.
Edit:
X changes are dependent on this OMR PR:
https://github.com/eclipse/omr/pull/7438
Behavior of `inlineCompareAndSwapNative` and `inlineCompareAndSwapObjectNative` in `J9TreeEvaluator.cpp` must match behavior in `willBeEvaluatedAsCallByCodeGen` in `OMRCodeGenerator.cpp`

Accelerate Unsafe CAS Intrinsics on Power and X

---

runtime/compiler/env/j9method.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp

`nullptr` is not supported by some supported compilers. So some uses of `nullptr` are now changed to use `NULL` instead.

Changes some uses of nullptr to NULL

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java

CRIU adds `@NotCheckpointSafe` at `ClassLoader.getClassLoadingLock()`
This is expected to address 
```
[err] openj9.internal.criu.JVMRestoreException: Blocking operation is not allowed in CRIU single thread mode.
[err]   at java.base/java.lang.ClassLoader.getClassLoadingLock(ClassLoader.java:1270)
[err]   at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:837)
[err]   at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:825)
[err]   at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[err]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1093)
[err]   at com.ibm.ws.kernel.internal.classloader.JarFileClassLoader._loadClass(JarFileClassLoader.java:172)
[err] …
```

CRIU adds @NotCheckpointSafe at ClassLoader.getClassLoadingLock()

---

runtime/jcl/common/getstacktrace.c

If `inspectorCount` is `-1`, then the virtual thread is in an unsteady
state (mounting or unmounting). In such cases, `NULL` should be returned
and the JCL code should retry in order to avoid unexpected behavior.
Related: #18910

Return NULL from getStackTraceForThread for unsteady virtual threads

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java

CRIU adds `@NotCheckpointSafe` at `ClassLoader.getClassLoadingLock()`
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/20303

(0.48) CRIU adds @NotCheckpointSafe at ClassLoader.getClassLoadingLock()

---

runtime/jcl/common/getstacktrace.c

If `inspectorCount` is `-1`, then the virtual thread is in an unsteady
state (mounting or unmounting). In such cases, `NULL` should be returned
and the JCL code should retry in order to avoid unexpected behavior.
Backport of #20306
Fixes: #18910

(0.48) Return NULL from getStackTraceForThread for unsteady virtual threads

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
buildenv/jenkins/variables/defaults.yml

Builds for Java 22 are not possible since #20286.

Remove build configuration entries for jdk22

---

runtime/oti/j9nonbuilder.h
runtime/vm/JFRChunkWriter.cpp
runtime/vm/JFRChunkWriter.hpp
runtime/vm/JFRConstantPoolTypes.cpp
runtime/vm/JFRConstantPoolTypes.hpp
runtime/vm/jfr.cpp

JFR timestamps are calculated in the following manner.
timestamp = chunkStartTime + (jfrTicks - chunkStartTicks)
The reason the data seemed sensible is because we always made the chunkStartTicks zero in the chunk header, so the relative difference in the millisecond time entries made some sense, but this was incorrect.

Update jfr time calculations

---

test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java

Related to https://github.com/eclipse-openj9/openj9/pull/20290#pullrequestreview-2348438875

Remove unnecessary casting

---

runtime/oti/VMHelpers.hpp
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java

Fixes: https://github.com/eclipse-openj9/openj9/issues/20305

Nullable array class cannot be cast to null-restricted

---

runtime/codert_vm/CodertVMHelpers.cpp

Acquire classTableMutex when traversing sub class links
Fixes: #20257

Acquire classTableMutex when traversing sub class links

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/j9method.h
runtime/compiler/env/j9methodServer.hpp
runtime/compiler/ilgen/Walker.cpp
runtime/compiler/net/CommunicationStream.hpp

Support unresolved dispatch of invokeHandle/invokeDynamic for SVM AOT
compilations. No additional relocation/validation records are needed as
the method type table entry / callsite entry addresses are not emitted
in the generated code. Additionally, the polymorphic signature of the
dummy linkToStatic resolved method is entirely determined by the callee
and thus the combination of the callee's SVM ID and Class Chain
validations are sufficient to validate the polymorphic signature.
Depends on https://github.com/eclipse/omr/pull/7475

Add SVM AOT support for unresolved invokeHandle/invokeDynamic dispatch

---

runtime/compiler/env/VMJ9.cpp

A `VarHandle` can be initialized such that its access mode method invocation behaves like a `MethodHandle.invokeExact` invocation. We can check if this is the case by checking whether the `VarHandle.exact` field was set to true. In such a case, an additional check is necessary, where we need to verify whether `AccessDescriptor.symbolicMethodTypeExact` field matches the corresponding entry in the `MethodType` table, failing which the JIT should abort trying to lookup the `MethodHandle` table.
The `MethodType` table would only be initialized for a `VarHandle` if the `VarHandle.exact` field was initialized as true. Therefore, by moving the check for whether the `MethodType` table is valid to occur only after we confirm that the `VarHandle` has `invokeExact` behaviour, we prevent prematurely …

Check for VarHandle's MethodType table only when necessary

---

jcl/src/java.base/share/classes/java/lang/Class.java

This method has been removed from the latest valuetypes extensions repository.
Fixes: https://github.com/eclipse-openj9/openj9/issues/13695

Remove Class.asNullRestrictedType

---

test/functional/Java22andUp/playlist.xml

These tests were previously disabled due to the valuetypes extensions repository being out of date.
The tests are now passing https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/44071/
Fixes: https://github.com/eclipse-openj9/openj9/issues/18583
fyi @JasonFengJ9

Enable Jep454Tests for valhalla builds

---

runtime/compiler/runtime/RelocationRecord.cpp

The ordered pair variant of `TR_RelocationRecordClassAddress::applyRelocation` now correctly gets its old constant pool pointer for generating the new constant pool pointer.
Fixes #15696

TR_RelocationRecordClassAddress Relocates Correctly with Ordered Pair

---

runtime/jcl/common/jcltrace.c
runtime/jvmti/jvmtiModules.c
runtime/jvmti/jvmtiThread.cpp
runtime/vm/classloadersearch.c

Avoid the expense of creating a JNI reference when it's not needed.

Use ExceptionCheck() instead of ExceptionOccurred() where appropriate

---

doc/compiler/jitserver/Usage.md

Update the docs of JITServer AOT Cache to remove the 'experimental' wording and clarify the usage on the client side.

Update the JITServer AOT Cache Doc

---

runtime/compiler/runtime/IProfiler.cpp

Before this commit, the interpreter profiler was not collecting data on switches during 'classLoadPhase'. This was done to reduce the overhead of interpreter profiler. However, we have seen cases where, for some methods compiled during 'classLoadPhase' there is no profiling data for some hot switches, making the compiler to infer the wrong block frequencies.
This commit always collects information for switches. We can afford to do so because:
1. Typically switches are not that frequently executed compared to branches
2. When using the shared class cache (SCC), IProfiler is turned off during start-up, relying on profiling info stored in SCC in the cold run.

Always profile switches in interpreter profiler

---

runtime/compiler/runtime/IProfiler.cpp
runtime/compiler/runtime/IProfiler.hpp

The code that retrieves IProfiler info from the shared class cache (SCC) first does a check to see whether the data stored is valid. This check is done against `entry->getData()`, but for switches this always returns 0. As a consequence the JVM is never able to retrieve switch IProfiler data from SCC.
This commit adds a new virtual call, `hasData()`, which will be tested instead of `getData()`.
The reason we cannot use `getData()` directly, is that the switch data uses 32 bytes, exceeding the size returned by `getData()` which is only 8 bytes (for 64-bit architectures).

Fix retrieval of switch IProfiler info from SCC

---

runtime/compiler/x/env/J9CPU.cpp

Backport of https://github.com/eclipse-openj9/openj9/pull/20347

(0.48) x86: add option to disable AVX-512

---

runtime/j9vm/java11vmi.c
runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/intfunc.c
runtime/vm/jnimisc.cpp
runtime/vm/stringhelpers.cpp

See https://bugs.openjdk.org/browse/JDK-8338709 and https://bugs.openjdk.org/browse/JDK-8328877.
Truncate length while evaluating length of a `UTF-8` string
- On 32-bit systems, the length is truncated to `UDATA_MAX`.
- For JNI `getStringUTFLength`, the length is truncated to `INT32_MAX`.
Add restrictions while copying a string to `UTF-8` to avoid overflow
- The length is restricted to `UDATA_MAX` to accommodate memory allocation
functions, which take a `UDATA` as the input parameter for length.
- The data is stopped from being written to the `UTF-8` buffer if its
length will be exceeded.

Fix overflow issues

---

runtime/j9vm/java11vmi.c
runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/intfunc.c
runtime/vm/jnimisc.cpp
runtime/vm/stringhelpers.cpp

Backport of https://github.com/eclipse-openj9/openj9/pull/20362
See https://bugs.openjdk.org/browse/JDK-8338709 and https://bugs.openjdk.org/browse/JDK-8328877.
Truncate length while evaluating length of a `UTF-8` string
- On 32-bit systems, the length is truncated to `UDATA_MAX`.
- For JNI `getStringUTFLength`, the length is truncated to `INT32_MAX`.
Add restrictions while copying a string to `UTF-8` to avoid overflow
- The length is restricted to `UDATA_MAX` to accommodate memory allocation
functions, which take a `UDATA` as the input parameter for length.
- The data is stopped from being written to the `UTF-8` buffer if its
length will be exceeded.

(0.48) Fix overflow issues

---

jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/PlatformMBeanProvider.java

New MXBean added upstream in:
* [8338890: Add monitoring/management interface for the virtual thread scheduler](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/7abcfe079c167845df4ee854b451a6319470aee1)
Fixes: https://github.com/eclipse-openj9/openj9/issues/20352

Add support for VirtualThreadSchedulerMXBean

---

runtime/nls/shrc/j9shr.nls
runtime/oti/j9nonbuilder.h
runtime/shared/shrclssup.c
runtime/shared_common/CacheMap.cpp
runtime/shared_common/CacheMap.hpp
runtime/shared_common/CompositeCache.cpp
runtime/shared_common/CompositeCacheImpl.hpp
runtime/shared_common/j9shr.tdf
runtime/shared_common/shrinit.cpp
runtime/shared_common/shrinit.h
test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-6.xml

1. Add a new field in the cache header which is the number of additional
startup hints that are allowed to be stored to the SCC.
2. Add a CML option to adjust this number.
3. Add test cases.
Fixes: https://github.com/eclipse-openj9/openj9/issues/19308

Limit the number of startup hints in SCC

---

runtime/compiler/runtime/IProfiler.cpp

Collection of IProfiler data is done without any form of synchornization due to the high overhead of IProfiler. Thus, we should try to minimize all windows of opportunities for races to appear.
The profiling data for a branch is just a 32-bit entity which encodes two 16-bit counters (taken and not-taken). If incrementing one of these counters would cause an overflow, we will divide both counters by 2 and only then increment the desired counter. This operation is complex and cannot be done atomically without a lock.
In order to minimize the race conditions, this commit reads the value of the 32-bit word containing the 2 counters and performs all the desired operations on this copy of the data before writing it back. Since reading and writing a 32-bit aligned word is atomic on most modern …

Updates to IProfiler branch data collection

---

runtime/gc_base/ReferenceChainWalker.cpp
runtime/gc_base/ReferenceChainWalker.hpp
runtime/gc_include/HeapIteratorAPI.h
runtime/jvmti/jvmtiHeap.c
runtime/jvmti/jvmtiHeap10.c

Added new structure to hold JNI and Stack local referrer data. Update JNI locals found via jniLocalReferences table to be marked as Stack root.
Closes: #18416 

Refactor J9JVMTI_HEAP_EVENT_STACK data parsing

---

jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/PlatformMBeanProvider.java

Not all the required classes are available in https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes; see https://github.com/eclipse-openj9/openj9/pull/20325#issuecomment-2420102508.

Omit VirtualThreadSchedulerMXBean in builds for valuetypes

---

runtime/jcl/common/attach.c
runtime/port/zos390/protect_helpers.c
runtime/rasdump/dmpagent.c
runtime/rasdump/dmpsup.c
runtime/rasdump/javadump.cpp
runtime/redirector/redirector.c

Mostly a collection of missing function declaration fixes and other commonly seen errors/warnings from Open XL compilation.
runtime/jcl/common/attach.c : missing int specifier
runtime/rasdump/dmpagent.c : missing assembly func declarations
runtime/rasdump/dmpsup.c : implicit function declarations
runtime/rasdump/javadump.cpp : implicit function declarations
runtime/redirector/redirector.c : implicit function declarations

Open XL implicit function declaration fixes

---

runtime/compiler/z/codegen/UncommonBCDCHKAddressNode.cpp
runtime/compiler/z/codegen/UncommonBCDCHKAddressNode.hpp

Update BCDCHK uncommoning for off-heap because address node of BCDCHK can be aloadi with single child if off-heap is enabled.

Update BCDCHK uncommoning for off-heap

---

runtime/oti/j9nonbuilder.h
runtime/util/hshelp.c
runtime/vm/createramclass.cpp

OpenJ9 and OpenJDK MethodHandles have differing fields in the class structures. This patch fixes the fields that were not conditionally-included properly, inconsistent, or missing.

Update fields and MethodHandle directives in class structures

---

runtime/shared_common/CompositeCache.cpp

It is possible that we could call getExtraStartupHints() during startup.
Fixes #20370

Remove incorrect assertion

---

runtime/vm/exceptiondescribe.c

Port from https://github.com/eclipse-openj9/openj9/pull/20371
Fixes: https://github.com/eclipse-openj9/openj9/issues/20368

(0.48) Update classloader when cached rom to ram entry is found

---

runtime/compiler/z/codegen/J9CodeGenerator.cpp

"value" field for in AtomicLong is of type "long" and therefore should be aligned to 8-byte boundary.
checkFieldAlignmentForAtomicLong was incorrectly checking that the offset of the field is a multiple of 4 instead of a multiple of 8.
This PR fixes that.
addresses https://github.com/eclipse-openj9/openj9/issues/20235

Fix fieldAlignment check for AtomicLong on Z

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/control/JITServerHelpers.hpp
runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/env/J9ClassEnv.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.cpp
runtime/compiler/net/MessageTypes.hpp
runtime/compiler/optimizer/J9ValuePropagation.cpp
runtime/compiler/optimizer/J9ValuePropagation.hpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp
runtime/compiler/runtime/SymbolValidationManager.cpp

(1) Add utility methods for null restricted arrays
(2) Fix null restricted array related issues
- Add recognized method  `jdk/internal/value/ValueClass.newArrayInstance`
- Add VP fixed class constraint if `ValueClass.newArrayInstance` creates null restricted array
- Rename `isArrayCompTypePrimitiveValueType` to `isArrayNullRestricted` to reflect the updated logic
- Update `isArrayNullRestricted` on how to determine whether or not an array is a null restricted array
- Disable transformation based on type hint which is no longer sufficient enough to decide whether or not the array is null restricted or not
- If flattenable arrays are enabled, do not create fixed class constraint for parm array class based on signature since both nullable and null restricted arrays share the same signature …

Fix null restricted array related issues for value types

---

runtime/gc_base/IndexableObjectAllocationModel.cpp
runtime/gc_base/IndexableObjectAllocationModel.hpp

Method MM_IndexableObjectAllocationModel::layoutContiguousArraylet() is not used and can be removed

Remove unused method layoutContiguousArraylet()

---

runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/z/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.hpp

Adds support for the following recognized methods:
```
CompareAndExchangeObject     //JDK11
CompareAndExchangeReference  //JDK17,21
CompareAndExchangeInt        //JDK11,17,21
CompareAndExchangeLong       //JDK11,17,21
```
The accelerated CAE code was built on top of the existing accelerated CAS support on Z. Changes are similar to previously added support on Power and X.
Edit:
Depends on: https://github.com/eclipse/omr/pull/7482
Ideally merged as a pair.

Accelerate Unsafe CAS Intrinsics on Z

---

buildenv/jenkins/variables/defaults.yml

https://openssl-library.org/news/secadv/20241016.txt
https://github.com/ibmruntimes/openssl/releases/tag/openssl-3.0.15%2BCVEs1

Update OpenSSL 3.0.15 to include the fix for CVE-2024-9143

---

runtime/vm/CRIUHelpers.cpp
test/functional/cmdLineTests/criu/criu_nonPortable.xml
test/functional/cmdLineTests/criu/src/org/openj9/criu/TimeChangeTest.java

Port of: https://github.com/eclipse-openj9/openj9/pull/20262

(0.48) Restrict getting the restore process start time to CRaC API

---

runtime/compiler/env/VMJ9Server.hpp

The isIndexableDataAdrPresent() and isOffHeapAlocationEnabled() methods override the TR_J9VMBase implementations. They are now marked with override; a compilation error results without it with clang in the default configuration (with -Werror).

Mark TR_J9VMServer virtual methods with override

---

runtime/vm/extendedMessageNPE.cpp
runtime/vm/j9vm.tdf

NPE extended message `RTV_SEND` case should assign `classSig` a value
In `simulateStack()` `RTV_SEND` case, `classSig` should always be assigned a value instead of using the initial `NULL`.
This matches the verifier code https://github.com/eclipse-openj9/openj9/blob/bd36b1da7b46660e9f7c38b312150b248678ee14/runtime/bcverify/bcverify.c#L1717-L1722
This fixed [a user-raised segmentation error](https://ibm-cloud.slack.com/archives/C59HR9D5X/p1729590804796459) (~more tests are still running~ no failure occurred)
```
2024-10-22T09:39:45.196210938Z ----------- Stack Backtrace -----------
2024-10-22T09:39:45.211754265Z getSendSlotsFromSignature+0x10 (0x00007FAFE1ADEF50 [libj9vm29.so+0x1a7f50])
2024-10-22T09:39:45.211754265Z getNPEMessage+0x12ce (0x00007FAFE19753EE [libj9vm29.so+0x3e3ee]) …
```

NPE extended message RTV_SEND case should assign classSig a value

---

runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/env/J9ClassEnv.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/optimizer/EscapeAnalysis.cpp
runtime/compiler/optimizer/J9ValuePropagation.cpp
runtime/compiler/optimizer/TreeLowering.cpp

Also updated code comments where the old primitive value type is referenced
Related: #18157

Remove isPrimitiveValueTypeClass

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/runtime/IProfiler.cpp
runtime/compiler/runtime/IProfiler.hpp

The TR_IProfiler::releaseAllEntries() function is used with DEBUG to check that all entries in the IProfiler _bcHashTable are unlocked at JVM exit. This function now compensates for a known race condition in TR_IProfiler::findOrCreateEntry() by also reporting the number of locked entries it encounters that were likely not a result of that race condition, so it can be asserted instead that that total is zero.
Fixes: https://github.com/eclipse-openj9/openj9/issues/20344

Adjust IProfiler locked entry assert

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/MessageTypes.cpp
runtime/compiler/net/MessageTypes.hpp
runtime/compiler/net/ServerStream.hpp
runtime/compiler/net/StreamExceptions.hpp
runtime/compiler/runtime/JITServerAOTCache.cpp
runtime/compiler/runtime/JITServerAOTCache.hpp
runtime/compiler/runtime/JITServerAOTSerializationRecords.hpp
runtime/oti/j9nonbuilder.h

Added an option that makes the client request a list of cached methods from the server on bootstrap, and set the count for those methods as scount to improve rampup
Depends on https://github.com/eclipse/omr/pull/7458

Client Request Cached Methods List from JIT Server

---

runtime/bcutil/cfreader.c
runtime/bcverify/vrfyhelp.c
runtime/oti/j9.h
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java

- Only recognize strict field for valuetype class versions
- Remove outdated value type field verification checks (@hangshao0 can you confirm this? I wasn't able to track down what draft spec these were part of and I can't find anything in the latest version)
Related to https://github.com/eclipse-openj9/openj9/pull/19830 and https://github.com/eclipse-openj9/openj9/issues/13182

Fix Valhalla Jtreg StrictFields test

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp

Disables code on Power and Z that hides compressedrefs logic from the fast path code generation for the following recognized methods:
`sun_misc_Unsafe_compareAndSwapObject_jlObjectJjlObjectjlObject_Z`
`jdk_internal_misc_Unsafe_compareAndExchangeObject`
`jdk_internal_misc_Unsafe_compareAndExchangeReference`
Fast path code generation for those recognized methods is updated to handle compressedrefs.
Original behavior can be restored by setting the `TR_UseOldCompareAndSwapObject` environment variable. This behavior matches the X implementation which has already disabled the compressedrefs hiding logic when the envvar is not set.

Unhide compressed refs logic from Unsafe CAS codegen

---

runtime/compiler/control/HookedByTheJit.cpp

unordered_set was introduced in c++-11 standard.
Platforms that support JITServer code add a compiler option to provide support for c++-11 standard.
This commit protects the inclusion of the unordered_set header file with `#if defined(J9VM_OPT_JITSERVER)`

Include <unordered_set> only for JITServer platforms

---

runtime/compiler/control/rossa.cpp

PR #20129 added two includes (for "string" and "vector") that are only needed for JITServer specific code. Thus the two includes should be protected by `#if defined(J9VM_OPT_JITSERVER)`

Protect <string>/<vector> includes with #ifdef

---

jcl/src/java.base/share/classes/java/lang/Thread.java

Made `threadRef` volatile so that the most up-to-date value is seen
by all the threads.
`threadRef = NO_REF` assignment will happen once, and similarly, the
`started` field is also set once during initialization.
A user of these methods will probably invoke them multiple times
until the desired result is achieved. A delay in getting the most
up-to-date value should not hinder the functionality of these
methods.
To sum up, removing synchronization in these methods improves perf
by reducing lock contention without hindering the functionality.
Reference to `PR 1FJMO7Q` has been removed and a comment related to
`ThreadGroup` has been updated since the code seems to have evolved
since the comments were written.
Related: #20414

Remove synchronized blocks in Thread isAlive and isDead methods

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp
runtime/compiler/compile/J9SymbolReferenceTable.hpp
runtime/compiler/optimizer/J9TransformUtil.cpp

A method named `findOrCreateClassDepthAndFlagsSymbolRef` was introduced to `TR_J9VMBase` by a previous commit to correct the typo in the name of the method, `findOrCreateClassAndDepthFlagsSymbolRef`.  That change kept the old method due to upstream uses in `J9_PROJECT_SPECIFIC` code in OMR.
This change replaces a call to `findOrCreateClassAndDepthFlagsSymbolRef` that was recently introduced with a call to
`TR_J9VMBase::testIsClassArrayType` instead, to hide the manipulation of the `classDepthAndFlags` field.
As that was the last remaining use of
`findOrCreateClassAndDepthFlagsSymbolRef`, this change also removes the now obsolete method from `TR_J9VMBase`.
This is follow on to pull request #19558 which first introduced `TR_J9VMBase::findOrCreateClassDepthAndFlagsSymbolRef` to replace …

Remove method TR_J9VMBase::findOrCreateClassAndDepthFlagsSymbolRef

---

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp

Add a null check for J9JavaVM->bytecodeVerificationData

---

runtime/compiler/optimizer/J9ValuePropagation.cpp
test/functional/Valhalla/playlist.xml

Update isUnreliableSignatureType to check if the class is an array class. If the class is an array class and its component class is value type and the array class is not null-restricted array, the type is not reliable because it can either be a nullable array class type or a null-restricted array type.
Fixes: #19914

Do not trust nullable arrayclass type in VP

---

jcl/src/java.base/share/classes/java/lang/Class.java

Valhalla still uses `static Class<?> getPrimitiveClass(String name)`
Valhalla extension repo has no latest openjdk change to use `static <T> Class<T> getPrimitiveClass(String name)`.
This fixes [JDKnext_x86-64_linux_valhalla_Nightly](https://hyc-runtimes-jenkins.swg-devops.com/view/Valhalla%20Tests/job/Build_JDKnext_x86-64_linux_valhalla_Nightly/1585/consoleFull) compilation error:
```
21:08:31  /home/jenkins/workspace/Build_JDKnext_x86-64_linux_valhalla_Nightly/src/java.base/share/classes/java/lang/Short.java:83: error: incompatible types: Class<Object> cannot be converted to Class<Short>
21:08:31      public static final Class<Short>    TYPE = (Class<Short>) Class.getPrimitiveClass("short");
21:08:31                                                                                       ^ …
```

Valhalla still uses static Class<?> getPrimitiveClass(String name)

---

test/functional/VM_Test/src/j9vm/test/unsafe/UnsafeCopyMemoryTest.java

In TestUnsafeCopyMemory.testCopyLargeArrayIntoRawMemory(), arrayBaseOffset has been used to generate the arbitrary arrayOffsets for copy, the original test assume that arrayBaseOffset is positive number( array header size), but for off-heap enabled case arrayBaseOffset =0, which could cause negative offset for testing copy(trigger exceptions), update the test code to avoid negative offset for copying.

Update j9vmtest for off-heap feature

---

runtime/bcverify/bcverify.c

j9rtv_verifyArguments expects errorDetailCode to be reset for each class. The error may be processed
incorrectly in j9bcv_createVerifyErrorString if errorDetailCode is kept from a previously
verified class.

Reset errorDetailCode before bytecode verification

---

runtime/compiler/control/J9Options.cpp

The effect of PR #20417 was to enable the TR_UseIdleTime option which was disabled by a code bug. Apparently, this change caused some of the tests to timeout.
This commit temporarily disables TR_UseIdleTime until we understand and fix the cause of the timeouts.
Fixes: #20435

Disable TR_UseIdleTime temporarily

---

runtime/gc_base/IdleGCManager.cpp
runtime/gc_base/IdleGCManager.hpp

- using proper types
- code formatting

Cleanup code for MM_IdleGCManager

---

runtime/gc_stats/FrequentObjectsStats.cpp
runtime/gc_stats/FrequentObjectsStats.hpp

replace U_32 with uint32_t
replace UDATA with uintptr_t
correct code formats
fix:https://github.com/eclipse-openj9/openj9/issues/20449

Clean up code for FrequentObjectsStats

---

runtime/gc_base/FinalizableClassLoaderBuffer.hpp
runtime/gc_base/FinalizableObjectBuffer.hpp
runtime/gc_base/FinalizableReferenceBuffer.hpp

Use correct types, fix formatting

Clean up GC_Finalizable*Buffer classes code

---

test/functional/Valhalla/playlist.xml

Reenable all ValueTypeTestsJIT tests
Fixes: #19708

Reenable all ValueTypeTestsJIT tests

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/il/J9Node.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp

Enabled by default.  Disable by setting the `TR_noPauseOnSpinWait` environment variable.

Replace Thread.onSpinWait() with a PAUSE instruction on x86

---

runtime/gc_base/ObjectCheck.cpp
runtime/gc_base/ObjectCheck.hpp

Update ObjectCheck.cpp and ObjecrCheck.hpp according Coding Standards:
- use correct variable types
- fix code formatting
- replace extensions to ext

Cleanup ObjectCheck

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9method.h
runtime/compiler/il/J9Node.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/UnsafeFastPath.cpp
runtime/compiler/optimizer/VarHandleTransformer.cpp

Adds support for the following recognized methods:
```
CompareAndExchangeObject     //JDK11
CompareAndExchangeReference  //JDK17,21
CompareAndExchangeInt        //JDK11,17,21
CompareAndExchangeLong       //JDK11,17,21
```
The accelerated CAE code was built on top of the existing accelerated CAS support on Arm. Changes are similar to previously added support on Power, X and Z.
Cleans up `isUnsafeCAS` to remove the now unused `comp` parameter. Also cleans up `isUnsafeWithObjectArg`, `isVarHandleAccessMethod` and `isSignaturePolymorphicMethod` to remove unused comp parameters.
Edit:
Needs to be check in with:
https://github.com/eclipse/omr/pull/7505
Due to the changes to the parameters of `isUnsafeCAS` and `isUnsafeWithObjectArg`.

Accelerate Unsafe CAS Intrinsics on Aarch64

---

test/functional/UnsafeTest/src_80/org/openj9/test/unsafe/TestUnsafeCopyMemory.java

In TestUnsafeCopyMemory.testCopyLargeArrayIntoRawMemory(), arrayBaseOffset has been used to generate the arbitrary arrayOffsets for copy, the original test assume that arrayBaseOffset is positive number( array header size), but for off-heap enabled case arrayBaseOffset =0, which could cause negative offset for testing copy(trigger exceptions), update the test code to avoid negative offset for copying.

Update java8 openj9 unsafe test for new off-heap case

---

runtime/compiler/runtime/Listener.cpp

The port in sockaddr (see man 7 ip) is stored in network order, so needs to be converted to host order to be used elsewhere.

Fix bound JITServer port reporting

---

runtime/vm/CRIUHelpers.cpp

Reverts eclipse-openj9/openj9#20421

Revert "Implicitly make sync methods notcheckpointsafe"

---

runtime/j9vm/exports.cmake
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/javanextvmi.cpp
runtime/jvmti/jvmtiHook.c
runtime/redirector/forwarders.m4

Removed upstream by:
* [8343132: Remove temporary transitions from Virtual thread implementation](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/4f96a8ecd7af92122394cada0c74d8504fe1f4c9)

Remove JVM_VirtualThreadHideFrames() from Java 24+

---

runtime/compiler/compile/J9SymbolReferenceTable.cpp

Clean up the redundant VM Access critical section before getObjectClassAt(), since TR_J9VMBase::getObjectClassAt() will acquire/release VM Access internally, and
TR_J9ServerVM::getObjectClassAt() will query the client instead.

Clean Up VM Access in J9SymbolReferenceTable.cpp

---

runtime/include/jni.h.m4
runtime/j9vm31/exports.cmake
runtime/j9vm31/j9vm31.h
runtime/j9vm31/jnicsup.cpp
runtime/j9vm31/jnimisc.cpp
runtime/jnichk/jnicwrappers.c
runtime/oti/j9protos.h
runtime/vm/jnicsup.cpp
runtime/vm/jnimisc.cpp

Also add missing JNI check wrappers for `GetModule` and `IsVirtualThread`.

Add GetStringUTFLengthAsLong for Java 24+

---

runtime/j9vm/exports.cmake
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/javanextvmi.cpp
runtime/redirector/forwarders.m4

Valhalla still requires `JVM_VirtualThreadHideFrames`
Valhalla extension repo is behind OpenJDK latest update, and still requires `JVM_VirtualThreadHideFrames`.
This addresses [JDKnext_x86-64_linux_valhalla_Nightly](https://hyc-runtimes-jenkins.swg-devops.com/view/Valhalla%20Tests/job/Build_JDKnext_x86-64_linux_valhalla_Nightly/1589/consoleFull) compilation failure:
```
20:29:57  /usr/local/gcc11/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/jenkins/workspace/Build_JDKnext_x86-64_linux_valhalla_Nightly/build/linux-x86_64-server-release/support/native/java.base/libjava/VirtualThread.o:(.data.rel+0x70): undefined reference to `JVM_VirtualThreadHideFrames'
```

Valhalla still requires JVM_VirtualThreadHideFrames

---

test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/NullRestrictedTypeOptTests.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeGenerator.java
test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java

This change along with https://github.com/eclipse-openj9/openj9/pull/20473 enables all the disabled tests in ValueTypeTests or associates them with an issue. The change includes:
- Commenting that testCheckCastNullRestrictedTypeOnNull will be enabled with https://github.com/eclipse-openj9/openj9/issues/19764
- Correcting the spelling of sych to synch
- Enabling and updating testSynchMethodsOnValueTypes which was not previously associated with an issue. Since the time this tests was disabled it has become illegal to use synchronized methods that are not static. This is tested in testValueTypeHasSynchMethods. This change removes the part of testSynchMethodsOnValueTypes that attempts to verify a synchronized instance method and renames the test to testStaticSynchMethodsOnValueTypes.
- Add a …

Update disabled functional/Valhalla tests

---

test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java

ValueTypeTests.testDefaultValueWithNonValueType tests the same thing as ValhallaAttributeTests. testNonValueTypeClassWithImplicitCreationAttribute
Fixes: https://github.com/eclipse-openj9/openj9/issues/12197

Remove ValueTypeTests.testDefaultValueWithNonValueType

---

runtime/gc_modron_startup/mmparseXgc.cpp

Values for -Xgc:"tlhInitialSize, -Xgc:tlhMinimumSize and
-Xgc:tlhMaxmumSize can not be
smaller than hardcoded absolute TLH Minimum size

Correct parsing for -Xgc:"tlhInitialSize and -Xgc:tlhMinimumSize

---

doc/release-notes/0.48/0.48.md

Created 0.48.0 release note and updated with the available content specific to 0.48.0 release.
[skip ci]

0.48.0 release note

---

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp

AbstractMemorySegmentImpl.reinterpret methods contain calls to
Reflection.getCallerClass. Optimization of getCallerClass requires
the caller to be inlined. Otherwise, we would end up using the
JNI helper which performs a very expensive stackwalk to obtain
the caller class.
Issue: #20270

Force inline AbstractMemorySegmentImpl.reinterpret for getCallerClass optimization

---

runtime/vm/mz64/UpcallThunkGen.cpp

This commit fixes a bug in FFI Upcall on z/OS where the counter for stack slots in memory is not always increased when iterating through arguments. Specifically, the counter was not being incremented when structs were present in the argument list. It will now be incremented correctly for every argument.

Increment stackSlotCount for structs correctly in FFI Upcall on z/OS

---

runtime/gc_base/ObjectCheck.cpp

Code in j9gc_ext_check_is_valid_heap_object() does verification of j9object (in the heap) and j9class alignments. Currently both of the checks do verify alignment to uintptr_t. However j9object can be aligned to 16 bytes (for Compressed Refs 4-bit shift) or 8 bytes for all other cases. j9class should be aligned to 256 bytes always.

Use correct alignment checks for j9class and j9object

---

runtime/gc_modron_startup/mminit.cpp
runtime/oti/j9nonbuilder.h
runtime/vm/vmthread.cpp

- cache flag isVirtualLargeObjectHeapEnabled in both J9VMThread and J9JavaVM.
- initialize both isVirtualLargeObjectHeapEnabled flags.

Add flag isVirtualLargeObjectHeapEnabled in J9VMThread and J9JavaVM

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/optimizer/IdiomRecognition.cpp
runtime/compiler/optimizer/IdiomRecognition.hpp
runtime/compiler/optimizer/IdiomTransformations.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9Simplifier.cpp
runtime/compiler/optimizer/SequentialStoreSimplifier.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9MemoryReference.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp

The old opcodes had the letter i as a prefix if the operation was indirect. Those opcodes were renamed to use the letter as a suffix instead.
This commit cleans up the references to the old opcodes, iiload/iistore ilload/ilstore iaload/iastore ibload/ibstore, to iloadi/istorei lloadi/lstorei aloadi/astorei bloadi/bstorei in the code comments and trace messages
Related: eclipse-openj9/openj9#19489

Clean up references to old opcodes

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp

For large applications, the code caches can become full, preventing further JIT compilation. Compilation requests issued by the invocation counting mechanism of the interpreter will be rejected early by the JIT, before having the chance of being queued for compilation. Ideally, once a method has been rejected once, it will not be sent again for compilation. Currently this is not happening due to the circumstances described in https://github.com/eclipse-openj9/openj9/issues/20448
This commit will prevent an interpreted method to be sent repeatedly for JIT compilation if compilation is disabled (because of code/data caches becoming full or because of a user specified command line option).
Fixes: https://github.com/eclipse-openj9/openj9/issues/20448

Prevent repeated comp requests when code caches are full

---

runtime/vm/BufferWriter.hpp
runtime/vm/JFRChunkWriter.hpp
runtime/vm/JFRConstantPoolTypes.cpp
runtime/vm/JFRConstantPoolTypes.hpp

Detect chunk buffer overflow and prevent subsequent writes to the buffer. Also, update chunk buffer size calculations.
Skip frames with incomplete data in stacktraces.
Add missing memory frees.

JFR: Prevent chunk buffer overflows

---

jcl/src/java.base/share/classes/java/lang/Access.java
jcl/src/java.base/share/classes/java/lang/Class.java
jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/PlatformMBeanProvider.java

valhalla enable methods for latest openjdk updates
After merging latest openjdk updates, these methods need to be enabled for valhalla.
A personal build [JDKnext_x86-64_linux_valhalla](https://hyc-runtimes-jenkins.swg-devops.com/job/Pipeline_Build_Test_JDKnext_x86-64_linux_valhalla/1985/) passed.
However, https://github.com/eclipse-openj9/openj9/issues/20372 still fails so it needs further investigation.
Required by 
* https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/pull/16
closes https://github.com/eclipse-openj9/openj9/issues/20381

valhalla enable methods for latest openjdk updates

---

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/env/J9ObjectModel.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/ilgen/J9ByteCodeIlGenerator.hpp
runtime/compiler/ilgen/Walker.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9TransformUtil.cpp
runtime/compiler/optimizer/J9TransformUtil.hpp
runtime/compiler/optimizer/J9ValuePropagation.cpp
runtime/compiler/optimizer/UnsafeFastPath.cpp
runtime/compiler/p/codegen/J9CodeGenerator.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/runtime/JitRuntime.cpp
runtime/compiler/x/codegen/J9CodeGenerator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp

With #20461 defining the OffHeap macro and renaming it, this PR changes the usage of the macro to the new name in the JIT code, from `J9VM_GC_ENABLE_SPARSE_HEAP_ALLOCATION` to `J9VM_GC_SPARSE_HEAP_ALLOCATION`.
With this PR the OffHeap JIT code will be first compiled with builds but OffHeap is still disabled.
Testing: 
https://hyc-runtimes-jenkins.swg-devops.com/job/Pipeline-Build-Test-Personal/24804/
https://hyc-runtimes-jenkins.swg-devops.com/job/Pipeline-Build-Test-Personal/24925/

Rename OffHeap macro in JIT code

---

jcl/src/java.base/share/classes/java/lang/System.java

System.IdentityHashCode() should always return the same hash as Object.hashCode(), no matter the object is VT or not.

Update identityHashCode() in System.java for Value type

---

runtime/compiler/build/files/common.mk.ftl
runtime/compiler/control/DLLMain.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/OptionsPostRestore.cpp
runtime/compiler/env/CMakeLists.txt
runtime/compiler/env/DependencyTable.cpp
runtime/compiler/env/DependencyTable.hpp
runtime/compiler/env/J9PersistentInfo.hpp
runtime/compiler/env/PersistentCollections.hpp
runtime/compiler/env/SharedCache.hpp

The new TR_AOTDependencyTable tracks all loaded classes whose class chains match what is stored in the local SCC. In future, it will also be responsible for tracking potential AOT loads; it will use this offset map to detect when all the dependencies of the stored AOT compilation have been satisfied and reduce the count of the associated method to induce a load in response.
This class tracking is disabled by default. It can be controlled with the option -XX:[+|-]TrackAOTDependencies.
Related: https://github.com/eclipse-openj9/openj9/issues/20529

Track loaded classes with valid class chains

---

runtime/vm/jvminit.c

`j9localmap_LocalBitsForPC` is more aggressive than
`j9localmap_DebugLocalBitsForPC` in the way it analyzes and marks local
variables as object references. Aggressiveness relates to determining
whether a local object is being used at a specific point in the
bytecode execution, and this helps optimize garbage collection and
runtime performance. In contrast, `j9localmap_DebugLocalBitsForPC`
adopts a conservative approach; it overestimates and plays safe by
marking objects alive even if they are not being used.
`j9localmap_DebugLocalBitsForPC` resolves the issue seen in
https://github.com/ibmruntimes/Semeru-Runtimes/issues/93.
We have run the following benchmarks: Liberty DT8/DT10 Startup &
Footprint, JRuby and Nashorn. No performance difference is seen between …

Make j9localmap_DebugLocalBitsForPC the default mapper
