runtime/vm/vmprops.c
Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/882 and back-ports.
Fixes: https://github.com/eclipse-openj9/openj9/issues/20534.
=> Define system property jdk.debug from JDK_DEBUG_LEVEL

runtime/jcl/common/reflecthelp.c, runtime/oti/j9consts.h
The value types java.lang.reflect.Field replaces the trustedFinal boolean with a flags int. Set TRUSTED_ACCESS and
NULL_RESTRICTED flags.
Fixes: https://github.com/eclipse-openj9/openj9/issues/20372
edit: I ran a personal build to confirm that sanity tests with a valhalla build will pass with this change https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/24974/
=> Set java.lang.reflect.Field flags for value types

runtime/vm/jvminit.c
Reverts eclipse-openj9/openj9#20569
See https://github.com/eclipse-openj9/openj9/pull/20569#issuecomment-2470939347
=> Revert "Make j9localmap_DebugLocalBitsForPC the default mapper"

runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/env/j9method.cpp, runtime/compiler/runtime/SymbolValidationManager.cpp
This PR fixes a build break in JDK8 and JDK11 introduced by https://github.com/eclipse-openj9/openj9/pull/20373 which occurred because `J9VM_OPT_OPENJDK_METHODHANDLE` is not defined.
=> Fix build break in JDK8,11 due to undefined targetMethodFromMemberName

test/functional/Java8andUp/src_110_up/org/openj9/test/java/lang/Test_Class.java
Synthetic Class of an old class file version does not hava Identity flag set. Update test case accordlingly.
closes #20576
=> Update getModifiers() test for syntheticClass

runtime/compiler/z/codegen/J9CodeGenerator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp
Check is Constrained Transactional Execution feature supported on the CPU to inline ConcurrentLinkedQueue.tmOffer/Poll. Check if CPU has support for Transactional Exuecution feature which covers non constrained TM as well in addition to environment flag is set to generate non constrainedTM sequence for tmOffer and tmPoll.
=> Update supportsInlineConcurrentLinkedQueue to check for CTX

runtime/compiler/aarch64/runtime/CMakeLists.txt, runtime/compiler/build/files/host/aarch64.mk, runtime/compiler/runtime/Runtime.cpp
This commit implements arraytranslateTRTO255 for AArch64.
=> AArch64: Implement arraytranslateTRTO255

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
This commit increases arraycopyRepMovsReferenceArrayThreshold from 32 bytes to 64 bytes or 128 bytes if AVX-512 is supported
=> x86: Increase inline reference arraycopy threshold

test/functional/JIT_Test/playlist.xml, test/functional/JIT_Test/src/jit/test/tr/arrayTranslate/ArrayTranslateTest.java, test/functional/JIT_Test/testng.xml
This commit adds tests for char[] to byte[] cases of JIT arraytranslate.
=> Add tests for JIT arraytranslate

runtime/jcl/common/reflecthelp.c, runtime/oti/vmconstantpool.xml
The fields `Field.flags` and `Field.trustedFinal` are related, but have different types, making it inappropriate to treat them as aliases.
Fixes: #20580.
=> Don't use <fieldalias> for java/lang/reflect/Field.flags

runtime/compiler/codegen/J9CodeGenerator.hpp, runtime/compiler/env/j9method.cpp, runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp, runtime/compiler/z/codegen/J9CodeGenerator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.hpp, test/functional/JIT_Test/src/jit/test/recognizedMethod/TestJavaLangMath.java, test/functional/JIT_Test/src/jit/test/recognizedMethod/TestMathUtils.java
- Enables inlining of Math.max/Math.min functions for floats and doubles
- Implements Java standard
- +0 compares as strictly greater than -0
- if the first arg is a NaN, returns the NaN unchanged. If only the second arg is a NaN, returns that NaN unchanged
vmfarm: http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=81412
personal build test: https://hyc-runtimes-jenkins.swg-devops.com/job/Pipeline-Build-Test-Personal/24986/
=> Support Java Behaviour w.r.t Math.max and Math.min for Floating Points

runtime/gc_structs/ConstantPoolClassSlotIterator.cpp, runtime/gc_structs/ConstantPoolClassSlotIterator.hpp
=> Clean up ConstantPoolClassSlotIterator class

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties, jcl/src/java.base/share/classes/java/lang/Access.java, jcl/src/java.base/share/classes/java/lang/System.java, jcl/src/java.base/share/classes/java/security/AccessControlContext.java, jcl/src/java.base/share/classes/java/security/AccessController.java, runtime/jcl/common/java_lang_Class.cpp, runtime/oti/vmconstantpool.xml
Support JEP 486: Permanently Disable the Security Manager
JDK24 removes the following:
```
SecurityManager.invalidatePackageAccessCache();
SecurityManager.addNonExportedPackages(ml);
Access.allowSecurityManager();
Throw new AccessControlException() for
AccessControlContext.checkPermission() and
AccessController.javaAccessController.checkPermission();
AccessController.getContext() returns NO_PERMISSIONS_ACC;
Thread.inheritedAccessControlContext.
```
Originally included
* https://github.com/eclipse-openj9/openj9/pull/20566
Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/886
Related to https://github.com/eclipse-openj9/openj9/issues/20563
=> Support JEP 486: Permanently Disable the Security Manager

runtime/compiler/optimizer/VectorAPIExpansion.cpp, runtime/compiler/optimizer/VectorAPIExpansion.hpp
- we should not add array header to the address but use base address and offset provided by the intrinsic, whether it's array or segment
=> Fix array and memory segment access in VectorAPIExpansion

runtime/compiler/control/CompilationThread.hpp, runtime/compiler/env/J9SharedCache.cpp, runtime/compiler/env/J9SharedCache.hpp, runtime/compiler/runtime/J9Runtime.hpp
When the dependencies of compiled AOT method bodies are tracked, they will be stored in the SCC as arrays of uintptr_t values, with the first entry being the length of the array, and the subsequent entries being encoded class chain offsets. The low bit of the class chain offset will be cleared if the corresponding class merely needs to be loaded before the compiled method body in the SCC can be loaded.
This infrastructure is currently unused.
Related: https://github.com/eclipse-openj9/openj9/issues/20529
=> Add storage, retrieval of AOT method dependencies

runtime/compiler/runtime/Runtime.cpp
This commit implements arraytranslateTRTO (ASCII conversion) for AArch64.
=> AArch64: Implement arrayTranslateTRTO

runtime/util/cphelp.c, runtime/vm/JFRConstantPoolTypes.cpp, runtime/vm/JFRConstantPoolTypes.hpp, runtime/vm/jfr.cpp
- Assert that VM access is always held while interacting with JFR buffer
- Previously, we stored classhashtable entries. Class hashtable can grow and these entries become stale. Instead use romClass as the key for the package table
- Previously, we iterated ClassEntry hashtables while adding entries to them (see fixupShallowEntries), this results in corruption. Instead we now make a list of the classes we need to scan (findShallowEntries), then walk the list and add scan entries after.
- Dont create tables with J9HASH_TABLE_ALLOW_SIZE_OPTIMIZATION since we cant use that flag and iterate them.
Other fixes:
- dont assume moduleName is always non-NULL
- skip thread flush if the buffer is NULL
- add aserts to non-sensible events
=> Fix JFR synchronization issues

.github/recommendation.js
TriagerX temporarily disables assignees predicition to focus on Components.
Issue: https://github.com/eclipse-openj9/openj9/issues/20489
=> TriagerX temporarily disables assignees predicition

runtime/gc_base/RootScanner.cpp, runtime/gc_glue_java/ConcurrentMarkingDelegate.cpp, runtime/gc_glue_java/MarkingDelegate.cpp, runtime/gc_glue_java/MetronomeDelegate.cpp, runtime/gc_vlhgc/CopyForwardScheme.cpp, runtime/gc_vlhgc/GlobalMarkCardScrubber.cpp, runtime/gc_vlhgc/GlobalMarkingScheme.cpp, runtime/gc_vlhgc/WriteOnceCompactor.cpp, runtime/j9vm/java11vmi.c, runtime/oti/j9.h, runtime/oti/j9nonbuilder.h, runtime/util/module.tdf, runtime/vm/createramclass.cpp, runtime/vm/jvminit.c, test/functional/Java16andUp/playlist.xml, test/functional/Java16andUp/src/org/openj9/test/java/lang/Test_SubClass.java, test/functional/Java16andUp/testSubClassOfSealedSuperFromDifferentPackageInSameUnnamedModule.xml
=>  Fix unnamed module spelling mistake

jcl/src/java.base/share/classes/java/lang/Access.java
JDK24 removes `AccessControlContext` references
Removed `Access.newThreadWithAcc()`.
Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/889
=> JDK24 removes AccessControlContext references

runtime/gc_glue_java/UtilGlue.c
=> Fix OMR_GLUE unnamed spelling mistake

runtime/gc_stats/CopyForwardStats.hpp, runtime/gc_stats/MarkVLHGCStats.hpp, runtime/gc_verbose_handler_vlhgc/VerboseHandlerOutputVLHGC.cpp, runtime/gc_verbose_handler_vlhgc/VerboseHandlerOutputVLHGC.hpp
-new outputOffHeapInfo in CopyForward and Mark for balancedGC
\<offheap candidates="xxx" cleared="xxx" /\>
- output offheap-objects in MemoryInfo \<offheap-objects objects="xxx" bytes="xxx" /\>
=> Update verbose GC for off-heap

runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/env/VMJ9Server.cpp, runtime/compiler/env/VMJ9Server.hpp, runtime/compiler/net/CommunicationStream.hpp, runtime/compiler/net/MessageTypes.cpp, runtime/compiler/net/MessageTypes.hpp, runtime/compiler/optimizer/VectorAPIExpansion.cpp, runtime/compiler/optimizer/VectorAPIExpansion.hpp, runtime/compiler/runtime/JITClientSession.hpp
Cache the reflect class pointer used by the client VM in its VMInfo for the JITServer so the JITServer can identify those classes.
Also ensures that the server will not make vm access requests in the vector API, and that it will not access the inside of any J9Class, but rather uses OpaqueClassBlock and requests information from the appropriate frontend.
=> Cache Client's Reflect Class Pointers at JITServer

runtime/gc/gctable.c, runtime/gc_base/ObjectAccessBarrier.hpp, runtime/gc_base/accessBarrier.cpp, runtime/gc_base/gc_internal.h, runtime/gc_glue_java/ArrayletObjectModel.cpp, runtime/gc_glue_java/ArrayletObjectModel.hpp, runtime/gc_realtime/RealtimeAccessBarrier.hpp, runtime/gc_vlhgc/VLHGCAccessBarrier.cpp, runtime/gc_vlhgc/VLHGCAccessBarrier.hpp, runtime/oti/j9nonbuilder.h
new API j9gc_objaccess_indexableDataDisplacement used by the JIT.
Returns the displacement for the data of moved array object.
For adjacent Array and 0 size array, displacement = dst - src
For Off-heap Array, displacement = 0
should only be called for off-heap eanbled case.
Signed-off-by: lhu <linhu@ca.ibm.com>
=> New vm/gc API j9gc_objaccess_indexableDataDisplacement

buildenv/jenkins/common/build.groovy
In the event we are rate-limited or restricted from pulling from DockerHub, this should work around the problem by pulling from Nvidia's site.
Issue runtimes/automation/122
=> Pull cuda image from nvcr

runtime/gc_vlhgc/VLHGCAccessBarrier.cpp
A couple of Offheap APIs are guarded with 64 bit compile flag.
A more accurate fix would be to guard them with Offheap specific build flag (and do not compile the whole dir for 32bit), but it would require more complex changes.
=> Don't use Offheap APIs for 32 bit

jcl/src/java.base/share/classes/java/lang/System.java
Disable JFR JCL APIs until JFR natives are implemented. 
Related to: https://github.com/eclipse-openj9/openj9/issues/20607
=> Disable JFR JCL APIs

buildenv/jenkins/common/build.groovy
In the event we are rate-limited or restricted from pulling from DockerHub, this should work around the problem by pulling from Nvidia's site.
Issue runtimes/automation/122
Cherry pick https://github.com/eclipse-openj9/openj9/pull/20622
=> (0.49) Pull cuda image from nvcr

runtime/compiler/runtime/J9CodeCache.cpp
After flushing the code cache under FSD there is a call to resetTrampolines. The _trampolineAllocationMark and _trampolineReservationMark need to be reset to their starting positions but were incorrectly set to the end of the trampoline space. As a result all active segments at the time of the cache flush are marked as full (assuming a platform that uses trampolines). This can be seen by taking a JIT verbose log with option `codecache` which will show
CODECACHE:  CodeCache 00007E759000C660 marked as full in reserveSpaceForTrampoline
=> Reset trampoline pointers to top of space

runtime/vm/jfr.cpp
Cherry pick https://github.com/eclipse-openj9/openj9/pull/20621
https://github.com/eclipse-openj9/openj9/pull/20611 was included in the 0.49 branch so this fix should go in as well.
=> (0.49) Fix conditon in JFR buffer test

runtime/compiler/runtime/J9CodeCache.cpp
Backport of https://github.com/eclipse-openj9/openj9/pull/20614 for v0.49.0-release
=> Reset trampoline pointers to top of space (0.49)

runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/DLLMain.cpp, runtime/compiler/control/HookedByTheJit.cpp, runtime/compiler/env/DependencyTable.cpp, runtime/compiler/env/DependencyTable.hpp, runtime/compiler/env/J9SharedCache.cpp, runtime/compiler/env/J9SharedCache.hpp
When a method is initialized in jitHookInitializeSendTarget, the SCC will be checked to see if it has a stored AOT body that was compiled with tracked dependencies. If it does, and all of them are satisfied, the method will be given an initial count of 0. If not all of the dependencies are satisfied, the method will be tracked by the TR_DependencyTable until the dependencies are satisfied, at which point its count will be set to zero, triggering an AOT load on its next invocation.
Related: https://github.com/eclipse-openj9/openj9/issues/20529
=> Track methods with AOT bodies with dependencies

runtime/compiler/compile/J9Compilation.cpp, runtime/compiler/compile/J9SymbolReferenceTable.cpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/DLLMain.cpp, runtime/compiler/control/HookedByTheJit.cpp, runtime/compiler/control/J9CompilationStrategy.cpp, runtime/compiler/control/MethodToBeCompiled.cpp, runtime/compiler/control/OptionsPostRestore.cpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/env/VMJ9Server.cpp, runtime/compiler/env/annotations/Annotations.cpp, runtime/compiler/env/j9method.cpp, runtime/compiler/ilgen/Walker.cpp, runtime/compiler/optimizer/IdiomRecognition.cpp, runtime/compiler/optimizer/IdiomTransformations.cpp, runtime/compiler/ras/kca_offsets_generator.cpp, runtime/compiler/runtime/GPUHelpers.cpp, runtime/compiler/runtime/IProfiler.cpp, runtime/compiler/runtime/JITServerROMClassHash.cpp, runtime/compiler/runtime/JitRuntime.cpp, runtime/compiler/runtime/MetaDataDebug.cpp, runtime/exelib/common/libhlp.c, runtime/vm/JFRChunkWriter.hpp, runtime/vm/linearswalk.c
There is one remaining place that will require a coordinated merge with OMR.
=> Replace sprintf with snprintf in many places

jcl/src/java.base/share/classes/com/ibm/oti/vm/ORBBase.java, jcl/src/java.base/share/classes/com/ibm/oti/vm/ORBVMHelpers.java
Afaik they are only needed for IBM Java 8.
Noticed while looking at [Warn upon Use of Memory-Access Methods in sun.misc.Unsafe](https://openjdk.org/jeps/498)
Tested jdk11 compile via https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/623/
=> Remove ORBBase, ORBVMHelpers from OpenJ9 builds

runtime/j9vm/exports.cmake, runtime/j9vm/j7vmi.c, runtime/j9vm/j9vmnatives.xml, runtime/j9vm/vmi.c, runtime/oti/sunvmi_api.h, runtime/redirector/forwarders.m4, runtime/sunvmi/sunvmi.c
These functions are not needed for Java 24+:
- `jobjectArray JVM_GetClassContext(JNIEnv *);`
- `jobject      JVM_GetInheritedAccessControlContext(JNIEnv *, jclass);`
- `jobject      JVM_GetStackAccessControlContext(JNIEnv *, jclass);`
See upstream changes:
- [8338411: Implement JEP 486: Permanently Disable the Security Manager](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/95daf5dd71a529a0f8f9498812566cec7a92237a)
- [8341916: Remove ProtectionDomain related hotspot code and tests](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/d429ce5e29cba2deabbb41dd27fa22c74cefc9b0)
=> Remove functions no longer used by Java 24+

runtime/gc_base/ObjectAccessBarrier.cpp, runtime/gc_base/ObjectAccessBarrier.hpp, runtime/gc_modron_standard/StandardAccessBarrier.cpp
-Extract copyArrayCritical copyBackArrayCritical, copyStringCritical
and freeStringCritical code from StandardAccessBarrier to
ObjectAccessBarrier(baseclass).
=> Extract copy/free arrayCritical code from StandardAccessBarrier

test/functional/TestUtilities/src/org/openj9/test/util/TimeUtilities.java
Fix TimeUtilities thread number counting synchronization
Use `AtomicInteger` to update the thread number atomically.
closes https://github.com/eclipse-openj9/openj9/issues/20464
=> Fix TimeUtilities thread number counting synchronization

runtime/jvmti/jvmtiHook.c
CRIU `jvmtiHookVMRestoreStartAgent()` requires `internalEnterVMFromJNI()`
`internalEnterVMFromJNI()` after `DisposeEnvironment()` ensures `vmThread->inNative` is false.
closes https://github.com/eclipse-openj9/openj9/issues/20359
=> CRIU jvmtiHookVMRestoreStartAgent() requires internalEnterVMFromJNI()

runtime/vm/createramclass.cpp
Ignore ClassCircularityError created by LoadableDescriptors lists. I encountered this error when trying to enable migrated value classes https://github.com/eclipse-openj9/openj9/issues/20386
Related to https://github.com/eclipse-openj9/openj9/issues/19119
```
class Test {
public static void main(String[] args) throws Throwable {
Circ c = new Circ();
}
}
value class Circ {
static Circ2 c2;
/* LoadableDescriptors list contains Circ2 */
}
value class Circ2 {
static Circ c;
/* LoadableDescriptors list contains Circ */
}
```
=> Ignore class loading errors in LoadableDescriptors

test/functional/Java16andUp/java16andUpSettings.mk, test/functional/Java16andUp/playlist.xml
Add variable `ENABLE_PREVIEW` to enable option `--enable-preview` in
Jep397Tests in Valhalla standard build
Fixes #20575
=> Add a setting file to control options used in Java16andUp tests

runtime/gc_realtime/ConfigurationRealtime.cpp, runtime/gc_realtime/RealtimeAccessBarrier.cpp, runtime/nls/j9gc/j9modron.nls
- Update RealtimeAccessBarrier to use opyArrayCritical, copyBackArrayCritical, copyStringCritical and freeStringCritical common functions (in ObjectAccessBarrier baseclass) to replace similar code in class RealtimeAccessBarrier.
- output warning message if off-heap is enabled in gcpolicy:metronome.
depends on : https://github.com/eclipse-openj9/openj9/pull/20648
=> Update RealtimeAccessBarrier to use common apis for copy arrayCritical

runtime/gc/gctable.c, runtime/gc_base/ClassLoaderManager.cpp, runtime/gc_base/gc_internal.h, runtime/gc_base/modronapi.cpp, runtime/gc_glue_java/MetronomeDelegate.cpp, runtime/oti/j9nonbuilder.h
Add external GC function to report cumulative class unloading stats. Use general API to update counters in class unloading stats.
=> Add j9gc_get_cumulative_class_unloading_stats()

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp, runtime/compiler/compile/AOTClassInfo.hpp, runtime/compiler/compile/J9Compilation.cpp, runtime/compiler/compile/J9Compilation.hpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/env/J9SharedCache.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/env/VMJ9Server.hpp, runtime/compiler/runtime/RelocationRecord.cpp, runtime/compiler/runtime/RelocationRecord.hpp, runtime/compiler/runtime/SymbolValidationManager.cpp, runtime/compiler/runtime/SymbolValidationManager.hpp
The dependencies of AOT-compiled method bodies (class chain offsets of classes and whether or not they are initialized) are recorded during an AOT compilation and stored in the local SCC.
Related: https://github.com/eclipse-openj9/openj9/issues/20529
=> Track method dependencies during AOT store compilations

runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/control/JITServerCompilationThread.cpp, runtime/compiler/control/JITServerCompilationThread.hpp, runtime/compiler/env/j9methodServer.cpp, runtime/compiler/env/j9methodServer.hpp, runtime/compiler/net/CommunicationStream.hpp
Cache the value of unresolvedInCP for virtual, static, and special calls when caching a resolved method at the JIT Server, instead of assuming it is true for all cases.
=> Cache unresolvedInCP at the JIT Server

runtime/compiler/p/codegen/J9TreeEvaluator.cpp, runtime/compiler/p/codegen/J9TreeEvaluator.hpp
The current implementation of `OMR::Power::setmemoryEvaluator()` has some OpenJ9 dependencies (namely when getting the `classDepthAndFlags` from the object's `J9Class` to generate the [runtime array check](https://github.com/eclipse-omr/omr/blob/5be76769e35bd6bd3dfec8c5237fb87d8a5e81b0/compiler/p/codegen/OMRTreeEvaluator.cpp#L6130-L6149)), and is only ever used by OpenJ9 to generate assembly code for `Unsafe.setMemory()`. Thus, to avoid having to re-implement `setmemoryEvaluator()` to eliminate these OpenJ9 dependencies, we will move it over to OpenJ9 instead.
Depends on https://github.com/eclipse-omr/omr/pull/7513
=> Move setmemoryEvaluator() from OMR to Openj9

runtime/compiler/runtime/MethodMetaData.c
In `walkJITFrameSlotsForInternalPointers()`, a displacement of data is calculated between an array object before and after it is moved. Currently, when offheap is enabled, this displacement is calculated as the difference between the dataAddr pointers of the new and old locations. However, because the src object may be overwritten during sliding object movement, it is not safe to read its contents, such as the dataAddr pointer.
Thus, this contribution modifies how the stackwalker calculates displacement when offheap allocation is enabled such that:
- If the array data is adjacent to the array header (i.e.: `dataAddr == pinningArrayAddr + sizeofHeader`), calculate the displacement as `dst - src`
- Otherwise, set displacement to 0
Depends on …
=> Fix stackwalker calculation of object displacement for Offheap

runtime/jvmti/jvmtiHook.c
CRIU `jvmtiHookVMRestoreStartAgent()` requires `internalEnterVMFromJNI()`
`internalEnterVMFromJNI()` after `DisposeEnvironment()` ensures `vmThread->inNative` is false.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/20517
=> (0.49) CRIU jvmtiHookVMRestoreStartAgent() requires internalEnterVMFromJNI()

test/functional/TestUtilities/src/org/openj9/test/util/TimeUtilities.java
Fix TimeUtilities thread number counting synchronization
Use `AtomicInteger` to update the thread number atomically.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/20638
=> (0.49) Fix TimeUtilities thread number counting synchronization

runtime/compiler/control/JITServerCompilationThread.cpp, runtime/compiler/env/j9method.cpp, runtime/compiler/env/j9method.h, runtime/compiler/env/j9methodServer.cpp, runtime/compiler/env/j9methodServer.hpp
This parameter is unused and can be safely removed.
Fixes: #20665
=> Remove unresolvedInCP param from createResolvedMethodFromJ9Method

runtime/gc/gctable.c, runtime/gc_base/ClassLoaderManager.cpp, runtime/gc_base/gc_internal.h, runtime/gc_base/modronapi.cpp, runtime/gc_glue_java/MetronomeDelegate.cpp, runtime/oti/j9nonbuilder.h
Add external GC function to report cumulative class unloading stats. Use general API to update counters in class unloading stats.
=> (0.49) Add j9gc_get_cumulative_class_unloading_stats()

runtime/compiler/z/codegen/J9CodeGenerator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.hpp, runtime/compiler/z/codegen/S390CHelperLinkage.cpp, runtime/compiler/z/codegen/S390CHelperLinkage.hpp
Calls to Class.isAssignableFrom will now use CHelper instead of a JNI call.
note: as discussed (@r30shah ), this change is not enabled yet on Z. It will be enabled when the inlined tests are added to `checkAssignabeEvaluator`.
[vmfarm sanity check for this branch](https://hyc-runtimes-jenkins.swg-devops.com/job/jvm.29.personal/34447/)
The following tests were run on a branch with the change enabled:
[vmfarm](https://hyc-runtimes-jenkins.swg-devops.com/job/jvm.29.personal/34474/)
[personal s390x](https://hyc-runtimes-jenkins.swg-devops.com/job/Pipeline-Build-Test-Personal/25034/)
[personal s390x (unstable re-run)](https://hyc-runtimes-jenkins.swg-devops.com/job/Pipeline-Build-Test-Personal/25047/)
=> Change Class.isAssignableFrom to use CHelper instead of JNI call on Z

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
With valuetypes it's possible for the lockword not to be the first field.
Unblocks https://github.com/eclipse-openj9/openj9/issues/20386
=> Don't assume lockword of class is at index 0

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp, runtime/compiler/optimizer/UnsafeFastPath.cpp
During recognizedCallTransformer and unsafeFastPath, `Unsafe.getAndAdd()` or `Unsafe.getAndSet()` can be transformed into an `atomicFetchAndAdd`/`atomicSwap` helper call. For the UnsafeAPI methods, the destination address is passed in as two separate values: a base object address and an offset. When they are transformed into atomic helper calls, these values are added together and passed in as a single destination address value. However, this does not account for the differing shape of array objects under offheap/balanced GC policy (as opposed to the default, gencon).
Thus, this contribution includes the following changes
- For both recognizedCallTransformer and unsafeFastPath, if the object is an array, the `dataAddr` pointer is loaded and used as the base address.
- For …
=> Adjust arguments to transformed UnsafeAPI calls when offheap is enabled

runtime/compiler/runtime/MetaDataDebug.cpp, runtime/j9vm/javanextvmi.cpp, runtime/oti/util_api.h, runtime/util/bcdump.c
Codependent on https://github.com/eclipse-omr/omr/pull/7555
=> Use indent size rather than buffer for printing bytecodes

runtime/compiler/codegen/J9CodeGenerator.hpp, runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp, runtime/compiler/env/j9method.cpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/z/codegen/J9CodeGenerator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.hpp
Accelerate StringCoding.hasNegatives() API on s390 platform.
Port of https://github.com/eclipse-openj9/openj9/pull/20574
=> (0.49) Accelerate StringCoding.hasNegatives on Z

runtime/rastrace/method_trace.c
The changes reflect the feature request https://github.com/eclipse-openj9/openj9/issues/16416.
Print the actual string instead of address at max of 32 characters. 
Subsequent PRs: cmdline option for length (part 2) and tests (part 3).
Signed-off-by: Nick Kamal <[nick.kamal@ibm.com](mailto:nick.kamal@ibm.com)>
=> Print actual string arguments with -Xtrace (part 1)

runtime/compiler/env/J9VMMethodEnv.cpp, runtime/compiler/runtime/J9CodeCache.cpp
OMR version of startPC expects either a valid start PC or 0 to be returned from J9::VMMethodEnv::startPC since it isn't aware of the J9 specific non-startPC special values that are currently being returned.
This change checks if the J9_STARTPC_NOT_TRANSLATED bit flag is set on the startPC to be returned. This indicates that it isn't a real startPC and will return 0 instead.
Related to:
https://github.com/eclipse-omr/omr/pull/7550
They don't need to go in at the same time since this is currently broken and both PRs are needed to fix the issue. Checking in OpenJ9 or OMR first won't make the problem worse.
=> Change J9::VMMethodEnv::startPC error return value

runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/DLLMain.cpp, runtime/compiler/control/HookedByTheJit.cpp, runtime/compiler/env/DependencyTable.cpp, runtime/compiler/env/DependencyTable.hpp, runtime/compiler/env/J9SharedCache.cpp, runtime/compiler/env/J9SharedCache.hpp
Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/20599 (8f5ae8db13a013702b2fc23b537b69154073b8f5).
When a method is initialized in jitHookInitializeSendTarget, the SCC will be checked to see if it has a stored AOT body that was compiled with tracked dependencies. If it does, and all of them are satisfied, the method will be given an initial count of 0. If not all of the dependencies are satisfied, the method will be tracked by the TR_DependencyTable until the dependencies are satisfied, at which point its count will be set to zero, triggering an AOT load on its next invocation.
=> (0.49) Track methods with AOT bodies with dependencies

runtime/compiler/compile/J9SymbolReferenceTable.cpp, runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/env/VMJ9Server.cpp, runtime/compiler/env/VMJ9Server.hpp, runtime/compiler/net/CommunicationStream.hpp
Classes can now be looked up by signature in a constant pool when compiling AOT or remote methods. An SVM assertion failure relating to shadow symbols has also been fixed using this new support.
Fixes: https://github.com/eclipse-openj9/openj9/issues/20669
=> Add support for class lookup by name in CP for JITServer/AOT

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp, runtime/compiler/compile/AOTClassInfo.hpp, runtime/compiler/compile/J9Compilation.cpp, runtime/compiler/compile/J9Compilation.hpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/env/J9SharedCache.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/env/VMJ9Server.hpp, runtime/compiler/runtime/RelocationRecord.cpp, runtime/compiler/runtime/RelocationRecord.hpp, runtime/compiler/runtime/SymbolValidationManager.cpp, runtime/compiler/runtime/SymbolValidationManager.hpp
Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/20637 (59f667b5efc763a3d0da0b4b5a067aabbf87dca8 53924c71bf0788f84c0233622e9a6c2f780a2768 ac1d4a4e553aa4f06c1c34ade4e1126dc84af041)
The dependencies of AOT-compiled method bodies (class chain offsets of classes and whether or not they are initialized) are recorded during an AOT compilation and stored in the local SCC.
=> (0.49) Track method dependencies during AOT store compilations

runtime/compiler/x/codegen/J9TreeEvaluator.cpp, runtime/compiler/x/codegen/J9TreeEvaluator.hpp, runtime/compiler/x/env/J9CPU.cpp, runtime/compiler/x/env/J9CPU.hpp
With `ipopcnt` and `lpopcnt` IL opcodes implemented in OMR, the OpenJ9 specializations are no longer needed.
Depends on https://github.com/eclipse-omr/omr/pull/7553
=> X: Remove popcnt specialization

runtime/compiler/env/j9method.cpp, runtime/compiler/optimizer/J9EstimateCodeSize.cpp
This PR does the following:
* Only set RecognizedMethod info for MemorySegment getters and setters, as other MemorySegment methods do not require special handling - the special handling being forced to iterate with state in InterpreterEmulator.
* Restrict peeking of MemorySegment method callers to only the getters and setters.
=> Restrict special handling of MemorySegment methods to only the getters and setters

jcl/src/java.base/share/classes/java/lang/Class.java, jcl/src/java.base/share/classes/java/lang/ClassLoader.java, jcl/src/java.base/share/classes/java/lang/invoke/MethodTypeHelper.java
`JDK24` removes `SecurityConstants.GET_CLASSLOADER_PERMISSION`
This resolves JDK next abuild compilation failures:
```
00:01:59  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.base/share/classes/java/lang/Class.java:465: error: cannot find symbol
00:01:59  				sm.checkPermission(SecurityConstants.GET_CLASSLOADER_PERMISSION);
00:01:59  				                                    ^
00:01:59    symbol:   variable GET_CLASSLOADER_PERMISSION
```
=> JDK24 removes SecurityConstants.GET_CLASSLOADER_PERMISSION

runtime/compiler/env/J9VMMethodEnv.cpp, runtime/compiler/runtime/J9CodeCache.cpp
OMR version of startPC expects either a valid start PC or 0 to be returned from J9::VMMethodEnv::startPC since it isn't aware of the J9 specific non-startPC special values that are currently being returned.
This change checks if the J9_STARTPC_NOT_TRANSLATED bit flag is set on the startPC to be returned. This indicates that it isn't a real startPC and will return 0 instead.
Error checking has also been added to addFreeBlock to handle startPC returning 0.
Backport of https://github.com/eclipse-openj9/openj9/pull/20657
=> (0.49.0) Change J9::VMMethodEnv::startPC error return value

runtime/compiler/env/J9SharedCache.hpp, runtime/compiler/env/VMJ9.h
These overrides are helpful when changing the interfaces of classes, so that warnings (at least in clang) are generated if the methods of the base classes aren't changed to compensate.
=> Add override to virtual methods of TR_J9SharedCache and TR_J9VMBase

runtime/compiler/env/J9KnownObjectTable.hpp, runtime/compiler/net/CommunicationStream.hpp, runtime/compiler/runtime/JITServerAOTDeserializer.hpp
These headers mention certain types but do not include the relevant headers for them. This does not yet cause a compilation error because all of their use sites are coincidentally only after those headers have been included.
=> Fix some include warnings in JITServer

runtime/compiler/CMakeLists.txt, runtime/compiler/x/env/J9CPU.cpp
Breaking dependence on eclipse/omr#7540 due to file changes.
=> OpenJ9 JIT changes to support OMR FrontEnd base class refactoring

runtime/compiler/control/CompilationThread.cpp
Currently, methods with unsatisfied dependencies may still have loads attempted for them. This can happen if their counts reach zero very quickly. Since this is the case, methods that are about to be queued for compilation no longer need to be tracked in the method dependency table.
=> Notify dependency table at method queue time

runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/env/VMJ9Server.cpp, runtime/compiler/env/VMJ9Server.hpp, runtime/compiler/net/CommunicationStream.hpp, runtime/compiler/net/MessageTypes.cpp, runtime/compiler/net/MessageTypes.hpp
Ensure VPKnownObject works in server mode with appropriate queries.
=> VPKnownObject Constraints for JITServer

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
This reverts commit edccce1ec177d1d9d8835094729c7c0bcc64a73a, reversing changes made to ec1ae09aa830560872bb9a432dcc99aa4ea91fb1.
This reverts PR #20525 and reduces the threshold for reference arraycopy REP MOVS instructions back to 32 bytes
This addresses the performance regression reported in the internal issue 482.
=> Revert "Merge pull request #20525"

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
This ports https://github.com/eclipse-openj9/openj9/pull/20701 to v0.49
This reduces the threshold for reference arraycopy REP MOVS instructions back to 32 bytes
=> (v0.49) Revert "Merge pull request #20525"

runtime/bcverify/clconstraints.c, runtime/jcl/common/java_dyn_methodhandle.c, runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp, runtime/jcl/common/java_lang_invoke_VarHandle.c, runtime/oti/bcverify_api.h, runtime/oti/j9nonbuilder.h, runtime/vm/createramclass.cpp, runtime/vm/lookupmethod.c, runtime/vm/resolvesupport.cpp
For the case mentioned in https://github.com/eclipse-openj9/openj9/issues/20189#issuecomment-2491620527 `sig1` in `j9bcv_checkClassLoadingConstraintsForSignature` should be copied but `sig2` does not need to be copied. I added an additional boolean for each signature and it is only set to false if the signature is found in a class memory segment.
Related to: https://github.com/eclipse-openj9/openj9/issues/20189
=> Copy local signature from MethodHandleNatives.resolve

runtime/compiler/runtime/RelocationRecord.cpp, runtime/compiler/runtime/RelocationRecord.hpp
This method and its overrides have returned true unconditionally since at least the initial commit.
=> Remove unused checkInlinedClassValidity method

jcl/src/java.base/share/classes/java/lang/ref/Reference.java, jcl/src/java.base/share/classes/java/lang/ref/ReferenceQueue.java
Issue https://github.com/eclipse-openj9/openj9/issues/13823
=> Remove synchronization in Reference and unused methods in ReferenceQueue

runtime/compiler/control/JITClientCompilationThread.cpp
Fix an error so that VM_getObjectClassFromKnownObjectIndexJLClass will not result in the boolean value being sent before assigned.
=> Fix Sequence Error in a Case of HandleServerMessage

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp, runtime/compiler/compile/J9Compilation.cpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/env/DependencyTable.cpp, runtime/compiler/env/DependencyTable.hpp
The verbose options dependencyTracking and dependencyTrackingDetails turn on various verbose log messages related to class and method tracking in the dependency table, and method dependency gathering at compile time.
Depends on https://github.com/eclipse-omr/omr/pull/7571
=> Add verbose logging to dependency table

jcl/src/java.base/share/classes/java/lang/Class.java, jcl/src/java.base/share/classes/java/security/AccessControlContext.java, jcl/src/java.base/share/classes/java/security/AccessController.java
Required by changes soon to be merged into the openj9-staging branch of jdknext, for example:
* [8344397: Remove Security Manager dependencies from java.security and sun.security packages](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/3c63a7f8304b129d50e85b97100f069d50d91808)
=> Remove more security checks for Java 24+

test/functional/Valhalla/playlist.xml, test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeGenerator.java, test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java, test/functional/cmdLineTests/valuetypeddrtests/flattened32bitRefBackfillTest.xml, test/functional/cmdLineTests/valuetypeddrtests/flattenedvaluetypeddrtests.xml, test/functional/cmdLineTests/valuetypeddrtests/playlist.xml, test/functional/cmdLineTests/valuetypeddrtests/unflattenedvaluetypeddrtests.xml
Depends on: https://github.com/eclipse-openj9/openj9/pull/20652 https://github.com/eclipse-openj9/openj9/pull/20642
Related: https://github.com/eclipse-openj9/openj9/issues/20386
=> Use migrated value classes in Valhalla functional tests

jcl/src/java.base/share/classes/java/lang/Access.java, jcl/src/java.base/share/classes/openj9/internal/criu/security/CRIUConfigurator.java
JDK24 adds `JavaLangAccess.virtualThreadDelayedTaskSchedulers()` and removes `GetPropertyAction`.
Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/902
=> JDK24 adds JavaLangAccess.virtualThreadDelayedTaskSchedulers()

jcl/src/java.base/share/classes/java/lang/Class.java
The class `ReflectionFactory.GetReflectionFactoryAction` is removed by:
* [8345286: Remove use of SecurityManager API from misc areas](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/6edf5f4e700a12a5403ea1f8221ca3918a2ff6a6)
which will be merged to the staging branch shortly.
=> JDK24 removes ReflectionFactory.GetReflectionFactoryAction

runtime/vm/JFRConstantPoolTypes.cpp, runtime/vm/JFRConstantPoolTypes.hpp
This fixes the error of "Size of check point event doesn't match content" while reading a JFR chunk.
=> Add an unknown thread entry to JFR constant pool

runtime/j9vm/j8vmi.c
The java caller has added Unsafe.arrayBaseOffset() to the offset for JVM_CopySwapMemory JNI API, need to remove it as GetPrimitiveArrayCritical returns a pointer to the first element, need to replace J9VMTHREAD_CONTIGUOUS_INDEXABLE_HEADER_SIZE() with J9VMTHREAD_UNSAFE_INDEXABLE_HEADER_SIZE() for off-heap case, because arrayBaseOffset() == 0 when off-heap is enabled.
=> Update JVM_CopySwapMemory for off-heap enabled case

runtime/compiler/optimizer/J9ValuePropagation.cpp
Bypass the code that requires a VM read in constraintRecognizedMethod under JITServer mode, to prevent an invalid class pointer being sent to the client and crashing the client.
This block of code should only be reached in jdk11, fixing a crash caused by https://github.com/eclipse-omr/omr/pull/7565.
=> Bypass Code Requiring VM Read at JITServer

runtime/oti/SnapshotFileFormat.h, runtime/vm/VMSnapshotImpl.cpp, runtime/vm/VMSnapshotImpl.hpp, runtime/vm/jvminit.c, runtime/vm/resolvefield.cpp
On restore runs, hidden instance fields have already been added. This patch adds the `JavaVM::hiddenInstanceFields` to the snapshot and adds the functionality to find and fill-in the hidden instance field's correct offset during restore runs.
Related: https://github.com/eclipse-openj9/openj9/issues/20612
=> Add hiddenInstanceFields to the VM snapshot

runtime/vm/JFRConstantPoolTypes.cpp, runtime/vm/JFRConstantPoolTypes.hpp
This fixes the error of "Size of check point event doesn't match content" while reading a JFR chunk.
=> (0.49) Add an unknown thread entry to JFR constant pool

test/functional/UnsafeTest/src_90/org/openj9/test/unsafe/TestUnsafeCopyMemory.java
In TestUnsafeCopyMemory.testCopyLargeArrayIntoRawMemory(), arrayBaseOffset has been used to generate the arbitrary arrayOffsets for copy, the original test assume that arrayBaseOffset is positive number( array header size), but for off-heap enabled case arrayBaseOffset =0, which could cause negative offset for testing copy(trigger exceptions), update the test code to avoid negative offset for copying.
=> Update java9above unsafe test for off-heap case

jcl/src/java.base/share/classes/jdk/internal/ref/CleanerShutdown.java
JDK24 removes `CleanerImpl.phantomCleanableList`
Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/904
=> JDK24 removes CleanerImpl.phantomCleanableList

runtime/compiler/codegen/J9CodeGenerator.hpp, runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp, runtime/compiler/env/j9method.cpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/z/codegen/J9CodeGenerator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.hpp
This PR accelerates the `StringCoding.countPositives` API on z/codegen for JDK21+. This API is similar in implementation to the recently accelerated `StringCoding.hasNegatives` API so we leverage the existing implementation to add acceleration for `StringCoding.countPositives` as well.
=> Accelerate StringCoding.countPositives on Z

test/functional/J9 Exclude File Support/src/com/oti/j9/exclude/XMLParser.java
In https://github.com/eclipse-openj9/openj9/pull/20625, I requested the space be removed from test xml files in places like this:
```
<echo value=" "/>
```
However, the XML parser didn't support empty attribute values:
```
<echo value=""/>
```
This fixes that.
=> XMLParser: support attributes with empty values

runtime/compiler/optimizer/VectorAPIExpansion.cpp, runtime/compiler/optimizer/VectorAPIExpansion.hpp
- introduce new category of temps: vec_len_boxed_unknown
- build temp and whole webs as before
- wherever a temp was invalidated before assign vec_len_boxed_unknown instead
- store vectorization info for calls per node vs. per symbol reference for temps
- always vectorize nodes that are calls to vector API methods, even if input vectors need to be unboxed or result needs to be boxed
- since boxing/unboxing is not supported for all types, have an extra pass just before transformation and invalidate whole web if it contains unsupported boxing/unboxing
- transformation happens as before, except that we first check if children of non-vectorized node need to be boxed or children of vectorized node need to be unboxed, insert boxing/unboxing correspondingly
- this prototype is only enabled under …
=> Implement boxing/unboxing during VectorAPIExpansion under an option

jcl/src/java.base/share/classes/com/ibm/jit/JITHelpers.java, runtime/compiler/build/files/host/p.mk, runtime/compiler/build/files/host/x.mk, runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp, runtime/compiler/compile/J9Compilation.cpp, runtime/compiler/env/j9method.cpp, runtime/compiler/p/codegen/J9TreeEvaluator.cpp, runtime/compiler/p/runtime/CMakeLists.txt, runtime/compiler/p/runtime/J9PPCEncodeUTF16.spp, runtime/compiler/runtime/Runtime.cpp, runtime/compiler/x/codegen/J9TreeEvaluator.cpp, runtime/compiler/x/codegen/J9TreeEvaluator.hpp, runtime/compiler/x/runtime/.gitignore, runtime/compiler/x/runtime/CMakeLists.txt, runtime/compiler/x/runtime/X86EncodeUTF16.nasm, runtime/compiler/z/codegen/J9CodeGenerator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.hpp
This commit restores the changes for encodeUTF16Big and encodeUTF16Little that were removed by #20613.
=> Revert "Stop recognizing UTF16_Encoder.encodeUTF16 methods"

runtime/compiler/codegen/J9CodeGenerator.hpp, runtime/compiler/env/j9method.cpp, runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp, runtime/compiler/z/codegen/J9CodeGenerator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.hpp, test/functional/JIT_Test/src/jit/test/recognizedMethod/TestJavaLangMath.java, test/functional/JIT_Test/src/jit/test/recognizedMethod/TestMathUtils.java
- Enables inlining of Math.max/Math.min functions for floats and doubles
- Implements Java standard
- +0 compares as strictly greater than -0
- if the first arg is a NaN, returns the NaN unchanged. If only the second arg is a NaN, returns that NaN unchanged
Uses SIMD instructions for floats on z14+, and for doubles on z13+ (fixes errors on z13 machines that were seen after https://github.com/eclipse-openj9/openj9/pull/20530). 
https://github.ibm.com/runtimes/openj9-jit-z/issues/935#issuecomment-98667018
depends on https://github.com/eclipse-omr/omr/pull/7572
[vmfarm](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=82594)
[vmfarm w recognizedmethodtests](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=82653)
=> Support Java behaviour w.r.t fmin/fmax/dmin/dmax on Z

test/functional/cmdLineTests/jitserver/playlist.xml
Issue https://github.com/eclipse-openj9/openj9/issues/18599
=> Exclude testJitserverArguments on xlinux jdk8

runtime/compiler/control/CompilationThread.cpp
The existing code does not bind the InterruptibleOperation object to a name, so it is destroyed immediately after it is created.
=> Ensure relocating fresh AOT is interruptible

jcl/src/java.base/share/classes/java/lang/Access.java, jcl/src/java.base/share/classes/java/lang/System.java
Issue https://github.com/eclipse-openj9/openj9/issues/20748
Cherry pick https://github.com/eclipse-openj9/openj9/pull/20749
=> (0.49) Add java.lang.Access.allowSecurityManager to jdk21

runtime/oti/jvminit.h, runtime/vm/vmprops.c
After reading the last `--illegal-native-access=<VALUE>` option,
the system property `jdk.module.illegal.native.access` is assigned
the specified `<VALUE>`.
Related: #19680
Related: #20354
=> [JDK24] Find and consume --illegal-native-access=<VALUE>

debugtools/DDR_VM/src/com/ibm/j9ddr/BytecodeGenerator.java
Remove the reference to `J9ProcessorArchitecture` that will go away with the solution to #20668.
=> Update sample code for enum type fields in BytecodeGenerator.java

runtime/vm/initsendtarget.cpp
`initializeMethodRunAddressNoHook` is called by JIT'd code when it needs
to revert to the interpeter. #20387 modified this function to set
the extra to `0x1`. However, resetting the extra can result in hang
(see #20750 for details).
This commit reverts the change specific to
`initializeMethodRunAddressNoHook`.
Closes https://github.com/eclipse-openj9/openj9/issues/20750
Fixes https://github.com/eclipse-openj9/openj9/issues/20663
=> Revert initializeMethodRunAddressNoHook

runtime/compiler/compile/J9Compilation.hpp, runtime/compiler/env/DependencyTable.cpp, runtime/compiler/env/DependencyTable.hpp, runtime/compiler/runtime/RelocationRecord.cpp, runtime/compiler/runtime/SymbolValidationManager.cpp
For classes acquired via profiling, the dependency table can be used to obtain candidates for relocation.
=> Use dependency table as arbitrary class fallback

runtime/oti/j9nonbuilder.h, runtime/vm/JFRChunkWriter.hpp, runtime/vm/JFRConstantPoolTypes.cpp, runtime/vm/JFRConstantPoolTypes.hpp, runtime/vm/jfr.cpp
- ->system seems to be replaced by the compiler
- = {0} initialization isn't supported by the compiler
=> Make JFR compile on z/OS

runtime/compiler/optimizer/VectorAPIExpansion.cpp
- do not use TR_enableMaskUnboxing environment option since the issue was fixed
- handle astore correctly when RHS is not aload
=> Minor VectorAPI boxing fixes

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties, jcl/src/java.base/share/classes/java/lang/Class.java, jcl/src/java.base/share/classes/java/lang/System.java, jcl/src/java.base/share/classes/java/security/AccessControlContext.java, jcl/src/java.base/share/classes/java/security/AccessController.java, runtime/jcl/CMakeLists.txt, runtime/jcl/common/java_lang_Class.cpp, runtime/jcl/common/java_lang_Class.h, runtime/jcl/exports.cmake, runtime/jcl/uma/se6_vm-side_natives_exports.xml, runtime/jcl/uma/se6_vm-side_natives_objects.xml, runtime/oti/j9nonbuilder.h, runtime/oti/jclprots.h, test/functional/Java8andUp/src/org/openj9/test/attachAPI/TestAttachAPI.java, test/functional/Java8andUp/src_110_up/org/openj9/test/java/lang/Test_Class.java, test/functional/cmdLineTests/J9security/playlist.xml, test/functional/cmdLineTests/URLClassLoaderTests/exclude.xml, test/functional/cmdLineTests/criu/criu_nonPortable.xml, test/functional/cmdLineTests/proxyFieldAccess/playlist.xml, test/functional/cmdLineTests/shareClassTests/DataHelperTests/DataHelperTests_SecurityManager.xml, test/functional/cmdLineTests/shareClassTests/DataHelperTests/playlist.xml, test/functional/testVars.mk
- Throw an error on initialization if java.security.manager attempts to add a security manager
- configure System.setSecurityManager to always throw an UnsupportedOperationException
- System.getSecurityManager will always return null since a security manager can't be set
- Update java.security.* javadocs
- Exclude unused helper methods in java.security.* including native code
- Exclude unused helper methods and natives in java.lang.Class
- Disable functional tests that rely on a security manager
=> JDK24: Permanently Disable the Security Manager

jcl/src/java.base/share/classes/java/lang/System.java
Add native access checks in `System.load/loadLibrary` to comply with
JEP472 (Prepare to Restrict the Use of JNI).
Related: #19680
Related: #20354
=> [JDK24] Add native access checks in System.load/loadLibrary

runtime/compiler/z/codegen/J9CodeGenerator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.hpp
Thread.onSpinWait() is a simple `nop` instruction on z. Enabled by default. Disable by setting the `TR_noPauseOnSpinWait` environment variable.
=> Z: Accelerate inlining Thread.onSpinWait()

runtime/compiler/control/JITClientCompilationThread.cpp
The maxCount parameter is a dynamic quantity, and creating an array of that length in C++ causes a warning-as-error with Clang 18.
=> Fix variable-length array warning in clang

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp, runtime/compiler/p/codegen/J9TreeEvaluator.cpp, runtime/compiler/x/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp
When evaluating Unsafe.CAS, the card marking uses the dstObj to calculate the card entry to dirty.
With OffHeap the dstObj is a dataAddrPointer load of the baseObj:
```
n85n      NULLCHK on n87n [#32]
n86n        icall  jdk/internal/misc/Unsafe.compareAndSetObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z[#415  final native virtual Method -304]
n87n          aload  java/util/concurrent/ConcurrentHashMap.U Ljdk/internal/misc/Unsafe;[#407  final Static]
n92n          aloadi  <contiguousArrayDataAddrFieldSymbol>[#352  final Shadow +16] 
n88n            aload  tab<parm 0 [Ljava/util/concurrent/ConcurrentHashMap$Node;>[#403  Parm]
n13n          ladd                                 
n9n             lshl                               
n6n               i2l …
```
=> OffHeap CardMarking using the baseObj instead of dataAddr

runtime/compiler/z/codegen/J9TreeEvaluator.cpp
Adds class equality check as first check; calls C Helper in OOL section on fail.
This change is not yet enabled, but will be enabled once remaining inlined tests are added.
[vm-farm this branch (mz,xz)](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=83425), [sanity aft comments](https://hyc-runtimes-jenkins.swg-devops.com/job/jvm.29.personal/34558/)
https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/25470/
The following are tests run on a branch with this change enabled:
[vm-farm test branch (mz, xz)](http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=83422), [sanity aft comments](https://hyc-runtimes-jenkins.swg-devops.com/job/jvm.29.personal/34557/)
https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Persona …
=> Generate inline class equality test for Class.isAssignableFrom on Z

runtime/gc_glue_java/ConfigurationDelegate.hpp
MM_ConfigurationDelegate::tearDown() should not use local _extensions, It might be not initialized yet. The definition from J9JavaVM should be used instead.
=> tearDown() in Configuration Delegate should not use local _extensions

runtime/oti/j9nonbuilder.h
Effectively this was already a boolean, just taking more space than necessary. Thus compiler will be able to better pack 2 consecutive booleans (isIndexableDataAddrPresent and
isVirtualLargeObjectHeapEnabled)
=> Downgrade isIndexableDataAddrPresent  to BOOLEAN

runtime/jit_vm/ctsupport.cpp
Some constant pool entries may be unresolved when attempting to relocate a method. If the classes involved are all loaded or initialized properly and the entry is a static field ref, then resolveStaticFieldRef() will be able to resolve the entry, allowing relocation to proceed.
=> Resolve static field ref in CP if possible

runtime/gc_base/GCExtensions.hpp, runtime/gc_modron_startup/mmparseXXgc.cpp, runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp
The standard way to set region size is -Xgc:regionSize. However JVM performs check for minimum region size. We need an alternative option for debugging purpose to provide region size without limitations.
=> Add -XXgc:regionSizeWithOverride

runtime/vm/initsendtarget.cpp
Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/20763
=> 0.49: Revert initializeMethodRunAddressNoHook

.github/recommendation.js, .github/workflows/TriageClosedIssue.yml
Move TriagerX comment to a sandbox temporarily
=> Move TriagerX comment to a sandbox temporarily

runtime/oti/j9nonbuilder.h, runtime/oti/vm_api.h, runtime/vm/VMSnapshotImpl.cpp, runtime/vm/initsendtarget.cpp, runtime/vm/intfunc.c
=> Add initializeMethodRunAddressForSnapshot function

runtime/compiler/x/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp
For OffHeap, the arraycopy transformations uses the correct base object as the dstObj node, instead of the dataAddrPtr load. 
To ensure correctness this PR adds an asserts that checks that the dstObj is not a dataAddrPtr.
```
Valid:
n60n        arraycopy  java/lang/System.arraycopy(Ljava/lang/Object;ILjava/lang/Object;II)V[#405  unresolved notAccessed static Method] [flags 0x400 0x0 ] (Unsigned forwardArrayCopy noArra>
n58n          aload  <parm 0 [Ljava/lang/Object;>[#403  Parm]                          
n59n          aload  <parm 1 [Ljava/lang/Object;>[#404  Parm]                            
n54n          aloadi  <contiguousArrayDataAddrFieldSymbol>[#352  final Shadow +8] [flags 0x20604 0x0 ] (internalPtr )  [    0x78f0fb0e00a0] bci=[-1,0,20] rc=1 vc=33 vn=- li=- udi=- nc=1 fl>
n55n …
```
=> Assert dstObj in arraycopyEval is not a dataAddrPtr in X/Z

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
`nullptr` isn't supported on the z/OS XLC v2r1 compiler used for IBM Java 8 builds on s390x.
`java_lang_invoke_MethodHandleNatives.cpp` is only compiled in builds with OpenJDK MethodHandles enabled. Once OpenJDK MHs are enabled by default, the `nullptr`s here would cause build errors on the platform mentioned above. Probably best just to remove the `nullptr` uses now to conform with the supported C++ features list.
=> Replace nullptr with NULL in java_lang_invoke_MethodHandleNatives.cpp

runtime/oti/vm_api.h
Doxygen documentation does not require "@\return void" to specify a
void return type. The absence of a "@\return" tag inherently implies
a void return type.
Removing "@\return void" ensures consistency across vm_api.h, as some
sections already omit the "@\return" tag for void return types.
Related: https://github.com/eclipse-openj9/openj9/pull/20828
=> Remove "@return void" from vm_api.h documentation

runtime/compiler/env/j9methodServer.cpp
When lambda form sharing is enabled, distinct lambda forms can end up with identical names and signatures, since that option causes the non-deterministic address suffix in their name to be replaced with a NULL address. Thus, the existing name comparison in TR_ResolvedJ9JITServerMethod::staticsAreSame() could cause distinct lambda forms to be identified together inappropriately, leading to crashes in remotely-compiled code. The new code instead always treats two lambda forms with identical names as being distinct, relying on the existing fallback in TR_J9ServerVM::jitStaticsAreSame() to ensure that equal lambda forms are correctly identified as such.
=> Avoid shared lambda form statics name comparison

runtime/oti/j9trace.h, runtime/rasdump/dmpsup.c, runtime/rastrace/j9rastrace.h, runtime/rastrace/method_trace.c, runtime/rastrace/method_trigger.c, runtime/rastrace/trcengine.c
The changes reflect the feature request https://github.com/eclipse-openj9/openj9/issues/16416.
Adding cmdline option to specify string argument length.
-Xtrace:maxstringlength=[0-128]
maxstringlength takes an unsigned integer value from 0 to 128
If maxstringlength = 0 or unspecified, default to address printing.
Other invalid inputs result in the input error.
There will be subsequent PR for tests (part 3).
Signed-off-by: Nick Kamal <<nick.kamal@ibm.com>>
=> Print actual string arguments with -Xtrace (part 2)

runtime/compiler/runtime/SymbolValidationManager.cpp, runtime/jit_vm/ctsupport.cpp
The existing code was introduced to improve the relocation success rate for AOT compilations that track dependencies, by attempting to resolve static field refs in jitGetClassOfFieldFromCP if they were not already resolved. This has introduced a regression in comp CPU for AOT stores, so the attempted field resolution has now been moved to the relevant record validation function to avoid this defect.
=> Modify compile-time static field ref resolution

jcl/src/java.base/share/classes/java/lang/Access.java, jcl/src/java.base/share/classes/java/lang/ClassLoader.java, runtime/oti/vmconstantpool.xml, runtime/vm/bindnatv.cpp
A new version of `ClassLoader.findNative` has been introduced, which
accepts the Java method name and the Java class where the native
method is declared as input parameters. It performs native access
checks to comply with JEP 472 (Prepare to Restrict the Use of JNI).
Related: #19680
Related: #20354
=> Update ClassLoader.findNative to support JEP 472

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/gccheck/CheckEngine.java
If dataAddr field is discovered bad and error code is returned this fact should not prevent continue to iterate through the region.
=> Do not interrupt heap iteration if dataAddr is bad in DDR GC Check

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
The label that marked the beginning of a loop that handles residual bytes for the inline implementation of ArraysSupport.vectorizedHashCode was incorrectly marked as both the Start and End of internal control flow.  The end loop label should have been marked as the End of internal control flow.
Fixes #20786
=> Mark loop end label as end-of-internal-control-flow label

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
The result register from inline vectorizedHashCode implementation is marked as live at the end of the method. The call node->setRegister(result) should not happen twice.
Issue: eclipse-openj9/openj9#20824
=> x86: Fix reg marked as live in vectorizedHashCode

runtime/compiler/optimizer/SequentialStoreSimplifier.cpp
SequentialStoreSimplification compares baseVar (first child to `aladd`) symRef to confirm stores being to the same array for simplification. For object fields the symRef matches even if arrays are different.
To fix the issue a node check is added to make sure that its storing to the same array even if symRefs match.
```
n64n      bstorei  <array-shadow>[#222  Shadow] [flags 0x80000601 0x0 ]                       [0x7284a30603c0] bci=[-1,46,2542] rc=0 vc=730 vn=- li=- udi=- nc=2
n63n        aladd (X>=0 internalPtr )                                                         [0x7284a3060370] bci=[-1,46,2542] rc=1 vc=730 vn=- li=- udi=- nc=2 flg=0x8100
n8n           aloadi  TestSeqStore.a [B[#419  Shadow +8] [flags 0x607 0x0 ]                     [0x736004404ac0] bci=[-1,1,5] rc=6 vc=2185 vn=- …
```
=> Compare nodes in addition to symRef in SequentialStoreSimplification

runtime/compiler/control/HookedByTheJit.cpp
Before this change one could force the optimization level of a particular DLT compilation through a command line option (dltOptLevel=...) only if the TR_DebugDLT env var was defined. This was done to avoid the overhead of searching the option subsets for a given method.
This commit allows one to specify the optimization level of DLT compilations without the need of an env var. Examples:
-Xjit:dltOptLevel=hot
-Xjit:{myMethod}(dltOptLevel=cold)
The overhead for searching option sets has been eliminated if no option subset uses the dltOptlevel= option
Depends on eclipse/omr#7596
=> Change DLT opt level based on option

runtime/jcl/common/stdinit.c
The code for initializing the persisted `applicationClassLoader` and `extensionClassLoader` from a VM snapshot was in an unreachable path. On restore runs, neither of those class loaders will be `null`, but there was a `null` check guarding the initialization.
This patch reorders some of those checks, and ensures that the class loaders are initialized properly.
=> Fix VM snapshot class loader initialization

runtime/gc_glue_java/GlobalCollectorDelegate.cpp
Local class _extensions field might be not initialized if we call tearDown() before initialize()
=> GlobalCollectorDelegate::tearDown() shouldn't use local _extensions

test/functional/cmdLineTests/jfr/jfr.xml
The increased timeout should provide sufficient time for the JFR tests
to complete.
Related: #20865
=> Increase JFR test suite timeout to 30 mins

runtime/compiler/env/VMJ9.cpp
The call to isClassLibraryMethod in isChangeCurrentThread should be safe during AOT(https://github.com/eclipse-openj9/openj9/issues/19965), setting the parameter to true prevents the assertion failure in isClassLibraryMethod.
Fixes https://github.com/eclipse-openj9/openj9/issues/19965
=> Flag Call to isClassLibraryMethod in isChangeCurrentThread as vettedForAOT

runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/env/J9KnownObjectTable.cpp, runtime/compiler/env/J9KnownObjectTable.hpp, runtime/compiler/env/VMJ9Server.hpp, runtime/compiler/net/CommunicationStream.hpp, runtime/compiler/net/MessageTypes.cpp, runtime/compiler/net/MessageTypes.hpp, runtime/compiler/optimizer/J9TransformUtil.cpp, runtime/compiler/optimizer/J9TransformUtil.hpp
Implement TransformIndirectLoadChain partially for the JITServer so it can employ the Vector API during optimization.
=> TransformIndirectLoadChain at JITServer

test/functional/cmdLineTests/xtraceTests/build.xml, test/functional/cmdLineTests/xtraceTests/playlist.xml, test/functional/cmdLineTests/xtraceTests/xtraceTests.xml
The changes reflect the feature request https://github.com/eclipse-openj9/openj9/issues/16416 - part 3
Following part 2 - https://github.com/eclipse-openj9/openj9/pull/20662
cmdline tests for -Xtrace:maxstringlength
Closes: https://github.com/eclipse-openj9/openj9/issues/16416
Signed-off-by: Nick Kamal <<nick.kamal@ibm.com>>
=> Print actual string arguments with -Xtrace (part 3)

runtime/compiler/env/j9methodServer.cpp, runtime/compiler/net/CommunicationStream.hpp
The JITServer version of getResolvedDynamicMethod and getResolvedHandleMethod were missing SVM validations, which caused errors when enabling AOT support for Method Handles with JITServer.
=> Add SVM validations for JITServer ResolvedHandle/DynamicMethod APIs

runtime/compiler/control/CompilationThread.cpp
Add a flag in the optimization plan for compilations triggered by the compileMethod API, which can have the invocation count be any positive integer; replenishInvocationCount will not raise the assertion failure for unexpected count value.
Based on https://github.com/eclipse-openj9/openj9/issues/15472
Depends on https://github.com/eclipse-omr/omr/pull/7598
=> Consider the compileMethod() API in replenishInvocationCount() Assertion

runtime/vm/threadpark.cpp
If the deadline since epoch given to Unsafe.park is negative the calculation of `mills` could overflow. To prevent this set the return code to `J9THREAD_TIMED_OUT ` for non-positive deadlines since they have always passed.
Related to: https://github.com/eclipse-openj9/openj9/issues/17135
=> Return from park immediately for non-positive time since epoch

runtime/compiler/control/JITServerHelpers.cpp
Add additional checks so that the assertion "(memcmp(dst, str, J9UTF8_TOTAL_SIZE(str)) == 0)" in packCallBack() also accounts for the dst signature being truncated for generated classes. Prevents the non-fatal assertion from failing.
Fixes https://github.com/eclipse-openj9/openj9/issues/20046
=> Account for Truncated Signatures in a JITServerHelpers Assertion

buildenv/jenkins/README.md
A test level of `sanity` previously mapped to `sanity.functional`, but since pull request #20203 was merged, maps to `sanity.functional,sanity.openjdk`.  This change updates build documentation to reflect that.  It also adds `openjdk` to the list of recognized test groups, `functional` and `system`.
[skip ci]
=> Update test descriptions to include sanity.openjdk

runtime/compiler/optimizer/J9ValuePropagation.cpp, runtime/compiler/optimizer/J9ValuePropagation.hpp
If null-restricted array is enabled and the class is an array class, the null-restricted array class and the nullable array class share the same signature. The null-restricted array can be viewed as a sub-type of the nullable array. Therefore, the constraint cannot be fixed class.
Related: #20522
=> Add methods to check if array class can be trusted as fixed class

runtime/tests/port/j9vmemTest.c
Since the `keepCycles` array is zero-initialized, if the test is aborted in the very first cycle (`i == 0`) the cleanup procedure at the end cannot rely on the fact that `keepCycles[j] >= i` implies that segment `j` must be freed. Before these changes, such a scenario would cause the test to segfault during cleanup.
Fixes: https://github.com/eclipse-openj9/openj9/issues/19509
=> Avoid segfaults in j9vmem_testOverlappingSegments

runtime/vm/jfr.cpp
- explicitly initialize prevContextSwitches
- calculate switchRate with float
Related: https://github.com/eclipse-openj9/openj9/pull/20725
=> JFR ThreadContextSwitchRate fix-ups

runtime/compiler/control/HookedByTheJit.cpp, runtime/compiler/runtime/IProfiler.cpp, runtime/compiler/runtime/IProfiler.hpp
This PR implements:
- Support for storing all IProfiler info into SCC at shutdown
- Support for printing stats about number of targets for CallGraph entries in the IProfiler
- Other miscellaneous and refactoring changes
=> Support for storing all IProfile info to SCC at shutdown

jcl/src/java.base/share/classes/java/lang/System.java, runtime/oti/vm_api.h, runtime/oti/vmconstantpool.xml, runtime/vm/createramclass.cpp, runtime/vm/resolvesupport.cpp, test/functional/Java8andUp/src_110_up/org/openj9/test/java/lang/Test_Class.java
This change removes the `System.security` private field from Java 24 which fixes the previously failing reflection check to `System.security` in `test/functional/Java8andUp/src_110_up/org/openj9/test/java/lang/Test_Class.java`.
For previous JDK versions `System.security` was included in [`jdk/internal/reflect/Reflection.fieldFilterMap`](https://github.com/ibmruntimes/openj9-openjdk-jdk23/blob/openj9/src/java.base/share/classes/jdk/internal/reflect/Reflection.java#L65) which would cause a `NoSuchFieldException ` to be thrown during an attempt to reflectively access `System.security`. In JDK 24 OpenJDK has removed the `security` field from the System class and from the fieldFilterMap as well. Since OpenJ9 does not need this field in JDK 24 I will remove it as well. The absence of this field …
=> Remove System.security field and getSecurityManager calls for JDK 24

runtime/compiler/optimizer/J9ValuePropagation.cpp
Bypass the code that requires a VM read in constraintRecognizedMethod() under JITServer mode, to prevent an invalid class pointer being sent to the client and crashing the client.
=> Bypass Code Blocks Requiring VM Access for the JIT Server

test/functional/cmdLineTests/URLClassLoaderTests/exclude.xml
Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk24/pull/8 and https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/914
Fixes https://github.com/eclipse-openj9/openj9/issues/20702
=> Enable NonExistJarTests.CheckForError1 test

runtime/vm/CMakeLists.txt
OpenXL on PPC has been known to have some issues with branch tables/indirect branch prediction before, which, when compiling OpenJ9 on AIX with OpenXL, resulted in a ~15% performance regression from before (i.e.: when building with xlC). To eliminate this degredation, the compiler flags `-mllvm -ppc-min-jump-table-entries=512` can be used on the souce files containing the interpreter loop.
=> Set min jump table entries when compiling interpreter

debugtools/DDR_VM/src/com/ibm/j9ddr/J9DDRClassLoader.java, debugtools/DDR_VM/src/com/ibm/j9ddr/StructureReader.java, debugtools/DDR_VM/src/com/ibm/j9ddr/VMDataFactory.java, debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/minidump/unwind/UnwindCode.java, debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/minidump/unwind/UnwindInfo.java, debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/tdump/TDumpReader.java, debugtools/DDR_VM/src/com/ibm/j9ddr/tools/ddrinteractive/Context.java, debugtools/DDR_VM/src/com/ibm/j9ddr/tools/ddrinteractive/plugins/DDRInteractiveClassLoader.java, debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/OptInfo.java, debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/RomClassWalker.java
* remove redundant casts
* remove redundant initialization
* remove redundant type arguments
* suppress unavoidable rawtype warnings
* use getDefinedPackage() instead of deprecated getPackage()
Make some general improvements:
* make inner classes static where possible
* prefer notNull() over !isNull()
Fix error in format specifier (% instead of &).
=> Address some compiler warnings in DDR

jcl/src/java.base/share/classes/java/lang/Access.java
The changes reflect part of the fix for issue https://github.com/eclipse-openj9/openj9/issues/19144.
Removed `!INLINE-TYPES ` for changes now supported by Valhalla project.
There is still some code not supported by Valhalla.
Signed-off-by: Nick Kamal <[nick.kamal@ibm.com](mailto:nick.kamal@ibm.com)>
=> Include temporarily disabled Valhalla code

debugtools/DDR_VM/src/com/ibm/j9ddr/J9DDRClassLoader.java, debugtools/DDR_VM/src/com/ibm/j9ddr/tools/ddrinteractive/plugins/DDRInteractiveClassLoader.java
`ClassLoader.getDefinedPackage()` is only available in Java 9+.
=> Fix DDR build error for Java 8

runtime/oti/j9consts.h, test/functional/Valhalla/build.xml, test/functional/Valhalla/src/org/openj9/test/lworld/ValhallaUtils.java
Valhalla bringup for Java 25 updates
Updated `-source` to `25`;
Updated `VALUE_TYPE_CLASS_FILE_VERSION` to `69`;
Updated `VALUE_TYPES_MAJOR_VERSION` to `69`.
This change is required for Valhalla extension Java 25 update
* https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/pull/17
=> Valhalla bringup for Java 25 updates

debugtools/DDR_VM/src/com/ibm/j9ddr/tools/PointerGenerator.java, jcl/src/openj9.traceformat/share/classes/com/ibm/jvm/format/Format2Tprof.java, jcl/src/openj9.traceformat/share/classes/com/ibm/jvm/format/TraceSection.java
Don't generate or use javadoc style comments in inappropriate places.
For example, 101 such warnings are reported in https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_linux_OpenJDK/824. There are more, but only the first 100 warnings are printed for each module.
=> Fix dangling-doc-comments warnings

test/functional/Java8andUp/playlist.xml, test/functional/Jsr292/playlist.xml, test/functional/NativeTest/playlist.xml, test/functional/OpenJ9_Jsr_292_API/playlist.xml, test/functional/cmdLineTests/callsitedbgddrext/playlist.xml, test/functional/cmdLineTests/gptest/playlist.xml, test/functional/cmdLineTests/jep178staticLinkingTest/playlist.xml
Versions 9, 10, 13 and 18 are no longer supported.
=> Remove dead versions in test playlists

runtime/gc_modron_startup/mminit.cpp
default setting unsafeIndexableHeaderSize is only covered IndexableObjectWithoutDataAddress case, so for Balanced GC Off heap disabled case, there is potentially missing to set unsafeIndexableHeaderSize, change to set default
unsafeIndexableHeaderSize for both w/wo DataAddress cases.
=> Fix potential issue in initializing unsafeIndexableHeaderSize

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp, runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp, runtime/compiler/codegen/J9CodeGenerator.cpp, runtime/compiler/codegen/J9CodeGenerator.hpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/p/codegen/J9CodeGenerator.cpp, runtime/compiler/p/codegen/J9TreeEvaluator.cpp, runtime/compiler/x/codegen/J9CodeGenerator.cpp, runtime/compiler/x/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/J9CodeGenerator.cpp
Changes TR_DisableCASInlining envvar to disable inlining Unsafe compareAndSwap on all platforms. This used to only work on X and would also disable inlining compareAndExchange at the same time. Now it only disables inlining compareAndSwap.
Renames TR_DisableCAEIntrinsic envvar to TR_DisableCAEIntrinsic and it disables inlining Unsafe compareAndExchange on all platforms.
Envvars are now checked in fewer locations and set an option bit instead. The following methods were added to support this: getSupportsInlineUnsafeCompareAndSet
setSupportsInlineUnsafeCompareAndSet
getSupportsInlineUnsafeCompareAndExchange
setSupportsInlineUnsafeCompareAndExchange
These methods are used to indicate support for inlining CAS/CAE and also to query for suppport.
=> Make disable CAS and CAE options consistant

runtime/compiler/optimizer/J9EstimateCodeSize.cpp
Several inlining parameters can be tuned via command line options or env vars. Recently, I needed to tune some inlining parameters that could not be controlled without changing the source. This PR fixes the cases that I observed by adding env vars. I also added some heuristic trace diagnostics that print when we estimate a call but don't inline it.
=> Fix missing diagnostics and tuning knobs in inliner

runtime/compiler/control/DLLMain.cpp
This change improves throughput, footprint and CompCPU while possibly affecting rampup. However, since the goal is to have to best throughput possible in the long run, this change is justified.
=> Change -Xtune:throughput to disable AOT

runtime/rastrace/trcengine.c
See https://github.com/eclipse-openj9/openj9/pull/20662#issuecomment-2533049801.
=> Describe maxstringlength in -Xtrace:help output

runtime/vm/JFRConstantPoolTypes.hpp
JMC wants to get class name from fully qualified class name. And the fully qualified class name of a class that isn't in a package doesn't contain the default package name, resulting a StringIndexOutOfBoundsException.
=> Change JFR default package name to empty string to avoid failure on JMC

runtime/vm/UpcallThunkMem.cpp, runtime/vm/j9vm.tdf
Currently, the `J9Heap` size to store the `UpcallThunk` is restricted to
the page size. If the thunk is greater than the page size, then the
existing code ends in an infinite loop creating `J9Heap`s of page size.
The correct sized `J9Heap` will never be created so the code will never
progress.
To resolve this issue, an adequately sized `J9Heap`, aligned to the page
size, is created to store the `UpcallThunk`.
=> Create an adequately sized J9Heap to store the UpcallThunk

runtime/gc_glue_java/EnvironmentDelegate.hpp, runtime/gc_include/ObjectAllocationAPI.hpp, runtime/gc_modron_startup/mminit.cpp, runtime/gc_realtime/ConfigurationRealtime.cpp, runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp, runtime/gc_vlhgc/VLHGCAccessBarrier.cpp, runtime/oti/j9accessbarrier.h, runtime/oti/j9nonbuilder.h, runtime/vm/vmthread.cpp
Optimize array access macros to use is-contiguous check only in presence
of arraylets
Along with new offheap feature support, Macro Array Element Access
J9JAVAARRAY_EA/J9JAVAARRAY_EA_VM need 1 or 2 more runtime flags check to
handle new cases/new structures. extra runtime condition checks in the
Macro, which is called in hotspot, could cause certain performance
regression in some platforms. especially for standard GC cases, off-heap
would not contribute any benefit at all.
Optimize Macro J9JAVAARRAY_EA/J9JAVAARRAY_EA_VM to avoid runtime check
IsContiguousArray for stamdard GC and balanced GC with off-heap eanable
cases, because there is no discontigouos array for these cases(except o
size array).
1, replace isVirtualLargeObjectHeapEnabled and
isIndexableDataAddrPresent flag with …
=> Optimize array access macros to reduce using is-contiguous check

doc/compiler/aot/LoadingByDependency.md, doc/compiler/aot/README.md
Developer documentation for the dependency-based AOT load scheduling feature has been added to the `doc/` folder.
=> Add documentation for dependency tracking

runtime/compiler/env/j9method.cpp
This commit adds comments to some encoding/decoding methods that are recognized by the JIT.
Only limited Java versions use these methods.
=> Add comments to JIT recognized methods for encoding/decoding

runtime/compiler/p/codegen/J9CodeGenerator.cpp, runtime/compiler/p/codegen/J9TreeEvaluator.cpp
Calculate the address for the array data in OffHeap mode correctly for the String.indexOf instrinsic.
=> Enable String.indexOf intrinsic for OffHeap on POWER

runtime/gc_realtime/ConfigurationRealtime.cpp
new flag indexableObjectLayout in J9JavaVM is only for 64bit platforms need to preprocessing check "#if defined(J9VM_ENV_DATA64)" for setting the flag in ConfigurationRealtime.
=> Fix 32bit platform compiling error

runtime/vm/JFRChunkWriter.hpp, runtime/vm/JFRConstantPoolTypes.cpp
Fixes for buffer size allocation.
=> JFR Park event fixes.

runtime/vm/bindnatv.cpp
`j9gc_createJavaLangString` can release VM access, which allows the GC
to move or collect objects. To prevent this, `entryName` is pushed to
a special frame before the call to `j9gc_createJavaLangString`. This
ensures that `entryName` is protected from being moved or collected by
the GC.
Related: #20870
=> Protect entryName from being collected by the GC

test/functional/cmdLineTests/libpathTest/playlist.xml
Adoptium builds riscv64_linux "headless", test cmdLineTester_libpathTestRtfChild needs excluding for headless builds
Ref: https://github.com/adoptium/aqa-tests/issues/5879
=> Disable cmdLineTester_libpathTestRtfChild for headless riscv64_linux built at Adoptium

runtime/vm/JFRChunkWriter.hpp, runtime/vm/JFRConstantPoolTypes.cpp
Fixes for buffer size allocation into 0.49 release.
=> (0.49) JFR threadpark event fix.

runtime/vm/JFRConstantPoolTypes.hpp
JMC wants to get class name from fully qualified class name. And the fully qualified class name of a class that isn't in a package doesn't contain the default package name, resulting a
StringIndexOutOfBoundsException.
=> (0.49) Change JFR default package name to empty string to avoid failure on JMC

runtime/compiler/p/codegen/J9TreeEvaluator.cpp, runtime/gc_glue_java/ArrayletObjectModel.hpp, runtime/oti/j9accessbarrier.h, test/functional/Java22andUp/src/org/openj9/test/jep454/downcall/HeapArrayTests1.java, test/functional/Java22andUp/src/org/openj9/test/jep454/downcall/HeapArrayTests2.java
New misspellings were introduced in #20888.
=> Fix spelling of contiguous/discontiguous

runtime/compiler/p/codegen/J9TreeEvaluator.cpp
`Thread.onSpinWait()` is a `yield` instruction on Power. The method is recognized and inlined into JIT code.
Original behavior can be restored by setting the `TR_noPauseOnSpinWait` environment variable.
Edit:
Depends on https://github.com/eclipse-omr/omr/pull/7604
The OMR PR needs to be merged first since it implements the properties of the `yield` instruction.
=> Recognize Thread.onSpinWait() on Power

runtime/compiler/optimizer/J9ValuePropagation.cpp
Redundant getComponentType() transformation was observed in value propagation optimization. Adding condition to perform this transformation only in last time through run.
@hzongaro
=> Prevent redundant call transformation

runtime/compiler/env/j9method.cpp
AccessController.doPrivileged methods have historically
not been compiled by the JIT due to security manager use.
Starting in JDK 24 the security manager will be removed
and these methods can be compiled.
=> JIT compile AccessController.doPrivileged in JDK 24+

runtime/compiler/optimizer/VectorAPIExpansion.cpp, runtime/compiler/optimizer/VectorAPIExpansion.hpp
- print intrinsic info as soon as it's parsed
- print astore info during IL transformation phase
=> Improve VectorAPI tracing

runtime/compiler/optimizer/BoolArrayStoreTransformer.cpp
When BoolArrayStoreTransformer insert runtime checks for unknown array type stores generated by `bastore` bytecode, it uses the target array address (without offset) as the base array to load the `vft-symbol` and check the class type. With OffHeap that node would be the `dataAddrPtr` instead of array base.
This PR checks if its the `dataAddrPtr` and uses the correct array base node for the generated check. 
```
BEFORE
n88n      bstorei  <array-shadow>[#244  Shadow] 
n87n        aladd (internalPtr )                                                              
n85n          aloadi  <contiguousArrayDataAddrField>[#347  final Shadow +8] 
n69n            aload  UnsafeArrayGetTest.largeByteArray [B[#404  final Static] (obj1) 
n86n          i2l (X>=0 ) …
```
=> Use correct arrayBaseNode in BoolArrayStoreTransformer for OffHeap

runtime/compiler/runtime/IProfiler.cpp
Interpreter profiler data collection contained two bugs which are fixed by this commit.
=> Fixes to IProfiler fanin data collection

runtime/compiler/runtime/IProfiler.cpp
For diagnostics, IProfiler fanin data can be dumped at shutdown into a specified file.
This commit improves the formatting of the data that is dumped and adds a histogram about the number of callers for each tracked callee.
The following environment variables control the output:
- `TR_PrintIPFanInStats`: enables the printing of fanin data at JVM shutdown time. Note that another way of enabling the printing of this data is to use -Xjit:iprofilerVerbose, provided TR_PrintMethodHashTableFileName is set
- `TR_PrintMethodHashTableFileName`: sets the name of the file that the data will be dumped into. If this is not provided the dump will not occur.
- `TR_PrintMethodHashTableMethodNames`: print method names as well. By default, method names are not printed to avoid potential crashes due to …
=> Stats for IProfiler fanin data

runtime/compiler/p/codegen/J9TreeEvaluator.cpp
Without sign extending the 32bit offsets, it is possible for the upper 32bits of the offset registers to contain garbage bits that will cause the address calculations to produce incorrect (unaddressable) results.
=> Sign extend 32bit offsets in inlineIntrinsicInflate

test/functional/NativeTest/playlist.xml
https://github.com/eclipse-openj9/openj9/issues/20835
=> Temporarily exclude thrstatetest on jdk24+

runtime/compiler/optimizer/J9EstimateCodeSize.cpp, runtime/compiler/optimizer/J9EstimateCodeSize.hpp
During the inlining optimization, there is a phase named estimate code size, that essentially collects the methods in the call graph of the top level callee that ought to be inlined. This estimation has a size threshold that limits the size of the call graph that will be analyzed, in order to prevent the estimation from taking too much cpu and memory. As per the original implementation, if the estimation looked at a call graph that has bytecodes that add up to more than the size threshold, this would cause the top level callee to not be inlined.
However, there was a "backtracking" mechanism added subsequently (still many years ago), that allowed us to skip over some very large parts of the call graph after estimating it, i.e. skip that part of the call graph from what gets considered for …
=> Change inliner estimate code size heuristic

runtime/compiler/control/J9Options.cpp, runtime/compiler/control/J9Options.hpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/runtime/IProfiler.cpp
The only consumer of the fanin info is the inliner. However, the inliner will ignore the fanin data for any method (callee) that is less than 50 bytecodes. Thus, it makes sense to avoid storing fanin info for such small methods. 
With this change the number of entries stored by the fanin mechanism is reduced by about 72%. This is expected to reduce footprint somewhat and to reduce the overhead of the methodinfo hashtable which stores fanin info.
The threshold that decides what is consiredered a small method from the fanin mechanism point of view can be changed with `-Xjit:iprofilerFaninMethodMinSize=` option (default is 50 bytecodes)
=> Reduce the amount of fanin info collected by IProfiler

runtime/compiler/optimizer/VectorAPIExpansion.cpp, runtime/compiler/optimizer/VectorAPIExpansion.hpp
- only use elementType, vectorBitLength, and objectType info calculated during analysis phase (e.g. don't analyze nodes again)
- use objectType info when selecting opcode to distinguish between Vector and Mask operations. For example, some binary operations can be for vectors and for masks and require different opcodes
=> Improve VectorAPI Expansion IL transformation phase

runtime/compiler/build/files/common.mk.ftl
The new OMR compiler source file `UnsafeSubexpressionRemoval.cpp` needs to be included in OpenJ9's UMA makefile in order to build OpenJ9 successfully in that build environment.
This change depends on OMR pull request eclipse-omr/omr#7573
=> Add OMR UnsafeSubexpressionRemover.cpp to UMA makefile

runtime/j9vm/exports.cmake, runtime/j9vm/j9vmnatives.xml, runtime/j9vm/valhallavmi.cpp, runtime/redirector/forwarders.m4
This change adds:
- JVM_IsFlatArray
- JVM_NewNullableAtomicArray
- JVM_NewNullRestrictedAtomicArray
Fixes: https://github.com/eclipse-openj9/openj9/issues/20973
=> Add new jdk.internal.value.ValueClass native methods

runtime/oti/j9nonbuilder.h, runtime/vm/classallocation.c, runtime/vm/createramclass.cpp, runtime/vm/jfr.cpp, runtime/vm/jvminit.c
JFR loadedClassCount was originally kept tracked in classloader. When the classloader gets unloaded, we will lose the count.
Related: https://github.com/eclipse-openj9/openj9/pull/20679
=> Move JFR loadedClassCount to J9JavaVM

test/functional/Java8andUp/playlist.xml
Issue https://github.com/eclipse-openj9/openj9/issues/20810
=> Temporarily exclude VmArgumentTests on jdk24

test/functional/cmdLineTests/lockWordAlignment/playlist.xml
Issue https://github.com/eclipse-openj9/openj9/issues/20539
=> Temp exclude cmdLineTester_lockWordAlignment_Object_X tests for jdk24

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp
When current code transforms an atomic call from the `java/util/concurrent/atomic/` package into an intrinsic, it skips generating the static check given that it's known to not be a static field being accessed (flagged by `isNotStaticField`). But with OffHeap a null and array checks are still required to check if loading the `dataAddrPtr` is necessary for correct address calculation.
Current code adds the OffHeap checks except for `java/util/concurrent/atomic/` calls which was fine in some JDK levels as it uses VarHandles but for JDK8 it still uses `processUnsafeAtomicCall()` and without the OffHeap check its targeting the wrong address.
This PR adds inserting the OffHeap null and array checks to the `isNotStaticField` case.
I tried sharing some code between the case with and without …
=> Add null/array checks for OffHeap NotStaticField atomic case

runtime/compiler/runtime/IProfiler.cpp
PR #20975 is known to cause some throughput regressions. These regressions are caused by limiting the IProfiler to collect fanin info only for methods larger than 50 bytecodes. It turns out that the code in `isLargeCompiledMethod()` does not refer to the size of the callee in the variable called `bytecodeSize`. `bytecodeSize` is actually some computed value which can be much bigger than the size of the callee.
This commit eliminates the code that restricts the fanin info to the methods larger than 50 bytecodes, but leaves all the other changes of PR #20975 intact.
=> Effectively revert PR #20975

jcl/src/java.base/share/classes/java/lang/J9VMInternals.java, runtime/oti/j9protos.h, runtime/oti/vm_api.h, runtime/oti/vmconstantpool.xml, runtime/vm/callin.cpp, runtime/vm/createramclass.cpp, runtime/vm/resolvesupport.cpp
There's no need to call a method that does nothing.
=> Remove J9VMInternals.checkPackageAccess() from Java 24+

runtime/compiler/optimizer/VectorAPIExpansion.cpp
- for example, the output can be: #VECTOR API: Vectorized using vstoreiVector128Int32 in VAdd.main()V at scorching DLT
=> Add DLT info to Vector API verbose output

jcl/src/java.base/share/classes/java/lang/Access.java
JDK25 removes JavaLangAccess.getCharsLatin1()/getCharsUTF16()
Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/925
=> JDK25 removes JavaLangAccess.getCharsLatin1()/getCharsUTF16()

runtime/compiler/optimizer/InlinerTempForJ9.cpp
The inliner uses some heuristics that tries to avoid the inlining of large callees that have already been compiled. What constitutes a large method is determined in a routine called `isLargeCompileMethod()`.
If the callee is in a large frequency block, then we always want to inline that callee.
If the callee is in a medium or low frequency block, then we look at callee size and at the fanin info (how many methods call this callee). For low frequency blocks we are more conservative with inlining than with medium frequency blocks. The existing code contained a bug in that, if there was no fanin info for a callee in a low frequency block, we would always inline the callee, regardless of its size.
This commit fixes this problem and considers the size of the callee first and then the fanin …
=> Adjust inliner use of profiled fanin data

jcl/src/java.base/share/classes/java/lang/Class.java, jcl/src/java.base/share/classes/java/lang/ClassLoader.java, jcl/src/java.base/share/classes/java/lang/StackWalker.java, jcl/src/java.base/share/classes/openj9/internal/criu/CRIUDumpPermission.java, jcl/src/java.base/share/classes/openj9/internal/criu/InternalCRIUSupport.java, jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUDumpPermission.java, jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
Remove calls to System.getSecurityManager for JDK 24 since this method is deprecated for removal and returns null. This change also removes javadoc references to SecurityException which no longer apply with the removal of System.getSecurityManager.
I have more pull requests removing SecurityException and System.getSecurityManager coming. I wanted to break this into smaller chunks for review since there are many uses in OpenJ9.
=> Remove System.getSecurityManager calls from java.base and criu

runtime/compiler/aarch64/runtime/Recomp.cpp, runtime/compiler/arm/runtime/Recomp.cpp, runtime/compiler/p/runtime/Recomp.cpp, runtime/compiler/runtime/JitRuntime.cpp, runtime/compiler/x/runtime/Recomp.cpp, runtime/compiler/z/runtime/Recomp.cpp
This code was copied with minor cosmetic differences into five places.
=> Deduplicate definition of J9::Recompilation::invalidateMethodBody()

doc/release-notes/0.49/0.49.md
Created 0.49.0 release note and updated with the available content specific to 0.49.0 release.
[skip ci]
=> 0.49.0 release note

jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/ClassLoadingMXBeanImpl.java, jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/ManagementPermissionHelper.java, jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/ManagementUtils.java, jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/MemoryMXBeanImpl.java, jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/MemoryPoolMXBeanImpl.java, jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/RuntimeMXBeanImpl.java, jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/ThreadMXBeanImpl.java, jcl/src/java.management/share/classes/java/lang/management/MemoryMXBean.java, jcl/src/java.management/share/classes/java/lang/management/MemoryPoolMXBean.java, jcl/src/java.management/share/classes/java/lang/management/RuntimeMXBean.java, jcl/src/java.management/share/classes/java/lang/management/ThreadMXBean.java, jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9AttachProvider.java, jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/ExtendedOperatingSystemMXBeanImpl.java, jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/ExtendedRuntimeMXBeanImpl.java, jcl/src/jdk.management/share/classes/openj9/lang/management/internal/OpenJ9DiagnosticsMXBeanImpl.java, jcl/src/openj9.gpu/share/classes/com/ibm/gpu/CUDAManager.java, jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Log.java, jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Trace.java, test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestManagementUtils.java
=> JDK24 remove System.getSecurityManager part 2

runtime/vm/ClassInitialization.cpp
Discovered because it messes up indentation when iprinting tracepoints. Tracepoint already exists but never called at the end of performVerification.
=> Add missing exit tracepoint in performVerification

runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/optimizer/J9Inliner.hpp
The two callers of `isLargeCompiledMethod` appear to be inconsistent with the "size" that gets passed in. In one case, the size is the estimated call graph size, whereas in the other case, the size is just the bytecode size. This commit changes `isLargeCompiledMethod` such that the thresholds to compare against are refactored out and passed in from the caller side, thus allowing different thresholds to be used from the two callers. New env vars have been introduced to do some experiments with passing in different size thresholds, though in principle, we could also vary the other thresholds being passed in at each caller.
=> Add env vars to experiment with large method heuristic

runtime/compiler/runtime/CRRuntime.cpp, runtime/compiler/runtime/CRRuntime.hpp
A common best practice in CRIU mode, at least in OpenJ9, is to close all open files before a checkpoint, and reopen them on restore. The JIT would keep log files such as the vlog and rtLog open across a checkpoint/restore boundary. This PR closes these files on checkpoint and reopens them on restore.
=> Close and Reopen JIT log files across a checkpoint/restore

buildenv/jenkins/jobs/infrastructure/Update-Reference-Repos.groovy
=> Skip git gc on aix and master/built-in

runtime/compiler/z/codegen/J9TreeEvaluator.cpp
Takes out unused method `generateInlineTest`.
=> Remove unused static method

runtime/compiler/runtime/Runtime.cpp
This commit implements arraytranslateTROTNoBreak for AArch64.
=> AArch64: Implement arrayTranslateTROTNoBreak

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
Update array inline allocation sequence to initialize dataAddr field only for non-zero size arrays. Field should be left blank for zero size arrays. Additionally this also clears padding field after the size field.
=> NULL initialize dataAddr field for 0 size arrays

runtime/include/j9access.h, runtime/jcl/CMakeLists.txt, runtime/jcl/jcl_java.tdf, runtime/jcl/jcl_net.tdf, runtime/jcl/jcl_nio.tdf
Issue https://github.ibm.com/runtimes/semeru-requests/issues/46
=> Add selected tracepoints for JCL

jcl/src/java.base/share/classes/jdk/internal/ref/CleanerShutdown.java, test/functional/Java8andUp/playlist.xml, test/functional/NativeTest/playlist.xml
JDK24 `CleanerShutdown` invokes `CleanerImpl.CleanableList.reset()`
Enabled the `thrstatetest` and `VmArgumentTests`.
closes https://github.com/eclipse-openj9/openj9/issues/20810
closes https://github.com/eclipse-openj9/openj9/issues/20835
=> JDK24 CleanerShutdown invokes CleanerImpl.CleanableList.reset()

jcl/src/java.base/share/classes/java/security/AccessControlContext.java, jcl/src/java.base/share/classes/java/security/AccessController.java
When we try to invoke doPrivilegedWithCombiner function to
perform a privileged action under an existing context
environment, we are used to construct a new context but ignore
the parent context.
We should take consideration of a combination of the current
and parent context, rather than just choose either the current
or the parent.
This patch solves the failed case in issue https://github.com/eclipse-openj9/openj9/issues/19499.
=> Update doPrivilegedWithCombinerHelper function

jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java
JDK25 changes `Unsafe` base offset from `int` to `long`
Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/929
=> JDK25 changes Unsafe base offset from int to long

jcl/src/java.base/share/classes/com/ibm/sharedclasses/spi/SharedClassProvider.java, jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/MemoryMXBeanImpl.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedAbstractHelper.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedAbstractHelperFactory.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassAbstractHelper.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassHelperFactoryImpl.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassPermission.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassPermissionCollection.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassTokenHelper.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassTokenHelperImpl.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassURLClasspathHelper.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassURLClasspathHelperImpl.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassURLHelper.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassURLHelperImpl.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassUtilities.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassesNamedPermission.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedDataHelper.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedDataHelperFactoryImpl.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedDataHelperImpl.java, jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/provider/SharedClassProviderImpl.java
sanity.functional: https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/26075/
extended.functional:  https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/47119/
=> JDK24 remove System.getSecurityManager part 3

runtime/gc_modron_startup/mmparse.cpp
There is a new option to set physical page size/flags for Sparse Heap. Currently this option is going to accept any valid page size, even it is not recommended for Sparse Heap. Any specific limitations can be added later.
=> Add -Xlp:offheap:

runtime/compiler/control/CompilationThread.cpp
Before this change, a profiled-very-hot compilation that fails due to excessiveComplexity would not be retried, relying on the existing compiled body. If the existing compiled body is at warm (or even cold) opt level, then the performance could be suboptimal.
With this commit profiled-very-hot compilations that fail will be retried at the hot optimization level, but without any profiling. We avoid profiling compilations because they are more complex than non-profiled ones and the likelihood of a failure for a profiled-hot compilation is relatively high when we know that a profiled-very-hot compilation for the same method already failed.
=> Retry failed profiled very-hot compilations at hot instead of warm

test/functional/cmdLineTests/criu/criu_nonPortable.xml, test/functional/cmdLineTests/criu/src/org/openj9/criu/DeadlockTest.java
CRIU `DeadlockTest` adds thread synchronization to keep the lock
Ensure the test thread holds the lock while a checkpoint thread attempts to acquire this lock in the single thread mode;
Also add a few log messages and trace points.
Related to
* https://github.com/eclipse-openj9/openj9/issues/19618
=> CRIU DeadlockTest adds thread synchronization to keep the lock

runtime/compiler/control/HookedByTheJit.cpp, runtime/compiler/control/J9CompilationStrategy.cpp, runtime/compiler/control/J9CompilationStrategy.hpp, runtime/compiler/control/J9Recompilation.cpp, runtime/compiler/control/J9Recompilation.hpp, runtime/compiler/control/OptionsPostRestore.cpp, runtime/compiler/control/RecompilationInfo.hpp, runtime/compiler/control/rossa.cpp, runtime/compiler/runtime/JitRuntime.cpp, runtime/compiler/runtime/RuntimeAssumptions.cpp
...and specify the reason whenever we invalidate a JIT body.
Post-restore exclusion was already specially distinguished by a flag in `TR_PersistentMethodInfo`.
Preexistence invalidation should also have been similarly distinguished, but the logic to avoid making new preexistence assumptions has been treating all invalidations as potentially preexistence-related.
This change is in preparation to add a new invalidation reason: the unloading of an inlined method. It will be important to know when a method has had a JIT body invalidated due to unloading so that when recompiling, inlining can be restricted to avoid repeated invalidation.
=> Track JIT body invalidation reasons as bit flags

runtime/compiler/x/codegen/J9CodeGenerator.cpp
With OffHeap arraycopy optimizations are possible given that large heaps are allocated "off-heap" contiguously.
This PR sets the flag to enable that for reference arraycopy. The flag is already set for primitive and for other platforms.
=> Set SupportsReferenceArrayCopy for x86 with OffHeap

runtime/compiler/optimizer/VectorAPIExpansion.cpp
- check if any of operands have known vector type
- vectorize if such operand is found
=> Vectorize Vector API intrisics if operands are known

runtime/gc_check/CheckEngine.cpp, runtime/gc_glue_java/ArrayletObjectModel.hpp, runtime/gc_vlhgc/CopyForwardScheme.cpp, runtime/gc_vlhgc/GlobalMarkingScheme.cpp, runtime/gc_vlhgc/WriteOnceCompactor.cpp
Verify the consistency (dataAddr, size and related proxy array object) of off heap Entry before freeing the off heap array or updating related proxy object.
depends on: https://github.com/eclipse-omr/omr/pull/7614
Signed-off-by: lhu <linhu@ca.ibm.com>
=> Verify off heap entry during update and free offheap array

runtime/compiler/optimizer/JProfilingValue.cpp
Jprofiling adds control flow to the IL as part of the lowering of the calls to profile values. This control flow splits blocks, and in the process creates temps for values commoned across the split point. If there are enough internal pointers commoned in the method, the lower may end up creating more than the max number of internal pointers allowed, thus causing the compile to fail. This commit keeps track of how many internal pointers are created and avoids lowering any more calls once we have reached a certain threshold. Also added an env var to control this threshold for experimenting in the future.
=> JProfiling fix to avoid too many internal pointers

runtime/j9vm/j7vmi.c
Windows 8 build: http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=87302
=> Include J9VMInternals_doPrivileged methods for Java 8 Windows only

doc/compiler/README.md, doc/compiler/runtime/Bootstrap.md
Closes https://github.com/eclipse-openj9/openj9/issues/12506
=> Document the JIT bootstrap process

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/DiagnosticUtils.java, runtime/jcl/common/com_ibm_oti_vm_VM.cpp, test/functional/cmdLineTests/jfr/jfr.xml, test/functional/cmdLineTests/jfr/src/org/openj9/test/VMAPITest2.java
There is an issue where jfr recording can be stopped twice. When this occurs buffers that are already free'd are freed a second time.
=> Prevent doube stop of JFR recording

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/DiagnosticUtils.java, runtime/vm/jfr.cpp
JFR can invoke `VM.setJFRRecordingFileName()` before `VM.startJFR()`
Allow `VM.setJFRRecordingFileName()` to be invoked before `VM.startJFR()`;
Ignore the changing of the recording filename within the commands `JFR.dump` and `JFR.stop`.
Related to
* https://github.com/eclipse-openj9/openj9/issues/21069
=> JFR can invoke VM.setJFRRecordingFileName() before VM.startJFR()

jcl/src/java.base/share/classes/java/lang/Class.java
Using this approach, `allPermissionsPD` can be a final field. VM's class
initialization mechanisms will prevent races via the `static` block.
Fixes: #20351
=> Use a nested holder class to store allPermissionsPD

runtime/gc/gctable.c, runtime/gc_base/gc_internal.h, runtime/gc_base/modronapi.cpp, runtime/gc_base/modronapi.hpp, runtime/oti/j9nonbuilder.h
JFR stats needs API to get YoungGenerationConfiguration->minSize and YoungGenerationConfiguration->maxSize.
For OpenJ9 Gencon use Nursery minimum/maximum sizes. For OpenJ9 Balanced use Eden Ideal minimum/maximum sizes.
=> Add functions to GC Table to return min and max young gen size

runtime/oti/j9accessbarrier.h, runtime/oti/j9accessbarrierhelpers.h
Macros for Array Effective Address calculations are inherently inlined
and seem to create much pressure either on register or code cash in
Bytecode interpreter.
They are rewritten in C and forced to be outlined specifically for GNU
compilers on X and Z, where we saw regression when Offheap was
introduced (what made the macros more complex, creating even more
pressure).
For other platforms where we did not see regression, we continue to
inline (ATM unknown if outlining would have negative or possitive
effect). Hence we still keep it in a header (*.h) file.
=> Force outlining for array EA API

runtime/compiler/runtime/J9CodeCacheManager.cpp, runtime/oti/j9nonbuilder.h
This field is set to 1 by the JIT when it detects that that no additional code cache can be allocated and all of the allocated code caches are very low on free space. This information can be used by other VM components. For example, the GC can use it to trigger class unloading more aggressively, to make more room in the code caches.
=> Add 'lowCodeCacheFreeSpace' field to J9JITConfig

runtime/compiler/p/codegen/J9TreeEvaluator.cpp
Update array inline allocation sequence to initialize dataAddr field
only for non-zero size arrays. Field should be left blank for zero
size arrays.
=> p: NULL initialize dataAddr field for 0 size arrays 

runtime/gc_glue_java/configure_includes/configure_aix_ppc.mk, runtime/makelib/targets.mk.aix.inc.ftl
~Clean up usage of `OMR_ENV_OPENXL` make/config files~
Replace all usages of OMR_ENV_OPENXL with the already existing env variable, `OMR_TOOLCHAIN`
Depends on https://github.com/eclipse-omr/omr/pull/7605
=> Fix OMR_ENV_OPENXL Usage

runtime/compiler/net/LoadSSLLibs.cpp
When libssl3 (or higher) is bundled with the JDK, we want to load that version in preference over the one present on the system. `dlopen` will do that because the RUNPATH for the JIT dll (from which `dlopen` is invoked) includes the "JDK/lib" path where libssl is bundled. However, as part of loading libssl3, `dlopen` will also attempt to load libcrypto3 (because it is a dependency). This is searched in the RPATH of the jitserver executable for a server, or in the RPATH of the java executable for a client. Currently, the jitserver executable does not include an RPATH, so libcrypto3 is searched on the system and this may fail on systems that do not have version 3 installed. This problem can be circumvented by performing an explicit `dlopen` for the crypto library, in which case the RUNPATH …
=> Explicitly load libcrypto for JITServer

buildenv/jenkins/README.md, buildenv/jenkins/common/pipeline-functions.groovy, buildenv/jenkins/jobs/infrastructure/wrapper_variables.yml
Not sure if it ever worked, but it certainly won't now after https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/928 and backports.
=> Remove support for the obsolute uma and cm spec suffixes

doc/build-instructions/Build_Instructions_V11.md, doc/build-instructions/Build_Instructions_V17.md, doc/build-instructions/Build_Instructions_V21.md
Also fix a couple of references to Visual Studio 2019. JDK21 can boot with the latest JDK21 rather than JDK20.
=> Fix build doc, Windows doesn't need --disable-warnings-as-errors

runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/control/JITServerHelpers.cpp, runtime/compiler/control/JITServerHelpers.hpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/env/VMJ9Server.cpp, runtime/compiler/env/VMJ9Server.hpp, runtime/compiler/env/j9method.cpp, runtime/compiler/env/j9method.h, runtime/compiler/env/j9methodServer.cpp, runtime/compiler/net/CommunicationStream.hpp, runtime/compiler/optimizer/J9TransformUtil.cpp, runtime/compiler/runtime/JITClientSession.cpp, runtime/compiler/runtime/JITClientSession.hpp
The frontend query `isStable(J9Class *fieldClass, int32_t cpIndex)` determines if the field at given J9Class and cpIndex has the @stable annotation.
Before this commit, the JITServer implementation had to send a VM_isStable message to the client for every such query. This commit implements caching of the isStable values at JITServer. Caching is done with a hashtable per J9Class, where the key is the cpIndex we are interested in.
To further reduce the number of the hashtables that serve as a cache, the `isStable()` will answer `false` for any non-bootstrap class. The reason is that at the moment only bootstrap classs have the @stable annotation. This behavior can be disabled by defining the following environment variable:
`TR_DontIgnoreStableAnnotationForUserClasses`.
Another optimization …
=> Reduce the number of VM_isStable messages

runtime/compiler/control/HookedByTheJit.cpp, runtime/compiler/env/jitsupport.cpp, runtime/jcl/common/jclcinit.c, runtime/jnichk/jnicheck.c, runtime/jvmti/jvmtiStartup.c, runtime/oti/j9port_generated.h, runtime/rasdump/dmpagent.c, runtime/rasdump/dmpmap.c, runtime/rasdump/dmpsup.c, runtime/rasdump/trigger.c, runtime/rastrace/trcengine.c, runtime/rastrace/trclog.c, runtime/rastrace/trcmain.c, runtime/rastrace/trcmisc.c, runtime/tests/algorithm/argscantest.c, runtime/tests/algorithm/sendslottest.c, runtime/tests/algorithm/wildcardtest.c, runtime/tests/cutest/parser.c, runtime/tests/jni/memoryCheckTest.c, runtime/tests/port/j9ttyTest.c, runtime/tests/thread/cuharness/parser.c, runtime/tests/thread/thrstate/runtest.c, runtime/vm/exceptiondescribe.c, runtime/vm/exceptionsupport.c, runtime/vm/gphandle.c, runtime/vm/jvminit.c, runtime/vm/jvmrisup.c, runtime/vm/logsupport.c, runtime/vm/vmthread.cpp, runtime/vm/xcheck.c
There's no need to expect users to provide a pointer to the port library (the macro already assumes access via `PORTLIB`); this avoids possible problems being used with a different, incompatible argument.
At least one parameter must be supplied (so the function in `omrtty.c` receives at least two).
Remove unnecessary casts to `(char *)` of format argument.
This is similar to https://github.com/eclipse-openj9/openj9/pull/21051, but for `j9tty_err_printf()`.
=> Improve definition of j9tty_err_printf()

runtime/oti/util_api.h
Building with the change in https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/789, the compiler warns:
```
In file included from openj9/runtime/oti/j9protos.h:123,
from openj9/runtime/util/tracehelp.c:23,
from jdk08/jdk/src/share/native/common/check_version.c:36:
openj9/runtime/oti/util_api.h:2334:88: warning: ‘struct jvmtiClassDefinition’ declared inside parameter list will not be visible outside of this definition or declaration
verifyClassesCanBeReplaced (J9VMThread * currentThread, jint class_count, const struct jvmtiClassDefinition * class_definitions);
^~~~~~~~~~~~~~~~~~~~
openj9/runtime/oti/util_api.h:2337:78: warning: ‘struct jvmtiClassDefinition’ declared inside parameter list will not be visible outside of this definition or declaration
reloadROMClasses (J9VMThread * …
```
=> Add forward declaration to avoid compiler warnings

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Update array inline allocation sequence to initialize dataAddr field
only for non-zero size arrays. Field should be left blank for zero
size arrays.
=> AArch64: NULL initialize dataAddr field for 0 size arrays

test/functional/cmdLineTests/criu/criu_nonPortable.xml, test/functional/cmdLineTests/criu/src/org/openj9/criu/DeadlockTest.java
CRIU `DeadlockTest` adds thread synchronization to prevent premature exit
Ensure a test thread with `@NotCheckpointSafe` is running while another thread attempts to checkpoint in the single thread mode;
Also add a few log messages and trace points.
Related to
* https://github.com/eclipse-openj9/openj9/issues/20832
=> CRIU DeadlockTest adds thread synchronization to prevent premature exit

jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java
This change includes the jdk.internal.misc.Unsafe methods missing in the latest value types build.
Related: https://github.com/eclipse-openj9/openj9/issues/21055
=> New unsafe method stubs for ValueTypes

runtime/compiler/env/VMJ9Server.cpp, runtime/compiler/runtime/JITClientSession.cpp, runtime/compiler/runtime/JITClientSession.hpp
These messages are sent by the server to inquire about the offsets of the reference slots in a j9class.
This commit implements caching at the JITServer of the information received from the client. This change reduces the number of VM_getReferenceSlotsInClass by a factor of 10.
=> Reduce number of VM_getReferenceSlotsInClass messages for JITServer

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java, runtime/jvmti/jvmtiStackFrame.cpp
Since frame callback is not called for skipped frame, frames with JvmtiMountTransition annotation will not be correctly handled.
Also added JvmtiMountTransition annotations to `Continuation.enter()`, `Continuation.yield()`, and `Continuation.yield0()`.
Fixes: https://github.com/eclipse-openj9/openj9/issues/20541
=> Handle frame-skipping of jvmtiGetFrameLocation in frame callback

runtime/compiler/env/VMJ9.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp
Update array inline allocation sequence to initialize dataAddr field only for non-zero length arrays. Field should be left blank for zero length arrays. Additionally this also clears padding field after the size field.
=> Initialize dataAddr field only for non-zero length array

runtime/compiler/p/codegen/J9CodeGenerator.cpp
Re-enable the fast-pathing of Math.min/max for floating points with the behaviours around +/-0.0 and NaN correctly handled.
Depends on https://github.com/eclipse-omr/omr/pull/7617
=> Fast Path Math.min/max_F/D

runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/env/VMJ9Server.cpp, runtime/compiler/env/VMJ9Server.hpp, runtime/compiler/env/j9method.cpp, runtime/compiler/net/CommunicationStream.hpp, runtime/compiler/net/MessageTypes.cpp, runtime/compiler/net/MessageTypes.hpp, runtime/compiler/optimizer/StringBuilderTransformer.cpp
The return type of the JVM's `getStringUTF8Length` method has changed from `IDATA` to `UDATA`.  This change adjusts the JIT compiler's uses of that method.  In particular, the return type of `TR_FrontEnd::getStringUTF8Length` and its overriding methods change from `intptr_t` to `int32_t`.  Similarly, the `bufferSize` argument of `TR_FrontEnd::getStringUTF8` becomes `uintptr_t` where it was `int32_t`.
The motivation was that the length of a UTF-8 encoded String could be greater than 2<sup>32</sup> bytes, so the length could overflow `intptr_t` on a 32-bit platform.  All uses of `getStringUTF8Length` in the JIT involve signatures, descriptors, method names and class names, which will never be large enough to exceed the range of the `int32_t` type.  This was something that @jpmpapin was good …
=> Change return type of getStringUTF8Length

runtime/compiler/CMakeLists.txt
Fixes https://github.com/eclipse-openj9/openj9/issues/20956
=> Link j9jit library without execstack flag on Linux

test/functional/cmdLineTests/runtimemxbeanTests/getPidTest.pl
WMIC is deprecated in the latest Windows versions, causing issues in retrieving process IDs. 
This update switches to PowerShell-based commands for future support
=> Replace deprecated wmic with powershell command to getPid

runtime/gc_vlhgc/WriteOnceCompactor.cpp
When fixing up contiguous reference arrays in Write Once Compactor the
rules should be:
- pick any, if arraylet mode (offheap disabled)
- pick any fully initialized array (dataAddr is set), if
offheap enabled mode
No need to check if data is adjacent - it's given by these conditions.
More so, it's not even correct to use is-adjacent API for arraylet mode.
=> Don't use adjacancy check for arraylets in WOC fixup

runtime/gc_base/IndexableObjectAllocationModel.cpp, runtime/gc_glue_java/ArrayletObjectModel.cpp, runtime/gc_glue_java/ArrayletObjectModel.hpp, runtime/gc_glue_java/ArrayletObjectModelBase.cpp
In array object model distinguish between APIs:
- should be adjacent
- is adjacent
The former is used early when the object is being constructed, and dataAddr is yet to be initialized. API makes a decision based on size in bytes explicitely provided or read from the array heder, and is used to determine if data should be allocated in main heap or offheap.
The latter is used at later points in time (like GC, JNI Critical API) when object is fully initialized. Then the check is about actual dataAddr value (if it points to the end of the header or not). This is faster and simpler check and is preferred, unless dataAddr is not initialized yet.
=> Should-be-adjacent vs is-adjacent data API cleanup

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp, runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp, runtime/compiler/env/j9method.cpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp, runtime/compiler/optimizer/J9RecognizedCallTransformer.hpp, runtime/compiler/p/codegen/J9TreeEvaluator.cpp, runtime/compiler/x/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/J9CodeGenerator.cpp
This commit recognizes StringLatin1.inflate([BI[BII)V and changes it to an arraytranslate node with boundary checks.
=> Recognize StringLatin1.inflate([BI[BII)V

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp, runtime/compiler/env/j9method.cpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp
For helper methods identityHashcode and fastIdentityHashcode,
it may be possible to evaluate their results at compile
time when their enclosing method Object.hashCode() has a known
class object info being passed as an arg which we can evaluate
during compile time. This is done in Value Propagation, but
only if we prevent the inlining of the identityHashcode and
fastIdentityHashcode helper methods.
Also added recognized method java/lang/Object.hashCode().
=> Suppress inlining identityHashcode and fastIdentityHashcode

runtime/compiler/env/ProcessorDetection.cpp, runtime/compiler/x/codegen/J9CodeGenerator.cpp, runtime/compiler/x/env/J9CPU.cpp
Prereq eclipse-omr/omr#7602
Issue: #19408
=> x86: Respect disableAVX2/512 options and check XCR0 for OS support

runtime/oti/j9accessbarrierhelpers.h
Reverts eclipse-openj9/openj9#21153.
Until we can find a way to express the intent in #21153 that works with all compilers (including those used in IBM Java 8) I suggest that those that want to use `-O0` can configure using `--disable-warnings-as-errors-openj9` to ignore the resulting warnings.
=> Revert "Add unused macro to access barrier helpers"

runtime/jvmti/j9jvmti.tdf, runtime/jvmti/jvmtiFunctionTable.c, runtime/jvmti/jvmtiStackFrame.cpp, runtime/jvmti/jvmti_internal.h
=> [JDK25] Add a stub for JVMTI ClearAllFramePops

runtime/compiler/p/runtime/J9PPCArrayTranslate.spp
This commit changes arrayTranslateTRTO helper function for Power to handle the case of length zero.
=> Allow length 0 in arrayTranslateTRTO for Power

runtime/jcl/common/jdk_jfr_internal_JVM_common.cpp, runtime/jcl/common/jdk_jfr_internal_JVM_jdk17andUp.cpp, runtime/oti/j9.h, runtime/oti/j9nonbuilder.h, runtime/oti/vm_api.h, runtime/vm/intfunc.c, runtime/vm/j9vm.tdf, runtime/vm/jfr.cpp, runtime/vm/jvmfree.c, runtime/vm/jvminit.c
A unique type ID is assigned to each JFR event type. In a subsequent PR these type IDs will be used to generate the metadata blob file.
=> Add support for JFR type IDs

runtime/j9vm31/CMakeLists.txt, runtime/j9vm31/j9cel4ro64.c, runtime/j9vm31/j9vm31floatstubs.s
Makes the necessary changes to support compiling the j9vm31 module with Open XL. This includes tweaking the compiler flags to ensure it is built in 32 bit no-xp link mode.
tagging for reference: @joransiu
=> j9vm31 Open XL support

runtime/gc_modron_startup/mmparseXXgc.cpp, runtime/gc_modron_startup/mmparseXgc.cpp
Introduce -XXgc:concurrentScavengeAllocAverageBoost= option to control
headroom for CS. Similar to existing -Xgc:concurrentScavengeSlack=.
The former is a relative boost factor (to the existing allocation rate),
and the latter is an absoulte number in bytes.
Either one can be used to help with noisy applications with spikes in
allocations.
Also moving concurrentScavengeAllocDeviationBoost from -Xgc to -XXgc,
since both boost options are unlikely to be used with customers.
The values specified are integers that are 100x larger then the desired
values.
For example, 130 actually represents 1.30x boost factor.
=> Command line option to control CS relative headroom

runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp
Having dataAddr alive across GC point can lead to a crash. DataAddr
pointer is evaluated into a object stack slot so GC expects it to have an
class pointer but it's just a pointer to first data element. To avoid this
we delay the evaluation of the dataAddr node to OOL.
=> Delay evaluation of dataAddr node till OOL if ref count is 1

jcl/src/java.base/share/classes/java/lang/System.java
Unneeded/unused, the file encoders are no longer in the sun.io package. OpenJDK sets it in jdk8 so keep in there.
=> Remove obsolete system property file.encoding.pkg in jdk11+

runtime/vm/vmprops.c
Enable ConfigFileTest: https://github.com/adoptium/aqa-tests/pull/5967
Related: https://github.com/eclipse-openj9/openj9/issues/20357
Personal build: https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/26570/
jdk_security1 tests: https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/48237/
=> Set OSX argument encoding default to UTF-8 to match ri

runtime/compiler/z/codegen/J9TreeEvaluator.cpp
ArrayStoreCHK on Z uses null check and a seperate store path for nullSource stores, evaluating the destination address early to be used in either paths.
For OffHeap evaluating the destination address includes loading the dataAddr pointer, where having it alive across GC points (OOL ArrayTypeCheck) will cause a crash [1].
To defer the evaluation and loading the dataAddr into a register, this consolidate the store paths for null and non-null stores and defers the destination address evaluation till before the store happens for OffHeap.
Side-effect of this is null-stores performing a wrtbar/card-marking even thought it's not necessary but opted for instead of a second null check.
[1]
Reason of crashing is evaluating the dataAddr pointer into a collectable register. A long-term solution is …
=> Defer dataAddr eval & use wrtbar store for nullSource OffHeap Z ArrayStoreCHK

runtime/compiler/runtime/MethodMetaData.c, runtime/gc_base/ObjectAccessBarrier.hpp, runtime/gc_base/RootScanner.hpp, runtime/gc_base/accessBarrier.cpp, runtime/gc_base/gc_internal.h, runtime/gc_glue_java/ArrayletObjectModel.cpp, runtime/gc_glue_java/ArrayletObjectModel.hpp, runtime/gc_realtime/RealtimeAccessBarrier.hpp, runtime/gc_structs/VMThreadStackSlotIterator.cpp, runtime/gc_structs/VMThreadStackSlotIterator.hpp, runtime/gc_vlhgc/CopyForwardScheme.cpp, runtime/gc_vlhgc/VLHGCAccessBarrier.cpp, runtime/gc_vlhgc/VLHGCAccessBarrier.hpp, runtime/gc_vlhgc/WriteOnceCompactor.cpp, runtime/oti/j9nonbuilder.h
When calculating data displacement during array movement in root scanning, data adjacency check has to be aware what type of movement it is.
For Copy-Forward scanner, adjacency check has to be peformed against source object, since destination one may not be fully copied yet.
For WOC scanner, adjacency check has to be peformed against dst object, since source one may be overwritten.
=> RootScanner awareness for array displacement API

runtime/compiler/optimizer/SPMDParallelizer.cpp
`TR_SPMDKernelParallelizer::processSPMDKernelLoopForSIMDize` creates a `TR::StackMemoryRegion` object that's used to allocate space for a `TR_ScratchList` and a `TR_HashTab`.  However, while that `TR::StackMemoryRegion` is still in scope, another `TR_HashTab` - `_loopDataType` - that was allocated in an earlier `TR::StackMemoryRegion` is used and potentially has more entries added to it.  Once `processSPMDKernelLoopForSIMDize`'s `TR::StackMemoryRegion` goes out of scope and then comes back into scope, the contents of `_loopDataType` could become corrupted.
Fixed this by narrowing the scope of the `TR::StackMemoryRegion` object in `processSPMDKernelLoopForSIMDize` to ensure it goes out of scope before `_loopDataType` might be manipulated again.
Note that with this change the …
=> Narrow scope of TR::StackMemoryRegion during SPMD parallelization

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/LayoutStrPreprocessor.java, runtime/vm/OutOfLineINL_openj9_internal_foreign_abi_InternalDowncallHandler.cpp
The changes reflect the fix for issue https://github.com/eclipse-openj9/openj9/issues/21017.
buildInternalNativeStackFrame before setting exception.
Added check for sequence layout of zero length.
Closes: https://github.com/eclipse-openj9/openj9/issues/21017
Signed-off-by: Nick Kamal <[nick.kamal@ibm.com](mailto:nick.kamal@ibm.com)>
=> OpenJDK java/foreign/TestLinker crash fix

test/functional/cmdLineTests/lockWordAlignment/exclude.xml, test/functional/cmdLineTests/lockWordAlignment/playlist.xml
Currently, the entire LockWordAlignment test suite is disabled to
suppress failure #20539.
It was observed that javap no longer overrides core JCL classes, such
as java/lang/Object, in JDK24+. This behavior is also present in the
RI.
As a result, the LockWordAlignment test suite is being re-enabled,
with only the affected sub-test impacted by the change in
javap -bootclasspath behavior being disabled.
We plan to reach out to OpenJDK developers to confirm whether this is
an intentional behavior change or a bug. Until then, #20539 will
remain open.
Related: #20539
=> Disable javap -bootclasspath test in LockWordAlignment for JDK24+

doc/build-instructions/Build_Instructions_V11.md, doc/build-instructions/Build_Instructions_V17.md, doc/build-instructions/Build_Instructions_V21.md, doc/build-instructions/Build_Instructions_V8.md
The jdk8 link didn't work, update them all to use `openj9-openjdk-jdk<ver>` links.
=> Update the build doc troubleshooting links

runtime/compiler/z/codegen/J9TreeEvaluator.cpp
Commons out code in `genTestIsSuper` and `genInstanceOfOrCheckCastSuperClassTest` into 3 helpers (`genTestRuntimeFlags`, `genLoadAndCompareClassDepth`, `genCheckSuperclassArray`)
Replaces calls to the old generators with calls to the 3 new
=> Refactor SuperclassTest generators on Z

buildenv/jenkins/common/pipeline-functions.groovy
Test pipelines expect this to be a bool. There is a warning printed in the pipelines currently that the type doesn't match and it converts it.
https://github.ibm.com/runtimes/aqa-tests/blob/3f58e11aa281ae1c673e5a2659e0c2884c097929/buildenv/jenkins/testJobTemplate#L445
Current output
```
00:39:15.880  Scheduling project: [Test_openjdk21_j9_sanity.functional_aarch64_linux_Nightly](https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_aarch64_linux_Nightly/)
00:39:15.880  The parameter 'KEEP_REPORTDIR' did not have the type expected by [Test_openjdk21_j9_sanity.functional_aarch64_linux_Nightly](https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_aarch64_linux_Nightly/). Converting to Boolean Parameter.
```
Now
```
00:15:49.006  Scheduling project: …
```
=> Change KEEP_REPORTDIR param to bool

runtime/cmake/platform/toolcfg/openxl.cmake, runtime/cmake/platform/toolcfg/xlc.cmake
Contains all the initial required toolchain changes to start using Open XL compiler with z/OS builds.
---
Keeping as draft state until I have verified it does not interfere with z/OS XLC Builds.
=> Open XL Toolchain Changes

runtime/compiler/CMakeLists.txt
Open XL compilation causes "expected relocatable expression" error when attempting to compile codertinit.cpp with the O3 optimization level. It was recommended to lower the optimization level for this particular file and an issue has been opened internally to track fixing this issue in context of Open XL.
=> Open XL workaround: lower optimization level for codertinit.cpp

runtime/compiler/optimizer/J9ValuePropagation.cpp
Use debug utility to print TR_YesNoMaybe
Closes: #17956
=> Use debug utility to print TR_YesNoMaybe

runtime/compiler/p/codegen/J9TreeEvaluator.cpp
The array allocation length is a int node/value, using a cmp8 on it can result in the wrong result if it the register has undefined value in the upper 4-bytes.
Current code show proper cmp instruction compared to the added offheap check.
WIP: finishing tests
=> Fix P allocationInlining OffHeap len cmp to use cmp4 instead of cmp8

runtime/compiler/control/HookedByTheJit.cpp
incGlobalClassUnloadID() function is used to increment a counter every time a class unload event happens. This is used by the interpreter profiler to determine if it needs to re-examine the validity of the entries it looks at. If there was no class unload operation since the last time it looked at an entry, it doesn't have to check again.
Currently, incGlobalClassUnloadID() is called in jitHookAnonClassesUnload() and jitHookClassLoaderUnload(), but we only have to do it once per class unload cycle. This commit moves the location of incGlobalClassUnloadID() to jitHookClassesUnload() which is called only once per class unload cycle.
=> Move location of incGlobalClassUnloadID()

runtime/vm/ContinuationHelpers.cpp
The second argument must be the *address* of a lock word.
Discovered because it wouldn't compile in a compressedrefs-only build:
```
[ 81%] Building CXX object runtime/vm/CMakeFiles/j9vm.dir/ContinuationHelpers.cpp.o
In file included from jdknext/build/compressed/vm/runtime/vmhook.h:26,
from jdknext/build/compressed/vm/runtime/vmhook_internal.h:10,
from jdknext/openj9/runtime/oti/j9.h:42,
from jdknext/openj9/runtime/vm/ContinuationHelpers.cpp:22:
jdknext/openj9/runtime/vm/ContinuationHelpers.cpp: In function ‘UDATA preparePinnedVirtualThreadForUnmount(J9VMThread*, j9object_t, BOOLEAN)’:
jdknext/openj9/runtime/oti/j9accessbarrier.h:697:47: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
? (j9objectmonitor_t)*(U_32 volatile *)(lwEA) \
^ …
```
=> Correct uses of J9_LOAD_LOCKWORD()

runtime/jcl/common/stdinit.c
`getPropertyList()` is declared but not used; noticed while considering #21200.
=> Remove unused function declaration

runtime/gc_vlhgc/WriteOnceCompactor.cpp, runtime/gc_vlhgc/WriteOnceCompactor.hpp
java stack slots in continuation structure can be
stack allocated reference (non heap reference), fixup non heap reference slot cpuld cause the assertion, so WriteOnceCompactor fixup java stack slots need to
check if the slot is heap reference.
fix: https://github.com/eclipse-openj9/openj9/issues/21036
=> Fix assertion in WriteOnceCompactor stackslot process

runtime/gc_base/IndexableObjectAllocationModel.cpp, runtime/gc_base/IndexableObjectAllocationModel.hpp, runtime/gc_base/RootScanner.cpp, runtime/gc_base/RootScanner.hpp, runtime/gc_glue_java/ArrayletObjectModel.cpp, runtime/gc_glue_java/ArrayletObjectModel.hpp, runtime/gc_glue_java/ArrayletObjectModelBase.cpp, runtime/gc_glue_java/ArrayletObjectModelBase.hpp, runtime/gc_stats/CopyForwardStats.hpp, runtime/gc_stats/MarkVLHGCStats.hpp, runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp, runtime/gc_vlhgc/CopyForwardScheme.cpp, runtime/gc_vlhgc/GlobalMarkingScheme.cpp, runtime/gc_vlhgc/HeapRegionDescriptorVLHGC.hpp, runtime/gc_vlhgc/VLHGCAccessBarrier.cpp
Along with new off-heap feature, double-mapping has been removed (off-heap can cover all of double-mapping cases with better performance), but in case enabling off-heap could not be set as default, re-introduce double-mapping as alternative backup.
1, double mapping is still part of array Discontiguous layout 
2, no share code between off-heap and double-mapping
=> Re-introduce double-mapping for non off-heap case

runtime/vm/JFRChunkWriter.cpp
The error was introduced in
https://github.com/eclipse-openj9/openj9/pull/20158.
=> Fix JFR checkpoint delta error

runtime/compiler/env/VMJ9.cpp, runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp, runtime/oti/j9nonbuilder.h, runtime/util/hshelp.c
Centralizes expression of extracting the kind of a native method handle from its flags.
=> Add and use new macro MN_GET_REFERENCE_KIND

runtime/compiler/x/codegen/J9CodeGenerator.cpp, runtime/compiler/x/codegen/J9TreeEvaluator.cpp, runtime/compiler/x/codegen/J9TreeEvaluator.hpp, test/functional/Java9andUp/playlist.xml
This PR implements Math.fma intrinsics on x86 with vfmadd instructions.
Issue: #7474
=> x86: Implement fma intrinsic

runtime/vm/JFRChunkWriter.cpp
The error was introduced in
https://github.com/eclipse-openj9/openj9/pull/20158.
Backport https://github.com/eclipse-openj9/openj9/pull/21205
=> (0.51) Fix JFR checkpoint delta error

runtime/gc_base/GCExtensions.hpp, runtime/gc_modron_startup/mmparseXXgc.cpp, runtime/gc_realtime/ConfigurationRealtime.cpp, runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp
Enable off-heap as default only Balanced GC
1, global flag isVirtualLargeObjectHeapEnabled = true on Balanced GC by
default.
2, if user specify -XXgc:disableVirtualLargeObjectHeap on Balanced GC
off heap can be disabled.
3, isVirtualLargeObjectHeapEnabled = false on the rest of
gcpolicies.
4, -XXgc:disableVirtualLargeObjectHeap/enableVirtualLargeObjectHeap
would be ignored on  the rest of gcpolicies.
5, if user specify -XXgc:enableVirtualLargeObjectHeap on
gcpolicy:metronome, jvm would output warmomg message
=> Enable off-heap as default on Balanced GC

runtime/util/vmargs.c
Fix a memory leak in a corner case `j9sysinfo_get_env("PATH")` failed
Passed [a personal build openjdk24_j9_sanity.functional_x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk24_j9_sanity.functional_x86-64_windows_Personal_testList_1/10/consoleFull)
closes https://github.com/eclipse-openj9/openj9/issues/21181
=> Fix a memory leak in a corner case j9sysinfo_get_env("PATH") failed

runtime/util/vmargs.c
Fix a memory leak in a corner case `j9sysinfo_get_env("PATH")` failed
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/21231
=> (0.51) Fix a memory leak in a corner case j9sysinfo_get_env("PATH") failed

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp, test/functional/Java11andUp/playlist.xml, test/functional/Java8andUp/playlist.xml, test/functional/Java8andUp/src/org/openj9/test/java/lang/invoke/Test_MethodHandleInfo.java
`MethodHandleNatives.resolve()` should work with a field at offset 0
A field at offset has `target` 0, the check `(0 != target)` is invalid;
Added a test.
closes https://github.com/eclipse-openj9/openj9/issues/21180
=> MethodHandleNatives.resolve() should work with a field at offset 0

runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp, test/functional/Java11andUp/playlist.xml, test/functional/Java8andUp/playlist.xml, test/functional/Java8andUp/src/org/openj9/test/java/lang/invoke/Test_MethodHandleInfo.java
`MethodHandleNatives.resolve()` should work with a field at offset 0
A field at offset has `target` 0, the check `(0 != target)` is invalid;
Added a test.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/21191
=> (0.51) MethodHandleNatives.resolve() should work with a field at offset 0

runtime/jcl/unix/syshelp.c, runtime/jcl/win32/syshelp.c
There are no callers with codepageProp NULL, and making this call wouldn't do anything anyway.
=> Remove obsolete code from getPlatformFileEncoding

runtime/gc_vlhgc/WriteOnceCompactor.cpp, runtime/gc_vlhgc/WriteOnceCompactor.hpp
java stack slots in continuation structure can be
stack allocated reference (non heap reference), fixup non heap reference slot cpuld cause the assertion, so WriteOnceCompactor fixup java stack slots need to
check if the slot is heap reference.
=> (0.51)Fix assertion in WriteOnceCompactor stackslot process

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
JvmtiMountTransition was added by mistake in
https://github.com/eclipse-openj9/openj9/pull/21084
Fixes: https://github.com/eclipse-openj9/openj9/issues/21186 https://github.com/eclipse-openj9/openj9/issues/21185
=> Remove JvmtiMountTransition annotation from Continuation.enter()

runtime/compiler/optimizer/DataAccessAccelerator.cpp
Disable DAA optimiziation if vector packed decimal facilities aren't available.
This is a temporary fix to enable off-heap enablement while we continue to
investigate the bug in non-vectorized pdload evaluator.
fixes: https://github.com/eclipse-openj9/openj9/pull/21220
=> Disable DAA optimization if vector facilities are not available

jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java, runtime/vm/BytecodeInterpreter.hpp, runtime/vm/bindnatv.cpp
Starting in Java 24 the ffi CaptureCallState and Critical options can be used together. When heap memory use is allowed through the critical option the captured call state should be returned to the given heap memory segment.
Related: https://github.com/eclipse-openj9/openj9/issues/21018
Related: https://github.com/eclipse-openj9/openj9/issues/21019
OpenJDK foreign test suite (failure is related to https://github.com/eclipse-openj9/openj9/issues/21018): https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/48403/
=> Support heap memory for ffi CaptureCallState

runtime/gc_vlhgc/VLHGCAccessBarrier.cpp
In presence of double mapping code (which we recently reintroduced), handling of discontiguous arrays (including 0-sized) ones should be done before handling offheap case. Otherwise offheap case will incorrectly use isDataAdjacentToHeader API, what could be a 0-size array, and that API assumes that array is contiguous.
=> Reorder handling of JNI critical between offheap and discontiguous

runtime/gc_vlhgc/VLHGCAccessBarrier.cpp
In presence of double mapping code (which we recently reintroduced), handling of discontiguous arrays (including 0-sized) ones should be done before handling offheap case. Otherwise offheap case will incorrectly use isDataAdjacentToHeader API, what could be a 0-size array, and that API assumes that array is contiguous.
Cherry pick https://github.com/eclipse-openj9/openj9/pull/21254
=> (0.51) Reorder handling of JNI critical between offheap and discontiguous

test/functional/cmdLineTests/jfr/playlist.xml
Related to: https://github.com/eclipse-openj9/openj9/issues/21242
=> Exclude jfr event tests on JDK11

jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
JvmtiMountTransition was added by mistake in
https://github.com/eclipse-openj9/openj9/pull/21084
Fixes: https://github.com/eclipse-openj9/openj9/issues/21186 https://github.com/eclipse-openj9/openj9/issues/21185
=> (0.51) Remove JvmtiMountTransition annotation from Continuation.enter()

test/functional/Valhalla/playlist.xml
This reverts https://github.com/eclipse-openj9/openj9/pull/20429
These Xdump options are no longer needed since the failure was resolved by https://github.com/eclipse-openj9/openj9/pull/20700
Fixes: #20189
=> Revert "Add -Xdump debug option for ValueTypeTests"

test/functional/JLM_Tests/src/j9vm/test/softmx/SoftmxAdvanceTest.java
Allow that test passes if heap contracts to exact SoftMx value (previously, required to be `less then`, what was unnecessarily strict)
=> Relax SoftMx test passing criteria

runtime/compiler/runtime/IProfiler.cpp, runtime/compiler/runtime/IProfiler.hpp
TR_IPBCDataFourBytes::getSumBranchCount returns the sum of the two branch counters. Internally these are stored as two 16 bit integers. getSumBranchCount is called only by TR_IProfiler::getSamplingCount which returns a int32_t. However, TR_IPBCDataFourBytes::getSumBranchCount sums up the two 16 bit integers as uint16_ts and returns a int16_t. This has the consequence of sometimes returning a negative number because of overflow.
This PR fixes this by consistently using int32_t.
=> Fix bug in TR_IPBCDataFourBytes::getSumBranchCount

runtime/compiler/control/CompilationThread.cpp
Currently, when the JIT cannot allocate code cache space anymore, it will set the `J9JIT_CODE_CACHE_FULL` flag in JITConfig and disable further compilation. However, class unloading can free code cache allocations allowing future JIT compilations to be performed.
This commit disables setting the `_disableFurtherCompilation` flag once the code cache runs out of space. Instead, it will check the `J9JIT_CODE_CACHE_FULL` flag to see if compilation requests should not even be queued. The difference is that `_disableFurtherCompilation` is never reset while `J9JIT_CODE_CACHE_FULL` is reset after code cache deallocations. This resetting can be disabled with `-Xjit:disableClearCodeCacheFullFlag`
=> Restart JIT activity when code cache allocations are freed

runtime/compiler/runtime/IProfiler.cpp, runtime/compiler/runtime/IProfiler.hpp
Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/21274
=> 0.51: Fix bug in TR_IPBCDataFourBytes::getSumBranchCount

runtime/j9vm/javanextvmi.cpp, runtime/oti/j9nonbuilder.h, runtime/oti/vm_api.h, runtime/vm/ContinuationHelpers.cpp
J9JavaVM is now retrieved from currentThread, simplifying the code.
=> Remove J9JavaVM from takeVirtualThreadListToUnblock's parameter list

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp, runtime/compiler/env/j9method.cpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/optimizer/J9EstimateCodeSize.cpp, runtime/compiler/optimizer/J9Inliner.hpp
To propagate arg info from callers of `HashMap.put`, `HashMap.get`, `HashMap.hash`, `Map.get`, `Map.put` and `Object.hashCode`, generating IL of their callers is necessary when called from an inlined method. This allows us to propagate prex arg info from caller and enable compile-time folding of fastIdentityHashCode calls during Value Propagation.
=> Enable peeking ILGen for inlined methods related to java/util/HashMap get/put operations.

jcl/src/java.base/share/classes/jdk/crac/Core.java, jcl/src/java.base/share/classes/openj9/internal/criu/InternalCRIUSupport.java, jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/CRIUTestUtils.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/DeadlockTest.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/EnvVarFileTest.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/SoftmxTest.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/TestCRIUFailurePath.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/TestDelayedOperations.java
`CRIUSupport` supports only one singleton instance
`InternalCRIUSupport` has only one singleton instance as well;
Updated test usages.
Related to
* https://github.com/eclipse-openj9/openj9/issues/21161
=> CRIUSupport supports only one singleton instance

buildenv/jenkins/variables/defaults.yml
Related changes to build base on XCode level rather os specified version. related: runtimes/infrastructure#8105. Also unnecessary additionalTestLables related to mac_10_11 removes as those nodes are not exists anymore and the fact that test framework set labels in logic. e.g here
Sigend-off-by: mahdi@ibm.com
=> replace os specific labels for mac aarch,x64 with sw.tool.xcode.15_2

runtime/codert_vm/arm64nathelp.m4, runtime/codert_vm/armnathelp.m4, runtime/codert_vm/cnathelp.cpp, runtime/codert_vm/pnathelp.m4, runtime/codert_vm/riscvnathelp.m4, runtime/codert_vm/xnathelp.m4, runtime/codert_vm/znathelp.m4, runtime/compiler/compile/J9AliasBuilder.cpp, runtime/compiler/compile/J9SymbolReferenceTable.cpp, runtime/compiler/compile/J9SymbolReferenceTable.hpp, runtime/compiler/ilgen/Walker.cpp, runtime/compiler/optimizer/TreeLowering.cpp, runtime/compiler/runtime/Runtime.cpp, runtime/compiler/runtime/asmprotos.h, runtime/jilgen/jilconsts.c, runtime/oti/j9nonbuilder.h
Previously, specifying an instance of a value type class on a `monitorenter` bytecode would result in an `IllegalMonitorStateException`; a `java.lang.IdentityException` must now be thrown instead.
This commit introduces a non-helper, `<isIdentityObject>`, that checks that the operand of a `TR::monent` instruction is an instance of an identity class rather than a value type class.  If it is a value type class, it throws an `IdentityException`.  The actual test is expanded to test the flags field of the object's class during the Tree Lowering optimization pass.
The result of `<isIdentityObject`> is tested on a `ZEROCHK` operation that is generated before the `monent` during IL generation.
This change includes only required functional changes that allow JIT-compiled code to detect whether it …
=> Throw IdentityException if operand of monent is a value type object

runtime/oti/j9nonbuilder.h, runtime/vm/JFRChunkWriter.hpp, runtime/vm/jfr.cpp, test/functional/cmdLineTests/jfr/playlist.xml
The "timeout" and "until" fields weren't correctly initialized.
Fixes: https://github.com/eclipse-openj9/openj9/issues/21242
Related: https://github.com/eclipse-openj9/openj9/pull/20885
=> Fix JFR ThreadPark support

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp, runtime/compiler/env/j9method.cpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/optimizer/J9EstimateCodeSize.cpp, runtime/compiler/optimizer/J9Inliner.hpp
This PR contributes #21157 for 0.51.
=> (0.51) Enable peeking ILGen for inlined methods related to java/util/HashMap get/put operations

runtime/compiler/env/ProcessorDetection.cpp, runtime/compiler/x/env/J9CPU.cpp, runtime/compiler/x/env/J9CPU.hpp
Reverts eclipse-openj9/openj9#21241
See https://github.com/eclipse-openj9/openj9/pull/21241#issuecomment-2707445838
=> Revert "x86: check xcr0 in AOT compiles"

runtime/j9vm/javanextvmi.cpp, runtime/oti/j9nonbuilder.h, runtime/oti/vm_api.h, runtime/oti/vmconstantpool.xml, runtime/vm/BytecodeInterpreter.hpp, runtime/vm/ContinuationHelpers.cpp, runtime/vm/intfunc.c, runtime/vm/monhelpers.c
- Enter/exit critical transition when preparing for unmount/re-mount pinned vthread.
- Fix Object.wait/notify logic.
- Allow pinned vthread to yield in normal path.
#20709 passed with this change using `-Xint -XX:+YieldPinnedVirtualThreads`
=> Fix hang on vthread unmount when -XX:+YieldPinnedVirtualThreads is enabled

jcl/src/java.base/share/classes/jdk/crac/Core.java, jcl/src/java.base/share/classes/openj9/internal/criu/InternalCRIUSupport.java, jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/CRIUTestUtils.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/DeadlockTest.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/EnvVarFileTest.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/SoftmxTest.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/TestCRIUFailurePath.java, test/functional/cmdLineTests/criu/src/org/openj9/criu/TestDelayedOperations.java
`CRIUSupport` supports only one singleton instance
`InternalCRIUSupport` has only one singleton instance as well;
Updated test usages.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/21225
=> (0.51) CRIUSupport supports only one singleton instance

runtime/oti/j9nonbuilder.h, runtime/vm/JFRChunkWriter.hpp, runtime/vm/jfr.cpp, test/functional/cmdLineTests/jfr/playlist.xml
The "timeout" and "until" fields weren't correctly initialized.
Fixes: https://github.com/eclipse-openj9/openj9/issues/21242
Related: https://github.com/eclipse-openj9/openj9/pull/20885
=> (0.51) Fix JFR ThreadPark support

doc/compiler/README.md, doc/compiler/control/ExternalOptions.md, runtime/compiler/control/DLLMain.cpp, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/J9Options.hpp, runtime/compiler/control/OptionsPostRestore.cpp, runtime/compiler/runtime/RelocationRuntime.cpp
This PR addresses https://github.com/eclipse-openj9/openj9/issues/21122.
The proposed change iterates over all `J9::ExternalOptions` and calls `FIND_AND_CONSUME_VMARG` on the ones that are consumed by the JIT, caching the arg index. This ensures that `-XX:-IgnoreUnrecognizedXXColonOptions` does not cause the JVM to terminate incorrectly.
Aside from the root cause of https://github.com/eclipse-openj9/openj9/issues/21122, there were several options that were only processed using `FIND_ARG_IN_VMARGS`, which would also run into the `-XX:-IgnoreUnrecognizedXXColonOptions` issue; this means that simply moving `checkArgsConsumed` as I suggested in https://github.com/eclipse-openj9/openj9/issues/21122 isn't a complete solution.
Closes https://github.com/eclipse-openj9/openj9/issues/21122
=> Find and consume all -X / -XX options relevant to the JIT

runtime/gc_base/RootScanner.hpp, runtime/gc_base/accessBarrier.cpp, runtime/gc_vlhgc/CopyForwardScheme.cpp, runtime/gc_vlhgc/VLHGCAccessBarrier.cpp, runtime/gc_vlhgc/WriteOnceCompactor.cpp
Improve API for displacement calculation of stack referenced arrays for offheap to rely on region flags to determine the type of the movement (evacuate vs sliding). Previously the movement type was determined by RootScanner. But unlike standard platform threads, Virtual Threads (Continuations) are not roots and their stack walker does not instantiate RootScanner.
Relying on region flags (of source object) works for both types of threads.
=> Displacement API for offheap using region flags

jcl/src/java.base/share/classes/java/lang/System.java
Related to https://github.com/eclipse-openj9/openj9/pull/21172
=> No need to check file.encoding.pkg during boot since it's not used

runtime/shared_common/CompositeCache.cpp
Port of https://github.com/eclipse-openj9/openj9/pull/21333
Fixes #21315
=> (0.51) Unprotect header when modifying extraStartupHints

runtime/compiler/x/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp
We need to use 32 bit compare because the top half of the size reg can contain
class pointer. On z, Class pointer is written to top half by IIHF in
genInitObjectHeader. I have updated the compare instruction on x as well to
avoid future issues related to garbage in top half of the size register.
=> Use 32bit compare for array size in inline array allocation sequence

runtime/vm/BufferWriter.hpp, runtime/vm/JFRChunkWriter.cpp, runtime/vm/JFRChunkWriter.hpp, runtime/vm/JFRWriter.hpp, runtime/vm/jfr.cpp
Note that NativeLibrary is only supported on Linux at this moment.
=> Add JFR ThreadDump support

runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp
Class MM_SparseVirtualMemory shouldbe killed at shutdown
=> Kill MM_SparseVirtualMemory at shutdown

jcl/src/java.base/share/classes/java/lang/J9VMInternals.java, test/functional/cmdLineTests/imageReaderInitializationTest/build.xml, test/functional/cmdLineTests/imageReaderInitializationTest/imageReaderInitializationTest.xml, test/functional/cmdLineTests/imageReaderInitializationTest/playlist.xml, test/functional/cmdLineTests/imageReaderInitializationTest/src/org/openj9/test/ImageReaderInitializationTest.java
This is to avoid being affected by a potential invalid java.home path.
Fixes: https://github.com/eclipse-openj9/openj9/issues/21105
=> Initialize ImageReader during boot

jcl/src/java.base/share/classes/java/lang/J9VMInternals.java, test/functional/cmdLineTests/imageReaderInitializationTest/build.xml, test/functional/cmdLineTests/imageReaderInitializationTest/imageReaderInitializationTest.xml, test/functional/cmdLineTests/imageReaderInitializationTest/playlist.xml, test/functional/cmdLineTests/imageReaderInitializationTest/src/org/openj9/test/ImageReaderInitializationTest.java
This is to avoid being affected by a potential invalid java.home path
Fixes: https://github.com/eclipse-openj9/openj9/issues/21105
=> (0.51) Initialize ImageReader during boot

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
=> x86: call cg->getCurrentBlock() instead of node->getBlock()

runtime/gc_base/IndexableObjectAllocationModel.cpp
In an unlikely case that Offheap is full, return NULL spine object, rather then valid spine object with NULL dataPtr.
This is the same how we handle individual arraylet region allocation failures.
=> return NULL object spine if offheap full

debugtools/DDR_VM/src/com/ibm/j9ddr/BytecodeGenerator.java, debugtools/DDR_VM/src/com/ibm/j9ddr/tools/ddrinteractive/plugins/DDRInteractiveClassLoader.java, jcl/src/java.base/share/classes/module-info.java.extra, jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/image/j9/ImageFactory.java, jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/plugins/impl/ClassScanner.java, jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/plugins/impl/PluginManagerImpl.java
This updates reading and generation of class bytecode to use the new classfile API available in Java 24 and up.
Validated by comparing the output of `javap -c -private -v` on all classes in the `com.ibm.j9ddr.vm29.pointer.generated` package before and after this change.
Also:
* Update `BytecodeGenerator` (correct max locals in `subOffset(long)`).
* Encapsulate uses of `objectweb.asm` within `ClassScanner`.
Fixes: #9990.
Fixes: #20938.
=> Use new classfile API to work with bytecode for Java 24+

test/functional/cmdLineTests/gcRegressionTests/gcRegressionTests.xml
Looks like -Xcheck:memory has a problem on x86 Mac platform preventing to run Balanced with enabled off-heap with default maximum heap size as 25% of RAM available on machine failing with Native OOM. I guess it forces Sparce Heap to be allocated in the physical memory instead of be mostly virtual. Size of the heap is not significant for this particular test, so it can be explicitly set to smaller value to avoid the problem. We are going to investigate -Xcheck:memory behaviour on x86 Mac.
=> Add -Xmx512m to -Xcheck:memory GC Regression tests

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
=> (0.51) x86: call cg->getCurrentBlock() instead of node->getBlock()

runtime/vm/BytecodeInterpreter.hpp, runtime/vm/ContinuationHelpers.cpp
[Correctly derive an inflated object monitor](https://github.com/eclipse-openj9/openj9/commit/52f247c234926f7094702b4447ff0be981b4bda4)
A null object monitor is being passed to `detachMonitorInfo`, which
leads to a segfault. In the inflated case, the object monitor is
correctly derived to prevent the segfault.
This fix helps the `LotsOfContendedMonitorEnter` test in #20705.
[Correctly handle notify before wait for virtual threads](https://github.com/eclipse-openj9/openj9/commit/539c353763f993e1450cc23346fbb9067662be9a)
If a notify is issued before wait, then there `waitingContinuations`
will be `NULL`. In this case, the notify steps should not be executed
since there are no virtual threads waiting, and
`waitingContinuations->vthread` will be NULL.
Addresses point 3 in the below Github …
=> Virtual Threads: Bug fixes for JEP491

runtime/vm/BytecodeInterpreter.hpp, runtime/vm/ContinuationHelpers.cpp
[Correctly derive an inflated object monitor](https://github.com/eclipse-openj9/openj9/commit/52f247c234926f7094702b4447ff0be981b4bda4)
A null object monitor is being passed to `detachMonitorInfo`, which
leads to a segfault. In the inflated case, the object monitor is
correctly derived to prevent the segfault.
This fix helps the `LotsOfContendedMonitorEnter` test in #20705.
[Correctly handle notify before wait for virtual threads](https://github.com/eclipse-openj9/openj9/commit/539c353763f993e1450cc23346fbb9067662be9a)
If a notify is issued before wait, then there `waitingContinuations`
will be `NULL`. In this case, the notify steps should not be executed
since there are no virtual threads waiting, and
`waitingContinuations->vthread` will be NULL.
Addresses point 3 in the below Github …
=> (0.51) Virtual Threads: Bug fixes for JEP491

runtime/vm/JFRChunkWriter.hpp, runtime/vm/JFRConstantPoolTypes.cpp, runtime/vm/ObjectMonitor.cpp, runtime/vm/jfr.cpp, test/functional/cmdLineTests/jfr/jfrevents.xml, test/functional/cmdLineTests/jfr/src/org/openj9/test/WorkLoad.java
- Fix Owner for JFR monitor enter
- Add tests to validate monitor enter events
Backport of https://github.com/eclipse-openj9/openj9/pull/21340
=> (0.51) Fix owner for JFR monitor enter

runtime/oti/ContinuationHelpers.hpp, runtime/oti/j9nonbuilder.h, runtime/vm/BytecodeInterpreter.hpp, runtime/vm/ContinuationHelpers.cpp
When a vthread is in a timed wait, it is added to the running queue
by a Java thread directly if the timeout elapses. In this case, we
need to ensure it is removed from any waiting list, as it will not
pass through the takeVirtualThreadListToUnblock path.
=> Fix issue with waiting vthreads

runtime/gc_vlhgc/VLHGCAccessBarrier.cpp
User currentThread, rather than walkThread when fetching omrVMThread and GC environment struct for debug message printing purposes in VLHGC indexableDataDisplacement.
If the walk thread is a Continuation, there is no omrVMThread struct associated with it.
=> currentThread for debug messages in indexableDataDisplacement

runtime/port/sysvipc/j9shmem.c, runtime/port/sysvipc/j9shsem_deprecated.c, runtime/port/zos390/j9hypervisor_systemz.h, runtime/port/zos390/j9sysinfo_helpers.h
These changes includes some of the uncategorized fixes, header fixes and the recommended __attribute__((packed)) notation usage that works with both Open XL and XLC.
=> Open XL attribute packed and misc fixes

runtime/oti/ContinuationHelpers.hpp, runtime/oti/j9nonbuilder.h, runtime/vm/BytecodeInterpreter.hpp, runtime/vm/ContinuationHelpers.cpp
When a vthread is in a timed wait, it is added to the running queue by a Java thread directly if the timeout elapses. In this case, we need to ensure it is removed from any waiting list, as it will not pass through the takeVirtualThreadListToUnblock path.
=> (0.51) Fix issue with waiting vthreads

runtime/gc_base/ReferenceChainWalker.cpp, runtime/gc_base/ReferenceChainWalker.hpp, runtime/gc_base/RootScanner.cpp, runtime/gc_base/RootScanner.hpp, runtime/gc_glue_java/CompactSchemeFixupObject.cpp, runtime/gc_glue_java/CompactSchemeFixupObject.hpp, runtime/gc_glue_java/ConcurrentMarkingDelegate.cpp, runtime/gc_glue_java/ConcurrentMarkingDelegate.hpp, runtime/gc_glue_java/HeapWalkerDelegate.cpp, runtime/gc_glue_java/MarkingDelegate.cpp, runtime/gc_glue_java/MarkingDelegate.hpp, runtime/gc_glue_java/MarkingSchemeRootMarker.cpp, runtime/gc_glue_java/MetronomeDelegate.cpp, runtime/gc_glue_java/MetronomeDelegate.hpp, runtime/gc_glue_java/ScavengerDelegate.cpp, runtime/gc_glue_java/ScavengerDelegate.hpp, runtime/gc_glue_java/ScavengerRootScanner.hpp, runtime/gc_glue_java/ScavengerThreadRescanner.hpp, runtime/gc_include/j9modron.h, runtime/gc_realtime/RealtimeMarkingSchemeRootMarker.hpp, runtime/gc_structs/CMakeLists.txt, runtime/gc_structs/ContinuationSlotIterator.cpp, runtime/gc_structs/ContinuationSlotIterator.hpp, runtime/gc_vlhgc/CopyForwardScheme.cpp, runtime/gc_vlhgc/CopyForwardScheme.hpp, runtime/gc_vlhgc/GlobalMarkCardScrubber.cpp, runtime/gc_vlhgc/GlobalMarkingScheme.cpp, runtime/gc_vlhgc/GlobalMarkingScheme.hpp, runtime/gc_vlhgc/WriteOnceCompactor.cpp, runtime/gc_vlhgc/WriteOnceCompactor.hpp
In order to supporting yield of pinned VirtualThread a couple of heap references have been added in chain of continuation structures, GC need to maintain(scan/update) these references.
1, new ContunuationSlotIterator to iterate all of the references
list of monitorRecord
list of jniMonitorRecord
vthread reference
ContunuationSlotIterator also contains state and related vmThread state (can be state_monitor_records or state_vthread) for assert check in doContinuationSlot() (monitor_records can be non heap reference), vmThread is for retrieving related carrier context during rootscanning.
2, two new methods doSlot() and doContinuationSlot() are introduced doSlot() would handle basic processing, which can be shared between doContinuationSlot() and doStackSlot().
doContinuationSlot() would …
=> (0.51) GC update for supporting yield of pinned VirtualThread(JEP491)

jcl/src/java.base/share/classes/java/lang/System.java, runtime/jcl/common/system.c, runtime/jcl/exports.cmake, runtime/jcl/uma/se11_exports.xml, runtime/oti/jclprots.h, runtime/vm/vmprops.c
Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/880
=> Use extensions System.initProperties to help init jdk11 properties

runtime/compiler/optimizer/J9EstimateCodeSize.cpp, runtime/compiler/optimizer/J9EstimateCodeSize.hpp
During Estimate Code Size, if we came across a callee that exceeded the bigCalleeThreshold, we would mark every method above the call chain as also too big. This would result in removal of call targets above the callee marked too big. To get around this issue, we utilize the new field _bigCalleesSize that is set when a callee exceeds the big callee threshold, and is used to adjust the analyzed size of the methods above the big callee's level.
This is a follow up work for #20904, which helped significantly reduce the amount of estimation done during ECS.
=> Prevent callers of big callees getting marked as big during ECS

jcl/src/java.base/share/classes/java/lang/Access.java
JDK25 JavaLangAccess removed `exit(int status)`
Accommodate upstream change https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/6e164eab87017808b9e066c0b8c3b07407f1c68f
=> JDK25 JavaLangAccess removed exit(int status)

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
Reverts #21344 and commit 1bae589 from #21282 due to performance regression.
Did not revert all commits from #21282 because they include improvements for Vectorized HashCode.
=> (0.51) Revert "x86: Implement String.hashCode with vectorizedHashCode()"

jcl/src/java.base/share/classes/java/lang/System.java, runtime/jcl/common/system.c, runtime/jcl/exports.cmake, runtime/jcl/uma/se11_exports.xml, runtime/oti/jclprots.h, runtime/vm/vmprops.c
Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/880
Cherry pick https://github.com/eclipse-openj9/openj9/pull/21357
=> (0.51) Use extensions System.initProperties to help init jdk11 properties

runtime/oti/vmconstantpool.xml, runtime/vm/BytecodeInterpreter.hpp
- Throw InterruptedException on return fom vthread wait if interrupted field is set
- Add timeout value to vthread object
Backport of #21361
=> (v0.51.0) Fix Object.wait logic

runtime/vm/ContinuationHelpers.cpp, runtime/vm/monhelpers.c, runtime/vm/vmthread.cpp
Currently, there are timing holes between
JVM_TakeVirtualThreadListToUnblock and monitor deflation. A monitor can
be deflated while it is being accessed in
JVM_TakeVirtualThreadListToUnblock. This leads to a NULL dereference
causing a segfault. Adding more synchronization will cause a
significant overhead in the object monitor exit path. Until an
efficient solution is developed, the policy to never deflate will be
employed in order to support JEP491. Since the current JEP491
implementation always inflates monitors before usage, deflating will be
counter-productive.
Also, added a null check for syncObjectMonitor in
JVM_TakeVirtualThreadListToUnblock to ensure that the monitor is
inflated before operations are performed on it.
Operations on J9ObjectMonitor's virtualThreadWaitCount field may …
=> JEP491: Never Deflate Monitors and Synchronize virtualThreadWaitCount

runtime/vm/ContinuationHelpers.cpp, runtime/vm/monhelpers.c, runtime/vm/vmthread.cpp
Currently, there are timing holes between
JVM_TakeVirtualThreadListToUnblock and monitor deflation. A monitor can
be deflated while it is being accessed in
JVM_TakeVirtualThreadListToUnblock. This leads to a NULL dereference
causing a segfault. Adding more synchronization will cause a
significant overhead in the object monitor exit path. Until an
efficient solution is developed, the policy to never deflate will be
employed in order to support JEP491. Since the current JEP491
implementation always inflates monitors before usage, deflating will be
counter-productive.
Also, added a null check for syncObjectMonitor in
JVM_TakeVirtualThreadListToUnblock to ensure that the monitor is
inflated before operations are performed on it.
Operations on J9ObjectMonitor's virtualThreadWaitCount field may …
=> (0.51) JEP491: Never Deflate Monitors and Synchronize virtualThreadWaitCount

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
CRIU restores `CRIUSupport(Path imageDir)` constructor
Support the original `CRIUSupport(Path imageDir)` constructor API with a singleton `InternalCRIUSupport` instance.
Related to
* https://github.com/eclipse-openj9/openj9/issues/21386
=> CRIU restores CRIUSupport(Path imageDir) constructor

runtime/vm/jvminit.c
Previously, continuation options are parsed after thread parsing which
means deflation policies do not take effect. This PR corrects this.
=> Move arg parsing of continuation options

runtime/compiler/optimizer/J9EstimateCodeSize.cpp, runtime/compiler/optimizer/J9EstimateCodeSize.hpp
Reverts eclipse-openj9/openj9#21364
See https://github.com/eclipse-openj9/openj9/issues/21397
=> Revert "Prevent callers of big callees getting marked as big during ECS"

runtime/vm/BytecodeInterpreter.hpp
A frame needs to be built before attempting a stack walk in vthread monenter to find owned monitors. Failure to do so may result in a crash.
=> Build frame in blocking vthread monenter

jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
CRIU restores `CRIUSupport(Path imageDir)` constructor
Support the original `CRIUSupport(Path imageDir)` constructor API with a singleton `InternalCRIUSupport` instance.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/21401
=> (0.51) CRIU restores CRIUSupport(Path imageDir) constructor

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
In x86 ArrayStoreCHK, with OffHeap the destination tree evaluation is deferred but its subtrees still need to be evaluated early especially if subtrees are complex and might introduce more instructions and virtual-registers.
WIP: Testing
=> Evaluate destination subtrees early when deferring destination eval

runtime/compiler/z/codegen/J9TreeEvaluator.cpp
Following https://github.com/eclipse-openj9/openj9/pull/21195#discussion_r1986140734, this PR includes better checks for tree shapes for ArrayStoreCHK evaluation with OffHeap.
It also adds an assert for unexpected shapes this ensures if tree shapes change in the future (eg enabling commoning) this can be updated (revert the `deferDestinationEvaluation` code).
Testing...
=> Guard ArrayStoreCHK early subtree eval tree shape

runtime/compiler/control/CompilationThread.cpp
Cherry-pick of https://github.com/eclipse-openj9/openj9/pull/21453
=> 0.51: Only allow one active comp thread pre-checkpoint under -XX:+DebugOnRestore

runtime/port/zos390/j9csrsi.h
This addresses the missing functional declaration error thrown with Open XL on z/OS.
---
Trying to build with latest openj9/master and noticing a few missing changes that are needed by Open XL, adding them as I find them.
=> Add j9csrsi_wrp function declaration for Open XL

test/functional/cmdLineTests/criu/playlist.xml, test/functional/cmdLineTests/jvmtitests/playlist.xml
cmdLineTester_criu_nonPortableRestoreJDK20Up
cmdLineTester_jvmtitests_Java21andUp
Issues
https://github.com/eclipse-openj9/openj9/issues/21443 https://github.com/eclipse-openj9/openj9/issues/21444
=> Exclude a couple of tests on plinux jdk24+

buildenv/jenkins/variables/defaults.yml
Related changes to build base on XCode level rather os specified version. related: runtimes/infrastructure#8105. Also unnecessary additionalTestLables related to mac_10_11 removes as those nodes are not exists anymore and the fact that test framework set labels in logic. e.g here
Cherry pick https://github.com/eclipse-openj9/openj9/pull/21283
=> (0.51) replace os specific labels for mac aarch,x64 with sw.tool.xcode.15_2

test/functional/Java21andUp/playlist.xml
Issue https://github.com/eclipse-openj9/openj9/issues/21477
=> Exclude Jep425Tests_testVirtualThread on plinux,aix for jdk24+

test/functional/cmdLineTests/criu/playlist.xml, test/functional/cmdLineTests/jvmtitests/playlist.xml
cmdLineTester_criu_nonPortableRestoreJDK20Up
cmdLineTester_jvmtitests_Java21andUp
Issues
https://github.com/eclipse-openj9/openj9/issues/21443 https://github.com/eclipse-openj9/openj9/issues/21444
Cherry pick https://github.com/eclipse-openj9/openj9/pull/21467
=> (0.51) Exclude a couple of tests on plinux jdk24+

test/functional/cmdLineTests/imageReaderInitializationTest/playlist.xml
Afaik `-Xdump` by itself doesn't do anything.
Fixes https://github.com/eclipse-openj9/openj9/issues/21471
=> Remove -Xdump option from cmdLineTester_imageReaderInitializationTest

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp, runtime/compiler/env/j9method.cpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/optimizer/J9EstimateCodeSize.cpp
ConcurrentHashMap.get is similar in nature to HashMap.get operations, and we can benefit from compile-time folding of various queries such as Object.hashCode() if the object being passed as arg is known and fixed. For that to be possible, we need to ensure that the caller method of ConcurrentHashMap.get() undergoes peeking IL-gen so that the object information can be passed down and used.
~In Draft state until further testing is done.~
=> Propagate known key info to ConcurrentHashMap.get

test/functional/Java21andUp/playlist.xml
Issue https://github.com/eclipse-openj9/openj9/issues/21477
Cherry pick https://github.com/eclipse-openj9/openj9/pull/21478
=> (0.51) Exclude Jep425Tests_testVirtualThread on plinux,aix for jdk24+

runtime/vm/jvminit.c
Restore the change of error reporting
Restore to the standard function setErrorJ9dll() to complete error report(missed J9VMDllLoadInfo.loadFlags).
=> Revert the change of error reporting by PR #20387

runtime/j9vm/exports.cmake, runtime/j9vm/javanextvmi.cpp, runtime/redirector/forwarders.m4
JDK25 adds `JVM_NeedsClassInitBarrierForCDS`
No implementation is required for OpenJ9.
Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/971
=> JDK25 adds JVM_NeedsClassInitBarrierForCDS

runtime/vm/jfr.cpp
areJFRBuffersReadyForWrite checks the thread local JFR buffer which has
already been free'd during shutdown, so that is replaced by the other
two checks directly.
=> Fix JFR data not being flushed during VM shutdown

runtime/compiler/control/J9Options.cpp, runtime/compiler/control/rossa.cpp
Port of #21394 for 0.51
Issue: #21371
=> (0.51) CRIU: JIT should generate portable code by default

debugtools/DDR_VM/src/com/ibm/j9ddr/StructureReader.java, debugtools/DDR_VM/src/com/ibm/j9ddr/tools/PointerGenerator.java, debugtools/DDR_VM/src/com/ibm/j9ddr/tools/StructureStubGenerator.java
On AIX, `/usr/include/sys/var.h` includes a declaration of `struct var`; without this change, that would lead to the generation of `var.java` containing `class var ...` which would not compile.
=> Remove unwanted type names found in superset.dat

runtime/vm/jfr.cpp
areJFRBuffersReadyForWrite checks the thread local JFR buffer which has already been free'd during shutdown, so that is replaced by the other two checks directly.
=> (0.51) Fix JFR data not being flushed during VM shutdown

runtime/vm/FastJNI.cpp
Replace improper use of tab with space.
=> Correct spelling of implementation

test/functional/DDR_Test/tck_ddrext.xml, test/functional/Java14andUp/build.xml, test/functional/Java14andUp/playlist.xml, test/functional/Java14andUp/src/org/openj9/test/jep358/NPEMessageTests.java, test/functional/JavaAgentTest/build.xml, test/functional/JavaAgentTest/playlist.xml, test/functional/UnsafeTest/build.xml, test/functional/UnsafeTest/playlist.xml, test/functional/UnsafeTest/src_90/org/openj9/test/unsafe/UnsafeTestBase.java, test/functional/cmdLineTests/J9security/build.xml, test/functional/cmdLineTests/J9security/j9SecurityTest.xml, test/functional/cmdLineTests/J9security/jsr292.policy, test/functional/cmdLineTests/J9security/playlist.xml, test/functional/cmdLineTests/J9security/src/com/ibm/j9/jsr292/indyn/TestJSR292.java, test/functional/cmdLineTests/lockWordAlignment/alignment.xml, test/functional/cmdLineTests/lockWordAlignment/alignmentSettings.mk, test/functional/cmdLineTests/lockWordAlignment/build.xml, test/functional/cmdLineTests/lockWordAlignment/playlist.xml, test/functional/cmdLineTests/lockWordAlignment/src/CreateTestObjectJar.java, test/functional/cmdLineTests/lockWordAlignment/src/IntLongObjectAlignmentTestGenerator.java
JDK25 removed `jdk.internal.org.objectweb.asm` package and classes
Modified the tests to use `asm` jar and its `org.objectweb.asm.*` classes to accommodate all Java levels;
Disabled `JavaAgentTest` for JDK25+ temporarily;
Disabled `lockWordAlignment` `Check whether Object contains necessary private fields if any` temporarily.
Related to
* https://github.com/eclipse-openj9/openj9/issues/21463
=> JDK25 removed jdk.internal.org.objectweb.asm package and classes

runtime/gc_base/IndexableObjectAllocationModel.cpp
During slow path allocation, when we initialize dataAddr field for
adjacent data case, we now check if dataAddr is present first, before
checking if data should be adjacent.
Previously, we would check adjacency first, which could read bogus
value. Relatively benign, since we would still correctly skip
initializing dataAddr, because it's not present.
But in abnormal cases with say class slot corruption, we could end up
crashing prematurely in adjacency check even if dataAddr is not present
(what would be confusing), rather then asserting later that class slot
is corrupted.
=> Reorder is-present and should-be-adjacent checks in alloc path

runtime/vm/BytecodeInterpreter.hpp
=> (v0.51.0) Reset the virtual thread's notified field before releasing Object monitor

runtime/jvmti/jvmtiRawMonitor.c
Our current implementation uses `J9VMThread->ownedMonitorCount` to
track both object monitors and raw monitors owned by a virtual thread.
The RI pins a virtual thread while it holds a raw monitor. Our current
implementation allows a virtual thread to be unmounted and remounted
while holding a raw monitor. This causes `J9ThreadMonitor->owner` to
become invalid, as the virtual thread's `J9Thread` changes during the
unmount and remount phases.
Currently, there is no way to track which raw monitors a virtual
thread owns. This prevents us from fixing `J9ThreadMonitor->owner`
for raw monitors when a virtual thread is unmounted and remounted.
To match the RI, `continuationPinCount` will be used instead of
`ownedMonitorCount` to pin a virtual thread when it acquires a raw
monitor.
Fixes: #21409
=> Pin virtual threads while they hold raw monitors

runtime/compiler/optimizer/J9EstimateCodeSize.cpp, runtime/compiler/optimizer/J9EstimateCodeSize.hpp
This PR delivers the changes in ~#21364~ #21465 for 0.51.
=> (0.51) Prevent callers of big callees getting marked as big during ECS

runtime/jcl/common/jdk_jfr_internal_JVM_jdk21andUp.cpp, runtime/jcl/exports.cmake
JDK25 added `jdk.jfr.internal.JVM.isProduct()Z`
Re-group the existing JFR exports.
closes https://github.com/eclipse-openj9/openj9/issues/21496
=> JDK25 added jdk.jfr.internal.JVM.isProduct()Z

runtime/codert_vm/cnathelp.cpp, runtime/oti/vm_api.h, runtime/vm/BytecodeInterpreter.hpp, runtime/vm/ContinuationHelpers.cpp
Remove use of objectMonitorInflate on lock that current thread doesn't own.
Change to use of FLC bit to signal owner thread to inflate the monitor
when it exits the monitor.
Use CAS operation to ensure only one thread can update the lockword flag bits
to contended flatlock and ignore current lock learning state.
Lock reservation is cancelled before inflation/FLC bit set.
=> Redesign preparePinnedVirtualThreadForUnmount logic

runtime/jvmti/jvmtiRawMonitor.c
Our current implementation uses `J9VMThread->ownedMonitorCount` to
track both object monitors and raw monitors owned by a virtual thread.
The RI pins a virtual thread while it holds a raw monitor. Our current
implementation allows a virtual thread to be unmounted and remounted
while holding a raw monitor. This causes `J9ThreadMonitor->owner` to
become invalid, as the virtual thread's `J9Thread` changes during the
unmount and remount phases.
Currently, there is no way to track which raw monitors a virtual
thread owns. This prevents us from fixing `J9ThreadMonitor->owner`
for raw monitors when a virtual thread is unmounted and remounted.
To match the RI, `continuationPinCount` will be used instead of
`ownedMonitorCount` to pin a virtual thread when it acquires a raw
monitor.
Fixes: #21409 …
=> (0.51) Pin virtual threads while they hold raw monitors

runtime/gc_base/IndexableObjectAllocationModel.cpp, runtime/gc_base/IndexableObjectAllocationModel.hpp
Prepare and store is-data-adjacent value in the constructor of AllocationModel, and then reuse the value later in initializeAllocateDescription and initializeIndexableObject.
=> Prepare and store is-data-adjacent early

runtime/gc_base/IndexableObjectAllocationModel.cpp
During slow path allocation, when we initialize dataAddr field for adjacent data case, we now check if dataAddr is present first, before checking if data should be adjacent.
Previously, we would check adjacency first, which could read bogus value. Relatively benign, since we would still correctly skip initializing dataAddr, because it's not present.
But in abnormal cases with say class slot corruption, we could end up crashing prematurely in adjacency check even if dataAddr is not present (what would be confusing), rather then asserting later that class slot is corrupted.
Cherry pick https://github.com/eclipse-openj9/openj9/pull/21493
=> (0.51) Reorder is-present and should-be-adjacent checks in alloc path

runtime/codert_vm/cnathelp.cpp, runtime/oti/vm_api.h, runtime/vm/BytecodeInterpreter.hpp, runtime/vm/ContinuationHelpers.cpp
Remove use of objectMonitorInflate on lock that current thread doesn't own. Change to use of FLC bit to signal owner thread to inflate the monitor when it exits the monitor.
Use CAS operation to ensure only one thread can update the lockword flag bits to contended flatlock and ignore current lock learning state.
Lock reservation is cancelled before inflation/FLC bit set.
backport of #21459
=> (v0.51.0) Redesign preparePinnedVirtualThreadForUnmount logic

runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp
Reference count check was added to avoid commoning of dataAddr pointer (first child of address node) by preventing early evaluation. However, this might create functional issues if a later instruction expects the child, and/or siblings of dataAddr pointer to be evaluated into a register. This change prevents commoning of dataAddr pointer while maintaining functional correctness.
Port of: https://github.com/eclipse-openj9/openj9/pull/21454
=> (0.51) Fix early evaluation logic for address node of BCDCHK

runtime/gc_verbose_old/VerboseFileLoggingOutput.cpp, runtime/oti/j9port_generated.h, runtime/rasdump/dmpagent.c, runtime/rasdump/trigger.c, runtime/rastrace/trclog.c, runtime/tests/port/j9strTest.c, runtime/vm/jvminit.c
There's no need to expect users to provide a pointer to the port library (the macro already assumes access via `PORTLIB`); this avoids possible problems being used with a different, incompatible argument.
At least three parameters must be supplied (so the function in `omrstr.c` receives at least four).
Tidy up whitespace.
=> Improve definition of j9str_set_token()

runtime/vm/monhelpers.c
#21459 updated the behaviour of blocking monitor to use FLC flag instead of incorrectly inflating.
This adds the matching notify call to monitor exit path.
=> Notify vthread unblocker on monitorExit from flatlock with FLC flag

runtime/vm/monhelpers.c
=> (v0.51.0) Notify vthread unblocker on monitorExit from flatlock with FLC flag

runtime/vm/ContinuationHelpers.cpp
- Adds missing monitor exit for flatlock case.
Backport of #21527
=> (v0.51.0) Fixes preparePinnedVirtualThreadForUnmount assertion

runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/optimizer/J9Inliner.hpp
- Return true only if the call is actually transformed.
- Skip `performTransformation()` for indirect calls.
- Trace if inlining fails after `performTransformation()`.
In a separate preparatory commit, `trivialInliningOnly()` is overridden to return true for targets satisfying `isInlineableJNI()`, which is required to allow `tryToInlineTrivialMethod()` to return false when it fails to transform calls to those targets.
This depends on eclipse-omr/omr#7702
=> Make some minor improvements to tryToInlineTrivialMethod()

runtime/vm/ContinuationHelpers.cpp
The ownedMonitorCount includes the number of re-entries to the same monitor whereas monitorCount does not.
=> Update monitor count assertions

runtime/gc_vlhgc/CopyForwardScheme.cpp, runtime/gc_vlhgc/CopyForwardScheme.hpp, runtime/gc_vlhgc/CopyScanCacheChunkVLHGC.cpp, runtime/gc_vlhgc/CopyScanCacheChunkVLHGC.hpp, runtime/gc_vlhgc/CopyScanCacheListVLHGC.cpp
Currently we preallocate all copy-scan-caches upfront based on the maximum heap size. This unnecessarily slows down startup time and increases footprint during during ramp-up.
Now, we create only small set at startup and dynamically increase during GC as we need it.
The code is mostly borrowed from Scavenger, except we don't look at heap size, but only at GC thread count during both initial and incremental increase (the goal is just not to create contention during incremental increase).
=> Dynamic copy-cache allocation in Balanced

runtime/compiler/net/LoadSSLLibs.cpp
When encryption is enabled for JITServer, the server will attempt to load the crypto and ssl libraries. The server maintains a list of library names (ordered by priority). In the near future OpenJ9 JVM distributions will embed crypto/ssl libraries with specific names. This commit adds those specific names to the list
of libraries that the server will be looking for.
=> JITServer support for ssl libs name changes

runtime/rasdump/dmpsup.c, runtime/rasdump/rasdump_internal.h
Installations of newer releases of Dynatrace capture the original `core_pattern` in a fixed location.
Generalize the tag in `2CISYSINFO` for `original_core_pattern` so it doesn't include a partial path that could be misleading.
Fixes: https://github.com/eclipse-openj9/openj9/issues/21554.
=> Print Dynatrace core_pattern location in java dumps

runtime/compiler/optimizer/DataAccessAccelerator.cpp
Previously, the non-vectorized DAA path was mistakenly enabled along with the vectorized DAA path for off-heap. Now, only the vectorized DAA path is enabled as intended.
=> Fix bug with DAA enablement conditions for off-heap memory

runtime/gc_vlhgc/InterRegionRememberedSet.cpp, runtime/gc_vlhgc/InterRegionRememberedSet.hpp
Currently, all Control Blocks (kind of a header structure) for Remembered Set Buffers, for all possible regions, are allocated upfront with one big malloc. This is suboptimal from footprint perspective. Also, in extreme cases with very large heaps the allocation may not even succeed.
We will now allocate that space as Virtual Memory which will be lazily committed as needed (as regions are first time used and their RSCL is first time initialized).
RS Buffers themselves are already allocated incrementally/gradually, as regions are first time used, although still malloced. In future, we may want to allocate them as virtual memory too, but currently that is less important (relative to Control Blocks) due to their incremental allocation.
=> Allocate RS Control Blocks for Balanced as virtual memory

runtime/vm/JFRChunkWriter.cpp, runtime/vm/JFRChunkWriter.hpp, runtime/vm/JFRConstantPoolTypes.hpp, test/functional/cmdLineTests/jfr/jfrevents.xml
This change adds support for the JFR GC Heap Configuration Event.
Backport of https://github.com/eclipse-openj9/openj9/pull/21382
=> (0.51) Add JFR GCHeapConfiguration Event

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/gccheck/CheckEngine.java
Currently Check Engine code failed at attempt to read class data if it is unexpected garbage.
=> Prevent DDR code crash on reading garbage

jcl/src/java.base/share/classes/jdk/crac/Core.java, jcl/src/java.base/share/classes/openj9/internal/criu/InternalCRIUSupport.java, jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/DiagnosticUtils.java
CRIU Jcmd `CRIU.checkpoint` takes key/value pairs as system properties
`InternalCRIUSupport` singleton instance overrides checkpoint parameters with current system properties;
Added a Jcmd command `CRIU.checkpoint` for CRIU enabled JVM;
Added `InternalCRIUSupport.setCheckpointDefaultParams()` to allow Jcmd `CRIU.checkpoint` and `JDK.checkpoint` work without additional key/value pairs;
Jcmd commands `CRIU.checkpoint` takes key/value pairs as system properties, the keys are added prefix `"openj9.internal.criu."`;
`JDK.checkpoint` doesn't take any parameters.
closes https://github.com/eclipse-openj9/openj9/issues/21161
=> CRIU Jcmd CRIU.checkpoint takes key/value pairs as system properties

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/DiagnosticUtils.java
JFR dump to Jcmd current working directory by default
If the filename supplied is not an absolute path, `Jcmd` current work directory is used instead of the target VM location;
Throw an error if the duration option doesn't have time units.
Related to
* https://github.com/eclipse-openj9/openj9/issues/21069
=> JFR dump to Jcmd current working directory by default

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/gccheck/CheckEngine.java
DDR intends to read class slot from the object in the heap. However this slot can contain unexpected value (garbage). Use UDATA class to prevent failure.
=> Prevent DDR failed during reading garbage

runtime/gc_base/StackSlotValidator.cpp, runtime/gc_base/StackSlotValidator.hpp, runtime/gc_glue_java/ConcurrentMarkingDelegate.cpp, runtime/gc_glue_java/MarkingDelegate.cpp, runtime/gc_glue_java/MetronomeDelegate.cpp, runtime/gc_glue_java/ScavengerDelegate.cpp, runtime/gc_glue_java/ScavengerDelegate.hpp, runtime/gc_vlhgc/CopyForwardScheme.cpp, runtime/gc_vlhgc/GlobalMarkingScheme.cpp, runtime/vm/ContinuationHelpers.cpp
- validStackSlot for scanning/fixing java stack slots of continuations.
- reuse stackThread.currentContinuation (stackThread is "fake Thread", which is created just for walkJavaStackSlots of the continuation)for recording related J9VMContinuation structure.
- report related J9VMContinuation when validStackSlot fails during walkJavaStackSlots of the continuations.
=> Add validStackSlot for all of doStackSlots

runtime/vm/ObjectMonitor.cpp
The changes address the regression seen in https://github.ibm.com/runtimes/javanext/issues/510.
Backport of https://github.com/eclipse-openj9/openj9/pull/21572
=> (0.52) Fix for CleanedLibertyStartupDT, CleanedLibertyStartupDT7 and CleanedLibertyStartupDT10 Startup regression

runtime/oti/j9nonbuilder.h, runtime/vm/BytecodeInterpreter.hpp
=> Trigger contended object monitor enter event for virtual threads

runtime/gc_base/StackSlotValidator.cpp, runtime/gc_base/StackSlotValidator.hpp, runtime/gc_glue_java/ConcurrentMarkingDelegate.cpp, runtime/gc_glue_java/MarkingDelegate.cpp, runtime/gc_glue_java/MetronomeDelegate.cpp, runtime/gc_glue_java/ScavengerDelegate.cpp, runtime/gc_glue_java/ScavengerDelegate.hpp, runtime/gc_vlhgc/CopyForwardScheme.cpp, runtime/gc_vlhgc/GlobalMarkingScheme.cpp, runtime/vm/ContinuationHelpers.cpp
- validStackSlot for scanning/fixing java stack slots of continuations.
- reuse stackThread.currentContinuation (stackThread is "fake Thread", which is created just for walkJavaStackSlots of the continuation)for recording related J9VMContinuation structure.
- report related J9VMContinuation when validStackSlot fails during walkJavaStackSlots of the continuations.
=> (0.52)Add validStackSlot for all of doStackSlots

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/DiagnosticUtils.java
JFR dump to Jcmd current working directory by default
If the filename supplied is not an absolute path, `Jcmd` current work directory is used instead of the target VM location;
Throw an error if the duration option doesn't have time units.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/21076
=> (0.51) JFR dump to Jcmd current working directory by default

runtime/gc_base/GCExtensions.cpp, runtime/gc_base/GCExtensions.hpp, runtime/gc_modron_startup/mminit.cpp, runtime/gc_modron_startup/mmparse.cpp
In the case if maximum heap size is not specified and taken by default and initial heap size is specified and initial value is larger than default maximum increase maximum heap size to match initial size.
Related https://github.com/eclipse-openj9/openj9/issues/14386
=> Adjust max heap size if -Xms is set higher explicitly

runtime/cmake/caches/aix_ppc-64.cmake, runtime/cmake/caches/linux_390-64.cmake
Noticed while reviewing https://github.com/eclipse-openj9/openj9/pull/21598.
=> Correct spelling of "variables"

debugtools/DDR_VM/src/com/ibm/j9ddr/StructureHeader.java
To avoid warnings building DDR tools in newer Java versions.
=> Suppress "this-escape" warning for StructureHeader

buildenv/jenkins/variables/defaults.yml
See https://github.com/eclipse-openj9/openj9/issues/20402#issuecomment-2795613593.
Use temurin builds for Java 24 until an OpenJ9 release is available.
Also remove configuration information for jdk23.
=> Update boot JDK version for jdknext

jcl/src/java.base/share/classes/java/lang/Access.java
JDK25 removes `JavaLangAccess.virtualThreadDelayedTaskSchedulers()`
This fixes https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_OpenJDK/773/consoleFull
```
00:06:32  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:610: error: method does not override or implement a method from a supertype
00:06:32  	@Override
00:06:32  	^
00:06:32  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:612: error: cannot find symbol
00:06:32  		return VirtualThread.delayedTaskSchedulers();
00:06:32  		                    ^
00:06:32    symbol:   method delayedTaskSchedulers()
``` …
=> JDK25 removes JavaLangAccess.virtualThreadDelayedTaskSchedulers()

jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/DiagnosticUtils.java
JFR dump to Jcmd current working directory by default
If the filename supplied is not an absolute path, `Jcmd` current work directory is used instead of the target VM location;
Throw an error if the duration option doesn't have time units.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/21076
=> (0.52) JFR dump to Jcmd current working directory by default

jcl/src/java.base/share/classes/jdk/crac/Core.java, jcl/src/java.base/share/classes/openj9/internal/criu/InternalCRIUSupport.java, jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/DiagnosticUtils.java
CRIU Jcmd `CRIU.checkpoint` takes key/value pairs as system properties
`InternalCRIUSupport` singleton instance overrides checkpoint parameters with current system properties;
Added a Jcmd command `CRIU.checkpoint` for CRIU enabled JVM;
Added `InternalCRIUSupport.setCheckpointDefaultParams()` to allow Jcmd `CRIU.checkpoint` and `JDK.checkpoint` work without additional key/value pairs;
Jcmd commands `CRIU.checkpoint` takes key/value pairs as system properties, the keys are added prefix `"openj9.internal.criu."`;
`JDK.checkpoint` doesn't take any parameters.
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/21351
=> (0.52) CRIU Jcmd CRIU.checkpoint takes key/value pairs as system properties

buildenv/jenkins/variables/defaults.yml
There is no Java 24 version available for AIX via the Adoptium API.
=> Update AIX Java 24 boot jdk

runtime/vm/VMSnapshotImpl.cpp
Currently, the object refs in the unnamed module for the system classloader are not reset before the snapshot is created. During the restore phase, this leads to an InternalError in RCP JDK21+ since the object refs point to stale objects which no longer exist.
To resolve the InternalError, the object refs in the unnamed module are reset before the snapshot is created.
Exception in thread "(unnamed thread)" java/lang/InternalError:
module is already set in the unnamedModuleForSystemLoader
at jdk/internal/loader/BootLoader.setBootLoaderUnnamedModule0
at jdk/internal/loader/BootLoader. (java.base@21/BootLoader.java:68)
at java/lang/ClassLoader.initializeClassLoaders
(java.base@21/ClassLoader.java:187)
at java/lang/Thread.initialize (java.base@21/Thread.java:3108)
at java/lang/Thread. …
=> RCP: Reset object refs in unnamed module for system loader

runtime/compiler/optimizer/J9ValuePropagation.cpp, runtime/compiler/optimizer/J9ValuePropagation.hpp
When ValuePropagation is able to obtain the object info of the receiver MethodHandle object, we can refine the invokeBasic call, and possibly inline the refined method and its callees. The refined invokeBasic calls get stored in a new VP field _refinedMethodHandleINLMethodsToInline, and handled during delayed VP transformations.
=> Refine MethodHandle invokeBasic INL calls during ValuePropagation

runtime/vm/BytecodeInterpreter.hpp, runtime/vm/ContinuationHelpers.cpp
- Correctly unwind the thread stack frame when re-mounting from J9VM_CONTINUATION_RETURN_FROM_SYNC_METHOD
- Ensure that all access to blockedVirtualThreadsMutex is done consistently
- Address infinite loop in takeVirtualThreadListToUnblock if vm->blockedContinuations is NULL
- Also skip SO check when returning from J9VM_CONTINUATION_RETURN_FROM_SYNC_METHOD to remain consistent with how it would behave in the pinning case.
https://github.com/eclipse-openj9/openj9/issues/21560 https://github.com/eclipse-openj9/openj9/issues/21649 https://github.com/eclipse-openj9/openj9/issues/21648 are now passing
https://github.com/eclipse-openj9/openj9/issues/21446 https://github.com/eclipse-openj9/openj9/issues/21422 no longer crashing
=> Fix synchronized method enter vthread transition

runtime/j9vm/java11vmi.c
Prevent VM failure when the moduleName pointer is NULL
Fixes: #20871
Co-authored-by: Babneet Singh sbabneet@ca.ibm.com
Co-authored-by: Tobi Ajila tobi_ajila@ca.ibm.com
Co-authored-by: Lige Zhou lige.zhou@ibm.com
=> Add the validation of string pointer

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
This PR reverts the (newer) vectorized implementation of String.hashCode due to a performance regression observed in several benchmarks. While we investigate further and decide on the right path forward, this change is being reverted to avoid disrupting others, as the regression is impacting performance runs.
=> Revert "x86: Implement String.hashCode with vectorizedHashCode()"

runtime/compiler/build/files/common.mk.ftl, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/J9Options.hpp, runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/control/JITServerCompilationThread.cpp, runtime/compiler/control/JITServerCompilationThread.hpp, runtime/compiler/control/JITServerHelpers.cpp, runtime/compiler/control/OptionsPostRestore.cpp, runtime/compiler/env/VMJ9Server.cpp, runtime/compiler/runtime/CMakeLists.txt, runtime/compiler/runtime/IProfiler.cpp, runtime/compiler/runtime/IProfiler.hpp, runtime/compiler/runtime/JITClientSession.cpp, runtime/compiler/runtime/JITClientSession.hpp, runtime/compiler/runtime/JITServerAOTCache.cpp, runtime/compiler/runtime/JITServerAOTCache.hpp, runtime/compiler/runtime/JITServerIProfiler.cpp, runtime/compiler/runtime/JITServerIProfiler.hpp, runtime/compiler/runtime/JITServerProfileCache.cpp, runtime/compiler/runtime/JITServerProfileCache.hpp, runtime/compiler/runtime/JITServerSharedROMClassCache.cpp, runtime/compiler/runtime/JITServerSharedROMClassCache.hpp
This PR is a barebones implementation of a shared bytecode profile repository at JITServer.
At the moment only profiling related to branches is stored in the profile repository.
The profile cache code is enabled by the client which can signal its intention of using it by providing `-XX:+JITServerUseProfileCache` on the command line. Note that the client must also use the JITServer AOT cache which is a prerequisite for the profile cache: `-XX:+JITServerUseAOTCache`.
There is a strong association between an AOTCache and a sharedProfileCache. Each data structure points back to its counterpart. Once an AOT cache is created, a profile cache is also created even if the client has no intention of using it (if no client uses the profile cache, it will remain empty). Because a JITServer can have …
=> Barebones JITServer shared profile cache implementation

runtime/vm/vmprops.c
Set the system property ibm.java9.forceCommonCleanerShutdown to true
to enable termination of the Common Cleaner thread, thus freeJavaVM()
is invoked to create snapshot file on VM shutdown.
Fixes: #20873
Co-authored-by: Babneet Singh sbabneet@ca.ibm.com
Co-authored-by: Tobi Ajila tobi_ajila@ca.ibm.com
Co-authored-by: Lige Zhou lige.zhou@ibm.com
=> RCP: Invoke freeJavaVM() on VM shutdown

runtime/j9vm/java11vmi.c, runtime/jcl/common/stdinit.c, runtime/vm/createramclass.cpp, runtime/vm/initsendtarget.cpp
Add `#if defined(J9VM_OPT_SNAPSHOTS)` around Snapshot utility macros
As per https://github.com/eclipse-openj9/openj9/pull/21667#discussion_r2049086579, when the feature is disabled, `IS_RESTORE_RUN` is always `FALSE`. The previous assumption was that the compiler will optimize the code block
and evaluate it as dead code, removing it. However, we've observed perf issues on `zLinux` where the compiler fails to optimize correctly. Just to be safe, it should be `#ifdef'ed`.
=> Add #if defined(J9VM_OPT_SNAPSHOTS) around Snapshot utility macros

runtime/compiler/control/JITServerCompilationThread.cpp, runtime/compiler/control/JITServerCompilationThread.hpp, runtime/compiler/net/ServerStream.hpp, runtime/compiler/net/StreamExceptions.hpp
The `AOTCacheMap_request` is processed by throwing an exception. This isn't a good way of implementing this from a conceptual integrity point of view. This PR refactors the code to explicitly process both `compilationRequest` and `AOTCacheMap_request`.
=> Cleanup AOTCacheMap_request code

runtime/compiler/runtime/JITServerIProfiler.cpp
The IProfiler code at JITServer used to cache empty information about methods that have no profiled bytecodes. Recent changes related to the shared profile cache have added a new code path where caching of empty information no longer happens, resulting in more messages being sent and an increase in the CompCPU at the client. This commit rectifies the situation dscribed above.
=> JITServer IProfiler cache fix

runtime/jcl/common/mgmtmemory.c, runtime/oti/j9nonbuilder.h, runtime/vm/createramclass.cpp
The changes reflect the feature request https://github.com/eclipse-openj9/openj9/issues/20644.
Adding segment categories for RAMClass fragments:
sub4G
Frequently accessed
Infrequently accessed
Closes: https://github.com/eclipse-openj9/openj9/issues/20644
Signed-off-by: Nick Kamal <[nick.kamal@ibm.com](mailto:nick.kamal@ibm.com)>
=> WIP:RamClass: Segment allocation enhancements

runtime/compiler/optimizer/EscapeAnalysis.cpp, runtime/compiler/optimizer/EscapeAnalysis.hpp
This change makes some minor improvements to Escape Analysis for maintainability.  None of the changes represents a functional change to the optimization.
- Some calls to `traceMsg` would print a pointer to the `Candidate` structure that's being examined rather than the `Candidate::_node` field, the relevant object allocation node in the IL.  Fixed those, including some that were in code that was commented out, to aid in debugging Escape Analysis using trace files.
- This change also adds some comments to `TR_EscapeAnalysis::checkDefsAndUses` and some of the related methods it calls to assist the reader in following the logic.
- Code in [`TR_EscapeAnalysis::collectValueNumbersOfIndirectAccessesToObject`](https://github.com/eclipse-openj9/openj9/blob/b5393ad63ee5e0d1097b33f9ccc66de5dd0840b9 …
=> Various Escape Analysis clean up items

runtime/vm/JFRChunkWriter.cpp, runtime/vm/JFRChunkWriter.hpp, runtime/vm/JFRConstantPoolTypes.hpp, test/functional/cmdLineTests/jfr/jfrevents.xml
Add NativeLibrary event to JFR
Capture libraryName, base and top addresses for each library.
=> Add JFR NativeLibrary event

runtime/jvmti/jvmtiStackFrame.cpp, runtime/jvmti/jvmtiThread.cpp
`haltThreadForInspection` may release VM access. A GC can occur after
VM access is released, potentially moving objects. To avoid accessing
stale objects and risking segfaults, objects must be refetched after
`haltThreadForInspection`.
Fixes: #21670
=> Refetch objects after haltThreadForInspection

runtime/vm/FastJNI.cpp
Related: https://github.com/eclipse-openj9/openj9/pull/21489
=> (0.52) Fix disabling fast JNI wait for JEP491

doc/release-notes/0.46/0.46.md
New DAA API related to external decimals added in 0.46.0 release documented.
[skip ci]
=> 0.46.0 Release note update

doc/release-notes/0.51/0.51.md
Created 0.51.0 release note and updated with the available content specific to 0.51.0 release.
[skip ci]
=> 0.51.0 release note

runtime/bcutil/ClassFileWriter.hpp, runtime/bcverify/bcverify.c, runtime/bcverify/vrfyhelp.c, runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp, runtime/jcl/common/jclexception.cpp, runtime/oti/j9.h, runtime/tests/shared/CompiledMethodTest.cpp, runtime/verbose/errormessageframeworkrtv.c, runtime/verbose/verbose.c, runtime/vm/CRIUHelpers.cpp, runtime/vm/exceptiondescribe.c, runtime/vm/jfr.cpp, runtime/vm/stringhelpers.cpp
Adjust uses of `J9UTF8*` macros to provide arguments of the right types where necessary.
See also https://github.com/eclipse-openj9/openj9/pull/21688/files#r2056064379.
=> Remove casts from J9UTF8 macros

runtime/vm/BytecodeInterpreter.hpp
An immediate async event cannot occur in native INL
=> Remove asyncCheck from enterContinuation

doc/compiler/runtime/J9JITExceptionTable.md, runtime/codert_vm/cnathelp.cpp, runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp, runtime/compiler/codegen/J9CodeGenerator.cpp, runtime/compiler/codegen/J9CodeGenerator.hpp, runtime/compiler/p/codegen/CallSnippet.cpp, runtime/compiler/p/codegen/PPCPrivateLinkage.cpp, runtime/compiler/runtime/MetaData.cpp, runtime/compiler/runtime/MethodMetaData.c, runtime/compiler/runtime/MethodMetaData.h, runtime/compiler/runtime/RelocationRuntime.cpp, runtime/compiler/runtime/codertinit.cpp, runtime/compiler/x/codegen/X86PrivateLinkage.cpp, runtime/compiler/z/codegen/S390PrivateLinkage.cpp, runtime/oti/j9nonbuilder.h, runtime/vm/BytecodeInterpreter.hpp
It is possible for `MethodHandle.linkToVirtual()` to be called with a `MemberName` that specifies `MethodHandle.invokeBasic()` as the virtual method. For performance, any `linkToVirtual()` call that goes unrefined in a JIT compilation will be transformed into a computed call through the vtable using `JITHelpers.dispatchVirtual()`. When the target happens at runtime to be `invokeBasic()`, this will result in a call through the vtable entry for `invokeBasic()`, which has been the cause of multiple problems that are fixed by this commit.
1. `old_slow_icallVMprJavaSendPatchupVirtual()` would try to find the J2I thunk based on the signature from the ROM method, which doesn't necessarily (or even probably) match the signature at the call site because `invokeBasic()` is signature-polymorphic. …
=> Add table of invokeBasic() call sites to J9JITExceptionTable

runtime/compiler/optimizer/J9ValuePropagation.cpp, runtime/compiler/optimizer/J9ValuePropagation.hpp
When ValuePropagation is able to obtain the known object info of the MemberName child of a linkToSpecial, linkToVirtual and linkToStatic call, it is possible to refine the INL call and avoid a more expensive dispatch mechanism. The refined linkTo* INL call then gets inlined during delayed VP transformations.
This change also adds a new static helper to deal with populating prex arg info.
=> Refine and inline MethodHandle.linkTo* methods in ValuePropagation

runtime/gc_glue_java/ConcurrentMarkingDelegate.cpp, runtime/gc_glue_java/ConcurrentMarkingDelegate.hpp, runtime/gc_glue_java/MarkingDelegate.cpp, runtime/gc_glue_java/MarkingDelegate.hpp, runtime/gc_structs/VMThreadStackSlotIterator.cpp
Sharing logic for scanning continuation slots and
continuation stack slots between MarkingDelegate and
ConcurrentMarkingDelegate.
- update GC_VMThreadStackSlotIterator::scanSlots() can
handle both mounted and unmounted continuation Object.
- update C method stackSlotIteratorForMarkingDelegate()
to static MM_MarkingDelegate::stackSlotIterator().
- update struct StackIteratorData4MarkingDelegate to
MM_MarkingDelegate::StackIteratorData.
- new method MM_MarkingDelegate.scanContinuationNativeSlotsNoSync
handle scanning both continuation slots and continuation
stack slots.
- call MM_MarkingDelegate.scanContinuationNativeSlotsNoSync() in
MM_ConcurrentMarkingDelegate for scanning.
Signed-off-by: lhu <linhu@ca.ibm.com>
=>  Sharing scanning continuation logic for Marking Delegates

doc/release-notes/0.51/0.51.md
0.51.0 release note updated with the available content specific to 0.51.0 release. Added JFR related content.
[skip ci]
=> 0.51 Release notes update

runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/rossa.cpp, runtime/compiler/control/rossa.h, runtime/compiler/env/VMJ9.cpp, runtime/compiler/exceptions/AOTFailure.hpp
During an AOT compilation, if the compiler needs to store a J2I thunk in the shared class cache (SCC) but fails, the JIT throws a CompilationException exception and the method under compilation will continue as interpreted.
This commit introduces a new exception, AOTThunkPersistenceFailure, which will be thrown when a J2I thunk cannot be stored in SCC. When this type of exception is caught, the JIT will retry the compilation of the method, but refrain from using AOT.
=> Retry AOT compilations on J2I thunk store failure

jcl/src/java.base/share/classes/java/security/AccessControlContext.java
JDK25 removed `sun.security.util.FilePermCompat`
This addresses the compilation error at https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_OpenJDK/789/consoleFull
```
23:25:56  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.base/share/classes/java/security/AccessControlContext.java:31: error: cannot find symbol
23:25:56  import sun.security.util.FilePermCompat;
23:25:56                          ^
23:25:56    symbol:   class FilePermCompat
23:25:56    location: package sun.security.util
```
=> JDK25 removed sun.security.util.FilePermCompat

runtime/oti/j9nonbuilder.h, runtime/rasdump/javadump.cpp, runtime/util/moninfo.c, runtime/util/thrinfo.c, runtime/vm/ContinuationHelpers.cpp, runtime/vm/ObjectMonitor.cpp, runtime/vm/monhelpers.c
Monitor owner is set to 1 if the virtual thread is detached. Add a new
macro for that. getVMThreadFromOMRThread() should only be called if the
owner is a valid omr thread.
Closes #21761
=> Do not call getVMThreadFromOMRThread() if monitor owner is detached

runtime/util/propsfile.c
Cherry pick https://github.com/eclipse-openj9/openj9/pull/21762
=> (0.51) Fix call to propsfile_read_text buffer length calculation

test/functional/cmdLineTests/criu/playlist.xml, test/functional/cmdLineTests/jvmtitests/playlist.xml
Fixes: https://github.com/eclipse-openj9/openj9/issues/21443
Fixes: https://github.com/eclipse-openj9/openj9/issues/21444
=> Re-enable Java 24+ cmdline tests

runtime/vm/JFRChunkWriter.cpp, runtime/vm/JFRChunkWriter.hpp, runtime/vm/JFRConstantPoolTypes.hpp, test/functional/cmdLineTests/jfr/jfrevents.xml, test/functional/cmdLineTests/jfr/playlist.xml
Implement system process tracking in OpenJ9 Flight Recorder
Capture and store pid and command line for each process.
=> Add JFR SystemProcess event

runtime/compiler/z/env/J9CPU.cpp
The facility is expected to be disabled on hardware prior to zNext as it was introduced in zNext.
=> Disable MIE4 on hardware prior to zNext

runtime/vm/BytecodeInterpreter.hpp, runtime/vm/ContinuationHelpers.cpp
- Prevent vthreads from being notified before being added to the wait list
- Prevent Object.notify occuring between prepareVirtualThreadForUnmount
and yieldPinnedContinuation to be ignored by unblocker
=> Fix synchronization issues of notifying yielding vthreads

runtime/vm/JFRChunkWriter.cpp, runtime/vm/JFRChunkWriter.hpp, runtime/vm/JFRConstantPoolTypes.hpp, test/functional/cmdLineTests/jfr/jfrevents.xml
Capture libraryName, base and top addresses for each library.
=> Add JFR NativeLibrary event (Version 2)

runtime/jvmti/jvmtiThread.cpp
The below error cases should only be exercised if a virtual thread is
not the current thread:
- Error if a virtual thread is not suspended; and
- Error if a virtual thread is unmounted.
Related: #21695
=> Update error handling for virtual threads in JVMTI StopThread

runtime/cmake/platform/toolcfg/xlc.cmake
Avoid warnings on AIX
/opt/IBM/xlC/13.1.3/bin/.orig/xlC_r: 1501-210 (W) command option Wc,inline(auto contains an incorrect subargument
/opt/IBM/xlC/13.1.3/bin/.orig/xlC_r: 1501-210 (W) command option Wc,list() contains an incorrect subargument
/opt/IBM/xlC/13.1.3/bin/.orig/xlC_r: 1501-210 (W) command option Wc,offset contains an incorrect subargument
/opt/IBM/xlC/13.1.3/bin/.orig/xlC_r: 1501-210 (W) command option Wc,gonumber contains an incorrect subargument
Related to https://github.com/eclipse-openj9/openj9/pull/19657
=> Remove z/OS compile options from AIX

test/functional/cmdLineTests/fips/playlist.xml
Move cmdLineTester_fips from sanity to extended
Issue: git_ibm/runtimes/automation/issues/371
=> Move cmdLineTester_fips to extended.functional

runtime/compiler/optimizer/JProfilingValue.cpp
Need to anchor the value node before the helper call node is removed. Otherwise, the child value node could be currently anchored under the helper call node. When the helper call node is removed, the value node will be moved down and anchored where the next reference is. It will be a problem if there is a store into this value between the helper call node and the next reference. After the helper call node is removed, the reference will load the updated value instead of the original value.
Fixes: #21256
=> Anchor the value node before the removal of the call node

runtime/compiler/optimizer/VectorAPIExpansion.cpp, runtime/compiler/optimizer/VectorAPIExpansion.hpp
- use the same code as for loading a mask from an array
Depends on: https://github.com/eclipse-omr/omr/pull/7737
=> Correct Mask unboxing in VectorAPIExpansion

runtime/compiler/optimizer/VectorAPIExpansion.cpp
- The blend() intrinsic requires lane-wise value selection, while TR::vbitselect is bitwise
- Vector API blend() intrinsic should generate TR::vblend and not TR::vbitselect
=> Generate vblend for Vector API blend intrinsic

runtime/j9vm/java11vmi.c, runtime/oti/vm_api.h, runtime/vm/classsupport.c
Refetch module object reference after GC point
Added comment for methods with potential GC points;
Added `internalFindClassUTF8()` & `internalFindKnownClass()` defines into `vm_api.h`.
Related to
* https://github.com/eclipse-openj9/openj9/issues/18970
=> Refetch module object reference after GC point

runtime/vm/JFRChunkWriter.hpp, runtime/vm/JFRConstantPoolTypes.hpp, runtime/vm/JFRWriter.hpp
Fixes https://github.com/eclipse-openj9/openj9/issues/21823 Follow-up of https://github.com/eclipse-openj9/openj9/pull/21818
=> Fill SystemProcess and NativeLibrary pools only on explicit dump

runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/net/CommunicationStream.hpp, runtime/compiler/net/MessageTypes.cpp, runtime/compiler/net/MessageTypes.hpp, runtime/compiler/runtime/IProfiler.cpp, runtime/compiler/runtime/IProfiler.hpp, runtime/compiler/runtime/JITClientSession.cpp, runtime/compiler/runtime/JITClientSession.hpp, runtime/compiler/runtime/JITServerAOTCache.cpp, runtime/compiler/runtime/JITServerAOTCache.hpp, runtime/compiler/runtime/JITServerAOTDeserializer.cpp, runtime/compiler/runtime/JITServerAOTDeserializer.hpp, runtime/compiler/runtime/JITServerAOTSerializationRecords.hpp, runtime/compiler/runtime/JITServerIProfiler.cpp, runtime/compiler/runtime/JITServerIProfiler.hpp, runtime/compiler/runtime/JITServerProfileCache.cpp
For virtual invokes, interface invokes, checkcast and instanceof bytecodes the IProfiler profiles 3 different target RAMClasses in a data structure called `CallSiteProfileInfo`. We will refer to them as slots. The server cannot cache the RAMClasses because they are valid for just one client. Because the SharedProfileCache is supposed to work with many clients, we need to convert the RAMClasses into something else that is client agnostic. In this implementation we will use the ClassRecord from the JITServer AOT cache.
If the server determined that the profiling information received from the client is better than the one it currently has in the SharedProfileCache (JITServerSharedProfileCache::compareBytecodeProfiles(sharedProfileSummary, clientProfileSummary);) then it will proceed to store …
=> JITServer profiling infra for CallGraph entries

runtime/compiler/CMakeLists.txt
Reverts eclipse-openj9/openj9#21135
Obsoleted by https://github.com/eclipse-omr/omr/pull/7747
=> Revert "Link j9jit library without execstack flag on Linux"

runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
...and ignore the call symref. For an inlined indirect call, the inlined method can differ from the method specified by the call symref, which could result in an incorrect inlining table at load time.
=> SVM: Always specify the actual inlined method for inlined method relos

runtime/compiler/optimizer/EstimateCodeSize.hpp, runtime/compiler/optimizer/J9EstimateCodeSize.cpp, runtime/compiler/optimizer/J9EstimateCodeSize.hpp
In Estimate Code Size, we would terminate estimation once _analyzedSize exceeded the analyzed size threshold, which was obtained using sizeThreshold * allowanceFactor. However, not increasing the analyzed size threshold for methods that are always worth inlining - a property set through inliner policy or through the use of @ForceInline annotation, meant that those methods were not being prioritized as necessary. To overcome that issue, this commit introduces a few changes to the ECS heuristics:
* forceInlineMultiplier - to be used to multiply the analyzed size threshold for a method that is always worth inlining.
* Change estimateCodeSize function signature to be able to recursively pass down caller method's analyzed size threshold to callees along an always worth inlining call graph.
* …
=> Raise allowance size threshold along alwaysWorthInlining calls

runtime/vm/ContinuationHelpers.cpp
In vthread.afterYield() where the state is first set to WAIT then BLOCKED if the notify occurred during the transition phase.
Related: https://github.com/eclipse-openj9/openj9/issues/21037#issuecomment-2860676990
=> Update assertion to account for state change in afterYield

runtime/gc_vlhgc/CopyForwardScheme.cpp, runtime/gc_vlhgc/CopyForwardScheme.hpp
If Ownable Synchronizer object scan has not been successful (caused Copy Forward Abort) it should not be aadded to the list right away. This object is remembered in the work packet and is going to be rescanned for the second time.
=> Do not add Own.Sync. object to the list if scan wasn't successful

buildenv/docker/mkdocker.sh, buildenv/jenkins/variables/defaults.yml, doc/build-instructions/Build_Instructions_V11.md, doc/build-instructions/Build_Instructions_V17.md, doc/build-instructions/Build_Instructions_V21.md, doc/build-instructions/Build_Instructions_V8.md
Th older nasm has issues finding include files and on Windows can't build OpenSSL 3.5.
=> Update minimum nasm dependency from 2.13.03 to 2.15.05

buildenv/jenkins/jobs/infrastructure/Bootjdk_Cleanup.groovy
Remove all bootjdks from build machines.
Skip zos as they do not automatically repopulate.
Simply trigger all-nodes-matching-label job with appropriate params
Issue automation 355
=> Add jenkins script for bootjdk cleanup

runtime/compiler/p/codegen/J9CodeGenerator.cpp, runtime/compiler/p/codegen/J9TreeEvaluator.cpp
Calculate the address for the array data in OffHeap mode correctly for vectorizedHashCode
=> Enable vectorizedHashCode intrinsic for OffHeap on POWER

runtime/vm/JFRChunkWriter.cpp, runtime/vm/JFRChunkWriter.hpp, runtime/vm/JFRConstantPoolTypes.hpp, test/functional/cmdLineTests/jfr/jfrevents.xml
This change adds support for the JFR Young Generation Configuration Event.
=> Add JFR YoungGenerationConfiguration Event

test/functional/Java8andUp/playlist.xml
related: runtimes/backlog/issues/1656
=> Exclude pthreadDestructor on IBM Java 8 AIX

jcl/src/java.base/share/classes/com/ibm/oti/vm/VM.java, runtime/jcl/common/com_ibm_oti_vm_VM.cpp, runtime/jcl/exports.cmake, runtime/oti/jclprots.h
JDK24+ add `com.ibm.oti.vm.VM.isYieldBlockedVirtualThreadsEnabled()`
By default, this method returns `true`, i.e., not in legacy locking mode.
=> JDK24+ add com.ibm.oti.vm.VM.isYieldBlockedVirtualThreadsEnabled()

test/functional/VM_Test/src/j9vm/test/arraylets/ArrayletAllocateTestRunner.java
Increasing the heap size of ArrayletAllocateTest to 71M, as per calculation in this comment:
https://github.com/eclipse-openj9/openj9/issues/9969#issuecomment-2803359631
=> Increase Arraylet Allocate test heap size

runtime/vm/BytecodeInterpreter.hpp, test/functional/Java22andUp/playlist.xml
We need to update the way we calculate the data start address now that it is possible to have non-adjacent data section of an array in offheap mode.
Fixes https://github.com/eclipse-openj9/openj9/issues/21303
=> Off-heap support for FFI callouts

test/functional/DDR_Test/playlist.xml, test/functional/NativeTest/playlist.xml, test/functional/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml
Temporarily exclude several failed tests due to mixedrefs path
Issue: ibm_git/runtimes/backlog/issues/1654
=> Temporarily exclude failed tests due to mixedrefs path

buildenv/jenkins/variables/defaults.yml
This updates to OpenSSL version 3.5.0 ( with fixes necessary for AIX).
Signed-off-by: Jason Katonica <katonica@us.ibm.com>
=> Enable OpenSSL Version 3.5.0

runtime/compiler/optimizer/J9EstimateCodeSize.cpp
In hot and above compilatios, if a target it is looking to inline is still interpreted, increase the frequency cut-off for such targets. Currently this is not extended to warm compiles, but changes in this commit also adds environment variable to apply higher frequency cut-off for interpreted targets in warm compilations.
=> Increase the cutoff to inline interpreted targets

jcl/src/java.base/share/classes/java/lang/Access.java
Update JDK25 `java.lang.Access` to `jdk.internal.access.JavaLangAccess`
Resolve JDKnext abuild compilation errors - https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_OpenJDK/802/consoleFull
```
00:20:34  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:72: error: Access is not abstract and does not override abstract method uncheckedStringConcat1(String[]) in JavaLangAccess
00:20:34  final class Access implements JavaLangAccess {
```
=> Update JDK25 java.lang.Access to jdk.internal.access.JavaLangAccess

runtime/compiler/ilgen/J9ByteCodeIlGenerator.hpp, runtime/compiler/ilgen/Walker.cpp
When an error is caught during resolveInvokeDynamic (MethodHandleResolver.java), a MethodHandle that throws a BootstrapMethodError is returned, which has no arguments. This can cause an issue for OSR where we run out of pending push temp slots during OSR BookKeeping since we are not popping all the args off the operand stack.
This change recognizes when we have not popped all the arguments and pops them accordingly
Fixes: #21419
=> Pop extra args on BootstrapMethodError for invokedynamic

runtime/compiler/runtime/IProfiler.cpp, runtime/compiler/runtime/IProfiler.hpp, runtime/compiler/runtime/JITServerIProfiler.cpp
The IProfiler does not collect samples for direct calls. Instead, the optimizer will use the setCallCount() API to set the number of samples for such direct calls. Until this commit, direct-call info was stored in `TR_IPBCDataCallGraph` entries which was mainly created for interface and virtual calls. Such entries track 3 different call targets and are somewhat bigger than the rest of IProfiler entries. For direct calls we only need a simple counter, so using `TR_IPBCDataCallGraph` entries for this purpose is wasteful.
This commit introduces a new type of IProfiler entry, called `TR_IPBCDataDirectCall`, which will be used for storing profiling info related to direct calls. Note that the optimizer will remain the sole entity that will populate such entries. Moreover, these new entries will …
=> Create TR_IPBCDataDirectCall for IProfiler

runtime/compiler/ilgen/J9ByteCodeIlGenerator.hpp, runtime/compiler/ilgen/Walker.cpp
Reverts eclipse-openj9/openj9#21720
See https://github.com/eclipse-openj9/openj9/pull/21720#issuecomment-2887444489
=> Revert "Pop extra args on BootstrapMethodError for invokedynamic"

runtime/compiler/z/codegen/J9CodeGenerator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp
The acceleration was initially disabled because it added array header size to the array object, which was required to reach the elements. However, this is unnecessary for off-heap mode. As a result, the evaluator has been updated to add the array header size exclusively for non-off-heap mode, while in off-heap mode, it now retrieves the data element address directly from the array header, enabling acceleration in off-heap mode.
=> Update IntegerToChars evaluators for off-heap

runtime/compiler/runtime/IProfiler.cpp
`isCallByteCode(U_8 byteCode)` is a method defined in IProfiler.cpp but it is unused and incomplete: it misses two other call bytecodes (JBinvokestaticsplit and JBinvokestaticsplit).
Rather than fixing the code, it's better to just remove it.
=> Remove unused isCallByteCode() method

test/functional/DDR_Test/playlist.xml, test/functional/NativeTest/playlist.xml, test/functional/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml
Re-enable mixedrefs related tests since fixed, and exclude thrstatetest
Issue: Git_ibm/runtimes/backlog/issues/1659 and Git_ibm/runtimes/backlog/issues/1656
=> Re-enable IBM Java 8 compressedrefs native tests and disable thrstatetest

runtime/compiler/z/codegen/J9CodeGenerator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp
The acceleration was initially disabled because it added array header size to the array object, which was required to reach the elements. However, this is unnecessary for off-heap mode. As a result, the evaluator has been updated to add the array header size exclusively for non-off-heap mode, while in off-heap mode, it now retrieves the data element address directly from the array header, enabling acceleration in off-heap mode.
=> Update CRC32C acceleration for off-heap

runtime/compiler/z/codegen/J9CodeGenerator.cpp, runtime/compiler/z/codegen/J9TreeEvaluator.cpp
The acceleration was initially disabled because it added array header size to the array object, which was required to reach the elements. However, this is unnecessary for off-heap mode. As a result, the evaluator has been updated to add the array header size exclusively for non-off-heap mode, while in off-heap mode, it now retrieves the data element address directly from the array header, enabling acceleration in off-heap mode.
=> Update hashCodeHelper for off-heap

runtime/compiler/z/codegen/J9CodeGenerator.cpp
This already uses
`TR::TransformUtil::generateFirstArrayElementAddressTrees`  API to generate appropriate trees for off-heap and non off-heap modes so no change is needed to the evaluator.
=> Enable EncodeASCII acceleration for off-heap

runtime/compiler/infra/J9Cfg.cpp
getParentCallCount() is a method in J9CFG.cpp that is only used in some dead (commented out) code.
Remove its definition and the dead code where it is referenced.
=> Remove unused getParentCallCount() method

runtime/vm/JFRConstantPoolTypes.hpp
This change fixes style and consistency issues in some JFR event code.
=> Fix style and consistency issues in some JFR events

runtime/compiler/env/VMJ9Server.cpp
For `CLASSINFO_ROMCLASS_EXTRAMODIFIERS` the result is `uint32_t`, but these call sites were passing a pointer to `uintptr_t`, which on 64-bit is twice as big as necessary. On a big-endian system, the result would be stored to the high half of the variable, leaving the low half zero, so these functions would return false for all classes.
=> Fix is{Anonymous,Hidden}Class() for 64-bit big-endian JITServer

runtime/gc_include/j9modron.h, runtime/gc_modron_startup/mmhelpers.cpp
Add new key j9gc_modron_configuration_gcConcurrentMarkThreadCount for j9gc_modron_getConfigurationValueForKey().
=> Add new keys for j9gc_modron_getConfigurationValueForKey()

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp
Use the codegen flags instead of cpu flags to check support for bitwise compress and expand IL opcodes when inlining `(Integer|Long).(compress|expand)`.
Requires coordinated merge with https://github.com/eclipse-omr/omr/pull/7740.
=> Use cg flags to check compress/expand support

runtime/vm/ContinuationHelpers.cpp, runtime/vm/monhelpers.c
Use CompareAndSwap to ensure updates to lockword is not overwritten during exit.
Also ensure vthread blocked on monitor is notified properly.
Related: #21826
=> Update non-FLC flatlock exit to use CAS

runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/optimizer/J9EstimateCodeSize.cpp
NPH keeps track of loads of parameters when the caller method has prex arg info, which is then used when we come across one of the invoke* bytecodes. If the param load is used as arg for the call, then we would want to propagate the prex arg info down the callee, for which peeking ILGen is necessary. This commit also terminates NPH once _needsPeeking is set as true, as any further analysis would not change the peeking outcome.
=> Enable peeking ILGen for param loads using NeedsPeekingHeuristic

runtime/compiler/codegen/J9CodeGenerator.hpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/z/codegen/J9CodeGenerator.cpp
The existing SupportsInlineStringIndexOf flag controls inlining of both String.indexOf(int) and String.indexOf(String).
This commit introduces a new flag SupportsInlineStringIndexOfString for String.indexOf(String).
Only Z codegen supports String.indexOf(String) at the moment.
=> Introduce SupportsInlineStringIndexOfString flag

runtime/oti/xhelpers.m4, runtime/vm/jvminit.c
Reverts eclipse-openj9/openj9#21924
See https://github.com/eclipse-openj9/openj9/pull/21924#issuecomment-2914042755
=> Revert "x86: Reduce AVX-SSE mixing penalties"

jcl/jpp_configuration.xml
It's combined with SIDECAR18-SE-OPENJ9 as a separate config is not needed.
Co-dependent on https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/836
=> Remove JCL preprocessor config SIDECAR18-TOOLS-OPENJ9

runtime/compiler/build/toolcfg/zos-xlc/common.mk, runtime/makelib/targets.mk.zos.inc.ftl
OMR_ISDIGIT macro added to omrcomp.h requires _AE_BIMODAL to be defined in order to make isdigit_a() to be available. This defines it in the appropriate contexts for the z/OS builds.
This change is associated with https://github.com/eclipse-omr/omr/pull/7761
@keithc-ca @babsingh 
context tag: open xl
=> Add _AE_BIMODAL to support OMR_ISDIGIT macro

runtime/compiler/optimizer/VectorAPIExpansion.cpp, runtime/compiler/optimizer/VectorAPIExpansion.hpp
- use the same code as for storing mask into array
Depends on: https://github.com/eclipse-omr/omr/pull/7753
=> Correct Mask boxing in VectorAPIExpansion

runtime/tests/jvmtitests/CMakeLists.txt
When building on AIX with OpenXL, flags `libjvmtitest.so` to skip the `strip` step after its debug information is extracted.
Part of the fix for https://github.com/eclipse-openj9/openj9/issues/21528
Depends on: https://github.com/eclipse-omr/omr/pull/7732
=> Skip strip step for libjvmtitest.so when building on AIX with OpenXL

runtime/cfdumper/romdump.c, runtime/compiler/il/J9DataTypes.cpp, runtime/jcl/common/jcltrace.c, runtime/rastrace/trccomponent.c, runtime/rastrace/trcoptions.c, runtime/redirector/redirector.c, runtime/util_core/j9argscan.c
In order to support removal of a2e header redefinitions for
isdigit() method, the usage of isdigit() are replaced with
OMR_ISDIGIT() to properly recognize ascii digit literals.
This is done by conditionally using __isdigit_a() on z/OS
platforms.
Main PR driving this change, that needs to be merged beforehand: https://github.com/eclipse-omr/omr/pull/7761
(project tag: Open XL z/OS compiler support)
=> Replace isdigit with OMR_ISDIGIT

runtime/compiler/control/HookedByTheJit.cpp
`TR::Options::INLINE_failedToDevirtualize` and `TR::Options::INLINE_failedToDevirtualizeInterface` are not really options, but rather statistics. The code that updates them (present in omr project) is supposed to be removed and thus we must remove their references in OpenJ9 as well.
=> Remove TR::Options::INLINE_failedToDevirtualize usage

runtime/compiler/runtime/IProfiler.cpp
setWarmCallGraphTooBig is an IProfiler routine used by the Inliner as a hint that the call at a particular callsite is expensive to be inlined.
Static and special invokes are not tracked by the IProfiler and therefore profiling entries for such calls are not created, yet we may want to set the warmCallTooBig hint for direct calls as well. We have empirical evidence that not doing so increases the compilation overhead by ~5%.
Having said that, the Inliner indirectly creates profiling entries for direct calls when using setCallCount(), so, most of the time the inliner can set the warmCallTooBig hint if it wants to. However, we plan to eliminate the setCallCount()/getCallCount() pair of routines and, to compensate, this PR creates IProfiler entries for static/special invokes in the …
=> setWarmCallGraphTooBig() creates IProfiler entry if needed

test/functional/cmdLineTests/jfr/jfrevents.xml
Enable JFR NativeLibrary test on AIX by updating the platform tag.
=> Enable JFR NativeLibrary event test for AIX

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp, runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp, runtime/compiler/p/codegen/J9CodeGenerator.cpp, runtime/compiler/x/codegen/J9CodeGenerator.cpp, runtime/compiler/z/codegen/J9CodeGenerator.cpp
Support the acceleration of vectorizedMisMatch for OffHeap implementation by adding a block of code to calculate the address of the arrays, while accounting for null values.
=> Support Accelerating ArraysSupport.vectorizedMismatch for OffHeap

jcl/src/java.base/share/classes/java/lang/Access.java, runtime/j9vm/exports.cmake, runtime/j9vm/javanextvmi.cpp, runtime/redirector/forwarders.m4
JDK25 adds `JVM_CreateThreadSnapshot`, removes `isCarrierThreadLocalPresent`
Required by
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/1032
=> JDK25 adds JVM_CreateThreadSnapshot, removes isCarrierThreadLocalPresent

runtime/gc_base/RootScanner.cpp, runtime/gc_glue_java/ConcurrentMarkingDelegate.cpp, runtime/gc_glue_java/MarkingDelegate.cpp, runtime/gc_glue_java/MetronomeDelegate.cpp, runtime/gc_vlhgc/CopyForwardScheme.cpp, runtime/gc_vlhgc/GlobalMarkCardScrubber.cpp, runtime/gc_vlhgc/GlobalMarkingScheme.cpp, runtime/gc_vlhgc/WriteOnceCompactor.cpp
Current behaviour j9module should have moduleObject set when GC
discovers it has been changed in Java 21 by adding Java API to set a few
special module objects. It introduces a case when GC can see NULL in
moduleObject slot. Resolving this problem for GC by simple unconditional
NULL check applicable for any module.
=> Add NULL check for moduleObject in GC

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp
Add "if defined(J9VM_GC_SPARSE_HEAP_ALLOCATION)" guard to the recognized call transformer for vectorizedMismatch.
=> Add Guards to the OffHeap-exclusive Code for vectorizedMismatch Transformer

runtime/j9vm/java11vmi.c
Tracepoints don't evaluate their arguments if `UT_TRACE_OVERHEAD <= 0`.
=> Separate side-effects from tracepoint use

runtime/compiler/env/j9methodServer.cpp
Outside of JITServer, `getDeclaringClassFromFieldOrStatic()` always returns null in non-SVM AOT. Explicitly return null for consistency. Otherwise the result could be non-null if it was cached by an earlier non-AOT remote compilation.
=> Suppress getDeclaringClassFromFieldOrStatic() in JITServer non-SVM AOT

runtime/compiler/optimizer/JProfilingValue.cpp
In the process of finding values to profile, the method `TR_JProfilingValue::cleanUpAndAddProfilingCandidates` would insert calls to the `jProfileValueWithNullCHK` non-helper for `instanceof` and `checkcast` operations, with the child of each call being an indirect load of the `<vft-symbol>` for the value that is to be profiled.
During `TR_JProfilingValue::addProfilingTrees`, those calls would be transformed to guard the dereference of the indirect load with a test of whether the value is a null reference.
However, if generation of profiling trees is halted early during `TR_JProfilingValue::lowerCalls`, any value beneath the `jProfileValueWithNullCHK` will simply be left anchored in its original position, unguarded.  This can result in a segmentation fault if the value that was to be …
=> [v0.53.0] Defer generating dereference of vft-symbol in JProfilingValue

runtime/compiler/optimizer/J9TransformUtil.cpp
When `-Xjit:disableKnownObjectTable` is used the "Known Object Table" will not be created. Code that takes advantage of the "Known Object Table" must specifically test its presence.
=> Fix crash with -Xjit:disableKnownObjectTable

jcl/src/java.base/share/classes/java/lang/Access.java
JDK26 `JavaLangAccess` adds `decodeASCII()`, removes `uncheckedDecodeASCII()`
Also adds `countPositives()` & `inflateBytesToChars()`, removes `uncheckedCountPositives()` & `uncheckedInflateBytesToChars()`.
This addresses the build failure - https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_OpenJDK/819/consoleFull
```
13:48:42  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:72: error: Access is not abstract and does not override abstract method decodeASCII(byte[],int,char[],int,int) in JavaLangAccess
13:48:42  final class Access implements JavaLangAccess {
```
=> JDK26 JavaLangAccess adds decodeASCII(), removes uncheckedDecodeASCII()

runtime/compiler/control/CompilationRuntime.hpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/control/JITServerCompilationThread.cpp, runtime/compiler/env/VMJ9Server.cpp, runtime/compiler/net/CommunicationStream.hpp, runtime/compiler/net/MessageTypes.cpp, runtime/compiler/net/MessageTypes.hpp, runtime/compiler/runtime/JITClientSession.cpp, runtime/compiler/runtime/JITClientSession.hpp
Recent changes in Inliner have added a check of whether a method has been DLTed before (DLT stands for Dynamic Loop Transfer). As a consequence, the number of `VM_compiledAsDLTBefore` messages sent by the server has increased a lot adding to compilation overhead.
This commit eliminates all `VM_compiledAsDLTBefore` messages. The idea is for the server to keep track of all DLT compilations that it performs on behalf of a client. When the client connects for the first time to a new server, it will send the set of DLTed methods to the server, so that the server can initialize its own set. This action takes care of two possible situations: (1) The client connects to a server at a later point in time (because a server was not available from the very begining). (2) The client is connected to a …
=> Eliminate VM_compiledAsDLTBefore message for JITServer

runtime/tests/sharedclassapi/CMakeLists.txt, runtime/tests/sharedclassapi/module.xml, runtime/tests/sharedclassapi/sharedClasses.c
- Move the sharedClasses native code from openj9_systemtest into OpenJ9,
as part of removing the native compiler dependency in system tests.
related:https://github.com/adoptium/aqa-tests/issues/5965
=> Move SharedClassAPI test native code into openj9

runtime/nls/j9vm/j9vm.nls, runtime/vm/createramclass.cpp, runtime/vm/lookupmethod.c, runtime/vm/vm_internal.h, test/functional/cmdLineTests/classLoaderTest/build.xml, test/functional/cmdLineTests/classLoaderTest/illegalAccessErrorTest.xml, test/functional/cmdLineTests/classLoaderTest/playlist.xml, test/functional/cmdLineTests/classLoaderTest/src/org/openj9/test/illegalAccessError/DefaultVisibility.java, test/functional/cmdLineTests/classLoaderTest/src/org/openj9/test/illegalAccessError/DefaultVisibilityInterface.java, test/functional/cmdLineTests/classLoaderTest/src/org/openj9/test/illegalAccessError/ExtendsDefaultVisibility.java, test/functional/cmdLineTests/classLoaderTest/src/org/openj9/test/illegalAccessError/ExtendsDefaultVisibilityInterface.java, test/functional/cmdLineTests/classLoaderTest/src/org/openj9/test/illegalAccessError/IllegalAccessErrorTest.java, test/functional/cmdLineTests/classLoaderTest/src/org/openj9/test/illegalAccessError/ImplementDefaultVisibilityInterface.java
Improve `IllegalAccessError` with specific exception messages
The improved exception message looks like:
```
java.lang.IllegalAccessError: class org/openj9/test/illegalAccessError/ExtendsDefaultVisibility (in unnamed module 0x0000000000000000 from loader java/net/URLClassLoader) cannot access its superclass org/openj9/test/illegalAccessError/DefaultVisibility (in unnamed module 0x0000000000000000 from loader jdk/internal/loader/ClassLoaders$AppClassLoader)
```
Added a test.
=> Improve IllegalAccessError with specific exception messages

runtime/compiler/runtime/J9CodeCacheManager.cpp
Remove the 16M restriction on large page size in the code cache manager for Power. The requested page size would have already been verified as valid when parsing the options, and any valid size request should be honoured.
=> Remove Hard-Coded Restrictions to CodeCache Page Sizes on P

doc/compiler/jitserver/IProfiler.md, runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/env/j9methodServer.cpp, runtime/compiler/env/j9methodServer.hpp, runtime/compiler/net/CommunicationStream.hpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/runtime/IProfiler.cpp, runtime/compiler/runtime/IProfiler.hpp, runtime/compiler/runtime/JITClientSession.cpp, runtime/compiler/runtime/JITClientSession.hpp, runtime/compiler/runtime/JITServerIProfiler.cpp, runtime/compiler/runtime/JITServerIProfiler.hpp, runtime/compiler/runtime/JITServerProfileCache.cpp, runtime/compiler/runtime/JITServerProfileCache.hpp
Fanin data is used by the Inliner to determine from how many different places a callee is invoked. Fanin data is collected by the interpreter profiler and is kept per j9method caller. For each caller we have a linked list of up to 20 entries of <caller, pcIndex, numSamples>  (the searching key is <caller, pcIndex>). Currently, the fanin data is serialized and sent to server every time the server creates a j9ResolvedMethod (this happens very often).
This PR proposes to store fanin data at the server in a shared repository (JITServerSharedProfileCache hashtable) that can be accessed by different clients. The 'key' to search for the fanin data of a particular method is a `AOTCacheMethodRecord`. The 'value' is a `ProfiledMethodEntry` which includes a `FaninProfile`. For simplicity, the …
=> JITServer shared fanin cache

runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/CompilationThread.hpp, runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/runtime/JITServerAOTDeserializer.cpp, runtime/compiler/runtime/JITServerAOTDeserializer.hpp
The wasDeserialized flag is used to inform other threads that the deserializer was reset. This used to be a member of the TR_CompilationInfoPerThread class. However, this class is only guaranteed to exist for compilation threads. In preparation to support AOT Method Dependencies for JITServer, a non-compilation thread may need to invoke the deserializer. As such, there needs to be a way to inform non-compilation threads that the deserializer was reset.
This commit refactors out the flag and places it in the TR_J9VMBase class. It also adds an API to allow non-compilation threads to register with the Deserializer to be notified about when the deserializer gets reset.
See https://github.com/eclipse-openj9/openj9/issues/22014
=> Refactor wasDeserialized flag

test/TestConfig/resources/excludes/current_exclude_8.txt
- Copy over `current_exclude_8 file into openj9
related:https://github.ibm.com/runtimes/backlog/issues/1671
=> Copy over `current_exclude_8` into openj9

doc/release-notes/0.51/0.51.md
Documenting the issue seen when using docker container with IBM Semeru Runtime built on IBM Z17 hardware where AOT compiled code gets invalidated.
=> Add documentation about docker AOT issue on Linux on IBM Z®

runtime/tests/sharedclassapi/sharedClasses.c
Whilst compiling with Open XL on z/OS, what usually would appears as a warning surfaces as an error:
error: call to undeclared function '__atoe'; ISO C99 and later do not support implicit function declarations
[-Wimplicit-function-declaration]
This change includes the header that declares this function.
=> Add missing header include required by __atoe

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp
When loading `MemberName.vmindex` for the call to `dispatchVirtual`, we were loading using `aloadi`. However, this field has type `long`, which creates problems on x86_32.
This commit changes the load to use `lloadi` instead to avoid the compiler assertion fail `bad integer narrowing constraint`
Issue: #18751
=> Fix 'bad integer narrowing constraint' assertion fails occurring with OpenJDK MethodHandle implementation on X86_32

runtime/oti/ContinuationHelpers.hpp, runtime/oti/j9.h
This fixes a build break in Java 21.
Related to https://github.com/eclipse-openj9/openj9/pull/22144
=> Restrict virtual unblocker thread signal definitions to Java 24+

runtime/oti/j9.h
Set `pendingBlockedVirtualThreadsNotify` bool before notifying the unblocker thread.
=> Set the notify bool before calling notify()

CMakeLists.txt
Newer builds of cmake are no longer compatible with version 3.4.
Combined with https://github.com/eclipse-omr/omr/pull/7817, builds succeed with cmake version 4.0.3.
=> Support using newer versions of cmake

runtime/vm/vmthread.cpp
When running on a single CPU, a tight spin loop may only waste CPU resources because there the thread that holds the lock cannot run on another CPU and release the lock. In such a case it's better to directly yield the CPU to another thread, hopefully the thread that holds the lock.
=> Use a "defaultMonitorSpinCount1" value of 1 when running on a single CPU

runtime/vm/BytecodeInterpreter.hpp
When calling the various linkTo methods (namely `linkToStatic()`, `linkToSpecial()`, `linkToVirtual()`, `linkToInterface()`), the JIT must pass in a `MemberName` object which` linkTo*()` expects to be at `_sp[0]`. The `linkTo*()` methods use the MN to find the target method, after which it is not needed. So, before running the target, we move the MN to `_sp[methodArgCount]`, where `methodArgCount` is the argument count of the target method.
This creates problems on x86 32 bit, where we pass arguments on the stack. When calling a MH from JITed code where we transition into the interpreter, only the target method's arguments will be popped of the stack upon return which causes the MN address to end up in the EIP when the caller returns.
This PR changes the `linkTo*()` methods to pop the MN …
=> Remove MemberName Object Ref from Stack in OpenJDK MethodHandle linkTo* INL Methods

runtime/compiler/control/JITClientCompilationThread.cpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/env/VMJ9Server.cpp, runtime/compiler/env/VMJ9Server.hpp, runtime/compiler/il/J9Symbol.cpp, runtime/compiler/il/J9Symbol.hpp, runtime/compiler/net/CommunicationStream.hpp, runtime/compiler/net/MessageTypes.cpp, runtime/compiler/net/MessageTypes.hpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/optimizer/J9TransformUtil.cpp, runtime/compiler/optimizer/MethodHandleTransformer.cpp, runtime/compiler/optimizer/MethodHandleTransformer.hpp
When the VarHandle object and the AccessDescriptor objects are known, we can perform a compile-time lookup of the corresponding entry in the VarHandle's MethodHandle table. This commit enables such a
transformation through the following:
* Add recognized fields from which the MethodHandle table gets loaded, accounting for the differences different JDK versions
* Add checkVarHandleGenericType to the list of non-inlinable methods
* Add new function in MethodHandleTransformer to be triggered when visiting checkVarHandleGenericType call node that generates the trees and transforms the call node.
Furthermore, visitStoreToLocalVariable can now be triggered for cases of direct stores of nodes anchored by PassThrough nodes, which would result from calls that have been transformed into …
=> Fold calls to Invokers.checkVarHandleGenericType into its result

test/functional/cmdLineTests/jfr/jfrevents.xml
Enable JFR NativeLibrary test on MacOS and Windows. 
Update the platform tag.
=> Enable JFR NativeLibrary event test for MacOS and Windows

jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java
JDK26 migrates away from `jdk.internal.ref.Cleaner`
Use `sun.nio.Cleaner` instead.
Required by 
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/1044
=> JDK26 migrates away from jdk.internal.ref.Cleaner

CMakeLists.txt, doc/build-instructions/Build_Instructions_V11.md, doc/build-instructions/Build_Instructions_V17.md, doc/build-instructions/Build_Instructions_V21.md, doc/build-instructions/Build_Instructions_V8.md, doc/build-instructions/cmake.md
See some discussion in https://github.ibm.com/runtimes/infrastructure/issues/10196 about compatibility with cmake 4.x
=> Update the cmake minimum version to 3.5

test/functional/cmdLineTests/jfr/jfrevents.xml
Update platform tag to enable SystemProcess test on macOS
=> Enable JFR SystemProcess test on macOS

runtime/compiler/optimizer/EstimateCodeSize.cpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/optimizer/J9Inliner.hpp
This commit fixes the misspelled function name
supressInliningRecognizedInitialCallee().
=> Fix spelling of "supress"

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp, runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
This commit generates vectorized inlined code for AArch64 for methods StringLatin1.indexOf([BI[BII)I and
JITHelpers.intrinsicIndexOfStringLatin1().
=> AArch64: Inline StringLatin1.indexOf([BI[BII)I

runtime/compiler/optimizer/J9EstimateCodeSize.cpp
During EstimateCodeSize, if we came across a callee method that was deemed too big, and therefore, set to be discarded as an inlining candidate, a size adjustment for other methods above such methods is necessary to ensure the entire call graph does not get marked as too big. For JDK8 and 11, this adjustment was disabled due to a functional issue that was exposed due to the different inlining outcome from this adjustment. This change removes the restriction that was in place as a workaround, and fixes performance issues resulting from early ECS termination in JDK8 and 11.
The restriction placed to avoid any functional issues until JDK8 and 11 builds switch to using OpenJDK MethodHandle implementation is to terminate recursive ECS once we reach a MethodHandle thunk archetype.
With the …
=> Enable bigCallee size adjustment during ECS for JDK8 and 11

runtime/compiler/optimizer/VectorAPIExpansion.cpp
- Improve assert about the type of intrinsic operand
- Correct return type of Convert intrinsic since it can it be Vector or Mask
=> Apply fixes in VectorAPIExpansion

runtime/jcl/common/jcldefine.c
The initialization of classObject of J9Class is done by
loadWarmClassFromSnapshot() and make initializeSnapshotClassObject()
redundant. Other modification includes if the call is failed, go to
exit or error processing.
Fixes: #22201
=> RAM Class Persistence: Remove redundant call to initializeSnapshotClassObject

runtime/vm/ContinuationHelpers.cpp
Only set VirtualThread.blockPermit for a virtual thread in the BLOCKING state when the lock is available. This prevents virtual threads from being unblocked prematurely.
Fixes: https://github.com/eclipse-openj9/openj9/issues/22077
Grinder: https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/52611/
=> Set blockPermit for BLOCKING thread when lock is free

runtime/rasdump/javadump.cpp
There's no definitive rule regarding how many spaces each tab represents, so avoid the issue by using spaces exclusively.
=> Don't write tabs to java dumps

runtime/compiler/optimizer/J9EstimateCodeSize.cpp
Enabling peeking ILGen for non-root methods that contain invokedynamic or invokehandle bytecodes. This will ensure that final field folding necessary for obtaining the target method is possible, and paves the way for more inlining opportunities along MethodHandle operations.
=> Enable peeking ILGen for methods with invokedynamic/invokehandle

runtime/compiler/x/codegen/J9X86Instruction.cpp
X87 registers are no longer allocated.
~~Requires coordinated merge with https://github.com/eclipse-omr/omr/pull/7799~~
=> Remove TR_X87_Mask guarded code

jcl/src/java.base/share/classes/java/lang/Class.java
Enabling the reflect cache debugging logic you can see there are numerous paths that can poison the reflection caches with non-root reflection objects. Rather than attempt to unravel all the possible paths in to this point I figured it would be easier to just extract the root instances and move on.
I'm not 100% on the preprocessor logic in use here, and whether this code is going to tolerate all the different possible target JDK version? I assume/hope that there's enough CI coverage to prove if this needs more work/polish.
Fixes https://github.com/eclipse-openj9/openj9/issues/14143
=> Prevent non-root accessible objects from poisoning the cache

runtime/compiler/p/runtime/PicBuilder.spp, runtime/jilgen/jilconsts.c
This PR inserts iTableWalk for POWER in IPIC `_interfaceSlotsUnavailable` to be performed before calling the VM helper for better interface call performance when cache-miss.
The reason of choosing `_interfaceSlotsUnavailable` is because its the target called by the snippet after the 2 cache slots in the compilation snippet is populated and was a cache-miss. Hence interface calls use already existing paths to find and populate the caches (`_interfaceCallHelper` and `_interfaceCompeteSlot2`) and then the snippet call is patched to `_interfaceSlotsUnavailable` where the iTableWalk is performed.
New implementation path (after cache is populated):
1. Mainline cache check for the 2 snippet cache slots
2. IPIC lastITableCheck (checks the `J9Class.lastITable` cache)
3. IPIC iTableWalk (checks …
=> Insert iTableWalk in _interfaceSlotsUnavailable

runtime/compiler/z/codegen/J9CodeGenerator.cpp, runtime/compiler/z/codegen/J9CodeGenerator.hpp
enables new version of the evaluator for Class.isAssignableFrom which uses a C Helper call for interfaces and abstract classes as opposed to a JNI call. The enabled change also does a class depth test at compile time (when possible) to further improve performance of Class.isAssignableFrom
=> Enable new Class.isAssignableFrom evaluator on Z

runtime/compiler/optimizer/VectorAPIExpansion.hpp
Depends on: eclipse-omr/omr#7833
=> x86: Enable VectorAPI at 128-bits

runtime/compiler/z/codegen/J9TreeEvaluator.cpp
Previously we were skipping test case generation for most cases when both the toClassSymRefs and fromClassSymRefs are resolved at compile time and both are not interfaces.
Now the we set the fastFail guard in the correct branch to only fast fast when we known the depths at compile time and toClassDepth > fromClassDepth
Fixes: #22276
=> Move fast fail into correct branch

runtime/compiler/optimizer/J9EstimateCodeSize.cpp
This commit disables peeking ILGen due to presence of invokedynamic or invokehandle bytecodes. This is meant to be a temporary measure until DDR test failures caused with such peeking ILGen can be investigated and fixed. Peeking ILGen for non-root methods containing invokedynamic/invokehandle bytecodes would now have to be enabled using the option TR_enablePeekingForMHInvokes.
Issue: #22256
=> Guard peeking behaviour for invokedynamic/handle with an env option

runtime/vm/monhelpers.c
When debugging issues related to `OBJECT_HEADER_LOCK_FLC`, global search of `OBJECT_HEADER_LOCK_FLC` will miss this piece of code, which makes things harder. If the code is checking for a macro, use the macro rather than its value.
=> Modify objectMonitorExit to use OBJECT_HEADER_LOCK_FLC instead of 0x02

test/functional/cmdLineTests/jfr/jfrevents.xml
Remove platform tag to enable SystemProcess test on all platforms.
=> Enable JFR SystemProcess test on Windows

runtime/compiler/control/J9Options.cpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/env/VMJ9.h, runtime/compiler/ilgen/IlGenerator.cpp, runtime/compiler/ilgen/J9ByteCodeIlGenerator.hpp
Dynamic loop transfer can transfer control from the interpreter into a JIT-compiled method after the point at which `monitorenter` bytecode instructions have been executed.  With Java 24 and later, the JVM uses the JIT's live monitor metadata to locate monitors that might need to be detached from carrier threads when the owning virtual thread is unmounted.
If the JIT is unable to determine that no `monitorenter`s will be executed prior to the entry point for dynamic loop transfer, it must fail the compilation.
Fixes: #22266
Port of pull request #22291 to v0.54.0-release branch
=> [0.54] Detect any monitorenter before point of dynamic loop transfers

runtime/gc_modron_startup/mmparseXgc.cpp
-Xgc:enableEstimateFragmentation and -Xgc:disableEstimateFragmentation options have been added.
=> Add -Xgc options to enable/disable Estimate Fragmentation

runtime/compiler/control/HookedByTheJit.cpp
Previously, the rate of the JIT sampling thread was decided only based on the number of "active" Java threads (threads with VM access) using a very simple formula:  `period = max(10 ms, 2ms * numActiveThreads)`. 
The idea was to limit the overhead of sampling when the number of threads increases.
However, when the JVM is heavily starved of CPU resources, the sampling thread will still beat every 10 ms, while the application thread may get little time on the CPU. This is another example of sampling thread vs application thread imbalance which this commit attempts to fix.
Starting with this commit, the rate of the sampling thread will also be adjusted based on the CPU utilization of the JVM and the entire machine. Basically, we want the sampling thread to be less active when we detect that …
=> Adjust sampling thread rate based on CPU utilization

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/stackwalker/JITStackWalker.java, runtime/codert_vm/jswalk.c
There are cases that the stack walker walk jit frames in transition frame e.g. when a virtual thread fails to enter a synchronized method. We still walk the register map in transition frame if there are object slots in registers but we don't update the register table with spilled registers which is causing failure.
This PR add procedure to update register table with spilled register when it is in method prologue for synchronized method cases.
Closes: https://github.com/eclipse-openj9/openj9/issues/22079
Backport of https://github.com/eclipse-openj9/openj9/pull/22303
=> (0.54) Add spill registers in walkTransitionFrame()

runtime/jcl/common/system.c, runtime/tests/zos/zosnatives.c
WARNING CCN3280 system.c: lines 104, 106
* assignment between types "char*" and "const char*" is not allowed
WARNING CCN3068 zosnatives.c: line 275
* operation between types "unsigned short*" and "const unsigned short*" is not allowed
Also tidy up: formatting, initialize locals
=> Fix compile warnings in native code on z/OS

runtime/oti/arm64helpers.m4
The macro `BRANCH_VIA_VMTHREAD` in the JIT runtime uses the `x8` register to perform an indirect branch to an arbitrary function. However, this macro may be used in contexts where it is not safe to clobber `x8`.
Use the conventional AArch64 ABI register `x16` for this purpose instead. The JIT does not register assign `x16` so there are no conflicts.
Issue: #21824
=> Use AArch64 IPC register for indirect branches in JIT runtime

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp, runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
This commit adds support for off-heap arrays in inlineIntrinsicIndexOf() for AArch64.
=> AArch64: Add support for off-heap arrays in inlineIntrinsicIndexOf()

runtime/oti/phelpers.m4
r11 is volatile for private-linkage, helper-linkage, and system-linkage.
in any case, hardware link stack for return-address prediction is destroyed by a non-local return, although it has no functional implications.
=> Use r11 instead of r0 for non-local-return

runtime/compiler/x/codegen/J9CodeGenerator.cpp, runtime/compiler/x/codegen/J9CodeGenerator.hpp, runtime/compiler/x/codegen/J9TreeEvaluator.cpp
This commit introduces `getMaxPreferredVectorLength()` for detecting the optimal vector length for compiler intrinsics. New intrinsics that support 256-bit and 512-bit vectorization should consult this function. Wider vectors can cause CPU frequency throttling on some microarchitectures. An ~8% freq regression was observed on Haswell with 256-bit vectorization. This function should avoid penalties by preferring smaller lengths on some microarchitectures.
=> x86: Introduce getMaxPreferredVectorLength()

runtime/oti/phelpers.m4
r11 is volatile for all linkages
Backport https://github.com/eclipse-openj9/openj9/pull/22345
=> (0.54) Use r11 instead of r0 for non-local return

buildenv/jenkins/variables/defaults.yml
We started running nightly jdk24 release builds. Keep more than the last 3, otherwise the build from the last weekend is quickly gone.
=> Keep 10 release builds instead of 3

runtime/oti/monhelp.h, runtime/vm/ContinuationHelpers.cpp
Extract side-effects out of assertions and remove
redundant parentheses in monhelp.h.
=> Extract side-effects out of assertions

runtime/compiler/env/CpuUtilization.cpp, runtime/compiler/env/CpuUtilization.hpp
Use the newly added userTime, systemTime, and idleTime fields in
J9SysinfoCPUTime to evaluate CPU load.
When all three fields are available for both current and previous
samples, CPU load is now calculated as:
```
CPU load = (user + system) / (user + system + idle)
```
This replaces the previous calculation which relied on only cpuTime
and timestamps:
```
CPU load = (cpuTime delta) /
(number of CPUs * elapsed time)
```
If the new fields are unavailable, the implementation falls back to the
old method.
The average CPU usage and idle percentages are now computed using these
new ratios, and the values are stored in the CPU usage circular buffer
alongside user, system, and idle samples for better historical
tracking.
Depends on https://github.com/eclipse-omr/omr/pull/7853.
=> Use user/system/idle times for CPU load calculation in CpuUtilization

runtime/vm/BytecodeInterpreter.hpp
Ensure that the continuation blocking enter detects if the caller is
from a J2I frame so that the continuation can resume from the correct
point upon return.
Fixes https://github.com/eclipse-openj9/openj9/issues/22340
=> Add J2I check in stackoverflow handling

runtime/oti/monhelp.h, runtime/vm/BytecodeInterpreter.hpp, runtime/vm/ContinuationHelpers.cpp, runtime/vm/montable.c, runtime/vm/threadhelp.cpp
Add a notify to unblocker in both vthread and platform thread wait
paths. Also, fix the lockword comparison to account for different
lockword modes (learning & reserved). Also, add some assertions to
catch invalid cases.
Fixes the MonitorWaitNotify test
Fixes: https://github.com/eclipse-openj9/openj9/issues/22332
Backport of https://github.com/eclipse-openj9/openj9/pull/22308 and https://github.com/eclipse-openj9/openj9/pull/22352
=> (0.54) Add notify to carrier thread wait path 

runtime/vm/BytecodeInterpreter.hpp
Ensure that the continuation blocking enter detects if the caller is from a J2I frame so that the continuation can resume from the correct point upon return.
Fixes https://github.com/eclipse-openj9/openj9/issues/22340
=> Add J2I check in stackoverflow handling v2

runtime/compiler/control/CompilationRuntime.hpp, runtime/compiler/control/HookedByTheJit.cpp, runtime/compiler/control/J9Options.cpp, runtime/compiler/control/J9Options.hpp
`CompilationInfo` will a add a boolean flag that indicates whether or not the JVM is starved of CPU resources. The flag is supposed to be used by future commits. The flag is set/reset by the sampling thread based on the CPU utilization of the JVM and the machine it is running on. 
The feature is controlable through a new option, `-Xjit:jvmStarvationThreshold=<NNN>`, whose default value is 40. If the CPU utilization of the JVM is lower than jvmStarvationThreshold-10 either because of low JVM CPU entitlement or because of other processes running on the machine, the starvation flag is set. When the CPU utilization of the JVM goes above jvmStarvationThreshold+10, the flag is reset. The flag is also reset if the JVM does not use its entire CPU entitlement and there are idle CPUs on the system.
=> Add flag for JVM CPU starvation

runtime/jvmti/jvmtiStackFrame.cpp
The JDWP frames command sets max_frame_count for JVMTI GetStackTrace
based on the value returned by JVMTI GetFrameCount, and expects the
number of frames filled by GetStackTrace to match that frame count.
For JDK 20 and later, when debugging virtual threads, the first stack
walk in jvmtiInternalGetStackTrace may filter out frames annotated
with JvmtiMountTransition. These frames represent mount and unmount
transitions for virtual threads and are not reported to the debugger.
As a result, the frame count returned by GetStackTrace can be less than
expected, causing JDWP to report a
com.sun.jdi.InternalException: Unexpected JDWP Error: 113.
This change increases maxFrames in the second stack walk by the number
of frames skipped in the first pass. This ensures that after skipping
mount …
=> Adjust maxFrames in jvmtiInternalGetStackTrace for skipped frames

runtime/compiler/env/J9KnownObjectTable.cpp, runtime/compiler/env/VMJ9.cpp, runtime/compiler/optimizer/InterpreterEmulator.cpp
The possibility of failure makes this method inapplicable at some call sites, and unwieldy at others. There doesn't seem to be any good reason why this method needs to be fallible though. By simply blocking until it gets VM access, it can always succeed.
=> Make `getObjectClassFromKnownObjectIndex()` always succeed

runtime/vm/BytecodeInterpreter.hpp
Add a null check for `_currentThread->threadObject` in
`inlThrowableFillInStackTrace` to prevent a crash during early JVM
startup.
When `J9_EXTENDED_RUNTIME2_SHOW_CARRIER_FRAMES` is enabled,
continuation stack walking is triggered to collect carrier frames. This requires
a valid `threadObject`, which may be uninitialized during early exceptions
(e.g., during `Unsafe.registerNatives`). Without the check, a `null`
dereference can occur when calling `IS_JAVA_LANG_VIRTUALTHREAD`.
This fix ensures stack walking is only attempted when `threadObject` is
set, preventing segmentation faults during JVM initialization.
Related: https://github.com/eclipse-openj9/openj9/issues/21734
=> Avoid crash in fillInStackTrace when threadObject is null

runtime/compiler/control/CompilationRuntime.hpp, runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/HookedByTheJit.cpp
This commit implements heuristics that reduce the compilation overhead when the JVM is starved of CPU resources. Specifically, the following changes are performed under CPU starvation conditions:
- Warm compilations will be downgraded to cold. If allowed, (SCC is enabled, enough space in SCC, etc) these compilations will use AOT.
- For AOT compilations some of the expensive optimizations will be disabled.
- Inlining will be subdued (similar to the -Xtune:virtualized case)
All these changes can be disabled by preventing the JVM to enter the starvation mode with -Xjit:jvmStarvationThreshold=-1
=> Reduce compilation overhead when JVM is CPU starved

runtime/vm/BytecodeInterpreter.hpp
Add a null check for `_currentThread->threadObject` in
`inlThrowableFillInStackTrace` to prevent a crash during early JVM
startup.
When `J9_EXTENDED_RUNTIME2_SHOW_CARRIER_FRAMES` is enabled,
continuation stack walking is triggered to collect carrier frames. This requires
a valid `threadObject`, which may be uninitialized during early exceptions
(e.g., during `Unsafe.registerNatives`). Without the check, a `null`
dereference can occur when calling `IS_JAVA_LANG_VIRTUALTHREAD`.
This fix ensures stack walking is only attempted when `threadObject` is
set, preventing segmentation faults during JVM initialization.
Related: https://github.com/eclipse-openj9/openj9/issues/21734
Backport of https://github.com/eclipse-openj9/openj9/pull/22382
=> (0.55) Avoid crash in fillInStackTrace when threadObject is null

runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp, runtime/compiler/env/j9method.cpp, runtime/compiler/optimizer/InlinerTempForJ9.cpp, runtime/compiler/x/codegen/J9TreeEvaluator.cpp, runtime/compiler/z/codegen/J9CodeGenerator.cpp
This commit changes the JIT compiler to recognize the method StringUTF16.indexOfUnsafe([BI[BII)I in addition to StringUTF16.indexOf([BI[BII)I.
It improves the performance of String.indexOf(String) on Z and X with Java 17+.
=> Recognize StringUTF16.indexOfUnsafe([BI[BII)I

runtime/oti/ContinuationHelpers.hpp
thrtypes.h includes dependency to <fcntl.h> which on AIX contains
macro: #define open open64
This conflicts with other uses of the name "open" in files that
includes "ContinuationHelpers.hpp".
Fix: #22410
=> Undefine conflicting macro in header file

runtime/oti/ContinuationHelpers.hpp
thrtypes.h includes dependency to <fcntl.h> which on AIX contains macro: #define open open64
This conflicts with other uses of the name "open" in files that includes "ContinuationHelpers.hpp".
Backport of #22413
=> (v0.54.0) Undefine conflicting macro in header file

runtime/oti/ContinuationHelpers.hpp
thrtypes.h includes dependency to <fcntl.h> which on AIX contains macro: #define open open64
This conflicts with other uses of the name "open" in files that includes "ContinuationHelpers.hpp".
Backport of #22413
=> (v0.55.0) Undefine conflicting macro in header file

runtime/jcl/exports.cmake, runtime/oti/jclprots.h
The native method should only be declared and exported if configured with JFR support.
Fixes: https://github.com/eclipse-openj9/openj9/issues/22422.
=> JFR: Fix Windows build failure

runtime/gc_vlhgc/HeapRegionManagerVLHGC.cpp, runtime/gc_vlhgc/IncrementalGenerationalGC.cpp, runtime/gc_vlhgc/IncrementalGenerationalGC.hpp, runtime/gc_vlhgc/SchedulingDelegate.cpp, runtime/gc_vlhgc/SchedulingDelegate.hpp
Previous PR https://github.com/eclipse-openj9/openj9/pull/17107 target
to prevent exception "committed argument cannot be less than 0" for
MemoryPool "balanced-reserved" during collecting memoryUsage at the end
of GC(balanced GC only), but there are two special cases haven't been
covered.
Fix case 1: maxHeapExpansionRegions could add on maxEdenChange and use
_extensions->globalVLHGCStats._heapSizingData.edenRegionChange to notify
heap resize to adjust heap size to match eden change, but it did not
consider the case which eden size is bigger than free memory, so update
_extensions->globalVLHGCStats._heapSizingData.edenRegionChange =
OMR_MIN(maxHeapExpansionRegions, edenChangeWithSurvivorHeadroom +
(intptr_t)(_edenRegionCount - freeRegions));
for keeping free memory >= eden size after heap …
=> Fix exception "committed argument cannot be less than 0"

runtime/j9vm/exports.cmake, runtime/j9vm/vmi.c, runtime/oti/sunvmi_api.h, runtime/redirector/forwarders.m4, runtime/sunvmi/sunvmi.c
Uses were removed earlier, but even the declaration has been removed from `jvm.h`:
* [8364750: Remove unused declaration in jvm.h](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/f64b51c0a6e3ac7997041165a0e03ee02b687573)
=> Remove JVM_GetClassAccessFlags() no longer used by Java 26+

runtime/compiler/p/codegen/J9CodeGenerator.cpp, runtime/compiler/p/codegen/J9TreeEvaluator.cpp
Fast path the StringCoding methods countPositives and hasNegative on Power, since their logics are similar, they can be implemented by a single instrinsic.
=> Fast Path StringCoding.countPositives and hasNegative for Power

jcl/src/java.management/share/classes/java/lang/management/ManagementPermission.java
JDK25+ `ManagementPermission` adds `@Deprecated` annotation
Cherry-pick
* https://github.com/eclipse-openj9/openj9/pull/22458
=> (0.55) JDK25+ ManagementPermission adds @Deprecated annotation

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
This commit generates vectorized inlined code for AArch64 for methods StringUTF16.indexOf([BI[BII)I and
JITHelpers.intrinsicIndexOfStringUTF16().
=> AArch64: Inline StringUTF16.indexOf([BI[BII)I

runtime/compiler/optimizer/DataAccessAccelerator.cpp
An extra address node is created for BCDCHK but in some scenarios, no BCDCHK is required and the extra address node remains orphaned. This PR created the extra node only if it is required.
=> Remove unused node from pdstore transformer

runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp, runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
This commit generates vectorized inlined code for AArch64 for the following StringCoding methods.
- hasNegatives()
- countPositives()
=> AArch64: Accelerate StringCoding.hasNegatives()/countPositives()

buildenv/jenkins/variables/defaults.yml
Port of https://github.com/eclipse-openj9/openj9/pull/22456
=> (0.55) Update AIX bootjdk 24 to use release build

jcl/src/java.base/share/classes/java/lang/Access.java
JDK26 Access method updates
Removed `newStringUTF8NoRepl()` and `uncheckedEncodeASCII()` for JDK26;
JDK26 now uses encodeASCII() like pre-JDK25 levels;
Added `uncheckedNewStringWithLatin1Bytes()` for JDK26.
Resolves Java next compilation error - https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_OpenJDK/861/consoleFull
```
23:51:33  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:72: error: Access is not abstract and does not override abstract method encodeASCII(char[],int,byte[],int,int) in JavaLangAccess
23:51:33  final class Access implements JavaLangAccess {
23:51:33        ^
23:51:33  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-s …
```
=> JDK26 Access method updates

runtime/bcutil/cfreader.c
Corrupt InnerClasses attribute entries should not interrupt the vm.
Port of https://github.com/eclipse-openj9/openj9/pull/22464
=> (0.55) InnerClasses entries are duplicates iff all indices match

runtime/compiler/optimizer/VectorAPIExpansion.cpp
VectorAPIExpansion create an address node with
generateArrayElementAddressNode() to load the target address. This load address node has an inner lshl node. The fisrt child of lshl must be a long type but a int type was passed instead.
This PR fix the passed child type.
=> Fix vectorAPI unboxNode

runtime/libffi/z/ffi.c, runtime/libffi/z/ffi64.c, runtime/libffi/z/ffitarget.h, runtime/libffi/z/sysvz64.s
In case of variadic arguments in XPLINK, all arguments within the variadic part are passed into GPRs if available or argument list even if arguments are of double type. z/OS port of Libffi was missing handling of such variadic arguments, causing us to pass double or complex type parameters into FPRs. This commit adds new field in ffi_cif struct providing number of fixed args in parameters and use it to ensure double or complex type parameters within variadic part is set up correctly.
=> Update LIBFFI for z/OS for varargs

runtime/codert_vm/decomp.cpp, runtime/codert_vm/j9codertvm.tdf, runtime/jvmti/jvmtiStackFrame.cpp, runtime/jvmti/jvmti_internal.h, runtime/oti/j9nonbuilder.h, runtime/oti/jitprotos.h
Introduce the `ClearAllFramePops` function to clear all pending frame pop
requests for a thread, preventing `FramePop` events. Clears the
`J9SF_A0_REPORT_FRAME_POP_TAG` during a stack walk, resets early return
info, clears the `POP_FRAMES_INTERRUPT` halt flag, and deletes JIT
decompilation entries with reason `JITDECOMP_POP_FRAMES`.
Related: https://github.com/eclipse-openj9/openj9/issues/21735
Backport of https://github.com/eclipse-openj9/openj9/pull/22479
=> (0.55) Implement JVMTI ClearAllFramePops and cleanup related decompilations

runtime/oti/j9nonbuilder.h, runtime/oti/jvminit.h, runtime/util/vmargs.c, runtime/vm/jvminit.c, runtime/vm/jvminitcommon.h, runtime/vm/logsupport.c
* remove duplicates of `OPTION_*` macros defined by OMR
* move `DLLNAME_LEN` to `j9nonbuilder.h` for use by `J9VMDllLoadInfo`
* move some constants from `jvminitcommon.h` to `jvminit.h`
* improve definitions of `{SMALL,LARGE}_STRING_BUF_SIZE`
* remove unused `MED_STRING_BUF_SIZE`
* add parentheses to macro definitions of negative values
* make `JVMINIT_VERBOSE_INIT_*TRACE*` macros consistent
=> Remove duplicate macro definitions and make other improvements

runtime/compiler/codegen/J9CodeGenerator.cpp, runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp, runtime/compiler/x/i386/codegen/IA32PrivateLinkage.cpp
Previously, the VTable index argument register was not marked as such on x86-32 for 32-bit arguments, which caused issues when invoking MethodHandles through dispatchVirtual. 
This changes dispatchVirtual to always use `long` arg0 for the jit entry point and jit vft offset so the index register is marked properly in linkage.
Issue: #18751
=> Fix x86-32 private linkage for dispatchVirtual

runtime/gc_glue_java/MarkingSchemeRootMarker.cpp, runtime/vm/classsupport.c, runtime/vm/visible.c
Add missing locks for module hashtable access. Also add missing check to scan modularity objects.
Fixes https://github.com/eclipse-openj9/openj9/issues/22264
Backport of https://github.com/eclipse-openj9/openj9/pull/22495
=> (0.56) Add missing locks for module hashtable access

runtime/j9vm/javanextvmi.cpp, runtime/jvmti/jvmtiHelpers.cpp, runtime/oti/j9nonbuilder.h, runtime/oti/vm_api.h, runtime/oti/vmconstantpool.xml, runtime/vm/intfunc.c, runtime/vm/threadhelp.cpp
Refactor getVMThread/releaseVMThread into internalVMFunctions
Add ThreadSnapshot constant pool entries
Set thread name, carrier and blocker object on the snapshot
Port of https://github.com/eclipse-openj9/openj9/pull/22476 and https://github.com/eclipse-openj9/openj9/pull/22517
=> (0.56) Support for ThreadSnapshot part 1

runtime/bcverify/vrfyhelp.c, runtime/oti/j9.h, test/functional/Valhalla/playlist.xml, test/functional/Valhalla/src/org/openj9/test/lworld/StrictFieldGenerator.java, test/functional/Valhalla/src/org/openj9/test/lworld/StrictFieldTests.java, test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeGenerator.java, test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java, test/functional/Valhalla/testng.xml
- update putfield verification checks for ACC_STRICT_INIT fields with latest spec draft
- separate strict field test from value type tests
Related https://github.com/eclipse-openj9/openj9/issues/21884
=> Update putfield ACC_STRICT_INIT verification and tests

runtime/compiler/env/VMJ9.cpp, runtime/compiler/p/codegen/J9TreeEvaluator.cpp
Supports the inlining of multianewArray on P when a new 2D array is created with the second dimension having a length of zero.
=> Accelerate multianewArray on P for 2D arrays

runtime/bcutil/jimageintf.c, runtime/j9vm/exports.cmake, runtime/j9vm/java11vmi.c, runtime/j9vm/jvm.c, runtime/jcl/common/sun_reflect_ConstantPool.c, runtime/oti/jclprots.h, runtime/oti/libjimage.h, runtime/oti/vmconstantpool.xml, runtime/redirector/forwarders.m4
Update signatures of `ConstantPool` natives and JVM functions:
* `ConstantPool` natives no longer receive the `constantPoolOop` reference as a parameter in jdk26 - they must fetch the field
Adapt to removal of `JIMAGE_PackageToModule()` and tidy up `jimageintf.c`:
+ remove unwanted (and unsafe) casts from `UDATA` to `I_32`
+ correct `JIMAGE` signatures in function lookups
+ don't attempt to take the address of an array
Fixes: #22518.
=> Adapt to recent changes for jdk26

runtime/compiler/x/codegen/X86PrivateLinkage.cpp
X86PicBuilder expects that the last instruction before the done label is a JNE instruction to the lookup routine. The JNE should not jump to the lookup routine, but is required because this code may be patched. This commit introduces a JNE instruction to replace a JMP instruction, which always call the lookup routine, which incurs a performance penalty.
=> x86: Fix interface dispatch performance

runtime/util/vmargs.c, runtime/vm/jvminit.c, test/functional/cmdLineTests/xxargtest/XXArgumentTesting_j9.xml
~Add GET_RAW_MEM_VALUE and associated setRawMemoryOptionToOptElse helper function. Adopt for the `-XX:MaxDirectMemorySize` parsing to avoid rounding values passed to the Java layer beyond the internal signed 64-bit limit.~
Memory option values are rounded up to be pointer-width aligned unless this would lead to a value greater than U_32_MAX or I_64_MAX on 32 and 64 bit platforms respectively. In these cases we truncate (round down) to the next pointer-width aligned value.
At the same time we add a bounds check on the MaxDirectMemorySize value on 64 bit platforms to ensure it maps safely to a Java long before passing in to the JVM initialization.
Issue https://github.com/eclipse-openj9/openj9/issues/22480
=> Modify memory option rounding to avoid overflow

runtime/util/vmargs.c
vmargs.c(342): error C2220: the following warning is treated as an error
vmargs.c(342): warning C4101: 'oldValue': unreferenced local variable
Related to https://github.com/eclipse-openj9/openj9/pull/22481
=> Remove unused var to fix compilation error on Windows

runtime/util/vmargs.c, runtime/vm/jvminit.c, test/functional/cmdLineTests/xxargtest/XXArgumentTesting_j9.xml
Memory option values are rounded up to be pointer-width aligned unless this would lead to a value greater than U_32_MAX or I_64_MAX on 32 and 64 bit platforms respectively. In these cases we truncate (round down) to the next pointer-width aligned value.
At the same time we add a bounds check on the MaxDirectMemorySize value on 64 bit platforms to ensure it maps safely to a Java long before passing in to the JVM initialization.
Issue https://github.com/eclipse-openj9/openj9/issues/22480
Backport https://github.com/eclipse-openj9/openj9/pull/22481 and https://github.com/eclipse-openj9/openj9/pull/22557
=> (0.56) Modify memory option rounding to avoid overflow

runtime/compiler/optimizer/InlinerTempForJ9.cpp
In the process of preparing to generate IL for an `Unsafe.get` method, `createUnsafeGetWithOffset` tries to determine whether sign extension or zero extension is needed for array elements of type boolean, byte, char or short.  However, it was only accounting for a subset of the `Unsafe.get` methods &mdash; for other methods, whether it performed sign or zero extension was based on an uninitialized boolean variable.
This change accounts for all known `Unsafe.get` methods that will have IL generated by `createUnsafeGetWithOffset`, and changes a `TR_ASSERT` into a `TR_ASSERT_FATAL` so we can detect if any additional `Unsafe.get` methods need to be accounted for in the future.
It also removes `sun_misc_Unsafe_putBooleanVolatile_jlObjectJZ_V` from consideration, as only `Unsafe.get` methods …
=> [0.56.0] Ensure createUnsafeGetWithOffset considers all Unsafe.get methods

runtime/gc/gctable.c, runtime/gc_base/ObjectAccessBarrier.hpp, runtime/gc_base/accessBarrier.cpp, runtime/gc_base/gc_internal.h, runtime/gc_vlhgc/VLHGCAccessBarrier.cpp, runtime/gc_vlhgc/VLHGCAccessBarrier.hpp, runtime/j9vm/java11vmi.c, runtime/oti/j9nonbuilder.h
Write Barrier should be triggered at the moment new module is added to the classloader's hash table. Introducing new external GC function j9gc_objaccess_postStoreModuleToClassLoader.
=> Add missed Write Barrier to adding new module to hash table

runtime/j9vm/javanextvmi.cpp
Make the minimal changes needed for `StructuredThreadDumpTest` to pass,
without fully implementing `jdk.internal.vm.ThreadSnapshot`.
Reorder operations so objects do not require a special frame for GC
protection when VM access is not held. This also resolves a crash.
Remove setting of `jdk.internal.vm.ThreadSnapshot.blockerObject` to avoid
a crash in `jdk.internal.vm.ThreadDumper`.
A full implementation of `ThreadSnapshot` is not required for release,
since it is an internal API used mainly for introspection in test code.
It can be developed gradually as further tests require support.
Related: #22220
Backport of https://github.com/eclipse-openj9/openj9/pull/22603
=> (0.56) [JDK25] Fix StructuredTaskScope/StructuredThreadDumpTest

runtime/compiler/control/CompilationThread.cpp, runtime/compiler/control/HookedByTheJit.cpp, runtime/compiler/env/CpuUtilization.cpp, runtime/compiler/env/CpuUtilization.hpp, runtime/compiler/runtime/CRRuntime.cpp
Existing code uses CpuUtilization info after a test on CpuUtilization->isFunctional(). However, to report CPU utilization we need two data collections at different points in time (the JVM computes the difference of two absolute values). Until the two data collections are available, the data reported by CpuUtilization cannot be trusted (for instance the JVM CPU  utilization shows up as 0).
This PR introduces a new getter, `CpuUtilization->hasValidData()` that returns true if at least two CPU data collections have been performed. The existing code has been changed to replace isFunctional() with hasValidData() for most of the queries (isFunctional() is still used when updating the CpuUtilization information).
To minimize the window of time when the CpuUtilization is functional but does not …
=> Use CpuUtilization info only if it has valid data

jcl/src/jdk.management/share/classes/com/ibm/lang/management/OperatingSystemMXBean.java
`CpuLoadCalculationConstants.UNSUPPORTED_VALUE` no longer applies to
`getCpuLoad()` and `getSystemCpuLoad()` on z/OS.
Related:
- https://github.com/eclipse-openj9/openj9-docs/issues/1584
- https://github.com/eclipse-openj9/openj9/pull/22258
- https://github.com/eclipse-omr/omr/pull/7853
=> Remove outdated z/OS documentation

jcl/src/jdk.management/share/classes/com/ibm/lang/management/OperatingSystemMXBean.java
`CpuLoadCalculationConstants.UNSUPPORTED_VALUE` no longer applies to
`getCpuLoad()` and `getSystemCpuLoad()` on z/OS.
Backport https://github.com/eclipse-openj9/openj9/pull/22632
=> (0.56) Remove outdated z/OS documentation

runtime/rastrace/method_trace.c, runtime/rastrace/mt.tdf
Address the review comments on: https://github.com/eclipse-openj9/openj9/pull/20933
The changes reflect the feature request https://github.com/eclipse-openj9/openj9/issues/20878.
Print string contents for this references.
Also, print address for string arguments and returns.
=> (Rework) Print string contents for "this" references

runtime/compiler/p/codegen/J9TreeEvaluator.cpp
The temp2Reg is used by `VMnonNullSrcWrtBarCardCheckEvaluator` in some cases in a `stbx` instruction, which can't have GPR0 as the RA argument or it will act upon it as a null value.
This can cause an unexpected register spill in the middle of an internal control-flow sequence that might not be fully executed [1].
The inserted exclusion is sufficiently conditioned under `doWrtBar && doCrdMrk` (both true only when `gcMode == gc_modron_wrtbar_cardmark_and_oldcheck`), similarly conditioned by other callers to `VMnonNullSrcWrtBarCardCheckEvaluator`, and the `stbx` instruction generated by `VMnonNullSrcWrtBarCardCheckEvaluator` is conditioned under `doCrdMrk = (gcMode == gc_modron_wrtbar_cardmark_and_oldcheck)`
Testing: https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/ …
=> Set register dep to exclude GPR0 for temp2Reg in inlineCompareAndSet

runtime/jcl/common/mgmtmemory.c, runtime/jvmti/jvmtiExtensionMechanism.c, runtime/oti/j9nonbuilder.h, runtime/vm/createramclass.cpp, runtime/vm/segment.c
This PR reverts the below PRs:
- https://github.com/eclipse-openj9/openj9/pull/22578
- https://github.com/eclipse-openj9/openj9/pull/22590
These changes are being reverted because of
- a perf issue (more details in https://github.com/eclipse-openj9/openj9/pull/22530#issuecomment-3304016781); and
- a functional issue (more details in https://github.com/eclipse-openj9/openj9/issues/22584#issuecomment-3309764285).
=> (0.56) Revert "RAM Class: Per-kind segment allocation and sizing"

runtime/gc_base/IndexableObjectAllocationModel.cpp, runtime/gc_vlhgc/AllocationContextBalanced.cpp, runtime/gc_vlhgc/AllocationContextBalanced.hpp, runtime/gc_vlhgc/CollectionSetDelegate.cpp, runtime/gc_vlhgc/CollectionSetDelegate.hpp, runtime/gc_vlhgc/CopyForwardScheme.cpp, runtime/gc_vlhgc/GlobalMarkingScheme.cpp, runtime/gc_vlhgc/ProjectedSurvivalCollectionSetDelegate.cpp, runtime/gc_vlhgc/ProjectedSurvivalCollectionSetDelegate.hpp, runtime/gc_vlhgc/SchedulingDelegate.cpp
For off-heap enabled case, the Large size Array(larger than
region size) will be allocated on sparse heap, but we still
reserve leaf regions for preventing over usage on heap.
Currently we have to allocate/reserve whole region for the
remaining bytes(remainder of array size from region size), it
potentially generate fragmentation on heap.
Introduce new _sharedArrayReservedRegionsBytesUsed in common
AllocationContext to keep the record for used bytes of the shared
reserved regions (the remainders of the Large size Arrays).
allocateFromSharedArrayReservedRegion() and
recycleToSharedArrayReservedRegion() need lock for handling multi thread
race condition.
comment:
for Off-Heap enabled case, the reserved regions(Arraylet leaf regions)
has been recycled during clearable phase of GC Scan …
=> Reduce fragmentation of reserved regions for off heap

runtime/vm/BytecodeInterpreter.hpp
If invokeinterface resolves an abstract method _sendMethod should be the interface's method. This ensures the correct error handling logic is used by
throwUnsatisfiedLinkOrAbstractMethodError.
Fixes: https://github.com/eclipse-openj9/openj9/issues/22157
With this change the output in the test from https://github.com/eclipse-openj9/openj9/issues/22157 is:
```
Exception in thread "main" java.lang.IllegalAccessError: P0/C2.m()Ljava/lang/Integer;
at P0.I0.test(Unknown Source)
at P0.I0.main(Unknown Source)
```
invokeinterface tests:
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/54641/
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/54640/
=> Invokeinterface error handling for abstract method resolution

jcl/src/java.base/share/classes/java/lang/Access.java
Add `@Override` to Access APIs and remove obsoleted methods
Related to https://github.com/eclipse-openj9/openj9/pull/22671#discussion_r2375745621
=> Add @Override to Access APIs and remove obsoleted methods

runtime/tests/port/j9vmemTest.c
Fixes https://github.com/eclipse-openj9/openj9/issues/22695.
=> Guard pragmas to avoid warnings from MSVC

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/stackwalker/StackWalker.java
The thread address is formatted as long integer in debug output that makes it difficult to read. Change the formatting to hexadecimal.
=> Fix thread address format in debug output

runtime/compiler/control/CompilationThread.cpp
=> Add extra logging when compilationHeapLimitExceeded occurs

runtime/compiler/control/CompilationThread.cpp
...if either `verbose={compileRequest}` or `verbose={failures}` is set.
=> Write to the verbose log when purging the compilation queue

jcl/jpp_configuration.xml
Noticed while reviewing #22675.
=> Add missing source folder for jdk.incubator.foreign

runtime/compiler/z/codegen/J9TreeEvaluator.cpp
Adding instructions to inline allocation of two dimensional arrays with any length. Before this change, we only inline 2d arrays if at least one dimension length is zero.
=> Z: Inline any length 2d array allocation
