eclipse-openj9/openj9

README.md

The build link and the FAQ link were incorrect, so fixed them.
Fixes #2 #3
Signed-off-by: Mark Stoodley <mstoodle@ca.ibm.com>

Fix two broken links in README.md

---

jcl/src/java.base/share/classes/java/lang/ClassCastException.java

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

fixed typo in javadoc

---

README.md

Add license badges for EPLv2 & APLv2 to the README.md

---

CONTRIBUTING.md

Update commit message guidance to mention skipping ci

---

buildenv/docker/test/Dockerfile
buildenv/docker/test/README.md

* create a Dockerfile to allow test execution
* test Dockerfile is located in buildenv/docker/test
* update build Dockerfiles to be capable to run tests
Issue: #23

Create Dockerfiles that allow test execution

---

runtime/tr.source/trj9/optimizer/EscapeAnalysis.cpp

Escape analysis may have to create initialization
code at the method start. If the first block is
part of a loop, it will create a new block to hold
these trees. However, the block test did not consider
whether the first block was in an improper region,
resulting in init code being placed inside a loop.
Signed-off-by: Nicholas Coughlin <cnic@ca.ibm.com>

Correct escape analysis loop check

---

runtime/buildtools.mk

Co-req to https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/30

Support receiving parent project warnings-as-errors parameter

---

jcl/src/java.base/share/classes/com/ibm/tools/attach/target/Attachment.java

This improves upon https://github.com/eclipse/openj9/pull/98.
Also make sure all streams are closed.
FYI @pdbain-ibm

Simplify creation of a socket connection to the attacher

---

runtime/tr.source/trj9/infra/J9Cfg.cpp

Signed-off-by: Luc des Trois Maisons <lmaisons@ca.ibm.com>

Remove unused cs2/tableof.h includes

---

runtime/tr.source/trj9/runtime/Runtime.cpp
runtime/tr.source/trj9/x/runtime/X86ArrayTranslate.asm

Optimized assembly sequences of array translate helpers.

Array Translate Improvement on X86

---

test/cmdLineTests/verbosetest/verbosetests.xml

- corrected the path in verbosetests.xml

Fix verbosetest

---

runtime/tr.source/trj9/optimizer/J9Optimizer.cpp

Optimization options for OSR have been extended
to specify the OSR mode: voluntary or involuntary.
This change updates uses of these modes in the
optimization strategies.

Use optimization options for OSR modes

---

runtime/tr.source/trj9/env/PersistentCHTable.cpp

Side effect guards are runtime guards that can
be patched on class initialization. When committing
the guard, it is necessary to check such initialization
has not yet occurred. The prior check would walk the
class hash table to determine if one of the
assumed was present. However, there are few classes
where this assumption is made, so it is cheaper to
query them directly.

Simplify check for class initialization

---

test/Makefile
test/README.md
test/TestConfig/makefile
test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl

Add external group in testKitGen

---

test/Makefile
test/README.md
test/TestConfig/makefile
test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl
test/TestConfig/scripts/testKitGen/resultsSummary/resultsSum.pl

- add perf group
- move summary to bottom
- fix corner case with empty target

Minor fix to testKitGen

---

runtime/jcl/cl_se7_basic/module.xml
runtime/jcl/common/sun_misc_URLClassPath.c
runtime/jcl/uma/se8only_exports.xml
runtime/jcl/uma/se8only_objects.xml
runtime/oti/jclprots.h

Add URLClassPath_getLookupCacheURLs stub for OpenJ9 Java8 support

---

buildenv/jenkins/README.md

- Provide list of builds with
- Build name
- Jenkins build badge
- Description
- Trigger
- Provide instructions for launching pull request builds
- Best practices when adding new builds
- link to Jenkins instance
Fixes #123

Initial commit for Jenkins README

---

runtime/j9vm/jvm.c
runtime/port/common/j9hypervisor_common.c
runtime/port/linuxs390/j9gs.c
runtime/port/linuxs390/j9ri.c

z/TPF fixes during initial sniff testing.  Fixes unresolved functions.
Fixes Memory Leak.
Signed-off-by: jjohnst-us <jjohnst@us.ibm.com>
Signed-off-by: jjohnst-us <jjohnst@us.ibm.com>

z/TPF Fixes during initial sniff testing.

---

test/VM_Test/src/j9vm/test/mxbeans/MXBeansGetterSanityTest.java

* the exception related to passed test should not be printed
Fixes: #187

fix false negative test output

---

runtime/j9vm/jvm.c

Notice a malloc without a null check.  Fixing

Add missing null check to jvm.c:isFileInDir

---

buildenv/jenkins/lineEndingsCheck

- Remove HASH as it doesnt add value to console formatting
- Change BAD_FILES def to allow appending values
Issue #63

Fix lineEndings check when fails

---

test/TestConfig/resources/excludes/openj9_exclude.txt

Temporarily exclude TestAttachAPI:
- test_agntld01
- test_agntld02
- test_agntld03
[skip ci]
Issue: #238

Exclude TestAttachAPI

---

test/TestConfig/resources/excludes/openj9_exclude.txt

Temporarily TestManagementAgent:test_startLocalManagementAgent
[skip ci]
Issue: #241

Exclude TestManagementAgent:test_startLocalManagementAgent

---

test/TestConfig/resources/excludes/openj9_exclude.txt

Temporarily exclude VmArgumentTests:testCrNocr
[skip ci]
Issue: #244

Exclude VmArgumentTests:testCrNocr

---

test/TestConfig/scripts/tools/getDependencies.pl

* validate the sha1 of downloaded dependent jars
Fixes:#198

add sha1 sum check to downloaded dependent jars

---

jcl/src/com.ibm.management/share/classes/com/ibm/lang/management/MemoryPoolMXBean.java

Update the comments of MemoryPoolMXBean common behavior changes for javaDoc

---

test/Makefile

Print java version in openJ9 targets

---

runtime/vm/FastJNI.cpp

The prefix removal code was not performing the correct match against the
method name in the per-class tables after removing the prefixes,
resulting in an inappropriate Fast JNI implementation being used for
prefixed natives.
Fixes: #269

Fix native method prefixing in Fast JNI

---

jcl/src/java.base/share/classes/java/lang/invoke/ArrayVarHandle.java

Offset and scale are used to calculate the memory address of a given array index. These values are constant and don't need to be stored in VarHandle instance fields, but can be stored in `static final` fields in `ArrayVarHandleOperations.Op*` instead.
This should benefit the VM (`invokestatic` instead of `invokevirtual`), and it should also benefit the JIT (`static final` values).

Store offset and scale per type in VH Ops classes instead of VarHandle

---

runtime/tr.source/trj9/z/codegen/J9S390CHelperLinkage.cpp
runtime/tr.source/trj9/z/codegen/J9S390CHelperLinkage.hpp
runtime/tr.source/trj9/z/codegen/J9TreeEvaluator.cpp

This commit contains following changes to JIT helper dispatch function.
1. Use pre dependency condition and clobber evaluation of the
children of call node to prepare arguments for helper call.
2. There was an issue with using above cleaner approach to prepare arguments.
GC thinks that argument register contains live object which is a problem
as these are volatile register and mostly will be altered with call-out.
To fix this we need to use precise register map for GC which only contains
the preserved registers.
As all non-preserved register are either spilled on stack or stored in preserved
registers before call, we are sure that there is no live object in non-preserved
registers and GC does not need to look into these registers for live object.
3. For helper calls within ICF previously …

Modify J9S390CHelperLinkage

---

runtime/jcl/cl_se9/module.xml
runtime/jcl/common/vm_scar.c

Skip dbgwrapper load on windows for openj9 builds

---

buildenv/jenkins/copyrightCheck
buildenv/jenkins/lineEndingsCheck

- If FILES is empty, skip checking files
- Copyright check and line endings check
[skip ci]
Fixes Issue #323

Do not check PRs with only file deletes

---

buildspecs/j9.build-info
buildspecs/osx_x86-64.spec

This contributes to accomplishing #36 Supporting OSX builds

 Add buildspec for OSX

---

sourcetools/com.ibm.uma/com/ibm/j9/uma/configuration/ConfigurationImpl.java
sourcetools/com.ibm.uma/com/ibm/j9/uma/platform/PlatformOSX.java

This contributes to accomplishing #36 Supporting OSX builds

Add OSX platform support to uma

---

buildspecs/osx_x86-64.spec

Disable osx autobuild flag

---

buildspecs/osx_x86-64.spec

Remove product flag on osx spec

---

test/TestConfig/scripts/build_test.xml
test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl
test/cmdLineTests/URLClassLoaderTests/exclude.xml
test/cmdLineTests/build.xml
test/cmdLineTests/cmdLineTest_J9tests/j9tests_Java8.xml
test/cmdLineTests/cmdLineTest_J9tests/j9tests_Java9.xml
test/cmdLineTests/gcRegressionTests/gcRegressionTests.xml
test/cmdLineTests/gcRegressionTests/gcRegressionTests_excludes.xml
test/cmdLineTests/gcRegressionTests/playlist.xml
test/cmdLineTests/gcsuballoctests/gcsuballoctests.xml
test/cmdLineTests/gptest/cmdlineopttest_exclude.xml
test/cmdLineTests/ignoreUnrecognizedVMOptions/ignoreunrecognizedvmoptions.xml
test/cmdLineTests/jvmtitests/jvmtitests_excludesSE90.xml
test/cmdLineTests/libpathTest/src/org/openj9/test/libpath/Rtf.java
test/cmdLineTests/shareClassTests/ListAllCachesTests/expireAndListAllCachesTests.xml
test/cmdLineTests/shareClassTests/ListAllCachesTests/listAllCachesTests.xml
test/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-1.xml
test/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml
test/cmdLineTests/shareClassTests/SCCommandLineOptionTests/exclude.xml
test/cmdLineTests/shareClassTests/SCCommandLineOptionTests/playlist.xml
test/cmdLineTests/softmxCmdOptTest/softmx.xml
test/cmdLineTests/xxargtest/XXArgumentTesting.xml
test/cmdline_options_testresources/build.xml

* enable cmdLine tests on Openj9
* excluded some failed test and open issue for them
Fixes:#305

enable cmdLine tests on OpenJ9

---

buildspecs/osx_x86-64.spec
runtime/gc_glue_java/configure_includes/configure_osx.mk
runtime/jilgen/jilconsts.c
runtime/jilgen/module.xml
runtime/makelib/targets.mk.ftl
runtime/makelib/targets.mk.osx.inc.ftl
runtime/port/module.xml
runtime/thread/threadshared.mk.ftl

* add OSX specific uma artifacts
* update uma artifacts with osx requirements
This contributes to accomplishing #36 Supporting OSX builds

Fixes for errors encountered compiling for OSX

---

runtime/codert_vm/jswalk.c
runtime/util/fltconv.c
runtime/util/hshelp.c
runtime/util/srphashtable.c
runtime/util/vmargs.c

Fixes for compile issues seen on OSX due to the newer compiler levels being used.
We should be able to merge this independently of the greater support OSX effort.
Issue: #36

Minor OSX compile fixes

---

runtime/tr.source/trj9/z/codegen/J9TreeEvaluator.cpp

inlineCurrentTimeMaxPrecision uses a signed subtract which may raise a
hardware trap if the fixed-point overflow exception flag is set in the
PSW. The result of STCKF is however a true 64-bit unsigned value and as
such we should be using logical subtracts.

Avoid fixed-point overflow in inlineCurrentTimeMaxPrecision

---

test/cmdLineTests/shareClassTests/SCCommandLineOptionTests/exclude.xml

Enable tests nameOption2 and nameOption4

---

runtime/vm/createramclass.cpp

Do not create exceptions while holding classTableMutex - instead, pass
the data out to be used after the appropriate locks have been released.

Fix exception creation during vTable init

---

jcl/.classpath

The comment must appear after the `<?xml?>` line.

Move copyright notice in .classpath so it is valid xml

---

test/Jsr292/src/com/ibm/j9/jsr292/api/MethodHandleAPI_dropArgumentsToMatch.java

Fixed byte testcase dependency on ASCII charset

---

jcl/src/java.base/share/classes/java/lang/Class.java

The current implementation of the various annoation APIs in
java/lang/Class are based on the AnnotationCache data structure which
has two fields of type Map - an interface type. The maps are either set
to and instance of the EmptyMap type or an instance of LinkedHashMap.
This change switches EmptyMap cases to be null. This in turn allows the
fields to be declared to be of the concrete LinkedHashMap type which
boosts performance and simplifies handling of empty maps. This also
makes the call profiling from the IProfiler much less confusing for the
JIT leading to throughput boost of around 30% in microbenchmarks of the
getAnnotation API.

Improve perf of j/l/Class annotation APIs

---

test/TestConfig/scripts/build_test.xml
test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl

Compilation issue from enabling tests in OpenJ9.

Disable Jsr292 tests

---

runtime/tr.source/trj9/control/CompilationThread.cpp
runtime/tr.source/trj9/env/J9SegmentCache.cpp
runtime/tr.source/trj9/env/J9SegmentCache.hpp
runtime/tr.source/trj9/env/J9SegmentProvider.hpp

Partially addresses https://github.com/eclipse/openj9/issues/434 .

Check preferred size on J9::SystemSegmentProvider init

---

test/NativeTest/jniargtests/JniArgTests.java
test/NativeTest/jniargtests/build.xml
test/NativeTest/playlist.xml

Build jniargtests.jar in test component
[skip ci]

Build jniargtests.jar in test component

---

test/TestConfig/makefile

- add result summary into target prepended with underscore
- make test group target print out java version by default

Add result Summary into individual test target

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ExtendedMethodFlagInfoCommand.java

Fix DDR break

---

runtime/gc_glue_java/configure_includes/configure_osx.mk
runtime/oti/j9protos.h
runtime/port/module.xml

OSX specific configuration changes

---

test/cmdLineTests/xcheckjni/playlist.xml

export LIBPATH for checkJNI tests

---

test/TestConfig/extraSettings

Update JAVA_SHARED_LIBRARIES_DIR setting

---

test/Java8andUp/src/org/openj9/test/support/Support_Exec.java

Signed-off-by: Andrew Leonard <andrew_m_leonard@uk.ibm.com>

Update test Support_Exec to match OpenJ9 java.vendor string

---

test/cmdLineTests/URLClassLoaderTests/exclude.xml
test/cmdLineTests/URLClassLoaderTests/playlist.xml

Re-enable sub-tests in SCURLClassLoaderTests

---

runtime/j9vm/jvm.c

The following three functions have been updated:
1) JVM_FindSignal
2) JVM_RaiseSignal
3) JVM_RegisterSignal

Update JVM_*Signal Functions

---

runtime/rasdump/dmpagent.c

Closes: #520
Signed-off-by: Srividya S <sshamaia@in.ibm.com>

Fix incorrect -Xdump:dump:defaults output

---

runtime/gc_glue_java/MarkingDelegate.cpp

In case of an aborted Concurrent Scavenge, in follow-up Percolate Global
GC, when doing final clearing pass, if encountering a referent slot
(within any of soft/weak/phantom refs), that already points to a
copy&forwarded object, fixup up the referent slot to point to the
forwarded version of the object. Then liveness of the referent would be
verified on the forwarded version.
We used to do it only for phantom reference, which would lead to
incorrectly clearing weak/soft reference (since liveness would be
checked on the  original version of the referent which would not be
marked, even though forwarded version would).

Fixup forwarded referent slot

---

runtime/tr.source/trj9/z/codegen/J9S390PrivateLinkage.cpp

ALS is currently set to z9 so z990 related code can be deprecated.

Remove z990 case in J9S390PrivateLinkage

---

runtime/j9vm/j9vm_internal.h
runtime/j9vm/jvm.c

Add defines for OSX platform support

---

runtime/j9vm/jvm.c

Fix preprocessor condition for ZTPF

---

test/TestConfig/scripts/tools/getDependencies.pl

* file will be generated if download is unsuccessful.
* delete the fake generated file

Delete fake file which was unsuccessfully downloaded

---

runtime/j9vm/jvm.c

Rework 'if defined' line for clarity

---

test/cmdLineTests/shareClassTests/DataHelperTests/exclude.xml

Re-enable all excluded tests in DataHelperTests

---

sourcetools/j9constantpool/com/ibm/oti/VMCPTool/CmakeFlagInfo.java
sourcetools/j9constantpool/com/ibm/oti/VMCPTool/IFlagInfo.java
sourcetools/j9constantpool/com/ibm/oti/VMCPTool/Main.java
sourcetools/j9constantpool/com/ibm/oti/VMCPTool/UmaFlagInfo.java
sourcetools/j9constantpool/com/ibm/oti/VMCPTool/Util.java

- Allow user to specify the directory where generated files are output
- Add ability to read config flag states from a CMake cache file
See individual commit messages for details

VMCPTool Updates for CMake

---

sourcetools/j9nls/com/ibm/oti/NLSTool/J9NLS.java

Add a new -source argument to point to the source tree.
If not given, falls back to default behaviour

Modify j9nls tool to support out of tree builds

---

runtime/tr.source/trj9/optimizer/J9Optimizer.cpp

Enable IdiomRecognition for warm methods

---

runtime/tr.source/trj9/optimizer/DataAccessAccelerator.cpp

BCDCHK nodes take the method symbol references of the call nodes they
replace. No need to create new method symbol references.

Reuse call node method symRef for DAA calls

---

test/README.md

Update README.md file with getdependency target information
Fixes: #196

Update README.md file with getdependency target information

---

runtime/compiler/trj9/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/trj9/env/VMJ9.cpp
runtime/compiler/trj9/env/j9method.cpp
runtime/compiler/trj9/optimizer/IdiomRecognition.cpp
runtime/compiler/trj9/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/trj9/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/trj9/z/codegen/J9TreeEvaluator.cpp

Add jit support for Reference.reachabilityFence

---

runtime/compiler/trj9/optimizer/SPMDParallelizer.cpp

The variable currentNode inside insertGPUTemporariesLivenessCode can
sometimes be used without being initialized. This can lead to problems such
as a segfault.
This change updates insertGPUTemporariesLivenessCode to ensure that
currentNode is initialized to a useable value before being used. It also
cleans up the code in the function to remove unused variables and to make
the code logic easier to follow.
Issue: #557

Fix segfault in insertGPUTemporariesLivenessCode

---

jcl/src/java.base/share/classes/java/lang/String.java

Use null test for compressionFlag as a check to see if string is compressed, 
for public APIs length, getBytes, hashCode, regionMatches.

Use null test for compressionFlag as a check to see if string is compressed for length, getBytes, hashCode, regionMatches

---

buildenv/jenkins/copyrightCheck
buildenv/jenkins/lineEndingsCheck

Update diff to detect file copies and renames

---

test/cmdLineTests/shareClassTests/SCCommandLineOptionTests/exclude.xml

Exclude nameOption14 to 19 for windows compressed refs spec

---

test/cmdLineTests/libpathTest/exclude.xml
test/cmdLineTests/libpathTest/exclude_rtfchild.xml
test/cmdLineTests/libpathTest/playlist.xml

Exclude libpathTest for windows compressed refs spec

---

test/cmdLineTests/cmdlinetestertests/exclude.xml

Exclude CmdLineTester Test 12 for windows compressed refs spec

---

test/TestConfig/makefile
test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl

* add jck test target into testKitGen
* correct typos about runtest and perf targets

add jck test target into testKitGen

---

jcl/src/java.base/share/classes/java/lang/String.java

Implemented compressionFlag null test for remaining String operations

Use compressionFlag null test as a check to see if string is compressed

---

runtime/compiler/trj9/optimizer/J9SimplifierHandlers.cpp

Remove the replaceSetSignUnderBinaryWithAbs() handler for the following
two reasons:
1. This handler handles obsolete pd2iu and pd2lu opcodes. The Java DAA API
will never generate these unsigned nodes.
2. This handler can also introduce labs (long absolute value) nodes above
pd2l nodes. This is problematic in two ways: first, this handler only
replaces the pd2l with labs on the first appearance of the pd2l. Subsequent
references to that pd2l are not fixed up. If a pd2l is replaced by labs,
the current pd2l and all future references to it must all be replaced.
Second, the BCDCHK evaluator, by design, is not able
to recognize nor handle none PD related nodes. As a result of this, having
labs nodes under BCDCHK nodes can cause runtime crashes.

Remove a pd2l simplification handler in J9

---

runtime/jcl/common/jclcinit.c

Changed strcat to defines wrapped in preprocessor flags,
Use compiler string literal concatenation to build format string
Fixes #272 

Replaced strcat with sprintf in jclcinit.c

---

runtime/libffi/module.xml
runtime/port/module.xml
runtime/vm/module.xml

OSX compilation fixes

---

jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/plugins/impl/PluginManagerImpl.java

Also use the Java preprocessor to include code specific to Java 9.

Update com.ibm.dtfjview module name to openj9.dtfjview

---

test/Java8andUp/src/org/openj9/test/vmcheck/TestLoadingClassesFromJarfile.java

* exclude modules from test that only compile stubs
* improve command line printing readability
Fixes: #732

Fix Java8 extended failure testvmcheck

---

test/TestConfig/scripts/build_test.xml
test/TestConfig/scripts/testKitGen/testKitGen.pl

- add a else case in build.xml for future release (i.e., SE100)
- remove exclude for Panama and Valhalla as we have check in lower level
build.xml
- Set special JAVAC for SE80

Add subset SE100 in testKitGen

---

jcl/src/java.base/share/classes/com/ibm/tools/attach/target/Attachment.java

The Agent classes in OpenJ9 Java 8 are different from IBM Java 8.  They are
(modulo package names) the same as Java 9.
Fixes: https://github.com/eclipse/openj9/issues/730

Update the API used by StartAgent() and StartLocalAgent()

---

jcl/jpp_configuration.xml

Create source for DTFJ, DTFJVIEW, and TRACEFORMAT for tools.jar

Create SIDECAR18-TOOLS-OPENJ9 Java preprocessor config

---

test/Java10andUp/.classpath
test/Java10andUp/.project
test/Java10andUp/.settings/org.eclipse.jdt.core.prefs
test/Java10andUp/build.xml
test/Java10andUp/playlist.xml
test/Java10andUp/src/org/openj9/test/stackWalker/StackWalkerTestJava10.java
test/Java10andUp/testng.xml

Checking in the rough version of the files.  It's not fully tested because we don't have a stable Java 10 yet.
@llxia would you kindly take a look?  @smlambert FYI.

WIP: Initial checkin of Java10andUp project

---

test/TestConfig/makefile
test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl
test/TestConfig/scripts/testKitGen/resultsSummary/resultsSum.pl

- Display skipped tests due to capabilities in SKIPPED
- Display capabilities, jvm options and machine requirements if
available

Display skipped tests due to capabilities

---

runtime/bcverify/staticverify.c
runtime/bcverify/vrfyhelp.c
runtime/oti/portsock.h
runtime/port/common/j9sysinfo_helpers.c
runtime/port/unix/j9sock.c
runtime/port/unix/j9sysinfo.c
runtime/vm/jvminit.c
runtime/vm/vmthread.c

Add defines for OSX; restructuring for compilation on OSX

---

debugtools/DDR_Autoblob/src/com/ibm/j9ddr/autoblob/GetNativeDirectory.java
debugtools/DDR_Autoblob/src/com/ibm/j9ddr/autoblob/xmlparser/J9FlagsXMLParser.java
jcl/src/openj9.traceformat/share/classes/com/ibm/jvm/trace/format/api/TraceRecord.java
runtime/compiler/trj9/runtime/Trampoline.cpp
runtime/gc_base/GenerationalAccessBarrierComponent.cpp
runtime/gc_modron_standard/StandardAccessBarrier.cpp
runtime/gc_vlhgc/VLHGCAccessBarrier.cpp
runtime/oti/j9.h
runtime/oti/jitprotos.h
runtime/rasdump/heapdump.cpp
runtime/simplepool/simplepool.c
runtime/tests/algorithm/srphashtabletest.c
runtime/util/srphashtable.c
runtime/vm/jvminit.c
sourcetools/com.ibm.jpp.preprocessor/com/ibm/jpp/om/ExternalMessagesExtension.java
test/cmdLineTests/shareClassTests/DataHelperTests/src/apitesting/Testbase.java

Remove obsolete comments

---

runtime/j9vm/jvm.c

Added EINTR handling for the following methods:
* JVM_Accept
* JVM_Recv
* JVM_RecvFrom
* JVM_Send
* JVM_SendTo
* JVM_SocketAvailable
* JVM_Connect
* JVM_SocketClose
Fixes: #705
Peer review: @babsingh

EINTR handling for JVM_ socket methods

---

runtime/include/vendor_version.h

Added documentation on setting vendor information

---

jcl/src/java.base/share/classes/java/lang/StringBuffer.java
jcl/src/java.base/share/classes/java/lang/StringBuilder.java

NegativeArraySizeException is not thrown from the StringBuffer
constructor that takes capacity as an argument. In the constructor, the
capacity argument is modified before the byte/char array is created. If
the capacity argument is Integer.MIN_VALUE (-2147483648), then capacity
*= 2 will yield a non-negative number due to overflow. Thus, we will
fail to throw NegativeArraySizeException. A new check has been added to
assure that NegativeArraySizeException is thrown if capacity argument is
less than 0.
The implementation of similar constructor in StringBuilder has been
updated to maintain consistency between StringBuffer and StringBuilder.

NegativeArraySizeException not thrown from StringBuffer constructor

---

jcl/src/java.base/share/classes/java/lang/invoke/MethodHandle.java

This commit contains the following change:
1) Add an early return in MethodHandle.asType so that type information
can be propagated without inlining the real implementation which
contains much more complicated java code.
2) Touch thunks.invokeExactThunk in MethodHandle's constructor so that
it is resolved in the JIT compilation, preventing the block from
being marked as cold.

Changes in MethodHandle for VarHandle performance

---

buildenv/Build_Instructions_V8.md
buildenv/Build_Instructions_V9.md
test/Java9andUp/src/org/openj9/test/constantPoolTags/ConstantPoolTagTests.java
test/Java9andUp/src/org/openj9/test/defineModuleAsClass/DefineModuleAsClassTest.java

Update to proper license information

---

jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/corereaders/NewWinDump.java

Remove comments containing Windows native structure definitions

---

runtime/compiler/trj9/z/env/J9CPU.cpp

Update existing z/TPF logic to determine Machine Type
Information to use the standard uname function 
instead of OS specific memory access.
Signed-off-by: jjohnst-us <jjohnst@us.ibm.com>

Change z/TPF Machine Type Determination Logic

---

doc/compiler/JProfiling.md

This adds some documentation describing the JProfiling
implementation and behaviour.

Add JProfiling Documentation

---

runtime/compiler/trj9/z/runtime/Math.m4
runtime/compiler/trj9/z/runtime/PicBuilder.m4
runtime/compiler/trj9/z/runtime/Recompilation.m4
runtime/compiler/trj9/z/runtime/ValueProf.m4
runtime/compiler/trj9/z/runtime/s390_asdef.inc
runtime/compiler/trj9/z/runtime/s390_macros.inc
runtime/compiler/trj9/z/runtime/zLinux_macros.inc
runtime/compiler/trj9/z/runtime/zOS_macros.inc
runtime/port/zos390/j9csrsi_wrp.s
runtime/port/zos390/j9gs_get_supported.s
runtime/port/zos390/j9gs_load_gscb.s
runtime/port/zos390/j9gs_store_gscb.s
runtime/port/zos390/j9mprotect.s
runtime/port/zos390/j9munprotect.s
runtime/vm/mz31/unsafeHelper.s
runtime/vm/mz64/unsafeHelper.s
runtime/vm/xz31/unsafeHelper.s
runtime/vm/xz64/unsafeHelper.s

Fix SPDX in all z assembler so its not longer than 71 characters

---

runtime/port/unix/j9sysinfo.c

Remove mention of libauxv as OpenJ9 does not use this open source

---

runtime/compiler/trj9/runtime/J9ValueProfiler.hpp

When rearranging values in a JProfiling hash table,
default matches with the first entry in the table
where possible at any point. This could result
in the table exceeding its capacity in the middle
of rearrangement. By ensuring the first slot in
the table holds -1 when not filled, a default match
is not possible.
This also introduces a shortcut in the hash calculation
and rearrangement, along with improving the tracing.

Fix race in JProfiling addKey

---

runtime/jcl/common/jclcinit.c

Removed extra space in Java fullversion string

---

doc/diagnostics/VMState.md

Document the diagnostic purpose and decoding of the VM state

---

runtime/vm/visible.c

Only use J9Class and J9Module for visibility checks
Remove the need to fetch objects when doing visibility checks. This will
make it easier to use this code to do visibility checks during
classloading (ie. check that class has access to superClass) or other
places where the class is partially created.

Only use J9Class and J9Module for visibility checks

---

jcl/src/java.base/share/classes/java/lang/String.java
jcl/src/java.base/share/classes/java/lang/StringBuffer.java
jcl/src/java.base/share/classes/java/lang/StringBuilder.java

- Fix an off by one bug in offsetByCodePoints
- Update the buffer length before calling decompress
- Pass the string array to getByteFromArrayByIndex

Fix functional bugs in string compression code

---

runtime/compiler/trj9/env/VMJ9.cpp

Added check for s390 platform for changes in eclipse/openj9#759

Fix compilation issues on x86 Concurrent Scavenger build.

---

jcl/jpp_configuration.xml
jcl/src/java.base/share/classes/java/lang/Access.java

Implement `Java 10 j.l.Access.newStringUTF8NoRepl/getBytesUTF8NoRepl`.
Also updated `Java 10` pConfig to refer `rt-compressed.sunJava10.jar`.
closes: #904 
Reviewer @pshipton 
FYI: @DanHeidinga 

Implement Java 10 j.l.Access.newStringUTF8NoRepl/getBytesUTF8NoRepl

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ITableSizeCommand.java

Enhance !itablesize to compute the space required if iTables also
describe all methods inherited from superinterfaces.

Add another iTable size computation

---

buildspecs/win_x86-64_cmprssptrs.spec

Enable OpenJ9 OpenJDK8 build flag

---

runtime/compiler/trj9/z/codegen/J9TreeEvaluator.cpp
runtime/compiler/trj9/z/codegen/ReduceSynchronizedFieldLoad.cpp

Load Extensions has been refactored and rewritten in OMR. Update the
references to deprecated APIs.

Update Load Extensions deprecated APIs

---

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
test/Jsr292/src/com/ibm/j9/jsr292/api/MethodHandleAPI_iteratedLoop.java

Fix MethodHandles loop methods

---

runtime/gc_modron_startup/mminit.cpp

The check for GC policy is missed. GC structures might be initialized
inconsistently if any other then Gencon GC policy is requested with
-Xgc:concurrentScavenge option. Silently ignore Concurrent Scavenger
request if it is not applicable to GC policy (pattern we using for
similar -Xgc options like -Xgc:concurrentMark)
Signed-off-by: dmitripivkine <Dmitri_Pivkine@ca.ibm.com>

Allow -Xgc:concurrentScavenge for Gencon GC policy only

---

test/Java8andUp/src_80/org/openj9/test/java/lang/Test_System.java
test/Java8andUp/src_90/org/openj9/test/java/lang/Test_System.java

Remove bogus comment, re-enable test_setSecurityManager2()

---

runtime/gc_glue_java/ObjectModel.hpp
runtime/gc_modron_standard/StandardAccessBarrier.cpp

Revert Co-operative copy of long object

---

runtime/jcl/common/vm_scar.c

Remove unused define for JAVA_ASSISTIVE_STR

---

runtime/gc_modron_startup/mminit.cpp

This problem was exposed by Concurrent Scavenger. There is a case where
region size can be set larger then default. The Initial Memory size for
non-flat configuration can not be smaller then three regions (one for
Tenure and one for each half of Nursery). If -Xms value is smaller then
minimum it is silently corrected.
Also if Initial Memory size is smaller then eight regions the default
split 75% for Tenure / 25% for Nursery can not be established
(considering minimum two regions for Nursery is 25%). So Nursery size
has to be set to two regions and reminder goes to Tenure. 
Signed-off-by: dmitripivkine <Dmitri_Pivkine@ca.ibm.com>

Fix Initial Memory minimum size for non-flat configuration

---

test/cmdLineTests/javaAssertions/build.xml
test/cmdLineTests/javaAssertions/javaAssertions.xml
test/cmdLineTests/javaAssertions/playlist.xml
test/cmdLineTests/javaAssertions/src/StringAssertionStatus.java

Porting test cmdLineTester_javaAssertions to Openj9 repo

---

test/Jsr335/playlist.xml

Fix jsr335 unexpected behavior

---

test/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-1.xml
test/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-2.xml
test/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-4.xml
test/cmdLineTests/shareClassTests/SCCMLTests/exclude.xml
test/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml

Migrate testSCCMLTests4

---

runtime/gc_glue_java/ObjectModel.hpp
runtime/gc_modron_standard/StandardAccessBarrier.cpp

For Concurrent Scavenger, use copyOrWait() API to ensure that object is
fully copied before exposing the new verison of the object. The API is
no-op in Standard Scavenger.
Introduce a varion of getArrayLayout() that will return layout info
based on preserved info in ForwardedHeader, instead of looking into the
(destination) object header itself, which is not available with
co-operative copying, since the destination object header contains copy
progress info, while copy is still in progress.

Co-operative copy of large objects in CS

---

test/TestConfig/resources/excludes/latest_exclude_SE80.txt

Add known issue to SE80 exclude file

---

test/TestConfig/resources/excludes/latest_exclude_SE80.txt

Update latest_exclude_SE80.txt with OpenJ9 Issue numbers

---

test/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-1.xml
test/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-2.xml
test/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-3.xml
test/cmdLineTests/shareClassTests/SCCMLTests/exclude.xml
test/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml
test/cmdLineTests/shareClassTests/TokenHelperTests/APITests/TokenGetDifferentHelperTest.java
test/cmdLineTests/shareClassTests/TokenHelperTests/APITests/TokenMultipleGetHelperCallTest.java
test/cmdLineTests/shareClassTests/TokenHelperTests/APITests/TokenStoreFindTest.java
test/cmdLineTests/shareClassTests/TokenHelperTests/StaleMarkingTests/StaleMarkingTest.java
test/cmdLineTests/shareClassTests/TokenHelperTests/StaleMarkingTests/Test1.props
test/cmdLineTests/shareClassTests/TokenHelperTests/TimeStampingTests/TimeStampingTest.java
test/cmdLineTests/shareClassTests/TokenHelperTests/TimeStampingTests/props_unix/Test1.props
test/cmdLineTests/shareClassTests/TokenHelperTests/TimeStampingTests/props_unix/Test2.props
test/cmdLineTests/shareClassTests/TokenHelperTests/TimeStampingTests/props_unix/Test3.props
test/cmdLineTests/shareClassTests/TokenHelperTests/TimeStampingTests/props_unix/Test4.props
test/cmdLineTests/shareClassTests/TokenHelperTests/TimeStampingTests/props_win/Test1.props
test/cmdLineTests/shareClassTests/TokenHelperTests/TimeStampingTests/props_win/Test2.props
test/cmdLineTests/shareClassTests/TokenHelperTests/TimeStampingTests/props_win/Test3.props
test/cmdLineTests/shareClassTests/TokenHelperTests/TimeStampingTests/props_win/Test4.props
test/cmdLineTests/shareClassTests/TokenHelperTests/build.xml

Migrate testSCCMLTests3 to openj9/test

---

buildenv/jenkins/copyrightCheck
buildenv/jenkins/lineEndingsCheck

- ghprbGhRepository is set by the GH PR Builder plugin
- `<namespace>/<repo>`
- Allows the script to be used by other repos

Determine SRC_REPO from Jenkins variable

---

buildenv/jenkins/copyrightCheck

- Determine if PR is from Eclipse or IBM Runtimes
- Set REGEX for grep depending on namespace
[skip ci]

Add second copyright regex for ext repos

---

runtime/vm/createramclass.cpp

Coalesce module lookups in createRamClass
Combine module lookups in createRamClass.c. Move up the lookup for
module with findModuleForPackage() earlier in the code so that the
module info can be used to do access checking for superclasses and
interfaces (this will come in another PR).
Reviewer: @pshipton

Coalesce module lookups in createRamClass

---

jcl/src/java.base/share/classes/java/lang/String.java

- Compare the last character first as a shortcut to tell two Strings are not equal.
- When string compression is active, only need to convert both chars to
uppercase and compare once, as all characters are within the ASCII char set.
- When string compression is not active, if either character is not in ASCII
char set, we have to convert to upper and lower case and compare twice.

Improve path length for String equalsIgnoreCase

---

jcl/src/java.base/share/classes/java/lang/Class.java
jcl/src/java.base/share/classes/java/lang/StackWalker.java
runtime/jcl/common/java_lang_StackWalker.cpp
runtime/oti/vmconstantpool.xml
test/Java10andUp/src/org/openj9/test/stackWalker/StackWalkerTestJava10.java

Grab the signature from the ROM method and put it in the Frame object.
Use the signature to generate descriptor and MethodType.
closes #522

Implement StackFrame.getDescriptor(), getMethodType()

---

test/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-5.xml
test/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-6.xml
test/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml
test/cmdLineTests/utils/build.xml

Migrate testSCCMLTests5,6 to openj9

---

runtime/vm/createramclass.cpp

Fix compile failures on windows

Fix compile failures on windows

---

test/Java8andUp/playlist.xml

Run memoryCategories in REPORTDIR

---

test/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml
test/cmdLineTests/shareClassTests/SCCMLTests/testSCCMLSnapshot.xml

Migrate testSCCMLSnapshot to openj9

---

test/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-5.xml
test/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml

Fix sccm tests failure on wins

---

runtime/gc_modron_standard/StandardAccessBarrier.cpp

Enusure that snapshot is really taken of the object slot, which is
generally volatile (can be mutated by another thread), since an
aggressive compiler can decide to re-read the slot instead of using the
snapshot variable.

Ensure slot snapshot in Read Barrier

---

test/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-6.xml
test/cmdLineTests/utils/build.xml

[ci skip]
Remove jar the duplicate utilsBk.jar in the build.xml

Copy jar inside the test

---

test/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml
test/cmdLineTests/shareClassTests/SCCMLTests/testSCCMLSoftmx.xml

Migrate testSCCMLSoftmx to openj9

---

runtime/compiler/trj9/control/rossa.cpp

z/TPF already had code to allocate 5% of MAXXMES for use
by the code cache.  This Pull Request increases this percentage
to 20% and explicitly sets other code and data cache limits for 
readability.
Signed-off-by: jjohnst-us <jjohnst@us.ibm.com>

Change z/TPF Code Cache default allocation from 5% to 20%

---

test/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml
test/cmdLineTests/shareClassTests/SCCMLTests/testSCCMLAotMethodOperation.xml

Migrate testSCCMLAotMethodOperation to openj9

---

doc/README.md
doc/processes/release_process.md

Initial draft of release process for OpenJ9

---

jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Dump.java

Signed-off-by: Chandrakala <chandra-ms@in.ibm.com>

Removed references to IBM and changed the wordings in the desscription

---

runtime/compiler/trj9/build/files/common.mk
runtime/compiler/trj9/build/files/host/arm.mk
runtime/compiler/trj9/build/files/host/i386.mk
runtime/compiler/trj9/build/files/host/p.mk
runtime/compiler/trj9/build/files/host/x.mk
runtime/compiler/trj9/build/files/host/z.mk
runtime/compiler/trj9/build/files/target/amd64.mk
runtime/compiler/trj9/build/files/target/arm.mk
runtime/compiler/trj9/build/files/target/i386.mk
runtime/compiler/trj9/build/files/target/p.mk
runtime/compiler/trj9/build/files/target/x.mk
runtime/compiler/trj9/build/files/target/z.mk

Alphabetize sources in jit makefiles

---

runtime/compiler/trj9/compile/J9SymbolReferenceTable.cpp
runtime/compiler/trj9/compile/J9SymbolReferenceTable.hpp

Issue: eclipse/omr#2125
Signed-off-by: Shivam Mittal <shivammittal99@gmail.com>

Relocated currentThreadDebugEventData from OMR

---

doc/processes/release_process.md

Fix links in the release_process.md

---

test/cmdLineTests/gcRegressionTests/gcRegressionTests_excludes.xml

Enable excluded testcase in gcRegressionTests

---

test/README.md
test/TestConfig/playlist.xsd

- updated test tag part
- updated test target part

Update test README.md

---

test/Java8andUp/playlist.xml

Replace \<tags\>  with \<levels>\.
Test is currently running in the extended bucket due to changes in the test tools.
@smlambert @smlambert FYI.

Update playlist.xml to new format

---

runtime/gc_modron_startup/mminit.cpp

- Initial Nursery size -Xmns can not be smaller then two regions.
Adjust it silently if it is a case.
- Initial Tenure size -Xmos can not be smaller then one region.
Adjust it silently if it is a case.
- In case if Initial Tenure size is smaller then six regions default
split Tenure/Nursery 75%/25% can not be set. So set Initial Nursery size
to minimum two regions and assign reminder to Tenure.
- "-Xmn<value>" option is treated as "-Xmns<value> -Xmnx<value>". Modify
error message if it is too small to prevent "-Xmn too large for -Xmn"
message, replace it to " -Xmn too small, must be at least 1 Mbytes"
Signed-off-by: dmitripivkine <Dmitri_Pivkine@ca.ibm.com>

Silent correction for -Xmns and -Xmos is value is too small

---

test/cmdLineTests/classesdbgddrext/playlist.xml

- run test under $(REPORTDIR)
[ci skip]

fix cmdLineTester_classesdbgddrext test

---

runtime/compiler/trj9/runtime/IProfiler.cpp

- Correct the update and overflow check of `_residueWeight`
Fixes: #450

Fix incorrect handling of _residueWeight in IProfiler data structures

---

test/IllegalAccessError_for_protected_method/playlist.xml
test/JIT_Test/playlist.xml
test/JLM_Tests/playlist.xml
test/Java10andUp/playlist.xml
test/Java8andUp/playlist.xml
test/Java9andUp/playlist.xml
test/JavaAgentTest/playlist.xml
test/Jsr292/playlist.xml
test/Jsr335/playlist.xml
test/Jsr335_interfaceStaticMethod/playlist.xml
test/Panama/playlist.xml
test/SVT_LoadTest/exclude_playlist.xml
test/SVT_Modularity/exclude_playlist.xml
test/SharedCPEntryInvokerTests/playlist.xml
test/TestConfig/playlist.xsd
test/TestConfig/scripts/testKitGen/testKitGen.pl
test/TestExample/playlist.xml
test/UnsafeTest/playlist.xml
test/VM_Test/excluded_playlist.xml
test/VM_Test/playlist.xml
test/Valhalla/playlist.xml

- featureId is not useful in the open while we track our work
with PR
[skip ci]

Remove featureId from playlist.xml

---

test/JLM_Tests/playlist.xml

Disable testDefaultDisclaimMemory on zlinux31

---

test/Java9andUp/playlist.xml

Exclude failing DenyAccess while fix is pending
Related to #1086 

Exclude failing DenyAccess while fix is pending

---

runtime/compiler/trj9/control/CompilationThread.cpp

Signed-off-by: Irwin D'Souza <dsouzai@ca.ibm.com>

Check verbose option before printing to log

---

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/elf/Address32.java
debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/elf/Address64.java

(following advice of the Java compiler)

Move auxiliary classes to separate source files

---

runtime/compiler/trj9/env/VMJ9.cpp

Read barrier is needed before dereferencing an object at compile time
when in concurrentScavenge, this is because object can be moved in
parallel with java and JIT compilation threads.

Emit read barrier before dereference

---

runtime/vm/VMAccess.cpp

A deadlock could be caused if thread holding JNI Critical access is
halted during acquireVMAccess by HALTED_AT_SafePoint without
releasing JNI access and then blocked by exclusiveVMAccess_HALT
which has higher priority. In this case, the thread requesting exclusive
access will be locked waiting for JNI Critical access to be released

Update acquireVMAccess to release JNI Access before halt check

---

runtime/util/openj9_version.c

Add Extensions for OpenJDK version to java -Xinternalversion

---

runtime/oti/jvminit.h
runtime/vm/jvminit.c

Use the same option as OpenJDK for compatibility.
Closes: #948

Rename -XX:+StringCompression to -XX:+CompactStrings

---

test/Java8andUp/testng.xml

Changing attribute parallel setting "none" instead of "false"

Update parallel setting none value

---

runtime/bcutil/ClassFileOracle.cpp

Signed-off-by: Eric Zhang <eric99.zhang@gmail.com>

Fix Valhalla value types opcode remap typos in ClassFileOracle.cpp

---

sourcetools/com.ibm.uma/com/ibm/j9/uma/configuration/ConfigurationImpl.java

* the method checks cCopyrightNotice instead of rawCopyrightNotice
* reformatted

Fix lazy computation of rawCopyrightNotice

---

jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/plugins/Container.java
jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/plugins/Entry.java
jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/plugins/impl/PluginManagerImpl.java

Not all Entry objects have an associated File and so, can't all contribute to the classpath.
Issue: #378

Fix ddr plugin manager

---

jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/image/j9/ImageFactory.java

The existing code which reflectively exports access to DDR was
written prior to the refactoring which moved java.lang.reflect.Module
to java.lang.Module.
This code doesn't have the advantage of being preprocessed and so
can't make distinctions at that time. Instead, this version attempts
to locate Module in the new package first and then falls back to
looking in the old package.
Issue: #378

Export access to DDR for b165+

---

jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/image/ImageFactory.java

As suggested in the review of #1223.
[ci skip] documentation-only change

Improve javadoc for ImageFactory

---

jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java

Add new objectFieldOffset for Java 10 and up

---

runtime/codert_vm/armnathelp.m4
runtime/codert_vm/cnathelp.cpp
runtime/codert_vm/pnathelp.m4
runtime/codert_vm/xnathelp.m4
runtime/codert_vm/znathelp.m4
runtime/compiler/trj9/control/rossa.cpp
runtime/oti/VMHelpers.hpp
runtime/oti/j9nonbuilder.h

- Implemented JIT runtime helper for final field notification
- Added placeholder function of JIT final field callback
- Removed null check for jitConfig function pointer

JIT runtime helper for final field notification

---

jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java
runtime/jcl/common/sun_misc_Unsafe.cpp

Identify unsafe stubs in javadocs

---

buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK8-linux_ppc-64_cmprssptrs_le

Jenkins PR fix missing single quote

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All

Fix OpenJDK repository URL in the Build-Test-All pipeline

---

buildenv/jenkins/jobs/builds/Build-JDK8-linux_390-64_cmprssptrs
buildenv/jenkins/jobs/builds/Build-JDK9-linux_ppc-64_cmprssptrs_le

Fix typo and clean up in Build-JDK pipelines

---

runtime/j9vm/jvm.c

g_sigaction is not used. Reformat code.

Remove dead code in jvm.c

---

runtime/j9vm/generated.h.m4

Update comments to reflect use of m4

---

buildenv/jenkins/common/pipeline-functions

fix undefined variable name BUILD_JOB

---

runtime/jvmti/jvmtiStartup.c

Fix `Windows` platform compilation failures
Reviewer @pshipton
FYI: @danheidinga

Fix Windows platform compilation failures

---

runtime/hyvm/module.xml

Caused by #1009. Other dependencies fixed by #1335

Fix another dependency on generated.h

---

buildenv/jenkins/common/build
buildenv/jenkins/common/variables-functions
buildenv/jenkins/jobs/builds/Build-JDK8-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/builds/Build-JDK9-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-JDK8-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-JDK9-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK8-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK9-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK8-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK9-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK8-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK9-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/tests/Test-Extended-JDK8-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/tests/Test-Extended-JDK9-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/tests/Test-Sanity-JDK8-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/tests/Test-Sanity-JDK9-aix_ppc-64_cmprssptrs
buildenv/jenkins/variables/defaults.yml

Compile pipeline
https://ci.eclipse.org/openj9/view/Build/job/Build-JDK9-aix_ppc-64_cmprssptrs/3/console

Add build file and variables for AIX support

---

buildenv/jenkins/README.md
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All

Add AIX to daily builds and document pull request instructions for aix

---

buildenv/jenkins/common/pipeline-functions

Skip slack notification when slack_channel is not set

---

buildenv/jenkins/common/test
buildenv/jenkins/jobs/builds/Build-JDK8-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/builds/Build-JDK9-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-JDK8-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-JDK9-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/tests/Test-Extended-JDK8-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/tests/Test-Extended-JDK9-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/tests/Test-Sanity-JDK8-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/tests/Test-Sanity-JDK9-linux_x86-64_cmprssptrs

Add build and tests pipelines for JDK 8 and 9.
[ci skip]

Add Jenkins files for Linux x86 build and test pipelines

---

buildenv/jenkins/jobs/infrastructure/branchSplit

- Pipeline file to branch OpenJ9 and OpenJ9-OMR
- Fail if branch already exists
- Fail if split point does not exist
- Inputs: new branch name and SHAs for OpenJ9 and OMR
[skip ci]

Initial commit for Branch-Split job

---

test/README.md
test/docs/DependentLibs.md
test/docs/OpenJ9TestUserGuide.md
test/docs/Prerequisites.md

- create a quick start guide with common user cases
- separate original README into several files (DependentLibs.md,
OpenJ9TestUserGuide.md and Prerequisites.md)
[ci skip]

Update OpenJ9 test README

---

runtime/compiler/trj9/optimizer/JProfilingValue.cpp

Before lowering JProfling value calls, scan the trees around to make
sure it won't orphan a compressedrefs anchor node.

Fix trees around jProfiling value call trees

---

doc/processes/labels.md

Initial description of labels and their intended usage

---

buildenv/jenkins/variables/defaults.yml

Use full path to avoid variables expansion issues
[ci skip]

Remove use of environment variables from variables file

---

runtime/compiler/trj9/p/codegen/J9TreeEvaluator.cpp

When inlining array allocations, several checks are performed to make sure that
the allocation is valid and can be done inline. Some of the checks performed
try to determine if the size or number of elements of the array that is being
allocated fall under a max value. If they do not, the VM handles the allocation
out-of-line.
An issue with the aformentioned checks was that the size or number of elements,
were being stored in registers that could have most significant bits that were
contaminated by  prior instructions. Thus when the checks were performed,
although the size of the array or number of elements was within the range of an
inline array allocation, it would seem as if they were not and an out-of-line
allocation would occur, affecting the performance.
In order to fix this, the …

Fixed Inline Array Allocation

---

runtime/vm/resolvesupport.cpp

Final fields in java must be set by the class in which it is declared. Final instance variables must be set in every constructor of the class they are declared in (<init>) and final static variables by the static initializer of the class they are declared in (<clinit>).
Private fields/methods of a class can currently only be accessed by the class in which they are declared. Earlier access checks therefore assumed that checking if a field ref has private access to a final field was sufficient.
With the advent of nestmates (see JEP 181), private fields/methods of a class can be accessed by its fellow 'nest members' classes. The existing access check would therefore allow two classes within the same 'nest' to see eachothers' final fields within their own constructors.
This commit changes the …

Updates final field access check

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java

Avoid instantiating ClassLoader objects when throwing SecurityException
Removed flag `initDone` and related set & check code;
Added a static helper method `checkSecurityPermission` to check if callers have permission required;
Refactored `ClassLoader` constructors to invoke `checkSecurityPermission`.
closes: #1353
Reviewer @DanHeidinga 
FYI @paulcheeseman

Avoid instantiating ClassLoader objects when throwing SecurityException

---

runtime/port/unix/j9sysinfo.c

There's a crash on PPC due to assuming query_auxv never fails.
The return value needs to be checked for -1 or 0 before using it
to map to something.
fixes: #1476

Check return value from query_auxv before using it

---

runtime/jcl/common/system.c

Minor cleanup for the comment formatting

---

test/README.md
test/TestConfig/scripts/testKitGen/testKitGen.pl
test/TestConfig/settings.mk
test/docs/OpenJ9TestUserGuide.md

- Add SE110 into testKitGen.pl
- Update README.md
[ci skip]

Enable SE110 for testing

---

runtime/gc_structs/ClassIterator.cpp
runtime/gc_structs/ClassIterator.hpp
runtime/gc_vlhgc/CopyForwardScheme.cpp
runtime/gc_vlhgc/GlobalMarkCardScrubber.cpp
runtime/gc_vlhgc/GlobalMarkingScheme.cpp
runtime/gc_vlhgc/PartialMarkingScheme.cpp
runtime/gc_vlhgc/WriteOnceCompactor.cpp

Cleanup class scanning in Balanced GC (vlhgc) to use general
Class Slots Iterator that is available: GC_ClassIterator, instead of
several different iterators.
Closes: #1301

Cleanup class scanning in Balanced GC

---

runtime/compiler/trj9/arm/env/J9CPU.cpp
runtime/compiler/trj9/arm/env/J9CPU.hpp

Fix ARM compile error due to TR_ProcessorFeatureFlags error 

---

buildenv/jenkins/jobs/builds/Build-JDK10-linux_ppc-64_cmprssptrs_le
buildenv/jenkins/jobs/builds/Build-JDK8-linux_390-64_cmprssptrs
buildenv/jenkins/jobs/builds/Build-JDK9-linux_ppc-64_cmprssptrs_le

fix bad defined variable name for variableFile

---

runtime/bcutil/cfreader.c

Align OpenJ9 behaviour with reference implementation,
which checks the classfile version before other verification.
Fixes https://github.com/eclipse/openj9/issues/1282
Tested in openjdk-tests:
```
TEST: java/lang/System/Versions.java
build: 0.094 seconds
compile: 0.093 seconds
main: 0.075 seconds
TEST RESULT: Passed. Execution successful
```

Check classfile version as soon as possible

---

runtime/compiler/trj9/build/files/target/arm.mk

Fix ARM undefined symbol issue

---

test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl
test/TestConfig/scripts/testKitGen/resultsSummary/resultsSum.pl

- Change first letter to uppercase.
[ci skip]

Update the test time stamp message

---

runtime/compiler/trj9/z/codegen/J9TreeEvaluator.cpp

VSI instructions have 12-bit displacements and a base register. There is
not need for a separate LA/LAY instruction if a memory reference lacks
index register.
If the index register is absent, codegen should avoid evaluating address
nodes, and delay the index register/large displacement handling to the
generateVSIInstruction() API call, which will explicitly call
separateIndexRegister() API for such matter.

Avoid evaluation of VSI instruction memory references

---

buildenv/jenkins/common/build
buildenv/jenkins/common/test

- For any Compile or Test build
- Also includes PRs
[skip ci]

Add NODE_NAME to build description

---

test/Java10andUp/build.xml

- Add TestUtilites into build.xml
[ci skip]

Fix Java10andUp compilation

---

buildspecs/aix_ppc-64_cmprssptrs.spec

Enable OpenJ9 on AIX within the buildspecs

---

runtime/compiler/trj9/runtime/HookHelpers.cpp

When the metadata is reclaimed (due to a recompilation of a method), the
previous and next metadatas in the linked list are are updated in
updateExceptionTableLinkedList. However, there's a corner case that
wasn't handled. If the metadata being reclaimed is the first in the
list, then the pointer to it (either off the classloader or the class
(if anonymous)) was not updated to point to the new stub metadata. This
PR rectifies this.

Fix Metadata Reclamation Bug

---

runtime/compiler/trj9/optimizer/MonitorElimination.cpp

When replacing a monitor-enter with a transaction we did not check if
the monitor-enter is under a Null-Check (i.e. a synchronized block) and
therefore we did not build the transaction with a preceding Null-Check.
This could allow for a SEGV during the transaction if the variable
being locked is null.
On PPC a SEGV within a transaction will result in a core dump rather
then a transaction rollback. For this reason we must have an explicit
Null-Check before the transaction starts. On platforms were a SEGV in
a transaction would result in a rollback, it still might be better to
Null-Check before the transaction to avoid a series of SEGV's during
the transaction attempts. At the moment TLE is only enabled on Z, so
this change is being done in case TLE is re-enabled on PPC in the
future. …

Fix a PPC TLE issue, a missing NULLCHK causing a crash in a transaction

---

test/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-6.xml

Fix typo in ShareClassesCMLTests-6-xml.

---

jcl/src/java.base/share/classes/java/lang/invoke/GenerateJLIClassesHelper.java

Fixes #1606 
Signed-off-by: Andrew Leonard <andrew_m_leonard@uk.ibm.com>

Add new GenerateJLIClassesHelper stub method

---

runtime/bcutil/ClassFileOracle.cpp

If a type annotation's type_index does not refer to a CONSTANT_UTF8_info
structure, don't mark it as being used.  When writing the ROM class, ensure
that constant pool entries marked as used by annotations are UTF8.
FYI @fengxue-IS 

Check type_index of runtime visible type annotations

---

runtime/include/jniport.h
runtime/vm/jvminit.c

Delete references to RIM386

---

runtime/compiler/trj9/optimizer/InlinerTempForJ9.cpp
runtime/compiler/trj9/optimizer/J9EstimateCodeSize.cpp

The function name is changed in OMR.

Use getClass instead of getFixedClass

---

runtime/jvmti/jvmtiHeap.c

Per JVMTI specification for FollowReferences(), do not report the class of
Class objects.

Do not report references to object type from Class objects

---

buildenv/jenkins/common/build
buildenv/jenkins/common/test

Convert NODE_NAME to hyperlink in build description

---

buildenv/docker/jdk8/s390x/ubuntu16/Dockerfile

- fixes https://github.com/eclipse/openj9/issues/1526
- [skip ci]

Update s390 docker image for JDK8 to use Adopt-OpenJ9

---

jcl/com.ibm.lang.management-javadoc-829.xml
jcl/src/jdk.management/share/classes/openj9/lang/management/package-info.java

Update management javadoc with additions for openj9.lang.management.

Update management javadoc

---

runtime/compiler/trj9/optimizer/J9Optimizer.cpp

Signed-off-by: Yan Luo <Yan_Luo@ca.ibm.com>

Run explicit new initialization pass after local VP to recognize more field initialization

---

test/Jsr292/src/com/ibm/j9/jsr292/LookupAPITests_Find.java
test/Jsr292/src/com/ibm/j9/jsr292/TestInterfaceWithDefaultMethod.java

Add tests for findVirtual on interface concrete methods

---

buildenv/jenkins/common/test

Do not fail the test pipeline build when clean workspace fails

---

runtime/compiler/trj9/env/SystemSegmentProvider.cpp

In J9::SystemSegmentProvider::release, when a large segment is freed, it
doesn't get added to the free list, but rather, is immedately released
to the OS. However, the code would first free this memory, and then read
the size, which can cause crashes or risks reading invalid data. This
commit fixes this issue. This is only an issue because when a
TR::MemorySegment is added to the _segments set in
J9::SystemSegmentProvider::allocateNewSegment, what gets returned is not
a copy of the TR::MemorySegment, but a reference to the element in the
set; therefore, when the element is erased from the set, all references
to it become invalid.

Get segment size before erase

---

test/README.md
test/docs/OpenJ9TestUserGuide.md

* update test docs to match test structure
[ci skip]
Issue:#1708

update test docs to match test structure

---

runtime/compiler/trj9/optimizer/DataAccessAccelerator.cpp
runtime/compiler/trj9/z/codegen/J9TreeEvaluator.cpp

BCDCHK is a node that can GC-and-Return. As a result of this,
LocalCSE does not common BCDCHK's address node with any address
node after the BCDCHK.
When the BCDCHK produces a PackedDecimal type, it'll be followed by a
pdstorei node, which has the same address node as the BCDCHK node.
If this BCDCHK and it's following pdstorei share the same
address node, then no address node after the pdstorei could be commoned
with the pdstorei's address node because BCDCHK prevents this from
happening. Failing to common such address nodes can result in unnecessary
load-after-store instruction sequence (e.g. VLRL after VSTRL). This is
redundant and inefficient.
Separating BCDCHK's and pdstorei's address nodes makes the aforementioned
address node commoning possible and opens up opportunities for packed …

Separate address node of BCDCHK and fix data type

---

runtime/jnichk/jnicheck.c
runtime/jnichk/jnicmem.c

Add new scope to allow macros to define variables.

Fix compile errors

---

buildenv/docker/jdk10/ppc64le/ubuntu16/Dockerfile
buildenv/docker/jdk10/s390x/ubuntu16/Dockerfile
buildenv/docker/jdk10/x86_64/ubuntu16/Dockerfile
buildenv/docker/jdk8/ppc64le/ubuntu16/Dockerfile
buildenv/docker/jdk8/s390x/ubuntu16/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu16/Dockerfile
buildenv/docker/jdk9/ppc64le/ubuntu16/Dockerfile
buildenv/docker/jdk9/s390x/ubuntu16/Dockerfile
buildenv/docker/jdk9/x86_64/ubuntu16/Dockerfile

Add CMake to the docker images

---

buildenv/jenkins/jobs/infrastructure/tagRepos

Increase timeout for tagRepos builds

---

test/TestConfig/run_configure.mk
test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl
test/TestConfig/scripts/testKitGen/testKitGen.pl
test/docs/OpenJ9TestUserGuide.md

- TKG will only generate make files for projects in BUILD_LIST.
- Update readme.
[ci skip]

Add support for build list in TKG

---

runtime/gc_structs/ConstantPoolObjectSlotIterator.cpp

Update GC_ConstantPoolObjectSlotIterator to recognize constantDynamic
Close: #1273

Add Constant Dynamic support in GC

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK10-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK10-linux_390-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK10-linux_ppc-64_cmprssptrs_le
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK8-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK8-linux_390-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK8-linux_ppc-64_cmprssptrs_le
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK9-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK9-linux_390-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK9-linux_ppc-64_cmprssptrs_le
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK10-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK10-linux_390-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK10-linux_ppc-64_cmprssptrs_le
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK8-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK8-linux_390-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK8-linux_ppc-64_cmprssptrs_le
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK9-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK9-linux_390-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK9-linux_ppc-64_cmprssptrs_le
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK10-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK10-linux_390-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK11-linux_ppc-64_cmprssptrs_le_valhalla_nestmates
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK8-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK8-linux_390-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK8-linux_ppc-64_cmprssptrs_le
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK9-aix_ppc-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK9-linux_390-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK9-linux_ppc-64_cmprssptrs_le

Set a 10 hours timeout for the entire pipeline build
[ci skip]

Add pull request pipelines timeout

---

buildspecs/linux_ppc-64_cmprssptrs_le_valhalla_nestmates.spec

- Turn off java8, java9, j2se
- Update shortname
Signed-off-by: Talia McCormick <Talia.McCormick@ibm.com>

Update Valhalla nestmates spec flags

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/gc/MMObjectAccessBarrier_V1.java

- Prevent DDR compile failure in default builds with reflection
Addition to issue #1669

Create noncompressedrefs build (step 1)

---

buildenv/Build_Instructions_V10.md
buildenv/Build_Instructions_V8.md
buildenv/Build_Instructions_V9.md

* OMR now detects the location of the DIA SDK automatically
* cpio is in the Utils package

Update build instructions for Windows

---

runtime/vm/CMakeLists.txt

CMake: Add missing files to vm

---

buildenv/jenkins/README.md
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK10-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK8-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK9-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK10-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK8-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK9-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK10-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK8-linux_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK9-linux_x86-64_cmprssptrs
buildenv/jenkins/variables/defaults.yml

- Add to nightly build
- Add PullRequest builds
- Add xLinux variables
- Update README
[skip ci]
Issue #1785

Add xLinux JenkinsFiles

---

test/Utils/src/org/openj9/test/util/IncludeExcludeTestAnnotationTransformer.java

Create tmp exclude file if EXCLUDE_FILE env var null or empty
Issue #1375 
[ci skip]

Fix for issue 1375 (exclude file not found)

---

README.md

Contributors don't need to become foundation members.

fix contribution guide

---

buildenv/jenkins/README.md
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK10-win_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK8-win_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK9-win_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK10-win_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK8-win_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK9-win_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK10-win_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs
buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK9-win_x86-64_cmprssptrs
buildenv/jenkins/variables/defaults.yml

- Add Windows variables
- Add to nightly build
- Add PullRequest Builds
[skip ci]
Issue #1662 
~Depends #1803~
~Currently Blocked by https://github.com/eclipse/openj9/issues/1662#issuecomment-385605381~
~Depends ibmruntimes/openj9-openjdk-jdk8#83~

Add JenkinsFiles for Windows

---

buildenv/jenkins/variables/defaults.yml

- Git clone step looks for Windows style path
Issue #1873
[skip ci]

Change Windows ref_repo to Win style path

---

jcl/src/java.base/share/classes/java/lang/Class.java
test/functional/Java8andUp/src_80/org/openj9/test/java/lang/Test_Class.java
test/functional/Java8andUp/src_90/org/openj9/test/java/lang/Test_Class.java

Fix Class.getResource result with object as array

---

runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/followReferences/fr002.c
runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/followReferences/fr003.c
runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/followReferences/fr004.c

Fix problems introduced by #1901

Fix printf formatters in jvmti tests to avoid compiler errors

---

buildenv/jenkins/common/test

Archive test results if build UNSTABLE

---

test/functional/Java8andUp/src_80/org/openj9/test/java/lang/Test_Class.java
test/functional/Java8andUp/src_90/org/openj9/test/java/lang/Test_Class.java

Test with object as an array
Tests: #1849

Additional test for Class.getResourceAsStream

---

test/functional/cmdLineTests/shareClassTests/SCCommandLineOptionTests/playlist.xml

Exclude SCCommandLineOptionTests until it's fixed

---

test/functional/cmdLineTests/shareClassTests/SCCommandLineOptionTests/playlist.xml

Exclude SCCommandLineOptionTests for SE80 windows

---

runtime/vm/VMAccess.cpp

- add some stronger barriers to exclusive
- refactor exclusive to check inNative first

Atomic-free JNI work

---

debugtools/DDR_VM/src/com/ibm/j9ddr/tools/PointerGenerator.java

Whether a generated pointer class is needed is independent of how
many fields or constants it might declare. We could analyze all
the types and generate only those with fields, or that are used
by some other type, but not all references can be expressed in
the superset.dat file. In particular, the format of that file
permits a type to have at most one superclass, and there are C++
classes that employ multiple inheritance (e.g. SH_CompositeCacheImpl
inherits from both SH_CompositeCache and AbstractMemoryPermission).
As a result, a few extra classes will be generated, but they will be
small (they have no fields else they would been generated previously).
On zLinux, a few is about 140.
Minor cleanup:
* remove empty 'omitList' and its uses
* simplify generation of base class name
Fixes #1973

Generate all DDR pointer types

---

test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl
test/functional/SharedCPEntryInvokerTests/build.xml

Enable SharedCPEntryInvokerTests

---

buildenv/jenkins/README.md

- Document an example of each regex we use for each unique build
[skip ci]
Issue #2020

Add section for PR trigger regexes

---

test/TestConfig/scripts/testKitGen/resultsSummary/resultsSum.pl

Generate tap file when there's no test

---

test/TestConfig/makefile
test/TestConfig/scripts/tools/getDependencies.pl
test/docs/Prerequisites.md

Related issue: https://github.com/AdoptOpenJDK/openjdk-tests/issues/431
[ci skip]

Use curl to download dependencies on zos

---

jcl/src/java.base/share/classes/java/lang/String.java
test/functional/Java11andUp/src/org/openj9/test/java_lang/Test_String.java

Add new Java 11 methods
Fixes: #1977

 Added String.strip, stripLeading, stripTrailing

---

runtime/jcl/common/reflecthelp.c

`JVM_GetMethodParameters` returns `null` to trigger parameter synthesizing
A `NULL` return value from `getMethodParametersAsArray()` eventually `JVM_GetMethodParameters` triggers `j.l.r.Executable.synthesizeAllParams()`, which supplies proper parameter info.
closes: #1850 #1851 #1852 #1853 #1854
In addition, this PR fixes an `OpenLiberty` issue mentioned at https://github.com/eclipse/openj9/issues/1852#issuecomment-393888832.
Note: current code returns `NULL` as well when there is an error condition. Probably an explicit `exception/error` is thrown instead. Will leave that to a separated PR when `JVM_GetMethodParameters` is understood better before changing JVM behaviours.

JVM_GetMethodParameters returns null to trigger synthesizing

---

jcl/jpp_configuration.xml

Update Java 11 rt-compressed classes

---

test/functional/Java8andUp/src/org/openj9/test/attachAPI/AttachApiTest.java
test/functional/Java8andUp/src/org/openj9/test/attachAPI/TestAttachAPI.java
test/functional/Java8andUp/src/org/openj9/test/attachAPI/TestAttachErrorHandling.java
test/functional/TestUtilities/src/org/openj9/test/util/FileUtilities.java

Add the initial version of FileUtilities with one method:
recursive file/directory deletion.

Add FileUtilities

---

buildenv/Build_Instructions_V10.md
buildenv/Build_Instructions_V8.md
buildenv/Build_Instructions_V9.md

Add build information for noncompressedrefs builds

---

runtime/nls/j9vm/j9vm.nls

Avoid unnecessary translation and having to fix sample inputs

Remove the text for some obsolete NLS messages

---

runtime/compiler/optimizer/J9Inliner.cpp
runtime/compiler/runtime/ValueProfiler.cpp

This commit has the following changes:
- Fix the problem that getMethodsList returns a mix of methods and
classes
- Use isSameMethod instead of '==' to test the equality of two
TR_ResolvedMethods in getMethodsList
- Use classOfMethod to get the target class

Fix for getting hottest profiled method

---

test/functional/cmdLineTests/callsitedbgddrext/build.xml
test/functional/cmdLineTests/callsitedbgddrext/callsiteddrtests.xml
test/functional/cmdLineTests/callsitedbgddrext/playlist.xml

Migrate callsitedbgddrext test to openj9

---

sourcetools/CMakeLists.txt
sourcetools/com.ibm.jpp.preprocessor/CMakeLists.txt
sourcetools/j9constantpool/CMakeLists.txt
sourcetools/j9nls/CMakeLists.txt
sourcetools/objectmodel/CMakeLists.txt

CMake: Add cmakelists for sourcetools

---

buildenv/jenkins/common/build
buildenv/jenkins/common/variables-functions
buildenv/jenkins/jobs/builds/Build-JDK9-linux_x86-64_cmprssptrs_cmake
buildenv/jenkins/jobs/pipelines/Pipeline-OMR-Acceptance
buildenv/jenkins/variables/defaults.yml

Jenkins: Add CMake build to omr acceptance build

---

buildenv/jenkins/jobs/pipelines/Pipeline-OMR-Acceptance

Fix missing quotes in omr acceptance pipeline

---

runtime/bcverify/rtverify.c

The change is to avoid decoding the garbage data on
the live stack in generating the error messages if
the stack is loaded from one of stackmaps in which
there is no data existing on the stack.
Signed-off-by: CHENGJin <jincheng@ca.ibm.com>

Prevent the garbage data from being decoded on the stack

---

buildenv/jenkins/jobs/pipelines/Pipeline-OMR-Acceptance

Properly define the openjdk repo for java 9

Fix omr acceptance pipeline issue

---

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
jcl/src/java.base/share/classes/java/lang/ref/Reference.java

Added an implementation of java.lang.ref.Reference.clone().
Closes: #1978
[ci skip] 

Add implementation of java.lang.ref.Reference.clone()

---

test/functional/cmdLineTests/jvmtitests/jvmtitests_excludes_SE80.xml

Fix regex in ta001 exclude

---

runtime/bcutil/defineclass.c

Don't update module if Java 8 or romclass is null

---

runtime/gc_base/StringTable.cpp

Interned String objects are created in tenure space. Currently,
the char[] backing these String objects is left in the nursery.
This means that until the char[] is tenure the Remembered Set has
to contain an entry for each new interned String. To reduce the
overhead on the RS we are going to tenure the char[].
Historically this was happening but the change got lost in
refactoring a few years ago.
Signed-off-by: Charlie Gracie <charlie.gracie@gmail.com>

Tenure char[] for interned String objects

---

runtime/vm/createramclass.cpp

Fix incorrect local variable type

---

buildenv/jenkins/README.md

Issue #1884 #1669
[skip ci]
@pshipton

Add xlinux large heap to README

---

runtime/vm/jnifield.cpp

Fix copyright broken by revert

---

buildenv/Build_Instructions_V8.md

* correct path to freetype.vcxproj
* simplify configure advice

Update build instructions for Windows 32-bit

---

buildenv/jenkins/common/pipeline-functions

Remove extra bracket

---

buildenv/jenkins/common/pipeline-functions

Fix syntax problem in jobs array variable index reference

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

For obtaining the hashCode of a compressed String, each iteration of the SSE loop moves 4 bytes from memory to the low doubleword of the XMM register. The stride shift amount is set to 0 for handling bytes. These packed 1 byte integers are then zero extended with instruction pmovzxbd and the same procedure to obtain the hashCode as with decompressed Strings is used.
A vector conversion example has been added to show how this procedure works.
Signed-off-by: Mansoor Saqib <Mansoor.Saqib@ibm.com>

Acceleration for x86 compressed String hashCode with vectorization

---

test/functional/JLM_Tests/playlist.xml

Temporarily exclude TestOpenJ9DiagnosticsMXBean on win_x86

---

test/functional/cmdLineTests/shareClassTests/SCHelperCompatabilityTests/HelperCompatabilityTests.xml
test/functional/cmdLineTests/shareClassTests/SCHelperCompatabilityTests/HelperCompatabilityTests_SE80.xml
test/functional/cmdLineTests/shareClassTests/URLHelperTests/URLHelperTests.xml
test/functional/cmdLineTests/shareClassTests/URLHelperTests/URLHelperTests_80.xml

Use cache name for HelperCompatabilityTests and URLHelperTests

---

runtime/shared_common/OSCache.cpp
runtime/shared_common/ScopeManagerImpl.cpp
runtime/shared_common/ScopeManagerImpl.hpp
runtime/shared_common/shrinit.cpp

Fix the compile errors from -Woverloaded-virtual

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

General code cleanup, removing deadcode.

Remove deadcode in X86::J9TreeEvaluator

---

sourcetools/com.ibm.uma/com/ibm/j9/uma/platform/PlatformWindows.java

Clean up outdated code for palm-size pc

---

test/TestConfig/resources/excludes/latest_exclude_SE110.txt
test/functional/Java9andUp/playlist.xml
test/functional/Java9andUp/src/org/openj9/test/constantPoolTags/ConstantPoolTagTests.java

get Java9andUp test ready for JDK11

---

test/functional/cmdLineTests/shrcdbgddrext/build.xml
test/functional/cmdLineTests/shrcdbgddrext/concatenate_dumps.sh
test/functional/cmdLineTests/shrcdbgddrext/playlist.xml
test/functional/cmdLineTests/shrcdbgddrext/shrcdbgextddrtests.xml

Migrate shrcdbgddrext test to openj9

---

runtime/compiler/build/platform/host/amd64-osx-clang.mk
runtime/compiler/build/toolcfg/host/osx.mk
runtime/compiler/runtime/J9Profiler.hpp
runtime/compiler/runtime/J9ValueProfiler.hpp

Signed-of-by: Nazim Uddin Bhuiyan <nazimudd@ualberta.ca>

Enable building the JIT on OSX

---

runtime/compiler/z/codegen/J9S390PrivateLinkage.cpp

Remove deprecated restricted register query

---

cdsadapter/.project
cdsadapter/com.ibm.cds/src/com/ibm/cds/CDSBundleEntry.java
cdsadapter/com.ibm.cds/src/com/ibm/cds/CDSBundleFile.java
cdsadapter/com.ibm.cds/src/com/ibm/cds/CDSHookConfigurator.java
cdsadapter/com.ibm.cds/src/com/ibm/cds/CDSHookImpls.java

Contribute only the java source files of the CDS adapter project to
OpenJ9

Contribute the source code of CDS adapter to OpenJ9

---

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/Platform.java
runtime/ddrext/ddr.h
runtime/ddrext/ddrinit.c
runtime/ddrext/ddrjni.c
runtime/makelib/targets.mk.osx.inc.ftl
runtime/runtimetools/osmemory/OSMemoryAgent.cpp

More mac changes to address compile issues

---

runtime/jcl/uma/se6_vm-side_natives_exports.xml

Delete obsolete setNumberEntitledCPUsImpl export

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

Rework x86 code generation for wrtbari under gencon GC
Reworked code to first check whether the target object of the write barrier is old and whether the value is not old to reduce the frequency of calling the out-of-line VM write barrier helper.  Also, should always check heapBaseBarrierRange and heapSizeBarrierRange instead of lowTenureAddress and highTenureAddress, as the latter will be going away.
Fixes: #2135

Gc mark remembered final

---

buildenv/jenkins/jobs/pipelines/Pipeline-OMR-Acceptance

[skip ci]
Fixes #2301
@pshipton

Increase OMR build timeout to 10H

---

runtime/redirector/generated.c.m4
runtime/redirector/redirector.c

Add OSX ifdefs to redirector

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

Code cleanup, removing deprecated string hash code implementation on X86.

Remove deprecated code related to string hash code

---

runtime/tests/port/j9shsemTest.c
runtime/tests/port/j9shsem_deprecatedTest.c
runtime/tests/port/j9vmemTest.c
runtime/tests/port/shmem.c
runtime/tests/port/testProcessHelpers.c
runtime/tests/redirector/jep178/testjep178.c
runtime/tests/redirector/jep178/testjep178.h
runtime/tests/shared/ProcessHelper.cpp

Fix if defined() formatting and add OSX

---

jcl/src/java.base/share/classes/java/lang/Access.java

Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

Add missing throws CharacterCodingException

---

runtime/compiler/z/codegen/ReduceSynchronizedFieldLoad.cpp

The ReduceSynchronizedFieldLoad codegen path did not check the load node's
isSignExtendedTo64BitAtSource flag. As a result, a 32-bit value without sign
extension can lead to program crashes.
This commit fixes this issue by performing a sign extension on the
loaded 32-bit field.

Add sign extension for reduce synchronized field load

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/X86PrivateLinkage.cpp

Issue: #36
Signed-off-by: Nazim Uddin Bhuiyan <nazimudd@ualberta.ca>

JIT on Mac OSX: add OSX ifdef checks, handle uint64_t vs uintptr_t

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

eclipse/omr#2640 introduced TR_OutlinedInstructionsGenerator, which uses RAII
to hide the management of the instruction stream manipulations.
OpenJ9 now adopts it.

Adopt OMR's TR_OutlinedInstructionsGenerator

---

test/TestConfig/settings.mk
test/functional/cmdLineTests/runtimemxbeanTests/exclude.xml
test/functional/cmdLineTests/runtimemxbeanTests/getPidTest.pl
test/functional/cmdLineTests/runtimemxbeanTests/playlist.xml
test/functional/cmdLineTests/runtimemxbeanTests/src/GetPid.java

Reverts eclipse/openj9#1957
[ci skip]

Revert "Fix getPid failure in Windows"

---

runtime/nls/shrc/j9shr_cs.nls

j9shr_cs.nls file update in TVT pass 2.
Signed-off-by: Lei Pan pleinb@cn.ibm.com

Modify the translated PII files in nls folder

---

buildenv/jenkins/README.md
buildenv/jenkins/jobs/infrastructure/signedOffByCheck

Add ability to check SignedOffby format for commits

---

runtime/buildtools.mk

CMake: set J9VM_JAVA_VERSION from VERSION_MAJOR if provided

---

runtime/redirector/CMakeLists.txt

CMake: Add missing defines to redirector

---

runtime/util/hshelp.c

Fix warning introduced in #2409

---

runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp
runtime/compiler/x/codegen/X86PrivateLinkage.cpp
runtime/compiler/x/i386/codegen/IA32PrivateLinkage.cpp

According to Agner Fog's instruction tables, one PUSH instruction performs worse
than the SUB+MOV instruction combinations. In addition, using PUSH instruction
requires stack adjustments before and after preserving registers as they are neither
at the beginning nor at the end of the stack; and hence two extra SUB instructions
cannot be avoided. In fact, X86-64 never uses PUSH instruction for register
preservations, and X86-32 only uses it under limited situations.
This commit removes the logics related to allow using PUSH instruction to preserve
registers, so that follow-up changes can elimite one or two instructions in the prolog.

Disallow using PUSH to preserve registers on X86

---

runtime/j9vm/java11vmi.c
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/intfunc.c
runtime/vm/visible.c

Add implementation for JVM_AreNestMates

Implement JVM_AreNestMates public native

---

runtime/compiler/x/codegen/X86PrivateLinkage.cpp

General code cleanup for prolog generation of private linkage on X86.

Code cleanup for Private Linkage on X86

---

test/TestConfig/scripts/tools/getDependencies.pl

If a file exists, verify its SHA before skipping the download step: issue https://github.com/eclipse/openj9/issues/2440

Improve test dependency acquisition

---

runtime/codert_vm/cnathelp.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/runtime/RelocationRecord.cpp
runtime/jcl/common/java_dyn_methodhandle.c
runtime/jit_vm/cthelpers.cpp
runtime/oti/VMHelpers.hpp
runtime/oti/j9.h
runtime/oti/j9nonbuilder.h
runtime/oti/j9protos.h
runtime/oti/vm_api.h
runtime/util/hshelp.c
runtime/util/resolvehelp.c
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/callin.cpp
runtime/vm/classsupport.c
runtime/vm/createramclass.cpp
runtime/vm/intfunc.c
runtime/vm/jnicsup.cpp
runtime/vm/resolvesupport.cpp

Revert "Revert "Refactor VTable index/offset variable name""

---

runtime/vm/ObjectMonitor.cpp

1) **Revert "Improve locking"**
This commit reverts the first commit in #553.
The purpose of the original change was to reduce compare and swap
operations in the spinlock loop; thus, reducing spinning overhead. The
premise was to improve throughput by reducing spinning overhead. In the
initial benchmarking, no throughput improvements were noticed because of
this change. Recently, this change has resulted in regressing
throughput. ~30% throughput drop is observed in one of the OpenLiberty
benchmarks. Thus, it has been decided to revert the original change.

Locking Changes

---

jcl/src/java.base/share/classes/com/ibm/jit/JITHelpers.java
jcl/src/java.base/share/classes/java/lang/String.java
runtime/compiler/codegen/J9CodeGenerator.hpp
runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/x/codegen/J9CodeGenerator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp

Implement an evaluator for String.indexOf() using vectors
on Z.
Signed-off-by: Daniel Hong <daniel.hong@live.com>

Implement vectorized String.indexOf() on Z

---

runtime/compiler/env/CHTable.cpp

In commiting virtual guards, mergedWithOSRGuard is not handled
correctly, resulting in some guards of this kind always be patched at
compile time.
Fixes: #2475

Properly register assumptions on mergedWithOSRGuard

---

jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/utils/file/ZipFileManager.java

Add one additional check in getExtractLocation().

---

test/functional/cmdLineTests/jvmtitests/jvmtitests_excludes_SE80.xml

Unexclude jvmtitest ta001

---

jcl/src/java.base/share/classes/java/lang/String.java

Signed-off-by: Yan Luo <Yan_Luo@ca.ibm.com>

String startsWith fast path for single char comparison

---

runtime/codert_vm/cnathelp.cpp
runtime/compiler/codegen/J9CodeGenerator.hpp
runtime/compiler/env/j9method.cpp
runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp
runtime/compiler/optimizer/J9RecognizedCallTransformer.hpp
runtime/compiler/runtime/Runtime.cpp
runtime/compiler/x/codegen/J9CodeGenerator.cpp
runtime/compiler/x/codegen/J9CodeGenerator.hpp
runtime/oti/jitprotos.h

java/lang/Class.isAssignableFrom() is transformed into a JIT Helper
so that JNI call overhead is avoided.

Optimize j/l/Class.isAssignableFrom on X86

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/AlgorithmVersion.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/J9ClassHelper.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/RamClassWalker.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/J9VTablesCommand.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/VmCheckCommand.java
runtime/ddr/algorithm_versions.c

- Add algorithm version for vtable
- update vtable access methods to use J9VTableHeader structure
Close: #2488 

Fix DDR vTable Indexing

---

buildenv/jenkins/common/pipeline-functions

Enable extended.system test in nightly build

---

test/functional/Valhalla/build.xml
test/functional/Valhalla/playlist.xml

Turn on nestmates test in Java11

Turn on nestmates test in Java11

---

jcl/src/java.base/share/classes/java/lang/StringBuilder.java

- Replace the creation of substrings with an arraycopy
to StringBuilder's value array.
- Remove Java 9 path as it won't be compiled for Java 9+
Signed-off-by: Mansoor Saqib <Mansoor.Saqib@ibm.com>

Accelerate StringBuilder append for Java8 by removing substrings

---

buildspecs/aix_ppc-64.spec
buildspecs/aix_ppc-64_cmprssptrs.spec
buildspecs/aix_ppc.spec
buildspecs/linux_390-64.spec
buildspecs/linux_390-64_cmprssptrs.spec
buildspecs/linux_390.spec
buildspecs/linux_ppc-64.spec
buildspecs/linux_ppc-64_cmprssptrs.spec
buildspecs/linux_ppc-64_cmprssptrs_le.spec
buildspecs/linux_ppc-64_cmprssptrs_le_gcc.spec
buildspecs/linux_ppc-64_le.spec
buildspecs/linux_ppc-64_le_gcc.spec
buildspecs/linux_ppc.spec
buildspecs/linux_x86-64.spec
buildspecs/linux_x86-64_cmprssptrs.spec
buildspecs/linux_x86.spec
buildspecs/linux_ztpf_390-64.spec
buildspecs/linux_ztpf_390-64_cmprssptrs.spec
buildspecs/win_x86-64.spec
buildspecs/win_x86-64_cmprssptrs.spec
buildspecs/win_x86.spec
buildspecs/zos_390-64.spec
buildspecs/zos_390-64_cmprssptrs.spec
buildspecs/zos_390.spec

Enable the feature everywhere but ARM and OSX.

Enable atomic-free JNI

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/stackwalker/StackWalker.java

Forgot the change in the original PR.

Update DDR to match #2569

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

On X86, the current gencon JIT write barrier instruction sequence requires range check to see if an object is in the tenure space or not. It is implemented as a subtract instruction to calculate the offset of the object pointer (`offset = object - heapBase`), followed by a compare instruction that compares `offset` with `heapSize`. If `heapSize` and `heapBase` are fixed (e.g. `-Xmx -Xms` are set at the same value), we can optimize this sequence by using one instruction that simply compares the object with `(heapBase + heapSize)`, whose value can be materialized at compile time and does not change during the lifetime of the JVM process. 
Signed-off-by: Yan Luo <Yan_Luo@ca.ibm.com>

Gencon fixed heap wrtbar range check optimization on X86

---

runtime/jvmti/jvmtiClass.c

In extended HCR, the J9Class pointers of replaced classes change. Update
the watched field data that references J9Class pointers.

Update watched field data when replacing classes

---

jcl/src/java.base/share/classes/module-info.java.extra
jcl/src/java.management/share/classes/module-info.java.extra
jcl/src/jdk.attach/share/classes/module-info.java.extra
jcl/src/jdk.management/share/classes/module-info.java.extra

Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

Fixup module-info.java.extra files

---

jcl/src/java.base/share/classes/module-info.java.extra
jcl/src/java.management/share/classes/module-info.java.extra
jcl/src/jdk.attach/share/classes/module-info.java.extra
jcl/src/jdk.management/share/classes/module-info.java.extra
sourcetools/J9_JCL_Build_Tools/src/com/ibm/moduletools/ModuleInfoMerger.java

Replays https://github.com/eclipse/openj9/pull/2586 and fixes ModuleInfoMerger.

Fix module-info.java.extra files

---

buildenv/jenkins/jobs/pipelines/Pipeline-OMR-Acceptance

Add vendor tests parameters to Jenkins build job

---

buildenv/jenkins/jobs/pipelines/Pipeline-OMR-Acceptance

Initialize vendor test variables for Jenkins jobs

---

runtime/compiler/z/codegen/DFPTreeEvaluator.cpp
runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp

The API has moved from the FrontEnd class.

Use findOrCreateLiteral from Z code generator

---

runtime/port/unix/j9sysinfo.c

If the `LOADxx MACHMIG VEF` load parameter is set at IPL time the user
has requested to disable the VEF support in z/OS, as such the CVTVEF
bit will not be enabled for the system.
We currently only check the LE support which says whether LE is
configured to support vector registers. In addition to this check we
also need to validate the CVTVEF bit in the CVT data structure
similarly to other features requiring OS support, such as RI, TX, or GS.
Further we take this opportunity to make improvements in the area:
- Isolate all OS checks into separate functions
- Use them instead of directly checking CVT bits
- Add documentation on which bits we are checking
- Move checks to corresponding processor areas
- Remove stale comments

Improve z/OS hardware check for Vector Extension Facility

---

runtime/oti/j9consts.h

Add bits to enable the JIT to push nestmates code.

Add iTable tag bits

---

test/functional/Java8andUp/src/org/openj9/test/vmArguments/VmArgumentTests.java

Exercise the -XX:[+-]HeapDumpOnOutOfMemoryError option added by
https://github.com/eclipse/openj9/pull/2533.  Add a trivial "HelloWorld"
program to exercise program launching.
[ci skip]

Add tests for heap dump enabling and disabling

---

runtime/gc_modron_standard/StandardAccessBarrier.cpp
runtime/gc_trace/TgcParallel.cpp

For Concurrent Scavenger Read Barrier, update two stats counters:
- number of object copied 
- number of slots updated
Report the progress of the stats in TGC parallel (it's expected to see
more activity early in a cycle).
Sample report shown (a few columns removed for brevity). The new columns
are rb-copy and rb-update.
```
micros	idle	busy	active	lists	caches	copied	scanned	rb-copy	rb-update
42315	0	4	4	14.9	123.7	591668	1094906	58784	59552
42167	0	4	4	14.8	130.3	632934	1081696	40320	41280
32368	0	4	4	14.1	80.2	605463	1070141	27360	27776
34518	0	4	4	10.2	136.4	555636	1058887	18944	19168
39602	0	4	4	5.3	107.6	652755	1056900	12672	12832
42559	0	4	4	4.7	83.2	665033	1060761	7232	7360
38657	0	4	4	5	163.1	670042	1058390	4064	4128
36611	0	4	4	5	311	669552	1058263	6240	6272
35870	0	4	4	4.2 …
```

Read barrier stats

---

runtime/gc_glue_java/MarkingDelegate.cpp

In MarkingDelegate.cpp, pass the object directly to the MarkObject
function.

Marking Delegate Optimization

---

runtime/vm/VMAccess.cpp

releaseExclusiveVMAccessFromExternalThread (mostly used by the metronome
GC policy) hands off to the normal exclusive while leaving
J9_PUBLIC_FLAGS_NOT_COUNTED_BY_EXCLUSIVE set in the target, which causes
a hang on the next hand off.
Fixes: #2643

Fix hang with metronome exclusive hand-off

---

test/functional/Java8andUp/playlist.xml

disable generalExtendedTest until the issue is fixed

---

runtime/jcl/common/java_lang_Class.cpp
runtime/nls/j9cl/j9jcl.nls
runtime/nls/j9vm/j9vm.nls
runtime/vm/visible.c

Refactor nestmates jcl natives

Refactor nestmates jcl natives

---

runtime/jcl/common/system.c
runtime/oti/j9nonbuilder.h
runtime/util/vmargs.c
runtime/vm/jvminit.c

Set the maximum direct byte buffer memory based on heap size

---

runtime/compiler/p/codegen/J9CodeGenerator.cpp

Changes to iterator prefetching has made an existing
bug more likely to surface by increasing the stride
value and by adding a new case that iterator prefetching
will operate on.
This change disables iterator prefetching unless
-Xaggressive is enabled which causes the GC to add a
trailing padding page to the end of the heap which
makes iterator prefecting perfectly safe.

Fix a possible SEGV due to iterator prefetching

---

runtime/jcl/common/java_lang_Class.cpp

Fix windows compile failures

---

runtime/jit_vm/cthelpers.cpp
runtime/oti/j9protos.h

add JIT compile time helper for getting constant dynamic type

---

runtime/codert_vm/armnathelp.m4
runtime/codert_vm/cnathelp.cpp
runtime/codert_vm/pnathelp.m4
runtime/codert_vm/xnathelp.m4
runtime/codert_vm/znathelp.m4
runtime/compiler/runtime/asmprotos.h
runtime/jilgen/jilconsts.c
runtime/oti/j9nonbuilder.h

Implement JIT helper for resolve constantDynamic

---

buildenv/jenkins/variables/defaults.yml

Remove unnecessary config options from AIX

---

test/functional/Java8andUp/playlist.xml
test/functional/Java8andUp/testng.xml

Move reflect tests in generalTest and reflect_getMethods to reflect testcase.
Close #2688 
[ci skip]

Set reflect tests in generalTest and reflect_getMethods to reflect testcase

---

runtime/compiler/optimizer/HCRGuardAnalysis.cpp

HCRGuardAnalysis uses single bit container as the gen and kill set, thus
when gen/kill is set, kill/gen should be cleared. For exception edges,
gen will flow through the exception edge when there exists one exception
point that can be reached by the gen. The fix also considers non-treetop
nodes that may except.

Fix HCRGuardAnalysis

---

test/functional/Jsr335/src/org/openj9/test/jsr335/defineAnonClass/AnonClass.java
test/functional/Jsr335/src/org/openj9/test/jsr335/defineAnonClass/TestUnsafeDefineAnonClass.java

Added a test to check if an anonymous class containing literals(a String
in the test case) of its own class name will return the correct value
Signed-off-by: Charles_Zheng <Juntian.Zheng@ibm.com>

AnonClass get own class name test

---

runtime/compiler/runtime/SignalHandler.c

The JIT should be converting a SIGBUS into an InternalError
exception when the signal occurs while executing java code
but when executing an a JIT helper (like arraycopy) the
code did not detect that as running in java code and
would fail to convert to an exception resulting in a
javacore/systemdump to be generated instead.

Handle SIGBUS properly when executing in PPC helpers

---

runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/decompResolveFrame/decomp001.c
runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/decompResolveFrame/decomp002.c
runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/decompResolveFrame/decomp004.c
runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/followReferences/fr001.c
runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/getPotentialCapabilities/gpc002.c
runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/redefineBreakpointCombo/rbc001.c
runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/retransformationCapableAgent/rca001.c
runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/retransformationIncapableAgent/ria001.c

Update error messages to refer to the right events

---

test/TestConfig/settings.mk

Set JVM_VERSION is sap only if JAVA_IMPL is sap

---

test/README.md

The closing tag should be `</disabled>`.
Also remove extraneous whitespace.
[ci skip]

Fix example XML element

---

jcl/src/java.base/share/classes/java/lang/invoke/MethodHandle.java
runtime/jcl/common/java_dyn_methodhandle.c
runtime/jcl/common/sun_reflect_ConstantPool.c
runtime/jcl/uma/se11_exports.xml
runtime/oti/jclprots.h

- add jcl export `getCPConstantDynamicAt`
- enable `getCPConstantDynamicAt` in MH.resolve code
Close: #1276 

Add sun_reflect_ConstantPool native for constantDynamic resolve

---

buildenv/jenkins/common/test

* [skip ci]
* partially address #2761

Set NATIVE_TEST_LIB environment for pull request testing

---

test/functional/Valhalla/build.xml
test/functional/build.xml

include Valhalla in top level build.xml

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All

- Add promote job at the end based on PROMOTE_OMR bool
- Remove jdk9 support from default releases
- Add cmake spec (jdk9 only)
Issue #2778
[skip ci]

Add OMR Acceptance support to P-B-T-All

---

runtime/compiler/runtime/Runtime.cpp
runtime/compiler/z/codegen/J9UnresolvedDataSnippet.cpp
runtime/compiler/z/runtime/PicBuilder.m4

This commit contains changes to suppport Constant Dynamic
in JIT Compiled code on Z platform.

IBM Z Codegen changes to support Condy in jdk11

---

runtime/jcl/common/java_lang_Class.cpp
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/intfunc.c
runtime/vm/visible.c
test/functional/Valhalla/src/org/openj9/test/valhalla/NestAttributeTest.java

Fix getNestMembers API exception handling
Add new tests to verify missing exception cases

Fix getNestMembers API exception handling

---

runtime/vm/BytecodeInterpreter.hpp

ldc loads data into a UDATA slot on the stack and primitive values
only uses 32bit on a 64bit system, this change will ensure that
32 bit values will always be written to the lower 32 bit of the slot
(For BE and LE systems)

Update ldc to load Constant_Dynamic primitives as I_32 type

---

runtime/vm/jnicsup.cpp

Remove goto in switch statement which caused PPCLE GCC to generate incorrect code.
Move local variables to inner scopes.
Remove deprecated usage of '--'.
Fixes https://github.com/eclipse/openj9/issues/2788

Clean up pushArguments()

---

runtime/vm/pcinterp.m4

Initialize JIT register based on 32/64-bit

---

runtime/compiler/z/codegen/S390J9CallSnippet.cpp

- Enable J2I thunk relocation for nestmate
- Replace addProjectSpecializedRelocation API with
addExternalRelocation() API, which is native to the OpenJ9 project.

Enable nestmate J2I thunk AOT support

---

runtime/nls/shrc/j9shr.nls
test/functional/cmdLineTests/shareClassTests/SCCommandLineOptionTests/nameOption6.bat
test/functional/cmdLineTests/shareClassTests/SCCommandLineOptionTests/nameOption6.sh
test/functional/cmdLineTests/shareClassTests/SCCommandLineOptionTests/sharedClassesUtil.pl

Fix typo and related tests

---

runtime/exelib/common/libargs.c
runtime/jniinv/main.c
runtime/tests/shared/main.c
runtime/tests/thread/thrstate/runtest.c
runtime/tests/vm_lifecycle/main.c

Fixes #2946 and updates error messages issued when the shared library fails to load.

Fix path returned by cmdline_fetchRedirectorDllDir

---

jcl/src/java.base/share/classes/java/lang/System.java

Preload security sensitive classes
Preload security sensitive classes when current security manager is `null`;
Not adding an extra static field to preload only once;
Minor refactoring to address Eclipse compiler warnings.
Along with https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/24
https://github.com/ibmruntimes/openj9-openjdk-jdk10/pull/60
and https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/37
fix: #2978 
Manually verified that the tests in question now pass with two PRs referred above.
Reviewer: @pshipton 
FYI: @DanHeidinga 

Preload security sensitive classes

---

test/functional/Jsr292/src/com/ibm/j9/jsr292/LookupAPITests_AccessClass.java
test/functional/Jsr292/src/com/ibm/j9/jsr292/LookupAPITests_FindClass.java

Update tests to match behaviour of reference implementation.
Fixes https://github.com/eclipse/openj9/issues/3037

Fix Jsr292 access checking tests

---

test/TestConfig/settings.mk
test/TestConfig/testEnv.mk

- add testEnv.mk
- if TEST_FLAG is JITAAS, startup and kill jitaasserver server

Add test evironment setup and teardown

---

runtime/gc_vlhgc/CopyForwardScheme.cpp

- the Assertion with the addtional message for helping debugging 
the case.

Update Invalid class Assertion check with message in CopyForward

---

runtime/util/hshelp.c

Correctly look up the method when doing the redefinition check for
private interface methods. Also correctly ignore final and virtual
Object methods in interface calls (Object can currently not be
redefined).
[ci skip]

Handle redefinition of private interface methods

---

jcl/src/java.base/share/classes/java/lang/Class.java

Fix UMA conditional content and use `&lt;` instead of `&#60;`, etc.

Fix javadoc for toGenericString()

---

test/TestConfig/scripts/tools/getDependencies.pl

Update link to get ASM-7.0 from Beta release page

---

buildenv/jenkins/common/build

- Slash already there via artifactory_upload_dir
[skip ci]
Issue #2952

Remove extra slashes in CUSTOMIZED_SDK_URL

---

runtime/codert_vm/cnathelp.cpp
runtime/codert_vm/xnathelp.m4
runtime/oti/xhelpers.m4

Update the code style to be consistent with nearby code.

Style update of jitReferenceArrayCopy on X86

---

buildenv/jenkins/common/pipeline-functions
buildenv/jenkins/common/variables-functions
buildenv/jenkins/jobs/infrastructure/Promote-OpenJ9-OMR-master-to-openj9

- YYYYMMDD-HHMMSS
- Affects the SDK filenames as well as the
merge date on the OMR tags
- Move function to be reusable

Fix datestamp to be ISO8601

---

buildenv/jenkins/common/variables-functions

Only set Artifactory env variables if they are not null

---

buildenv/jenkins/common/variables-functions

Fix Artifactory again

---

runtime/CMakeLists.txt
runtime/cmake/J9vmGenAsm.cmake
runtime/util/CMakeLists.txt
runtime/vm/CMakeLists.txt

Function simplifies generating assembly from m4 files

CMake: Add j9vm_gen_asm function

---

runtime/libffi/CMakeLists.txt
runtime/libffi/module.xml
runtime/libffi/preconf/oa/ffi.h
runtime/libffi/preconf/oa/fficonfig.h

- Added new pre-configured headers
- Updated UMA to use these new headers rather than the linux ones
- Add osx build config to CMake

FFI: update FFI to support osx

---

buildenv/jenkins/common/build
buildenv/jenkins/common/variables-functions
buildenv/jenkins/variables/defaults.yml

* [skip ci]
* Addresses #3118
* platforms: xlinux cmake, xlinux, xlinux large heap, plinux, zlinux, aix
* JDK8 only

Enable openssl within nightly and pr builds

---

buildenv/jenkins/variables/defaults.yml

Due to
https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/122
https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/123

Disable OpenSSL on zLinux and AIX

---

runtime/vm/vmbootlib.c

Improve readability by decreasing parameter indentation level

---

runtime/gc_modron_startup/mmparseXXgc.cpp
runtime/gc_verbose_handler_vlhgc/VerboseHandlerOutputVLHGC.cpp
runtime/gc_vlhgc/CollectionSetDelegate.cpp
runtime/gc_vlhgc/CopyForwardDelegate.hpp
runtime/gc_vlhgc/CopyForwardScheme.cpp
runtime/gc_vlhgc/CopyForwardScheme.hpp
runtime/gc_vlhgc/HeapRegionDescriptorVLHGC.cpp
runtime/gc_vlhgc/HeapRegionDescriptorVLHGC.hpp
runtime/gc_vlhgc/IncrementalGenerationalGC.cpp
runtime/gc_vlhgc/ProjectedSurvivalCollectionSetDelegate.cpp
runtime/gc_vlhgc/SchedulingDelegate.cpp

The original PR was causing failures when running with debug  -XXgc:tarokEnableExpensiveAssertions option that none of Travis or Jenkins test uses. Reverting till understanding if the failure is real or just the debug option is broken.

Revert "CopyForwardHybrid"

---

buildenv/jenkins/variables/defaults.yml

- add configuration options to enable OpenSSL
[ci skip]

Enable OpenSSL on Windows

---

runtime/cmake/platform.cmake
runtime/gc/CMakeLists.txt
runtime/port/CMakeLists.txt
runtime/thread/CMakeLists.txt

Simplifies our platform config story. Also allows us to conditionally
link librt

CMake: use OMR platform configuration

---

runtime/compiler/CMakeLists.txt

CMake: Only linux compiler exports when building on linux

---

runtime/CMakeLists.txt

This is the osx equivilent of $ORIGIN

CMake: set rpath to "@loader_path" on osx

---

runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/control/JITaaSCompilationThread.cpp
runtime/compiler/control/JITaaSCompilationThread.hpp
runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/env/J9ClassEnv.hpp
runtime/compiler/env/VMJ9Server.cpp

Jitaas development messages

---

debugtools/DDR_VM/compile_ddr.xml

Revert "Remove unused compile_ddr.xml file from DDR_VM debugtools"

---

test/TestConfig/openj9Settings.mk
test/TestConfig/testEnv.mk

- added option -XX:JITaaSClient for all tests when JITAAS is on
[ci skip]

Add jvm options for jitaas tests

---

buildenv/jenkins/variables/defaults.yml

* [skip ci]
Issue https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/129

Turn off openssl option for AIX

---

runtime/compiler/control/JITaaSCompilationThread.cpp
runtime/compiler/control/JITaaSCompilationThread.hpp
runtime/compiler/env/VMJ9Server.cpp

@mpirvu please review the changes

Reduce number of messages between client and server

---

buildenv/jenkins/docker-slaves/ppc64le/ubuntu16/Dockerfile

Added Dockerfile to create ubuntu16 containers on ppc64le.

Added new ppc64le Dockerfile

---

runtime/compiler/z/codegen/J9S390PrivateLinkage.cpp

In preparation for folding the query away in OMR we fold away the
TR_DisableLongDispStackSlot as false, meaning it is always available.
Issue: https://github.com/eclipse/omr/issues/2848

Fold away TR_DisableLongDispStackSlot as false

---

buildenv/jenkins/common/build

Fix git scm credentials

---

buildenv/jenkins/common/pipeline-functions
buildenv/jenkins/variables/defaults.yml

- Convert to int when used for RESTART time
[skip ci]
#3329

Pass RESTART_TIMEOUT around as string

---

runtime/shared_common/ROMClassManagerImpl.cpp
runtime/shared_common/ROMClassManagerImpl.hpp
runtime/shared_common/j9shr.tdf

Remove obsolete class RcLinkedListImpl

---

runtime/compiler/codegen/J9CodeGenerator.cpp

Under Concurrent Scavenger, read barriers when accessing
non-compressed instance fields will be generated.
Part of Issue #3338 

Generate read barrier for Concurrent Scavenger

---

buildenv/jenkins/common/pipeline-functions

Fixes: https://github.com/eclipse/openj9/issues/3480
[ci skip]

Fix MissingPropertyException for DOWNSTREAM_JOB_TIME property

---

buildenv/jenkins/docker-slaves/ppc64le/centos7/Dockerfile

Added new Dockerfile capable of creating centos7 containers on ppc64le.
[skip ci]

Added ppc64le centos7 dockerfile

---

buildenv/jenkins/common/build
buildenv/jenkins/common/test
buildenv/jenkins/jobs/builds/Build-Test-Any-Platform
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-Any-Platform

- Open Jenkins issue 54225
- Workspace isn't being deleted
Related #3309
[skip ci]

Temporarily turn off disableDeferredWipeout for cleanWs

---

buildenv/travis/build-on-travis.sh
runtime/CMakeLists.txt
runtime/cmake/version.cmake
runtime/jcl/CMakeLists.txt
runtime/jcl/cl_se10/CMakeLists.txt

CMake: Add support for java 10

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/optimizer/InlinerTempForJ9.cpp

Add a diamond to take the original call if the field is static final.

Report illegal write for Unsafe.put

---

buildenv/jenkins/variables/defaults.yml

* [skip ci]
* v2.13.03 installed as per #3461

Add nasm to path for windows pipelines

---

runtime/compiler/runtime/Runtime.cpp
runtime/compiler/x/amd64/codegen/J9TreeEvaluator.hpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.hpp
runtime/compiler/x/i386/codegen/J9TreeEvaluator.hpp

Add evaluator supports for reporting field access.
issue: #2668

Add the x86 evaluators for rdbar/wrtbar for field watch

---

runtime/compiler/control/J9Options.cpp

The supported Xcodecachetotal option is not allowed to decrease the default
value for the code cache repository. This commit eliminates that restriction,
but imposes a lower bound of 2MB.

Allow Xcodecachetotal to decrease default total code cache size

---

test/TestConfig/openj9Settings.mk
test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl
test/functional/NativeTest/playlist.xml
test/functional/cmdLineTests/dumpromtests/dumpromclasstests_excludes.xml
test/functional/cmdLineTests/dumpromtests/playlist.xml
test/functional/cmdLineTests/jep178staticLinkingTest/playlist.xml
test/functional/cmdLineTests/pltest/playlist.xml

Enable for 8,9,11
Disable problematic tests with issues opened
[ci skip]

Enable native tests using executables in test image

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/ModularityHelper.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/FindModulesCommand.java

- Will allow for improved testing
- Clarifies when no results were found over previous empty output
Signed-off-by: Andrew Crowther <acrowthe3388@gmail.com>

Update DDR !findmodules to output number of matches

---

test/functional/NativeTest/playlist.xml
test/functional/cmdLineTests/dumpromtests/playlist.xml
test/functional/cmdLineTests/jep178staticLinkingTest/playlist.xml

Disable failed tests
[ci skip]

Update jep178_staticLinking JVMLIBPATH

---

runtime/compiler/x/codegen/X86PrivateLinkage.cpp

Use generated instructions to call stack overflow check helper.

Migrate stack overflow check to generated instructions on X86

---

test/functional/cmdLineTests/modularityddrtests/modularityddrtests.xml

Add tests for the !findmodules ddr command implemented in #3024

Add tests for ddr !findmodules command

---

test/functional/cmdLineTests/shareClassTests/SCCMLTests/testSCCMLSnapshot.xml

Add osx to successful/failure conditions of testSCCMLSnapshot

---

test/functional/cmdLineTests/jep178staticLinkingTest/playlist.xml

Enable jep178_staticLinking_SE80 for jdk8

---

runtime/tests/shared/CacheDirPerm.cpp
runtime/tests/shared/CorruptCacheTest.cpp
runtime/tests/shared/OSCacheTestMmap.cpp
runtime/tests/shared/OSCacheTestSysv.cpp
runtime/tests/shared/SharedCacheAPITest.cpp
test/functional/NativeTest/playlist.xml

Update the test to use user's home directory as the cache directory 
on Java 11.
closes #3516

Fix shrtest

---

test/TestConfig/openj9Settings.mk
test/TestConfig/settings.mk

- Added flag KEEP_REPORTDIR in setting.mk to control staging
[ci skip]

Add a flag to switch on and off report dir staging

---

test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeGenerator.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java

Add new VT tests for default value
- Refactor existing VT generator and reduce code duplication
- Update VT generator to use defaultValue bytecode
- update comment in tests to show flattened vs ref
- add new generic VT creator for Q types 

Add new VT tests for default value

---

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/minidump/unwind/RuntimeFunction.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/LinearDumper.java

* ensure the behavior is reflexive and transitive
* use Integer.compare() and Long.compare() where appropriate
Fixes #3673

Fix implementations of Comparable

---

jcl/src/java.base/share/classes/java/lang/Class.java

As requested by @DanHeidinga [https://github.com/eclipse/openj9/pull/3638#discussion_r233868053].

Improve comment in doInitCacheIds()

---

test/functional/DDR_Test/playlist.xml

- Add playlist entires for openj9 and ibm
[ci skip]

Enable testDDRExt_Callsites test

---

buildenv/jenkins/common/variables-functions
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All

- Personal builds have the option to enter
BUILD_LIST but the option was never passed
along to the Pipeline jobs
[skip ci]

Pass BUILD_LIST from PBT-All

---

buildenv/jenkins/common/pipeline-functions
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All

Fix missed SETUP_LABEL variable rename

---

runtime/vm/BytecodeInterpreter.cpp
runtime/vm/BytecodeInterpreter.hpp

Signed-off-by: Charlie Gracie <charlie.gracie@gmail.com>

Enable computed goto for OSX

---

test/functional/VM_Test/src/j9vm/test/arraycopy/MultiThreadedBackwardArrayCopyTest.java

This commits adds a Java Test to verify atomicity of doing array copy in babckward direction.

Add multithreaded backward arraycopy test

---

buildenv/jenkins/variables/defaults.yml

- Branch names were updated to be consistent with other repos
[skip ci]

Update jdk(next) branch name

---

buildenv/jenkins/variables/defaults.yml

- Removed from folder name in jdk(next) (12+)
[skip ci]

Remove 'normal' from release folder

---

test/functional/cmdLineTests/sigxfszHandlingTest/sigxfszHandlingTest.xml

Fix typo in sigxfszHandlingTest

---

test/functional/Java8andUp/playlist.xml

Explicitly export LIBPATH JDK8 folder structure updates

---

runtime/oti/VMHelpers.hpp

Truncate JNI boolean returns

---

test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl

Temporarily turn off mode service

---

jcl/src/java.base/share/classes/java/lang/Access.java
jcl/src/java.base/share/classes/java/lang/ClassLoader.java
jcl/src/java.base/share/classes/java/lang/System.java
jcl/src/java.base/share/classes/java/lang/invoke/MethodHandle.java
jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
jcl/src/java.base/share/classes/java/lang/ref/Reference.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/BufferPoolMXBeanImpl.java

Fix Java12 import compile errors

---

doc/compiler/jitaas/README.md

Link points on file that was removed in 97b7ce388ff67728266c81269c0b783eb6bfabd7.

Remove broken link

---

test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeGenerator.java
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java

Add tests for withfield bytecode

Add tests for withfield bytecode

---

runtime/compiler/runtime/RelocationRuntime.cpp
runtime/compiler/runtime/RelocationRuntime.hpp

Fixes #3769
Signed-off-by: Irwin D'Souza <dsouzai@ca.ibm.com>

Ensure Concurrent Scavenge AOT compatibility

---

jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/FindCommand.java

The minor change is to modified the simplified usage
output of the find command to make it clear to users
Fix: #3819
Signed-off-by: CHENGJin <jincheng@ca.ibm.com>

Update the simplified usage output of find in jdmpview

---

runtime/cmake/caches/osx_x86-64.cmake

CMake: Add cache file for osx builds

---

runtime/jcl/common/shared.c

Fix boolean return in SCC API

---

doc/compiler/jitaas/Build.md

Add in "How to prepare your system for JITaaS". Previous doc was missing protobuf and other dependency installation procedures.
[skip ci]

Update JITaaS build documentations

---

runtime/compiler/env/j9method.cpp

Previously, if a filter arguments method handler was compiled, known object table had to be enabled, otherwise the compiler would crash.
However, Known Object Table is only used to improve an existing symbol
reference, it's not required for compilation.
This change enables to run with disabled known object table, by
using a list of filters, instead of a list of filter indices, to check if a null filter is used.

Handle disabled Known Object Table in invokeFilterArgumentsHandle

---

test/functional/Java8andUp/playlist.xml

Temporarily disable ContendedFieldsTests on osx

---

buildenv/jenkins/docker-slaves/ppc64le/ubuntu16/Dockerfile

Added gdb to package list to allow generation of core files

Updated ppc64le ubuntu16 Dockerfile

---

buildenv/jenkins/docker-slaves/x86/ubuntu18/Dockerfile

Added new dockerfile to create ubuntu18 docker containers
for testing purposes only.

Added ubuntu18 x86 Dockerfile

---

buildenv/jenkins/docker-slaves/ppc64le/ubuntu18/Dockerfile

Added new dockerfile to create ubuntu18 docker containers
for testing purposes only.

Added ubuntu18 ppc64le Dockerfile

---

test/functional/cmdLineTests/pltest/pltest_numcpus_bound.xml
test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-1.xml
test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-2.xml
test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-3.xml
test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-4.xml
test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-5.xml
test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-6.xml

- add osx in NON_WINDOWS_PLATFORMS
- remove unused variables
Fixes: #3776
[ci skip]

add osx in NON_WINDOWS_PLATFORMS

---

runtime/compiler/build/files/common.mk
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/J9Options.hpp
runtime/compiler/control/JITaaSCompilationThread.hpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/runtime/StatisticsThread.cpp
runtime/compiler/runtime/StatisticsThread.hpp

The idea is to have some sort of validation that
JITaaS is doing its job and add a thread which print
the JITaas Statistics regularly with some tunable frequency.

Health Check for Jitaas

---

doc/compiler/jitaas/Testing.md
test/docs/OpenJ9TestUserGuide.md

Add an explanation for how to get ant-contrib.jar,
as it's something people have struggled with previously

Update JITaaS testing docs

---

buildenv/jenkins/common/variables-functions

- Since we need PERSONAL_BUILD in Build jobs
Related #3863
[skip ci]

Also define PERSONAL_BUILD in Build jobs

---

buildenv/jenkins/variables/defaults.yml

Change to bootjdk11 for java11,next

---

jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/infocommands/InfoSystemCommand.java

JVM start time (milliseconds and nanoseconds) are only available if a JVM was found.

Avoid NPEs running 'info system' when no JRE is found

---

runtime/oti/j9.h
runtime/shared_common/OSCache.cpp
runtime/tests/shared/CacheDirPerm.cpp
runtime/tests/shared/CorruptCacheTest.cpp
runtime/tests/shared/OSCacheTestMmap.cpp
runtime/tests/shared/OSCacheTestSysv.cpp
runtime/tests/shared/SharedCacheAPITest.cpp
test/functional/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml

Fixes #3854 
Fixes #3882
Doc issue https://github.com/eclipse/openj9-docs/issues/149

Enable class sharing by default on all openj9 builds except OSX

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All

- OMR Promotion job
Related #3932

Add GITHUB_SERVER to build with slack function call

---

test/functional/cmdLineTests/verboseVerification/VerboseVerification.xml
test/functional/cmdLineTests/verboseVerification/build.xml
test/functional/cmdLineTests/verboseVerification/cmdlineopttest_exclude.xml
test/functional/cmdLineTests/verboseVerification/playlist.xml

Enable VerboseVerification Test

---

test/functional/VM_Test/playlist.xml

Enable jvmnativestest

---

test/functional/cmdLineTests/modularityddrtests/modularityddrtests.xml

Implement tests for the DDR command that is implemented in #3072
Requires #3350 due to variable usage

Add tests for the ddr !dumpmodules command

---

runtime/compiler/control/J9Options.cpp

The safe reserve memory value refers to JIT scratch memory allocations.
Since in JITaaS world compilations are done remotely they do not use
(much) scratch memory and therefore we could use a very low value
(even 0) for it. The user can still override this decision with an
option: -Xjit:safeReservePhysicalMemoryValue=<NNN>

Do not use a safe reserve memory value for JITaaS

---

runtime/compiler/z/codegen/J9S390CHelperLinkage.cpp

Fix a bug where HPRs are not preserved across calls built by CHelper
linkage.
All HPRs are volatiles for 32 bit SDKs. If 64-bit registers can
be used in 32-bit SDKs, the RA should be informed of 64-bit registers
that are in use and preserve them across native calls. This is achieved
by adding a KillVolHighRegs to the post dependency group of a CHelper
call.

Add extra dependency to CHelper to preserve HPRs

---

buildenv/jenkins/variables/defaults.yml

Enable openssl on JDK11 for Windows,pLinux and xLinux

---

buildenv/jenkins/variables/defaults.yml

Enable openssl on OSX for JDK8 & JDK11

---

buildenv/jenkins/variables/defaults.yml

* [skip ci]
* related ibmruntimes/openj9-openjdk-jdk11#31

Rearrange yaml file properties for osx extra_configure_options

---

buildenv/jenkins/docker-slaves/jenkinsfile-build-container

Script will build a docker image based on supplied dockerfile
and push it to dockerhub, using openj9bot user, with tags for
the build number and either the pull request ID (if pull request)
or just 'latest'

Added script to build docker images

---

jcl/src/java.base/share/classes/com/ibm/oti/vm/AbstractClassLoader.java

Also do some other minor cleanup:
- fix warnings about empty blocks
- make methods static
- add type parameter
This completes work started in 
https://github.com/eclipse/openj9/pull/4008

Remove unused definePackage()

---

buildenv/jenkins/docker-slaves/x86/centos6.9/Dockerfile

Add libXi libXrandr to Cent6 Dockerfile for jdk12+

---

test/functional/cmdLineTests/classesdbgddrext/playlist.xml

re-enable cmdLineTester_classesdbgddrext_aix

---

buildenv/jenkins/docker-slaves/jenkinsfile-build-container

Previously when building a docker container build description
was overwritten by new data, but now new data will be appended
to the build description.

Updated job build description

---

buildenv/jenkins/variables/defaults.yml

* [skip ci]
* related ibmruntimes/openj9-openjdk-jdk8#115

Add openssl support for jdk8 on osx

---

runtime/gc_base/RootScanner.hpp

Implicitly, also better handling of timestamp overflow.

Better code sharing for TGC root scan times

---

test/functional/NativeTest/playlist.xml

Temporarily excluded thrstatetest until the issue is fixed on osx

---

runtime/compiler/control/CompilationThread.cpp

Enable local AOT compilations at the client

---

runtime/compiler/arm/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/p/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/p/runtime/PPCRelocationTarget.cpp
runtime/compiler/ras/DebugExt.cpp
runtime/compiler/runtime/RelocationRecord.cpp
runtime/compiler/runtime/RelocationRecord.hpp
runtime/compiler/runtime/Runtime.cpp
runtime/compiler/x/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/z/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/z/codegen/S390AOTRelocation.cpp

https://github.com/eclipse/openj9/issues/3031
This PR consolidates a few Relocation Records, removing code duplication. It is the first of several PRs.

Consolidate Relocation Records

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/ModularityHelper.java

Also fix spelling of 'outputter'.

Remove unused import

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All
buildenv/jenkins/variables/defaults.yml

Add support for jdk12 to pipeline variables

---

buildenv/jenkins/docker-slaves/README.md

Added readme to describe docker files/containers,
how to use them from a terminal or jenkins, and how
to use the docker jobs on eclipse to generate containers.
[skip ci]

Added Docker README

---

runtime/compiler/control/CompilationThread.cpp

Fix local AOT compilation bug

---

test/functional/JLM_Tests/playlist.xml

remove -Xdump:none and add verbosegclog for all SoftMx tests

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

The indirect load, loading J9Class from the object, generated for rdbar
and wrtbar can cause NPE and needs a GC map.

Add GC map for loading J9Class for rd/wrtbar

---

runtime/compiler/control/CompilationThread.cpp

Some recently introduced AOT heuristic makes some test to fail on PPC.
This is likely due to an existing AOT bug on PPC. Until we figure the
reason, we should backout this change on PPC only.

Backout AOT heuristic on PPC

---

runtime/compiler/optimizer/J9SimplifierHandlers.cpp

There isn't a late clean folding pass anymore.  The Option flag is always
false, so remove and fold surrounding code assuming it is false.

Eliminate enableLateCleanFolding Option flag

---

buildenv/jenkins/common/variables-functions
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All

Move get_specs() method to variables-functions
[ci skip]

Reformat Pipeline-Build-Test-All

---

runtime/compiler/control/CompilationThread.cpp

In stopcompilationthread the dummy message is send to server
for cleaning the client data session. If the server is killed
before that the dummy messagei, send will fail and an exception
is generated. Adding the catch for the exception in the
stopcompilationThread to avoid crash.

Fix for client crash when killing server

---

jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
runtime/vm/MHInterpreter.cpp

Throw ClassCastException for Byte to char during invocation

---

buildenv/jenkins/variables/defaults.yml

Doc issue https://github.com/eclipse/openj9-docs/issues/191

Switch Linux platforms to compile with gcc 7

---

test/functional/cmdline_options_testresources/src/VMBench/GPTests/GPTest.java

Remove out of date "Source Control Header" comment

---

doc/processes/labels.md

Add `depends:infra` and jdk12 related labels

---

jcl/src/java.base/share/classes/java/lang/String.java

The class `StringSpliteratorOfInt` worked fine for `chars()`, but not for `codePoints()` which must deal with the pairing of characters to form single code points. That class was removed in favour of using helper classes from `StringLatin1` and `StringUTF16`.
Also:
* use `Character.isHighSurrogate()` and `Character.isLowSurrogate()` to detect surrogate characters
* use `Character.toCodePoint()` to combine surrogates into code points
* fix tests: `((i + 1) < len)` can fail where `(i < (len - 1))` won't as long as `(len >= 0)`
Fixes: #4301

Fix implementation of String.codePoints()

---

runtime/j9vm/j8vmi.c

Change the native to safely copy the memory using memmove, then flip
all the elements in the destination. Fix the primitive array case to
remove the Unsafe.arrayBaseOffset() added by the java caller.
Related: #4312
[ci skip]

Fixes for JVM_CopySwapMemory

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/p/codegen/J9PPCInstruction.cpp
runtime/compiler/p/codegen/J9PPCSnippet.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/ras/DebugExt.cpp
runtime/compiler/runtime/MetaData.cpp
runtime/compiler/x/codegen/CallSnippet.cpp
runtime/compiler/x/codegen/J9CodeGenerator.cpp

* Use CodeGenerator CodeCache functions
* Use NumReservedIPICTrampoline getter/setters from CodeGenerator

Misc. CodeCache and Trampoline cleanup

---

runtime/compiler/env/VMJ9Server.hpp

Add TR_J9SharedCacheVM declarations

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp

The notification code has caused a start up regression, turn it off.

Turn off Unsafe illegal write notification

---

runtime/tests/gp/gptest.c

Use a non-unity dividend in the test to prevent clang from optimizing out the
hardware divide instruction. See
https://github.com/eclipse/openj9/issues/3789#issuecomment-456443740
Fixes (partly) issue #3789.
Also delete some legacy code that is always ifdef'ed out.

Fix Java_VMBench_GPTests_GPTest_gpHardwareFloat

---

test/functional/cmdLineTests/openssl/build.xml
test/functional/cmdLineTests/openssl/openssl.xml
test/functional/cmdLineTests/openssl/playlist.xml
test/functional/cmdLineTests/openssl/src/org/openj9/test/openssl/CryptoTest.java

add cmdLineTester_CryptoTest for OpenSSL

---

test/functional/Java8andUp/playlist.xml
test/functional/cmdLineTests/openssl/playlist.xml

Restrict from running against IBM implementations
[ci skip]

Only run openssl test on openj9 impl

---

buildspecs/j9.build-info

Update FIPS level for zOS

---

runtime/port/common/j9prt.tdf
runtime/port/win32/j9shmem.c

Include the error code into Trc_PRT_shmem_j9shmem_stat_Exit2_V2

---

runtime/compiler/runtime/SignalHandler.c

Update JIT to match https://github.com/eclipse/omr/pull/3509.

Fix read of FPC register

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/CompilationThread.hpp
runtime/compiler/control/JITaaSCompilationThread.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.hpp

JITaaS remote AOT is by default disabled. To enable it, set environment variable "TR_EnableJITaaSRemoteAOT" to 1.
Issue: #4401 
[skip ci]

Initial setup for JITaaS remote AOT

---

buildenv/docker/jdk11/aarch64_CC/arm-linux-aarch64/Dockerfile

This commit adds a Dockerfile for cross-compiling for AArch64.

AArch64: Dockerfile for JDK11

---

runtime/compiler/env/VMJ9.cpp

Fix TR_Assert typo in TR_J9VMBase::get

---

runtime/vm/gphandle.c

Update JIT to match eclipse/omr#3509 and fix an additional spot missed in #4477.

Fix read of FPC register for z/OS -XCEEHDLR

---

runtime/compiler/runtime/RelocationRuntime.hpp

TR_SharedCacheJITaaSRelocationRuntime is drived from TR_JITaaSRelocationRuntime

Initial implementation of TR_SharedCacheJITaaSRelocationRuntime

---

jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/LogCommand.java

* print the intended message rather than throw a NullPointerException

Fix jdmpview check for valid logger name

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/runtime/RelocationRecord.cpp
runtime/compiler/x/codegen/X86PrivateLinkage.cpp

Patches to enable direct calls and profiled devirtualization in JITaaS mode, along with a miscellaneous bug fix.

Implement direct calls in JITaaS mode

---

runtime/compiler/env/j9methodServer.hpp

TR_ResolvedRelocatableJ9JITaaSServerMethod is drived from TR_ResolvedJ9JITaaSServerMethod

Initial implementation of TR_ResolvedRelocatableJ9JITaaSServerMethod

---

runtime/compiler/z/codegen/J9TreeEvaluator.cpp

Update New object allocation inlining to add relocation under SVM if it is enabled.

Update relocation for Object Allocation inlining

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp

Function implementation for the TR_J9SharedCacheServerVM class

---

doc/release-notes/0.12/0.12.1.md

New topic in the 0.12 release folder to
cover the notable change for 0.12.1 and
to record it as an issue in the table.

Add release notes for 0.12.1

---

jcl/src/java.base/share/classes/java/lang/Access.java

Perhaps this should have been included in #4563 with the removal of the conditional return type.

Fold opening of getBootLayer() onto a single line

---

runtime/compiler/build/rules/win-msvc/helper_macro.mk

The list of commands isn't valuable (it's absent on other platforms).

Suppress echoing commands to build file list on Windows

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

Evacuate Top is null when CS is inactive, and non-null otherwise;
therefore, J9_PRIVATE_FLAGS_CONCURRENT_SCAVENGER_ACTIVE can be
deprecated.

Use evacuate top to check if CS is active on X86

---

buildenv/jenkins/common/build

Add compression option when archiving test natives in Jenkins build

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp

Implement TR_J9SharedCacheServerVM::getMethodFromClass

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp

Implement TR_J9SharedCacheServerVM::isPublicClass

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp

Implement TR_J9SharedCacheServerVM::isInstanceOf

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp

Implement TR_J9SharedCacheServerVM::supportAllocationInlining

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp

Implement TR_J9SharedCacheServerVM::getClassFromSignature

---

runtime/compiler/env/j9methodServer.cpp
runtime/compiler/env/j9methodServer.hpp

[skip ci]
Signed-off-by: Dmitry Ten <Dmitry.Ten@ibm.com>

Implement storeValidationRecordIfNecessary for JITaaS

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp

Implement TR_J9SharedCacheServerVM::getSystemClassFromClassName

---

runtime/nls/shrc/j9shr.nls
runtime/oti/j9port.h
runtime/port/sysvipc/j9sharedhelper.h
runtime/port/win32/j9shsem.c
runtime/port/win32/j9shsem_deprecated.c
runtime/shared_common/CacheLifecycleManager.cpp
runtime/shared_common/OSCache.cpp
runtime/shared_common/OSCachesysv.cpp
runtime/shared_common/j9shr.tdf
runtime/shared_common/shrinit.cpp

Reverts eclipse/openj9#4532
as per https://github.com/eclipse/openj9/issues/4614#issuecomment-461216574

Revert "Make sure the cache file path is shorter than the OS limit"

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp

Implement TR_J9SharedCacheServerVM::getProfiledClassFromProfiledInfo

---

runtime/j9vm/java11vmi.c
runtime/j9vm/jvm.c
runtime/jcl/common/jclcinit.c
runtime/jcl/common/system.c
runtime/jvmti/jvmtiModules.c
runtime/oti/j2sever.h
runtime/util/modularityHelper.c
runtime/vm/classloadersearch.c

* remove J2SE_SHAPE_B136, J2SE_SHAPE_B148
* replace J2SE_SHAPE_B165 with J2SE_SHAPE_V9

Remove dead code for obsolete Java 9 'shapes'

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp

Implement TR_J9SharedCacheServerVM::hasFinalizer

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp

Implement TR_J9SharedCacheServerVM::getClassDepthAndFlagsValue

---

runtime/compiler/env/j9methodServer.cpp
runtime/compiler/env/j9methodServer.hpp

Signed-off-by: Dmitry Ten <Dmitry.Ten@ibm.com>

Implemented TR_ResolvedRelocatableJ9JITaaSServerMethod::isInterpreted()

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp

Implement TR_J9SharedCacheServerVM::isPrimitiveClass

---

runtime/compiler/env/VMJ9Server.hpp

WIP: Implement TR_J9SharedCacheServerVM::isGetImplInliningSupported

---

runtime/compiler/env/VMJ9Server.cpp

Avoid TR::comp() in TR_J9SharedCacheServerVM

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp

Implement TR_J9SharedCacheServerVM::getComponentClassFromArrayClass

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp

Implement TR_J9SharedCacheServerVM::getArrayClassFromComponentClass

---

runtime/gc_glue_java/CMakeLists.txt
runtime/gc_glue_java/MetronomeAlarmThreadDelegate.cpp
runtime/gc_glue_java/MetronomeAlarmThreadDelegate.hpp
runtime/gc_realtime/MetronomeAlarmThread.cpp
runtime/gc_realtime/MetronomeAlarmThread.hpp

Modify MetronomeAlarmThread for moving into OMR

---

runtime/compiler/env/j9methodServer.hpp

Function implementation for TR_ResolvedRelocatableJ9JITaaSServerMethod
Issue: #4401

Function implementation for TR_ResolvedRelocatableJ9JITaaSServerMethod

---

runtime/compiler/env/VMJ9Server.hpp

Implement TR_J9SharedCacheServerVM::getMethodFromName

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp

Implement TR_J9SharedCacheServerVM::getLeafComponentClassFromArrayClass

---

runtime/gc_glue_java/MetronomeAlarmThreadDelegate.cpp
runtime/gc_realtime/MetronomeAlarmThread.hpp

Fixing compilation warning and typo

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp

Implement TR_J9SharedCacheServerVM::getBaseComponentClass

---

runtime/shared_common/CacheMap.cpp
runtime/shared_common/CacheMap.hpp
runtime/tests/shared/ProtectNewROMClassDataTests.cpp
runtime/tests/shared/ProtectSharedCacheDataTests.cpp

Add assertions for the UTF8 SRPs of J9ROMClass

---

test/functional/Java8andUp/src/org/openj9/test/java/security/DigestLoop.java
test/functional/Java8andUp/testng.xml

Add DigestLoop test class

---

runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp

Implement TR_J9SharedCacheServerVM::getClassFromNewArrayType

---

runtime/compiler/runtime/RelocationRuntime.hpp

Remove TR_SharedCacheJITaaSRelocationRuntime and add asserts

---

runtime/compiler/env/j9methodServer.cpp
runtime/compiler/env/j9methodServer.hpp

Implement methods in TR_ResolvedRelocatableJ9JITaaSServerMethod
Issue: 4401

Implement methods in TR_ResolvedRelocatableJ9JITaaSServerMethod

---

buildspecs/linux_aarch64_cmprssptrs.spec
runtime/gc_glue_java/configure_includes/configure_linux_aarch64.mk

This commit adds a buildspec for aarch64 compressed references.

AArch64: Add buildspec for compressed references

---

runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h

Remove deprecated FrontEnd indexedTrampolineLookup function

---

doc/compiler/aot/SymbolValidationManager.md

[ci-skip]
Signed-off-by: Irwin D'Souza <dsouzai@ca.ibm.com>

Add further SVM documentation

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/JITaaSCompilationThread.cpp

Add J9HookVMDynamicCodeLoad for JITaaS remote AOT relocation

---

runtime/util/hshelp.c

Remove unused local.
[ci skip]

Fix windows compile error

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/runtime/J9Runtime.hpp
runtime/compiler/runtime/RelocationRecord.cpp

Add AOT Stats When Well Known Classes Validation Fails
Closes: #4833

Add AOT Stats When Well Known Classes Validation Fails

---

runtime/compiler/env/j9methodServer.cpp
runtime/compiler/env/j9methodServer.hpp

Functions implemented for TR_ResolvedRelocatableJ9JITaaSServerMethod

---

runtime/compiler/control/JITaaSCompilationThread.cpp
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/rpc/protos/compile.proto

Implement all methods related to storing/retrieving thunks:
getJ2IThunk
setJ2IThunk
persistJ2IThunk
persistThunk
findPersistentThunk

Implemented TR_J9SharedCacheVM methods

---

runtime/compiler/env/j9methodServer.cpp
runtime/compiler/env/j9methodServer.hpp

Implement:
getDeclaringClassFromFieldOrStatic
fieldOrStaticNameChars

Implement remaining methods of TR_ResolvedRelocatableJ9JITaaSServerMethod

---

buildenv/jenkins/README.md

Clarify that the signedOff by check is Extensions-only

---

jcl/jpp_configuration.xml

Remove unused specifications, relocate the flags they define.
Fixes https://github.com/eclipse/openj9/issues/4800

Clean up jpp_configurations.xml

---

runtime/vm/MHInterpreter.cpp

- Eliminates an extra memcpy in foldArguments MethodHandle calls
- Makes code easier to understand - reason for copying is to make stack compatible with insertPlaceHolderFrame
@DanHeidinga as discussed previously for #3980 

Refactor fold native MHInterpreter

---

runtime/oti/VMHelpers.hpp

Remove referencese to Multi-Tenant isolated classes

---

buildspecs/j9.build-info

Update buildspec to use updated Fips libraries

---

runtime/compiler/ilgen/Walker.cpp

In 3b2830ef `genInvokeVirtual()` was modified to detect resolved private methods for nestmates. If a private method is found, it generates a direct call, and otherwise (including when the method reference is unresolved) it generates a virtual call. In order to generate a virtual call, it queries the constant pool a second time, and if the constant pool entry was originally unresolved, it might have become resolved since. In this case, ilgen could fail to identify for a resolved call that the called method is final, and generate an indirect instead of a direct call. Normally it's harmless for the call to be indirect, but there are a number of final methods recognized by the JIT compiler that undergo transformations assuming that calls to them are direct.
To prevent this problem, …

Ensure resolved final methods are called directly

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All

Add summary badge to show the downstream pipelines status for current
run. Require Groovy Postbuild plugin.
[ci skip]

Add downstream jobs status to Jenkins Pipeline-Build-Test-All

---

test/TestConfig/run_configure.mk
test/TestConfig/settings.mk

Temporarily support for JAVA_VERSION=SE130

---

runtime/compiler/arm/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/p/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/x/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/z/codegen/J9AheadOfTimeCompile.cpp

https://github.com/eclipse/openj9/issues/4803

Consolidate AOT Relocation Records

---

runtime/vm/BytecodeInterpreter.hpp

delivered to master: https://github.com/eclipse/openj9/pull/4946

0.13: Wrap Class.arrayTypeImpl in native frame

---

doc/release-notes/0.13/0.13.md

Created a new release note, with work in progress
for milestone 1.
[ci skip]

Release notes for 0.13.0 milestone 1

---

runtime/compiler/build/files/host/aarch64.mk
runtime/compiler/build/files/target/aarch64.mk
runtime/compiler/build/platform/host/aarch64-linux-gcc.mk
runtime/compiler/build/toolcfg/host/aarch64.mk
runtime/compiler/build/toolcfg/target/aarch64.mk
runtime/compiler/compiler.mk
runtime/compiler/makefile.ftl

This commit adds files for building AArch64 JIT.

AArch64: Add files for building AArch64 JIT

---

test/.gitignore
test/TestConfig/envSettings.mk
test/TestConfig/makeGen.mk
test/TestConfig/run_configure.mk
test/TestConfig/settings.mk
test/TestConfig/src/build_envInfo.xml
test/TestConfig/src/org/openj9/envInfo/EnvDetector.java
test/TestConfig/src/org/openj9/envInfo/JavaInfo.java

Add support for AUTO_DETECT for JDK_VERSION, JDK_IMPL and SPEC

---

buildenv/jenkins/common/variables-functions

Add check for options per spec.
[ci skip]

Fix NPE for extra_getsource_options

---

test/README.md
test/docs/OpenJ9TestUserGuide.md

Added AUTO_DETECT part in readme

---

runtime/compiler/optimizer/EscapeAnalysis.cpp

The pattern used to match an inline finalizable test might be incorrect in 64-bit mode as tree simplification might result in 32-bit operations being used.  This change accounts for that possibility by checking whether an `l2i` was applied to the result of the load of `isClassAndDepthFlags`, and checks for 32-bit operations accordingly.
Fixes:  Issue #4885

Revise tree pattern used to match inline finalizable test

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp

When the IL has two JNI calls to the same method it's possible for the 1st
call to be devirtulized and the 2nd to be left as an indirect call.
Setting the method symbol's linkage to JNI would be incorrect for the
upcoming indirect call using the same method symbol so we must not
set the linkage to JNI!

Don't set JNI symbol's linkage to TR_JNILinkage in directCallEvaluator()

---

test/TestConfig/resources/excludes/latest_exclude_13.txt
test/functional/cmdLineTests/jvmtitests/jvmtitests_excludes_13.xml

- copied from JDK12 excludes
Issue: #4999
[ci skip]

Add exclude files for JDK13

---

.github/ISSUE_TEMPLATE/generic.md
.github/ISSUE_TEMPLATE/test-suite-failure.md
.github/ISSUE_TEMPLATE/user-problem.md

Create some issue templates for test failures and user problems

---

test/TestConfig/openj9Settings.mk

Remove unwanted quotes in `TEST_LIB_PATH_VALUE`.

Fix quoting of LD_LIBRARY_PATH

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/JITaaSCompilationThread.cpp

Refactor storing of AOT in SCC

---

runtime/gc_realtime/AllocationContextRealtime.cpp
runtime/gc_realtime/AllocationContextRealtime.hpp

Modify AllocationContextRealtime for moving into OMR

---

runtime/gc_realtime/IncrementalOverflow.cpp
runtime/gc_realtime/IncrementalOverflow.hpp

Modify IncrementalOverflow for moving into OMR

---

test/TestConfig/envSettings.mk
test/TestConfig/run_configure.mk
test/docs/OpenJ9TestUserGuide.md

Changed AUTO_DETECT variable from on/off into true/false

---

runtime/gc_realtime/IncrementalParallelTask.cpp
runtime/gc_realtime/IncrementalParallelTask.hpp

Modify IncrementalParallelTask for moving to OMR

---

runtime/vm/createramclass.cpp

The iTable building code was considering all methods in the interface
class, not just the ones that are appropriate for the iTable. This
results in an incorrect iTable shape (and very possibly writing off the
end of the allocated iTable chunk).
Process only methods from the interface which make up the interface
contract (public methods that appear in the vTable).
[ci skip]

(0.13) Fix incorrect iTable build

---

runtime/gc/CMakeLists.txt
runtime/gc_glue_java/CMakeLists.txt
runtime/gc_glue_java/RealtimeGCDelegate.cpp
runtime/gc_glue_java/RealtimeGCDelegate.hpp
runtime/gc_glue_java/StaccatoGCDelegate.cpp
runtime/gc_glue_java/StaccatoGCDelegate.hpp
runtime/gc_realtime/RealtimeAccessBarrier.cpp
runtime/gc_realtime/RealtimeGC.cpp
runtime/gc_realtime/RealtimeGC.hpp
runtime/gc_realtime/RealtimeMarkingScheme.cpp
runtime/gc_staccato/StaccatoAccessBarrier.cpp
runtime/gc_staccato/StaccatoGC.cpp

Modify RealtimeGC for moving into OMR

---

runtime/gc_realtime/OSInterface.cpp
runtime/gc_realtime/OSInterface.hpp

Modify OSInterface for moving into OMR

---

test/TestConfig/src/org/openj9/envInfo/JavaInfo.java

Modified AUTO_DETECT using java.vm.name

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/JITaaSCompilationThread.cpp

Refactor CompilationEnd and remoteCompilationEnd

---

runtime/gc_realtime/ProcessorInfo.cpp
runtime/gc_realtime/ProcessorInfo.hpp

Modify Metronome ProcessorInfo for moving into OMR

---

runtime/gc_realtime/SweepSchemeRealtime.cpp
runtime/gc_realtime/SweepSchemeRealtime.hpp

Modify SweepSchemeRealtime for moving to OMR

---

runtime/gc_realtime/Timer.cpp
runtime/gc_realtime/Timer.hpp

Modify metronome Timer for moving to OMR

---

runtime/gc_realtime/UtilizationTracker.cpp
runtime/gc_realtime/UtilizationTracker.hpp

Modify UtilizationTracker for moving to OMR

---

runtime/shared_common/CompositeCache.cpp

Fix tabs vs spaces issues to improve readability

---

buildenv/jenkins/docker-slaves/ppc64le/centos7/Dockerfile
buildenv/jenkins/docker-slaves/s390x/ubuntu16/Dockerfile
buildenv/jenkins/docker-slaves/x86/centos6.9/Dockerfile

Update cmake to 3.11.4 on the Docker containers

---

runtime/gc_realtime/YieldCollaborator.cpp
runtime/gc_realtime/YieldCollaborator.hpp

Modify YieldCollaborator for moving to OMR

---

runtime/gc_realtime/WorkPacketsRealtime.cpp

Modify WorkPacketsRealtime for moving into OMR

---

jcl/src/java.base/share/classes/java/lang/invoke/MethodHandle.java

Remove unused native and fix tabs vs spaces

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/J9S390PrivateLinkage.cpp

Remove opcodes -
- iucall
- iucalli
- lucall
- lucalli
https://github.com/eclipse/omr/issues/2657
Signed-off-by: Somesh Sharma <someshsharma0312@gmail.com>

Remove deprecated Call/Return IL Opcodes

---

.github/ISSUE_TEMPLATE/test-suite-failure.md

For a test regressions, ask for last passing / first failing SHAs.
[ci skip]

Update the test-suite-failure issue template

---

jcl/src/java.base/share/classes/java/lang/String.java

This commit fixes a bug in String.indexOf(String) API where certain optimal
paths (intrinsics that can be hardware accelerated) can never be reached. 
As a result of this, the String.indexOf(string) API always defaults to the sub-optimal
string search logic.
This applies to both compact and non-compact string modes.

Make String.indexOf(String) handle compact strings correctly

---

runtime/redirector/module.xml

Remove reference to libdl.a on z/OS

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/VmCheckCommand.java
runtime/vmchk/checkinterntable.c

It's possible the VM has not had to construct a `ROMClassBuilder` because, with a shared class cache, all classes loaded thus far have been found in the cache.
Update DDR `!vmcheck` command to check `thread.inNative` before considering a thread to have VM access.
Fixes: #5175

Add checks that romClassBuilder is not NULL

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/LoggingMXBeanImpl.java
jcl/src/java.management/share/classes/java/lang/management/DefaultPlatformMBeanProvider.java
jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/PlatformMBeanProvider.java
jcl/src/jdk.management/share/classes/openj9/lang/management/internal/OpenJ9DiagnosticsMXBeanImpl.java

Remove ifdefs which select betweenn Java 9 Build 148 and OpenJ9

Remove references to Java 9 Build 148

---

runtime/compiler/env/VMJ9Server.cpp

Array class of RAM class can be initialized
when the class is already loaded, so it is not
safe to cache NULL as array class.
Only cache non-NULL values, make remote call otherwise.
If a remote call returns non-NULL, it means that array
class has been initiailized. It should not change anymore
so it's safe to cache it.
Fixes: #5124

Do not cache array class of RAM class
