buildenv/jenkins/variables/defaults.yml

- This will enable builds to push to Artifactory
Issue #2637
Related #5146 
[skip ci]

Add Artifactory details for Eclipse OpenJ9 Jenkins

---

runtime/gc_base/GCExtensions.cpp

Destroy idleGCManager at tear down

---

test/TestConfig/settings.mk

- export JAVA_HOME=JDK_HOME
[ci skip]

Export JAVA_HOME in TestKitGen

---

buildenv/jenkins/common/build

Add SDK and Testlib Artifactory URLs to description

---

runtime/gc_glue_java/configure_includes/configure_aix_ppc.mk
runtime/gc_glue_java/configure_includes/configure_linux_390.mk
runtime/gc_glue_java/configure_includes/configure_linux_ppc.mk
runtime/gc_glue_java/configure_includes/configure_linux_x86.mk
runtime/gc_glue_java/configure_includes/configure_win_x86.mk
runtime/gc_glue_java/configure_includes/configure_zos_390.mk.ftl
runtime/makelib/mkconstants.mk.ftl
runtime/makelib/targets.mk.ftl

Remove unnecessary UMA_SP_CFLAGS, and the _sp SPECs from gc_glue_java

---

buildenv/jenkins/common/build

Fix missing +

---

test/README.md
test/TestConfig/playlist.xsd
test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl
test/TestConfig/scripts/testKitGen/testKitGen.pl
test/docs/OpenJ9TestUserGuide.md
test/functional/NativeTest/playlist.xml

- added type in the playlist.xml parsing and make generating logic
- updated target counting logic
- updated documentations
- updated playlist.xsd
- update NativeTest playlist.xml
[ci skip]

Support tagging test with type

---

runtime/gc_glue_java/CMakeLists.txt
runtime/gc_glue_java/MemorySubSpaceMetronomeDelegate.cpp
runtime/gc_glue_java/MemorySubSpaceMetronomeDelegate.hpp
runtime/gc_realtime/MemorySubSpaceMetronome.cpp
runtime/gc_realtime/MemorySubSpaceMetronome.hpp

Modify MemorySubSpaceMetronome for moving to OMR

---

runtime/gc_glue_java/MetronomeAlarmThreadDelegate.cpp
runtime/gc_realtime/EnvironmentRealtime.cpp
runtime/gc_realtime/EnvironmentRealtime.hpp
runtime/gc_realtime/MetronomeAlarmThread.hpp
runtime/gc_realtime/RealtimeAccessBarrier.cpp
runtime/gc_realtime/RealtimeGC.cpp
runtime/gc_realtime/RealtimeMarkingScheme.cpp
runtime/gc_realtime/RealtimeRootScanner.cpp
runtime/gc_realtime/RealtimeSweepTask.cpp
runtime/gc_staccato/StaccatoAccessBarrier.cpp

Modify EnvironmentRealtime for moving into OMR

---

runtime/cmake/J9vmGenAsm.cmake

CMake: Add windows support for m4 generated assembly

---

runtime/gc_modron_standard/StandardAccessBarrier.cpp

Monitor table is weak (clearable) root and Read Barrier should not copy
objects, since info if objects is live or not is not known in a middle
of a GC cycle. The barrier only needs to update the reference slot if
object happened to be already copied.
For API with vmThread provided, also impose the assert that object is
already copied, which is true for typical synchronizing object
(vmThread->blockingEnterObject). The other API with VM provided should
be used when accessing random monitor table slots with unknown liveness
info.

Don't copy monitor object in Read Barrier

---

runtime/gc_glue_java/RealtimeGCDelegate.cpp
runtime/gc_glue_java/StaccatoGCDelegate.cpp
runtime/gc_glue_java/StaccatoGCDelegate.hpp
runtime/gc_realtime/RealtimeGC.hpp
runtime/gc_staccato/StaccatoGC.cpp
runtime/gc_staccato/StaccatoGC.hpp

Remove MM_RealtimeAccessBarrier from files moving to OMR

---

runtime/gc_glue_java/RealtimeGCDelegate.cpp
runtime/gc_glue_java/RealtimeGCDelegate.hpp
runtime/gc_modron_startup/mminit.cpp
runtime/gc_realtime/ConfigurationRealtime.cpp
runtime/gc_realtime/ConfigurationRealtime.hpp

Modify ConfigurationRealtime for moving into OMR

---

doc/compiler/jitaas/Build.md

Update JITaaS docs on building the JIT

---

runtime/compiler/control/JITaaSCompilationThread.cpp
runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/rpc/protos/compile.proto

Add JITaaS remote support to classHasIllegalStaticFinalModification

---

runtime/CMakeLists.txt

CMake: Enable ASM_MASM on windows

---

runtime/util/CMakeLists.txt

CMake: add windows support to j9util

---

runtime/libffi/CMakeLists.txt

CMake: Update libffi to support windows

---

runtime/compiler/arm/codegen/TreeEvaluatorTable.hpp
runtime/compiler/il/ILOpCodeProperties.hpp
runtime/compiler/il/ILProps.hpp
runtime/compiler/p/codegen/TreeEvaluatorTable.hpp
runtime/compiler/x/amd64/codegen/TreeEvaluatorTable.hpp
runtime/compiler/x/i386/codegen/TreeEvaluatorTable.hpp
runtime/compiler/z/codegen/TreeEvaluatorTable.hpp

Use renamed headers in the compiler

---

runtime/gc_realtime/CMakeLists.txt

CMake: On windows link j9realtime against winmm.lib

---

runtime/compiler/control/JITaaSCompilationThread.cpp

Fix NULL metaData pointer in verbose log

---

test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java

Steps:
The test creates 2 VT objects
The test creates a flatenned array with the VT class
The test adds the 2 VT objects to the array and check if they are added correctly
Related #5021
Signed-off-by: Aidan Ha <qbha@edu.uwaterloo.ca>

Add test for flatenned ValueType arrays

---

runtime/bcutil/ROMClassBuilder.cpp
runtime/bcutil/ROMClassWriter.cpp
runtime/shared_common/SCImplementedAPI.cpp

Round up romClassMinimalSize to sizeof(U_64).

---

buildenv/docker/jdk8/x86_64/ubuntu18/jitaas/build/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu18/jitaas/test/Dockerfile
doc/compiler/jitaas/Docker.md

Update JITaaS Dockerfiles and guidelines

---

runtime/gc_ddr/gcddrstructs.properties

That directory was removed via #5327.

Remove reference to gc_staccato which no longer exists

---

buildenv/jenkins/ARTIFACTORY.md

Add Artifactory Install and Configure Documentation

---

test/functional/TestUtilities/src/org/openj9/test/util/PlatformInfo.java

@pshipton and @JasonFengJ9 would you kindly review this too?
[ci skip]

Add utility method to check if we are running on OpenJ9

---

runtime/compiler/runtime/Runtime.cpp

There have been recent crashes in getEnv2 on OSX.  Reviewing the
code indicated a potential use of null pointer if the allocation
failed.
Fixed the use of the null pointer and cleaned up the allocation
in the case where the subsequent getEnv failed.
Related: #5061

Address potential null dereference & memory leak in getEnv2

---

doc/compiler/jitaas/Docker.md

Add a demo on building JITaaS using Dockerfile

---

buildenv/jenkins/common/variables-functions
buildenv/jenkins/jobs/infrastructure/artifactory_cleanup.groovy
buildenv/jenkins/variables/defaults.yml

This will make sure that we are not using too much space on the server
This will clean up jobs based on the number of Builds in a folder
Or how old the build is
This script utilized the rest api for Artifactory to check and delete builds
[skip ci]

Adding an Artifactory cleanup script

---

test/.gitignore
test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl

- generate a separate makefile to store common target dependencies
[ci skip]

Reduce the generated file size of TestKitGen

---

runtime/cmake/caches/linux_x86-64_cmprssptrs.cmake

CMake: Stop forcing the values of the compilers

---

debugtools/DDR_VM/src/com/ibm/j9ddr/StructureHeader.java

The expression to compute the fourth byte was wrong.

Fix decomposition of blob version

---

test/functional/JIT_Test/playlist.xml
test/functional/JLM_Tests/playlist.xml
test/functional/Java8andUp/playlist.xml
test/functional/SharedCPEntryInvokerTests/playlist.xml
test/functional/VM_Test/playlist.xml
test/functional/cmdLineTests/dumpromtests/playlist.xml
test/functional/cmdLineTests/gptest/playlist.xml
test/functional/cmdLineTests/jep178staticLinkingTest/playlist.xml
test/functional/cmdLineTests/jvmtitests/playlist.xml
test/functional/cmdLineTests/lazyClassLoadingTest/playlist.xml
test/functional/cmdLineTests/pltest/playlist.xml
test/functional/cmdLineTests/vmRuntimeState/playlist.xml
test/functional/cmdLineTests/xcheckjni/playlist.xml

Add tag for native tests

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All

Parameterize timeout period and always show downstream jobs status.
[ci skip]

Summary badge not shown when the pipeline times out

---

doc/release-notes/0.14/0.14.md

Reword release notes for jps and jstack for consistency and clarity

---

runtime/CMakeLists.txt

CMake: Propagate missing dependencies to omrcore

---

runtime/vm/jvminit.c

Currently, Openj9 breaks legacy applications running JVM from C++ with empty VM options, providing the error message: JVMJ9VM007E Command-line option unrecognised.
Instead, these empty options should be ignored, to match the RI behaviour.
Fixes: #5332. 
Note: this PR addresses ignoring options that are empty or all whitespace, but continues to reject ASCII characters beyond 0x7F.
Signed-off-by: Sharon Wang <sharon-wang-cpsc@outlook.com>

Ignore empty and whitespace VM options

---

test/TestConfig/src/build_envInfo.xml
test/TestConfig/src/org/openj9/envInfo/EnvDetector.java
test/TestConfig/src/org/openj9/envInfo/JavaInfo.java
test/TestConfig/src/org/openj9/envInfo/MachineInfo.java

The program takes two flags:
- `JavaInfo` for AUTO_DETECT
- `MachineInfo` for getting machine information (i.e., uname, cores, memory, disk space, etc)
[ci skip]

Add machine info detection

---

runtime/vm/jvminit.c

Cherry-picked from PR: https://github.com/eclipse/openj9/pull/5353
Fixes: #5332 
Currently, Openj9 breaks legacy applications running JVM from C++ with empty VM options, providing the error message: JVMJ9VM007E Command-line option unrecognised.
Instead, these empty options should be ignored, to match the RI behaviour.
Signed-off-by: Sharon Wang <sharon-wang-cpsc@outlook.com>

(v0.14.0) Ignore empty and whitespace VM options

---

buildenv/jenkins/docker-slaves/ppc64le/centos7/Dockerfile
buildenv/jenkins/docker-slaves/s390x/ubuntu16/Dockerfile
buildenv/jenkins/docker-slaves/x86/centos6.9/Dockerfile

Adding JDK12 to the docker containers to build jdk13

---

buildenv/docker/jdk8/x86_64/ubuntu16/jitaas/build/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu16/jitaas/test/Dockerfile

Fix JITaaS Dockerfile for Ubuntu16

---

runtime/vm/createramclass.cpp

Cast 1 to uint64_t
Fixes GH-5161
Signed-off-by: Aidan Ha <qbha@edu.uwaterloo.ca>

Fix Compile warning on Windows for SET_STRIDE

---

test/functional/DDR_Test/playlist.xml

Enable testDDRExt_General on zos

---

test/TestConfig/scripts/testKitGen/makeGenTool/modesService.pl

- update warning message when modes service is not accessible
[ci skip]

Update warning message from modes service

---

test/functional/Java8andUp/src/org/openj9/test/java/security/DigestLoop.java
test/functional/Java8andUp/src/org/openj9/test/java/security/OpenSSLInvalidCBCKeySizeTest.java
test/functional/Java8andUp/src/org/openj9/test/java/security/OpenSSLInvalidGCMKeySizeTest.java

Signed-off-by: Jerry Lui <jerrylui@ibm.com>

Fix testCBC and testGCM compatibility with IBM Java

---

test/functional/DDR_Test/src/j9vm/test/ddrext/Constants.java
test/functional/DDR_Test/src/j9vm/test/ddrext/junit/TestSharedClassesExt.java

Modified ddr test key

---

runtime/compiler/x/amd64/codegen/AMD64JNILinkage.cpp

1. Use the sign-extended byte version instruction when possible;
2. Eliminated the need of scratch registers for checkForJNIExceptions
and cleanupJNIRefPool.

Optimized JNI linkage on X86-64

---

buildenv/jenkins/variables/defaults.yml

Change Windows Openssl location to match playbooks

---

runtime/vm/VMAccess.cpp

Trigger the hook before handling for exclusive VM access (possible
notification that exclusive access has been acquired). If called after
the notification, then a party that requested exclusive VM access could
run and race the hook, and the hook could occur after the party
performed the action that could be interested in the hook trigger.
It also makes the code sequence more symmetrical to the one in VM access
acquire:
- in acquire: exclusive VM access handling, invoke hook and then set
thread VM access bit
- in release: reset VM access bit, invoke hook, then exclusive VM access
handling
Fixes https://github.com/eclipse/openj9/issues/5389

Trigger release VM Access hook earlier

---

runtime/compiler/z/runtime/PicBuilder.m4
runtime/compiler/z/runtime/Recompilation.m4
runtime/compiler/z/runtime/s390_macros.inc

Revert "Fix incorrect macros in m4 files"

---

runtime/compiler/aarch64/codegen/CMakeLists.txt
runtime/compiler/aarch64/codegen/CallSnippet.cpp
runtime/compiler/aarch64/codegen/CallSnippet.hpp
runtime/compiler/build/files/target/aarch64.mk

This commit implements CallSnippet for aarch64.

AArch64: Implement CallSnippet

---

test/.gitignore
test/README.md
test/TestConfig/makefile
test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl
test/docs/OpenJ9TestUserGuide.md

- generate disabled.mk file to list disabled tests
- disabled tests can run by categories
[ci skip]
Signed-off-by: Longyu Zhang <longyu.zhang@IBM.com>

Support running disabled tests in TestKitGen

---

buildenv/jenkins/jobs/infrastructure/Cleanup-Nodes

- clean test resources from /tmp and Windows user's home directory 
- clean aix shared memory
- clean workspace for terminated pipelines
- kill hanging processes (optional) 

Add script to clean Jenkins nodes

---

runtime/port/sysvipc/j9shmem.c
runtime/port/sysvipc/j9shsem_deprecated.c

Add IBM i specific changes to avoid more incorrect messages.

Add IBM i specific changes to avoid more incorrect messages

---

runtime/hookable/CMakeLists.txt

CMake: Link hookable against j9utilcore

---

runtime/port/CMakeLists.txt

CMake: Add export symbols to port library

---

runtime/port/sysvipc/j9sharedhelper.c

Add  IBM i specific authority determination code. Actually, these code changes have been merged back when we haven't open sourced openj9 code, but missed after open sourced by some reasons.  So we have to merge back again.  Could you help to review and merge the fix?  Thanks.

 Add IBM i specific authority determination

---

runtime/compiler/aarch64/codegen/CallSnippet.cpp
runtime/compiler/arm/codegen/CallSnippet.cpp
runtime/compiler/arm/codegen/J9ARMEvaluator.cpp
runtime/compiler/arm/codegen/J9CodeGenerator.cpp
runtime/compiler/arm/codegen/J9TreeEvaluator.cpp
runtime/compiler/codegen/CodeGenGC.cpp
runtime/compiler/codegen/CodeGenRA.cpp
runtime/compiler/optimizer/DataAccessAccelerator.cpp
runtime/compiler/optimizer/SequentialStoreSimplifier.cpp
runtime/compiler/p/codegen/CallSnippet.cpp
runtime/compiler/p/codegen/DFPTreeEvaluator.cpp
runtime/compiler/p/codegen/J9CodeGenerator.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/p/codegen/StackCheckFailureSnippet.cpp
runtime/compiler/x/amd64/codegen/AMD64GuardedDevirtualSnippet.cpp
runtime/compiler/x/codegen/J9CodeGenerator.cpp
runtime/compiler/x/codegen/J9Linkage.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp
runtime/compiler/x/codegen/X86Recompilation.cpp
runtime/compiler/z/codegen/J9Linkage.cpp
runtime/compiler/z/codegen/J9MemoryReference.cpp

Remove unnecessary includes of Linkage.hpp

Reference Linkage_inlines.hpp files where appropriate

---

buildenv/jenkins/jobs/infrastructure/artifactory_cleanup.groovy

When a Test job cleanup it launched, and there is no matching Test folder
on the Artifactory server, a 404 is returned and the build fails.
This will add an error message to the description and log and keep the build green.
Reporting false errors will hide any real errors
[skip ci]

Suppress Artifactory cleanup failure if the build does not exist

---

buildenv/jenkins/common/build

* [skip ci]
@vsebe for review.

Update build script to reference new platform name

---

buildenv/jenkins/common/pipeline-functions
buildenv/jenkins/common/variables-functions
buildenv/jenkins/variables/defaults.yml

The cleanup job will only be called if the variable is set to true
[skip ci]

Adding a variable to indicate if the cleanup Artifactory should run

---

buildenv/jenkins/common/pipeline-functions

Fix test pipeline name for JITaaS builds.
[ci skip]

Pipeline status summary fix for JITaaS builds

---

runtime/CMakeLists.txt

CMake: add OPENJ9_BUILD compiler define

---

runtime/bcverify/bcverify.c
runtime/bcverify/rtverify.c

Modify verifier check for unterminated method

---

runtime/bcverify/bcverify.c
runtime/bcverify/rtverify.c

(v0.14.0) Modify verifier check for unterminated method

---

doc/release-notes/0.14/0.14.md

Added to issues table.
[ci skip]

Add shrc generation number change to release notes

---

runtime/compiler/z/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/ReduceSynchronizedFieldLoad.cpp
runtime/compiler/z/codegen/S390Recompilation.cpp
runtime/compiler/z/codegen/S390StackCheckFailureSnippet.cpp

Needed to resolved linking errors on zOS.

Add missing Linkage_inlines includes

---

runtime/jcl/common/sun_reflect_ConstantPool.c

Add proper JNI / j9object_t error handling

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

JIT's X86 CodeGen now always call GC's read barrier helpers when GC's
read barrier type is "gc_modron_readbar_always", which can be requested
via JVM option "-Xgc:alwaysCallReadBarrier".

Respect GC's alwaysCallReadBarrier request on X86

---

runtime/j9vm/CMakeLists.txt
runtime/j9vm/exports.cmake

CMake: Add exports to j9vm

---

runtime/gc_glue_java/MetronomeDelegate.cpp
runtime/gc_glue_java/MetronomeDelegate.hpp
runtime/gc_realtime/RealtimeGC.cpp
runtime/gc_realtime/RealtimeGC.hpp
runtime/gc_realtime/RealtimeMarkTask.cpp
runtime/gc_realtime/RealtimeMarkTask.hpp

Modify RealtimeMarkTask for moving to OMR

---

runtime/compiler/env/J9SharedCache.cpp

Check client SCC before sending SharedCache_addHint

---

runtime/cmake/caches/win_x86-64_cmprssptrs.cmake

CMake add cache file for Windows

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/CompilationThread.hpp
runtime/compiler/control/J9Recompilation.cpp
runtime/compiler/control/JITaaSCompilationThread.cpp
runtime/compiler/control/JITaaSCompilationThread.hpp
runtime/compiler/control/MethodToBeCompiled.cpp
runtime/compiler/control/MethodToBeCompiled.hpp
runtime/compiler/env/J9VMMethodEnv.cpp
runtime/compiler/env/JITaaSCHTable.cpp
runtime/compiler/env/JITaaSPersistentCHTable.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/env/j9methodServer.hpp
runtime/compiler/rpc/raw/J9Client.cpp
runtime/compiler/rpc/raw/J9Server.cpp
runtime/compiler/rpc/raw/J9Stream.hpp
runtime/compiler/runtime/IProfiler.hpp
runtime/compiler/runtime/JITaaSIProfiler.cpp
runtime/compiler/runtime/RuntimeAssumptions.cpp
runtime/compiler/x/codegen/X86Recompilation.cpp
runtime/compiler/x/runtime/Recomp.cpp

Since mainline doesn't support nullptr,
replace all of its occurences in JITaaS code with NULL.

Replace nullptr with NULL

---

test/TestConfig/src/org/openj9/envInfo/EnvDetector.java
test/TestConfig/src/org/openj9/envInfo/MachineInfo.java

Resolves: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1079
Signed-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>

Add ulimit to the machine info output in builds

---

test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java

Add new tests to valuetype tests for flattened fields
We need to test creation of flattened fields
- Add tests the create the following structures: 
Triangle2D, valueLong, valueInt, valueDouble, valueFloat,
valueObject, AssortedValueWithLongAlignment,
AssortedValueWithObjectAlignment, AssortedValueWithSingleAlignment,
LargeObject, MegaObject, AssortedReftWithLongAlignment,
AssortedRefWithObjectAlignment, AssortedRefWithSingleAlignment,
LargeRef, MegaRef
- ensure that fields can be read and written to correctly.
Related:#4983
Signed-off-by: MarkQingGuo <Qing.Guo@ibm.com>

Add new tests to valuetype tests for flattened fields

---

runtime/compiler/control/JITaaSCompilationThread.cpp

- Server needs to be informed that client has aborted the remote compilation request midway into the compilation.
- This issue was never handled and was exposed when we switched from using per-compilation connections to using per-compilation-thread connections
[skip ci]
Issue: #5578

Fix Arity Mismatch Assertion

---

runtime/gc_glue_java/MetronomeDelegate.cpp
runtime/gc_glue_java/MetronomeDelegate.hpp
runtime/gc_realtime/RealtimeAccessBarrier.cpp
runtime/gc_realtime/RealtimeGC.cpp
runtime/gc_realtime/RealtimeGC.hpp
runtime/gc_realtime/RealtimeMarkingScheme.cpp
runtime/gc_realtime/RealtimeRootScanner.cpp

Move _unmarkedImplies* fields from RealtimeGC to delegate

---

buildenv/jenkins/common/test

* AdoptOpenJDK/openjdk-tests#1093
* [skip ci]

Replace JAVA_BIN with TEST_JDK_HOME for PR builds

---

runtime/vm/rasdump.c

Fix low performance of resolving ip address when ipv6 is inactive.

Fix low performance of resolving ip address when ipv6 is inactive.

---

buildenv/jenkins/jobs/infrastructure/wrapper_job.groovy
buildenv/jenkins/jobs/infrastructure/wrapper_template
buildenv/jenkins/jobs/infrastructure/wrapper_variables.yml
buildenv/jenkins/variables/admin_list.yml

There are three parts to this:
Wrapper_job.groovy
Wrapper_variables.yml
Wrapper_template
When this is properly configured, Jenkins will have a pipeline with
the different configurations as Boolean values
The pipeline will then get the configuration values from the yaml file
It will then call the template with those values
The template will then create the jobs to the specification
[skip ci]
Signed-off-by: Samuel Rubin samuel.rubin@ibm.com

Creating a Jenkins job that will create wrapper jobs

---

runtime/compiler/arm/codegen/ARMJNILinkage.cpp
runtime/compiler/arm/codegen/J9ARMEvaluator.cpp
runtime/compiler/arm/codegen/J9TreeEvaluator.cpp
runtime/compiler/p/codegen/DFPTreeEvaluator.cpp
runtime/compiler/p/codegen/J9CodeGenerator.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/p/codegen/PPCJNILinkage.cpp
runtime/compiler/p/codegen/PPCPrivateLinkage.cpp

* Modify Power codegen to call addDependency from CodeGeneratorUtils
* Modify ARM codegen to call addDependency from CodeGeneratorUtils

Modify codegens to call addDependency from CodeGeneratorUtils

---

buildenv/jenkins/jobs/infrastructure/Cleanup-Nodes

Cleanup AIX pipes

---

buildenv/jenkins/jobs/infrastructure/omrMirror

- Convert from declrative to scripted pipeline
- Add retry(2) loop with cleanup in between in order
to catch failures.
[skip ci]

Refactor OMR Mirror script

---

test/.gitignore
test/README.md
test/TestConfig/makefile
test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl
test/TestConfig/scripts/testKitGen/resultsSummary/resultsSum.pl
test/docs/OpenJ9TestUserGuide.md

- integrated disabled tests information in test result summary
- support printing disabled tests and reasons
[ci skip]

Add displaying disabled tests and reasons in TestKitGen

---

runtime/CMakeLists.txt
runtime/gc/CMakeLists.txt
runtime/jcl/CMakeLists.txt
runtime/jvmti/CMakeLists.txt
runtime/port/CMakeLists.txt
runtime/rastrace/CMakeLists.txt
runtime/shared/CMakeLists.txt
runtime/thread/CMakeLists.txt
runtime/vm/CMakeLists.txt

CMake: enable ddr

---

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/macho/MachoDumpReader.java

Fixes https://github.com/eclipse/openj9/issues/5230
Reviewer: @keithc-ca

Handle multiple threads in OSX corereader

---

runtime/compiler/CMakeLists.txt

Numerous places assume a linux build.

CMake: Fix platform specific config for compiler component

---

buildenv/jenkins/common/pipeline-functions

- In order to insert a username & password
[skip ci]
Related #5677

Strip off https:// from repo address

---

buildenv/jenkins/common/variables-functions

Fix java.lang.IllegalStateException when checking supported platforms.
[ci skip]

Fix IllegalStateException in Jenkins pipeline

---

runtime/gc_glue_java/MixedObjectScanner.hpp
runtime/gc_glue_java/PointerArrayObjectScanner.hpp
runtime/gc_glue_java/ReferenceObjectScanner.hpp

This is step 3 of the change: remove functions with old signature

Cleanup after changing of signature of getNextSlotMap()

---

runtime/jniinv/main.c

Delete unused method

---

runtime/codert_vm/cnathelp.cpp

When reporting a static field write from the JIT, the new value pointer
passed in is often a pointer into the java stack. If the report helper
causes the class to be initialized, the stack may grow, invalidating the
pointer.
Read the value from the pointer into a local before initializing the
class.
[ci skip]

Read new field value before initializing the class

---

runtime/compiler/runtime/MethodMetaData.c
runtime/vm/MHInterpreter.cpp

Fix a few things found while attempting a debug windows build.
[ci skip]

Compiler warning and error fixes

---

runtime/bcverify/rtverify.c

The change is to disable the check on the uninitializedThis
flag on old version classfiles (< 51) as such check is only
applied to classfiles with stackmaps which was introduced
since Java 7(class version is 51).
Fix: #5676
Port of #5736 

(v0.14.2) Disable the flag check on method without stackmaps

---

runtime/jcl/common/jniidcacheinit.c

Switch `JCL` field ID cache setting order to avoid reading `NULL`
There is a time hole between setting `JCL` field IDs `CLS_sun_reflect_ConstantPool` and
`FID_sun_reflect_ConstantPool_constantPoolOop`. One thread could set `CLS_sun_reflect_ConstantPool` but not `FID_sun_reflect_ConstantPool_constantPoolOop` yet; another thread reads the `non-null CLS_sun_reflect_ConstantPool`, skip `initializeSunReflectConstantPoolIDCache()`, and de-reference `NULL
FID_sun_reflect_ConstantPool_constantPoolOop` which caused `gpf`.
Switching the setting order and add issueWriteBarrier().
Also refactoring for code format and comments.
This is discovered in an internal test. Verified that this PR can make the test pass consistently.

Switch JCL field ID cache setting order to avoid reading NULL

---

runtime/gc_base/RootScanner.hpp
runtime/gc_glue_java/MetronomeDelegate.cpp
runtime/gc_glue_java/MetronomeDelegate.hpp
runtime/gc_realtime/EnvironmentRealtime.hpp
runtime/gc_realtime/RealtimeGC.cpp
runtime/gc_realtime/RealtimeGC.hpp
runtime/gc_realtime/RealtimeMarkTask.cpp
runtime/gc_realtime/RealtimeMarkingScheme.cpp
runtime/gc_realtime/RealtimeMarkingScheme.hpp
runtime/gc_realtime/RealtimeMarkingSchemeRootClearer.hpp
runtime/gc_realtime/RealtimeMarkingSchemeRootMarker.hpp
runtime/gc_realtime/RealtimeRootScanner.cpp
runtime/gc_realtime/RealtimeRootScanner.hpp
runtime/gc_realtime/Scheduler.cpp
runtime/gc_realtime/Scheduler.hpp

Modify RealtimeMarkingScheme for moving to OMR

---

runtime/vm/resolvesupport.cpp

Not re-fetch `ramCPEntry` via `CP` index
Use `ramCPEntry` directly instead of re-fetching it via `CP` index. This matches the code pattern for `invokePrivate` in similar case.
Also refactoring code format within the the method affected.
This is a following-up cleanup after https://github.com/eclipse/openj9/pull/5694.
Reviewer: @gacholio 
FYI: @DanHeidinga 

Not re-fetch ramCPEntry via CP index

---

runtime/gc_base/modron.h
runtime/gc_modron_startup/mminit.cpp
runtime/vm/J9OMRHelpers.cpp
runtime/vm/segment.c

Some compile errors and heap settings.
[ci skip]

Fix some startup issues in mixed mode

---

runtime/compiler/runtime/HookHelpers.cpp

Reverts eclipse/openj9#5826
See #5832

Revert "Fix bug in assumption reclamation"

---

buildenv/jenkins/README.md
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All
buildenv/jenkins/variables/defaults.yml

- By adding --with-noncompressedrefs
- Update README for definition of ALL platforms
[skip ci]

Add spec for Windows Large Heap

---

buildenv/jenkins/variables/defaults.yml

Correct Windows LargeHeap platform name

---

buildenv/jenkins/variables/defaults.yml

- No longer support these versions
[skip ci]

Remove JDK9,10 from Specs

---

jcl/src/java.base/share/classes/java/lang/Class.java
jcl/src/java.base/share/classes/java/lang/ClassLoader.java
jcl/src/java.base/share/classes/java/lang/StackTraceElement.java
jcl/src/java.base/share/classes/java/lang/StackWalker.java
jcl/src/java.base/share/classes/java/lang/String.java
jcl/src/java.base/share/classes/java/lang/System.java
jcl/src/java.base/share/classes/java/lang/invoke/MethodHandle.java
jcl/src/java.base/share/classes/java/lang/invoke/MethodHandleInfo.java
jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
jcl/src/java.base/share/classes/java/lang/invoke/WrongMethodTypeException.java
runtime/vm/KeyHashTable.c

Fix javadoc warnings and remove #if 0'd code

---

runtime/compiler/control/J9Options.cpp

We have performed the necessary testing and have validated that all
known bugs have been fixed now.

Enable z15 by default

---

runtime/compiler/env/VMJ9.cpp

Fix spelling mis-correction

---

runtime/vm/resolvesupport.cpp

The resolve code for Condy wasn't using the correct static
gc barriers (J9STATIC_OBJECT_STORE) when writing into the
constantpool entry.
This is especially important for Condy as it can store young-gen
objects into the cp entry due being unable to clone the user
created object into tenure.
issue: #5895

(v0.14.3) Add gc barriers to constant_dynamic resolution

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java

Skip retrieving system property `systemClassLoader` for `JDK11+`
The system property `systemClassLoader` is a `J9` extension and is obsoleted for `JDK11+`.
Retrieving this property only in `JDK8`.
Note: I used JPP flag `Java11` instead of `Sidecar19-SE` which should be replaced by `Java 11`, but that can be done in a separated PR.
Verified that `pConfig` for `JDK 8/11` still compile.
closes: #5940
FYI: @pshipton 

Skip retrieving system property systemClassLoader for JDK11+

---

jcl/src/java.base/share/classes/java/lang/ClassLoader.java

The effect is that the VM loads 43 fewer classes to run a 'Hello world' application.

Replace lambda with a helper class

---

runtime/compiler/p/codegen/PPCPrivateLinkage.cpp

Also, replace uses of deprecated `FrontEnd->getObjectAlignmentInBytes()`
with `TR::Compiler->om.objectAlignmentInBytes()`.

Misc. formatting and dead code cleanup for PPCPrivateLinkage

---

buildenv/jenkins/variables/defaults.yml

- As per OpenJ9 Community call discussion June 5
[skip ci]

Increase build history to 30 for Nightly and OMR

---

test/functional/Java8andUp/playlist.xml
test/functional/NativeTest/playlist.xml
test/functional/cmdLineTests/shareClassTests/DataHelperTests/playlist.xml
test/functional/cmdLineTests/shareClassTests/ListAllCachesTests/playlist.xml
test/functional/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml
test/functional/cmdLineTests/shareClassTests/SCCommandLineOptionTests/playlist.xml
test/functional/cmdLineTests/shareClassTests/SCHelperCompatibilityTests/playlist.xml
test/functional/cmdLineTests/shareClassTests/ShareClassesSimpleSanity/playlist.xml
test/functional/cmdLineTests/shareClassTests/StoreFilterTests/playlist.xml
test/functional/cmdLineTests/shareClassTests/URLHelperTests/playlist.xml

https://github.com/eclipse/openj9/issues/5767

Mark tests appropriately for AOT testing

---

runtime/compiler/il/symbol/J9Symbol.cpp

Currently we recognize a field by comparing its reference class' name to
the declaring class' name. The referenece class can be the declaring
class' subclass and the compare will fail. Fix it.
#4837 

Recognize a field by its declaring class

---

jcl/jpp_configuration.xml

https://github.com/eclipse/openj9/pull/6017#discussion_r291264938

Remove obsolete J9 JCL Automated Tests v2

---

jcl/jpp_configuration.xml

* it depends on JAVA13 and should also use `rt-compressed.sunJava13.jar`

Fix PANAMA configuration

---

runtime/jvmti/jvmtiHelpers.c

`DisposeEnvironment()` need to clear `J9JVMTI_FLAG_SAMPLED_OBJECT_ALLOC_ENABLED` such that later `AddCapabilities()` can still add the capability `can_generate_sampled_object_alloc_events`.
Minor code format refactoring.
Note: this was discovered in an internal test.
Reviewer: @gacholio 
FYI: @DanHeidinga @pshipton 

Clear J9JVMTI_FLAG_SAMPLED_OBJECT_ALLOC_ENABLED at disposeEnvironment

---

jcl/src/java.base/share/classes/java/lang/invoke/PrimitiveHandle.java

Fix MethodHandle exception wrapping

---

runtime/compiler/ilgen/Walker.cpp

Evaluate ifcmp in walker when its operands are integral constants and
fold it. This helps reducing method size of a custom MethodHandle thunk
as code like `if (ILGenMacros.isShareableThunk())` will be folded away.
#4837 

Fold ifcmp with two constant integral operands

---

test/functional/cmdLineTests/gcRegressionTests/playlist.xml
test/functional/cmdLineTests/shareClassTests/DataHelperTests/playlist.xml
test/functional/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml

- this causes issue when AOT is on
- remove or replace TESTOUTPUT with REPORTDIR
[ci skip]
Fixes #6052

Remove referece to TESTOUTPUT in playlist.xml

---

test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl
test/TestConfig/scripts/testKitGen/makeGenTool/parseFilesForZos.pl

- utilize customized xml parser on zos
[ci skip]

Support xml parsing on zos in testKitGen

---

jcl/src/java.base/share/classes/java/lang/invoke/MethodHandle.java

Remove duplicate code by creating common method for MethodHandle.resolveConstantDynamic and resolveInvokeDynamic. Verified indy/condy tests on Java 8 and 11.
Fixes: #2662

Create common method for MH.resolveCondy/Indy

---

runtime/compiler/build/toolcfg/ztpf-gcc/common.mk
runtime/makelib/targets.mk.ftl

Compiler Option updates as part of building for GCC 7.
Signed-off-by: James D Johnston <jjohnst@us.ibm.com>

Updates associated with z/TPF GCC 7 Builds

---

buildenv/docker/test/Dockerfile
runtime/tests/jvmtitests/agent/tests.c
runtime/tests/jvmtitests/include/jvmti_test.h
runtime/tests/jvmtitests/module.xml
runtime/tests/jvmtitests/src/CMakeLists.txt
runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/fieldwatch/fw001.c
test/functional/cmdLineTests/jvmtitests/fieldwatchtests.xml
test/functional/cmdLineTests/jvmtitests/playlist.xml
test/functional/cmdLineTests/jvmtitests/src/com/ibm/jvmti/tests/fieldwatch/MyObject.java
test/functional/cmdLineTests/jvmtitests/src/com/ibm/jvmti/tests/fieldwatch/TestDriver.java
test/functional/cmdLineTests/jvmtitests/src/com/ibm/jvmti/tests/fieldwatch/fw001.java

Add JVMTI tests for fieldwatch.

Add tests for field watch

---

jcl/jpp_configuration.xml
runtime/bcutil/defineclass.c
runtime/include/j9cfg.h.ftl
runtime/include/j9cfg.h.in
runtime/jcl/common/jclcinit.c
runtime/oti/j2sever.h
runtime/oti/j9nonbuilder.h
runtime/vm/rasdump.c

Enables building from the `openj9-staging` branch of `openj9-openjdk-jdk`.

Add support for Java 14

---

buildenv/jenkins/variables/defaults.yml

This reverts commit f50808179e7e961e451be872e8021cdb20e31e22.
PR #5830

Revert "TEMP [skip ci] unexclude cmake tests"

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All
buildenv/jenkins/variables/defaults.yml

- Update variable file and PBT-All
[skip ci]

Add JDK13 to Jenkins Pipelines

---

test/TestConfig/settings.mk
test/functional/cmdLineTests/shareClassTests/DataHelperTests/playlist.xml
test/functional/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml

- created another variable REPORTDIR_NQ
- use it inside quoation
[ci skip]

Fix quotation issue when using REPORTDIR

---

runtime/vm/CMakeLists.txt

CMake: Add support for osx in vm

---

CMakeLists.txt
buildenv/travis/build-on-travis.sh

* find java, javac and jar based on BOOT_JDK

CMake: require that BOOT_JDK be specified

---

runtime/jcl/common/mgmtinit.c

Due to The JIT code cache grows from both ends of the segment,
memory in use for JIT code cache need to be calculated differently.
Update MXBeans code Match the logic for calculating used memoryUsage
of JIT code cache in Java Core Dump.
fix: #5418 

fix JMX report issue for JIT Code cache

---

runtime/vm/exceptionsupport.c

When first class `java/lang/Object` is failed to be loaded due to unsupported version error, current `JVM` exits without meaningful message. 
This fix allows `JVM` exit with messages like `JVMCFRE003 bad major version; class=java/lang/Object, offset=6`.
`JVM` output before this fix:
```
Aborted
```
`JVM` output with this PR:
```
JVMCFRE003 bad major version; class=java/lang/Object, offset=6 
JVMJ9VM019E Unrecoverable error: Unable to find and initialize required class java/lang/Object
JVMJ9VM023I This may indicate that JAVA_HOME is incorrect, or that class libraries are not installed
``` 
Note: this kind of error usually is observed when bringup Java new levels. It is not expected during actual application running hence not use `NLS` output.
Signed-off-by: Jason …

Exit with message for unsupported version error at startup

---

runtime/compiler/codegen/CodeGenGC.cpp

* reorder and group initialization code more logically
* rename variables to improve readability
* add additional documentation
* misc code formatting changes
* remove unneeded include directives
None of these changes the functionality or the order of operations
in this function.

Misc. readability improvements to createStackAtlas

---

runtime/oti/j9accessbarrier.h

Fix ARM compile error

---

runtime/oti/j9accessbarrier.h

More windows compile errors

---

runtime/oti/j9accessbarrier.h

Another windows fix

---

runtime/compiler/codegen/CodeGenGC.cpp

* minor code improvements suggested in the review for PR #6159
* query Options directly rather than use privatized versions

Additional readability enhancements to createStackAtlas

---

runtime/gc_ddr/gcddrstructs.properties
runtime/gc_modron_startup/module.xml
runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp
runtime/gc_vlhgc/module.xml

The table will track the current state of each region in VLHGC.
cc @amicic @charliegracie @rwy0717

Create HeapRegionStateTable on VLHGC startup

---

buildenv/jenkins/README.md

- Add Doc to explain the TEST_FLAG option and how to launch with it.
Fixes #5879
[skip ci]

Add Jenkins PR doc for TEST_FLAG option

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-Any-Platform

Move DSL step outside setup step and into parallel

---

runtime/tests/jvmtitests/agent/tests.c
runtime/tests/jvmtitests/include/jvmti_test.h
runtime/tests/jvmtitests/module.xml
runtime/tests/jvmtitests/src/CMakeLists.txt
runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/redefineClasses/rc020.c
test/functional/cmdLineTests/jvmtitests/jvmtitests_hcr.xml
test/functional/cmdLineTests/jvmtitests/src/com/ibm/jvmti/tests/redefineClasses/rc020.java
test/functional/cmdLineTests/jvmtitests/src/com/ibm/jvmti/tests/redefineClasses/rc020_Source.java
test/functional/cmdLineTests/jvmtitests/src/com/ibm/jvmti/tests/redefineClasses/rc020_testIndyAsmGenerator.java
test/functional/cmdLineTests/jvmtitests/src/com/ibm/jvmti/tests/redefineClasses/rc020_testIndyBSMs.java

First step for issue: #4542
Tests for: #5029

Add test for class redef callsite propagation

---

jcl/src/java.base/share/classes/com/ibm/oti/lang/ArgumentHelper.java
jcl/src/java.base/share/classes/com/ibm/oti/vm/MsgHelp.java
jcl/src/java.base/share/classes/java/lang/Access.java
jcl/src/java.base/share/classes/java/lang/StackWalker.java
jcl/src/java.base/share/classes/java/lang/System.java
jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java
jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/LoggingMXBeanImpl.java
jcl/src/java.management/share/classes/java/lang/management/DefaultPlatformMBeanProvider.java
jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/PlatformMBeanProvider.java
jcl/src/jdk.management/share/classes/openj9/lang/management/internal/OpenJ9DiagnosticsMXBeanImpl.java

* types in java.lang (e.g. java.lang.Module) are imported implicitly

Remove redundant import statements

---

runtime/compiler/build/files/common.mk
runtime/compiler/compile/CMakeLists.txt
runtime/compiler/compile/J9Method.cpp
runtime/compiler/compile/J9Method.hpp
runtime/compiler/compile/Method.hpp
runtime/compiler/il/symbol/MethodSymbol.hpp

* Consume refactored method files from OMR
* Create skeleton implementation of J9Method extensible class

Support Method extensible base class

---

runtime/ddr/vmddr.cpp

Declare obsolete J9_JAVA constants in DDR blob for compatibility

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

The receiver of a method handle thunk is always a known object. Set
prexArg for methodhandle thunks in all cases to propagate the info
without peeking in inlining or global VP.
In the special case of a method handle thunk being  mutable callsite
target, the known object info is only available in the inlined body
rather than taken side of the guard.
issue: #4837

Set prexArg for method handle thunks

---

doc/release-notes/0.15/0.15.md

Draft release notes for 0.15, milestone 1.

Add a set of release notes for MS1

---

runtime/libffi/CMakeLists.txt

CMake: make libffi work on aix

---

runtime/util/CMakeLists.txt

Add aix sources to util component

---

runtime/thread/CMakeLists.txt

Link against the platform agnostic OMR_PLATFORM_THREAD_LIBRARY

---

runtime/jcl/common/proxy.c

When we create a proxy of an interface with MethodHandleProxies and invoke a default method from the proxied interface's superinterfaces, an access check in the VM fails in JDK8 because the proxy itself does not have the superinterface listed as one of its own direct superinterfaces. In JDK11 and later, the generated proxy classes have a flag set that exempts them from validation. This PR does the same to the proxy classes generated in JDK8.
Fixes #5950

Exempt com/sun/proxy classes from validation

---

runtime/jcl/common/proxy.c

When we create a proxy of an interface with MethodHandleProxies and invoke
a default method from the proxied interface's superinterfaces, an access
check in the VM fails in JDK8 because the proxy itself does not have the
superinterface listed as one of its own direct superinterfaces. In JDK11
and later, the generated proxy classes have a flag set that exempts them
from validation. This PR does the same to the proxy classes generated in
JDK8.
Backported from #6258 
Reviewer: @DanHeidinga

(v.0.15.0) Exempt com/sun/proxy classes from validation

---

runtime/oti/VMHelpers.hpp

Fix ValueType compilation failures

---

runtime/vm/CMakeLists.txt

Add aix support to vm component

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.hpp

This commit implements the constructor of ARM64PrivateLinkage.

AArch64: Implement constructor of ARM64PrivateLinkage

---

runtime/compiler/arm/codegen/J9CodeGenerator.cpp

Fix ARM CodeGenerator constructor build break

---

runtime/util/CMakeLists.txt

Cmake: Remove divrem.c

---

doc/release-notes/0.15/0.15.md

Replace ~5 restarts with a few restarts.
[ci-skip]

Update release notes for GC hints

---

runtime/compiler/control/J9Options.cpp
runtime/compiler/ilgen/Walker.cpp

* Disable Quad optimization for AArch64
* Disable internal pointers on AArch64
* Disable arrayset optimizations on AArch64

Disable features not available on AArch64 yet

---

buildenv/jenkins/variables/defaults.yml

- Nightly to 40
- OMR to 20
- As per OpenJ9 community call
Related #6021
[skip ci]

Increase Nightly & Decrease OMR history

---

buildenv/docker/jdk8/x86_64/ubuntu16/jitaas/build/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu16/jitaas/buildenv/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu18/jitaas/build/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu18/jitaas/buildenv/Dockerfile

Update Docker files to build protobuf with -fPIC enabled.

Update JITaaS Docker files

---

runtime/libffi/CMakeLists.txt

CMake: add zLinux support to ffi

---

runtime/codert_vm/CMakeLists.txt

CMake: add s390 support to codert_vm

---

runtime/compiler/aarch64/codegen/CMakeLists.txt
runtime/compiler/aarch64/codegen/ForceRecompilationSnippet.cpp
runtime/compiler/aarch64/codegen/ForceRecompilationSnippet.hpp
runtime/compiler/build/files/target/aarch64.mk

This commit adds new files for ForceRecompilationSnippet for AArch64.

AArch64: Add ForceRecompilationSnippet files

---

test/docs/OpenJ9TestUserGuide.md

- modified test instructions
[ci skip]

modified Test User Guide

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.hpp

Code that adds an evaluator to handle storeFence, loadFence, fullFence
and allocationFence for AArch64.
Signed-off-by: Hillary Soontiens <hsoontie@unb.ca>

Implement store/load/full/allocationFence for AArch64

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.hpp

This commit implements BNDCHK Evaluator for openj9.
Signed-off-by: marufunb <mrahma15@unb.ca>

AArch64: Implementation of BNDCHK Evaluator

---

buildenv/jenkins/jobs/infrastructure/Update-Reference-Repos.groovy

Cache OpenJ9 repository on master and build slaves. This allows to
reduce the clone time, the network and disk space.
To be referenced by the scm step in all of the pipelines jobs and
scripts.
[ci skip]

Add OpenJ9 repository to git cache

---

buildenv/jenkins/common/build.groovy

Fix incorrect function name call

---

jcl/src/java.base/share/classes/java/lang/invoke/CollectHandle.java
runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/j9method.cpp
runtime/compiler/il/J9DataTypes.hpp

- Preallocate empty array for CollectHandle
- Convert allocateArray to newarray if CollectHandle is a known object
#4837 

Improve CollectHandle

---

buildenv/jenkins/common/pipeline-functions.groovy
buildenv/jenkins/variables/defaults.yml

- special.system test build should run in parallel (set `IS_PARALLEL` to true)
- set `IS_PARALLEL` to false for other test builds
- only enable special.system on ppcle for JDK8 for now
Closes: #6478
[ci skip]

enable special.system test build on ppcle only

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.hpp

This commit implements ArrayStoreCHKEvaluator() for AArch64.

AArch64: Implement ArrayStoreCHKEvaluator()

---

runtime/compiler/runtime/Listener.cpp
runtime/compiler/runtime/Listener.hpp

Changed JITaaS into JITServer, performed some small clean-up
and added a few comments.

Preparing listener code to be merged into master branch

---

runtime/jit_vm/ctsupport.c
runtime/oti/j9protos.h

Add JIT compile-time query for ROM field declaring class

---

runtime/compiler/CMakeLists.txt
runtime/compiler/build/files/common.mk
runtime/compiler/build/files/net.mk
runtime/compiler/build/rules/gnu/common.mk
runtime/compiler/build/rules/gnu/filetypes.mk
runtime/compiler/build/toolcfg/common.mk
runtime/compiler/build/toolcfg/gnu/common.mk
runtime/compiler/compiler.mk
runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/env/J9PersistentInfo.hpp
runtime/compiler/env/PersistentCollections.hpp
runtime/compiler/net/CMakeLists.txt
runtime/compiler/net/ClientStream.cpp
runtime/compiler/net/ClientStream.hpp
runtime/compiler/net/CommunicationStream.cpp
runtime/compiler/net/CommunicationStream.hpp
runtime/compiler/net/ProtobufTypeConvert.cpp
runtime/compiler/net/ProtobufTypeConvert.hpp
runtime/compiler/net/SSLProtobufStream.hpp
runtime/compiler/net/ServerStream.cpp
runtime/compiler/net/ServerStream.hpp
runtime/compiler/net/StreamExceptions.hpp
runtime/compiler/net/protos/compile.proto

Merge files under `net` directory on `jitaas` branch to `master` branch.
Changes related to JITServer are guarded with `JITSERVER_SUPPORT` flag.

Merge JITServer networking files

---

runtime/compiler/optimizer/J9EstimateCodeSize.cpp

Remove some dead code. Remove
setJ9EstimateCodeSizeMethod/getJ9EstimateCodeSizeMethod and replace it
with calltarget->_calleeMethod since they are the same.

Clean up inliner estimate code size

---

runtime/compiler/aarch64/runtime/ARM64RelocationTarget.cpp
runtime/compiler/aarch64/runtime/ARM64RelocationTarget.hpp
runtime/compiler/aarch64/runtime/CMakeLists.txt
runtime/compiler/build/files/host/aarch64.mk
runtime/compiler/runtime/RelocationRuntime.cpp

This commit adds code for ARM64RelocationTarget.

AArch64: Add ARM64RelocationTarget

---

runtime/compiler/build/files/common.mk
runtime/compiler/build/files/target/p.mk
runtime/compiler/p/codegen/J9PPCSnippet.cpp

OpenJ9 piece of eclipse/omr#3930.

Consolidate InstOpCode tables on Power and improve documentation

---

runtime/compiler/optimizer/J9Inliner.cpp

In many places, OSR-related code in the inliner is calling `getOwningMethodSymbol()` on a symbol reference in order to access information about the calling method.  However, the owning method for a symbol reference is not necessarily the calling method.
Instead, code should call `getInlinedResolvedMethodSymbol()` on the `TR::Compilation` object for the bytecode's caller index or, if the caller index is -1, call `getMethodSymbol()`.

Look for right caller method when handling OSR in context of inliner

---

runtime/compiler/build/files/common.mk
runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/env/VMJ9.h
runtime/compiler/runtime/CompileService.cpp
runtime/compiler/runtime/CompileService.hpp
runtime/compiler/runtime/Listener.cpp
runtime/compiler/runtime/Listener.hpp

Port Listener.cpp and Listener.hpp from `jitaas` branch to mainline

Port JITServer Listener

---

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp

Choose the API that can recreate the node with valid properties instead of no property.
Signed-off-by: simonameng <simonameng97@gmail.com>

Fix the `dsqrt` transformation 

---

runtime/compiler/env/j9method.cpp

VM access is required before dereferencing a java object during JIT
compilation. Also check that MethodHandle object is non-null before
folding CollectHandle.allocateArray.

Add missing vm access

---

runtime/compiler/control/JITaaSCompilationThread.cpp

Fix bug with ClientSessionTerminate verbose output

---

test/docs/OpenJ9TestUserGuide.md

- rename systemtest to test
[ci skip]

Update test readme

---

jcl/src/java.management/share/classes/java/lang/management/ManagementFactory.java

A call to `MBeanServerFactory.createMBeanServer()` can fail; thus it is not reasonable to include such a call in the static initializer of a class. This reorganizes that call into a method where an exception can properly be propagate back to the caller of `ManagementFactory.getPlatformMBeanServer()`.
Fixes: #6623

Reorganize lazy creation of MBeanServer

---

runtime/vm/jvminit.c

Enable Transparent Hugepage on xLinux by default

---

runtime/cmake/compiler_config.cmake

CMake: Add s390 host/target defines

---

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
jcl/src/java.base/share/classes/java/lang/Throwable.java

- class check on suppressedException
- construct new ArrayList to hold the suppressed exceptions

Add extra checks to Throwable.readObject

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Work in progress implementation of awrtbarEvaluator and associated helper
wrtbarEvaluator will also be used by awrtbariEvaluator when that is implemented
Signed-off-by: Michael Flawn <mflawn@unb.ca>

AArch64: Implementation of awrtbarEvaluator in AArch64

---

runtime/compiler/optimizer/J9Inliner.cpp

Changes to the way the calling method is determined for OSR-related code in the Inliner were guarded by `#if defined(INLINER_OSR_CALLING_METHOD)`.  Now that that macro is defined in OMR, the change can be made unconditional in OpenJ9.

Enable change to determine calling method for OSR code unconditionally

---

runtime/compiler/env/VMJ9.cpp
runtime/compiler/runtime/JitRuntime.cpp
runtime/gc_api/HeapIteratorAPI.cpp
runtime/gc_base/ObjectAccessBarrier.cpp
runtime/gc_base/RootScanner.cpp
runtime/gc_glue_java/ArrayletObjectModelBase.hpp
runtime/gc_glue_java/objectdescription.h
runtime/gc_include/ObjectAccessBarrierAPI.hpp
runtime/gc_modron_startup/mgcalloc.cpp
runtime/jcl/common/thread.cpp
runtime/oti/ObjectMonitor.hpp
runtime/oti/j9accessbarrier.h
runtime/oti/monhelp.h
runtime/tests/jni/montest.c
runtime/tests/thread/testnatives/testnatives.c
runtime/util/moninfo.c
runtime/util/thrinfo.c
runtime/vm/ObjectMonitor.cpp
runtime/vm/monhelpers.c
runtime/vm/montable.c
runtime/vm/threadhelp.cpp

Runtime compressed refs work

---

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
jcl/src/java.base/share/classes/java/lang/Throwable.java

Revert "Add extra checks to Throwable.readObject"

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Work in progress implementation of awrtbariEvaluator and associated helper.
wrtbarEvaluator will also be used by awrtbarEvaluator when that is implemented.
Signed-off-by: Michael Flawn <mflawn@unb.ca>

AArch64: Implementation of awrtbariEvaluator in AArch64

---

runtime/codert_vm/jswalk.c

The metadata cache in the stack walker is not thread-safe, but is
potentially used from multiple threads at once. Add some verification to
the cache lookup to prevent invalid lookups rather than adding explicit
locking or memory barriers.
[ci skip]

Handle multi-threaded metadata cache access

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.hpp

Work in progress implementation of MethodEnter/ExitHookEvaluator
Actual evaluator is same for both, conditionalHelperEvaluator
Signed-off-by: Michael Flawn <mflawn@unb.ca>

AArch64: Implementation of MethodEnterHook/MethodExitHook

---

test/docs/Prerequisites.md

update make version to 4.1 in test readme

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp

Both the generateFillInDataBlockSequenceForUnresolvedField() and generateReportFieldAccessOutlinedInstructions() functions store their first argument in gr3 and call a VM helper function via a trampoline that uses gr11 to store the callee address. Before implementing this fix, the contents of gr3 were stored to gr11 before the helper function call and loaded back to gr3 after. However, since gr11 was being used by the trampoline, after the helper function call, the wrong data would be loaded back, corrupting gr3 and causing a segmentation fault. In this commit, gr11 has been added as a dependency to ensure that it used only for the callee address (and not to back up gr3), and that gr3 is not corrupted.

Adding gr11 as dependency before calling VMHelper during Field Watch

---

runtime/compiler/control/HookedByTheJit.cpp

Lowering the invocation count results in methods getting compiled
sooner. When the SCC is used, this means that there are more methods
available in the SCC during startup, which improves startup time.
However, this also comes at the cost of increased footprint.
Additionally, it only makes sense to lower the invocation count of the
SCC cold run (ie the populate SCC run), because it just results in more
AOT loads as opposed to having JIT compiled those additional loads;
lowering the invocation count in the SCC warm run (ie the load from SCC
run) risks hurting startup because any methods that weren't compiled in
the first run would now get JIT/AOT compiled sooner; in fact these methods
might not even be all that important as they weren't compiled in the
first run.
This PR extends the …

Lower invocation counts for SCC cold runs

---

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
jcl/src/java.base/share/classes/java/lang/String.java

add new Java 13 String Methods

---

doc/release-notes/0.16/0.16.md

Draft release notes to support milestone 1.

Release notes to support 0.16 milestone 1

---

runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp

Added fix to ensure commoned blocks are fixed up, and reference counts are correct
Fixes: #4657
Signed-off-by: Jacob Nauenberg <jacob.nauenberg@ibm.com>

Added fixup to nodes; nodes only referenced within one basic block

---

runtime/compiler/build/files/common.mk
runtime/compiler/env/VMJ9.h
runtime/compiler/runtime/CMakeLists.txt
runtime/compiler/runtime/ClassUnloadAssumption.cpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp
runtime/compiler/runtime/RuntimeAssumptions.hpp

Port JITClientSession changes to master

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.hpp

This commit implements ARM64PrivateLinkage::createEpilogue().

AArch64: Implement ARM64PrivateLinkage::createEpilogue()

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

If the array length in a `BNDCHKWithSpineCHK` is constant, generated code was comparing the constant length with the bound, bypassing the spine check, which is only OK if the array is not discontiguous.
Added a compile-time check of whether the array is discontiguous if the length is known.  If it is discontiguous, generate an unconditional branch to the spine check/bound check snippet.
Fixes #6498 and fixes #6773

Branch to snippet unconditionally for array known to be discontiguous

---

runtime/compiler/control/CompilationController.cpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/MethodToBeCompiled.cpp
runtime/compiler/control/MethodToBeCompiled.hpp

Merge `JITServer` functionalities to `MethodToBeCompiled`.

Merge JITServer functionalities to MethodToBeCompiled

---

buildenv/docker/jdk8/s390x/ubuntu16/jitaas/build/Dockerfile
buildenv/docker/jdk8/s390x/ubuntu16/jitaas/buildenv/Dockerfile
buildenv/docker/jdk8/s390x/ubuntu16/jitaas/run/Dockerfile
buildenv/docker/jdk8/s390x/ubuntu16/jitaas/test/Dockerfile

Add JITServer Dockerfiles for zLinux

---

runtime/gc_realtime/MetronomeAlarmThread.cpp

z/TPF does not make use of linux/unistd.h.  The update
was to simply move the header include statement into
a !z/TPF guard macro block in the MetronomeAlarmThread.cpp
segment.
Signed-off-by: James D Johnston <jjohnst@us.ibm.com>

Minor Header Platform configuration change for z/TPF

---

runtime/compiler/z/codegen/J9AheadOfTimeCompile.cpp

Use front-end query to get ROMMethod from RAMMethod

---

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
jcl/src/java.base/share/classes/java/lang/String.java

Implements new String methods:
- formatted(Object...)
- stripIndent()
- transplateEscapes()
Port of #6624 and #6952 for the 0.16 release.

(0.16.0) Add new Java 13 String Methods

---

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
jcl/src/java.base/share/classes/com/ibm/tools/attach/target/CommonDirectory.java
jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9AttachProvider.java
jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9VirtualMachine.java

**Add attach API logs**
No explicit functionality changes;
Added more logs for trouble shooting purpose.
Related: #5274 
Reviewer: @pshipton 

Add attach API logs

---

runtime/compiler/aarch64/codegen/StackCheckFailureSnippet.cpp

This commit adds implementation of debug print function for
`TR::ARM64StackCheckFailureSnippet`.
Depends on https://github.com/eclipse/omr/pull/4250

AArch64: Add implementation of debug print function for StackCheckFailureSnippet

---

jcl/src/java.base/share/classes/java/lang/Throwable.java

Remove extra semi-colon in Throwable.java

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/AttachedDataWrapperHelper.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/ByteDataWrapperHelper.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/CompiledMethodWrapperHelper.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/ROMClassWrapperHelper.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/ScopedROMClassWrapperHelper.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/SharedClassesMetaDataHelper.java
debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ShrCCommand.java

Add DDR support for multi-layer shared cache

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/MethodToBeCompiled.cpp
runtime/compiler/control/MethodToBeCompiled.hpp

Update `MethodToBeCompiled` for merging into the `master` branch.

Update MethodToBeCompiled for merging into master

---

test/TestConfig/scripts/testKitGen/resultsSummary/resultsSum.pl
test/TestConfig/settings.mk

Add grinder rebuild option in the end of test target

---

buildenv/jenkins/variables/defaults.yml

Include special.system tests for osx CR on JDK8

---

runtime/compiler/z/codegen/S390Recompilation.cpp

Get existing method info from the J9Method instead of startPC

---

buildenv/jenkins/variables/defaults.yml

(v0.16.0) Include special.system testing in the 0.16 release branch

---

test/TestConfig/scripts/testKitGen/resultsSummary/resultsSum.pl
test/TestConfig/settings.mk

Add CUSTOM_TARGET in the rebuild links

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/SharedClassesMetaDataHelper.java

Use reflection to get cache layer from J9shrOffset

---

test/TestConfig/TKGJ/src/org/testKitGen/Options.java

- keep buildList and projectRootDir case sensitive
[ci skip]

Fix Option issue in TKGJ

---

runtime/compiler/env/J9SharedCache.cpp

1) Existing code forgot to add the flag for the new hint being added
2) Exiting code used `storeAttachedData()` when adding a hint when another hint
for the same romMethod already existed. The SCC API returned an error code
indicating that hints already exist for the desired romMethod. In this case
we should use `storeAttachedData()`
3) Existing code forgot to write the value of the new count when just the
count needs to be updated in the hint area

Fix multiple bugs in TR_J9SharedCache::addHint()

---

buildenv/docker/jdk8/x86_64/rhel7/jitaas/build/Dockerfile
buildenv/docker/jdk8/x86_64/rhel7/jitaas/run/Dockerfile

Add rhel7 x86 Dockerfile

---

test/TestConfig/scripts/testKitGen/resultsSummary/resultsSum.pl

- corrected openjdk_ppc64_aix mapping to aix_ppc-64_cmprssptrs
[ci skip]
Close: #7026

Fixed Jenkinsfile SPEC mapping

---

runtime/shared_common/CacheMap.cpp

Readers can change the page protection when reading cache updates,
resulting in SIGSEGV if another thread is marking cache item stale. Lock
the cache to make sure there are no readers.
Fixes #6330

Lock the cache inside markItemStaleCheckMutex().

---

runtime/shared_common/CacheMap.cpp

Readers can change the page protection when reading cache updates,
resulting in SIGSEGV if another thread is marking cache item stale. Lock
the cache to make sure there are no readers.
Fixes #6330
Port of https://github.com/eclipse/openj9/pull/7038 for 0.16.0

(v0.16.0) Lock the cache inside markItemStaleCheckMutex().

---

runtime/gc/gctable.c
runtime/gc_api/HeapIteratorAPI.cpp
runtime/gc_base/gc_internal.h
runtime/gc_include/HeapIteratorAPI.h
runtime/oti/j9nonbuilder.h

There seems to be no callers of this API, so I'm removing it.
Signed-off-by: Robert Young <rwy0717@gmail.com>

WIP: Remove j9mm_arraylet_identification GC API

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/runtime/JITServerStatisticsThread.cpp

Port review suggestions for JITServerStatisticsThread to jitaas branch

---

runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/env/J9ClassEnv.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h

Merge common methods from JITServer, ClassEnv, and VM
This PR has dependency on eclipse/omr#4301.

Merge common methods from JITServer ClassEnv and VM

---

runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/compile/J9Compilation.hpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/env/J9ClassEnv.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/x/codegen/J9TreeEvaluator.cpp

Update `JITServerHelpers` to be ported into the master branch

Update JITServerHelpers to be ported into the master branch

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.hpp

This commit implements buildArgs(), buildDirectDispatch(), etc. for
ARM64PrivateLinkage.

AArch64: Implement buildArgs() and buildDirectDispatch() in PrivateLinkage

---

runtime/gc_modron_startup/CMakeLists.txt
runtime/redirector/CMakeLists.txt

CMake: update include paths for z/OS

---

runtime/util/CMakeLists.txt

CMake: Add zos specific sources to j9util

---

buildenv/jenkins/jobs/infrastructure/artifactory_cleanup.groovy

Added a try and catch block to Artifactory Cleanup script. 
runtimes/infrastructure#2361

Enhance Artifactory Cleanup script to Slack on error

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.hpp

* Implement loadStackParametersToLinkageRegisters
* Implement copyParametersToHomeLocation

Implement functions to load/spill linkage registers for private linkage

---

runtime/compiler/build/files/common.mk
runtime/compiler/compile/J9Compilation.cpp
runtime/compiler/compile/J9Compilation.hpp
runtime/compiler/control/CMakeLists.txt
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.hpp
runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/control/JITServerHelpers.hpp
runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/env/J9ClassEnv.hpp

Merge `JITServerHelpers` to the master branch.

Merge JITServerHelpers to the master branch

---

buildenv/jenkins/common/pipeline-functions.groovy

Switched the color from red to grey for aborted jenkins jobs
[skip ci]

Changed the color of slack messages into grey for aborted jenkins jobs

---

runtime/runtimetools/osmemory/OSMemoryAgent.hpp
runtime/tests/jni/jnitest.c

* add missing return in non-void function
* remove anonymous typedefs (xlc16 issues errors)
Issue #5074

Fix compile warnings/errors

---

test/TestConfig/run_configure.mk

- move the compilation statement out of if condition
[ci skip]

Fix tkg compilation issue when AUTO_DETECT=false

---

runtime/tests/zos/module.xml

Fix misnamed exports in zos native tests

---

test/TestConfig/scripts/tools/getDependencies.pl

Port of #6567 and #6574
[ci skip]

Update getDependencies.pl (v0.15.0-release)

---

jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java

Fix MH.insertArguments argument check

---

runtime/compiler/CMakeLists.txt

CMake: Add missing file to compiler excludes

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Recompilation.cpp
runtime/compiler/control/J9Recompilation.hpp
runtime/compiler/control/JITServerCompilationThread.hpp
runtime/compiler/control/RecompilationInfo.hpp
runtime/compiler/control/rossa.cpp
runtime/compiler/control/rossa.h
runtime/compiler/env/VMJ9.h
runtime/compiler/ilgen/IlGeneratorMethodDetails.hpp
runtime/compiler/ilgen/J9IlGeneratorMethodDetails.cpp
runtime/compiler/ilgen/J9IlGeneratorMethodDetails.hpp
runtime/compiler/net/StreamExceptions.hpp
runtime/compiler/runtime/J9Runtime.hpp
runtime/compiler/runtime/JitRuntime.cpp
runtime/compiler/runtime/RelocationRecord.cpp

Also a part of the preparation for merging `JITServerCompilationThread`.

Merge IlGeneratorMethodDetails related methods to master

---

buildenv/jenkins/common/build.groovy

Added retry and echo to Artifactory upload for testing purposes
Fixes #6808

Added retry and echo to Artifactory upload for testing purposes

---

debugtools/DDR_VM/src/com/ibm/j9ddr/J9DDRClassLoader.java
runtime/ddr/vmddr.cpp

Cherry-picking #7064 for the 0.17 release.

(v0.17.0) Generate DDR pointer classes dynamically as appropriate

---

runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.hpp
runtime/compiler/runtime/SymbolValidationManager.cpp
runtime/compiler/runtime/SymbolValidationManager.hpp

Merge `JITServerCompilationThread` from the `jitaas` branch.
The mirrored JITServer branch change is in PR #7200.

Merge JITServerCompilationThread

---

runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.hpp
runtime/compiler/runtime/SymbolValidationManager.cpp
runtime/compiler/runtime/SymbolValidationManager.hpp

Update `JITServerCompilationThread` to be merged into the `master` branch.
The mirrored master branch change is in PR #7201.

Update JITServerCompilationThread to be merged into master

---

test/TestConfig/TKGJ/src/org/testKitGen/MkTreeGen.java
test/TestConfig/TKGJ/src/org/testKitGen/TestInfo.java
test/TestConfig/makeGen.mk

- ignore case when matching JDK_VERSION
[ci skip]

Update TestKitGen Java for Valhalla and Panama

---

runtime/verbose/CMakeLists.txt

CMake: Fix platform specific flags in the verbose component

---

test/functional/Jsr292/src/com/ibm/j9/jsr292/AdaptorTests.java
test/functional/Jsr292/src/com/ibm/j9/jsr292/Crash.java

Update MH.asSpreader tests

---

runtime/bcutil/BuildResult.hpp
runtime/bcutil/ClassFileOracle.cpp
runtime/bcutil/ClassFileOracle.hpp
runtime/bcutil/ROMClassBuilder.cpp
runtime/bcutil/defineclass.c
runtime/nls/cfre/cfrerr.nls
runtime/oti/bcutil.h

pr to master: https://github.com/eclipse/openj9/pull/7041
Signed-off-by: Theresa Mammarella Theresa.T.Mammarella@ibm.com

0.17.0: Disallow duplicate LocalVariableTypeTable entries

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp

This commit sets register dependencies for AArch64 FP registers that
are not used as arguments on method calls.
FP registers are all volatile registers in PrivateLinkage.
This commit also excludes reserved GPRs (such as LR) from register
dependencies for method calls.

AArch64: Set dependencies for FP registers that are not method args

---

buildenv/jenkins/docker-slaves/x86/centos6.9/Dockerfile

Changed Cuda 7.5 to Cuda 9.0 for CentOS 6

---

runtime/rasdump/javadump.cpp

- When a dump is printed, the hook statistics are reset
- Changing the ms to us to reflect change in OMR.
- Dependant on omr change: https://github.com/eclipse/omr/pull/4221
Doc issue https://github.com/eclipse/openj9-docs/issues/364

Resetting dump statistics after event

---

runtime/rasdump/javadump.cpp

- When a dump is printed, the statistics are reset.
- A note was added in the HOOK subcomponant of dump routine to indicate stats are since previous javacore
- Changing the ms to us to reflect change in OMR.
- Dependant on omr change: https://github.com/eclipse/omr/pull/4221
Ported from #6822

(v0.17.0) Resetting dump statistics after event

---

runtime/libffi/CMakeLists.txt

CMake: Add zos support to libffi

---

jcl/src/openj9.cuda/share/classes/module-info.java
jcl/src/openj9.dataaccess/share/classes/module-info.java
jcl/src/openj9.dtfjview/share/classes/module-info.java
jcl/src/openj9.gpu/share/classes/module-info.java
jcl/src/openj9.jvm/share/classes/module-info.java
jcl/src/openj9.sharedclasses/share/classes/module-info.java
jcl/src/openj9.traceformat/share/classes/module-info.java
jcl/src/openj9.zosconditionhandling/share/classes/module-info.java

Add javadoc comments to openj9 modules

---

jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
jcl/src/java.base/share/classes/openj9/internal/tools/attach/diagnostics/base/DiagnosticProperties.java
runtime/bcutil/ROMClassCreationContext.hpp
runtime/oti/bcverify_api.h

Fix comments which contain incorrect whitespace characters.
Signed-off-by: Jiahan Xi <doomerXe@gmail.com>

Fix the incorrect whitespace characters on the comments

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ShrCCommand.java

Fix DDR shrc commands

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp

This commit adds a check in buildPrivateLinkageArgs() for AArch64.
When a method takes one or more integer arguments and the method
returns an address, the post-condition for the method call must
use a collected reference register for the return value.

AArch64: Use of collected reference reg in buildPrivateLinkageArgs()

---

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
jcl/src/java.base/share/classes/java/lang/invoke/MethodHandle.java
test/functional/Jsr292/src/com/ibm/j9/jsr292/indyn/BootstrapMethods.java
test/functional/Jsr292/src/com/ibm/j9/jsr292/indyn/Helper.java
test/functional/Jsr292/src/com/ibm/j9/jsr292/indyn/IndyTest.java
test/functional/Jsr292/src/com/ibm/j9/jsr292/indyn/SimpleIndyGenerator.java

Port from https://github.com/eclipse/openj9/pull/7067
Signed-off-by: Theresa Mammarella Theresa.T.Mammarella@ibm.com

v0.17.0: Indy error checking for null resolution Java 11+

---

runtime/rasdump/javadump.cpp

A replay of #7341 for the 0.17.0 release branch.

(v0.17.0) Adjust hook section in javacore files

---

runtime/vm/CMakeLists.txt

CMake: add missing sources to vm for zos

---

debugtools/DDR_VM/.gitignore

Those files are now generated within the build directory.

Remove ignore for files which are now generated elsewhere

---

runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/runtime/RelocationRuntime.cpp
runtime/compiler/runtime/RelocationRuntime.hpp

Merge `JITServerRelocationRuntime` from the `jitaas` branch.
The mirrored JITServer change is in #7237.

Merge JITServerRelocationRuntime from the jitaas branch

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Add a register map to ARM64HelperCallSnippet for gc safe point helpers
because helper call snippets use branch-and-link instruction to call helpers.
Depends on https://github.com/eclipse/omr/pull/4400

AArch64: Add a register map to snippet gc map of ARM64HelperCallSnippet

---

buildenv/aix/jdk11/yum_install_aix-ppc64.txt
buildenv/aix/jdk13/yum_install_aix-ppc64.txt
buildenv/docker/jdk13/ppc64le/ubuntu16/Dockerfile
buildenv/docker/jdk13/s390x/ubuntu16/Dockerfile
buildenv/docker/jdk13/x86_64/ubuntu16/Dockerfile
doc/build-instructions/Build_Instructions_V13.md

Add missing build instructions and docker/yum artifacts.
Remove unsupported JDK yum files
[ci-skip]

Add detailed build instructions for OpenJDK 13

---

runtime/jcl/exports.cmake

CMake: Fix typos in jcl exports

---

runtime/vm/xa64/unsafeHelper.m4

Fix unsafeHelper.m4 to use correct mov instruction.

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ByteCodeDumper.java

* extract and reuse behavior from tableswitch bytecode
* reduce cost of setting j9bcutil_dumpBytecodes in the environment
Fixes #7349

Fix allowance for padding after lookupswitch bytecode

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/runtime/IProfiler.cpp
runtime/compiler/runtime/RelocationRecord.cpp
runtime/compiler/runtime/RelocationRuntime.cpp
runtime/compiler/runtime/RelocationRuntime.hpp
runtime/compiler/runtime/SymbolValidationManager.cpp

Update `JITServerRelocationRuntime` to be merged into the `master` branch.
The mirrored master change is in #7236.

Update JITServerRelocationRuntime to be merged into master

---

runtime/compiler/aarch64/codegen/StackCheckFailureSnippet.cpp

This commit fix GC Map set to StackCheckFailureSnippet.
- Reset stack map bits for parameter passed in the register
- Set register map bits for parameters passed in the register

AArch64: Fix GC Map set to StackCheckFailureSnippet

---

runtime/vm/xa64/unsafeHelper.m4

(v0.17.0) Fix unsafeHelper.m4 to use correct mov instruction.

---

debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ByteCodeDumper.java

* extract and reuse behavior from tableswitch bytecode
* reduce cost of setting j9bcutil_dumpBytecodes in the environment
This is a replay of #7357 for the 0.17 release branch.

(v0.17.0) Fix allowance for padding after lookupswitch bytecode

---

runtime/compiler/runtime/MetaData.cpp

Enable reloLogging for JITServer

---

jcl/src/jdk.jcmd/share/classes/module-info.java

Add a javadoc comment to the jdk.jcmd module.

---

runtime/codert_vm/decomp.cpp

At an exception catch point in jitted code, there could be any number of
inlines, e.g.
```
void blah() throws Exception {
throw new Exception();
}
void bar(Exception e) {
e.printStackTrace();
}
void foo(Exception e) {
bar(e);
}
void example() {
try {
blah();
} catch(Exception e) {
foo(e);
}
}
```
The previous code was thinking like the interpreter - the catching stack
must be a subset of the throwing stack, which is not true in the example
above.
With full inlining, the stack at the catch point could be:
```
bar
foo
example
```
When decompiling at a catch, rather than depending on subsetting,
discard any existing decompilation for the frame and perform a new OSR
at the catch point with the correct stack.
[ci skip]

Fix decompile at exception catch

---

runtime/util/filecache.c
runtime/util/filecache.h

The original names could conflict with other defines.

Rename badly named util/filecache constants

---

runtime/compiler/CMakeLists.txt

Add cmake support for building the jit on aix

---

buildenv/jenkins/variables/defaults.yml

* [skip ci]
* eclipse/openj9#7331

Update bootjdks for jdknext/14 to use jdk13

---

runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/runtime/IProfiler.hpp
runtime/compiler/runtime/JITClientSession.cpp
runtime/compiler/runtime/JITClientSession.hpp
runtime/compiler/runtime/RelocationRuntime.cpp
runtime/compiler/runtime/RelocationRuntime.hpp

Reverts eclipse/openj9#7438
Merged the wrong PR

Revert "Port TR_J9JITServerSharedCache from jitaas to master"

---

buildenv/jenkins/common/pipeline-functions.groovy

Issue: runtimes/backlog/issues/167
[ci skip]

Add EXTRA_OPTIONS for jck tests

---

runtime/compiler/optimizer/EscapeAnalysis.cpp
runtime/compiler/optimizer/J9Inliner.cpp

- Use FrontEnd API `isClassLoadedBySystemClassLoader()`.

Port JITSERVER change in Optimizer to the master branch

---

buildenv/jenkins/common/pipeline-functions.groovy

Retry the function set_build_status and catch its failure

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.hpp

* entryPointFromCompiledMethod
* entryPointFromInterpretedMethod

Implement linkage entry point functions for ARM64PrivateLinkage

---

runtime/compiler/control/JITServerHelpers.cpp
runtime/compiler/env/J2IThunk.cpp
runtime/compiler/env/J9ObjectModel.cpp
runtime/compiler/env/J9VMEnv.cpp
runtime/compiler/env/J9VMMethodEnv.cpp

Backport the following changes:
https://github.com/eclipse/openj9/pull/7319
https://github.com/eclipse/openj9/pull/7485

Backport various changes from master

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy

Added an option to send slack message when a build passes

---

runtime/compiler/control/CompilationController.cpp
runtime/compiler/control/CompilationController.hpp

Remove unused RemoteCompilationRequest methodEvent

---

runtime/compiler/env/J2IThunk.cpp
runtime/compiler/env/J9ObjectModel.cpp
runtime/compiler/env/J9VMEnv.cpp
runtime/compiler/env/J9VMMethodEnv.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9method.h

Most of the changes are related to formatting.

Merge JITServer update in env directory

---

test/functional/Jsr335/playlist.xml
test/functional/Jsr335_interfaceStaticMethod/playlist.xml
test/functional/cmdLineTests/gcRegressionTests/playlist.xml
test/functional/cmdLineTests/shareClassTests/ListAllCachesTests/playlist.xml

Support running functional test targets against hs implementation

Update J9 specific test targets

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/CompilationThread.hpp
runtime/compiler/env/VMJ9Server.cpp

Backport CompilationThread.cpp/hpp changes from master

---

buildenv/jenkins/docker-slaves/ppc64le/centos7/Dockerfile
buildenv/jenkins/docker-slaves/s390x/ubuntu16/Dockerfile
buildenv/jenkins/docker-slaves/x86/centos6.9/Dockerfile

Add bootjdk 13 to Dockerfiles

---

runtime/compiler/CMakeLists.txt

CMake: Link jit statically against c++ standard lib

---

runtime/compiler/env/VMJ9.cpp
runtime/compiler/runtime/CMakeLists.txt

Remove JITSERVER_TODO macro

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/CompilationThread.hpp
runtime/compiler/control/MethodToBeCompiled.hpp
runtime/compiler/ilgen/J9IlGeneratorMethodDetails.cpp
runtime/compiler/ilgen/J9IlGeneratorMethodDetails.hpp

This reverts commit ac10cd3d859fdec5e75a7adb944e89c08e8736fc.

Revert "Merge JITServer changes to CompilationThread.cpp/hpp"

---

runtime/gc_base/GCObjectEvents.cpp
runtime/gc_base/ScavengerForwardedHeader.cpp
runtime/gc_base/ScavengerForwardedHeader.hpp
runtime/gc_base/StringTable.cpp
runtime/gc_check/CheckEngine.cpp
runtime/gc_vlhgc/CopyForwardScheme.cpp

Revert "Runtime compressed refs work"

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/CompilationThread.hpp
runtime/compiler/control/MethodToBeCompiled.hpp
runtime/compiler/ilgen/J9IlGeneratorMethodDetails.cpp
runtime/compiler/ilgen/J9IlGeneratorMethodDetails.hpp

This PR reinstates the JITServer changes delivered in #7454 (and reverted in #7551) plus a bug fix related to properly failing recompilations.

Port CompilationThread changes for JITServer

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/J9KnownObjectTable.cpp
runtime/compiler/env/annotations/GPUAnnotation.cpp
runtime/compiler/p/codegen/J9AheadOfTimeCompile.cpp
runtime/compiler/x/codegen/J9AheadOfTimeCompile.cpp

Backport control-related changes from master to jitaas

---

test/README.md
test/docs/OpenJ9TestUserGuide.md

- update the instruction on how to execute a directory of tests
[ci skip]

Update test documents

---

buildenv/jenkins/common/pipeline-functions.groovy

Wrapped the function setup_pull_request and
made calls to it according to the number of
trigger comments

Make Jenkins trigger parsing more forgiving

---

runtime/compiler/CMakeLists.txt
runtime/compiler/z/codegen/CMakeLists.txt
runtime/compiler/z/env/CMakeLists.txt
runtime/compiler/z/runtime/CMakeLists.txt

CMake: Add s390 support to the compiler

---

runtime/compiler/ilgen/IlGenerator.cpp
runtime/compiler/ilgen/Walker.cpp
runtime/compiler/ras/DebugExt.cpp
runtime/compiler/runtime/ClassUnloadAssumption.cpp
runtime/compiler/runtime/MetaData.cpp
runtime/compiler/runtime/MetaDataDebug.cpp
runtime/compiler/runtime/RelocationRecord.cpp
runtime/compiler/runtime/RelocationTarget.hpp
runtime/compiler/runtime/SymbolValidationManager.cpp
runtime/compiler/z/runtime/Recomp.cpp

Back port various changes from master to jitaas

---

runtime/compiler/p/codegen/J9AheadOfTimeCompile.cpp

Add TR_MethodCallAddress to the relo runtimes table on Power

---

runtime/compiler/optimizer/EscapeAnalysis.cpp

Ordinarily Escape Analysis avoids fix-up of fields of stack allocated objects in cold block escapes, but as a special case, fix-up still happens for immutable discontiguous objects, as the initialization of the temporary used to represent a field of such an object might end up in such a cold block.
However, the fix-up for the fields of such an object in a cold block escape was happening for both loads and stores.  That's not usually a problem except if the load refers to the vft-symbol, as no temporary is ever properly initialized to represent the vft-symbol for a discontiguously stack allocated object.
Avoided this situation by only performing the special case fix-up for immutable discontiguously stack allocated objects for store operations.  It's safe to load the field from the …

Avoid load rewrites for cold escapes of immutable discontiguous objects

---

buildenv/jenkins/docker-slaves/ppc64le/centos7/Dockerfile
buildenv/jenkins/docker-slaves/ppc64le/ubuntu16/Dockerfile
buildenv/jenkins/docker-slaves/ppc64le/ubuntu18/Dockerfile
buildenv/jenkins/docker-slaves/s390x/ubuntu16/Dockerfile
buildenv/jenkins/docker-slaves/s390x/ubuntu18/Dockerfile
buildenv/jenkins/docker-slaves/x86/centos6.9/Dockerfile
buildenv/jenkins/docker-slaves/x86/ubuntu16/Dockerfile
buildenv/jenkins/docker-slaves/x86/ubuntu18/Dockerfile

- No longer need JSON, Text::CSV or XML::Psrser
- https://github.com/eclipse/openj9/blob/master/test/docs/Prerequisites.md

Remove perl modules no longer required

---

runtime/compiler/x/codegen/J9TreeEvaluator.cpp

Put back the `inlineMathSQRT` function and the related switch cases on X86. Because the transformation to `dsqrt` (changes in #6217) will not be triggered in X86 and Power, leading to slow performance on calling the `StrictMath.sqrt` and `Math.sqrt` to the VM which implements the function. 
We'll keep the `inlineMathSQRT` on X86 for now. And then we'll work on the proper solution (reduce the call to a proper `dsqrt` evaluator).
Fixes: #7525
Signed-off-by: simonameng <simonameng97@gmail.com>

Restore the inline handling for 'StrictMath.sqrt()' and 'Math.sqrt()' on X86

---

buildenv/jenkins/variables/defaults.yml

Enable CUDA in pLinux builds

---

jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassURLClasspathHelperImpl.java

Add checks for invalidURLExists before calling notifyClasspathChange3()

---

buildenv/jenkins/variables/defaults.yml

Enable special.system AIX jdk8, plinux & zlinux jdk11

---

runtime/compiler/ilgen/Walker.cpp

Don't duplicate array on stack when check is not needed

---

runtime/compiler/env/J9SharedCache.cpp

TR_J9JITServerSharedCache is instantiated on JITServer which always invokes the TR_J9SharedCache constructor but it won't have a _sharedCacheConfig.

Guard TR_J9SharedCache constructor for JITServer

---

buildenv/jenkins/common/build.groovy

Captured diagnostic files created during build job for zos spec, and renamed it.
Imported libraries for pattern matching

Capture diagnostic files created during build job for zos spec

---

runtime/compiler/p/codegen/J9TreeEvaluator.cpp

Use FE query to do instanceOfOrCheckcast check on Power

---

runtime/compiler/control/CompilationThread.cpp

When JITServer is at the "early translation" stage and JITClient issues 
an interruption, an exception will be thrown in the next JITServer read. 
However, the catch statement did not include handling of `StreamInterrupted`
exceptions and as a result will treat the interruption as a `compilationFailure` . 
An client-issued interruption and an actual compilationFailure are handled differently. 
For the actual `compilationFailure`, JITserver has to inform JITclient about the 
compilation failure so it terminates the compilation on its end. But for an interruption, 
JITClient already took action and terminated the compilation so JITserver should not 
remind JITClient about it again.
[skip ci]

Add missing JITServer StreamInterrupted handle

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/JITClientCompilationThread.cpp

The main cause of the message type mismatches is
due to JITServer/JITClient messages not being 1-to-1. 
In order to make sure that the messages always get 
received by the correct receiver, we must avoid double
sending of messages.
In this problem, JITClient sends a compilationRequest 
but immediately realized that it needs to abort the 
compilation so it sends another "writeError()" message. 
This double sending from the JITClient has caused both 
JITServer and JITClient not receiving correct messages 
sometimes. We eliminated the double sending and resolved 
the issue by having the JITClient wait for the next message
from JITServer before sending out the "writeError()" message.
Additionally, when JITServer is at the "early translation" 
stage and JITClient issues an interruption, an …

Fix JITServer message type mismatch

---

test/functional/Valhalla/playlist.xml
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java

This commit adds tests for the GC scanning of flattened arrays.
Signed-off-by: Adithya Venkatarao <adi_101@live.com>

Testing the GC scanning of flattened value types in arrays

---

runtime/compiler/ilgen/Walker.cpp

Generate aconst node for constant ref pointing to null

---

runtime/compiler/build/scripts/s390m4check.pl

As part of the error message print out the text of the failing line.

Print out the failing line in s390m4check.pl

---

runtime/compiler/aarch64/codegen/CallSnippet.cpp

This commit implements TR_Debug::print() for VirtualUnresolvedSnippet
and InterfaceCallSnippet for AArch64.

AArch64: Implement print() for CallSnippets

---

buildenv/jenkins/docker-slaves/ppc64le/centos7/Dockerfile
buildenv/jenkins/docker-slaves/ppc64le/ubuntu16/Dockerfile
buildenv/jenkins/docker-slaves/ppc64le/ubuntu18/Dockerfile

* eclipse/openj9#7099
* [skip ci]

Add protobuf to plinux containers

---

runtime/gc_vlhgc/CopyForwardScheme.cpp

The regression was introduced by the optimization in copyforward scheme
(#3922), which does not clear soft/weak reference during copyforward,
hence keep them alive till GMP that will eventually clear them. It
artificaially increases promotion/tenuring and causes the more frequent
GMPs.
Rollback code partially, to fix the issue.

Fix the copyforward regression

---

runtime/vm/ModularityHashTables.c

Use direct call rather than internalVMFunction table

---

runtime/compiler/runtime/Trampoline.cpp

This change enables the materializing of addresses in trampoline
sequences with IIHF and IILF instructions by default (on supported
architectures - Z). This saves us a memory reference
and potential cache misses.
We can enable this by default as the mininumALS on Z is now Z9.
Signed-off-by: Pushkar Bettadpur <pushkar.bettadpur@gmail.com>

Enables TR_IIHF in trampoline sequences by default

---

buildenv/jenkins/docker-slaves/x86/ubuntu16/Dockerfile
buildenv/jenkins/docker-slaves/x86/ubuntu18/Dockerfile

Add `--disable-shared --with-pic` for consistency with other Dockerfiles.

Update protobuf configure options

---

buildenv/docker/jdk8/s390x/ubuntu18/Dockerfile

Fix s390x Ubunutu18 Dockerfile to be able to complete the configure step

---

runtime/compiler/z/codegen/CMakeLists.txt

J9S390PrivateLinkage.cpp -> S390PrivateLinkage.cpp

CMake: Update source file name in jit s390 codegen

---

runtime/compiler/p/codegen/J9PPCInstruction.cpp

This is a double delivery of #7384

Direct call fixes for JITServer on Power

---

runtime/compiler/ilgen/Walker.cpp

This is a double delivery of #7385

Disable use of TR_VMField on JITServer

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

Check if getClass returns NULL before trying to do instanceOf with its
result.

Handle the case where getClass returns NULL

---

runtime/compiler/il/J9Node.cpp
runtime/compiler/p/codegen/PPCJNILinkage.cpp

This is a double delivery of #7391

Disable JNI specialCasing of java_util_zip_CRC32_updateBytes

---

runtime/compiler/p/codegen/CallSnippet.cpp

This is a double delivery of #7386

Use JITServer check to create a relocation record for interface calls on Power

---

runtime/compiler/p/codegen/J9CodeGenerator.cpp
runtime/compiler/p/codegen/J9PPCSnippet.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/p/codegen/PPCPrivateLinkage.cpp

loadAddressConstant's definition was recently changed in OMR. This commit updates the consumers of this API in order to conform to the new API definition.

Update consumers of loadAddressConstant API

---

test/functional/cmdLineTests/shareClassTests/URLHelperTests/APITests/NullPointerAndEmptyArrayTest.java
test/functional/cmdLineTests/shareClassTests/URLHelperTests/URLHelperTests.xml
test/functional/cmdLineTests/shareClassTests/URLHelperTests/URLHelperTests_80.xml

Added the test cases of
1. empty url array
2. url array with invalid urls
on the URLHelperTests
Fixes: #7627
Signed-off-by: Jiahan Xi <doomerXe@gmail.com>

Added the Test cases on URLHelperTests

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/CompilationThread.hpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.hpp

Properly free CompilationInfoPerThread resources
Fixes: #7338

Properly free CompilationInfoPerThread resources(JITServer)

---

buildenv/jenkins/common/pipeline-functions.groovy

Remove use of variable that is no longer defined

---

runtime/port/CMakeLists.txt

CMake: link port library with iconv on osx and aix

---

buildenv/jenkins/jobs/infrastructure/promote_repo.groovy
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy

- Completely removing this code since Promote-OpenJDK
doesn't use it either.
[skip ci]
fixes #7902

Stop tagging OMR promotions

---

buildenv/jenkins/README.md
buildenv/jenkins/jobs/infrastructure/wrapper_variables.yml
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
buildenv/jenkins/variables/defaults.yml
test/TestConfig/scripts/resultsSum.pl
test/functional/JLM_Tests/playlist.xml

Fixes #7856
This builds on the commit from #7858 to avoid any merge conflicts.

Add support for plinux large heap builds

---

runtime/jvmti/jvmtiStartup.c

**Skip code page encoding converting for an empty options string**
An empty options string can be passed to `agentInitFunction` directly.
There is no need to perform code page encoding.

Skip code page encoding converting for an empty options string

---

runtime/j9vm/exports.cmake

CMake: Update exports of j9vm

---

test/functional/VM_Test/src/j9vm/test/romclasscreation/NewROMCreationAfterModifyingExistingClassTestRunner.java

Use a cache name for NewROMCreationAfterModifyingExistingClassTest

---

runtime/compiler/runtime/JITServerIProfiler.cpp

JITServerIProfiler::setCallCount uses two types of caches to reduce
the number of messages sent to the client: a per-client cache which
uses persistent memory and a per-compilation cache which uses scratch
memory. The memory leak happens because we use persistent memory to
store an entry in the per-compilation cache. This cache will vanish
when the compilation is over because all of the backing scratch
memory segments are returned to the OS but the attached entries
allocated with persistent memory will leak.
The fix is to use scratch memory for the per-compilation cache and
persistent memory for the per-client cache.

Fix memory leak in JITServer related to IProfiler

---

runtime/j9vm/exports.cmake

Invert if for Java 11

---

test/functional/CacheManagement/src/tests/sharedclasses/TestUtils.java
test/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheJavaAPI.java

Remove unnecessary debug print

---

runtime/compiler/aarch64/codegen/ARM64RecompilationSnippet.cpp
runtime/compiler/aarch64/codegen/ARM64RecompilationSnippet.hpp
runtime/compiler/aarch64/codegen/CMakeLists.txt
runtime/compiler/build/files/target/aarch64.mk

This commit adds the class ARM64RecompilaitonSnippet.

AArch64: Implement ARM64RecompilationSnippet

---

runtime/vm/createramclass.cpp

* typo: instace -> instance
* add missing classFlag: J9ClassContainsUnflattenedFlattenables
* fix position of classFlag: J9ClassCanSupportFastSubstitutability
* remove trailing whitespace

Fix comments

---

runtime/gc_modron_standard/StandardAccessBarrier.cpp

The standard read barrier may be triggered even when there is no
scavenger.  Check to see if scavenger is enabled before performing
preObjectRead().
cc @dmitripivkine @amicic

Check for scavenger in preObjectRead

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.hpp

This commit implements ZEROCHKEvaluator for AArch64.

AArch64: Implement ZEROCHKEvaluator

---

sourcetools/j9constantpool/CMakeLists.txt

CMake: Fix classpath for j9vmcp on cygwin

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Options.hpp

Increase scratchSpaceLimit by a factor of 2 on JITServer
[skip ci]
Issue: #5644

Increase scratchSpaceLimit for JITServer

---

buildenv/jenkins/common/variables-functions.groovy
buildenv/jenkins/variables/defaults.yml

Jenkins: Implement inheritance between builds specs

---

buildenv/jenkins/variables/defaults.yml

Remove hardcoded jobs=8 from AIX configure options

---

runtime/compiler/control/CompilationRuntime.hpp
runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/CompilationThread.hpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.hpp

Properly free CompilationInfoPerThread resources
Port the change #7655 from the `jitaas` branch to the `master` branch. 
Fixes: #7338

Properly free CompilationInfoPerThread resources

---

runtime/gc_glue_java/MarkingDelegate.hpp

Fix compilation failure

---

runtime/gc/gctable.c
runtime/gc_base/ObjectAccessBarrier.cpp
runtime/gc_base/ObjectAccessBarrier.hpp
runtime/gc_base/accessBarrier.cpp
runtime/gc_base/gc_internal.h
runtime/gc_include/ObjectAccessBarrierAPI.hpp
runtime/oti/j9nonbuilder.h
runtime/vm/BytecodeInterpreter.hpp

Refactor flattened array barrier API

Refactor flattened array barrier API

---

jcl/src/java.base/share/classes/java/lang/Class.java

Fixes: https://github.com/eclipse/openj9/issues/7973

JCL Stubs for JEP 359

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy

Add auto-refresh of the downstream jobs status summary (optional,
disabled by default). When enabled, it displays the current status of
the downstream builds as they progress with a small delay.
The auto-refresh rate is set to 5 minutes by default.
Reduce verboseness on auto-refresh: remove elapsed time info in the
get_downstream_builds() function.
[ci skip]

Add downstream pipelines status auto-refresh

---

runtime/cmake/platform.cmake

CMake: use ".so" as shared lib extension on aix

---

jcl/src/java.base/share/classes/java/lang/Class.java

Class.isRecord stub to always return false

---

debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/memory/BufferedMemory.java
debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/memory/BufferedMemorySource.java

* put files in the directory matching the package declaration
* remove unused imports

Tidy up BufferedMemory & BufferedMemorySource

---

buildenv/docker/jdk8/x86_64/rhel7/jitserver/build/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu16/jitserver/build/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu16/jitserver/buildenv/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu16/jitserver/buildserver/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu18/jitserver/build/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu18/jitserver/buildenv/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu18/jitserver/buildserver/Dockerfile
doc/compiler/jitserver/Build.md

Use multi-stage builds to minimize the size of the final image.
Once the JDK is built, we will throw away all the build time dependencies and only keeping the runtime dependencies.
[skip ci]

Update JITServer Dockerfile

---

buildenv/jenkins/variables/defaults.yml

Remove extra variables that got set for the cmake buildspec

Fix problems with jenkins inheritance pr

---

buildenv/jenkins/common/pipeline-functions.groovy

Catch PR trigger Jenkins test compile

---

runtime/compiler/codegen/J9CodeGenerator.cpp
runtime/compiler/codegen/J9CodeGenerator.hpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.hpp

Add new needRelocationsForCurrentMethodPC query

---

runtime/gc_realtime/MetronomeAlarm.cpp
runtime/gc_realtime/MetronomeAlarm.hpp

Replace metronome usage of deprecated Windows timeSetEvent()

---

runtime/compiler/env/j9method.cpp

Reflect new changes from JIT in JITServer.
Original JIT change can be found here
https://github.com/eclipse/openj9/pull/6305
Issue: #7674

Fix JITServer java_lang_invoke_PermuteHandle_permuteArgs

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp
runtime/compiler/optimizer/J9Inliner.hpp

Propagate arg info from caller

---

buildspecs/linux_riscv64.spec
buildspecs/linux_riscv64_cmprssptrs.spec
buildspecs/linux_riscv64_cmprssptrs_cross.spec
buildspecs/linux_riscv64_cross.spec

We don't have build machines at the moment.

Disable auto-build for RISC-V build specs

---

buildspecs/linux_riscv64.spec
buildspecs/linux_riscv64_cmprssptrs.spec
buildspecs/linux_riscv64_cmprssptrs_cross.spec
buildspecs/linux_riscv64_cross.spec

`build_product` cannot be `true` unless `build_autobuild == true`

RISC-V: set build_product to false

---

runtime/compiler/env/j9method.cpp

Reflect new changes from JIT in JITServer.
Original JIT change can be found here
https://github.com/eclipse/openj9/pull/6305
Issue: #7674

Mirror new changes in JIT to JITServer

---

jcl/jpp_configuration.xml

Merge Java12 flag into configuration for Java13.

Remove obsolete configuration for Java12

---

doc/release-notes/0.18/0.18.md

Draft release notes to support changes in 0.18 milestone 1.
[ci skip]

Add release notes for 0.18 milestone one

---

buildenv/jenkins/variables/admin_list.yml

Add new committer to admin_list.yml

---

test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-3.xml
test/functional/cmdLineTests/shareClassTests/SCCMLTests/exclude.xml
test/functional/cmdLineTests/shareClassTests/SCCMLTests/exclude_openj9.xml

Added the command line tests & a javacore test for the Multi-layer caches sub-options:
```
-Xshareclasses:layer=<number>
-Xshareclasses:createLayer
-Xshareclasses:printTopLayerStats[=option[+s]]
```
Issue #5480
Signed-off-by: Jiahan Xi <doomerXe@gmail.com>

Added the tests for the Multi-layer caches sub-options

---

buildenv/jenkins/variables/defaults.yml

Don't exclude special.system testing on the 0.18 branch

---

buildenv/jenkins/variables/defaults.yml

Re-enable special.system jdk8 testing on Windows

---

buildenv/jenkins/variables/defaults.yml

Reverts eclipse/openj9#8126
Re-instate the change, #8123 still occurs with it reverted.

Revert "Revert "Don't exclude special.system testing on the 0.18 branch""

---

test/.gitignore
test/Utils/.classpath
test/functional/IllegalAccessError_for_protected_method/.classpath
test/functional/JIT_Test/.classpath
test/functional/Java8andUp/.classpath
test/functional/Java9andUp/.classpath
test/functional/Jsr292/.classpath
test/functional/Jsr335/.classpath
test/functional/SharedCPEntryInvokerTests/.classpath
test/functional/TestExample/.classpath
test/functional/TestUtilities/.classpath
test/functional/UnsafeTest/.classpath
test/functional/Valhalla/.classpath

- change test lib location to TKG/lib
[ci skip]

Update test lib location

---

runtime/compiler/codegen/J9TreeEvaluator.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/VMJ9.h
runtime/compiler/env/VMJ9Server.cpp
runtime/compiler/env/VMJ9Server.hpp
runtime/compiler/net/protos/compile.proto
runtime/compiler/z/codegen/J9TreeEvaluator.cpp

This PR is a double delivery of #6909

Use FrontEnd implementations of instanceOfOrCheckCast routines

---

runtime/compiler/runtime/ValueProfiler.cpp

When adding new values to a JProfiling table, it is necessary for the
JIT helpers to lock the table in question to avoid conflicts. However,
the previous method of locking involved a data race on the _metaData
field. Specifically, the read of _metaData to determine the value to
CAS was not atomic. The result was that xlc compiled this into two
reads, one of _metaData.otherIndex and one of _metaData.rawData. If
another thread were to release the lock in between these two reads, this
could result in the value swapped into _metaData having otherIndex < 0,
which would trigger the "JIT access not disabled" assert.
This has been corrected by performing a single volatile read of
_metaData to determine what value to use. While it's not clear that this
eliminates all undefined behaviour here, it …

Fix data race when locking JProfiling tables

---

runtime/compiler/aarch64/codegen/ARM64JNILinkage.cpp

Implement `adjustReturnValue` helper method in JNILinkage for aarch64.
Depends on https://github.com/eclipse/openj9/pull/7972

AArch64: Implement adjustReturnValue in JNILinkage

---

runtime/compiler/runtime/ValueProfiler.cpp

This PR applies #8148 to the OpenJ9 0.18 release branch.

0.18: Fix data race when locking JProfiling tables

---

runtime/codert_vm/armnathelp.m4

Fix ARM 32bit jit helpers

---

buildenv/jenkins/variables/defaults.yml

Enable JIT Server for xlinux jdk8 and jdk11

---

buildenv/jenkins/variables/defaults.yml

`--enable-jitserver` and `--enable-jitserver=yes` have the same effect.

Configure option '--enable-jitserver' does not need a value

---

runtime/vm/exceptionsupport.c

Add missing params to exception msg

Add missing params to exception msg

---

buildenv/jenkins/common/pipeline-functions.groovy

Format a better error message when a bad spec is requested in a PR

---

jcl/src/openj9.traceformat/share/classes/com/ibm/jvm/traceformat/TraceFormat.java

Don't consider TraceFormat.dat in OpenJ9 builds

---

buildenv/jenkins/variables/defaults.yml

- JITServer
- Build Node Lables
- OpenSSL
- Build Environment
- RELEASE variable
- Configure options
- Freemarker
- Repository Cache
[skip ci]

Extend Spec Inheritance for remaining components

---

runtime/compiler/runtime/IProfiler.cpp

Closes https://github.com/eclipse/openj9/issues/7890

Check if pointer is in the SCC before loading it

---

runtime/compiler/runtime/IProfiler.cpp

Cherry-picked from https://github.com/eclipse/openj9/pull/8227

Check if pointer is in SCC before loading it (0.18.0)

---

buildenv/jenkins/variables/defaults.yml

Build openssl support in aarch64 builds

---

buildenv/jenkins/variables/defaults.yml

Enable JIT Server for xlinux jdk8 and jdk11 (0.18.0)

---

buildenv/jenkins/docker-slaves/ppc64le/centos7/Dockerfile
buildenv/jenkins/docker-slaves/s390x/ubuntu16/Dockerfile
buildenv/jenkins/docker-slaves/x86/centos6.9/Dockerfile
buildenv/jenkins/jobs/infrastructure/Update-Reference-Repos.groovy
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
buildenv/jenkins/variables/defaults.yml

- Remove refs to jdk12
- Reference repos
- Docker slaves
- PBT-All
- Variable file
[skip ci]

Add JDK14 to pipelines

---

buildenv/jenkins/variables/defaults.yml

Enable JIT Server for plinux jdk8 and jdk11

---

buildenv/jenkins/common/pipeline-functions.groovy

- When a multiline PR trigger is used,
only pass down the line that fired
the job. The rest is unnecessary.
- Build.groovy uses the comment but is
expecting it to be a single line.
- There was a bug where if you had the keyword
'depends' in your comment then the code would
go down the path of looking for dependent changes.
Follows #7509
[skip ci]

Only pass down single line trigger comment

---

jcl/src/java.base/share/classes/java/lang/Class.java
test/functional/Java8andUp/src/org/openj9/test/reflect/GetMethodsTests.java
test/functional/Java8andUp/src_80/org/openj9/test/java/lang/Test_Class.java
test/functional/Java8andUp/src_90/org/openj9/test/java/lang/Test_Class.java

Reverts eclipse/openj9#7788
Reverting because this causes #8255

Revert "master: Apply #311 to Java 8"

---

jcl/src/java.base/share/classes/java/lang/Class.java
test/functional/Java8andUp/src/org/openj9/test/reflect/GetMethodsTests.java
test/functional/Java8andUp/src_80/org/openj9/test/java/lang/Test_Class.java
test/functional/Java8andUp/src_90/org/openj9/test/java/lang/Test_Class.java

Reverts eclipse/openj9#8134
Reverting this as it introduces #8255

Revert "0.18.0: Apply #311 to Java 8"

---

doc/release-notes/0.18/0.18.md

Updated to include HotSpot compatibility options, JITServer
tech preview and the removal of a Javadoc issue.

Update release notes for milestone 2

---

runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/runtime/IProfiler.cpp

Fixes https://github.com/eclipse/openj9/issues/7890

Check if offset is in the SCC before loading it

---

runtime/compiler/env/J9SharedCache.cpp
runtime/compiler/env/J9SharedCache.hpp
runtime/compiler/runtime/IProfiler.cpp

Cherry pick of https://github.com/eclipse/openj9/pull/8261
Closes https://github.com/eclipse/openj9/issues/7890

0.18: Check if offset is in the SCC before loading it

---

jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/LoggingMXBeanImpl.java

Don't initialize LogManager class prematurely

---

debugtools/DDR_VM/.classpath
jcl/jpp_configuration.xml
jcl/src/com.ibm.jzos/share/classes/com/ibm/jzos/ZFile.java
jcl/src/com.ibm.jzos/share/classes/module-info.java
jcl/src/java.base/share/classes/java/lang/System.java

Depends on:
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/358
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/249
https://github.com/ibmruntimes/openj9-openjdk-jdk14/pull/5
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/162
Closes #8297

Use com.ibm.jvm.io.ConsolePrintStream.localize for z/OS

---

buildenv/jenkins/variables/defaults.yml

Debugging for #8173, create diagnostic files if the problem occurs again.

Add -Xdump on ClassCastException to osx,xlinux builds

---

jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/LoggingMXBeanImpl.java

A replay of #8319 for the 0.18.1 release branch.

(v0.18.0.1) Don't initialize LogManager class prematurely

---

runtime/compiler/optimizer/InlinerTempForJ9.cpp

Add String.charAt in list of alwaysWorthInlining list

Add String.charAt in list of alwaysWorthInlining list

---

buildenv/docker/jdk8/s390x/ubuntu16/jitserver/test/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu16/jitserver/test/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu18/jitserver/test/Dockerfile
doc/compiler/jitserver/Testing.md
test/README.md
test/docs/OpenJ9TestUserGuide.md

- update files to remove run_configure.mk step
[ci skip]

Update TKG running process

---

runtime/ddr/CMakeLists.txt

CMake: Link ddr_misc with -bexpall on aix

---

test/docs/OpenJ9TestUserGuide.md

- runtest target will be replaced with _all
[ci skip]

Remove runtest target from test guide

---

buildenv/jenkins/common/variables-functions.groovy

- Was broken due to #8098
[skip ci]

Use getScalarField to set TEST_FLAG

---

runtime/verbose/CMakeLists.txt

CMake: fix j9vrb on clang

---

buildenv/jenkins/jobs/infrastructure/artifactory_cleanup.groovy

- The subfolder 'Test' is added to test jobs when
they upload to Artifactory. This extra bit is set in
the Test Autogen job.
[skip ci]

Add Test subfolder to repo path

---

runtime/gc_vlhgc/VLHGCAccessBarrier.cpp

Empty arraylets are treated as discontiguous arraylets. But since
they are empty there's no need to copy them in the critical section,
however, jniGetPrimitiveArrayCritical callers expects not NULL
values; therefore, in case of empty arraylets we advance the
pointer ahead of the header and return that address instead of
NULL which was the case when double mapping was enabled
Fixes: https://github.com/eclipse/openj9/issues/8386

Fix jniGetPrimitiveArrayCritical in the case of empty arraylets

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit adds code to `awrtbariEvaluator` to support
compressed references for aarch64.

AArch64: Add code for compressed refs - awrtbariEvaluator

---

runtime/compiler/aarch64/codegen/J9ARM64Snippet.cpp
runtime/compiler/aarch64/codegen/J9ARM64Snippet.hpp
runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

This commit implements ARM64MonitorEnterSnippet and
ARM64MonitorExitSnippet.

AArch64: Implement ARM64MonitorEnter/ExitSnippet

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
runtime/compiler/aarch64/runtime/Recompilation.spp

This commit implements computed calls in PrivateLinkage for AArch64.
Issue: #7023

AArch64: Implement computed calls

---

buildenv/jenkins/variables/defaults.yml

Disable jdk8 special.system on AIX while not enough machines

---

buildenv/jenkins/jobs/infrastructure/Update-Reference-Repos.groovy

Remove JDK13 from ref repo updater job

---

test/functional/cmdLineTests/runtimemxbeanTests/getPidTest.pl

Using JVM options like -XX:+UseJITServer can generate additional
output which causes getPidTest.pl to fail incorrectly.
Updated the script to look for PID in the Java process output, and
ignore other messages.
Fixes: #8220
Signed-off-by: Ashutosh Mehra <mehra.ashutosh@ibm.com>

Update getPidTest.pl to parse output for PID

---

jcl/src/java.base/share/classes/java/lang/Access.java

The signature of `addOpensToAllUnnamed()` changed in Java 15.

Adapt to JavaLangAccess changes for Java 15

---

test/functional/JIT_Test/playlist.xml
test/functional/JIT_Test/src/jit/test/jitt/misc/SanityCompareAndBranch.java
test/functional/JIT_Test/testng.xml

Add compare and branch JIT Test

---

buildenv/jenkins/variables/defaults.yml

Reverts eclipse/openj9#8533
Closes #8534

Revert "Revert to gcc 7.3 on xlinux" which switches to gcc 7.5

---

jcl/src/java.base/share/classes/java/lang/String.java

Cherry-pick of: https://github.com/eclipse/openj9/pull/8572
Signed-off-by: Sharon Wang <sharon-wang-cpsc@outlook.com>

(v0.19.0) Support new escape sequences introduced in JDK 14 (JEP 368)

---

runtime/jcl/common/reflecthelp.c
runtime/util/optinfo.c

JEP 359 windows compile failures

---

runtime/jcl/common/reflecthelp.c
runtime/util/optinfo.c

0.19 release port from https://github.com/eclipse/openj9/pull/8583

0.19: JEP 359 windows/arm compile failures

---

runtime/compiler/arm/codegen/J9ARMEvaluator.cpp

Signed-off-by: Leonardo Banderali <leonardo2718@protonmail.com>

Add missing ) in ARM code generator

---

runtime/bcutil/ClassFileWriter.cpp
runtime/bcutil/ClassFileWriter.hpp
runtime/bcutil/cfreader.c
runtime/cfdumper/main.c
runtime/oti/cfr.h
runtime/util/romclasswalk.c

Fixes: #7945
depends on JEP 359 part 1: #8061
depends on JEP 359 part 2: #8351

JEP 359 cfdumper support

---

runtime/bcutil/ClassFileWriter.cpp
runtime/bcutil/ClassFileWriter.hpp
runtime/bcutil/cfreader.c
runtime/cfdumper/main.c
runtime/oti/cfr.h
runtime/util/romclasswalk.c

port from: https://github.com/eclipse/openj9/pull/8391

v0.19: JEP 359 cfdumper support

---

jcl/src/java.base/share/classes/java/lang/Class.java

Add missing space to "record " qualifier

---

runtime/codert_vm/arm64nathelp.m4
runtime/codert_vm/armnathelp.m4
runtime/codert_vm/cnathelp.cpp
runtime/codert_vm/pnathelp.m4
runtime/codert_vm/xnathelp.m4
runtime/codert_vm/znathelp.m4
runtime/compiler/compile/J9AliasBuilder.cpp
runtime/compiler/runtime/Runtime.cpp
runtime/compiler/runtime/asmprotos.h
runtime/jilgen/jilconsts.c
runtime/oti/j9nonbuilder.h
runtime/oti/vm_api.h
runtime/vm/intfunc.c
runtime/vm/valueTypeHelpers.cpp
runtime/vm/valueTypeHelpers.hpp

Add jit helper stub for acmp
Depends on https://github.com/eclipse/omr/pull/4841

Add jit helper stub for acmp

---

buildenv/jenkins/jobs/infrastructure/omrMirror.groovy

Only fire original OMR build after mirror

---

runtime/gc_trace/TgcParallel.cpp

Reporting changes for https://github.com/eclipse/omr/pull/4833
- Report missed updates
- Use newly introduced `majorUpdate` field rather than calculating major
updates from minor updates

TGC Parallel Reporting Changes

---

runtime/bcutil/ROMClassBuilder.cpp

Remove execute permissions that confuse git on Windows

---

jcl/src/java.base/share/classes/java/lang/invoke/LambdaForm.java
jcl/src/java.base/share/classes/java/lang/invoke/MemberName.java
jcl/src/java.base/share/classes/java/lang/invoke/VarHandle.java

Mirror of https://github.com/eclipse/openj9/pull/8414.

[0.19.0 Release] JEP-370 Implementation (Part 2)

---

runtime/bcutil/cfreader.c

record attribute is not part of code attribute

---

runtime/shared_common/CompositeCache.cpp

Compare _cacheFullFlags against _theca->cacheFullFlags to see if
_theca->cacheFullFlags has been updated. If yes, use the latest
_theca->cacheFullFlags value to set runtime flags.
Move the setting of _cacheFullFlags and its comparison against
_theca->cacheFullFlags inside _runtimeFlagsProtectMutex.
Fixes #8628

Resolve the race condition setting/reading _theca->cacheFullFlags

---

jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/ExtendedOperatingSystemMXBeanImpl.java

Resolves problem introduced by #8265

Fix jdk14 usage of removed variable cpuUtilizationHelper

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy

Do not draw summary table if buildFile is undefined

---

buildenv/jenkins/variables/defaults.yml

* [skip ci]
* eclipse/openj9#7791

Move 390 compiles from ubuntu16 to Redhat7

---

runtime/include/j9cfg.h.in

CMake: fix missing platform flags

---

runtime/tests/jvmtitests/exports.cmake
runtime/tests/jvmtitests/src/CMakeLists.txt

Add sources / exports for fieldwatch test
fixes #8666

CMake: add missing sources to jvmtitests

---

runtime/j9vm/java11vmi.c
runtime/oti/j9nonbuilder.h
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/FastJNI_com_ibm_oti_vm_VM.cpp

Replace J9JavaVM platformClassLoader with extensionClassLoader

---

runtime/vm/jvminit.c

Fix illegal variable declaration

---

runtime/jcl/common/sun_misc_Unsafe.cpp

Move variables inside ifdef

---

runtime/vm/jvminit.c

Another bad variable declaration

---

runtime/bcutil/cfreader.c
runtime/nls/cfre/cfrerr.nls

Record component is implicitly final

---

jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
jcl/src/java.base/share/classes/java/lang/invoke/VarHandle.java
runtime/oti/vm_api.h
runtime/vm/BytecodeInterpreter.hpp
runtime/vm/MHInterpreter.cpp
runtime/vm/exceptionsupport.c

Port https://github.com/eclipse/openj9/pull/8501 to the 0.19.0 release

(v0.19.0) JEP-370 Implementation (Part 3)

---

jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java
runtime/jcl/common/sun_misc_Unsafe.cpp
runtime/oti/j9nonbuilder.h
runtime/oti/j9port.h
runtime/port/common/j9sysinfo_helpers.c
runtime/port/common/j9sysinfo_helpers.h
runtime/vm/jvminit.c

Port #7258 #8700 #8701 #8702 to the v0.19.0-release branch

(v0.19.0) Unsafe writebackMemory for Java 14 

---

buildenv/jenkins/README.md
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
buildenv/jenkins/variables/defaults.yml

Add plinux cmake jenkins build

---

test/functional/VM_Test/src/com/ibm/oti/jvmtests/AutoRun.java

- added result handling for test failures for jvmnativestest
Issue: #8716
[ci skip]

Added failure handling for jvmnativestest

---

runtime/vm/jvminit.c

On Linux on Z, `libj9jit` library dynamically links the `libj9zlib` library available in OpenJ9. In regular world, both library sits in the same directory and when it need to load `libj9zlib` which is required by `libj9jit` it finds it from the previously set path. When we specify the `-XXjitdirectory` option it overwrites the path to load dynamically linked libraries from and JVM fails to start as it can not find `libj9zlib` needed by JIT library. In order to fix this issue, we need to preload `libj9zlib` library before it loads `libj9jit` similarly as we preload other libraries such as `libjvm` .
Signed-off-by: simonameng <simonameng97@gmail.com>

Fix '-XXjitdirectory' option on Linux on Z

---

runtime/compiler/aarch64/env/J9CPU.hpp
runtime/compiler/arm/env/J9CPU.hpp
runtime/compiler/env/CPU.hpp
runtime/compiler/env/J9CPU.hpp
runtime/compiler/p/env/J9CPU.hpp
runtime/compiler/x/env/J9CPU.hpp
runtime/compiler/z/env/J9CPU.hpp

Mark CPU extensible and add new constructor

---

buildenv/jenkins/common/build.groovy

Related to https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/270

Build debug-image on z/OS

---

runtime/compiler/control/rossa.cpp

[ci skip]
Introduced via #8756

(0.19.0) `#if define()` should be `#if defined()` in rossa.cpp

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp

This commit fixes `buildPrivateLinkageArgs` to correctly push arguments
to Java stack.

AArch64: Fix buildPrivateLinkageArgs

---

test/functional/JIT_Test/playlist.xml

Issue #8653
Issue #8674
Issue #8708
Issue #8726
Issue #8769
Issue #8770
Issue #8788

Disable JITServer tests until failures are fixed

---

jcl/src/java.base/share/classes/java/lang/invoke/VarHandle.java

Mirror of https://github.com/eclipse/openj9/pull/8783.

(0.19.0) Fix VarHandle coordinateTypes

---

buildenv/jenkins/common/build.groovy

Prior to this change, one would need to use the `--strip-components=1` option:
```
tar xzf --strip-components=1 debug-image.tar.gz
```
Now, the archive will have the proper structure for use directly:
```
tar xzf debug-image.tar.gz
```
This corrects https://github.com/eclipse/openj9/pull/8774#issuecomment-596050357 by not adding `debug-image.tar.gz` to `CUSTOMIZED_SDK_URL`.
Fixes: #8757.

Remove the prefix 'debug-image' from paths in debug info archives

---

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
jcl/src/java.base/share/classes/java/lang/StringBuffer.java
jcl/src/java.base/share/classes/java/lang/StringBuilder.java

Check for int overflow in StringBuffer and StringBuilder

---

runtime/bcutil/ClassFileOracle.cpp

Mark record_component annotations as referenced

---

runtime/bcutil/ClassFileOracle.cpp

Port from: https://github.com/eclipse/openj9/pull/8816

(v0.20.0): Mark record_component annotations as referenced

---

jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
jcl/src/java.base/share/classes/java/lang/String.java
jcl/src/java.base/share/classes/java/lang/StringBuffer.java
jcl/src/java.base/share/classes/java/lang/StringBuilder.java

Replays #8771 and #8830 for the 0.20.0 release branch.

(0.20.0) Improve overflow checking in String classes

---

runtime/compiler/build/rules/aix-xlc/common.mk

This is a replay of #8848 for the 0.20.0 release branch.

(0.20.0) AIX: Create .debuginfo file for JIT shared library

---

runtime/bcutil/cfreader.c

Port to v0.20.0: https://github.com/eclipse/openj9/pull/8873
Currently it is assumed that the length of a RuntimeVisibleAnnotation or RuntimeVisibleTypeAnnotation will be at least 2. This may not be the case for a malformed annotation. Deal with the cases where the length is 0 or 1 and ensure that the error is properly handled.

Correct numberOfAnnotations in Runtime*Annotations

---

runtime/bcutil/cfreader.c

Port from: https://github.com/eclipse/openj9/pull/8761
Currently it is assumed that the length of a RuntimeVisibleAnnotation or RuntimeVisibleTypeAnnotation will be at least 2. This may not be the case for a malformed annotation. Deal with the cases where the length is 0 or 1 and ensure that the error is properly handled.

(v0.20.0): Runtime*Annotations malformed edge cases

---

buildenv/jenkins/README.md
buildenv/jenkins/common/pipeline-functions.groovy

Accept short or full platform names in PR build requests

---

buildenv/jenkins/variables/defaults.yml

The Xvfb problem #8376 on xlinux has been resolved.
See also #8881

Include sanity.openjdk for xlinux

---

test/README.md
test/docs/OpenJ9TestUserGuide.md

Update test readme and user guide to include list of tests

---

buildenv/jenkins/variables/defaults.yml

Exclude sanity.openjdk testing from cmake builds

---

buildenv/jenkins/common/pipeline-functions.groovy

- OpenJDK, OpenJ9, OMR and Vendor Tests
[skip ci]
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>

Convert short SHAs in build description to hyperlinks

---

buildenv/jenkins/common/pipeline-functions.groovy

- Simplify the test functions by combining them into one.
- Conditionally decide which params to add based on if
we're doing Upstream or Artifactory pulls.
[skip ci]
Helps with #4719

Combine both test functions

---

CONTRIBUTING.md

A future version of the OpenJ9 web site may not contain this
information.

Add a building and testing section to CONTRIBUTING.md

---

buildenv/jenkins/jobs/infrastructure/artifactory_cleanup.groovy

Delete job folders when num to keep is 0

---

jcl/src/java.base/share/classes/java/lang/invoke/FieldVarHandle.java
runtime/jcl/common/java_lang_invoke_VarHandle.c
runtime/oti/vmconstantpool.xml
test/functional/Java9andUp/src/org/openj9/test/varhandle/StaticFieldVarHandleTests.java
test/functional/Java9andUp/src/org/openj9/test/varhandle/StaticHelperChild.java

Mirror of https://github.com/eclipse/openj9/pull/8892 for the v0.20.0 release.

(0.20.0) Fix definingClass for StaticFieldVarHandle

---

runtime/compiler/env/J9ClassEnv.cpp
runtime/compiler/env/J9ClassEnv.hpp

Add isClassValueType to ClassEnv query

---

runtime/rasdump/javadump.cpp

Compute the bit mask indexes properly, which are used to track memory
category ancestors. Memory category codes don't need to be consecutive.
Fixes #8984

Fix javacore native mem info output

---

runtime/rasdump/javadump.cpp

Compute the bit mask indexes properly, which are used to track memory
category ancestors. Memory category codes don't need to be consecutive.
Fixes #8984
Cherry pick of #8985 for the 0.20.0 release.

(0.20.0) Fix javacore native mem info output

---

doc/build-instructions/cmake.md

Add build instructions for cmake

---

buildenv/jenkins/common/pipeline-functions.groovy

Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

Fix typo SVENDOR_TEST_SHAS_MAP

---

doc/release-notes/0.20/0.20.md

Notable changes added.
[ci skip]

Draft release notes for Eclipse OpenJ9 0.20.0

---

runtime/compiler/env/J9ClassEnv.cpp

Fix debug build break in JITServer code

---

runtime/vm/jvminit.c

IBMJ9 has started to use `JVM_*Signal` functions in the `sun.misc.Signal`
class. So, it is no longer dependent on `shutDownHookWrapper`. Hence,
`shutDownHookWrapper` is removed.

Remove shutDownHookWrapper

---

test/functional/cmdLineTests/build.xml
test/functional/cmdLineTests/proxyFieldAccess/build.xml

Enable ProxyFieldAccess tests for JCL_VERSION=latest

---

runtime/bcutil/jimageintf.c
runtime/bcutil/test/dyntest/misc_tests.cpp
runtime/compiler/aarch64/codegen/CallSnippet.cpp
runtime/compiler/aarch64/runtime/ARM64RelocationTarget.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/optimizer/DataAccessAccelerator.cpp
runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp
runtime/compiler/optimizer/J9ValuePropagation.cpp
runtime/compiler/optimizer/SignExtendLoads.cpp
runtime/compiler/runtime/ClassUnloadAssumption.cpp
runtime/compiler/runtime/RelocationRecord.cpp
runtime/compiler/x/codegen/X86HelperLinkage.hpp
runtime/gc_vlhgc/EnvironmentVLHGC.cpp
runtime/jcl/common/sun_reflect_ConstantPool.c
runtime/port/sysvipc/j9shmem.c
runtime/port/win32/j9process.c
runtime/rastrace/trccomponent.c
runtime/shared_common/CacheLifecycleManager.cpp
runtime/shared_common/CacheMap.cpp
runtime/shared_common/SCImplementedAPI.cpp
runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/fieldwatch/fw001.c
runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/modularityTests/mt001.c
runtime/tests/port/shmem.c
runtime/verbose/errormessageframeworkrtv.c
runtime/vm/BytecodeInterpreter.hpp

Remove unneeded semicolons, and minor formatting

---

runtime/gc_glue_java/FlattenedArrayObjectScanner.hpp
runtime/gc_glue_java/HeadlessMixedObjectScanner.hpp
runtime/gc_glue_java/MarkingDelegate.hpp
runtime/gc_glue_java/MixedObjectScanner.hpp
runtime/gc_glue_java/ObjectScannerState.hpp
test/functional/Valhalla/playlist.xml
test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java

- Use flattened size when iterating flattened arrays
- Use object ptr in Mixed and Reference scanner constructors
cc @dmitripivkine @amicic Sorry for the delay, I forgot to open the PR on this repo.

Add FlattenedArrayObjectScanner

---

runtime/vm/BytecodeInterpreter.hpp

In the below example, `compareAndExchangeRelease` translates to an
OutOfLine INL method named `OutOfLineINL_jdk_internal_misc_Unsafe_compareAndExchangeIntVolatile`.
**Example:**
```
InstFieldVH <- InstanceFieldVarHandle provides access to an int field in an object.
1000 threads concurrently execute {
int old, new;
do {
old = (int)InstFieldVH.getVolatile(object);
new = old + 2;
} while (old != InstFieldVH.compareAndExchangeRelease(object, old, new));
}
```
There is a **race condition** between **1)** invoking the target method in
`BytecodeInterpreter.hpp::outOfLineINL`; and **2)** resolving the native
address (`J9Method->extra`) of the target method in
`BytecodeInterpreter.hpp::bindNative`.
Due to the race condition, the native address of the target method may
not be resolved when certain …

Handle race condition in outOfLineINL

---

jcl/src/java.base/share/classes/java/lang/invoke/MethodHandle.java
jcl/src/java.base/share/classes/java/lang/invoke/VarHandle.java

Revert "Remove final from fields being set in native methods"

---

runtime/cmake/omr_config.cmake

CMake: Enable omrsig

---

runtime/cmake/platform/toolcfg/xlc.cmake

CMake: Generate debug info on xlc

---

jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/corereaders/CoreReaderSupport.java
jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/CombinedContext.java
jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/DeadlockCommand.java
jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/FindCommand.java
jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/OpenCommand.java
jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/infocommands/InfoClassCommand.java
jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/infocommands/InfoHeapCommand.java
jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/infocommands/InfoJitmCommand.java
jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/infocommands/InfoLockCommand.java
jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/infocommands/InfoMemoryCommand.java
jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/infocommands/InfoMmapCommand.java
jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/infocommands/InfoSymCommand.java
jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/infocommands/InfoThreadCommand.java
jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/xcommands/XJCommand.java
jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/xcommands/XKCommand.java

In preparation for the solution to #8983:
* avoid raw types
* remove unused imports

Clean up DTFJ code

---

runtime/makelib/targets.mk.zos.inc.ftl

Enable c99 interfaces on zos

---

buildenv/jenkins/variables/defaults.yml

Adds --enable-jitserver for jdk14+

Enable --enable-jitserver for all xlinux and plinux

---

runtime/compiler/env/J9ClassEnv.cpp

This PR adds jitserver implementation for `J9::ClassEnv::isZeroInitializable()`. JITServer reads from cached information and return the desired result. 
Reference: https://github.com/eclipse/openj9/issues/9161
Signed-off-by: Chris Chong <Zichun.Chong@ibm.com>

Add JITServer implementation for new added API isZeroInitializable

---

buildenv/jenkins/variables/defaults.yml

Include special.system testing for AIX

---

buildenv/jenkins/variables/defaults.yml

* [skip ci]
* eclipse/openj9#9089

Update Windows openssl in use to v1.1.1f

---

debugtools/DDR_VM/compile_ddr.xml
debugtools/DDR_VM/generate.xml
debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/ICore.java
debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/aix/AIXDumpReader.java
debugtools/DDR_VM/src/com/ibm/j9ddr/view/dtfj/image/J9DDRImage.java
jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/image/Image.java
jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/OpenCommand.java

This is a replay of #9199 with a second commit that fixes the compile problem.

Warn when opening a truncated core file

---

buildenv/jenkins/variables/defaults.yml

Update aarch64 platform to use gcc-7.5

---

test/functional/Java8andUp/src/org/openj9/test/java/lang/reflect/Test_Executable.java

Enum classes have a third synthetic method in jdk15+, `$values()`.
Also fixed some mistakes in the enum test.
Fixes #9216
[ci skip]

Fix enum reflection test for jdk15+

---

buildenv/jenkins/variables/defaults.yml

This enabled uploading to the UNB
Artifactory server. Downloading will
need to be enabled on each machine
as per #8817.
Related #8425
[skip ci]

Enable UNB Artifactory server

---

doc/release-notes/0.20/0.20.md

Update known issues table in the 0.20.0 release notes.
[ci skip]

Add known issues for 64-bit ARM

---

jcl/src/openj9.traceformat/share/classes/com/ibm/jvm/trace/format/api/ByteStream.java

It was always false otherwise it wouldn't work (the code would throw IllegalMonitorStateException).

Remove ByteStream.blocking

---

runtime/compiler/aarch64/codegen/CallSnippet.cpp

This commit adds adjustments for addresses of virtual unresolved call
snippets and interface call snippets so that the 64-bit data in
snippets are naturally aligned.

AArch64: Align 64-bit data in call snippets

---

runtime/compiler/env/VMJ9.h
runtime/compiler/x/codegen/J9TreeEvaluator.cpp

Resolves issue #9222 by @0xdaryl

Remove functions ScopeCHKEvaluator, atccheckEvaluator, lowerAtcCheck

---

runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/runtime/codertinit.cpp

JITServer does not trigger any of the JIT hooks thus disabling them
Issue: #7508

Disable all JIT Hooks at JITServer

---

runtime/gc_glue_java/ScavengerDelegate.cpp

Now that cache flushing is simplifed
(https://github.com/eclipse/omr/pull/5041), and directly
accesses/modifies target's thread caches/remainders in context of
calling thread (that walks all threads), we should not call it for
threads that are actively running (have VM access).
This is a minimum we must do, but we also need to prevent threads that
are about to acquire VM access and race with the calling thread.
This is why we hold target's thread publicFlagsMutex, although we might
need extra mechanism to force target thread to take slow
acquire-VM-access pass (that will also acquire publicFlagsMutex and
serialize with caller thread). This is still subject to testing (all
this code is still inactive).

Flush caches for threads without VM access only

---

buildenv/jenkins/variables/defaults.yml

Update Windows to use openssl 1.1.1g

---

buildenv/jenkins/README.md

Add example of PR build on a release branch

---

doc/processes/release_process.md

See discussion in https://github.com/eclipse/openj9/issues/9349#issuecomment-619171085 about why having the tag is important

Update release process to include tagging system-test

---

jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/HexdumpCommand.java
jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/helpers/Utils.java

* accept length in hex
* make error messages more helpful
* improve EBCDIC table

Improve jdmpview 'hexdump' command

---

runtime/codert_vm/arm64nathelp.m4
runtime/codert_vm/armnathelp.m4
runtime/codert_vm/cnathelp.cpp
runtime/codert_vm/decomp.cpp
runtime/codert_vm/j9codertvm.tdf
runtime/codert_vm/pnathelp.m4
runtime/codert_vm/xnathelp.m4
runtime/codert_vm/znathelp.m4
runtime/compiler/runtime/MethodMetaData.c
runtime/compiler/runtime/asmprotos.h
runtime/jilgen/jilconsts.c
runtime/oti/VMHelpers.hpp
runtime/oti/j9nonbuilder.h

Details in #9267
Also reverts #7340 which was a failed attempt to fix this before we
completely understood the issue.
[ci skip]

VM side of synthetic handler fix

---

runtime/compiler/optimizer/StringPeepholes.cpp
runtime/compiler/optimizer/StringPeepholes.hpp

DecimalFormatHelper has been deleted in #5666, clean up its referencce
in the JIT.

Clean up reference to DecimalFormatHelper in the JIT

---

doc/build-instructions/Build_Instructions_V11.md

The change is to add the building steps to enable
RISC-V 64bit from the OpenJ9 perspective.
Issue: #7421
Signed-off-by: Cheng Jin jincheng@ca.ibm.com

Update the building instructions for RISC-V in OpenJ9 (part8/doc)

---

buildenv/jenkins/common/pipeline-functions.groovy
buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy

Reformat the method fetching the downstream job builds -
get_downstream_builds() - to return a list of builds instead of the last
build.
Add restart information for the downstream jobs to the summary badge
table. Show a spinner if the build has been restarted (has more then
one runs/builds). When hovering over the image, display a
message: This build has been restarted n time[s]!
[ci skip]

Add build restart information to the top pipeline summary badge

---

runtime/bcutil/ClassFileOracle.cpp

fixes: https://github.com/eclipse/openj9/issues/8890

Fix duplicate LocalVariableTypeTable check

---

runtime/j9vm/exports.cmake
runtime/j9vm/j9vmnatives.xml
runtime/j9vm/java11vmi.c
runtime/j9vm/jvm.c
runtime/redirector/forwarders.m4

Required for jdk8u262-b01
Fixes #9389

Backport JVM_BeforeHalt from jdk11 to jdk8

---

runtime/compiler/optimizer/StringPeepholes.cpp

Remove use of DecimalFormatHelper related enum

---

runtime/gc_glue_java/ScavengerDelegate.cpp

Fix corner case where Ownable Sync Objet is duplicated in the Ownable Sync list. This occurs
when Ownable object construction finishes much after allocation causing
it to survive multiple scavenges and being tenured. The object will be
added by jit following the STW phase, the concurrent phase will
attempt to add it again. The current `!isObjectInNewSpace(link)` condition would
stop this in normal circumstances. However, since this object will be
linked to tenure, `!isObjectInNewSpace(link)` will not be a sufficient
check as it only checks against survivor space which would cause the tenured Ownable to pass
the condition and be added again. 

Concurrent Scavenger Ownable Synchronizer Fix

---

runtime/compiler/env/VMJ9Server.cpp

A recent commit for value type inlinine allocations changed the
implementation of TR_J9ServerVM::canAllocateInlineClass, but introduced
a bug since the classFlags of the ramClass are obtained only
if the class is not initialized.
This commit obtaines the value of the classFlags from the JITServer cache
in all cases, thus eliminating the bug and avoiding extra messages.

Fix TR_J9ServerVM::canAllocateInlineClass

---

runtime/codert_vm/cnathelp.cpp

Keep the decompilation stack sane when re-throwing from the synthetic
handler.
The code is less than ideal in that it expressly targets the only two kinds
of exceptions that can be thrown from today's synthetic handlers, but
the more general fix will be complex (so better done seperately).
Related: #9267 #9368
[ci skip]

Fix exception catch at synthetic handler

---

buildenv/jenkins/common/pipeline-functions.groovy

[ci skip]
Related: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1563 and
https://github.com/AdoptOpenJDK/openjdk-tests/pull/1758

Update PARALLEL param for test builds

---

test/functional/Java8andUp/playlist.xml
test/functional/NativeTest/playlist.xml
test/functional/SharedCPEntryInvokerTests/playlist.xml
test/functional/cmdLineTests/lazyClassLoadingTest/playlist.xml

Related: runtimes/backlog/issues/303
[ci skip]

Add Mode110 and Mode610 to native tests

---

doc/build-instructions/Build_Instructions_V11.md
doc/build-instructions/Build_Instructions_V14.md
doc/build-instructions/Build_Instructions_V8.md

Fix build instructions docker --with-boot-jdk= paths

---

buildenv/jenkins/variables/defaults.yml

Jenkins: Enable testing on osx cmake builds

---

runtime/compiler/optimizer/StringBuilderTransformer.cpp

Closes: #9508
Signed-off-by: Laura Cohen <lauramimona@gmail.com>
This is my first pull request, please let me know if it was all done correctly!

Updated misspelling of recogniedMethod

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/z/codegen/S390PrivateLinkage.cpp

See eclipse/omr#5165 for details.
Issue: #9428

Consolidate all trace CG options

---

runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/decompResolveFrame/decomp005.c

Revert "Initialize variable to fix build break on windows"

---

runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/decompResolveFrame/decomp005.c

Revert "Revert "Initialize variable to fix build break on windows""

---

test/README.md

add regular to skip native tests
[ci skip]

Update test readme file

---

buildenv/jenkins/variables/defaults.yml

Enable DDR for cmake builds of jdk14/next

---

jcl/src/java.base/share/classes/java/lang/System.java

Remove obsolete support for -Duse.legacy.version

---

runtime/nls/jitm/j9jit_ca.nls
runtime/nls/jitm/j9jit_cs.nls
runtime/nls/jitm/j9jit_de.nls
runtime/nls/jitm/j9jit_es.nls
runtime/nls/jitm/j9jit_fr.nls
runtime/nls/jitm/j9jit_hu.nls
runtime/nls/jitm/j9jit_it.nls
runtime/nls/jitm/j9jit_ja.nls
runtime/nls/jitm/j9jit_ko.nls
runtime/nls/jitm/j9jit_pl.nls
runtime/nls/jitm/j9jit_pt_BR.nls
runtime/nls/jitm/j9jit_ru.nls
runtime/nls/jitm/j9jit_sk.nls
runtime/nls/jitm/j9jit_sl.nls
runtime/nls/jitm/j9jit_tr.nls
runtime/nls/jitm/j9jit_zh.nls
runtime/nls/jitm/j9jit_zh_CN.nls
runtime/nls/jitm/j9jit_zh_TW.nls

Files update for PII_Ship2.
Signed-off-by: Xiao Juan Chen <bjchenxj@cn.ibm.com>

Modify the translated PII files in nls folder - 20200518

---

runtime/util/fltconv.c

Work around a problem with float cast in VS2017 15.9

Convert long to float on Windows-32 bit

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp

Use `stp` instruction to clear collectable locals in `J9::ARM64::PrivateLinkage::createPrologue()`.
Depends on https://github.com/eclipse/omr/pull/5205

AArch64: Use stp instruction to clear collectable locals in createPrologue()

---

doc/build-instructions/Build_Instructions_V11.md

The change mainly includes a couple of updates in the document
in case users might encounter during the cross-compilation.

Update the document specific to RISC-V

---

runtime/libffi/CMakeLists.txt

CMake: Add arm support for libffi

---

runtime/compiler/CMakeLists.txt
runtime/compiler/linter.mk

CMake: Stop copying jit tracegen to source tree

---

runtime/compiler/build/toolcfg/aix-xlc/common.mk

Signed-off-by: gaoli <gaolibj@cn.ibm.com>

Change the AS path and add IBM i specific flags

---

buildenv/jenkins/ARTIFACTORY.md

Add GC schedule setting Artifactory Doc

---

buildenv/jenkins/common/pipeline-functions.groovy

enable dynamic parallel in extended.functional_x86-64_linux_Nightly

---

buildenv/jenkins/common/build.groovy

Capture more diagnostics info to help resolve #9126

Jenkins: Capture more diagnostics info for cmake builds

---

README.md

Add a link to the user documentation, and the migration blog

Update README.md for jdk11, add links, fix links

---

buildenv/jenkins/common/pipeline-functions.groovy

enable dynamic parallel for all functional test builds

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/JITClientCompilationThread.cpp
runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/env/j9jit.tdf
runtime/compiler/runtime/JITClientSession.cpp

Add the first set of trace points for JITServer relating to the server client connection handshake.
Implements #9482

Add trace points for JITServer

---

jcl/src/java.base/share/classes/java/lang/Access.java

jdk15 Implement java.lang.Access.stringConcatMix

---

runtime/compiler/optimizer/VarHandleTransformer.cpp

Fix method name of getAndBitwiseXor

---

buildspecs/win_x86-64.spec
buildspecs/win_x86-64_cmprssptrs.spec
buildspecs/win_x86.spec

fyi @pshipton when you are ready.

Enable windows compilation with VS2017

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Enhance `VMnewEvaluator` in aarch64 code generator to support `TR::anewarray`
with constant length.

AArch64: Enhance VMnewEvaluator to support anewarray with constant length

---

runtime/compiler/control/CompilationThread.cpp
runtime/compiler/control/HookedByTheJit.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/J9CompilerEnv.cpp
runtime/compiler/env/ProcessorDetection.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/env/j9method.cpp
runtime/compiler/env/j9methodServer.cpp
runtime/compiler/ilgen/IlGenerator.cpp
runtime/compiler/ilgen/Walker.cpp
runtime/compiler/p/env/J9CPU.cpp
runtime/compiler/runtime/RelocationRuntime.cpp
runtime/compiler/z/codegen/DFPTreeEvaluator.cpp
runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp
runtime/compiler/z/codegen/J9CodeGenerator.cpp
runtime/compiler/z/codegen/J9MemoryReference.cpp
runtime/compiler/z/codegen/J9SystemLinkagezOS.cpp
runtime/compiler/z/codegen/J9TreeEvaluator.cpp
runtime/compiler/z/codegen/ReduceSynchronizedFieldLoad.cpp
runtime/compiler/z/codegen/S390PrivateLinkage.cpp
runtime/compiler/z/env/J9CPU.cpp
runtime/compiler/z/env/J9CPU.hpp

depends on: https://github.com/eclipse/omr/pull/5153

Replace CPU APIs on Z

---

jcl/src/jdk.management/share/classes/com/ibm/lang/management/ProcessorUsage.java

Throw better error from com.ibm.lang.management.ProcessorUsage

---

runtime/nls/j9vm/j9vm_ca.nls
runtime/nls/j9vm/j9vm_cs.nls
runtime/nls/j9vm/j9vm_de.nls
runtime/nls/j9vm/j9vm_es.nls
runtime/nls/j9vm/j9vm_fr.nls
runtime/nls/j9vm/j9vm_hu.nls
runtime/nls/j9vm/j9vm_it.nls
runtime/nls/j9vm/j9vm_ja.nls
runtime/nls/j9vm/j9vm_ko.nls
runtime/nls/j9vm/j9vm_pl.nls
runtime/nls/j9vm/j9vm_pt_BR.nls
runtime/nls/j9vm/j9vm_ru.nls
runtime/nls/j9vm/j9vm_sk.nls
runtime/nls/j9vm/j9vm_sl.nls
runtime/nls/j9vm/j9vm_tr.nls
runtime/nls/j9vm/j9vm_zh.nls
runtime/nls/j9vm/j9vm_zh_CN.nls
runtime/nls/j9vm/j9vm_zh_TW.nls

Files update for PII_Emergency_Ship.
Signed-off-by: Xiao Juan Chen <bjchenxj@cn.ibm.com>

Modify the translated PII files in nls folder - 20200603

---

runtime/compiler/z/codegen/J9TreeEvaluator.cpp

On IBM Z, for Non Compressed Ref configuration, instanceOf evaluator uses a Store Quadword instruction to store the data into dynamic cache. To store the data in OOL evaluator was using new register pair assigning `objClassReg` and `castClassReg` as register pair which was causing an issue in register assigner as on mainline sequence these registers were not used as register pair. To fix this issue and minimizing pressure on register assigner, this fix in this commit reuses the register pair used in mainline sequence to load from cache instead of allocating new one.
Fixes: #9770

Fix dependencies generated in instanceOf Evaluator

---

buildspecs/combogc.feature
buildspecs/j9.flags

Remove unused staccato build flags

---

runtime/compiler/control/JITServerCompilationThread.cpp
runtime/compiler/env/JITServerPersistentCHTable.cpp

As described in #9762, `_numActiveThreads` is not incremented when the thread is unloading the class or doing CHTable update. It could cause a race condition when another thread is timed out
on waiting for the first thread to complete, the second thread that’s timed out will clear the client session cache because `_numActiveThreads` is `0`.
Fixes #9762, #9694

Update numActiveThreads at the proper location at the server

---

test/functional/cmdLineTests/pltest/playlist.xml

-added cmdLineTester_pltest_j9sig_ext test to playlist.xml
-fixed error with _JVM_OPTIONS, all occurrences changed to JVM_OPTIONS
[ci skip]
Signed-off-by: Nikola Milijevic <nmilijev@uwaterloo.ca>

Port cmdLineTester_pltest_j9sig_ext Test

---

runtime/compiler/aarch64/runtime/Recomp.cpp
runtime/compiler/runtime/J9Runtime.hpp

This commit implements functions in Recomp.cpp.

AArch64: Implement Recomp.cpp

---

runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.hpp
runtime/compiler/aarch64/codegen/ARM64Recompilation.cpp
runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp
runtime/compiler/aarch64/codegen/J9CodeGenerator.hpp
runtime/compiler/aarch64/runtime/Recompilation.spp

This commit implements some functions for sampling recompilation for
AArch64.

AArch64: Implement functions for sampling recompilation

---

buildenv/jenkins/common/pipeline-functions.groovy

- set NUM_MACHINES="" as default in pipline-functions.groovy
[ci skip]

Update the default value of NUM_MACHINES

---

buildenv/jenkins/variables/defaults.yml

Fix indentation

---

runtime/gc_base/FinalizerSupport.cpp
runtime/vm/jniinv.c

Revert "Mark VM as exitting earlier"

---

buildenv/jenkins/common/build.groovy
buildenv/jenkins/common/variables-functions.groovy

Signed-off-by: Simon Rushton <rushton@uk.ibm.com>

Archive openj9-docs if ARCHIVE_JAVADOC is set

---

runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp

Enhance `VMnewEvaluator` to support variable length array allocation.
Depends on: https://github.com/eclipse/openj9-omr/pull/61
Master PR: https://github.com/eclipse/openj9/pull/9793

(0.21.0) AArch64: Enhance VMnewEvaluator to support variable length array allocation

---

buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
buildenv/jenkins/variables/defaults.yml

- Update PBT-All and defaults.yml
[skip ci]

Add jdk15 to pipelines

---

runtime/include/jvmti.h.m4
runtime/jvmti/jvmtiGeneral.c
runtime/jvmti/jvmtiHook.c
runtime/tests/jvmtitests/agent/version.c

* Defined `JVMTI_VERSION_15`;
* Updated `jvmtiGetVersionNumber()` & `jvmtiHookGetEnv()`;
* Minor refactoring.
Reviewer: @gacholio 
FYI: @DanHeidinga 

Add JDK15 JVMTI Version

---

runtime/j9vm/jvm.c

There are a couple of cases to cover.  The most common
being that the JVM already appended `:/usr/lib` to the
LIBPATH.
If we find :/usr/lib somewhere, we need to check whether
it's the end of the string, or somewhere in the middle.
If it's in the middle, we need to differentiate between
:/usr/lib: and :/usr/lib/something.
Otherwise, check for /usr/lib at the start of the LIBPATH.
If the length of LIBPATH is the same as /usr/lib, then
we're done.  Otherwise, confirm that we found /usr/lib:.
Which is a lot of parsing to pass a test.
fixes: #8504

Only add `/usr/lib` to AIX LIBPATH if not already there

---

runtime/rasdump/trigger.c

Fixes: https://github.com/eclipse/openj9/issues/8552
Pending xdump threads are waiting in such a way that blocks other threads from acquiring exclusive vm access. The threads wait to acquire a key until the running xdump thread finishes and hold shared vm access while spinning.
Solution:
- release vm access while waiting for dumpKey so other threads can acquire exclusive vm access
- moved dumpKey acquire first in prepareForDump so no differentiation between J9RAS_DUMP_DO_SUSPEND_OTHER_DUMPS and J9RAS_DUMP_DO_EXCLUSIVE_VM_ACCESS is needed
- re-order events in unwindAfterDump to match the reverse order of prepareForDump

Don't acquire exclusive vm access with waiting xdump

---

runtime/rasdump/trigger.c

Port from: https://github.com/eclipse/openj9/pull/9840
Pending xdump threads are waiting in such a way that blocks other threads from acquiring exclusive vm access. The threads wait to acquire a key until the running xdump thread finishes and hold shared vm access while spinning.
Solution:
- release vm access while waiting for dumpKey so other threads can acquire exclusive vm access
- moved dumpKey acquire first in prepareForDump so no differentiation between J9RAS_DUMP_DO_SUSPEND_OTHER_DUMPS and J9RAS_DUMP_DO_EXCLUSIVE_VM_ACCESS is needed
- re-order events in unwindAfterDump to match the reverse order of prepareForDump

(0.21) Can't acquire exclusive vm access with waiting xdump

---

runtime/include/jvmti.h.m4
runtime/jvmti/jvmtiGeneral.c
runtime/jvmti/jvmtiHook.c
runtime/tests/jvmtitests/agent/version.c

Reverts eclipse/openj9#9883
See https://github.com/eclipse/openj9/issues/9889

Revert "Add JDK15 JVMTI Version"

---

runtime/nls/shrc/j9shr.nls

Add missing END NON-TRANSLATABLE in j9shr.nls

---

runtime/oti/j9nonbuilder.h
runtime/shared_common/shrinit.cpp
runtime/shared_common/shrinit.h

Added query to determine is SCC is the default SCC, returns TRUE is SCC is the default and FALSE otherwise. Closes #6826

Create query to determine the SCC mode

---

buildenv/jenkins/common/build.groovy

- Speed up get_source clones by using a local
reference repository cache.
Issue #6744
[skip ci]

Pass Reference repo to get_source.sh

---

buildenv/jenkins/common/build.groovy

Reverts eclipse/openj9#9705
See https://github.com/eclipse/openj9/pull/9705#issuecomment-645025485

Revert "Pass Reference repo to get_source.sh"

---

buildenv/jenkins/common/build.groovy

- Speed up get_source clones by using a local
reference repository cache.
Issue #6744
[skip ci]

[Reapply] Pass Reference repo to get_source.sh

---

test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_Thread.java

Improve Test_Thread.test_join3() failure diagnostics

---

runtime/compiler/optimizer/UnsafeFastPath.cpp

In generational GC mode, wrtbar is needed for writes to static object fields.
Fixes: #8838 

Add wrtbar for UnsafeFastPath static field writes

---

runtime/port/module.xml
runtime/port/unix/j9process.c

Reverts eclipse/openj9#9937
See https://github.com/eclipse/openj9/pull/9937#issuecomment-646367295

Revert "Port: silence warning about ignored return value"

---

runtime/jcl/common/sun_misc_Unsafe.cpp

Re-Fetch patcharray after entering VM

---

runtime/jcl/common/sun_misc_Unsafe.cpp

(0.21.0) Re-Fetch patch array after entering VM

---

test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_Thread.java

Related to #9915. The failure we're tracking re-occurred, but in a
different place. I've tried to over them all.
[ci skip]

Improve Test_Thread failure diagnostics

---

buildenv/jenkins/jobs/infrastructure/Update-Reference-Repos.groovy
buildenv/jenkins/variables/defaults.yml

Add OpenJ9 & OMR to Reference Repo

---

runtime/compiler/control/DLLMain.cpp
runtime/compiler/control/J9Options.cpp
runtime/compiler/control/rossa.cpp
runtime/compiler/env/ProcessorDetection.cpp
runtime/compiler/env/VMJ9.cpp
runtime/compiler/il/J9ResolvedMethodSymbol.cpp
runtime/compiler/p/codegen/DFPTreeEvaluator.cpp
runtime/compiler/p/codegen/J9CodeGenerator.cpp
runtime/compiler/p/codegen/J9TreeEvaluator.cpp
runtime/compiler/p/codegen/PPCJNILinkage.cpp
runtime/compiler/p/codegen/PPCPrivateLinkage.cpp
runtime/compiler/p/env/J9CPU.cpp
runtime/compiler/p/env/J9CPU.hpp
runtime/compiler/runtime/Trampoline.cpp

depends on: https://github.com/eclipse/openj9/pull/9571

Replace CPU APIs on Power
