eclipse-openj9/openj9

- runtime/compiler/control/JITClientCompilationThread.cpp
The client connects to JITServer and then re-uses the same connection
for many compilation requests (as long as there is something in the
compilation queue). While this saves latency and CPU, it can cause
the following bad scenario:
1) During compilation, client throws an exception, but the server is
not aware about it.
2) Client starts a new compilation request re-using the same connection.
3) JITServer sends a query to client, but receives the compilation
request, so it throws an exception and sends an error message to client
4) Client sees the error message and aborts the compilation that just
started.
As a result, the seqNo sent by the client is forever lost and JITServer
is going to needlessly wait for it, increasing latencies and in the end
being forced to start over after clearing …
> Break connection to JITServer on exceptions

- runtime/j9vm/jvm.c
backport #9814
There are a couple of cases to consider:
* "/usr/lib": Path is exactly equal to /usr/lib
* "/usr/lib:..." Path begins with /usr/lib.  This may
or may not result in a valid match depending
on whether it is followed by a ':' or not.
* "...:/usr/lib:..." Path includes /usr/lib.  This may
or may not result in a valid match depending
on whether it is preceded by ":" and followed
by a ':' or not.
* "....:/usr/lib" Path ends with /usr/lib.
All of these can be handled by looping through the LIBPATH
looking for /usr/lib and then handling the boundary cases
carefully.
fixes: #8504
> (v0.21.0) Process the whole LIBPATH looking for '/usr/lib'.

- jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/plugins/impl/ClassScanner.java
The plugin manager will fail to load all the expected classes if it encounters any that use class-file features not supported by the specified ASM version.
Fixes: #9985.
> Use the latest available ASM version

- jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/plugins/impl/ClassScanner.java
A replay of #9989 for the 0.21.0 release branch.
> (0.21.0) Use the latest available ASM version

- buildenv/jenkins/variables/defaults.yml
Try to avoid running out of space, in particular before testing for 0.21.0 M2 this weekend.
> Reduce limits for keeping artifacts and logs

- doc/compiler/aot/README.md
> Add overview doc for AOT

- runtime/shared_common/shrinit.cpp
> Delete dead code for a no longer applicable compiler bug

- runtime/codert_vm/CMakeLists.txt
> CMake: add arm/aarch64 support to codert_vm

- runtime/j9vm/java11vmi.c
Fixes: #6462
Original pr: https://github.com/eclipse/openj9/pull/6709
> Cleanup: Check packages in unnamed module when creating module

- runtime/compiler/optimizer/InlinerTempForJ9.cpp
> Call inlineRecognizedCryptoMethod from FrontEnd object

- runtime/gc_glue_java/ScavengerDelegate.cpp
In Concurrent Scavenger, when a GC thread observes scan Q is empty and
wants to signal mutators to flush their copy caches for final scan, the
GC thread will also attempt to flush those caches for threads that don't
have VM access. In addition it will hold public flags mutex to prevent
race with target thread, however, between realizing target thread does
not have VM access and acquiring the mutex, the thread can actually
acquire VM access and GC thread can mess up with caches of actively
running Mutator.
So, once GC threads acquire the mutex, it will double change target
thread still has no VM access.
The outer check still makes sense to avoid unnecessarily acquiring mutex
for active target threads.
> Extra VM access check in signalling pass

- buildenv/jenkins/ARTIFACTORY.md
- buildenv/jenkins/common/build.groovy
- buildenv/jenkins/common/pipeline-functions.groovy
- buildenv/jenkins/common/variables-functions.groovy
- buildenv/jenkins/docker-slaves/jenkinsfile-build-container.groovy
- buildenv/jenkins/jobs/infrastructure/Cleanup-Nodes.groovy
- buildenv/jenkins/jobs/infrastructure/Update-Reference-Repos.groovy
- buildenv/jenkins/jobs/infrastructure/artifactory_cleanup.groovy
- buildenv/jenkins/jobs/infrastructure/branchSplit.groovy
- buildenv/jenkins/jobs/infrastructure/copyrightCheck.groovy
- buildenv/jenkins/jobs/infrastructure/lineEndingsCheck.groovy
- buildenv/jenkins/jobs/infrastructure/omrMirror.groovy
- buildenv/jenkins/jobs/infrastructure/signedOffByCheck.groovy
- buildenv/jenkins/jobs/infrastructure/tagRepos.groovy
- buildenv/jenkins/jobs/infrastructure/wrapper_job.groovy
- buildenv/jenkins/jobs/infrastructure/wrapper_template.groovy
- buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
- buildenv/jenkins/jobs/pipelines/Pipeline_Template.groovy
* use whitespace consistently
* indent only with spaces
* remove trailing whitespace
> Tidy up in buildenv/jenkins

- buildenv/jenkins/jobs/infrastructure/wrapper_template.groovy
- buildenv/jenkins/jobs/pipelines/Pipeline_Template.groovy
- DSL changes require Jenkins admin approval
unless the dsl security setting is disabled.
[skip ci]
Related #10016
> Add comment about DSL changes

- runtime/compiler/z/codegen/ForceRecompilationSnippet.cpp
> Fix ForceRecompilationSnippet.cpp compilation error

- test/functional/Java11andUp/build.xml
- test/functional/Java11andUp/playlist.xml
- test/functional/Java14andUp/build.xml
- test/functional/Java14andUp/playlist.xml
- test/functional/Java14andUp/src/org/openj9/test/utilities/RecordClassGenerator.java
- test/functional/cmdLineTests/lockWordAlignment/alignmentSettings.mk
Merge needs to be coordinated with: https://github.com/AdoptOpenJDK/TKG/pull/89
- this includes support for Java 15 preview features
- Records API has been updated from experimental
This update is needed for sealed classes testing (https://github.com/eclipse/openj9/issues/9626)
And enabling test for the Java 15 Records preview (https://github.com/eclipse/openj9/issues/8590) (https://github.com/eclipse/openj9/issues/9529)
> Upgrade ASM version to 8.0.1

- runtime/gc_realtime/Scheduler.cpp
This change is to prepare for eclipse/omr#5336.
Scheduler's base class method `MM_ParallelDispatcher::prepareThreadsForTask` will be reworked. Scheduler should continue to make use of the original implementation.
- Copy `MM_ParallelDispatcher::prepareThreadsForTask` implementation to `MM_Scheduler::prepareThreadsForTask` method (existing override)
- Remove call to `MM_ParallelDispatcher::prepareThreadsForTask` from Scheduler
> Implement Scheduler's prepareThreadsForTask From Base Class

- buildenv/jenkins/common/build.groovy
Most of the omitted files are available in the debug image (an exception is `*.map` files on Windows).
Fixes: #9996.
> Omit debuginfo files from the main SDK archive

- runtime/jvmti/jvmtiClass.c
GetClassLoaderClasses returns the list of classes whose loading was
initiated by the given class loader, including the base type primitive
array classes. All array classes of these classes must also be returned.
Fixes: #9965
[ci skip]
> Include array classes in GetClassLoaderClasses

- runtime/compiler/CMakeLists.txt
- runtime/compiler/aarch64/CMakeLists.txt
> CMake: Add aarch64 support to the jit

- buildspecs/j9.build-info
New Windows binaries for VS2017
[skip ci]
> Update fips sha

- jcl/src/java.base/share/classes/java/lang/Thread.java
- runtime/oti/vmconstantpool.xml
- runtime/vm/vmthread.c
- test/functional/Java11andUp/build.xml
- test/functional/Java11andUp/playlist.xml
- test/functional/Java14andUp/build.xml
- test/functional/Java14andUp/playlist.xml
- test/functional/Java14andUp/src/org/openj9/test/java/lang/Test_Thread.java
- test/functional/Java14andUp/src/org/openj9/test/utilities/RecordClassGenerator.java
- test/functional/Java14andUp/testng.xml
- test/functional/cmdLineTests/lockWordAlignment/alignmentSettings.mk
Port:  #10057 and #9341
Related: https://github.com/eclipse/openj9/issues/10091
Signed-off-by: lanxia lan_xia@ca.ibm.com
> (v0.20.0) Upgrade ASM version to 8.0.1

- runtime/cmake/caches/linux_aarch64.cmake
- runtime/cmake/caches/linux_aarch64_cmprssptrs.cmake
> CMake: add cache files for aarch64

- buildenv/jenkins/README.md
- buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
- buildenv/jenkins/variables/defaults.yml
Adds AIX non compressed refs to build pipeline
> Add Option to Build AIX with full references

- buildenv/jenkins/variables/defaults.yml
> Jenkins: Enable -Werror on cmake builds

- test/functional/Java11andUp/build.xml
- test/functional/Java11andUp/playlist.xml
- test/functional/Java14andUp/build.xml
- test/functional/Java14andUp/playlist.xml
- test/functional/Java14andUp/src/org/openj9/test/utilities/RecordClassGenerator.java
- test/functional/cmdLineTests/lockWordAlignment/alignmentSettings.mk
- this includes support for Java 15 preview features
- Records API has been updated from experimental
Cherry pick of #10057 for the 0.21.0 release.
Fixes #10091
> (v0.21.0) Upgrade ASM version to 8.0.1

- runtime/jvmti/jvmtiClass.c
Exit redefineclassescommon gracefully if we fail to recreate a single
ramClass.
Fixes: https://github.com/eclipse/openj9/issues/10104
> Do not notify GC if class redef fails

- test/docs/OpenJ9TestUserGuide.md
> Update OpenJ9TestUserGuide to remove "_" from TESTLIST

- test/functional/DDR_Test/playlist.xml
- test/functional/DDR_Test/src/j9vm/test/ddrext/AutoRun.java
related issue: https://github.com/eclipse/openj9/issues/1511
> enable TestCollisionResilientHashtable in DDR_Test

- test/functional/Java11andUp/build.xml
- test/functional/Java11andUp/playlist.xml
- test/functional/Java14andUp/build.xml
- test/functional/Java14andUp/playlist.xml
- test/functional/cmdLineTests/lockWordAlignment/alignmentSettings.mk
Resolve: https://github.com/AdoptOpenJDK/TKG/issues/90
Related: https://github.com/AdoptOpenJDK/TKG/pull/93
[ci skip]
> Rename asm-8.0.1.jar to asm.jar

- test/functional/Java11andUp/build.xml
- test/functional/Java11andUp/playlist.xml
- test/functional/Java14andUp/build.xml
- test/functional/Java14andUp/playlist.xml
- test/functional/cmdLineTests/lockWordAlignment/alignmentSettings.mk
Cherry pick of #10116 for the 0.21.0 release.
> (v0.21.0) Rename asm-8.0.1.jar to asm.jar

- buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
> Jenkins: add aarch64 cmake builds

- runtime/compiler/z/codegen/J9CodeGenerator.cpp
> Disable array translate support for remote compilations

- test/functional/Java8andUp/build.xml
- test/functional/cmdLineTests/proxyFieldAccess/build.xml
- test/functional/cmdLineTests/proxyFieldAccess/playlist.xml
> Stop using obsolete javac option -Xmodule: in tests

- test/functional/cmdLineTests/proxyFieldAccess/build.xml
Tested on Windows JDK11 via https://ci.eclipse.org/openj9/view/Test/job/Grinder/957
Tested on plinux JDK11 via https://ci.eclipse.org/openj9/view/Test/job/Grinder/958
Tested on Windows JDK8 via https://ci.eclipse.org/openj9/view/Test/job/Grinder/962
Tested on plinux JDK8 via https://ci.eclipse.org/openj9/view/Test/job/Grinder/963
Fixes https://github.com/eclipse/openj9/pull/10131#issuecomment-657065913
> Set proxyFieldAccess test build destdir to fix Windows compile

- runtime/vm/stringhelpers.cpp
The intention of this change is to avoid allocating memory
twice in both `verifyQualifiedName` and `internalFindClassString`
> Remove copyStringToUTF8WithMemAlloc from verifyQualifiedName

- test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_Object.java
Related to: https://github.com/eclipse/openj9/issues/10071
> Remove unused test variables

- runtime/compiler/p/codegen/DFPTreeEvaluator.cpp
> Fix incorrect tests for mtvsr* instruction support

- runtime/gc_glue_java/MarkingDelegate.hpp
New delegate stub to be used in the future for metronome.
cc @jason-hall @amicic
> Add setupIndexableScanner to MarkingDelegate

- runtime/nls/cfre/cfrerr_ca.nls
- runtime/nls/cfre/cfrerr_cs.nls
- runtime/nls/cfre/cfrerr_de.nls
- runtime/nls/cfre/cfrerr_es.nls
- runtime/nls/cfre/cfrerr_fr.nls
- runtime/nls/cfre/cfrerr_hu.nls
- runtime/nls/cfre/cfrerr_it.nls
- runtime/nls/cfre/cfrerr_ja.nls
- runtime/nls/cfre/cfrerr_ko.nls
- runtime/nls/cfre/cfrerr_pl.nls
- runtime/nls/cfre/cfrerr_pt_BR.nls
- runtime/nls/cfre/cfrerr_ru.nls
- runtime/nls/cfre/cfrerr_sk.nls
- runtime/nls/cfre/cfrerr_sl.nls
- runtime/nls/cfre/cfrerr_tr.nls
- runtime/nls/cfre/cfrerr_zh.nls
- runtime/nls/cfre/cfrerr_zh_CN.nls
- runtime/nls/cfre/cfrerr_zh_TW.nls
Files update for JAV11 PII_Ship2.
Signed-off-by: Xiao Juan Chen <bjchenxj@cn.ibm.com>
> Modify the translated PII files in nls folder - 20200720

- test/functional/Java11andUp/playlist.xml
> Exclude Nestmate_virtual_private tests on zos

- runtime/bcutil/ClassFileWriter.cpp
- runtime/bcutil/cfreader.c
- runtime/cfdumper/main.c
- runtime/oti/cfr.h
- runtime/util/romclasswalk.c
Related to: https://github.com/eclipse/openj9/issues/9626
> JEP 360: cfdumper support

- test/functional/JIT_Test/playlist.xml
- test/functional/Java8andUp/playlist.xml
- test/functional/Jsr335/playlist.xml
- test/functional/cmdLineTests/openssl/playlist.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml
Related: runtimes/backlog/issues/356
[ci skip]
> Add impl ibm to Java 11+ openj9 tests

- runtime/tests/aixerrmsg/CMakeLists.txt
> CMake: Build aixbaddep test library

- runtime/util/hshelp.c
- test/functional/Java15andUp/META-INF/MANIFEST.MF
- test/functional/Java15andUp/build.xml
- test/functional/Java15andUp/playlist.xml
- test/functional/Java15andUp/src/org/openj9/test/java/lang/instrument/Test_Instrumentation.java
- test/functional/Java15andUp/src/org/openj9/test/utilities/JavaAgent.java
- test/functional/Java15andUp/src/org/openj9/test/utilities/SealedClassGenerator.java
- test/functional/Java15andUp/testng.xml
Related to: https://github.com/eclipse/openj9/issues/9626
> JEP 360 sealed classes instrumentation restrictions

- buildenv/aix/jdk15/yum_install_aix-ppc64.txt
- doc/build-instructions/Build_Instructions_V15.md
Based off OpenJDK14 - might need some amendments.
[ci skip]
> Add new set of build instructions for OpenJDK15

- runtime/jnichk/jnicmem.c
This fixes a hang scenario:
One thread holds VM access and attempts to enter `MemMonitor`;
Another thread already entered `MemMonitor`, `exitJavaVM()` due to `fatalError()`, and `acquireExclusiveVMAccessFromExternalThread()` but can't acquire exclusive VM access because last thread holds the VM access which can't proceed either since this thread holds `MemMonitor`, hence deadlock.
This PR exits `MemMonitor` before invoking `jniCheckFatalErrorNLS()/fatalError()` to avoid the hang scenario above.
closes: #10191 
> Exit MemMonitor before jniCheckFatalErrorNLS() if not JNICHK_NONFATAL

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
This commit enables `OutOfLineCodeSection` for `ZEROCHKEvaluator` on aarch64.
Depends on:
https://github.com/eclipse/omr/pull/5392
https://github.com/eclipse/openj9/pull/10155
> AArch64: Enable OOL for ZEROCHKEvaluator

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
This commit enables `OutOfLineCodeSection` for `VMnewEvaluator`.
Depends on:
https://github.com/eclipse/omr/pull/5392
https://github.com/eclipse/openj9/pull/10155
> AArch64: Enable OOL for VMnewEvaluator

- test/functional/NativeTest/nativeTestSettings.mk
- test/functional/NativeTest/playlist.xml
- Add target for TestInvtest in playlist.xml
- Added makefile to account for variable dependencies based on spec and version
[ci skip]
Signed-off-by: Nikola Milijevic <nmilijev@uwaterloo.ca>
> Migrate TestInvtest to OpenJ9

- runtime/tests/port/si.c
On z/OS the /tmp directory is typically found under /SYSTEM. On OSX,
under /private. Rather than hard coding assumptions, update the test to
determine the location of /tmp dynamically.
Before the fix:
```
Starting test j9sysinfo_test_get_cwd3
mkdir /tmp/j9sysinfo_test_get_cwd3/
cd /tmp/j9sysinfo_test_get_cwd3/
CWD = /SYSTEM/tmp/j9sysinfo_test_get_cwd3
./si.c line 1907: j9sysinfo_test_get_cwd3 invalid directory rc: 1
LastErrorNumber: 0
LastErrorMessage: 
Ending test j9sysinfo_test_get_cwd3
```
With the fix:
```
Starting test j9sysinfo_test_get_cwd3
cd /tmp/
CWD = /SYSTEM/tmp
expected result /SYSTEM/tmp/j9sysinfo_test_get_cwd3/
mkdir j9sysinfo_test_get_cwd3/
cd j9sysinfo_test_get_cwd3/
CWD = /SYSTEM/tmp/j9sysinfo_test_get_cwd3
Ending test j9sysinfo_test_get_cwd3
```
> Fix sysinfo_test_get_cwd3 to handle symlinks

- runtime/j9vm/exports.cmake
- runtime/j9vm/j9vmnatives.xml
- runtime/j9vm/java11vmi.c
- runtime/j9vm/module.xml
- runtime/redirector/forwarders.m4
- runtime/redirector/module.xml
> Add JVM_IsUseContainerSupport for jdk16

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
This commit fixes arraylengthEvaluator() for AArch64, changing the
mnemonic for loading the array length.
> AArch64: Fix arraylengthEvaluator()

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Reverts eclipse/openj9#10319
I clicked the "Merge" button by mistake.
> Revert "AArch64: Fix arraylengthEvaluator()"

- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-1.xml
Related: https://github.com/eclipse/openj9/pull/10291
[ci skip]
> Fix aarch64 regex in ShareClassesCMLTests-1.xml

- jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
> Revert "Selectively enforce lookup class package check"

- jcl/jpp_configuration.xml
- jcl/src/java.base/share/classes/com/ibm/oti/vm/AbstractClassLoader.java
- jcl/src/java.base/share/classes/java/lang/StackTraceElement.java
- jcl/src/java.base/share/classes/java/lang/ThreadGroup.java
- jcl/src/java.base/share/classes/java/lang/Throwable.java
* remove JAVA14 configuration
* remove obsolete flag: AnnotateOverride
* remove unused flag: Sidecar15
* sort classpath entries
* use whitespace consistently
> Tidy up jpp_configuration.xml

- runtime/compiler/env/J9ClassEnv.cpp
Create TypeLayoutEntry for flattened fields with adjusted offset from the top level class for value types.
This change was originally authored by Yi Zhang who is listed as a co-author below.
Co-authored-by: Yi Zhang yizhang@ca.ibm.com
> Add TypeLayoutEntry build for flattened fields

- jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
- jcl/src/java.base/share/classes/java/lang/invoke/CollectHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/ConstantHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/ConvertHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/DelegatingMethodHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/DirectMethodHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/DynamicInvokerHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/FilterArgumentsHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/FilterArgumentsWithCombinerHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/FilterReturnHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/FoldHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/GuardWithTestHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/InsertHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/MethodHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
- jcl/src/java.base/share/classes/java/lang/invoke/PassThroughHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/PermuteHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/PrimitiveHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/ReceiverBoundHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/SimpleMethodHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/SpreadHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/VarHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/VarargsCollectorHandle.java
1. Add support for IndirectVarHandle.
2. Scan for checked exceptions in OpenJ9 MethodHandles.
https://github.com/ibmruntimes/openj9-openjdk-jdk15/pull/11 depends on this PR.
Related: #9625.
> JEP383 Support Part 4

- runtime/compiler/z/codegen/J9CodeGenerator.cpp
- runtime/compiler/z/codegen/J9CodeGenerator.hpp
> Create correct relocation record for java_lang_invoke_ComputedCalls_dispatchJ9Method in remote compilations

- test/functional/DDR_Test/playlist.xml
- test/functional/DDR_Test/src/j9vm/test/ddrext/AutoRun.java
- test/functional/DDR_Test/tck_ddrext.xml
> enable testDDRExtJunit_MonitorsAndDeadlock* in DDR

- runtime/compiler/il/J9IL.cpp
- runtime/compiler/il/J9IL.hpp
> Override opCodeForCorrespondingDirect API in OMR

- test/README.md
- test/docs/OpenJ9TestUserGuide.md
> Update instruction to run disabled test in readme files

- runtime/oti/VMHelpers.hpp
> isHiddenMethod() should include method from hidden classes

- runtime/oti/VMHelpers.hpp
> (v0.22.0) isHiddenMethod() should include method from hidden classes

- runtime/jvmti/suspendhelper.cpp
When suspending a thread, handle the case where the Thread lock object
has not yet been assigned. This can occur if an event (e.g. method
enter) is reported during the construction of the Thread object. The
thread will be in the thread list, but the object will not be fully
intitialized.
[ci skip]
> Check for NULL thread lock

- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/OptInfo.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/J9ROMClassHelper.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/RomClassWalker.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/J9BCUtil.java
- runtime/oti/j9nonbuilder.h
- runtime/util/rcdump.c
Port from: https://github.com/eclipse/openj9/pull/10381
> JEP 360/JEP 384 Sealed classes and records ddr support

- runtime/jvmti/suspendhelper.cpp
When suspending a thread, handle the case where the Thread lock object
has not yet been assigned. This can occur if an event (e.g. method
enter) is reported during the construction of the Thread object. The
thread will be in the thread list, but the object will not be fully
intitialized.
[ci skip]
> (0.22) Check for NULL thread lock

- runtime/compiler/env/J9ClassEnv.cpp
- runtime/compiler/env/J9ClassEnv.hpp
- runtime/compiler/env/j9method.cpp
- runtime/compiler/env/j9method.h
Create JIT helper functions on checking flattened fields.
> Create JIT helper functions on checking flattened fields

- test/functional/DDR_Test/playlist.xml
- test/functional/DDR_Test/src/j9vm/test/corehelper/FindExtCoreGenerator.java
- test/functional/DDR_Test/src/j9vm/test/ddrext/AutoRun.java
- test/functional/DDR_Test/src/j9vm/test/ddrext/Constants.java
> enable FindExtThread in DDR

- runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
- runtime/compiler/runtime/MetaData.cpp
- runtime/compiler/runtime/RelocationRuntimeLogger.cpp
- Merge `TR_TraceReloCG` into `TR_TraceRelocatableDataCG`
- Remove `TR_TraceRelocatableDataDetailsRT`
- Remove `TR_TraceRelocatableDataRT`
Closes: #9428
> Merge/Remove 3/5 relocation options

- runtime/compiler/optimizer/SPMDParallelizer.cpp
In some cases, the generated IL will put the IV increment before
the instructions that will be vectorized. This may cause wrong
address being used when auto vectorization is performed.
This commit disables the auto vectorization for such case.
Signed-off-by: Mohammad Nazmul Alam <mohammad.nazmul.alam@ibm.com>
> Disable AutoSIMD for problematic IV increment

- runtime/port/unix/j9sysinfo.c
Signed-off-by: gaoli <gaolibj@cn.ibm.com>
> Add IBM i specific chagnes to fix build issues

- README.md
> Add openj9-utils repo

- runtime/vm/CMakeLists.txt
> CMake: Update flag handling on interpreter sources

- jcl/src/java.base/share/classes/java/lang/Class.java
@ChengJin01 's changes from https://github.com/eclipse/openj9/pull/7985 plus an add on (see https://github.com/eclipse/openj9/pull/7985#issuecomment-567709614)
Fixes: #7897
Fixes: https://github.com/eclipse/openj9/issues/7623
> Fix Class.getMethod() and Class.getMethods() missing cases

- jcl/src/java.base/share/classes/com/ibm/oti/vm/VMLangAccess.java
- jcl/src/java.base/share/classes/java/lang/VMAccess.java
- jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
> (v0.22.0) Ensure Lookup::defineClass links the class

- runtime/compiler/p/codegen/CallSnippet.cpp
- runtime/compiler/p/codegen/PPCPrivateLinkage.cpp
- runtime/compiler/runtime/Trampoline.cpp
Previously, either pTOC entry or long sequence are used in gettting
the snippet address. Prefixed instruction can be used for the same
purpose nicely on P10 without pTOC.
Correspondingly, interface snippet emitting needs to change. In
particular, CallSitePatching needs to be adjusted as well.
Signed-off-by: Julian Wang <zlwang@ca.ibm.com>
> Exploit prefixed instruction in IPIC sequence on POWER10

- runtime/jcl/common/java_lang_Class.cpp
> Remove rename unnecessary local variable

- test/functional/cmdLineTests/shareClassTests/URLHelperTests/URLHelperTests.xml
- test/functional/cmdLineTests/shareClassTests/URLHelperTests/URLHelperTests_80.xml
Fix SCC cmdLineTester test failures
Fixes: https://github.com/eclipse/openj9/issues/10584
> Fix SCC cmdLineTester test failures

- doc/build-instructions/Build_Instructions_V8.md
This commit describes how to build JDK 8 for AArch64 Linux in
Build_Instructions_V8.md.
[ci skip]
> Update AArch64 section in Build_Instructions_V8.md

- buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
> Allow building of aarch64 for all current releases

- doc/snapshot/building.md
> Basic snapshot branch build instructions

- .github/ISSUE_TEMPLATE/snapshot_issue.md
> Create "snapshot" label issue template

- doc/release-notes/0.22/0.22.md
Add doc/release-notes/0.22.md
Signed-off-by: Peter Hayward <pmhayward@uk.ibm.com>
> Create release notes for 0.22.0

- buildenv/jenkins/variables/defaults.yml
> Update to openssl 1.1.1h

- jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/corereaders/NewElfDump.java
- jcl/src/openj9.dtfj/share/classes/com/ibm/jvm/j9/dump/extract/Main.java
This is a replay of #10661 for the 0.23.0 release.
> (0.23.0) Improve jextract for ELF core files

- .github/ISSUE_TEMPLATE/epic-issue.md
Closes https://github.com/eclipse/openj9/issues/4275
> Add Epic Issue template

- jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
> Fix possible NPE in J9VMInternals.getClassInfoStrings()

- runtime/compiler/env/VMJ9.cpp
- runtime/compiler/env/VMJ9.h
> Add routines to fetch target method from MethodHandle and MemberName

- runtime/compiler/runtime/codertinit.cpp
- runtime/compiler/z/codegen/J9TreeEvaluator.cpp
- runtime/jcl/common/unsafe_mem.c
- runtime/vm/jvminit.c
Fix compilation failures seen while building JDK on Z.
> Fix compilation failures for building JDK ON Z

- jcl/src/java.base/share/classes/java/lang/invoke/CallSite.java
- jcl/src/java.base/share/classes/java/lang/invoke/CollectHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/ConvertHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/FilterReturnHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/MethodHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/MethodHandleInfoImpl.java
- jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
- jcl/src/java.base/share/classes/java/lang/invoke/MethodType.java
- jcl/src/java.base/share/classes/java/lang/invoke/NativeMethodHandle.java
- jcl/src/java.base/share/classes/java/lang/invoke/VarHandle.java
MT.returnType       -> MT.returnType()
MT.arguments        -> MT.ptypes()
MT.arguments[?]     -> MT.parameterType(?)
MT.arguments.length -> MT.parameterCount()
Related: #7352 
> rename MT field access outside of MethodType.java

- runtime/j9vm/exports.cmake
- runtime/j9vm/j9vmnatives.xml
- runtime/j9vm/java11vmi.c
- runtime/j9vm/module.xml
- runtime/redirector/forwarders.m4
- runtime/redirector/module.xml
> Rename JVM functions supporting CDS for jdk 16

- test/functional/cmdLineTests/reflectCache/playlist.xml
> temporarily disable cmdLineTester_reflectCache on JDK15

- runtime/compiler/control/CompilationController.cpp
- runtime/compiler/control/CompilationRuntime.hpp
- runtime/compiler/control/CompilationThread.cpp
- runtime/compiler/control/HookedByTheJit.cpp
- runtime/compiler/control/JITClientCompilationThread.cpp
- runtime/compiler/net/CommunicationStream.hpp
- runtime/compiler/net/MessageTypes.hpp
- runtime/oti/j9nonbuilder.h
Port of https://github.com/eclipse/openj9/pull/10672 into 0.23
> Fix Start PC race condition (0.23)

- runtime/compiler/runtime/JITClientSession.cpp
- runtime/compiler/runtime/JITClientSession.hpp
- runtime/compiler/runtime/SymbolValidationManager.cpp
- runtime/compiler/runtime/SymbolValidationManager.hpp
> (0.23) Store classes not worth remembering per client for JITServer

- runtime/nls/cdrt/codert_ca.nls
- runtime/nls/cdrt/codert_es.nls
- runtime/nls/dump/j9dmp_ca.nls
- runtime/nls/j9cl/j9jcl_ca.nls
- runtime/nls/j9ti/jvmti_ca.nls
- runtime/nls/j9vm/j9vm_ca.nls
- runtime/nls/jnck/jnichk_ca.nls
- runtime/nls/shrc/j9shr_ca.nls
Files update for JAV11 project TVT_Pass2.
Signed-off-by: Xiao Juan Chen <bjchenxj@cn.ibm.com>
> Modify the translated PII files in nls folder - 20200929

- runtime/nls/cdrt/codert_ca.nls
- runtime/nls/cdrt/codert_es.nls
- runtime/nls/dump/j9dmp_ca.nls
- runtime/nls/j9cl/j9jcl_ca.nls
- runtime/nls/j9ti/jvmti_ca.nls
- runtime/nls/j9vm/j9vm_ca.nls
- runtime/nls/jnck/jnichk_ca.nls
- runtime/nls/shrc/j9shr_ca.nls
Files update for JAV11 project TVT_Pass2.
Cherry pick https://github.com/eclipse/openj9/pull/10739 for the 0.23.0 release.
> (0.23.0) Modify the translated PII files in nls folder - 20200929

- runtime/vm/createramclass.cpp
Delay init of ramclass link params
When a class fails loading due to a classloading constraint error, the
ramclass remains in the class memory segments with an unverified state.
This causes a a crash in the GC because the GC expects all ramclasses to
have classObjects assign. Delaying the linking of the class in the
memory segment list and subclass traversal list until after the class
passes loading constraints checks will ensure that the GC or any other 
component cannot iterate an invalid class.
Fixes: https://github.com/eclipse/openj9/issues/10541
> Delay init of ramclass link params 

- buildenv/jenkins/variables/defaults.yml
> Update boot JDKs for jdknext

- test/functional/VM_Test/build.xml
- test/functional/VM_Test/classUnloadingSupportTests/src/j9vm/test/classunloading/classestoload/ClassToLoad1.java
- test/functional/VM_Test/classUnloadingSupportTests/src/j9vm/test/classunloading/classestoload/ClassToLoad2.java
- test/functional/VM_Test/classUnloadingSupportTests/src/j9vm/test/classunloading/classestoload/ClassToLoad3.java
- test/functional/VM_Test/classUnloadingSupportTests/src/j9vm/test/classunloading/classestoload/ClassToLoadWithException.java
- test/functional/VM_Test/classUnloadingSupportTests/src/j9vm/test/classunloading/classestoload/DependentClassToLoad1.java
- test/functional/VM_Test/classUnloadingSupportTests/src/j9vm/test/classunloading/classestoload/DependentClassToLoad2.java
- test/functional/VM_Test/classUnloadingSupportTests/src/j9vm/test/classunloading/classestoload/DependentClassToLoad3.java
- test/functional/VM_Test/classUnloadingSupportTests/src/j9vm/test/classunloading/classestoload/InterfaceToLoad1.java
- test/functional/VM_Test/classUnloadingSupportTests/src/j9vm/test/classunloading/classestoload/InterfaceToLoad2.java
- test/functional/VM_Test/classUnloadingSupportTests/src/j9vm/test/classunloading/classestoload/InterfaceToLoad3.java
- test/functional/VM_Test/playlist.xml
- test/functional/VM_Test/src/j9vm/test/classunloading/ClassPathSettingClassLoader.java
-related: backlog issue 387
[ci skip]
> add j9vmClassUnloading into openj9

- test/functional/Java8andUp/build.xml
- test/functional/Java8andUp/playlist.xml
- test/functional/Java8andUp/scr_DupClassNameTest/version1/DupClassNameTest.java
- test/functional/Java8andUp/scr_DupClassNameTest/version2/DupClassNameTest.java
Add a test that there are 2 different classes with the 
same name loaded by 2 different class loaders.
> Add DupClassNameTest

- buildenv/jenkins/common/variables-functions.groovy
> Change == to .equals on groovy string compare

- doc/release-notes/0.23/0.23.md
New changes for 0.23.0
[ci-skip]
> Add release notes for 0.23.0

- debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/elf/ProgramHeaderEntry.java
Copyright not updated in #10754
> Fix copyright in file that was recently updated

- runtime/jnichk/jnicheck.c
- runtime/jnichk/jnichk_internal.h
- runtime/jnichk/jnicwrappers.c
> Detect NULL jvalue pointers in JNI check

- runtime/compiler/control/JITClientCompilationThread.cpp
- runtime/compiler/net/CommunicationStream.hpp
- runtime/compiler/runtime/JITClientSession.hpp
- runtime/compiler/runtime/Runtime.cpp
> (0.23) Fetch addresses of helper methods from the client

- buildenv/jenkins/common/variables-functions.groovy
- buildenv/jenkins/variables/defaults.yml
Cherry picked from master and Peter's fork
> (0.23.0) Auto download bootjdk & Remove excludes for special.system tests

- runtime/compiler/runtime/RelocationRuntime.cpp
- runtime/shared_common/CacheMap.cpp
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-1.xml
depends on: https://github.com/eclipse/omr/pull/5570
> Print processor feature in Xshareclasses:printStats for Z

- jcl/src/java.base/share/classes/java/lang/String.java
- jcl/src/java.base/share/classes/java/lang/Thread.java
* String.java - only for Java 12
* Thread.java - only for Java 13
> Remove code that only applies to unsupported versions

- .github/workflows/assign-to-snapshot-project.yml
Extend triage automation to MH-related PRs as well
> Add support to assign project:MH to its project

- runtime/jnichk/jnicheck.c
- runtime/jnichk/jnichk_internal.h
- runtime/jnichk/jnicwrappers.c
> Check class loader type in JNI check DefineClass

- runtime/shared_common/CacheMap.cpp
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-1.xml
> Print cpu feature in Xshareclasses:printStats for Power

- runtime/compiler/runtime/RelocationRuntime.cpp
- runtime/compiler/runtime/RelocationRuntime.hpp
- runtime/nls/jitm/j9jit.nls
> Add variableHeapBarrier to AOT compatibility check

- runtime/jnichk/jnicheck.c
> Fix compile errors from #10877

- runtime/compiler/optimizer/IdiomRecognition.cpp
- runtime/compiler/optimizer/IdiomTransformations.cpp
- runtime/compiler/runtime/JITServerIProfiler.cpp
- runtime/compiler/z/codegen/S390CHelperLinkage.hpp
Reverts eclipse/openj9#10865
See https://github.com/eclipse/openj9/pull/10865#issuecomment-708717529
> Revert "Use TR_UNIMPLEMENTED macro in JIT"

- test/functional/cmdLineTests/fastClassHashTable/build.xml
- test/functional/cmdLineTests/fastClassHashTable/fastClassHashTableTest.xml
- test/functional/cmdLineTests/fastClassHashTable/playlist.xml
Related: runtimes/backlog/issues/378
[ci skip]
> Port cmdLineTester_fastClassHashTable into openj9

- jcl/jpp_configuration.xml
* enable use of recent preprocessor improvements (#10870)
* also fix classpath for PANAMA configuration
> Define preprocessor macro 'JAVA_SPEC_VERSION'

- buildenv/jenkins/variables/defaults.yml
* [skip ci]
* eclipse/openj9#10666
> Update Windows to openssh 1.1.1h

- buildenv/jenkins/variables/defaults.yml
> Update 0.23.0 release branch to use openssl 1.1.1h for all platforms

- doc/release-notes/0.23/0.23.md
> Adding JITServer tech preview for Linux on P/Z to 0.23 release notes

- buildspecs/linux_arm.spec
Issue https://github.com/eclipse/openj9/issues/10412
> Disable java 8 autobuild of the ARM platform

- runtime/bcverify/rtverify.c
For OpenJDK VarHandles, the invokevirtual calls to the VarHandle
polymorphic methods are rewritten to the invokehandle bytecode in
ClassFileOracle (#10557). Bytecode verification has been updated to
handle this conversion. These changes are identical to the existing
MethodHandle handling.
Related: #7352
Co-authored-by: Jack Lu <Jack.S.Lu@ibm.com>
> Update bytecode verification to support OpenJDK VarHandles

- runtime/j9vm/exports.cmake
- runtime/j9vm/j9vmnatives.xml
- runtime/j9vm/java11vmi.c
- runtime/redirector/forwarders.m4
> Remove JVM_IsDynamicDumpingEnabled

- runtime/compiler/control/J9Options.cpp
- runtime/compiler/control/JITClientCompilationThread.cpp
- runtime/compiler/env/VMJ9.h
- runtime/compiler/env/VMJ9Server.cpp
- runtime/compiler/env/VMJ9Server.hpp
- runtime/compiler/net/CommunicationStream.hpp
- runtime/compiler/runtime/JITClientSession.hpp
> Use JITClient's heap boundary addresses in JITServer

- test/functional/DDR_Test/playlist.xml
- test/functional/DDR_Test/src/j9vm/test/corehelper/SimpleThread.java
- test/functional/DDR_Test/src/j9vm/test/ddrext/Constants.java
related: backlog/issue 112
[ci skip]
> port testDDRExt_Class into OpenJ9

- doc/diagnostics/AddingTracepoints.md
> Add description of various types of tracepoints

- runtime/compiler/env/VMJ9Server.hpp
> Enable support embedded heap bounds for JITServer

- runtime/compiler/ilgen/Walker.cpp
Folding final fields early can benefit more optimizations.
Folding instance final fields outside of MethodHandle will expose an
optimizer bug that is still under investigation. As for now, fold only
instance fields from MethodHandle.
#4837 
> Fold final field in ILGen

- runtime/compiler/p/codegen/J9PPCInstruction.cpp
> Use entryPointFromCompiledMethod linkage API for recursive calls

- jcl/src/java.base/share/classes/java/lang/reflect/Array.java
See discussion in #10979
[ci skip]
> Restore previous optimization in existing LTS streams

- runtime/redirector/CMakeLists.txt
> CMake: link the redirector against omrutil on zos

- runtime/port/CMakeLists.txt
> CMake: compile metal-c files in port library

- runtime/port/CMakeLists.txt
> CMake: include omr metal-c files in port library

- doc/compiler/BestPractices.md
> Add "JITServer Best Practices" to documentation

- test/functional/cmdLineTests/bootStrapStaticVerify/build.xml
- test/functional/cmdLineTests/doProtectedAccessCheck/build.xml
- test/functional/cmdLineTests/dscr/build.xml
- test/functional/cmdLineTests/locales/build.xml
- test/functional/cmdLineTests/reflectCache/build.xml
- test/functional/cmdLineTests/shareClassTests/BadStackMap/build.xml
- test/functional/cmdLineTests/shareClassTests/StorageKey/build.xml
> fix Prologue Failure in vm farm

- runtime/jnichk/jnicheck.c
> Detect internal class refs in JNI check pedantic mode

- jcl/src/java.base/share/classes/java/lang/Class.java
It appears #10930 is causing https://github.com/eclipse/openj9/issues/11040
> Revert #10930 and #11017

- runtime/tests/jvmtitests/src/com/ibm/jvmti/tests/classModificationAgent/cma001.c
> Fix tabs vs spaces formatting issues

- test/functional/VM_Test/playlist.xml
> port xlpTests, xlpCodeCacheTests into openj9

- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/view/dtfj/java/DTFJJavaRuntime.java
- jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/java/JavaRuntime.java
- jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/java/j9/JavaRuntime.java
- jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/java/javacore/JCJavaRuntime.java
- jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/phd/PHDJavaRuntime.java
- jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/DTFJContext.java
- jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/CombinedContext.java
- jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/OpenCommand.java
Reverts eclipse/openj9#11049
See https://github.com/eclipse/openj9/pull/11049#issuecomment-719538271
> Revert "Warn of mismatch between jdmpview and producer of core file"

- runtime/compiler/env/j9method.cpp
- runtime/compiler/env/j9method.h
- runtime/compiler/env/j9methodServer.cpp
- runtime/compiler/env/j9methodServer.hpp
PR #10617 modified a number of methods of ResolvedMethod classes.
This commit implements these changes for JITServer
Closes: #10941
> Handle MethodHandle signature-polymorphic native methods for JITServer

- doc/compiler/BestPractices.md
[ci skip]
Update the Best Practices doc with a point regarding updating the
MINOR_VERSION when a change is made to the frontend or a relocation.
> Update Best Practices Doc

- buildspecs/osx_x86-64.spec
- buildspecs/osx_x86-64_cmprssptrs.spec
- runtime/cmake/caches/osx_x86-64.cmake
- runtime/cmake/options.cmake
- runtime/gc_base/IndexableObjectAllocationModel.cpp
- runtime/gc_base/IndexableObjectAllocationModel.hpp
- runtime/gc_glue_java/configure_includes/configure_osx.mk
- runtime/gc_vlhgc/CopyForwardScheme.cpp
- runtime/gc_vlhgc/GlobalMarkingScheme.cpp
Update call to double map API
Depends on: https://github.com/eclipse/omr/pull/5580
> Add double map API to OSX

- buildenv/jenkins/variables/defaults.yml
- runtime/compiler/build/toolcfg/win-msvc/common.mk
> Revert "Update JDK8 windows compiles to use Visual Studio 2013"

- runtime/bcverify/bcverify.c
While reviewing #11086, I looked at mergeStacks (the
source of the compiler bug) and see that there are a
lot of uninitialized variables.
First attempt at this moved them inside the loop but
this is clearly wrong - see the VerifyErrors that
occurred, causing it to be reverted.
> Initialize variables so mergeStacks is easier to read

- buildenv/jenkins/variables/defaults.yml
- runtime/compiler/build/toolcfg/win-msvc/common.mk
Reverts eclipse/openj9#11100
Restore https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/449
> Revert "Revert "Update JDK8 windows compiles to use Visual Studio 2013""

- jcl/src/jdk.jcmd/share/classes/openj9/tools/attach/diagnostics/tools/Jps.java
- test/functional/Java8andUp/src/org/openj9/test/attachAPI/TestJps.java
This patch improves jps to be able to handle composed arguments
Fixes #11036
Signed-off-by: Alexey Anufriev contact@alexey-anufriev.com
> Improve jps to be able to handle composed arguments

- buildenv/jenkins/common/pipeline-functions.groovy
Related: runtimes/backlog/issues/408
[ci skip]
> Enable parallel on zos test builds

- runtime/compiler/control/JITClientCompilationThread.cpp
- runtime/compiler/control/JITServerCompilationThread.cpp
- runtime/compiler/env/J9JitMemory.cpp
- runtime/compiler/env/J9SegmentAllocator.cpp
- runtime/compiler/env/JITServerCHTable.cpp
- runtime/compiler/net/LoadSSLLibs.cpp
- runtime/compiler/runtime/CompileService.cpp
- runtime/compiler/runtime/IProfiler.cpp
- runtime/compiler/runtime/JITClientSession.cpp
- runtime/compiler/runtime/JITServerStatisticsThread.cpp
- runtime/compiler/runtime/Listener.cpp
- runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp
> Add missing VerboseLog.hpp includes

- runtime/compiler/compile/J9SymbolReferenceTable.cpp
> Create known object for MethodHandle constant

- runtime/compiler/x/codegen/J9TreeEvaluator.cpp
Fix array size offset for inline allocated zero sized arrays in x86 systems. The fix adds 2 extra instructions to the path of array allocations and 3 instructions in case of zero sized arrays.
Tests were conducted and the proposed fix does not impact throughput and performance
The fix adds 2 instructions to the critical path of array allocations, and 3 instructions in case of zero sized arrays. The 2 added instructions are a compare and a jump, and the third is a store to properly initialize the size field in case of zero sized array.
This is x86 assembly before the change:
```
############# Before change ############
…
rep stosb                        # SAME 1
mov rax, rdx                     # SAME 2
mov dword ptr [rax], 0x0010b300  # SAME 3
mov dword ptr [rax+0x4], r12d    # SAME 4 …
```
> Fix array size offset for inlined zero sized arrays in x86

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Remove `TR_DisableInlineInstanceOf` guard since it is done
by `calculateInstanceOfOrCheckCastSequences` function.
Make `ArrayOfJavaLangObjectTest` simpler as it is folowed by `GoToFalse` only.
Generate `b` instruction to OOL helper call when non-test sequence is followed by `HelperCall`
or `HelperCall` is an only item in the sequence.
> AArch64: Cleanup instanceof evaluator

- runtime/compiler/x/codegen/J9TreeEvaluator.cpp
Reverts eclipse/openj9#10946
See https://github.com/eclipse/openj9/pull/10946#issuecomment-722922733
> Revert "Fix array size offset for inlined zero sized arrays in x86"

- test/functional/cmdLineTests/defaultLazySymbolResolution/build.xml
- test/functional/cmdLineTests/forceLazySymbolResolution/build.xml
related: https://github.com/AdoptOpenJDK/run-aqa/issues/37
[ci skip]
> exclude hotspot for default/forceLazySymbolResolution

- jcl/src/java.base/share/classes/java/lang/ref/Reference.java
- runtime/jcl/common/java_lang_ref_Reference.cpp
- runtime/jcl/exports.cmake
- runtime/jcl/module.xml
- runtime/jcl/uma/se16_exports.xml
- runtime/oti/jclprots.h
> Implement java.lang.ref.Reference.refersTo() for Java 16

- runtime/cmake/J9vmTargetSupport.cmake
- runtime/cmake/shared_lib.rc.in
> CMake: Add copyright info to dlls on windows

- runtime/jcl/common/java_lang_ref_Reference.cpp
* for consistency with declaration
> Remove JNIEXPORT from function definition

- runtime/vm/jvminit.c
- test/functional/cmdLineTests/xlogTests/build.xml
- test/functional/cmdLineTests/xlogTests/playlist.xml
- test/functional/cmdLineTests/xlogTests/xlog.xml
Issue https://github.com/eclipse/openj9/issues/10799
Doc issue https://github.com/eclipse/openj9-docs/issues/671
> Parse -Xlog:gc variants for compatibility and add tests

- runtime/vm/vmprops.c
The change is to convert the property value string from the platform
encoding to the modified UTF8 to adapt to the OS locale setting.
Fixes: #11139
> Convert the property value from the platform encoding to MUTF8 string

- runtime/shared_common/CacheMap.cpp
1. Call ccToUse->getPrevious() only in the case of CC_STARTUP_OK, 
so that we don't pass in a NULL ccToUse to handleStartupError().
2. In the case of CM_CACHE_CORRUPT, jump to handleStartupError().
> Fix VM crash inside SH_CacheMap::handleStartupError()

- jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/tools/ToolsRegistryOutputChannels.java
- jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/tools/utils/OutputStreamModifier.java
- jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/tools/utils/StringReceiver.java
ByteArrayOutputStream is much more space-efficient than any list of Byte object references.
> Use ByteArrayOutputStream instead of List<Byte>

- runtime/vm/VMSnapshotImpl.cpp
Refactor the VMSnapshotImpl destructor to skip most of
the implementation if the `_vm` is null. This likely
indicates that we're shutting down from a partially
initialized state - likely due to a missing image
file.
Some additional refactoring to make the code slightly
clearer about which state we're in (restore / snapshot)
and what the expected behaviour is.
> Ensure we don't crash when image not present

- runtime/shared_common/CacheMap.cpp
- runtime/shared_common/CompositeCache.cpp
- runtime/shared_common/CompositeCacheImpl.hpp
- runtime/shared_common/j9shr.tdf
> Remove obsolete code related to CC_STARTUP_NO_CACHELETS

- runtime/compiler/z/codegen/S390J9CallSnippet.cpp
- runtime/compiler/z/codegen/S390PrivateLinkage.cpp
While addressing the suggestions on the PR, there were couple of issues introduced that was hitting the Assert. This commit fixes them.
> Fix failures on Z due to PIC Dispatch changes

- buildenv/jenkins/docker-slaves/jenkinsfile-build-container.groovy
- buildenv/jenkins/jobs/infrastructure/branchSplit.groovy
- buildenv/jenkins/jobs/infrastructure/omrMirror.groovy
- buildenv/jenkins/jobs/infrastructure/tagRepos.groovy
- buildenv/jenkins/variables/defaults.yml
> Update Jenkins Credential IDs to new human-readable names

- jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Log.java
- jcl/src/openj9.jvm/share/classes/com/ibm/jvm/package-info.java
Related to https://github.com/eclipse/openj9/pull/10873
> Update documentation from -Xlog to -Xsyslog

- runtime/compiler/optimizer/SPMDParallelizer.cpp
Changes default behavior for AutoSIMD under SPMDParallelizer to bail out if
there are asynccheck nodes in the loop.
Currently, calling out to handle asyncchecks does not interact well with
vector registers. It requires all vector registers to be spilled before the
call out. This is now avoided by AutoSIMD bailing out if there are asyncchecks
in the loop.
This also adds a new TR_enableAutoSIMDSkipAsynccheck env variable. When
TR_enableAutoSIMDSkipAsynccheck is set, AutoSIMD will remove asynccheck nodes
in a loop when parallelzing them instead of bailing out.
In both cases, asynccheck nodes should no longer appear inside a vectorized
loop.
Closes: #11125
> Disable AutoSIMD of loops with asyncchecks

- debugtools/DDR_VM/src/com/ibm/j9ddr/StructureReader.java
> Enable use of a Java 7 bootjdk

- debugtools/DDR_VM/src/com/ibm/j9ddr/StructureReader.java
> Remove unwanted import

- jcl/src/java.base/share/classes/java/lang/Thread.java
To ensure proper `Thread`/`ClassLoader` initialization before binding the native method `java.lang.Thread.setNameImpl(threadRef, threadName)`, move it after `initialize(booting, threadGroup, null, null, true)` within the `Thread` constructor.
fixes #11181 
> Move native Thread.setNameImpl method after Thread initialize()

- runtime/jcl/CMakeLists.txt
- runtime/jcl/common/vectornatives.cpp
- runtime/jcl/exports.cmake
- runtime/jcl/uma/se16_exports.xml
- runtime/jcl/uma/se16_objects.xml
- runtime/oti/jclprots.h
Add native stubs for vector API support
> Add native stubs for vector API support

- runtime/vm/ObjectMonitor.cpp
> Fix undeclared variable at objectMonitorEnterNonBlocking

- runtime/codert_vm/cnathelp.cpp
Enable LoadFlattenableArray for non-VT arrays
The JIT array load helpers are used for object and VT arrays, so the NPE
check needs to be performed only in the case of VTs.
Also, this PR fixes the arg ordering for
jitStoreFlattenableArrayElement.
> Enable LoadFlattenableArray for non-VT arrays

- runtime/compiler/z/codegen/J9TreeEvaluator.cpp
Disable the evaluator to unblock the openjdk test failures.
Closes https://github.com/eclipse/openj9/issues/11333
> Disable multianewarray evaluator on Z

- jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
Related: https://github.com/eclipse/openj9/pull/11322
> Remove duplicate of defineHiddenClassWithClassData

- buildenv/jenkins/variables/admin_list.yml
> Add Ben Thomas (aviansie-ben) to PR launch list

- test/functional/VM_Test/build.xml
related: https://github.com/AdoptOpenJDK/TKG/issues/63
[ci skip]
> get third party dependency in VM_Test

- runtime/compiler/control/rossa.cpp
- runtime/compiler/env/ProcessorDetection.cpp
- runtime/oti/j9nonbuilder.h
- runtime/rasdump/javadump.cpp
depends on: https://github.com/eclipse/omr/pull/5707
Issue: #11184
> Add cpu feature info to javacore

- runtime/compiler/control/rossa.cpp
- runtime/compiler/env/ProcessorDetection.cpp
- runtime/oti/j9nonbuilder.h
- runtime/rasdump/javadump.cpp
Reverts eclipse/openj9#11385
Adds back #11215 now that OMR acceptance has promoted.
> Revert "Revert "Add cpu feature info to javacore""

- runtime/compiler/control/rossa.cpp
- runtime/compiler/env/ProcessorDetection.cpp
- runtime/oti/j9nonbuilder.h
- runtime/rasdump/javadump.cpp
Issue: #11184
Port https://github.com/eclipse/openj9/pull/11215 for the 0.24 release.
> (0.24.0) Add cpu feature info to javacore

- buildenv/jenkins/jobs/infrastructure/Cleanup-Nodes.groovy
> Add ability to delete tso datasets for zOS guests

- runtime/compiler/control/CompilationRuntime.hpp
- runtime/compiler/control/JITServerCompilationThread.cpp
- runtime/compiler/runtime/JITClientSession.cpp
- runtime/compiler/runtime/JITClientSession.hpp
This is a port of PR #11416 from master branch into the v0.20.0-release branch 
Signed-off-by: Marius Pirvu mpirvu@ca.ibm.com
> (0.24.0) Fix bug related to sequencing scheme in JITServer

- test/functional/Java8andUp/playlist.xml
- add --illegal-access=permit in JCL_Test and JCL_Test_none_SCC
- Issue: https://github.com/eclipse/openj9/issues/11419
[skip ci]
> Add --illegal-access=permit in JCL tests

- jcl/src/java.base/share/classes/com/ibm/oti/util/Util.java
Fixes https://github.com/eclipse/openj9/issues/11449
> Avoid NPE with -verbose:stacktrace when source location is null

- test/functional/cmdLineTests/loadLibraryTest/playlist.xml
[ci skip]
Close #11470 
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>
> Disable cmdLineTester_loadLibraryTests from hotspot impl

- runtime/compiler/net/ClientStream.cpp
gethostbyname() used in openConnection() (which is used in JITServer code) is
known to be non MT safe. We have observed rare crashes in the client JVM,
which are likely due to usage of gethostbyname() as explained in #11415
This commit replaces the usage of gethostbyname() with gettaddrinfo() which is
reentrant and therefore more amenable to multithreaded code.
Fixes: #11415
> Replace deprecated gethostbyname() with getaddrinfo() to avoid crash

- runtime/gc_vlhgc/IncrementalGenerationalGC.cpp
Fix how Eden size is reported at `gc-start` and `gc-end` in balanced GC policy. Make it consistent with reporting
MM_HeapRegionManagerVLHGC::getHeapMemorySnapshot()
Reorder how/when taxation threshold and regions' age are updated. Instead of updating region's age at the very end of a GC increment, we now update it at the end of GC increment but before we report `gc-end`. With the update of `exportStats` on how Eden is reported, we now have total Eden size being reported as `getCurrentEdenSizeInBytes()` always while free eden size in bytes contains the correct value, where at `gc-start` `_edenFreeHeapSize` is close to zero and at `gc-end` it's equal to Eden heap size.
> Update how Eden size is reported at gc-start and gc-end

- runtime/compiler/env/j9methodServer.cpp
- runtime/compiler/env/j9methodServer.hpp
> Fix build break due to definingClassFromCPFieldRef change

- runtime/compiler/z/codegen/J9TreeEvaluator.cpp
> Use TR::MemoryReference::create API where applicable

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
This commit implements implicit NULLCHK evaluator for aarch64.
Depends on:
- https://github.com/eclipse/openj9/pull/11345
> AArch64: Implement implicit NULLCHK

- runtime/compiler/runtime/J9Profiler.cpp
- runtime/compiler/runtime/J9Profiler.hpp
Added code for serialization of TR_BlockFrequencyInfo.
Signed-off-by: Ashutosh Mehra <asmehra@redhat.com>
> Support for serialization of TR_BlockFrequencyInfo

- test/functional/TestUtilities/src/org/openj9/test/attachAPI/TargetManager.java
Accessing internals requires special permission in JDK16+ due to
JEP 396.
Tested for jdk17: https://ci.eclipse.org/openj9/view/Test/job/Grinder/1292
Tested for jdk11: https://ci.eclipse.org/openj9/view/Test/job/Grinder/1293
Tested for jdk8: https://ci.eclipse.org/openj9/view/Test/job/Grinder/1296
> Use JDK11+ API to get process pid to fix AttachAPISanity for JDK16+

- runtime/bcutil/ComparingCursor.cpp
Fix utf8 range check in SCC
The existing check dereferences the utf8 before ensuring that the header
is in the SCC. This causes a segfault when the header is not in the SCC.
> Fix utf8 range check in SCC

- buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
- buildenv/jenkins/variables/defaults.yml
> Add jdk16 to the build pipelines

- runtime/compiler/ilgen/Walker.cpp
For now, the implementation generates VM helpers calls for the
aaload and aastore operations.
Signed-off-by: Leonardo Banderali <leonardo2718@protonmail.com>
> Implement JIT support for flattened value type arrays

- runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
ARM64HelperCallSnippets add a GCMap to the instruction next to the `bl` instruction to the helper,
and if an ARM64HelperCallSnippet is emitted at the end of the method,
the address which a GCMap is added is beyond the range of the method.
To avoid that, we add a dummy ConstantDataSnippet.
Data snippets are emitted after normal snippets, so we can make sure that
a snippet emitted at the end of the method is not an ARM64HelperCallSnippet.
Depends on https://github.com/eclipse/omr/pull/5726
> AArch64: Add dummy constant data snippet

- doc/release-notes/0.24/0.24.md
- Updates and changes for the 0.24 release
[ci skip]
> Release notes for OpenJ9 0.24.0

- doc/compiler/jitserver/Build.md
- doc/compiler/jitserver/CHTable.md
- doc/compiler/jitserver/Caching.md
- doc/compiler/jitserver/Problem.md
- doc/compiler/jitserver/README.md
- doc/compiler/jitserver/ResolvedMethod.md
- doc/compiler/jitserver/Sockets.md
- doc/compiler/jitserver/Testing.md
- doc/compiler/jitserver/Usage.md
- Remove/fix outdated information: option names, protobuf mentions
- Update usage and testing guides
- Add more detailed documentation for resolved methods
- Add tips for debugging JITServer
> Update JITServer documentation

- runtime/rasdump/javadump.cpp
> Fix minor formatting issues

- buildenv/jenkins/variables/defaults.yml
> Update Windows to openssh 1.1.1i

- buildenv/jenkins/variables/defaults.yml
* [skip ci]
* eclipse/openj9#11407
> (0.24.0) Update Windows to openssh 1.1.1i

- test/functional/cmdLineTests/classesdbgddrext/playlist.xml
-fixes: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2144
[ci skip]
> openj9/ibm for cmdLineTester_classesdbgddrext_aix

- test/functional/cmdLineTests/sigabrtHandlingTest/sigabrtHandlingTest.xml
- test/functional/cmdline_options_tester/src/Tokenizer.java
Add single quote detection to Tokenizer.java per described issue #11351.
- Added single quote detection
- Adjusted comments so they make sense
- Changed command strings in sigabrtHandlingTest.xml to reflect this change
Closes:  #11351 
Signed-off-by: J. Cody Arnholt <j.cody.tbone@gmail.com>
> Add single quote detection

- doc/release-notes/0.24/0.24.md
- add a table entry for PR 11184
> Add entry for Java dump file containing processor features

- doc/compiler/jitserver/Build.md
- doc/compiler/jitserver/CHTable.md
- doc/compiler/jitserver/Caching.md
- doc/compiler/jitserver/Problem.md
- doc/compiler/jitserver/README.md
- doc/compiler/jitserver/ResolvedMethod.md
- doc/compiler/jitserver/Sockets.md
- doc/compiler/jitserver/Testing.md
- doc/compiler/jitserver/Usage.md
This is a 0.24 port of #11529.
> (0.24) Update JITServer documentation

- sourcetools/buildj9tools.mk
This is a much simpler solution as compared with #11543.
> Add new make target for building java preprocessor

- runtime/compiler/aarch64/codegen/J9AheadOfTimeCompile.cpp
- runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
- runtime/compiler/control/CompilationThread.cpp
- runtime/compiler/control/J9Recompilation.cpp
- runtime/compiler/control/J9Recompilation.hpp
- runtime/compiler/control/rossa.cpp
- runtime/compiler/control/rossa.h
- runtime/compiler/optimizer/JProfilingBlock.cpp
- runtime/compiler/optimizer/JProfilingRecompLoopTest.cpp
- runtime/compiler/p/codegen/J9AheadOfTimeCompile.cpp
- runtime/compiler/runtime/J9Profiler.cpp
- runtime/compiler/runtime/J9Profiler.hpp
- runtime/compiler/runtime/RelocationRecord.cpp
- runtime/compiler/runtime/RelocationRecord.hpp
- runtime/compiler/x/codegen/J9AheadOfTimeCompile.cpp
- runtime/compiler/z/codegen/J9AheadOfTimeCompile.cpp
Created a new relocation records for block frequency and the flag
for checking if the method is already in recompilation queue.
Signed-off-by: Ashutosh Mehra <asmehra@redhat.com>
> Add new relocation records for block frequency

- runtime/compiler/compile/J9SymbolReferenceTable.cpp
- runtime/compiler/ilgen/Walker.cpp
- runtime/compiler/optimizer/ProfileGenerator.cpp
- runtime/compiler/z/codegen/J9CodeGenerator.cpp
> Remove use of get and setAccessStaticsIndirectly APIs

- runtime/compiler/il/J9SymbolReference.cpp
> Return type signature for NonSpecificConstObject

- doc/build-instructions/Build_Instructions_V11.md
- doc/build-instructions/Build_Instructions_V15.md
- doc/build-instructions/Build_Instructions_V8.md
> Update JDK8 build instructions using VS2013 for Windows

- runtime/codert_vm/arm64nathelp.m4
- runtime/codert_vm/armnathelp.m4
- runtime/codert_vm/cnathelp.cpp
- runtime/codert_vm/pnathelp.m4
- runtime/codert_vm/xnathelp.m4
- runtime/codert_vm/znathelp.m4
- runtime/compiler/runtime/asmprotos.h
- runtime/jilgen/jilconsts.c
- runtime/oti/j9consts.h
- runtime/oti/j9nonbuilder.h
> Add stub and constants for jitResolveFlattenableField

- runtime/compiler/env/J9ObjectModel.cpp
- runtime/compiler/env/J9ObjectModel.hpp
- runtime/compiler/env/VMJ9.cpp
- runtime/compiler/env/VMJ9.h
- runtime/compiler/x/codegen/J9TreeEvaluator.cpp
- runtime/gc_base/IndexableObjectAllocationModel.cpp
- runtime/gc_glue_java/ArrayletObjectModel.cpp
- runtime/gc_glue_java/ArrayletObjectModel.hpp
- runtime/gc_include/ObjectAllocationAPI.hpp
- runtime/oti/j9consts.h
- runtime/oti/j9nonbuilder.h
Reverts eclipse/openj9#11507
due to https://github.com/eclipse/openj9/issues/11616
> Revert "Add extra U_64 data field to Indexable Object Headers"

- buildenv/jenkins/ARTIFACTORY.md
> Update UNB curl redirection script to be more detailed

- debugtools/DDR_VM/src/com/ibm/j9ddr/VMDataFactory.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/DataType.java
* 'BLOb' -> 'BLOB'
* `j9RASPoitner` -> `j9RASPointer`
* add missing `@Overrides` annotations
* minimize scope of `@SuppressWarnings` annotations
* use `StandardCharsets`
> Fix typos, formatting

- runtime/gc_base/StringTable.cpp
- runtime/oti/VMHelpers.hpp
Fixes https://github.com/eclipse/openj9/issues/11650
> j9gc_createJavaLangString() check for ASCII properly in Unicode

- .copyrightignore
- buildenv/jenkins/ARTIFACTORY.md
- buildenv/jenkins/common/variables-functions.groovy
- buildenv/jenkins/jobs/infrastructure/Cleanup-Nodes.groovy
- buildenv/jenkins/jobs/infrastructure/Update-Reference-Repos.groovy
- buildenv/jenkins/jobs/infrastructure/copyrightCheck.groovy
- buildenv/jenkins/jobs/infrastructure/wrapper_template.groovy
- buildenv/jenkins/jobs/infrastructure/wrapper_variables.yml
- buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
- slave -> node
- whitelist -> allowlist
- blacklist -> blocklist
- Jenkins master -> Jenkins Manager node
> Inclusive terms for infra scripts

- buildenv/jenkins/jobs/infrastructure/Cleanup-Nodes.groovy
* [skip ci]
* sh-np-* for zOS, xlc* for AIX
> Add file types to clean up job

- doc/compiler/aot/InlinedMethods.md
> Fix typo in doc/compiler/aot/InlinedMethods.md

- runtime/compiler/codegen/LinkageConventions.enum
- runtime/compiler/z/codegen/J9Linkage.hpp
- runtime/compiler/z/codegen/Linkage.hpp
- runtime/compiler/z/codegen/S390CHelperLinkage.cpp
- runtime/compiler/z/codegen/S390CHelperLinkage.hpp
- runtime/compiler/z/codegen/S390PrivateLinkage.cpp
- runtime/compiler/z/codegen/S390PrivateLinkage.hpp
This PR combines the two enums as they serve the same purpose. See https://github.com/eclipse/omr/pull/5732 for related OMR PR.
> Fold TR_ S390LinkageConventions into TR_LinkageConventions

- runtime/ddr/overrides-vm
> Add DDR type override

- runtime/vm/CMakeLists.txt
> Remove -g flag when building the interpreter on aix

- jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
Related: https://github.com/eclipse/openj9/issues/11135
> Implement MethodHandles.dropReturn for JDK16

- test/functional/CacheManagement/build.xml
> Correct formatting of test build.xml for zOS

- runtime/gc_base/StringTable.cpp
Record the location that needs to be fixed rather than searching for it
after the fact.
[ci skip]
> Optimize anon class name fixup

- runtime/exelib/common/memcheck.c
Fixes https://github.com/eclipse/openj9/issues/11740
> Remove duplicate line in memcheck.c

- runtime/shared_common/CacheMap.cpp
> Fix incorrect if condition in CacheMap.cpp

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
- runtime/compiler/aarch64/codegen/J9TreeEvaluator.hpp
- runtime/compiler/runtime/Runtime.cpp
This commit implements monitor enter/exit VM helper call for value types
for AArch64.
Closes: #10432
> AArch64: Implement monitor enter/exit VM helper call for value types

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Implement inlined version of write barrier evaluators.
This commit implements code for generational GC policies only.
For `gc_modron_wrtbar_cardmark` or `gc_modron_wrtbar_cardmark_incremental`,
it simply calls write barrier helper.
Also, `ArrayStoreCHKEvaluator` is not yet changed to use this inlined version.
> AArch64: Implement inlined version of awrtbar/awrtbariEvaluator

- test/functional/JLM_Tests/playlist.xml
- test/functional/Java11andUp/playlist.xml
- test/functional/Java8andUp/playlist.xml
- test/functional/NativeTest/playlist.xml
- test/functional/VM_Test/playlist.xml
- test/functional/Valhalla/playlist.xml
- test/functional/cmdLineTests/callsitedbgddrext/playlist.xml
- test/functional/cmdLineTests/cmdLineTest_J9tests/playlist.xml
- test/functional/cmdLineTests/dumpromtests/playlist.xml
- test/functional/cmdLineTests/forceLazySymbolResolution/playlist.xml
- test/functional/cmdLineTests/jep178staticLinkingTest/playlist.xml
- test/functional/cmdLineTests/libpathTest/playlist.xml
- test/functional/cmdLineTests/pltest/playlist.xml
- test/functional/cmdLineTests/shrcdbgddrext/playlist.xml
> Use new disabled feature to exclude tests

- buildenv/docker/mkdocker.sh
* update list of boot JDKs (15 replaces 14)
* update list of remotes in git cache (16 replaces 15)
> Update docker script

- jcl/jpp_configuration.xml
- jcl/src/java.base/share/classes/java/lang/Thread.java
- jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/BufferPoolMXBeanImpl.java
- jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/plugins/impl/ClassScanner.java
* remove `JAVA15` preprocessor configuration
* remove Java code that applies only to Java 12, 13 or 14.
> Remove code related to unsupported Java versions

- jcl/src/java.base/share/classes/com/ibm/oti/util/Util.java
> Remove unused import in Java 8 from Util.java

- runtime/ddr/algorithm_versions.c
> Fix algorithm version constant MIXED_REFERENCE_MODE for DDR

- test/functional/cmdLineTests/CDSAdaptorTest/playlist.xml
- test/functional/cmdLineTests/J9security/playlist.xml
- test/functional/cmdLineTests/SystemPropertiesTest/playlist.xml
- test/functional/cmdLineTests/classLoaderTest/playlist.xml
- test/functional/cmdLineTests/gcRegressionTests/playlist.xml
- test/functional/cmdLineTests/gcsuballoctests/playlist.xml
- test/functional/cmdLineTests/gptest/playlist.xml
- test/functional/cmdLineTests/ignoreUnrecognizedVMOptions/playlist.xml
- test/functional/cmdLineTests/jep178staticLinkingTest/playlist.xml
- test/functional/cmdLineTests/jvmtitests/playlist.xml
- test/functional/cmdLineTests/openssl/playlist.xml
- test/functional/cmdLineTests/pltest/playlist.xml
- test/functional/cmdLineTests/sigabrtHandlingTest/playlist.xml
- test/functional/cmdLineTests/stackSizeInfoTest/playlist.xml
- test/functional/cmdLineTests/xlpCMLTests/playlist.xml
> Remove -verbose flag in playlist.xml

- test/functional/RasapiTest/playlist.xml
> exclude testRASAPI on JDK 16 and 17

- runtime/compiler/codegen/J9CodeGenerator.cpp
Closes https://github.com/eclipse/openj9/issues/11814
> Update incorrect variable in assert

- buildenv/jenkins/jobs/infrastructure/artifactoryCheck.groovy
> Initial commit for artifactory storage monitoring

- jcl/src/java.base/share/classes/java/lang/Class.java
- runtime/jcl/common/reflecthelp.c
- test/functional/Java16andUp/build.xml
- test/functional/Java16andUp/playlist.xml
- test/functional/Java16andUp/src/org/openj9/test/java/lang/Test_Class.java
- test/functional/Java16andUp/src/org/openj9/test/utilities/CustomClassLoader.java
- test/functional/Java16andUp/src/org/openj9/test/utilities/SealedClassGenerator.java
- test/functional/Java16andUp/testng.xml
As per https://github.com/eclipse/openj9/issues/10977, method name is changing and return type is changing from `ClassDesc[]` to `Class[]`.
Still need to check if there are any external tests that reference the old signature and if it is safe to remove it, and check behaviour against newest RI.
Fixes https://github.com/eclipse/openj9/issues/10977
fyi: @tajila
> Change Class#permittedSubclasses() to getPermittedSubclasses() and updated tests

- runtime/compiler/control/CompilationThread.cpp
In the catch block of `TR::CompilationInfoPerThreadBase::compile`
we were accessing the compilation object and calling its destructor.
However, by that point the heap memory region is out of scope and thus
the pointer to the compilation object is invalid.
This bug can be triggered on JITServer, if adding hints at the
end of the compilation results in `StreamFailure` exception.
To handle it, this commit surrounds code that adds hints with
try/catch block and properly destroys the compilation object at that
point.
> Fix incorrect access of Compilation object

- test/functional/Java16andUp/build.xml
Fixes https://github.com/eclipse/openj9/issues/11856
fyi @pshipton
> Fix case sensitive file path in Java16AndUp tests

- runtime/cmake/options.cmake
- runtime/cmake/platform/toolcfg/gnu.cmake
Fixes https://github.com/eclipse/openj9/issues/7995
> Enable -rdynamic on linux builds

- runtime/compiler/control/CompilationThread.cpp
As described in #11831, we do not want to hold the compilation
queue monitor while sending the last message with a compiled method
back to the client. We do not actually need the monitor on the server in
`postCompilationTasks` so the acquisition is delayed until
the end of that method.
> Do not hold compilation monitor in postCompilationTasks on the server

- doc/build-instructions/Build_Instructions_V11.md
- doc/build-instructions/Build_Instructions_V15.md
- doc/build-instructions/Build_Instructions_V8.md
Signed-off-by: Harpreet Kaur <hkaur3@unb.ca>
> Update build instructions for Windows [skip ci]

- buildenv/jenkins/variables/defaults.yml
> Increase content retention limit for UNB artifactory

- runtime/compiler/env/J9SharedCache.cpp
- runtime/compiler/env/j9method.cpp
Adds definition of snprintf for the uses added in https://github.com/eclipse/openj9/pull/11871
> Add definition for snprintf for MSC_VER < 1900

- runtime/util/hshelp.c
Fixup varHandleMethodTypes in HCR
> Fixup varHandleMethodTypes in HCR

- sourcetools/CMakeLists.txt
- sourcetools/j9constantpool/CMakeLists.txt
> CMake:  Update java handling for windows jdk16+

- .github/workflows/autoTestPR.yml
- .github/workflows/rmAutoTestPRBranch.yml
- autoTestPR for auto exclusion
- rmAutoTestPRBranch for deleting branch after PR is closed
[ci skip]
> Add workflows for auto test exclusion

- buildenv/jenkins/common/pipeline-functions.groovy
> Increase the number for systemtest parallel machines to 3

- jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
Line 431, had leading spaces instead of tabs like the rest of the file.
> Fix indentation, remove trailing whitespace

- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/AlgorithmVersion.java
* move test into `init()` instead of at call sites
* ensure `vmMajorVersion` and `vmMinorVersion` are always initialized
* fix typo in 'ALgorithm'
* make field `algVersion` final
* refactor casts to `int`
* merge `catch` blocks
> Tidy up AlgorithmVersion

- buildenv/jenkins/variables/defaults.yml
Issue https://github.com/eclipse/openj9/issues/11980
> Update to openssl 1.1.1j for all platforms but Windows

- runtime/compiler/compile/J9SymbolReferenceTable.cpp
Current code always sets the symbol flag to ConstString when the symbol
is not created the first time. Fix it.
> Set patched string cp entry symbol flag correctly

- runtime/gc_vlhgc/CopyForwardScheme.cpp
Copyforward/markCompact hybrid collector is the default PGC collector.
it can retrieve scan work from both scanCache and Work Packet, But
for the best performance, we only try to retrieve the works from
Work Packet for the abort case or the live objects in non evacuation
regions. for extremely case, the scan work might be retrieved from
work packet during copyforward to markcompact transition, so we should
handle this case as well.
> Handle potential exception case during copyforward completeScan

- runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
Fixes memory leak in MHN.resolve if the method lookup failed with exception.
Fixes #11921
> Fix memory leak during MHN.resolve

- runtime/gc_glue_java/MarkingDelegate.cpp
Change added to o reduce code redundancy and simplify code.
Currently disables ITable optimization which only looks at ITable
values for boolean arrays since all arrays share the same ITable.
Signed-off-by: Oussama Saoudi <oussama.saoudi@ibm.com>
> Changed MarkingDelegate scanClass to reuse ClassIteratorClassSlots

- runtime/compiler/control/CompilationThread.cpp
- runtime/compiler/control/JitDump.cpp
- Rename a few functions in JitDump.cpp to more meaningful names
- Standardize flags passed to `j9sig_protect`
- Fix types used for OMR APIs
- Remove unneeded ifdefs
- Only `sig_protect` methods that can crash
- Ensure the closing XML tag is always printed
- Properly print the symbol reference table
- Add comments to tricky places in the code
Closes: #9227
> Avoid recursive crashes when dumping current IL during jitdump generation

- test/README.md
- test/docs/OpenJ9TestUserGuide.md
> Update test doc for new exclusion feature

- buildenv/jenkins/variables/defaults.yml
> Update Windows to openssh 1.1.1j

- test/docs/OpenJ9TestUserGuide.md
> Update test user guide indentation for exclusion section

- runtime/tests/shared/OSCacheTestSysv.cpp
> Set memory to 0 after allocation in OSCacheTestSysv.cpp

- runtime/tests/shared/OSCacheTestSysv.cpp
Reverts eclipse/openj9#12022
See https://github.com/eclipse/openj9/pull/12022#issuecomment-783864363
> Revert "Set memory to 0 after allocation in OSCacheTestSysv.cpp"

- doc/build-instructions/Build_Instructions_V11.md
- doc/build-instructions/Build_Instructions_V16.md
- doc/build-instructions/Build_Instructions_V8.md
> Update build intructions for mixedrefs by default, remove ARM sections 

- buildenv/jenkins/common/pipeline-functions.groovy
- buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
- buildenv/jenkins/variables/defaults.yml
> Add aot builds which set test_flags: 'AOT'

- runtime/compiler/CMakeLists.txt
> CMake: enable jit on zos

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
This commit changes `ArrayStoreCHKEvaluator` to use write barrier evaluator
rather than calling out to VM helper.
> AArch64: Use inlined write barrier evaluator for ArrayStoreCHK

- runtime/compiler/runtime/JITServerStatisticsThread.cpp
Moved the updateCpuUtil function outside the if statment that requires
the staticsFrequency option to be used. This will alow the Jvm Cpu
values to be updated even if the stats thread was not enabled under the condition
of having any verbose option set.
issue: #12031
Signed-off-by: Eman Elsabban <eman.elsaban1@gmail.com>
> Update the values of JVM Cpu in the compilation msgs in server's verbose

- runtime/nls/cfre/cfrerr_es.nls
- runtime/nls/cfre/cfrerr_ja.nls
- runtime/nls/cfre/cfrerr_sl.nls
- runtime/nls/cfre/cfrerr_zh_TW.nls
- runtime/nls/j9cl/j9jcl_sl.nls
- runtime/nls/j9gc/j9modron_sl.nls
- runtime/nls/j9ti/jvmti_sl.nls
- runtime/nls/j9vm/j9vm_sl.nls
- runtime/nls/jitm/j9jit_sl.nls
- runtime/nls/jnck/jnichk_cs.nls
- runtime/nls/jnck/jnichk_ja.nls
- runtime/nls/jnck/jnichk_pl.nls
- runtime/nls/jnck/jnichk_sl.nls
- runtime/nls/shrc/j9shr_cs.nls
- runtime/nls/shrc/j9shr_pt_BR.nls
- runtime/nls/shrc/j9shr_sl.nls
- runtime/nls/verb/verbose_pl.nls
- runtime/nls/vrfy/j9bcv_pt_BR.nls
- runtime/nls/vrfy/j9bcv_sl.nls
- runtime/nls/vrfy/j9bcv_zh_TW.nls
> Modify the translated PII files in nls folder 02252021

- runtime/bcutil/cfreader.c
- runtime/nls/cfre/cfrerr.nls
- runtime/vm/jvminit.c
- test/functional/Valhalla/playlist.xml
- test/functional/cmdLineTests/valuetypeddrtests/flattened32bitRefBackfillTest.xml
- test/functional/cmdLineTests/valuetypeddrtests/flattenedvaluetypeddrtests.xml
- test/functional/cmdLineTests/valuetypeddrtests/playlist.xml
- test/functional/cmdLineTests/valuetypeddrtests/unflattenedvaluetypeddrtests.xml
> Enable -XX:+EnableValhalla by default in Valhalla builds

- doc/release-notes/0.25/0.25.md
- Update notable changes table
[ci skip]
> Add release notes for 0.25.0

- test/functional/DDR_Test/src/j9vm/test/ddrext/Constants.java
- test/functional/DDR_Test/src/j9vm/test/ddrext/junit/TestClassExt.java
This is a cherry-pick of #11952 for the 0.25.0 release branch.
Fixes: #12099.
> Fix test TestClassExt.testFJ9ObjectExt

- runtime/compiler/build/files/target/amd64.mk
* OMRJitCodeRXObjectFormat.cpp
* OMRJitCodeRWXObjectFormat.cpp
> Add ObjectFormat files to the build

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Implement inlined version of write barrier evaluators.
This commit implements code for optavgpause/balanded GC policies.
> AArch64: Implement wrtbar evaluator for optavgpause/balanced GC policies

- buildenv/jenkins/common/build.groovy
* [skip ci]
* cleanWs tends to fail when there are processes or long paths
* #10834
> Modify initial workspace clean on windows compiles

- buildenv/jenkins/variables/defaults.yml
> Remove artifact storage cap on UNB artifactory

- .github/workflows/autoTestPR.yml
> Add test excluded label in auto exclusion

- runtime/vm/createramclass.cpp
> Fix typo in function name

- test/functional/JIT_Test/src/jit/test/jitserver/JITServerTest.java
In each test case of `testJITServer`, client and server
are terminated using `p.destroy()`. However, this call does not
guarantee that the process will exit. This commit increases
time a test will wait for the process to exit, and if it's still
running will terminate it with `p.destroyForcibly()` and fail the
test case.
This commit also enables to run all test cases even if the last
test case failed. Previously, if a test case fails before server is
terminated, then all subsequent cases fail as well, because they
cannot start their own server. Now, we check whether a previous
instance of a process is running, and if it is, we kill it first.
> Improve testJITServer test

- doc/build-instructions/Build_Instructions_V8.md
Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/484
> Update Windows 32-bit build instructions for cmake default

- test/docs/OpenJ9TestUserGuide.md
> Add suggestion to pass Xjit with braces to TKG

- runtime/oti/j9nonbuilder.h
Conveniently document the various bits in the aligned portion of the
class pointer so readers have a concentrated reference to all the
bit flags and their use and meaning.
> Document the J9Object.clazz bit flags

- doc/build-instructions/Build_Instructions_V11.md
This is a continuation of #12236.
> Remove remaining references to Visual Studio 2013

- buildenv/jenkins/variables/defaults.yml
* update boot jdk for jdknext to Java 16
* remove information relating to jdk15
> Update build configurations

- test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeGenerator.java
- test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java
Modified the ValueType Generator so that all tests pass using the
hotspot JVM.
- Move init helper to ref types only
- Classfile version is 56 instead of 55
- Remove monitor enter and monitor exit tests as hotpsot enforces
structured locking. Only montiorEnterAndExit remains.
- Modified wither and getter methods
- Test syncMethod disabled temporarily due to lack of hotspot support
on ValueTypes by appropriate exception handling.
- checkCast on invalid Qtype throws NPE
Modified ValueTypeTests:
- disabled com.ibm.jvm.Dump.SystemDump() due to incompatibility with
hotspot
- changed all instances of generate(Getter | Wither) to
generateGeneric(Getter | Wither)
Disabled following tests due to incompatible code on OpenJ9:
- testDefaultValueWithNonValueType
- testCheckCastValueTypeOnInvalidQtype …
> Modify VTGenerator to work with Hotspot

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
java_nio_Bits_keepAlive and
java_lang_ref_Reference_reachabilityFence have been added
by consulting the semantics on other architectures.
Closes: #7137
Signed-off-by: Siri Sahithi Ponangi <sahithi.ponangi@unb.ca>
> Inlined version of recognized methods

- runtime/compiler/control/J9Options.cpp
When JITServer opens SSL certificate and key files,
it uses `j9jit_fopen_existing`, which automatically opens the file
read and write mode. Since these files are only read, this commit
replaces the call with `j9jit_fopen` to open files with read
permissions only.
Closes: #11702
> Do not require write permissions for SSL certificate and key files

- runtime/codert_vm/pnathelp.m4
- runtime/jilgen/jilconsts.c
- runtime/oti/JITInterface.hpp
- runtime/oti/j9nonbuilder.h
- runtime/oti/phelpers.m4
- runtime/vm/pcinterp.m4
> Revert "Preserve vector registers across helper calls on P"

- runtime/j9vm/CMakeLists.txt
- runtime/j9vm/asgct.cpp
- runtime/j9vm/exports.cmake
- runtime/j9vm/j9vmnatives.xml
- runtime/j9vm/module.xml
- runtime/redirector/forwarders.m4
- runtime/vm/createramclass.cpp
Currently only supported on Linux x86-64.
> Initial implementation of AsyncGetCallTrace

- runtime/compiler/runtime/SignalHandler.c
In the event of a seg fault in the JIT code, the DF flag should be
cleared, otherwise something must be wrong in the JIT code, in which
case we should fail the VM right away to generate a core dump with the
right context for defect investigation.
This commit adds such check which is to be enabled by an environment
variable in testing.
> Check DF flag in X86 signal handler

- test/functional/IllegalAccessError_for_protected_method/build.xml
- test/functional/JIT_Test/build.xml
- test/functional/JLM_Tests/build.xml
- test/functional/Java10andUp/build.xml
- test/functional/Java11andUp/build.xml
- test/functional/Java12andUp/build.xml
- test/functional/Java14andUp/build.xml
- test/functional/Java15andUp/build.xml
- test/functional/Java16andUp/build.xml
- test/functional/Java8andUp/build.xml
- test/functional/Java9andUp/build.xml
- test/functional/JavaAgentTest/build.xml
- test/functional/Jsr292/build.xml
- test/functional/Jsr335/build.xml
- test/functional/Jsr335_interfaceStaticMethod/build.xml
- test/functional/NativeTest/build.xml
- test/functional/OpenJ9_Jsr_292_API/build.xml
- test/functional/Panama/build.xml
- test/functional/SharedCPEntryInvokerTests/build.xml
- test/functional/TestExample/build.xml
- test/functional/UnsafeTest/build.xml
- test/functional/VM_Test/build.xml
- test/functional/Valhalla/build.xml
- test/functional/cmdLineTests/build.xml
> remove unused target dist_functional in build.xml

- buildenv/jenkins/variables/defaults.yml
> Update to openssl 1.1.1k for all platforms but Windows

- doc/release-notes/0.26/0.26.md
One item for GC scan ordering mode
[skip ci]
> Add release notes for 0.26 release

- runtime/compiler/z/codegen/J9TreeEvaluator.cpp
We were seeing a segmentation fault trying to init 2nd dim class. This
was because the memory reference to the class slot was invalid.
The memory reference is calculated using `targetReg` and `temp1Reg`.
`targetReg` seemed to be fine. However, `temp1Reg` carries over some
old garbage. When we write to `temp1Reg` using `SLLK` we only copy
lower 32 bits and leave the upper 32 bits untouched. This garbage in
upper 32 bits of `temp1Reg` is what was messing up our calculate of the
2nd dim class slot.
Changing `SLLk` to `SLLG` and `AFI` to `AGFI` fixes the failure.
fixes https://github.com/eclipse/openj9/issues/11531
> multianewArrayEvaluator segmentation fault fix

- runtime/compiler/z/codegen/J9TreeEvaluator.cpp
We were seeing a segmentation fault trying to init 2nd dim class. This
was because the memory reference to the class slot was invalid.
The memory reference is calculated using `targetReg` and `temp1Reg`.
`targetReg` seemed to be fine. However, `temp1Reg` carries over some
old garbage. When we write to `temp1Reg` using `SLLK` we only copy
lower 32 bits and leave the upper 32 bits untouched. This garbage in
upper 32 bits of `temp1Reg` is what was messing up our calculate of the
2nd dim class slot.
Changing `SLLk` to `SLLG` and `AFI` to `AGFI` fixes the failure.
> (0.26.0) multianewArrayEvaluator segmentation fault fix

- doc/GuideForCommitters.md
> Add committer instructions for performing coordinated merges with OMR

- buildenv/jenkins/variables/defaults.yml
> Update Openssl for Windows to 1.1.1k

- runtime/compiler/ilgen/Walker.cpp
If the transition target is invokehandle/invokedynamic, the arguments to
be stashed are those already pushed onto the stack before generating the 
bytecode, regardless of the number of arguments needed by the generated
call.
The generated call requires one (in resolved case) or two (in unresolved
case) implicit arguments, so we need to substract them to get the actual
number of arguments needed.
The reason why we don't need to stash the implicit arguments is because
when we transition to the VM, VM will push the implicit argument onto
the stack which is part of the behavior of the 
invokehandle/invokedynamic bytecode.
> Stash the right number of arguments for invokehandle/invokedynamic

- runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
In a method prologue, we initialize stack slots according to stack atlas.
If the method has many local variables and internal pointers to be initialized,
offsets to those slots become larger than 4095.
This commit fixes `initializeLocals` to use `addx` instruction for cases
where the offset to first local or internal pointer is larger than 4095.
> AArch64: Fix offset value overflow in prologue

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Initialize lockword of allocated object by JIT if needed.
This is required if BatchClearTLH is not enabled.
> AArch64: Initialize lockword of allocated object by JIT if needed

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
`VMnewEvaluator` generates instructions to clear allocated TLH.
This commit changes the evaluator not to clear it if `tlhHasBeenCleared()`
returns true.
Depends on https://github.com/eclipse/openj9/pull/12333
> AArch64: Omit clearing TLH if tlhHasBeenCleared is true

- runtime/vm/resolvesupport.cpp
For `invokedynamic`, the first thread wins and gets to update the
`result`. The remaining threads use the `result` from the first thread.
In case of an `exception`,
- always set the the `result` to the `exception`; and
- use `CAS` to update the `callSite`.
Co-authored-by: Jack Lu <Jack.S.Lu@ibm.com>
> Fix invokedynamic resolution for OJDK MHs

- runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
> Fix the setCallSiteTarget api to use correct macro

- runtime/compiler/p/runtime/PPCHWProfiler.cpp
- runtime/compiler/p/runtime/PPCHWProfilerAIX.cpp
- runtime/compiler/p/runtime/PPCHWProfilerLinux.cpp
Remove unsed code that has been surrounded by `#if 0`
for a significant period of time.
> Cleanup dummied PPCHWProfiler code

- test/functional/cmdLineTests/jython/build.xml
- test/functional/cmdLineTests/jython/jython.xml
- test/functional/cmdLineTests/jython/playlist.xml
- test/functional/cmdLineTests/jython/src/JythonHello.java
related: https://github.com/eclipse/openj9/issues/12284
related: https://github.com/adoptium/TKG/pull/168
[ci skip]
> Add cmdLine_jython test

- test/functional/JIT_Test/playlist.xml
- test/functional/JIT_Test/src/jit/test/recognizedMethod/TestJavaLangStringLatin1.java
- test/functional/JIT_Test/testng.xml
This method will be JIT regonized via an intrinsic (work yet to come).
In anticipation of such work we add unit tests for this recognized
method for various sizes and inputs that cover most corner cases.
> Add StringLatin1.inflate unit tests

- test/functional/cmdLineTests/jython/build.xml
- test/functional/cmdLineTests/jython/jython.xml
- test/functional/cmdLineTests/jython/playlist.xml
- test/functional/cmdLineTests/jython/src/JythonHello.java
> (0.26.0) add cmdLineTester_jython to openj9

- test/functional/DDR_Test/src/j9vm/test/ddrext/junit/TestFindExt.java
* `testFindpattern()` must use the same pattern for both searches (specify 'u8' for the first consistency with the second)
* correct some comments
Fixes #12076.
> Clean up and fix DDR test TestFindExt

- jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/FindCommand.java
* fix search termination test: don't waste time finding `N+1` occurrences when the user only asked for `N`
* fix formatting
* adjust help
> Clean up the DDR 'find' command

- runtime/compiler/p/codegen/J9TreeEvaluator.cpp
In arrayCopyEvaluator, the P10 version of helper uses VSX registers
that are not marked dead after usage. Which leads to incrementally
higher number of VSX registers being used until a memory corruption
happens. This commit fixes this bug by marking the VSX register as
dead. Also, to avoid high number of live FPR register, this commit
mark the live register as dead in "genWrtbarForArrayCopy" method.
This issue appears when gc uses concurrentScavenger.
Signed-off-by: Mohammad Nazmul Alam <mohammad.nazmul.alam@ibm.com>
> Fix high number of live register in arrayCopyEvaluator

- jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
> Update accessCheckArgRetTypes to always check array component type

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Implement inlined version of ArrayStoreCHKEvaluator.
Depends on https://github.com/eclipse/omr/pull/5903
> AArch64: Implement inlined ArrayStoreCHKEvaluator

- runtime/libffi/z/ffi64.c
The latest specification of the CEL4RO31 control block
consolidates the environment and entry point members into
a single function descriptor member.
> libffi: Update CEL4RO31 control block function descriptor member

- test/functional/JLM_Tests/src/org/openj9/test/management/TestOperatingSystemMXBean.java
Part of tests testOSMXBeanLocal and testOSMXBeanRemote, which run
org.openj9.test.management.TestOperatingSystemMXBean.runTestOSMXBean()
Issue https://github.com/eclipse/openj9/issues/12038
Cherry pick of https://github.com/eclipse/openj9/pull/12420 for the 0.26.0 release.
> (0.26.0) Exclude OperatingSystemMXBean PhysicalMemory test in Docker

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Use `dmb` instructions for flushEvaluator instread of too conservative
`dsb` instructions.
Also, fix parameters for `dmb` instructions to satisfy requirements correctly.
> AArch64: Use best barrier instructions for flushEvaluator

- runtime/vm/ValueTypeHelpers.cpp
> Fix compilation error

- runtime/j9vm/exports.cmake
- runtime/j9vm/j9vmnatives.xml
- runtime/j9vm/javanextvmi.c
- runtime/j9vm/module.xml
- runtime/redirector/forwarders.m4
- runtime/redirector/module.xml
* `void JVM_DumpClassListToFile(JNIEnv *env, jstring str)`
* `void JVM_DumpDynamicArchive(JNIEnv *env, jstring str)`
Fixes: #12456.
> Add required stubs for jdk17

- runtime/j9vm/exports.cmake
- runtime/j9vm/j9vmnatives.xml
- runtime/j9vm/java11vmi.c
- runtime/j9vm/module.xml
- runtime/redirector/forwarders.m4
- runtime/redirector/module.xml
* `JVM_GetRandomSeedForCDSDump`
* `JVM_IsCDSSharingEnabled`
> Remove functions used only by Java 15

- runtime/compiler/runtime/MethodMetaData.c
- runtime/jvmti/jvmtiCapability.c
- runtime/redirector/redirector.c
This PR fixes compiler errors when the compile time flag `DEBUG` is defined.
> Fix compiler errors when DEBUG is defined

- runtime/compiler/CMakeLists.txt
> CMake: Add missing flags for jit on z/OS

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
As in JMM Cookbook, the required barriers are:
- StoreStore barrier before each volatile store
- StoreLoad barrier after each volatile store
- LoadLoad and LoadStore barriers after each volatile load
> AArch64: Issue weaker but sufficient memory barriers for loads/stores

- runtime/compiler/optimizer/HotFieldMarking.cpp
Update JIT hot field tracing for dynamic breadth-first scan ordering. Remove overly verbose and incorrect trace message and modify the helpful trace message to use printf so that an additional trace option is not required to be set in order to trace marking of hot fields. This is also consistent with how hot field tracing was previously done.
> Update JIT Hot Field Tracing For Dynamic Breadth-First Scan Ordering

- runtime/vm/BytecodeInterpreter.hpp
`linkToVirtual` behaviour is corrected for cases where `J9JNIMethodID->vTableIndex`
is 0.
Related: https://github.com/eclipse/openj9/pull/11367
> Update linkToVirtual to correctly handle J9JNIMethodID->vTableIndex

- runtime/compiler/optimizer/StaticFinalFieldFolding.hpp
> Add documentation of StaticFinalFieldFolding

- runtime/compiler/z/codegen/DFPTreeEvaluator.cpp
- runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp
This API is unimplemented and calling it and using the result will
likely produce a crash. This API is used in dead code paths:
1. DFP
2. arraycmpWithPad
3. pdneg
4. vsetlem
under certain circumstances. Please see the self review in the PR which
is associated to this commit for explicit reasons as to why failing the
compilation in each case is safe and warranted.
> Deprecate findOrCreateLiteral codegen API

- jcl/src/java.base/share/classes/com/ibm/oti/util/Util.java
* Avoid NPE if an exception is thrown from a module running the exploded JDK (when `ModuleReferenceImpl.recordedHashes()` returns `null`). Discovered while trying to fix #12524.
* Use `Charset` instead of `String` to capture the default encoding.
* Avoid possible `IndexOutOfBoundsException` in `startsWithDriveLetter()`
* Add missing braces, remove extraneous parentheses.
> Improve com.ibm.oti.util.Util

- runtime/compiler/build/files/target/z.mk
- runtime/compiler/codegen/CodeGenGPU.cpp
- runtime/compiler/infra/J9Cfg.cpp
- runtime/compiler/optimizer/DynamicLiteralPool.cpp
- runtime/compiler/optimizer/EscapeAnalysis.cpp
- runtime/compiler/optimizer/NewInitialization.cpp
- runtime/compiler/optimizer/NewInitialization.hpp
- runtime/compiler/x/codegen/J9TreeEvaluator.cpp
- runtime/compiler/z/codegen/InMemoryLoadStoreMarking.cpp
* Remove merged new allocation code
* Cleanup work for deprecated IL opcodes
> Cleanup work for deprecated IL opcodes

- sourcetools/com.ibm.jpp.preprocessor/com/ibm/jpp/om/JavaPreprocessor.java
There are a few places where the code would be cleaner if the preprocessor supported a sequence of `ELSEIF` branches of an `IF` block. For example:
```
/*[IF JAVA_SPEC_VERSION == 8]*/
// Java 8
/*[ELSEIF JAVA_SPEC_VERSION == 11]*/
// Java 11
/*[ELSEIF JAVA_SPEC_VERSION == 16]*/
// Java 16
/*[ELSE]*/
// JavaNext
/*[ENDIF] JAVA_SPEC_VERSION == 8*/
```
Also improve error checking: disallow multiple `ELSE` clauses.
> Add support for ELSEIF in preprocessor

- runtime/compiler/control/CompilationThread.cpp
Tracing higher optimization level compilations may put us past the
allocation limit and result in an std::bad_alloc exception being thrown.
To maximize our chances of getting a trace log we artificially inflate
the scratch space memory for JitDump compilations.
> Use maximum allowed scratch space memory limit for JitDump compilations

- runtime/compiler/codegen/J9CodeGenerator.cpp
- runtime/compiler/p/codegen/PPCPrivateLinkage.cpp
> Deprecate blockIndex

- runtime/vm/CMakeLists.txt
> CMake: Update compiler flags for interpreter on z/OS.

- runtime/compiler/x/codegen/J9TreeEvaluator.cpp
Update JIT inline array allocation sequence to populate `dataAddr` slot
for contiguous, and 0 size discontiguous arrays.
Part of phase 2 of https://github.com/eclipse/openj9/issues/11438.
> Update JIT inline array allocation sequence on x

- runtime/tests/jvmtitests/agent/CMakeLists.txt
- runtime/tests/jvmtitests/src/CMakeLists.txt
> CMake: Fix jvmtitest exports on z/OS

- buildenv/jenkins/ARTIFACTORY.md
> Add Artifactory info for removing anon-read and adding openj9 account

- runtime/compiler/optimizer/TreeLowering.cpp
- runtime/compiler/optimizer/TreeLowering.hpp
Fix build error on big endian platforms
> Fix build error on big endian platforms

- runtime/compiler/optimizer/EscapeAnalysis.cpp
It appeared there are allocationFence(s) removed by EA by mistake.
It caused sporadic/non-deterministic crashes in running. Added better
tracing too.
Signed-off-by: Julian <zlwang@ca.ibm.com>
> Fix missing allocationFence after EscapeAnalysis

- buildenv/jenkins/jobs/pipelines/Pipeline-Initialize.groovy
> Add Retry with delay to initial clone

- runtime/cmake/caches/zos_390-64.cmake
- runtime/cmake/caches/zos_390-64_cmprssptrs.cmake
> CMake: Add initial zos caches

- test/functional/JLM_Tests/playlist.xml
- test/functional/Java9andUp/playlist.xml
- test/functional/cmdLineTests/jvmtitests/playlist.xml
> fix schema error in playlist.xml

- doc/compiler/aot/README.md
- doc/compiler/aot/RelocationRecords.md
> Add documentation for relocation records

- runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp
- runtime/compiler/aarch64/codegen/J9CodeGenerator.hpp
> AArch64: Enable supportsInliningOfIsInstance flag

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
This commit implements variants of CAS methods of Unsafe.
Depends on https://github.com/eclipse/omr/pull/5998
> AArch64: Complete implementation of Unsafe CAS

- runtime/compiler/optimizer/TreeLowering.cpp
NULL check on LHS and RHS for fast acmp path is only required if they are not non-NULL.
> Add isNonNull check on the fast acmp path in tree lowering

- runtime/compiler/x/codegen/J9TreeEvaluator.cpp
> Fix build break in J9TreeEvaluator.cpp

- doc/release-notes/0.27/0.27.md
The release notes will continue to be updated as necessary.
> Add initial 0.27 release notes

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Enhance ArrayStoreCHKEvaluator using array component class set in node by VP.
> AArch64: Enhance ArrayStoreCHKEvaluator

- test/functional/Jsr335/build.xml
related: https://github.com/eclipse-openj9/openj9/issues/12755
[ci skip]
> compile Jsr335 for ibm/openj9 only

- test/functional/cmdLineTests/J9security/build.xml
related: https://github.com/eclipse-openj9/openj9/issues/12756
[ci skip]
> compile J9security for ibm/openj9 only

- runtime/jit_vm/cthelpers.cpp
- runtime/oti/j9nonbuilder.h
- runtime/oti/j9protos.h
- runtime/oti/util_api.h
- runtime/oti/vm_api.h
- runtime/tests/annotationtests/CMakeLists.txt
- runtime/tests/annotationtests/annhelp_tests.c
- runtime/tests/annotationtests/module.xml
- runtime/util/annhelp.c
- runtime/util/vmutil.tdf
- runtime/vm/intfunc.c
- runtime/vm/resolvefield.cpp
JIT cthelpers to query annotations
Details are in the issues below.
Fixes: #11990
Most of the work was done by @sharon-wang. Creating this PR on her
behalf.
> JIT cthelpers to query annotations

- runtime/tests/port/j9vmemTest.c
- test/functional/VM_Test/playlist.xml
- test/functional/VM_Test/src/j9vm/test/xlpcodecache/XlpCodeCacheOptionsTestRunner.java
> All 64k pagesize tests fix

- buildenv/jenkins/common/build.groovy
- buildenv/jenkins/common/variables-functions.groovy
- buildenv/jenkins/variables/defaults.yml
> Add ability to build within a container

- runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
> Fix Field MemberName init value of vmtarget

- buildenv/jenkins/jobs/infrastructure/artifactory_cleanup.groovy
Just like numeric based cleanup, for time based cleanup
delete the parent folder rather than the individual
artifacts. Previously, this left empty dirs. This also
reduced the number of calls made since we only need
to delete 1 build folder rather than several artifacts
within it.
> Cleanup parent folders instead of individual artifacts

- buildenv/jenkins/variables/defaults.yml
In order to workaround a cleanup issue after
the move to the new Jenkins server. We've
created a new repo to start fresh. The old repo
will remain until all the Artifacts expire.
Existing links will work for the existing repo.
> New Artifactory Repo

- doc/GuideForCommitters.md
> Update OpenJ9 CI links in GuideForCommitters.md

- CONTRIBUTING.md
- buildenv/jenkins/README.md
- test/docs/OpenJ9TestUserGuide.md
> Update OpenJ9 CI links in various docs

- runtime/bcutil/ROMClassBuilder.cpp
Fix windows compilation failure
> Fix windows compilation failure

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Use CASAL instruction for monitor enter when FEAT_LSE is available.
> AArch64: Use CASAL instruction for monitor enter

- test/functional/DDR_Test/playlist.xml
related: https://github.com/eclipse-openj9/openj9/issues/12836
[ci skip]
> Update DDR Extension test to run in REPORTDIR

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Add registers allocated by ScratchRegisterManager to RegisterDependency.
Call `stopUsingRegister` when scratch registers become unnecessary.
> AArch64: Fix usage of ScratchRegisterManger in VMinlineCompareAndSwap

- buildenv/jenkins/variables/defaults.yml
> Update version of docker container for JDK8&11 x86 compiles

- runtime/bcutil/ClassFileWriter.hpp
Adds small fix to #12860
Allocate class name statically if class is InjectedInvoker, don't free
> Reset InjectedInvoker class name during Classfile Recreation

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Use CASAL instruction for Unsafe#compareAndSwap if FEAT_LSE is available.
> AArch64: Use CASAL for Unsafe#compareAndSwap

- debugtools/DDR_VM/src/com/ibm/j9ddr/StructureReader.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/tools/PointerGenerator.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/tools/StructureStubGenerator.java
If a type is no longer present, create a fictitious `StructureDescriptor` for its optional fields.
Code generated by `PointerGenerator` must anticipate `NoClassDefFoundError`.
Also
* don't return null from `StructureDescriptor.getSuperName()`
* remove unused field `StructureDescriptor.pointerName`
* update help messages
Issue: #12874.
> Handle optional fields in obsolete types

- doc/release-notes/0.27/0.27.md
Issue https://github.com/eclipse-openj9/openj9/issues/12797
I'll keep this as draft in case it needs updates, until https://github.com/eclipse-openj9/openj9-docs/issues/795 is merged.
> Update release notes for JAVA_OPTIONS

- runtime/compiler/runtime/JITClientSession.cpp
PR #12458 introduced fast client session destruction: most of the destructor code can be skipped since most data in the client session is allocated with the per-client persistent allocator and is freed in bulk when the per-client allocator is destroyed. Any objects allocated globally (not with the per-client allocator) still need to be freed. This PR fixes missing deallocation of `std::string` objects in the client session (which are allocated using the global `malloc` heap).
This is a temporary fix until we get rid of `malloc` usage in client session data.
> Fix memory leaks when using fast client session destruction

- debugtools/DDR_VM/src/com/ibm/j9ddr/StructureReader.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/tools/PointerGenerator.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/tools/StructureStubGenerator.java
This cherry-picks #12908 for the 0.27.0 release.
> (0.27.0) Handle optional fields in obsolete type

- test/docs/OpenJ9TestUserGuide.md
- test/functional/JLM_Tests/playlist.xml
- test/functional/Java11andUp/playlist.xml
- test/functional/Java8andUp/playlist.xml
- test/functional/NativeTest/playlist.xml
- test/functional/RasapiTest/playlist.xml
- test/functional/VM_Test/playlist.xml
- test/functional/cmdLineTests/URLClassLoaderTests/playlist.xml
- test/functional/cmdLineTests/callsitedbgddrext/playlist.xml
- test/functional/cmdLineTests/cmdLineTest_J9tests/playlist.xml
- test/functional/cmdLineTests/dumpromtests/playlist.xml
- test/functional/cmdLineTests/jep178staticLinkingTest/playlist.xml
- test/functional/cmdLineTests/libpathTest/playlist.xml
- test/functional/cmdLineTests/pltest/playlist.xml
- test/functional/cmdLineTests/shrcdbgddrext/playlist.xml
> Update <plat> to <platform> for playlist disabled tag

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Make sure that TLH is properly aligned when `-XXgc:forcedShiftingCompressionAmount=4` is used.
Resolves https://github.com/eclipse-openj9/openj9/issues/12945
> AArch64: Fix alignment in VMnewEvaluator

- runtime/codert_vm/CMakeLists.txt
- runtime/codert_vm/cnathelp.cpp
- runtime/codert_vm/riscvnathelp.m4
- runtime/jilgen/jilconsts.c
- runtime/oti/j9nonbuilder.h
- runtime/oti/riscvhelpers.m4
- runtime/oti/stackwalk.h
This code is taken from AArch64 and updated for RISC-V.
> RISC-V: add skeleton of codert_vm component

- runtime/compiler/control/JITClientCompilationThread.cpp
- runtime/compiler/env/VMJ9.cpp
- runtime/compiler/env/VMJ9.h
- runtime/compiler/env/VMJ9Server.hpp
- runtime/compiler/optimizer/InterpreterEmulator.cpp
- runtime/compiler/optimizer/J9TransformUtil.cpp
- runtime/compiler/optimizer/J9TransformUtil.hpp
Reverts eclipse-openj9/openj9#12893 due to some failures.
> Revert "Implement  Stable field folding"

- runtime/compiler/x/codegen/J9TreeEvaluator.cpp
When running 64 bit compressed refs, if clazz is an address
above the 2G boundary then we can't use a push 32bit immediate
instruction to pass it on the stack to the jitThrowClassCastException
helper as the address gets sign extended. It needs to be
stored in a temp register and then push the register to the stack.
Port #12852 into 0.27.0 release 
> (0.27.0) Fix incorrect J9Class pointer in ClassCastException

- runtime/compiler/env/j9methodServer.cpp
JITServer's `getClassFromConstantPool` uses client session cache to
associate constant pool indices with J9 classes.
The method wasn't properly checking whether runtime resolution is
enabled.
This resulted in a bug, where we would resolve and cache a class
reference during method handle thunk compilation (which ignore runtime resolution
flag), and return the cached value during a regular compilation, instead
of respecting the runtime resolution flag and returning NULL.
This commit adds proper checks to the method.
> Check runtime resolve flag in TR_ResolvedJ9JITServerMethod::getClassFromConstantPool

- debugtools/DDR_VM/src/com/ibm/j9ddr/AuxFieldInfo29.dat
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/VmCheckCommand.java
- runtime/vmchk/checkclasses.c
Ensure the correct classloader classsegments are searched.
Fixes: #12499
> Update vmcheck to handle lambda classes

- buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
- buildenv/jenkins/variables/defaults.yml
> Add jdk17 to the build pipelines

- test/functional/cmdLineTests/utils/build.xml
- test/functional/cmdLineTests/utils2/build.xml
> exclude hotspot for classTestHelper compilation

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
- runtime/compiler/aarch64/codegen/J9TreeEvaluator.hpp
Issue: #6438
Signed-off-by: Siri Sahithi Ponangi <sahithi.ponangi@unb.ca>
> AArch64: Implement ArrayCHKEvaluator()

- runtime/compiler/aarch64/codegen/CallSnippet.cpp
This commit implements debug print functions for CallSnippets.
Depends on https://github.com/eclipse/omr/pull/6082
Closes https://github.com/eclipse-openj9/openj9/issues/6859
> AArch64: Implement debug print functions for CallSnippets

- runtime/vm/resolvefield.cpp
Potentially fix segmentation error with vmState=0x000565ff due to a NULL hotFieldPoolMutex. I have been unable to reproduce the issue, however, from analyzing the code, this patch addresses the corner case where the `hotFieldPool` for the `classloader` is successfully created while the `hotFieldPoolMutex` for the `classloader` is not successfully created.
Related to: https://github.com/eclipse-openj9/openj9/issues/12782 
> Fix potential Segmentation Error due to a NULL hotFieldPoolMutex

- .github/workflows/runAqaConfig.json
> Add custom_openj9_repo false in runAqaConfig file

- jcl/.classpath
- jcl/jpp_configuration.xml
- jcl/src/openj9.criu/share/classes/module-info.java
- jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUDumpPermission.java
- jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
- runtime/jcl/common/criusupport.c
- runtime/jcl/exports.cmake
- runtime/jcl/uma/criusupport_exports.xml
- runtime/nls/j9cl/j9jcl.nls
- runtime/oti/j9nonbuilder.h
- runtime/oti/jclprots.h
- runtime/oti/vm_api.h
- runtime/vm/CMakeLists.txt
- runtime/vm/criuhelpers.cpp
- runtime/vm/intfunc.c
> Add JVM checkpoint API

- runtime/compiler/control/J9Options.cpp
- runtime/compiler/control/J9Options.hpp
Refactor fePreProcess into smaller methods.
Closes: #12504
> Simplify fePreProcess

- runtime/jcl/CMakeLists.txt
- runtime/jcl/common/java_dyn_methodhandle.c
- runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
- runtime/jcl/exports.cmake
- runtime/jcl/module.xml
- runtime/jcl/uma/java_dyn_methodhandle_exports.xml
- runtime/jcl/uma/java_lang_invoke_MethodHandleNatives_exports.xml
- runtime/jcl/uma/java_lang_invoke_MethodHandleNatives_objects.xml
- runtime/jcl/uma/se829_exports.xml
- runtime/oti/jclprots.h
> Replicate Methodhandle.invoke/invokeExact behavior in OJDK impl

- test/TestConfig/resources/excludes/feature_ojdkmh_exclude.txt
> Exclude failing tests in jsr292Tests_JitCount0

- runtime/util_core/j9argscan.c
Specifying double values on the command line should not be locale
dependent but always use '.'. This affects -XX:MaxRAMPercentage and
-XX:InitialRAMPercentage.
Fixes https://github.com/eclipse-openj9/openj9/issues/13057
> Parse command line double values using `.` instead of locale setting

- runtime/util_core/j9argscan.c
Specifying double values on the command line should not be locale
dependent but always use '.'. This affects -XX:MaxRAMPercentage and
-XX:InitialRAMPercentage.
Issue https://github.com/eclipse-openj9/openj9/issues/13057
Cherry pick https://github.com/eclipse-openj9/openj9/pull/13079#event-4955979270 for the 0.27 release.
> (0.27.0) Parse command line double values using `.` instead of locale setting

- runtime/vm/BytecodeInterpreter.hpp
- test/TestConfig/resources/excludes/feature_ojdkmh_exclude.txt
> Add receiver null check for linkToSpecial case

- test/functional/Java8andUp/playlist.xml
- test/functional/Java8andUp/src_110_up/org/openj9/test/annotation/ContainsRuntimeAnnotationTest.java
- test/functional/Java8andUp/src_80/org/openj9/test/annotation/ContainsRuntimeAnnotationTest.java
- test/functional/Java8andUp/testng.xml
Tests whether a field contains the "Stable" annotation
Related: #12679
> Add tests for jitIsFieldStable

- test/functional/Java8andUp/src_110_up/org/openj9/test/annotation/ContainsRuntimeAnnotationTest.java
> Fix RuntimeAnnotationTests failing to parse version 17

- runtime/util/annhelp.c
Add assertation to detect invalid cpIndexes
> Add assertation to detect invalid cpIndexes

- test/functional/cmdline_options_testresources/src_90/com/ibm/j9/getcallerclass/RefectionMHTests.java
> Update getcallerclass testcase to support OJDK MH

- debugtools/DDR_VM/src/com/ibm/j9ddr/StructureReader.java
* don't map "__" at the beginning of a simple name to "$"
* handle types nested more than one level deep
Fixes #12956.
> DDR: fix decoding of nested type names

- debugtools/DDR_VM/src/com/ibm/j9ddr/StructureReader.java
Use string concatenation instead.
> Remove unnecessary uses of String.format()

- test/functional/cmdLineTests/cmdLineTest_J9tests/j9tests.xml
- test/functional/cmdLineTests/ignoreUnrecognizedVMOptions/ignoreunrecognizedvmoptions.xml
- test/functional/cmdLineTests/ignoreUnrecognizedVMOptions/ignoreunrecognizedxxcolonoptions.xml
- test/functional/cmdLineTests/jimageinterface/jimageinterface.xml
- test/functional/cmdLineTests/shareClassTests/ListAllCachesTests/expireAndListAllCachesTests.xml
- test/functional/cmdLineTests/shareClassTests/ListAllCachesTests/listAllCachesTests.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-1.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-2.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-3.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-4.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-5.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-6.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/SharedClassesModularityTests.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/testSCCMLAotMethodOperation.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/testSCCMLSnapshot.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/testSCCMLSoftmx.xml
- test/functional/cmdLineTests/xlpCMLTests/xlpCMLTests.xml
- test/functional/cmdLineTests/xxargtest/XXArgumentTesting.xml
Recognize new product name `Semeru`
closes https://github.com/eclipse-openj9/openj9/issues/13153
> Recognize new product name Semeru

- test/functional/Java16andUp/src/org/openj9/test/foreignMemoryAccess/TestCloseScope0.java
> Fix CloseScope0Tests hang

- test/README.md
- test/docs/OpenJ9TestUserGuide.md
- test/functional/JLM_Tests/playlist.xml
- test/functional/Java11andUp/playlist.xml
- test/functional/Java8andUp/playlist.xml
- test/functional/Java9andUp/playlist.xml
- test/functional/NativeTest/playlist.xml
- test/functional/RasapiTest/playlist.xml
- test/functional/VM_Test/playlist.xml
- test/functional/Valhalla/playlist.xml
- test/functional/cmdLineTests/URLClassLoaderTests/playlist.xml
- test/functional/cmdLineTests/callsitedbgddrext/playlist.xml
- test/functional/cmdLineTests/cmdLineTest_J9tests/playlist.xml
- test/functional/cmdLineTests/dumpromtests/playlist.xml
- test/functional/cmdLineTests/forceLazySymbolResolution/playlist.xml
- test/functional/cmdLineTests/jep178staticLinkingTest/playlist.xml
- test/functional/cmdLineTests/jython/playlist.xml
- test/functional/cmdLineTests/libpathTest/playlist.xml
- test/functional/cmdLineTests/pltest/playlist.xml
- test/functional/cmdLineTests/shrcdbgddrext/playlist.xml
> Update disable element

- runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
- runtime/compiler/env/j9method.cpp
- runtime/compiler/optimizer/J9ValuePropagation.cpp
Recognize Vector API Intrinsics
- recognize VectorSupport load, store, and binaryOp
- propogate vector class constraint from argument to the return type
> Recognize Vector API Intrinsics

- runtime/compiler/optimizer/InlinerTempForJ9.cpp
While inlining non-static method calls, we build the parameters where
the very first slot of the parameters is the class of which that method
belongs to. We later build ArgInfo from the method symbol of the callee
by iterating through this list of parameters and for any parameter which
is Class, we query VM to get the class pointer from the signature of
the class. This was causing an issue when we were trying to inline a
method that belongs to hidden class as VM would return NULL when queried
to get class from signature.
We do not need to call VM to get the class pointer for the
first parameter slot of the non-static method calls as we have that
information avaible through resolvedMethodSymbol.
> Fix incompatible arguments for inlining method from hidden class

- jcl/src/openj9.dtfj/share/classes/com/ibm/jvm/j9/dump/extract/Main.java
When the `-x` option is used, an extra entry in the zip file called `excluded-files.txt` is created which names the excluded dump file. The contents of that file are encoded as UTF-8.
Fixes: #12344.
> Add jpackcore option to exclude core file

- jcl/src/openj9.dtfj/share/classes/com/ibm/jvm/j9/dump/extract/Main.java
This cherry-picks #13194 for the 0.27.0 release branch.
> (0.27.0) Add jpackcore option to exclude core file

- doc/diagnostics/WritingDdrCode.md
Issue: #12370. Explain how fields and constants that have not always been present are handled.
> Document rules for writing DDR Java code

- runtime/compiler/optimizer/EstimateCodeSize.cpp
- runtime/compiler/optimizer/EstimateCodeSize.hpp
- runtime/compiler/optimizer/InlinerTempForJ9.cpp
> Log the estimate code size error state as a string

- runtime/compiler/runtime/J9Profiler.cpp
- runtime/compiler/runtime/J9Profiler.hpp
> Remove obsolete long parm value profiling code

- test/functional/cmdLineTests/cmdLineTest_J9tests/j9tests.xml
- test/functional/cmdLineTests/ignoreUnrecognizedVMOptions/ignoreunrecognizedvmoptions.xml
- test/functional/cmdLineTests/ignoreUnrecognizedVMOptions/ignoreunrecognizedxxcolonoptions.xml
- test/functional/cmdLineTests/jimageinterface/jimageinterface.xml
- test/functional/cmdLineTests/shareClassTests/ListAllCachesTests/expireAndListAllCachesTests.xml
- test/functional/cmdLineTests/shareClassTests/ListAllCachesTests/listAllCachesTests.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-1.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-2.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-3.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-4.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-5.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-6.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/SharedClassesModularityTests.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/testSCCMLAotMethodOperation.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/testSCCMLSnapshot.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/testSCCMLSoftmx.xml
- test/functional/cmdLineTests/xlpCMLTests/xlpCMLTests.xml
- test/functional/cmdLineTests/xxargtest/XXArgumentTesting.xml
Recognize new product name `Semeru`
Cherry-pick from https://github.com/eclipse-openj9/openj9/pull/13156
and resolved conflict at `openj9/test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-6.xml`
> (v0.27.0-release) Recognize new product name Semeru

- runtime/vm/classsupport.c
Cherry-pick of #13221 for the 0.27.0 release branch.
> Fix memory leak in internalFindClassString

- jcl/src/java.base/share/classes/java/lang/System.java
Add a `WeakHashMap` to hold `setSecurityManager()` caller classes;
Apply the `UnsupportedOperationException` or warning message to incoming `null` `SecurityManager` instance as well.
Related to https://github.com/eclipse-openj9/openj9/issues/12760
Note: The new failure https://github.com/eclipse-openj9/openj9/issues/12760#issuecomment-880158723 was introduced via ibmruntimes/openj9-openjdk-jdk17@e700988.
#13170 was developed & tested based on my local `JDK17` extension copy which happens to be couple of days older than the update in question hence didn't catch new warning messages.
To conclude, #13170 is still valid, this PR matches latest RI behaviours and pass the updated `SecurityManagerWarnings` test.
Launching person test build to verify.
> JDK17+ show setSecurityManager message once for each caller class

- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-4.xml
- test/functional/cmdLineTests/xlogTests/xlog.xml
Cherry-pick from https://github.com/eclipse-openj9/openj9/pull/13224
> (0.27.0) Recognize new product name Semeru

- runtime/jit_vm/cthelpers.cpp
- runtime/oti/j9protos.h
- test/functional/Java8andUp/src_110_up/org/openj9/test/annotation/ContainsRuntimeAnnotationTest.java
> Add jit helper to detect `@DontInline` annotation

- CONTRIBUTING.md
- buildenv/jenkins/jobs/infrastructure/lineEndingsCheck.groovy
Fixes #13246.
This has been tested in #12910, both before and after white-space corrections were made.
> Extend line endings check

- test/functional/Java11andUp/playlist.xml
> Remove duplicated <impls> from JCL_TEST_Java-Lang-Invoke

- runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
...including in particular instances of subclasses. Previously, `setCallSiteTargetImpl()` would recognize an instance as an MCS only if its concrete type was exactly `MutableCallSite`. As a result, if the target of an instance of a subclass of `MutableCallSite` were inlined, and if that call site were later updated with a different target, we would fail to invalidate the runtime assumptions.
> Use jitSetMutableCallSiteTarget for all instances of MutableCallSite

- runtime/vm/BytecodeInterpreter.hpp
We need to handle cases like this:
```
interface Intf { void ig1(); void ig2(); void ig3(); void ig4();
void m1(); }
abstract static class Super implements Intf { public abstract void
m2(); public int f2; }
abstract static class Sub extends Super { }
...
MethodHandle m1 = lookup().findVirtual(Sub.class, "m1",
methodType(void.class));
```
This PR adds a check to linkToVirtual to check if the target method is
an interface method, if so it does a itable lookup.
> Handle find virtual of interface methods

- test/functional/cmdLineTests/gcsuballoctests/gcsuballoctests.xml
- test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-4.xml
- test/functional/cmdLineTests/xxargtest/XXArgumentTesting.xml
> Update tests to check Semeru in java -version output

- buildenv/jenkins/variables/defaults.yml
Version 16
Includes GH and GHE in known_hosts file
> Update to latest centos6 container

- runtime/compiler/p/codegen/J9TreeEvaluator.cpp
When investigating TPCDS query 72, performance improved significantly when using the optthroughput GC policy as opposed to gencon. Upon further examination, it was observed that the space boundaries for the new/tenured spaces in the heap were being loaded from memory twice: once when checking if the object is in the tenured space, and once when checking if it is in the new space. This change is an attempt to save on performance by keeping these values in reserved registers, thus eliminating the need for a second load.
Signed-off-by: Jackie Midroni <jackie.midroni@ibm.com>
> Improve write barrier codegen by eliminating redundant loads

- runtime/compiler/z/codegen/J9TreeEvaluator.cpp
> Revert "Fix off-by-one error in String.indexOf acceleration on z15"

- runtime/oti/VMHelpers.hpp
> Fix LambdaForm spelling errors in comment

- runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
- runtime/compiler/env/j9method.cpp
- runtime/compiler/optimizer/InlinerTempForJ9.cpp
See the commit messages for more detail
> Exempt certain methods from call target trimming

- buildenv/jenkins/variables/defaults.yml
> Support aarch compiles on all versions in a container

- buildenv/jenkins/variables/defaults.yml
Issue: eclipse-openj9/openj9#13373
> Update to openssl 1.1.1l for all platforms but Windows

- runtime/nls/j9cl/j9jcl.nls
New NLS messages introduced by #13276 should have been added at the end; this fixes that.
> Move new CRIU messages to the end

- runtime/gc_check/CheckReporterTTY.cpp
Fix `GCCheck` reporting bug in `ReportObjectHeader` method. When the object to report is a hole, the method may crash. The method was implemented in order to handle this case however there was a bug in the handling of the case as `objectModel.getHeaderSize(objectPtr)` should not be used to get the header size when `objectPtr`  is a hole, and this previously could result in a crash.
Fixes: https://github.com/eclipse-openj9/openj9/issues/13260
> Fix GCCheck Reporting bug in `ReportObjectHeader` Method When Object to Report is a Hole

- runtime/vm/BytecodeInterpreter.hpp
Replaces: #12522
Depends: #13388
> Remove NULL appendix in linkToStaticSpecial call

- runtime/vm/BytecodeInterpreter.hpp
> (0.28.0) Remove NULL appendix in linkToStaticSpecial call

- runtime/vm/createramclass.cpp
A hiddenClass should have the same defining classLoader/runtime package
as the Loopkup class (ie. hostClass). so VM need to use the hostClassLoader
when setting the unnamed module for hiddenClass as VM may uses the
anonymousClassLoader to load hiddenClass and update to hostClassLoader
after class load. This will cause hiddenClass to have different module
than the hostClass.
Port of: #13381
> (0.28.0) Patch HiddenClass's moduleObject initialization

- runtime/bcverify/staticverify.c
- runtime/nls/cfre/cfrerr.nls
Fix jsr inliner for zero indexes
> Fix jsr inliner for zero indexes

- runtime/nls/cfre/cfrerr.nls
See https://github.com/eclipse-openj9/openj9/pull/13412#discussion_r701338517.
> Fix J9NLS_CFR_ERR_BC_JUMP_RECURSIVE keys

- jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
- runtime/criusupport/criusupport.c
- runtime/criusupport/criusupport.h
Add new CRIU API methods
Add capabilities to set tcpEstablished, trackMemory and autoDedup
> Add new CRIU API methods

- runtime/compiler/optimizer/VectorAPIExpansion.cpp
- runtime/compiler/optimizer/VectorAPIExpansion.hpp
- check whether intrinsic can be vectorized or scalarized
- while validating a class make sure all intrinsics can be either vectorized
or scalarized
- vectorize a class if possible
- otherwise, scalarize  a class if possible
> Vectorize Vector API intirinsics if possible

- runtime/compiler/env/SystemSegmentProvider.cpp
- runtime/compiler/env/SystemSegmentProvider.hpp
This is another fix for #13126
These exact commits have already been merged into master in #13456
> (0.28.0) Use MemorySegment intrusive list for SystemSegmentProvider free list

- buildenv/docker/aarch64-linux_CC/Dockerfile
This commit updates the Dockerfile for AArch64 Linux cross build.
> AArch64: Update Dockerfile for cross build

- test/functional/CacheManagement/build.xml
- test/functional/DDR_Test/build.xml
- test/functional/HealthCenter/build.xml
- test/functional/IllegalAccessError_for_protected_method/build.xml
- test/functional/InstrumentationAgent/build.xml
- test/functional/Java10andUp/build.xml
- test/functional/Java11andUp/build.xml
- test/functional/Java12andUp/build.xml
- test/functional/Java14andUp/build.xml
- test/functional/Java15andUp/build.xml
- test/functional/Java16andUp/build.xml
- test/functional/Java8andUp/build.xml
- test/functional/Java9andUp/build.xml
- test/functional/JavaAgentTest/build.xml
- remove unnecessary import from test build.xml
- add dependencies in build.xml
[ci skip]
> Update functional tests dependencies part1

- runtime/compiler/control/J9Options.cpp
> (0.28.0) Disable JITServer Tech Preview message for Power and x86

- runtime/jitserver_launcher/jitserver.c
Do not print the message on x86 and Power architectures.
Closes: #13491
> Remove JITServer tech preview message from the server

- runtime/compiler/control/CompilationThread.cpp
To improve start-up/ramp-up of applications, OpenJ9 allows some compilations
to be downgraded from "warm" (the default optimization level) to "cold"
optimization level. However, current logic prevents downgrading of methods
that are flagged as MethodHandleInvokes because inlining is crucial for
the performance of such methods.
In order to improve start-up time of applications, this commit allows the
downgrading of JSR292 methods under certain conditions:
1. The JVM is in the start-up phase
2. Shared classes are enabled explicitly on the command line
3. AOT is enabled
The reason is that, if the shared classes are explicitly enabled on the
command line and AOT is not disabled, there is a good likelihood that the
user cares about start-up time.
Performance evaluation has shown that start-up …
> Allow downgrading of JSR292 methods

- runtime/bcverify/rtverify.c
Throw NCDE on inaccesble catch classes
> Throw NCDE on inaccesble catch classes

- runtime/bcverify/rtverify.c
Change order of exception verification to match RI
Back port of https://github.com/eclipse-openj9/openj9/pull/13444
> Change order of exception verification to match RI (0.28)

- debugtools/DDR_VM/src/com/ibm/j9ddr/VMDataFactory.java
When locating the blob, try a given address only once.
Fixes: #13191.
> Don't loop forever trying to find DDR blob in z/OS system dumps

- runtime/jitserver_launcher/jitserver.c
> (0.28.0) Remove JITServer tech preview message from the server

- test/functional/JIT_Test/build.xml
- test/functional/JLM_Tests/build.xml
- test/functional/Jsr292/build.xml
- test/functional/Jsr335/build.xml
- test/functional/Jsr335_interfaceStaticMethod/build.xml
- test/functional/NativeTest/build.xml
- test/functional/OpenJ9_Jsr_292_API/build.xml
- test/functional/Panama/build.xml
- test/functional/SharedCPEntryInvokerTests/build.xml
- test/functional/TestExample/build.xml
- test/functional/UnsafeTest/build.xml
- test/functional/VM_Test/build.xml
- test/functional/Valhalla/build.xml
- test/functional/cmdLineTests/build.xml
- remove unnecessary import from test build.xml
- add dependencies in build.xml
[ci skip]
> Update functional tests dependencies part2

- test/functional/cmdLineTests/cmdLineTest_J9tests/j9tests_exclude.xml
Enable -XX:+PortableSharedCache on all platforms except aarch
> Enable -XX:+PortableSharedCache test on all platforms

- runtime/compiler/z/runtime/Recomp.cpp
The file `runtime/compiler/z/runtime/Recomp.cpp` defines a
`DEBUG` macro that guards a number of print statements meant
for debugging. These print statements are never used, while
also having incorrect format specifiers that break JITServer builds.
This commit removes the `DEBUG` macro and all associated print
statements.
> Remove unused print statements on s390

- jcl/src/java.base/share/classes/java/lang/ClassLoader.java
The `bootstrapClassLoader` uses `BootLoader.getNativeLibraries()` for native libraries storage & retrieving.
Related to https://github.com/eclipse-openj9/openj9/pull/12981#issuecomment-908422165
> JDK17+ unify bootstrapClassLoader nativelibs w/ BootLoader

- test/functional/cmdLineTests/buildTools.xml
- test/functional/cmdLineTests/utils/build.xml
> Add testng dependency in cmdLineTests/utils build file

- jcl/src/java.base/share/classes/java/lang/ClassLoader.java
The `bootstrapClassLoader` uses `BootLoader.getNativeLibraries()` for native libraries storage & retrieving.
Cherry-pick from https://github.com/eclipse-openj9/openj9/pull/13554
> (v0.29.0-release) JDK17+ unify bootstrapClassLoader nativelibs w/ BootLoader

- runtime/bcutil/ClassFileOracle.cpp
- runtime/gc_check/CheckEngine.cpp
> Check for Qtype static field

- buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
- buildenv/jenkins/variables/defaults.yml
Enable ValueType testing on all platforms
> Enable ValueType testing on all platforms

- jcl/src/java.base/share/classes/java/lang/ref/Reference.java
- jcl/src/jdk.management/share/classes/com/sun/management/GcInfo.java
- jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/java/JavaClass.java
Also indent consistently and trim trailing whitespace.
> Fix @since tags in javadoc

- runtime/vm/ObjectFieldInfo.cpp
- runtime/vm/resolvefield.cpp
> Fix compilation error on Windows Value Type build

- runtime/vm/createramclass.cpp
Certain failure paths in class loading were not popping the loading
stack, resulting in crashes or ClassCircularityError being thrown
incorrectly.
Fix these paths and add an assertion to ensure the class loading stack
is the same on entry and exit from defineClass.
Fixes: #13605
[ci skip]
> Correctly pop class loading stack in some error paths

- runtime/vm/createramclass.cpp
Certain failure paths in class loading were not popping the loading
stack, resulting in crashes or ClassCircularityError being thrown
incorrectly.
Fix these paths and add an assertion to ensure the class loading stack
is the same on entry and exit from defineClass.
Fixes: #13605
Port of https://github.com/eclipse-openj9/openj9/pull/13624 for the 0.29.0 release.
> (0.29) Correctly pop class loading stack in some error paths

- runtime/compiler/runtime/Runtime.cpp
This commit adds additional arraycopy helper entries.
Signed-off-by: Siri Sahithi Ponangi <sahithi.ponangi@unb.ca>
> AArch64: Adding additional arraycopy helper entries

- buildenv/jenkins/common/variables-functions.groovy
- buildenv/jenkins/variables/defaults.yml
Allows setting different url for each spec/version
Related eclipse-openj9#13585
> Pull bootjdk url to be set in variable file

- jcl/src/java.base/share/classes/java/lang/StringBuffer.java
- jcl/src/java.base/share/classes/java/lang/StringBuilder.java
- jcl/src/java.base/share/classes/java/lang/reflect/Array.java
- runtime/codert_vm/cnathelp.cpp
- runtime/oti/j9nonbuilder.h
- runtime/oti/vm_api.h
- runtime/vm/BytecodeInterpreter.hpp
- runtime/vm/bchelper.c
- runtime/vm/exceptionsupport.c
- runtime/vm/intfunc.c
- runtime/vm/jnicsup.cpp
- runtime/vm/jnicsup.h
- runtime/vm/jnimisc.cpp
- test/functional/Java8andUp/src/org/openj9/test/java/lang/reflect/Test_Array.java
Issue #13280
Signed-off-by: Alexey Anufriev <contact@alexey-anufriev.com>
> Add invalid size to NegativeArraySizeException

- test/functional/JIT_Test/src/jit/test/jitserver/JITServerTest.java
JITServer tests run multiple test cases where servers frequently
start and shut down. If the port is not immediately released
back into the system, or another process grabs it before the next
server can start, all subsequent test cases will fail because server
will not be able to start.
This commit modifies the test to generate a new JITServer port
for each test case, to minimize the chances that the port is not
available.
Closes: #13801
> Modify JITServerTest to use a new port for each subtest

- runtime/compiler/control/CompilationThread.cpp
> Print compilation thread shutdown message

- test/functional/JIT_Test/src/jit/test/jitserver/JITServerTest.java
> (0.29.1) Modify JITServerTest to use a new port for each subtest

- runtime/compiler/net/ClientStream.cpp
> Reduce ClientStream::INCOMPATIBILITY_COUNT_LIMIT to 1

- runtime/compiler/control/CompilationThread.cpp
Currently, compilation-failure lines from the verbose log show
less information than compilation-end lines. In particular, they
are missing information about the j9method pointer and the
compilation thread ID that attempted that compilation. This makes
pairing [compilation-start, compilation-fail] events harder than
it should be, in scripts that attempt to process the verbose logs.
Note that method name is not enough for such pairing, because the
same method may be loaded by different class loaders resulting in
different j9method identifiers.
This commit adds j9method pointer and compThreadID to the
compilation-fail lines in the verbose log. Moreover, to make the
compilation-fail lines more like compilation-end lines, this commit
also adds information about the compilation queue size and …
> Add more info to compilation failure lines in vlog

- doc/release-notes/0.27/0.27.1.md
- doc/release-notes/0.27/0.27.md
To reflect the current address of this repo.
> Update github URLs

- runtime/criusupport/CMakeLists.txt
- runtime/criusupport/criusupport.cpp
- runtime/criusupport/criusupport.hpp
- runtime/criusupport/exports.cmake
Convert criu files to cpp
Also fix some build config issues
> Convert criu files to cpp

- jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
Add missing null check for envFile
Fixes https://github.com/eclipse-openj9/openj9/issues/13829
> Add missing null check for envFile

- runtime/jcl/common/java_lang_ref_Reference.cpp
- runtime/vm/FastJNI_java_lang_ref_Reference.cpp
> Improve implementation of Reference.refersTo()

- jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
> Cleanup of Env file processing

- runtime/shared_common/CacheMap.cpp
- runtime/shared_common/CompositeCache.cpp
It is possible that we will enter write mutex inside
updateRuntimeFullFlags(). If it is called from a reader, this could
result in a deadlock if there is another thread waiting for the reader
to finish and trying to lock the cache. 
1. For readers, move the call of updateRuntimeFullFlags() at the
beginning of enterReaderMutex() before the reader count is incremented. 
2. Add assertions that write mutex are not acquired after read mutex.
Closes #13837
> Do not enter the write mutex after the read mutex

- runtime/compiler/z/codegen/S390PrivateLinkage.cpp
> Remove vestigal setStackSizeCheckNeeded() calls

- runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp
> Ensure log trace message is guarded

- runtime/vm/jnimisc.cpp
> Update comment about signature of NativeLibraries.load()

- runtime/j9vm/exports.cmake
- runtime/j9vm/j9vmnatives.xml
- runtime/j9vm/jvm.c
- runtime/redirector/forwarders.m4
> jdk18: adjust signature of JVM_LoadLibrary()

- test/functional/VM_Test/src/com/ibm/oti/jvmtests/GetNanoTimeAdjustment.java
Reverts eclipse-openj9/openj9#13896
See https://github.com/eclipse-openj9/openj9/pull/13896#issuecomment-965913771
> Revert "Fix jvmnativestest test_EnsureWallClockTime()"

- jcl/src/java.base/share/classes/java/lang/Class.java
Switch to `ReflectionFactory` `copyField`/`copyMethod`/`copyConstructor` from direct reflection calls;
No change to `JDK8` since it has no `ReflectionFactory` support.
fixes https://github.com/eclipse-openj9/openj9/issues/13880
This resolves the `StackOverflowError`, however `jdk.reflect.useDirectMethodHandle` can't be re-enabled yet, `useDirectMethodHandle` changes the stacktrace frames which caused a NPE test failure
https://github.com/eclipse-openj9/openj9/blob/4911a34ab7ad1428a8aa78e32699d56074183b6f/test/functional/Java14andUp/src/org/openj9/test/jep358/NPEMessageTests.java#L1022-L1023
The expected NPE message is `null` but got 
```
java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.linkToSpecial(java.lang.Object, java.lang.invoke.MemberName)" because …
```
> Use ReflectionFactory helpers to adopt JEP 416 MH changes

- buildenv/jenkins/variables/defaults.yml
> Update BootJDK 17 to 0.29.1 M1

- runtime/vm/swalk.c
Before computing the maximum number of frames that might exist, verify that
the SP is between the start and end of the stack.
Related: #13910
> Add assertions to stack walker caching

- runtime/compiler/arm/codegen/J9AheadOfTimeCompile.cpp
- runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
- runtime/compiler/compile/AOTClassInfo.hpp
- runtime/compiler/compile/J9Compilation.cpp
- runtime/compiler/compile/J9Compilation.hpp
- runtime/compiler/control/CompilationThread.cpp
- runtime/compiler/control/CompilationThread.hpp
- runtime/compiler/control/J9Options.cpp
- runtime/compiler/control/JITClientCompilationThread.cpp
- runtime/compiler/control/JITServerCompilationThread.cpp
- runtime/compiler/control/JITServerHelpers.cpp
- runtime/compiler/control/JITServerHelpers.hpp
- runtime/compiler/control/rossa.cpp
- runtime/compiler/env/J9PersistentInfo.hpp
- runtime/compiler/env/J9SharedCache.cpp
- runtime/compiler/env/J9SharedCache.hpp
- runtime/compiler/env/SharedCache.hpp
- runtime/compiler/env/VMJ9.cpp
- runtime/compiler/env/j9methodServer.cpp
- runtime/compiler/net/CommunicationStream.hpp
- runtime/compiler/net/MessageTypes.hpp
- runtime/compiler/p/codegen/J9AheadOfTimeCompile.cpp
- runtime/compiler/runtime/JITClientSession.cpp
- runtime/compiler/runtime/JITClientSession.hpp
- runtime/compiler/runtime/RelocationRuntime.cpp
- runtime/compiler/runtime/RelocationRuntime.hpp
- runtime/compiler/runtime/SymbolValidationManager.cpp
- runtime/compiler/runtime/SymbolValidationManager.hpp
Reverts eclipse-openj9/openj9#13907
See https://github.com/eclipse-openj9/openj9/pull/13907#issuecomment-973027309
> Revert "Infrastructure for creating JITServer AOT cache records during compilation"

- runtime/compiler/x/codegen/J9CodeGenerator.cpp
- runtime/compiler/x/codegen/J9CodeGenerator.hpp
- runtime/compiler/x/codegen/J9TreeEvaluator.cpp
- runtime/compiler/x/codegen/J9TreeEvaluator.hpp
Implement evaluator for inlining of StringLatin1.inflate
> Implement evaluator for inlining of StringLatin1.inflate

- runtime/gc_glue_java/ConcurrentMarkingDelegate.cpp
- runtime/gc_glue_java/ConcurrentMarkingDelegate.hpp
- runtime/gc_glue_java/ConfigurationDelegate.hpp
- runtime/gc_glue_java/MarkingDelegate.cpp
- runtime/gc_glue_java/MarkingDelegate.hpp
- runtime/gc_modron_standard/StandardAccessBarrier.cpp
- runtime/gc_modron_standard/StandardAccessBarrier.hpp
- runtime/gc_realtime/RealtimeAccessBarrier.hpp
These changes are to coordinate with upstream OMR SATB changes, which are to follow.
Depends on: https://github.com/eclipse/omr/pull/6223
> Coordinated SATB Changes 

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
- runtime/compiler/arm/codegen/J9ARMEvaluator.cpp
- runtime/compiler/codegen/J9TreeEvaluator.cpp
- runtime/compiler/codegen/J9TreeEvaluator.hpp
- runtime/compiler/env/VMJ9.cpp
- runtime/compiler/env/VMJ9Server.cpp
- runtime/compiler/p/codegen/J9TreeEvaluator.cpp
- runtime/compiler/x/codegen/J9TreeEvaluator.cpp
- runtime/compiler/z/codegen/J9TreeEvaluator.cpp
Allow inline allocation for value types
> Allow inline allocation for value types

- runtime/compiler/arm/codegen/ARMPrivateLinkage.cpp
- runtime/compiler/env/VMJ9.cpp
- runtime/compiler/ilgen/IlGenerator.cpp
- runtime/compiler/ilgen/Walker.cpp
- runtime/compiler/optimizer/InlinerTempForJ9.cpp
- runtime/compiler/z/codegen/S390PrivateLinkage.cpp
I think the conditional statements in the caller
methods of the classesOnHeap method are refactored
based on the return value of the classesOnHeap method
that is always true.
Closes: #11791
> Refactor classesOnHeap

- runtime/codert_vm/CodertVMHelpers.cpp
- runtime/codert_vm/cnathelp.cpp
- runtime/codert_vm/decomp.cpp
- runtime/codert_vm/jswalk.c
- runtime/compiler/runtime/MethodMetaData.c
- runtime/compiler/runtime/MethodMetaData.h
- runtime/compiler/runtime/SignalHandler.c
- runtime/oti/j9nonbuilder.h
- runtime/oti/j9protos.h
- runtime/rasdump/javadump.cpp
- runtime/vm/exceptiondescribe.c
Same as prior commit with 32-bit build break fix.
> Disable stackMap cache during ASGCT

- test/functional/Valhalla/playlist.xml
- test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeUnsafeTestClasses.java
- test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeUnsafeTests.java
- test/functional/Valhalla/testng.xml
Part of testing for #13614
Depends on #13924 being merged
> Add testing for isFlattened and IsFlattenedArray Unsafe methods

- runtime/gc_base/StringTable.cpp
j9gc_createJavaLangString() must use the Unicode length when checking if
a Unicode string is ASCII or Latin 1.
Bug introduced by https://github.com/eclipse-openj9/openj9/pull/11700 in
0.25 although there was a different but similar problem in previous
releases.
Fixes https://github.com/eclipse-openj9/openj9/issues/13655
> j9gc_createJavaLangString() must use Unicode length for Unicode strings

- runtime/gc_base/StringTable.cpp
j9gc_createJavaLangString() must use the Unicode length when checking if
a Unicode string is ASCII or Latin 1.
Bug introduced by https://github.com/eclipse-openj9/openj9/pull/11700 in
0.25 although there was a different but similar problem in previous
releases.
Issue https://github.com/eclipse-openj9/openj9/issues/13655
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/14041 for the 0.29.1 release.
> (0.29.1) j9gc_createJavaLangString() must use Unicode length for Unicode strings

- runtime/compiler/control/CompilationThread.cpp
When a compilation request is added to the compilation queue,
the JIT needs to scan the queue for a duplicate request and
coalesce the two requests into one if a duplicate exists.
In some corner cases the compilation queue can grow to thousand
of entries and scanning the queue for duplicates adds a lot of
overhead. This commit avoids scanning the queue based on the fact
that asynchronous queued entries always have
j9method->extra == J9_JIT_QUEUED_FOR_COMPILATION
This optimization can be disabled by defining the following env var:
TR_DisableSkipSearchingForRequestDuplicates = 1
Partially addresses issue #13807
> Avoid scanning the compilation queue for duplicates

- doc/release-notes/0.30/0.30.md
> Add release documentation for java option `-XX:[+|-]EnsureHashed`

- runtime/codert_vm/decomp.cpp
- runtime/codert_vm/j9codertvm.tdf
Add tracepoints to decompilation paths
> Add tracepoints to decompilation paths

- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/J9ObjectFieldOffsetIterator_V1.java
- runtime/gc_base/ObjectAccessBarrier.cpp
- runtime/vm/createramclass.cpp
- runtime/vm/resolvefield.cpp
Scan hidden fields for instance description bits
> Scan hidden fields for instance description bits

- buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy
- buildenv/jenkins/variables/defaults.yml
- Remove jdk16
- Update bootjdk17 url
Issue #14127
> Add jdk18 to pipelines

- test/TestConfig/resources/excludes/latest_exclude_19.txt
Copied from `latest_exclude_18.txt`.
fyi @llxia 
> Add latest_exclude_19.txt

- runtime/compiler/z/codegen/J9TreeEvaluator.cpp
Fixes https://github.com/eclipse-openj9/openj9/issues/13647
> Use correct add instruction in inlineStringLatin1Inflate

- runtime/compiler/z/codegen/J9TreeEvaluator.cpp
> (0.30.0) Use correct add instruction in inlineStringLatin1Inflate

- jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java
- runtime/vm/BytecodeInterpreter.hpp
> Implement valueHeaderSize and uninitializedDefaultValue Unsafe apis

- jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassStatistics.java
- runtime/jcl/common/shared.c
- runtime/jcl/exports.cmake
- runtime/jcl/j9jcl.tdf
- runtime/jcl/uma/se829_exports.xml
- runtime/oti/j9nonbuilder.h
- runtime/oti/jclprots.h
- runtime/rasdump/javadump.cpp
- runtime/shared_common/CacheLifecycleManager.cpp
- runtime/shared_common/OSCache.cpp
- runtime/shared_common/OSCache.hpp
- runtime/shared_common/OSCachemmap.cpp
- runtime/shared_common/OSCachesysv.cpp
- runtime/tests/shared/SharedCacheAPITest.cpp
Also cacheName(), cacheDir(). Add the nattach value (numberAttached) to
the javacore.
Issue https://github.com/eclipse-openj9/openj9/issues/12784
> Implement SharedClassStatistics.numberAttached(), cachePath(), etc.

- runtime/bcverify/staticverify.c
The change is to replace delayedErrorCode with errorCode when
throwing the VerifyError for the bad offset in stackmaps so as
to match the RI's behaviour.
Extension of https://github.com/eclipse-openj9/openj9/pull/14216
Internal ref 146697
> Replace delayedErrorCode with errorCode for the bad offset in stackmaps

- runtime/compiler/aarch64/codegen/ARM64JNILinkage.cpp
This commit adds support for macOS in ARM64JNILinkage.
The layout of arguments in the stack is different between AArch64 Linux
and macOS.
> AArch64: Add support for macOS in JNILinkage

- .github/ISSUE_TEMPLATE/test-suite-failure.md
- .github/workflows/autoTestPR.yml
- doc/compiler/jitserver/Testing.md
- doc/processes/labels.md
- test/README.md
- test/docs/OpenJ9TestUserGuide.md
- test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java
I didn't update the jenkins code, or the vendor used in the API for excluding tests.
> Update some instances of AdoptOpenJDK to Adoptium

- jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java
- runtime/vm/BytecodeInterpreter.hpp
- runtime/vm/ValueTypeHelpers.hpp
> Implement putValue and getValue Unsafe APIs

- runtime/compiler/x/codegen/J9TreeEvaluator.cpp
`srcBufferReg` and `destBufferReg` should be on the register
dependency list. The internal control flow should start right
after the register dependency setup, so that if any register
is spilled to stack before the internal control flow, they can
be restored properly at the end.
Fixes: #13983
> Fix the start of internal control flow and deps in inlining StringLatin1Inflate

- runtime/compiler/x/codegen/J9TreeEvaluator.cpp
In inlining StringLatin1Inflate, `srcBufferReg` and `destBufferReg`
should be added on the register dependency list. The internal
control flow should start right after the register dependency setup,
so that if any register is spilled to stack before the internal
control flow, they can be restored properly at the end.
Fixes: #13983
Port of https://github.com/eclipse-openj9/openj9/pull/14287 for the 0.30 release.
> (0.30.0) Fix the start of internal control flow and deps

- jcl/src/java.base/share/classes/java/lang/System.java
See JEP 400 https://openjdk.java.net/jeps/400
native.encoding should always be the platform encoding and is not
affected by values set on the command line. Even on jdk18+ it remains
the platform encoding while file.encoding defaults to UTF-8.
In jdk18+ the console charset/encoding needs to use the native.encoding
and not the default (UTF-8) charset.
> Fix native.encoding and properly initialize the console charset

- runtime/zlib/inflate.c
Cherry pick of https://github.com/eclipse-openj9/openj9/pull/14312 for the 0.30.0 release.
> (0.30.0) Resolve https://github.com/madler/zlib/issues/245 in zlib

- doc/release-notes/0.30/0.30.md
See
https://github.com/eclipse-openj9/openj9-docs/pull/866
https://github.com/eclipse-openj9/openj9/issues/14192
> Add missing release note and known problem

- buildenv/jenkins/common/variables-functions.groovy
- buildenv/jenkins/variables/defaults.yml
If OpenSSL is not present on machine, download
it to our expected location
Related #14208
> Auto-download OpenSSL on Windows

- doc/release-notes/0.30/0.30.md
See
https://github.com/eclipse-openj9/openj9-docs/pull/866
https://github.com/eclipse-openj9/openj9/issues/14192
> (0.30.0) Add missing release note and known problem

- runtime/compiler/runtime/Listener.cpp
- runtime/rasdump/javadump.cpp
The javadump time zone code is now redundant; the `omrstr_current_time_zone` function is used instead.
We now emit the time zone in the jitserver verbose log.
Blocked by: https://github.com/eclipse/omr/pull/6309
Fixes: https://github.com/eclipse-openj9/openj9/issues/13563
> Use omrstr_current_time_zone in javadump, emit time zone in the jitserver verbose log

- runtime/compiler/env/J9ClassEnv.cpp
- runtime/compiler/env/J9ClassEnv.hpp
- runtime/compiler/env/VMJ9.cpp
- runtime/compiler/env/VMJ9.h
> Remove unused frontend function isString(uintptr_t objectPointer)

- jcl/src/java.base/share/classes/java/lang/Access.java
* remove redundant preprocessor conditions
* trim trailing whitespace
(These changes were included in #14015.)
> Clean up Access.java

- doc/compiler/jitserver/ClientSession.md
> Update JITServer docs about actions needed when extending ClientSessionData

- runtime/j9vm/exports.cmake
- runtime/j9vm/j9vmnatives.xml
- runtime/j9vm/jvm.c
- runtime/redirector/forwarders.m4
- runtime/vm/jnimisc.cpp
This cherry-picks #13968 for the 0.30.0 release.
> (0.30.0) Change signatures in JDK17

- buildenv/jenkins/common/pipeline-functions.groovy
- set LIGHT_WEIGHT_CHECKOUT to false for release
- set GENERATE_JOBS to match with AUTOMATIC_GENERATION to generate child test jobs
Resolves: https://github.com/eclipse-openj9/openj9/issues/14289
Related: https://github.com/eclipse-openj9/openj9/issues/14318
> Set parameters for generating test jobs

- runtime/compiler/codegen/J9CodeGenerator.hpp
- runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
- runtime/compiler/env/VMJ9.cpp
- runtime/compiler/env/j9method.cpp
- runtime/compiler/optimizer/DataAccessAccelerator.cpp
- runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp
- runtime/compiler/z/codegen/J9CodeGenerator.cpp
- runtime/compiler/z/codegen/J9TreeEvaluator.cpp
- runtime/compiler/z/codegen/J9TreeEvaluator.hpp
- runtime/compiler/z/env/J9CPU.cpp
- test/functional/JIT_Test/src/jit/test/recognizedMethod/TestJavaIntegerAndLongToString.java
- test/functional/JIT_Test/testng.xml
This PR adds hardware exploitation to the JIT compiler in the z/codegen for zNext. The commits have been authored by @VermaSh @r30shah and myself.
> Add zNext hardware exploitation to JIT z/codegen

- buildenv/jenkins/common/pipeline-functions.groovy
- set LIGHT_WEIGHT_CHECKOUT to false for release
- set GENERATE_JOBS to match with AUTOMATIC_GENERATION to generate child test jobs
Resolves: https://github.com/eclipse-openj9/openj9/issues/14289
Related: #14318
cherry-pick: https://github.com/eclipse-openj9/openj9/pull/14345
> (v0.30.0-release) Set parameters for generating test jobs

- runtime/CMakeLists.txt
- runtime/cmake/caches/osx_aarch64.cmake
- runtime/codert_vm/cnathelp.cpp
- runtime/codert_vm/decomp.cpp
- runtime/compiler/aarch64/codegen/CallSnippet.cpp
- runtime/compiler/aarch64/runtime/PicBuilder.spp
- runtime/compiler/aarch64/runtime/Recomp.cpp
- runtime/compiler/control/CompilationThread.cpp
- runtime/compiler/env/J2IThunk.cpp
- runtime/compiler/runtime/ClassUnloadAssumption.cpp
- runtime/compiler/runtime/J9CodeCache.cpp
- runtime/compiler/runtime/RelocationRecord.cpp
- runtime/compiler/runtime/RelocationRuntime.cpp
- runtime/compiler/runtime/Trampoline.cpp
This commit adds calls to pthread_jit_write_protect_np() for AArch64 macOS.
> AArch64 macOS: Call pthread_jit_write_protect_np()

- jcl/src/java.base/share/classes/java/lang/StackWalker.java
- runtime/gc_base/RootScanner.cpp
- runtime/gc_glue_java/ConcurrentMarkingDelegate.cpp
- runtime/gc_glue_java/MarkingDelegate.cpp
- runtime/gc_glue_java/MetronomeDelegate.cpp
- runtime/gc_vlhgc/CopyForwardScheme.cpp
- runtime/gc_vlhgc/GlobalMarkCardScrubber.cpp
- runtime/gc_vlhgc/GlobalMarkingScheme.cpp
- runtime/gc_vlhgc/WriteOnceCompactor.cpp
Add bootloader unnamed module to root set
Also, modify stack walker to only look for module name if it is a named
module.
Related to: #14097
> Add bootloader unnamed module to root set

- buildenv/jenkins/common/pipeline-functions.groovy
Related: https://github.com/eclipse-openj9/openj9/pull/14345#discussion_r791800260
> Convert AUTOMATIC_GENERATION to boolean

- debugtools/DDR_VM/data/superset-constants.dat
- runtime/oti/j9nonbuilder.h
- runtime/vm/romclasses.c
Resolves https://github.com/eclipse-openj9/openj9/issues/14280
> Rename array shape constants

- jcl/src/java.base/share/classes/java/lang/ClassLoader.java
The macro is either contained in a method or a method is entirely contained
in the macro block.
> Reformat [IF JAVA_SPEC_VERSION >= 18] macros

- jcl/src/java.base/share/classes/java/lang/Class.java
For JEP416, a private adapter method which accepts an additional `Class<?>`
parameter is needed for the below methods:
- `Class.forName(String)`
- `Class.forName(String, boolean, ClassLoader)`
- `Class.forName(Module, String)`
Related: #13852.
Depends on https://github.com/eclipse-openj9/openj9/pull/14177.
> [JEP416] Add caller sensitive adapter methods in java.lang.Class

- runtime/compiler/optimizer/J9ValuePropagation.cpp
- runtime/compiler/optimizer/J9ValuePropagation.hpp
Transform flattened array element load and store in VP.
Depends on 
> Transform flattened array element load and store in VP

- jcl/src/java.base/share/classes/java/lang/Thread.java
Moved `started` check & `group.add(this)` out of the `try` block , and removed check of `started` for failed thread removal;;
Added imports;
Introduced `EMPTY_STACK_TRACE`;
Fixed space format;
Simplify method parameters.
This PR intended to start the discussion about the concerns raised at https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/387 via porting the refactoring done in that PR, and any change purposed can have better test coverages here.
Note: existing other thread code might use some refactoring as well, could be done in separated PRs. 
> Thread refactoring to match ibmruntime jdk extension repo PR #387

- jcl/src/java.base/share/classes/java/lang/Class.java
isValueType() is renamed to isPrimitiveValueType().
isValue() is added.
issue #13615
> Add stub VT method to unblock Valhalla builds

- doc/release-notes/0.30/0.30.md
> Balanced GC resizing

- test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeUnsafeTestClasses.java
- test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeUnsafeTests.java
part of testing for https://github.com/eclipse-openj9/openj9/issues/13614
resolves https://github.com/eclipse-openj9/openj9/issues/14117
> Add tests for getValue, putValue, and getObjectSize Unsafe apis

- runtime/j9vm/java11vmi.c
The buffer only needs to be large enough.
> Relax overly strict assertions

- test/functional/cmdLineTests/gcRegressionTests/gcRotatingVerboseLogTests.xml
- Update gcRotatingVerbose comments
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/14422
> Update gcRotatingVerbose comments

- runtime/compiler/aarch64/codegen/ARM64JNILinkage.cpp
- runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
Preserve vector registers across function calls.
It applies to both JNILinkage and PrivateLinkage.
Depends on https://github.com/eclipse/omr/pull/6327
Resolves https://github.com/eclipse-openj9/openj9/issues/14374
> AArch64: Preserve vector registers across calls

- doc/release-notes/0.31/0.31.md
> Add release documentation for `-XX:[+|-]ShowHiddenFrames`

- runtime/compiler/net/ClientStream.cpp
This change prevents a memory leak at the client in case of an invalid JITServer SSL certificate.
> Add missing BIO_free_all() call when SSL certificate verification fails

- runtime/compiler/control/CompilationThread.cpp
This commit implements the following changes:
1. Lines that had the `method ... will continue interpreted` information
will be printed under `verbose={compilePerformance}` too. Moreover, these
lines used to start with `+` sign which is used for successful compilations.
Such lines will now start with `#INFO` if the compilation was rejected by
compilation filters (e.g. `-Xjit:exclude={method}`), or with `#FAILURE`
if the compilation was attempted, but failed.
2. Lines with `JIT CACHES FULL` information will be printed under
`verbose={compilePerformance}` too. Moreover, such lines will change the
tag from `#INFO` to `#PERF` (because code caches being full has major
performance implications) and they will include a timestamp. These changes
make the lines with `JIT CACHES FULL Disable further …
> Small changes to vlog output for various failing conditions

- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/BCNames.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/PCStack.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/VrfyTbl.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/RomClassWalker.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ByteCodeDumper.java
- runtime/bcutil/ClassFileOracle.cpp
- runtime/bcutil/ClassFileOracle.hpp
- runtime/bcutil/ConstantPoolMap.hpp
- runtime/bcverify/rtverify.c
- runtime/bcverify/staticverify.c
- runtime/cfdumper/main.c
- runtime/codert_vm/decomp.cpp
- runtime/compiler/ilgen/J9ByteCode.hpp
- runtime/compiler/ilgen/J9ByteCodeIlGenerator.hpp
- runtime/compiler/ilgen/J9ByteCodeIterator.cpp
- runtime/compiler/ilgen/Walker.cpp
- runtime/oti/bcnames.h
- runtime/oti/cfr.h
- runtime/util/bcdump.c
- runtime/util/bcnames.c
- runtime/util/jbcmap.c
- runtime/util/pcstack.c
- runtime/util/romclasswalk.c
- runtime/util/sunbcrel.c
- runtime/util/vrfytbl.c
- runtime/vm/BytecodeInterpreter.hpp
- test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeGenerator.java
- test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java
> Rename bytecode defaultValue to aconst_init

- runtime/j9vm/jvm.c
Partially addresses https://github.com/eclipse-openj9/openj9/issues/947.
> Capture command line on AIX

- runtime/compiler/aarch64/codegen/ARM64JNILinkage.cpp
This commit changes the layout of JNI arguments that are passed in
the stack.  AArch64 macOS packs 8/16-bit integer arguments to 1/2-byte
boundaries of address space.
> AArch64 macOS: Handling 8/16-bit integer arguments for JNI

- runtime/compiler/p/runtime/PicBuilder.spp
Merged into master via #14527 and #14550, cherry-picked to this branch.
@pshipton
> (0.31.0) Fix Power iTable offset tag bits check

- runtime/gc_vlhgc/CopyForwardScheme.cpp
- runtime/gc_vlhgc/GlobalMarkCardScrubber.cpp
- runtime/gc_vlhgc/GlobalMarkingScheme.cpp
https://github.com/eclipse-openj9/openj9/pull/14577
Fix missing condition for scrubbing reference of unamedModuleObject
https://github.com/eclipse-openj9/openj9/pull/14471
Add missed rememberReferenceIfRequired call
> (0.31.0) Cherry-Pick to v0.31.0-release for PR14471/PR14577

- runtime/compiler/aarch64/codegen/ARM64JNILinkage.cpp
This commit changes the layout of JNI arguments that are passed in
the stack. AArch64 macOS packs 8/16-bit integer arguments to 1/2-byte
boundaries of address space.
Original PR in master: #14479
> (0.31.0) AArch64 macOS: Handling 8/16-bit integer arguments for JNI

- buildenv/jenkins/common/pipeline-functions.groovy
> Enable DYNAMIC_COMPILE=true for functional and external testing

- runtime/tests/jniarg/jniargtests.h
Avoid possible compile problems introduced in #14575.
> Use C-style comments

- runtime/j9vm/exports.cmake
- runtime/redirector/CMakeLists.txt
Fix typos, correct or remove useless comments.
> Minor cmake clean-up

- buildenv/jenkins/common/pipeline-functions.groovy
Fixes: https://github.com/eclipse-openj9/openj9/issues/14612
> Set DYNAMIC_COMPILE to false for valhalla

- runtime/compiler/codegen/J9CodeGenerator.hpp
- runtime/compiler/compile/J9SymbolReferenceTable.cpp
- runtime/compiler/compile/J9SymbolReferenceTable.hpp
- runtime/compiler/env/VMJ9.cpp
- runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp
- runtime/compiler/optimizer/J9RecognizedCallTransformer.hpp
- runtime/compiler/z/codegen/J9CodeGenerator.cpp
- runtime/compiler/z/codegen/J9TreeEvaluator.cpp
- runtime/compiler/z/codegen/J9TreeEvaluator.hpp
- test/functional/JIT_Test/playlist.xml
- test/functional/JIT_Test/src/jit/test/recognizedMethod/TestJavaLangStringCodingEncodeASCII.java
- test/functional/JIT_Test/testng.xml
> Inline StringCoding.encodeASCII on Z

- buildenv/jenkins/common/pipeline-functions.groovy
Related: infrastructure/issues/6547 and https://github.com/eclipse-openj9/openj9/issues/14016
> Add criu label for testing

- doc/release-notes/0.31/0.31.md
PR https://github.com/eclipse-openj9/openj9/pull/13925
> Add release note for new SharedClassStatistics API

- runtime/compiler/compile/J9Compilation.cpp
> Fix printing in printCompYieldStats

- runtime/compiler/codegen/J9CodeGenerator.hpp
- runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
- runtime/compiler/compile/J9SymbolReferenceTable.cpp
- runtime/compiler/compile/J9SymbolReferenceTable.hpp
- runtime/compiler/env/VMJ9.cpp
- runtime/compiler/env/j9method.cpp
- runtime/compiler/ilgen/Walker.cpp
- runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp
- runtime/compiler/optimizer/J9RecognizedCallTransformer.hpp
- runtime/compiler/z/codegen/J9CodeGenerator.cpp
- runtime/compiler/z/codegen/J9TreeEvaluator.cpp
- runtime/compiler/z/codegen/J9TreeEvaluator.hpp
- test/functional/JIT_Test/playlist.xml
- test/functional/JIT_Test/src/jit/test/recognizedMethod/TestJavaLangStringCodingEncodeASCII.java
- test/functional/JIT_Test/testng.xml
See https://github.com/eclipse-openj9/openj9/pull/13855/ and https://github.com/eclipse-openj9/openj9/pull/14671/ for original PRs
> (0.32.0) Inline StringCoding.encodeASCII and String.encodeASCII on Z

- runtime/j9vm/jvm.c
If unable to determine the command line or store it in the environment, try to remove any inherited definition.
> Remove inherited command line from environment

- runtime/codert_vm/xnathelp.m4
- runtime/jilgen/jilconsts.c
- runtime/oti/j9nonbuilder.h
- runtime/oti/xhelpers.m4
> Preserve ymm/zmm registers on x

- runtime/compiler/control/CompilationRuntime.hpp
- runtime/compiler/control/CompilationThread.cpp
> Add diagnostics to compInfoPT assertion

- buildenv/aix/jdk11/yum_install_aix-ppc64.txt
- buildenv/aix/jdk17/yum_install_aix-ppc64.txt
- buildenv/aix/jdk18/yum_install_aix-ppc64.txt
- buildenv/aix/jdk8/yum_install_aix-ppc64.txt
This is the version installed on the machines.
> Update freetype prereq on AIX to be 2.8-1

- runtime/oti/arm64helpers.m4
- runtime/oti/armhelpers.m4
- runtime/oti/phelpers.m4
- runtime/oti/riscvhelpers.m4
- runtime/oti/xhelpers.m4
- runtime/oti/zhelpers.m4
- runtime/vm/armcinterp.m4
- runtime/vm/pcinterp.m4
- runtime/vm/riscvcinterp.m4
- runtime/vm/wa64/stackswap.m4
- runtime/vm/wi32/stackswap.m4
- runtime/vm/xa64/stackswap.m4
- runtime/vm/xa64/unsafeHelper.m4
- runtime/vm/xcinterp.m4
- runtime/vm/xi32/stackswap.m4
- runtime/vm/xr64/unsafeHelper.m4
- runtime/vm/zcinterp.m4
* indent consistently (only with tabs)
* don't use tabs in other places
> Tidy up m4 assembler source

- runtime/compiler/optimizer/J9ValuePropagation.cpp
- runtime/compiler/optimizer/J9ValuePropagation.hpp
Reverts eclipse-openj9/openj9#14411
See https://github.com/eclipse-openj9/openj9/pull/14411#issuecomment-1068206584
> Revert "Improve IL for array load and store helpers for value types support"

- buildenv/jenkins/variables/defaults.yml
> Update to OpenSSL 1.1.1n

- buildenv/jenkins/variables/defaults.yml
Cherry-pick #14721 for the 0.32.0 release.
> (0.32.0) Update to OpenSSL 1.1.1n

- buildenv/jenkins/variables/defaults.yml
Cherry-pick #14721 for the 0.31.0 release.
> (0.31.0) Update to OpenSSL 1.1.1n

- runtime/gc_include/ObjectAccessBarrierAPI.hpp
#14700 will supercede this fix.
> Temporary compile fix for VT builds

- runtime/compiler/control/HookedByTheJit.cpp
- runtime/compiler/runtime/RelocationRuntime.cpp
- runtime/compiler/runtime/RelocationRuntime.hpp
> Print compressedPointersShift to the Vlog

- runtime/j9vm/java11vmi.c
- runtime/j9vm/jvm.c
It's either unset or always zero.
> Remove CALL_BUNDLED_FUNCTIONS_DIRECTLY

- runtime/j9vm/exports.cmake
- runtime/j9vm/j9vmnatives.xml
- runtime/j9vm/jvm.c
- runtime/redirector/forwarders.m4
Cherry-pick #14739 for the 0.32.0 release.
> (0.32.0) jdk11: adjust signature of JVM_LoadLibrary()

- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/FindStackValueCommand.java
Compare values found on stacks more carefully.
Fixes the 'U64 contains value larger than Long.MAX_VALUE' problem noted [here](https://github.com/eclipse-openj9/openj9/issues/13868#issuecomment-1072645486).
> Fix findstackvalue DDR command

- runtime/cmake/caches/linux_riscv64.cmake
- runtime/cmake/caches/linux_riscv64_cmprssptrs.cmake
- runtime/cmake/caches/linux_riscv64_mxdptrs.cmake
> CMake: Add riscv cache files

- runtime/cmake/caches/zos_390-64.cmake
- runtime/compiler/build/toolcfg/zos-xlc/common.mk
- runtime/makelib/targets.mk.zos.inc.ftl
Issue https://github.com/eclipse/omr/pull/6250#r820957190
> Tune z/OS compilation to 12 (z14)

- test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeUnsafeTestClasses.java
- test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeUnsafeTests.java
part of testing for https://github.com/eclipse-openj9/openj9/issues/13614
> Add tests for compareAndSetValue and related unsafe APIs

- jcl/src/java.base/share/classes/java/security/AccessController.java
When calling doPrivilegedWithCombiner with limited permissions, if the passed
AccessControlContext is null, get the current context and set it as parent.
For limited doPrivilegedWithCombiner frames, getAccSnapshot returns a
ProtectionDomain array on the first and a single object on subsequent frames.
Update code in getContextHelper to handle the different format.
Fixes https://github.com/eclipse-openj9/openj9/issues/14499
> Fix limited doPrivilegedWithCombiner calls

- buildenv/jenkins/variables/defaults.yml
> Run xlinux criu build on bare cent7

- jcl/src/java.base/share/classes/java/security/AccessController.java
When calling doPrivilegedWithCombiner with limited permissions, if the passed
AccessControlContext is null, get the current context and set it as parent.
For limited doPrivilegedWithCombiner frames, getAccSnapshot returns a
ProtectionDomain array on the first and a single object on subsequent frames.
Update code in getContextHelper to handle the different format.
Port of https://github.com/eclipse-openj9/openj9/pull/14606
fyi @pshipton
> (v0.31.0)Fix limited doPrivilegedWithCombiner calls

- runtime/jcl/common/mgmtthread.c
The uses were removed by #14767.
> Remove unused stack depth parameters

- doc/compiler/aot/Diagnostics.md
- doc/compiler/aot/README.md
- runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
* Fix printing of offsets in RTLog
* Add doc describing traces used for AOT debugging
> Add doc for AOT Debugging & fix bug in offset printing code

- runtime/gc_modron_startup/mmparse.cpp
- runtime/gc_trace_vlhgc/TgcInterRegionReferences.cpp
- runtime/gc_vlhgc/RememberedSetCardBucket.cpp
- runtime/shared_common/OSCachesysv.cpp
- runtime/vm/jnicsup.cpp
Fixes #14822
Signed-off-by: Kevin Grigorenko <kevin.grigorenko@us.ibm.com>
> Issue #14822: Fix variable set but not used compile errors

- longabout.html
- runtime/zlib/about.html
See https://github.com/eclipse-openj9/openj9/pull/14809
> Update document dates missed when updating to zlib 1.2.12

- runtime/libffi/LICENSE
- runtime/libffi/about.html
> (v0.31)Update the version and copyright date for libFFI

- runtime/libffi/LICENSE
- runtime/libffi/about.html
> (v0.32)Update the version and copyright date for libFFI

- runtime/codert_vm/jswalk.c
- runtime/oti/j9.h
- runtime/vm/ownedmonitors.c
- runtime/vm/swalk.c
> (v0.32.0) Add skip hidden frame logic to getOwnedObjectMonitorsIterator

- runtime/compiler/x/env/J9CPU.cpp
- runtime/vm/jvminit.c
> Enable AVX512 support

- runtime/compiler/runtime/MetricsServer.cpp
> Fix incorrect offset for null terminated string

- jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
- jcl/src/java.base/share/classes/java/lang/Thread.java
Refactoring `Thread` to simplify RI `java.lang.Thread` adoption.
> Move Thread.completeInitialization() into J9VMInternals

- buildenv/jenkins/common/pipeline-functions.groovy
> Remove criu spec suffix

- jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
- jcl/src/java.base/share/classes/java/lang/System.java
Fixes https://github.com/eclipse-openj9/openj9/issues/14872
> Throw UnsatisfiedLink from System.loadLibrary() when library has a path

- runtime/compiler/optimizer/J9ValuePropagation.cpp
- parameter 2 indicates return type of compare intrinsic
- parameter 0 indicates return type of blend intrinsic
> Propagate return types for compare and blend vector intrinsics

- runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
- runtime/compiler/arm/codegen/J9TreeEvaluator.cpp
- runtime/compiler/codegen/CodeGenGPU.cpp
- runtime/compiler/il/ILOpCodesEnum.hpp
- runtime/compiler/il/ILOps.hpp
- runtime/compiler/il/J9IL.cpp
- runtime/compiler/optimizer/IdiomRecognition.cpp
- runtime/compiler/optimizer/IdiomRecognition.hpp
- runtime/compiler/optimizer/SPMDParallelizer.cpp
- runtime/compiler/optimizer/SPMDPreCheck.cpp
- runtime/compiler/optimizer/SimplifierTable.hpp
- runtime/compiler/optimizer/VectorAPIExpansion.cpp
- runtime/compiler/optimizer/VectorAPIExpansion.hpp
- runtime/compiler/p/codegen/J9TreeEvaluator.cpp
- runtime/compiler/x/codegen/J9TreeEvaluator.cpp
- runtime/compiler/z/codegen/J9TreeEvaluator.cpp
- Handle new vector opcodes introduced by OMR
Depends on https://github.com/eclipse/omr/pull/6458
> Implement new vector opcodes

- runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp
> Fix unconditional JIT trace log updates from separateNullCheck

- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/ObjectModel.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/gc/GCMemoryPool.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/gc/GCObjectHeapIteratorAddressOrderedList_V1.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/gc/GCObjectHeapIteratorSegregated_V1.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/gc/GCObjectModel.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/gc/GCObjectModel_V1.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/walkers/HeapWalker.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/gccheck/CheckEngine.java
- debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/gccheck/CheckReporterTTY.java
Fixes #10537
Signed-off-by: Kevin Grigorenko <kevin.grigorenko@us.ibm.com>
> Don't return dark matter objects in DTFJ's JavaHeap.getObjects

- runtime/compiler/env/J9ClassEnv.cpp
- runtime/compiler/optimizer/J9ValuePropagation.cpp
- runtime/compiler/optimizer/J9ValuePropagation.hpp
If the two operands of acmp are value type and their class has:
(1) one field: transform acmp non helper call to field comparison
(2) multiple integral fields: transform acmp non helper call to arraycmp
> Inline comparison of VTs with either a single field or multiple integral fields in VP

- jcl/src/java.base/share/classes/module-info.java.extra
- runtime/jcl/CMakeLists.txt
Replace leading tab w/ spaces for qualified exports.
fyi @tajila 
> Include criu.cpp when J9VM_OPT_CRIU_SUPPORT is enabled
